### ISSUE TITLE
Chrome Refresh Issue

### ISSUE THREAD

**Issue by jonmchan** [keeweb/keeweb#1001]
This has very little to do with keeweb, but more of a bug to be aware for others using keeweb hosted on a web server.

When hosting keeweb on a static server such as nginx, when using Chrome, the main index page can get cached in such a way that no amount of hard resetting can clear the cache ( I tried opening developer tools, cmd+shift+R, clearing cache - nothing helped). 

This normally isn't an issue as the page would rarely need to be updated, but if you do something like change the config file meta field which I did and wonder why the change wasn't taking effect - the google chrome cache not resetting is the reason. 

It seems like this is caused because the inline javascript on the keeweb page? I'm not completely sure. Here's the Chrome bug report: 

https://bugs.chromium.org/p/chromium/issues/detail?id=44122

Feel free to just close this bug immediately, but I figure I put it up so that google search results may potentially pick it up for anyone having the issue.

**Comment by antelle** [comment]
Hi! This doesn't clear AppCache.
There are two things you can do to refresh the page:
1. change appcache.manifest file
2. clear the AppCache this way:
<img width="192" alt="cache" src="https://user-images.githubusercontent.com/633557/45924951-2705bb80-bf0c-11e8-8181-e80bcd0fff32.png">

**Comment by jonmchan** [comment]
Clearing storage from the `Application` tab did the trick! Amazing to note! Thanks for sharing that. Hopefully this answer will be useful for someone in the future when they try to google!
