### ISSUE TITLE
KDB file changes not merged from other sessions

### ISSUE THREAD

**Issue by raags** [keeweb/keeweb#1003]
- what were your actions?

If multiple keeweb sessions make changes to the same kdb file simultaneously, only the latest changes are saved. The kdb file is stored on Google Drive, and loaded as a local file on two computers.

The FAQ suggests that before save, changes are loaded and merged, but this is not happening for local file at lest.

If merging is not possible, a warning or a lock file that causes keeweb to go into read only mode would protect from overwriting changes.

- what was wrong?

Changes from multiple sessions when using local file (stored on google drive) are not merged.

- app version

`v1.6.3 (2017-12-11)`

- your user-agent (from Settings/Help section)

```
KeeWeb v1.6.3 (cded8a4, 2017-12-11)
Environment: electron v1.7.9
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) KeeWeb/1.6.3 Chrome/58.0.3029.110 Electron/1.7.9 Safari/537.36
```

- does it happen on Demo or New database?
New Database

**Comment by antelle** [comment]
Hi! 
Could you please describe what was changed in entries?
Maybe it's the way it's perceived, e.g. if you change a password one one computer and username on another, you will see either username, or password, not both. Only entries are merged, not details.

**Comment by raags** [comment]
New entry was added in the first session, and another was removed in the second. The new entry added was not visible when the second session was saved.

**Comment by antelle** [comment]
Interesting. Does it repeat? If so, please attach logs from both clients.
