### ISSUE TITLE
Autotype to Chrome stopped working in macOS Mojave

### ISSUE THREAD

**Issue by Raptor399** [keeweb/keeweb#1004]
- what were your actions?

I updated from macOS High Sierra to macOS Mojave. Logging in to a website using KeeWeb with ctrl-option-T (autotype) does pop up KeeWeb. After selecting the entry, the KeeWeb window hides itself, but nothing is entered in the login inputs on the page.

The first time I did this, two popups appeared, asking to grant KeeWeb access to certain apps (one of 'em was Chrome, forgot the other, sorry). I did grant access.

After the initial ask, it never returned.

I'm using Chrome and the latest version of KeeWeb and I'm doing the exact same thing as earlier when my computer was still macOS High Sierra.

Please investigate why autotype stopped working on macOS Mojave.

**Comment by antelle** [comment]
Hi! It's a known issue, see #953

**Comment by Raptor399** [comment]
Ah apologies, thanks!
