### ISSUE TITLE
[Feature Request] Add separator for password generator

### ISSUE THREAD

**Issue by Hugo1380** [keeweb/keeweb#1006]
Add the possibility to have separator in the password generator, example : 

XXXX-XXXX-XXXX-XXXX

Where "X" is a character of the password. So we can chose what separator we want (-._: ..etc), how many word and how many characters in each word. It can be useful for pronounceable password.

[Enpass](https://www.enpass.io/) already do that if you want to better understand.

**Comment by KaKi87** [comment]
What about regex pattern ?

**Comment by Hugo1380** [comment]
Can you give an example ?

**Comment by KaKi87** [comment]
[Interactive tutorial to regular expressions](https://regexone.com/)

If you want to generate a pass like `XXXX-XXXX-XXXX-XXXX` with only uppercase letters and digits, you could try : `^([A-Z0-9]{4}-){3}[A-Z0-9]{4}$`

```
6OL2-P01A-6OS6-YR8Q
EO4D-67MM-6C4J-VPZ1
X5O1-EEX0-OHNW-PRGV
94KM-PQQR-8B86-DFKF
CON2-FQ0A-79F0-ZJMU
U4XK-0E1V-IESR-FHS9
YWS7-BIKI-U050-CQV1
VL6O-Q9YU-G4IM-6DQT
L0HI-WB3P-EA5G-M6BV
XRGD-SMBV-34IR-C3B8
```

Or something more complex, with some symbols and both uppercase and lowercase letters : `^([A-Za-z!@#$%&*]{4}-){3}[A-Za-z!@#$%&*]{4}$`

```
XXXX-XXXX-XXXX-XXXX
WFtA-UKkK-lGqu-yEdP
xFXe-mefj-dSVb-oSd%
ntAV-vr#L-adSq-Jb%!
%dHK-RxpE-ZPVE-JcVz
fScp-zzwA-zDfl-IwbF
emKm-HIIj-Rg#X-ToPb
@j$p-ew#e-Tje*-vukt
RhrZ-GznL-IPpl-Zenb
yMlY-VpC!-Cbi*-Jj&j
DCfP-hvOW-#bm!-tXbL
```

Or if you want any character but hyphen : `^([^-]{4}-){3}[^-]{4}$`

```
0:!u-O1bG-l_o2-.89H
mU|+-m7gI-szs[-90B_
txfu-{*x_-&b(>-zybL
2.8s-(;=b-z7X.-]Wt!
[DzX-7]hs-A6y{-E8tq
.bm8-{{2q-T3<n-.;5q
dm8u-qsV7-USZr-h'^l
;3nk-S*s2-DMl%-!{\r
}[QK-K9Y;-LO3r-R;E7
TgiK-.,Bz-UOr8-s~>D
```

You can use [Regex101](https://regex101.com/) to test your regular expressions and a website like [this one](https://www.browserling.com/tools/text-from-regex) to generate text from your regular expressions.

**Comment by antelle** [comment]
Adding a regex makes more sense and covers more cases than separators, I agree.

**Comment by antelle** [comment]
So, regex won't be implemented here because:
1. it will ignore all other settings
2. there's no way to generate a string based on a regex, unless we include a huge library for that

**Comment by KaKi87** [comment]
It should at least allow to choose uppercase and/or lowercase letters and/or digits.

**Comment by antelle** [comment]
Yes, something like `a` – lowercase letters, `A` - uppercase letters, `0` - digits, `X` - everything else, other symbols – will remain as is.

**Comment by KaKi87** [comment]
Hey there, any news on this ? Thanks

**Comment by KaKi87** [comment]
Any news on this ?

**Comment by antelle** [comment]
Deployed to [beta.keeweb.info](https://beta.keeweb.info), will be available in the next release.
<img width="661" alt="Screen Shot 2020-03-15 at 11 20 40" src="https://user-images.githubusercontent.com/633557/76699580-11abc080-66af-11ea-8aaf-98ea952944c5.png">
