### ISSUE TITLE
Can't get .json config file to load with kw-config option

### ISSUE THREAD

**Issue by tetsuo29** [keeweb/keeweb#1007]
- Tried the directions for using a .json file as described here:
https://github.com/keeweb/keeweb/wiki/Dropbox-and-GDrive

- Verified that the URL to my JSON file works:
https://passwords.svuus.org/kwconfig.json

- No matter how I specify the URL in the kw-config option in indext.html, when I open the console and run kw.settings.get(); my gdriveClientId was not getting set.
I've tried the following in the 'content="(no-config)"'
content="kwconfig.json"
content="./kwconfig.json"
content="(kwconfig.json)"
content="(./kwconfig.json)"
content="https://passwords.svuus.org/kwconfig.json"
content="passwords.svuusorg/kwconfig.json"
content="(https://passwords.svuus.org/kwconfig.json)"
content="(passwords.svuusorg/kwconfig.json)"
content="http://passwords.svuus.org/kwconfig.json"
content="(http://passwords.svuus.org/kwconfig.json)"
content="https%3A%2F%2Fpasswords.svuus.org%2Fkwconfig.json"

- I believe my .json file is good because I had success with the URL parameter form:
https://passwords.svuus.org/?config=kwconfig.json
(Also had to adjust the URI redirect setting in my Google Credentials for this web app).

- Finally resorted to modifying the gdriveClientId setting already in index.html because I am trying to avoid the URL parameter form.

- app version = v1.6.3
- I tried this on Safari (Mac), Chrome (Mac), Chrome (Windows), Firefox (Mac), Firefox (Linux), Safari (iOS), & Chrome (iOS) all with the same results until I just changed the gdriveClientId setting in index.html

What am I doing wrong that I can't get the '<meta name="kw-config" content="my_json_config_URL">' option to load my .json file?

**Comment by tetsuo29** [comment]
So, I stumbled upon a solution that works. I discovered that if I name my JSON file "config.json" then  I can set:
     <meta name="kw-config" content="config.json">

and things work as described at:
     https://github.com/keeweb/keeweb/wiki/Configuration#json-app-config

I wish the directions on that page had specified that the file *HAS* to be named "config.json" and also that using the URL parameter hadn't worked when my file was named "kwconfig.json". Clearer instructions or consistency in naming requirements would have saved me hours in frustrating trial and error.

Don't misunderstand. I think what you're doing here is great and I will definitely making a donation. I just hope that you will make the directions clearer or make the program more flexible about naming the .json file when using the kw-config meta tag option. (Or, explain what I was doing wrong when my file was named "kwconfig.json"- I'm still open to that possibility because I have discovered that I have to clear my browser cache in order to actually see changes made to my index.html take place. So, who knows, maybe one of the above examples of the 'content=' settings would have worked if I'd been clearing my browser cache each time.)

**Comment by antelle** [comment]
Hi!
It shouldn't be like this. Could you please provide error logs when you set it to kwconfig.json?

**Comment by tetsuo29** [comment]
So, I'm really thinking it was because when I tried:
config="kwconfig.json"

... I needed to clear my browser caches. Because I renamed it and it is working now.

**Comment by antelle** [comment]
Yes, otherwise it doesn't know about the config.  
I've added a note to the configuration wiki page, hopefully it will help in future.
