### ISSUE TITLE
Bug: Find as you type: Missing keystrokes

### ISSUE THREAD

**Issue by GitHubGeek** [keeweb/keeweb#1011]
- what were your actions? _Search for items by typing in All Items > Search box_
- what was wrong? _When typing fast, 1-2 characters keystrokes are missed_
- app version: `KeeWeb v1.6.3 (cded8a4, 2017-12-11)`
- your user-agent: `User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:63.0) Gecko/20100101 Firefox/63.0`
- does it happen on Demo or New database? _Database with dozens of items_
- please, open dev tools in your browser and attach output log from Console tab: _No messages in console_

I suspect the _find as you type_ filtering is implemented as a synchronous, blocking operation which caused the missing keystrokes. This happen on a fairly performant machine (Core i7-8550U).

**Comment by antelle** [comment]
Hi! I've never noticed it. Is there anything special with the file, for example, does it repeat on demo db?

**Comment by GitHubGeek** [comment]
I couldn't replicate it with the demo db. On my personal db, there're 150+ items. I can consistently replicate it by typing the word "admin":

1. Type A, 140+ items in the list
2. Type D, down to 37 items
3. Type M, down to 21 items
4. I, N, 21 items

Most often, the character M would be missed

**Comment by antelle** [comment]
Does it repeat in browsers?

**Comment by GitHubGeek** [comment]
Got access to a low-end Chromebook and tested the typing issue - Couldn't replicate. Seems to be Firefox specific?

Next I should find a plain vanilla Firefox install and test

**Comment by antelle** [comment]
I haven't noticed this in any browser, not sure how this is possible. Probably it's specific to firefox + your linux distro version, which is skipping events.
