### ISSUE TITLE
webdav auto-capitalization causes HTTP 400 error

### ISSUE THREAD

**Issue by diachedelic** [keeweb/keeweb#1014]
Using `https://keeweb.info` on iOS and Android, to open a webdav file, the first character of the `path` field is automatically capitalized, so it reads something like `Https://dav.server.com/file.kdbx`.  While this works to initially open the file, KeeWeb fails to sync after that, complaining of a 400 error.  Inspecting my nginx logs, I find this error:

```
2018/10/09 12:38:25 [error] 17224#17224: *300790 client sent invalid "Destination" header: "Https://dav.server.com/file.kdbx", client: 137.59.252.195, server: dav.server.com, request: "MOVE /.file.kdbx.1539088702822 HTTP/2.0", host: "dav.server.com", referrer: "https://passwords.server.com/"
```

Or more concisely,
```
client sent invalid "Destination" header: "Https://dav.server.com/file.kdbx"
```

Recreating the file in KeeWeb with correct casing fixes the issue, however any local modifications are lost.

**Comment by antelle** [comment]
Hi! Do you mean the webdav field is auto-capitalizing the first character, or it happens somewhere inside?

**Comment by diachedelic** [comment]
Yes the webdav path field is auto-capitalizing the first char

**Comment by dploeger** [comment]
@antelle Hm. This issue should be closed because you fixed it in 4a070bb, right?

**Comment by antelle** [comment]
It will be closed automatically when the new release is merged: https://github.com/keeweb/keeweb/wiki/FAQ#features

**Comment by dploeger** [comment]
Okay, but this makes it hard to see, when 1.7 is ready to be merged...

**Comment by antelle** [comment]
@dploeger you can see the list of open issues for 1.7 here: https://github.com/keeweb/keeweb/issues?q=is%3Aopen+is%3Aissue+milestone%3Av1.7+no%3Aassignee
