### ISSUE TITLE
FR: (Autotype) Support only pasting username or password

### ISSUE THREAD

**Issue by dploeger** [keeweb/keeweb#1017]
Autotype currently supports only a default sequence or specific sequences by entry. For some situations (like services that use separated username and password fields in two steps) it would be great to use the great autotype filter window to not do the sequence but instead only paste the password or the username separately.

**Comment by antelle** [comment]
Thanks! 🎁 
I think it makes sense, added a comment about implementation there.

**Comment by dploeger** [comment]
Closed by #1018 
@antelle Any idea when 1.7 will be released?

**Comment by antelle** [comment]
No idea for now, I hope it will be there soon
