### ISSUE TITLE
webdav config.json ignored

### ISSUE THREAD

**Issue by davidgiga1993** [keeweb/keeweb#1019]
I've just installed keeweb on a selfhosted instance. Access to the kdbx is working fine but the `files` part of the `config.json` is ignored (everything else is working file).

Here is my config
```
{
    "settings": {
        "canOpenDemo": false,
        "canImportXml": false,
        "canCreate": false,
        "dropbox": false,
        "gdrive": false,
        "onedrive": false,

        "showOnlyFilesFromConfig": true,
        "files": [{
            "storage": "webdav",
            "name": "IT",
            "path": "db/it.kdbx",
            "options": { "user": "", "password": "" }
        }]
    }
}
```

any idea why the file is now shown as default?

![image](https://user-images.githubusercontent.com/3924958/46919077-f203fa80-cfd9-11e8-82b5-bf0a734bde72.png)

I've expected the following:
![image](https://user-images.githubusercontent.com/3924958/46919081-fdefbc80-cfd9-11e8-8379-0a9449cfeb1e.png)

**Comment by antelle** [comment]
Hi! It must be outside settings section, in the root
