### ISSUE TITLE
About keeweb-gh-pages

### ISSUE THREAD

**Issue by Razin79** [keeweb/keeweb#1023]
Hi, 

Not really an issue with the app, but with the functionning of [ Keeweb ](https://github.com/keeweb/keeweb/tree/gh-pages) => i canno't read into the index file, due to his size.

Anyway, the app says "the file is stored in the internal app storage" but where ? I'd like to understand.

Thank you in advance.

**Comment by antelle** [comment]
Hi!
In apps, it's app directory: AppData on Windows or Application Support on mac.
In browser, it's internal browser storage, IndexedDB in particular.

**Comment by Razin79** [comment]
Thank you very much for your aid, antelle !  

Is it possible to set into the "**index.html**", the loading of a **.kdbx** file at the opening ?

Because when all parameters in the browser are cleared, parameters in the IndexedDB also, and i have to reopen the **.kdbx** file.

**Comment by antelle** [comment]
I don’t quite understand the case. Where do you host index.html and the kdbx? It remembers last files, does it open with an empty list for you?

**Comment by Razin79** [comment]
The idea is that if I place the html file on an X machine, and open this index.html file (with Firefox or Chrome) from a Y or Z machine I will always have this default **test.kdbx** file.

Thus, even if the parameters of the browsers are cleared (precisely folder IndedexDb), i will always have the **test.kdbx** file at startup.

So I was wondering if it was possible to set up in this file index.html ? 

[Example in illustration](https://ibb.co/kZ0J5f) 

I hope I've made it clearer.

**Comment by antelle** [comment]
It's not possible with files saved in the internal storage, for this you will need several things:

1. Choose a cloud storage. You can use Dropbox, Google Drive, or WebDAV on your server (requires more configuration)
2. Host keeweb somewhere on your server
3. Create a [config](https://github.com/keeweb/keeweb/wiki/Configuration#json-app-config) and add your file there

**Comment by Razin79** [comment]
Ok, thank you for your follow-up and patience.

:-)
