### ISSUE TITLE
Keyboard menu navigation.

### ISSUE THREAD

**Issue by BorisB** [keeweb/keeweb#1024]
I made navigation on menu with Cmd+Up and Cmd+Down. It works on both Settings and Main menu.
If this feature is demanded I can make pull request.

**Comment by antelle** [comment]
Hi! I would expect it to navigate it this way:

- as it is now on setting, to the beginning of the page
- to the beginning of the entry list outside settings

**Comment by BorisB** [comment]
Maybe Cmd+Alt+Up/Down?

**Comment by antelle** [comment]
You mean for the menu? Maybe, cmd+alt+arrow is not used for other things. For scrolling, cmd+arrrow works this way in most of apps (scroll to top/bottom).

**Comment by BorisB** [comment]
Done. Sorry for stupid question, I'm new here, but how can I share my code? Pushing new branch gives me 'permission denied'.
