### ISSUE TITLE
nextcloud + keeweb

### ISSUE THREAD

**Issue by edzoe** [keeweb/keeweb#1027]
Hello,

I'm running NC 14.0,3 with keeweb 1.5.0 :-)

If I work with the admin account from NC, all is good, the keeweb works well and recognizes the .kdbx. If I switch to a different account, cant open anymore the keepass databases. Any idea where is the problem?

Thank you in advance.

KeeWeb v1.5.0 (4c4a308, 2017-05-22)
Environment: web
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:62.0) Gecko/20100101 Firefox/62.0

**Comment by antelle** [comment]
Hi! This is probably a question for nextcloud-keeweb project: https://github.com/jhass/nextcloud-keeweb
