### ISSUE TITLE
Autotype fails on Mac v. 1.6.3, Chrome 70

### ISSUE THREAD

**Issue by AugustNagro** [keeweb/keeweb#1028]
Recently updated Chrome & Keeweb to the latest versions, which unfortunately broke Autotype functionality.

Typing the combo (^⌥T) pops the locked application to the foreground, and after unlocking focus changes to Chrome. However, the username/password is not entered, nor is the form submitted.

The console logs show no error (`2018-10-25T23:17:19.333Z [auto-type] Complete 212ms`) despite not functioning on any website I've thus tried. 

Version info:

KeeWeb v1.6.3 (cded8a4, 2017-12-11)
Environment: electron v1.7.9
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_0) AppleWebKit/537.36 (KHTML, like Gecko) KeeWeb/1.6.3 Chrome/58.0.3029.110 Electron/1.7.9 Safari/537.36

**Comment by antelle** [comment]
Hi! It looks like you need to re-enable keeweb in Accessibility section of system settings.

**Comment by antelle** [comment]
see #1004
