### ISSUE TITLE
Sync files by timeout or listen to file changes on storages

### ISSUE THREAD

**Issue by sbollini** [keeweb/keeweb#1029]
Hi! We are a group of technicians sharing a keepas file in a shared google drive folder, with keeweb v1.6.3 for windows.
We realized that when one of us introduces some change in the file, and then synchronizes the file, the rest of us don't receive the change until we close the file and open it again.
I read https://github.com/keeweb/keeweb/wiki/FAQ but we're not sure if this is the intended behavior. Is it, or is there some malfunction?

KeeWeb v1.6.3 (cded8a4, 2017-12-11)
Environment: electron v1.7.9
User-Agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) KeeWeb/1.6.3 Chrome/58.0.3029.110 Electron/1.7.9 Safari/537.36

Kind regards

**Comment by antelle** [comment]
Hi! There's no real-time sync, it's updated when you change something. Next version will also sync changes every 30min.

**Comment by antelle** [comment]
Right, but there's a workaround: if you open a file from your file system and let google drive sync it, keeweb will pick it up and reload the file when it's updated by google drive app.

**Comment by sbollini** [comment]
We don't use google drive sync, but google file stream. Could it work with it?

**Comment by antelle** [comment]
I haven't used any of them, but if it updates files in the filesystem, yes.

**Comment by sbollini** [comment]
No, the mechanism is quite different. It has a sort of cache of small file pieces representing the changes made to the original file. No, I guess the answer is "no".
Can we expect to have this automatic sync you mentioned, any time soon? :-)

**Comment by antelle** [comment]
Probably no, but you can try. I don't know, it was never asked yet, it should be quite easy to do, if it's not realtime.

**Comment by antelle** [comment]
When you save the file, data inside it is merged, not overwritten. So, if user1 syncs the file, then user3 gets this copy, no matter what happened between, user3's copy will have changed version of key1. If user1 doesn't save the file, user3 will indeed get previous version of key1. But once sync happens, it will be updated, again, no matter when user2 saves it.
The [data type](https://en.wikipedia.org/wiki/Conflict-free_replicated_data_type) used in keeweb guarantees eventual consistency, which means that *eventually* data will be in same state on all copies.

**Comment by sbollini** [comment]
You say
> When you save the file, data inside it is merged, not overwritten. 
This is done by keeweb, not by google drive, correct?

**Comment by antelle** [comment]
correct

**Comment by sbollini** [comment]
Ok, great!
So, we look forward to get this new version with automatic sync support :-)
Thanks a lot

**Comment by antelle** [comment]
automatic sync won’t happen on file updates though, but it’s also possible to implement, it you would like to contribute, I can show where it can be done

**Comment by sbollini** [comment]
On Mon, Oct 29, 2018 at 8:06 AM antelle <notifications@github.com> wrote:

> automatic sync won’t happen on file updates though,
>
Sorry, I didn't understand that...

but it’s also possible to implement, it you would like to contribute, I can
> show where it can be done
>
Thank you for the invite, but I'm not a developer, just a humble user :-)

Regards!

**Comment by return42** [comment]
> it’s also possible to implement, it you would like to contribute, I can show where it can be done

@antelle where would you start .. I can't promise you any contribution, but I want to take a look on. Hence a small hint might be enough for the first. / Thanks

**Comment by antelle** [comment]
@return42 most likely here: https://github.com/keeweb/keeweb/blob/master/app/scripts/models/app-model.js#L649
We launch sync on external file changes, but for some reason something is not going as expected, this needs more debugging there.
