### ISSUE TITLE
There was an error loading app settings

### ISSUE THREAD

**Issue by kostya-wnot** [keeweb/keeweb#1030]
Hi there!
We have installed own instance on our server - https://alfred.uiux.ru
We created own config file - https://alfred.uiux.ru/alfred_config.json
When we change the value of meta-tag "content" from "(none)" to "https://alfred.uiux.ru/?config=alfred_config.json" we see "Error loading app with own server" page (There was an error loading app settings. Please double check the app URL or contact your administrator.).

Please give us a hand, what are we doing wrong?

**Comment by antelle** [comment]
Hi! Could you please check Console and Network tab in devtools? There should be an error printed there.

**Comment by kostya-wnot** [comment]
Hi Antelle!
Thank you for your reply. Screenshot below.
<img width="1440" alt="scr_keeweb_console" src="https://user-images.githubusercontent.com/17786036/47719806-51f6d400-dc5d-11e8-9999-e5c7614953d9.png">

**Comment by antelle** [comment]
The contents of kw-config must be `alfred_config.json`, not `https://alfred.uiux.ru/?config=alfred_config.json`

**Comment by kostya-wnot** [comment]
Yeeeeeees!
It's working!
Thank you very match=)

One more a little question: Can we disable More button and show instead GD button?

**Comment by antelle** [comment]
"More..." button will be hidden if there's nothing inside. E.g. you can disable Dropbox, WebDAV, and everything else. You can do it with config options: https://github.com/keeweb/keeweb/wiki/Configuration#json-app-config

canOpenDemo, canImportXml, etc...
