### ISSUE TITLE
Rendering errors around fonts

### ISSUE THREAD

**Issue by ipimpat** [keeweb/keeweb#1031]
I have some issues with font rendering, there is weird pixel around the fonts.

I also have the same issue on another computer also, both computers are running Linux Mint 19

The errors are seen all over the application.

I've added a screenshot where I marked the weird pixels, you might have to zoom the image.

```
$ cat /etc/lsb-release
DISTRIB_ID=LinuxMint
DISTRIB_RELEASE=19
DISTRIB_CODENAME=tara
DISTRIB_DESCRIPTION="Linux Mint 19 Tara"
```

Application information:
```
KeeWeb v1.6.3 (cded8a4, 2017-12-11)
Environment: electron v1.7.9
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) KeeWeb/1.6.3 Chrome/58.0.3029.110 Electron/1.7.9 Safari/537.36
```

![screenshot](https://i.imgur.com/XjiyA0p.png)

**Comment by antelle** [comment]
Duplicates #900
