### ISSUE TITLE
ios safari + firefox: webdav: network error

### ISSUE THREAD

**Issue by lowrider2025** [keeweb/keeweb#1033]
- what were your actions? open keepass file
- what was wrong? error: network error
- app version: web app (app.keeweb.info)
- your user-agent: safari + firefox(14.0 (12646)) ios
- does it happen on Demo or New database? open existing database (more button)
- if you are using a test db without your personal data, please attach it
- please, open dev tools in your browser and attach output log from Console tab 
    (if you are using desktop app, devtools can be opened from Settings/General/Advanced)
how can I do this in iOS ?

Tried to access the keepass db through webdav on firefox in windows. Does not work either. The db is located on personal onedrive. I can access it through keepass and webdav.

**Comment by antelle** [comment]
Hi! Which error is there in Network tab? Maybe you don't have cors enabled?

**Comment by Coises** [comment]
@lowrider2025 : Just a thought... you mention WebDAV and "personal onedrive." Are you in fact attempting to access OneDrive, but using the WebDAV storage type rather than the OneDrive storage type? If so... does it work if you use the OneDrive storage type?

Accessing from a desktop application (like KeePass) is different from accessing through a web application, so it is possible that WebDAV/OneDrive could work in KeePass but not in KeeWeb if OneDrive doesn't support CORS through WebDAV.

**Comment by lowrider2025** [comment]
@antelle:

this is the content from 401 error:
Registraties aanhouden
Buffer uitschakelen
401
OPTIONS
xxxx.kdbx
xxxxxxxxxx
xhr
plain
537 B
0 B
→ 261 ms
Eén aanvraag
0 B / 537 B overgebracht
Voltooien: 261 ms
Aanvraag-URL:
Aanvraagmethode:
Extern adres:
Statuscode:
401
Versie:
	
Antwoordheaders (537 B)	
Content-Length	
16
Content-Type	
text/plain; charset=utf-8
Date	
Thu, 08 Nov 2018 18:33:42 GMT
MicrosoftSharePointTeamServices	
16.0.0.4639
request-id	
6c6ca09e-8bba-d045-f81a-829130fc8e3e
Server	
Microsoft-IIS/10.0
SPIisLatency	
1
SPRequestDuration	
3
SPRequestGuid	
6c6ca09e-8bba-d045-f81a-829130fc8e3e
Vary	
Accept-Encoding
WWW-Authenticate	
NTLM
WWW-Authenticate	
Basic realm="xxxxxxx"
X-Content-Type-Options	
nosniff
X-FRAME-OPTIONS	
SAMEORIGIN
X-MS-InvokeApp	
1; RequireReadOnly
X-Powered-By	
ASP.NET
Aanvraagheaders (483 B)	
Accept	
text/html,application/xhtml+xm…plication/xml;q=0.9,*/*;q=0.8
Accept-Encoding	
gzip, deflate, br
Accept-Language	
nl,en-US;q=0.7,en;q=0.3
Access-Control-Request-Headers	
authorization,cache-control
Access-Control-Request-Method	
HEAD
Connection	
keep-alive
DNT	
1
Host	
xxxxxxxxxxx
Origin	
https://app.keeweb.info
User-Agent	
Mozilla/5.0 (Windows NT 10.0; …) Gecko/20100101 Firefox/56.0

**Comment by antelle** [comment]
Options must return 200, otherwise we can't open it.

**Comment by lowrider2025** [comment]
request headers:
Host: 
User-Agent: Mozilla/5.0 (Windows NT 10.0; WOW64; rv:56.0) Gecko/20100101 Firefox/56.0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Language: nl,en-US;q=0.7,en;q=0.3
Accept-Encoding: gzip, deflate, br
Access-Control-Request-Method: HEAD
Access-Control-Request-Headers: authorization,cache-control
Origin: https://app.keeweb.info
Connection: keep-alive
DNT: 1

reply headers:
HTTP/1.1 401 Unauthorized
Content-Type: text/plain; charset=utf-8
Server: Microsoft-IIS/10.0
SPRequestGuid: c271a09e-5b8e-d045-ef6b-ffdda4751d4f
request-id: c271a09e-5b8e-d045-ef6b-ffdda4751d4f
X-FRAME-OPTIONS: SAMEORIGIN
SPRequestDuration: 3
SPIisLatency: 0
WWW-Authenticate: NTLM
X-Powered-By: ASP.NET
MicrosoftSharePointTeamServices: 16.0.0.4639
X-Content-Type-Options: nosniff
X-MS-InvokeApp: 1; RequireReadOnly
WWW-Authenticate: Basic realm=
Date: Thu, 08 Nov 2018 20:06:56 GMT
Content-Length: 16
Vary: Accept-Encoding

**Comment by antelle** [comment]
well, the server says “not authorized”.

**Comment by lowrider2025** [comment]
No way to make this work ? No other methods ? Webdav  with onedrive works with keepass desktop on windows and keepass2android on android but no methods on ios ?

**Comment by lowrider2025** [comment]
But thanks for trying to help. Too bad it won't work.

**Comment by antelle** [comment]
Only make the server not return 401

**Comment by Coises** [comment]
@lowrider2025 Have you tried selecting OneDrive instead of WebDAV to open the database in KeeWeb?

**Comment by lowrider2025** [comment]
@coises yes, tried that too.did not work either. thanks for the help.

**Comment by antelle** [comment]
@lowrider2025 this means that you can't use this server with keeweb.

**Comment by KaKi87** [comment]
Hello, I experienced the same problem with self-hosted WebDAV.
KeeWeb on Chrome for Windows and Android, KeePass on Windows and KeePass2Android work, but KeeWeb on Firefox for Windows doesn't.
Thanks

**Comment by blahblubber** [comment]
It works for me with Safari on iPad OS and Firefox on Windows on a self-hosted WebDAV when the KeeWeb "installation" (index.html and other files) is on the same WebDAV server. You have to enter the WebDav user/password twice, once to access the KeeWeb "installation" (index.html) and another time when you want to open the Keepass DB via WebDAV.
