### ISSUE TITLE
[Feature Request] Clear Cache

### ISSUE THREAD

**Issue by Shoggomo** [keeweb/keeweb#1034]
It'd be helpful if critical error messages had a option to clear the apps cache.
Even though this is simple to do in the browser (on mobile not so much) it may not come to mind immediately.

I, specifically, had a problem preventing me from logging in to my db due to corrupted cache (which can happen fairly easy).

**Comment by antelle** [comment]
Hi! To clear cache, you can remove the db and add it again.
