### ISSUE TITLE
Feature Request: Add icon management to delete old icons

### ISSUE THREAD

**Issue by titleofliberty** [keeweb/keeweb#1044]
Please consider adding a way to manage the custom icons. I have several I don't need anymore and would like to delete.

**Comment by antelle** [comment]
Hi! They will be deleted automatically if there are no entries using them. We have another issue about allowing to keep icons without references, but it's not implemented yet.

**Comment by kostya-fr** [comment]
The feature seems not working. 
On Windows app I add the same icon twice and it keep them both. I can't find any way to delete the first one.
