### ISSUE TITLE
Web version db load/backup options.

### ISSUE THREAD

**Issue by Azbests** [keeweb/keeweb#1045]
It would be nice to have an option to load db each time from specific dir or be able to turn on backup option to it for local dir. 

These options kinda seems missing in web version. And in cases when browser history/cache needs to be cleaned without such option it's a way for user to lose db as it sits in browsers userdata dir.

As this is already in app version, possibly this is some kind of limitation of web app variation of keeweb?

**Comment by antelle** [comment]
Hi! It's not possible to write files in web version, but you can backup to Dropbox.
