### ISSUE TITLE
Cookies not saved by desktop app.

### ISSUE THREAD

**Issue by amadrzyk** [keeweb/keeweb#1046]
Hello! I'm currently using the Mac desktop app v1.6.3, and I'm unable to sync my key file from Google Drive.

Here's what I get when trying to log into Google:
<img width="694" alt="screen shot 2018-12-11 at 10 51 59 pm" src="https://user-images.githubusercontent.com/20073334/49846238-50f6ad80-fd98-11e8-87f3-dd9f1cb295ff.png">

I don't have this issue when using the online version of the app.

**Comment by antelle** [comment]
Duplicates #810

**Comment by SwiftArchitect** [comment]
> see https://github.com/keeweb/keeweb/issues/810#issuecomment-356238959

`rm ~/Library/Application\ Support/KeeWeb/runtime-data.json`
