### ISSUE TITLE
Can't open Dropbox file on Firefox

### ISSUE THREAD

**Issue by MrP** [keeweb/keeweb#1049]
Entering the password to the file, I get the following error in the UI:

There was an error opening file

[object Event]

And this is what I see in the console: 

```
2018-12-16T19:11:16.021Z [storage-cache] Error opening indexed db 
error { target: IDBOpenDBRequest, isTrusted: true, srcElement: IDBOpenDBRequest, currentTarget: IDBOpenDBRequest, eventPhase: 2, bubbles: true, cancelable: true, returnValue: true, defaultPrevented: false, composed: false, … }
app.keeweb.info:1:1212
2018-12-16T19:11:16.022Z [open:SimpleKeeWeb] Loaded file from cache 
error { target: IDBOpenDBRequest, isTrusted: true, srcElement: IDBOpenDBRequest, currentTarget: IDBOpenDBRequest, eventPhase: 2, bubbles: true, cancelable: true, returnValue: true, defaultPrevented: false, composed: false, … }
app.keeweb.info:1:889
2018-12-16T19:11:16.023Z [open-view] Error opening file 
error { target: IDBOpenDBRequest, isTrusted: true, srcElement: IDBOpenDBRequest, currentTarget: IDBOpenDBRequest, eventPhase: 2, bubbles: true, cancelable: true, returnValue: true, defaultPrevented: false, composed: false, … }
app.keeweb.info:1:1212 
```

It's not the wrong password, although entering the wrong password has exactly the same effect.  
I've been using that file for years, on Chrome and Firefox, always without any problem.
I can open it OK on Chrome.

Firefox 63.03, and I see it asks to update.  I'll do that and update here with any changes.

**Comment by antelle** [comment]
Hi! Are there any details in the error? Probably it's possible to expand it.

**Comment by MrP** [comment]
After restarting Firefox and letting it update to 64, it doesn't happen anymore.  Problem solved!

**Comment by MrP** [comment]
Oh, wow, very quick reply time.  Sorry, I lost the console logs after restarting FF.  I'll do a bit more digging if it happens again.

**Comment by asabbagh** [comment]
This is happening consistently for me with Firefox 67.0.4 (64-bit)

The first time I open a file, it succeeds, but afterwards if I try opening the file again I get the error, no matter if the password I type is correct or not. I can prevent the error from happening on the next attempt by deleting the local storage, specifically the entry called "fileInfo". Subsequent attempts will still have the error.
Browser popup that has in it:
```
There was an error opening file

[object Event]
```
Checking in the browser's console there is more info. The part of the error that I think is relevant is:

> error: DOMException: "A mutation operation was attempted on a database that did not allow mutations."

But a larger excerpt is included here:

```
2019-07-01T04:48:42.668Z [open-view] Error opening file 
error
​
bubbles: true
cancelBubble: false
cancelable: true
composed: false
currentTarget: null
defaultPrevented: false
eventPhase: 0
explicitOriginalTarget: IDBOpenDBRequest { onblocked: null, onupgradeneeded: onupgradeneeded(), readyState: "done", … }
isTrusted: true
originalTarget: IDBOpenDBRequest { onblocked: null, onupgradeneeded: onupgradeneeded(), readyState: "done", … }
returnValue: true
srcElement: IDBOpenDBRequest { onblocked: null, onupgradeneeded: onupgradeneeded(), readyState: "done", … }
target: IDBOpenDBRequest

error: DOMException: "A mutation operation was attempted on a database that did not allow mutations."
​
onblocked: null
onerror: function onerror()
onsuccess: function onsuccess()
onupgradeneeded: function onupgradeneeded()
readyState: "done"
source: null
transaction: null
<prototype>: IDBOpenDBRequestPrototype { onblocked: Getter & Setter, onupgradeneeded: Getter & Setter, … }
timeStamp: 75738
type: "error"
<get isTrusted()>: function isTrusted()
<prototype>: EventPrototype { composedPath: composedPath(), stopPropagation: stopPropagation(), stopImmediatePropagation: stopImmediatePropagation(), … }
passwords:12:2660
```
