### ISSUE TITLE
Feature Request to hide items in folded Sub-Group(s)

### ISSUE THREAD

**Issue by T3KN0KRAT** [keeweb/keeweb#1062]
I didn't find this in the Settings, nor as an existing Issue.

I have nested Groups, and when I select a top-level group, I would expect to see Entries belonging to that Group only.  Instead, I see all of the entries within the nested sub-Groups. I suppose that this would be a welcome feature to some, but I'd prefer to not see _all_ of the entries within that group recursively.

**Comment by antelle** [comment]
It’s Settings > General > Appearance > Show entries from all subgroups
