### ISSUE TITLE
self-hosted release is obsolete

### ISSUE THREAD

**Issue by hejnm1am** [keeweb/keeweb#1064]
Current release is now 1.6.3, but the self-hosted release (branch gh-pages) is still on 1.3.3.

Could you please update gh-pages branch?
Or better provide instructions how to build self-hosted pages from sources?

Thank you.

**Comment by antelle** [comment]
Hi! It's 1.6.3, not 1.3.3. Which commit did you check out to get 1.3.3?

**Comment by hejnm1am** [comment]
You are right. Sorry, it was my mistake.
I downloaded gh-pages.zip from github.com/keeweb/keeweb/archive/gh-pages.zip

I am not sure, what I did wrong, it was probably nginx cache or something.

**Comment by antelle** [comment]
Probably you had it open in browser and refreshed. It won't update, because there's application cache. If you refresh it two times, you will see the new version.
