### ISSUE TITLE
[help wanted] use keeweb to open kdbx on restricted webdav domain

### ISSUE THREAD

**Issue by giopas** [keeweb/keeweb#1066]
Hello,

Until now I used to access my personal passwords from work via KeePass (portable) and a webdav access to my NAS (via a DDNS provider).

However my IT administrator recently put such DDNS domain on the blacklist, so that I do not have access to my kdbx anymore.

My question is probably stupid (as I think the app only downloads the db on the fly and stores it in the desktop cache) but it is worth to ask: can I use keeweb, maybe installed on another domain, to connect to my kdbx?

If not, what other solutions do you foresee?

Thanks in advance!

**Comment by antelle** [comment]
If the domain where you store kdbx is blocked, you won't be able to access it.
You can move it to another domain (or ip address, if it's available) and work with it.
