### ISSUE TITLE
Multiline entry fields causes clipping

### ISSUE THREAD

**Issue by Strikeskids** [keeweb/keeweb#107]
There is no way to create multiline fields. Additionally, multiline fields from other apps get squashed into a single line in the history view, causing various buttons to disappear.

I imagine this will occur in all versions of the app.

In normal view, it looks okay.

![normal view](https://cloud.githubusercontent.com/assets/1040016/13325265/183bef22-dbaf-11e5-8448-41f10183e8a7.png)

Sample of buttons clipping outside of the screen in history view

![picture of clipping](https://cloud.githubusercontent.com/assets/1040016/13325222/f4c7f14e-dbae-11e5-9bad-e48a6daa388b.png)

[Sample database used](https://github.com/antelle/keeweb/files/146852/multiline.kdbx.zip)

**Comment by antelle** [comment]
currently, only title supports multi-line text...

**Comment by leolivier** [comment]
+1 for fixing this fast!
I wanted to add my 2FA Google rescue codes in a note in my Google entry but it's simply unreadable without new lines !
(great app anyway! I'm using it on Linux only for several months now and I think I will use it everywhere)

**Comment by screendriver** [comment]
Any news about that? This issue is pretty old and I can't save multiline fields at the moment (not only in history but in general)

**Comment by kumabon** [comment]
I also wish all fields besides Notes can support multi-line soon. It currently displays multi-line value well, but can't edit. With sufficient desperation thus motivation, an obvious but sad workaround is to use another KeePass client to enter such value...

For those of us who uses KeeWeb for record keeping beyond just website username/password would find this feature highly desirable.

Thanks and keep up the good work!

**Comment by jarlave** [comment]
Anything new?

**Comment by dzek69** [comment]
Bump?

I just corrupted my private key stored into a custom field. KeeWeb doesn't show new lines on edit, but it looks just fine when not editing. However - copying breaks new lines and I cannot use my private key as expected.

I'm forced to use Notes field.

**Comment by fboutin-pmc** [comment]
@dzek69 

Same here. Maybe we should kick a specific issue about supporting SSH Key entry type...

**Comment by dzek69** [comment]
Adding one specific type isn't way to go IMO, becuase more people may find more data types they need to store. All fields should support multiline.

**Comment by antelle** [comment]
Finally after three years, this is fixed. 😌 
Deployed to [beta.keeweb.info](https://beta.keeweb.info), will be available in the next release.
