### ISSUE TITLE
Google Drive integration is broken in 1.7.x

### ISSUE THREAD

**Issue by ginkel** [keeweb/keeweb#1080]
**Describe the bug**
Starting with v1.7.1 (I did not test 1.7.0) I can no longer authenticate with Google Drive to sync. I am using a GSuite account with 2FA enabled if that matters.

Keeweb is running as Desktop app obtained from: https://aur.archlinux.org/packages/keeweb-desktop/

**To Reproduce**
0. Clear cookies with `sed -i.bak -e 's/"cookies":\[.*\]/"cookies":[]/g' ~/.config/KeeWeb/runtime-data.json`
1. Open App
2. Click on Google Drive icon
3. A pop-up opens
4. Click on More
5. Click on Google Drive
6. Enter credentials
7. After entering 2FA token a redirect to the following dialog happens:

![image](https://user-images.githubusercontent.com/174129/50769573-ae412a00-1284-11e9-9858-0c54a8f56b6f.png)

8. When attempting another log-in an OAuth2 error is displayed:

![image](https://user-images.githubusercontent.com/174129/50769745-49d29a80-1285-11e9-9fdb-ecc4334dbfd6.png)

**Expected behavior**
I can successfully log-in to Google Drive.

**Screenshots**
See above.

**Environment**
KeeWeb v1.7.1 (22728d8, 2019-01-06)
Environment: electron v4.0.1
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) KeeWeb/1.7.1 Chrome/69.0.3497.106 Electron/4.0.1 Safari/537.36

**Kdbx File**
n/a

**Logs**
```
[ERROR] 2019-01-07T12:58:34.168Z [settings] Error loading file-info SyntaxError: Unexpected token l in JSON at position 409
[INFO ] 2019-01-07T12:58:34.390Z [app] Started in 461ms ¯\_(ツ)_/¯
[DEBUG] 2019-01-07T12:58:41.744Z [storage-gdrive] OAuth: popup opened
[ERROR] 2019-01-07T13:00:16.457Z [storage-gdrive] OAuth error popup closed
[DEBUG] 2019-01-07T13:00:18.718Z [storage-gdrive] OAuth: popup opened
[ERROR] 2019-01-07T13:09:02.428Z [storage-gdrive] OAuth error popup closed
```

**Comment by MichielVanwelsenaere** [comment]
same scenario for the dropbox integration

**Comment by JochenDiekenbrock** [comment]
Same here on Windows

**Comment by antelle** [comment]
This is already fixed, an update will be released tonight.

**Comment by JochenDiekenbrock** [comment]
> This is already fixed, an update will be released tonight.

Perfect @antelle , thank you!
