### ISSUE TITLE
Fail to build with grunt

### ISSUE THREAD

**Issue by JohRest** [keeweb/keeweb#1081]
I'm trying to build the html file, but I cannot get past this build error message:
Loading "Gruntfile.js" tasks...ERROR
>> Error: Cannot find module './build/util/postcss-replace-font'
Warning: Task "default" not found. Use --force to continue.

Aborted due to warnings.

I tried to resolve the postcss-replace-font package, but couldn't find any suitable...

Regards & thanks!

Johannes

**Comment by antelle** [comment]
Hi! How do you launch grunt?

**Comment by antelle** [comment]
Added missing files, thanks
