### ISSUE TITLE
Loading "sass.js" tasks...ERROR

### ISSUE THREAD

**Issue by JohRest** [keeweb/keeweb#1083]
started grunt from command line:
Loading "sass.js" tasks...ERROR
>> SyntaxError: Unexpected token (
>> Local Npm module "grunt-appdmg" not found. Is it installed?
Loading "grunt-sign-desktop-files.js" tasks...ERROR
>> SyntaxError: missing ) after argument list
Loading "grunt-sign-dist.js" tasks...ERROR
>> SyntaxError: missing ) after argument list
Loading "grunt-sign-exe.js" tasks...ERROR
>> SyntaxError: missing ) after argument list
Warning: Task "sass" not found. Use --force to continue.

Aborted due to warnings.

Execution Time (2019-01-07 18:50:46 UTC+1)
loading tasks  1.2s  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 100%
Total 1.2s

**Comment by antelle** [comment]
Hi! Which branch is it?

**Comment by antelle** [comment]
This works for me, what does it give to you (please exclude node-gyp stuff)?
```
npm -v && git clone git@github.com:keeweb/keeweb.git -b develop && cd keeweb && npm i && grunt --skip-sign
```

**Comment by JohRest** [comment]
will give it a try

**Comment by JohRest** [comment]
npm -v && git clone git@github.com:keeweb/keeweb.git -b develop && cd keeweb && npm i && grunt --skip-sign
6.5.0
Klone nach 'keeweb'...
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by antelle** [comment]
You can clone with https if a git url fails for you

**Comment by JohRest** [comment]
[johannes@jritserver tmp]$ npm -v && git clone https://github.com/keeweb/keeweb.git -b develop && cd keeweb && npm i && grunt --skip-sign             
6.5.0
Klone nach 'keeweb'...
remote: Enumerating objects: 116, done.
remote: Counting objects: 100% (116/116), done.
remote: Compressing objects: 100% (89/89), done.
remote: Total 15310 (delta 49), reused 76 (delta 27), pack-reused 15194
Empfange Objekte: 100% (15310/15310), 9.74 MiB | 4.99 MiB/s, done.
Löse Unterschiede auf: 100% (11404/11404), done.

> iltorb@1.3.10 install /home/johannes/tmp/keeweb/node_modules/iltorb
> detect-libc prebuild-install || node-gyp rebuild


> keytar@4.3.0 install /home/johannes/tmp/keeweb/node_modules/keytar
> prebuild-install || node-gyp rebuild

prebuild-install WARN install libsecret-1.so.0: cannot open shared object file: No such file or directory
Package libsecret-1 was not found in the pkg-config search path.
Perhaps you should add the directory containing `libsecret-1.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libsecret-1' found
gyp: Call to 'pkg-config --libs-only-l libsecret-1' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:345:16)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:219:12)
gyp ERR! System Linux 3.10.0-957.1.3.el7.x86_64
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/johannes/tmp/keeweb/node_modules/keytar
gyp ERR! node -v v6.16.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 

> node-sass@4.11.0 install /home/johannes/tmp/keeweb/node_modules/node-sass
> node scripts/install.js

Downloading binary from https://github.com/sass/node-sass/releases/download/v4.11.0/linux-x64-48_binding.node
Download complete..] - :
Binary saved to /home/johannes/tmp/keeweb/node_modules/node-sass/vendor/linux-x64-48/binding.node
Caching binary to /home/johannes/.npm/node-sass/4.11.0/linux-x64-48_binding.node

> electron@4.0.1 postinstall /home/johannes/tmp/keeweb/node_modules/electron
> node install.js

Downloading tmp-8365-1-SHASUMS256.txt-4.0.1
[============================================>] 100.0% of 4.74 kB (4.74 kB/s)

> node-sass@4.11.0 postinstall /home/johannes/tmp/keeweb/node_modules/node-sass
> node scripts/build.js

Binary found at /home/johannes/tmp/keeweb/node_modules/node-sass/vendor/linux-x64-48/binding.node
Testing binary
Binary is fine

> keeweb@1.7.2 postinstall /home/johannes/tmp/keeweb
> cd desktop && npm install

added 1 package from 1 contributor and audited 1 package in 0.809s
found 0 vulnerabilities

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: grunt-appdmg@1.0.0 (node_modules/grunt-appdmg):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for grunt-appdmg@1.0.0: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: appdmg@0.4.5 (node_modules/appdmg):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for appdmg@0.4.5: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: keytar@4.3.0 (node_modules/keytar):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: keytar@4.3.0 install: `prebuild-install || node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

added 1595 packages from 1110 contributors and audited 12946 packages in 72.421s
found 0 vulnerabilities

Loading "sass.js" tasks...ERROR
>> SyntaxError: Unexpected token (
>> Local Npm module "grunt-appdmg" not found. Is it installed?
Loading "grunt-sign-desktop-files.js" tasks...ERROR
>> SyntaxError: missing ) after argument list
Loading "grunt-sign-dist.js" tasks...ERROR
>> SyntaxError: missing ) after argument list
Loading "grunt-sign-exe.js" tasks...ERROR
>> SyntaxError: missing ) after argument list
Warning: Task "sass" not found. Use --force to continue.

Aborted due to warnings.


Execution Time (2019-01-07 21:04:38 UTC+1)
loading tasks  1.3s  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 100%
Total 1.3s

**Comment by antelle** [comment]
Do you have an idea what it is?
```
SyntaxError: Unexpected token (
```
I don't get it on my machine.

**Comment by JohRest** [comment]
to be honest I do not know. Perhaps my nodejs installation might be simply too old. node --version yields:

v6.16.0

Might that be the reason why?

**Comment by JohRest** [comment]
running on centos 7

**Comment by antelle** [comment]
Oh that's old, however your npm version is quite new. I would try new node.js, something like v10.15.0.

**Comment by antelle** [comment]
I've added "engine" section to package.json to show that node.js should be 10+.

**Comment by JohRest** [comment]
tested this with my laptop setup (running 10.13 or so) works like a charm. I've copied the output to my production machine and it works there too... :-) Convincing my server to build it is not that easy as it always prefers the matching version of nodejs (which is 6.x.x). But anyway... I think we can close this.
