### ISSUE TITLE
Google Drive sync opens another KeeWeb window instead of syncing [AUR version]

### ISSUE THREAD

**Issue by koterpillar** [keeweb/keeweb#1089]
**Describe the bug**

Since 1.7, after a successful Google Drive authorization the authorization popup displays the main KeeWeb "Click to open a file" screen and doesn't sync anything.

**To Reproduce**
1. Open KeeWeb 1.7.3.
2. Open a file from Google Drive.
3. Complete the authorization process in the popup.
4. The popup stays open with the default KeeWeb theme and language.

Alternatively:

1. Open a file from Google Drive on KeeWeb 1.6.x.
2. Open KeeWeb 1.7.3.
3. Choose "synchronize" and complete the authorization process in the popup.
4. The popup stays open with the default KeeWeb theme and language.

**Expected behavior**
The popup should disappear and the database be synchronized.

**Screenshots**
![default](https://user-images.githubusercontent.com/140276/51240262-78f8b280-19cf-11e9-93b6-14a19a637dda.png)

**Environment**
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) KeeWeb/1.7.3 Chrome/66.0.3359.181 Electron/3.0.13 Safari/537.36

**Kdbx File**
Does it happen on Demo or New database?  
If you have a test db without your personal data, please attach it.

**Logs**
```
index.html:18 2019-01-16T09:46:51.443Z [sync:XXXXXXXXXX] Sync started gdrive 0B-5Mr_F4zO26V2I4TmZzXzNOLWc {startedByUser: true}
index.html:18 2019-01-16T09:46:51.458Z [sync:XXXXXXXXXX] Stat file
index.html:18 2019-01-16T09:46:51.459Z [storage-gdrive] OAuth: popup opened
```

At this point, the popup just shows the "Click to open a file", so I closed it.

```
index.html:18 2019-01-16T09:46:59.034Z [storage-gdrive] OAuth error popup closed
s.error @ index.html:18
e @ index.html:18
p @ index.html:13
g @ index.html:13
l @ index.html:13
s.trigger @ index.html:13
triggerClosed @ index.html:18
setTimeout (async)
(anonymous) @ index.html:18
apply @ /usr/lib/electron/resources/electron.asar/common/api/callbacks-registry.js:47
ipcRenderer.on @ /usr/lib/electron/resources/electron.asar/renderer/api/remote.js:285
emit @ events.js:182
index.html:18 2019-01-16T09:46:59.035Z [sync:XXXXXXXXXX] Stat error, not dirty OAuth: popup closed
index.html:18 2019-01-16T09:46:59.036Z [sync:XXXXXXXXXX] Sync finished OAuth: popup closed
```

**Comment by antelle** [comment]
Hi! Does it repeat on a fresh setup? Could be related to the cookie fix.

**Comment by koterpillar** [comment]
Yes, the same thing happens, I removed the whole directory:

![screenshot](https://user-images.githubusercontent.com/140276/51309049-a872f200-1a97-11e9-987a-b2ac72a56efa.png)

**Comment by koterpillar** [comment]
In the logs:

```
2019-01-17T09:37:49.806Z [storage-gdrive] OAuth: popup opened
```

**Comment by koterpillar** [comment]
Is there any debugging I can do to provide the necessary information?

**Comment by antelle** [comment]
Let's try this:

1. open DevTools from Settings > General > Advanced
2. paste this to Console:
```js
require('electron').remote.app.openWindow = opts => {
    const electron = require('electron').remote.require('electron');
    const win = new electron.BrowserWindow(opts);
    win.webContents.on('will-redirect', (e, url) => console.log('will-redirect', url));
    win.webContents.on('will-navigate', (e, url) => console.log('will-navigate', url));
    return win;
};
```
3. check the output (important: strip everything from it! I what I need is the domain name + url, not the actual args). For example, on my machine it's this:
```
2019-01-18T14:45:40.940Z [storage-gdrive] OAuth: popup opened
VM256:5 will-navigate https://accounts.google.com/signin/oauth?...
VM256:5 will-navigate https://accounts.google.com/CheckCookie?...
VM256:4 will-redirect https://accounts.youtube.com/accounts/SetSID?...
VM256:4 will-redirect https://accounts.google.nl/accounts/SetSID?...
VM256:5 will-navigate https://accounts.google.com/signin/oauth/consent?...
VM256:4 will-redirect https://accounts.google.com/signin/oauth/consent?...
VM256:5 will-navigate https://app.keeweb.info/#access_token=...
index.html:12 2019-01-18T14:46:27.972Z [storage-gdrive] OAuth token received
index.html:12 2019-01-18T14:46:27.973Z [storage-gdrive] List
index.html:12 2019-01-18T14:46:28.409Z [storage-gdrive] Listed 436ms
```

**Comment by koterpillar** [comment]
Well, this is embarrassing.

I've downloaded the _official_ 1.7.4 release, and it works fine.

Note in the About dialog, it now says:

> KeeWeb v1.7.4 (f2303f44, 2019-01-17)
> Environment: electron v4.0.1
> User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) KeeWeb/1.7.4 Chrome/69.0.3497.106 Electron/4.0.1 Safari/537.36

Before I was using [keeweb from AUR](https://aur.archlinux.org/packages/keeweb/):

> KeeWeb v1.7.3 (da922d2, 2019-01-14)
> Environment: electron v3.1.1
> User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) KeeWeb/1.7.3 Chrome/66.0.3359.181 Electron/3.1.1 Safari/537.36

Note the Electron major version 3.

By the way, I did try that code snipped with `will-redirect` and `will-navigate` but it showed nothing at all.

I'll close this and try to get the message to AUR instead.

**Comment by koterpillar** [comment]
(Leaving open in case more people try to report this - close at your discretion)

**Comment by antelle** [comment]
Indeed, electron was upgraded to v4, in this version they changed their API, so KeeWeb doesn't get events and can't close the window.
CC @fthiery

**Comment by fthiery** [comment]
> Before I was using [keeweb from AUR](https://aur.archlinux.org/packages/keeweb/):
> > KeeWeb v1.7.3 ([da922d2]
> Note the Electron major version 3.

Can you try the 1.7.4 AUR to compare apples to apples ? (was pushed by "wget" yesterday).

You need to understand that the AUR package uses the official build archive too; it just disables the updater feature. In other terms, it's not the package that defines the electron version (it's a binary package -- despite wget's comment on  2017-09-24 12:34: https://aur.archlinux.org/packages/keeweb-desktop/).

**Comment by fthiery** [comment]
NB: with the latest AUR i also get electron v4.0.1

```KeeWeb v1.7.4 (f2303f44, 2019-01-17)
Environment: electron v4.0.1
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) KeeWeb/1.7.4 Chrome/69.0.3497.106 Electron/4.0.1 Safari/537.36```

**Comment by antelle** [comment]
Let's close this, it doesn't seem to be actionable.
