### ISSUE TITLE
self hosting with Gdrive

### ISSUE THREAD

**Issue by unas08** [keeweb/keeweb#1090]
I'm trying to set up keeweb on my own domain (https://keeweb.iapp.no). 
When I try to connect it with gdrive to store keyfile, stops here. 
I'm a new in programing and can't understand about CONFIGURE & .json files etc. 

Can anyone make a good guide with steps by step, how to connect gdrive for self hosting. PLEASE

**Comment by antelle** [comment]
Hi! You need to create your app in Google Drive: https://github.com/keeweb/keeweb/wiki/Dropbox-and-GDrive#google-drive
Then create a json config for KeeWeb: https://github.com/keeweb/keeweb/wiki/Configuration#json-app-config
and add your `gdriveClientId` there (you get it when you create an app in gdrive).

**Comment by unas08** [comment]
Hi antelle,
Thanks for your guide. But, sorry to say. 
I have tried everything according to your guide. but I don't get it.  

I get an error message: redirect_uri_mismatch.

I have the following settings:
CNAME: https://keeweb.iapp.no

Keeweb file locations: https://iapp.no/keeweb

Created config.json file...
{
    "settings": {
    "gdrive": "true", 
    "gdriveClientId": "850648644064-xxxxxxxxxxxxxxxxxxx.apps.googleusercontent.com"
    }
}

Authorized JavaScript origins & Authorized redirect URI is: https://keeweb.iapp.no

What is wrong here. Help me pls.

**Comment by antelle** [comment]
So, what do you have as redirec uri in google app settings?

**Comment by unas08** [comment]
![image](https://user-images.githubusercontent.com/46752826/51286139-f7664c00-19f1-11e9-870b-a401bb261b41.png)

**Comment by antelle** [comment]
What happens if you add the last slash there (https://keeweb.iapp.no/)?

**Comment by unas08** [comment]
Great, after i entered tha "slash", works fine on PC. 
But not on mobile version. Here is error again. 
![image](https://user-images.githubusercontent.com/46752826/51306803-7bdebc00-1a3e-11e9-802c-02adadf97603.png)

**Comment by antelle** [comment]
probably the config is not applies, project id is different

**Comment by unas08** [comment]
Pls. guide me to apply this config. 
I'm not very good at programming. I start with this now and I like this program.

What am I doing wrong here?

Has created a config.json file and uploaded the same directory with index.html file.

Has changed the following..
<meta name = "kw-config" content = "config.json">

And uppdated by...https://keeweb.iapp.no/?config=config.json

![image](https://user-images.githubusercontent.com/46752826/51308799-42f51600-1a43-11e9-89c2-e3bceeca1cd4.png)

**Comment by unas08** [comment]
wow, now its working. superb. thank you.
But, still have trouble to create "Group". No create og save button.
![image](https://user-images.githubusercontent.com/46752826/51378724-1a861e00-1b0e-11e9-918a-e9757133d10a.png)

**Comment by antelle** [comment]
There's no Save button, it's already created when you put something into the Name field.

**Comment by unas08** [comment]
![image](https://user-images.githubusercontent.com/46752826/51392961-ce030880-1b36-11e9-8a00-5c1d6d10e42d.png)

**Comment by antelle** [comment]
Weird. Does it happen if you create a new file?

**Comment by unas08** [comment]
Sorry It was my fault.
Folders and files hidden under the main folder.
However, when I create files or folders, it does not display the same as your view. Why?

![image](https://user-images.githubusercontent.com/46752826/51393549-3e5e5980-1b38-11e9-9401-94958a744cd3.png)

**Comment by antelle** [comment]
Creating a folder doesn't expand it. If it's collapsed, it remains collapsed. So the folder is created, but it's not visible.

**Comment by unas08** [comment]
yes, thats right

**Comment by esturniolo** [comment]
Hi @antelle.
I've the same error as @unas08, but with the difference that I can't make it work.
I know that this is not a KeeWeb issue, but I'm tired of googling without find any result where say what in the hell should I put in the URI.
I've the same problem to add a Login with Google for another personal project, where I should add something in the URI but I don't know what.
I tried every combination that I imagine.
If I run `kc.settings.get();` on the console, I see all the settings even my Google Client ID. Should I include the `.apps.googleusercontent.com ` section of the ID? 

<img width="589" alt="captura de pantalla 2019-02-04 a la s 18 22 24" src="https://user-images.githubusercontent.com/5169045/52238541-fd41a580-28aa-11e9-97fa-f9b92c759fac.png">
<img width="626" alt="captura de pantalla 2019-02-04 a la s 18 17 13" src="https://user-images.githubusercontent.com/5169045/52238542-fd41a580-28aa-11e9-8eba-680fd15e27d1.png">


Regards and sorry for bother you with this.

Thanks for KeeWeb, it's a great solution.

**Comment by antelle** [comment]
@esturniolo that's weird, if they're the same. 
> Should I include the .apps.googleusercontent.com section of the ID

It looks like your ID is correct, because you see the project in Google. If you go to the link displayed on the screenshot - does it open this project settings?

**Comment by esturniolo** [comment]
>  does it open this project's Google settings?
I don't fully understand your question, what do you mean? The Google Console link or keeweb link?

If I open the link were keeweb is installed I see the following:

<img width="991" alt="captura de pantalla 2019-02-04 a la s 18 42 01" src="https://user-images.githubusercontent.com/5169045/52239265-d08e8d80-28ac-11e9-997b-de9bf6469ace.png">

Then, I click on "More"

<img width="989" alt="captura de pantalla 2019-02-04 a la s 18 42 09" src="https://user-images.githubusercontent.com/5169045/52239283-dab08c00-28ac-11e9-9c96-881a409e1d11.png">

Finally on the Drive icon and this stupid popup message.

<img width="1005" alt="captura de pantalla 2019-02-04 a la s 18 42 21" src="https://user-images.githubusercontent.com/5169045/52239311-e8661180-28ac-11e9-8cfb-6e5ac032e7e3.png">

As I said before, the devs console show the correct info:

<img width="658" alt="captura de pantalla 2019-02-04 a la s 18 45 35" src="https://user-images.githubusercontent.com/5169045/52239427-3713ab80-28ad-11e9-9168-139605b0bb8d.png">

So really I'm lost with this.

I can use with Dropbox that works flawlessly, but I've all my universe on Google.

**Comment by antelle** [comment]
Yes, I mean the Google's Console link. This thing:
<img width="390" alt="untitled" src="https://user-images.githubusercontent.com/633557/52239720-6fc47c80-28cf-11e9-8c13-9f3b207056e0.png">

(I just want to ensure the settings are applied correctly)

**Comment by antelle** [comment]
Another suggestion: try removing the `/kw/` url from the project settings, what will be displayed in the ui?

**Comment by esturniolo** [comment]
> Yes, I mean the Google's Console link. This thing:
> <img alt="untitled" width="390" src="https://user-images.githubusercontent.com/633557/52239720-6fc47c80-28cf-11e9-8c13-9f3b207056e0.png">
> 
> (I just want to ensure the settings are applied correctly)

Yes, the same Client Id that I put on the .json.

**Comment by esturniolo** [comment]
> Another suggestion: try removing the `/kw/` url from the project settings, what will be displayed in the ui?

I removed /kw/ in the project setting, so you can see that the link is `https://myweb.com` instead of `https://myweb.com/kw/`
Same results...

I wanna cry.

**Comment by esturniolo** [comment]
Hi again @antelle.

I started from scratch with new credentials and new domain (thanks .tk domains for your existence) and now I've all working.

Anyway the URI are a little tricky.
