### ISSUE TITLE
Keeweb keeps asking me what Google account to use

### ISSUE THREAD

**Issue by bnbaz** [keeweb/keeweb#1091]
Since 1.7.3, my file did not sync to Google drive anymore (404 error). After logging out and into my Google account again, sync worked.

However, Keeweb now repeatedly shows me me (upon launch?) a google popup with the option to pick one of my two Google accounts. I use 2 Google accounts in Chrome, but only one in Keeweb. I do not recall logging into my second Google account.

I will add details as soon as I find out more.

Possibly related to #1089 ?

**Comment by antelle** [comment]
Hi! What happens if you delete `ApplicationData/KeeWeb/temp`, then uncheck Google Drive in settings and check it again? This should fix it.

**Comment by bnbaz** [comment]
This seems to fix the issue on at least one of the two devices it occurred
on
