### ISSUE TITLE
Password DB 

### ISSUE THREAD

**Issue by HannesPoe** [keeweb/keeweb#1092]
Hi!
After I updated to v4.0.1, the program opens without a valid database.  It askes for a *.kdbx file which I can't find on the entire system.
Which is the default path for the database? Could the database have another name? Did you use a different DB format in older versions?
Thank You!
Johannes

KeeWeb v1.7.3 (da922d22, 2019-01-13)
Environment: electron v4.0.1
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) KeeWeb/1.7.3 Chrome/69.0.3497.106 Electron/4.0.1 Safari/537.36

**Comment by antelle** [comment]
Hi! Did you use a file stored "inside the internal app storage"? It should be in `Application Data/Offline Files`, unless it was removed by something from there.
