### ISSUE TITLE
Is there anywhere a log for keeweb?

### ISSUE THREAD

**Issue by DimpiM** [keeweb/keeweb#1093]
My last synchronization was on 13.01.19
I load my keepass file over dropbox but after 13.01.19 the syncronization fails with the message
`Error: Network error`
I can read all passwords but I can not save new entries.
![02](https://user-images.githubusercontent.com/4437412/51371905-bfe3c680-1afb-11e9-8cb1-4f7c3cc56009.PNG)
So, is there any way to read the log file to identify the error or is this a known issue?

If i click `Syncronization` the endpoint `get_metadata` replies with a 302 Status.
I also noticed that the site is not secure.

![01](https://user-images.githubusercontent.com/4437412/51371816-83b06600-1afb-11e9-9797-ac22a5982a72.PNG)

Kind regards

**Comment by antelle** [comment]
Hi! Let’s see your network tab in devtools. Perhaps something is going wrong with saving your file.

**Comment by DimpiM** [comment]
![01](https://user-images.githubusercontent.com/4437412/51372537-e4d93900-1afd-11e9-89d9-ea863df6f6f1.PNG)
This happens if I click on `Syncronization`

I also noticed a small red circle in the left bottom corner
![02](https://user-images.githubusercontent.com/4437412/51372731-64ff9e80-1afe-11e9-9e52-3f6b514d7261.PNG)
