### ISSUE TITLE
KeeWeb does not come to foreground if logged out on Autofill

### ISSUE THREAD

**Issue by ginkel** [keeweb/keeweb#1095]
**Describe the bug**

**To Reproduce**
1. Log in to KeeWeb
2. Wait until logout happens, do not minimize or close the window
3. Trigger an autofill using Alt+Shift+T
4. Nothing happens, the window does not come to front and gain the focus

**Expected behavior**
Step 3 above brings the KeeWeb window to front with its focus in the password entry field (as has been the case with KeeWeb < 1.7).

**Screenshots**
n/a

**Environment**
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) KeeWeb/1.7.3 Chrome/69.0.3497.106 Electron/4.0.1 Safari/537.36

**Kdbx File**
n/a

**Logs**
```
[INFO ] 2019-01-19T10:07:30.628Z [app] Started in 531ms ¯\_(ツ)_/¯
[INFO ] 2019-01-19T10:07:34.258Z [open:***] File open request
[INFO ] 2019-01-19T10:07:34.258Z [open:***] Open file from cache, will sync after load gdrive
[DEBUG] 2019-01-19T10:07:34.259Z [storage-cache] Load ***
[DEBUG] 2019-01-19T10:07:34.263Z [storage-cache] Loaded *** 2ms
[INFO ] 2019-01-19T10:07:34.263Z [open:***] Loaded file from cache null
[INFO ] 2019-01-19T10:07:34.477Z [file] Opened file tg: 210ms, 100000 rounds, 95 kB
[DEBUG] 2019-01-19T10:07:34.477Z [app] Add last open file *** *** gdrive *** ***
[INFO ] 2019-01-19T10:07:34.634Z [open:***] Sync just opened file
[INFO ] 2019-01-19T10:07:34.664Z [sync:***] Sync started gdrive *** {}
[INFO ] 2019-01-19T10:07:34.667Z [sync:***] Stat file
[DEBUG] 2019-01-19T10:07:34.667Z [storage-gdrive] Stat ***
[DEBUG] 2019-01-19T10:07:35.017Z [storage-gdrive] Stated *** 350ms
[INFO ] 2019-01-19T10:07:35.017Z [sync:***] Stat found same version, not modified
[INFO ] 2019-01-19T10:07:35.017Z [sync:***] Sync finished no error
[DEBUG] 2019-01-19T10:26:40.757Z [auto-type] Auto type event null
[DEBUG] 2019-01-19T10:26:40.762Z [auto-type] Get window title
[INFO ] 2019-01-19T10:26:40.794Z [launcher] spawn xdotool: 0, 32ms
*** - Chromium
[DEBUG] 2019-01-19T10:26:40.795Z [auto-type] Window title *** - Chromium null
[DEBUG] 2019-01-19T10:26:40.795Z [auto-type] auto-type event delayed
```

**Comment by antelle** [comment]
Strange, seems to be linux-specific. Works here on macOS.

**Comment by ginkel** [comment]
FYI, still happens with v1.7.4.

**Comment by antelle** [comment]
Of course if happens, otherwise it would've been closed.

**Comment by benzkji** [comment]
I've encoutered some "getting no focus" issues with the new 1.7 releases as well, whereas under 1.6 it was much more stable. using xubuntu / xfce. but, not specific to log out, I'm not locking my keeweb. just randomly not getting focus, when no or too many entries are found. I'm on 1.7.2, will update.

**Comment by antelle** [comment]
That's weird, focus stuff was changed in v1.7.4.

**Comment by benzkji** [comment]
1.7.4 is better for me, after a quick test (though, still the first time it didnt get focus). will report again.

**Comment by benzkji** [comment]
sorry, not really better. I cannot detect a logic to reproduce this issue.

**Comment by HarlemSquirrel** [comment]
I'm also experiencing this issue on ArchLinux since upgrading from 1.6 to 1.7. Even with the latest version 1.7.7 KeeWeb appears above other windows but my blinking cursor remains on the previous window. I can use [Alt] + [Tab] to switch fully to KeeWeb and then continue the global auto-type process.

**Comment by HarlemSquirrel** [comment]
Still a problem with v1.7.8. Is there any way I can help out? I'm not super familiar with Electron but if someone can point me in the right directory I could test or poke around a bit.

**Comment by antelle** [comment]
@HarlemSquirrel you can start here: https://github.com/keeweb/keeweb/blob/master/desktop/app.js
