### ISSUE TITLE
WebDav configuration. Lingering questions.

### ISSUE THREAD

**Issue by larssb** [keeweb/keeweb#1097]
First of all. Thank you for a great piece of software.

I'm trying to get WebDav to work with KeeWeb. I can load the KDBX database over WebDav by KeeWeb without any issue. This happens on e.g. *https://x.my-keeweb.com/keeweb/db/my.kdbx*. However when I want to sync changes with "*overwrite kdbx file with PUT*" I see the following error in the *app logs*:

```
[DEBUG] 2019-01-29T14:47:06.070Z [storage-webdav] Save:put error https://x.my-keeweb.com/keeweb/db/my.kdbx 403 40ms
[INFO ] 2019-01-29T14:47:06.071Z [sync:my] Error saving data to storage
[INFO ] 2019-01-29T14:47:06.071Z [sync:my] Sync finished HTTP status 403
```

If i try the "*Upload a temporary file and move*" option I get the following error:

```
[INFO ] 2019-01-29T14:53:12.342Z [sync:my] Stat found same version, modified, saving
[INFO ] 2019-01-29T14:53:12.342Z [sync:my] Getting file data for saving
[INFO ] 2019-01-29T14:53:14.058Z [sync:my] Saving to storage, skip cache because not dirty
[INFO ] 2019-01-29T14:53:14.058Z [sync:my] Save data to storage
[DEBUG] 2019-01-29T14:53:14.058Z [storage-webdav] Save:stat https://x.my-keeweb.com/keeweb/db/my.kdbx
[DEBUG] 2019-01-29T14:53:14.101Z [storage-webdav] Save:stated https://x.my-keeweb.com/keeweb/db/my.kdbx Thu, 17 Jan 2019 18:51:17 GMT 42ms
[DEBUG] 2019-01-29T14:53:14.101Z [storage-webdav] Save:put https://x.my-keeweb.com/keeweb/db/my.kdbx.1548773594058
[DEBUG] 2019-01-29T14:53:14.146Z [storage-webdav] Save:put error https://x.my-keeweb.com/keeweb/db/my.kdbx.1548773594058 404 45ms
[INFO ] 2019-01-29T14:53:14.146Z [sync:my] Error saving data to storage
[INFO ] 2019-01-29T14:53:14.146Z [sync:my] Sync finished {"notFound":true}
```
---
**Setup**

- Webserver: [Lighttpd](https://www.lighttpd.net/) v1.4.48
- Load-balancer: [HAProxy](http://www.haproxy.org/) v1.8
- OS: Busybox distro, on a [QNAP](https://www.qnap.com/) NAS. Kernel is v4.2.8
- HTTPS: A valid LetsEncrypt certificate is used via HAProxy. 
---
**Tried the following**

- Controlled for solved/closed issues related to this one. Haven't found one mactching the issue I have really well. Found this [one](https://github.com/keeweb/keeweb/issues/435). But the issue is fixed via a code change, so cannot see that a path issue should be the culprit
- Controlled that it **is** basic auth that I configured. It is. I also tried with no auth on WebDav, just as a test. No change
- Read this guide: [WebDav config](https://github.com/keeweb/keeweb/wiki/WebDAV-Config). I did **not** enable CORS though. As I cannot see that it should be necessary when the KDBX database is accessed over WebDav on the same URI as the KeeWeb software executes on. So to me there is no cross-origin here. Unless I swallowed my soup sideways on how CORS works :-D (could very well be, so please feel free to enlighten me)
- Controlled the permissions on the KeeWeb webroot dir and the involved folders when syncing.

1. The KeeWeb webroot dir: `drwxrwx---  4 wwwuser administrators 4096 2019-01-26 22:45 keeweb/`
2. The db dir: `drwxr-xr-x 2 wwwuser administrators    4096 2019-01-26 22:45 db/`
3. The db itself: `-rwxrwxrwx 1 wwwuser            504 93966 2019-01-17 19:51 my.kdbx*`

- Disabled basic auth on the KeeWeb endpoint. Made no change. Still `HTTP403` or `Error saving data to storage`
- I don't think it is HAProxy blocking this as I can confirm log entries in the Lighttpd *access.log* when trying to sync over WebDav. So requests *are* getting to the Lighttpd server. Here is the entries from the *access.log* when using "*overwrite...with PUT*" and when using "*...temporary file...*":

```
[~] # cat /opt/var/log/lighttpd/access.log | tail      
x.my-keeweb.com 127.0.0.1 - - [29/Jan/2019:16:11:41 +0100] "GET /keeweb/manifest.appcache HTTP/1.1" 304 0 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36"
x.my-keeweb.com 127.0.0.1 - - [29/Jan/2019:16:11:41 +0100] "GET /keeweb/icons/favicon-32x32.png HTTP/1.1" 200 1884 "https://x.my-keeweb.com/keeweb/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36"
x.my-keeweb.com 127.0.0.1 - - [29/Jan/2019:16:11:41 +0100] "GET /keeweb/manifest.appcache HTTP/1.1" 304 0 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36"
x.my-keeweb.com 127.0.0.1 - - [29/Jan/2019:16:11:41 +0100] "GET /keeweb/icons/favicon-32x32.png HTTP/1.1" 200 1884 "https://x.my-keeweb.com/keeweb/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36"
x.my-keeweb.com 127.0.0.1 - - [29/Jan/2019:16:12:16 +0100] "HEAD /keeweb/db/my.kdbx HTTP/1.1" 304 0 "https://x.my-keeweb.com/keeweb/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:64.0) Gecko/20100101 Firefox/64.0"
x.my-keeweb.com 127.0.0.1 - - [29/Jan/2019:16:12:18 +0100] "HEAD /keeweb/db/my.kdbx HTTP/1.1" 304 0 "https://x.my-keeweb.com/keeweb/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:64.0) Gecko/20100101 Firefox/64.0"
x.my-keeweb.com 127.0.0.1 - - [29/Jan/2019:16:12:19 +0100] "PUT /keeweb/db/.my.kdbx.1548774808602 HTTP/1.1" 404 345 "https://x.my-keeweb.com/keeweb/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:64.0) Gecko/20100101 Firefox/64.0"
x.my-keeweb.com 127.0.0.1 - - [29/Jan/2019:16:12:31 +0100] "HEAD /keeweb/db/my.kdbx HTTP/1.1" 304 0 "https://x.my-keeweb.com/keeweb/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:64.0) Gecko/20100101 Firefox/64.0"
x.my-keeweb.com 127.0.0.1 - - [29/Jan/2019:16:12:32 +0100] "HEAD /keeweb/db/my.kdbx HTTP/1.1" 304 0 "https://x.my-keeweb.com/keeweb/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:64.0) Gecko/20100101 Firefox/64.0"
x.my-keeweb.com 127.0.0.1 - - [29/Jan/2019:16:12:33 +0100] "PUT /keeweb/db/my.kdbx HTTP/1.1" 403 345 "https://x.my-keeweb.com/keeweb/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:64.0) Gecko/20100101 Firefox/64.0"
```

---

So.

* Do I really need to enable CORS here?
* Or is something else wrong?

Suggestions and general advice is more than welcome.

Thank you so much.

**Comment by antelle** [comment]
Hi,

Looks like it's not an issue with CORS.
The server returns either 403, or 404, that’s something that should be fixed, then keeweb will work.

Most likely it's not configured to write files over webdav?
