### ISSUE TITLE
Open URL in new tab

### ISSUE THREAD

**Issue by KaKi87** [keeweb/keeweb#1098]
I'm always frustrated when I want to open a website from an item, knowing that it will be opened in KeeWeb tab if I don't copy the URL, open a new tab, paste the URL, press Enter, go back to KeeWeb, copy the password, return to the new tab and paste the password

I would like to be able to right click the URL to open it in a new tab, or set up KeeWeb to always open links in new tab.

Thanks !

**Comment by antelle** [comment]
Hi! All of them have target=_blank, and they open in a new tab for me. Isn't it the same for you? Which browser/os are you using?
