### ISSUE TITLE
make mobile apps with cordova

### ISSUE THREAD

**Issue by benzkji** [keeweb/keeweb#1099]
just a short "will never happen" or "maybe" ;-) feel free to close it right away.

**Is your feature request related to a problem? Please describe.**
no

**Describe the solution you'd like**
embed the web app in cordova and release android and ios apps.

**Describe alternatives you've considered**
none

**Additional context**
none

**Comment by antelle** [comment]
Hi,
It's being discussed in #534.
Maybe it will happen, in theory that's possible, but we need contributions for this.
