### ISSUE TITLE
KdbxError: Error NotImplemented: AES-CBC not implemented

### ISSUE THREAD

**Issue by sekekec** [keeweb/keeweb#1100]
**THIS BUG OCCURS ONLY IN CHROME** 

**Describe the bug**
Self-hosted version does not work in **Chrome**

**To Reproduce**
1. Download gh-pages.zip
2. Extract it on your server
3. Open url to keeweb
4. See error: KdbxError: Error NotImplemented: AES-CBC not implemented

**Expected behavior**
Start screen should appear without any errors

<img width="693" alt="bildschirmfoto 2019-02-02 um 21 22 23" src="https://user-images.githubusercontent.com/47146365/52168962-66051280-2731-11e9-97e8-2c8e3b7581a3.png">

**Comment by antelle** [comment]
Hi! Most likely you're hosting it on http, not on https, am I correct? If so, it won't work.

**Comment by fazlerabbi37** [comment]
@antelle, can you please explain why it would not work over http? Last time I tried this app on Nextcloud 12 it did work but I could not use it due to the bug mentioned in [here](https://github.com/jhass/nextcloud-keeweb/issues/75).

**Comment by antelle** [comment]
Browsers can disable WebCrypto API if the page is loaded without HTTP, that's what happens here. We check if WebCrypto is available when we start the app and show this message if there's an error.

**Comment by fazlerabbi37** [comment]
@antelle thanks for your explanition!
