### ISSUE TITLE
Keeweb windows app doesn't save

### ISSUE THREAD

**Issue by hillout** [keeweb/keeweb#1104]
**Describe the bug**
After second editing of the same entry the app doesn't sync the file. It's no matter if it's set to update automatically or you do it manually. My file is syncing via Google Drive. 

**To Reproduce**
1. Open any entry.
2. Edit it.
3. Sync the file (with Google Drive). 
4. Open the same entry
5. Edit the entry second time.
6. Sync file.
7. You'll see that it hasn't been synced.

**Expected behavior**
Expected to see the file being synced after second editing, but it's not.

**Environment**
KeeWeb v1.7.5 (41a4e7ef, 2019-02-04)
Environment: electron v4.0.1
User-Agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) KeeWeb/1.7.5 Chrome/69.0.3497.106 Electron/4.0.1 Safari/537.36

**Logs**
First editing of an entry:
[DEBUG] 2019-02-05T13:30:38.648Z [storage-gdrive] Save 
[DEBUG] 2019-02-05T13:30:40.310Z [storage-gdrive] Saved 1662ms
[INFO ] 2019-02-05T13:30:40.311Z [sync:Keepass_tima] Update rev in file info
[INFO ] 2019-02-05T13:30:40.311Z [sync:Keepass_tima] Save to storage complete, update sync date
[INFO ] 2019-02-05T13:30:40.311Z [sync:Keepass_tima] Sync finished no error

After second editing of the same entry:

DEBUG] 2019-02-05T13:31:45.835Z [storage-gdrive] Stat 
[DEBUG] 2019-02-05T13:31:46.168Z [storage-gdrive] Stated 333ms
[INFO ] 2019-02-05T13:31:46.168Z [sync:Keepass_tima] Stat found same version, not modified
[INFO ] 2019-02-05T13:31:46.168Z [sync:Keepass_tima] Sync finished no error

**Comment by antelle** [comment]
Hi! Could you please describe what was changed in the entry? Maybe there's s specific change that we're missing.

**Comment by hillout** [comment]
Hi! Well I tried to change for example Note field, and also Name of the entry.
But I just noticed one weird thing - when in the group of entries I've checked the box which Enables searching in the entries - the problem disappears. Once I uncheck it - the problem persists.

**Comment by antelle** [comment]
That's the important thing, now I can repeat it, thanks.
