### ISSUE TITLE
New Bug - App window jumping around

### ISSUE THREAD

**Issue by tcz305** [keeweb/keeweb#1105]
**Describe the bug**
New bug with 1.7.5. Not present on previous versions.
Happens intermittently, not always. When either opening app or reactivating when minimized to dock, the app window will open on the center of the screen for about a half second or so and then bounce back to where it was on close.

**Expected behavior**
App window should open at same location when closed, not on the screen center, and then bounce back where it was on close.

**Environment**
KeeWeb v1.7.5 (41a4e7ef, 2019-02-04)
Environment: electron v4.0.1
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_2) AppleWebKit/537.36 (KHTML, like Gecko) KeeWeb/1.7.5 Chrome/69.0.3497.106 Electron/4.0.1 Safari/537.36

**Comment by antelle** [comment]
Weird, I can't reproduce it. Let's wait if there are other reports. Any help would be very welcome.

**Comment by tcz305** [comment]
It happened 4 times the first day I downloaded this version but have also not been able to reproduce it.
Possibly just a glitch on my end ...
Will update if anything new happens.
Thanks

**Comment by tcz305** [comment]
It just happened again. Reactivated from minimized after I minimized it when the app was showing some visual glitches.
Reopened a few minutes later and the app opened on the screen center for a good seemed like 3 seconds and then jumped to where it was on close.
Here's the log if it's any help

[log.txt](https://github.com/keeweb/keeweb/files/2847583/log.txt)

**Comment by antelle** [comment]
I really don't know what to do with it and won't be able to help, sorry.
If someone having this issue can debug it, it would be great.

**Comment by tcz305** [comment]
ok, no worries, it's not a big issue, feel free to close it.
Thanks

**Comment by antelle** [comment]
I would prefer to keep it open, maybe someone else has it.

**Comment by antelle** [comment]
I assume, it doesn't repeat.
