### ISSUE TITLE
AUR libsass 2.5.5 manjaro

### ISSUE THREAD

**Issue by lil5** [keeweb/keeweb#1109]
**Describe the bug**

Installation of signal desktop via AUR on Manjaro issn't working due to dependency libsass version

**To Reproduce**
1. Install manjaro gnome
2. Run pamac
3. Install `keeweb` from the aur
   http://aur.archlinux.org/packages/keeweb

**Expected behavior**
An updated keeweb.

(Manjaro at the moment uses libsass `3.5.4`)

**Screenshots**

**Environment**
n/a

**Kdbx File**

n/a

**Logs**

```
Warning: cannot resolve "libsass>=3.5.5", a dependency of "keeweb"
Failed to prepare transaction.
Failed to prepare transaction:
could not satisfy dependencies:
unable to satisfy dependency 'libsass>=3.5.5' required by keeweb
```

**Comment by antelle** [comment]
Hi! This is not an official package.
