### ISSUE TITLE
DB-specific information lost when upgrading from 1.7.5 to 1.7.7

### ISSUE THREAD

**Issue by Coises** [keeweb/keeweb#1110]
I use two webdav databases with KeeWeb on Windows 7. When I installed 1.7.7 over the top of 1.7.5, KeeWeb lost its memory of both databases. Nothing showed in the list of recently-used databases, and I had to reenter both the webdav information and the automatic backup settings.

Nothing on the General Settings page was lost, just the database-specific information.

This did not happen with previous upgrades. I presume it is unexpected. (If it is expected for this release only, it would be good to put a warning in the release notes.)

**Comment by antelle** [comment]
It's unexpected, normally this shouldn't happen. This release actually does't have anything special regarding this, let's see what happens after next update.

**Comment by Coises** [comment]
I can't rule out that it might have been an anomaly on my system. Unfortunately, it would be a significant pain in the butt to restore from backup to some point before the upgrade and try to repeat it.

When the next update comes, is there anything I should do before upgrading that would help to diagnose this if it turns out that it does happen again?

**Comment by antelle** [comment]
It would be interesting to understand what happened to the config. Last files are stored in `~/AppData/KeeWeb/file-info.json`. Somehow it was erased during the update, not sure why. 
How did you update it: downloaded new version or used the update button in KeeWeb?

**Comment by Coises** [comment]
I downloaded the new version. (I like to keep an archive of everything I've installed.)

I have a copy of `file-info.json` from a system snapshot taken around 12 hours before I upgraded. Except for file ids and access times, it looks, superficially, to be the same as the file that's there now (after I've already re-entered the db-specific information). I don't have a copy from just after the upgrade, before I re-entered the information.

I remember one thing about the progress log during the upgrade. Following the first line — something like `KeeWeb is not running.` — the second line said, `Copy failed.` I seem to remember that in previous upgrades too, though.

**Comment by antelle** [comment]
Looks like it's an installer issue, I'll try to check it. You can also install new versions with app updates, it should be also faster.

**Comment by Coises** [comment]
I just installed 1.7.8 over 1.7.7; same method, downloading and running the installer rather than using the in-app updater.

This time, everything worked as expected.  (The `Copy failed.` line was still there; unfortunately, the details which display during installation disappear without action when installation is complete, so I couldn't see any way to copy them.)  Database names, webdav login information and automatic backup settings were retained.

I'm guessing this was just one of those unexplained occurrences that never will be explained, since it didn't repeat.  Unless someone else thinks there's still a problem here, I think this can be closed.

**Comment by antelle** [comment]
That's weird, I thought that message was somewhat related. Thanks for your efforts trying to reproduce this!  
Please let me know if it happens again.
