### ISSUE TITLE
Onedrive Business Error Using Self-Hosting gh-pages

### ISSUE THREAD

**Issue by jmbarneck** [keeweb/keeweb#1112]
**Describe the bug**
Error when attempting to connect Keeweb app to onedrive

Started with:
git clone -b gh-pages --single-branch https://github.com/keeweb/keeweb.git ./

**To Reproduce**

1. Go to self-hosted URL
2. Click on "New"
3. Enter Password
4. Click Save to...
5. Select Onedrive
6. Enter Onedrive Personal Credentials
7. Get error "Unable to complete request" (see screenshot)

**Expected behavior**
Connect to Onedrive

**Screenshots**
Attached

**Environment**
Your user-agent (from Settings/Help section)

**Kdbx File**
Does it happen on Demo or New database? New
If you have a test db without your personal data, please attach it.

**Logs**
Please open dev tools in your browser and attach output log from Console tab. If you are using a desktop app, devtools can be opened from Settings/General/Advanced.

Creating Application Cache with manifest https://gigabit.com/pm/manifest.appcache
(index):1 Application Cache Checking event
(index):1 Application Cache Downloading event
(index):12 2019-02-12T05:10:40.766Z [app] Started in 861ms ¯\_(ツ)_/¯
(index):1 Application Cache Progress event (0 of 1) https://gigabit.com/pm/index.html
(index):1 Application Cache Error event: Resource fetch failed (2) https://gigabit.com/pm/index.html
(index):12 2019-02-12T05:11:08.049Z [storage-onedrive] OAuth: popup opened

![onedrive_business](https://user-images.githubusercontent.com/40224881/52613141-094cda80-2e4a-11e9-9326-0a10d2386854.JPG)

**Comment by antelle** [comment]
Hi! Have you changed onedrive client id?

**Comment by antelle** [comment]
Well, I see, it's not changed. Unfortunately there's no guide for oneDrive, but you can do it in the same way as for Google, Dropbox, etc...: https://github.com/keeweb/keeweb/wiki/Dropbox-and-GDrive
The config variable name is `onedriveClientId`
