### ISSUE TITLE
Show real root group name

### ISSUE THREAD

**Issue by DervishD** [keeweb/keeweb#1113]
Root group is always named as the filename, and since in `kdbx` format the root group can have an actual name, IMHO it should be shown.

Issue #771 requested that and also being able to rename root group, and it was closed because not being able to rename is by design, leaving the second part of the issue (showing the real name of the root group) without a solution.

Could it be possible to show this name, please. I think it makes the user interface clearer, because the same name (the file name, actually) is shown at the bottom and at the root group...

Thanks a lot for KeeWeb, by the way ;)

KeeWeb v1.7.7 (4ca2eb4c, 2019-02-09)
Environment: web
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.96 Safari/537.36

**Comment by antelle** [comment]
Hi! This is by design, we always show the file name instead of top group name to avoid extra complexity and mental load.

**Comment by DervishD** [comment]
No problem then, and thanks for explaining this. I thought that not being able to rename the root group was by design but not showing the name was unintentional. If it's by design, no problem 👍 :)
