### ISSUE TITLE
Database name is not shown anywhere in the user interface

### ISSUE THREAD

**Issue by DervishD** [keeweb/keeweb#1114]
At the bottom of the user interface, next to the padlock icon, the filename of the active database is shown, but not the database name.

I think it would be very useful to see the actual database name, specially coming from using a desktop KeePass application.

Thanks again for KeeWeb :)

KeeWeb v1.7.7 (4ca2eb4c, 2019-02-09)
Environment: web
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.96 Safari/537.36

**Comment by antelle** [comment]
Hi! Same as #1113, we intentionally ignore file name, otherwise it can be quite complicated to understand what's going on and we need additional (unnecessary) controls for displaying this.

**Comment by DervishD** [comment]
Again, thanks for explaining. I don't agree that showing the database name would make things more complicated to understand for users, as it's the user the one who chose the name, but if it's by design I respect the decision even if I don't share it.
What I completely understand and agree is the need for additional controls, which adds complexity to the code, so no problem there 👍
