### ISSUE TITLE
[Feature request]: add a setting/toggle to not show entries from subfolders/subgroups

### ISSUE THREAD

**Issue by grossetti** [keeweb/keeweb#1116]
When I click on a folder/group it shows me all entries including those from subfolders/subgroups; this partially defeats the purpose of subfolders/subgroups. For example:

Suppose we have this:

root/entry1
root/group1/entry2
root/group1/subgroup1/entry3
root/group1/subgroup2/entry4
root/group2/entry5

Currently:
 - selecting "root" will show you "entry1, entry2, entry3, entry4, entry5"
 - selecting "root/group1" will show you "entry2, entry3, entry4"
 - selecting "root/group2" will show you "entry5"

I would like : 
 - selecting "root" will show you "entry1"
 - selecting "root/group1" will show you "entry2"
 - selecting "root/group1/subgroup1" will show you "entry3"
 - selecting "root/group1/subgroup2" will show you "entry4"
 - selecting "root/group2" will show you "entry5"

Personally I would like the subfolder/subgroup keys to not show when you click on the parent folder/group by default, but I assume some people may like the current behaviour. So the most sensible thing is to add a configuration setting or a toggle button somewhere to let the user choose his/her preferred behaviour.

**Comment by antelle** [comment]
Hi! It already exists, is that what you're looking for? 

<img width="582" alt="untitled" src="https://user-images.githubusercontent.com/633557/53053031-96261280-34a0-11e9-91b0-6059b90234c4.png">

**Comment by antelle** [comment]
Looks like everything is already there. Please reopen if I understood it wrong.

**Comment by grossetti** [comment]
Hi Antelle, yes this is it! I can't believe I did not see that option, thanks!
