### ISSUE TITLE
[Question] Login and user-based database

### ISSUE THREAD

**Issue by DualBandWiFi** [keeweb/keeweb#1117]
Hello there, I've been watching the repo for a week and really like the project, it's amazing!

I'm gonna host myself, to start the transition from paper to server-based password administration, and the ceo of where I work liked more KeeWeb against KeePass.

How I'm supposed to set-up KeePass for final users? I've read on the net about YunoHost or similar, the end goal it's to have a login and after logging in showing the passwords, similar to how KeePass will work once installed (asks for the db password, and opens it.)

Was thinking on some kind of Auth using .htaccess but I'm not really sure which option would the best.

Any help would be greatly appreciated, and thanks again for such an awesome project.

**Comment by antelle** [comment]
Hi! Most likely you should set up webdav server and add a json config: https://github.com/keeweb/keeweb/wiki/Configuration#json-app-config. Then keeweb will be opened with your file already pre-filled and you will be able to save files to WebDav.
These examples can be also useful: https://github.com/keeweb/keeweb/wiki/WebDAV-Config
