### ISSUE TITLE
Corrupted DB

### ISSUE THREAD

**Issue by davazlan** [keeweb/keeweb#1118]
**Describe the bug**
My kbdx file appears to be corrupted after opening it with KeeWeb (webapp). I can still open it with the webapp; however, Keepass2Android, portable Keepass (windows), keeweb (Desktop v. 1.6.3) and KeepasX say that the file is corrupted and can't be opened.

**To Reproduce**
1. Open the kbdx file with the KeeWeb Webapp and edit it
2. Open the same kbdx file with any of the mentioned Keepass apps

**Expected behavior**
The kbdx file should be compatible with all keepass implementations

**Screenshots**
![image](https://user-images.githubusercontent.com/41060273/53182681-49eee580-35fa-11e9-9fa7-18e8301b51de.png)

**Environment**
Keeweb Web:
KeeWeb v1.7.7 (4ca2eb4c, 2019-02-09)
Environment: web
User-Agent: Mozilla/5.0 (Windows NT 10.0; WOW64; rv:60.0) Gecko/20100101 Firefox/60.0

Keeweb Desktop:
KeeWeb v1.6.3 (cded8a4, 2017-12-11)
Environment: electron v1.7.9
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) KeeWeb/1.6.3 Chrome/58.0.3029.110 Electron/1.7.9 Safari/537.36

Keepass2Android: 
version 1.06f

**Kdbx File**
It happens on an existing database I've been using for a while

**Logs**
[INFO ] 2019-02-21T16:08:36.730Z [open:pdb] Open file from content loaded from storage
[ERROR] 2019-02-21T16:08:36.775Z [file] Error opening file InvalidKey Error InvalidKey: invalid key KdbxError: Error InvalidKey: invalid key
[ERROR] 2019-02-21T16:08:36.776Z [open-view] Error opening file KdbxError: Error InvalidKey: invalid key

**Comment by antelle** [comment]
Hi! Does it repeat on a new file created this way? If so, please attach it. There’s something in your file which makes us generate broken output, but it won’t be possible to understand without the file itself.

**Comment by antelle** [comment]
I'm sorry to say, I have to close this. Without an example we won't be able to fix it. If you would like to spend some time on reproducing the issue, please let me know, I'll explain how to test it (this will take about one-two hours of your time).

**Comment by davazlan** [comment]
Hi,

No worries, I was not able to reproduce it anyway. Thanks!
