### ISSUE TITLE
[Feature request] Templates

### ISSUE THREAD

**Issue by justinkelly** [keeweb/keeweb#112]
Firstly - amazing work @antelle !!!!

Secondly - is it possible to support entry templates?
- in a similar manner to LastPass note types - refer image below

So i can have a Credit card template, server template, membership etc.. so we don't have to manually added the fields each time

![lastpass](http://i.imgur.com/vR1gxbv.png)

Cheers

Justin

**Comment by antelle** [comment]
Entry templates are planned but not for nearest future. There's a lot of work to make them usable. I'm still thinking about better usability and compatibility with keepass format.

**Comment by justinkelly** [comment]
thanks for the update @antelle

**Comment by antelle** [comment]
I'll reopen it, to help users find this issue and let know that the feature request exists and fill be fixed.

**Comment by antelle** [comment]
Deployed to [beta.keeweb.info](https://beta.keeweb.info), will be available in the next release.
Please let me know if you find any issue with it.
