### ISSUE TITLE
Keyboard navigation is getting slower and slower

### ISSUE THREAD

**Issue by dploeger** [keeweb/keeweb#1124]
**Describe the bug**
This is mainly a reminder, to further try and reproduce the bug. I believe, that when the app is opened for some time (noticed it on the desktop version) keyboard navigation (at least the database selection using arrows in the lock screen) is becoming painfully slow.

It's hard to analyze because it doesn't happen directly only after some time as it seems.

**To Reproduce**
I'm not completely done, analyzing this, but:
1. Open the app
2. Keep it running for about a day and let it lock itself
3. Use Autotype
4. Try to select a database from the lock screen using arrow keys

**Expected behavior**
The databases can be switched without a delay.

**Environment**
KeeWeb v1.7.7 (4ca2eb4c, 2019-02-09)
Environment: electron v4.0.1
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_2) AppleWebKit/537.36 (KHTML, like Gecko) KeeWeb/1.7.1 Chrome/69.0.3497.106 Electron/4.0.1 Safari/537.36

**Logs**
I've opened the console when this happens, but no logs are shown when a key is pressed.

**Comment by ramonreschke** [comment]
+1 also experiencing this issue. 
same version and also nothing interesting in the logs

**Comment by antelle** [comment]
Interesting, I'll try to reproduce as well.

**Comment by dzek69** [comment]
This happens not only on lock screen, but on unlocked screen as well. Switching between items with arrow keys hangs the app for around 10-15 seconds.

**Comment by antelle** [comment]
I can repeat it, that's good. I'll try to reproduce it on a dev build and see what it is.

**Comment by antelle** [comment]
I think I found it.
223827ad760e58606132e8471045b7a16b29f504 introduced a [listener](https://github.com/keeweb/keeweb/blob/4ca2eb4c0e294e95e674ff2c0515c86998b970c4/app/scripts/views/open-view.js#L70), which is not removed on destroy, so when the app goes into background, it gets instantiated crazy amount of times and everything gets slow.

I've fixed it, but unfortunately the js profiler, as well as heap analyzer, crashes in Electron for some reason, so I need an additional day to validate my hypothesis. If it helps, a fix is coming soon.

**Comment by antelle** [comment]
Looks like that was it. Please reopen if it happens on v1.7.8.

**Comment by dploeger** [comment]
Whoops. I made that commit. Sorry. Thanks for fixing it so quick!

**Comment by antelle** [comment]
no worries, it happens ¯\\\_(ツ)\_/¯
next version (it I manage to finish it) will have better designed event subscriptions, so that it's harder to forget about it.

**Comment by ddotlic** [comment]
> Whoops. I made that commit. Sorry. Thanks for fixing it so quick!

🤣 this is pure gold, you opening an issue that you inadvertently caused 😉 

Anyway, this issue was annoying me to no end, seems to be _much, much_ faster now.

**Comment by ddotlic** [comment]
@antelle I don't think that this is entirely fixed.

In my case, repro is simple but takes time: run the desktop app, let it open for a day or so. Unlock, type something in the search box, then try to use arrows up/down to navigate the list. It's **very** slow and the first CPU core (sometimes second two) shortly spike with the activity.

How can I help you debug this?

**Comment by dploeger** [comment]
@ddotlic Are you on 1.7.8? I haven't seen this behaviour in 1.7.8 anymore.

**Comment by ddotlic** [comment]
When I say "let it open" I mean simply don't close the app, just let it stay running in a locked state. Concretely, I restarted the app (in beta mode, but should not change anything) last night around 6 PM, used just a few times, locked, laptop was in sleep mode all night as usual, this morning around 9AM when I used the app I experienced the keyboard slowdown.

**Comment by ddotlic** [comment]
@dploeger I'm on a current beta.

**Comment by dploeger** [comment]
@antelle Does the beta include your fix?

**Comment by ddotlic** [comment]
@dploeger Was just wondering about the same thing. If the beta is issued from a different branch, that'd explain the discrepancy. I'd go back to mainline, but I like the ranked search _so much_ 😉

**Comment by antelle** [comment]
I would suggest trying it on the release version, bate can be somewhat different

**Comment by ddotlic** [comment]
@antelle Release worked like a charm. So this is just a FYI - let's not let this fix fall through the cracks.

**Comment by antelle** [comment]
Merged changed into beta, now it should be up-to-date.
