### ISSUE TITLE
Feature Request: Add Shortcut for showing password when key is pressed

### ISSUE THREAD

**Issue by ramonreschke** [keeweb/keeweb#1125]
It is a bit inconvenient in KeeWeb to show a password for example to another user. The current possibility is to click on the password and go into the editing password. If I do that, I'll risk to change the password.

It would be nice to have an shortcut like pressing the `ALT` key to show the password. During the keypress the password will be shown, if the keypress ends the password will be hidden again.

**Comment by joaopms** [comment]
I don't know if you're talking about an entry password or the master password, but both would be nice!

**Comment by antelle** [comment]
Deployed to [beta.keeweb.info](https://beta.keeweb.info), will be available in the next release.

<img width="307" alt="Screen Shot 2019-09-26 at 23 45 40" src="https://user-images.githubusercontent.com/633557/65727391-e65cf700-e0b7-11e9-9c64-d5531c751ce9.png">
