### ISSUE TITLE
WebDAV sync method "put temporary and move" stalls

### ISSUE THREAD

**Issue by aclex** [keeweb/keeweb#1129]
I use key file on WebDAV (the same domain, as keeweb is self-hosted), saving, opening and syncing with PUT work flawlessly, but when using sync via PUTting temporary and then MOVE it stalls forever.

Here's Firefox network log:
```
304 HEAD wallet.kdbx keeweb.local xhr octet-stream 0 b → 6 ms
304 HEAD wallet.kdbx keeweb.local xhr octet-stream 0 b → 1 ms
201 PUT .wallet.kdbx.1551741898117 keeweb.local xhr xml 2,67 Kb 0 b → 2 ms
304 HEAD wallet.kdbx keeweb.local xhr octet-stream 0 b → 1 ms
```

and no MOVE at all.

Nginx log reads the same:
```
192.168.1.2 - - [05/Mar/2019:02:27:50 +0300] "HEAD /wallet/wallet.kdbx HTTP/1.1" 304 0 "https://keeweb.local/" "Mozilla/5.0 (X11; Linux x86_64; rv:63.0) Gecko/20100101 Firefox/63.0"
192.168.1.2 - - [05/Mar/2019:02:27:50 +0300] "HEAD /wallet/wallet.kdbx HTTP/1.1" 304 0 "https://keeweb.local/" "Mozilla/5.0 (X11; Linux x86_64; rv:63.0) Gecko/20100101 Firefox/63.0"
192.168.1.2 - - [05/Mar/2019:02:27:51 +0300] "PUT /wallet/.wallet.kdbx.1551742067341 HTTP/1.1" 201 0 "https://keeweb.local/" "Mozilla/5.0 (X11; Linux x86_64; rv:63.0) Gecko/20100101 Firefox/63.0"
192.168.1.2 - - [05/Mar/2019:02:27:51 +0300] "HEAD /wallet/wallet.kdbx HTTP/1.1" 304 0 "https://keeweb.local/" "Mozilla/5.0 (X11; Linux x86_64; rv:63.0) Gecko/20100101 Firefox/63.0"
```

Console prints the only error message:
```
TypeError: Cannot convert string to ByteString because the character at index 45 has value 1082 which is greater than 255. keeweb.local:12:200668
```

The file seems to be obfuscated, so it's so hard to find the exact string for me.

1. Use "PUT temporary and then MOVE" WebDAV syncronization method (the default).
2. Change something in the key file to trigger sync.
3. Notice the eternal "loading" rotating arrows.

One particular moment is that I use Cyrillic filename instead of "wallet" here (replaced it with wallet in the logs to preserve readability, as it appears to be URL-encoded as `%D0%BA%D0%BE%D1%88%D0%B5%D0%BB%D1%91%D0%BA` — "Кошелёк").

I just use alternative PUT sync method without any problems, but decided to report an issue. The HTML is the most fresh `gh-pages` branch clone at the moment.

**Comment by antelle** [comment]
Hi! Probably it doesn't work with such file names.

**Comment by aclex** [comment]
@antelle Oh, indeed, just tried with Latin filename, works just fine.

**Comment by antelle** [comment]
How did you add this file to KeeWeb: URL-encoded or as is?

**Comment by aclex** [comment]
I created it in KeeWeb and stored to WebDAV at once with the original (Cyrillic) name. Then I just made changes and noticed, that synchronization stalls. And yes, doing just the same sequence with Latin filename work fine.

**Comment by antelle** [comment]
Does it work if you add it url-encoded?

**Comment by aclex** [comment]
Yes, it works as well. The file is in fact created with proper Cyrillic name.

**Comment by antelle** [comment]
So, everything works as expected in this case? I.e. The file is displayed with a proper name in KeeWeb, it can be saved, opened, and so on?

**Comment by aclex** [comment]
I've just checked, yes, it appears to be so. I can even open it using original name, without URL-encoding, and then it still synchronized properly. So the key moment is to save it the first time using URL-encoded filename — when saving with original non-Latin name, the saving is fine, synchronization with "PUT temporary and MOVE" stalls. Have just reproduced it with fresh file to be sure.

**Comment by antelle** [comment]
The bot was misconfigured, sorry for a wrong notification.

**Comment by aclex** [comment]
Nice, thank you very much for the fix and taking care of it!
