### ISSUE TITLE
Arrow down up lagging

### ISSUE THREAD

**Issue by KonradHolubek** [keeweb/keeweb#1130]
**Describe the bug**
Keeweb is lagging and sometimes stops responding when I try to navigate my entries by hitting the down (and up) arrow

**To Reproduce**
1. Go to an entry
2. Click on down arrow
4. lag (and sometimes app stops responding)

**Expected behavior**
no lag

**Screenshots**

**Environment**
Keeweb : 1.7.7
Computer : Mac, Mojave 10.14.3

**Kdbx File**
Does it happen on Demo or New database?  
If you have a test db without your personal data, please attach it.

**Comment by antelle** [comment]
this is fixed in 1.7.8
