### ISSUE TITLE
Fingerprint unlock using the phone

### ISSUE THREAD

**Issue by aroumeliotis** [keeweb/keeweb#1132]
The idea is to take advantage of the fingerprint sensor that exists on almost every modern phone today.  I know it sounds a bit complicated and maybe a bit far fetched, but would be nice to hear your opinion. Would also require developement of an android/ios app just for this cause...

The desktop app could send a request to a listening server on the phone side and if it gets the ok, then it unlocks the database and fills the username/pass fields.

This android app implements something kinda similar for windows. Well not really similar, but implements the idea of using the phones fingerprint sensor to access the pc.
https://play.google.com/store/apps/details?id=ro.andreimircius.remotefingerauth

**Comment by Xavier-Plasma** [comment]
Maybe it is related to the discussion on this issue: https://github.com/keeweb/keeweb/issues/534

**Comment by antelle** [comment]
Yes, mobile version is discussed in that ticket, thanks @Xavier-Plasma

**Comment by KaKi87** [comment]
Hello there,

Authenticating using Android's unlock features (fingerptint/pin/schema/whatever) is now possible.

Please consider looking at the [PublicKeyCredential](https://developer.mozilla.org/en-US/docs/Web/API/PublicKeyCredential) API.

Thanks

**Comment by antelle** [comment]
This is a part of WebAuthN, it's not very useful without a server verifying credentials, so we won't be able to use it.

**Comment by KaKi87** [comment]
You have a server.

**Comment by antelle** [comment]
No we don't, and we won't. The idea of KeeWeb is to operate fully in browser, without a need to send anything over network apart from static files.
