### ISSUE TITLE
Add instructions to use OneDrive on self-hosted installs to the wiki

### ISSUE THREAD

**Issue by jaden** [keeweb/keeweb#1133]
It would be helpful to add instructions for adding OneDrive support for a self-hosted Keeweb instance. Could these steps be added to the wiki page for Google Drive and Dropbox?

1. Create an app at https://apps.dev.microsoft.com/#/appList
1. Name it
1. Add the "Web" Platform
1. Add the root of your site as the redirect URL
1. Add the following permissions: `Files.Read.All`, `Files.ReadWrite.All`, `Directory.Read.All`
1. Add the root of your site as the home page URL
1. Save
1. Copy the `Application Id` value and place it in KeeWeb's `config.json` under the key `onedriveClientId`

**Comment by antelle** [comment]
Thanks, done: https://github.com/keeweb/keeweb/wiki/Dropbox-and-GDrive#onedrive
(unfortunately it's not possible to submit a PR to wiki, that's a pity)
