### ISSUE TITLE
WebDAV sync

### ISSUE THREAD

**Issue by Harlihop** [keeweb/keeweb#1139]
**Describe the bug**
I cannot sync the Webdav to my KeeWeb client. So, I installed a CentOS 7 server with apache.
I am trying to make a WebDAV with the keys in it along with a web client of KeeWeb. I followerd every steps of the WebDav kiki and I get the same error again and again, no matter what...
I'm not very experienced, I don't have all of the ropes yet, thank you for your help ! :)

**To Reproduce**

**Expected behavior**
Be able to sync 

**Screenshots**
![image](https://user-images.githubusercontent.com/48350824/54439463-1f93d200-4739-11e9-8bdd-2a741bf3a3e9.png)

**Kdbx File**
Brand New kdbx database.

**Logs**
`172.19.16.203 - - [15/Mar/2019:15:30:28 +0100] "PUT /webdav/.New.kdbx.1552660228195 HTTP/1.1" 405 251
172.19.16.203 - - [15/Mar/2019:15:30:42 +0100] "HEAD /webdav/New.kdbx HTTP/1.1" 200 -
172.19.16.203 - - [15/Mar/2019:15:30:42 +0100] "HEAD /webdav/New.kdbx HTTP/1.1" 200 -
172.19.16.203 - - [15/Mar/2019:15:30:42 +0100] "PUT /webdav/.New.kdbx.1552660242289 HTTP/1.1" 405 251
172.19.16.203 - - [15/Mar/2019:15:30:42 +0100] "HEAD /webdav/New.kdbx HTTP/1.1" 200 -
172.19.16.203 - - [15/Mar/2019:15:30:42 +0100] "HEAD /webdav/New.kdbx HTTP/1.1" 200 -
172.19.16.203 - - [15/Mar/2019:15:30:42 +0100] "PUT /webdav/.New.kdbx.1552660242982 HTTP/1.1" 405 251
172.19.16.203 - - [15/Mar/2019:15:30:43 +0100] "HEAD /webdav/New.kdbx HTTP/1.1" 200 -
172.19.16.203 - - [15/Mar/2019:15:30:43 +0100] "HEAD /webdav/New.kdbx HTTP/1.1" 200 -
172.19.16.203 - - [15/Mar/2019:15:30:43 +0100] "PUT /webdav/.New.kdbx.1552660243364 HTTP/1.1" 405 251
172.19.16.203 - - [15/Mar/2019:15:33:02 +0100] "GET / HTTP/1.1" 200 1355679
172.19.16.203 - - [15/Mar/2019:15:33:04 +0100] "HEAD /webdav/New.kdbx HTTP/1.1" 200 -
172.19.16.203 - - [15/Mar/2019:15:33:05 +0100] "HEAD /webdav/New.kdbx HTTP/1.1" 200 -
172.19.16.203 - - [15/Mar/2019:15:33:05 +0100] "PUT /webdav/.New.kdbx.1552660385031 HTTP/1.1" 405 251

`

**Comment by antelle** [comment]
Hi! PUT returns 405, so sync doesn't work.

**Comment by Harlihop** [comment]
Hey, thanks for the response, but this is the only thing I already knew, I can't find why PUT returns 405, I've allowed OPTIONS PUT GET... almost every http request is allowed...

**Comment by antelle** [comment]
Probably server logs can give a hint about it.

**Comment by antelle** [comment]
On the server

**Comment by Harlihop** [comment]
Do you have even a vague idea of where to look ? The server logs don't tell me much about where is the problem, only that it's he PUT request involved.

**Comment by antelle** [comment]
Google it, something like how to allow write access for webdan in $server_name

**Comment by Harlihop** [comment]
My webdav.conf looks like this, almost every post from google I found said to make it like that :

DavLockDB /var/www/example.com/html/DavLock
<VirtualHost *:80>
	ServerAdmin webmaster@localhost
    DocumentRoot /var/www/example.com/html/webdav/
    ErrorLog /var/log/httpd/error.log
    CustomLog /var/log/httpd/access.log combined
    Alias /webdav /var/www/example.com/html/webdav

	RewriteEngine on
	RewriteCond %{REQUEST_METHOD} OPTIONS
	RewriteRule ^(.*)$ blank.html [R=200,L,E=HTTP_ORIGIN:%{HTTP:ORIGIN}]

    <Directory /var/www/example.com/html/webdav>
        DAV On
        AuthType Basic
        AuthName "webdav"
		AuthBasicProvider file
        AuthUserFile /etc/httpd/.htpasswd
        Require valid-user
		
		Options Indexes
		Header always set Access-Control-Allow-Origin "*"
		Header always set Access-Control-Allow-Headers "origin, content-type, cache-control, accept, authorization, if-match, destination, overwrite"
		Header always set Access-Control-Expose-Headers "ETag"
		Header always set Access-Control-Allow-Methods "GET, HEAD, POST, PUT, OPTIONS, MOVE, DELETE, COPY, LOCK, UNLOCK"
		Header always set Access-Control-Allow-Credentials "true"

    </Directory>

</VirtualHost>

**Comment by return42** [comment]
What does `/var/log/httpd/error.log` say?

Check read/write access of folder

     ls -la  /var/www/example.com/html/webdav

**Comment by Harlihop** [comment]
Here's the log :

```
172.19.16.203 - - [18/Mar/2019:08:06:56 +0100] "GET / HTTP/1.1" 200 1355679
172.19.16.203 - - [18/Mar/2019:08:07:04 +0100] "GET / HTTP/1.1" 200 1355679
172.19.16.203 - - [18/Mar/2019:08:07:06 +0100] "GET /icons/favicon-32x32.png HTTP/1.1" 404 221
172.19.16.203 - - [18/Mar/2019:08:07:07 +0100] "GET /icons/favicon-16x16.png HTTP/1.1" 404 221
172.19.16.203 - - [18/Mar/2019:08:07:10 +0100] "GET /manifest.appcache HTTP/1.1" 200 83
172.19.16.203 - - [18/Mar/2019:08:07:10 +0100] "GET /index.html HTTP/1.1" 200 1355679
172.19.16.203 - - [18/Mar/2019:08:24:32 +0100] "HEAD /webdav/New.kdbx HTTP/1.1" 200 -
172.19.16.203 - - [18/Mar/2019:08:24:33 +0100] "HEAD /webdav/New.kdbx HTTP/1.1" 200 -
172.19.16.203 - - [18/Mar/2019:08:24:33 +0100] "PUT /webdav/.New.kdbx.1552893873046 HTTP/1.1" 405 251
172.19.16.203 - - [18/Mar/2019:08:24:35 +0100] "HEAD /webdav/New.kdbx HTTP/1.1" 200 -
172.19.16.203 - - [18/Mar/2019:08:24:35 +0100] "HEAD /webdav/New.kdbx HTTP/1.1" 200 -
172.19.16.203 - - [18/Mar/2019:08:24:35 +0100] "PUT /webdav/.New.kdbx.1552893875362 HTTP/1.1" 405 251
172.19.16.203 - - [18/Mar/2019:08:24:36 +0100] "HEAD /webdav/New.kdbx HTTP/1.1" 200 -
172.19.16.203 - - [18/Mar/2019:08:24:36 +0100] "HEAD /webdav/New.kdbx HTTP/1.1" 200 -
172.19.16.203 - - [18/Mar/2019:08:24:36 +0100] "PUT /webdav/.New.kdbx.1552893876267 HTTP/1.1" 405 251
172.19.16.203 - - [18/Mar/2019:08:25:38 +0100] "HEAD /webdav/New.kdbx HTTP/1.1" 200 -
172.19.16.203 - - [18/Mar/2019:08:25:38 +0100] "HEAD /webdav/New.kdbx HTTP/1.1" 200 -
172.19.16.203 - - [18/Mar/2019:08:25:38 +0100] "PUT /webdav/.New.kdbx.1552893938075 HTTP/1.1" 405 251
172.19.16.203 - - [18/Mar/2019:08:25:38 +0100] "HEAD /webdav/New.kdbx HTTP/1.1" 200 -
172.19.16.203 - - [18/Mar/2019:08:25:38 +0100] "HEAD /webdav/New.kdbx HTTP/1.1" 200 -
172.19.16.203 - - [18/Mar/2019:08:25:38 +0100] "PUT /webdav/.New.kdbx.1552893938436 HTTP/1.1" 405 251
172.19.16.203 - - [18/Mar/2019:08:25:38 +0100] "HEAD /webdav/New.kdbx HTTP/1.1" 200 -
172.19.16.203 - - [18/Mar/2019:08:25:38 +0100] "HEAD /webdav/New.kdbx HTTP/1.1" 200 -
172.19.16.203 - - [18/Mar/2019:08:25:38 +0100] "PUT /webdav/.New.kdbx.1552893938657 HTTP/1.1" 405 251
172.19.16.203 - - [18/Mar/2019:08:25:38 +0100] "HEAD /webdav/New.kdbx HTTP/1.1" 200 -
172.19.16.203 - - [18/Mar/2019:08:25:38 +0100] "HEAD /webdav/New.kdbx HTTP/1.1" 200 -
172.19.16.203 - - [18/Mar/2019:08:25:38 +0100] "PUT /webdav/.New.kdbx.1552893938849 HTTP/1.1" 405 251
172.19.16.203 - - [18/Mar/2019:08:25:38 +0100] "HEAD /webdav/New.kdbx HTTP/1.1" 200 -
172.19.16.203 - - [18/Mar/2019:08:25:38 +0100] "HEAD /webdav/New.kdbx HTTP/1.1" 200 -
172.19.16.203 - - [18/Mar/2019:08:25:38 +0100] "PUT /webdav/.New.kdbx.1552893939006 HTTP/1.1" 405 251
172.19.16.203 - - [18/Mar/2019:08:25:39 +0100] "HEAD /webdav/New.kdbx HTTP/1.1" 200 -
172.19.16.203 - - [18/Mar/2019:08:25:39 +0100] "HEAD /webdav/New.kdbx HTTP/1.1" 200 -
172.19.16.203 - - [18/Mar/2019:08:25:39 +0100] "PUT /webdav/.New.kdbx.1552893939173 HTTP/1.1" 405 251
172.19.16.203 - - [18/Mar/2019:08:25:39 +0100] "HEAD /webdav/New.kdbx HTTP/1.1" 200 -
172.19.16.203 - - [18/Mar/2019:08:25:39 +0100] "HEAD /webdav/New.kdbx HTTP/1.1" 200 -
172.19.16.203 - - [18/Mar/2019:08:25:39 +0100] "PUT /webdav/.New.kdbx.1552893939342 HTTP/1.1" 405 251
172.19.16.203 - - [18/Mar/2019:08:25:39 +0100] "HEAD /webdav/New.kdbx HTTP/1.1" 200 -
172.19.16.203 - - [18/Mar/2019:08:25:39 +0100] "HEAD /webdav/New.kdbx HTTP/1.1" 200 -
172.19.16.203 - - [18/Mar/2019:08:25:39 +0100] "PUT /webdav/.New.kdbx.1552893939527 HTTP/1.1" 405 251
172.19.16.203 - - [18/Mar/2019:08:25:39 +0100] "HEAD /webdav/New.kdbx HTTP/1.1" 200 -
172.19.16.203 - - [18/Mar/2019:08:25:39 +0100] "HEAD /webdav/New.kdbx HTTP/1.1" 200 -
172.19.16.203 - - [18/Mar/2019:08:25:39 +0100] "PUT /webdav/.New.kdbx.1552893939787 HTTP/1.1" 405 251
```



And the permissions :

![2019-03-18_08h44_00](https://user-images.githubusercontent.com/48350824/54514352-3402e500-495a-11e9-9294-ad2673de7245.png)

**Comment by return42** [comment]
The log looks good to me, but it is old?! Can't see the 405 in. Seems the wrong log.
For what is `DavLockDB /var/www/example.com/html/DavLock` good?
I see `rwx` is given to ..., so I guess your apache service user is  `apache`.

**Comment by Harlihop** [comment]
The DavLock came straight from the recommended configuration from the KeeWeb Wiki, with some digging, I found out this : 

```
[Mon Mar 18 08:55:38.875426 2019] [ssl:warn] [pid 8431] AH01909: RSA certificate configured for "servername" does NOT include an ID which matches the server name
[Mon Mar 18 08:55:38.899581 2019] [ssl:warn] [pid 8431] AH01909: RSA certificate configured for "servername" does NOT include an ID which matches the server name
```

I'm gonna look into it and come back to you if it doesn't work out.

**Comment by return42** [comment]
> The DavLock came straight from the recommended configuration from the KeeWeb Wiki

does it? Can't see it on https://github.com/keeweb/keeweb/wiki/WebDAV-Config

**Comment by Harlihop** [comment]
It wasn't the source of the problem :')

You are right, i must have found it on another tuto. sorry for the confusion.

I fixed it and  restarted of the service

```
[Mon Mar 18 09:11:32.172243 2019] [mpm_prefork:notice] [pid 5746] AH00170: caught SIGWINCH, shutting down gracefully
[Mon Mar 18 09:11:33.241322 2019] [suexec:notice] [pid 6345] AH01232: suEXEC mechanism enabled (wrapper: /usr/sbin/suexec)
[Mon Mar 18 09:11:33.242189 2019] [ssl:warn] [pid 6345] AH01916: Init: (frmtpkwb.orchestra.net:443) You configured HTTP(80) on the standard HTTPS(443) port!
[Mon Mar 18 09:11:33.263723 2019] [auth_digest:notice] [pid 6345] AH01757: generating secret for digest authentication ...
[Mon Mar 18 09:11:33.264372 2019] [lbmethod_heartbeat:notice] [pid 6345] AH02282: No slotmem from mod_heartmonitor
[Mon Mar 18 09:11:33.265098 2019] [ssl:warn] [pid 6345] AH01916: Init: (frmtpkwb.orchestra.net:443) You configured HTTP(80) on the standard HTTPS(443) port!
[Mon Mar 18 09:11:33.269144 2019] [mpm_prefork:notice] [pid 6345] AH00163: Apache/2.4.6 (CentOS) OpenSSL/1.0.2k-fips configured -- resuming normal operations
[Mon Mar 18 09:11:33.269170 2019] [core:notice] [pid 6345] AH00094: Command line: '/usr/sbin/httpd -D FOREGROUND'
```
