### ISSUE TITLE
Dropbox OAUTH with security fob does not work on desktop

### ISSUE THREAD

**Issue by roninkenji** [keeweb/keeweb#1140]
**Describe the bug**
Unable to link Dropbox account top the desktop application.
OAUTH window just closes after logging in without prompting for Security token, or authenticator app/SMS OTP. 

**To Reproduce**
On a fresh install
1. Go to 'More'
2. Click on 'Dropbox'
3. Fill out the login details in the popup window and submit
4. popup window just closes

**Expected behavior**
Login to dropbox by prompting for a 2FA mechanism (similar to google drive)

**Logs**
[DEBUG] 2019-03-16T13:37:18.051Z [storage-dropbox] List
[DEBUG] 2019-03-16T13:37:18.052Z [storage-dropbox] OAuth: popup opened
[DEBUG] 2019-03-16T13:38:01.519Z [popup-notifier] did-fail-load {"sender":{"history":["https://www.dropbox.com/oauth2/authorize?client_id=eor7hvv6u6oslq9&scope=&response_type=token&redirect_uri=https%3A%2F%2Fapp.keeweb.info"],"currentIndex":0,"pendingIndex":-1,"inPageIndex":-1,"_events":{"will-navigate":[null,null]},"_eventsCount":23,"_maxListeners":0,"browserWindowOptions":{"show":false,"webPreferences":{"nodeIntegration":false,"webSecurity":false,"allowDisplayingInsecureContent":true,"allowRunningInsecureContent":true},"width":600,"height":400,"y":480.5,"x":772}}} -20 ERR_BLOCKED_BY_CLIENT chrome-extension://kmendfapggjehodndflmmgagdbamhnfd/u2f-comms.html false
[ERROR] 2019-03-16T13:38:01.850Z [storage-dropbox] OAuth error popup closed

**Comment by antelle** [comment]
Hi,
In desktop you can also open files directly from the filesystem, from the Dropbox folder.

**Comment by buranik** [comment]
Same problem with me on Mac. I have two similar Macs, Dropbox window shows up on one Mac, and automatically closes on the second one.

**Comment by buranik** [comment]
> Hi,
> In desktop you can also open files directly from the filesystem, from the Dropbox folder.

This doesn't work if Dropbox is prohibited in your corporate network.

**Comment by antelle** [comment]
The bot was misconfigured, sorry for a wrong notification.

**Comment by vbadiuc** [comment]
I had the same issue. After updating to the new version [v1.12.3](https://github.com/keeweb/keeweb/releases/tag/v1.12.3), seems like it's not happening anymore. 
Could you @roninkenji try again?

**Comment by roninkenji** [comment]
Seems to be working now... Closing the issue.
