### ISSUE TITLE
Add a submit button in login form for mobile screens

### ISSUE THREAD

**Issue by gsportelli** [keeweb/keeweb#1142]
**Is your feature request related to a problem? Please describe.**
When I access the app from Safari on my iPhone and use the fingerprint-enabled password autofill, the keyboard hides and leaves me with the login form with the password filled in. To submit the password, I have to reopen the keyboard by clicking on the password input field and then press enter (see screen below).

This is a bit frustrating because the keyboard takes a second to reopen. It is not a big deal, but I think that the solution is very simple.

**Describe the solution you'd like**
Add an "Access" or "OK" or "Open" button below the password field, at least when in mobile screens.

![image](https://user-images.githubusercontent.com/3187799/54666358-d69d9e00-4ae9-11e9-9593-01e1d9457986.png)

**Comment by antelle** [comment]
Makes sense for mobile, when the password is auto-completed, right

**Comment by gsportelli** [comment]
Just wanted to report that in v. 1.12.3 I see the submit button on my iPad but not on my iPhone.

**Comment by antelle** [comment]
Deployed to [beta.keeweb.info](https://beta.keeweb.info), will be available in the next release.
<img width="285" alt="Screen Shot 2020-03-15 at 13 02 56" src="https://user-images.githubusercontent.com/633557/76701002-56d6ef00-66bd-11ea-91be-054e7de44e84.png">
