### ISSUE TITLE
installer issue on mac

### ISSUE THREAD

**Issue by CoderJason123** [keeweb/keeweb#1143]
this is not an issue but a question- please.  On the mac, what exactly is the installer app?  It is not a pkg file, but an embedded app.

What type of installer are you using, it's not clear to me at least.  Thank you kindly.

**Comment by antelle** [comment]
Hi,
You mean, "KeeWeb Installer", which is started when you launch KeeWeb for the first time? It's a special app that runs as root and changes permissions of /Applications/KeeWeb.app.
