### ISSUE TITLE
Admin & User account

### ISSUE THREAD

**Issue by TristanCrudeli** [keeweb/keeweb#1144]
I would found love if KeeWeb can have an admin & user password,

You can share the admin password and this grants write privileges.
In case of you share the user password only read privileges are available !

I hope use this feature for my Google drive keeweb !

**Comment by antelle** [comment]
Hi! It won't be possible to do, the kdbx format is not designed to support multiple users with different access rights.

**Comment by cognitivedj** [comment]
Antelle-- 

I would also like an admin/user (RW/RO) into the KeeWeb interface, but present this request as more of a front end usability feature than it is a security feature.

In a small group, we share the keepass password.  A user can easily click on an item and accidentally type in it when they think they are on another screen.  Or even worse: accidentally delete an entry.  Keeweb may screenlock and many hours later or even the next business day, the user may then eventually save their session with the bad data.  (We have autosave turned off to help against bad data getting back).

I'm OK with leveraging kdbx for the one user gets all the access limitation.  If one of our trusted users wants to use keepass (or a different keepass app) to modify all the entries and upload it back to the file repo, they are really looking to do harm and we can protect against this in other ways.

So, I'm looking at this request as more of a "sudo" sanity for an admin account.  I guess you take it one step further into a keeweb specific feature--Having a "keewebrw" user that has an encrypted hash as the password entry.  Keeweb would check against that hash for a second password for it to go into RW mode.  

If you did decide on implementing this feature, then keeweb should notify the user it is setup for RO or in RW mode, by having some type of notification in keeweb that it is in elevated or non elevated status--color changes, banner, etc.

**Comment by antelle** [comment]
@cognitivedj what you describe here, is a readonly mode, not admin/user feature. In your case I would solve it with different webdav users:

1. admin account, which can read/write
2. user account, which is read-only

In this case, even if they save something, it won't work (hoever the UI will go crazy about this, but it's easy to restore). Additionally the UI can switch to read-only mode if a file is opened as read-only, this would make sense. However it's a bit different from what's described in the feature.
