### ISSUE TITLE
Network Error

### ISSUE THREAD

**Issue by DavideFranchioni** [keeweb/keeweb#1149]
Hello,

I'm having Network Error on my self-host KeeWeb:
![image](https://user-images.githubusercontent.com/48943584/54981879-b4a09180-4fa9-11e9-8990-35989b672096.png)
That are the network information showed in Chrome:
![image](https://user-images.githubusercontent.com/48943584/54981910-c84bf800-4fa9-11e9-9d34-12bee96d399e.png)
![image](https://user-images.githubusercontent.com/48943584/54981921-ceda6f80-4fa9-11e9-8a98-e1e8c004b412.png)

I'm try to open my password DB using WebDav protocol but i have found this issues.
I have downloaded the windows client and i was able to open my password DB from WebDav.
I have tried to open the DB from my WebDav server( is a SME one (storage made easy server)) using your public KeeWeb UI but i get the same issues.
But as i said with windows client all works fine.
It look like CORS is enable on my SME server this is the basic test that i do:
`[root@keeweb ~]# curl --user 'user:password' --head https://webdav.it/Database/pwd.kdbx
HTTP/1.1 200 OK
Date: Tue, 26 Mar 2019 07:56:47 GMT
Server: Apache
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Strict-Transport-Security: max-age=15768000
Vary: Authorization
Last-Modified: Mon, 25 Mar 2019 16:30:59 GMT
ETag: "3dd252827dea41b3198d47ad48097c3a"
Content-Type: application/octet-stream
`
That are the log showed from KeeWeb UI about WebDav connection:
`[DEBUG] 2019-03-26T07:51:45.538Z [storage-webdav] Stat https://pws.kdbx
[DEBUG] 2019-03-26T07:51:46.164Z [storage-webdav] Stat error https://pwd.kdbx 626ms`

Could Someone help me with that ?

Thank you in advanced,
Best Regards,
Davide.

**Comment by antelle** [comment]
Hi OPTIONS request returns 401, that’s why it fails. If you change it, it will probably work.

**Comment by DavideFranchioni** [comment]
Hello Antelle,

As you can see the curl return a 200.
So was the curl not ok to test the CORS?
Is there another way to manual test it?

Thank you in advanced,
Best Regards,
Davide.

**Comment by antelle** [comment]
If you make a curl with OPTIONS, it will also return 401.
