### ISSUE TITLE
search not filtering results after keyboard input when auto type has no real result [linux]

### ISSUE THREAD

**Issue by benzkji** [keeweb/keeweb#1152]
**Describe the bug**
alt-shift-t for autotype, no results found to autotype. keeweb gets focus. when typing/searching for my record, the search field on the top right gets filled, but the resultset doesnt change, always remains the full set.

**To Reproduce**
see above.

**Expected behavior**
when typing/filling the search field, the resultlist should change

**Environment**
Mozilla 5.0 (X11; Linux x86_64) AppleWebKid 537.36  ... like Gecko
Keeweb 1.8.0 Chrome 69.0.3497.103 Electron 4.0.1 Safari 537.36

**Kdbx File**
probably not the issue.

**Logs**
How to copy paste from the logs?!!
At least I dont see any "search/filtering" specific log entries, and also no errors.

**Comment by dploeger** [comment]
There are actually no logs show up in the developer tools when the error occurs. The search simply gets ignored.

**Comment by dploeger** [comment]
Found it. @antelle Please have a look at the pull request and push out a minor release. This is really annoying. Thanks! 😄

**Comment by antelle** [comment]
Will merge it this week and make an update indeed, thanks a lot! 🎁

**Comment by antelle** [comment]
Done
