### ISSUE TITLE
WebDav MOVE Destination Header

### ISSUE THREAD

**Issue by hei-pa** [keeweb/keeweb#1154]
**Describe the bug**
WebDav Move Destination Header should be relative

**To Reproduce**
Setup a reverse proxy with https and forward the request to the keeweb backend (http)
The WebDav MOVE Destination will be set to `https://...`
This cannot be processed because the backend (http) requires starting the destination header url with `http://...` otherwise it will not find the destination and refuses with Bad Request 400

**Expected behavior**
The destination header should be set relativ to /
Then the protocol or any rewrites/proxy manipulations will not affect this mechanism.

**Comment by antelle** [comment]
The bot was misconfigured, sorry for a wrong notification.
