### ISSUE TITLE
Network error opening database

### ISSUE THREAD

**Issue by auchri** [keeweb/keeweb#1156]
**Describe the bug**
When I want to open the database, I get a network error:
![image](https://user-images.githubusercontent.com/5092164/55855465-e39d3280-5b67-11e9-8a68-87a3c2de591a.png)

Looking at the http requests, I can see that the request is blocked by csp:
![image](https://user-images.githubusercontent.com/5092164/55855494-fd3e7a00-5b67-11e9-84e1-af7ddac2a765.png)

**To Reproduce**
1. Go to the database
2. Click on the database
3. Enter the database password

**Expected behavior**
Database should open

**Environment**
Nextcloud 14.0.3

**Comment by antelle** [comment]
Hi! Looks like should change your CSP. Keeweb itself doesn’t have csp, it’s added on top of it.

**Comment by Nick0278** [comment]
how can i do this?

**Comment by antelle** [comment]
@Nick0278 depends. You commented on an ancient issue, now we do have a strict CSP.

**Comment by Nick0278** [comment]
> @Nick0278 depends. You commented on an ancient issue, now we do have a strict CSP.

Ok I'll create a new thread
