### ISSUE TITLE
[Plugin idea] WebDAV all-in-one authentication

### ISSUE THREAD

**Issue by vfabioux** [keeweb/keeweb#1157]
Hi,

Right now you need two passwords to access your database :
- A password with read/write access to the kbdx storage (Google Drive, Dropbox, a private server...).
- A master password to decipher the kbdx file.

If you remove the first password, anyone can delete or corrupt the kbdx file, which is something you don't want (even though they cannot decipher the file).

The purpose of this plugin is to use only the master password to access your database while keeping it safe from griefers. Here is my proposal on how it would work with WebDAV:

## On the server
There are two files:
- db.kbdx : contains all your passwords. Can be deciphered using _masterpassword_.
- auth.kbdx : contain only one password : _authpassword_. Can also be deciphered using _masterpassword_.

There are also two WebDAV users:
- user: _public_, password: none. Has read access to auth.kbdx.
- user: _auth_, password: _authpassword_. Has read/write access to db.kbdx and auth.kbdx.

## On the client
- You enter your _masterpassword_ into the password field and press Enter.
- The client gets auth.kbdx which is publicly accessible and tries to decipher it using _masterpassword_.
- If successfull, the client takes _authpassword_ from that file.
- The client now gets the db.kbdx file as user: _auth_ and password: _authpassword_ and deciphers it using _masterpassword_.
- Done, you now have access to your database!

## Is it secure?
If your database is secure (meaning your password entropy is high enough to ensure someone who has access to the file cannot decipher it), then it is secure. Anyone can download auth.kbdx, but deciphering auth.kbdx will not be easier than deciphering db.kbdx.

Your server also only knows about _authpassword_ but has never access to _masterpassword_ in case someone installs malicious software.

## Are there alternatives?
Yes:
- _authpassword_ could be stored directly into db.kbdx which would eliminate the need for auth.kbdx. The upside is that the client would only need to decipher one file. The downside is that anyone could download db.kbdx and see your database size at any given time (and from there find out when you add entries). I think the time gained from not reading an almost empty kbdx file is not worth that downside.
- _masterpassword_ could be hashed on the client side and used as _authpassword_. The thing is, if hashing is slower than deciphering then this is useless. And if hashing is faster than deciphering, then it is less resilient against brute-force attacks.

## Should it be a base keeweb feature?
In my opinion, no. I think we should keep the basic WebDAV feature as it is, because this proposal adds a lot of configuration on the server side and the whole back and forth authentification thing could be confusing for newcomers.

I also think one of the most important feature of this plugin will be to handle multiple users on the same server. And this would bring even more configuration, options and UI changes which may not be accepted by everyone.

## Can you develop this plugin?
Maybe.

But first I would like to know your opinion about this proposal:
- Is it secure enough? I'm no security expert, maybe I forgot something important.
- Can it be done with the api keeweb offers to plugins? My main concern is the password field: can a plugin access its content?

Thanks for reading.

**Comment by antelle** [comment]
Hi! Excellent explanation!
But isn't one of alternatives similar to how it works now?

When you open a db via WebDAV, the webdav password is saved and encrypted with your master password in browser storage. Then, after you've opened the db, we use this WebDAV password to sync it.

**Comment by vfabioux** [comment]
Thanks for the quick answer!

I actually had no idea that the WebDAV password was encrypted using the master password. I though it stored some kind of authentication token which would have allowed anyone accessing the device to erase or corrupt the files. Now I know I don't need to clear everything after logging on someone else computer. Is it also the case for Google Drive and Dropbox? I think this is a feature worth mentionning on the front page since a lot of people I know like to nuke their friend's computer after they log into them.

As for the plugin, I still see some use cases where it could be usefull:
- For people constantly browsing in incognito mode who have to type the WebDAV password again.
- For people using the same device 99% of the time who are very likely to forget the WebDAV password.

But it's too much configuration for very small benefits.

I think the only way to make it worth would be to make it a feature of a multi-users plugin. There would be no need to create the db.kbdx and auth.kbdx and configure all the permissions manually. Everything would be done automatically when creating a new user from the admin account.

**Comment by antelle** [comment]
Clearing everything after you load a kdbx on a shared computer is actually a good habit. There may be traces of logs, file parts, caches, etc... left. The files themselves are cached. This won't give access to the contents of the file as is, but can provide some metadata (e.g. last access date, file size, storage path, and so on), which can be used later for social engineering and other attacks.
For Google Drive and Dropbox we're using access tokens, they're stored in plaintext.
Ok, I see, looks like we already have one of suggested variants implemented and we can close the issue. Multi-user access is a bit different story.
