### ISSUE TITLE
kdbxweb errors during npm install

### ISSUE THREAD

**Issue by emyarod** [keeweb/keeweb#1161]
When running `npm install`, I receive this error message:

```
npm ERR! Could not install from "node_modules/kdbxweb/pako@github:keeweb/pako#653c0b00d8941c89d09ed4546d2179001ec44efc" as it does not contain a package.json file.
```

**To Reproduce**
1. clone from branch `develop`
2. `npm install` from repository root

**Expected behavior**

**Screenshots**

**Environment**

OS: macOS 10.14.4
node version: 11.13.0
npm version: 6.7.0

**Comment by antelle** [comment]
merged this
