### ISSUE TITLE
Install on Ubuntu 19.04 Fails

### ISSUE THREAD

**Issue by Gabb1995** [keeweb/keeweb#1163]
**Describe the bug**
Installing .deb package fails on Ubuntu 19.04

**To Reproduce**
1. run sudo dpkg -i KeeWeb-1.8.1.linux.x64.deb
2. See error

**Expected behavior**
Installs successfuly

**Screenshots**
![Screenshot from 2019-04-22 09:21:44](https://user-images.githubusercontent.com/20728259/56488875-10dece80-64e0-11e9-8179-e6ca234ba787.png)

**Environment**
Ubuntu 19.04

**Logs**
```
Selecting previously unselected package keeweb-desktop.
(Reading database ... 322952 files and directories currently installed.)
Preparing to unpack KeeWeb-1.8.1.linux.x64.deb ...
Unpacking keeweb-desktop (1.8.1-1) ...
dpkg: dependency problems prevent configuration of keeweb-desktop:
 keeweb-desktop depends on libgconf2-4; however:
  Package libgconf2-4 is not installed.

dpkg: error processing package keeweb-desktop (--install):
 dependency problems - leaving unconfigured
Processing triggers for gnome-menus (3.32.0-1ubuntu1) ...
Processing triggers for desktop-file-utils (0.23-4ubuntu1) ...
Processing triggers for bamfdaemon (0.5.3+18.04.20180207.2-0ubuntu1) ...
Rebuilding /usr/share/applications/bamf-2.index...
Processing triggers for mime-support (3.60ubuntu1) ...
Processing triggers for shared-mime-info (1.10-1) ...
Processing triggers for hicolor-icon-theme (0.17-2) ...
Errors were encountered while processing:
 keeweb-desktop
```

**Comment by antelle** [comment]
Hi! Someone reported a similar issue via email recently. Do you know if changing the dependency from `libgconf2-4` to `libgconf-2-4` will fix this?

**Comment by Gabb1995** [comment]
Just tried it and it did fix it yes.

**Comment by antelle** [comment]
Good, thanks, I'll download ubuntu 19 today and will make a new release if it works there.

**Comment by antelle** [comment]
Checked it, published a new release with the fix.
