### ISSUE TITLE
[New Feature] Double Click to Username or Password

### ISSUE THREAD

**Issue by Leboubou111** [keeweb/keeweb#1164]
On KeePass I like double click to username or password for copy and minimize keepass to paste entry behind window.
Could you report this feature on KeeWeb ?

**Comment by antelle** [comment]
Should be a plugin.

**Comment by antelle** [comment]
So, now it's possible to do this, let's close this issue.

![](https://user-images.githubusercontent.com/633557/65727444-0987a680-e0b8-11e9-9da6-e2e5220e9c1e.png)

**Comment by Leboubou111** [comment]
Sorry for this long time.
It's not really this case that was mentioned.
I'm talking about minimizing window when I click on "user" or "password" field.

**Comment by antelle** [comment]
Auto-type will minimize it

**Comment by Leboubou111** [comment]
Yes, but you will need to click on the item, look password field, click on the small icon on the right side and select "Auto-type".
This is not easy to use.
Into KeePass, just to click on Username or Password field (no need to open it), KeePass copy item on clipboard and minimize window to return on the window need it... Left's to paste it. Simple and fast.

**Comment by antelle** [comment]
Most likely we should come up with better auto-type hotkeys, but it needs some thinking.

**Comment by Leboubou111** [comment]
For this moment, could you add just a feature (in option ?) to minimize keeweb's window after clicking to user or password flied ?
And, another feature... minimize window after databases locking...

Keeweb has a great UX/UI than keepas and I like how it easy to change databases.

**Comment by antelle** [comment]
No, that's not a good solution.

**Comment by Leboubou111** [comment]
Huummm, I'm a bad dev.
Thanks for your replys @antelle

**Comment by antelle** [comment]
Added #1460 to think about it, since this issue is closed and most likely will be forgotten.

**Comment by Leboubou111** [comment]
Thanks @antelle 
In my case, I look to create a plugin. I'm a webdev and I know some jQuery functions.
I'll try to integrate some windows commands with JS.

Necessarily, I'll create a new issue.

**Comment by antelle** [comment]
So, at the moment I added a feature that will auto-type the selected field on double-click, it will come in v1.15. Since it makes single clicks slow, it's behind a feature which is disabled by default. Most likely in future there should be a pop-up that appears when you press the shortcut, but it can be together with this feature as well.

**Comment by Leboubou111** [comment]
Thank for this @antelle 
After a month of use, I think it just misses the fact of reducing the window when you click on "user" or "password" shortcut.
