### ISSUE TITLE
Auto save and sync does't work by time interval

### ISSUE THREAD

**Issue by andreasbica** [keeweb/keeweb#1165]
Auto save and sync does't work by time interval on macOS app.

**To Reproduce**
1. Go to Settings
2. Scroll to Function
3. Set "Automatically save and sync periodically" > Every 1 minute(s)
4. Check the last sync date !!!

**Comment by antelle** [comment]
Hi! Are there changes in your file? It won't sync if there are no changes.

**Comment by andreasbica** [comment]
Yes, there are changes !

**Comment by andreasbica** [comment]
It save when I click active > "cmd + s".

**Comment by antelle** [comment]
Weird. Could you please paste logs while it's open and a minute passed, maybe there was an error?

**Comment by andreasbica** [comment]
Hm! Now it was done ... I watched the last sync date, and the sync does't work ... now works fine! I'm sorry for my mistake !

**Comment by andreasbica** [comment]
But, the Nextcloud Plug-In sync right to the internal storage! Or, where did it synced?

**Comment by andreasbica** [comment]
Oha, you save my password plain in the log file. This is not cool :(

`
[INFO ] 2019-04-22T19:48:07.557Z [app] Started in 2256ms ¯\_(ツ)_/¯
[INFO ] 2019-04-22T19:48:15.437Z [open:passwords] File open request
[INFO ] 2019-04-22T19:48:15.437Z [open:passwords] Open file from cache as main storage
[DEBUG] 2019-04-22T19:48:15.437Z [storage-cache] Load ff53c6b5-936b-7f83-4c71-26b069813287
[DEBUG] 2019-04-22T19:48:15.446Z [storage-cache] Loaded ff53c6b5-936b-7f83-4c71-26b069813287 3ms
[INFO ] 2019-04-22T19:48:15.446Z [open:passwords] Loaded file from cache null
[INFO ] 2019-04-22T19:48:15.533Z [file] Opened file passwords: 87ms, 12 rounds, 72 kB
[DEBUG] 2019-04-22T19:48:15.534Z [app] Add last open file ff53c6b5-936b-7f83-4c71-26b069813287 passwords null null null
[INFO ] 2019-04-22T19:51:18.862Z [sync:passwords] Sync started webdav Passwords/passwords.kdbx {"storage":"webdav","path":"Passwords/passwords.kdbx","opts":{"user":"...","password":"..."},"startedByUser":true}
[INFO ] 2019-04-22T19:51:18.863Z [sync:passwords] Stat file
[DEBUG] 2019-04-22T19:51:18.864Z [storage-webdav] Stat Passwords/passwords.kdbx
[DEBUG] 2019-04-22T19:51:19.463Z [storage-webdav] Stat error Passwords/passwords.kdbx no headers 600ms
[INFO ] 2019-04-22T19:51:19.464Z [sync:passwords] Stat error, not dirty No Last-Modified header
[INFO ] 2019-04-22T19:51:19.464Z [sync:passwords] Sync finished No Last-Modified header
`

**Comment by andreasbica** [comment]
One thing... in my local network I use http. Only from outside my network I use https. Maybe is this a problem ...

**Comment by antelle** [comment]
I'm not familiar with nextcloud integration, not sure where it syncs by default. The nextcloud part is developed here, in a separate project: https://github.com/jhass/nextcloud-keeweb. Ok, looks like it's solved now. Thanks for opening a separate issue about passwords in logs!
