### ISSUE TITLE
WebDAV password saved plain in log file

### ISSUE THREAD

**Issue by andreasbica** [keeweb/keeweb#1166]
`[INFO ] 2019-04-22T19:51:18.862Z [sync:passwords] Sync started webdav passwords.kdbx {"storage":"webdav","path":"passwords.kdbx","opts":{"user":"...","password":"..."},"startedByUser":true}`

Plain user is ok, but not the password.

**Comment by antelle** [comment]
Logs are not saved anywhere, but we should indeed remove it from there.
