### ISSUE TITLE
KeeWeb.app for iOS ?!

### ISSUE THREAD

**Issue by andreasbica** [keeweb/keeweb#1167]
Hi, is the macOS app also planned for iOS?
The macOS app is a perfect 1Password replacement!

---
Hi, ist die macOS app auch geplant für iOS ?
Die macOS-App finde ich einen perfekten 1Password Ersatz!

**Comment by antelle** [comment]
Hi,
The native iOS app unfortunately requires too much effort. You can use MiniKeePass (abandoned), or add KeeWeb to the iPhone homescreen: https://twitter.com/kee_web/status/1112368677494710272 (some features are not supported, e.g. password management integration). So far I haven't found any free app that would provide good enough experience for using KeePass on iOS 😢

**Comment by andreasbica** [comment]
Hi, thx for all informations 👍🏼

Can I trust jhass and his implementation?!
He does’t save any password plain in his logs or server anywhere?
Via app.keeweb.info you save any passwords plain on your server?

Sorry, this questions are realy important !!!

No iOS nativ app? Okay, this is sad, because I will change entries in the kdbx file and the app save this changes back to the Nextcloud Directory.

I hope y understand what I meen...

Von meinem iPad gesendet

**Comment by antelle** [comment]
I haven't audited their implementation. Most likely it's ok. But you never know for sure.
app.keeweb.info doesn't save anything, apart from encrypted file content to Dropbox, Google Drive, etc... But again, you never know for sure. If this concerns you, you can download the index.html file, put it to your server, and protect it with a proper CSP, then you know for sure that it won't be able to send anything anywhere.
I understand the pain of not having an iOS app, new ios password management integration is quite handy and living without it takes some additional time finding and copy-pasting passwords (also security issues regarding copy-pasting). Not sure what to do with it though, we won't be able to develop it. Maybe someone else would like to pick up minikeepass and make it live again?

**Comment by andreasbica** [comment]
Thanks for your insurance!

Now, I can change the kdbx File directly in Nextcloud on my iOS Browser (Safari).
That works fine.

But, I can't use your KeeWebApp or my Nextcloud to copy User/Password and paste it in 
a website! Because, your KeeWebApp or my Nextcloud will always refresh the site and I
must enter my Master-Password again.

This is not practicable :(

The only way, develop a nativ iOS App as like on macOS.
Hmmm. this is an unfavorable position ...

I hope it finds itself still a solution ...

**Comment by antelle** [comment]
Hm, strange, it shouldn’t refresh like this. Does it also refresh if you, for example, open a demo file? Maybe your file consumes too much memory and it makes the tab refresh?

**Comment by andreasbica** [comment]
It refresh also by the demo file. It refresh always :(
that is the Problem! My PwdFile has 75 KB ... the memory should't be the problem ...

**Comment by andreasbica** [comment]
Ha! It works with Cliqz Broweser for iOS .... yeah ! Apple is just getting worse, and worse. But this is a workaround, not a solution ;)

**Comment by antelle** [comment]
Interesting, when does it refresh? When you switch tabs? It doesn't do it for me in Safari.

**Comment by andreasbica** [comment]
When I switch apps and Safari "Tabs". I have activated the private mode in Safari! Maybe this is the reason ...

**Comment by andreasbica** [comment]
It would be nice or ingenious if even after 3 seconds automatic can be stored.Sometimes 1 minute is too long to save.

**Comment by antelle** [comment]
Most likely private mode is what causing this.  
You can click Close (the icon in the right bottom corner), then it will save immediately.

**Comment by andreasbica** [comment]
The button in the right corner, is the button to leave this password file ... either I can save explicit or (for comfort) it save automaticly by setting (3 secs, 30 secs, 1 min., ...) this would be nice :)

**Comment by andreasbica** [comment]
Okay, the private mode in Safari is it not :(

**Comment by antelle** [comment]
Very strange, something is wrong here. For me, it doesn't reload in Safari even after an hour.

**Comment by antelle** [comment]
Which iOS version is it?

**Comment by andreasbica** [comment]
It is iOS 12.1 (16B92)
