### ISSUE TITLE
Sync kdbx with Nextcloud.app

### ISSUE THREAD

**Issue by andreasbica** [keeweb/keeweb#1168]
I have already installed the Nextcloud App on iOS. I will open a kdbx File with a native KeeWeb.app for iOS (Future?) and the KeeWeb.app sync changes back to the directory of Nextcloud.

I think, this is a great step foreward to sync passwords without Dropbox and 1Password.

**Comment by antelle** [comment]
Hi! There's a [nextcloud-keeweb](https://github.com/jhass/nextcloud-keeweb) project that provides better nextcloud integration support, perhaps using the web version on iOS can give the sync experience too.
