### ISSUE TITLE
Not able to partially copy from fields

### ISSUE THREAD

**Issue by gynet** [keeweb/keeweb#1169]
Just realized keeweb does not able to copy string from the fields unless click on the filed name. If I  select and hit ctrl+c on on of the words in the note field, when I paste it, it does not work. Is this by design to lock down the copying?

**Comment by antelle** [comment]
It's not supposed to be like that, thanks, it's a bug.

**Comment by harshlele** [comment]
Not sure if i understood it correctly, but just selecting some/all words in a field and pressing Ctrl + C does work for me. (I'm on Ubuntu 18.04)

**Comment by gynet** [comment]
seems working on Mac now with latest version, not try windows yet

**Comment by gynet** [comment]
it happens on Windows 10 randomly.

**Comment by antelle** [comment]
Deployed to [beta.keeweb.info](https://beta.keeweb.info), will be available in the next release.
