### ISSUE TITLE
WebAssembly is not supported

### ISSUE THREAD

**Issue by jb911** [keeweb/keeweb#1170]
Hello,

I use the Keeweb v1.7.8 (014264d1, 2019-03-02)
Keeweb seems not to work with Safari on Ipad 4 :(. I get the message : "WebAssembly is not supported".

**Comment by antelle** [comment]
Hi,
Which iOS version is that?

**Comment by jb911** [comment]
iOS version 10.3.3

**Comment by antelle** [comment]
That's two versions ago, already not supported.
