### ISSUE TITLE
Check for Updates not visible on Linux Mint 19.1

### ISSUE THREAD

**Issue by rohit-s8** [keeweb/keeweb#1171]
The Check for updates section is completely missing when I installed via the debian package https://github.com/keeweb/keeweb/releases/download/v1.8.2/KeeWeb-1.8.2.linux.x64.deb. Found it in the General settings section when I downloaded the zip archive https://github.com/keeweb/keeweb/releases/download/v1.8.2/KeeWeb-1.8.2.linux.x64.zip.

**Comment by antelle** [comment]
Right, the auto-updater are disabled when the app installed from deb.

**Comment by antelle** [comment]
I don't remember why though. Found this ticket: https://github.com/keeweb/keeweb/issues/78, but it's a bit different thing.

**Comment by rohit-s8** [comment]
Hmmm I see. I guess resolving #141 should resolve this as well.

**Comment by FranklinYu** [comment]
Most (if not all) Linux distributions expect applications not to update itself. For Ubuntu, PPA is the right way.
