### ISSUE TITLE
Two Channel Auto Type Obfuscation

### ISSUE THREAD

**Issue by rohit-s8** [keeweb/keeweb#1173]
IMHO having TCATO as in [KeePass2](https://keepass.info/help/v2/autotype_obfuscation.html) might be a better way to go as it would make it faster by avoiding many kestrokes (#616) and would probably not cause it to crash on linux desktop app as in #708 as xdotool seems to be receiving bad values whenever obfuscation is set to on at the moment.

**Comment by antelle** [comment]
We're using a similar thing, it's not clear what is the proposed change.
It's faster in keepass, because it's using a native module instead of an external program, eventually we should implement this too.

**Comment by rohit-s8** [comment]
What KeePass claims to do is split the the entry into two parts and copies the first part to the clipboard which is then pasted into the search field. And subsequently inserts the characters of the second part into the field. From what i understand KeeWeb does (using pykeylogger) is that it does not perform this splitting. So in principle one could simply re-run the logged sequence of keys to get the final output (which i did manage to do). And I also believed it would solve the aforementioned issues as well. Again this just in IMO. Would you agree?

**Comment by antelle** [comment]
No, keeweb also copies parts of passwords into clipboard and pastes them, it's performed [here](https://github.com/keeweb/keeweb/blob/master/app/scripts/auto-type/auto-type-obfuscator.js#L122). There are two copy-paste operations maximum. You can try it: log the keystrokes using a keylogger and then play them. You will discover that you will get a different password as the result.
