### ISSUE TITLE
single fixed hard-coded key file

### ISSUE THREAD

**Issue by ignucius** [keeweb/keeweb#1176]
hi

i would like to alter the code so that the user has no possibility to load external keepass files and is presented with the password field of a hard-coded keepass file. like when you click on the "demo" icon but with a password. and that keepass file should be in the same location as the keeweb script.

where do i have to look for such an adjustment?

cheers

**Comment by antelle** [comment]
Hi,
You should provide a config with a default file for this and disable certain options.

https://github.com/keeweb/keeweb/wiki/Configuration#json-app-config
