### ISSUE TITLE
password is not correct when i chosed Backups

### ISSUE THREAD

**Issue by luckydogM** [keeweb/keeweb#1177]
first: creat a new project and set a master password  and exit ,this app run normal
![dmeo](https://user-images.githubusercontent.com/28353897/57565930-b529a600-73f8-11e9-9ec3-129a415750b3.gif)

and when i chosed the Backups item , and backup right now ,then  exit 

this time i can not open the project , and i can sure the password is absolutely correct;

why this happened , and how can i used it correctly

**Comment by antelle** [comment]
Hi!
Apart from making a backup, you added a keyfile to your kdbx, which means that only password is not enough to open it. To be able to open it, you need to select the keyfile you generated.
