### ISSUE TITLE
Uppercase accented characters autotyped as lowercase

### ISSUE THREAD

**Issue by WylieYYYY** [keeweb/keeweb#1183]
**Describe the bug**
Autotype correctly type English alphabet with upper and lowercase, and symbols such as [², ¬, ×]. But typed passwords with uppercase accented character such as [Ø, È] as lower equivalent [ø, è]

**To Reproduce**
1. Go to any input field
2. Press Shift+Alt+T and select a password profile
3. Press Enter or Ctrl+Enter

**Expected behavior**
Password of [mH^Q5OÁiu/O{ñ7Y(] becomes [mH^Q5Oáiu/O{ñ7Y(] (Á to á)

**Environment**
System: Arch Linux (5.1.4-arch1-1-ARCH)
Package Manager: Installed from AUR (yay)
xdotool explicitly installed from Pacman

**Kdbx File**
DB file and details are stored correctly

**Logs**
[INFO ] 2019-05-25T11:25:20.902Z [launcher] spawn xdotool: 0, 23ms
[DEBUG] 2019-05-25T11:25:20.902Z [auto-type] Complete 1973ms
[DEBUG] 2019-05-25T11:28:23.554Z [auto-type] Auto type event null
[DEBUG] 2019-05-25T11:28:23.565Z [auto-type] Get window title
[INFO ] 2019-05-25T11:28:23.592Z [launcher] spawn xdotool: 0, 27ms
*Untitled 1 - Mousepad
[DEBUG] 2019-05-25T11:28:23.593Z [auto-type] Window title *Untitled 1 - Mousepad null
[DEBUG] 2019-05-25T11:28:25.097Z [auto-type] Entry selected {"entry":{"id":"88f4341e-c3b3-fcec-beef-cceb922f409b:SXWueSyoa/bxs36IdDKVMg==","uuid":"SXWueSyoa/bxs36IdDKVMg=="},"sequenceType":0}
[DEBUG] 2019-05-25T11:28:25.104Z [auto-type] Hide window
[DEBUG] 2019-05-25T11:28:25.221Z [auto-type] Start {USERNAME}{TAB}{PASSWORD}{ENTER}
[DEBUG] 2019-05-25T11:28:25.221Z [auto-type] Parsed [op:USERNAME,op:TAB,op:PASSWORD,op:ENTER]
[DEBUG] 2019-05-25T11:28:25.223Z [auto-type] Resolved [*************************,key:tab,[*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*],key:enter]
[INFO ] 2019-05-25T11:28:25.644Z [launcher] spawn xdotool: 0, 421ms

**Comment by antelle** [comment]
May be fixed in v1.17

**Comment by WylieYYYY** [comment]
1.17 has indeed fixed the issue. Thank you very much!

**Comment by antelle** [comment]
Awesome, thank you!
