### ISSUE TITLE
Broken field names when adding a new credit card

### ISSUE THREAD

**Issue by dbogdanov** [keeweb/keeweb#1184]
**Describe the bug**
The field names aren't properly visualized (see the screenshot) when adding a new credit card. 

**To Reproduce**
Add a new Credit Card record

**Expected behavior**
User-friendly field names.

**Screenshots**
![Screen Shot 2019-05-26 at 01 33 47](https://user-images.githubusercontent.com/409668/58375599-dccf5100-7f56-11e9-93a3-ea8239cdd79f.png)

**Environment**
Using the desktop app on MacOS (KeeWeb v1.8.2)
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6)

**Comment by antelle** [comment]
Hi! Please describe how you "add a new credit card".
It's not possible that these fields appear by themselves, it should be some sort of plugin.

**Comment by dbogdanov** [comment]
"Add New" --> "Credit Card"
That's strange, as my only plugins installed are Keewebhttp and Haveibeenpwned

**Comment by antelle** [comment]
This thing comes from templates.
Most likely the file was created in keepass and this template was added by some plugin there. If you modify your template, field names will change accordingly.

**Comment by dbogdanov** [comment]
Thank you for this information! Where can I modify templates?

**Comment by antelle** [comment]
There's a folder with templates somewhere in your file. In keeweb it's not customizable and it's always called "Templates". In keepass it can be changed, I would suggest checking there.
Please keep in mind that if you change the template, the plugin that created it might stop working.

**Comment by lastranikos** [comment]
There was update of this feature?
