### ISSUE TITLE
Custom Interface 

### ISSUE THREAD

**Issue by RustinCassiem** [keeweb/keeweb#1185]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. 

I would like 
![Capture](https://user-images.githubusercontent.com/38912152/58457263-86b10800-8126-11e9-9d46-478b33c86da9.PNG)

I liked this system with one drive so that all the passwords are stored on a database for now however we would like to add it to a server and have a custom IP/https, can I have a detailed description on how I may accomplish this, also I used https://github.com/keeweb/keeweb/wiki/Configuration to try to fix my problem however this only made it worse    

**Describe the solution you'd like**
I want to add a custom IP also I don't want my users to see anything else but this and an entre button 

**Describe alternatives you've considered**
Messed with the code best I can but kept breaking the application

**Comment by antelle** [comment]
Hi! It's not possible to hide the password field.  
There's no description apart from this wiki page, you can try changing options like "canOpenDemo", "canCreate", "canImportXml", and so on, they can give something similar.
