### ISSUE TITLE
Firefox 67-70, invalid global autotype

### ISSUE THREAD

**Issue by AnFlare** [keeweb/keeweb#1186]
When using Firefox (last update) and Alt+Shift+T (global autotype shortcut) it sends login/password sequence in unpredictable manner, not using Keystrokes sequence at all.

KeeWeb v1.8.2 (ebe7d35c, 2019-04-22)
Environment: electron v4.0.1
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) KeeWeb/1.7.8 Chrome/69.0.3497.106 Electron/4.0.1 Safari/537.36

**Comment by AnFlare** [comment]
Also it doesn't offer a choice for a record to type

**Comment by antelle** [comment]
There were some auto-type fixed in 1.9.2, let's check if it works better now

**Comment by AnFlare** [comment]
@antelle Downloaded update right now. Seems nothing changed. When I try to login into Github, it offers login&pass of Firefox record.

**Comment by AnFlare** [comment]
Same with yandex.com
No matter what, it just autotype Firefox credentials.

**Comment by antelle** [comment]
Strange. Does it work in other apps on this OS?

**Comment by AnFlare** [comment]
It works in Chrome.

**Comment by AnFlare** [comment]
After so many updates nothing has changed. Going to KeePass XC, sorry..

**Comment by AnFlare** [comment]
["URL in title" addon](https://addons.mozilla.org/en-US/firefox/addon/url-in-title-keepass/?src=search) fixes this bug...
... but it's not a proper solution.

**Comment by AnFlare** [comment]
Found out that entry title must be some part of tab title. Seems Keeweb doesn't take page address into consideration at all  😐

**Comment by antelle** [comment]
Finally, we'll have an extension and KeePassXC-Browser integration in the next version. Closing this issue because it's unlikely it will be possible to fix it. Browser extensions will provide much better experience in this case.
