### ISSUE TITLE
Custom URL and changing where the files are called from our database and server

### ISSUE THREAD

**Issue by RustinCassiem** [keeweb/keeweb#1188]
**Is your feature request related to a problem? Please describe.**
I want to use this application in a private environment with my group of co-workers, to do this I want the Application to point to our database and server   

**Describe the solution you'd like**
I want the application to be on our server and when we call the custom URL ex.www.oururl.com/security, I want the application not to call to your GitHub Repo but to our servers instead and to be updating the database through our servers as well  

**Describe alternatives you've considered**
We have been using the application locally but for security reasons, I want this application to run through our browser from our network server so that we can maintain the version of the application another thing I want is to make regular backups twice a day but we can figure something out to do that on the server side like run a script periodically so that we can have backups and rollback when needed  

**Additional context**
We had an issue with running this locally where one of our main computers which stored and updated our password on its SSD became corrupt, this is why we wanted to implement the application onto a server for more of us to have access and flexibility when wanting to see the passwords we have stored

**Comment by antelle** [comment]
Hi! Thanks for the detailed description!
Do I understand it right that Application here means a web application / page, not the desktop build?

Self-hosting of the webapp is quite easy, there are two ways: using a docker container or deploying the html content manually, they’re described on this page: https://github.com/keeweb/keeweb/blob/master/README.md#self-hosting

For the desktop app it would be a bit more complicated. Basically what you need to do is: 1. build the app yourself with changed URLs; 2. set up a web server that will host the update manifest; 3. host update files with metadata about them.

Additionally, to make backups and save the kdbx file on a server, you can set up a webdav server and host your file there. This way you will be able to store an encrypted database on your remote storage.

**Comment by RustinCassiem** [comment]
curl https://raw.githubusercontent.com/keeweb/keeweb/develop/dev-env.sh | bash - link gives rl: (7) Failed to connect to raw.githubusercontent.com port 443: Timed out

**Comment by antelle** [comment]
I don’t quite understand what you mean by this curl. There was a timeout connecting to github, that’s all I see here.

**Comment by RustinCassiem** [comment]
This is the link/command provided "curl https://raw.githubusercontent.com/keeweb/keeweb/develop/dev-env.sh | bash -" when running it I get this error link gives rl: (7) Failed to connect to raw.githubusercontent.com port 443: Timed out

**Comment by antelle** [comment]
you need to fix the timeout indeed.

**Comment by RustinCassiem** [comment]
Also, can I get the raw data of the app so that I can try to rebuild the applications using our data

**Comment by RustinCassiem** [comment]
how would I fix it, nothing on my side is causing the timeout

**Comment by antelle** [comment]
You mean the build itself? Yes sure, it’s in releases: https://github.com/keeweb/keeweb/releases

**Comment by antelle** [comment]
> how would I fix it, nothing on my side is causing the timeout

Something does. Your proxy settings, firewall, etc... Github is up and running, you just can’t connect

**Comment by RustinCassiem** [comment]
if i recreate the app what are the name of the files calling to your repo

**Comment by antelle** [comment]
It’s this file: https://github.com/keeweb/keeweb/blob/master/app/scripts/const/links.js

**Comment by RustinCassiem** [comment]
is the app calling from any other files because I will be changing repo,desktop,webapp,removing beta.webapp,autotype and plugins

**Comment by antelle** [comment]
Urls should be configured only there. Removing something from the ui will require digging deeper of course.

**Comment by antelle** [comment]
the question seems to answered now :)
