### ISSUE TITLE
[Feature Request] Copy OTP into clipboard on Autotype

### ISSUE THREAD

**Issue by dploeger** [keeweb/keeweb#1190]
**Is your feature request related to a problem? Please describe.**
On mfa-enabled apps, I always need to manually search for the current otp token after using autotype to automatically log into the app.

**Describe the solution you'd like**
I saw this in Kypass, which has the same problems as iOS is only supporting a username/password based login. They solved that by simply copying the OTP into the clipboard before returning the username and password.

So, when Autotype takes place and the entry has an otp, simply copy that otp into the clipboard. This should be configurable of course.

**Describe alternatives you've considered**
You could as well use the custom Autotype sequence with the OTP enabled, but this is cumbersome because many applications handle the use of OTP differently.

**Comment by jivarson** [comment]
Either that or create a hotkey for "autotype TOTP". With TOTP chaning every 30th second it could be useful. Perhaps <Shift> + Enter? or maybe even better, let <Shift>+Enter (or some other combo) be up for the user to bind..

**Comment by dploeger** [comment]
Will be handled by #1243

**Comment by snakyjake1** [comment]
Did this feature ever get implemented?
If so, how do I get it to work?
I want to have the OTP copied to the clipboard on autotype.

Thanks.

**Comment by antelle** [comment]
@snakyjake1 as you can see in comments, it was implemented as an alternative solution described in the linked issue.

**Comment by snakyjake1** [comment]
I would like a simple way (or automated) to populate the OTP field on a website.  Something that auto-populates the OTP field just like it does with the username and password.  At the very least, after populating the username+password on a website, KeeWeb can copy the OTP field into the clipboard.

**Comment by antelle** [comment]
We should develop a browser extension...
