### ISSUE TITLE
Dealing with bad data

### ISSUE THREAD

**Issue by luckyrat** [keeweb/keeweb#1191]
I see in https://github.com/keeweb/keeweb/commit/28201418978dc449bdd86a22ccabee91bf8ab9c3 that protection against the user inputting char 0x1A was added. As part of the import functionality in Kee Vault, I have just added protection for bad data exported from LastPass (or any other password manager that fails in this way). I based [my fix](https://github.com/kee-org/kdbx-import/commit/623dd0eb1faf85afcad976d58235c63da9ff055b#diff-6533e9c3761a74f5f9fad2ec2172f3f3) on the StrUtil.cs:SafeXmlString function in KeePass in order to hopefully maximise compatibility across different KeePass ports.

This solves the short-term problem for me but got me thinking about whether we could improve how we handle these errors in future so, some questions to consider:

1) Should KeeWeb add protection against the many other bad characters that a user could put into an input field?

2) Should the fix be applied to protected data values too? Obviously being encoded into the XML means that the XML does not become invalid in the same way as with unprotected data. However, in the interests of predictability/consistency for the user and reducing the risk of programming errors manipulating this data in a way that corrupts the XML at a later date, I think it's worth considering behaving the same for both protected and unprotected fields.

3) Should this sort of bad data be handled in the kdbxweb layer rather than KeeWeb and all other consumers of kdbxweb?

    I'm a little surprised that the XmlDocument and/or the XMLSerializer even allow the existence of and serialisation of invalid characters but even if that's a WebAPI spec bug that will get fixed in future, we probably have to work around this behaviour for current browsers now. Any better ideas than running a regex replace through the resulting serialised string? I'd guess that this will be pretty fast, especially compared to walking the XML tree and processing every individual node value before passing to the serialiser.

    Maybe we should handle errors when reading the XML too so that this easy-to-recover-from class of data corruption can be silently fixed for users?

    Maybe by introducing a recovery path in the "parserError" handler in xml-utils.js? We could inspect for errors relating to bad characters and strip all dodgy characters out of the source string before trying the parse operation again. I suggest only doing it after we find an error because it's going to be a very very low percentage of parses that fail in this way and this approach would have no performance impact on the happy path.

**Comment by antelle** [comment]
Hi! Somehow I missed your issue and came to it just now, when cleaning up the backlog.

1. Most likely yes, if there's something like this one, however only this character makes it fail hard.
2. If it doesn't break the format, it's a good question. Most likely it's ok.
3. To my understanding, it's the same as 2. Having this character in the UI can give a bit worse UX for those who happened to insert it, however it's ok from the library's point of view.
