### ISSUE TITLE
Override and modify a model prototype method

### ISSUE THREAD

**Issue by vldgeorgiev** [keeweb/keeweb#1192]
While playing with plugin creation I saw that it is possible to override some of the Keeweb views methods to change or add the desired functionality.
E.g. in a plugin.js code I was able to modify (with the appropriate uninstall code at the ent):
```
const AppView = require('views/app-view');
const appViewRender = AppView.prototype.render;
AppView.prototype.render = function() {
    // Render the default content
    appViewRender.apply(this);
    // .... do other stuff
}
```

I could add features in render or other View methods, like handleAutoSaveTimer for example, etc.
However, is it possible to override in the same way model methods, like? Or is this something applicable to views only?
```
const EntryModel = require('models/entry-model');
const entryModelNewEntry = EntryModel.prototype.newEntry;
EntryModel.prototype.newEntry = function(group, file) {
        entryModelNewEntry.apply(this);
        // ... do other stuff
};
```

Thanks.

**Comment by antelle** [comment]
Hi! `newEntry` is a static method, it should be overridden like this:
```
EntryModel.newEntry = () => alert('newEntry');
```
Other instance methods can be replaced as usual:
```
EntryModel.prototype.deleteHistory = () => alert('deleteHistory');
```

**Comment by vldgeorgiev** [comment]
Thanks. The static override did the job.
