### ISSUE TITLE
Add context menu when is lock

### ISSUE THREAD

**Issue by orblazer** [keeweb/keeweb#1193]
**Is your feature request related to a problem? Please describe.**
When the file is locked and have only mouse under your hands you can't paste password because we can't right click on field

**Describe the solution you'd like**
Add context menu when right click on field for allow paste password

**Comment by antelle** [comment]
I’m not sure if copy-pasting master password is a good idea. Anyway, interface without a keyboard is a very special thing.

**Comment by BrandonGillis** [comment]
A possible alternative to a physical keyboard would be to implement a virtual keyboard for typing the master password, which allow to type the password safely with the mouse instead of copy-pasting

**Comment by antelle** [comment]
The bot was misconfigured, sorry for a wrong notification.

**Comment by antelle** [comment]
Just realized that there's a context menu on the main password input. Looks like it's fixed now.
