### ISSUE TITLE
webDAV sync with ownCloud

### ISSUE THREAD

**Issue by bastos77** [keeweb/keeweb#1195]
**Describe the bug**
Fehler: Network Error

**To Reproduce**
try to get webDAV file in apps.keeweb.info

I understand, that I have to enable CORS.
In OwnCloud CORS requires to white list domains.
What is the domain I have to whitelist? Or where can I see it?

Thanks

**Comment by antelle** [comment]
Hi! The domain name is app.keeweb.info. Examples of configuration can be found here: https://github.com/keeweb/keeweb/wiki/WebDAV-Config
