### ISSUE TITLE
Create two different KeeWeb types 

### ISSUE THREAD

**Issue by RustinCassiem** [keeweb/keeweb#1196]
**Is your feature request related to a problem? Please describe.**
 I am building two custom sites of keeweb one for users and one for admins, the one for users can edit the file and remove things however the admin one can create the database file(.kdbx file) so in the user version I want to remove the new button on the home screen so that people cant create new databases and make a mess in the folder however if they want a new database(.kdbx file) they have to request on by an admin which on a different interface with the all the features active the admin can add it with no problem .

so to give a good example the user URL would be something like www.user-keepass.com
and an admin URL would be www.admn-keepass.com I just want to limit the user interaction and only allow admins to be able to create a new .kdbx file on our servers

**Describe the solution you'd like**
I would like to know where I can make the changes I desire because I have been sitting with the site for a week and all the changes I make breaks the site completely changing the index.html in the temp folder as my test  dummy becomes a challenge since the second I know what I am looking for I can't find it in the code since everything is so tightly packed on itself 

**Describe alternatives you've considered**
I have tried everything I could think of

**Comment by antelle** [comment]
Hi! You can achieve this by generating a [config file](https://github.com/keeweb/keeweb/wiki/Configuration#json-app-config) and giving different versions of configs to different users.  
Then some of them will have "new" option, and some of them will have it disabled.
