### ISSUE TITLE
js location 

### ISSUE THREAD

**Issue by RustinCassiem** [keeweb/keeweb#1197]
where is the view and js for this button 
![Capture](https://user-images.githubusercontent.com/38912152/59556675-c4d37600-8fc6-11e9-9d16-01b50255eea8.PNG)

**Comment by antelle** [comment]
There's no explicit view for it. It's rendered as a menu item here: 

https://github.com/keeweb/keeweb/blob/master/app/templates/menu/menu-item.hbs
https://github.com/keeweb/keeweb/blob/master/app/scripts/views/menu/menu-item-view.js
https://github.com/keeweb/keeweb/blob/master/app/scripts/models/menu/menu-item-model.js
