### ISSUE TITLE
Js location

### ISSUE THREAD

**Issue by RustinCassiem** [keeweb/keeweb#1198]
![Capture](https://user-images.githubusercontent.com/38912152/59556819-e124e200-8fc9-11e9-835f-fef8809708fa.PNG)
 
where is the view and js for this button, please

and thanks for all the info of the other

**Comment by antelle** [comment]
Hi,
It's here:

https://github.com/keeweb/keeweb/blob/master/app/templates/open.hbs#L5
https://github.com/keeweb/keeweb/blob/master/app/scripts/views/open-view.js#L297
