### ISSUE TITLE
The wiki content about the chrome extension address is outdated

### ISSUE THREAD

**Issue by imaojun** [keeweb/keeweb#1199]
**Describe the bug**
In the wiki page:
https://github.com/keeweb/keeweb/wiki/Browser-AutoFill#chrome
> Install ChromeIPass extension.(https://chrome.google.com/webstore/detail/chromeipass/ompiailgknfdndiefoaoiligalphfdae)
Go to its settings and click Connect:

ChromeIPass page does not exist(404), has been updated to KeePassHttp-Connector. Please update the extension address to:
https://chrome.google.com/webstore/detail/keepasshttp-connector/dafgdjggglmmknipkhngniifhplpcldb

**Comment by antelle** [comment]
Done thanks!
