### ISSUE TITLE
Add Themes

### ISSUE THREAD

**Issue by RustinCassiem** [keeweb/keeweb#1200]
I added a new theme file in _all-themes.scss and as _example.scss but it wont add to the options

**Comment by antelle** [comment]
Hi! If you would like to add a new theme, the suggested way is to create a [plugin](https://github.com/keeweb/keeweb/wiki/Plugins) with it.

Built-in themes should be added in js to appear in settings: https://github.com/keeweb/keeweb/blob/8a47ed864ca11f813ad3c90a5a3ecdc2de9596a3/app/scripts/comp/settings-manager.js#L15.

**Comment by RustinCassiem** [comment]
Let just try that

**Comment by RustinCassiem** [comment]
able to select the theme but its invisible

**Comment by antelle** [comment]
I would try searching where other themes are defined.
