### ISSUE TITLE
Location of function 

### ISSUE THREAD

**Issue by RustinCassiem** [keeweb/keeweb#1201]
Hi 
where is the function that opens the explorer in the files/pictures section 

also thanks for all the help so far

**Comment by RustinCassiem** [comment]
when clicking the lock it opens in te pictures folder all the time ,What I want it to do is open in a folder within our netowkr it works ,I just want to find the fuction that force opens in the photo folder

**Comment by RustinCassiem** [comment]
I want to force set where it opens

**Comment by antelle** [comment]
Hi,
It should open last folder instead of pictures, but maybe it doesn't work for you for some reason. Anyway, it's here: https://github.com/keeweb/keeweb/blob/master/app/scripts/views/open-view.js#L297
