### ISSUE TITLE
Auto type uses wrong credentials

### ISSUE THREAD

**Issue by melo0187** [keeweb/keeweb#1202]
Hey there! Really enjoying keeweb and being able to use my own NAS as webdav server to always have my kdbx file available!
After using it for a few months I noticed a minor glitch in auto-type that I wanted to report.

**Describe the bug**
KeeWeb uses the wrong credentials on auto-type for the sites where it thinks it is able to detect the correct entry itself. For the situations where it asks me which entry to use after having triggered auto-type things work fine. Also triggering auto-type when having the entry select in keeweb with ctrl+T always works.

**To Reproduce**
1. Have keeweb started and minimized
2. Go to https://trakt.tv/auth/signin
3. shift+alt+T
4. wrong credentials are submitted

**Expected behavior**
Expected correct credentials to be used.

**Environment**
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) KeeWeb/1.8.2 Chrome/69.0.3497.106 Electron/4.0.1 Safari/537.36

I'm using Ubuntu 19.04

**Logs**
```
2019-06-19T17:23:34.508Z [auto-type] Auto type event null
index.html:12 2019-06-19T17:23:34.510Z [auto-type] Get window title
index.html:12 2019-06-19T17:23:34.517Z [launcher] spawn xdotool: 0, 7ms
Sign in to Trakt.tv - Trakt.tv - Google Chrome
index.html:12 2019-06-19T17:23:34.517Z [auto-type] Window title Sign in to Trakt.tv - Trakt.tv - Google Chrome null
index.html:12 2019-06-19T17:23:34.520Z [auto-type] Hide window
index.html:12 2019-06-19T17:23:34.520Z [auto-type] Start {USERNAME}{TAB}{PASSWORD}{ENTER}
index.html:12 2019-06-19T17:23:34.520Z [auto-type] Parsed [op:USERNAME,op:TAB,op:PASSWORD,op:ENTER]
index.html:12 2019-06-19T17:23:34.521Z [auto-type] Resolved [************************,key:tab,[*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*],key:enter]
index.html:12 2019-06-19T17:23:35.052Z [launcher] spawn xdotool: 0, 531ms
index.html:12 2019-06-19T17:23:35.175Z [launcher] spawn xdotool: 0, 122ms
index.html:12 2019-06-19T17:23:35.321Z [launcher] spawn xdotool: 0, 146ms
index.html:12 2019-06-19T17:23:35.403Z [launcher] spawn xdotool: 0, 82ms
index.html:12 2019-06-19T17:23:35.540Z [launcher] spawn xdotool: 0, 136ms
index.html:12 2019-06-19T17:23:35.656Z [launcher] spawn xdotool: 0, 115ms
index.html:12 2019-06-19T17:23:35.763Z [launcher] spawn xdotool: 0, 107ms
index.html:12 2019-06-19T17:23:35.871Z [launcher] spawn xdotool: 0, 108ms
index.html:12 2019-06-19T17:23:35.985Z [launcher] spawn xdotool: 0, 114ms
index.html:12 2019-06-19T17:23:36.085Z [launcher] spawn xdotool: 0, 99ms
index.html:12 2019-06-19T17:23:36.184Z [launcher] spawn xdotool: 0, 100ms
index.html:12 2019-06-19T17:23:36.335Z [launcher] spawn xdotool: 0, 150ms
index.html:12 2019-06-19T17:23:36.445Z [launcher] spawn xdotool: 0, 109ms
index.html:12 2019-06-19T17:23:36.551Z [launcher] spawn xdotool: 0, 106ms
index.html:12 2019-06-19T17:23:36.655Z [launcher] spawn xdotool: 0, 104ms
index.html:12 2019-06-19T17:23:36.758Z [launcher] spawn xdotool: 0, 102ms
index.html:12 2019-06-19T17:23:36.859Z [launcher] spawn xdotool: 0, 101ms
index.html:12 2019-06-19T17:23:36.892Z [launcher] spawn xdotool: 0, 32ms
index.html:12 2019-06-19T17:23:36.893Z [auto-type] Complete 2372ms
```

Hope this description is useful.
Let me know how I can help looking further into this.

**Comment by antelle** [comment]
Hi! Do you have another entry in your file with these wrong credentials? Maybe it selects a wrong entry and types it?

**Comment by melo0187** [comment]
Hi! Thanks for replying. I recognize the entered e-mail address as mine. So KeeWeb is not making things up. It just seems to be selecting the wrong entry, but being confident about its correctness instead of asking me which entry to use, which is the case for other sites.

**Comment by melo0187** [comment]
**Update**: By going through my kdbx and changing the capitalization in my e-mail address entry by entry and triggering auto-type after changing each entry and managed to figure out which entry is wrongly selected. It is the entry for my Google account.

Things the entries have in common:
- are in the same folder
- have been added to the kdbx the same day (Google entry actually being created 10m earlier than the one for Trakt)

I moved the entry for Google to the trash. At that point keeweb asked me to select an entry when triggering auto-type on https://trakt.tv/auth/signin. Restoring the Google entry from trash made the bug reappear.

**Comment by antelle** [comment]
Please post the title and url for both entries and the website where auto-type is initiated.

**Comment by melo0187** [comment]
Sure thing!

Google Entry:
- title: Google
- url: https://accounts.google.com/signin

Trakt Entry:
- title: TraktTV
- url: https://trakt.tv/auth/signin

I initiate auto-type here: https://trakt.tv/auth/signin

Another thing: I deactivated the option "automatically autotype if only one matching entry is found", at which point I get the "Auto-Type Select" dialog with the Google entry at the first position followed by what looks like my entire list of remaining entries sorted alphabetically.
This is a strong indicator, that autotypefilter returns just the one entry for Google [here](https://github.com/keeweb/keeweb/blob/master/app/scripts/auto-type/index.js#L202).
As of the debug log output getActiveWindowTitle returns "Sign in to Trakt.tv - Trakt.tv Google Chrome" as title and "null" as url. Therefore autotypefilter has only the title "Sign in to Trakt.tv - Trakt.tv Google Chrome" to lookup entries. If I find the time this weekend I might try to debug what autotypefilter is doing in that situation, but I don't have much experience in debugging an Electron app.

**Comment by melo0187** [comment]
**Update**: Changing the title for Trakt from TraktTV to Trakt.tv allows autotypefilter to actually find both entries. So it looks like it needs an exact word match.
Anyway, the root of the problem on Ubuntu 19.04 seems the to be the windowname returned by xdotool.
I tested it like this: `sleep 2 && xdotool getactivewindow getwindowname`
The `sleep 2` giving me the time to switch to Google Chrome being the active window. Xdotool's returned windowname will always contain the application name for Google Chrome.

**Comment by melo0187** [comment]
I was thinking to update `auto-type-helper-linux.js` to process the returned windowname. Something like this:
```
[...]
        complete: function(err, res) {
            return callback(err, res ? (
                res.split('-').length > 1 ? (
                    res.split('-').slice(0, -1).join().trim()
                ) : res.trim()
            ) : undefined);
        }
[...]
```
However I don't think this is ideal, because it is not specific to the browser windows and might end up cutting off a part of a non-problematic windowname of a non browser window, but I'll let you be the judge of that.

In the meantime I renamed my entry for Google from "Google" to "Google Account", which is not a match for "Google Chrome" and thus fixes my problem =)
