### ISSUE TITLE
Tags and Subtags separated by backslash

### ISSUE THREAD

**Issue by paulotcf** [keeweb/keeweb#1204]
I would like to check the possibility of creating subtags. The separation of the tags and subtags can be done with the backslash and the visualization in tree format. For example:
Financial\Bank
Financial\Credit Card
Work\Company 1
Work\Company 2

Tks

**Comment by antelle** [comment]
There are two options for categorization: tags and folders. Folders are hierarchical, tags are flat. We should not mix them.
