### ISSUE TITLE
[feature request] Add the ability to filter entries based on source

### ISSUE THREAD

**Issue by Navds** [keeweb/keeweb#1206]
When multiple sources are opened at the same time, all entries are displayed in a merged view without any hint which ones belong to which source unless you click one and view the details.
It would be great if we can filter only all entries in one file. 

KeeWeb v1.8.2 (ebe7d35c, 2019-04-22)
Environment: electron v4.0.1
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_5) AppleWebKit/537.36 (KHTML, like Gecko) KeeWeb/1.8.2 Chrome/69.0.3497.106 Electron/4.0.1 Safari/537.36

**Comment by antelle** [comment]
Hi! You can filter them if you select a top-level group on the left.
