### ISSUE TITLE
WebDAV credentials corrupted 

### ISSUE THREAD

**Issue by luelista** [keeweb/keeweb#1208]
**Describe the bug**
The login credentials stored in file-info.json get corrupted. The username was reset to my local computer's username. The password was changed to a non-ascii string of same length as the original password (maybe it wasn't changed but the app is just unable to decrypt it).

e.g. before, the correct data was

    "opts":{"user":"webdav-max","encpass":"***********"}

after, the corrupted data is

    "opts":{"user":"mw","encpass":"***********"}

(I censored out the base64 string because I'm not sure if it still correlates with my password)

I have multiple WebDAV files open in KeeWeb, and for all of them (all entries in file-list.json) the same invalid "opts" value was stored.

**To Reproduce**
- I don't know how to cause the corruption
- after it is caused, clicking "Sync" shows a HTTP 401 sync error, because the credentials are invalid
- in the network tab of dev tools I see the incorrect credentials transmitted and the server responding correctly with a 401.

**Expected behavior**
The credentials should be stored exactly as entered.

**Environment**
KeeWeb v1.8.2 (ebe7d35c, 2019-04-22)
Environment: electron v4.0.1
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_2) AppleWebKit/537.36 (KHTML, like Gecko) KeeWeb/1.7.7 Chrome/69.0.3497.106 Electron/4.0.1 Safari/537.36

**Logs**
```
2019-07-03T20:23:54.987Z [sync:password2] Sync started webdav http://example.org/sync/keepass/password2.kdbx {startedByUser: true}
index.html:formatted:25273 2019-07-03T20:23:54.989Z [sync:password2] Stat file
index.html:formatted:25267 2019-07-03T20:23:54.990Z [storage-webdav] Stat http://example.org/sync/keepass/password2.kdbx
index.html:formatted:34707 HEAD http://example.org/sync/keepass/password2.kdbx 401 (Unauthorized)
_request @ index.html:formatted:34707
stat @ index.html:formatted:34511
syncFile @ index.html:formatted:32990
save @ index.html:formatted:43330
saveDefault @ index.html:formatted:43333
M @ index.html:formatted:9810
(anonymous) @ index.html:formatted:9819
(anonymous) @ index.html:formatted:9398
dispatch @ index.html:formatted:23030
p.handle @ index.html:formatted:22968
index.html:formatted:25267 2019-07-03T20:23:55.024Z [storage-webdav] Stat error http://example.org/sync/keepass/password2.kdbx 401 32ms
index.html:formatted:25273 2019-07-03T20:23:55.024Z [sync:password2] Stat error, not dirty HTTP status 401
index.html:formatted:25273 2019-07-03T20:23:55.024Z [sync:password2] Sync finished HTTP status 401
```

**Comment by antelle** [comment]
Hi! It would be interesting to understand how to reproduce this. Once they're corrupted, it's quite obvious what will happen.

**Comment by max-weller** [comment]
Did I research correctly, the WebDAV password is encrypted by XORing it with the UUID of the Root Group of the kdbx file?

**Comment by antelle** [comment]
Yes exactly.

**Comment by max-weller** [comment]
Ah, I checked the file-info.json in more detail, the incorrect "opts" data is indeed correct for one of the files (the "mw" user works there, and the password decrypts with this file's UUID). So I guess at some point, when storing the file-info.json, the "opts" from one file is copied over to all others.

**Comment by antelle** [comment]
The bot was misconfigured, sorry for a wrong notification.

**Comment by hewittchoi** [comment]
There was an error opening file
No Last-Modified header
When I opened Webdav database.

**Comment by antelle** [comment]
@hewittchoi unrelated to this issue. Most likely the server doesn't provide this header, please don't post about it in this ticket to keep it clean.

**Comment by max-weller** [comment]
It has worked correctly for quite some time now, but I just hit the same bug again. The `encpass` field has been overwritten with the value for another file. 

One thing I found out from the log is that I had no internet connection during opening the file, and when I got online, the sync failed with 401 because of the mangled password. I'm not sure however when the corruption occured exactly, if it was already corrupted when opening the app.

I put a slightly redacted version of the Dev Tools log here: https://gist.github.com/max-weller/3e3a41c7232531147df50470b718176b

**Comment by max-weller** [comment]
Just as a note for other people in the same situation or for the future me...
I was able to recover from this without completely removing and re-adding the file by changing the file-info.json:
Replace opts.encpass with an opts.password field with the correct password in plaintext, and change the user field to the right value.

E.g. before:

```
 "opts":{"user":"thewronguser","encpass":"***********"}
```

After:

```
 "opts":{"user":"thecorrectuser","password":"thecorrectpassword"}
```

**Comment by antelle** [comment]
I finally managed to reproduce it, the fix is coming soon.

**Comment by max-weller** [comment]
Awesome, thanks :)
