### ISSUE TITLE
Wordpress Intergration 

### ISSUE THREAD

**Issue by RustinCassiem** [keeweb/keeweb#1211]
**Is your feature request related to a problem? Please describe.**
So importing the compiled code into a WordPress page shows up as a blank, for security reason we run ApacheDirectory which is integrated as a plugin and when you load the page asks for your username and password before you can see the site so security is fine, only admins can view keeweb in WordPress site but we can't see it because something in the code disables it from being viewed 

**Describe the solution you'd like**
I would like to know where the security scripts are to either modify them or remove them since we already have a security solution in place 

**Describe alternatives you've considered**
I thought it could be WordPress that was the problem however I tried running it on Joomla both are frameworks we use here but Joomla is one I introduced only a week ago 

**Additional context**
I feel that once we get it running on the WordPress framework we could share the finished product with everyone else if anyone wants to replace it for themselves, of course, we will remove anything that has to do with our company of course before we do so

**Comment by antelle** [comment]
Hi,
I would suggest going into devtools and checking what's there, maybe it will bring more clarity what's going on.

**Comment by RustinCassiem** [comment]
Devtools in WordPress ?

**Comment by antelle** [comment]
in the browser

**Comment by RustinCassiem** [comment]
So I tried just turning the application into a WordPress theme and that naturally would work however the site says the JavaScript runtime ,app and CSS can't be loaded due to a loading error ,I got that also when I tried removing some of the security settings

**Comment by RustinCassiem** [comment]
If I do it in the browser ,don't I have to do it I all browsers ,I want to access the site in ?

**Comment by antelle** [comment]
Sorry, I can't answer questions described this way.
