### ISSUE TITLE
System tray icon on KDE not display

### ISSUE THREAD

**Issue by elbowz** [keeweb/keeweb#1212]
**Describe the bug**
A picture is worth a thousand words

**Screenshots**
![Screenshot_20190709_094001](https://user-images.githubusercontent.com/1451484/60869540-74e77800-a22f-11e9-88e4-7297b6af0bdd.png)

**Environment**
KeeWeb v1.8.2 (ebe7d35c, 2019-04-22)
Environment: electron v4.0.1
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) KeeWeb/1.8.2 Chrome/69.0.3497.106 Electron/4.0.1 Safari/537.36

**Thanks for your app, hard works and time!**

**Comment by antelle** [comment]
The bot was misconfigured, sorry for a wrong notification.

**Comment by elbowz** [comment]
It's not a priority bug :)
Thanks for your message!

**Comment by elbowz** [comment]
Something changed:
![Screenshot_20191004_102039](https://user-images.githubusercontent.com/1451484/66192441-c2d61580-e690-11e9-9df6-4a5507f84431.png)

now it seems works!
The only issues that remain:
* app name (electron)
* icon color (white on black could be better)

anyway the issue is solved if you wish close it :+1:

**Comment by antelle** [comment]
Nice, this means it’s fixed in Electron.
