### ISSUE TITLE
Location of funtion

### ISSUE THREAD

**Issue by RustinCassiem** [keeweb/keeweb#1213]
**Is your feature request related to a problem? Please describe.**
I want to know where the function is that keeps a copy of where the previous file was accessed from,

So we have keeweb hosted on a server and the database for the files on a windows server but we don't want users to explore the windows server to find the file, I want it to be auto saved in the last browsed area where previous files are stored

**Comment by antelle** [comment]
Hi! If you mean saving caches during opening files, it's inside `saveFile`: https://github.com/keeweb/keeweb/blob/master/app/scripts/models/app-model.js#L678.
