### ISSUE TITLE
The icon doesn't show in taskbar

### ISSUE THREAD

**Issue by xunilarium** [keeweb/keeweb#1214]
The keeweb icon does not show after installation, I tried to remove and reinstall it but the same issue has appeared. (I installed Windows and Keeweb 3 days ago)

![keeweb](https://user-images.githubusercontent.com/10381709/61517009-7bd66d80-aa1b-11e9-89bf-8404660a7cb7.png)

**Comment by antelle** [comment]
Seems to be working well on latest electron
