### ISSUE TITLE
keewebhttp should match fields even if no url is specified

### ISSUE THREAD

**Issue by asbachb** [keeweb/keeweb#1215]
### Summary
Currently the ranking algorithm which is invoked by keewebhttp does not handle entries when no "Website" entry was defined.

### Use Case
In case of an SSO environment for me it seems more applicable to define these environments as additional fields
e.g.
* Application1: http://application1.local/login
* Application2: https://application2.local/

### Expectation
The ranking algorithm should not differ between "Website" fields and other fields. The "Website" field might get a higher ranking than other fields. But they should not be completely ignored when not "Website" is defined.

### Links
Related Issues: #285

**Comment by antelle** [comment]
Currently they're not ignored, but the url must match exactly. Doesn't it work for your setup?

**Comment by asbachb** [comment]
> Currently they're not ignored, but the url must match exactly. Doesn't it work for your setup?

It works only when then "Website" field is not empty. With that I see several problems
a) The bevahiour is a little bit unclear. Why should a user expect that the feature only works when another field is filled?
b) If you're in a business environment when your windows account information is used for several web applications. What's your primary one? For me it feels more natural to define custom fields for these web applications.

**Comment by antelle** [comment]
You mean, it works everywhere when you put something to website, right?  
In this case, you can put the url of the identity provider to the website field (i.e. where you change the password, create accounts, etc... your federation system), which will fix it.

**Comment by asbachb** [comment]
> You mean, it works everywhere when you put something to website, right?
Yes.

> In this case, you can put the url of the identity provider to the website field (i.e. where you change the password, create accounts, etc... your federation system), which will fix it.
In case of a windows account there's no IDM.

Anyway I wonder if a functionality should be only available if some kind of field is filled. For a user this behavior (at least for me) does not seem to be obvious.

**Comment by antelle** [comment]
It shouldn't of course, but now the issue becomes much easier to fix, I'll fix it.

**Comment by antelle** [comment]
Done, next release will behave as expected.
