### ISSUE TITLE
Invite users to make keeweb default app to open kdbx files

### ISSUE THREAD

**Issue by Thatoo** [keeweb/keeweb#1217]
**Is your feature request related to a problem? Please describe.**
When I click on the url of a .kdbx file, my browser offere me to download the file.

**Describe the solution you'd like**
When I open keeweb for the first time in my browser, it could invite me to always open .kdbx files with this web app as it is the case for email webapp, calendar web app and so on..

**Describe alternatives you've considered**
Should it tell Firefox, Chromium and co tto take in account this new Mimetype and link .kdbx files to the desired keeweb.

**Additional context**
Example when opening mail app in nextcloud. It invites me to consider this mail (web) app as the default app to manage my emails.
![add-app](https://user-images.githubusercontent.com/464782/61956074-acd71500-afbc-11e9-93eb-9ab3c2930888.png)

**Comment by antelle** [comment]
Hi! This should be implemented in [nextcloud-keeweb](https://github.com/jhass/nextcloud-keeweb), it's a separate project.

**Comment by Thatoo** [comment]
I thought keeweb could exist in standalone solution too, out of nextcloud... This feature would be cool too for these keeweb. I didn't have specifically nextcloud-keeweb in mind when I've made my request.
When one open keeweb (hosted in nextcloud or a standalone keeweb app), one could enjoy having the choice to set this app as the default app for .kdbx .

**Comment by antelle** [comment]
Hm, standalone keeweb (the desktop app) should open .kdbx files after you download them. Then I'm not sure I understand the question.
What was the desired behavior? Like gmail does with mail? That's not possible, `.kdbx` is a file extension, not a protocol like `mailto://`.

**Comment by Thatoo** [comment]
That was my idea, I thought it might be possible. My bad if it's possible to do so only with protocol...
