### ISSUE TITLE
App breaking in IIS

### ISSUE THREAD

**Issue by RustinCassiem** [keeweb/keeweb#1218]
**Is your feature request related to a problem? Please describe.**
Running Application on IIS run fine however the site refuses to run on default port which is port 80, it will only run on port 8080, the site has a custom url and no other application is running on port 80 so in theory, it shouldn't refuse port 80 

**Describe the solution you'd like**
I would like it to run on port 80 instead of users having to put 8080 every time they want to access the web app

**Comment by antelle** [comment]
Hi! KeeWeb is HTML, we don't manage ports in any way. Please check your server docs.
