### ISSUE TITLE
Problem accessing webdav

### ISSUE THREAD

**Issue by xyko0** [keeweb/keeweb#1219]
Hello,
Sorry if I missunderstood something but when I try to connect to my webdav server from keeweb, I have a 401 return.
I tried with both Basic-Auth and without and I can access my file through cadaver and others applications so my webdav server is working fine. 
access.log returns : 
[30/Jul/2019:11:11:47 +0200] "OPTIONS /shares/my-files/xyko_db.kdbx HTTP/1.1" 401 3831 "https://app.keeweb.info/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.142 Safari/537.36"

Thank you for your help.
Xyko0

**Comment by xyko0** [comment]
Well after several researches, it is CORS on Chrome blocking access to the request that keeweb is doing. Is it posible to access my webdav file without turning chrome or firefox CORS policy off ?
Thanks for the help :)

**Comment by antelle** [comment]
It's not possible without CORS. You don't want any website to be able read files from your webdav server, do you?

**Comment by xyko0** [comment]
Hi antelle thanks for your answer. 
I mean, I can access my kdbx file with others apps so why can't I access my webdav with keeweb ?
I think I did something wrong in my virtualhost because Console show me this :

Access to XMLHttpRequest at 'https://webdav.xyko.fr/webdav/xyko_db.kdbx' from origin 'https://app.keeweb.info' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.

But in the Vhost I declared 'Access-Control-Allow-Origin' header,  like explained here https://github.com/keeweb/keeweb/wiki/WebDAV-Config

**Comment by xyko0** [comment]
As I thought, I didn't get the whole concept after hours working on my server ^^'
Keeweb and CORS needs URL origin to be the same. 
I was trying to catch webdav.mydomain.fr from keeweb.mydomain.fr so that was my problem
I created a webdav folder in keeweb.mydomain.fr/webdav and here it works.
Night is a good thing to think.
Thank you and I hope my feedback could help some ppl.

Xyko0

**Comment by antelle** [comment]
Sure if you host keeweb on the same domain, it won't need CORS ☺️
