### ISSUE TITLE
We are using HTTP keepass API but we could use custom native browser api!

### ISSUE THREAD

**Issue by marataziat** [keeweb/keeweb#1220]
**Is your feature request related to a problem? Please describe.**
As you said here: https://github.com/keeweb/keeweb/wiki/Browser-AutoFill
> But first, we would like to warn you about the criticism of KeePassHTTP security, that's why this extension not enabled by default in KeeWeb. Auto-Type can be a solid alternative, moreover, it works with other apps, not only browsers. It's recommended to try auto-type approach first.

But as I know everybody uses keeweb only on the machine where passwords are stored! Not via remote http connection! So we could implement custom solution based on browser's native API: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Native_messaging
 https://developer.chrome.com/apps/nativeMessaging

**Additional context**
I'm not sure how good practice is that, but gnome shell actually uses Native API!

**Comment by antelle** [comment]
Using native messaging would be much better and there are browser plugins supporting that, however some work needs be done to support it. It's #874
