### ISSUE TITLE
Auto-lock custom time

### ISSUE THREAD

**Issue by AlexeyGy** [keeweb/keeweb#1221]
Dear keeweb team,

I just tried to set the auto-lock time to 30 mins and couldn't since 15 mins was a bit short but 1 hour a bit too long.

 It would be great to be able to set custom times for auto-lock, e.g., 30 minutes. I don't see anything against it and it should be easy to implement, just add a "custom" option and add a text field which displays if the custom option is selected. The text field can be validated to contain an integer value between [1 and 24*60] minutes.

![image](https://user-images.githubusercontent.com/13885630/62446773-e7cb0c80-b763-11e9-9d09-4cdfe84e16b4.png)

**Comment by antelle** [comment]
Hi! Let's just add '30 min' there.

**Comment by AlexeyGy** [comment]
Bedankt for the fast reply and suggested quick fix!

**Comment by antelle** [comment]
Graag gedaan, this will be probably included in the next hotfix.

**Comment by Lukasdoe** [comment]
Is it still needed to have an option for a custom value? I could implement a field for custom minutes for example...

**Comment by antelle** [comment]
@Lukasdoe no.
