### ISSUE TITLE
Broken Search

### ISSUE THREAD

**Issue by GamerClassN7** [keeweb/keeweb#1224]
Hi
I am unable to use search in sub groups,

**Expected behavior**
If i clicked on root dir in db it should search in whole db

**Environment**
Windows

Thanks for any suggestion. :)

**Comment by antelle** [comment]
Hi! Please give more details: where do you click? what did you put in the search field? what do you see when you just open the file? etc...

**Comment by GamerClassN7** [comment]
wehwn i open file i see only file structure (subfolders etc.) and records right in root

for example i am clicket on root folder of db and i write DB in search field and nothing show but when i select subfolder root\SteelAnts and do same process it show correct record.

![image](https://user-images.githubusercontent.com/22167469/62714897-b4a4a980-b9ff-11e9-9113-2221e9d5fd4e.png)

![image](https://user-images.githubusercontent.com/22167469/62714926-c1290200-b9ff-11e9-8b23-615c96219af0.png)

**Comment by GamerClassN7** [comment]
Sorry for my bad English :(

**Comment by antelle** [comment]
What do you have in this setting?
<img width="467" alt="Untitled" src="https://user-images.githubusercontent.com/633557/62715143-3268b500-ba00-11e9-9189-e6470d079c95.png">

**Comment by GamerClassN7** [comment]
![image](https://user-images.githubusercontent.com/22167469/62715270-73f96000-ba00-11e9-91a3-f296a9438ec4.png)

**Comment by antelle** [comment]
Okay, now let's go to the group settings:

<img width="148" alt="Untitled" src="https://user-images.githubusercontent.com/633557/62715389-b4f17480-ba00-11e9-9949-2be29fde73a5.png">

and check this thing:
<img width="624" alt="123" src="https://user-images.githubusercontent.com/633557/62715440-cb97cb80-ba00-11e9-8123-5843565180a7.png">

**Comment by GamerClassN7** [comment]
All have this option unchecked, that is wierd because until last update it was working fine! is there any way how to check it on every folder ?

**Comment by antelle** [comment]
No, only go through all folders manually and check them.

**Comment by GamerClassN7** [comment]
Ok Thanks for help :) you are best 👍
