### ISSUE TITLE
keewebhttp not working after update to v1.8.2

### ISSUE THREAD

**Issue by GamerClassN7** [keeweb/keeweb#1225]
Hi

**Describe the bug**
no chrome extension is able to detect credentials in database.

**To Reproduce**
1. Unlock Database
2. Check in chrome extension connection status
3. refresh page see if there are any credentials available 

**Expected behavior**
Show list of available credentials based on url.

**Screenshots**
![image](https://user-images.githubusercontent.com/22167469/62775414-db1e1f80-baa7-11e9-80d5-54994a48ba33.png)

![image](https://user-images.githubusercontent.com/22167469/62775451-fa1cb180-baa7-11e9-9cb3-6c0e035d7ff8.png)

**Environment**
WIN 10 (18362)
CHROME 76.0.3809.100
KEEWEB v1.8.2

Thanks for any advice and sorry to bother you

**Comment by antelle** [comment]
Hi! Let's check the logs:

1. open DevTools (from settings)
2. run this: `localStorage.keewebhttpDebug = 1`
3. restart KeeWeb
4. do the thing
5. after debugging, don't forget to run `delete localStorage.keewebhttpDebug`

**Comment by GamerClassN7** [comment]
Where do i find the log ?

**Comment by GamerClassN7** [comment]
![image](https://user-images.githubusercontent.com/22167469/63158000-9c90e380-c018-11e9-8c4e-6fda02512e29.png)
May be this will be the problem  ?

**Comment by antelle** [comment]
What happens if you open a demo db and try to autocomplete a password on facebook.com?

**Comment by antelle** [comment]
I just tried it on demo and it seems to be working well. Could you please create a new file with only this record and fake username/password, so that I can take a look?

Please reopen this issue then.

**Comment by GamerClassN7** [comment]
HI
sorry for minor delay. I did like you say from a new file it work like charm ? 

Could by my database somehow corrupted or similar think  ?
is there any way how to fix it

**Comment by GamerClassN7** [comment]
But i am unable to reopen this issue :(

**Comment by GamerClassN7** [comment]
I try to use keepass repair mode but no change

**Comment by antelle** [comment]
It’s not broken, just something is wrong. One thing you can try is exporting your file as xml and inspecting what’s inside your entry. If nothing obvious pops up, you can send it to me, but please make sure you delete all passwords and other stuff from there first! (they’re stored encoded)

**Comment by GamerClassN7** [comment]
how could i export it like xml ?

**Comment by antelle** [comment]
it’s in file settings, save as...

**Comment by GamerClassN7** [comment]
It is one huge mess would be possible to send you only one Record to check i am afraid if i send you whole file i miss some password

**Comment by antelle** [comment]
just one record. If it contains anything encoded, not plaintext, etc... it can be a password, you should not send it.

**Comment by GamerClassN7** [comment]
i know sorry i have terrible English!

I meant that file is no formatted but midified (i think because of size ??)

so i was asking if i could send you only one entry where i will be sure that i delete all private data 
`
    <String>
      <Key>Title</Key>
      <Value>Košík.CZ</Value>
    </String>
    <String>
      <Key>URL</Key>
      <Value>https://www.kosik.cz/</Value>
    </String>
    <String>
      <Key>UserName</Key>
      <Value>[MYEMAIL]</Value>
    </String>
    <AutoType>
      <Enabled>False</Enabled>
      <DataTransferObfuscation>0</DataTransferObfuscation>
    </AutoType>
    <History/>
  </Entry>
  <Entry>
    <UUID>[UID]</UUID>
    <IconID>1</IconID>
    <ForegroundColor/>
    <BackgroundColor/>
    <OverrideURL/>
    <Tags/>
    <Times>
      <CreationTime>2019-07-15T10:11:09Z</CreationTime>
      <LastModificationTime>2019-07-15T10:11:48Z</LastModificationTime>
      <LastAccessTime>2019-08-08T14:50:06Z</LastAccessTime>
      <ExpiryTime>2019-07-15T10:10:51Z</ExpiryTime>
      <Expires>False</Expires>
      <UsageCount>1</UsageCount>
      <LocationChanged>2019-08-08T14:50:06Z</LocationChanged>
    </Times>
    <String>
      <Key>Notes</Key>
      <Value/>
    </String>
    <String>
      <Key>Password</Key>
      <Value ProtectInMemory="True">[DELETED]</Value>
    </String>
`

**Comment by GamerClassN7** [comment]
and from what i notice passwords are there like a plain text that is not a good idea in my eies :D  or it sis because of export ?

**Comment by antelle** [comment]
it’s because of export, the file is not stored like this indeed. I’ll take a look tonight, thanks.

**Comment by GamerClassN7** [comment]
i tanks to you for your patient etc. thanks

**Comment by GamerClassN7** [comment]
ANY NEWS ? :)

**Comment by antelle** [comment]
Just checked your entry, it has AutoType disabled:
```
    <AutoType>
      <Enabled>False</Enabled>
      <DataTransferObfuscation>0</DataTransferObfuscation>
    </AutoType>
```

If you enable it, it should work.

<img width="276" alt="Screen Shot 2019-08-20 at 20 08 48" src="https://user-images.githubusercontent.com/633557/63372489-81123980-c386-11e9-8bd4-4d53ae902182.png">

<img width="510" alt="Screen Shot 2019-08-20 at 20 09 08" src="https://user-images.githubusercontent.com/633557/63372497-84a5c080-c386-11e9-818f-5ad010cca3c9.png">

**Comment by GamerClassN7** [comment]
Hi,
THANKS!!!!!
I will try it today!

but there are some additional information's down below :(

if you remember we solve together problem when search was not working.
it was caused by mot checked checkbox in sub folders detail.

and after yesterday update are all again unmarked. 

and both thinks worked until update to 1.8.2

cannot be there some problem that after each update, for some reason keeweb unchecked all check-boxes ? ?

**Comment by GamerClassN7** [comment]
So i test it 
it work for other sites but not for Košik.cz

![image](https://user-images.githubusercontent.com/22167469/63409414-6aed9300-c3f1-11e9-91ee-b2552a5f89f3.png)

**Comment by antelle** [comment]
> for some reason keeweb unchecked all check-boxes

Please check those checkboxes for other groups, maybe they're checked somewhere on top of the entry / group.

What if you delete the entry and add it again?

**Comment by GamerClassN7** [comment]
Thanks
After deleting and reading exact same record it finally work :) 

I hope that after next update it will work, and no check boxes will be unchecked :D 
if yes can i write again to this issue or create new one ? :)

**Comment by antelle** [comment]
I don’t think it happens between updates, it must be something else. Let’s see if it disappears again.
