### ISSUE TITLE
[Question] How do you unlink Google Drive access on https://app.keeweb.info ?

### ISSUE THREAD

**Issue by flatline-studios** [keeweb/keeweb#1227]
Love the project. Just what I was looking for.

One thing strikes me though, when I'm at a friends house, at a library (yeah, right), etc., and I need to get a password, I:

1) Go to: https://app.keeweb.info/
2) Hit "--- MORE"
3) Select "Google Drive"
4) Authorise it.
5) Navigate to my database folder, and select the relevant file.
6) Type in the password, and I'm done.

Great.

The issue is when I'm done, I can use "Lock" to get out. But then if I click "--- MORE", and select "Google Drive", I'm still logged in/authorised for Google Drive, and the next user can browse my Google Drive account. This is a bit sketchy.

I can't seem to find anyway to remove access from the https://app.keeweb.info/ interface.

Is there actually a way? A deauthorise all button would be handy here, or am I missing something?

**Comment by antelle** [comment]
Hi! This is indeed is not possible to find,
but you can disconnect Google Drive if you go to settings, uncheck Google Drive and check it again.
