### ISSUE TITLE
Cannot connect to Dropbox when added to homescreen on iOS.

### ISSUE THREAD

**Issue by DSDeniso** [keeweb/keeweb#1228]
**Describe the bug**
When added on the homescreen on iOS, it's not possible to create a connection to Dropbox.

**To Reproduce**
1. Add KeeWeb to the homescreen from Safari
2. Open a password database from Dropbox
3. Sign in to Dropbox
4. See a message that says that KeeWeb is open in another tab and asks you to close it without the possibility of doing so

**Expected behavior**
Close sign in window and show database files in Dropbox

**Environment**
Newest iOS

**Comment by antelle** [comment]
Hi! Which iOS is this: public or beta? It works for me on latest iOS 12.

**Comment by antelle** [comment]
I think the issue happens because you're trying to open a file stored in Dropbox. In this case, please open keeweb and click Dropbox, without opening the file - this should work.

**Comment by ollar** [comment]
Android 6.0.1, Firefox - same behaviour. I am trying to connect my dropbox acc, pass through authorization, came back to the app and get this error.

*Expected behavior*
Close sign in window and show database files in Dropbox

**Comment by antelle** [comment]
@ollar I won’t be able to test it in Android

**Comment by DSDeniso** [comment]
Hi

Sorry. For some reason I didn't get an email about your response. I'll try again soon and update. Have you noticed that the issue is only relevant when added as an "app" to the homescreen?

All the best
Deni

**Comment by gsportelli** [comment]
Hi, I’ve seen the same problem on my iPad 12.9’’ with iOS 12.1.3. The problem disappears after updating to 13.2.2.
