### ISSUE TITLE
kdb4 relative time wrong ?

### ISSUE THREAD

**Issue by kaich** [keeweb/keeweb#1229]
**Describe the bug**
When I use the kdbx 4 file. The creation time is not equal to macpass.

The kdbx 4 rule as below:

```
In encrypted KDBX 4 files (not in plaintext XML exports), all times are now stored as Base64 string of the Int64 number of seconds elapsed since 0001-01-01 00:00 UTC. This improves the performance and reduces the file size.
```

But when I read the code. I found the keeweb refer to 0001-01-03 00:00 UTC.  And macpass refer to  0001-01-01 00:00 UTC. which is the right one ?

**Comment by antelle** [comment]
Hi! The easiest way is to compare with KeePass. Could you please check which one is the same?

**Comment by kaich** [comment]
@antelle Keepass is same to keeweb. But the document said it's refer to 0001-01-01 00:00 UTC. So I confused.

**Comment by antelle** [comment]
Please report to MacPass.  
If you’re concerned about discrepancy between the doc and implementation in KeePass, please report to their bug tracker.

When/If it’s changed in KeePass, please open another issue in KeeWeb.
