### ISSUE TITLE
Language translate for Turkish ?

### ISSUE THREAD

**Issue by Deadlyhacker** [keeweb/keeweb#123]
I can translate English > Turkish for Turkish users like me if you want developer :)

**Comment by antelle** [comment]
Thank you! I'll contact you once the app will be translation-ready.
For now, all strings have been already externalized, but they change rather quickly and there's no language-switching UI, so it's not reasonable, to translate at this time. Full support of languages is planned for 1.2 .. 1.3 release, then I'll create a public project on a service like transifex, so everyone will be able to add a translation.
I'll create translations for some popular languages: German, French, Dutch, Norwegian, Finnish and some others.

**Comment by antelle** [comment]
Translations will be handled here: http://keeweb.oneskyapp.com/
Just uploaded strings and screenshots to it, so translations may be confusing / not full. Please let me know if something is strange.
