### ISSUE TITLE
"Error InvalidArg: data

### ISSUE THREAD

**Issue by AndiLeni** [keeweb/keeweb#1230]
When I enter my password the online version gives me this error.
Here is the console output:

````
code: "InvalidArg"
​
message: "Error InvalidArg: data"
​
name: "KdbxError"
​
stack: ""
````

**Environment**
Your user-agent (from Settings/Help section)

**Kdbx File**
An older file which worked correctly before.

**Comment by antelle** [comment]
Hi! Perhaps you cleaned up the storage in your browser. Please delete the file from the list and open it again from the storage, it will fix this. Next version should give a better error about this.

**Comment by AndiLeni** [comment]
Thanks! This worked for me :)
