### ISSUE TITLE
Toolbar on Windows

### ISSUE THREAD

**Issue by xago9** [keeweb/keeweb#1232]
**Describe the bug**
Since last version, a toolbar as appeared making the app looking weird.

**To Reproduce**
Install last version on Windows (10).

**Expected behavior**
A normalized app like before or add a way to hide the tool bar.

**Screenshots**
https://i.imgur.com/iZSobu3.png

**Environment**
KeeWeb v1.9.0 (64c41785, 2019-08-18)
Environment: electron v6.0.2
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) KeeWeb/1.9.0 Chrome/76.0.3809.110 Electron/6.0.2 Safari/537.36

**Kdbx File**
//

**Logs**
No log to give since it's design related.

**Comment by TeknoMobil** [comment]
Why did this unnecessary menu come from? The same thing exists in Linux.

**Comment by antelle** [comment]
That’s the new Electron, I’ll take a look tonight
