### ISSUE TITLE
Write concurrency using WebDAV

### ISSUE THREAD

**Issue by amine250** [keeweb/keeweb#1236]
Hello @antelle ,

I have self-hosted on Apache, I tried to test the concurrency on 2 browsers while opening a WebDAV kdbx file.
The 1st user syncs successfully but the second one gets an error:
The same behavior is seen using the MOVE or PUT webdav save method.

```
(index):12 2019-08-21T08:13:56.373Z [sync:TEAM Database] Sync started webdav /TEAM-Database.kdbx {startedByUser: true}
(index):12 2019-08-21T08:13:56.375Z [sync:TEAM Database] Stat file
(index):12 2019-08-21T08:13:56.375Z [storage-webdav] Stat /TEAM-Database.kdbx
(index):12 2019-08-21T08:13:56.406Z [storage-webdav] Stated /TEAM-Database.kdbx Wed, 21 Aug 2019 07:39:04 GMT 30ms
(index):12 2019-08-21T08:13:56.406Z [sync:TEAM Database] Found new version, loading from storage
(index):12 2019-08-21T08:13:56.407Z [sync:TEAM Database] Load from storage, attempt 1
(index):12 2019-08-21T08:13:56.407Z [storage-webdav] Load /TEAM-Database.kdbx
(index):12 XHR finished loading: HEAD "https://example.com/TEAM-Database.kdbx".
...
(index):12 2019-08-21T08:13:56.439Z [storage-webdav] Loaded /TEAM-Database.kdbx Wed, 21 Aug 2019 07:39:04 GMT 32ms
(index):12 2019-08-21T08:13:56.439Z [sync:TEAM Database] Load from storage {rev: "Wed, 21 Aug 2019 07:39:04 GMT"} no error
(index):12 XHR finished loading: GET "https://example.com/TEAM-Database.kdbx".
(index):12 2019-08-21T08:13:56.454Z [file] File merge error r {name: "KdbxError", code: "MergeError", message: "Error MergeError: Duplicate: AAAAABBBBBCCCCCC"}code: "MergeError"message: "Error MergeError: Duplicate: AAAAABBBBBCCCCCC"name: "KdbxError"__proto__: constructor: ƒ Error()message: ""name: "Error"toString: ƒ toString()__proto__: Object
...
(index):12 2019-08-21T08:13:56.455Z [sync:TEAM Database] Merge complete r {name: "KdbxError", code: "MergeError", message: "Error MergeError: Duplicate: AAAAABBBBBCCCCCC"}
(index):12 2019-08-21T08:13:56.474Z [sync:TEAM Database] Sync finished r {name: "KdbxError", code: "MergeError", message: "Error MergeError: Duplicate: AAAAABBBBBCCCCCC"}code: "MergeError"message: "Error MergeError: Duplicate: AAAAABBBBBCCCCCC"name: "KdbxError"__proto__: Object
```

I use a config.json as follows:
```
{
	"settings": {
		"theme": "fb",
		"autoSave": true,
		"autoSaveInterval": 1,
		"canOpenDemo": false,
		"dropbox": false,
		"gdrive": false,
		"onedrive": false
	},
	"files": [{
		"storage": "webdav",
		"name": "TEAM Database",
		"path": "/TEAM-Database.kdbx"
	}]
}

```

It looks like it actually detected that a new file was on the server. And according to logs, it should have downloaded it, but I couldn't see the user1's changes on the 2nd browser.

Meaning it didn't properly got the latest version of the file. 
Besides, what could `Duplicate: AAAAABBBBBCCCCCC` mean?

Thanks,

**Comment by antelle** [comment]
Hi! How does the second user open this file, also from webdav? Or they are two new files saved into the same location?

**Comment by amine250** [comment]
They both open the same existing file from webdav

**Comment by antelle** [comment]
Does it happen with a new file?

**Comment by amine250** [comment]
Hi @antelle 
I just tried it at home again using a new .kdbx file (that was created by keeweb), I did not reproduce the error.
As you said, the .kdbx we've been using at work has probably a duplicate inside. I'll check tomorrow.
Thanks for your help.

**Comment by antelle** [comment]
Good, please let me know what you find. You can find duplicates if you export your file in xml, search the mentioned id there.

**Comment by amine250** [comment]
@antelle,
It actually was a duplicate in my kdbx. I reopened it using the Keepass Desktop app and it suggested repairing it, which solved the problem.
Sorry and thanks for your time :)
