### ISSUE TITLE
KeePassHTTP-Connector can't link to KeeWeb since 1.9.1

### ISSUE THREAD

**Issue by Erimen** [keeweb/keeweb#1237]
Before the release v1.9.0 all was working fine. This morning I updated KeeWeb and now KeePassHTTP-Connector can't find KeeWeb

What I have 
- Ubuntu 18.04.3 LTS x64 (GNOME v3.28.2)
- KeeWeb v1.9.1
- Module Keewebhttp v0.1.3
- Opera v63.0.3368.35
- KeePassHTTP-Connector v1.0.11

![image](https://user-images.githubusercontent.com/17588040/63429304-f67b1a00-c419-11e9-8e7e-9644a14d6062.png)

Do you have the same issue ?

Edit : I already removed/reinstalled the module Keewebhttp and KeePassHTTP-Connector

**Comment by antelle** [comment]
Hi! Do you have KeeWebHttp plugin installed? Let's see the logs.

**Comment by Erimen** [comment]
Hi, where can I find the logs ?

**Comment by antelle** [comment]
They’re in Settings/General/Advanced

**Comment by Erimen** [comment]
`[DEBUG] 2019-08-22T08:23:23.500Z [plugin-gallery] Loaded cached plugin gallery 9ms
[INFO ] 2019-08-22T08:23:23.502Z [plugin:keewebhttp] Loading plugin with resources js (local)
[DEBUG] 2019-08-22T08:23:23.503Z [storage-plugin-files] Load keewebhttp_plugin.js
[DEBUG] 2019-08-22T08:23:23.507Z [storage-plugin-files] Loaded keewebhttp_plugin.js 3ms
[DEBUG] 2019-08-22T08:23:23.507Z [plugin:keewebhttp] Resource data loaded js 4ms
[DEBUG] 2019-08-22T08:23:23.507Z [plugin:keewebhttp] Resource signature validated js 0ms
[INFO ] 2019-08-22T08:23:23.507Z [plugin:keewebhttp] Installing plugin resources
[DEBUG] 2019-08-22T08:23:23.510Z [plugin:keewebhttp] Plugin script installed 2ms
[DEBUG] 2019-08-22T08:23:23.510Z [plugin:keewebhttp] Plugin settings loaded 0ms
[INFO ] 2019-08-22T08:23:23.510Z [plugin:keewebhttp] Install complete 8ms
[INFO ] 2019-08-22T08:23:23.511Z [plugin-mgr] Loaded 1 plugins 20ms
[INFO ] 2019-08-22T08:23:23.647Z [app] Started in 502ms ¯\_(ツ)_/¯
[INFO ] 2019-08-22T08:23:23.648Z [updater] Next update check will happen in 85582s
[DEBUG] 2019-08-22T08:23:24.049Z [keewebhttp] Server running at http://127.0.0.1:19455/
[INFO ] 2019-08-22T08:23:30.719Z [open:dev] File open request
[INFO ] 2019-08-22T08:23:30.719Z [open:dev] Open file from storage file
[INFO ] 2019-08-22T08:23:30.719Z [open:dev] Stat file
[DEBUG] 2019-08-22T08:23:30.719Z [storage-file] Stat /Path/To/Passwords/dev.kdbx
[DEBUG] 2019-08-22T08:23:30.720Z [storage-file] Stat done /Path/To/Passwords/dev.kdbx 1ms
[INFO ] 2019-08-22T08:23:30.720Z [open:dev] Open file from storage (1566198671469, local 1566198671469)
[INFO ] 2019-08-22T08:23:30.720Z [open:dev] Load from storage
[DEBUG] 2019-08-22T08:23:30.720Z [storage-file] Load /Path/To/Passwords/dev.kdbx
[DEBUG] 2019-08-22T08:23:30.722Z [storage-file] Loaded /Path/To/Passwords/dev.kdbx 1566198671469 1ms
[INFO ] 2019-08-22T08:23:30.722Z [open:dev] Open file from content loaded from storage
[DEBUG] 2019-08-22T08:23:30.722Z [storage-file] Load /Path/To/Keys/dev.kdbx.key
[DEBUG] 2019-08-22T08:23:30.723Z [storage-file] Loaded /Path/To/Keys/dev.kdbx.key 1550220445000 1ms
[INFO ] 2019-08-22T08:23:30.891Z [file] Opened file dev: 167ms, 6000 rounds, 107 kB
[DEBUG] 2019-08-22T08:23:30.892Z [app] Add last open file 4bfb1e8e-3a64-98c7-d88e-63d5813e1ed2 dev file /Path/To/Passwords/dev.kdbx 1566198671469
[DEBUG] 2019-08-22T08:23:30.965Z [storage-file] Watch dir /Path/To/Passwords`

**Comment by Erimen** [comment]
The browser plugin is configured 
![image](https://user-images.githubusercontent.com/17588040/63501341-be341400-c4cb-11e9-8a84-dc63b1e436ef.png)

**Comment by antelle** [comment]
Looks like it can't connect to KeeWeb. Does the browser plugin say that it's connected?

**Comment by Erimen** [comment]
Hello,

Thanks for your time, this morning KeeWeb has update into v1.9.2 and now it's working fine.
Dunno what was causing the issue but the update solved it.

Have a nice week :)
