### ISSUE TITLE
line spacing 

### ISSUE THREAD

**Issue by cognitivedj** [keeweb/keeweb#1239]
**Is your feature request related to a problem? Please describe.**
For a keeweb instance that has a lot of passwords: the amount of information displayed on the screen is limited by the amount of spaces between the horizontal lines.  

**Describe the solution you'd like**
A config.json value that sets the pixel count between the font and the next line in tabuler and list views.  I don't necessarily care about the single selected entry as much, its the lists of larger datasets.

**Describe alternatives you've considered**
Attempted to modify the index.html for px values and line-height, but it didn't seem to work out, and doesn't scale well with updating the versions.

**Additional context**
Out of the box, regardless of the font size (0,1,2) about 50% of the pixels on the screen are in the spacing between lines.    It should be mentioned:
[A previous case was opened regarding a similar line spacing request](https://github.com/keeweb/keeweb/issues/936#issue-327918308)
[Antelle responded with a recommended solution was to setup a plugin:](https://github.com/keeweb/keeweb/issues/936#issuecomment-393339127)

The thing is, this is a basic feature that should be included either in the config.json or in an external css, no?

**Comment by antelle** [comment]
Hi! Now it’s possible to create themes, this seems to be a perfect candidate for that. You can call it something like “compact layout” and adjust different spacing things inside.
