### ISSUE TITLE
autochecking source file before pushing updates

### ISSUE THREAD

**Issue by cognitivedj** [keeweb/keeweb#1240]
**Is your feature request related to a problem? Please describe.**
We purposefully do not autosave our WebDAV files with the clients as we don't want bad changes to be easily propagated.    When a user makes a change, they will go back and sync it back to the server manually.  

Unfortunately, a user may have updates that need to go back and keep those changes for a long time.  Other users may update the keeweb file in the mean time.  Thus, we have entries that can be overridden.

The keystore on the bottom of the screen will add a "button gif" notification that changes were made.  There is no notification method for a user that a file has been updated before their updates are applied.  In fact, keeweb does not tell the user if a newer file is available anywhere--even if going to the settings page.  Although the settings page DOES include the last sync time.

**Describe the possible solutions you'd like**
A few things:
1) Once edits have been made on the local copy, have an auto-check mechanism that the remote source file is newer?  

1B) If the file is newer, then give additional warnings on the bottom icon (make it an exclamation icon versus a dot?)

2) Have keeweb list the last sync time next to the opened key name on the bottom of the screen at all times.  (this lets the user know that their changes are likely stale).  

3) Config option to only allow updating if the source file hasn't been modified since last sync?

4) Allow for a timeout to check if a newer file and request that it be updated first before making changes.   (this autocheck is different than the current implement autoupdate), where one is a RO and the other is a RW.  Personally, we would be fine with the same autoupdate mechansim, but a checkbox to have it RW vs RO.  (set a timeout to autocheck, and then a true/false to autowrite updates or not).

**Describe alternatives you've considered**
Ability to merge individual records is another approach, but that sounds like it would be a lot more complicated.

**Additional context**

**Comment by antelle** [comment]
Hi! This seems to be an attempt to fix symptoms but not the root cause (users save bad changes). KeeWeb is designed in a way that updates should propagate as seamlessly and invisible to the user, as possible.
So, if you fix the main problem and make users not add bad changes, you can enable autosave and it should fix other issues mentioned here.

**Comment by cognitivedj** [comment]
Hello Antelle--

Thanks for taking the time to review this case.  

Also thanks for making the application "just work" 99.99% of the time.  Given this, I agree with the spirit of your response; however, I do offer another vantage point that that goes with the application being seamless/invisible while updating:

Users in an enterprise can have server outages, network outages, or can connect through a VPN connection (that may go down).  Those users maybe working on a project where they need to share passwords and thus update their keeweb.  In fact, keeweb can work with disconnected laptops with configured extended timeouts [ie: if the person needs to take their laptop into the datacenter to deploy new vendor equipment (and a lot of times only external/"internet" wifi available in the datacenter)].

I'm not suggesting advanced merging needs to exist--just mechanism(s) to inform a user that their  update is out of sync with the last synced version.  And in this scenario, the mechanisms should be in place in keeweb for it to do the intelligent thing(s).
