### ISSUE TITLE
A configuration to Allow or Disallow XML export of the kdbx

### ISSUE THREAD

**Issue by amine250** [keeweb/keeweb#1241]
**Is your feature request related to a problem? Please describe.**
It would be nice to be able to disable or enable the Save to XML button

**Describe the solution you'd like**
Just like the canImportXML, we could have a canSaveToXML config parameter

**Describe alternatives you've considered**
A not so proper alternative I found is to replace in the `index.html`, the `"click .settings__file-save-to-xml"`'s value which was the function `saveXML` by any string that doesn't exist as a function name.

**Comment by antelle** [comment]
Deployed to [beta.keeweb.info](https://beta.keeweb.info), will be available in the next release.

**Comment by antelle** [comment]
The bot was misconfigured, sorry for a wrong notification.
