### ISSUE TITLE
Dynamic AutoType for any field

### ISSUE THREAD

**Issue by jivarson** [keeweb/keeweb#1243]
Instead of hijacking OP's thread in #1203, I'm creating a feature request here.

The clipboard in most OS's are insecure and not suitable for the delivery of secrets.
KeeWeb already has an excellent AutoType-implementation which is the foremost reason I use it.

Currently it's easy to autotype username and password dynamically. Other fields has to be set up beforehand.

This sort of limits the use of autotype when there's many secrets for an item.

I'd like AutoType to be more dynamic on this.

### - While in background;
In the dialogue of Global Auto-type, when the correct item is selected, press and hold Shift to browse the items Fields including custom ones. Releasing <Shift> selects and autotypes it.

### - While in foreground:
Holding <Shift> while clicking a Field of an entry autotypes it instead of copying it to clipboard.

**Comment by antelle** [comment]
This makes a lot of sense, however it should be implemented as a soft of field action icons that will appear on hover (which will include copy, auto-type, show/hide password, etc...).

**Comment by jivarson** [comment]
Indeed, it's better to present functionality visually rather than using modifier-keys, this would work in foreground-mode.
But I'd really like to have it accessible via autotype in background as well, without the need of a mouse.

**Comment by antelle** [comment]
Sorry I read it wrong and first time I thought the suggestion was to auto-type on shift-click. So it should be:

- `background` auto-type: right, it should be a new hotkey combo for this, like shift or something else.
- `foreground` auto-type: field icons. Clicking on a field maybe doesn't do anything at all, but doesn't perform auto-type (this would be very unexpected, while copying is somewhat ok, but unexpected too, but it doesn't send the password anywhere).

**Comment by jivarson** [comment]
Correct.
Key-combo is needed in background autotype, while floating icons or something would do it in foreground autotype

**Comment by Coises** [comment]
Dragging and dropping the label works now on Windows.  (I seem to recall being told that it doesn't work on Mac, though.)  For me, at least, that covers the situation where I have room to get both KeeWeb and the target window on screen at the same time, and it avoids taking focus away from the target window once you've located the correct entry in KeeWeb and switched back to the target window.

I use this method all the time for entering data that doesn't fit in the "User/Password" mold.

Not that an auto-type method for non-standard fields wouldn't be good to have... I just wanted to note that there is a solution other than copy/paste that works now given the right conditions.

**Comment by jivarson** [comment]
Awesome work!

**Comment by antelle** [comment]
That's what it will look like in the field options dropdown:  
<img width="307" alt="Screen Shot 2019-09-26 at 23 45 40" src="https://user-images.githubusercontent.com/633557/65727444-0987a680-e0b8-11e9-9da6-e2e5220e9c1e.png">

**Comment by tbradsha** [comment]
I love the addition of other fields in auto-type (background?) mode. One possible regression (or if intentional, an annoyance for me) is that I can no longer simply click on the name of an entry when the auto-type/background mode comes up; I now have to press enter to trigger the normal user/password auto-type.

In normal/foreground mode, I love being able to click the field name itself to copy the field contents.

**Comment by antelle** [comment]
Hm, clicking field name in auto-type popup never copied its content (or it was not supposed to work). To auto-type a specific field, you can select it using the dots button on the right.

**Comment by tbradsha** [comment]
I think there was some confusion. Clicking the field name is only possible in foreground/normal mode. Ignore this; I only brought it up as my preferred alternative to the above screenshot with the "Copy" item in the field options dropdown. :^)

As for the auto-type popup: I used to be on a website, use my auto-type shortcut, and then click the entry I wanted it to auto-type, which would immediately dismiss the auto-type popup and auto-type the username/password, which is all I need in most situations. Now a click on a row does nothing more than select the entry; I have to then press Enter to dismiss the auto-type popup and trigger auto-type of the username/password.
