### ISSUE TITLE
compatibility to other kdbx apps broken?

### ISSUE THREAD

**Issue by bastos77** [keeweb/keeweb#1248]

**Comment by antelle** [comment]
Please answer the questions.

**Comment by bastos77** [comment]
Until some days it has not been a problem to open keeweb created files in other kdbx compatible apps like keepass DX. But since some days apps tell that there is no password set
![Screenshot_2019-09-01-11-36-53](https://user-images.githubusercontent.com/12494783/64074554-05c95580-ccad-11e9-9c4d-06493b060cbf.jpeg)

Created current file in keeweb on Ubuntu 18.04. tried to open in several kdbx apps. Only in keeweb this is successful

**Comment by antelle** [comment]
Does it work in KeePass? Which other apps did you try? Please create a new file that doesn’t open and share it here, let’s see.

**Comment by bastos77** [comment]
Successfully opened the original kdbx in KeePassXC on my main computer (ubuntu 18.04). I synchronize this folder via OwnCloud so I will see at home on my other devices.

**Comment by bastos77** [comment]
Additional information: 
Synchronized via OwnCloud Version 2.5.1 (build 10450) the kdbx can be opened in KeeWeb but not in KeePassX 2.0.2. Error as attachment.
I have produced a new kdbx in KeeWeb 1.9.2 and synchronized it via Owncloud. This file can be opened in KeePassX 2.0.2. without problems
So something in my main kdbx seems to be a little bit corrupt so that only KeeWeb is able to handle it.


![Bildschirmfoto vom 2019-09-02 18-32-37](https://user-images.githubusercontent.com/12494783/64127284-3a263a00-cdb1-11e9-9922-16897e33dd2b.png)

**Comment by antelle** [comment]
Could you please attach an example?

**Comment by antelle** [comment]
Another question: if you copy the same file without OwnCloud, does it work?

**Comment by bastos77** [comment]
> Could you please attach an example?
I can not attach the example (deleted all entries out of the original kdbx) Even not if compressed as zip. So here is the OwnCloud Link: https://x15.id4net.de/owncloud/s/ai9o5QylZp2Jn6h

**Comment by bastos77** [comment]
> Another question: if you copy the same file without OwnCloud, does it work?

I tried several transfer methods. Nothing works. Only KeeWeb is in every case able to open the kdbx.

**Comment by antelle** [comment]
What's the password for this file?

**Comment by bastos77** [comment]
> > Could you please attach an example?
> > I can not attach the example (deleted all entries out of the original kdbx) Even not if compressed as zip. So here is the OwnCloud Link: https://x15.id4net.de/owncloud/s/ai9o5QylZp2Jn6h

kdbx Passwort: test

**Comment by bastos77** [comment]
> What's the password for this file?

test

**Comment by antelle** [comment]
I confirm, my KeePassXC can't open this file. Just created a new [script] that allows to dump file header: https://github.com/keeweb/kdbxweb/blob/master/scripts/dump-header.js

So, here it is for your file:

```
{
    "versionMajor": 4,
    "versionMinor": 0,
    "dataCipherUuid": "McHy5r9xQ1C+WAUhavxa/w==",
    "compression": 1,
    "masterSeed": "LS6eGUQBJbDzGjGZTGQjtS4OZWVQ2UGTdPVsPzKKT+0=",
    "encryptionIV": "UIO9/pczaoMdAO98TNOveQ==",
    "endPos": 207,
    "kdfParameters": {
        "R": 6000,
        "S": "lJQW7789DOI9vFemtV+tuehuBYbyC9/qzNRC8bgXrj4=",
        "$UUID": "ydnzmmKKRGC/dA0IwYpP6g=="
    }
}
```

It's V4 format, which is not supported by KeePassX. If you download a fresh version of KeePassXC, it will be able to open it (just checked on KeePassXC 2.4.3). Also another client, macPass, can open it too.

**Comment by antelle** [comment]
KeeWeb doesn't upgrade files by itself, so I assume it should've been done by something else.

**Comment by bastos77** [comment]
Thanks. Can you advice how to use?

**Comment by antelle** [comment]
You mean, how to downgrade a file in KeePassXC? It's here:
<img width="912" alt="version" src="https://user-images.githubusercontent.com/633557/64129610-6778e500-cdbd-11e9-8ffb-b8445d53a532.png">

**Comment by bastos77** [comment]
Thanks. Will try.
But my question was regarding how to use the script

**Comment by antelle** [comment]
Oh I thought you asked how to change the file format. To use the script, clone kdbxweb repo and launch it [like this](https://github.com/keeweb/kdbxweb/blob/master/scripts/dump-header.js#L13). It will print what I posted in [this comment](https://github.com/keeweb/keeweb/issues/1248#issuecomment-527211170) above on your file (please note that it doesn't require password, it prints only the first header; there's no secret information here).

**Comment by bastos77** [comment]
I think maybe KeePassDX 2.5.0.0 beta22 has upgraded to v4. Now everything is fine again for the time being.

Thank you very much for your prompt and competent support @antelle !
