### ISSUE TITLE
Modify index.html for Keeweb

### ISSUE THREAD

**Issue by bridrod** [keeweb/keeweb#1250]
Is there instructions on how to modify index.html? Right now I need to change the "lock" function to logout by redirecting to another URL, instead of the one where I have to input the password to open the KDBX file. Is it possible?

Thanks,

**Comment by antelle** [comment]
Yes, but you need to build it, the instructions can be found in the readme of this repo. You must be familiar with we development to do that.
About modifying it directly, most likely the best advice is not to do it.

**Comment by bridrod** [comment]
Antelle, thanks for the info. Yeah, unfortunately web development is not my forte. I was hoping to find a "place" in there and could input/replace the lock with my "http://website/logout.php" script to log out completely out of the system and redirect somewhere else. I understand not being a recommended step to edit the index.html file directly (which I did in the past to adjust a couple of settings, customizing to my needs), but like I said, my skills are limited. If there was a way to edit like a find/replace type of situation, I would gladly give it a try! :)

Thanks!

**Comment by antelle** [comment]
There is a place and you can try finding it, but it will be quite challenging.

**Comment by bridrod** [comment]
Haven't lost hope yet. Still fiddling with the index.html file. I thought it would be around this part:

**FROM:**
> {var t="https://login.microsoftonline.com/common/oauth2/v2.0/logout?post_logout_redirect_uri={url}".replace("{url}",this._getOauthRedirectUrl())

**TO:**
> {var t="https://login.microsoftonline.com/common/oauth2/v2.0/logout?post_logout_redirect_uri={https://MYSERVER.DOMAIN.COM/logout}".replace("{https://MYSERVER.DOMAIN.COM/logout}",this._getOauthRedirectUrl())

But that did not work. Hard to "try and error" when you don't understand the code. I have been lucky before, though... :)

**Comment by antelle** [comment]
No, that’s not it. The place you need is this one: https://github.com/keeweb/keeweb/blob/master/app/scripts/views/app-view.js#L477
