### ISSUE TITLE
Autotype types password with special chars wrong

### ISSUE THREAD

**Issue by molikuner** [keeweb/keeweb#1251]
**Describe the bug**
If you have special characters in your password, it will often be typed wrong. The shortest string of characters I could reproduce it with is: `:**`

**To Reproduce**
1. Create an entry with `:**` as password
2. Put the window into the background
3. Initiate autotype for the password
4. Look at the resulting string and see error
5. If you got one of the rare cases where it did worked restart from 3.

**Expected behavior**
The password gets typed like it's defined in the file.

**Environment**
KeeWeb v1.9.2 (54430cd8, 2019-08-22)
Environment: electron v6.0.2
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) KeeWeb/1.9.2 Chrome/76.0.3809.110 Electron/6.0.2 Safari/537.36

**Kdbx File**
Does it happen on Demo or New database?  Yes: [autotype-password.zip](https://github.com/keeweb/keeweb/files/3586919/autotype-password.zip).
If you have a test db without your personal data, please attach it.

**Logs**
```
2019-09-07T18:33:09.601Z [auto-type] Auto type event null
index.html:1 2019-09-07T18:33:09.622Z [auto-type] Get window title
index.html:1 2019-09-07T18:33:09.734Z [launcher] spawn xdotool: 0, 111ms
DummyPage - Firefox Developer Edition
index.html:1 2019-09-07T18:33:09.736Z [auto-type] Window title DummyPage - Firefox Developer Edition null
index.html:1 2019-09-07T18:33:14.687Z [auto-type] Entry selected {entry: r, sequenceType: 0}
index.html:1 2019-09-07T18:33:14.695Z [auto-type] Hide window
index.html:1 [Violation] 'setTimeout' handler took 91ms
index.html:1 2019-09-07T18:33:14.875Z [auto-type] Start {PASSWORD}
index.html:1 2019-09-07T18:33:14.876Z [auto-type] Parsed [op:PASSWORD]
index.html:1 2019-09-07T18:33:14.877Z [auto-type] Resolved [[*,*,*]]
index.html:1 2019-09-07T18:33:15.018Z [launcher] spawn xdotool: 0, 139ms
index.html:1 2019-09-07T18:33:15.152Z [launcher] spawn xdotool: 0, 133ms
index.html:1 2019-09-07T18:33:15.276Z [launcher] spawn xdotool: 0, 123ms
index.html:1 2019-09-07T18:33:15.278Z [auto-type] Complete 403ms
```

**Comment by antelle** [comment]
I tried to reproduce it on ubuntu and xubuntu, and looks like your password is working for me. Which distro was that?

**Comment by molikuner** [comment]
Debian (stretch) with Gnome

**Comment by jivarson** [comment]
I had this too some months back, ran Sabayon with GNOME. Never solved it, however im sure **xdotool** was the one to blame which is used by keeweb. Do you get the correct chars from `xdotool type <xyz>` in a terminal?

**Comment by molikuner** [comment]
Seems like it:
```bash
$ for i in {1..20}; do xdotool type ':**'; xdotool key Return; done
```
```
:**
:**
:**
:(*
Ö*(
Ö(*
:**
Ö(*
Ö(*
Ö**
:**
:**
:((
Ö*(
Ö**
Ö**
Ö**
Ö(*
Ö(*
Ö**
```

**Comment by antelle** [comment]
😞  that's quite disappointing, it means that we should consider other alternatives, preferably native (native modules support is #1253).

**Comment by ptoews** [comment]
I'm having the same issue, but with the @ character. Also caused by xdotool, it replaces it with a `"`. This means that auto type  doesn't work most of the times for me, because it cannot even type in my email address correctly.

**Comment by renyhp** [comment]
I also had the same issue; in my case the @ character was being replaced by `q`.
I solved it with the command `setxkbmap <my locale>`. 
`ls /usr/share/X11/xkb/symbols/` told me which code to use. [Link to source](https://stackoverflow.com/a/36480692/11232160)

**Comment by antelle** [comment]
@molikuner the easiest solution would be understanding why `xdotool` works like this, perhaps for now it's the way to go.

**Comment by molikuner** [comment]
So I invested some time into reading the `xdotool` source code and reading some issues on other projects, which try to achieve the same. Basically the API to type sth. on Linux isn't that friendly.
All those tools/libs (at least all that I found) convert the input string back into a sequence of key presses as this is the only way to produce an input. Looks like `xdotool` has sometimes a problem converting those strings into key presses.
**todo:**
check whether the problem is `xdotool` or the underlying `libxkb` which handles the keyboard layout etc.
**to consider**
is it worth debugging `xdotool` more than this, as `xdotool` natively doesn't support `wayland` and probably never will? We could close this issue by closing #1246 by using an other tool or writing sth. on our own.

**Comment by antelle** [comment]
If there's another tool doing this, with more os coverage and less issues, perhaps we should consider switching it indeed.
Most likely writing something would create more problems than solves.

**Comment by antelle** [comment]
Now we're not using `xdotool` anymore. Let's check if it works on latest KeeWeb, and if it's not, it will be easier to fix now.

**Comment by antelle** [comment]
Other reports similar to this make me think this is not fixed. It's still there? Please let me know and I'll look into it!
