### ISSUE TITLE
Blank screen after password field

### ISSUE THREAD

**Issue by Arty2** [keeweb/keeweb#1257]
**Describe the bug**
Clicking inside the password field in any entry causes black screen. Unfortunately it cannot be replicated faithfully, but bug seems to be caused by the presence of custom themes, eg. theme-arc or theme-mojave.

**To Reproduce**
1. View any entry
2. Click on the password field, or the generate password icon.
3. Click outside the field (or sometimes appears when clicking)
4. The KeeWeb window turns black, and only option to restore the interface is to close the app.

**Expected behavior**

**Environment**
KeeWeb v1.10.0 (1b64dd6d, 2019-09-09)
Environment: electron v6.0.7
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) KeeWeb/1.10.0 Chrome/76.0.3809.139 Electron/6.0.7 Safari/537.36

**Comment by antelle** [comment]
Hi! This seems like a javascript error. Could you please try reproducing it with devtools open (can be opened in Settings > General)?

**Comment by antelle** [comment]
Additional question: are you using argon2?
Please don’t forget to share logs, the issue will be closed if no response is provided.

**Comment by Arty2** [comment]
I'm unsure what **argon2** is, or more specifically where this might have been set.
The error log after the window turning blank and then having to restart seems purged, doesn't display anything before the last time it opened. Dev tools also seem unable to open: clicking on the button does nothing.

Perhaps it's worth noting that the app is not installed under Program Files but on another directory as I do not have admin access on this system.

**Comment by Arty2** [comment]
I'm unsure what **argon2** is, or more specifically where this might have been set.
The error log after the window turning blank and then having to restart seems purged, doesn't display anything before the last time it opened. Dev tools also seem unable to open: clicking on the button does nothing.

Perhaps it's worth noting that the app is not installed under Program Files but on another directory as I do not have admin access on this system.

**Comment by antelle** [comment]
Could you please open devtools and then capture the logs? Logs after restarting won’t help.

**Comment by Arty2** [comment]
> Could you please open devtools and then capture the logs when it fails? Logs after restarting won’t help.

Clicking on *Show dev tools* does nothing unfortunately. May be related?

**Comment by antelle** [comment]
you can also open them with ctrl-F12

**Comment by Arty2** [comment]
Reinstalled to make sure there wasn't anything gone wrong in the process, and still devtools will not open, not even through the shortcut.

Really appreciate your time looking into this; it doesn't make the app unusable as it usually occurs when creating new passwords, but its unpredictability can become annoying.

**Comment by antelle** [comment]
Hm, not opening devtools is very weird. You tried to do it right after start?

**Comment by antelle** [comment]
anyway... let’s check if you have argon2, please open file properties (in file settings tab) and check the last section there.

**Comment by Arty2** [comment]
Correct, right after starting the app and the buttons / shortcut bring no response.

Assuming I am looking at the right place...
`Settings > 🔒 *databasename* ` then into the *Advanced* section:

![image](https://user-images.githubusercontent.com/3519269/65239011-a8c00300-dae6-11e9-9352-1b577907e5d3.png)

**Comment by antelle** [comment]
So, you don't have argon2 enabled, this must be something else...

**Comment by antelle** [comment]
I need help reproducing this. If there's anyone who is able to pause in devtools to debug this issue, please let me know.

**Comment by antelle** [comment]
There's another issue like this: #1263 but with logs, let's close this one as a duplicate.
