### ISSUE TITLE
Random OneDrive prompts

### ISSUE THREAD

**Issue by Arty2** [keeweb/keeweb#1258]
**Describe the bug**
A connect to Microsoft account window pop-ups randomly when the database is stored in OneDrive.

**Environment**
KeeWeb v1.10.0 (1b64dd6, 2019-09-09)
Environment: electron v6.0.7
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) KeeWeb/1.10.0 Chrome/76.0.3809.139 Electron/6.0.7 Safari/537.36

**Comment by antelle** [comment]
Hi! This can happen, because we need to refresh a token from time to time. Does it happen often for you?

**Comment by Arty2** [comment]
After some time on this system, the prompt appears about 2-3 times per day. I unlock the base about 5-6 times per day.  At this point, I would personally caution against using OneDrive; although the base is loaded from cache and you can technically avoid the prompt until you have unlocked it, it tends to urge towards using a weak and easy to remember password for OneDrive. 

Understandably this may be a shortcoming of OneDrive. *Keepass for Android* seems to go away with having to ask for credentials again.

@antelle Really appreciate your time looking into this, I hope it eventually gets fixed or superseded by improvements in OneDrive.

**Comment by antelle** [comment]
This is fixed in v1.14 with other OAuth improvements.
