### ISSUE TITLE
Blank screen while opening or saving database

### ISSUE THREAD

**Issue by DocLM** [keeweb/keeweb#1263]
**Describe the bug**
Clicking "enter button" near password field when unlocking causes a blank screen to appear. Application begin unrensponsive until restart. Also happening while saving the database with a new entry.
It cannot be replicated faithfully, it is not happening every time.

**To Reproduce**
1. Open app
2. Click on password field
3. Enter password
4. Click the button on the right or press enter.

**Expected behavior**

**Screenshots**
https://imgur.com/a/q4wj10L

**Environment**
KeeWeb v1.10.0 (1b64dd6d, 2019-09-09)
Environment: electron v6.0.7
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) KeeWeb/1.10.0 Chrome/76.0.3809.139 Electron/6.0.7 Safari/537.36

**Kdbx File**
Does it happen on Demo or New database?  
If you have a test db without your personal data, please attach it.

**Logs**
Web tools disconnect and 
```
2019-09-18T11:54:56.613Z [plugin-gallery] Loaded cached plugin gallery 2ms
index.html:1
2019-09-18T11:54:56.614Z [plugin:language-italian] Loading plugin with resources loc (local)
index.html:1
2019-09-18T11:54:56.615Z [plugin:theme-nord] Loaded inactive plugin
index.html:1
2019-09-18T11:54:56.615Z [plugin:haveibeenpwned] Loading plugin with resources js, css (local)
index.html:1
2019-09-18T11:54:56.615Z [storage-plugin-files] Load language-italian_it-IT.json
index.html:1
2019-09-18T11:54:56.615Z [storage-plugin-files] Load haveibeenpwned_plugin.js
index.html:1
2019-09-18T11:54:56.615Z [storage-plugin-files] Load haveibeenpwned_plugin.css
index.html:1
2019-09-18T11:54:56.616Z [storage-plugin-files] Loaded language-italian_it-IT.json 0ms
index.html:1
2019-09-18T11:54:56.616Z [plugin:language-italian] Resource data loaded loc 1ms
index.html:1
2019-09-18T11:54:56.616Z [storage-plugin-files] Loaded haveibeenpwned_plugin.css 1ms
index.html:1
2019-09-18T11:54:56.616Z [plugin:haveibeenpwned] Resource data loaded css 1ms
index.html:1 
2019-09-18T11:54:56.616Z [storage-plugin-files] Loaded haveibeenpwned_plugin.js 1ms
index.html:1 
2019-09-18T11:54:56.616Z [plugin:haveibeenpwned] Resource data loaded js 1ms
index.html:1
2019-09-18T11:54:56.617Z [plugin:language-italian] Resource signature validated loc 1ms
index.html:1 
2019-09-18T11:54:56.617Z [plugin:language-italian] Installing plugin resources
index.html:1 
2019-09-18T11:54:56.617Z [plugin:language-italian] Plugin locale installed
index.html:1 
2019-09-18T11:54:56.617Z [plugin:language-italian] Install complete 3ms
index.html:1 
2019-09-18T11:54:56.617Z [plugin:haveibeenpwned] Resource signature validated css 1ms
index.html:1 
2019-09-18T11:54:56.617Z [plugin:haveibeenpwned] Resource signature validated js 1ms
index.html:1 
2019-09-18T11:54:56.617Z [plugin:haveibeenpwned] Installing plugin resources
index.html:1 
2019-09-18T11:54:56.618Z [plugin:haveibeenpwned] Plugin style installed
index.html:1 
2019-09-18T11:54:56.620Z [plugin:haveibeenpwned] Plugin script installed 2ms
index.html:1 
2019-09-18T11:54:56.620Z [plugin:haveibeenpwned] Plugin settings loaded 0ms
index.html:1 
2019-09-18T11:54:56.621Z [plugin:haveibeenpwned] Install complete 6ms
index.html:1 
2019-09-18T11:54:56.621Z [plugin-mgr] Loaded 3 plugins 11ms
index.html:1 
2019-09-18T11:54:56.725Z [app] Started in 493ms ¯\_(ツ)_/¯
index.html:1 
2019-09-18T11:54:56.725Z [updater] Next update check will happen in 65326s
index.html:1
Failed to decode downloaded font: data:font/woff2;base64,
index.html:1 
2019-09-18T11:55:05.036Z [open:KeePass] File open request
index.html:1 
2019-09-18T11:55:05.036Z [open:KeePass] Open file from storage file
index.html:1 
2019-09-18T11:55:05.036Z [open:KeePass] Stat file
index.html:1 
2019-09-18T11:55:05.037Z [storage-file] Stat <REDACTED>.kdbx
index.html:1 
2019-09-18T11:55:05.038Z [storage-file] Stat done <REDACTED>.kdbx 1ms
index.html:1 
2019-09-18T11:55:05.038Z [open:KeePass] Open file from storage (1568806121718, local 1568806121718)
index.html:1 
2019-09-18T11:55:05.038Z [open:KeePass] Load from storage
index.html:1 
2019-09-18T11:55:05.038Z [storage-file] Load <REDACTED>s.kdbx
index.html:1 
2019-09-18T11:55:05.040Z [storage-file] Loaded <REDACTED>.kdbx 1568806121718 1ms
index.html:1 
2019-09-18T11:55:05.040Z [open:KeePass] Open file from content loaded from storage
index.html:1 
2019-09-18T11:55:05.105Z [argon2] WebAssembly runtime loaded 61ms
```

**Comment by antelle** [comment]
Hi!
Interesting, looks like argon2 didn’t work. Could you please share your KDF parameters (the last section of file settings)?

**Comment by antelle** [comment]
#1257 can be related

**Comment by DocLM** [comment]
> Hi!
> Interesting, looks like argon2 didn’t work. Could you please share your KDF parameters (the last section of file settings)?

Of course
- Iterations: 10
- Memory: 4096KB
- Parallelism: 4

**Comment by antelle** [comment]
That's 4MB, not that high. Would you be able to click pause in devtools when this happens, and capture the stack trace? The problem is, it doesn't freeze for me...

**Comment by DocLM** [comment]
> That's 4MB, not that high. Would you be able to click pause in devtools when this happens, and capture the stack trace? The problem is, it doesn't freeze for me...

Already tried but when happens the dev tool interface says that is not connected and will connect again when I'll reload the app.
No stack trace available, also by setting "stop on exception" in the debugger interface.
The log attached to the issue was collected after the crash, with all message levels activated

> The problem is, it doesn't freeze for me...
It is not happening every time, sometimes works and sometimes not.

**Comment by antelle** [comment]
Very interesting, thanks for sharing all the info. Not sure what to do with it though, I'm running the same macOS, electron, and keeweb version and use it several times per day, however it doesn't freeze for me.
How big is your password file? Does it happen on a new database?

**Comment by antelle** [comment]
Does it crash, as in, does the process dies? Normally if you search KeeWeb in Activity Monitor, you should see something like this:
<img width="184" alt="image" src="https://user-images.githubusercontent.com/633557/65264773-a4f4a680-db0f-11e9-9f97-90987a3ca2e1.png">

**Comment by DocLM** [comment]
> Does it crash, as in, does the process die? Normally if you search KeeWeb in Activity Monitor, you should see something like this:
> <img alt="image" width="184" src="https://user-images.githubusercontent.com/633557/65264773-a4f4a680-db0f-11e9-9f97-90987a3ca2e1.png">
> 
> If it dies, we can debug a crashdump.

When a crash occour only KeeWeb and Keeweb Helper (GPU) survive.

There is a log in ~/Library/Logs/DiagnosticReports relative to KeeWeb Helper (Render)

[KeeWeb Helper (Renderer)_2019-09-19-202209_MacBook.crash.log](https://github.com/keeweb/keeweb/files/3632690/KeeWeb.Helper.Renderer._2019-09-19-202209_MacBook.crash.log)

From what I can see there is a SEG_FAULT

**Comment by antelle** [comment]
So, it's a crash, nice, I'll submit it to Electron. Do you have any anti-virus software running?

**Comment by DocLM** [comment]
No, I'm not running something that interferes with other processes.

**Comment by antelle** [comment]
Strange. I wonder why it doesn't do it on my mac. If you can reproduce it, would you mind running a debug version of Electron? Looks like I need to [build](https://electronjs.org/docs/development/debugging-instructions-macos) it to be able to get anything useful from the crashdump.

**Comment by DocLM** [comment]
> Strange. I wonder why it doesn't do it on my mac. If you can reproduce it, would you mind running a debug version of Electron (I can make a build with it)? Looks like I need to [build](https://electronjs.org/docs/development/debugging-instructions-macos) it to be able to get anything useful from the crashdump.

If you can provide a debug build I'll take a look

**Comment by antelle** [comment]
Hm, looks like building electron is harder than I expected (because you basically need to build Chromium).

**Comment by ccwang002** [comment]
I had this issue as well using KeeWeb v1.9 and above using KDBX4/Argon2 on macOS. Sometimes, the database can be open for first time, but it becomes a blank screen afterwards. v1.8.2 seems to be the most recent version that doesn't have this issue.

Thanks for making this great tool. I've used it since 2016 and I'd like to help.

**Comment by antelle** [comment]
I'll try to make a debug build for testing this. Meanwhile any help with debugging is appreciated.

**Comment by deolivec** [comment]
Hello, I have exactly the same issue. When i switch back to AES algorithm, keeweb never hangs after password validation.

KeeWeb v1.11.5 (e8e2b499, 2019-09-29)
Environment: electron v6.0.10
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) 

Best regards

**Comment by labianchin** [comment]
Also experiencing the same issue, when opening a argon2 based database. 

Version 1.11.8 (0fabdac9)


```
2019-10-14T09:05:28.516Z [open:myfile1] File open request
index.html:1 2019-10-14T09:05:28.516Z [open:myfile1] Open file from storage file
index.html:1 2019-10-14T09:05:28.516Z [open:myfile1] Stat file
index.html:1 2019-10-14T09:05:28.517Z [storage-file] Stat /Users/me/myfile1.kdbx
index.html:1 2019-10-14T09:05:28.519Z [storage-file] Stat done /Users/me/myfile1.kdbx 2ms
index.html:1 2019-10-14T09:05:28.519Z [open:myfile1] Open file from storage (1569965069751, local 1569965069751)
index.html:1 2019-10-14T09:05:28.519Z [open:myfile1] Load from storage
index.html:1 2019-10-14T09:05:28.520Z [storage-file] Load /Users/me/myfile1.kdbx
index.html:1 2019-10-14T09:05:28.525Z [storage-file] Loaded /Users/me/myfile1.kdbx 1569965069751 6ms
index.html:1 2019-10-14T09:05:28.526Z [open:myfile1] Open file from content loaded from storage
index.html:1 2019-10-14T09:05:28.682Z [argon2] WebAssembly runtime loaded 147ms
index.html:1 2019-10-14T09:05:31.031Z [argon2] Hash computed 2348ms
```

**Comment by antelle** [comment]
Now, on macOS Catalina, I can reproduce it. Exactly the same log as @labianchin posted, then the same segfault in the crashdump as in @DocLM's above. I'd say, it's quite stable, as in, if I open a db 10 times, it will happen. So, now I need to build electron (unfortunately they don't have debug builds available)...

**Comment by antelle** [comment]
I need to say, I managed to repeat it on Chrome, it also crashes, but less than Electron, however the issue is most likely originating there, which means, it will be quite a challenge to debug 😬

**Comment by antelle** [comment]
I made some further steps in debugging this. This seems to be a bug in the implementation of WebAssembly in WebWorkers. If we don't kill the worker, it won't crash (but that's not a solution because it will you all your memory of course). I would assume it's a fuckup in Chrome's implementation of memory management, something like double free or so.
Meanwhile I'm trying different things to find a workaround for this.

**Comment by antelle** [comment]
Good, it doesn't crash if we do everything without a web worker. However I don't know how to release the memory used by WebAssembly, that's the biggest question for now.

**Comment by antelle** [comment]
This should be fixed now. 🎉
Please let me know if v1.11.10 works well for you.

**Comment by idpaterson** [comment]
Switched back to argon2 and all attempts to reopen the DB have succeeded!

**Comment by labianchin** [comment]
Thanks @antelle !

Really appreciate your work on KeeWeb and your response in this issue.
