### ISSUE TITLE
Website/URL Field and cmd://

### ISSUE THREAD

**Issue by bhandeland** [keeweb/keeweb#1264]
I'm unsure if I'm doing something wrong, or if the URL field in keeweb doesn't allow execution of a command.  From the documentation in keepass (https://keepass.info/help/base/autourl.html), the URL field will allow cmd:///path/to/executable to run.  However, in keeweb, this doesn't appear to work.

It would be nice to be able to execute external programs. Specifically, I want to call firefox with certain command line flags and pass a custom URL to it.

I've not been able to find any workarounds or solutions.  Any recommendations would be appreciated (short of using keepass).

Using the URL field to call external programs will help tremendously in integrating with my web browser and other utilities.

**Comment by antelle** [comment]
Currently not supported, #284
