### ISSUE TITLE
OneDrive access error when logged in in private and business account

### ISSUE THREAD

**Issue by Sajito** [keeweb/keeweb#1265]
**Describe the bug**
I have a private microsoft account and a business office365 account. I'm logged in into both accounts in my browser, so when I need to login into any app using microsoft login I get to see a page to select which account I want to connect to.
But when I try to use OneDrive access in KeeWeb for some reason it always automatically tries to connect to my business account, where KeeWeb is not registered, which leads me to an error page from microsoft telling me exactly that the application can't have access, because it's not registered.
I know it's not registered and I don't want to register it, as I only want to access my private OneDrive.

**To Reproduce**
Might be hard to reproduce without office365. You need a simple free "@outlook" account for microsoft. Also you need an office365 account where KeeWeb is not registered in the azure settings.
1. Login to your private microsoft account
2. Go to office365 and login to the office365 account
3. Go to KeeWeb and try to use OneDrive sync

**Expected behavior**
I should get asked which account I want to use. Instead it automatically tries to connect to the office365 account.

**Screenshots**
Here is a screenshot of the error I get to see:
![grafik](https://user-images.githubusercontent.com/6151929/65216932-d0957380-dab2-11e9-912a-2bd5980f6dbc.png)

**Environment**
Tried on Firefox 69 and Firefox 70 beta, as well as on Firefox for Android.

**Comment by Stephan-P** [comment]
I've been experiencing this too with my Vivaldi browser. On a limb, I've just tried the same with the Android DuckDuckGo browser and lo and behold: I managed to pass the login name and password entry. I had not gotten as far before.
Unfortunately it all ended there with a blanc screen, but hey it appears that the browser is playing a big file here. 
Maybe this is a clue?

**Comment by Stephan-P** [comment]
Another test with Edge Chromium Beta: Keeweb perfectly opens the OneDrive login allowing me to enter the login name (account name) myself and fetch my kbdx file from my personal OneDrive.

**Comment by Sajito** [comment]
@Stephan-P have you logged in in both - personal and business account - in your browser, before trying the OneDrive login?
If you have no active session on microsoft with any business account, then this error won't appear.

@antelle I think I have figured out how to solve this. Basically the client id has to be updated.
I logged in with my @outlook.de email on portal.azure.com. On the left side select `Azure Active Directory`, then `App registrations`. Register a new application here. On supported account types allow organization and personal accounts as you can see on this screenshot:
![grafik](https://user-images.githubusercontent.com/6151929/66707301-a98f3200-ed3e-11e9-9488-206de8034d6a.png)

Then just update the client id with the newly created client id. This should solve the issue. At least it did in my local testing.

**Comment by antelle** [comment]
@Sajito that's what is set there:
<img width="833" alt="Screen Shot 2019-10-12 at 23 02 29" src="https://user-images.githubusercontent.com/633557/66707681-9aab7e00-ed44-11e9-8887-2e2ceed69bf0.png">

**Comment by Sajito** [comment]
That's weird. With current client id when I try to access OneDrive while having an active session with business and personal account, then I get the error I described.
I went into my own azure portal, created the app as I described and set the needed permissions. When I replace the client id with the one I created, then on the microsoft page I get to choose which account I want to use.

The created client id is this one: 18ea017b-dde6-4e46-bf33-7586da82f7e5
The client id is just shared, if you want to test it. I will delete the registered application soon.

I don't know why, but your client id is also much shorter than my client id.

**Comment by olopez123** [comment]
Can you tell me how to configure correctly from the beginning?
There is no way to make it work with business accounts.
I have configured the app in Azure, but it doesn't work.

**Comment by Stephan-P** [comment]
@Sajito said: If you have no active session on microsoft with any business account, then this error won't appear.

Alright, I made a deliberate effort signing off from the business Office365 account, including the recommended browser restart. After that Keeweb - OneDrive did give me the option to select my personal Microsoft account and I was able to fetch the desired .kbdx.

So, Sajito is correct, but it's quite a hassle to have to log off from your business O365 account and to restart the browser to be able to make it work.

**Comment by javims90** [comment]
Hi @Stephan-P:

- Has office 365 business worked for you?
- Can you explain how the business account configuration is done, please.

Hi @antelle:
Show me this error can you help me or explain from the beginning how the record is created to the end please. Thank you.
![Error code](https://user-images.githubusercontent.com/63070104/78551903-c8aae000-7806-11ea-9698-4660e85bb026.jpg)

**Comment by Stephan-P** [comment]
The Windows Installer app (v.1.13.1) on my Desktop PC which has its user account associated with a personal Microsoft account, automatically connects to my personal OneDrive and opens the vault in good order.
The web app on my browser, which is logged in at my Office365-Educational account, cannot connect to any OneDrive and issues an error message.
![image](https://user-images.githubusercontent.com/10008599/78559252-56d99300-7814-11ea-9474-941e599d1764.png)

So, the Installer version of KeeWeb works for me, the online app doesn't.

**Comment by javims90** [comment]
Hi @Stephan-P,
Then we are the same, because the desktop and web versions work correctly with my personal account, but with the professional account it doesn't work.
We hope you can help us @antelle

**Comment by javims90** [comment]
@Sajito Has the application worked with your business account?

**Comment by Sajito** [comment]
Not working as long as I have an active session in business account.

**Comment by Stephan-P** [comment]
Checking the release notes of alternative password managers such as Enpass and Keepass2Android I noticed specific mention of "Onedrive business support".
Maybe there IS something very special to be done for this, otherwise it would not be worth the mentioning. Possibly you could make use of some lessons learned at the Keepass2Android project?

**Comment by Stephan-P** [comment]
I get the impression van v1.14.0 has resolved this issue.
After the update, I received a new authentication request where Ii was able to select the applicable account, be it my personal outlook.com account or my business O365 account. Perfect!

**Comment by antelle** [comment]
Right, in v1.14 we open the authentication screen in the system-default browser, great to hear that it fixed this issue as well!

**Comment by saulobejo** [comment]
@antelle @Stephan-P 

Regarding the onedrive business and Azure Active Directory for self-hosted web instances.

I've managed to make it run in my tenant. 

With those two changes you can have a instance of KeeWeb exclusive to your tenant, not multi-tenant.

The solution is:

1) Request the tenant id from the user (I put it in the JSON together with the rest of the onedrive information).
<https://github.com/keeweb/keeweb/blob/1d61c6ca03e4c2d489d7c01f48bbd7d9ee6a3da5/app/scripts/const/cloud-storage-apps.js#L32>

2) Replace the OAuth URL from `microsoftonline.com/common/` to `microsoftonline.com/TENANT ID/`
<https://github.com/keeweb/keeweb/blob/0e1b08609683fdcaf29faed48c8753668d4ebff9/app/scripts/storage/impl/storage-onedrive.js#L238-L239>

If you don't want to change in the source, you can change in the gh-page but the process is more involved as it needs to do string replace in the html file and fix the CSP hash for the javascript.

**Comment by antelle** [comment]
The first one can be replaced using the config. I can also add a property for the token url, didn't know it was needed.

**Comment by saulobejo** [comment]
@antelle that's the tanant id, not the client id. I didn't see any option in the config file to change it.

if this option can be in the config file and dynamically changed between common (for people using the shared keeweb tenant `bbc74d1b-`) and tenant's id itself for people using any other tenant, this would be great.

**Comment by antelle** [comment]
You mean the first one? 

<https://github.com/keeweb/keeweb/blob/1d61c6ca03e4c2d489d7c01f48bbd7d9ee6a3da5/app/scripts/const/cloud-storage-apps.js#L32>

It's actually the client id, that's how it's used:

<https://github.com/keeweb/keeweb/blob/1d61c6ca03e4c2d489d7c01f48bbd7d9ee6a3da5/app/scripts/storage/impl/storage-onedrive.js#L230>

It's configurable as `oneDriveClientId`. 

About the tenant id, you're right, it's not configurable and it should be very easy to add it. The only place where the tenant id should be used is `common` in urls, right?

**Comment by saulobejo** [comment]
@antelle 
sorry. i mistook it for the tenantid then.

and regarding your second question, yes, should replace common whenever it is defined.

the thing is, your wiki is correct.

if you configure as `multitenant`, you can leave the URL as `common`.
but if you configure as `single-tenant`, you have to replace `common` by `tenantId`

**Comment by antelle** [comment]
Okay good, thanks for the explanation! I'll add a config option then.
