### ISSUE TITLE
OneDrive Personal Vault

### ISSUE THREAD

**Issue by stophix** [keeweb/keeweb#1266]
**Is your feature request related to a problem? Please describe.**
In June 2019, Microsoft added the Personal Vault feature to OneDrive. The feature should enhance security by requesting 2FA when trying to access the folder. I was wondering if the Personal Vault could be integrated in the KeeWeb desktop app. As of yet, it is not possible to select the Vault-folder via the GUI.

**Describe the solution you'd like**
Choosing the Personal Vault-Folder as a source when selecting the location of the database-file.

**Additional context**
I'm not entirely sure whether this implementation is possible at all. I'd love to hear whether this could be an idea worth pursuing. If not, feel free to educate me! Anyways, a big thanks to all the KeeWeb contributors, great app!

**Comment by Riajyuu** [comment]
Just give a try with some other apps that implement OneDrive API ( 2yrs of Office 365 users already).
The answer is impossible. That directory is **NEVER** assesible through any third-party API, not even you unlock it at the first place.

**Comment by antelle** [comment]
Thanks @Riajyuu!

**Comment by stophix** [comment]
Thanks for answering!
