### ISSUE TITLE
Password for new database not being saved on creation

### ISSUE THREAD

**Issue by DiegoFleitas** [keeweb/keeweb#1270]
**Describe the bug**
When creating a new database for KeePass Desktop for Windows, even though the Master password field a the confirmation field are filled, the password is interpreted as emtpy

**To Reproduce**
1. Install KeeWeb-1.11.0.win.x64
2. Click on 'New'
3. Click on the database name
4. Fill master password and confirmation
5. Click on save to
6. Click on File

**The empty password alert pops up**

**Expected behavior**
Password should not be read as empty every time

**Screenshots**
![image](https://user-images.githubusercontent.com/15369935/65821655-c9870780-e20e-11e9-98e4-a28c4180dead.png)

**Environment**
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36

**Kdbx File**
Does it happen on Demo or New database?  
If you have a test db without your personal data, please attach it.

**Logs**
Please open dev tools in your browser and attach output log from Console tab. If you are using a desktop app, devtools can be opened from Settings/General/Advanced.

**Comment by DiegoFleitas** [comment]
I´m unable to reproduce this bug with the version KeeWeb-1.11.0.win.x64 so I think it was introduced with the new one

**Comment by antelle** [comment]
Thanks, will be fixed soon

**Comment by antelle** [comment]
The fix is rolled out

**Comment by DiegoFleitas** [comment]
Thanks, it's fixed now
