### ISSUE TITLE
Plugin problem in v1.11.0 (self-hosted)

### ISSUE THREAD

**Issue by xesarni** [keeweb/keeweb#1271]
**Describe the bug**
Loading language plugins via the config file breaks (Error loading app) v1.11.0 (self-hosted).

**To Reproduce**
Run a self-hosted version with a config file that loads a plugin.

**Expected behavior**
v1.10.1 runs fine, v11.0 should run fine too.

**Environment**
Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:70.0) Gecko/20100101 Firefox/70.0

**Logs**
From Firefox's console:
[app] Error starting app TypeError: "({url:"https://plugins.keeweb.info/translations/pl"}) is not a function"

**Comment by antelle** [comment]
Thanks, the fix it on its way, will be released in some minutes.

**Comment by antelle** [comment]
The fix is rolled out

**Comment by xesarni** [comment]
Thanks!
