### ISSUE TITLE
WebAssembly Error while using KDBX4 Argon2

### ISSUE THREAD

**Issue by ccwang002** [keeweb/keeweb#1272]
**Describe the bug**
Save or open a KDBX4 local database using Argon 2 will fail due to WebAssembly error. However, KDBX3/4 with AES seems to work fine, as in, I can save the same database successfully.

**To Reproduce**
On a new database:
1. Create a new database with one entry and a master password
2. Select file format as KDB4 with Argon2 (default parameters)
3. Save to a local file
4. Get Sync Error: WebAssembly error and no file is created

Open any existing KDB4/Argon2 database fails with the same WebAssembly error.

**Screenshots**
![Screen Shot 2019-09-28 at 4 15 29 PM](https://user-images.githubusercontent.com/1544283/65822533-7d869380-e20b-11e9-89bf-2d97e2216bfd.png)

**Environment**
KeeWeb v1.11.1 (326b9658, 2019-09-28)
Environment: electron v6.0.10
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) KeeWeb/1.11.1 Chrome/76.0.3809.146 Electron/6.0.10 Safari/537.36

**Logs**
[devtools.log](https://github.com/keeweb/keeweb/files/3666008/devtools.log)

**Comment by antelle** [comment]
Thanks, fixed it, will build a release tomorrow morning.

**Comment by antelle** [comment]
The fix is rolled out
