### ISSUE TITLE
Untranslated Systray menu

### ISSUE THREAD

**Issue by Stephan-P** [keeweb/keeweb#1273]
**Describe the bug**
The Systray menu of the desktop version of Keeweb is not translated

**To Reproduce**
1. Install Keeweb desktop version + Dutch language extension
2. In settings, enable Close app to Systray and enable Dutch language
3. Close app (to systray)
4. RMB click the systray icon and see menu including "Open KeeWeb" and "Quit KeeWeb"
5. Please note that the Dutch translation is 100% completed. These two menu items do not exist in the KeeWeb Translation Center.

**Expected behavior**
I would expect to see the menu in Dutch language: "KeeWeb openen" and "KeeWeb afsluiten"

**Environment**
KeeWeb v1.11.1 (326b9658, 2019-09-28)
Environment: electron v6.0.10
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) KeeWeb/1.11.1 Chrome/76.0.3809.146 Electron/6.0.10 Safari/537.36

**Comment by antelle** [comment]
Done, now we have two new phrases for this.

**Comment by Matthaiks** [comment]
More issues: 
1. A new database gets an English name "New".
2. "Trash" is translated but in a new database it's saved as "Recycle Bin" (this name is visible in KeePass).

**Comment by antelle** [comment]
Added a string for "New", thanks.

**Comment by Stephan-P** [comment]
close this issue?

**Comment by antelle** [comment]
It will be closed automatically when it’s released.

**Comment by Matthaiks** [comment]
BTW, some strings from v1.12.0 cannot be translated at OneSky: "No Phrases can be found".

**Comment by antelle** [comment]
@Matthaiks I'm not sure what you mean, do you have an example?

**Comment by Matthaiks** [comment]
![KeeWeb Translation Center](https://user-images.githubusercontent.com/3577122/67626278-41197800-f849-11e9-937b-bd856b7345fd.png)

**Comment by antelle** [comment]
I guess, it's because everything is translated.

**Comment by Matthaiks** [comment]
Found 2 of 4:
Markdown in notes
Generate (in the main menu)

**Comment by antelle** [comment]
Interesting. Which language is it?

**Comment by Matthaiks** [comment]
Polish.

**Comment by antelle** [comment]
I imported a file once again, but it looks like it doesn't change anything. For some languages there are more phrases marked as "Not Translated" than the filter actually gives when applied...

**Comment by antelle** [comment]
Yeah, the same for other languages, e.g. German. I have no idea why it's like this, probably sort of a bug in OneSky.

**Comment by Matthaiks** [comment]
It's fixed and, of course, "Markdown in notes" + "Generate" = 4 phrases, so that's all.

**Comment by antelle** [comment]
Oh they mean “4 **words**”? Didn’t know that, but looks like this, right! In total it’s 2k+, much more than the number of phrases.

**Comment by Matthaiks** [comment]
Or maybe there's a bug. ;-)

**Comment by Matthaiks** [comment]
v1.14.0
New English-only strings:
![kwen](https://user-images.githubusercontent.com/3577122/79636702-e4ed3c00-8179-11ea-9a74-44b48b617c8b.png)

**Comment by antelle** [comment]
They're coming

**Comment by Matthaiks** [comment]
Missing string for "Lock":

![1](https://user-images.githubusercontent.com/3577122/119991476-c8047880-bfc9-11eb-982e-9cc19418bdb8.png)
![2](https://user-images.githubusercontent.com/3577122/119991478-c89d0f00-bfc9-11eb-8c8c-805c351815f5.png)

KeeWeb v1.18.6 (070573e, 2021-05-19)
Environment: web
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:88.0) Gecko/20100101 Firefox/88.0

**Comment by antelle** [comment]
Thanks! added #1833

Better to post it as a new issue, so that I can track, plan it, and so on. Probably I need a bot that locks old issues, kind of my fault, I'll integrate it soon.
