### ISSUE TITLE
Crash after updating to 1.11.1 on elementary OS

### ISSUE THREAD

**Issue by Appeltabak** [keeweb/keeweb#1274]
**Describe the bug**
I'm using the desktop app and I was notified by the bell icon that there was an update, so I clicked the button to update. The window closed and after a second an error message popped up (see 'screenshots'). Unfortunately, KeeWeb won't start after closing this error dialog.

**To Reproduce**
I'm using elementary os 5.0 juno.
1. Go to the updates page on the desktop app
2. Click on the update button
3. See a error dialog appear
4. Try to start KeeWeb

**Expected behavior**
No error message and able to start an updated KeeWeb.

**Screenshots**
![Screenshot from 2019-09-29 10 03 53](https://user-images.githubusercontent.com/6260588/65829176-a27a1580-e2a2-11e9-9fb5-6a664d831d14.png)

**Environment**
Unfortunately, I'm unable to retrieve, because KeeWeb won't start

**Kdbx File**

**Logs**
Unfortunately, I'm unable to give some logs, because KeeWeb won't start

**Comment by antelle** [comment]
Hi! Could you please post the contents of app.asar here? Looks very weird, maybe it was not downloaded properly?

**Comment by antelle** [comment]
Also, from which version did you upgrade?

**Comment by Appeltabak** [comment]
I rebooted my system and could start KeeWeb again, it's on latest version (1.11.1). Maybe I was too fast to report this :sweat_smile: 

I upgraded from 1.10.1. Still worth to share the contents of `app.asar`?

**Comment by antelle** [comment]
I see, v1.10 had issued with the updater, they were fixed in v1.11. No, it doesn't make sense to share it, I know what it is.

**Comment by antelle** [comment]
It's #1256
