### ISSUE TITLE
Can not show app on mac: TypeError: Cannot read property 'titlebarStyle' of undefined

### ISSUE THREAD

**Issue by yaoxinghuo** [keeweb/keeweb#1275]
Can not show app on mac for the second time: 
TypeError: Cannot read property 'titlebarStyle' of undefined

**To Reproduce**
1. Open KeeWeb and unlock database and click 'close' (Do not use Cmd+Q)
2. Click Dock Icon or any other way to reopen KeeWeb 
3. See error:

**Screenshots**
![image](https://user-images.githubusercontent.com/69723/65829281-53e66e80-e2d6-11e9-86c3-d8da02c1a435.png)

**Environment**
MacOS 10.14.6
KeeWeb 1.11.2

**Logs**
Uncaught Exception:
TypeError: Cannot read property 'titlebarStyle' of undefined
    at createMainWindow (/Applications/KeeWeb.app/Contents/Resources/app.asar/app.js:164:36)
    at App.<anonymous> (/Applications/KeeWeb.app/Contents/Resources/app.asar/app.js:82:13)
    at App.emit (events.js:200:13)

**Comment by antelle** [comment]
Fixed, will roll it out today, meanwhile you can use ⌘H.

**Comment by antelle** [comment]
The fix is rolled out

**Comment by yaoxinghuo** [comment]
It works now, Thanks!
