### ISSUE TITLE
AutoType doesn't open AutoType window in locked state

### ISSUE THREAD

**Issue by molikuner** [keeweb/keeweb#1278]
**Describe the bug**
1.11.3 (maybe 1.11+, didn't tested those other versions much)
After locking the DB (timeout or manually) and opening AutoType with key bind I get asked for the password (expected), but after unlocking I'm in the normal screen and not in the AutoType screen.

**To Reproduce**
1. Lock your DB
2. Minimize/Hide the window
3. Initiate AutoType
4. Unlock your DB
5. See the "normal" screen, instead of the AutoType screen

**Expected behavior**
AutoType screen is presented, even after unlocking again

**Environment**
KeeWeb v1.11.3 (bece4a44, 2019-09-29)
Environment: electron v6.0.10
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) KeeWeb/1.11.3 Chrome/76.0.3809.146 Electron/6.0.10 Safari/537.36

**Logs**
```
[DEBUG] 2019-09-29T13:13:21.001Z [auto-type] Auto type event null
[DEBUG] 2019-09-29T13:13:21.010Z [auto-type] Getting window info
[INFO ] 2019-09-29T13:13:21.054Z [launcher] spawn xdotool: 0, 44ms
Sign in to GitHub · GitHub - Firefox Developer Edition
16777219
[DEBUG] 2019-09-29T13:13:21.055Z [auto-type] Window info Sign in to GitHub · GitHub - Firefox Developer Edition 16777219 null
[DEBUG] 2019-09-29T13:13:21.055Z [auto-type] auto-type event delayed
[INFO ] 2019-09-29T13:13:22.777Z [open:New] File open request
[INFO ] 2019-09-29T13:13:22.778Z [open:New] Open file from cache as main storage
[DEBUG] 2019-09-29T13:13:22.778Z [storage-cache] Load 1536fa66-3583-a197-cafa-70170f635f81
[DEBUG] 2019-09-29T13:13:22.784Z [storage-cache] Loaded 1536fa66-3583-a197-cafa-70170f635f81 6ms
[INFO ] 2019-09-29T13:13:22.784Z [open:New] Loaded file from cache null
[INFO ] 2019-09-29T13:13:23.021Z [file] Opened file New: 235ms, 300000 rounds, 2 kB
[DEBUG] 2019-09-29T13:13:23.022Z [app] Add last open file 1536fa66-3583-a197-cafa-70170f635f81 New null "" null
[DEBUG] 2019-09-29T13:13:35.236Z [auto-type] auto-type event cancelled
```

**Comment by antelle** [comment]
Thanks, fixed it, rolled out an update.
