### ISSUE TITLE
New Version not working

### ISSUE THREAD

**Issue by ci2014** [keeweb/keeweb#1279]
**Describe the bug**
After updating / downloading 1.11.4 KeeWeb on Mac is not working anymore.
I tried every version downwards from 11.11.4.
Many are not working.
Last working: KeeWeb-1.10.1.mac.dmg

**To Reproduce**
1. Install new version
2. Start Keeweb
3. You don't see the login screen. You just see the background color of KeeWeb.

**Expected behavior**
Seeing list of last used files and password field.

**Environment**
macOS Mojave 10.14.6 (18G95)

**Kdbx File**
It has nothing to do with the file. I used KeeWeb over years with the same files.

**Comment by zn414** [comment]
Exact same problem here.
On Windows 10 version 1903

For the time being, I just reinstalled Keeweb 1.9.2 and everything is fine.

**Comment by antelle** [comment]
Hi! Could you please start KeeWeb from terminal, to check what's going on there?
```
/Applications/KeeWeb.app/Contents/MacOS/KeeWeb --devtools
```

**Comment by ci2014** [comment]
<img width="1680" alt="screenshot" src="https://user-images.githubusercontent.com/8351245/65839675-d6d7eb00-e30f-11e9-8777-d18b7d6bee51.png">

**Comment by antelle** [comment]
Thanks, this explains the thing, the fix is coming soon

**Comment by antelle** [comment]
The fix is rolled out

**Comment by zn414** [comment]
Yep! 
That’s ok now.

Thank for the super quick fix.

**Comment by antelle** [comment]
Sorry for breaking it that hard this time. We got rid of an ancient framework (Backbone/Underscore), so there was a huge refactoring and things may go a bit crazy now. I'm trying to fix all issues asap after this release.

**Comment by adaugherity** [comment]
I'm seeing the same failure (blank app window) with 1.11.9 on macOS 10.14.6 (also 1.11.8 and 1.11.7; didn't try any earlier 1.11.x, but 1.10.1 works fine).

Starting with `--devtools` shows a slightly different error message:
<img width="1221" alt="Screen Shot 2019-10-15 at 1 59 23 PM" src="https://user-images.githubusercontent.com/1268533/66861098-00218980-ef54-11e9-9434-9a03cbb1baa5.png">

Apologies if this should go into a different issue...

**Comment by antelle** [comment]
@adaugherity yep it's a different issue. Could you please post contents of your config? It can be found here:
```
~/Library/Application\ Support/KeeWeb/app-settings.json
```
