### ISSUE TITLE
Save to webdav failed again with 11.5

### ISSUE THREAD

**Issue by ojehle** [keeweb/keeweb#1280]
Every 2nd sync works...   will check later this week the server logs..  

index.html:1 2019-09-30T16:41:39.433Z [app] Started in 312ms ¯\_(ツ)_/¯
index.html:1 2019-09-30T16:41:39.434Z [updater] Next update check will happen in 86395s
index.html:1 2019-09-30T16:41:43.525Z [open:yy] File open request
index.html:1 2019-09-30T16:41:43.525Z [open:yy] Open file from cache, will sync after load webdav
index.html:1 2019-09-30T16:41:43.526Z [storage-cache] Load 7e8e7d2d-51bf-e327-6a3d-dcf6bc1e4aae
index.html:1 2019-09-30T16:41:43.527Z [storage-cache] Loaded 7e8e7d2d-51bf-e327-6a3d-dcf6bc1e4aae 1ms
index.html:1 2019-09-30T16:41:43.528Z [open:yy] Loaded file from cache null
index.html:1 2019-09-30T16:41:43.658Z [file] Opened file yy: 129ms, 100000 rounds, 22 kB
index.html:1 2019-09-30T16:41:43.658Z [app] Add last open file 7e8e7d2d-51bf-e327-6a3d-dcf6bc1e4aae yy webdav https://xxx.xxxx.xx/~yy/yy.kdbx Mon, 30 Sep 2019 16:38:03 GMT
index.html:1 2019-09-30T16:41:43.726Z [open:yy] Sync just opened file
index.html:1 2019-09-30T16:41:43.733Z [sync:yy] Sync started webdav https://yy/~yy/yy.kdbx Object
index.html:1 2019-09-30T16:41:43.734Z [sync:yy] Stat file
index.html:1 2019-09-30T16:41:43.734Z [storage-webdav] Stat https://xxx.xxxx.xx/~yy/yy.kdbx
index.html:1 2019-09-30T16:41:44.003Z [storage-webdav] Stated https://xxx.xxxx.xx/~yy/yy.kdbx Mon, 30 Sep 2019 16:38:03 GMT 269ms
index.html:1 2019-09-30T16:41:44.003Z [sync:yy] Stat found same version, not modified
index.html:1 2019-09-30T16:41:44.003Z [sync:yy] Sync finished no error
index.html:1 2019-09-30T16:42:34.224Z [sync:yy] Sync started webdav https://xxx.xxxx.xx/~yy/yy.kdbx {startedByUser: true}
index.html:1 2019-09-30T16:42:34.226Z [sync:yy] Stat file
index.html:1 2019-09-30T16:42:34.227Z [storage-webdav] Stat https://xxx.xxxx.xx/~yy/yy.kdbx
index.html:1 2019-09-30T16:42:34.485Z [storage-webdav] Stated https://xxx.xxxx.xx/~yy/yy.kdbx Mon, 30 Sep 2019 16:38:03 GMT 258ms
index.html:1 2019-09-30T16:42:34.486Z [sync:yy] Stat found same version, modified, saving
index.html:1 2019-09-30T16:42:34.486Z [sync:yy] Getting file data for saving
index.html:1 2019-09-30T16:42:34.660Z [sync:yy] Saving to cache
index.html:1 2019-09-30T16:42:34.660Z [storage-cache] Save 7e8e7d2d-51bf-e327-6a3d-dcf6bc1e4aae
index.html:1 2019-09-30T16:42:34.662Z [storage-cache] Saved 7e8e7d2d-51bf-e327-6a3d-dcf6bc1e4aae 2ms
index.html:1 2019-09-30T16:42:34.663Z [sync:yy] Saved to cache, saving to storage
index.html:1 2019-09-30T16:42:34.663Z [sync:yy] Save data to storage
index.html:1 2019-09-30T16:42:34.664Z [storage-webdav] Save:stat https://xxx.xxxx.xx/~yy/yy.kdbx
index.html:1 2019-09-30T16:42:34.804Z [storage-webdav] Save:stated https://xxx.xxxx.xx/~yy/yy.kdbx Mon, 30 Sep 2019 16:38:03 GMT 140ms
index.html:1 2019-09-30T16:42:34.805Z [storage-webdav] Save:put https://xxx.xxxx.xx/~yy/yy.kdbx
index.html:1 2019-09-30T16:42:35.049Z [storage-webdav] Save:puted https://xxx.xxxx.xx/~yy/yy.kdbx null 244ms
index.html:1 2019-09-30T16:42:35.049Z [storage-webdav] Save:stat https://xxx.xxxx.xx/~yy/yy.kdbx
index.html:1 2019-09-30T16:42:35.122Z [storage-webdav] Save:stated https://xxx.xxxx.xx/~yy/yy.kdbx Mon, 30 Sep 2019 16:42:34 GMT 73ms
index.html:1 2019-09-30T16:42:35.123Z [storage-webdav] Save error https://xxx.xxxx.xx/~yy/yy.kdbx rev conflict Mon, 30 Sep 2019 16:42:34 GMT Mon, 30 Sep 2019 16:38:03 GMT
index.html:1 2019-09-30T16:42:35.123Z [storage-webdav] Save:delete https://xxx.xxxx.xx/~yy/yy.kdbx
index.html:1 2019-09-30T16:42:35.124Z [sync:yy] Save rev conflict, reloading from storage
index.html:1 2019-09-30T16:42:35.124Z [sync:yy] Load from storage, attempt 1
index.html:1 2019-09-30T16:42:35.124Z [storage-webdav] Load https://xxx.xxxx.xx/~yy/yy.kdbx
index.html:1 2019-09-30T16:42:35.209Z [storage-webdav] Save:delete error https://xxx.xxxx.xx/~yy/yy.kdbx no headers 85ms
index.html:1 GET https://xxx.xxxx.xx/~yy/yy.kdbx 404 (Not Found)
_request @ index.html:1
load @ index.html:1
u @ index.html:1
(anonymous) @ index.html:1
a @ index.html:1
(anonymous) @ index.html:1
(anonymous) @ index.html:1
load (async)
_request @ index.html:1
(anonymous) @ index.html:1
(anonymous) @ index.html:1
load (async)
_request @ index.html:1
(anonymous) @ index.html:1
(anonymous) @ index.html:1
load (async)
_request @ index.html:1
save @ index.html:1
p @ index.html:1
(anonymous) @ index.html:1
(anonymous) @ index.html:1
(anonymous) @ fs.js:153
index.html:1 2019-09-30T16:42:35.286Z [storage-webdav] Load error https://xxx.xxxx.xx/~yy/yy.kdbx 404 161ms
index.html:1 2019-09-30T16:42:35.286Z [sync:yy] Load from storage undefined {notFound: true}
index.html:1 2019-09-30T16:42:35.287Z [sync:yy] Sync finished {notFound: true}

2nd sync.....

2019-09-30T16:45:52.084Z [storage-webdav] Save:stat error https://xxx.xxxx.xx/~yy/yy.kdbx 404 95ms
index.html:1 2019-09-30T16:45:52.084Z [storage-webdav] Save: not found, creating
index.html:1 2019-09-30T16:45:52.084Z [storage-webdav] Save:put https://xxx.xxxx.xx/~yy/yy.kdbx
index.html:1 2019-09-30T16:45:52.330Z [storage-webdav] Save:puted https://xxx.xxxx.xx/~yy/yy.kdbx null 245ms
index.html:1 2019-09-30T16:45:52.330Z [storage-webdav] Save:stat https://xxx.xxxx.xx/~yy/yy.kdbx
index.html:1 2019-09-30T16:45:52.403Z [storage-webdav] Save:stated https://xxx.xxxx.xx/~yy/yy.kdbx Mon, 30 Sep 2019 16:45:52 GMT 73ms
index.html:1 2019-09-30T16:45:52.404Z [sync:yy] Update rev in file info
index.html:1 2019-09-30T16:45:52.405Z [sync:yy] Save to storage complete, update sync date
index.html:1 2019-09-30T16:45:52.406Z [backup:yy] Last backup time: Mon Sep 30 2019 18:38:07 GMT+0200 (Central European Summer Time), schedule: 1d, next time: Tue Oct 01 2019 18:38:07 GMT+0200 (Central European Summer Time), skip backup
index.html:1 2019-09-30T16:45:52.407Z [sync:yy] Sync finished no error

**Comment by ojehle** [comment]
Version 10.1 log

2019-09-30T16:50:36.429Z [app] Started in 373ms ¯\_(ツ)_/¯
index.html:1 2019-09-30T16:50:36.430Z [updater] Next update check will happen in 85858s
index.html:1 Failed to decode downloaded font: data:font/woff2;base64,
index.html:1 2019-09-30T16:50:40.635Z [open:yy] File open request
index.html:1 2019-09-30T16:50:40.635Z [open:yy] Open file from cache, will sync after load webdav
index.html:1 2019-09-30T16:50:40.635Z [storage-cache] Load b75697a0-6a07-284b-fb66-7be1753fd2dc
index.html:1 2019-09-30T16:50:40.636Z [storage-cache] Loaded b75697a0-6a07-284b-fb66-7be1753fd2dc 1ms
index.html:1 2019-09-30T16:50:40.637Z [open:yy] Loaded file from cache null
index.html:1 2019-09-30T16:50:40.771Z [file] Opened file yy: 133ms, 100000 rounds, 22 kB
index.html:1 2019-09-30T16:50:40.771Z [app] Add last open file b75697a0-6a07-284b-fb66-7be1753fd2dc yy webdav https://xxx.xxxx.xx/~yy/yy.kdbx Mon, 30 Sep 2019 16:45:52 GMT
index.html:1 2019-09-30T16:50:40.847Z [open:yy] Sync just opened file
index.html:1 2019-09-30T16:50:40.855Z [sync:yy] Sync started webdav https://xxx.xxxx.xx/~yy/yy.kdbx Object
index.html:1 2019-09-30T16:50:40.856Z [sync:yy] Stat file
index.html:1 2019-09-30T16:50:40.856Z [storage-webdav] Stat https://xxx.xxxx.xx/~yy/yy.kdbx
index.html:1 2019-09-30T16:50:41.176Z [storage-webdav] Stated https://xxx.xxxx.xx/~yy/yy.kdbx Mon, 30 Sep 2019 16:45:52 GMT 320ms
index.html:1 2019-09-30T16:50:41.176Z [sync:yy] Stat found same version, not modified
index.html:1 2019-09-30T16:50:41.176Z [sync:yy] Sync finished no error
index.html:1 2019-09-30T16:51:20.939Z [sync:yy] Sync started webdav https://xxx.xxxx.xx/~yy/yy.kdbx {startedByUser: true}
index.html:1 2019-09-30T16:51:20.941Z [sync:yy] Stat file
index.html:1 2019-09-30T16:51:20.942Z [storage-webdav] Stat https://xxx.xxxx.xx/~yy/yy.kdbx
index.html:1 2019-09-30T16:51:21.155Z [storage-webdav] Stated https://xxx.xxxx.xx/~yy/yy.kdbx Mon, 30 Sep 2019 16:45:52 GMT 213ms
index.html:1 2019-09-30T16:51:21.155Z [sync:yy] Stat found same version, modified, saving
index.html:1 2019-09-30T16:51:21.156Z [sync:yy] Getting file data for saving
index.html:1 2019-09-30T16:51:21.316Z [sync:yy] Saving to cache
index.html:1 2019-09-30T16:51:21.316Z [storage-cache] Save b75697a0-6a07-284b-fb66-7be1753fd2dc
index.html:1 2019-09-30T16:51:21.321Z [storage-cache] Saved b75697a0-6a07-284b-fb66-7be1753fd2dc 5ms
index.html:1 2019-09-30T16:51:21.323Z [sync:yy] Saved to cache, saving to storage
index.html:1 2019-09-30T16:51:21.323Z [sync:yy] Save data to storage
index.html:1 2019-09-30T16:51:21.323Z [storage-webdav] Save:stat https://xxx.xxxx.xx/~yy/yy.kdbx
index.html:1 2019-09-30T16:51:21.414Z [storage-webdav] Save:stated https://xxx.xxxx.xx/~yy/yy.kdbx Mon, 30 Sep 2019 16:45:52 GMT 91ms
index.html:1 2019-09-30T16:51:21.415Z [storage-webdav] Save:put https://xxx.xxxx.xx/~yy/.yy.kdbx.1569862281323
index.html:1 2019-09-30T16:51:21.596Z [storage-webdav] Save:puted https://xxx.xxxx.xx/~yy/.yy.kdbx.1569862281323 null 181ms
index.html:1 2019-09-30T16:51:21.597Z [storage-webdav] Save:stat https://xxx.xxxx.xx/~yy/yy.kdbx
index.html:1 2019-09-30T16:51:21.695Z [storage-webdav] Save:stated https://xxx.xxxx.xx/~yy/yy.kdbx Mon, 30 Sep 2019 16:45:52 GMT 98ms
index.html:1 2019-09-30T16:51:21.695Z [storage-webdav] Save:move https://xxx.xxxx.xx/~yy/.yy.kdbx.1569862281323
index.html:1 2019-09-30T16:51:21.814Z [storage-webdav] Save:moved https://xxx.xxxx.xx/~yy/.yy.kdbx.1569862281323 null 119ms
index.html:1 2019-09-30T16:51:21.815Z [storage-webdav] Save:stat https://xxx.xxxx.xx/~yy/yy.kdbx
index.html:1 2019-09-30T16:51:21.902Z [storage-webdav] Save:stated https://xxx.xxxx.xx/~yy/yy.kdbx Mon, 30 Sep 2019 16:51:21 GMT 87ms
index.html:1 2019-09-30T16:51:21.903Z [sync:yy] Update rev in file info
index.html:1 2019-09-30T16:51:21.904Z [sync:yy] Save to storage complete, update sync date
index.html:1 2019-09-30T16:51:21.905Z [backup:yy] Last backup time: Mon Sep 30 2019 18:49:49 GMT+0200 (Central European Summer Time), schedule: 1d, next time: Tue Oct 01 2019 18:49:49 GMT+0200 (Central European Summer Time), skip backup
index.html:1 2019-09-30T16:51:21.907Z [sync:yy] Sync finished no error

**Comment by antelle** [comment]
Hi! Looks like your server doesn't support `DELETE`. Could you please go to Network panel in your browser and check the failed request, to see what happens? Looks like the problem exists not only in v1.11, because I see that in v1.10 there was no conflict, so another path was used.

**Comment by ojehle** [comment]
should it not be the following?

put tempname
mv tempname realname

i can access the server earliest friday, but the version 10.1 works without any problem, i revert back to 10.1 and its ok

**Comment by ojehle** [comment]
i had the same mode with 1.10.1 and 1.11.5  
upload temporary and move... 

but it looks like the 1.11.5 try to delete and upload. 

i will check on friday, when i have access on the webdav server to see the error message there... 
but it looks like 1.11.5 works different with webdav.

**Comment by ojehle** [comment]
First... put only works... but upload temporary and move.. not works, because the filename has no temporary extension!  

if you look in 10.1

.yy.kdbx.1570199177420  then moved  to yy.kdbx

in 11.5

the filename putted as temporary is yy.kdbx  



---- 10.1

2019-10-04T14:25:57.624Z [sync:yy] Stat file
index.html:1 2019-10-04T14:25:57.625Z [storage-webdav] Stat https://xxx.xxxxx.xx/~yy/yy.kdbx
index.html:1 2019-10-04T14:25:57.689Z [storage-webdav] Stated https://xxx.xxxxx.xx/~yy/yy.kdbx Mon, 30 Sep 2019 16:51:21 GMT 64ms
index.html:1 2019-10-04T14:25:57.690Z [sync:yy] Stat found same version, not modified
index.html:1 2019-10-04T14:25:57.690Z [sync:yy] Sync finished no error
index.html:1 2019-10-04T14:26:17.038Z [sync:yy] Sync started webdav https://xxx.xxxxx.xx/~yy/yy.kdbx 
{startedByUser: true}
index.html:1 2019-10-04T14:26:17.039Z [sync:yy] Stat file
index.html:1 2019-10-04T14:26:17.039Z [storage-webdav] Stat https://xxx.xxxxx.xx/~yy/yy.kdbx
index.html:1 2019-10-04T14:26:17.299Z [storage-webdav] Stated https://xxx.xxxxx.xx/~yy/yy.kdbx Mon, 30 Sep 2019 16:51:21 GMT 259ms
index.html:1 2019-10-04T14:26:17.299Z [sync:yy] Stat found same version, modified, saving
index.html:1 2019-10-04T14:26:17.300Z [sync:yy] Getting file data for saving
index.html:1 2019-10-04T14:26:17.418Z [sync:yy] Saving to cache
index.html:1 2019-10-04T14:26:17.418Z [storage-cache] Save b75697a0-6a07-284b-fb66-7be1753fd2dc
index.html:1 2019-10-04T14:26:17.419Z [storage-cache] Saved b75697a0-6a07-284b-fb66-7be1753fd2dc 1ms
index.html:1 2019-10-04T14:26:17.420Z [sync:yy] Saved to cache, saving to storage
index.html:1 2019-10-04T14:26:17.420Z [sync:yy] Save data to storage
index.html:1 2019-10-04T14:26:17.421Z [storage-webdav] Save:stat https://xxx.xxxxx.xx/~yy/yy.kdbx
index.html:1 2019-10-04T14:26:17.541Z [storage-webdav] Save:stated https://xxx.xxxxx.xx/~yy/yy.kdbx Mon, 30 Sep 2019 16:51:21 GMT 120ms
index.html:1 2019-10-04T14:26:17.541Z [storage-webdav] Save:put https://xxx.xxxxx.xx/~yy/.yy.kdbx.1570199177420
index.html:1 2019-10-04T14:26:17.760Z [storage-webdav] Save:puted https://xxx.xxxxx.xx/~yy/.yy.kdbx.1570199177420 null 218ms
index.html:1 2019-10-04T14:26:17.760Z [storage-webdav] Save:stat https://xxx.xxxxx.xx/~yy/yy.kdbx
index.html:1 2019-10-04T14:26:17.857Z [storage-webdav] Save:stated https://xxx.xxxxx.xx/~yy/yy.kdbx Mon, 30 Sep 2019 16:51:21 GMT 96ms
index.html:1 2019-10-04T14:26:17.857Z [storage-webdav] Save:move https://xxx.xxxxx.xx/~yy/.yy.kdbx.1570199177420
index.html:1 2019-10-04T14:26:17.931Z [storage-webdav] Save:moved https://xxx.xxxxx.xx/~yy/.yy.kdbx.1570199177420 null 74ms







----- 11.5

2019-10-04T14:27:19.912Z [sync:yy] Stat file
index.html:1 2019-10-04T14:27:19.913Z [storage-webdav] Stat https://xxx.xxxxx.xx/~yy/yy.kdbx
index.html:1 2019-10-04T14:27:20.048Z [storage-webdav] Stated https://xxx.xxxxx.xx/~yy/yy.kdbx Fri, 04 Oct 2019 14:26:17 GMT 136ms
index.html:1 2019-10-04T14:27:20.049Z [sync:yy] Stat found same version, not modified
index.html:1 2019-10-04T14:27:20.049Z [sync:yy] Sync finished no error
index.html:1 2019-10-04T14:28:04.725Z [sync:yy] Sync started webdav https://xxx.xxxxx.xx/~yy/yy.kdbx {startedByUser: true}
index.html:1 2019-10-04T14:28:04.728Z [sync:yy] Stat file
index.html:1 2019-10-04T14:28:04.728Z [storage-webdav] Stat https://xxx.xxxxx.xx/~yy/yy.kdbx
index.html:1 2019-10-04T14:28:04.929Z [storage-webdav] Stated https://xxx.xxxxx.xx/~yy/yy.kdbx Fri, 04 Oct 2019 14:26:17 GMT 201ms
index.html:1 2019-10-04T14:28:04.930Z [sync:yy] Stat found same version, modified, saving
index.html:1 2019-10-04T14:28:04.930Z [sync:yy] Getting file data for saving
index.html:1 2019-10-04T14:28:05.160Z [sync:yy] Saving to cache
index.html:1 2019-10-04T14:28:05.161Z [storage-cache] Save b75697a0-6a07-284b-fb66-7be1753fd2dc
index.html:1 2019-10-04T14:28:05.162Z [storage-cache] Saved b75697a0-6a07-284b-fb66-7be1753fd2dc 1ms
index.html:1 2019-10-04T14:28:05.165Z [sync:yy] Saved to cache, saving to storage
index.html:1 2019-10-04T14:28:05.165Z [sync:yy] Save data to storage
index.html:1 2019-10-04T14:28:05.166Z [storage-webdav] Save:stat https://xxx.xxxxx.xx/~yy/yy.kdbx
index.html:1 2019-10-04T14:28:05.285Z [storage-webdav] Save:stated https://xxx.xxxxx.xx/~yy/yy.kdbx Fri, 04 Oct 2019 14:26:17 GMT 119ms
index.html:1 2019-10-04T14:28:05.285Z [storage-webdav] Save:put https://xxx.xxxxx.xx/~yy/yy.kdbx
index.html:1 2019-10-04T14:28:05.485Z [storage-webdav] Save:puted https://xxx.xxxxx.xx/~yy/yy.kdbx null 199ms
index.html:1 2019-10-04T14:28:05.485Z [storage-webdav] Save:stat https://xxx.xxxxx.xx/~yy/yy.kdbx
index.html:1 2019-10-04T14:28:05.554Z [storage-webdav] Save:stated https://xxx.xxxxx.xx/~yy/yy.kdbx Fri, 04 Oct 2019 14:28:05 GMT 68ms
index.html:1 2019-10-04T14:28:05.554Z [storage-webdav] Save error https://xxx.xxxxx.xx/~yy/yy.kdbx rev conflict Fri, 04 Oct 2019 14:28:05 GMT Fri, 04 Oct 2019 14:26:17 GMT
index.html:1 2019-10-04T14:28:05.554Z [storage-webdav] Save:delete https://xxx.xxxxx.xx/~yy/yy.kdbx
index.html:1 2019-10-04T14:28:05.555Z [sync:yy] Save rev conflict, reloading from storage
index.html:1 2019-10-04T14:28:05.556Z [sync:yy] Load from storage, attempt 1
index.html:1 2019-10-04T14:28:05.556Z [storage-webdav] Load https://xxx.xxxxx.xx/~yy/yy.kdbx
index.html:1 2019-10-04T14:28:05.616Z [storage-webdav] Save:delete error https://xxx.xxxxx.xx/~yy/yy.kdbx no headers 61ms
index.html:1 GET https://xxx.xxxxx.xx/~yy/yy.kdbx 404 (Not Found)
_request @ index.html:1
load @ index.html:1
u @ index.html:1
(anonymous) @ index.html:1
a @ index.html:1
(anonymous) @ index.html:1
(anonymous) @ index.html:1
load (async)
_request @ index.html:1
(anonymous) @ index.html:1
(anonymous) @ index.html:1
load (async)
_request @ index.html:1
(anonymous) @ index.html:1
(anonymous) @ index.html:1
load (async)
_request @ index.html:1
save @ index.html:1
p @ index.html:1
(anonymous) @ index.html:1
(anonymous) @ index.html:1
(anonymous) @ fs.js:153
index.html:1 2019-10-04T14:28:05.682Z [storage-webdav] Load error https://xxx.xxxxx.xx/~yy/yy.kdbx 404 126ms
index.html:1 2019-10-04T14:28:05.683Z [sync:yy] Load from storage undefined {notFound: true}
index.html:1 












xxx.xxxxx.xx:443 999.99.999.99 - yy [04/Oct/2019:16:28:04 +0200] "HEAD /~yy/yy.kdbx HTTP/1.1" 200 619 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) KeeWeb/1.10.1 Chrome/76.0.3809.139 Electron/6.0.7 Safari/537.36"
xxx.xxxxx.xx:443 999.99.999.99 - yy [04/Oct/2019:16:28:05 +0200] "HEAD /~yy/yy.kdbx HTTP/1.1" 200 462 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) KeeWeb/1.10.1 Chrome/76.0.3809.139 Electron/6.0.7 Safari/537.36"
xxx.xxxxx.xx:443 999.99.999.99 - yy [04/Oct/2019:16:28:05 +0200] "PUT /~yy/yy.kdbx HTTP/1.1" 204 351 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) KeeWeb/1.10.1 Chrome/76.0.3809.139 Electron/6.0.7 Safari/537.36"
xxx.xxxxx.xx:443 999.99.999.99 - yy [04/Oct/2019:16:28:05 +0200] "HEAD /~yy/yy.kdbx HTTP/1.1" 200 464 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) KeeWeb/1.10.1 Chrome/76.0.3809.139 Electron/6.0.7 Safari/537.36"
xxx.xxxxx.xx:443 999.99.999.99 - yy [04/Oct/2019:16:28:05 +0200] "DELETE /~yy/yy.kdbx HTTP/1.1" 204 351 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) KeeWeb/1.10.1 Chrome/76.0.3809.139 Electron/6.0.7 Safari/537.36"
xxx.xxxxx.xx:443 999.99.999.99 - yy [04/Oct/2019:16:28:05 +0200] "GET /~yy/yy.kdbx HTTP/1.1" 404 691 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) KeeWeb/1.10.1 Chrome/76.0.3809.139 Electron/6.0.7 Safari/537.36"
xxx.xxxxx.xx:443 999.99.999.99 - - [04/Oct/2019:16:28:25 +0200] "-" 408 156 "-" "-"
xxx.xxxxx.xx:443 999.99.999.99 - yy [04/Oct/2019:16:32:32 +0200] "HEAD /~yy/yy.kdbx HTTP/1.1" 404 3699 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) KeeWeb/1.10.1 Chrome/76.0.3809.139 Electron/6.0.7 Safari/537.36"
xxx.xxxxx.xx:443 999.99.999.99 - yy [04/Oct/2019:16:32:32 +0200] "HEAD /~yy/yy.kdbx HTTP/1.1" 404 395 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) KeeWeb/1.10.1 Chrome/76.0.3809.139 Electron/6.0.7 Safari/537.36"
xxx.xxxxx.xx:443 999.99.999.99 - yy [04/Oct/2019:16:32:32 +0200] "PUT /~yy/yy.kdbx HTTP/1.1" 201 723 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) KeeWeb/1.10.1 Chrome/76.0.3809.139 Electron/6.0.7 Safari/537.36"
xxx.xxxxx.xx:443 999.99.999.99 - yy [04/Oct/2019:16:32:33 +0200] "HEAD /~yy/yy.kdbx HTTP/1.1" 200 464 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) KeeWeb/1.10.1 Chrome/76.0.3809.139 Electron/6.0.7 Safari/537.36"
xxx.xxxxx.xx:443 999.99.999.99 - yy [04/Oct/2019:16:32:49 +0200] "HEAD /~yy/yy.kdbx HTTP/1.1" 200 619 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) KeeWeb/1.10.1 Chrome/76.0.3809.139 Electron/6.0.7 Safari/537.36"
xxx.xxxxx.xx:443 999.99.999.99 - yy [04/Oct/2019:16:32:58 +0200] "HEAD /~yy/yy.kdbx HTTP/1.1" 200 619 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) KeeWeb/1.10.1 Chrome/76.0.3809.139 Electron/6.0.7 Safari/537.36"
xxx.xxxxx.xx:443 999.99.999.99 - yy [04/Oct/2019:16:33:05 +0200] "HEAD /~yy/yy.kdbx HTTP/1.1" 200 619 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) KeeWeb/1.10.1 Chrome/76.0.3809.139 Electron/6.0.7 Safari/537.36"
xxx.xxxxx.xx:443 999.99.999.99 - yy [04/Oct/2019:16:33:05 +0200] "HEAD /~yy/yy.kdbx HTTP/1.1" 200 462 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) KeeWeb/1.10.1 Chrome/76.0.3809.139 Electron/6.0.7 Safari/537.36"
xxx.xxxxx.xx:443 999.99.999.99 - yy [04/Oct/2019:16:33:06 +0200] "PUT /~yy/yy.kdbx HTTP/1.1" 204 351 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) KeeWeb/1.10.1 Chrome/76.0.3809.139 Electron/6.0.7 Safari/537.36"
xxx.xxxxx.xx:443 999.99.999.99 - yy [04/Oct/2019:16:33:06 +0200] "HEAD /~yy/yy.kdbx HTTP/1.1" 200 464 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) KeeWeb/1.10.1 Chrome/76.0.3809.139 Electron/6.0.7 Safari/537.36"
xxx.xxxxx.xx:443 999.99.999.99 - yy [04/Oct/2019:16:33:06 +0200] "DELETE /~yy/yy.kdbx HTTP/1.1" 204 351 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) KeeWeb/1.10.1 Chrome/76.0.3809.139 Electron/6.0.7 Safari/537.36"
xxx.xxxxx.xx:443 999.99.999.99 - yy [04/Oct/2019:16:33:06 +0200] "GET /~yy/yy.kdbx HTTP/1.1" 404 691 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) KeeWeb/1.10.1 Chrome/76.0.3809.139 Electron/6.0.7 Safari/537.36"
xxx.xxxxx.xx:443 999.99.999.99 - - [04/Oct/2019:16:33:26 +0200] "-" 408 156 "-" "-"

**Comment by antelle** [comment]
Well, this means you should use PUT.

**Comment by ojehle** [comment]
i think temp and move is more secure. pls fix it that temporary name is used and then moved. not a direct put

**Comment by antelle** [comment]
Please provide me a full server response that fails. I still haven’t seen it, and I don’t want to guess what’s going on.

**Comment by ojehle** [comment]
I attached the logs for both versions now (took 1.11.6 to compare with 1.10.1) 

(keeweb and apache) Version 1.10.1 working ... 

there you see, the put is done with the temoporay filename and then moved..  Filename .oj.kdbx.1570447722717

[log10.1.txt](https://github.com/keeweb/keeweb/files/3696948/log10.1.txt)


WIth the version 1.11.6 the file is uploaded directly with the oj.kdbx filename (original filename, not the temporary filename), then the stat is failing because a mismatch of the stat information (because the server file is already changed) and the file is deleted on the webdav (the server support it, the file is deleted). the second sync is working, because there is no file on the server anymore.  

[log11.6.txt](https://github.com/keeweb/keeweb/files/3696949/log11.6.txt)

**Comment by fredericrous** [comment]
Thank you for this workaround @ojehle . second sync works :sweat_smile: . first one deleted the file from the server

**Comment by ojehle** [comment]
@fredericrous 

latest release works again. the order of the webdav arguments was wrong. but the developer was faster then me posting the patch ;-)

**Comment by fredericrous** [comment]
The issue is fixed indeed, however now with version 1.12.1 I face issue #1154 :(
