### ISSUE TITLE
[Feature request] Bidirectional sync with GDrive

### ISSUE THREAD

**Issue by davidpoza** [keeweb/keeweb#1281]
I wish KeeWeb was able to check the uploaded file looking for changes, and download them if needed. 

Now (I think) it just upload changes, but it's not fetching anything from cloud to local. 

The consequent problem with conflicts could be resolved simply by config, selecting your preference: local has priority or remote has priority. Another option would be just prompt user to select the action from a dialog in case of conflict.

**Comment by antelle** [comment]
Hi! We already have quite powerful conflictless sync, however it’s triggered only when you save your file. So what we need is to add sync by timer, or more complicated but better, subscribe to storage notifications and sync when there are changes. Duplicates #1029

**Comment by davidpoza** [comment]
Thanks! :wink:
