### ISSUE TITLE
Moving entries between files (#336) malfunctioning in v1.11.5

### ISSUE THREAD

**Issue by tobefound** [keeweb/keeweb#1285]
**Describe the bug**
You can drag and drop an entry from one file to another, but not the other way around. Also, when dragging an entry X from file A to file B, you cannot drag X back to A nor can you drag X to other folders within B.

**Logs**
index.html:1 Uncaught TypeError: Cannot read property 'entries' of undefined
    at p.move (index.html:1)
    at Proxy.moveHere (index.html:1)
    at u.drop (index.html:1)
    at u.eventListener (index.html:1)
    at HTMLDivElement.e (index.html:1)

**Comment by antelle** [comment]
The fix is rolled out
