### ISSUE TITLE
v1.116: Problems opening a new database when in Auto-Type

### ISSUE THREAD

**Issue by dploeger** [keeweb/keeweb#1288]
**Describe the bug**
When I hit the autotype command, I can not open a new database from the autotype screen properly anymore:

* The arrow keys doesn't work anymore in the database selection screen
* When entering a passphrase for the database-to-open, it triggers the auto type search instead

**To Reproduce**
1. Open a database
2. Use Autotype
3. Use the Open shortcut to open another database
=> Arrow keys don't work for selection
4. Select a database with the mouse
5. Type the passphrase
=> The autotype search is triggered

**Expected behavior**
I can select a database from the "Open Database" view with the arrow keys and enter my passphrase successfully after being sent back to the autotype screen, that includes the new database then.

**Environment**
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) KeeWeb/1.9.2 Chrome/76.0.3809.110 Electron/6.0.2 Safari/537.36

**Logs**
No logs come up for this.

**Comment by antelle** [comment]
Hi! Fixed this, but I can't build a hotfix because a lot of tools are broken on macOS Catalina. I'm trying to figure out what to do with all of them, as soon as it can be build, a hotfix will be there.

**Comment by antelle** [comment]
So, the only incompatibility we have is missing `wine`, which is used here for setting icons: https://github.com/electron/electron-packager/issues/1055. I'll think about possible ways of mitigation while `wine` is broken and it's unclear if they will fix it.

**Comment by dploeger** [comment]
Thanks. I'm still on Mojave and could give you a hand if that helps in any way.

**Comment by antelle** [comment]
I decided to set up a virtualbox with wine tonight.
It’s not possible to build KeeWeb without a hardware token with keys, so I have to fix the stuff...

**Comment by dploeger** [comment]
Allright. Thanks for the effort!

**Comment by antelle** [comment]
meh, VirtualBox keeps crashing, so I'll have to wait until they hotfix it...

**Comment by dploeger** [comment]
Damn. [Docker](https://hub.docker.com/r/strm/wine)?

**Comment by antelle** [comment]
It won't run in Docker 😄  well, I managed to set up a VirtualBox VM with wine using this hack: https://forums.virtualbox.org/viewtopic.php?f=39&t=93419&start=30. Now it's easy: create a wine executable that will do the stuff there instead of running a real wine locally. Will try to do it a bit later today.

**Comment by antelle** [comment]
Finally it's live! 🎉

**Comment by dploeger** [comment]
Yayy! Awesome. Thank you very much.

**Comment by dploeger** [comment]
Works as expected. 👍
