### ISSUE TITLE
Custom theme - password generator dropdown invisible

### ISSUE THREAD

**Issue by TomteT** [keeweb/keeweb#1290]
**Describe the bug**
I just noticed that the password generator dropdown **within** the password field doesn’t show up when developing a custom theme or when using the a custom theme like „theme-orange“ or „theme-nord“ from the plugin gallery.

I Inspected the source code and noticed the generator dropdown is opened but invisible because it's completely out of view. It actually doesn't get a top value assigned. Only the left property is set on click.

When using the generator button in the toolbar (next to settings), the generator dropdown is opened and visible as expected.

I also noticed that the mentioned themes and the theme I tried to create (using the plugin creator tool) share another „error“: every border or line to contrast sections and elements is missing. Thats just a very minor optical issue, but as there are probably some color variables / css properties missing in the plugin creator output / the plugin.css file.  Did the theme structure change recently? Maybe thats where the dropdown misbehavior comes from too?

**To Reproduce**
1. Go to ’Settings’ > ’Plugins’
2. Install ’Theme Orange‘ or ’Theme Nord’ from the plugins gallery
3. Activate the theme
4. Open a Kdbx File or Demo and select any entry or create a new one
5. Click on the password field input 
6. Click on the bolt icon to open the password generator dropdown

**Expected behavior**
The password generator dropdown should be opened and be visible inside the window

**Screenshots**
Dropdown element exists and is opened, just completely out of view:
![out-of-view](https://user-images.githubusercontent.com/36259611/66457613-1372b780-ea71-11e9-8858-67b702227619.png)

The element doesn't get assigned a top value:
![no-top-value](https://user-images.githubusercontent.com/36259611/66457614-1372b780-ea71-11e9-84b3-31de422622bb.png)

**Environment**
Reproduced on web and electron app:

KeeWeb v1.11.6 (37ad3fbf, 2019-10-04)
Environment: web User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.44 Safari/537.36

KeeWeb v1.11.6 (37ad3fbf, 2019-10-04)
Environment: electron v6.0.2
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) KeeWeb/1.9.2 Chrome/76.0.3809.110 Electron/6.0.2 Safari/537.36

**Kdbx File**
Any kdbx file

**Logs**
Developer tools console doesn't log any error or warning

**Comment by antelle** [comment]
Strange, I can't repeat it. Could you please share your window size? Maybe it's not visible on certain sizes? Is it visible on built-in themes?

**Comment by TomteT** [comment]
I tested this on multiple devices with different window sizes. Native resolution was 2560 x 1440 (27" iMac) and 1920 x 1200. Both machines are running mac OS (with different versions though). Used in Web and Standalone with fullscreen, full-size, small - every where the same result. 
I just did a quick check on a Parallels Windows 10 environment an the result within Microsoft Edge using the KeeWeb Web-App is the same. The Generator doesn't open when using "theme-orange" e.a.

Yes the build in themes like "Flat Blue" are working properly.

**Comment by antelle** [comment]
Let's check if it's working well now. I've found a bug in themes, they were somewhat broken in general, fixed it in v1.11.8. However I still can't repeat the generator thing...

**Comment by TomteT** [comment]
I noticed a minor difference in the appearance of the affected themes but sadly the original issue still exists. 
![Cast4 (1)](https://user-images.githubusercontent.com/36259611/66714486-b9972800-edb7-11e9-890a-27fb59b48db0.gif)

Currently I'm trying to get a working development environment from this repo running but having some trouble with this too.

I'll contact you as soon as I can find something

**Comment by antelle** [comment]
Now I can repeat it, thanks for the screenshot 😄 
Working on a fix...

**Comment by antelle** [comment]
Fixed it, the release is coming soon
