### ISSUE TITLE
Copying "Website" omits the protocol part of the url

### ISSUE THREAD

**Issue by matsev** [keeweb/keeweb#1293]
**Describe the bug**
When clicking on "Website" in the gui, the protocol part of the url is omitted (only the host and path of the url is copied to the clipboard).

**To Reproduce**
1. Click on `+`
2. Select `Entry` to create a new entry
3. Enter a `Website`, e.g. `https://www.gmail.com`
4. Click tab or click some other field so that the website is persisted
5. Click on `Website` again to copy the url to the clipboard
6. Open a text editor and paste

**Expected behavior**
The full url, including the protocol, should be pasted, e.g. `https://www.gmail.com`

**Actual behaviour**
The protocol part is missing when pasting the url, e.g. `www.gmail.com`

**Comment**
This is not a problem if the website has a redirect from http to https (gmail does this), otherwise the result is a connection error. Since KeeWeb has no way of knowing this, I suggest that you always copy the full url.

**Environment**
KeeWeb v1.11.5 (e8e2b499, 2019-09-29)
Environment: electron v6.0.10
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) KeeWeb/1.11.5 Chrome/76.0.3809.146 Electron/6.0.10 Safari/537.36

**Comment by ethnchao** [comment]
+1
