### ISSUE TITLE
where is the keyfile is saved

### ISSUE THREAD

**Issue by wshamroukh** [keeweb/keeweb#1294]
So when i hit new and create my own keyfile and put my passwords, where this file is kept?
if open the link from another web browser, i don't see this file i created.
BTW, i am hosting this on azure storage account.
i am wondering when you create your own file, where it is saved?

**Comment by antelle** [comment]
Hi! It's saved in your browser storage, in particular, [IndexedDB](https://developer.mozilla.org/nl/docs/IndexedDB).

**Comment by wshamroukh** [comment]
Im a little confused here. What is the idea of saving the passwords in the browser storage. I put the keeweb on azure storage account as a website so that i can access it from everywhere. If the passwords are only save to the client's browser storage, then you want be able to see what you have saved from another machine.
What is the point of this?
I want it to be saved at a central location so that it can be accessed from anywhere

**Comment by antelle** [comment]
You can move your database to Dropbox, Google Drive, OneDrive, or WebDav to be able to sync it. We don't support Azure storage, however if they have a WebDAV interface, you can add it to KeeWeb via WevDAV.

**Comment by wshamroukh** [comment]
@antelle i am using this one https://github.com/keeweb/keeweb/archive/gh-pages.zip to install it on my web server. However when i create a onedrive and integrate it with Azure ID, I am not sure where i need to put the client ID.. can you advise?

**Comment by antelle** [comment]
You need to create a config and put your onedrive client id there: https://github.com/keeweb/keeweb/wiki/Configuration#json-app-config
Alternatively, you can open a browser console and type
```javascript
kw.settings.set('onedriveClientId', 'your-client-id-here');
```
