### ISSUE TITLE
Password field shown

### ISSUE THREAD

**Issue by ChrisFromLafare** [keeweb/keeweb#1295]
Hello,
First at all, I would like to say that I've been using keeweb on mac for several years and I enjoy it.

**Describe the bug**
On my iphone, I recently started to use a keepass compatible app named KyPass. I get my databases synchronised beetween Kypass et KeeWeb using a Dropbox shared folder.

When I create/modifiy the password of an entry on KyPass, it is shown in plain text in keepass instead of being shown as password field.

**To Reproduce**

**Logs**
Please open dev tools in your browser and attach output log from Console tab. If you are using a desktop app, devtools can be opened from Settings/General/Advanced.
[test.kdbx.zip](https://github.com/keeweb/keeweb/files/3716054/test.kdbx.zip)
Mot de passe de la base: password
Erroneous entry: Dummy

**Comment by antelle** [comment]
Hi! 
It seems to be a bug in KyPass. The password is written like this in your db:

<Key>Password</Key><Value>password</Value>

however it should be written as a protected value.  You can see the xml here: https://tools.keeweb.info/kdbx-to-xml.html

**Comment by ChrisFromLafare** [comment]
Hi!

I come back to this issue, I performed a few tests on other clients, it seems that - even if you're right the field should be marked as protected -they handle the password field as a sensitive protected field whether or not it is marked as protected. Is it possible to provide the same behavior?
Thank you.
Should I make a feature request?

**Comment by mcgiany** [comment]
> 
> 
> Hi!
> It seems to be a bug in KyPass. The password is written like this in your db:
> 
> ```
> <Key>Password</Key><Value>password</Value>
> ```
> 
> however it should be written as a protected value. You can see the xml here: https://tools.keeweb.info/kdbx-to-xml.html

Alright, so its something that the kdbx file supports. For me, it looks like, there should be functionality to change this "flag" and make the password protected or unprotected. Am i wrong?

**Comment by antelle** [comment]
The format support many different things, we need to keep features in healthy balance. I don't think there should be a possibility to save the password unprotected.

**Comment by mcgiany** [comment]
@antelle i dont think you get my point. In previous post, you said "however it should be written as a protected value". That means, that KyPass doesnt saved the value as protected. And i asked, if its possible to re-write the same value as protected by KeeWeb, until the author of KyPass fixes the bug. And with that, enforce to show password as dots instead revealed in keeweb.

**Comment by antelle** [comment]
Well, looks like fixing it is a bit of a problem and probably we should do it while they're still working on it.
