### ISSUE TITLE
Autotype-Search doesn't after opening the first database

### ISSUE THREAD

**Issue by dploeger** [keeweb/keeweb#1296]
**Describe the bug**
When all databases are locked (i.e. after they timeout or after locking and unlocking the screen) and the autotype hotkey is used, the open database view is shown.

After entering the passphrase, the view switches to autotype, but the search feature doesn't work.

When canceling and re-hitting the autotype hotkey, everything works again.

**To Reproduce**
1. Lock all databases
2. Switch to another app
3. hit Autotype hotkey
4. Unlock a database
5. Try pressing keys to initiate search

=> no search is shown

6. Press Esc
7. Hit Autotype hotkey again
8. Try pressing keys to initiate search

=> search works

**Expected behavior**
Search works after unlocking the database

**Environment**
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) KeeWeb/1.9.2 Chrome/76.0.3809.110 Electron/6.0.2

**Logs**
No Logs exist

**Comment by antelle** [comment]
Thanks, fixed this.
Note for myself: there were three bugs about focus recently, I'll properly rewrite the focus manager in the next release so that it doesn't break like this.

**Comment by dploeger** [comment]
Awesome. Thx

**Comment by antelle** [comment]
Still struggling with [notarization](https://developer.apple.com/news/?id=06032019i) for the next release, but it should happen today...
Now building a new release includes ≈10min waiting for Apple.

**Comment by dploeger** [comment]
Don't sweat it. It's only a minor issue

**Comment by antelle** [comment]
Finally published it! Actually [this issue](https://github.com/keeweb/keeweb/issues/1292) is a bigger problem because people can't run KeeWeb on macOS Catalina at all and get a suggestion to contact the developer instead.
