### ISSUE TITLE
Make Docker container configurable

### ISSUE THREAD

**Issue by trickert76** [keeweb/keeweb#1298]
I'm using keeweb with Docker and I'd like to "preconfigure" the running environment. According to https://github.com/keeweb/keeweb/wiki/Configuration it is necessary to rewrite the `index.html` inside the container to define a custom JSON configuration. This isn't that easy, because in a Docker environment I can only change whole files and I think it is not a good practice to replace the complete `index.html` file. Instead I think about the following idea:

- Docker mounts the custom config.json somewhere in the htdocs of nginx. This needs to be documented only, because maybe the file is not hosted by the docker container itself. Something like `docker ... -v /path/to/config:/keeweb/config.json`
- Add a environment variable like `KEEWEB_CONFIG_URL` that is read by the `entrypoint.sh` script and when present use `sed` to replace "`(no-config)`" with the value in the environment variable, like `sed i/(no-config)/$KEEWEB_CONFIG_URL/ /keeweb/index.html`

**Comment by antelle** [comment]
I guess, you already fixed it with #1299 😄
