### ISSUE TITLE
Unable to change autotype keystrokes using predefined fields

### ISSUE THREAD

**Issue by tbradsha** [keeweb/keeweb#1300]
**To Reproduce**
1. Go to an entry
2. Click on **more... → Auto-type settings**
3. Add some predefined fields/keys in the **Keystrokes** field
4. Navigate away from the entry
5. Return to the entry, and the modified **Keystrokes** field is reset to default

Note that typing something like `asdf` saves in the entry.

**Expected behavior**
The **Keystrokes** field should allow predefined fields/keys, including the following variations:

```
{USERNAME}
{USERNAME}{TAB}{PASSWORD}
{USERNAME}{TAB}{TAB}{PASSWORD}{ENTER}
```

**Environment**
```
KeeWeb v1.11.8 (0fabdac9, 2019-10-11)
Environment: electron v6.0.2
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) KeeWeb/1.9.2 Chrome/76.0.3809.110 Electron/6.0.2 Safari/537.36
```

**Kdbx File**
It occurs on the demo DB as well.

**Logs**
Nothing was logged.

**Comment by antelle** [comment]
Temporary hack: type a character and delete it after selecting from the dropdown.

**Comment by tbradsha** [comment]
Spectacular! For an example of the workaround, first add it like this, with a character at the end:

`{USERNAME}{TAB}{TAB}{PASSWORD}{ENTER}a`

Leave the entry, come back, and remove the extra character at the end:

`{USERNAME}{TAB}{TAB}{PASSWORD}{ENTER}`
