### ISSUE TITLE
Cannot unlock database

### ISSUE THREAD

**Issue by midnightrunner007** [keeweb/keeweb#1301]
Bug Description
I use Keeweb as desktop client, KeePass Touch on iPad & Keepass2android on my phone to read/edit .kdbx files. It's been a while since I've used desktop version. For some time database file was accessed to add or edit passwords on ipad and phone only. Database synced in dropbox. No issues accessing the file through these devices. On desktop I noticed today that I cannot open the synced file, nor does copying it in local folder or changing its name help to access it
Error shown:
There was an error opening file
TypeError: Cannot read property 'id' of undefined
Tried with Keepass & Keepassx, same issue
As I don't know the cause I can't explain how to reproduce it. There is no browser log to show for this

**Environment**
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) KeeWeb/1.11.8 Chrome/76.0.3809.146 Electron/6.0.10 Safari/537.36

**Comment by antelle** [comment]
Hi! KeePass Touch writes files without IDs, see #1286

**Comment by antelle** [comment]
Since you're saying you haven't been using KeeWeb for a while and now you can't open it in any of the clients I assume, it's KeePass Touch what broke your database. If you convert it to XML, you should be able look what's inside, here's a tool for you: https://tools.keeweb.info/kdbx-to-xml.html
