### ISSUE TITLE
406 Not Acceptable Error When Installed on Hosting Platform

### ISSUE THREAD

**Issue by bunzelbulrner** [keeweb/keeweb#1302]
**Describe the bug**
I'm trying to set up a KeeWeb installation on an A2 Hosting account. I'm using the keeweb-gh-pages.zip file which provides a single HTML file with some support files. When I upload this to my hosting platform and try to access it, I get a 406 Not Acceptable error. I reached out to A2 Hosting support and they looked into and said they couldn't find anything wrong per se on their end. They said they could replace the index.html file with any other HTML file and it would work, but for some reason, the HTML file provided with the KeeWeb package is causing the error. They asked me to reach out to the developers to see if there is some server-side configuration needed that may be causing the issue with the HTML.

The URL for where I am hosting the KeeWeb installation is:

https://kp.joshbunzel.com

**Comment by antelle** [comment]
Hi! I can't help you with hosting issues, please solve it with your hosting provider.
About your question, there's no server configuration required, it's just an HTML file.
