### ISSUE TITLE
auto-type no longer working since 1.11.8 mac

### ISSUE THREAD

**Issue by tcz305** [keeweb/keeweb#1303]
**Describe the bug**
since 1.11.8 auto-type doesn't type anything ...works with 1.11.7 and previous versions.

**To Reproduce**
1. Click on site address
2. switch to keeweb
3. Click on 'auto-type'
4. focus switches to browser but nothing is typed

**Expected behavior**
Should enter username and password and enter.

**Environment**
KeeWeb v1.11.9 (2c9c8b9a, 2019-10-13)
Environment: electron v6.0.10
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_4) AppleWebKit/537.36 (KHTML, like Gecko) KeeWeb/1.11.9 Chrome/76.0.3809.146 Electron/6.0.10 Safari/537.36

**Comment by antelle** [comment]
Hi!
To fix this:
1. open System Preferences → Security & Privacy → Privacy → Accessibility
2. delete KeeWeb from the "Allow the apps below to control your computer" list
3. trigger auto-type
4. go to the same setting as on step 1
5. find KeeWeb and check the checkbox
6. trigger auto-type

**Comment by antelle** [comment]
I'll pin this issue because this will happen quite often after updating KeeWeb to v1.11.8+ or updating macOS to Catalina.
