### ISSUE TITLE
v1.11.9 - WebDAV - Deletes the DB from the server when saving

### ISSUE THREAD

**Issue by oblivian** [keeweb/keeweb#1305]
**Describe the bug**
When saving changes to a DB using WebDAV the db.kdbx file is deleted from the server.

**To Reproduce**
Upgrade to v1.11.9
Try to save. You'll get an error an the entire DB is gone from the server.
**Environment**
Server: Apache 2.4.18, Ubuntu 16.04

**Comment by antelle** [comment]
Please reopen with logs, server logs, etc..

**Comment by oblivian** [comment]
Well, the server has been running the same config for several years without any issues, including no issues with KeeWeb. The only thing that has changed is the upgrade to v1.11.9.

Anyways, I'll investigate further on my end.
Thanks.

**Comment by antelle** [comment]
I guess, the issue it most likely not on server, but something is configured not the way we expect. Logs in KeeWeb can give an insight of what was going wrong.

**Comment by antelle** [comment]
If you have keeweb logs deleted (e.g. if you closed the app), server logs from the time it was deleted can help as well, that's why I said "server or keeweb" logs.

**Comment by oblivian** [comment]
Server logs:
123.123.123.123 - user [15/Oct/2019:19:38:19 +0200] "HEAD /wd/db.kdbx HTTP/1.1" 200 779 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_0) AppleWebKit/537.36 (KHTML, like Gecko) KeeWeb/1.9.3 Chrome/76.0.3809.110 Electron/6.0.2 Safari/537.36"
123.123.123.123 - user [15/Oct/2019:19:38:19 +0200] "GET /wd/db.kdbx HTTP/1.1" 200 1443841 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_0) AppleWebKit/537.36 (KHTML, like Gecko) KeeWeb/1.9.3 Chrome/76.0.3809.110 Electron/6.0.2 Safari/537.36"
123.123.123.123 - user [15/Oct/2019:19:38:22 +0200] "HEAD /wd/db.kdbx HTTP/1.1" 200 779 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_0) AppleWebKit/537.36 (KHTML, like Gecko) KeeWeb/1.9.3 Chrome/76.0.3809.110 Electron/6.0.2 Safari/537.36"
123.123.123.123 - user [15/Oct/2019:19:38:22 +0200] "PUT /wd/db.kdbx HTTP/1.1" 204 664 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_0) AppleWebKit/537.36 (KHTML, like Gecko) KeeWeb/1.9.3 Chrome/76.0.3809.110 Electron/6.0.2 Safari/537.36"
123.123.123.123 - user [15/Oct/2019:19:38:22 +0200] "HEAD /wd/db.kdbx HTTP/1.1" 200 781 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_0) AppleWebKit/537.36 (KHTML, like Gecko) KeeWeb/1.9.3 Chrome/76.0.3809.110 Electron/6.0.2 Safari/537.36"
123.123.123.123 - user [15/Oct/2019:19:38:22 +0200] "GET /wd/db.kdbx HTTP/1.1" 404 954 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_0) AppleWebKit/537.36 (KHTML, like Gecko) KeeWeb/1.9.3 Chrome/76.0.3809.110 Electron/6.0.2 Safari/537.36"
123.123.123.123 - user [15/Oct/2019:19:38:22 +0200] "DELETE /wd/db.kdbx HTTP/1.1" 204 664 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_0) AppleWebKit/537.36 (KHTML, like Gecko) KeeWeb/1.9.3 Chrome/76.0.3809.110 Electron/6.0.2 Safari/537.36"

**Comment by oblivian** [comment]
Error log from KeeWeb:
index.html:1 HEAD https://host.domain.tld/wd/db.kdbx net::ERR_SPDY_PROTOCOL_ERROR

**Comment by oblivian** [comment]
Well, the 404 is because the file doesn't exist anymore after the HEAD method.
(index.html:1 HEAD https://host.domain.tld/wd/db.kdbx net::ERR_SPDY_PROTOCOL_ERROR)

**Comment by antelle** [comment]
HEAD doesn't delete files, it just queries the content. Anyway, the file must not be deleted in this case of course, it's a bug.

**Comment by antelle** [comment]
Also I think I found a reason why it behaves like this, will make a new version soon.

**Comment by antelle** [comment]
Fixed this, if you would like to give it a try, you can do it on [beta.keeweb.info](https://beta.keeweb.info), but I'm almost sure it fix the issue. Will make a hotfix with it soon, thanks for the detailed logs.

**Comment by damien6468** [comment]
Thanks, I hope it will fix it. I encountered the problem also : server apache2.4.38 debian10
2 reactions client side : 
- Chromium (v77) : -> Deletion of the file on the WebDAV folder
- Firefox (v69.0.1) : -> Failed auto-save file error (log : [storage-cache] Error opening indexed db )

**Comment by antelle** [comment]
Now everything should work

**Comment by damien6468** [comment]
From my side, everything's ok :) Thanks a lot.

**Comment by oblivian** [comment]
Everything works perfectly again. Thanks a million antelle.
