### ISSUE TITLE
Setup of Keeweb

### ISSUE THREAD

**Issue by RustinCassiem** [keeweb/keeweb#1306]
**Describe the bug**
Started a new instance of keeweb and all I get is an error when compiling the browser-based app

**To Reproduce**
1. curl https://raw.githubusercontent.com/keeweb/keeweb/develop/dev-env.sh | bash -
2. go into /keeweb/keeweb
3. npm install -g and npm install grunt
4. grunt dev 
5.error that suggest tod --force
6 .grunt dev --force 
7. all errors I have when calling in the site 

GET https://localhost/site/Vault/css/main.css?__inline=true net::ERR_ABORTED 404 (Not Found)
localhost/:30 GET https://localhost/site/Vault/js/vendor.js?__inline=true net::ERR_ABORTED 404 (Not Found)
localhost/:31 GET https://localhost/site/Vault/js/app.js?__inline=true net::ERR_ABORTED 404 (Not Found)
localhost/:32 GET https://localhost/site/Vault/js/runtime.js?__inline=true net::ERR_ABORTED 404 (Not Found)
favicon-32x32.png:1 GET https://localhost/site/Vault/icons/favicon-32x32.png 404 (Not Found)
favicon-16x16.png:1 GET https://localhost/site/Vault/icons/favicon-16x16.png 404 (Not Found)

**Expected behavior**
TO compile and work, I havent changed any code or settings in the folder and it breaks

**Comment by antelle** [comment]
Hi!
Two things:
1. don’t use —force, this tells grunt that you don’t care about one of tasks, and the result is indeed broken.
2. you’re not hosting it properly, there’s some “Vault” in the url, we don’t have this. Grunt dev hosts itself, you can’t use it with your webserver.
