### ISSUE TITLE
Text is stripped/reformatted after pasting to Notes field

### ISSUE THREAD

**Issue by VKondakoff** [keeweb/keeweb#1307]
**Describe the bug**
Text is stripped/reformatted after pasting to Notes field:

<img width="843" alt="Screenshot 2019-10-16 at 12 05 48" src="https://user-images.githubusercontent.com/230824/66905159-0116f180-f00e-11e9-900e-cbdf8003ae66.png">

(original text in VSCode, resulting text after pasting into Notes field)

This looks quite dangerous to me, because the text copied back from Notes field using Copy button differs from the original.

Here is the original text:

```
Valery Kondakoff <email@adre.ss>

adress_revoke.asc:

-----BEGIN PGP PUBLIC KEY BLOCK-----
Version: GnuPG v1.2.1 (MingW32)
Comment: A revocation certificate should follow

<text_deleted>
-----END PGP PUBLIC KEY BLOCK-----
```

Here is the same text after it was pasted to Notes field and copied back:

```
Valery Kondakoff email@adre.ss

adress_revoke.asc:

-----BEGIN PGP PUBLIC KEY BLOCK----- Version: GnuPG v1.2.1 (MingW32) Comment: A revocation certificate should follow

-----END PGP PUBLIC KEY BLOCK-----
```

**Environment**
KeeWeb v1.11.9 (2c9c8b9a, 2019-10-13)
Environment: electron v6.0.10
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_0) AppleWebKit/537.36 (KHTML, like Gecko) KeeWeb/1.11.9 Chrome/76.0.3809.146 Electron/6.0.10 Safari/537.36

**Comment by VKondakoff** [comment]
Ok, I see - there is markup formatting available in Notes field. Can it be disabled?

**Comment by antelle** [comment]
Right, this is Markdown formatting.
Adding an option makes sense, will add it in the next release. This will be a global option indeed, not a per-entry switch.

**Comment by VKondakoff** [comment]
Thanks, global option is OК.

**Comment by antelle** [comment]
<img width="642" alt="Screen Shot 2019-10-17 at 19 14 00" src="https://user-images.githubusercontent.com/633557/67031788-8e436e80-f112-11e9-8975-0512f5021903.png">

**Comment by VKondakoff** [comment]
Perfect! Thank you!

**Comment by antelle** [comment]
Deployed to [beta.keeweb.info](https://beta.keeweb.info), will be available in the next release.
