### ISSUE TITLE
GL error

### ISSUE THREAD

**Issue by pepa65** [keeweb/keeweb#1308]
**Describe the bug**
When started from the commandline:
```[17888:1016/223618.307701:ERROR:buffer_manager.cc(488)] [.DisplayCompositor]GL ERROR :GL_INVALID_OPERATION : glBufferData: <- error from previous GL command```

**To Reproduce**
1. Install KeeWeb-1.11.9.linux.x64.deb
2. Enter `KeeWeb` on the commandline

**Expected behavior**
The window to open as before with version 1.10.0
(The sad part: if I uninstall 1.11.9 and reinstall 1.10.0, a similar error occurs...)

**Environment**
Ubuntu MATE 18.04.3

**Kdbx File**
This is before any database is even loaded.

**Logs**
Can't access the interface.

**Comment by antelle** [comment]
Hi! To be honest, I have no clue what this means. What happens if you download the Electron demo app?
https://github.com/electron/electron-api-demos/releases

**Comment by pepa65** [comment]
Could it be some corrupted configuration somewhere?? It is strange that the old version that always worked splendidly suddenly gives the same error...

**Comment by antelle** [comment]
So, does the demo app start?

**Comment by pepa65** [comment]
If I run `~/Electron API Demos-linux-x64/Electron\ API\ Demos` a window(less) titlebar with menubar come up.

**Comment by antelle** [comment]
Interesting

**Comment by pepa65** [comment]
Nothing else got installed or updated. I have to say, when the app offered to "do" an update, I clicked on it. (I didn't just install the .deb...) That didn't end well (I think in the end it hung).

**Comment by antelle** [comment]
Let's check if it happens on v1.12, it has a new Electron.

**Comment by pepa65** [comment]
The exact same error comes up:
```
[21249:1027/082759.994884:ERROR:buffer_manager.cc(488)] [.DisplayCompositor]GL ERROR :GL_INVALID_OPERATION : glBufferData: <- error from previous GL command
```
But then the interface does come up (taking somewhat longer?), and seems to work as normal!

**Comment by antelle** [comment]
perfect, thanks for checking!
