### ISSUE TITLE
FR: there is no intuitive way to exit attachment preview 

### ISSUE THREAD

**Issue by VKondakoff** [keeweb/keeweb#1309]
Currently there is no intuitive way to exit attachment preview once you clicked on attachment icon (both in mobile and desktop apps). The only way to do this is to click on the entry name in the entry list  once again: this is not good from the usability point of view.
I suggest to add small 'Close attachment preview' button beside the main attachment button when attachment preview is open. Or (maybe) it is a good idea to add a button 'Back' or 'Exit preview' on the top left of the attachment preview. Or just a small close button on the top right of the attachment preview.

**Comment by antelle** [comment]
Deployed to [beta.keeweb.info](https://beta.keeweb.info), will be available in the next release.
<img width="847" alt="Screen Shot 2020-03-15 at 12 50 33" src="https://user-images.githubusercontent.com/633557/76700815-9997c780-66bb-11ea-8e33-6b2680f09cf7.png">
