### ISSUE TITLE
FR: the "Generate password" button should be accessible from the start screen

### ISSUE THREAD

**Issue by VKondakoff** [keeweb/keeweb#1310]
The "Generate password" button (the one with the lightning in it) should be accessible from the start screen. User should not be forced to enter the password of the current database just to be able to generate new password.
I suggest to add "Generate password" button as the third icon on the KeeWeb start screen: "Open", "New", "Generate", "More".

**Comment by antelle** [comment]
I'm not sure what the generator should look like on that screen, now it's a small popup that looks quite bad there.

**Comment by VKondakoff** [comment]
Maybe like this (the icons are in wrong order):

<img width="950" alt="passgen" src="https://user-images.githubusercontent.com/230824/67030973-4247f800-f119-11e9-85d2-eca0e85455f4.png">

Or like this:

<img width="950" alt="passgen1" src="https://user-images.githubusercontent.com/230824/67031016-54299b00-f119-11e9-9cac-0c998c40801b.png">

Sorry for the quick mockups.
I'm using KeeWeb for a two days and already twice needed to generate passwords without needing to save them as an entries. This is why I asked for this feature.

**Comment by antelle** [comment]
That's what I mean, the small generator looks like crap. Also the button doesn't look like right, but the button is easier of course.

**Comment by antelle** [comment]
Added the generator, however its design should be ideally improved. Anyway, if you don't click it, it doesn't pop up, and the button itself is not ugly.

Deployed to [beta.keeweb.info](https://beta.keeweb.info), will be available in the next release.

<img width="689" alt="generator" src="https://user-images.githubusercontent.com/633557/67034414-e9c42b00-f117-11e9-8c73-502cb95c3f3a.png">

<img width="698" alt="expanded" src="https://user-images.githubusercontent.com/633557/67034421-ed57b200-f117-11e9-85e6-b150cf324283.png">

**Comment by VKondakoff** [comment]
Working (and looking) great! Thanks for adding this: the great tool is even better now. 👏🏻
