### ISSUE TITLE
Wrong Cyrillic font in Notes (when formatted as code)

### ISSUE THREAD

**Issue by VKondakoff** [keeweb/keeweb#1311]
If the Russian text in Notes is formatted as code: ` ``` ... ``` ` it is displayed in wrong font.

MacOS: 

<img width="271" alt="image" src="https://user-images.githubusercontent.com/230824/67017649-bfb43e00-f102-11e9-8292-97de814f48fd.png">

iOS:

![CFDB914D-F202-4288-836C-1E05128ED027_1_201_a](https://user-images.githubusercontent.com/230824/67017679-c93da600-f102-11e9-8ad1-506d9684ffd0.jpeg)

**Comment by antelle** [comment]
I noticed that it's not using proper monospace fonts in general, fixed that.

**Comment by antelle** [comment]
Deployed to [beta.keeweb.info](https://beta.keeweb.info), will be available in the next release. Meanwhile you can check if the formatting looks good to you there.

**Comment by VKondakoff** [comment]
Looks great, thank you!
