### ISSUE TITLE
Icons folder conflict with Apache default config

### ISSUE THREAD

**Issue by LeoBenoist** [keeweb/keeweb#1315]
**Describe the bug**
When installing a self hosted version of Keeweb (gh-pages) icons in the `/icons` folder appear to be 404.

After some investigation it appear the Apache Module alias (activated by default on debian) has the following config:

```
        # require it to be present in the URL.  So "/icons" isn't aliased in this
        # example, only "/icons/".  If the fakename is slash-terminated, then the
        # We include the /icons/ alias for FancyIndexed directory listings.  If
        Alias /icons/ "/usr/share/apache2/icons/"
        <Directory "/usr/share/apache2/icons">
```
Making keeweb icons folder inaccessible.

Disabling the module appear to be a bad idea:
```
root@X:/etc/apache2/mods-available# a2dismod alias
WARNING: The following essential module will be disabled.
This might result in unexpected behavior and should NOT be done
unless you know exactly what you are doing!
 alias
```
**Possible solution**
- Rename the `icons` folder and update manifest files
or
- Document the issue on how to comment that config part of apache

**Comment by antelle** [comment]
Hi! Do you have an example how to prevent this behavior in Apache?

**Comment by LeoBenoist** [comment]
I fixed it my commenting out `Alias /icons` in `/etc/apache2/mods-enabled/alias.conf`

If someone want to do it with Ansible this is my config.
```
- name: Fix Apache + Keeweb incompatibility
  replace: dest=/etc/apache2/mods-enabled/alias.conf regexp='Alias \/icons\/' replace='#Alias /icons/'
  notify: restart apache
```

**Comment by antelle** [comment]
Done: https://github.com/keeweb/keeweb/wiki/Self-Hosting
Will add a link to this page soon.

**Comment by LeoBenoist** [comment]
Thanks and have a nice day

**Comment by lx78WyY0J5** [comment]
I can't find this on the documentation,
This issue seem still valid, but is the page still active ?

(Same issue)

**Comment by lx78WyY0J5** [comment]
I made this to fix the issue
```
# Renaming the folder to a unique name
mv /var/www/keeweb/icons/ /var/www/keeweb/keeweb-icons

# Update each reference from /icons to /keeweb-icons
sed -i 's/"keweb-icons\//"keeweb-icons\//g' /var/www/keeweb/manifest.json

# Update reference for BrowserConfig
sed -i 's/"\/icons\//"\/keeweb-icons\//g' /var/www/keeweb/browserconfig.xml

# Update the index.html
sed -i 's/"icons\//"keeweb-icons\//g' /var/www/keeweb/index.html 

# Restart Apache
systemctl restart apache2
```

After installation,
On Apache **if you have the __alias__ module enabled**, just do this to have you'r icons back ❤️ 

Thanks Keeweb for the project ⭐
