### ISSUE TITLE
Show bits of entropy (password strength) at password generating page

### ISSUE THREAD

**Issue by gwy15** [keeweb/keeweb#1317]
Hi. As I recently changed my daily client from KeePass2 to KeeWeb, I noticed that the user-friendly 'bits of entropy' bar is missing in the password generating page (see the image below). This entropy bar is actually pretty helpful for users like me who love to keep passwords have a entropy no less than, say 60bits.

Are you guys planning to add the password strength indicating bar? Thanks a lot.

![image](https://user-images.githubusercontent.com/23229760/67156381-6b9e9900-f350-11e9-8f8a-670159070f46.png)

**Comment by antelle** [comment]
Hi! No, this is not planned and will not be accepted. Normally you don’t have to worry about it, unless you’re a cryptography expert and know how to interpret the numbers and what they really mean in practical sense.

**Comment by antelle** [comment]
Answering your question: if you have a certain preference for passwords, you can calculate the preset parameters, make a preset using “...” button, and set is a default.
