### ISSUE TITLE
[Feature Request] Merge change before save offline cache

### ISSUE THREAD

**Issue by emanuelr93** [keeweb/keeweb#1320]
I have a DB file in Google Drive. I see that application cache this DB on .config/KeeWeb/OfflineFiles. Because i need to sync this file with a VM that cannot connect to internet, from VM i replace file in OfflineFiles. If KeeWeb is open, if i use Sync button, i lost change on file maded by VM.
It is possible to Merge file before save it in OfflineFiles cache?
It can be useful also if is possible to customize path and file name of OfflineFiles cache. Some time it is needed to work on offline cache

**Comment by antelle** [comment]
Hi! To do this, you can open your file from the filesystem. In this case, if you replace the file, it will be merged.

**Comment by emanuelr93** [comment]
Yes, you are right! But in this mode you cannot make syncronization with Google Drive.
The use case is bit complicate but i can try to explain better

I have laptop and VM. The laptop is connected to internet and download database from Google Drive. I access to this database also from VM that dosen't have Internet Connection.
If i modify database from VM, the KeeWeb dosen't merge modify before send it to Google Drive.
But if i open this file from filesystem, i lost syncronization features.
I don't know if now it is most clear

**Comment by antelle** [comment]
I'm afraid, it's not quite clear. So, you have two installations:

1. with internet connection, connected to Google Drive
2. without internet connection, where a file is opened from file system

> i modify database from VM...
How exactly do you open it there? 

> ...KeeWeb dosen't merge modify before send it to Google Drive
You said the VM doesn't have Internet connection, what do you mean "sent it to Google Drive". All it can do is saving a file to FS, and then you need to somehow get it from there. What is meant here?

**Comment by emanuelr93** [comment]
> I'm afraid, it's not quite clear. So, you have two installations:
> 
> 1. with internet connection, connected to Google Drive
> 2. without internet connection, where a file is opened from file system
> 
> In this case, how do you open a file on the VM and when do you transfer it to/from it?
> 
> > i modify database from VM...
> 
> How exactly do you open it there?
I have a shared folder between VM and Physical Machine. So, i open file from VM insider cache folder.
> 
> > ...KeeWeb dosen't merge modify before send it to Google Drive
> 
> You said the VM doesn't have Internet connection, what do you mean "sent it to Google Drive". All it can do is saving a file to FS, and then you need to somehow get it from there. What is meant here?
I mean that i have save some change from VM that have shared folder with physical machine. After i use my physical machine to send file to google drive. In this case, KeeWeb dosen't syncronize but overwrite directly the cache file

**Comment by antelle** [comment]
Ok, now your intention seems to be clear.

> So, i open file from VM insider cache folder.

You shouldn't. It's not designed to work like this, and by doing this you break sync exactly the way you described. There can be other damages as well, especially when a file is modified but not synced. Cache is not an external storage and won't be treated as such.

Overall, what you described is a sync with several upstreams that is not (and will not) be implemented. For you an ideal scenario would be a possibility to open a file from a filesystem AND google drive in the same time. In this case there could be a possibility to listen to both storages and sync changes to both of them. Although the algorithm behind file merging guarantees eventual consistency, this kind of sync is: 1. very complicated to implement and maintain, 2. can require several sync rounds to reach this eventual consistency, 3. complicated to explain in terms of UX, 4. not needed for most of users.
