### ISSUE TITLE
Sync error

### ISSUE THREAD

**Issue by goffballz** [keeweb/keeweb#1321]
**Describe the bug**
Creating a new entry/group on Keepass Touch(iOS), having it sync with Dropbox, and opening it with Keeweb issues a "Sync error: TypeError: Cannot read property 'id' of undefined". Entry does not need anything additional.

**To Reproduce**
1. Add entry on Keepass Touch
2. Sync to Dropbox
3. Open database in Keeweb

**Expected behavior**
Sync correctly

**Screenshots**
![Sync Error](https://user-images.githubusercontent.com/57021156/67610554-341d5b80-f759-11e9-85b5-862e0cf92c97.PNG)

**Environment**
KeeWeb v1.11.10 (92215e88, 2019-10-16)
Environment: electron v6.0.10
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) KeeWeb/1.11.5 Chrome/76.0.3809.146 Electron/6.0.10 Safari/537.36

**Kdbx File**
Does it happen on Demo or New database?  Yes, new database (master password = password, needed for Keepass Touch): [New.zip](https://github.com/keeweb/keeweb/files/3774188/New.zip)
If you have a test db without your personal data, please attach it.

**Logs**
Please open dev tools in your browser and attach output log from Console tab. If you are using a desktop app, devtools can be opened from Settings/General/Advanced.
```
[INFO ] 2019-10-25T23:56:11.654Z [app] Started in 397ms ¯\_(ツ)_/¯
[INFO ] 2019-10-25T23:56:11.656Z [updater] Next update check will happen in 82687s
[INFO ] 2019-10-25T23:56:13.273Z [open:New] File open request
[INFO ] 2019-10-25T23:56:13.274Z [open:New] Open file from cache, will sync after load dropbox
[DEBUG] 2019-10-25T23:56:13.274Z [storage-cache] Load dde1ed8a-8609-be5f-6abd-8435cec0002a
[DEBUG] 2019-10-25T23:56:13.275Z [storage-cache] Loaded dde1ed8a-8609-be5f-6abd-8435cec0002a 1ms
[INFO ] 2019-10-25T23:56:13.275Z [open:New] Loaded file from cache null
[INFO ] 2019-10-25T23:56:13.307Z [file] Opened file New: 31ms, 300000 rounds, 1 kB
[DEBUG] 2019-10-25T23:56:13.307Z [app] Add last open file dde1ed8a-8609-be5f-6abd-8435cec0002a New dropbox /New.kdbx 595c4e2230ea6582a48c9
[INFO ] 2019-10-25T23:56:13.339Z [open:New] Sync just opened file
[INFO ] 2019-10-25T23:56:13.342Z [sync:New] Sync started dropbox /New.kdbx {}
[INFO ] 2019-10-25T23:56:13.343Z [sync:New] Stat file
[DEBUG] 2019-10-25T23:56:13.343Z [storage-dropbox] Stat /New.kdbx
[DEBUG] 2019-10-25T23:56:13.634Z [storage-dropbox] Stated /New.kdbx 595c4e4c44406582a48c9 291ms
[INFO ] 2019-10-25T23:56:13.634Z [sync:New] Found new version, loading from storage
[INFO ] 2019-10-25T23:56:13.634Z [sync:New] Load from storage, attempt 1
[DEBUG] 2019-10-25T23:56:13.635Z [storage-dropbox] Load /New.kdbx
[DEBUG] 2019-10-25T23:56:14.146Z [storage-dropbox] Loaded /New.kdbx 595c4e4c44406582a48c9 512ms
[INFO ] 2019-10-25T23:56:14.146Z [sync:New] Load from storage {"rev":"595c4e4c44406582a48c9"} no error
[ERROR] 2019-10-25T23:56:14.177Z [file] Error opening file to merge undefined Cannot read property 'id' of undefined TypeError: Cannot read property 'id' of undefined
[INFO ] 2019-10-25T23:56:14.177Z [sync:New] Merge complete TypeError: Cannot read property 'id' of undefined
[INFO ] 2019-10-25T23:56:14.180Z [sync:New] Sync finished TypeError: Cannot read property 'id' of undefined
```

**Comment by antelle** [comment]
Hi! Yes, this is a known issue in (#1286): KeePass Touch creates files with records without IDs which makes files unreadable. Please reach out to KeePass developers with an XML dump and explain that it shouldn't happen because if they create entries like this, syncing will produce unexpected results. I don't know how to reach out to them. Meh, I should say here, I do know, but I don't like them because of the way they redistribute the code, so I won't, and let their users do it instead.
I'm thinking, shall we fix it? It's of course easy to assign new ids if another client made a weird file, but I'm not sure if fixing it makes sense because sync can be really broken. I'll give it another round of thoughts tomorrow.

**Comment by goffballz** [comment]
Ahh okay. I appreciate the reply! 

I wish iOS had better options like Android. Do you know if KyPass 4 or Strongbox are any better in this regard? They seem the most updated along KeePass Touch. 

I used to use MiniKeePass but it hasn’t been updated in over 2 years. I just don’t want to run into any other known problems.

Thank you for all the hard work!

**Comment by antelle** [comment]
I added a fix in KeeWeb for this, the current version won’t show the error. But please keep in mind that if they write existing entries without UUID, sync will be broken and this is not possible to fix.
There are quite a lot of other good iOS clients: https://github.com/keeweb/keeweb/wiki/iOS, some of them are proper open-source, unlike KeePass Touch. I’m personally using Strongbox, works quite well for me.

**Comment by goffballz** [comment]
Of course, the wiki! I forgot that section was there. Anyways, thanks for the fix! I’m going to check out Strongbox.
