### ISSUE TITLE
Save to File button disappears

### ISSUE THREAD

**Issue by mkbaranovskyi** [keeweb/keeweb#1322]
"Save database to File" button disappears after changing the default file location. Seems to happen on all created databases, not demo though. 

Steps to reproduce:
1. Create a new database.
2. Save it to the custom file.
3. Done. The button "File" disappears from the possible options of saving. You can never change database file location or return to in-app sync. 

Expected behavior: the ability to change database file location and to return to the default in-app sync. 

Options before changing the default save path: 
![Screenshot from 2019-10-26 20-52-47](https://user-images.githubusercontent.com/39165507/67623851-c47b9f00-f832-11e9-9045-94c50fa28cef.png)
Options after saving to File (saved on Desktop):
![Screenshot from 2019-10-26 20-53-41](https://user-images.githubusercontent.com/39165507/67623879-073d7700-f833-11e9-89a7-75dde797db4f.png)

Environment: electron v6.0.12
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) KeeWeb/1.11.10 Chrome/76.0.3809.146 Electron/6.0.12 Safari/537.36

**Comment by antelle** [comment]
Hi! That's expected, once you save it, it remains there. To move the file, remove it from keeweb, move it in the filesystem, and open it again. Returning
