### ISSUE TITLE
After updating to v1.12 there is still v1.11.9 in KeeWeb -> About KeeWeb

### ISSUE THREAD

**Issue by VKondakoff** [keeweb/keeweb#1323]
After updating to v1.12 there is still v1.11.9 in KeeWeb -> About KeeWeb. Bug?
(macOS Catalina).

<img width="538" alt="Image on 2019-10-26 11 22 14 PM" src="https://user-images.githubusercontent.com/230824/67625495-994f7a80-f847-11e9-928e-f01498ec9d6f.png">

**Comment by antelle** [comment]
It was not possible to customize before, however now electron provides API for that: https://electronjs.org/docs/api/app#appsetaboutpaneloptionsoptions-macos-linux
