### ISSUE TITLE
After upgrade to 1.12.1 blank screen (MacOS)

### ISSUE THREAD

**Issue by henkvantijen** [keeweb/keeweb#1325]
**Describe the bug**
After upgrade to 1.12.1 blank screen (MacOS)

**To Reproduce**
Upgrade to 1.12.1 (on MacOS Mojave 10.14.6)

**Expected behavior**
Login screen / select source (DropBox and others)

**Screenshots**
Blank white screen

**Environment**
MacBook Air 2013, 8GB RAM, MacOS 10.1.4.6

**Kdbx File**
Don't know

**Logs**
        AEGetDescData of non-desc type 'reco' not a good idea

**Comment by antelle** [comment]
Hi! 
> AEGetDescData of non-desc type 'reco' not a good idea

Where is this displayed? I can't recognize this error.

**Comment by henkvantijen** [comment]
In the Console app 

![image](https://user-images.githubusercontent.com/977532/67636982-643e3900-f8d6-11e9-8cb4-191a63c9c555.png)

**Comment by antelle** [comment]
Weird, I have no idea what it is. What happens if you download the whole new app, without updating?

**Comment by henkvantijen** [comment]
I did just that: download, open .dmg, copy over to /Applications ,
overwriting older.

**Comment by antelle** [comment]
Strange, let's see if anyone else has this. I can't find anything interesting about this error in Electron.

**Comment by henkvantijen** [comment]
Mmm.. I am a bit stuck now.  I thought "let's try 1.11.10"  - but MacOS does not let me even mount the .dmg.  This is the error:
![image](https://user-images.githubusercontent.com/977532/67637300-740b4c80-f8d9-11e9-936d-9fe9ae921ce9.png)

**Comment by antelle** [comment]
If you right-click it and select "Open", then it shouldn't happen.

**Comment by antelle** [comment]
Looks like notarizing the app make it behave weird in macOS Mojave (also see #1292).

**Comment by antelle** [comment]
If anyone else has this issue, please comment here or add a reaction to the first post.
