### ISSUE TITLE
regression WebDav MOVE Destination Header

### ISSUE THREAD

**Issue by fredericrous** [keeweb/keeweb#1326]
**Describe the bug**
Fix of issue #1154 was reverted. I cannot update my key file anymore.
The commit that introduced the regression: https://github.com/keeweb/keeweb/commit/0fe67c9e4ab6a82070d7dc7e6fb97328d6e561a6

**To Reproduce**
The issue is reproducible on v1.12.1 of keeweb but not on v1.11.8
original description of the issue :
Setup a reverse proxy with https and forward the request to the keeweb backend (http)
The WebDav MOVE Destination will be set to https://...
This cannot be processed because the backend (http) requires starting the destination header url with http://... otherwise it will not find the destination and refuses with Bad Request 400

**Expected behavior**
The destination header should be set relativ to /
Then the protocol or any rewrites/proxy manipulations will not affect this mechanism.

**Comment by antelle** [comment]
Hi! This was reverted deliberately. According to [RFC2518](https://tools.ietf.org/html/rfc2518#section-9.3), it must be absolute.
> 9.3 Destination Header
>   Destination = "Destination" ":" absoluteURI
>   The Destination header specifies the URI which identifies a
>   destination resource for methods such as COPY and MOVE, which take
>   two URIs as parameters.  Note that the absoluteURI production is
>   defined in [RFC2396].

**Comment by antelle** [comment]
In order to make it work in your setup, I guess, you need to fix your proxy software.

**Comment by fredericrous** [comment]
Hello antelle, here is the header info I have clientside

```
:authority: keeweb.home.lab
:method: MOVE
:path: /dav/.keypassx.kdbx.1572194061041
:scheme: https
accept: */*
accept-encoding: gzip, deflate, br
accept-language: en-US,en;q=0.9,fr;q=0.8
authorization: Basic em91Z2k6OTY4NDQxeis=
cache-control: no-cache
destination: https://keeweb.home.lab/dav/keypassx.kdbx
origin: https://keeweb.home.lab
overwrite: T
pragma: no-cache
referer: https://keeweb.home.lab/
sec-fetch-mode: cors
sec-fetch-site: same-origin
```

Here is the header info I have serverside:

```
2019/10/27 17:39:09 [error] 6#6: *2 client sent invalid "Destination" header: "https://keeweb.home.lab/dav/keypassx.kdbx", client: 192.168.0.111, server: keeweb.home.lab, request: "MOVE /dav/.keypassx.kdbx.1572194170237 HTTP/1.1", host: "keeweb.home.lab", referrer: "https://keeweb.home.lab/"
```
What should I do? Keeweb is hosted on a nginx behind a traefik

**Comment by antelle** [comment]
This header seems to be valid, is there a way to understand what exactly is wrong with it? Which software generated the last piece of log (`client sent invalid "Destination" header`), was it nginx?

**Comment by antelle** [comment]
You can also switch the WebDAV mode to PUT in KeeWeb, most likely it will fix the issue.

**Comment by fredericrous** [comment]
yup, it was nginx. here is my configuration:

```
server {
    listen       80;
    server_name  keeweb.daddyshome.space;
    root         /usr/share/nginx/html/keeweb/;

    #charset koi8-r;
    access_log /usr/share/nginx/html/keeweb_error_access.log main;
    error_log /usr/share/nginx/html/keeweb_error.log error;

    location / {
        index  index.html;
        #rewrite ^/$ https://$host?config=/config.json permanent;
        set $args $args&config=/config.json;
    }
    
    location /dav/ {
        alias     /usr/share/nginx/html/dav/;
        client_body_temp_path /tmp;
        dav_methods     PUT DELETE MKCOL COPY MOVE;

        create_full_put_path  on;
        dav_access    user:rw group:rw all:rw; 

        auth_basic "Restricted Content";
        auth_basic_user_file /usr/share/nginx/pass/.htpasswd;

        add_header 'Access-Control-Allow-Origin' '*' always;
        add_header 'Access-Control-Allow-Credentials' 'true' always;
        add_header 'Access-Control-Allow-Methods' 'GET, HEAD, POST, PUT, OPTIONS, MOVE, DELETE, COPY, LOCK, UNLOCK' always;
        add_header 'Access-Control-Allow-Headers' 'Authorization,DNT,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,X-Accept-Charset,X-Accept,origin,accept,if-match,destination,overwrite' always;
        add_header 'Access-Control-Expose-Headers' 'ETag' always;
        add_header 'Access-Control-Max-Age' 1728000 always;
        if ($request_method = 'OPTIONS') {
            add_header 'Content-Type' 'text/plain charset=UTF-8';
            add_header 'Content-Length' 0;
            add_header 'Access-Control-Allow-Origin' '*';
            add_header 'Access-Control-Allow-Credentials' 'true';
            add_header 'Access-Control-Allow-Methods' 'GET, HEAD, POST, PUT, OPTIONS, MOVE, DELETE, COPY, LOCK, UNLOCK';
            add_header 'Access-Control-Allow-Headers' 'Authorization,DNT,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,X-Accept-Charset,X-Accept,origin,accept,if-match,destination,overwrite';
            add_header 'Access-Control-Expose-Headers' 'ETag';
            add_header 'Access-Control-Max-Age' 1728000;
            return 204;
        }
    }
}
```

I tried to add these lines based on stackoverflow but it did not solve the issue:

```
        set $destination $http_destination;
    
        if ($destination ~* ^https(.+)$) {
             set $destination http$1;
        }
    
        proxy_set_header Destination $destination;
```

**Comment by fredericrous** [comment]
How can I switch to put mode?

**Comment by antelle** [comment]
> `listen       80;`

That's the problem. In the place where you proxy HTTPS, you need to rewrite the Destination header as well. Which software do you use for this?

> How can I switch to put mode?
Settings → General → WebDAV → Save method

**Comment by fredericrous** [comment]
my reverse proxy is traefik. The nginx container has a rule like:

```
    "traefik.http.routers.nginx.rule" = "Host(`${var.domain}`)"
    "traefik.http.routers.nginx.service" = "nginx"
    "traefik.http.routers.nginx.tls.certResolver" = "letsencrypt"
    "traefik.http.services.nginx.loadbalancer.server.port" = "80"
```

I set up a global redirect rule to redirect http to https like this

```
http:
  routers:
    redirecttohttps:
      entryPoints:
        - web
      middlewares:
        - httpsredirect
      rule: HostRegexp(`{host:.+}`)
      service: noop

  middlewares:
    httpsredirect:
      redirectScheme:
        scheme: https

  services:
    # noop service, the URL will be never called
    noop:
      loadBalancer:
        servers:
          - url: http://X.X.X.X
```

I will try with the PUT method, thanks

**Comment by antelle** [comment]
You should do something like this there: https://forum.nginx.org/read.php?2,276838
> looks like traefik cannot edit headers

Well, then you're in trouble and this means that this proxy is not suitable for using with WebDAV. You can however hack it on nginx, like set up another internal upstream and rewrite the header there.

But switching to PUT will solve this problem, so probably you won't want to figure how how to fix the Destination header in this setup.

**Comment by fredericrous** [comment]
yes switching to PUT solve the issue and is enough for my needs. Thank you for the great support and reactivity @antelle

**Comment by williamdes** [comment]
> > `listen       80;`
> 
> That's the problem. In the place where you proxy HTTPS, you need to rewrite the Destination header as well. Which software do you use for this?
> 
> > How can I switch to put mode?
> 
> Settings → General → WebDAV → Save method

With the Android app FolderSync I had to disable "Temporary file mode".
I am using Nginx on alpine with the webdav mode installed
