### ISSUE TITLE
Add a visual notification, that there is a KeeWeb update available

### ISSUE THREAD

**Issue by VKondakoff** [keeweb/keeweb#1327]
As far as I can see, currently there is not visual notification of KeeWeb update available.
I suggest to add something like a color dot near of the Settings icon to indicate there is update available.
Quick mockup:

<img width="273" alt="KeeWeb_update" src="https://user-images.githubusercontent.com/230824/67683929-50acd400-f9a3-11e9-9ab3-38d095028ec1.png">

**Comment by antelle** [comment]
Hi! There’s a notification (a bell sign), however the updater is now broken.
