### ISSUE TITLE
Global shortcut to get the select auto-type window.

### ISSUE THREAD

**Issue by renyhp** [keeweb/keeweb#1329]
**Is your feature request related to a problem? Please describe.**
Sometimes you want to auto-type only a custom field, or auto-type something different from what is set in the auto-type sequence. The select auto-type window would be the perfect solution, but there is no way to make it pop up while on a window that already matches an entry in the database.

**Describe the solution you'd like**
Have a global shortcut working when the app is in the background to make the select auto-type window appear.

**Comment by antelle** [comment]
Hi! You can hit the global auto-type sequence to trigger the auto-type window. If no matching entry is found, you will see the selection window. You can also make KeeWeb always show the auto-type selection window, there's a checkbox in Settings / General / Function.

**Comment by tbradsha** [comment]
The use case scenario for me would be to retrieve a custom field (generally a OTP) for the few websites that have it.

Most of the sites I have accounts with have only one account, and thus the auto-type window won't pop up. This is great! I don't want a window popping up in most cases; skip that step.

However, if I need a OTP for a specific site, a shortcut to bring up the prefiltered auto-type window would be ideal.

I don't want KeeWeb to always show the auto-type window, as that adds an extra step for 95% of the accounts in question. Even the entries with a OTP don't always need it; it's often a periodic security check every few days.
