### ISSUE TITLE
Desktop version exposes Electron shell

### ISSUE THREAD

**Issue by Stephan-P** [keeweb/keeweb#1335]
**Describe the bug**
The Windows Desktop version (installed via downloadable installer) shows a top menu "File, Edit, View, Window, Help" that is all about the Electron shell and has little to do with the Keeweb app it is hosting. Also, this Electron shell is not displayed in the local language like Keeweb is.

**To Reproduce**
1. Download the Windows installer of KeeWeb
2. Start it
3. Notice the top menu: File, Edit, View, etc.
4. Particularly the items in the Help menu are very confusing, because they have no relation to KeeWeb
5. If KeeWeb is setup in a language other than English, the Electron top menu remains English

**Expected behavior**
Maybe the Electron top menu should be hidden

**Screenshots**
KeeWeb setup in Dutch language
![image](https://user-images.githubusercontent.com/10008599/68068299-76dfc480-fd53-11e9-91b8-c87904aba59d.png)

**Environment**
KeeWeb v1.12.1 (149c565e, 2019-10-27)
Environment: electron v7.0.0
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) KeeWeb/1.12.1 Chrome/78.0.3905.1 Electron/7.0.0 Safari/537.36

**Comment by antelle** [comment]
Hi! Looks like it doesn't repeat for me, is it also like this for other Electron apps (for example, the [demo-app](https://github.com/electron/electron-api-demos/releases))? The menu is hidden [here](https://github.com/keeweb/keeweb/blob/master/desktop/app.js#L365), but somehow it doesn't work for you.

**Comment by fovebil391** [comment]
Hi,

I'm also getting the same toolbar on linux using Debian 10.

KeeWeb v1.12.1 (149c565e, 2019-10-27)
Environment: electron v7.0.0
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) KeeWeb/1.12.1 Chrome/78.0.3905.1 Electron/7.0.0 Safari/537.36

It seem it's not only a Windows problem. My Keeweb is in french if it can help.

**Comment by Coises** [comment]
The menu bar shows here, too, using Windows 10 Pro (1903/18362.418):

KeeWeb v1.12.1 (149c565e, 2019-10-27)
Environment: electron v7.0.0
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) KeeWeb/1.12.1 Chrome/78.0.3905.1 Electron/7.0.0 Safari/537.36.

I don't have a development environment set up right now, but could it be related to this comment:
https://stackoverflow.com/a/58548866
which suggests that menu bar handling changed in Electron 7.0?  I found this:
https://github.com/electron/electron/pull/19557
but that fix should be part of production 7.0.  I can't find anyone claiming failure of this method as a 7.0 bug, but 7.0 is rather new, so perhaps it just hasn't been noted yet.

**Comment by antelle** [comment]
While my Windows 10 is somewhat stuck, I managed to reproduce it on Ubuntu, most likely fixing it will fix it on Windows as well. I'll take a look next week.

**Comment by antelle** [comment]
New version should have the menu hidden.
