### ISSUE TITLE
Cannot view trash

### ISSUE THREAD

**Issue by rEnr3n** [keeweb/keeweb#1337]
**Describe the bug**
I cannot see the entries inside the trash when I click it. Clicking on `Trash` does not show it's empty. The main screen doesn't change as if I didn't click on it.

My database was kdbx3 when I encountered the bug. I changed it to kdbx4 (argon2) but I still have the same issue.

**To Reproduce**
1. Take note of main screen for active view (default is "All Items")
1. Click on `Trash`
1. See error (main screen remain unchanged)

**Expected behavior**
I should be able to see the entries on my trash. I am able to verify from another password manager that the trash has contents intact.

**Environment**
```
KeeWeb v1.12.1 (149c565e, 2019-10-27)
Environment: electron v7.0.0
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) KeeWeb/1.12.1 Chrome/78.0.3905.1 Electron/7.0.0 Safari/537.36
```

**Kdbx File**
Does it happen on Demo or New database?  
- It does not happen on demo or new database.

**Logs**
```
index.html:1 Uncaught Error: Attempt to write p into r
    at o (index.html:1)
    at Proxy.unshift (index.html:1)
    at index.html:1
    at Array.forEach (<anonymous>)
    at index.html:1
    at Array.forEach (<anonymous>)
    at Proxy.value (index.html:1)
    at P.addTrashGroups (index.html:1)
    at P.getEntries (index.html:1)
    at P.setFilter (index.html:1)
```

**Comment by antelle** [comment]
Hi! Thanks, I found a way to reproduce it, this happens when a group is moved to trash, will be fixed soon.
