### ISSUE TITLE
http status 403

### ISSUE THREAD

**Issue by FanyangMengDev** [keeweb/keeweb#1339]
**Describe the bug**
Set the configuration like how it said in your wiki. And go to the url which has added ?config=config.json. But when I click google drive and log in, it displays 'There was an error loading file list http status 403'

**To Reproduce**
1. Go to url with '?config=config.json'
2. Click on Google Drive
3. Log in

**Expected behavior**
it should be opened directly right?

**Screenshots**
![Screenshot_2019-11-03-19-51-22-431_com android chrome](https://user-images.githubusercontent.com/53750381/68084646-750d2280-fe73-11e9-9580-5c6b7af0fb14.jpg)

**Environment**
Web page version

**Logs**
Please open dev tools in your browser and attach output log from Console tab. If you are using a desktop app, devtools can be opened from Settings/General/Advanced.

**Comment by antelle** [comment]
Hi! Let's find this request in Network, maybe it explains what's going on?

**Comment by FanyangMengDev** [comment]
Sorry I don't understand you. Are you saying that I need to have a check on server network? I just check it and it's fine. I really do not know why this happened.

**Comment by antelle** [comment]
I mean, there's a 403 request somewhere. Most likely Google returns something meaningful inside, for example, it may contain error description in the response. This help you understanding the issue. To find this thing, you need to go to Network, find a request that returns 403 and check what's there.

**Comment by FanyangMengDev** [comment]
Oh I can feel you now. I am in the restaurant now and when I come back home I will have a check. Please allow me a few minutes. Thank you.

**Comment by FanyangMengDev** [comment]
Hi there,
I have solved this problem, I found that the Network alerts me that I need to active the API after create the web client, after that all is well now.
But I have to ask one more question, now when I input the url, I have to add config.json to the url, if I log in without adding config.json, I cannot log in Google drive, Could you please help me about that? How can I make this config file into the default URL?
Thank you so much for your hardworking

**Comment by antelle** [comment]
You can modify `kw-config` meta-tag in the HTML to be able to load without changing the url: https://github.com/keeweb/keeweb/wiki/Configuration#json-app-config
