### ISSUE TITLE
iPadOS 13's browsers display blank page

### ISSUE THREAD

**Issue by FanyangMengDev** [keeweb/keeweb#1340]
**Describe the bug**
Using the latest version of KeeWeb. But when switch to the iPad Pro 2018 with iPadOS 13 and input the url in both Chrome and Safari, I just got a blank page.

**To Reproduce**
1. Using iPadOS 13
2. Click on Chrome and Safari
3. Input my url https://pswd.fanyangmeng.com

**Expected behavior**
It should display the same page as in Windows or Android

**Screenshots**
![B57AD3B9-07B1-41E6-ADD6-50CCC121647F](https://user-images.githubusercontent.com/53750381/68178600-8ff0ab80-ffc7-11e9-85b3-561c60d99907.png)

**Environment**
KeeWeb, in Ubuntu 18.04 LTS. Using Chrome and Safari on iPad with iPad OS 13

**Logs**
iPad's application does not has this tool

**Comment by antelle** [comment]
Hi! Does app.keeweb.info work?

**Comment by FanyangMengDev** [comment]
Yours works fine to me.
So it really confused me so much.
And now I have just change to bitwarden.....
I just unzip your webpage file to the root of the website and it works fine on my PC and Android.
Really do not know why.

**Comment by antelle** [comment]
In this case something is wrong 
with your setup. You can try connecting to your ipad and check console logs, this can help.

**Comment by FanyangMengDev** [comment]
Ah..... OK. Please allow me a few hours, after I got home I will use my test server to test it and forward the logs to you.
Thank you

**Comment by antelle** [comment]
Please feel free to reopen with more info
