### ISSUE TITLE
Auto Lock does not lock the DB when Computer get locked on Windows 10

### ISSUE THREAD

**Issue by gynet** [keeweb/keeweb#1341]
**Describe the bug**
Turn on the option, auto lock when computer is locked, keeweb not lock the db on Windows 10

**To Reproduce**
1. Turn on the option
2. Lock computer
3. Unlock computer
4. The DB remains open

**Environment**
KeeWeb v1.12.3 (9b07bbd5, 2019-11-06)
Environment: electron v6.0.2
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) KeeWeb/1.9.0 Chrome/76.0.3809.110 Electron/6.0.2 Safari/537.36

**Comment by antelle** [comment]
Yeah, the only question is how to do it in Electron. On macOS we're using [this method](https://electronjs.org/docs/api/system-preferences#systempreferencessubscribenotificationevent-callback-macos), not sure if they also added a way to do it in Windows and Linux.

**Comment by antelle** [comment]
Actually, there's this now: https://electronjs.org/docs/api/power-monitor#event-lock-screen-macos-windows

**Comment by antelle** [comment]
It works as expected on macOS and I assume it should work on Windows (and Linux, once implemented in Electron) as well, nice, removed the old hack.
