### ISSUE TITLE
KeeWeb v1.12.3 for Linux 64 bits fails to open on openSuse 15.0

### ISSUE THREAD

**Issue by EricBrunel** [keeweb/keeweb#1344]
I just downloaded the latest version of KeeWeb (v1.12.3) to try it out on openSuse Linux 15.0 (64 bits). But the application doesn't launch at all: there's no error message, no significant exit code, nothing; when I run the command, it just exits at once.
My system is up to date for everything, and the KeeWeb version I have now (v1.8.0) works perfectly.

**Comment by antelle** [comment]
Hi! Does the [Electron demo app](https://github.com/electron/electron-api-demos/releases) work for you? Maybe there is anything interesting in system logs?
