### ISSUE TITLE
WebDAV network error 

### ISSUE THREAD

**Issue by SrDayne** [keeweb/keeweb#1347]
**Describe the bug**
Hello. First of all, I want to thank you for your work and this application.
I'm trying to open database, that is located on WebDAV server. For WebDav i'm using Apache webserver(version 2.4.34). It's running directly on local machine. For domain address I'm using local domain name testbase.loc. I configured it like it said in a wiki:
https://github.com/keeweb/keeweb/wiki/WebDAV-Config
Also, I'm using https connection to WebDAV with self-signed certificate. 

And keeweb server I'm running in docker container, like it said here, in "Self-hosting" section:
https://github.com/keeweb/keeweb

So, I'm trying to connect keeweb to WebDAV and gain network error.

I succesfully connected to my WebDAV server from Ubuntu file manager, from Mozilla, Chrome and EDGE browsers.

Help me, please, to handle this problem.

**Steps to reproduce the behavior:**
1. Use WebDAV connection
2. Try to connect to database

**Expected behavior**
Succesfully connected database.

**Screenshots**
Attached

**Environment**
Mozilla, Chrome, Edge

**Logs**
```
[DEBUG] 2019-11-12T15:00:15.394Z [storage-webdav] Stat https://testbase.loc:442/webdav/ls.kbdx

[DEBUG] 2019-11-12T15:00:15.464Z [storage-webdav] Stat error https://testbase.loc:442/webdav/ls.kbdx 70ms

[DEBUG] 2019-11-12T15:00:26.965Z [storage-webdav] Stat https://testbase.loc:442/webdav/

[DEBUG] 2019-11-12T15:00:27.004Z [storage-webdav] Stat error https://testbase.loc:442/webdav/ 39ms

[DEBUG] 2019-11-12T15:08:30.406Z [storage-webdav] Stat https://testbase.loc:442/webdav/

[DEBUG] 2019-11-12T15:08:30.611Z [storage-webdav] Stat error https://testbase.loc:442/webdav/ 204ms
```
Apache WebDAV config:

```
DavLockDB /var/www/DavLock
<VirtualHost *:442>

	ServerAdmin webmaster@localhost
	DocumentRoot /var/www/html
        SSLEngine on
        SSLCertificateFile /var/www/webdav/testbase.loc.crt
        SSLCertificateKeyFile /var/www/webdav/testbase.loc.key

	ErrorLog ${APACHE_LOG_DIR}/error.log
	CustomLog ${APACHE_LOG_DIR}/access.log combined

        RewriteEngine on
        RewriteCond %{REQUEST_METHOD} OPTIONS
        RewriteRule ^(.*)$ blank.html [R=200,L,E=HTTP_ORIGIN:%{HTTP:ORIGIN}]

        Alias /webdav /var/www/webdav 
        <Directory /var/www/webdav> 
         AuthType Basic
         AuthName "webdav"
         AuthBasicProvider file
         AuthUserFile /etc/apache2/webdav.passwords
         Require valid-user

         DAV On
         Options Indexes
         Header always set Access-Control-Allow-Origin "*"
         Header always set Access-Control-Allow-Headers "origin, content-type, cache-control, accept, authorization, if-match, destination, overwrite"
         Header always set Access-Control-Expose-Headers "ETag"
         Header always set Access-Control-Allow-Methods "GET, HEAD, POST, PUT, OPTIONS, MOVE, DELETE, COPY, LOCK, UNLOCK"
         Header always set Access-Control-Allow-Credentials "true"
        </Directory>
</VirtualHost>
```
![22222](https://user-images.githubusercontent.com/45735480/68685560-96a09500-056a-11ea-92fb-2c4fbc2f41cb.png)

**Comment by antelle** [comment]
Hi! If you find a failed request in Network panel, it will give more information.

**Comment by SrDayne** [comment]
Thanks for response. There are no failed requests in Network panel. Only that, on the screenshot.

**Comment by antelle** [comment]
Anything interesting in Console?

**Comment by SrDayne** [comment]
```
`This site appears to use a scroll-linked positioning effect. This may not work well with asynchronous panning; see https://developer.mozilla.org/docs/Mozilla/Performance/ScrollLinkedEffects for further details and to join the discussion on related tools and features! 

2019-11-12T15:34:53.966Z [storage-webdav] Stat https://testbase.loc:442/webdav/lans.kbdx 

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://testbase.loc:442/webdav/lans.kbdx. (Reason: CORS request did not succeed).`
```

**Comment by SrDayne** [comment]
(Reason: CORS request did not succeed)

But why? I enabled it in Apache config.

**Comment by antelle** [comment]
This means, OPTIONS didn’t return what was expected.

**Comment by SrDayne** [comment]
> This means, OPTIONS didn’t return what was expected.

So what settings for CORS in Apache had to be?

**Comment by antelle** [comment]
I have no idea, but it shod return Access-Control-* headers mentioned here: https://github.com/keeweb/keeweb/wiki/WebDAV-Config

**Comment by SrDayne** [comment]
Yes, I configured it like said there. I attached config file in ticket.

**Comment by SrDayne** [comment]
Hello again. I installed WebDAV on Nginx with config like in a wiki, and now it works. Seems like apache config is incorrect. Maybe this will help other.

**Comment by FillyAgioro** [comment]
I also can't connect to my kdbx file in pCloud through webdav https://webdav.pcloud.com. It always shows `Error: network error.

**Comment by GuilhermeStrice** [comment]
heres a working config, at least for me

```
RewriteEngine On
RewriteCond %{REQUEST_METHOD} OPTIONS
RewriteRule ^(.*)$ $1 [R=200,L]

Header always set Access-Control-Allow-Origin "*"
Header always set Access-Control-Allow-Headers "origin, content-type, cache-control, accept, authorization, if-match, destination, overwrite"
Header always set Access-Control-Expose-Headers "ETag"
Header always set Access-Control-Allow-Methods "GET, HEAD, POST, PUT, OPTIONS, MOVE, DELETE, COPY, LOCK, UNLOCK"
Header always set Access-Control-Allow-Credentials "true"

<Directory /thingy/path/whatever>
  AuthType Basic
  AuthName "Restricted Content"
  AuthUserFile /usr/local/apache/var/users.password
  Require valid-user
  
  DAV On
</Directory>
```

**Comment by ratatouillex** [comment]
It's a nightmare. webdav doesn't work at all. not in my installation and not in https://app.keeweb.info/
any ideas?
my link was: https://cloud.***.com/remote.php/dav/files/username/z_myShare/kbdx/Passwords.kdbx

**Comment by demoulins** [comment]
I have the same issue. 
I get an "Network error" to acces my file by Webdav. The same address in a browser open the KeePass file.

**Comment by WildaCZ** [comment]
I have the same problem, using Caddy as reverse proxy. Both self-hosted keeweb and the public one only gives "Network error". All other WebDAV apps work fine so it's definitely an issue with Keewebs implementation :-( Sucks because on mobile Keepass2Android works fine but on Chromebook Keeweb seems like the best solution by far.
