### ISSUE TITLE
Does application UI become really locked during run in background (alt+tab) ?

### ISSUE THREAD

**Issue by isbad** [keeweb/keeweb#135]
It seems desktop app shows unlocked and becomes locked in a moment if you're using "Auto-lock" setting. Not sure if it is a real (or keeweb related) issue but may worth attention. 

STR: 
- Open personal db (default window size)
- Set General -» Function -» Auto-lock if app is inactive in 5 minutes
- Switch (atl+tab) to another maximized (using spectacle app if it matters) app and do not open keeweb for at least 5 min
- Then switch back to keeweb

CR: 
UI shows unlocked and becomes locked in a moment

- desktop app
- OS X El Capitan 10.11.3
- new db w/ personal data
- v1.0.4

**Comment by antelle** [comment]
This is very strange, I'll verify this. The apps locks by timeout, maybe something like animations issue (which could be played when you return to the app).

**Comment by isbad** [comment]
Thank you! Will try to provide more info. Meantime, most probably I'm doing something wrong, so appreciate any info. I've some issues w/ running grunt tasks in os x (clean, copy, webpack), that seems to be os/path related: 

```
...
Running "copy:fonts" (copy) task
Verifying property copy.fonts exists in config...OK
Files: bower_components/font-awesome/fonts/fontawesome-webfont.* -> tmp/fonts/fontawesome-webfont.*
Options: encoding="utf8", processContent=false, processContentExclude=[], timestamp=false, mode=false
Copying bower_components/font-awesome/fonts/fontawesome-webfont.* -> tmp/fonts/fontawesome-webfont.*
Reading bower_components/font-awesome/fonts/fontawesome-webfont.*...ERROR
Warning: Unable to read "bower_components/font-awesome/fonts/fontawesome-webfont.*" file (Error code: ENOENT). Use --force to continue.
```

```
...
ERROR in ./app/scripts/views/dropdown-view.js
Module not found: Error: Cannot resolve module 'jquery/dist/jquery.min.js' in /Users/bad/zoo/keeweb/app/scripts/views
 @ ./app/scripts/views/dropdown-view.js 1:0-17

ERROR in ./app/scripts/models/menu/menu-option-model.js
Module not found: Error: Cannot resolve module 'backbone/backbone-min.js' in /Users/bad/zoo/keeweb/app/scripts/models/menu
 @ ./app/scripts/models/menu/menu-option-model.js 3:15-34
Warning: Task "webpack:js" failed. Use --force to continue.
```

You are using win8, right ? 
What is the right way to run unbuild version in browser ? 

Thanks

**Comment by antelle** [comment]
I'm using OX X as well (node.js v5, npm v3).
Does simply running `grunt` work for you?
There's no way to run unbuilt version, as source code require preprocessing. I use `grunt` and then `grunt watch` running in background to rebuild the app in `tmp` on changes.

**Comment by isbad** [comment]
> I'm using OS X as well (node.js v5, npm v3).

Same for me: v5.7.0, 3.8.0, 1.7.7 bower

> Does simply running `grunt` work for you?

Nope. After clear install npm & bower install with no any issues I've got an error: 

```
Running "clean:dist" (clean) task
Verifying property clean.dist exists in config...OK
Files: dist, tmp -> dist
Options: force=false, no-write=false
ERROR
Warning: Cannot delete files outside the current working directory. Use --force to continue.

Aborted due to warnings.
```

> There's no way to run unbuilt version, as source code require preprocessing

Is it possible to build source maps for dev purposes (having something like `grunt build` which is the current one and `grunt` _default_ w/ sourcemaps) ?

**Comment by antelle** [comment]
Oh, that's interesting. How it could be possible?
Obviously there's no clean outside working directory here: https://github.com/antelle/keeweb/blob/master/Gruntfile.js#L60

It's possible but requires gruntfile tuning, I had some issues with sourcemaps, I don't remember which exactly.

**Comment by antelle** [comment]
Wow. My nodejs was v5.4. After upgrading it to v5.7 I get the same error. I'll go and post a bug in grunt-contrib-clean, if it's not yet posted.

**Comment by antelle** [comment]
Some has already did: https://github.com/gruntjs/grunt-contrib-clean/issues/85

**Comment by isbad** [comment]
Thank you :beer: ! Will switch to lower version for now (and google next time)

**Comment by antelle** [comment]
Back to the issue: I've asked a question about a flicker on return to hidden app window here: https://github.com/atom/electron/issues/4645
Let's see whether someone knows the solution. Fast googling gave no result...

**Comment by antelle** [comment]
So, electron issue was closed without providing any workaround.
I've tried to change window size, background, or execute javascript inside webContents but not, it didn't help. As a possible solution, we can invalidate window rect from low-level native add-on but this is very hard way.

**Comment by antelle** [comment]
New flag was added in Electron, v1.3 will make use of it.
