### ISSUE TITLE
Password shown 

### ISSUE THREAD

**Issue by ChrisFromLafare** [keeweb/keeweb#1353]
**Is your feature request related to a problem? Please describe.**
Feature request associated to issue _#1295_

**Describe the solution you'd like**
Some other clients doesn't mark the password field as protected - it results in passwords shown by Keeweb. The password field should be managed as a password field wether or not it is marked as protected.

**Comment by antelle** [comment]
These clients should be fixed in first place. But we can force hidden mode for passwords of course.
