### ISSUE TITLE
Webdav web access ok, desktop app network error

### ISSUE THREAD

**Issue by nihilstic** [keeweb/keeweb#1354]
Hi,

Got an issue with webdav can't find figure out.

I got a brand new setup with : 

- SSL enabled setup working fine (https://hub.docker.com/r/deatheibon/keeweb-ssldav)
- Created my New.kdbx file and added it to my webdav (https) through davfs connection (Caja file finder from MATE Ubuntu), working fine 
- Connected to https://mydomain/ prompted more and configured webdav connection to my New.kdbx, working fine aswell
- I tested my kdbx url https://mydomain.com/webdav/New.kdbx from my web browser, it prompt login, and download my kdbx.

So i decided to connected this New.kdbx from my desktop app so i can use browser autofill, and with same setup i got and error : 

> Error: network error

> [DEBUG] 2019-11-20T10:37:47.057Z [storage-webdav] Stat https://mydomain.com/webdav/New.kdbx
[DEBUG] 2019-11-20T10:37:47.089Z [storage-webdav] Stat error https://mydomain.com/webdav/New.kdbx 31ms

I've checked dns setup everything is ok i can't find out what's going on.

Do you have an idea ? Keeweb is a fantastic project and answer to all my needs i really want to get it working !

**Comment by antelle** [comment]
Hi! Let's check Network tab in devtools (can be opened in Settings > General).

**Comment by nihilstic** [comment]
Hi, i'm not using network-manager, got classic config through /etc/network/interfaces

> auto lo
iface lo inet loopback

auto enp2s0
iface enp2s0 inet dhcp

+/etc/resolv.conf
search mydomain.com
nameserver localipofmydns

**Comment by antelle** [comment]
I mean, the Network tab in DevTools in KeeWeb.

**Comment by nihilstic** [comment]
I didnt saw the DevTools tab at first and now that i got it i find out myself it was due to the dockerhub container default network configuration given by the guy who made it. I removed it and it's working fine. Thanks for your help, keep going your project it is awesome !
