### ISSUE TITLE
Open Keepass file located in Nextcloud files

### ISSUE THREAD

**Issue by tiptruck** [keeweb/keeweb#1355]
I have a Keepass file located in my Nextcloud files.  It would be useful to be able to select to open that file using Keeweb to make my database available anywhere.

KeeWeb v1.8.2 (ebe7d35c, 2019-05-15)
Environment: web
User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:66.0) Gecko/20100101 Firefox/66.0

**Comment by Strubbl** [comment]
Yes, i second this. I tried with webdav, but that did not work.

**Comment by antelle** [comment]
Hi You can use WebDAV, or this project: https://github.com/jhass/nextcloud-keeweb
I guess, Nextcloud doesn't have JavaScript API like Dropbox or Google Drive.

**Comment by Strubbl** [comment]
Thanks a lot for the pointer. The nextcloud-keeweb plugin is linking to this repository in the help as it's the same settings/help page as in this keeweb

**Comment by vacy** [comment]
i digged a little into this idea of hosting the kdbx on nextcloud and have a standalone keeweb running.
but the kdbx needs to be available via OPTIONS without authentication, but nextclouds sabredav doesnt allow that, no matter what you tweak on your webserver. 
https://github.com/keeweb/keeweb/wiki/WebDAV%20Config
