### ISSUE TITLE
Nextcloud + KeeWeb

### ISSUE THREAD

**Issue by CoplandTech** [keeweb/keeweb#1358]
Hey. Sorry copy post! When installing KeeWeb, I encountered a problem where I need to create the config.json file
I tried to install it outside the keeweb directory on the path www/nextcloud/app-pkg. Also installed in keeweb/template.
When called in url/apps/keeweb/?config=config.json, the result: Redirects to the nextcloud home directory, when you go to url/apps/keeweb/keeweb/?config=config.json, the result: Invalid application URL.
There are no special errors in the browser console.

The config.json file is needed to specify the gID in Google Drive.

**Comment by antelle** [comment]
Hi! I can't help with nextcloud, perhaps this project is more relevant: https://github.com/jhass/nextcloud-keeweb/issues
