### ISSUE TITLE
Electron or PWA?

### ISSUE THREAD

**Issue by Stephan-P** [keeweb/keeweb#1360]
KeeWeb Desktop is Electron based and through the KeePassHttp-Connector it can provide Autofill facilities in browsers.

Modern webbrowsers are starting to offer functionality to install a website as a PWA. 
I just used Edge Dev to install app.keeweb.info as a PWA on my W10 laptop. 
Unfortunately I was not able to install the KeePassHttp-Connector plugin in this setting and so the autofill connection was not (yet) possible.

This brings up a question of future direction:
- To continue along the Electron path
- or change direction to PWA for local installation KeeWeb?

**Comment by antelle** [comment]
Hi!
KeeWeb can be actually added as PWA on iOS and Android. Installing as PWA however don't give a lot of advantage on desktop and now it has less possibilities compared to Electron.
So, for example, as you already noticed, it's not possible (and I guess, won't be possible in the nearest future) to use things like KeePassHttp-Connector or something else.
Actually I don't understand the question or proposal being suggested:
- Shall we switch to PWA on desktop? No.
- Do we need to support PWA? Yes, for example, on ChromeOS it's the only way to install an "app" (I haven't checked if it works on ChromeOS though, most likely not).

**Comment by Stephan-P** [comment]
And through what method can a connection be established between Keeweb PWA and the webbrowser in order to obtain autofill functionality?

**Comment by antelle** [comment]
I don’t know if it will appear in future, it’s possible. For now there’s no such method.

**Comment by loginov-rocks** [comment]
Despite the initial question was rather about the desktop version, I want to highlight, that https://app.keeweb.info isn't suggested as installable either on Android, neither on macOS. May we track this issue in here?

**Comment by antelle** [comment]
@loginov-rocks I didn't get it, why it's not suggested? For example, iOS shows a suggestion to install it in Sharing, which should also work on Android.

**Comment by loginov-rocks** [comment]
@antelle I have never got an installation suggestion on Android One (pure 9, 10) device.
