### ISSUE TITLE
"Show entries from all subgroups" disabled by default, like on KeePassX

### ISSUE THREAD

**Issue by DaniellMesquita** [keeweb/keeweb#1361]

**Comment by antelle** [comment]
No, an option is enough.
I’m sorry to give such a brief explanation, but it’s exactly the amount of motivation you provided.

**Comment by DaniellMesquita** [comment]
Yes, it will be yet a option. What I suggest is disabling it by default.
Sorry, "like on KeePassX (and KeePassXC)" isn't a good motivation.
I propose that because I had the need to disable it, as the app had a flood instead of organizing like KeePassX does.

**Comment by antelle** [comment]
That's another way of organizing things, it mostly depends on how people think of their database, so there's an option for different representations. The one with all entries feels more native to keeweb where all is put into one list, in the same way we don't have tabs for files and instead all entries can be found in one place.
