### ISSUE TITLE
x32 build for .deb

### ISSUE THREAD

**Issue by DaniellMesquita** [keeweb/keeweb#1362]

**Comment by antelle** [comment]
There’s no electron for x86 anymore

**Comment by DaniellMesquita** [comment]
That's how Muon will be useful, if it implements what KeeWeb needs. Reference: https://github.com/keeweb/keeweb/issues/1363

**Comment by antelle** [comment]
I fully agree with Electron’s motivation and don’t think we should release a 32bit version in 2020.
