### ISSUE TITLE
Autosave after unlock and after each change

### ISSUE THREAD

**Issue by dkeso** [keeweb/keeweb#1364]
**Is your feature request related to a problem? Please describe.**
If possible, it would be great to automatically sync after each change in the database (creation/modification/deletion entry/group/something/etc.) and after unlocking the db.

**Describe the solution you'd like**
Automatic sync after unlocking and each database modification (add/mod/del).

**Describe alternatives you've considered**
Set the current autosync feature with lower timing or saving and syncing manually, but I think it is more efficient and convenient to (also) automatically sync after every change and when unlocking the database.

**Additional context**
...

**Comment by antelle** [comment]
There’s already sync in unlock. Option to trigger it after change would make sense, however it needs a small throttling, like 10s or so (to avoid saving a lot of versions when editing text fields).

**Comment by efrandin** [comment]
Hello!  Just checking if there was any traction on this?

**Comment by StanSvec** [comment]
Glad to hear that _sync on unlock_ is already implemented. It's very useful when the database file is shared. Would be a good idea to implement this auto sync feature in a way that it's triggered automatically in certain interval which can be configured in the settings?

**Comment by antelle** [comment]
@StanSvec it's already implemented, will be released in the next version.
