### ISSUE TITLE
Save to disk AND sync to Google Drive / Dropbox?

### ISSUE THREAD

**Issue by koosvanderkolk** [keeweb/keeweb#1365]
I would like Keeweb to save a copy of the kdbx files to a local drive AND sync it to the cloud (Google Drive, Dropbox etc).

The current behavior seems to be OR to a local drive OR to the cloud.

Use cases:
* Sometimes I have access to my local drive, but not to the cloud; sometimes I have access to the cloud, but not to my local drive. E.g. working while traveling on my laptop and accessing the kdbx files on my phone.
* Using the cloud as a backup mechanism for the kdbx files, not as primary use.

**Comment by antelle** [comment]
Hi!

Looks like we already have it. In theory, offline mode should work for you. If you open a file from a cloud storage, it will be saved to so-called OfflineFiles on your disk, then when you try to open it and the cloud storage is not available, it will be saved back there and synced when you open it with a network connection. If you make changes on both devices offline, they will be merged when you connect the network.

Additionally you can back up your file to another storage.

About using cloud as a backup mechanism, there's an option to backup to Dropbox:
<img width="564" alt="Screen Shot 2019-12-04 at 18 38 23" src="https://user-images.githubusercontent.com/633557/70166536-4201bd00-16c5-11ea-82e0-f9b94121b6af.png">
