### ISSUE TITLE
Auto-Type based on Window title

### ISSUE THREAD

**Issue by josephernest** [keeweb/keeweb#1368]
Hello,
I imagine this feature exists out of the box with KeeWeb, but I couldn't find it in the [Autotype documentation](https://github.com/keeweb/keeweb/wiki/Auto-Type) nor in the README.md.

Example: you're on the Github login page in Chrome.
Is it possible, with a global keyboard shortcut, that KeeWeb (desktop app) reads the current window title (i.e. something like "Chrome - Github login"), and does an Auto-type for this specific entry "Github" automatically (without having to open KeeWeb and choose the right entry manually)?

What's the shortcut for this? Is it documented?

It is available in KeePass as "Global Auto Type" with CTRL+ALT+A by default IIRC.

**Comment by antelle** [comment]
Hi! Auto-type by title is supported and should be fuzzy matched, the shortcut can be found (and customized in Settings > Shortcuts.

**Comment by josephernest** [comment]
The name:

    Shift+Alt+T : Auto-type selected entry

is a bit misleading because we think it will auto-type the entry currently selected in the KeeWeb interface.

When I tried it, it did instead what I was looking for: `Auto-type based on current window title`.

You might want to rename this item to avoid the confusion?

Or was it a reason to call it `Auto-type selected entry`?

Something else: this option (auto type based on window title) is very hard to find in the documentation. Maybe it would be interesting to add a note about this in README or FAQ since many people want either a broswer extension or browser auto-type.

Congrats for your tool by the way!

**Comment by antelle** [comment]
Wow, it shouldn't be the same text indeed, that's very confusing. Changed it, thanks!

**Comment by josephernest** [comment]
Thank you! Do you want me to do a pull-request? In which file is the text
for this?

**Comment by antelle** [comment]
I’ve already changed it, it will be updated in the next release
