### ISSUE TITLE
Some .kdbx files not detected by KeeWeb

### ISSUE THREAD

**Issue by augustindo** [keeweb/keeweb#1369]
Some of my .kdbx files are not detected by keeweb:

![image](https://user-images.githubusercontent.com/20402274/70375165-08b29280-18fb-11ea-9804-772f386a0277.png)

As you can see only the second database keeweb icon displays: if I click on the second icon, it automatically opens the database under https://domain.tld/nextcloud/index.php/apps/keeweb/?open=%2F[obfuscated-folder]%2F[obfuscated]rax.kdbx

But if I click on the first icon `[obfuscated]xt.kdbx`, Nextcloud just propose me to download the file.

If I reuse the above url, changing manually the file name from `[obfuscated]rax.kdbx` to match `[obfuscated]xt.kdbx` (https://domain.tld/nextcloud/index.php/apps/keeweb/?open=%2F[obfuscated-folder]%2F[obfuscated]xt.kdbx), it works and KeeWeb can open my database.

I hope it's clear, I can give more details if needed.

Thanks for this very good tool :+1: 

Note: these database had been created by KeePassX and/or KeePass2 under GNU/Linux Debian Stretch.

**Comment by antelle** [comment]
Hi! I can't help with this, it's nextcloud-keeweb project: https://github.com/jhass/nextcloud-keeweb
