### ISSUE TITLE
URL not detected by Auto-Type feature

### ISSUE THREAD

**Issue by malins** [keeweb/keeweb#1375]
**Describe the bug**
Auto-type doesn't find entry by URL. I think Keeweb is not able to extract URL from browser. Issues with both Google Chrome and Firefox.

For example, I have exactly one entry with URL 'https://www.amazon.de' in my database, and on autotype (Shift-Alt-T) KeeWeb asks me to select the correct entry, displaying *all* entries from the database.

My environment:
* KeeWeb 1.12.3
* Google Chrome 79 / Firefox 71
* xdotool 1:3.20160805.1-3
* Kubuntu 18.04

**Logs**
```
[DEBUG] 2019-12-14T10:52:58.836Z [auto-type] Hide window
[DEBUG] 2019-12-14T10:52:58.950Z [auto-type] Getting window info
[INFO ] 2019-12-14T10:52:58.975Z [launcher] spawn xdotool: 0, 25ms
Amazon Anmelden - Google Chrome
60817409
[DEBUG] 2019-12-14T10:52:58.976Z [auto-type] Window info 60817409 Amazon Anmelden - Google Chrome null
```
Thank you,
Manuel

**Comment by antelle** [comment]
Hi! Right, we can't get the browser url in Linux, so matching is possible only by title. If your entry title matches the browser title, it should work.
