### ISSUE TITLE
[Question] Screen orientation

### ISSUE THREAD

**Issue by KaKi87** [keeweb/keeweb#1378]
I use KeeWeb on Android as a Chrome PWA and it seems that in this configuration, the app is forcing automated screen rotation while I didn't enabled it in my Android settings.

Before creating an issue, I searched the web for documentation about how a such behavior can be implemented, so I looked at the `manifest.json` file, but its values hasn't been modified since it was created, while I've only been recently experiencing this.

Any ideas why ?

Please note that I'm not facing such behavior in other PWAs.

Thanks

**Comment by antelle** [comment]
Interesting, it looks like a bug, we have `"orientation": "any"` in manifest.json, but it means that any orientation is supported, not that it should be enabled if it's disabled in system settings.

**Comment by antelle** [comment]
I guess, if we remove it, nothing will break, but it will probably fix it.

**Comment by KaKi87** [comment]
Hello, is there a release date for v1.13 ? Thanks

**Comment by antelle** [comment]
Not yet, there are some issues that need to be fixed/implemented for the new release

**Comment by KaKi87** [comment]
Why waiting for v1.13 for this such inoffensive issue then ?
