### ISSUE TITLE
haveibeenpwned plugin won't work anymore as the API requires a fee 

### ISSUE THREAD

**Issue by leolivier** [keeweb/keeweb#1379]
Hi
I'm the maintainer of the haveibeenpwned plugin and after having abandoned it for several months, I've been trying to fix it these last few days.
I found out after several hours of research that the API that checks accounts is no longer free and now costs $3.5 per month and per million call.
I don't think any user will want to pay this for the service so I don't have any solution for this unless you have an idea on how to finance it @antelle. 

see https://haveibeenpwned.com/API/Key for the information on the new API management...

**Comment by antelle** [comment]
Hi! I see that they don't provide any free options, so I guess, it means we can't use their API anymore.

**Comment by leolivier** [comment]
Actually, it keeps working for passwords only (but not for account name)...
So I will change the plugin description to explain the current status and do a PR on this...
