### ISSUE TITLE
Error After Upgrading to Catalina: Incorrect Header Check

### ISSUE THREAD

**Issue by thatcort** [keeweb/keeweb#1381]
After upgrading to MacOS Catalina, I can no longer open my database file. The error returned is `incorrect header check`. Using `Version 1.12.3 (9b07bbd5)`

**Logs**

```
[INFO ] 2020-01-02T03:18:59.518Z [plugin:keewebhttp] Loading plugin with resources js (local)
[DEBUG] 2020-01-02T03:18:59.521Z [storage-plugin-files] Load keewebhttp_plugin.js
[DEBUG] 2020-01-02T03:18:59.523Z [storage-plugin-files] Loaded keewebhttp_plugin.js 2ms
[DEBUG] 2020-01-02T03:18:59.523Z [plugin:keewebhttp] Resource data loaded js 3ms
[DEBUG] 2020-01-02T03:18:59.525Z [plugin:keewebhttp] Resource signature validated js 1ms
[INFO ] 2020-01-02T03:18:59.525Z [plugin:keewebhttp] Installing plugin resources
[DEBUG] 2020-01-02T03:18:59.527Z [plugin:keewebhttp] Plugin script installed 2ms
[DEBUG] 2020-01-02T03:18:59.528Z [plugin:keewebhttp] Plugin settings loaded 0ms
[INFO ] 2020-01-02T03:18:59.528Z [plugin:keewebhttp] Install complete 8ms
[INFO ] 2020-01-02T03:18:59.528Z [plugin-mgr] Loaded 1 plugins 14ms
[INFO ] 2020-01-02T03:18:59.641Z [app] Started in 1497ms ¯\_(ツ)_/¯
[INFO ] 2020-01-02T03:18:59.642Z [updater] Next update check will happen in 85026s
[DEBUG] 2020-01-02T03:19:00.048Z [keewebhttp] Server running at http://127.0.0.1:19455/
[INFO ] 2020-01-02T03:19:27.636Z [updater] Checking for update...
[INFO ] 2020-01-02T03:19:27.636Z [transport] GET https://app.keeweb.info/manifest.appcache
[INFO ] 2020-01-02T03:19:27.651Z [transport] Request to https://app.keeweb.info/manifest.appcache without proxy
[INFO ] 2020-01-02T03:19:27.829Z [transport] Response from https://app.keeweb.info/manifest.appcache: 200
[INFO ] 2020-01-02T03:19:27.831Z [updater] Update check: # 2019-11-06:v1.12.3
[INFO ] 2020-01-02T03:19:27.835Z [updater] Next update check will happen in 86400s
[INFO ] 2020-01-02T03:20:30.729Z [open:passwords] File open request
[INFO ] 2020-01-02T03:20:30.730Z [open:passwords] Open file from storage file
[INFO ] 2020-01-02T03:20:30.730Z [open:passwords] Stat file
[DEBUG] 2020-01-02T03:20:30.730Z [storage-file] Stat /Users/tc/Dropbox/keepass/passwords.kdbx
[DEBUG] 2020-01-02T03:20:30.731Z [storage-file] Stat done /Users/tc/Dropbox/keepass/passwords.kdbx 1ms
[INFO ] 2020-01-02T03:20:30.731Z [open:passwords] Open file from storage (1577308554000, local 1576379226233)
[INFO ] 2020-01-02T03:20:30.731Z [open:passwords] Load from storage
[DEBUG] 2020-01-02T03:20:30.731Z [storage-file] Load /Users/tc/Dropbox/keepass/passwords.kdbx
[DEBUG] 2020-01-02T03:20:30.736Z [storage-file] Loaded /Users/tc/Dropbox/keepass/passwords.kdbx 1577308554000 5ms
[INFO ] 2020-01-02T03:20:30.736Z [open:passwords] Open file from content loaded from storage
[ERROR] 2020-01-02T03:20:31.122Z [file] Error opening file undefined undefined incorrect header check
[ERROR] 2020-01-02T03:20:31.123Z [open-view] Error opening file incorrect header check
```

**Comment by antelle** [comment]
Hi! What happens if you delete the file from keeweb and add it again?

**Comment by thatcort** [comment]
I just tried deleting and re-adding the file and still get the same error. (Clicked the `x` next to the filename, clicked the password box and selected the file again)

**Comment by antelle** [comment]
Looks like your file is corrupted, is it possible to open it with other apps, like KeePass, KeePassX, etc...?

**Comment by thatcort** [comment]
Yes, I can open the file in other apps. I currently have the file open in MacPass and Android apps

**Comment by antelle** [comment]
Weird, looks like it happens during unpacking gzip, but I don't know what exactly of course. How did you save the file last time before it happened?

**Comment by thatcort** [comment]
It was either saved by KeeWeb or by an Android app. It was working fine before the Catalina upgrade, but that might be a red herring.

**Comment by antelle** [comment]
Strange. If you manage to repeat it on a new file, please post the result here. Until that, I guess, it won't be possible to fix it.

**Comment by thatcort** [comment]
I fixed the problem: I opened the file in MacPass, emptied the db recycle bin and saved it. Then it opened fine in KeeWeb again.

**Comment by antelle** [comment]
Interesting, looks like some app (maybe also keeweb) writes it in a strange way and it's not possible to open the file.

**Comment by ueberchild** [comment]
I've lost my db after exporting from self-hosted keeweb site.  
It says `incorrect header check`, other apps refuse to open as well.  
Previous exports were fine, db size as usual.  
Always manually check files for corruption after exporting...

**Comment by antelle** [comment]
@ueberchild it would be nice to understand how to repeat this. Dis you do anything special with this file before?

**Comment by ueberchild** [comment]
@antelle I used newest Keeweb HTML with no changes or plugins.  
File size is almost 25K, there were huge markdown cyrillic notes, no attachments, wasn't synced.  
I barely changed the file between successful and unsuccessful export.  
Tried MacPass in KVM: `The database header hash is wrong. Data integrity might be broken! (1019)`  
[head hexdump](http://sprunge.us/7int1E)

**Comment by antelle** [comment]
Interesting, now if you change the file from a successful export, does it get into this state again?

**Comment by ueberchild** [comment]
@antelle I have no backups of that safe.  
Not crucial, info is saved in other formats.  
Seems I used `user.js` based on arkenfox.  
Cannot reproduce incorrectness, though.

**Comment by antelle** [comment]
This js just changes privacy settings afaik, it shouldn't interfere with webcrypto. I would be happy to get a reproduction case, then it will be possible to investigate.
