### ISSUE TITLE
Feature request: add Touch ID support to unlock KeeWeb on macOS

### ISSUE THREAD

**Issue by matsev** [keeweb/keeweb#1383]
**Is your feature request related to a problem? Please describe.**

I would like to be able to use [Touch ID](https://support.apple.com/en-me/HT207054) to unlock KeeWeb on macOS

**Describe the solution you'd like**

*Touch ID user interaction flow*
1. The user starts KeeWeb and enters the password to unlock the KeePass file (either stored locally, on Dropbox, etc).
2. If the password is correct, KeeWeb is unlocked (in the same way as today). The password is stored in memory and a timer is started.
3. After some time, KeeWeb is locked due to inactivity (by the existing auto lock feature).
4. If the user needs access to KeeWeb again, he/she can unlock KeeWeb either by entering the password or using Touch ID (unless the timer has expired).
5. Unlocking KeeWeb (or some other KeeWeb interaction that requires KeeWeb to be unlocked) restarts the timer.
6. If the timer has expired, the password is erased from memory and the user must enter the password to unlock KeeWeb again.

*Configuration settings*
 
* The user should presented with the option to enable Touch ID in addition to the existing auto lock feature. 
* The timeout of how long the Touch ID is enabled should be configurable.
* The settings can be hidden (or disabled) for users that have installed KeeWeb on platforms that do not support Touch ID by using the [systemPreferences.canPromptTouchID()](https://electronjs.org/docs/api/system-preferences#systempreferencescanprompttouchid-macos) function.   
* The configuration setting of whether or not Touch ID is enabled should preferably not be enabled if the KeeWeb is locked.  

**Additional context**

Many applications on macOS use Touch ID to authenticate users, including Apple Pay and Keychain / Safari integration for providing username and password for web pages. 

The Touch ID apis ([systemPreferences.canPromptTouchID()](https://electronjs.org/docs/api/system-preferences#systempreferencescanprompttouchid-macos) and [systemPreferences.promptTouchID(reason)](https://electronjs.org/docs/api/system-preferences#systempreferencesprompttouchidreason-macos)) were added to the Electron as part of the [v6.0.0](https://github.com/electron/electron/releases/tag/v6.0.0) release.

**Comment by antelle** [comment]
Hi! What you describe is a sort of convenience measure, which is different from #679 where saving credentials to touch id is suggested. In this version we don't need to save password and all APIs are available, so it's possible to implement it like this.

**Comment by matsev** [comment]
@antelle Yes, this suggestion is for convenience. 

Initially, I thought of a similar implementation as described in the issue that you linked (e.g. storing the master password somewhere that can use Touch ID for authentication when reading and writing data). However, looking at the current Electron API, this is not feasible since as [you noted](https://github.com/keeweb/keeweb/issues/679#issuecomment-531514692) the Electron Touch ID API does not provide and API for reading and writing data (I have not looked at the native macOS APIs, but I would not be surprised if there are functions there). 

After thinking about the matter some more, it occurred to me that it is possible to restate the problem from "how can we unlock the KeePass database using Touch ID" to "how can we unlock the KeeWeb app using Touch ID" then the current Electron Touch ID API will suffice. IMHO it has also the benefit of _not_ storing the master password.

**Comment by antelle** [comment]
This will be implemented as one of options in #679, in v1.7

**Comment by antelle** [comment]
Touch ID is implemented, the settings will look like this:

<img width="468" alt="touch-id-settings" src="https://user-images.githubusercontent.com/633557/106799713-dbc55100-665f-11eb-9718-ed80f25ca58d.png">

It will be released in v1.17, in March or April.

**Comment by dmytro-ivonin** [comment]
> Touch ID is implemented, the settings will look like this:
> 
> <img alt="touch-id-settings" width="468" src="https://user-images.githubusercontent.com/633557/106799713-dbc55100-665f-11eb-9718-ed80f25ca58d.png">
> 
> <img alt="touch-id-options" width="462" src="https://user-images.githubusercontent.com/633557/106799870-0d3e1c80-6660-11eb-9bc2-1250f9b65707.png">
> 
> For now it will be opt-in, as in, you will need to go to settings and enable it manually to use it. When it becomes more stable, there will be some enrollment tooltips.
> 
> It will be released in v1.17, in March or April.

Hi,

I Just enabled Touch ID feature (Always use Touch ID instead of master password) and nothing changed, app still requires to enter Master Password both after minimize app and after close.

Environment: app version 1.18.7 (dfc6201), Macbook Air M1, macOS Monterey 12.2

What I messed to do?
Thank you in advance.

P.S. Thanks for the great application!
