### ISSUE TITLE
Auto This, Auto That 

### ISSUE THREAD

**Issue by JohnrC123** [keeweb/keeweb#1384]
Is it possible to 'auto create' a Login Entry after logging in (Chrome/Windows 10)?

Sorry if I'm 'fused, but when in KeeWeb, can have it send me to a website login page and autofill the Username and Password as stored?

Cheers.

KeeWeb v1.12.3 (9b07bbd5, 2019-11-06)
Environment: electron v7.0.0
User-Agent: Mozilla/5.0 (Windows NT 10.0) AppleWebKit/537.36 (KHTML, like Gecko) KeeWeb/1.12.3 Chrome/78.0.3905.1 Electron/7.0.0 Safari/537.36

**Comment by antelle** [comment]
Hi! It would be indeed nice, but won't be possible without a proper browser extension, and we don't have it unfortunately.
