### ISSUE TITLE
Loading database from network location causes error

### ISSUE THREAD

**Issue by abremora** [keeweb/keeweb#1385]
**Describe the bug**
When I try to open a database file from a network location on window 10, I get the following error:
`There was an error opening file`
`Error: EISDIR: illegal operation on a directory, watch '\\webdav.mc.gmx.net@SSL\DavWWWRoot\Safe'`

**To Reproduce**
1. Start App
2. Load file from network location
3. Error message appears
4. Click OK
5. App seems to work as expected

**Expected behavior**
No error occurs

**Screenshots**
/

**Environment**
KeeWeb v1.12.3 (9b07bbd5, 2019-11-06)
Environment: electron v7.0.0
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) KeeWeb/1.12.3 Chrome/78.0.3905.1 Electron/7.0.0 Safari/537.36

**Kdbx File**
This was a small test database

**Logs**
[INFO ] 2020-01-03T19:41:17.657Z [open:Database] File open request
[INFO ] 2020-01-03T19:41:17.657Z [open:Database] Open file from storage file
[INFO ] 2020-01-03T19:41:17.657Z [open:Database] Stat file
[DEBUG] 2020-01-03T19:41:17.657Z [storage-file] Stat \\webdav.mc.gmx.net@SSL\DavWWWRoot\Safe\Database.kdbx
[DEBUG] 2020-01-03T19:41:17.807Z [storage-file] Stat done \\webdav.mc.gmx.net@SSL\DavWWWRoot\Safe\Database.kdbx 150ms
[INFO ] 2020-01-03T19:41:17.807Z [open:Database] Open file from storage (1578079462000, local 1578079462000)
[INFO ] 2020-01-03T19:41:17.808Z [open:Database] Load from storage
[DEBUG] 2020-01-03T19:41:17.808Z [storage-file] Load \\webdav.mc.gmx.net@SSL\DavWWWRoot\Safe\Database.kdbx
[DEBUG] 2020-01-03T19:41:17.938Z [storage-file] Loaded \\webdav.mc.gmx.net@SSL\DavWWWRoot\Safe\Database.kdbx 1578079462000 130ms
[INFO ] 2020-01-03T19:41:17.938Z [open:Database] Open file from content loaded from storage
[INFO ] 2020-01-03T19:41:18.966Z [file] Opened file Database: 1025ms, 24086272 rounds, 3 kB
[DEBUG] 2020-01-03T19:41:18.966Z [app] Add last open file 18d376b4-a335-1903-8259-6e2b63118e06 Database file \\webdav.mc.gmx.net@SSL\DavWWWRoot\Safe\Database.kdbx 1578079462000
[DEBUG] 2020-01-03T19:41:19.027Z [storage-file] Watch dir \\webdav.mc.gmx.net@SSL\DavWWWRoot\Safe
[ERROR] 2020-01-03T19:41:19.261Z [file] Error opening file EISDIR EISDIR: illegal operation on a directory, watch '\\webdav.mc.gmx.net@SSL\DavWWWRoot\Safe' Error: EISDIR: illegal operation on a directory, watch '\\webdav.mc.gmx.net@SSL\DavWWWRoot\Safe'
[ERROR] 2020-01-03T19:41:19.262Z [open-view] Error opening file Error: EISDIR: illegal operation on a directory, watch '\\webdav.mc.gmx.net@SSL\DavWWWRoot\Safe'

**Comment by antelle** [comment]
Hi! While this is not fixed, you can open the file using webdav, this should work.

**Comment by abremora** [comment]
Just to be clear: I just have to ignore the error message, then I can keep using the app.
The same error also occurs when I use a mapped network drive:

[INFO ] 2020-01-03T19:56:24.182Z [open:Database] File open request
[INFO ] 2020-01-03T19:56:24.183Z [open:Database] Open file from supplied content
[INFO ] 2020-01-03T19:56:25.219Z [file] Opened file Database: 1034ms, 24086272 rounds, 3 kB
[DEBUG] 2020-01-03T19:56:25.219Z [app] Add last open file a7086694-17e7-18a7-4971-0043fa824a03 Database file S:\Safe\Database.kdbx undefined
[DEBUG] 2020-01-03T19:56:25.270Z [storage-file] Watch dir S:\Safe
[ERROR] 2020-01-03T19:56:25.273Z [file] Error opening file EISDIR EISDIR: illegal operation on a directory, watch 'S:\Safe' Error: EISDIR: illegal operation on a directory, watch 'S:\Safe'
[ERROR] 2020-01-03T19:56:25.274Z [open-view] Error opening file Error: EISDIR: illegal operation on a directory, watch 'S:\Safe'
