### ISSUE TITLE
Line-wrap in comment field gets disabled by special chars

### ISSUE THREAD

**Issue by Eniki** [keeweb/keeweb#1386]
As soon as you add a single- or double-quote character (didn't try others) to a comment, deliberate line wraps (added with SHIFT+ENTER) get ignored when in default view (I call it read-mode. i.e. comment field not selected, faint grey frame). 
As soon as you click into the field ("edit mode" with blue frame), the line-wraps display correctly.
See attached screenshots
1 no quote, read-mode, line-wrap OK:
![1 no quote, read-mode, line-wrap OK](https://user-images.githubusercontent.com/40298233/71768534-1b7ab000-2f17-11ea-82a6-00773b0a13b6.jpg)
2 with quote, read-mode, line-wrap not OK:
![2 with quote, read-mode, line-wrap not OK](https://user-images.githubusercontent.com/40298233/71768535-1f0e3700-2f17-11ea-8701-b30921242de0.jpg)
3 with quote, edit mode, line wrap OK:
![3 with quote, edit mode, line wrap OK](https://user-images.githubusercontent.com/40298233/71768536-233a5480-2f17-11ea-9ae2-a7398738391c.jpg)

**Expected behavior**
I'd expect formatting to be independent of characters used - and of course maintain (soft) line breaks in no matter what display mode.

**Environment**
KeeWeb v1.12.3 (9b07bbd5, 2019-11-06)
Environment: electron v6.0.10
User-Agent: Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) KeeWeb/1.11.6 Chrome/76.0.3809.146 Electron/6.0.10 Safari/537.36

Note: This feels like a regression to me, possibly introduced by the bugfix for a case I reported previously [https://github.com/keeweb/keeweb/issues/945] ?

**Comment by antelle** [comment]
Hi! It's because of Markdown, if you disable it in settings, it should behave as you expect.

**Comment by Eniki** [comment]
Interesting. I thought I hadn't seen the comment (where I detected this) garbled before, so I suspected it was a behavior only introduced lately.
Thanks anyway for the lightning-fast "solution" :-)
