### ISSUE TITLE
All entries shown at root instead of in their respective groups for kdbx3 database

### ISSUE THREAD

**Issue by cfogrady** [keeweb/keeweb#1392]
**Describe the bug**
I have a kdbx3 database file. When I load in KeeWeb, it shows all the entries when I'm at the root level instead of just the entries that don't have any group. If I drill down into a group I see all the entries of that group and it's sub groups instead of just the entries for the group. Tree structure isn't really being honored.

Example if I have a file:
Root
 - Entry1
 - Entry2
 - Group1
 -- Group1Entry1
 -- SubGroup1
 ---SubGroup1Entry1

If looking at root I will see Entry1, Entry2, Group1Entry1, and SubGroup1Entry1. I would expect to just see Entry1 and Entry2 at the root level. Similarly if I'm looking at Group1 I will see Group1Entry1 and SubGroup1Entry1 instead of just Group1Entry1

**Environment**
KeeWeb v1.12.3 (9b07bbd5, 2019-11-06)
Environment: web
User-Agent: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.117 Safari/537.36

**Kdbx File**
Does it happen on Demo or New database?  Yes
https://drive.google.com/open?id=129QqOFTh6Y-LrFo_rUcIx18LPg2MZWxV
Password: test

**Comment by antelle** [comment]
Hi! There’s a checkbox in settings called “show entries from all subgroups”, looks like it’s what you’re looking for.

**Comment by cfogrady** [comment]
Ah! Thanks for clearing that up! I might suggest that the above setting be off by default, but perhaps there are individuals who prefer it the way it currently is.
