### ISSUE TITLE
Advance search will cause a TypeError

### ISSUE THREAD

**Issue by andyf1111** [keeweb/keeweb#1395]
**Describe the bug**
`TypeError: t.toLowerCase is not a function` will be encountered while advance searching with secure or password filed checked.

**Environment**
KeeWeb v1.12.3 (9b07bbd5, 2019-11-06)
Environment: electron v7.0.0
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) KeeWeb/1.12.3 Chrome/78.0.3905.1 Electron/7.0.0 Safari/537.36

**Screenshots (use demo database)**
- **Without** secure **and** password filed checked: correct result
![image](https://user-images.githubusercontent.com/19814597/72664945-7d223a80-3a3e-11ea-9ddd-965f2ac9c6af.png)
- **With** secure **or** password filed checked: nothing searched
![image](https://user-images.githubusercontent.com/19814597/72665064-05eda600-3a40-11ea-90cc-f539c4a83f15.png)

**Little question**
Could anyone tell me what `Exact Option` mean in advance search? Search result seems no different whether check it or not.

**Comment by antelle** [comment]
If you have two words in your search, with exact search they will be searched as is, for example, "apple com" will find only records that have "apple com" inside. With the exact search turned off, records with "com apple" will also match.

**Comment by andyf1111** [comment]
@antelle I got it, thank you very much!
