### ISSUE TITLE
Hyperlinks in notes not work well

### ISSUE THREAD

**Issue by andyf1111** [keeweb/keeweb#1396]
![image](https://user-images.githubusercontent.com/19814597/72667339-d9448900-3a55-11ea-88af-c768c24711fd.png)

**Describe the bug**
Email address and normal URL shown as hyperlink in notes field directly like above pic, there are two problems I encountered about them:

1. KeeWeb crashed when I clicked an email address in notes at first time, but I can't reproduce it again and no logs saved, just ignore it for now is fine I guess.
2. The page hyperlink links to will be opened in KeeWeb window If I left click `www.apple.com` and no way to back, or another KeeWeb window if I click it with `Ctrl` pressed.
![image](https://user-images.githubusercontent.com/19814597/72667501-57555f80-3a57-11ea-892d-c421bc69ced8.png)

**Environment**
KeeWeb v1.12.3 (9b07bbd5, 2019-11-06)
Environment: electron v7.0.0
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) KeeWeb/1.12.3 Chrome/78.0.3905.1 Electron/7.0.0 Safari/537.36

**Suggestions about notes and new customize field**
1. Open links in default browser like the behavior in website field.
2. String in notes field shown as hyperlink only when it's enclosed by `<>` 
3. Cursor focus on field name instead of field value while add new customize field, it's hard to type in since cannot switch text box with `Tab`
![image](https://user-images.githubusercontent.com/19814597/72667637-f169d780-3a58-11ea-8e98-ce796ee37a8a.png)

**Comment by uberkelium** [comment]
Hi, I second this. Is there a way to disable hyperlink rendering in the notes field, or go backwards? Every time I click on the link, it renders inside KeeWeb instead of redirecting to my browser, with no way to go back.
