### ISSUE TITLE
use Segoe UI on Windows 7+

### ISSUE THREAD

**Issue by mlcdf** [keeweb/keeweb#1397]
Hello 

**Is your feature request related to a problem? Please describe.**
If I may, I think that currently Keeweb UI feels a little bit odd on Window.

**Describe the solution you'd like**
I think, simply making sure that the recommended font for Windows apps is used on Windows would make it look a bit more "native".

**Describe alternatives you've considered**
More profound CSS changes, but that would also impact the other platforms and it would also require a lot more work. So it doesn't seem like a good alternative.

**Additional context**
The recommended font for Windows apps is `Segoe UI` :
- https://docs.microsoft.com/en-us/windows/win32/uxguide/vis-fonts
- https://docs.microsoft.com/en-us/windows/uwp/design/style/typography

This font is also/therefore the one used by most websites using system fonts ([such as GitHub](https://markdotto.com/2018/02/07/github-system-fonts/)).

Here's a before/after test.

**Before**
![image](https://user-images.githubusercontent.com/9364931/72689978-cbefd300-3b17-11ea-9f11-2ea400771c31.png)
**After**
![image](https://user-images.githubusercontent.com/9364931/72689972-b8dd0300-3b17-11ea-9116-7d66428c4287.png)

If you're ok with this, I can work on the PR.

**Comment by antelle** [comment]
Hi! We should of course use it if it's a recommended font in the guidelines.
I'll add it to the fontstack in the next release, or you can submit a PR if you wish.
