### ISSUE TITLE
Create a new kdbx file with keeweb

### ISSUE THREAD

**Issue by torstendoerschel** [keeweb/keeweb#1399]
Hi,
I really like the keeweb, found it as the app version for nextcloud.

I am just confused that I cannot create a kdbx file with keeweb. Do I simply not see it, or is it not implemented( e.g. I always need another program like keepass to initally create a file).

Thanks for the cool and great work!

**Comment by antelle** [comment]
Hi! I guess, you need to ask in nextcloud-keeweb: https://github.com/jhass/nextcloud-keeweb/issues
In keeweb itself it's possible to create a file and save it.
