### ISSUE TITLE
keeweb failing to auto save

### ISSUE THREAD

**Issue by gann17** [keeweb/keeweb#1403]
Keeweb is failing to auto save when I go to close it after I add a new entry. Any ideas why or how to fix it? Hosting on my desktop.
It says "sync error: Error: EPERM, operation not permitted, open filepath"

i haven't changed any settings for it, so I dont know hwy its suddenly doing this

**Comment by antelle** [comment]
Hi! Do you have the logs to check which file it is?

**Comment by gann17** [comment]
I have no idea how to obtain the logs. I could probably generate them again, if they were a temporary thing, but I'm not a programmer of any kind, just trying to use a safe way to store passwords.

**Comment by antelle** [comment]
They can be found in Settings / General

**Comment by antelle** [comment]
They are temporary and not saved anywhere, you’ll need to do it again to capture logs

**Comment by gann17** [comment]
I just copied and pasted the logs from one error line to the next, and bolded the error lines to make it easier to see. It doesn't give a specific file thats causing the problem, as I have everything under one kdbx file, so its the only one listed.

**[ERROR] 2020-02-02T06:35:05.652Z [storage-file] Error writing local file C:\Program Files\keeweb kdbx\alterna.kdbx Error: EPERM: operation not permitted, open 'C:\Program Files\keeweb kdbx\alterna.kdbx'**
[INFO ] 2020-02-02T06:35:05.652Z [sync:alterna] Error saving data to storage
[INFO ] 2020-02-02T06:35:05.652Z [sync:alterna] Sync finished Error: EPERM: operation not permitted, open 'C:\Program Files\keeweb kdbx\alterna.kdbx'
[INFO ] 2020-02-02T06:58:35.875Z [updater] Checking for update...
[INFO ] 2020-02-02T06:58:35.876Z [transport] GET https://app.keeweb.info/manifest.appcache
[INFO ] 2020-02-02T06:58:35.905Z [transport] Request to https://app.keeweb.info/manifest.appcache without proxy
[INFO ] 2020-02-02T06:58:36.351Z [transport] Response from https://app.keeweb.info/manifest.appcache: 200
[INFO ] 2020-02-02T06:58:36.353Z [updater] Update check: # 2019-11-06:v1.12.3
[INFO ] 2020-02-02T06:58:36.354Z [updater] Next update check will happen in 86400s
[INFO ] 2020-02-02T06:58:36.354Z [updater] You are using the latest version
[INFO ] 2020-02-02T07:05:05.629Z [sync:alterna] Sync started file C:\Program Files\keeweb kdbx\alterna.kdbx {}
[INFO ] 2020-02-02T07:05:05.631Z [sync:alterna] Stat file
[DEBUG] 2020-02-02T07:05:05.631Z [storage-file] Stat C:\Program Files\keeweb kdbx\alterna.kdbx
[DEBUG] 2020-02-02T07:05:05.635Z [storage-file] Stat done C:\Program Files\keeweb kdbx\alterna.kdbx 4ms
[INFO ] 2020-02-02T07:05:05.635Z [sync:alterna] Stat found same version, modified, saving
[INFO ] 2020-02-02T07:05:05.635Z [sync:alterna] Getting file data for saving
[INFO ] 2020-02-02T07:05:05.666Z [sync:alterna] Saving to file storage
[INFO ] 2020-02-02T07:05:05.666Z [sync:alterna] Save data to storage
[DEBUG] 2020-02-02T07:05:05.666Z [storage-file] Save C:\Program Files\keeweb kdbx\alterna.kdbx 1577602787918
**[ERROR] 2020-02-02T07:05:05.666Z [storage-file] Error writing local file C:\Program Files\keeweb kdbx\alterna.kdbx Error: EPERM: operation not permitted, open 'C:\Program Files\keeweb kdbx\alterna.kdbx'**
[INFO ] 2020-02-02T07:05:05.666Z [sync:alterna] Error saving data to storage
[INFO ] 2020-02-02T07:05:05.666Z [sync:alterna] Sync finished Error: EPERM: operation not permitted, open 'C:\Program Files\keeweb kdbx\alterna.kdbx'

**Comment by antelle** [comment]
I guess it happens because you’re trying to save kdbx files to “program files”, it’s not where data should be

**Comment by gann17** [comment]
so, a couple of things. That kdbx file has been there for over a month with no problem until now. Also, where should the data be then?

**Comment by antelle** [comment]
Most likely you updated Windows or restored original permissions, which doesn’t allow writing to program files. It’s supposed to go in “my documents” or any other location of your choice, “program files” is supposed to contain application executables.

**Comment by gann17** [comment]
well, it appears as though moving the kdbx file to the documents folder has solved the issue. Thank you very much for the help!
