### ISSUE TITLE
How to install which out admin rights ? 

### ISSUE THREAD

**Issue by F3000** [keeweb/keeweb#1404]

**Comment by antelle** [comment]
I didn't get the question, sorry.

**Comment by F3000** [comment]
I can’t install the windows version on my coperate owned  laptop . 

I don’t have local admin rights

**Comment by antelle** [comment]
There’s a portable version in downloads: https://github.com/keeweb/keeweb/releases/download/v1.12.3/KeeWeb-1.12.3.win.x64.zip
It doesn’t require installation, so you can use it without admin rights.

**Comment by F3000** [comment]
Thanks . One question: Which browser extension can zu recommend ?

**Comment by antelle** [comment]
I can't recommend any of them, we don't have any own extensions and personally I'm using just auto-type instead of them.

**Comment by F3000** [comment]
How does auto type work when Keeweb runs outside a browser ?

**Comment by antelle** [comment]
You can either switch to KeeWeb, find a record, and trigger auto-type, or use a system-wide shortcut (depends on your OS, can be found in Settings / Shortcuts).

**Comment by F3000** [comment]
Ok thanks . I will try the global hotkey tomorrow

**Comment by F3000** [comment]
Does this version also auto update ?

**Comment by antelle** [comment]
It should, but better to try if it works.
