### ISSUE TITLE
How to delete keeweb "profile"

### ISSUE THREAD

**Issue by lucgiffon** [keeweb/keeweb#1406]
Hello, I have a simple problem: I have created multiple keeweb "profiles" and I can't find how to delete useless ones.

What I call a "profile" is an account protected by a password. I hope this is clear.

**Comment by antelle** [comment]
Hi! We don't have any accounts on KeeWeb. The only thing you can create is a kdbx file that can be stored in different places. If it's stored inside your browser, you can do one of the following:
- delete them from the start screen using a small `x` button
- clear cookies and website storage
