### ISSUE TITLE
Update Wiki  - Running Keeweb on Citrix Servers

### ISSUE THREAD

**Issue by ojehle** [keeweb/keeweb#1407]
To Use Keeweb on Citrix Servers, you have to deactivate the Citrix hooks.

https://support.citrix.com/article/CTX224067

Open Registry Editor.
Go to HKEY_LOCAL_MACHINE\SOFTWARE\Citrix\CtxHook.
Change/Create the value of registry key ExcludedImageNames and add keeweb.exe

**Comment by antelle** [comment]
Do you have an idea on which page it should go?

**Comment by ojehle** [comment]
perhaps supported systems desktop?

**Comment by antelle** [comment]
I’m not sure. For desktop, users are not supposed to read manuals and probably nobody finds it. I guess they will most likely go to issues or Google and find this ticket, so let’s leave it here.
