### ISSUE TITLE
Keeweb on Kali 

### ISSUE THREAD

**Issue by killmasta93** [keeweb/keeweb#1410]
**Describe the bug**
Hi,
I install the keeweb on Kali 2019 but when i try to open it i get this error on the logs

`kernel: [   87.432917] traps: KeeWeb[1371] trap int3 ip:55b924576cf4 sp:7ffd46dcb5d0 error:0 in KeeWeb[55b922675000+53ac000]`

**Comment by antelle** [comment]
Hi! Are there any other logs? I'm afraid I won't be able to understand what's going on without them.

**Comment by killmasta93** [comment]
Thank you for the reply, i checked in /var/log/syslog 
the only thing that appears when i open it is there another place i can check?

Thank you

**Comment by killmasta93** [comment]
issue was that keeweb does not run as root user if i run as another user it works
