### ISSUE TITLE
Desktop keeweb cannot open google drive file

### ISSUE THREAD

**Issue by merce78** [keeweb/keeweb#1412]
I've been using desktop keeweb with a file stored in google drive. However since the last update I cannot open it anymore. It looks like keeweb is not secure enough according to google. Please, find attached the screen shot. 
My desktop keeweb version is 1.12.3 and my OS is ubuntu 18.04 - 64b

![Selección_054](https://user-images.githubusercontent.com/6906090/75392728-ef632600-58ec-11ea-890e-6119aba27ed5.png)

KeeWeb v1.12.3 (9b07bbd5, 2019-11-06)
Environment: electron v7.0.0
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) KeeWeb/1.12.3 Chrome/78.0.3905.1 Electron/7.0.0 Safari/537.36

**Comment by antelle** [comment]
Hi! It's #1359
