### ISSUE TITLE
Auto-Type KeeWebHelper.exe huge delay in Vivaldi browser

### ISSUE THREAD

**Issue by lesu1** [keeweb/keeweb#1413]
Hi,

Trying to use Auto-Complete feature on my home PC with Vivaldi browser and it freezes for about a minute.
I have another machine with the same Keeweb version and Fresh Vivaldi browser with synchronization enabled (only two Extension instaled: KeePassHttp-Connector, URL in Title on both machines)

1. Clean install "Vivaldi" browser, Add KeePassHttp-Connector extension and add a database.
2. Open any side with login. (Reddit as example, or even keepass test form)
3. Hit Auto-type hotkey.

**Expected behavior**
No lag.

**Screenshots**
N/A

**Environment**
Machine with issue:
KeeWeb v1.12.3 (9b07bbd5, 2019-11-06)
Environment: electron v7.0.0
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) KeeWeb/1.12.3 Chrome/78.0.3905.1 Electron/7.0.0 Safari/537.36

Machine where tested and all good (everything the same as above):
KeeWeb v1.12.3 (9b07bbd5, 2019-11-06)
Environment: electron v7.0.0
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) KeeWeb/1.12.3 Chrome/78.0.3905.1 Electron/7.0.0 Safari/537.36

**Kdbx File**
Own/Personal (same database synchronized via OneDrive in between machines)

**Logs**
Logs from machine with issue (KeeWebHelper.exe: 0, 65310ms):
index.html:1 2020-02-27T10:54:36.396Z [keewebhttp] getLogins(https://www.reddit.com): 1
index.html:1 2020-02-27T10:54:37.029Z [keewebhttp] getLogins(https://www.reddit.com): 1
index.html:1 2020-02-27T10:54:37.335Z [auto-type] Auto type event null
index.html:1 2020-02-27T10:54:37.341Z [auto-type] Getting window info
index.html:1 2020-02-27T10:54:37.343Z [auto-type] Using auto-type helper C:\Program Files\KeeWeb\resources\helper\win32\KeeWebHelper.exe
index.html:1 2020-02-27T10:55:42.653Z [launcher] spawn C:\Program Files\KeeWeb\resources\helper\win32\KeeWebHelper.exe: 0, 65310ms
329456
reddit: the front page of the internet - https://www.reddit.com/ - Vivaldi
index.html:1 2020-02-27T10:55:42.654Z [auto-type] Window info 329456 reddit: the front page of the internet - https://www.reddit.com/ - Vivaldi https://www.reddit.com/
index.html:1 2020-02-27T10:55:42.666Z [auto-type] Hide window
index.html:1 2020-02-27T10:55:42.782Z [auto-type] Start {CLEARFIELD}{USERNAME}{TAB}{DELAY 1000}{CLEARFIELD}{PASSWORD}{ENTER}
index.html:1 2020-02-27T10:55:42.782Z [auto-type] Parsed [op:CLEARFIELD,op:USERNAME,op:TAB,op:DELAY,op:CLEARFIELD,op:PASSWORD,op:ENTER]
index.html:1 2020-02-27T10:55:42.783Z [auto-type] Resolved [[key:end,+key:home,key:bs],*****,key:tab,cmd:wait,[key:end,+key:home,key:bs],[*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*],key:enter]
index.html:1 2020-02-27T10:55:43.875Z [launcher] spawn C:\Program Files\KeeWeb\resources\helper\win32\KeeWebHelper.exe: 0, 1091ms
index.html:1 2020-02-27T10:55:43.876Z [auto-type] Complete 1094ms

P.S:
I've tried to completely remove "Vivaldi" and "KeeWeb" and reinstall them back. - No luck
I've added "KeeWeb" folder into Windows Defender under the Exclude folders for scanning. KeeWebHelper.exe added into Exclude as well. - No luck

Google Chrome and Mozilla works fine on the same machine, maybe you know where to dig, what to check.

Thanks!

**Comment by lesu1** [comment]
Updated to v1.17. Mozilla works fine, but the same issue for Vivaldi. 
Should I do something? I mean change setting or clean cache or I don't know.

Here are the logs:

2021-03-09T07:08:06.891Z [sync:allgood] Sync finished no error
index.html:1 2021-03-09T07:08:24.109Z [keewebhttp] getLogins(http://192.168.1.11:81): 1
index.html:1 2021-03-09T07:08:25.073Z [keewebhttp] getLogins(http://192.168.1.11:81): 1
index.html:1 2021-03-09T07:08:26.291Z [auto-type] Auto type event null
index.html:1 2021-03-09T07:08:26.291Z [auto-type] Getting window info
index.html:1 2021-03-09T07:08:26.292Z [auto-type] Using auto-type helper C:\Users\gg\AppData\Roaming\KeeWeb\helper\win32\KeeWebHelper.exe
index.html:1 2021-03-09T07:08:26.466Z [launcher] spawn C:\Users\gg\AppData\Roaming\KeeWeb\helper\win32\KeeWebHelper.exe: 0, 173ms
67120
Login – Nginx Proxy Manager http://192.168.1.11:81/login — Mozilla Firefox
index.html:1 2021-03-09T07:08:26.466Z [auto-type] Window info 67120 Login – Nginx Proxy Manager http://192.168.1.11:81/login — Mozilla Firefox null
index.html:1 2021-03-09T07:08:32.852Z [auto-type] Entry selected Object
index.html:1 2021-03-09T07:08:32.885Z [auto-type] Hide window
index.html:1 2021-03-09T07:08:32.992Z [auto-type] Getting window info
index.html:1 2021-03-09T07:08:33.281Z [launcher] spawn C:\Users\gg\AppData\Roaming\KeeWeb\helper\win32\KeeWebHelper.exe: 0, 289ms
67120
Login – Nginx Proxy Manager http://192.168.1.11:81/login — Mozilla Firefox
index.html:1 2021-03-09T07:08:33.281Z [auto-type] Window info 67120 Login – Nginx Proxy Manager http://192.168.1.11:81/login — Mozilla Firefox null
index.html:1 2021-03-09T07:08:33.282Z [auto-type] Active window matches
index.html:1 2021-03-09T07:08:33.282Z [auto-type] Start {CLEARFIELD}{USERNAME}{TAB}{DELAY 1000}{CLEARFIELD}{PASSWORD}{ENTER}
index.html:1 2021-03-09T07:08:33.282Z [auto-type] Parsed [op:CLEARFIELD,op:USERNAME,op:TAB,op:DELAY,op:CLEARFIELD,op:PASSWORD,op:ENTER]
index.html:1 2021-03-09T07:08:33.283Z [auto-type] Resolved [[key:end,+key:home,key:bs],*******************,key:tab,cmd:wait,[key:end,+key:home,key:bs],[*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*],key:enter]
index.html:1 2021-03-09T07:08:34.410Z [launcher] spawn C:\Users\gg\AppData\Roaming\KeeWeb\helper\win32\KeeWebHelper.exe: 0, 1127ms
index.html:1 2021-03-09T07:08:34.410Z [auto-type] Complete 1128ms
index.html:1 2021-03-09T07:08:47.488Z [keewebhttp] getLogins(http://192.168.1.11:81): 1
index.html:1 2021-03-09T07:08:48.421Z [keewebhttp] getLogins(http://192.168.1.11:81): 1
index.html:1 2021-03-09T07:09:03.999Z [auto-type] Auto type event null
index.html:1 2021-03-09T07:09:03.999Z [auto-type] Getting window info
index.html:1 2021-03-09T07:10:09.934Z [launcher] spawn C:\Users\gg\AppData\Roaming\KeeWeb\helper\win32\KeeWebHelper.exe: 0, 65934ms
132678

**Comment by antelle** [comment]
Wauw, is it 1.17? It shouldn’t use KeeWebHelper. What is the version displayed in settings / about?

**Comment by lesu1** [comment]
Ah, my bad. I thought it was updated from About > General after the restart as mentioned on the blue button, but it does not.
Used to re-install manually and it's working now. 

Checked few more sites (Reddit as well from my initial post). All good. We can close the issue.

Thanks a lot antelle!!

**Comment by antelle** [comment]
Cool, glad to hear it’s fixed!
