### ISSUE TITLE
Self-cleaning timer not working

### ISSUE THREAD

**Issue by kirebyte** [keeweb/keeweb#1415]
I've configured KeeWeb so clipboard becomes erased after 5 or 15 seconds, it hasn't worked on either cases, the password is still ready to paste.

KeeWeb v1.12.3 (9b07bbd5, 2019-11-06)
Environment: electron v7.0.0
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) KeeWeb/1.12.3 Chrome/78.0.3905.1 Electron/7.0.0 Safari/537.36

**Comment by antelle** [comment]
Duplicates #1372
