### ISSUE TITLE
This browser or app may not be secure

### ISSUE THREAD

**Issue by AlexWayfer** [keeweb/keeweb#1417]
**Describe the bug**

I can't synchronize my KeePass file in Google Drive.

**To Reproduce**

1. Try to open Google Drive file
2. Try to Sign in

**Expected behavior**

Successful sign in.

**Screenshots**

![image](https://user-images.githubusercontent.com/6510020/75799652-6b47ed00-5d89-11ea-8bcd-ae8e0f4f27da.png)

**Environment**

```
KeeWeb v1.12.3 (9b07bbd5, 2019-11-20)
Environment: electron v8.0.2
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) KeeWeb/1.12.3 Chrome/80.0.3987.86 Electron/8.0.2 Safari/537.36
```

**Kdbx File**

Personal.

**Logs**

I don't think we're needing for them.

**Comment by DAHopkins** [comment]
I also have this issue on Ubuntu 18.04.4.  Works in Web App, but not Desktop.

**Environment**
KeeWeb v1.12.3 (9b07bbd5, 2019-11-06)
Environment: electron v7.0.0
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) KeeWeb/1.12.3 Chrome/78.0.3905.1 Electron/7.0.0 Safari/537.36

**Comment by antelle** [comment]
duplicates #1359

**Comment by AlexWayfer** [comment]
Oh, sorry, I didn't find it. I hope at least this issue will help others.
