### ISSUE TITLE
Search a entrie

### ISSUE THREAD

**Issue by lollita** [keeweb/keeweb#1419]
To search un UserName in the entries by UserName programmatically do I have to load all groups, subgroups, entries and then iterate it to find?
Or do it have a shorter way.

**Comment by antelle** [comment]
Hi! You can do it here:
<img width="244" alt="Screen Shot 2020-03-05 at 19 28 17 1" src="https://user-images.githubusercontent.com/633557/76013008-89dbee80-5f17-11ea-8189-318baffbe8f5.png">

**Comment by lollita** [comment]
I asked programmatically not via gui.

**Comment by antelle** [comment]
Oh you mean using [kdbxweb](https://github.com/keeweb/kdbxweb)? You can iterate through entries and compare `fields.UserName` with yours.

**Comment by antelle** [comment]
You can also do: https://github.com/keeweb/kdbxweb#recursive-traverse on the root group

**Comment by lollita** [comment]
kdbxweb.js
So I need to iterate.
