### ISSUE TITLE
Error: EXIST: file already exists, mkdir '.../temp/...'

### ISSUE THREAD

**Issue by elbowz** [keeweb/keeweb#1423]
**Describe the bug**
Appear this error on start:

![Screenshot_20200311_152105](https://user-images.githubusercontent.com/1451484/76427141-3c92cd80-63ac-11ea-994c-d4701f1237c3.png)

I have tried to clean the `/temp` folder but the error appear again on the second start of app.

FYI: I use OneDrive to save the password file

Sorry, this is my second bug in one week.

**To Reproduce**
1. Just start the application

**Logs**
I cannot take the logs because the apps is not visible.
I have to `pkill electron` and restart it...and it works.

**Comment by antelle** [comment]
https://github.com/keeweb/keeweb/issues/1418
it's reported that electron 8.1 fixes it

**Comment by elbowz** [comment]
I cannot check now...but I have Arch Linux (rolling release) like who opened the linked issues...so for sure the incriminated one.

Thanks as usually for you time and hard works.
