### ISSUE TITLE
ServiceWorker is caching too much.

### ISSUE THREAD

**Issue by HolgerHees** [keeweb/keeweb#1426]
In a nextcloud app the keeweb tool is embedded as an inline tool which works very well but since the service worker is installed we have some caching issues. The main problem is that the service worker is caching everything and not only the necessary files. I'm not 100% sure how a generic patch could look but I fixed the problem by only caching one big file and bypass the rest.

All the details about the bug and the fix can be found here.

https://github.com/jhass/nextcloud-keeweb/issues/137

I would be happy if we can discuss how a generic solution could look.

**Comment by antelle** [comment]
Hi! I think, since the page is changed in nextcloud, and this is not something supported in keeweb, the service worker should be patched there as well. Now applying the patch will disable caching for all requests with `?config`, which sounds a bit strange.
