### ISSUE TITLE
Nextcloud config save

### ISSUE THREAD

**Issue by OMNiTRiX98** [keeweb/keeweb#1430]
!please describe your issue here!

KeeWeb v1.12.3 (9b07bbd5, 2020-02-14)
Environment: web
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.132 Safari/537.36

When I open a kdbx File on my Nextcloud in KeeWeb and edit the settings, the configuration is lost as soon as I log off from the Nextcloud. Is there any way to save the settings or set the kdbx File as default for my account?

**Comment by antelle** [comment]
Hi! This should be in nextcloud-keeweb project.
