### ISSUE TITLE
Beta Version doesn't activate when "Minimize the app instead of close" is active.

### ISSUE THREAD

**Issue by NeilCross** [keeweb/keeweb#1431]
**Describe the bug**
Beta Version doesn't activate when "Minimize the app instead of close" is checked.

**To Reproduce**
1. In settings under General -> Function -> "Minimize the app instead of close" is checked.
2. "Try beta version until restart" is clicked
3. The app will minimize to the taskbar, and not start the beta version.

**Expected behavior**
The app will start the beta version.
When "Minimize the app instead of close" is not checked, this feature behaves as expected.

**Environment**
KeeWeb v1.12.3 (9b07bbd5, 2019-11-06)
Environment: electron v6.0.10
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) KeeWeb/1.11.7 Chrome/76.0.3809.146 Electron/6.0.10 Safari/537.36

**Logs**
No relevant logs are generated during this operation.

**Comment by NeilCross** [comment]
P.S. i love keeweb, thanks for all the effort.

**Comment by antelle** [comment]
Hi! That’s how it behaves yes. Won’t be fixed for now. I’d like to remind that beta is supposed to be used for feature testing, not permanently.

**Comment by NeilCross** [comment]
FYI, I appreciate this is functionality to activate the beta functionality, however this issue occurs within the release build. 
Secondarily, keep in mind that depute your intentions,, this feature isn't only used for feature testing, I need it for the program to work correctly. For me and others, beta is required due to an unreleased google drive sync fix that's only available there,
