### ISSUE TITLE
Suggestion for a new 2FA TOTP web-based application

### ISSUE THREAD

**Issue by wltprgm** [keeweb/keeweb#1434]
**Is your feature request related to a problem? Please describe.**
Without needing a phone (maybe computer), a web-based **SECURE** TOTP application is desired, like keeweb for keepass

**Describe the solution you'd like**
I am trying to find a web-based open source, browser client-side javascript only 2FA TOTP application, like Keeweb solution for Keepass

**Describe alternatives you've considered**
I only found two via Google Search https://www.google.com/search?q=totp+app+online,
1. https://gauth.apps.gbraad.nl/, open source I think, https://github.com/gbraad/gauth/
2. https://totp.app/ may not be open source

**Additional context**
@antelle has invested quite some time in secure web-based keeweb and cryptography, I want to propose this idea to him

**Comment by antelle** [comment]
Hi! It's not quite clear, maybe we already have it. We already have TOTP support: create an entry, click more..., select "One-time passwords", scan a QR code → otp codes will be generated. Is that what you asked?

**Comment by wltprgm** [comment]
Wow, I didn't know you already included this 2FA feature in keeweb, that's amazing

Thanks for this seriously
