### ISSUE TITLE
Support YubiKey in challenge-response mode

### ISSUE THREAD

**Issue by antelle** [keeweb/keeweb#1435]
**Is your feature request related to a problem? Please describe.**
YubiKey supports [challenge-response](https://www.yubico.com/products/services-software/personalization-tools/challenge-response/) operations in form of HMAC-SHA1. This implementation has already gained some support in other well-known KeePass forks:

- KeePass supports it via [KeeChallenge](https://github.com/brush701/keechallenge) plugin
- KeePassXC has it [implemented natively](https://github.com/keepassxreboot/keepassxc/issues/1734)
- StrongBox has recently [integrated it](https://github.com/strongbox-password-safe/Strongbox/issues/95) in both the app itself and in AutoFill suggestions
- KeePassium also [already has it](https://github.com/keepassium/KeePassium/issues/25)
- MacPass doesn't support it yet, but there's a [ticket](https://github.com/MacPass/MacPass/issues/90)

**Describe the solution you'd like**
- desktop apps should use any of YubiKey API, such as native API or `ykman`, whichever is more feasible
- webapp can support it in two ways:
  - as a one-time mode with a static key, which can be for example scanned as a QR code from the desktop app
  - using a workaround with storing the key on the device, which has to be carefully assessed in terms of security, to make sure the key doesn't end up in iOS backups

**Describe alternatives you've considered**
There are some alternatives described on [this page](https://keepass.info/help/kb/yubikey.html):
- Static Password Mode:
  - that's actually not 2FA and I doubt if it gives any additional security, since the password is typed using a keyboard driver
  - it's of course possible to use it in KeeWeb just as is, as well, but that's not what we're looking for here
- One-Time Password Mode:
  - using the YubiKey in this mode is quite terrible in terms of UX, which is even worse on mobile devices
  - it will break sync and increase the risk of getting locked out, if sync fails
- WebAuthn / U2F:
  - WebAuthn is neither about encryption, nor hashing. It does exactly what it says, which is authentication with a relying party. In our case we don't want to store secrets on a central server and destroy the decentralized nature of KeePass, even if it would be super easy to implement
- Resident keys that were recently [added](https://duo.com/labs/tech-notes/resident-keys-and-the-future-of-webauthn-fido2) to WebAuthn:
  - it looks very promising: completely eliminates phishing, is available for web and native API's, however:
  - there's no support in Safari, which means we won't be able to use it on mobile devices yet
  - unfortunately I don't see other clients willing to support it, which is understandable because the web topic is interesting to us, first of all, however we can write a plugin of course
  - this topic can be addressed later as an additional mode of YubiKey integration

**Additional context**
Previous issues in KeeWeb about YubiKey support:
- #517 
- #410

**Comment by jivarson** [comment]
This would be so neat, currently using keepass2android on Android with yubikey in challenge-response mode (which requires the app ykdroid for the nfc-driver) and keepassxc for desktops for secrets I'm paranoid about

**Comment by antelle** [comment]
Just a note, it will work only on desktop without hacks; web/mobile version will be probably limited and not very convenient.

**Comment by ph00lt0** [comment]
@jivarson what makes you paranoid?

**Comment by jivarson** [comment]
@antelle that makes sense, there are at least one app for android with support for challenge-response :-) @ph00lt0 strong word, point being that for important passwords its good knowing that the second 2nd factor cant be copied after setup like a keyfile can

**Comment by antelle** [comment]
@jivarson good to know about Android, I'll add it to the manual that I'll write about YubiKey support. On iOS, most of KeePass-compatible apps already have support built-in.
> the second 2nd factor cant be copied

Unfortunately it can, to some extent. YubiKey integration in KeePass-like apps is in Challenge-Response mode, which means that it's not a true 2FA, so if you have:
- an old kdbx file
- its password
- access to YubiKey, no matter from what app or computer

You will be able to generate and save the response for this files. A more advanced technique can be sniffing USB, and again, as ChResp is not a one-time code, you can save and use it to open old files. However good news is that new files saved again will have a different challenge.

**Comment by ph00lt0** [comment]
Well it certainly is a second factor. But not a time based second factor if that is what you mean.

**Comment by antelle** [comment]
Indeed, my reply was to the copying part.

**Comment by jivarson** [comment]
Thanks for putting the record straight

**Comment by Nu11u5** [comment]
> Just a note, it will work only on desktop without hacks; web/mobile version will be probably limited and not very convenient.

Has using the WebUSB API been investigated to allow use in browser?

https://github.com/SantiagoTorres/yubikey-webusb

**Comment by antelle** [comment]
YubiKeys are not exposed via WebUSB because of security reasons:
https://www.yubico.com/blog/webusb-and-responsible-disclosure/
https://www.yubico.com/support/security-advisories/ysa-2018-02/
https://pwnaccelerator.github.io/2018/webusb-yubico-disclosure.html

**Comment by thefonseca** [comment]
Hello @antelle!
How do you intend to implement this?

I was thinking of doing something similar using [Safari App Extensions](https://developer.apple.com/safari/extensions/) on macOS. It would break the 100% web design of the project but we would have the benefit of reusing what was already implemented in other native apps. The app extension could be dropped in the future once browsers offer better native support.

In my case, I am more interested in smartphone-base keys (using the secure enclave) over BLE, so I am considering tweaking [Krypton](https://krypt.co) to add challenge-response support.

**Comment by antelle** [comment]
@thefonseca for now I think the web version will not support this feature at all.
Installing an app extension doesn't make a lot of sense, since it will be easier to download a desktop app instead.
If there's a smartphone-based key supporting challenge-response, it would be awesome, but I'm not sure if they exist, I'll try to find something.

**Comment by gynet** [comment]
Both Keepass2android and keepassium(ios) are supporting the challenge response mode through NFC, so it would be cool if the implementation of Keeweb is compatible with them

**Comment by antelle** [comment]
It will be compatible, but only the desktop version.

**Comment by thefonseca** [comment]
> @thefonseca for now I think the web version will not support this feature at all.
> Installing an app extension doesn't make a lot of sense, since it will be easier to download a desktop app instead.

Thanks @antelle, this makes sense. "a desktop app" you mentioned includes the KeeWeb electron version too? (I'd like to stick to KeeWeb for now).

**Comment by antelle** [comment]
Yes, KeeWeb desktop of course.

**Comment by Nu11u5** [comment]
My use-case is on Chromebook.  Sadly I don't think there is any solution for challenge-response mode at the moment (Android apps and Crostini/Linux can't directly access USB devices, either).

**Comment by antelle** [comment]
The feature is ready to test on desktop, if anyone would like to give it a try, please let me know.

**Comment by gynet** [comment]
@antelle I have a yubikey and can do some testing.

**Comment by antelle** [comment]
@gynet which operating system are you using?

**Comment by gynet** [comment]
@antelle I have win10 & Macos

**Comment by antelle** [comment]
Good, here's a version for [macOS](https://share.antelle.net/KeeWeb.app.zip) and [Windows x64](https://share.antelle.net/KeeWeb-win32-x64.zip). The macOS version will most likely work, I haven't tested it on Windows yet. Please don't forget to backup your file!  
Three's also a wiki page about using YubiKey with KeeWeb: https://github.com/keeweb/keeweb/wiki/YubiKey

**Comment by gynet** [comment]
Cool, will try it later today @antelle

**Comment by antelle** [comment]
It also has config encryption, after which the previous version won't be able to read configs, so better to try it as a portable installation: https://github.com/keeweb/keeweb/wiki/Configuration#portable

**Comment by gynet** [comment]
Here are some results so far: 
**MacOS:**
1. keeweb-portable.json does not work for me, it's still use the old profile. 
2. Plugged my 'Yubikey NEO;, the Yubikey icon shows up on the panel, but after I clicking on it, it shows "No Yubikey found", also the 'refresh the list' does not show anything either. 
I tried 'ykman list',  it shows my Yubikey. 

**Windows 10**
1. For the first time, keeweb-portable.json seems not got loaded, and it was still using the old profile I previous used, but it generated a new profile folder after second launch. 
2. change response worked as expected with a test db. 

**Some Feedback:**
1. the dependency tree of 'ykman' is pretty heavy, and I spent quite long time to get it and its dependencies installed on my Mac and Windows. As I remember,  the keepassxc does not depend on ykman, it there any alternative way for Keeweb interact with Yubikey without ykman? It's also would impact UX and the portability if it has dependency on ykman.

**Comment by antelle** [comment]
Thanks! 
1. keeweb-portable.json: could you please paste the absolute path to the file and KeeWeb? Sometimes it may be not loaded, depending on where it is.
2. Is KeeWeb is added to "Input Monitoring" in system security & privacy settings? YubiKey is implemented as a keyboard, so we need this permission to interact with it.
3. `ykman` is required only for one-time codes (OATH), OTP should work without `ykman` installed. When did you see the ykman prompt? The big YubiKey button on the start screen is OATH, the small one below the password field should work without it.

**Comment by antelle** [comment]
I've added a warning about "Input Monitoring" to the app, now it will show the explanation when there's a yubikey but it can't be used.

**Comment by gynet** [comment]
@antelle Do you mean the Challenge-response does not require ykman?
 I did not see any prompt, I just installed it anyway as I read wiki too fast :) 

**MacOS updates** 
- After I add the app into "Input Monitoring",  all the Yubikey slots are showing up now. 
- The portable json with abs path does not work either, also tried with granting full disk access. The path I am using is a folder under  user desktop 

**Test Ran**
- Test case 1: [x] Passed | T create a DB by Keeweb with Yubikey + keyfile.    

- Test case 2: [x] Passed  | Test case 2: create a DB by Keeweb with Yubikey + keyfile, decrypt it by KeepassXC.      

 **Issues** 
- Sometimes, the Keeweb does not show up the Yukikey slot list anymore after I opened another app using Yubikey, e.g., KeepassXC. 
- One more feedback: Current, the slot list does not the slot functionality, it would be better like  show the slot functionality as the KeepassXC<img width="632" alt="Screen Shot 2020-06-01 at 10 52 31 PM" src="https://user-images.githubusercontent.com/2174522/83484812-a1653d80-a45a-11ea-84e3-3113fb284dae.png">

**Comment by gynet** [comment]
I also tested with Keepass2droid. The database created by Keeweb failed on decryption by Keepass2droid + NFC. It shows "Invalid composite key". However, the database created by KeepassXC does not have this issue.

**Comment by antelle** [comment]
> Do you mean the Challenge-response does not require ykman?
Exactly, my first intention was to implement everything with ykman, so it was said in the wiki, however I quickly realized that there are too many limitations. Updated the wiki, thanks!

> After I adding the app into "Input Monitoring", all the Yubikey slots are showing up now.
👍 

> show the slot functionality as the KeepassXC
Makes sense, KeePassXC actually does a test challenge for that, I'll add it as well.

> The database created by Keeweb failed on decryption by Keepass2droid + NFC.
Can it be opened with KeePassXC? Could you please upload your database if it's a test one?

**Comment by gynet** [comment]
Here is the testing db file created by KeeWeb. It can be decrypted by both Keeweb and KeepassXC using MacOS, but it can not be decrypted by KeePassXC. 
[ybk_test_createdByKeeweb.kdbx.zip](https://github.com/keeweb/keeweb/files/4715279/ybk_test_createdByKeeweb.kdbx.zip)

**Comment by antelle** [comment]
> The portable json with abs path does not work either

What I meant, is please tell me the absolute path to KeeWeb and the json config

**Comment by gynet** [comment]
- App path: /Users/gynet/Desktop
- The json content is below 
```
{
    "userDataDir": "/Users/gynet/Desktop/mydir"
}
```

**Comment by antelle** [comment]
And where's the json config located?

**Comment by gynet** [comment]
/Users/gynet/Desktop/keeweb-portable.json

**Comment by antelle** [comment]
Cool, I'll check why it doesn't work.
Thanks for the file! I'll look into this file a bit later today. Could you please tell me:
- the password
- result of 
```
ykman otp calculate 2 d8a30cffaae97a52134550a3c852ef2a6b19203b96fea4154de5ededd3861f3c2020202020202020202020202020202020202020202020202020202020202020
```
(replace "2" with "1" if you're using slot 1)

**Comment by gynet** [comment]
```
2c2bb148ddae51f12f80d874771d500f37c6f3af
```

**Comment by antelle** [comment]
...and the password please
Another question, if you re-save the file, can it be opened with other apps?

**Comment by gynet** [comment]
@antelle  password is 'test'. Re-saved the file with Keeweb, it was able to reopen by KeepassXC

**Comment by gynet** [comment]
Also, another UX feedback, I saw iTerm do send notification about requesting security permission, would it be better the Keeweb also initialize the same permission request

**Comment by antelle** [comment]
What about Keepass2droid where it could not be decrypted before?  
I'll check how it's done, not sure how to request those.

**Comment by gynet** [comment]
Tried use Keepass2droid to open the db modified by Keeweb, it still shows "Invalid composite key"

**Comment by antelle** [comment]
what happens if you re-save the file in KeePassXC, can it be opened there?

**Comment by gynet** [comment]
just tried, re-save the file in KeePassXC, the Keepass2droid still could not open it

**Comment by antelle** [comment]
About the portable config: I just tried running KeeWeb from Desktop with these paths:
~/Desktop/KeeWeb.app
~/Desktop/keeweb-portable.json
```
{ "userDataDir": "kw-data" }
```
It displayed a question about accessing files in the desktop folder and worked well.

**Comment by antelle** [comment]
I [implemented](https://github.com/antelle/node-yubikey-chalresp/commit/fda05cb74ecb9fa4a006f9c1922ea35a2c8d6770) testing YubiKey slots, however I discovered that:
- it adds a significant delay (about .8 .. 1.5 s)
- sometimes it times out at all
- actually it behaves in the same way in KeePassXC if you refresh it several times

So, if we compare having a stable API vs displaying "touch (non)required" and hiding non-working slots, I would say, let's show less information but with better quality.

**Comment by antelle** [comment]
Just checked, if KeeWeb is launched for the first time, it shows this question when trying to access YubiKeys:
<img width="903" alt="Screen Shot 2020-06-02 at 15 11 57" src="https://user-images.githubusercontent.com/633557/83524149-7672fc00-a4e3-11ea-9ce8-fbaebfe30653.png">

**Comment by antelle** [comment]
I looked into keepass2android, looks like their implementation is compatible with KeePass/KeeChallenge, especially [this part](https://github.com/PhilippC/keepass2android/blob/ee6b7c4fe0257af35eed0eed09c83721db72e94c/src/keepass2android/KeeChallenge.cs#L50), as well as [the docs](https://github.com/PhilippC/keepass2android/blob/master/docs/How-to-use-Keepass2Android-with-YubiKey-NEO.md) If so, you won't be able to use files written by KeeWeb or KeePassXC, as it's also mentioned in the [KeePassXC FAQ](https://keepassxc.org/docs/#faq-yubikey-incompatible). I'll add it to the wiki page as well.
However Strongbox and KeePassium for iOS are compatible.

**Comment by gynet** [comment]
Hi @antelle 

Looks like keepass2android do have both KeePass/KeeChallenge and KeePassXC 's, I saw both options are aviable on the android app. 

Also it is mentioned by KeePassXC 's FAQ
```
Does KeePassXC work on mobile phones? If not, which app would you recommend?
    We don't have our own mobile app, but you can have the same functionality on both Android and iOS!

        For Android, we recommend KeePass2Android (it's open-sourced on GitHub)
        And for iOS, we suggest Strongbox (also open-sourced on GitHub)
```

**Comment by gynet** [comment]
It seems like it support both KeePass/KeeChallenge and KeePassXC's challenge reponse. I've tried the database created by KeepassXC, it works fine on keepass2android. I also saw the Android app do have two optios,  "challenge reponse" and " challenge reponse for KeepassXC" 

This was an [closed issue ](https://github.com/PhilippC/keepass2android/issues/4) on keepass2android's github

**Comment by gynet** [comment]
Also FYI
```
"Does KeePassXC work on mobile phones? If not, which app would you recommend?
    We don't have our own mobile app, but you can have the same functionality on both Android and iOS!

        For Android, we recommend KeePass2Android (it's open-sourced on GitHub)
        And for iOS, we suggest Strongbox (also open-sourced on GitHub)
"
```

**Comment by gynet** [comment]
Here is also the [issue ](https://github.com/keepassxreboot/keepassxc/issues/1060)regarding Keepass2android's implementation to be compatiable with KeepassXC .

**Comment by antelle** [comment]
Interesting, and still, both KeePassXC and KeeWeb write the db in a non-compatible format. I wonder what's the difference there. I guess, I need to run keepass2android to understand what it is 🤔

**Comment by antelle** [comment]
Status update: I didn't manage to install the necessary tooling on macOS, and looks like the project [can't be built](https://github.com/PhilippC/keepass2android/blob/master/src/build.readme.md) on mac, or at least there's no official guide how to do that, so tomorrow I'll try to read the code to understand why this can happen, however I won't be able to test it.

**Comment by antelle** [comment]
Meanwhile, what happens if you change the file format to KDBX4 in KeeWeb, does it become compatible?

**Comment by gynet** [comment]
@antelle 
- I uninstalled the existing Keeweb and cleaned all the settings in the Security & Privacy, then "Keystroke receiving" pop up window will up. Is that expected? 
- The portable json is still not working for me, and there is no questions or either any pop-up windows show for request any permission  
- After changing to  kdbx4 + argon2, the database created by Keeweb is working for all the three pass managers now

**Comment by gynet** [comment]
@antelle for the keepass2droid issue I think it's by design, just found [their release note](https://github.com/PhilippC/keepass2android/releases/tag/1.06f-nonet) mentioned that kdbx4 is required, but it would be better to document on the "compatibility table" as well.

**Comment by antelle** [comment]
> Keystroke receiving

Yes, YubiKey registers itself as a keyboard and this permission is required to interact with it. Not the best solution, I would say, but that's how it is now.

> portable json

Could you please try [this build](https://github.com/keeweb/keeweb-ci-sandbox/releases/tag/v1.14.3)? I've added more logs there, if you launch it from terminal, it should print what's going on around portable configs.

> kdbx4

Awesome so it was KDBX3 compatibility, then it's solved, thank you! I've changed the default file format of files created by KeeWeb to KDBX4 and added a note to the wiki page.

**Comment by gynet** [comment]
I tried this build, but i dont see anyting related 

```
```

<img width="940" alt="image" src="https://user-images.githubusercontent.com/2174522/83729506-921df580-a5fc-11ea-9bd8-edf006b2181f.png">

**Comment by antelle** [comment]
The logs schold me in Terminal, you need to start it not with open, but as an executable: KeeWeb.app/Contents/MacOS/KeeWeb

**Comment by gynet** [comment]
Hi Antelle,
If I launch from a terminal, things look good now. It starts use the new profile I defined in the json. However, when it requests permission using the popup window, it shows the app is iterm.app instead of the Keeweb, I think that my related to the issue we saw. 

I guess for some reason,  the MacOS will still treat the new version of Keeweb.app as the previous one installed?  I previously had an issue with upgrading Keeweb, and the auto-type did not work, and I had to manually clean up the existing "Security & Privacy"  settings regarding KeeWeb in macOS, then it would work 

```
Is portable: true
Portable config path: /Users/gynet/Desktop/keeweb-portable.json
Portable config path exists
Portable user data dir: /Users/gynet/Desktop/mydir
```

**Comment by gynet** [comment]
I did reset, and everything works now 
```
tccutil reset All

```

**Comment by antelle** [comment]
I think it checks by bundle id, and I really hope that also certificate, but maybe not, I’ll check. So you don’t need to update it for the new version.
It will show terminal in this case yes, otherwise it would be easy to bypass.
Ok cool that it works now!

**Comment by antelle** [comment]
Uploaded a new build here: https://github.com/keeweb/keeweb-ci-sandbox
This is probably what will be there in the release, at least for me everything seems to be working.
