### ISSUE TITLE
AutoType window breaks main window size / maximized state

### ISSUE THREAD

**Issue by AnFlare** [keeweb/keeweb#1440]
**Describe the bug**
AutoType window size doesn't respect global window size and "maximized" state.
Also breaks it.

**To Reproduce**
1. Maximize Keeweb or change its size to your liking
2. go to any website with multiple password entries
3. press Alt+Shift+T (global AutoType)
4. displayed AutoType window doesn't respect your main window size / "maximized" state
5. more than this, closing AutoType window changes your main window size!

**Expected behavior**
AutoType window size/maximizing should be the same as main window.
Closing AutoType window shouldn't change main window size/maximizing.

**Environment**
KeeWeb v1.12.3 (9b07bbd5, 2019-11-06)
Environment: electron v6.0.2
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) KeeWeb/1.9.2 Chrome/76.0.3809.110 Electron/6.0.2 Safari/537.36

**Comment by antelle** [comment]
Just checked this, it seems to work well on macos and linux, but broken on windows.

**Comment by AnFlare** [comment]
Seems AutoType window may be of current size. It's pretty usable and convenient. (Or may be adjustable on its own?)
The key is that it shouldn't break main window sizing.

**Comment by antelle** [comment]
Indeed, it should preserve the size, but it's broken on Windows.
