### ISSUE TITLE
Support OneDrive/Sharepoint Business for desktop app

### ISSUE THREAD

**Issue by isojakub** [keeweb/keeweb#1442]
I'd like to be able to reach my O365 business account with the desktop app. I'm able to do it using the web version, but web version does not support autotype nor auto-filling with keepasshttp-connector. It is a showstopper currently for me.

I think it can be achieved with providing similar configuration options as with the config.json file that the web version has.

**Comment by antelle** [comment]
Hi! What's the error you get in the desktop app? Unfortunately I don't have a business account to try it.

**Comment by isojakub** [comment]
You can see it below.
It's the same error that one would get if the onedriveclientid would not be configured in JSON for the web app. Correct me if I'm wrong, but there's no way to configure that for the desktop app, right?

```
Request Id: 38242fa1-3a8c-4ac9-9486-8e8a21173a00
Correlation Id: d1889bbf-849f-4581-acbb-b788640b9a08
Timestamp: 2020-04-01T14:20:32Z
Message: AADSTS700016: Application with identifier '000000004818ED3A' was not found in the directory '8d50d93a-e1f7-4252-a91f-2e0dbb2d1f1d'. This can happen if the application has not been installed by the administrator of the tenant or consented to by any user in the tenant. You may have sent your authentication request to the wrong tenant.


```

**Comment by antelle** [comment]
Hm, that's the same app id as the one used in the web version, do you have an idea why it happens on desktop?

**Comment by isojakub** [comment]
I'm confusing you, I'm sorry. app.keeweb.info also produces the same error. When I was talking about webapp, I was talking about a local version of it, that I installed myself on nginx, with the altered JSON config, that reflects the tenant if of my business account.

**Comment by antelle** [comment]
What happens if you change the config in the desktop version?

**Comment by isojakub** [comment]
How do I enforce the config in the desktop version? https://github.com/keeweb/keeweb/wiki/Dropbox-and-GDrive << This works for self-hosted web version

**Comment by antelle** [comment]
You can find the config in <app_data>/KeeWeb/app-settings.json

**Comment by isojakub** [comment]
Thank you :)

śr., 1 kwi 2020 o 17:05 Dimitri Witkowski <notifications@github.com>
napisał(a):
