### ISSUE TITLE
WebDav acces is broken

### ISSUE THREAD

**Issue by LiloBzH** [keeweb/keeweb#1446]
**Describe the bug**
Access file with Webdav is broken

Error in apache log : 

[04/Apr/2020:17:49:41 +0200] "HEAD /remote.php/dav/files/my_account/pass/Keepass.kdbx HTTP/1.1" 503 1747 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) KeeWeb/1.13.0 Chrome/80.0.3987.158 Electron/8.2.0 Safari/537.36"

In Keepass => Error : HTTP 503 Status (same error of course ^^ )

Bug since last version Desktop apps v1.13.0

I rolled back for now

**Comment by antelle** [comment]
Hi! Was it working in the previous release of KeeWeb?
Could you please compare what's the difference between requests in this and previous version?

**Comment by LiloBzH** [comment]
ok so since this update, webdav is broken.
I test with 1.12.3 and it's broken too ...

I dont interstand. I was in 1.12.3 before this update and it was ok ...

**Comment by antelle** [comment]
> Could you please compare what's the difference between requests in this and previous version?

**Comment by LiloBzH** [comment]
erf, i find why

here= https://github.com/keeweb/keeweb/issues/492#issuecomment-562583412

in /config/config.php

  'csrf.optout' =>
  array (
    0 => '/^WebDAVFS/',
    1 => '/^Microsoft-WebDAV-MiniRedir/',
    2 => '/KeeWeb\\/\\d\\.\\d\\.\\d/',
    3 => '/KeeWeb\/\d+\.\d+\.\d+/',
  ),
