### ISSUE TITLE
KeeWeb: line 2: 11957 Bus error               /opt/keeweb-desktop/KeeWeb --disable-updater "$1"

### ISSUE THREAD

**Issue by phgachoud** [keeweb/keeweb#1448]
**Describe the bug**
Not starting application

    pg@pgTower: /tmp$ keeweb 
    Fontconfig warning: "/etc/fonts/fonts.conf", line 100: unknown element "blank"
    /usr/bin/keeweb: line 2: 13506 Bus error               /usr/share/keeweb-desktop/keeweb "$@"
    pg@pgTower: /tmp$ which keeweb
    /usr/bin/keeweb
    pg@pgTower: /tmp$ ll /usr/bin/keeweb
    -rwxr-xr-x 1 root root 50 Apr  4 17:34 /usr/bin/keeweb
    pg@pgTower: /tmp$ sudo dpkg -l|grep keeweb
    ii  keeweb-desktop                                1.13.1-1                                    amd64        KeeWeb
    pg@pgTower: /tmp$ lsb_release -a
    No LSB modules are available.
    Distributor ID: Debian
    Description:    Debian GNU/Linux 9.12 (stretch)
    Release:        9.12
    Codename:       stretch

**To Reproduce**
1. Install keeweb debian package 
2. Start it
3. crashes

**Comment by antelle** [comment]
Hi! I see this warning about fonts in other reports, however it doesn't seem to be the reason. Is there anything other debug info?

**Comment by phgachoud** [comment]
Working after second reboot !!???? Close it...
