### ISSUE TITLE
Auto type not working in macOS Mojave (10.14.6) after updating to KeeWeb v1.13.1

### ISSUE THREAD

**Issue by ericbn** [keeweb/keeweb#1449]
**Describe the bug**
Auto type only switches to app running on the back, but does not type anything.

**To Reproduce**
1. Open Demo database
2. Select an entry
3. Type <kbd>CMD-T</kbd>, or select "Auto type" from the menu besides a field
4. App on the back is switched to the front, as expected, but nothing is auto typed.

**Expected behavior**
If using <kbd>CMD-T</kbd>, username<kbd>TAB</kbd>password<kbd>ENTER</kbd> should have been typed. If clicking on "Auto type" from the menu besides a field, that field value should have been typed.

**Screenshots**
Maybe a video if you want?

**Environment**
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) KeeWeb/1.13.1 Chrome/80.0.3987.158 Electron/8.2.0 Safari/537.36

**Kdbx File**
Can be reproduced with the Demo database.

**Logs**

```
2020-04-06T22:30:25.220Z [auto-type] Auto type event 
Proxy
2020-04-06T22:30:25.220Z [auto-type] Hide window
2020-04-06T22:30:25.327Z [auto-type] Start {USERNAME}{TAB}{PASSWORD}{ENTER}
2020-04-06T22:30:25.328Z [auto-type] Parsed [op:USERNAME,op:TAB,op:PASSWORD,op:ENTER]
2020-04-06T22:30:25.329Z [auto-type] Resolved [*****,key:tab,[*,*,*,*,*,*,*,*],key:enter]
2020-04-06T22:30:25.572Z [launcher] spawn /Applications/KeeWeb.app/Contents/Resources/helper/darwin/KeeWebHelper: 0, 241ms
2020-04-06T22:30:25.572Z [auto-type] Complete 245ms
```

**Comment by antelle** [comment]
Hi! I think you need to go to mac settings and (re-)add KeeWeb there:
System Settings -> Security & Privacy -> Privacy -> Accessibility
https://github.com/keeweb/keeweb/issues/953

Does it help? I'll add it to wiki then, and maybe to the application itself, if it happend often.

**Comment by ericbn** [comment]
I removed and then added back the KeeWeb and KeeWebHelper entries in the Accessibility list (which were there and enabled already), restarted KeeWeb, and then it worked. Thanks!

Maybe the installation of KeeWeb v1.13.1 could have taken care of that automatically...

**Comment by antelle** [comment]
Cool, I'll check if it's possible to do it automatically (probably not), but in any case we can detect it and display a message.
