### ISSUE TITLE
CSP error when trying to connect to WebDAV 

### ISSUE THREAD

**Issue by tbradsha** [keeweb/keeweb#1450]
**Describe the bug**
After updating to KeeWeb v1.13.1 from v1.12.3, I'm no longer able to open kdbx files via WebDAV. Opening the Network tab in DevTools shows `(blocked:csp)`, as shown in the screenshot below.

WebDAV is served by Nextcloud, but has been working fine until this latest update. The KeeWeb client is on macOS 10.15.2.

**Screenshots**
![image](https://user-images.githubusercontent.com/32492176/78742342-f8e2a380-7918-11ea-8f12-e376eb307ee1.png)

**Environment**
```
KeeWeb v1.13.1 (d9222909, 2020-04-04)
Environment: electron v8.2.0
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_2) AppleWebKit/537.36 (KHTML, like Gecko) KeeWeb/1.13.1 Chrome/80.0.3987.158 Electron/8.2.0 Safari/537.36
```

**Logs**
Please open dev tools in your browser and attach output log from Console tab. If you are using a desktop app, devtools can be opened from Settings/General/Advanced.

```
index.html:1 2020-04-08T03:41:55.323Z [sync:keypass] Stat file
index.html:1 2020-04-08T03:41:55.323Z [storage-webdav] Stat http://mydomain.com/remote.php/dav/files/someuser/keypass.kdbx
index.html:1 2020-04-08T03:41:55.326Z [storage-webdav] Stat error http://mydomain.com/remote.php/dav/files/someuser/keypass.kdbx 2ms
index.html:1 2020-04-08T03:41:55.326Z [sync:keypass] Stat error, not dirty network error
index.html:1 2020-04-08T03:41:55.326Z [sync:keypass] Sync finished network error
index.html:1 2020-04-08T03:43:52.249Z [sync:keypass] Sync started webdav http://mydomain.com/remote.php/dav/files/someuser/keypass.kdbx {startedByUser: true}
index.html:1 2020-04-08T03:43:52.250Z [sync:keypass] Stat file
index.html:1 2020-04-08T03:43:52.251Z [storage-webdav] Stat http://mydomain.com/remote.php/dav/files/someuser/keypass.kdbx
index.html:1 2020-04-08T03:43:52.253Z [storage-webdav] Stat error http://mydomain.com/remote.php/dav/files/someuser/keypass.kdbx 2ms
index.html:1 2020-04-08T03:43:52.253Z [sync:keypass] Stat error, not dirty network error
index.html:1 2020-04-08T03:43:52.253Z [sync:keypass] Sync finished network error
```

**Comment by tbradsha** [comment]
My suspicion is that it's related to #1438. Downgrading to v1.12.3 resolved the issue for now.

**Comment by antelle** [comment]
Hi! Is it HTTP or HTTPS? We’re blocking all insecure connections (HTTP) now.

**Comment by tbradsha** [comment]
Ah, it's HTTP, though HTTPS didn't have an SSL certificate (internal home network). As such, two questions:

1. In my case, I'm now in a situation where I can add a cert. What's the easiest way to update the kdbx WebDAV URL? Just edit `~/Library/Application Support/KeeWeb/file-info.json`?
2. Any way to override this to allow for HTTP in edge cases?

**Comment by antelle** [comment]
1. Yes, updating it here should work, but probably it's easier to remove the file from KeeWeb and add it again.
2. If you're self-hosting, you can edit the CSP to allow HTTP connections, search `connect-src` and add `http:` right after it.

**Comment by tbradsha** [comment]
To clarify, I'm self-hosting the kdbx, but using the macOS app. Where would I edit the CSP in the macOS app (if possible)?

**Comment by antelle** [comment]
It won't be possible in the macOS app, unfortunately. I would suggest switching to HTTPs, it's easy and free for everyone now.

**Comment by tbradsha** [comment]
Yep, HTTPS is best, and possible now. In some cases (e.g. a closed network), getting an SSL cert isn't so easy, though.

Thanks for confirming!

**Comment by antelle** [comment]
Well, you can generate a self-signed certificate, this will be already much better compared to HTTP.
