### ISSUE TITLE
Autotype has long delay

### ISSUE THREAD

**Issue by dploeger** [keeweb/keeweb#1451]
**Describe the bug**
On Keeweb 1.13.2 hitting the global autotype shortcut opens autotype, but only after a long delay of about 7 seconds.

**To Reproduce**
1. Open Keeweb App (with or without opening a db)
2. Hit autotype shortcut 

=> Autotype takes about 7 seconds to launch

**Expected behavior**
Autotype will open immediately

**Environment**
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/537.36 (KHTML, like Gecko) KeeWeb/1.13.2 Chrome/80.0.3987.158 Electron/8.2.0 Safari/537.36

**Logs**
I guess, the relevant part is this:

```
[DEBUG] 2020-04-11T14:08:45.834Z [auto-type] Auto type event null
[DEBUG] 2020-04-11T14:08:45.835Z [auto-type] Getting window info
[INFO ] 2020-04-11T14:08:46.304Z [launcher] spawn osascript: 0, 468ms
102425 Google Chrome
[INFO ] 2020-04-11T14:08:46.446Z [launcher] spawn osascript: 0, 142ms
https://web:8443/
Waldbühne Heessen
[DEBUG] 2020-04-11T14:08:46.446Z [auto-type] Window info 102425 Waldbühne Heessen https://web:8443/
[DEBUG] 2020-04-11T14:08:46.446Z [auto-type] auto-type event delayed
[INFO ] 2020-04-11T14:08:53.878Z [open:Dennis] File open request
```

**Comment by antelle** [comment]
Hi! Thanks!
This is CPU throttling 😡  not sure why electron has this bug in each and every version, I'll try to find what to do with it now.

**Comment by dploeger** [comment]
Awesome. Thanks

**Comment by antelle** [comment]
Found a workaround, the fix is coming today. Apparently throttling is applied only to injected scripts, so it's easy to fix.

**Comment by jivarson** [comment]
i commented in #1421 (for ubuntu) but maybe it's related to this issue, i didn't wait 7 seconds before switching windows..
Will investigate tonight

**Comment by antelle** [comment]
Done, the release is rolled out, please give it a try

**Comment by antelle** [comment]
Side note: we should show the window immediately, now the app tries to get the window title first, which gives some perceived delay, but that's not much indeed.

**Comment by dploeger** [comment]
Works like a charm! Thanks a lot.
