### ISSUE TITLE
KeeWeb-1.13.3.mac.dmg download blocked by Chrome Advanced Protection

### ISSUE THREAD

**Issue by aragos** [keeweb/keeweb#1452]
**Describe the bug**
When attempting to download the most recent version of KeeWeb (either through the direct link from keeweb.info or from the link on [github](https://github.com/keeweb/keeweb/releases/tag/v1.13.3)) the download is blocked in Chrome.

**Expected behavior**
The download should complete successfully.

**Screenshots**
<img width="356" alt="Screen Shot 2020-04-12 at 12 15 10" src="https://user-images.githubusercontent.com/2575453/79073930-5da25300-7cb7-11ea-9a1f-7d8d1bb23319.png">

**Environment**
Google Chrome 80.0.3987.163
MacOS 10.15.3

**Further Reading**
I believe this is due to my Google account being enrolled in Google's Advanced Protection program. The relevant FAQ can be found on this [Google help page](https://support.google.com/accounts/answer/7539956) under "Why did Chrome stop my download?". Further investigation suggests that the instructions on [Malware and Unwanted Software](https://support.google.com/webmasters/answer/3258249) may be helpful in identifying and fixing the issue.

**Comment by antelle** [comment]
Hi! I just got the same thing in Chrome, not sure why this happens.
It's interesting that I can't report it: if I click "Security Issues report" link, it shows there are no problems found:
<img width="875" alt="Screen Shot 2020-04-12 at 18 29 24" src="https://user-images.githubusercontent.com/633557/79074253-ac69e000-7ceb-11ea-837d-366e4db28fdd.png">

**Comment by antelle** [comment]
I guess, it can also happen because downloads are hosted on GitHub and there was some malware found, which resulted in other software being also blocked.

**Comment by antelle** [comment]
Seems to be fixed now, could you please check if it works for you as well?

<img width="696" alt="Screen Shot 2020-04-14 at 16 56 26" src="https://user-images.githubusercontent.com/633557/79239582-05af4c00-7e71-11ea-9d6c-ade038095ed5.png">

**Comment by aragos** [comment]
Yup, all seems fixed now!

**Comment by antelle** [comment]
Good, thanks for confirming, so it fixed itself, I haven't done anything
