### ISSUE TITLE
File Upload Feature

### ISSUE THREAD

**Issue by thefiredragon** [keeweb/keeweb#1455]
On macPass and other Desktop versions is a feature to attach files to entries.
Think this would be an important feature, on our old databases we have lot's of attachments.
Perhaps I'm blind but I can't find a button to attach a file or download or view an attached file.
Could it possible to bring up such a feature in the near future?

**Comment by jivarson** [comment]
there is, you can drag'n drop a file onto an entry to save it, it will then appear at the bottom of the entry for future access

**Comment by thefiredragon** [comment]
Okay thanks, and how to delete an attachment?

**Comment by thefiredragon** [comment]
thanks
