### ISSUE TITLE
Tag Color and Icon

### ISSUE THREAD

**Issue by newhinton** [keeweb/keeweb#1462]
**Is your feature request related to a problem? Please describe.**
Its an improvement

**Describe the solution you'd like**
Add the ability to set a color and or an icon for a tag. This could improve the overview of tags for an entry. The view for editing a tagname is already there, and could be expanded to include the nessessary settings.

**Comment by antelle** [comment]
Hi! We already have icons and colors for entries, having it on tag level is too much information. You can create a plugin for this if you prefer.

**Comment by newhinton** [comment]
Understandable. Just a quick idea i had :D
