### ISSUE TITLE
(help) multiple webdav configuration

### ISSUE THREAD

**Issue by thefiredragon** [keeweb/keeweb#1465]
Single webdav works fine, perhpas it's a bug or I missunderstand handling,

First try was to create two blocks for webdav, but only the first was showing up on main page.
Second try was to keep all informations in one block

Here the two codes
First:

   "files": [{
                "storage": "webdav",
                "name": "CG-KDBX",
                "path": "https://webdav.company-xxx/CG-KDBX.kdbx",
                "options": { "user": "webdav", "password": "xxx" }
        }],
   "files": [{
                "storage": "webdav",
                "name": "SHJ",
                "path": "https://webdav.company-xxx/SHJ.kdbx",
                "options": { "user": "webdav", "password": "" }
        }]

Second :

   "files": [{
                "storage": "webdav",
                "name": "CG-KDBX",
                "path": "https://webdav.company-xxx/cg.kdbx",
                "name": "SHJ",
                "path": "https://webdav.company-xxx/SHJ.kdbx",
                "options": { "user": "webdav", "password": "" }
}]

So my question here would be how to create multiple links on main page correclty? on both ways only first entry are showing up. :(

**Comment by antelle** [comment]
Hi! Both of them must be inside one “files” group

**Comment by thefiredragon** [comment]
`		"files": [{
		"storage": "webdav",
		"name": "CG-KDBX",
		"path": "URL",
		"options": { "user": "webdav", "password": "" }
},
{
               "storage": "webdav",
                "name": "SHJ",
                "path": "URL",
                "options": { "user": "webdav", "password": "" }
}]

}`

So it's working thanks, was little bit confused :)
