### ISSUE TITLE
Sync with GDrive not working due to DOM mutation

### ISSUE THREAD

**Issue by dominikheinz** [keeweb/keeweb#1467]
**Describe the bug**
Syncing the database (uploading changes) over google drive is not working anymore when using the web client (app.keeweb.info). 
Downloading changes is still working. 

**Specs:**
OS: Arch Linux x64; bspwm
Browser: Latest firefox

**To Reproduce**
No idea, the error just came up recently

**Expected behavior**
The sync should work normally

**Screenshots**
![2020-04-18-194220_1145x715_scrot](https://user-images.githubusercontent.com/32770080/79642251-bd5b9b00-819c-11ea-9a64-3dd42e2f3185.png)

**Environment**
Mozilla/5.0 (X11; Linux x86_64; rv:75.0) Gecko/20100101 Firefox/75.0

**Comment by antelle** [comment]
Hi! Does this happen in incognito in Firefox? If so, it's a known issue.

**Comment by dominikheinz** [comment]
Yeah, it happens apparently only in incognito mode. 
What is the reason for this? And can we expect a fix in the future?

**Comment by antelle** [comment]
Firefox doesn't allow using IndexedDB in incognito mode, and we're not prepared to work without it, see #1115
