### ISSUE TITLE
Auto type stopped working after updating to v1.14.0

### ISSUE THREAD

**Issue by shivamb** [keeweb/keeweb#1468]
**Describe the bug**
Auto type is not working on macOS Catalina 10.15.3 (19D76) after recent update.

**To Reproduce**
1. Go to any credential entry
2. Click on Auto Type or use shortcut Cmd+T

**Expected behavior**
The credentials should be auto typed on opened window.

**Screenshots**
n/a

**Environment**
KeeWeb v1.14.0 (eaf429d, 2020-04-18)
Environment: electron v8.2.3
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_3) AppleWebKit/537.36 (KHTML, like Gecko) KeeWeb/1.14.0 Chrome/80.0.3987.163 Electron/8.2.3 Safari/537.36

**Kdbx File**
Does it happen on Demo or New database?  
This happens with existing file which was working earlier.

**Logs**
[DEBUG] 2020-04-19T05:44:05.720Z [auto-type] Hide window
[DEBUG] 2020-04-19T05:44:05.828Z [auto-type] Start {USERNAME}{TAB}{PASSWORD}{ENTER}
[DEBUG] 2020-04-19T05:44:05.828Z [auto-type] Parsed [op:USERNAME,op:TAB,op:PASSWORD,op:ENTER]
[DEBUG] 2020-04-19T05:44:05.829Z [auto-type] Resolved [**********************,key:tab,[*,*,*,*,*,*,*,*,*,*],key:enter]
[INFO ] 2020-04-19T05:44:06.142Z [launcher] spawn /Applications/KeeWeb.app/Contents/Resources/helper/darwin/KeeWebHelper: 0, 313ms
[DEBUG] 2020-04-19T05:44:06.142Z [auto-type] Complete 314ms

**Comment by antelle** [comment]
https://github.com/keeweb/keeweb/issues/1303#issuecomment-541503996
