### ISSUE TITLE
Last release

### ISSUE THREAD

**Issue by thefiredragon** [keeweb/keeweb#1469]
What does 'using OAuth authorization code grant for all storage providers' mean?
Could you explain me this here?
Best Regards
Dan

**Comment by antelle** [comment]
Hi! You can find more about it here, if you're interested: https://oauth.net/2/grant-types/
For KeeWeb users it means more secure connection to cloud storage providers.

**Comment by thefiredragon** [comment]
Thanks for your answer, I know OAuth, I'm more interested how it's used in keeweb and how to configure it, best Regards

**Comment by antelle** [comment]
It's used to connect Dropbox, Google Drive, etc...
