### ISSUE TITLE
WebDAV Error: network error 

### ISSUE THREAD

**Issue by phenomeus** [keeweb/keeweb#1471]
**Describe the bug**
I cant connect via webdav tp my rpi4, with an ID + PW but with macOS I can and also with cadaver on the pi directly 

**To Reproduce**
1. start keeweb on macos
2. go to "… more"
3. go to webdav
4. instert http://localip/webdav/file.kdbx
5. instart ID
6. instert PW
7. **error: network error**

**Expected behavior**
a connection to save and work with the db

**Environment**
macOS 10.15.4

**Kdbx File**
fresh DB, created and transferred 

**Logs**
[DEBUG] 2020-04-20T06:47:44.447Z [storage-webdav] Stat http://192.168.1.10/webdav
[DEBUG] 2020-04-20T06:47:44.450Z [storage-webdav] Stat error http://192.168.1.10/webdav 3ms
[DEBUG] 2020-04-20T06:48:08.667Z [storage-webdav] Stat http://192.168.1.10/webdav
[DEBUG] 2020-04-20T06:48:08.670Z [storage-webdav] Stat error http://192.168.1.10/webdav 3ms
[DEBUG] 2020-04-20T06:48:14.700Z [storage-webdav] Stat http://192.168.1.10/webdav
[DEBUG] 2020-04-20T06:48:14.701Z [storage-webdav] Stat error http://192.168.1.10/webdav 1ms
[DEBUG] 2020-04-20T06:48:15.245Z [storage-webdav] Stat http://192.168.1.10/webdav
[DEBUG] 2020-04-20T06:48:15.248Z [storage-webdav] Stat error http://192.168.1.10/webdav 2ms
[DEBUG] 2020-04-20T06:48:15.397Z [storage-webdav] Stat http://192.168.1.10/webdav
[DEBUG] 2020-04-20T06:48:15.399Z [storage-webdav] Stat error http://192.168.1.10/webdav 2ms

**Comment by phenomeus** [comment]
maybe its the port? 
cadaver is going to 443, and I think keeweb on 80? don't know what macOS is using with cmd+k 
there is no port, so its defaulting

**Comment by antelle** [comment]
It's HTTP. Now HTTPS is enforced and the app will reject HTTP connections. Are you using a desktop version?

**Comment by phenomeus** [comment]
yes I do and it would be nice to actually see that hint as an user error message. "please use https" ;) will try to get my webdav setup in lighttpd to talk ssl

**Comment by antelle** [comment]
Makes sense, let's add a message indeed

**Comment by phenomeus** [comment]
strange, its still not working, but I'm connected and also can download that file with a browser. 
any other ideas? ssl is working and active. 

<img width="383" alt="Bildschirmfoto 2020-04-20 um 22 34 57" src="https://user-images.githubusercontent.com/5281493/79797278-43234600-8357-11ea-81ff-0bf5aeef3259.png">

**Comment by antelle** [comment]
Let's see the network logs in keeweb devtools

**Comment by phenomeus** [comment]
how?

**Comment by antelle** [comment]
Go to Settings / General and scroll down, click Show Advanced and then you will see the button.

**Comment by phenomeus** [comment]
ERR_CERT_COMMON_NAME_INVALID

**Comment by antelle** [comment]
Is the certificate trusted by the system? As in, if you load it in browsers, is there a security exception?

**Comment by phenomeus** [comment]
think so, no error message. just an download

**Comment by antelle** [comment]
Strange. In theory Electron should use certificate trust settings, I'll try to reproduce it

**Comment by antelle** [comment]
It looks like the certificate is not issued for the address used, what happens if you issue a certificate for a hostname and trust it in the keychain?

**Comment by iromeister** [comment]
@phenomeus Did you really insert http://localip/webdav/file.kdbx ? Because the log only shows
`Stat error http://192.168.1.10/webdav`
without the /file.kdbx

**Comment by phenomeus** [comment]
i tried both

**Comment by antelle** [comment]
I've just tried to load a file from a webdav server with a self-signed certificate. It works well, but as I said, the certificate must be installed to Keychain and trusted.

**Comment by phenomeus** [comment]
sorry for coming back that late again. I trusted the self signed certificate, I get a download in safari when I do: https://192.168.1.10/webdav/Database.kdbx or I use cmd+k and can connect to https://192.168.1.10/webdav/

the certificate is accepted. but still no luck with webdav, logs are showing: 
…
[INFO ] 2020-06-26T08:31:36.479Z [usb-listener] Starting USB listener
[DEBUG] 2020-06-26T08:31:36.479Z [native-module-connector] Starting native module host
[DEBUG] 2020-06-26T08:31:54.932Z [storage-webdav] Stat https://192.168.1.10/webdav/Database.kdbx
[DEBUG] 2020-06-26T08:31:55.114Z [storage-webdav] Stat error https://192.168.1.10/webdav/Database.kdbx 182ms
[DEBUG] 2020-06-26T08:32:12.673Z [storage-webdav] Stat https://192.168.1.10/webdav/Database.kdbx
[DEBUG] 2020-06-26T08:32:12.699Z [storage-webdav] Stat error https://192.168.1.10/webdav/Database.kdbx 25ms
[DEBUG] 2020-06-26T08:32:13.359Z [storage-webdav] Stat https://192.168.1.10/webdav/Database.kdbx
[DEBUG] 2020-06-26T08:32:13.391Z [storage-webdav] Stat error https://192.168.1.10/webdav/Database.kdbx 31ms
[DEBUG] 2020-06-26T08:32:13.528Z [storage-webdav] Stat https://192.168.1.10/webdav/Database.kdbx
[DEBUG] 2020-06-26T08:32:13.555Z [storage-webdav] Stat error https://192.168.1.10/webdav/Database.kdbx 27ms
[DEBUG] 2020-06-26T08:32:13.685Z [storage-webdav] Stat https://192.168.1.10/webdav/Database.kdbx
[DEBUG] 2020-06-26T08:32:13.706Z [storage-webdav] Stat error https://192.168.1.10/webdav/Database.kdbx 21ms
[DEBUG] 2020-06-26T08:32:13.842Z [storage-webdav] Stat https://192.168.1.10/webdav/Database.kdbx
[DEBUG] 2020-06-26T08:32:13.862Z [storage-webdav] Stat error https://192.168.1.10/webdav/Database.kdbx 20ms
[DEBUG] 2020-06-26T08:32:14.000Z [storage-webdav] Stat https://192.168.1.10/webdav/Database.kdbx
[DEBUG] 2020-06-26T08:32:14.031Z [storage-webdav] Stat error https://192.168.1.10/webdav/Database.kdbx 31ms
[DEBUG] 2020-06-26T08:35:04.328Z [storage-webdav] Stat https://192.168.1.10/webdav/Database.kdbx
[DEBUG] 2020-06-26T08:35:04.352Z [storage-webdav] Stat error https://192.168.1.10/webdav/Database.kdbx 24ms

any idea?
