### ISSUE TITLE
Improve folder navigation

### ISSUE THREAD

**Issue by sainf** [keeweb/keeweb#1474]
**Is your feature request related to a problem? Please describe.**
I'm migrated from other keepass and I have and extensive folder structure, but in this layout the folder structure is useless, I have to do a lot of scroll's to find one.

**Describe the solution you'd like**
Can a search box be implemented only for the folders?

Example:
![path4562](https://user-images.githubusercontent.com/1210947/79852899-363a3d00-83bf-11ea-99cf-4f284a1e6a27.png)

**Comment by antelle** [comment]
The design should be a bit different, but it’s a frequent request to search in folders yes.

**Comment by sainf** [comment]
The design has a fast inkscape draw...

For now I'm using the title with pseudo folder paths to be include in the search, so my Db is a mess.

Please considered in the near future.
Thanks for the great app, it resolve all my db sync problems!
