### ISSUE TITLE
Global type on Firefox doesn't get URL

### ISSUE THREAD

**Issue by dmitripr** [keeweb/keeweb#1477]
When using Global Type on Firefox, KeePass doesn't seem to be getting the URL passed to it. Safari works fine, however.

Log:
```[DEBUG] 2020-04-23T22:41:59.166Z [auto-type] Auto type event null
[DEBUG] 2020-04-23T22:41:59.167Z [auto-type] Getting window info
[INFO ] 2020-04-23T22:41:59.655Z [launcher] spawn osascript: 0, 488ms
163880 firefox
[INFO ] 2020-04-23T22:41:59.799Z [launcher] spawn osascript: 0, 144ms
Mozilla Firefox
[DEBUG] 2020-04-23T22:41:59.799Z [auto-type] Window info 163880 Mozilla Firefox null
[DEBUG] 2020-04-23T22:42:03.070Z [auto-type] Entry selected null
[DEBUG] 2020-04-23T22:42:03.076Z [auto-type] Hide window
```
KeeWeb v1.14.0 (eaf429d, 2020-04-18)
Environment: electron v8.2.0
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/537.36 (KHTML, like Gecko) KeeWeb/1.13.4 Chrome/80.0.3987.158 Electron/8.2.0 Safari/537.36

**Comment by antelle** [comment]
Hi! Unfortunately Firefox doesn't provide any API for getting the URL, so it's not possible right now.

**Comment by dmitripr** [comment]
Thanks for the feedback!

**Comment by antelle** [comment]
I'll reopen it to track similar issues here, if things ever change, it can be interesting for others as well.

**Comment by antelle** [comment]
Related Firefox issues:

https://bugzilla.mozilla.org/show_bug.cgi?id=125419
https://bugzilla.mozilla.org/show_bug.cgi?id=516502

**Comment by antelle** [comment]
We can close this now, when we have a browser plugin.
