### ISSUE TITLE
Missing auto-type in 1.14?

### ISSUE THREAD

**Issue by harvald** [keeweb/keeweb#1479]
In version 1.13.4 when clicked "more" button there was option "Auto-type settings" but in 1.14 it is gone.

**Comment by antelle** [comment]
Hi! What do you see in "more..."? I do have the auto-type item.

**Comment by harvald** [comment]
Add new field
Hide empty fields
One-time Passwords
Make a copy
Copy all fields

Option exists in exe version, but not under browsers (firefox, chrome). It seems that regardless of version 1.13.4 or 1.14 (sorry about that, my mistake).

So problem is only in browsers.

**Comment by antelle** [comment]
Indeed, you cannot auto-type in browsers
