### ISSUE TITLE
[Desktop App] Config location 

### ISSUE THREAD

**Issue by harvald** [keeweb/keeweb#1480]
Is there an option, to change configuration location of desktop app?
Default is in <system dir>\Users\<user>\AppData\Roaming\KeeWeb\
but i want to use program as portable.

**Comment by antelle** [comment]
Hi! Right now no, but we should add it.

**Comment by harvald** [comment]
Thank you very much! ;)

**Comment by antelle** [comment]
Next version will have a special config for portable installations: https://github.com/keeweb/keeweb/wiki/Configuration#portable
