### ISSUE TITLE
Hide config file, Keeweb

### ISSUE THREAD

**Issue by Owningle** [keeweb/keeweb#1481]
Hello, just wondering if it is possible to hide the config file on a hosted instance of keeweb. Would be useful since it contains credentials for the webdav server.

**Comment by antelle** [comment]
Hi! What do you mean as “hide”?

**Comment by Owningle** [comment]
put it in a location that ins't accessible outside of the app.
For example, currently, i have my config file in the same directory as the app, and have a rewrite rule to make sure that config is loaded, however, it is possible to go to https://domain.com/config.json and see the password used to access the webdav server there

**Comment by antelle** [comment]
It’s not possible. If a webpage/webapp can load it, everyone else can do that too.
