### ISSUE TITLE
[Feature Request] full path to the password in the tree structure

### ISSUE THREAD

**Issue by vojsat** [keeweb/keeweb#149]
It would be nice to see the full path to the password in the tree structure as additional information somewhere on the screen (e.g. after searching).

**Comment by antelle** [comment]
This would be useful and can be made in the following ways:
- as an additional item in `more...` entry menu, something like 'Show entry info'
- by adding `...` to `File` label which will expand folders, or just making file title clickable
I'm still thinking where the path should appear. Will be added in next releases.

**Comment by isbad** [comment]
Also click on path to focus it in tree view would be useful, I think (was mentioned in #98)

**Comment by antelle** [comment]
Deployed to [beta.keeweb.info](https://beta.keeweb.info), will be available in the next release
