### ISSUE TITLE
Auto-type issue in Firefox

### ISSUE THREAD

**Issue by harvald** [keeweb/keeweb#1490]
Auto-type cannot choose entry for a webpage if only matching criteria is URL (entry title has no substring of webpage name) and web browser is Firefox.

1. in KeeWeb app create entry with title "google"
2. enter some text in username field
3. in Firefox open webpage "youtube.com"
4. click "login"
5. copy entire webpage address
6. paste address in www field in entry from step 1.
7. click on email field on webpage
8. use alt+shift+T combination

**Expected behavior**
Auto-type should match address of web page from browser with address from entry and automatically enter username. Instead pops up window to manually choose entry.

In Chrome it is ok. I've tested Firefox 75 x64, 50 x64 and 40 x32 with new profile under Windows 7, and also 75 x64 under Ubuntu 18.04. Logs shows that auto-type gets "null" instead of URL from Firefox.

**Environment**
KeeWeb v1.14.0 (eaf429d, 2020-04-18)
Environment: electron v8.2.0
User-Agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) KeeWeb/1.13.4 Chrome/80.0.3987.158 Electron/8.2.0 Safari/537.36

**Logs**
2020-05-01T18:37:50.204Z [auto-type] Auto type event null
index.html:1 2020-05-01T18:37:50.207Z [auto-type] Getting window info
index.html:1 2020-05-01T18:37:51.143Z [launcher] spawn C:\Users\miru\AppData\Roaming\KeeWeb\helper\win32\KeeWebHelper.exe: 0, 935ms
20973242
YouTube — Mozilla Firefox
index.html:1 2020-05-01T18:37:51.144Z [auto-type] Window info 20973242 YouTube — Mozilla Firefox null
index.html:1 2020-05-01T18:37:51.150Z [auto-type] Hide window
index.html:1 2020-05-01T18:37:51.151Z [auto-type] Start {USERNAME}{ENTER}{DELAY 2000}{PASSWORD}{ENTER}
index.html:1 2020-05-01T18:37:51.153Z [auto-type] Parsed [op:USERNAME,op:ENTER,op:DELAY,op:PASSWORD,op:ENTER]
index.html:1 2020-05-01T18:37:51.155Z [auto-type] Resolved [******************,key:enter,cmd:wait,[*,*,*,*,*,*,*,*],key:enter]
index.html:1 2020-05-01T18:37:53.237Z [launcher] spawn C:\Users\miru\AppData\Roaming\KeeWeb\helper\win32\KeeWebHelper.exe: 0, 2080ms
index.html:1 2020-05-01T18:37:53.237Z [auto-type] Complete 2086ms

**Comment by antelle** [comment]
Hi! This is expected in Firefox: #1477

**Comment by harvald** [comment]
Ok, it seems that I found workaround. It can be done by GreaseMonkey script:
document.title = document.title + " - " + document.URL;
setTimeout(function(){ if (document.title.indexOf(document.URL) < 0) document.title = document.title + " - " + document.URL; }, 1000);
