### ISSUE TITLE
Smartphone: unable to zoom or view an image

### ISSUE THREAD

**Issue by TheFax** [keeweb/keeweb#1492]
**Describe the bug**
My report concerns KeeWeb in **html** version.
When you put the smartphone in **landscape** mode there is no possibility to view an attached image. Only a part of the image is visible.
When you put the smartphone in **vertical** mode, there is no possibility to zoom an attached image with fingers (pinch to zoom).

**To Reproduce**
1. Create a database and attach an image (in my example)
2. Open your database with a smartphone and KeeWeb html
3. Open the image
4. In landscape mode the image is not completely visible
5. In vertical mode the image is not zoomable

**Screenshots**
![1](https://user-images.githubusercontent.com/19174767/80870317-f4a26f80-8ca5-11ea-9d9e-03ab1fc47e5e.JPG)
![2](https://user-images.githubusercontent.com/19174767/80870322-f8ce8d00-8ca5-11ea-8c38-722519990153.jpg)

**Environment**
Your user-agent: Mozilla/5.0 - Android 9 - Chrome/81.0
(Unable also to see _Help section_ with smartphone in vertical mode ;-P )

**Kdbx File**
My personal database, created with KeePass more or less 1 year ago.

**Comment by antelle** [comment]
Now everything is zoomable
