### ISSUE TITLE
redirect_uri_mismatch when synchronizing with Google Drive

### ISSUE THREAD

**Issue by mkarnicki** [keeweb/keeweb#1494]
**Describe the bug**
When I open KeeWeb on Mac, I get the following error when it attempts to synchronize with password file in Google Drive:

```
Error 400: redirect_uri_mismatch
The redirect URI in the request, https://app.keeweb.info, does not match the ones authorized for the OAuth client. To update the authorized redirect URIs, visit: https://console.developers.google.com/apis/credentials/oauthclient/84754<redacted>.apps.googleusercontent.com?project=8475<redacted>
```

**To Reproduce**
1. Open KeeWeb info with the password store in Google Drive

**Expected behavior**
I would expect it synchronizes successfully.

**Environment**
KeeWeb v1.12.3 (9b07bbd5, 2019-11-06)
Environment: electron v6.0.2
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) KeeWeb/1.9.2 Chrome/76.0.3809.110 Electron/6.0.2 Safari/537.36

**Kdbx File**
Does it happen on Demo or New database?  
If you have a test db without your personal data, please attach it.

**Logs**
They show nothing interesting besides
`2020-05-05T09:36:16.652Z [storage-gdrive] OAuth: popup opened`

PS KeeWeb rocks

**Comment by antelle** [comment]
Hi! Please upgrade KeeWeb to the latest version. Redirect URI's have been reconfigured, and old ones are no longer supported.

**Comment by mkarnicki** [comment]
Thank you so much, works as expected 💪 You rock!
