### ISSUE TITLE
Error 400: redirect_uri_mismatch

### ISSUE THREAD

**Issue by deadlockmb** [keeweb/keeweb#1495]
Hi, 
After opening and entering the password for the KeeWeb I get this error: 
![keeweb_400](https://user-images.githubusercontent.com/47124380/81055255-3ad31b00-8ec0-11ea-8ae3-37a92d2d9889.png)

Maybe I should I just ignore it and update KeeWeb. I thought I will let you know anyway about this error.
Thanks for awesome application!

KeeWeb v1.10.1 (07177222, 2019-09-20)
Environment: electron v6.0.7
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) KeeWeb/1.10.0 Chrome/76.0.3809.139 Electron/6.0.7 Safari/537.36

**Comment by antelle** [comment]
Hi! Yes, you need to upgrade.

**Comment by deadlockmb** [comment]
Cool! Works perfect after update! Thank you! 👍
