### ISSUE TITLE
Error 400: redirect_uri_mismatch

### ISSUE THREAD

**Issue by wcampbell0x2a** [keeweb/keeweb#1496]
**Describe the bug**
Error 400: redirect_uri_mismatch

**To Reproduce**
1) goto https://app.keeweb.info/
2) use google drive file
3) type password
4) popup to select account, only it shows the following error
```
Authorization Error
Error 400: redirect_uri_mismatch
The redirect URI in the request, https://app.keeweb.info/, does not match the ones authorized for the OAuth client. To update the authorized redirect URIs, visit: https://console.developers.google.com/apis/credentials/oauthclient/847548101761-koqkji474gp3i2gn3k5omipbfju7pbt1.apps.googleusercontent.com?project=847548101761
```

**Expected behavior**
This error disallows me to ave my file when edited.

**Environment**
linux/google-chrome 80.0.3987.149

**Kdbx File**
Use on already created file

**Logs**
```
2020-05-05T15:19:03.904Z [open:wc_Passwords] File open request
(index):1 2020-05-05T15:19:03.905Z [open:****] Open file from cache, will sync after load gdrive
(index):1 2020-05-05T15:19:03.905Z [storage-cache] Load *****
(index):1 2020-05-05T15:19:03.911Z [storage-cache] Loaded *****
(index):1 2020-05-05T15:19:03.912Z [open:****] Loaded file from cache null
(index):1 2020-05-05T15:19:05.588Z [file] Opened file *****: 1673ms, 29012736 rounds, 21 kB
(index):1 2020-05-05T15:19:05.588Z [app] Add last open file ****** ***** ***** ***** *****
(index):1 2020-05-05T15:19:05.638Z [open:****] Sync just opened file
(index):1 2020-05-05T15:19:05.644Z [sync:**** Sync started gdrive **** 
{}
(index):1 2020-05-05T15:19:05.645Z [sync:****] Stat file
(index):1 2020-05-05T15:19:05.652Z [storage-gdrive] OAuth: popup opened
(index):1 2020-05-05T15:19:09.555Z [storage-gdrive] OAuth error popup closed
(index):1 2020-05-05T15:19:09.555Z [sync:****] Stat error, not dirty OAuth: popup closed
(index):1 
```

**Comment by antelle** [comment]
Hi! What's the version of keeweb?

**Comment by Conroman16** [comment]
Thought I'd chime in here.  I had this same issue start happening for me yesterday afternoon.  Couldn't sync my safe on any of my devices anymore.  Went back and looked and I was on KeeWeb v1.8.x.  1.14.x is current, so I updated.  Once the update was installed and upon unlocking my safe, KeeWeb wanted to re-auth with google.  After re-authing, no more `redirect_uri_mispatch` error.

**Comment by antelle** [comment]
Yes, redirect_uri was changed in the latest version, all old versions below v1.14.2 will be incompatible.

**Comment by wcampbell0x2a** [comment]
I am using https://app.keeweb.info/, which now is the correct version(maybe that was the problem) and it works.

-> Help
```
KeeWeb v1.14.2 (03c44d7, 2020-05.04)
```

Thanks for the great product btw

**Comment by Nu11u5** [comment]
> Yes, redirect_uri was changed in the latest version, all old versions below v1.14.2 will be incompatible.

This didn't hit me until today.  Good to know it's not a security issue.
