### ISSUE TITLE
Google Drive Auth Error 400: redirect_uri_mismatch

### ISSUE THREAD

**Issue by mstr3336** [keeweb/keeweb#1497]
**Describe the bug**

I'm getting a problem synching w/ my google drive on the desktop client on windows.

**To Reproduce**

I try to open my normal google drive database, and my google accounts oath dialogue gives me a hard time. 

The database still opens, but I assume this is the local cache version, and won't synch.

**Expected behavior**

**Screenshots**

```
Error 400: redirect_uri_mismatch
The redirect URI in the request, https://app.keeweb.info, does not match the ones authorized for the OAuth client. To update the authorized redirect URIs, visit: https://console.developers.google.com/apis/credentials/oauthclient/847548101761-koqkji474gp3i2gn3k5omipbfju7pbt1.apps.googleusercontent.com?project=847548101761
```

**Environment**
Your user-agent (from Settings/Help section)

KeeWeb v1.12.3 (9b07bbd5, 2019-11-06)
Environment: electron v6.0.2
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) KeeWeb/1.9.2 Chrome/76.0.3809.110 Electron/6.0.2 Safari/537.36

**Kdbx File**
Does it happen on Demo or New database?  
If you have a test db without your personal data, please attach it.

**Logs**
Please open dev tools in your browser and attach output log from Console tab. If you are using a desktop app, devtools can be opened from Settings/General/Advanced.

```
index.html:1 2020-05-07T07:11:48.730Z [app] Started in 504ms ¯\_(ツ)_/¯
index.html:1 2020-05-07T07:11:48.732Z [updater] Next update check will happen in 86397s
index.html:1 2020-05-07T07:11:54.798Z [open:PWords] File open request
index.html:1 2020-05-07T07:11:54.798Z [open:PWords] Open file from cache, will sync after load gdrive
index.html:1 2020-05-07T07:11:54.798Z [storage-cache] Load 8ca893c5-ff90-e936-00c5-4cd2c1251445
index.html:1 2020-05-07T07:11:54.801Z [storage-cache] Loaded 8ca893c5-ff90-e936-00c5-4cd2c1251445 2ms
index.html:1 2020-05-07T07:11:54.801Z [open:PWords] Loaded file from cache null
index.html:1 2020-05-07T07:11:55.171Z [file] Opened file PWords: 369ms, 60000 rounds, 1382 kB
index.html:1 2020-05-07T07:11:55.171Z [app] Add last open file 8ca893c5-ff90-e936-00c5-4cd2c1251445 PWords gdrive 1dq1OMI7Bw3gOE9lnm2HHslrGWy8_3bAf 0Bx-rRA2dsTZaS29SOU1pSFltUGxHSXFSWkttRlhUam4vVkVFPQ
index.html:1 2020-05-07T07:11:55.241Z [open:PWords] Sync just opened file
index.html:1 2020-05-07T07:11:55.271Z [sync:PWords] Sync started gdrive 1dq1OMI7Bw3gOE9lnm2HHslrGWy8_3bAf Object
index.html:1 2020-05-07T07:11:55.272Z [sync:PWords] Stat file
index.html:1 2020-05-07T07:11:55.272Z [storage-gdrive] OAuth: popup opened
index.html:1 2020-05-07T07:11:59.956Z [storage-gdrive] OAuth error popup closed
a.error @ index.html:1
index.html:1 2020-05-07T07:11:59.956Z [sync:PWords] Stat error, not dirty OAuth: popup closed
index.html:1 2020-05-07T07:11:59.956Z [sync:PWords] Sync finished OAuth: popup closed
index.html:1 2020-05-07T07:12:16.674Z [sync:PWords] Sync started gdrive 1dq1OMI7Bw3gOE9lnm2HHslrGWy8_3bAf Object
index.html:1 2020-05-07T07:12:16.675Z [sync:PWords] Stat file
index.html:1 2020-05-07T07:12:16.675Z [storage-gdrive] OAuth: popup opened
[Violation] Forced reflow while executing JavaScript took 43ms
```

**Comment by Bilb** [comment]
same issue here

**Comment by mstr3336** [comment]
Actually - The problem is documented in #1496 and it looks like the solution is clear:

https://github.com/keeweb/keeweb/issues/1496#issuecomment-624150597

> Yes, redirect_uri was changed in the latest version, all old versions below v1.14.2 will be incompatible.

My problem then becomes:

In-App updates don't really seem to work, everytime I click "Restart the app to update" it restarts, but I dont get a new option to update.

**Comment by mstr3336** [comment]
@Bilb if you're facing the same problem, try updating - if it doesnt work from the desktop app, let's just download a release from https://github.com/keeweb/keeweb/releases and that ought to fix it

**Comment by SergiusTheBest** [comment]
Confirming: updating to v1.14.2 fixes this issue.

**Comment by mstr3336** [comment]
I mean the fact that auto update consistently fails is still rough

**Comment by antelle** [comment]
It can fail, especially while updating from old versions.

**Comment by Bilb** [comment]
fixed for me too, but had to download release from website, not from auto update
