### ISSUE TITLE
yubikey challenge-response -> recovery process

### ISSUE THREAD

**Issue by jacek-1** [keeweb/keeweb#1501]
Hi,
securing keepassXC db with my a yubikey via challenge-reponse is nice, but what about a situation when I loose my yubikey ? 

In Keepass2 and KeeChallenge plugin there's a recovery mode when I manually paste a secrety key that I set with yubikey personalization tool,

how that works in keepassXC app ? at this moment without yubikey in my usb port, I simply see an error.

BR

**Comment by antelle** [comment]
Hi! We're KeeWeb, not KeePassXC :) 
There's no support of YubiKey in our app yet, however it will appear in the next version. Perhaps you're looking for these guys: https://github.com/keepassxreboot/keepassxc

**Comment by jacek-1** [comment]
oh apologies, my post to be deleted than.
