### ISSUE TITLE
Webdav add prompt for user and pass while config file

### ISSUE THREAD

**Issue by M1rc34** [keeweb/keeweb#1502]
**Is your feature request related to a problem? Please describe.**
I recently created a docker server using keeweb. Everything is fine so far except the fact that in order to keep the credentials for webdav encrypted I cannot use the config.json file.
I'm planing to use this with my wife. I have a kdbx and she has one. But it would be nice to be able to select it from the list and input the webdav password and the kdbx password.
She is not that technical and it will be a benefit for her to select her file from the list and input the passwords.

**Describe the solution you'd like**
Maybe there is a solution to allow users to put all their webdav files in the config file and create a prompt for webdav username and password if you are not specifying them in the config file.
The idea is to have the paths saved and show a prompt to input credentials for webdav. After that to be saved locally encrypted.

**Describe alternatives you've considered**
The alternative is already proposed in the other tickets related to this issue: put a basic authentication for the website files. The issue with this is that it requires extra steps, and for somebody who does not how to do that, takes a great deal of time to search and experiment.

**Comment by antelle** [comment]
Hi! It's #669
