### ISSUE TITLE
Support for native Windows arm64 build

### ISSUE THREAD

**Issue by mirogl** [keeweb/keeweb#1503]
Hi
Since I'm using a Surface Pro x I would like to use a native Windows arm64 version of Keeweb. Is there any posibility to build this by my own for Windows arm64 or to get an official Windows arm64 release ?
Thanks

**Comment by antelle** [comment]
Hi! I see that it’s supported in Electron: https://www.electronjs.org/docs/tutorial/windows-arm
but not sure what will be the amount of changes required. I for sure need help with building and testing this.

**Comment by mirogl** [comment]
Hi
I would like to help - I have a Surface Pro X for testing. But I still struggle with your build instructions.

I try to build it on Windows 10.

1. downloaded master from git and unzipped it
2. cd to unpacked dir
3. npm install -g grunt-cli
4. delete everything in node_modules
5. set npm_config_arch=arm64
6. npm install
7. grunt desktop --force 
Here I get first the problem, that linux, win32 and x64 is build - i expectedonly arm64 - and i run into this error: 
Running "electron:linux" (electron) task
Warning: An error occurred while processing a template (Cannot read property 'branch' of undefined). Used --force, continuing.
Packaging app for platform linux x64 using electron v8.2.5

Running "chmod:linux-desktop-x64" (chmod) task
>> 1 file had their `chmod` mode set to "4755".

Running "electron:darwin" (electron) task
Warning: Cannot find module './keys/codesign.json'
Require stack:
- C:\Users\miro\Downloads\keeweb-1.14.2\keeweb-1.14.2\Gruntfile.js
- C:\Users\miro\Downloads\keeweb-1.14.2\keeweb-1.14.2\node_modules\grunt\lib\grunt\task.js
- C:\Users\miro\Downloads\keeweb-1.14.2\keeweb-1.14.2\node_modules\grunt\lib\grunt.js
- C:\Users\miro\AppData\Roaming\npm\node_modules\grunt-cli\bin\grunt Used --force, continuing.

Running "electron:win32" (electron) task
Warning: An error occurred while processing a template (Cannot read property 'branch' of undefined). Used --force, continuing.
Packaging app for platform win32 ia32 using electron v8.2.5
Packaging app for platform win32 x64 using electron v8.2.5

Running "sign-exe:win32-build-x64" (sign-exe) task
(node:1628) UnhandledPromiseRejectionWarning: Error: Cannot find module './keys/codesign.json'
Require stack:
- C:\Users\miro\Downloads\keeweb-1.14.2\keeweb-1.14.2\Gruntfile.js
- C:\Users\miro\Downloads\keeweb-1.14.2\keeweb-1.14.2\node_modules\grunt\lib\grunt\task.js
- C:\Users\miro\Downloads\keeweb-1.14.2\keeweb-1.14.2\node_modules\grunt\lib\grunt.js
- C:\Users\miro\AppData\Roaming\npm\node_modules\grunt-cli\bin\grunt
  at Function.Module._resolveFilename (internal/modules/cjs/loader.js:1020:15)
  at Function.Module._load (internal/modules/cjs/loader.js:890:27)
  at Module.require (internal/modules/cjs/loader.js:1080:19)
  at require (internal/modules/cjs/helpers.js:72:18)
  at getCodeSingConfig (C:\Users\miro\Downloads\keeweb-1.14.2\keeweb-1.14.2\Gruntfile.js:32:37)
  at Object.get windows [as windows] (C:\Users\miro\Downloads\keeweb-1.14.2\keeweb-1.14.2\Gruntfile.js:588:28)
  at recurse (C:\Users\miro\Downloads\keeweb-1.14.2\keeweb-1.14.2\node_modules\grunt-legacy-util\index.js:120:33)
  at Object.util.recurse (C:\Users\miro\Downloads\keeweb-1.14.2\keeweb-1.14.2\node_modules\grunt-legacy-util\index.js:131:10)
  at Function.config.process (C:\Users\miro\Downloads\keeweb-1.14.2\keeweb-1.14.2\node_modules\grunt\lib\grunt\config.js:52:21)
  at Function.config.get (C:\Users\miro\Downloads\keeweb-1.14.2\keeweb-1.14.2\node_modules\grunt\lib\grunt\config.js:46:17)
  at Object.module.exports [as config] (C:\Users\miro\Downloads\keeweb-1.14.2\keeweb-1.14.2\node_modules\grunt\lib\grunt\config.js:12:19)
  at Object.options (C:\Users\miro\Downloads\keeweb-1.14.2\keeweb-1.14.2\node_modules\grunt\lib\grunt\task.js:228:15)
  at Object.<anonymous> (C:\Users\miro\Downloads\keeweb-1.14.2\keeweb-1.14.2\build\tasks\grunt-sign-exe.js:13:30)
  at Object.<anonymous> (C:\Users\miro\Downloads\keeweb-1.14.2\keeweb-1.14.2\node_modules\grunt\lib\grunt\task.js:252:15)
  at Object.thisTask.fn (C:\Users\miro\Downloads\keeweb-1.14.2\keeweb-1.14.2\node_modules\grunt\lib\grunt\task.js:70:16)
  at Object.<anonymous> (C:\Users\miro\Downloads\keeweb-1.14.2\keeweb-1.14.2\node_modules\grunt\lib\util\task.js:294:30)
  at Task.runTaskFn (C:\Users\miro\Downloads\keeweb-1.14.2\keeweb-1.14.2\node_modules\grunt\lib\util\task.js:244:24)
  at Task.<anonymous> (C:\Users\miro\Downloads\keeweb-1.14.2\keeweb-1.14.2\node_modules\grunt\lib\util\task.js:293:12)
  at C:\Users\miro\Downloads\keeweb-1.14.2\keeweb-1.14.2\node_modules\grunt\lib\util\task.js:220:11
  at processTicksAndRejections (internal/process/task_queues.js:79:11)

(Use `node --trace-warnings ...` to show where the warning was created)
(node:1628) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)

Any suggestion, how should i build this on Windows - or should i switch to Mac OS X for the desktop build ?

Thanks
Miro

**Comment by antelle** [comment]
I would try running tasks one by one, from [here](https://github.com/keeweb/keeweb/blob/master/grunt.entrypoints.js#L46), what's inside `desktop-win32`. Task definitions can be found in [this file](https://github.com/keeweb/keeweb/blob/master/grunt.tasks.js), you can run them something like `grunt electron:win32` and exclude linux and mac build.

**Comment by mirogl** [comment]
Hi
Thanks. I switched to my Mac OS X to test, if I have a platform specific problem.
Still same problem. Now I executed: grunt electron:win32

miro@miros-MBP keeweb % grunt electron:win32 
Running "electron:win32" (electron) task
Warning: An error occurred while processing a template (Cannot read property 'branch' of undefined). Use --force to continue.

Aborted due to warnings.


Execution Time (2020-05-10 17:18:07 UTC+2)
loading tasks  547ms  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 99%
Total 551ms

miro@miros-MBP keeweb % grunt electron:win32 --force
Running "electron:win32" (electron) task
Warning: An error occurred while processing a template (Cannot read property 'branch' of undefined). Used --force, continuing.
Packaging app for platform win32 ia32 using electron v8.2.5
Packaging app for platform win32 x64 using electron v8.2.5
Warning: ENOENT: no such file or directory, stat 'tmp/desktop/app' Used --force, continuing.

Done, but with warnings.


Execution Time (2020-05-10 17:18:27 UTC+2)
loading tasks   545ms  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 35%
electron:win32     1s  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 65

Any idea about the error "Error: Cannot find module './keys/codesign.json" and above ? Here the commands I tried

npm_config_arch=arm64
npm install
grunt desktop --force
grunt electron:win32
grunt electron:win32 --force

Thanks
Miro

**Comment by antelle** [comment]
You won't be able to build a Windows app on macos.
Here the problem is, you need to run `gitinfo` before every task:
`grunt gitinfo electron:win32`

I also advice against using --force, in most cases it will give weird results and it's better to inspect an error rather than getting something vague on later stages.

**Comment by mirogl** [comment]
Hi,
thanks for the info. So there is no option for cross build ? This would mean i need to get npm and grunt running on my Surface Pro X with arm64 ? Until now i tried the build on Windows 10 x64 and MacOS.
Can you just give me some info, what is happening after the npm install command ? It seems there are now a lot of files in the node_modules directory, which should be for arm64. Can i test them with some commands ?

Thanks
Miro

**Comment by antelle** [comment]
I'm not sure, I think it should be possible to build it on Windows, but not on macOS or Linux. The reason is that we depend on Windows tools, such as icon/resource editor and so on.

**Comment by mirogl** [comment]
Hi,
I still not understand, what is happening after the "npm install" - do I have already the finished web application and could distribute / pack it manually with the arm64 packages of electron ?

https://github.com/electron/electron/releases/download/v9.0.0-beta.23/electron-v9.0.0-beta.23-win32-arm64.zip
https://github.com/electron/electron/releases/download/v9.0.0-beta.23/chromedriver-v9.0.0-beta.23-win32-arm64.zip

What is grunt for - only for packaging ?

Thanks
Miro

**Comment by antelle** [comment]
Npm install is just installing modules, all building and packaging is done by different grunt tasks.

**Comment by mirogl** [comment]
Hi,
ok - thank. Now i switched to my arm64 device. When trying to copy the whole directory Windows Defender gives me a warning about a trojaner - i checked the file also with virustotal ant virustotal found an issue with 4 providers - see below - could you please check, where this file is created from ?

keeweb\node_modules\app-builder-bin\win\ia32\app-builder copy.exe

AhnLab-V3
Malware/Win32.RL_Generic.R329914
SecureAge APEX
Malicious

Bkav
W32.AIDetectVM.malware
Cylance
Unsafe

Ikarus
Trojan.Crypt
McAfee
Artemis!5D545B5A6076

McAfee-GW-Edition
BehavesLike.Win32.Trojan.rh
Rising
PUA.Presenoker!8.F608 (CLOUD)

VBA32
BScope.TrojanRansom.Encoder
Acronis
Undetected

Thanks
Miro

**Comment by antelle** [comment]
Well, disable the anti-virus

**Comment by mirogl** [comment]
Hi
now it is running ;-) I did the following. 

1.  Downloaded https://github.com/electron/electron/releases/download/v9.0.0-beta.23/electron-v9.0.0-beta.23-win32-arm64.zip on my Surface Pro X and unpacked it in the Downloads Directory.
2. Installed KeeWeb on my Windows 10 x64 machine and copied resources\app.asar fromm the PassWeb application directory to resources\app.asar  on my Surface Pro X electron directory.  Now when starting electron.exe i get the KeeWeb running on arm64 ;-)
3. To have a nice install i renamed electron.exe to KeeWeb.exe and the electron directory to KeeWeb and copied manually to my Programs directory.

For me this is ok and easy at the moment.

Many thanks for the support
Best regards
Miro

**Comment by antelle** [comment]
Good, so it seems to be starting, but just needs proper packaging.
Please let me know your experience with it after a couple of days, let's see if you find anything weird.

**Comment by mirogl** [comment]
Hi
I tested the functions and only found one issue. The Autotype feature does not work, because the helper\win32\KeeWebHelper.exe was not compiled arm64 - my assumption.The error is  "Error spawn C:\Program Files (Arm)\KeeWeb\ressources\helper\win32\KeeWebHelper.exe ENOENT". The rest works without any problems.

Thanks
Miro

**Comment by antelle** [comment]
What happens if you copy this helper and run it, does it throw and error? The helper is here: https://github.com/keeweb/keeweb/blob/master/helper/win32/KeeWebHelper.exe

**Comment by mirogl** [comment]
Hi
How can i test functionality ? on Both - win32/64 and arm64 the command just starts and does not quit without any output.
Thanks
Miro

**Comment by antelle** [comment]
It's good that it starts! What happens if you copy it to `C:\Program Files (Arm)\KeeWeb\ressources\helper\win32\KeeWebHelper.exe` and run auto-type in KeeWeb?

**Comment by mirogl** [comment]
Hi, i created the directory structure and copied the file - now it works ! 
So the reason is clear now. I downloaded KeeWeb on my Windows 10 x64 - so the download was automatically the x64 version. When i try to download KeeWeb from my Surface Pro X the win32 Version is offered for download. Since I took the copy from my x64, the exe won´t work - only win32, arm and arm64 is suppored on Surface Pro X- So the correct way would be to install the win32 Version and then replace the asar file. But then the package is still not native arm64. I looked into the source code of the KeeWebHelper.exe - and it needs the .NET Framework, which is currently not available as native arm64.
But again many thank - now everything works and since only the min application is running most of the time, the application now runds 99% native under arm64.

Thanks
Miro

**Comment by antelle** [comment]
I'm not sure I understand. You're saying it works, but below you're saying that the .NET Framework is not available. So, does any of versions (I assume, you ended up using the 32-bit one) work for you, as in, performs the auto-type?

**Comment by mirogl** [comment]
Hi
yes - the win32 version of KeeWebHelper.exe works and Auto Type now also. I was just looking into the KeeWebHelper.csproj and it seems to use the .NET Framework. For arm64 there is currently no native arm64 .NET Framework available - therefore it seems not possible to port the whole application with the Helper application to arm64 only - this exe will stay win32., since it uses the .NET Framework.

Thanks
Miro

**Comment by antelle** [comment]
I see, thanks for the explanation, so if we build a version for arm64, we should include the 32-bit helper into it.

**Comment by antelle** [comment]
How do you usually install apps on arm, do they come as installer, MSI or EXE, or just in zip archives?

**Comment by mirogl** [comment]
Hi, all of them. It is a full Windows, just arm64 based. The Electron Installer is an example.

**Comment by antelle** [comment]
I made a build for arm64, could you please try if it works for you? https://share.antelle.net/KeeWeb-win32-arm64.zip

Looks like installer is not

**Comment by mirogl** [comment]
Hi
I testet the build. It opens a kdbx files - everythings seems to work. But the Auto Type feature crashes again with:

 "Error spawn C:\Program Files (Arm)\KeeWeb\ressources\helper\win32\KeeWebHelper.exe ENOENT".

I found an interessting Thread from Visual Studio, where the build of arm64 Visual Studio Code and Desktop is discussed. Perhaps this helps, since both are Electron based.

Thanks

**Comment by antelle** [comment]
Cool, thanks for testing it! I was afraid it would crash because it has a native module compiled to arm64. If it doesn't crash, that's ok. Right, the auto-type helper is not added there. 
Then v1.15 will most likely include a zipped version without an installer, if I don't manage to get the installer working.

**Comment by mirogl** [comment]
Great ! If you need further testing, just give me a short info. Many Thanks !

**Comment by antelle** [comment]
If you run a win32 installer, where does it install the application? In "program files" or "program files (arm)"?

**Comment by mirogl** [comment]
Hi
Firefox arm64 installs into program files, not  program files (arm).

**Comment by antelle** [comment]
I guess, native arm64 apps should be installed to "... (arm)", right?
I meant the KeeWeb 32-bit installer: https://github.com/keeweb/keeweb/releases/download/v1.14.2/KeeWeb-1.14.2.win.ia32.exe

**Comment by mirogl** [comment]
Hi, Firefox arm64 is a native arm64 application.
In the program files (arm) i have only Microsoft apps.

**Comment by antelle** [comment]
Does the 32-bit keeweb installer run for you? if so, where does it install?

**Comment by antelle** [comment]
I tried to make an installer for arm64: https://share.antelle.net/KeeWeb.win.arm64.exe, let's see if it runs and what it does

**Comment by mirogl** [comment]
Hi
it installs and runs, but suggests "program files (x86)" for installation. I changed it manually to "program files" and it installed an works - also auto type.
Works great !

**Comment by antelle** [comment]
While I'm trying to understand why it's trying to use x86, a couple of questions:
- does the uninstaller work?
- does it correctly add file associations to the registry? as in, try to open a kdbx file in Windows Explorer:
  - does it show the KeeWeb icon?
  - does it open KeeWeb if you dbl-click it?

**Comment by mirogl** [comment]
Hi
does the uninstaller work? -> yes
does it correctly add file associations to the registry? as in, try to open a kdbx file in Windows Explorer:
does it show the KeeWeb icon? -> yes
does it open KeeWeb if you dbl-click it? -> yes

**Comment by antelle** [comment]
Cool, thanks for testing it!
I think I've fixed the x86 thing, could you please please try the [new installer](https://share.antelle.net/KeeWeb.win.arm64.exe) once again? Also don't forget to run the uninstaller to check if works and properly deletes files from program files (there were changes in it as well).
Let's reopen the issue, to wait until v1.15 when it becomes official.

**Comment by mirogl** [comment]
Hi
All worked like a charm.
Installation was to program files, everything worked (file associations , auto type, open when opening .kdbx )
and also uninstall worked (all files removed, start menu entry removed and also removed from program and features list)
So congratulations - works perfect !

**Comment by antelle** [comment]
Awesome, thanks a lot for helping me! Next version will have an installer and the portable version for arm64.
Another question, for the correct automatic version selection on the website: what is your user agent in Chrome and Edge?
It can be checked here: https://duckduckgo.com/?q=user+agent&ia=answer
Also, could you please open devtools in your browser, type `navigator`, expand it, and copy values from there? I don't have a possibility to test in arm, unfortunately.

**Comment by mirogl** [comment]
Hi
Edge (Chronium) arm64: Your user agent: Mozilla/5.0 (Windows NT 10.0; ) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36 Edg/81.0.416.72

Firefox: Your user agent arm64: Mozilla/5.0 (Windows NT 10.0; rv:76.0) Gecko/20100101 Firefox/76.0

Do you need Chrome - since it is win32 - not arm64 ?

For DevTools I have only Firefox - what do you need there ?

**Comment by antelle** [comment]
Ok, thank you! I'll think and search more how to detect arm64.
Well, it's not a big deal already, we can just redirect to the release page everything which is x64.

**Comment by antelle** [comment]
Hi @mirogl! The release is approaching, it should happen next week. Here's the build: https://github.com/keeweb/keeweb-ci-sandbox/releases/tag/v1.14.3
Could you please give it a try to test if everything works for you?

**Comment by mirogl** [comment]
Hi @antelle 
Thanks - I tried the release and everything workes for me. Installation, Update Check, Add, edit and delete entries, Auto Type - so everything is fine. Many Thanks
Miro

**Comment by antelle** [comment]
Awesome, thank you for testing it! Next release will have arm64 support.
