### ISSUE TITLE
Auto-type doesn't change active window

### ISSUE THREAD

**Issue by b3nj5m1n** [keeweb/keeweb#1509]
**Describe the bug**
When pressing the auto-type shortcut, the selection menu comes up, when I select an entry and press enter nothing happens.

**To Reproduce**
(I'm using Linux Mint with i3-gaps)
1. Open keeweb and another programm (Like firefox) in tiling mode
2. Press auto-type shortcut
3. Select entry from menu
4. Nothing happens

**Expected behavior**
The auto-type sequence gets typed to firefox

**Environment**
KeeWeb v1.14.3 (489eb55, 2020-05-15)
Environment: electron v8.2.5
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) KeeWeb/1.14.3 Chrome/80.0.3987.165 Electron/8.2.5 Safari/537.36

**Relevant part of logs**

> 2020-05-19T14:42:21.017Z [auto-type] Auto type event null
> index.html:formatted:26630 2020-05-19T14:42:21.019Z [auto-type] Getting window info
> index.html:formatted:26636 2020-05-19T14:42:21.037Z [launcher] spawn xdotool: 0, 18ms
> CodePen Login - Mozilla Firefox
> 29360131
> index.html:formatted:26630 2020-05-19T14:42:21.038Z [auto-type] Window info 29360131 CodePen Login - Mozilla Firefox null
> index.html:formatted:26630 2020-05-19T14:42:26.292Z [auto-type] Entry selected {entry: Proxy, sequence: undefined}
> index.html:formatted:26630 2020-05-19T14:42:26.314Z [auto-type] Hide window
> index.html:formatted:26630 2020-05-19T14:42:26.418Z [auto-type] Getting window info
> index.html:formatted:26636 2020-05-19T14:42:26.433Z [launcher] spawn xdotool: 0, 15ms
> KeeWeb
> 146800641
> index.html:formatted:26630 2020-05-19T14:42:26.434Z [auto-type] Window info 146800641 KeeWeb null
> index.html:formatted:26636 2020-05-19T14:42:26.434Z [auto-type] Active window doesn't match: ID is different. Expected 29360131, got 146800641

**Possible Solution**
(Please know that I am not familiar with the code)
Reading the logs gives me the impression that upon launch, auto-type gets the active window id, then notices that there is no single entry matching the window name and therefore opens the menu. After a selection is made from the menu, keeweb tries to hide itself again, which would make firefox the focused window again. This does not work on i3 due to the nature of tiling window managers, and I'm sure this is problematic on other wm's like bspwm or dwm.
So now, the active window is still keeweb and the error "Active window doesn't match" is thrown.
A possible solution to this would be to make xdotool type directly to the window using the id, which can be done using the --window flag. Here is an example:
`xdotool type --window 29360131 "test"`
As I said before, I am not familiar with the code, so I don't know if the current code would allow for such a change, but after looking around in the source code for a little bit I think that this line could be relevant:
`this.pendingScript.push('key U' + char.charCodeAt(0).toString(16));`
([auto-type-emitter-linux.js](https://github.com/keeweb/keeweb/blob/master/app/scripts/auto-type/emitter/auto-type-emitter-linux.js), line 82)
As a result, keeweb would still not be minimized after selecting from the list, but at least the username and password would get typed to the window, making the feature usable at least.

**Comment by b3nj5m1n** [comment]
I made some modifications and created a pull request to fix this issue.
#1511

**Comment by antelle** [comment]
Thank you very much! 🙏 
I've added some comments there, if you have time, I'd be glad if you address them, otherwise I can fix them myself and merge it a bit later.

**Comment by b3nj5m1n** [comment]
I've made another commit addressing those changes.

**Comment by b3nj5m1n** [comment]
Tested this for a while, didn't have any issues with it, so I'm going to close this issue.

**Comment by antelle** [comment]
Let's keep it open until the next version is released, according to our [issue policy](https://github.com/keeweb/keeweb/wiki/FAQ#features).
