### ISSUE TITLE
My Dropbox app & secret key appear on setting

### ISSUE THREAD

**Issue by kendriii** [keeweb/keeweb#1510]
hi, how to hide dropbox app & secret key appear in keeweb setting?

**Comment by kendriii** [comment]
![Capture](https://user-images.githubusercontent.com/65588744/82443444-b2619680-9acb-11ea-8873-c565d1f4499b.PNG)

**Comment by antelle** [comment]
Hi! It's not possible to hide them, and they will be visible in app settings anyway. Treat them as a public credential, as in, don't use this OAuth client in Google for anything else apart from KeeWeb. Embedding secret in the app is what's advised in Google's guide, so that's what we're doing here.

**Comment by kendriii** [comment]
how can i set like dropdown menu? like that picture i attach
![Capture](https://user-images.githubusercontent.com/65588744/82465862-f19ee000-9ae9-11ea-9238-52910b668b07.PNG)

**Comment by antelle** [comment]
I didn't understand the question
