### ISSUE TITLE
Desktop version can't decrypt keyring

### ISSUE THREAD

**Issue by b3nj5m1n** [keeweb/keeweb#1517]
**Describe the bug**
When trying to start the desktop version with `npm run electron` keeweb fails to decrypt the keyring, it throws the following error and then exits:

> Error loading app: Error reading config data app-settings: Error: error: 1e000065:Cipher functions:OPENSSL_internal:BAD_DECRYPT

**To Reproduce**
(Using Linux Mint, tested on both cinnamon and i3)
1. npm run dev
2. npm run electron

**Expected behavior**
Keeweb opens up.

I have tried multiple times to reset my keyrings, I deleted all files from the directory and created a new one using seahorse, I also let keeweb create it's own file and in both cases it seemed to store something in it (When looking at it in seahorse, there is an entry by keeweb), but then failed to decrypt it.

**Comment by antelle** [comment]
Hi! This is the dev version, right?
Assuming it's a dev installation, could you please paste the contents of `app-settings.dat` and your key from the keyring? I guess, we're not writing it properly.
Does it repeat if you delete app-settings.dat?

**Comment by kountrygirl2205** [comment]
This is Christine Cheuvront what are you talking about I've no computer n I
believe I'm being hatch so please who ever it is your communicating to
block them and there devices please!

KountryGirl

**Comment by b3nj5m1n** [comment]
> Hi! This is the dev version, right?

I tested it on the master branch and had no problems, so this was definitely introduced my the recent changes regarding keyrings. This error only occurs on the develop branch, using `npm run dev` and `npm run electron`

> Assuming it's a dev installation, could you please paste the contents of `app-settings.dat` and your key from the keyring? I guess, we're not writing it properly.

Sorry but what exactly do you mean by this? The contents of `app-settings.dat` is not human readable, do you want me to send you a copy anyways?

> Does it repeat if you delete app-settings.dat?

No, that actually solved the issue.

**Comment by antelle** [comment]
I think I know why, fixed it in bf7dec2437c3a9366d3e916fdf2c7622f6076a20

**Comment by antelle** [comment]
Encrypted configs were introduced in dev a couple of days ago, it works on master of course, and I'd be glad if you report other issue you find with them.
