### ISSUE TITLE
Invalid characters in different fields result in a broken KDBX

### ISSUE THREAD

**Issue by ruskiyos** [keeweb/keeweb#1520]
I tried using keeweb to setup a database with my passwords. I regenerated passwords for all my accounts. Everything worked well. 
In the notes section under one of the entries, I pasted some text that had non-standard characters.
I closed the file in keepass and now I cannot reopen it. Additionally, all keepass programs fail at reading my database. I don't have backups since I was just setting it up for the first time.

Is it possible to decrypt the file and dump the raw xml so that I could remove that part with invalid characters to be able to recover the file?

KeeWeb
```
KdbxError: Error FileCorrupt: bad xml: This page contains the following errors:error on line 4 at column 1815: PCDATA invalid Char value 2
Below is a rendering of the page up to the first error.
```

KeePass
```
Failed to load the specified file!
'[]', hexadecimal value 0x02, is an invalid character. Line 4, position 1815
```

kpcli
```
not well-formed (invalid token) at line 4, column 1814, byte 6748 at /usr/lib/perl5/5.30/vendor_perl/XML/Parser.pm line 187.
```

Any help would be greatly appreciated because I just lost access to most of my accounts...

**Comment by antelle** [comment]
Hi! Yes, here you can open the file as xml, remove the bad character, and import it back: https://keeweb.info/tools/kdbx-to-xml.html - this page doesn't upload the file anywhere, it works in your browser, you can also download the page and run it locally to be sure.

The bug should be fixed of course, it's not good that we can damage the file this way. Broken kdbx example (empty password): [New.kdbx.zip](https://github.com/keeweb/keeweb/files/4694276/New.kdbx.zip).

**Comment by antelle** [comment]
It's the same a https://github.com/keeweb/keeweb/issues/910, I'll add more characters to the list, actually it should be a range `\x00-\x1F`.

**Comment by antelle** [comment]
added a fix in 96263c11ec0af4840f588b7de6e9be9739b00a8e

**Comment by ruskiyos** [comment]
Thank you! That was a lifesaver :)

Btw, here are the characters that broke it

```
:shû°”q+b9442357a589fed9Û†t\õxÃ`dº›ÞñHå'çdÍD@F&lt; ÄÑ‘
```

**Comment by ruskiyos** [comment]
Actually, it looks like the passwords and otp were hashed.
Is it possible to get the original values back?

**Comment by antelle** [comment]
Did you import the xml in keeweb? It should understand this format. They’re not hashed, but encrypted.

**Comment by ruskiyos** [comment]
By import, do you mean to click "Open" and select the XML file?
I tried going through keeweb and keepass, but when they import, everything shows up correctly except for the passwords - they are either hashed or incorrectly decypted... I tried base64 decodes on it but that didn't work either.

**Comment by antelle** [comment]
Yes, this button. Well, I guess this XML can't be imported without the kdbx then. Do you still have the original kdbx? I can make a version that will remove the bad character and open it.

**Comment by ruskiyos** [comment]
Yes. How do you want me to transfer it over?

**Comment by antelle** [comment]
Let's try it here: https://beta.keeweb.info/?up - try opening your kdbx there, and if it works, save it as kdbx: it will not contain broken characters.

**Comment by ruskiyos** [comment]
Awesome! That did it.
Thank you so much for your help!
