### ISSUE TITLE
Autotype stops when typing password

### ISSUE THREAD

**Issue by MarceloZapatta** [keeweb/keeweb#1521]
Autotype type normally email but when goes to password type only the first letter and breaks.
This occurs with any password entry.

"There was an error performing auto-type: Exit code 2"

KeeWeb v1.14.3 (489eb55, 2020-05-15)
Environment: electron v8.2.0
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) KeeWeb/1.13.1 Chrome/80.0.3987.158 Electron/8.2.0 Safari/537.36

Happens in a old/new database

No console logs

SO: Debian Buster 10

**Comment by antelle** [comment]
Hi! It's #1409, it's fixed in v1.15

**Comment by MarceloZapatta** [comment]
> Hi! It's #1409, it's fixed in v1.15

Thanks! Tested in dev and working!
