### ISSUE TITLE
An error called No Last-Modified header 

### ISSUE THREAD

**Issue by Summer-sn0w** [keeweb/keeweb#1523]
**Thanks for Developer's devotion** 
The program is very fantastic.but when i use the webdev, an error always occurs. I don't think it is advisable that use a relay server for webdev. It may case some problems. Such as me, in china, some political problems keep us away from some website or server. (In fact, we could still use the server but Software Customer Service tells me that the program didn't use webdev standard which lead to the problem).So i think it could change the way to connect the webdev . Such as local connect.

**Comment by antelle** [comment]
Hi! This seems to be a frequent request, we should probably add an option that will allow using webdav with servers that don't return Last-Modified header. This can of course lead to sync errors when the file is updated by two users simultaneously, but it can be said in settings as a warning.

**Comment by Summer-sn0w** [comment]
Very thanks, it a big problem which stop me using the keeweb.
ps: a little problem, it could add ailpay as donation? I am a high school student which hasn't access to VISA. The donation will not big. just as the saying gose "A light gift from a far conveys deep feeling."

**Comment by Summer-sn0w** [comment]
Very thanks, it a big problem which stop me using the keeweb.
ps: a little problem, it could add alipay as donation? I am a high school student which hasn't access to VISA. The donation will not big. just as the saying gose "A light gift from a far conveys deep feeling."

**Comment by antelle** [comment]
Thank you! I don't think however OpenCollective have AliPay now, I hope they will add it in future.
