### ISSUE TITLE
login fail

### ISSUE THREAD

**Issue by leipengkai** [keeweb/keeweb#1525]
打开文件时出错
KdbxError: Error FileCorrupt: bad xml: This page contains the following errors:error on line 24 at column 5398: PCDATA invalid Char value 8
Below is a rendering of the page up to the first error.

[打开文件时出错](https://i.loli.net/2020/06/05/l72fxGtcoEHL8Te.png)

**Comment by antelle** [comment]
Hi! For now you can restore your file on https://beta.keeweb.info/, in the next version it's already fixed.

**Comment by antelle** [comment]
Duplicates #1520

**Comment by leipengkai** [comment]
Thank you!

**Comment by leipengkai** [comment]
I have updated v1.15.3, but it still has the same problem. The error of opening the saved kdbx file is reported, and https://beta.keeweb.info/ can’t be used. Do I have to give up the original kdbx file, and I can still Use??? How about so many accounts before???? How to transfer????

**Comment by antelle** [comment]
Hi! Did you manage to restore the file on beta before? If so, how did you end up in the same situation again, maybe you have a string that you pasted? Now it shouldn’t create broken files like that.

**Comment by leipengkai** [comment]
No, I just wait for the new version to appear. I opened the file to enter the password, not paste it. The file has not been modified

**Comment by antelle** [comment]
The new version won’t restore it, but it won’t create such files instead. So, you haven’t restored the file? Do you want me to build the patched beta again so that you can do it?

**Comment by leipengkai** [comment]
What I can do now is to give me a modified version, and then create a new file with the latest version, and then add one by one, does this mean?

**Comment by antelle** [comment]
I'm very sorry but I don't understand your last message, please try to paraphrase it.
I've just updated beta.keeweb.info with the same fix as before, which is TEMPORARY. If you open your broken file on beta, you will be able to save it, and it will work with all versions of KeeWeb. Please let me know when you do it, then I'll remove the patch from there.

**Comment by leipengkai** [comment]
In beta.keeweb.info, I can now open my original file, but it can’t be opened in the production version of Keeweb. I want to transfer the data to the production version and use it. IIs it only possible to create a new file in the production version, and then copy the beta data one by one.Or do you provide a better solution?

**Comment by leipengkai** [comment]
I just saved a copy of beta.keeweb.info, and then it can be opened in the new version, thank you

**Comment by antelle** [comment]
That's what I meant, yes:
1. open your file on beta
2. save it
3. now you can use this file on production

**Comment by leipengkai** [comment]
Thank you so much for doing it for me.
