### ISSUE TITLE
[Yubikey] - make serialnumber check optional?

### ISSUE THREAD

**Issue by jivarson** [keeweb/keeweb#1527]
Yubikey-support in challengemode is working fine here, Win10 2004!

I would however like to ask if the check for serialnumber can be dropped, at least optionally?

The reason is i might write the same 'secret' to two yubikeys at the same time, so one key can act as either a backupkey locked away or to store them in two separate locations, (like at work and home).

In both KeePassXC and Keepass2android i was able to do this, do you check for serialnumber as a securitymeasure?

**Comment by antelle** [comment]
Hi! I'm not sure about this. I have two YubiKeys that I use, with slots programmed to different values. I would be very upset if a file would be locked with a different YubiKey and I would not be aware of it, but I understand how it can be helpful in your case.
Perhaps we need a setting for this. However I have a question: how would we select which one to use if there are several keys inserted?

**Comment by antelle** [comment]
Well, probably first it should select the one used to open the file, and then if different yubikeys are found, allow to choose which one to use.

**Comment by jivarson** [comment]
Honestly I haven't worked with multiple keys inserted at once. But like you say, perhaps you can use the serialnumber for tracking the stick only while it's being unlocked. And making it marked as selected key I database settings

**Comment by antelle** [comment]
Hm, do I understand it right that you would like to be able to select a YubiKey before the file is opened, and not after it? In this case you can click the small YubiKey icon and select the one you need.

**Comment by jivarson** [comment]
No, I just 'echoed' what you said. 

> it should select the one used to open the file, and then if different yubikeys are found, allow to choose which one to use.

As you say, you already have the functionality to select and remember yubikeys between openings.

keep using the S/N to pre-select the yubikey and to make it preferred while the database is opened, but don't _require_ it for each lock\unlock as it's the secret within a key that matters, not necessarily the public id of one specific yubikey.

To elaborate on the first post again. 
The requirement for a specific S/N also means that users have to export or backup the database without the yubikey-factor to ensure it can still be opened in case of loss.

By dropping the S/N-pinning I could instead or in addition backup the yubikey config or write it to several yubikeys. I wont have to save \backup the kdbx-database with reduced security, nor make make backups of it, One initial backup\replication of the yubikeys during config is enough.
Hope i make sense

* of course backup is always needed for a vault but you get me.

**Comment by antelle** [comment]
What I meant is, there's no S/N pinning in the file itself, it's saved only in the list of latest files and used while the file is open. So, imagine that I have two YubiKeys programmed to the same secret, as you describe. My primary YubiKey is not with me now and I'd like to open the file. In this case I can click the small YubiKey icon on the open screen twice and select the backup YubiKey that I'd like to use.
However what I don't understand, is why I would like to use another YubiKey when the file is already open. What's the use case for that?

**Comment by jivarson** [comment]
Hm, I misinterpreted the UI and also wrote two unique secrets instead of identical to my Yubikeys by mistake. clever. I blame the new Yubikey manager..

KeeWeb works as it should. I don't :-)
Sorry!

**Comment by antelle** [comment]
Well I can still see the use case for that, but let's see if anyone else comes to ask a similar question. YubiKey feature is new and there will be of course some troubles in the beginning. Thank you for trying it out!
