### ISSUE TITLE
OTP field showing as URI, not code

### ISSUE THREAD

**Issue by Nu11u5** [keeweb/keeweb#1528]
The OTP field is now showing as the URI value (protected) instead of the OTP code.  The webapp was uninstalled and data reset and the issue persists.

When reproduced on a different device the webapp was a prior version which prompted to update.  Before the update the OTP fields worked correctly, and after the update the issue appeared.

**Working versions:**

> KeeWeb v1.14.3 (489eb55, 2020-05-15)
Environment: web
User-Agent: Mozilla/5.0 (iPhone; CPU iPhone OS 13_4_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.1 Mobile/15E148 Safari/604.1

**Issue versions:**

> KeeWeb v1.15.0 (3001afd, 2020-06-06)
Environment: web
User-Agent: Mozilla/5.0 (iPhone; CPU iPhone OS 13_4_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.1 Mobile/15E148 Safari/604.1

> KeeWeb v1.15.0 (3001afd, 2020-06-06)
Environment: web
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.97 Safari/537.36

**Comment by antelle** [comment]
Hi! Could you please share an example uri?

**Comment by antelle** [comment]
Okay, I see how it can be repeated

**Comment by antelle** [comment]
Fixed on [beta.keeweb.info](https://beta.keeweb.info)

**Comment by KaKi87** [comment]
Hello, would it be possible to either make a stable release as soon as possible for this specific fix or revert the changes which created the bug ?
This is kinda critical.
Thanks

**Comment by antelle** [comment]
Merged it, the release is building...

**Comment by KaKi87** [comment]
Very nice, thanks !

**Comment by antelle** [comment]
The release is complete: https://github.com/keeweb/keeweb/releases/tag/v1.15.1
