### ISSUE TITLE
Portable mode not working properly

### ISSUE THREAD

**Issue by harvald** [keeweb/keeweb#1530]
I'll describe few bugs together, because they are closely related.

Bugs:
1. If create file as described in [docs](https://github.com/keeweb/keeweb/wiki/Configuration#portable) and run program, then program run with grey background and nothing in it (no buttons, nothing).
2. Even in portable mode, program creates folders in default location besides one specified in keeweb-portable.json
3. Program creates only last part of path specified in keeweb-portable.json. If more than last part is not-existing then program will crash.
4. Path under windows normally should use "\\" as separator, not "/". It can be used here but in escaped fashion "\\\\", so some info about this should be added to docs.

**Comment by antelle** [comment]
Hi! Thanks, please see the answers below:
1. do you see anything interesting if you start it from terminal?
2. I need more details here: what is your OS, where is KeeWeb and the config located, and what's inside the config?
3. this one is clear, will be fixed
4. that's what should be in JSON, but I've added a note to the wiki

**Comment by harvald** [comment]
Ad. 1 Nothing in terminal, but I think source of this issue is "#" in path of KeeWeb.
Ad. 2 Windows 7 x64. I've deleted "c:\\Users\\<user>\\AppData\\Roaming\\KeeWeb" and had nothing under dir "config" specified in keeweb-portable.json. So I understand there is no configuration. KeeWeb in on pendrive under "h:\\#Programy\\KeeWeb", and when I ran it, it creates dir under "c:\\Users\\<user>\\AppData\\Roaming\\KeeWeb"

**Comment by antelle** [comment]
1. does it work without `#`?
2. do I understand it right that the config was empty? in this case it works as expected.

**Comment by harvald** [comment]
1. yes.
2. yes in was empty, but set for portable mode, so I expected configuration creation only in chosen directory.

**Comment by antelle** [comment]
It won’t have any effect if it’s empty, so it’s fine.
