### ISSUE TITLE
Desktop app 1.15.0 & 1.15.1 win x64 won't work

### ISSUE THREAD

**Issue by leolivier** [keeweb/keeweb#1532]
I installed the versions Keeweb-1.15.0.win.x64.exe (and same for 1.15.1) and they won't start !
 
So I reinstalled 1.14.3 and it started working again.

I tried this several times back and forth. Always the same...

No logs as the app won't start...

**Comment by antelle** [comment]
Hi! This can happen, there's a new electron and some native modules in this version.
How exactly it doesn't start, what do you see? Does it crash, or shows a blank screen?

**Comment by leolivier** [comment]
Actually, I don't see anything at all!
I tried running from a Windows terminal. It just goes back to the prompt with absolutely no message.

**Comment by antelle** [comment]
You mean, it immediately exists without displaying any UI?
Which version of Windows is that?

**Comment by leolivier** [comment]
Yes, that's exactly what I mean.
I'm on windows 10 insider version build 19631.1

**Comment by antelle** [comment]
Weird, that's what I have in my virtualbox as well. Would you mind running a test build with more logging?

**Comment by leolivier** [comment]
Yes, tell me

**Comment by antelle** [comment]
There are also some logging flags in Electron. Let's try these two on the current version, maybe there will be some hint?
```
--enable-logging -v=10
```

**Comment by antelle** [comment]
Here's an overview of options: https://www.electronjs.org/docs/api/command-line-switches

**Comment by leolivier** [comment]
Nothing more... no log at all

**Comment by antelle** [comment]
I see, I made a built that should print more: https://beta.keeweb.info/KeeWeb-win32-x64.zip, let's see if this one starts

**Comment by leolivier** [comment]
Sorry, went to sleep last night.
I gave the new build a try this morning and it's exactly the same.
Nothing shows and no trace... :/

**Comment by antelle** [comment]
That's weird! It means, it doesn't even come to running our code. Is there anything interesting in the system event log?

**Comment by leolivier** [comment]
I can see warnings on some certificates about to expire (partly in French) but I don't think it's linked:

_Nom du journal :Application
Source :       Microsoft-Windows-CertificateServicesClient-AutoEnrollment
Date :         09/06/2020 19:38:25
ID de l’événement :64
Catégorie de la tâche :Aucun
Niveau :       Avertissement
Mots clés :    Classique
Utilisateur :  N/A
Ordinateur :   Bagheera
Description :
Le certificat de Système local avec l’empreinte numérique xxxxxx est sur le point d’expirer ou a déjà expiré.
XML de l’événement :
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Microsoft-Windows-CertificateServicesClient-AutoEnrollment" Guid="{F0DB7EF8-B6F3-4005-9937-FEB77B9E1B43}" EventSourceName="AutoEnrollment" />
    <EventID Qualifiers="32768">64</EventID>
    <Version>0</Version>
    <Level>3</Level>
    <Task>0</Task>
    <Opcode>0</Opcode>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2020-06-09T17:38:25.9624153Z" />
    <EventRecordID>2831</EventRecordID>
    <Correlation />
    <Execution ProcessID="0" ThreadID="0" />
    <Channel>Application</Channel>
    <Computer>Bagheera</Computer>
    <Security />
  </System>
  <EventData>
    <Data Name="Context">Système local</Data>
    <Data Name="ObjId">70 cb 38 11 08 47 fc a1 da 2b fb 20 38 b1 44 01 59 f0 94 2c</Data>
  </EventData>
</Event>_

**Comment by antelle** [comment]
I don't think it's connected either. Is it possible to test if vanilla electron runs properly? Something like this:
```
npm i electron@9.0.2
./node_modules/.bin/electron
```

**Comment by antelle** [comment]
Then, if it works, try running KeeWeb using the Electron binary:
```
Electron.exe path-to-keeweb\resources\app.asar
```
Electron.exe should be in `node_modules/electron`.

**Comment by antelle** [comment]
You can also find electron here, if you don't have node.js installed: https://github.com/electron/electron/releases/tag/v9.0.2

**Comment by leolivier** [comment]
Does not work neither... same, no GUI, no trace...

**Comment by antelle** [comment]
Did I get it right that electron doesn't work, even without keeweb?

**Comment by leolivier** [comment]
I ran the command 
path/electron.exe path2/resources/app.asar
And that shows nothing.
How can I know if electron is working or not?

**Comment by antelle** [comment]
Just run electron.exe without any arguments, from the file explorer

**Comment by leolivier** [comment]
nothing happens...

**Comment by antelle** [comment]
This means we I won't be able to fix it. What happens for [9.0.3](https://github.com/electron/electron/releases/tag/v9.0.3) version?

**Comment by leolivier** [comment]
Same...

**Comment by antelle** [comment]
Do you have any anti-virus software installed? I don't see any other reports like this, however the Windows version has been downloaded more than 1000 times. Perhaps you can open an issue in the [electron repo](https://github.com/electron/electron)? I don't see anything like this there either.

**Comment by leolivier** [comment]
I have McAfee installed as my anti-virus. free version provided with my Dell laptop...
I will try to create an issue in the electron repo (already checked that there was nothing like this in the open issues)  but why 1.14.3 version is working? Is it a totally different version of electron?

**Comment by antelle** [comment]
Yes, it's [built on v8.2.5](https://github.com/keeweb/keeweb/blob/v1.14.3/package.json#L30).

**Comment by leolivier** [comment]
Ok, I'll create an issue on electron...
To be sure, do you think I can download the 8.2.5 version of electron and run the 1.15.1 app.asar?

**Comment by antelle** [comment]
You can try, but it will most likely crash on loading native modules. I would suggest that you stick to v1.14 while there's no fix for Electron 9.

**Comment by leolivier** [comment]
Ok. I downloaded electron 8.3.1 and ran it "standalone" and it opened the electron window so it's clearly linked to 9.x.

**Comment by leolivier** [comment]
https://github.com/electron/electron/issues/24035

**Comment by antelle** [comment]
Thank you! Most likely the maintainers will come with additional questions, that's why I didn't want to create it myself.

**Comment by antelle** [comment]
The reaction was fast! Actually I found that duplicated issue before, however it says it crashed, so I thought it was different.

**Comment by leolivier** [comment]
Maybe you should advertise that the latest version of keeweb might not work on Windows10 due to this problem...

**Comment by antelle** [comment]
There's a build mentioned in [this comment](https://github.com/electron/electron/issues/23841#issuecomment-641010204), you can also give it a try to see if it works.
Well I'm not sure about that. It looks like it doesn't work with a very particular setup, because I don't see any other comments / reports.

**Comment by leolivier** [comment]
This build works! I was able to run keeweb 1.15.1 with it (through the command line electron app.asar)

**Comment by antelle** [comment]
Status update: I see that the issue has been resolved and the fix is merged to v9 branch. Once new electron is released, it will be updated in KeeWeb v1.15.x.

**Comment by leolivier** [comment]
Great, thanks @antelle

**Comment by keesveerman** [comment]
Just tried to install 1.15.3 64bit on win10enterprise2004 and it wont install. Tried as normal user, and with 'run as admin'

message shown is:
This app cant run on your pc
To find a version for your Pc, check with the software publisher

**Comment by leolivier** [comment]
@keesveerman I don't think this is linked to the current issue, you should open another one.
But you're right, I have the same problem... (tested on another PC)

**Comment by antelle** [comment]
That's strange, it shows a message when run from a zip archive, but it works if launched after installation?

**Comment by leolivier** [comment]
On my side, I didn't try to install it from the package, only unzipped the 1.15.3 .zip archive (on another PC than the one on which 1.15 does not work) and tried to launch keeweb.exe. And, indeed, I got the above message translated in French. 
Then I downloaded the 1.15.2 version - zip archive again -  and this one worked like a breeze...

**Comment by antelle** [comment]
They have different (minor) Electron version. 🤔 
What happens if you run Electron 9.0.2 and 9.0.3 respectively?

**Comment by leolivier** [comment]
Sorry, unable to check on the other PC during the weekend

**Comment by antelle** [comment]
Electron is released, the fix is coming today

**Comment by leolivier** [comment]
:+1: Awesome, thanks for the great support @antelle
Using Keeweb almost everyday, never disappointed!

**Comment by antelle** [comment]
The release is published: https://github.com/keeweb/keeweb/releases/tag/v1.15.4
