### ISSUE TITLE
autotype password on Ubuntu broken

### ISSUE THREAD

**Issue by jivarson** [keeweb/keeweb#1533]
In 1.15.1 autotype is broken.
Ubuntu 19.04, xdotool 3.20160805.1

I know xdotool is troublesome but it's been working nice for me, but this i think is a keeweb glitch.
Autotyping username is fine,

> 2020-06-09T09:48:44.477Z [auto-type] Entry selected {entry: Proxy, sequence: "{USERNAME}"}
> index.html:1 2020-06-09T09:48:44.484Z [auto-type] Hide window
> index.html:1 2020-06-09T09:48:44.618Z [auto-type] Getting window info
> index.html:1 2020-06-09T09:48:44.630Z [launcher] spawn xdotool: 0, 12ms
> Forums - Google Chrome
> 83886081
> index.html:1 2020-06-09T09:48:44.631Z [auto-type] Window info 83886081 forum - Google Chrome null
> index.html:1 2020-06-09T09:48:44.631Z [auto-type] Active window matches
> index.html:1 2020-06-09T09:48:44.631Z [auto-type] Start {USERNAME}
> index.html:1 2020-06-09T09:48:44.632Z [auto-type] Parsed [op:USERNAME]
> index.html:1 2020-06-09T09:48:44.632Z [auto-type] Resolved [*******]
> index.html:1 2020-06-09T09:48:44.866Z [launcher] spawn xdotool: 0, 233ms
> index.html:1 2020-06-09T09:48:44.867Z [auto-type] Complete 235ms

 but when password field is interpreted, events gets repeated several times (14 x)

> 2020-06-09T09:48:50.851Z [auto-type] Entry selected {entry: Proxy, sequence: "{PASSWORD}"}
> index.html:1 2020-06-09T09:48:50.854Z [auto-type] Hide window
> index.html:1 2020-06-09T09:48:50.966Z [auto-type] Getting window info
> index.html:1 2020-06-09T09:48:50.980Z [launcher] spawn xdotool: 0, 13ms
> Forum- Google Chrome
> 83886081
> index.html:1 2020-06-09T09:48:50.980Z [auto-type] Window info 83886081 Forum - Google Chrome null
> index.html:1 2020-06-09T09:48:50.980Z [auto-type] Active window matches
> index.html:1 2020-06-09T09:48:50.980Z [auto-type] Start {PASSWORD}
> index.html:1 2020-06-09T09:48:50.981Z [auto-type] Parsed [op:PASSWORD]
> index.html:1 2020-06-09T09:48:50.981Z [auto-type] Resolved [[*,*,*,*,*,*,*,*,*,*,*,*,*,*]]
> index.html:1 2020-06-09T09:48:51.119Z [launcher] spawn xdotool: 0, 138ms
> index.html:1 2020-06-09T09:48:51.224Z [launcher] spawn xdotool: 0, 105ms
> index.html:1 2020-06-09T09:48:51.360Z [launcher] spawn xdotool: 0, 136ms
> index.html:1 2020-06-09T09:48:51.508Z [launcher] spawn xdotool: 0, 147ms
> index.html:1 2020-06-09T09:48:51.620Z [launcher] spawn xdotool: 0, 112ms
> index.html:1 2020-06-09T09:48:51.767Z [launcher] spawn xdotool: 0, 146ms
> index.html:1 2020-06-09T09:48:51.923Z [launcher] spawn xdotool: 0, 156ms
> index.html:1 2020-06-09T09:48:52.071Z [launcher] spawn xdotool: 0, 148ms
> index.html:1 2020-06-09T09:48:52.231Z [launcher] spawn xdotool: 0, 159ms
> index.html:1 2020-06-09T09:48:52.374Z [launcher] spawn xdotool: 0, 143ms
> index.html:1 2020-06-09T09:48:52.487Z [launcher] spawn xdotool: 0, 112ms
> index.html:1 2020-06-09T09:48:52.658Z [launcher] spawn xdotool: 0, 171ms
> index.html:1 2020-06-09T09:48:52.826Z [launcher] spawn xdotool: 0, 167ms
> index.html:1 2020-06-09T09:48:52.997Z [launcher] spawn xdotool: 0, 171ms
> index.html:1 2020-06-09T09:48:52.997Z [auto-type] Complete 2017ms

where the character 'p' seems to be the additional spawn?

**Comment by antelle** [comment]
Hi! What's auto-typed instead of the correct password?

**Comment by jivarson** [comment]
p

**Comment by antelle** [comment]
I see, this is #1409

**Comment by antelle** [comment]
The fix is released, please give it a try!

**Comment by jivarson** [comment]
Indeed. Works like a charm!
Thanks!
