### ISSUE TITLE
Won't open file from Dropbox on Win10 - v1.15.2

### ISSUE THREAD

**Issue by lifejw** [keeweb/keeweb#1535]
I am using KeeWeb on Win10.
Version: 1.15.2
Won't open file from Dropbox:

Log Error says:
```
[ERROR] 2020-06-10T13:32:06.490Z [launcher] spawn error: ykman, 9ms Error: spawn ykman ENOENT
[ERROR] 2020-06-10T13:32:06.491Z [launcher] spawn ykman: -4058, 9ms
```

KeeWeb v1.15.2 (819b10e, 2020-06-09)
Environment: electron v9.0.3
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) KeeWeb/1.15.2 Chrome/83.0.4103.100 Electron/9.0.3 Safari/537.36

**Comment by antelle** [comment]
It's released: https://github.com/keeweb/keeweb/releases/tag/v1.15.3

**Comment by lifejw** [comment]
Great Job!
