### ISSUE TITLE
Keeweb won't start because of "The name org.freedesktop.secrets was not provided by any .service files"

### ISSUE THREAD

**Issue by JochenDiekenbrock** [keeweb/keeweb#1536]
**Describe the bug**
Keeweb 1.15.2 on Ubuntu 19.10 does not start, showing an error popup "org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.secrets was not provided by any .service files"

**To Reproduce**
1. I upgraded from Keeweb 1.14.2. to 1.15.2 on Ubuntu 19.10.
2. Tried to start the new version of Keeweb
3. error message was shown

**to resolve the problem**
Install the gnome-keyring with "sudo apt install gnome-keyring"

**Expected behavior**
It should start :-)
Should the .deb file contain a dependency to gnome-keyring?

**Environment**
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) KeeWeb/1.15.2 Chrome/83.0.4103.100 Electron/9.0.3 Safari/537.36

**Logs**
Sorry, no logs, because I resolved the problem already

**Comment by antelle** [comment]
Hi! I'm not sure, would it cause errors on other desktop environments?

**Comment by JochenDiekenbrock** [comment]
I'm outside my area of knowledge here, so you're probably right, directly depending on gnome-keyring is not a good idea.

Perhaps there is some kind of generic dependency to a secrets-service that resolves depending on the desktop environment?

**Comment by antelle** [comment]
It's probably `libsecret`: https://github.com/atom/node-keytar#on-linux. But I wonder if it's enough. I'll try installing a fresh Ubuntu because for me it didn't give any error when I tried it.

**Comment by JochenDiekenbrock** [comment]
I was able to reproduce it. I did a default install of kubuntu-19.10-desktop-amd64 in a Virtualbox, downloaded Keeweb 1.15.3 and installed it. When it started, the same error occured.

Next, I installed libsecrets (sudo apt-get install libsecret-1-dev).  Error still occurs. One of the suggested packages was debian-keyring, so I installed that (sudo apt-get install debian-keyring). The error still occured.

Since I'm in the KDE environment, I checked that KWalletManager is installed, it was installed by default. Running out of more ideas, I installed gnome-keyring next. After this, keeweb started and a popup was displayed requesting the password for a new keyring.

Here's a screenshot of sudo apt-get install libsecret-1-dev:

![install-libsecret](https://user-images.githubusercontent.com/1625222/84510443-6918f700-acc5-11ea-9889-c79936351f69.png)

I took a disk snapshot after the default install so I can easily go back and do other tests that may help you to find the problem. Feel free to close the issue at any time. I just wanted to leave the information for other people googling for the error find help.

Thank you for this great tool and you timely support! Great job!

**Comment by antelle** [comment]
*K*ubuntu, I see, that's the reason. Cool, I can indeed repeat it on a fresh kubuntu, I'll try adding a dependency. Looks like gnome-keyring is what will work on KDE as well.

**Comment by antelle** [comment]
Just added a dependency and verified on kubuntu, it seems to be working. The release with it is coming soon, once electron is released.

**Comment by antelle** [comment]
The release is published: https://github.com/keeweb/keeweb/releases/tag/v1.15.4

**Comment by JochenDiekenbrock** [comment]
This release fixed the issue on my test system as well. Thanks again @antelle !

**Comment by vetko** [comment]
I have the same issue on a KDE system, but I wouldn't prefer to install **gnome**-keyring on **KDE**.
Would there be another solution, e.g. using KWallet on KDE?
Or could it be made an **optional dependency**?

May I ask why a credentials storage is needed for KeeWeb in the first place? KeeWeb supposed to be **the** credentials storage, shouldn't rely on another one, I guess...

**Comment by JochenDiekenbrock** [comment]
I had the issue on KUbuntu, which had KWallet(Manager) installed by default. That was not sufficient.

**Comment by antelle** [comment]
@vetko you can check [node-keytar](https://github.com/atom/node-keytar) package, maybe they have more details about what can be used to access secrets.
> why a credentials storage is needed for KeeWeb in the first place?

This is used to encrypt KeeWeb configs. Before v1.15 any app running even without superuser privileges could modify configs, change the way files are backed up, etc... This is not very cool, now it's solved by adding a secret to the keychain, which controls access per app.
