### ISSUE TITLE
OTP broken

### ISSUE THREAD

**Issue by DSDeniso** [keeweb/keeweb#1537]
**Describe the bug**
My KeeWeb client does not show the calculated OTP's, but just the secret. When trying to re-add, I get a dialog with the text "TypeError: Class contructor a cannot be invoked without 'new'"

**To Reproduce**
1. Add OTP to an entry in database
2. Paste the code from clipboard
3. Get frustrated with the error message

**Expected behavior**
To see the calculated OTP and actually be able to add new ones.

**Screenshots**
<img width="461" alt="Screenshot 2020-06-12 at 15 47 22" src="https://user-images.githubusercontent.com/5363898/84510241-2bb46980-acc5-11ea-8e0f-ea368802a40f.png">

**Environment**
Packages app for macOS

**Kdbx File**
With both existing Dropbox Argon4 database and brand new one.

**Logs**
<img width="875" alt="Screenshot 2020-06-12 at 15 57 46" src="https://user-images.githubusercontent.com/5363898/84510579-9bc2ef80-acc5-11ea-9f8b-7fa8582f81c0.png">

**Comment by antelle** [comment]
Hi! Which KeeWeb version is that?

**Comment by DSDeniso** [comment]
Hi @antelle 

I'm on version 1.15.5 (62ea631) :)

Best
Deni

**Comment by antelle** [comment]
Does it repeat on the demo db?

**Comment by antelle** [comment]
Strange, I can't reproduce it. Could you please share your steps, how you add the code?

**Comment by DSDeniso** [comment]
Sure. I do what I've always done. I took a screenshot from Google of the OTP seed and copied that file to the clip board and pasted it to the app.

I can't think of how to elaborate more than that.

**Comment by antelle** [comment]
I'm a bit puzzled. Let's try it this way:
1. create a code [here](https://www.the-qrcode-generator.com/) using this url: `otpauth://totp/Example:alice@google.com?secret=JBSWY3DPEHPK3PXP&issuer=Example`, it should be something like this: <img width="186" alt="Screen Shot 2020-06-18 at 17 15 03" src="https://user-images.githubusercontent.com/633557/85038776-484e1700-b187-11ea-82e2-ebac9702c3ad.png">
2. go to app.keeweb.info and create a new entry in a new db
3. paste the code

What happens for me: https://imgur.com/a/ocibdao

**Comment by DSDeniso** [comment]
Hi @antelle 

That works. The code I originally tried to add came from Google, so we can get to the bottom of what's actually wrong. It might well be Google.

**Comment by antelle** [comment]
I assume, you haven't used the code as OTP? Could you please paste it here to check why it doesn't work?
