### ISSUE TITLE
Cannot execute installer on Windows 10 x64

### ISSUE THREAD

**Issue by rik1599** [keeweb/keeweb#1539]
**Describe the bug**
When I execute the installer for the latest version (1.15.4) in Windows 10 1909 x64, it says "Unable to execute this app in your PC"

**To Reproduce**
1. Dowload the executable from https://github.com/keeweb/keeweb/releases/download/v1.15.4/KeeWeb-1.15.4.win.x64.exe
2. Double click on it

**Comment by antelle** [comment]
Hi! What does the error look like? Is there anything interesting in system logs?

**Comment by antelle** [comment]
I cannot find anything in Google with this error text, perhaps it was phrased differently?

**Comment by rik1599** [comment]
Yes, my PC is in Italian so I didn't know the exact english traslation.
The correct error is "This app can't run on your pc". Sorry

**Comment by antelle** [comment]
I see, thanks, something happened to code signing and it stopped working, I'll look into it soon.

**Comment by antelle** [comment]
Fixed it in 0c38b5b9f1f357ea1ca14a73a9477ed37152e0c4, the release will be built today. For now you can use this build if you need it: https://github.com/keeweb/keeweb-ci-sandbox/releases/tag/v1.15.4

**Comment by leolivier** [comment]
Hi @antelle 
I confirm I had the same problem and the build above fixes it (as well as the #1532 issue, yeah!!!)

**Comment by antelle** [comment]
The release is published: https://github.com/keeweb/keeweb/releases/tag/v1.15.5
