### ISSUE TITLE
[Feature Request] Copy / Share primary fields

### ISSUE THREAD

**Issue by dmytrobanasko** [keeweb/keeweb#154]
Hello, 

A lot of times I need to share record details(fields by default?) like following (templates?): 

> h: example.com
> u: user
> p: password

or maybe like this: 

> username:password@example.com

Is it possible and **secure** to get such thing available (under "more..." list for example) ? What do you think ?

Thank you

**Comment by antelle** [comment]
You mean entry templates, they [will be](https://github.com/antelle/keeweb/wiki/TODO#future) implemented. I've not yet made a mockup for now, but have already reviewed implementations in 1Password, LastPass and KeePass and came up with the following:
- when adding a new entry, there will be either additional dropdown, or additional sub-options under `+` &rarr; `Entry` menu item 
- simple click on entry creation item will still work and create an entry without a template
- in entry details, there will be `more...` &rarr; `Fill from template` menu item with templates inside it
- somewhere there will be an option to edit and add templates (maybe in template chooser menu? not sure yet)
- features that will not be implemented (like trash folder): 
 - changing template folder (but if it's already set, templates will be read from and added to it)
 - adding or removing template folder (will be added under the hood, when you add the first template

**Comment by isbad** [comment]
Nope, I'm talking about copy/share important data from record. Right now it takes few "clicks": 
copy/paste host + copy/paste username + copy/paste password to share these details. 
But not sure if it's really needed and secure

**Comment by antelle** [comment]
You mean copying to a new entry, or existing one? If new, we can create `more...` &rarr; `Create a copy`, but for existing, hm... no ideas for now.

**Comment by isbad** [comment]
I mean UI action just to share access to someone - send by IM or email (by copiing some fields to clipboard). Right now I need to copy and paste for each needed field.

As for templates, I mean templating share format ("what you see when you paste"). Sometimes you need to share `user:pwd@host` or `user / password`. But now I understand that it's not so usefull

**Comment by antelle** [comment]
Got it. This is like Print menu which will put entry details to clipboard, with fields and print settings defined somehow. The way I see it: `more...` &rarr; `Print` which will open print settings where you can change some defaults, e.g. exclude or include password and other fields from printing, and output the result in copy-friendly formats.
It will be also useful when multiple selection and bulk operations are implemented, so printing several entries will result in large table with all of them.

**Comment by isbad** [comment]
Sound great, that's definitely what I'm looking for
Thank you!

**Comment by kasoban** [comment]
Bonus thought: Could the print view / copy to clipboard content be structured in a way that would in turn allow importing entries from clipboard in said structure? That way the other party would be able to copy the pasted text and directly create an entry from that.
The obvious technical choice would be exchanging an XML export, but that would of course go against the idea of the human readable output which was the intention for this ticket.

**Comment by antelle** [comment]
Yes, if it is table-like export, it will be quite easy to parse it back.

**Comment by mitchellknight** [comment]
@antelle — Does this mean you plan to include a print feature in to future releases? I'd love to be able to print a PDF backup of all entries (perhaps with the native OS X print dialog).

**Comment by antelle** [comment]
// Milestone: v1.x
yes, it's planned

**Comment by antelle** [comment]
Now it's already possible to export the whole file as HTML. v1.11 will also allow copying entries to clipboard in HTML and TXT format:

<img width="1072" alt="image" src="https://user-images.githubusercontent.com/633557/64909882-abe77780-d711-11e9-98a4-673453a8320b.png">

What will be copied:

<img width="489" alt="image" src="https://user-images.githubusercontent.com/633557/64909906-d5080800-d711-11e9-9512-f0ac46d63ebc.png">

For creating new entries based on other entries, please use templates.
