### ISSUE TITLE
Theme sometimes destroyed

### ISSUE THREAD

**Issue by Fruchuxs** [keeweb/keeweb#1542]
Hello,
I use an own theme for keeweb (https://fruchuxs.dev/keeweb/themes/yant). Since 1.15.x my theme is not loaded ("invalid") after keeweb start. If I remove the plugin and add it again, the theme works fine.

**Comment by antelle** [comment]
Hi! Is it in the webapp or desktop? Which error do you see?

**Comment by Fruchuxs** [comment]
Hello again,
there is just a text "invalid" behind my email address.

With flat-blue theme:
![image](https://user-images.githubusercontent.com/5205672/84741479-72e57780-afaf-11ea-9d9b-6bd9ae8c353b.png)

After reinstall:
![image](https://user-images.githubusercontent.com/5205672/84741601-9c060800-afaf-11ea-962b-fe940416e8f9.png)

And now restart keeweb:
![image](https://user-images.githubusercontent.com/5205672/84741682-b4762280-afaf-11ea-82e1-e847b2efb8ee.png)

![image](https://user-images.githubusercontent.com/5205672/84741718-c2c43e80-afaf-11ea-873c-610ac82be3cb.png)

I use the desktop app.

**Comment by antelle** [comment]
It's #1254, for now there's no way to have a persistent plugin in the desktop version.
