### ISSUE TITLE
Cannot save file with YubiKey

### ISSUE THREAD

**Issue by stevegore** [keeweb/keeweb#1544]
**Describe the bug**
Attempting to use a YubiKey as part of the master key prevents saving.

**To Reproduce**
1. Go to save settings
2. Select Yubikey from the list
3. Click Save
4. No prompt to touch my Yubikey is shown. File does not save. Error displays: Sync error: [Object object]

 I've tried this with 2 YubiKeys. The application has been granted full Input Monitoring permissions.

**Expected behavior**
I should be prompted to touch my Yubikey. It should then save.

**Screenshots**

**Environment**
Your user-agent (from Settings/Help section)

```
KeeWeb v1.15.5 (62ea631, 2020-06-13)
Environment: electron v9.0.4
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_5) AppleWebKit/537.36 (KHTML, like Gecko) KeeWeb/1.15.5 Chrome/83.0.4103.104 Electron/9.0.4 Safari/537.36
```

Output from ykman  info

```
Device type: YubiKey 5 NFC
Serial number: XXXXXX
Firmware version: 5.2.4
Form factor: Keychain (USB-A)
Enabled USB interfaces: OTP+FIDO+CCID
NFC interface is enabled.

Applications	USB    	NFC
OTP     	Enabled	Enabled
FIDO U2F	Enabled	Enabled
OpenPGP 	Enabled	Enabled
PIV     	Enabled	Enabled
OATH    	Enabled	Enabled
FIDO2   	Enabled	Enabled
```

**Kdbx File**
[github issue.zip](https://github.com/keeweb/keeweb/files/4789677/github.issue.zip)

**Logs**
Attached
[keeweb.log](https://github.com/keeweb/keeweb/files/4789671/keeweb.log)

**Comment by stevegore** [comment]
FWIW my YubiKey does light up, expecting to be touched. But Keeweb gives up on the whole thing before I get to touch it. And there's definitely no prompt.

**Comment by antelle** [comment]
Hi! What happens if you run these commands:
```
ykchalresp -1 -x aa
ykinfo -a
```

**Comment by stevegore** [comment]
Looks like the problem might be with `ykman`:

```serial: 11163081
serial_hex: aa55c9
serial_modhex: llggrk
version: 5.2.4
touch_level: 517
programming_sequence: 1
slot1_status: 1
slot2_status: 0
vendor_id: 1050
product_id: 407
Yubikey core error: timeout
2020-06-18T08:50:58+1000 INFO [ykman.logging_setup.setup:58] Initialized logging for ykman version: 3.1.1
2020-06-18T08:50:58+1000 DEBUG [ykman.descriptor.Descriptor.open_device:86] transports: 0x1, self.mode.transports: 0x7
2020-06-18T08:50:58+1000 DEBUG [ykman.descriptor.open_device:91] Opening driver for serial: None, type: YUBIKEY.YK4, mode: OTP+FIDO+CCID
2020-06-18T08:50:58+1000 DEBUG [ykman.descriptor.open_device:94] Attempt 1 of 10
2020-06-18T08:50:58+1000 DEBUG [ykman.driver_otp.open_devices:224] Success in opening key at position 0
2020-06-18T08:50:58+1000 DEBUG [ykman.descriptor.open_device:97] Found driver: <ykman.driver_otp.OTPDriver object at 0x101f8e670>, key_type: YUBIKEY.YK4, mode: OTP+FIDO+CCID
2020-06-18T08:50:58+1000 DEBUG [ykman.device.__init__:198] Read config from device...
2020-06-18T08:50:58+1000 DEBUG [ykman.device.__init__:200] Success!
2020-06-18T08:50:58+1000 DEBUG [ykman.device.__init__:289] Identified YubiKey 5
2020-06-18T08:50:58+1000 DEBUG [ykman.otp.calculate:342] Sending a challenge to the device. Slot 1. Attempt 1. Wait for touch is False.
2020-06-18T08:50:59+1000 DEBUG [ykman.otp.calculate:355] Got ykpers error 4, b'timeout' as expected.
2020-06-18T08:50:59+1000 DEBUG [ykman.driver_otp.close:203] Close <ykman.driver_otp.OTPDriver object at 0x101f8e670>
Usage: ykman otp calculate [OPTIONS] [1|2] [CHALLENGE]
Try "ykman otp calculate -h" for help.

Error: Failed to calculate challenge.
2020-06-18T08:50:59+1000 DEBUG [ykman.driver_otp.__del__:208] Destroy <ykman.driver_otp.OTPDriver object at 0x101f8e670>
```

**Comment by jivarson** [comment]
I got the same with my Yubikey NEO (the first generation of NFC-enabled keys).
I _never_ got the issue with my Yubikey 4 nor my Yubikey Edge.

Í can hear Windows 10 detecting a device change when the keeweb challenge starts, so to me it seems that the Yubikey change it's state somehow. Initially thought it was my old yubikey key that was messed up, but perhaps its a NFC-thing (or a specific slot-configuration we made to it?)

**Comment by antelle** [comment]
@stevegore that looks weird, but since neither `ykchalreso` nor `ykman` can calculate the OTP, we won't be able to do it either. It looks like the yubikey is not programmed properly though, are you sure it's exactly Challenge-Response, and not Yubico OTP, what is programmed to slot 1? What happens if you write it to slot 2? For me it behaves exactly as your describe if I'm trying to use Yubico OTP as if it was Challenge-Response OTP.

**Comment by antelle** [comment]
This is not actionable in KeeWeb so closing the issue, but we can still discuss why it doesn't work.

**Comment by antelle** [comment]
There's one more thing, let's check so-called capabilities, maybe it contains a hint:
```
ykinfo -c 
```
for me it gives:
```
2e0102023f0302023f020400a2bf9304010105030502040602000007010f0801000d02023f0e0202230a01000f0100
```
Which is read as:
```
2e length
01 tag = USB_SUPPORTED
02 length
023f
03 tag = 0x03
02 length
023f
02 tag = SERIAL
04 length
00a2bf93 = my serial
04 tag = FORMFACTOR
01 length
01 FORM_FACTOR.USB_A_KEYCHAIN
05 tag = VERSION
03 length
050204 v5.2.4
06 tag = 0x06
02 length
0000
07 tag = CHALRESP_TIMEOUT
01 length
0f timeout = 15s <---- this is the value we're interested in
08 tag = DEVICE_FLAGS
01 length
00 flags
0d tag = NFC_SUPPORTED
02 length
023f
0e tag = NFC_ENABLED
02 length
0223
0a tag = CONFIG_LOCK
01 length
00
0f end
01 length
00
```

**Comment by stevegore** [comment]
Totally agree that this is not a KeeWeb issue. 

Thanks for that, unfortunately it looks like my timeout is the same. Key 1:

```
260102023f0302023f020400aa55c904010505030502040602000007010f0801000a01000f010c
```

Key 2:

```
2e0102023f0302023f020400a2916d04010105030502040602000007010f0801000d02023f0e02023f0a01000f0100
```

Think I'll raise an issue on the `yubikey-manager` repo.

Thank you!

**Comment by jivarson** [comment]
> Totally agree that this is not a KeeWeb issue.
> 
> Thanks for that, unfortunately it looks like my timeout is the same. Key 1:
> 
> ```
> 260102023f0302023f020400aa55c904010505030502040602000007010f0801000a01000f010c
> ```
> 
> Key 2:
> 
> ```
> 2e0102023f0302023f020400a2916d04010105030502040602000007010f0801000d02023f0e02023f0a01000f0100
> ```
> 
> Think I'll raise an issue on the `yubikey-manager` repo.
> 
> Thank you!

If you require button press, try to press and hold the button on the yubikey even before you hit enter in Keeweb for unlock.
