### ISSUE TITLE
Can not get plugins on selfhosted website

### ISSUE THREAD

**Issue by xdtianyu** [keeweb/keeweb#1546]
Thanks for your great work, I'm using keeweb for years, and I got CORS error today for downloading plugins, Here is the chrome console log:  

```
Access to XMLHttpRequest at 'https://plugins.keeweb.info/plugins.json' from origin 'https://www.***.org' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
```

It seems plugins.keeweb.info is hosting via cloudflare, and no cors header is set.

I'm using github-pages static files and hosting with nginx.

**Comment by antelle** [comment]
Hi! Plugins.keeweb.info are allowed to load only from app.keeweb.info, you need to self-host plugins aa well if you would like to use them. If you’re using our docker image, they’re already included.

**Comment by xdtianyu** [comment]
Thanks, I will try the docker image.

**Comment by HalliHalloSchatz** [comment]
How that work, self hosted plugins?

**Comment by antelle** [comment]
You have two options:
1. use plugins from plugins.keeweb.info
2. self-host plugins and add them via config, by the plugin url
