### ISSUE TITLE
Linux Appimage won't run on KDE, needs org.freedesktop.secrets

### ISSUE THREAD

**Issue by andre-fernando** [keeweb/keeweb#1547]
I am currently using Manjaro KDE and cannot use any Keeweb version beyond 1.14.3. When trying to launch a new version I get the following error:
Error loading app: Error: The name org.freedesktop.secrets was not provided by any .service files.

To my understanding this involves installing gnome keyring, but this might cause a number of issues as my system uses kde wallet. Is there an alternate fix for this?

**Comment by antelle** [comment]
Hi! We're using [node-keyring](https://github.com/mmarcon/node-keyring) package for managing the secret, now there's a switch to disable it, however the possibility to disable it will be probably removed. Just to understand, what kind of issues can it cause?

**Comment by andre-fernando** [comment]
I was under the impression that if I had to install gnome keyring I might have to install a lot of gnome dependencies which could cause some bugs from having 2 desktop environments packages running. But thankfully gnome keyring comes stand alone, I installed it and got it running, will test and see if any issues will arise from having 2 keyrings installed. I tried installing node-keyring via npm globally but that did not work with the app image.

**Comment by zbyna** [comment]
Hi,
thanks for great app!
I have the same issue, but I am not able to install gnome keyring - I am on really old Mint 17.3 b/c really old unsupported hardware:
```
zbyna@zbyna-MS-7681:~/Applications > sudo apt-get install  gnome-keyring
Načítají se seznamy balíků… Hotovo
Vytváří se strom závislostí       
Načítají se stavové informace… Hotovo
Pro opravení následujících můžete spustit „apt-get -f install“:
Následující balíky mají nesplněné závislosti:
 gnome-keyring : Závisí na: gcr (>= 3.4) ale nebude se instalovat
                 Závisí na: p11-kit (>= 0.16) ale nebude se instalovat
 libgpg-error0 : Porušuje: libgpg-error0:i386 (!= 1.38-2) ale 1.12-0.2ubuntu1 se bude instalovat
 libgpg-error0:i386 : Porušuje: libgpg-error0 (!= 1.12-0.2ubuntu1) ale 1.38-2 se bude instalovat
E: Nesplněné závislosti. Zkuste spustit „apt-get -f install“ bez balíků (nebo navrhněte řešení).
```
Any chance for including gnome-keyring and its dependencies in appimage?

**Comment by antelle** [comment]
Not sure, is it's possible to include dependencies to AppImage?

**Comment by zbyna** [comment]
> Not sure, is it's possible to include dependencies to AppImage?

In my opinion it is possible to include all dependencies one decides: https://discourse.appimage.org/t/does-appimage-include-all-shared-library-dependencies-by-default/509

In this case I  have just  recognized that I need service to run, not dependency :blush:  . After some fight with packages and Kodi uninstalling I was able to install gnome-keyring and the last version is flawlessly working on:
```
Linux 4.8.17-040817-generic
KDE SC: 4.13.2
```
