### ISSUE TITLE
考虑一下内置支持git，自己部署不同设备同步文件，可以开发手机app全端同步

### ISSUE THREAD

**Issue by Castleeee** [keeweb/keeweb#1548]
!please describe your issue here!

KeeWeb v1.14.3 (489eb55, 2020-05-15)
Environment: electron v8.2.5
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) KeeWeb/1.14.3 Chrome/80.0.3987.165 Electron/8.2.5 Safari/537.36

**Comment by antelle** [comment]
Hi! I'm not sure if Google Translate does good job here, but here's what I get:
> Consider built-in support for git, deploying different devices to synchronize files yourself, you can develop mobile app full-end synchronization

In this case, the answer is "wontfix", we won't provide support for git since it's not the place to store kdbx files, however you can create a plugin for that.
