### ISSUE TITLE
FR: default action onClick password field -> Copy (instead Reveal)

### ISSUE THREAD

**Issue by mwoz123** [keeweb/keeweb#1549]
**Is your feature request related to a problem? Please describe.**
Accidentally clicking on (previously saved) Password fileds reveal the password and is visible to nearby persons.

**Describe the solution you'd like**
When Password field is clicked default action should be `Copy` instead `Reveal`

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by antelle** [comment]
Hi! It's copied when you click on the label.
When you click on the password field itself, it's revealed, the editing cursor also suggests what will happen, having double-click or something else for editing would make editing harder.
I'll leave it open just to see what other people think about it, and if there are enough opinions, we can create an option in settings.
