### ISSUE TITLE
New entry only shows "Username" and no other fields

### ISSUE THREAD

**Issue by dploeger** [keeweb/keeweb#1553]
**Describe the bug**
When creating a new entry, only the title of the entry and the field "username" is shown. This happens regardless of using a template or not.

This happens on the desktop app on my mac, but now when I start the public web app on keeweb.info

**To Reproduce**
1. Open a new database
2. Create a new entry

**Expected behavior**
When creating a standard entry, the view should show the default fields "username", "password" and "website". When using a template, the view should show all the fields from the template.

**Screenshots**

![image](https://user-images.githubusercontent.com/203453/85854802-62a27900-b7b5-11ea-8cff-5f8c354faf9f.png)

**Environment**
KeeWeb v1.15.5 (62ea631, 2020-06-13)
Environment: electron v9.0.4
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_5) AppleWebKit/537.36 (KHTML, like Gecko) KeeWeb/1.15.5 Chrome/83.0.4103.104 Electron/9.0.4 Safari/537.36

**Logs**
No logs are coming up

**Comment by antelle** [comment]
Also "more..." is not visible. That' a bug indeed.

**Comment by antelle** [comment]
Fixed it. Sorry that it took that long, things happening in the world right now are not very helpful 😷

**Comment by dploeger** [comment]
Thanks a lot. Actually, I was about to close the bug again, because I completely removed all traces of Keeweb from my Mac and reinstalled it and it happened to work again. 🤷‍♂ 

I hope, you're well  during the pandemic. ❤️
