### ISSUE TITLE
Hard dependency on gnome-keyring

### ISSUE THREAD

**Issue by EwoutWal** [keeweb/keeweb#1557]
After updating to version 1.15.5-1 keeweb refused to start giving the error "the name org.freedesktop.secrets was not provided by any .service files" using Manjaro KDE. The solution was to install gnome-keyring, which is given as a solution to this issue in other projects as well. Perhaps add this as a dependency or try to find a more universal approach.

https://github.com/microsoft/vscode-docker/issues/1515
https://github.com/Foundry376/Mailspring/issues/681

I hope this saves others the headache of not being able to access their passwords.

**Comment by antelle** [comment]
Hi! This is already added as a dependency for example in .deb. Which distribution package did you use?

**Comment by EwoutWal** [comment]
That's strange, it did not show up as a dependency for me. There is no keeweb package in the pacman repositories, so I used the keeweb package in the AUR, which I installed using yay. This could be an issue with KDE not coming with gnome-keyring by default which is what users in the other issue threads are also talking about.

**Comment by antelle** [comment]
I see, the one in AUR is a 3rd-party package, please report there, they should include gnome-keyring to dependencies of course.

**Comment by EwoutWal** [comment]
I will do that, thank you for your quick replies!
