### ISSUE TITLE
 KeeWeb Http to auto-fill the password

### ISSUE THREAD

**Issue by orziie** [keeweb/keeweb#1558]
!please describe your issue here!

KeeWeb v1.15.5 (62ea631, 2020-06-13)
Environment: electron v9.0.4
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) KeeWeb/1.15.5 Chrome/83.0.4103.104 Electron/9.0.4 Safari/537.36

When I use KeeWeb Http to auto-fill the password, it can only auto-fill based on the URL, not the ip address. But this does not exist in "KeePass".

**Comment by antelle** [comment]
Hi! I didn't understand what is meant here.

**Comment by orziie** [comment]
你好，我是一个外国人，只能说简单的英语，现在我是在用谷歌翻译写这个回信，如下图所示，当图中“1”处是数字时，“KeeWeb Http”不会自动填充用户名和密码，这非常不方便。只有在图中“3”处是网址时，“KeeWeb Http”才会自动填充用户名和密码。请问可以改进吗？


Hello, I am a foreigner and can only speak simple English. Now I am writing this reply in Google Translate, as shown in the figure below, when the "1" in the figure is a number, "KeeWeb Http" will not automatically It is very inconvenient to fill in the username and password. Only when "3" in the figure is the URL, "KeeWeb Http" will automatically fill in the user name and password. Can it be improved?

[cid:image001.png@01D65191.B0C756D0] [cid:image003.png@01D65191.B0C756D0]
发件人: Dimitri Witkowski<mailto:notifications@github.com>
发送时间: 2020年7月3日 22:43
收件人: keeweb/keeweb<mailto:keeweb@noreply.github.com>
抄送: 布洛芬<mailto:orziie@outlook.com>; Author<mailto:author@noreply.github.com>
主题: Re: [keeweb/keeweb] KeeWeb Http to auto-fill the password (#1558)


Hi! I didn't understand what is meant here.

―

**Comment by antelle** [comment]
I don't see the image you mentioned, probably it was lost when you posted the answer, could you please attach it?
