### ISSUE TITLE
Use ServiceWorker when possible

### ISSUE THREAD

**Issue by antelle** [keeweb/keeweb#156]
Updater should use ServiceWorker if it's available in browser, with fallback to appCache.
https://ponyfoo.com/articles/simple-offline-site-serviceworker
- [x] add app manifest
- [x] use service worker
- [x] investigate signature checking inside the worker

**Comment by davinkevin** [comment]
Very old issue but still important from my point of view. Especially when using it on mobile device (android, ios) without any application, having the offline would be perfect !

**Comment by antelle** [comment]
ServiceWorker is everywhere, so the next version will be already using it instead of AppCache.
