### ISSUE TITLE
Bulk-selection of items

### ISSUE THREAD

**Issue by noelforte** [keeweb/keeweb#1560]
**Is your feature request related to a problem? Please describe.**
One thing I've noticed missing from KeeWeb is the ability to run batch actions on them (get favicons, export, move to group, assign icon, move to trash) etc.). I didn't find any relevant issues in this repository so unless this functionality already exists, I think it's something worth adding!

**Describe the solution you'd like**
Would like to be able to bulk select a range (Shift-click) or individual (Ctrl/Cmd-click) items in a kdbx file and be able to run batch actions on them as described above.

**Describe alternatives you've considered**
Alternate patterns that could be added that might work better on mobile are an `Edit` button that allows for items to be selected, then acted upon.

**Additional context**
<img width="1234" alt="Screen Shot 2020-07-05 at 11 10 10 PM" src="https://user-images.githubusercontent.com/2560683/86552310-9dbf4d80-bf15-11ea-98ff-0ec47e4805c9.png">

I can take time in the next few days to design something in more depth that shows how I think this could work.

**Comment by antelle** [comment]
Hi! It's #729
