### ISSUE TITLE
keeweb is not accepting http webdev url

### ISSUE THREAD

**Issue by chandu2503** [keeweb/keeweb#1562]
Please suggest a solution

**Comment by antelle** [comment]
Hi! There are two solutions:
1. use HTTPS
2. self-host the KeeWeb HTML file and set the appropriate CSP policy

**Comment by chandu2503** [comment]
If I use https instead of http,it is promoting as network error.

Thanks,
Chandu2503

**Comment by antelle** [comment]
Does the server have a valid certificate?

**Comment by chandu2503** [comment]
Yeah,it is working fine with keepass application.

**Comment by antelle** [comment]
I don't think I asked if it works fine with KeePass. Is the certificate accepted in browsers without adding an exception?
