### ISSUE TITLE
Can't run ("libgobject-2.0.so.0: undefined symbol:") when installed from snap package

### ISSUE THREAD

**Issue by mwoz123** [keeweb/keeweb#1563]
```
marcin@dell:~/Pobrane$ sudo snap install ./KeeWeb-1.15.5.linux.snap 
error: cannot find signatures with metadata for snap "./KeeWeb-1.15.5.linux.snap"
marcin@dell:~/Pobrane$ sudo snap install --dangerous ./KeeWeb-1.15.5.linux.snap 
keeweb 1.15.5 installed
marcin@dell:~/Pobrane$ keeweb 
/snap/keeweb/x1/gnome-platform/usr/lib/x86_64-linux-gnu/glib-2.0/gio-querymodules: symbol lookup error: /snap/keeweb/x1/gnome-platform/usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0: undefined symbol: g_date_copy
marcin@dell:~/Pobrane$ uname -a
Linux dell 5.4.0-26-generic #30-Ubuntu SMP Mon Apr 20 16:58:30 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```
this is fresh install ubuntu 20.04

Does it mean extra object dependency (libgobject) should be added to snap config?

**Comment by antelle** [comment]
No idea what it is, to be honest. Does the same happen with .deb and zip?

**Comment by mwoz123** [comment]
sound like a solution: https://forum.snapcraft.io/t/undefined-symbol-g-date-copy-problem/12235/2

could you try adding `libglib-2.0.so.0` in version 2.56 (or above) to snap dependecies, as it contains this function?

ps: deb works

**Comment by antelle** [comment]
Duplicates #1473

**Comment by antelle** [comment]
See the solution provided in [this comment](https://github.com/keeweb/keeweb/issues/1473#issuecomment-687929946):
```
/snap/keeweb/x1/app/keeweb
```
works, however `keeweb` doesn't.

**Comment by AndreiCherniaev** [comment]
> ```
> marcin@dell:~/Pobrane$ sudo snap install ./KeeWeb-1.15.5.linux.snap 
> error: cannot find signatures with metadata for snap "./KeeWeb-1.15.5.linux.snap"
> marcin@dell:~/Pobrane$ sudo snap install --dangerous ./KeeWeb-1.15.5.linux.snap 
> keeweb 1.15.5 installed
> marcin@dell:~/Pobrane$ keeweb 
> /snap/keeweb/x1/gnome-platform/usr/lib/x86_64-linux-gnu/glib-2.0/gio-querymodules: symbol lookup error: /snap/keeweb/x1/gnome-platform/usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0: undefined symbol: g_date_copy
> marcin@dell:~/Pobrane$ uname -a
> Linux dell 5.4.0-26-generic #30-Ubuntu SMP Mon Apr 20 16:58:30 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
> ```
> 
> this is fresh install ubuntu 20.04
> 
> Does it mean extra object dependency (libgobject) should be added to snap config?

https://medium.com/@Aenon/glib-symbol-lookup-bug-in-debian-or-ubuntu-def678dab5a6
