### ISSUE TITLE
Authorization Header not being sent - 07/13/2020 build

### ISSUE THREAD

**Issue by firedrow** [keeweb/keeweb#1565]
**Describe the bug**
I'm using Caddy Server v2 to host the KeeWeb site for self-hosting and the WebDav site for storage (2 different FQDN).  When I attempt to connect to the WebDav from KeeWeb, it appears KeeWeb is not sending the Authorization header to authenticate.

**To Reproduce**
1. Go to the KeeWeb site
2. Click on More -> WebDav
3. Fill in URL, User, Pass
4. Click Ok, get network error

**Expected behavior**
If the Authorization header is sent, it should authenticate to WebDav and allow connection to the KDBX file.

**Screenshots**

**Environment**
Your user-agent (from Settings/Help section):
* Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:78.0) Gecko/20100101 Firefox/78.0
* Firefox 78.0.2 64-bit

**Kdbx File**
I'm only testing against a WebDav connection.

**Logs**
Firefox DevTools Console:
```
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://dav.rowland.pw/keepass/drowland.kdbx. (Reason: CORS request did not succeed).
Failed to load ‘https://dav.domain.tld/keepass/userfile.kdbx’. A ServiceWorker passed a promise to FetchEvent.respondWith() that rejected with ‘TypeError: NetworkError when attempting to fetch resource.’.
```

Caddy Server Logs:
```
{"level":"error","ts":1594908257.0561504,"logger":"http.log.access.log1","msg":"handled request","request":{"method":"OPTIONS","uri":"/keepass/userfile.kdbx","proto":"HTTP/1.1","remote_addr":"192.168.20.1:33474","host":"dav.domain.tld","headers":{"Accept":["*/*"],"Accept-Language":["en-US,en;q=0.5"],"Access-Control-Request-Headers":["authorization,cache-control"],"Connection":["keep-alive"],"User-Agent":["Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:78.0) Gecko/20100101 Firefox/78.0"],"Accept-Encoding":["gzip, deflate, br"],"Access-Control-Request-Method":["HEAD"],"Referer":["https://kee.domain.tld/"],"Origin":["https://kee.domain.tld"]},"tls":{"resumed":false,"version":771,"ciphersuite":49196,"proto":"http/1.1","proto_mutual":true,"server_name":"dav.domain.tld"}},"common_log":"192.168.20.1 - - [16/Jul/2020:14:04:17 +0000] \"OPTIONS /keepass/userprofile.kdbx HTTP/1.1\" 401 0","duration":0.000085727,"size":0,"status":401,"resp_headers":{"Access-Control-Max-Age":["1728000"],"Access-Control-Allow-Origin":["kee.domain.tld"],"Www-Authenticate":["Basic realm=\"restricted\""],"Server":["Caddy"],"Referrer-Policy":["no-referrer-when-downgrade"],"Access-Control-Expose-Headers":["ETag"],"Access-Control-Allow-Credentials":["true"],"Access-Control-Allow-Headers":["Authorization,DNT,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,X-Accept-Charset,X-Accept,origin,accept,if-match,destination,overwrite,X-CustomHeader"],"Access-Control-Allow-Methods":["GET, HEAD, POST, PUT, MOVE, OPTIONS, DELETE, COPY, LOCK, UNLOCK, PROPFIND, MKCOL"],"Strict-Transport-Security":["max-age=31536000;"],"X-Content-Type-Options":["nosniff"]}}
```

**Comment by antelle** [comment]
I just realized that your logs show OPTIONS request. This preflight request never has authorization, it's also mentioned in the wiki: https://github.com/keeweb/keeweb/wiki/WebDAV%20Config

**Comment by requiem958** [comment]
This issue is not over as copying the webdav config just does not work with new caddy, since the cors directive no more exists and the webdav has changed to be a plugin.

Is there anyone who actually have a working caddy V2 config to replace the one in the wiki ?

**Comment by lyh458** [comment]
> This issue is not over as copying the webdav config just does not work with new caddy, since the cors directive no more exists and the webdav has changed to be a plugin.
> 
> Is there anyone who actually have a working caddy V2 config to replace the one in the wiki ?
> 
> ## Edit 1 To replace the cors config i could suggest (according to many questions online and personal tests) :
> 
> ```
>         header {
>                 Access-Control-Allow-Origin *
>                 Access-Control-Allow-Credentials true
>                 Access-Control-Allow-Methods "GET, HEAD, POST, PUT, OPTIONS, MOVE, DELETE, COPY, LOCK, UNLOCK, PROPFIND, MKCOL"
>                 Access-Control-Allow-Headers "Authorization,DNT,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,X-Accept-Charset,X-Accept,origin,accept,if-match,destination,overwrite,X-CustomHeader"
>                 Access-Control-Expose-Headers "ETag"
>                 Access-Control-Max-Age 1728000
>         }
> ```
> 
> ## Edit 2
> The only way to works keeweb and caddy together seems to be to not have basic authentication, which is a real issue.

Hi, any update?
