### ISSUE TITLE
Autotype timeout option between keystrokes sequence

### ISSUE THREAD

**Issue by MarceloZapatta** [keeweb/keeweb#1566]
Hi!

I thinks it is a good ideia have an item in the Keystrokes options which set a timeout/delay before the next command. 

Many sites like [www.amazon.com](url) or [www.office.com](url) are using the flow: 
Enter your e-mail/username -> Click confirm -> Enter password -> Click confirm.

With the timeout option beetween commands, we could set a custom Keystroke like this (timeout 5 seconds example):

{USERNAME}{ENTER}{TIMEOUT:5s}{PASSWORD}{ENTER}

Like this in the timeout it will wait until next page loads and them fill the password.

![image](https://user-images.githubusercontent.com/39474221/87708338-f1813080-c778-11ea-8a8b-b3498edd2f38.png)

**Comment by antelle** [comment]
Hi! It's called `DELAY`: https://github.com/keeweb/keeweb/wiki/Auto%20Type#commands
