### ISSUE TITLE
Auto-Type (KeeWeb 1.15.xx) does not work in Ubuntu 20.04

### ISSUE THREAD

**Issue by deemike** [keeweb/keeweb#1567]
**Describe the bug**
Auto-Type in versions 1.15. very long time does not work in Ubuntu 20.04 (kernel 5.7.7). 

**To Reproduce**

1. Focus firefox with a login page
2. Click on Ctrl+T or Alt+Shift+T
3. Nothing happens

**Expected behavior**
Auto-typing/filling the login form or the keeweb selection list (if not match with window title)

**Environment**
KeeWeb v1.15.5 (62ea631, 2020-06-13)
Environment: electron v9.0.4
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) KeeWeb/1.15.5 Chrome/83.0.4103.104 Electron/9.0.4 Safari/537.36

**Logs**
`[DEBUG] 2020-07-16T20:37:44.533Z [auto-type] Hide window
[DEBUG] 2020-07-16T20:37:44.550Z [storage-file] Stop watch dir /media/3TB/Nextcloud/KeeWeb
[DEBUG] 2020-07-16T20:37:44.635Z [auto-type] Start {USERNAME}
[DEBUG] 2020-07-16T20:37:44.635Z [auto-type] Parsed [op:USERNAME]
[DEBUG] 2020-07-16T20:37:44.635Z [auto-type] Resolved [*****************]
[ERROR] 2020-07-16T20:37:44.641Z [launcher] spawn write error Error: write EPIPE
[ERROR] 2020-07-16T20:37:44.641Z [launcher] spawn error: xdotool, 5ms Error: spawn xdotool ENOENT
[ERROR] 2020-07-16T20:37:44.641Z [auto-type] Run error xdotool is not installed
[ERROR] 2020-07-16T20:37:44.642Z [launcher] spawn xdotool: -2, 6ms

[INFO ] 2020-07-16T20:39:26.731Z [open:MyStuff] File open request
[INFO ] 2020-07-16T20:39:26.731Z [open:MyStuff] Open file from storage file
[INFO ] 2020-07-16T20:39:26.731Z [open:MyStuff] Stat file
[DEBUG] 2020-07-16T20:39:26.731Z [storage-file] Stat /media/3TB/Nextcloud/KeeWeb/MyStuff.kdbx
[DEBUG] 2020-07-16T20:39:26.733Z [storage-file] Stat done /media/3TB/Nextcloud/KeeWeb/MyStuff.kdbx 1ms
[INFO ] 2020-07-16T20:39:26.733Z [open:MyStuff] Open file from storage (1594915725320, local 1594915725320)
[INFO ] 2020-07-16T20:39:26.733Z [open:MyStuff] Load from storage
[DEBUG] 2020-07-16T20:39:26.733Z [storage-file] Load /media/3TB/Nextcloud/KeeWeb/MyStuff.kdbx
[DEBUG] 2020-07-16T20:39:26.734Z [storage-file] Loaded /media/3TB/Nextcloud/KeeWeb/MyStuff.kdbx 1594915725320 1ms
[INFO ] 2020-07-16T20:39:26.734Z [open:MyStuff] Open file from content loaded from storage
[INFO ] 2020-07-16T20:39:26.814Z [file] Opened file MyStuff: 79ms, 6000 rounds, 143 kB
[DEBUG] 2020-07-16T20:39:26.814Z [app] Add last open file dbedc6fb-5654-89ca-0403-f3c9170ac55b MyStuff file /media/3TB/Nextcloud/KeeWeb/MyStuff.kdbx 1594915725320
[DEBUG] 2020-07-16T20:39:26.864Z [storage-file] Watch dir /media/3TB/Nextcloud/KeeWeb
[ERROR] 2020-07-16T20:43:38.906Z [launcher] spawn error: ykman, 15ms Error: spawn ykman ENOENT
[ERROR] 2020-07-16T20:43:38.906Z [launcher] spawn ykman: -2, 15ms`

**Comment by antelle** [comment]
Hi! Do you have anything special in the entry? Like, 2FA or similar? Are you using a yubikey?

**Comment by antelle** [comment]
Ah I see, xdotool is not installed, is it really not installed, or KeeWeb just doesn't see it?

**Comment by deemike** [comment]
> Hi! Do you have anything special in the entry? Like, 2FA or similar? Are you using a yubikey?

Hi. No I don't use a 2FA or any yubikeys.

**Comment by deemike** [comment]
> Ah I see, xdotool is not installed, is it really not installed, or KeeWeb just doesn't see it?

My mistake. Yes, xdotool was not installed. When I installed it,  Auto-Type worked.
