### ISSUE TITLE
New status/task bar icon everytime I close keeweb on PopOs(linux)

### ISSUE THREAD

**Issue by piyu-sh** [keeweb/keeweb#1569]
**Describe the bug**
Everytime I open the Keeweb application from status icon, and then close it, it creates another icon.

**To Reproduce**

1. Enable the setting `Minimize the app instead of close`
2. Click the close icon to minimize app
3. The app is closed and visible as status icon
4. Open Keeweb again
5. Now close it, there will be another icon on status bar

**Expected behavior**
There should only be one icon in status bar

**Screenshots**
![Screenshot from 2020-07-18 14-59-59](https://user-images.githubusercontent.com/7107647/87849671-e1e42200-c907-11ea-9de0-806aaaf1ab16.png)

**Environment**
KeeWeb v1.15.5 (62ea631, 2020-06-13)
Environment: electron v9.0.4
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) KeeWeb/1.15.5 Chrome/83.0.4103.104 Electron/9.0.4 Safari/537.36

**Logs**
[keeweb_logs.log](https://github.com/keeweb/keeweb/files/4941401/keeweb_logs.log)

**Comment by antelle** [comment]
Duplicates #1181
