### ISSUE TITLE
Just to say a big thanks to the devs.

### ISSUE THREAD

**Issue by alkaphreak** [keeweb/keeweb#1570]
I'm happy to support your project.

KeeWeb v1.15.5 (62ea631, 2020-06-13)
Environment: electron v9.0.4
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) KeeWeb/1.15.5 Chrome/83.0.4103.104 Electron/9.0.4 Safari/537.36

**Comment by antelle** [comment]
Thank you! ❤️
