### ISSUE TITLE
Cannot quit keepass on a mac

### ISSUE THREAD

**Issue by barredterra** [keeweb/keeweb#1571]
**Describe the bug**

When my keeweb database is locked, not closed, its impossible to quit keeweb on a mac. What's more, locked and closed state cannot be told apart by the user (except by way of this issue).

**To Reproduce**

1. Open keeweb and unlock a database from Google Drive
2. Click the small logout icon on the bottom right or wait for auto-lock
3. Try to quit keeweb

Now that i'm trying to reproduce it, it doesn't work anymore. Maybe keepass has to stay open for a while? I'm facing this every day.

**Expected behavior**

Keeweb quits

**Environment**

KeeWeb v1.15.5 (62ea631, 2020-06-13)
Environment: electron v9.0.4
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) KeeWeb/1.15.5 Chrome/83.0.4103.104 Electron/9.0.4 Safari/537.36

**Comment by antelle** [comment]
Hi! It would be interesting to read logs when this happens, if you're saying it happens every day, could you please capture them next time you see it?

**Comment by barredterra** [comment]
Seems to be fixed, cannot reproduce anymore.
