### ISSUE TITLE
YubuKey Error Opening File [object Object] 

### ISSUE THREAD

**Issue by sshaginyan** [keeweb/keeweb#1572]
**Describe the bug**
YubiKey not working. I'm using WebDAV to connect to a remote service that hosts my kdbx file. This was working fine. The moment I introduced my YubiKey 5c Nano, I wasn't able to login anymore and an error would show up with message, "There was an error opening file [object Object]".

**To Reproduce**
1) Plugged in my YubiKey 5c Nano
2) Installed `ykman` and `YubiKey Manager`
3) Went to setting and selected my YubiKey
4) Told me this could be dangerous and that I should make up a backup of my kdbx file, so I did
5) Logged out and tried logging back in and I can't :-(.

**Expected behavior**
I was expecting to use my YubiKey as a 2nd factor for authentication with OTP. 

**Screenshots**

Before I put in my password
<img width="998" alt="Screen Shot 2020-07-21 at 5 00 42 PM" src="https://user-images.githubusercontent.com/325014/88119516-98007380-cb75-11ea-8db3-48ca69c89258.png">

After I put in my password and press enter.
<img width="1002" alt="Screen Shot 2020-07-21 at 5 01 29 PM" src="https://user-images.githubusercontent.com/325014/88120042-ee21e680-cb76-11ea-819c-7f1572cb9387.png">

**Environment**
MacBook Pro 16 inch 2019. MacOS Catalina 10.15.6

**Kdbx File**
Does it happen on Demo or New database?  
New Database

**Logs**

<img width="1002" alt="Screen Shot 2020-07-21 at 5 01 29 PM" src="https://user-images.githubusercontent.com/325014/88119653-f9c0dd80-cb75-11ea-88b6-3a972914f102.png">

**Comment by antelle** [comment]
Hi! Error with code 4 is a timeout (the message in the UI should be fixed of course): https://github.com/Yubico/yubikey-personalization/blob/a0f73997bc35ee15b2541d652ba16a9ecf4bc76d/ykcore/ykcore.h#L168
What happens if you calculate the code using `ykman`? Something like this:
```
ykman otp calculate 1 aa
```

**Comment by sshaginyan** [comment]
@antelle I get this.
<img width="422" alt="Screen Shot 2020-07-22 at 12 13 52 PM" src="https://user-images.githubusercontent.com/325014/88218399-dbf68580-cc14-11ea-8840-5a09b14d071a.png">

**Comment by antelle** [comment]
Well, this means we won't be able to fix it :( 
What if you run it with verbose logging?
```
ykman -l DEBUG otp calculate 1 aa
```

**Comment by antelle** [comment]
Just to make sure we're doing everything right, you have only one YubiKey and Challenge-Response is programmed to slot 1?
Does restarting the macbook help? What about other apps (before the restart), for example KeePassXC?
I also got this once, all tools were unable to use the YubiKey.

**Comment by sshaginyan** [comment]
Sorry I didn't properly program my YubiKey to Slot 1. Now it is! Let me try it again.

**Comment by sshaginyan** [comment]
It works! Sorry this was an error on my part. Had to program my yubikey. Should I create a PR for the UI messaging?

**Comment by antelle** [comment]
Sure, or I'll fix it myself in the next version
