### ISSUE TITLE
Unscrollable overflow menu

### ISSUE THREAD

**Issue by mkbaranovskyi** [keeweb/keeweb#1575]
When the window height is not enough, the appearing menu is just cut off and there's no way to scroll it.
[](url)
![Unscrollable menu](https://user-images.githubusercontent.com/39165507/88467857-3ed17080-cee4-11ea-921f-60e34f308aaa.png)

Looks like `overflow: hidden` is used. I suggest changing it to the `overflow: scroll`. I suppose, this is a bug, not a feature. 
Btw, this is a Linux version of the app.

**Comment by antelle** [comment]
It's a bit harder than that but yes, it should scroll, it's a bug.
