### ISSUE TITLE
Self-hosted with DropBox doesn't work anymore on Android

### ISSUE THREAD

**Issue by Xavier-Plasma** [keeweb/keeweb#1577]
**Describe the bug**
Self-hosted with DropBox doesn't work anymore on Chrome and Brave for Android.
The error displayed is : 
OAuth code exchange error: http status 400
The same self-hosted url works perfectly in Chrome and Brave on Windows 10 with the same config and the same kbdx hosted in the same DropBox account, and used to work before, so I don't think it comes from my settings. 
(And also the DropBox connexion works in the Desktop version of KeeWeb).

I've tested with version 1.14.0 and 1.15.5. 
I do not remember wich version I used before upgrading to v1.14, (and unfortunately I didn't have a backup) but an older version before v1.14 worked with Android without issues, with the same DropBox account and config. 

This maybe due to the changes introduced in version v1.14 as a result of the audit?

**To Reproduce**
1. Use a self-hosted version
2. Edit the meta "kw-config" of the file index.html to use a custom json settings file (hosted in the same place)
3. In the json settings file set a custom "dropboxFolder" and "dropboxAppKey"
4. Try to connect

**Expected behavior**
Connexion to DropBow does not fail.

**Environment**
KeeWeb v1.14.0 (eaf429d, 2020-04-18)
Environment: web
User-Agent: Mozilla/5.0 (Linux; Android 10; Mi 9T) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.105 Mobile Safari/537.36

**Logs**
I can't connect so I does not know how to provide logs from Android.

PS: Thanks a lot for this awesome application :)

**Comment by antelle** [comment]
Hi! Are there any details about the error? Let's try to see the Network panel in devtools, it's possible.

**Comment by Xavier-Plasma** [comment]
How can I open the dev tool panel on a chrome in android? On a chrome in a
computer, there is no error.

**Comment by antelle** [comment]
I don't know, I'm not an Android ecosystem user. On iOS, you can connect your mac using a cable and see devtools in Safari. I guess, similar is possible in Chrome and Android, there should be instructions in Google.

**Comment by Xavier-Plasma** [comment]
Thank you for your help, I was able to connect the devtool panel via usb debugging. 

The console log is in the attached file. 
[keeweb.log](https://github.com/keeweb/keeweb/files/4996059/keeweb.log)

Also, I can see the https://api.dropboxapi.com/oauth2/token is in error code 400, and the content is :
{error: "invalid_client: Invalid client_id or client_secret"}

How is it possible to have a invalid client id or client secret in android, but the same client id and secret working on a computer?

**Comment by antelle** [comment]
Have you set `dropboxSecret` in settings?

**Comment by Xavier-Plasma** [comment]
No, only "dropboxFolder" and "dropboxAppKey".

**Comment by antelle** [comment]
You need to set it, otherwise it won't work

**Comment by Xavier-Plasma** [comment]
Oh, I will try. Is this something new or something specific to mobile? Because I still not understand why this config working before version 1.14 and why this is working on a computer and not working on a Android.

**Comment by antelle** [comment]
Yes, in v1.14 we switched to another OAuth flow where the app secret is required. Not sure why it works on desktop for you, it shouldn't. Maybe it's loading an old version.

**Comment by Xavier-Plasma** [comment]
Thanks a lot, indeed, it is working great with the "dropboxSecret" in settings json file. 
On computer, I can say it is not an old html file loaded: I have tested with cache disabled and I can see the new version number in the help section (v1.15.5). 
But, anyway, this is a closed issue for me, thanks again.
