### ISSUE TITLE
Donation alternative method

### ISSUE THREAD

**Issue by seupedro** [keeweb/keeweb#1578]
Hi, do you have a paypal account? Cause I would like to contribute with this project. But after the coronavirus, the dollar became really expensive here. 💸

Anyways I still would like to contribute and pay to you a coffee cost of my country. Although it gonna be remains more symbolic than valuable. 🎁

**Comment by antelle** [comment]
Hi! 
I used to have a public paypal link, but I shut it down and now there are troubles enabling it back, so right now I have only GitHub and OpenCollective, which was the most requested option.
Anyway, thank you for expressing the feedback! ❤️ 
<details>
  <summary>If you need my PayPal account</summary>

```
dmitryvit@gmail.com
```

</details>
