### ISSUE TITLE
How to disable validating resource signature css

### ISSUE THREAD

**Issue by Gnog3** [keeweb/keeweb#1579]
I want to customize .css file of a plugin a bit, but when i do it, keeweb doesn't load the plugin, and says
```
[ERROR] 2020-08-07T18:50:56.659Z [plugin:theme-cupertino-dark] Resource signature invalid css
[ERROR] 2020-08-07T18:50:56.659Z [plugin:theme-cupertino-dark] Error validating resource signature css
[ERROR] 2020-08-07T18:50:56.659Z [plugin:theme-cupertino-dark] Error installing plugin Error loading plugin resources
```
How can i disable this validating?

**Comment by antelle** [comment]
Hi! It's not possible by design (so that bad guys can't inject strange plugins to your KeeWeb), you need to build your own plug-in, then sign it with your key, after which you will be able to load it: https://github.com/keeweb/keeweb/wiki/Plugins
