### ISSUE TITLE
keeweb not quitting from dock - Mac

### ISSUE THREAD

**Issue by tcz305** [keeweb/keeweb#1582]
**Describe the bug**
Happening since the last two versions but more prominent with latest release. It happened randomly with previous version, seems to happen 80-100% of the time with latest release.
When closing app to dock with red button app window will close. When right clicking dock icon and choosing 'Quit' app will not quit. There will also not be any 'force quit' option. With previous version right clicking and choosing 'Quit' a couple of times the app would eventually quit.
With latest release the bug has progressed that it will no longer quit no matter how many times you right click and choose 'Quit'.
You have to click the dock icon where the app window will open and then choose the 'Quit' command from the menubar. Also, right-clicking the dock icon and choosing 'Quit' while the app window is open the app will also quit normally.

**To Reproduce**
1. open app and database 
2. click red button to close app window
3. right-click dock icon and choose 'Quit'
4. app will not quit

**Expected behavior**
App should quit when right-clicking and choosing 'Quit".

**Environment**
KeeWeb v1.15.5 (62ea631, 2020-06-13)
Environment: electron v9.0.4
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) KeeWeb/1.15.5 Chrome/83.0.4103.104 Electron/9.0.4 Safari/537.36

**Kdbx File**
Does it happen on Demo or New database?
Yes, new or existing.

**Logs**
[INFO ] 2020-08-09T19:58:55.893Z [start-profiler] App started in 345ms: fetching=134ms, pre-init=177ms, loading modules=35ms, document ready=16ms, creating app model=3ms, loading configs=11ms, initializing modules=2ms, loading remote config=1ms, checking features=0ms, initializing storage=0ms, first view rendering=100ms, app ready event=0ms
[INFO ] 2020-08-09T19:58:55.897Z [usb-listener] Starting USB listener
[DEBUG] 2020-08-09T19:58:55.897Z [native-module-connector] Starting native module host
[INFO ] 2020-08-09T19:59:00.783Z [open:PW] File open request
[INFO ] 2020-08-09T19:59:00.783Z [open:PW] Open file from storage file
[INFO ] 2020-08-09T19:59:00.783Z [open:PW] Stat file
[DEBUG] 2020-08-09T19:59:00.783Z [storage-file] Stat /Users/terrym/Documents/PW.kdbx
[DEBUG] 2020-08-09T19:59:00.785Z [storage-file] Stat done /Users/terrym/Documents/PW.kdbx 2ms
[INFO ] 2020-08-09T19:59:00.785Z [open:PW] Open file from storage (1596855919644, local 1596855919644)
[INFO ] 2020-08-09T19:59:00.785Z [open:PW] Load from storage
[DEBUG] 2020-08-09T19:59:00.785Z [storage-file] Load /Users/terrym/Documents/PW.kdbx
[DEBUG] 2020-08-09T19:59:00.788Z [storage-file] Loaded /Users/terrym/Documents/PW.kdbx 1596855919644 2ms
[INFO ] 2020-08-09T19:59:00.788Z [open:PW] Open file from content loaded from storage
[INFO ] 2020-08-09T19:59:00.976Z [file] Opened file PW: 187ms, 6000 rounds, 64 kB
[DEBUG] 2020-08-09T19:59:00.976Z [app] Add last open file 2e1a4e8e-d7cb-2085-40f1-f3e4b960bd3d PW file /Users/terrym/Documents/PW.kdbx 1596855919644
[DEBUG] 2020-08-09T19:59:01.079Z [storage-file] Watch dir /Users/terrym/Documents

**Comment by antelle** [comment]
Hi! Does it happen, for example, if you open the Demo db without anything else? I was thinking, maybe it's hanging on saving?

**Comment by tcz305** [comment]
hi, sorry, i'll close this ....i just tried 1.15.6 and the bug seems to have vanished.
No hangs so far with this version. Whatever changed seems to have fixed the issue.
Thanks
