### ISSUE TITLE
Kdbx file disapeared after last update v1.15.6

### ISSUE THREAD

**Issue by Erimen** [keeweb/keeweb#1583]
Hello,

I lost all my passwords after the update of keeweb. I searched with the soft everywhere but nothing found. 
I tried to create a new kdbx file and save it to my local storage. In result of that, I only can find a shortcut to my old brand new kdbx which is not there (i tried multiple folders with different permissions)
I checked the quantine of my antivirus, windows defender is disabled so I don't think it is deleted by them.

Is it a bug from keeweb or from my computer ? I don't know where to search for now

Thank you in advance if you can help me,
Have a nice day

**Comment by antelle** [comment]
Hi! Was it web or desktop version? Where was the file stored previously? If it was in the so-called "in-app" storage, it can be found in "AppData/KeeWeb/Offline Files".

**Comment by Erimen** [comment]
Hi Antelle,
Thank you for answering me. 
It's the desktop version and this is my father's computer so we don't know where they could be stored. 
I checked Offline Files (in roaming folder) and I found 3 files. 2 from today, they are my tests, and one which was created months ago so I assume this is the good one ? 
I tried to open it without any success, it's name is like _dh8o9j4b__
What can I do with this file ?

**Comment by antelle** [comment]
That last file can be what you're looking for. Have you tried opening it with its password?

**Comment by Erimen** [comment]
The file has no extension and can't be opened, maybe if I add the extension manually ? (I unchecked the option to see all file extensions)

**Comment by antelle** [comment]
indeed, rename it, it's a regular kdbx file

**Comment by Erimen** [comment]
So simple haha 😅
I'll try that tomorrow, it's getting late in Belgium.
Thank you very much for your time. 
Have a nice day
