### ISSUE TITLE
Support Dark Mode based on system preferences

### ISSUE THREAD

**Issue by dploeger** [keeweb/keeweb#1584]
**Is your feature request related to a problem? Please describe.**
I switch the dark mode preference on my Mac from time to time based on the area I'm in. Most apps react to this and switch from dark to light automatically. Keeweb supports a dark and a light theme, but doesn't switch automatically.

**Describe the solution you'd like**
Keeweb should offer me a switch which theme should be applied when dark mode has been selected and which on light mode. The switch should be automatically depending on the system setting. To my knowledge, this is a macOS-only feature at the moment, but other OSes might support it as well.

**Additional context**
This probably can be done using the CSS feature [prefers-color-scheme](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme)

**Comment by antelle** [comment]
It won't be possible to use prefer-color-scheme, but there's an event in Electron that we can listen and switch theme based on it.

**Comment by dploeger** [comment]
Can we check wether dark mode switching is supported at all by the os? I'd suggest only showing the setting when it's possible and then breaking up the theme selection into two.

**Comment by antelle** [comment]
I'm not sure, better to test this module on different OS: https://www.electronjs.org/docs/api/native-theme

**Comment by dploeger** [comment]
Hmm. I can't find anything about a feature flag wether the system supports a dark theme at all. Then I guess we have to always show both theme selections. One Light/Default Theme and a dark one.

**Comment by antelle** [comment]
I mean, we can test it on, for example, Windows, Linux, and macOS, and see if it supports it. It may be mac-only, but better to check.

**Comment by dploeger** [comment]
I guess we can't assume, that all users use a system that supports it. I know macOS and win 10 support it, but maybe not every Linux desktop environment. And I wanted to clean up the UI for systems not supporting it.

Coming to think about it, we should still check if we **can** use the css media query as well for the browser, so we could support switching on all platforms.

**Comment by antelle** [comment]
Most of OS (macOS, Windows, Ubuntu in its default setup) have dark/white theme nowadays, probably that shouldn't be a big deal. The switcher should be something like this I guess:
```
<select theme>
[ ] automatically switch to dark/light theme
```
which becomes
```
<select a light theme>
[x] automatically switch to dark/light theme
<select a dark theme>
```
I like how it's done in iStatMenus:
![Screen Recording 2020-08-12 at 21 19 24](https://user-images.githubusercontent.com/633557/90058256-c9d2a900-dce1-11ea-8cdf-db5886911f72.gif)

**Comment by antelle** [comment]
It's coming soon, here's a preview: https://youtu.be/ktUgSao4BZo
There will be no possibility to select a theme though, in the first version they will be set automatically.

**Comment by antelle** [comment]
Deployed to [beta.keeweb.info](https://beta.keeweb.info), will be available in the next release.
