### ISSUE TITLE
[keewebhttp] Dead links on Keewebhttp plugin page

### ISSUE THREAD

**Issue by philippemilink** [keeweb/keeweb#1586]
Hi,

Links for browser plugins on page https://plugins.keeweb.info/plugins/keewebhttp/index.html are broken.

**Comment by antelle** [comment]
Looks like KeePassHttp - compatible plugins were removed from Chrome and Firefox stores.

**Comment by antelle** [comment]
It's more of another a KeePassHttp issue in general. We should probably develop an extension compatible with KeePassXC-HttpConnector.

**Comment by antelle** [comment]
I assume, KeePassHttp is somewhat dead now, and we should support the new thing.

**Comment by monsieurhannes** [comment]
@antelle, what is the new thing?

**Comment by antelle** [comment]
Plugins based on native messaging, intended to work with KeePassXC.  
There are, however, licensing and ethical questions how to use them. So, I have no idea what to do with it.

**Comment by existpierre** [comment]
i transfered keeweb app with App Support folder to new MacBook and keewebhttp plugin is missing (keewebhttp_plugin.js have in PluginFiles. I want this plugin because autofilling input after page loaded. How to enable this plugin on new pc ? thanks

**Comment by antelle** [comment]
KeeWebHttp is retired and not available for download. Instead, you can go to Settings / Browser and install the new plugin.

**Comment by existpierre** [comment]
as i sad - is bad for me - not autofilling immediately after load page. Is planned this feature soon or will be not available?

**Comment by antelle** [comment]
I'm not sure if this feature will come to KeeWeb Connect but KeeWeb will support returning multiple entries for KeePassXC-Browser.
