### ISSUE TITLE
[Feature Request] Shortcut to copy OTP code

### ISSUE THREAD

**Issue by KaKi87** [keeweb/keeweb#1589]
**Is your feature request related to a problem? Please describe.**
When logging into a OTP-enabled account, the code is almost always required just after the password.

**Describe the solution you'd like**
Therefore, after pressing Ctrl + C once to copy the password into the clipboard, I suggest that pressing Ctrl + C twice when getting back to KeeWeb would then copy the OTP code.

**Describe alternatives you've considered**
Continuing to manually use the mouse for the OTP code despite there's a shortcut for the password, I guess.

**Additional context**
None

-----

Thanks !

**Comment by antelle** [comment]
Hi! Ctrl+C shouldn't copy another thing to clipboard depending on what you did before, but you can set another shortcut to copy OTP in Settings/Shortcuts.

**Comment by KaKi87** [comment]
> depending on what you did before

Not that, but depending on how many times I press it in a second

**Comment by antelle** [comment]
Right now we don't support such "repeated" shortcuts and to be honest, I don't see a reason to do so, since it doesn't often appear in well-behaving apps (or maybe I'm not aware of them). But if if/once we support them, it will be possible to set such a combo for OTP as well.

**Comment by KaKi87** [comment]
Well, I suggested it because it feels logical to me, doesn't it to you ?
I mean the next step after copying the password is always copying the OTP code when there's one.
Otherwise which shortcut would you suggest to copy the OTP code ? Because I don't have any idea.

**Comment by antelle** [comment]
I haven't seen double Ctrl/Cmd+C used anywhere, so to me it sounds a bit strange if Ctrl+C+C copies something.
Well, it's up to you, you can set it to something like Ctrl-Alt-Shift-T or similar. Please note that this is a system-wide shortcut. We don't have an in-app shortcut to copy OTP, but it can be added if a system-wide one doesn't work for you.

**Comment by KaKi87** [comment]
`Ctrl-Alt-Shift-letter` require two hands, which means it's worse than a click.

**Comment by antelle** [comment]
Something like Alt-Shift-O, or depends on your keyboard layout. On macbooks the keyboard is different so I can't tell which modifiers can be more convenient for you since you're using Windows or Linux, but most likely there's a combination that can be pressed with one hand.
I have a feeling that we need to develop our own browser extension to simplify these things. Then it can be achieved much easier.

**Comment by KaKi87** [comment]
I understand.
PS : implementing something you never saw used anywhere is called innovating. 😉

**Comment by antelle** [comment]
If you decide you need an in-app shortcut for copying OTP, please let me know, I'll add it. I can understand why a system-wide one may not work for this case.

**Comment by KaKi87** [comment]
I figured out the next best shortcut to copy the OTP code would be `Alt + 2` (non-numpad, which actually means `Alt + é` in AZERTY or `Alt + @` in QWERTY), with `2` as in **2**FA.
Can this be implemented ?
Thanks.

**Comment by antelle** [comment]
It should work, what happens if you try setting it in app settings?

**Comment by KaKi87** [comment]
I see no entry to set a shortcut for the action of copying the OTP code

**Comment by antelle** [comment]
it's in the very end

**Comment by KaKi87** [comment]
![image](https://user-images.githubusercontent.com/21284089/92530507-c6710580-f22c-11ea-9e4e-cca9a3db5988.png)

**Comment by antelle** [comment]
scroll it

**Comment by antelle** [comment]
or, is it a browser version?

**Comment by KaKi87** [comment]
I'm using app.keeweb.info, yes.

**Comment by antelle** [comment]
I see, thanks, that was a confusion, so we should add a shortcut for web. Does `Ctrl + 2` also work on windows, or it's reserved for something?

**Comment by KaKi87** [comment]
> Does `Ctrl + 2` also work on Windows

What do you mean by "on Windows" ? If you mean the app, I'm not using it

**Comment by antelle** [comment]
On mac `alt - 2` is used to type the € sign. I know that similar things exist on Windows, but I already forgot it. That was my question, what would be more appropriate to use on Windows, alt- or ctrl-2?

**Comment by KaKi87** [comment]
None of `Ctrl+2` and `Alt+2` does anything system-wide on Windows, but in any browser on any OS, `Ctrl+2` focuses the second tab. Therefore `Alt` is the only choice.
Plus, a shortcut that prints special characters does not generate a conflict.

**Comment by antelle** [comment]
On macOS <kbd>Ctrl</kbd>+? is almost never used as a shortcut. Ok, thanks! I'll think what it should be.

**Comment by KaKi87** [comment]
Hello,
Any news on this ?
Thanks.

*PS : I found your portfolio by coincidence while looking for some projects related to argon2 password hashing, and I actually found your curriculum vitae very impressive. xD*

**Comment by antelle** [comment]
Hi! I haven't come to it yet, although it's planned to be fixed in the next version. It takes somewhat longer now with the situation in the world, I hope to be able to return to more active development soon.
Thanks 🙃

**Comment by KaKi87** [comment]
Thanks, is it released to app.keeweb.info already :)

**Comment by antelle** [comment]
It's building... https://github.com/keeweb/keeweb/runs/1470065411

**Comment by antelle** [comment]
It's rolled out, but CloudFlare seems to have issues with purging cache today, so it may be not available yet.
