### ISSUE TITLE
No synchronization from Keepass2Android to database (but OK from database to Keepass2Android)

### ISSUE THREAD

**Issue by frederetienne** [keeweb/keeweb#1590]
Hello everyone,
When I create a new entry in my phone on Keepass2Android, this new entry is not synchronised with my database online (https://app.keeweb.info/). I can see it on Keepass2Android, but I can't see it on the website.
But when I create a new entry on the website (or on my computer using KeeWeb app) : it is working fine : new entry is also available on my phone on Keepass2Android.
So synchronisation seems to be working in only one direction.

**Environment**
Keepass2Android Version 1.08b-r1
My database is hosted on google drive

Do you have any idea why ?

Thanks for your help

Frederic

**Comment by antelle** [comment]
Hi! If you have logs from KeeWeb, they can show the reason why it’s happening.

**Comment by frederetienne** [comment]
Here are the logs from KeeWeb : 

[INFO ] 2020-08-30T14:22:34.620Z [start-profiler] App started in 639ms: fetching=338ms, pre-init=428ms, loading modules=65ms, document ready=8ms, creating app model=4ms, loading configs=9ms, initializing modules=3ms, loading remote config=3ms, checking features=1ms, initializing storage=0ms, first view rendering=118ms, app ready event=0ms
[INFO ] 2020-08-30T14:22:34.625Z [updater] Next update check will happen in 81173s
[INFO ] 2020-08-30T14:22:34.625Z [usb-listener] Starting USB listener
[DEBUG] 2020-08-30T14:22:34.625Z [native-module-connector] Starting native module host
[INFO ] 2020-08-30T14:22:38.025Z [open:chuuuut] File open request
[INFO ] 2020-08-30T14:22:38.025Z [open:chuuuut] Open file from cache, will sync after load gdrive
[DEBUG] 2020-08-30T14:22:38.026Z [storage-cache] Load 155861c7-5430-193e-6590-7e3cada23c87
[DEBUG] 2020-08-30T14:22:38.034Z [storage-cache] Loaded 155861c7-5430-193e-6590-7e3cada23c87 4ms
[INFO ] 2020-08-30T14:22:38.034Z [open:chuuuut] Loaded file from cache null
[INFO ] 2020-08-30T14:22:38.255Z [file] Opened file chuuuut: 219ms, 500000 rounds, 23 kB
[DEBUG] 2020-08-30T14:22:38.256Z [app] Add last open file 155861c7-5430-193e-6590-7e3cada23c87 chuuuut gdrive 1TsUXz9ZQFH04BNamRVPt6QVo-GH0b1qt 0B9f-efX0RW83ZnNYd2F5OGM2VldCSzBzUjkyczZaUndGemxNPQ
[INFO ] 2020-08-30T14:22:38.385Z [open:chuuuut] Sync just opened file
[INFO ] 2020-08-30T14:22:38.399Z [sync:chuuuut] Sync started gdrive 1TsUXz9ZQFH04BNamRVPt6QVo-GH0b1qt {}
[INFO ] 2020-08-30T14:22:38.401Z [sync:chuuuut] Stat file
[DEBUG] 2020-08-30T14:22:38.401Z [storage-gdrive] Exchanging refresh token
[INFO ] 2020-08-30T14:22:38.402Z [storage-gdrive] HTTP request POST https://oauth2.googleapis.com/token
[INFO ] 2020-08-30T14:22:38.839Z [storage-gdrive] HTTP response POST https://oauth2.googleapis.com/token 200 {"status":"200","content-type":"application/json; charset=utf-8","vary":"Origin, X-Origin, Referer","content-encoding":"gzip","date":"Sun, 30 Aug 2020 14:22:39 GMT","server":"scaffolding on HTTPServer2","cache-control":"private","content-length":"273","x-xss-protection":"0","x-frame-options":"SAMEORIGIN","x-content-type-options":"nosniff","alt-svc":"h3-29=\":443\"; ma=2592000,h3-27=\":443\"; ma=2592000,h3-T051=\":443\"; ma=2592000,h3-T050=\":443\"; ma=2592000,h3-Q050=\":443\"; ma=2592000,h3-Q046=\":443\"; ma=2592000,h3-Q043=\":443\"; ma=2592000,quic=\":443\"; ma=2592000; v=\"46,43\""}
[INFO ] 2020-08-30T14:22:38.840Z [storage-gdrive] HTTP response 200
[DEBUG] 2020-08-30T14:22:38.841Z [storage-gdrive] Refresh token exchanged
[DEBUG] 2020-08-30T14:22:38.842Z [storage-gdrive] OAuth token received
[DEBUG] 2020-08-30T14:22:38.843Z [storage-gdrive] Stat 1TsUXz9ZQFH04BNamRVPt6QVo-GH0b1qt
[INFO ] 2020-08-30T14:22:38.843Z [storage-gdrive] HTTP request GET https://www.googleapis.com/drive/v3/files/1TsUXz9ZQFH04BNamRVPt6QVo-GH0b1qt?fields=headRevisionId
[INFO ] 2020-08-30T14:22:39.330Z [storage-gdrive] HTTP response GET https://www.googleapis.com/drive/v3/files/1TsUXz9ZQFH04BNamRVPt6QVo-GH0b1qt?fields=headRevisionId 200 {"status":"200","expires":"Sun, 30 Aug 2020 14:22:40 GMT","date":"Sun, 30 Aug 2020 14:22:40 GMT","cache-control":"private, max-age=0, must-revalidate, no-transform","vary":"Origin, X-Origin","content-type":"application/json; charset=UTF-8","content-encoding":"gzip","x-content-type-options":"nosniff","x-frame-options":"SAMEORIGIN","content-security-policy":"frame-ancestors 'self'","x-xss-protection":"1; mode=block","content-length":"97","server":"GSE","alt-svc":"h3-29=\":443\"; ma=2592000,h3-27=\":443\"; ma=2592000,h3-T051=\":443\"; ma=2592000,h3-T050=\":443\"; ma=2592000,h3-Q050=\":443\"; ma=2592000,h3-Q046=\":443\"; ma=2592000,h3-Q043=\":443\"; ma=2592000,quic=\":443\"; ma=2592000; v=\"46,43\""}
[INFO ] 2020-08-30T14:22:39.331Z [storage-gdrive] HTTP response 200
[DEBUG] 2020-08-30T14:22:39.331Z [storage-gdrive] Stated 1TsUXz9ZQFH04BNamRVPt6QVo-GH0b1qt 0B9f-efX0RW83ZnNYd2F5OGM2VldCSzBzUjkyczZaUndGemxNPQ 489ms
[INFO ] 2020-08-30T14:22:39.331Z [sync:chuuuut] Stat found same version, not modified
[INFO ] 2020-08-30T14:22:39.332Z [sync:chuuuut] Sync finished no error

**Comment by antelle** [comment]
Do I understand it right that this installation of KeeWeb is syncing ok, or there’s an issue in it?

**Comment by frederetienne** [comment]
It seems indded OK on KeeWeb. I think the issue is on Keepass2Android.

But logs on Keepass2Android seems also OK  

30/08/2020 19:46:36:537 -- DatabaseSettingsActivity.OnPause
30/08/2020 19:46:36:540 -- Timeout start
30/08/2020 19:46:36:553 -- GroupActivity.OnStart
30/08/2020 19:46:36:554 -- GroupActivity.OnResume
30/08/2020 19:46:36:554 --  DatabaseIsUnlocked=True
30/08/2020 19:46:36:554 -- Timeout cancel
30/08/2020 19:46:36:565 -- File flags: 455
30/08/2020 19:46:37:96 -- DatabaseSettingsActivity.OnStop
30/08/2020 19:46:37:98 -- DatabaseSettingsActivity.OnDestroyTrue
30/08/2020 19:46:40:52 -- status message: Initializing...
30/08/2020 19:46:40:53 -- status submessage: 
30/08/2020 19:46:40:84 -- status message: Synchronisation de la base de données mise en cache…
30/08/2020 19:46:40:84 -- status submessage: Chargement du fichier source…
30/08/2020 19:46:45:598 -- GroupActivity.OnPause
30/08/2020 19:46:45:598 -- Timeout start
30/08/2020 19:46:45:613 -- DatabaseSettingsActivity.OnCreate
30/08/2020 19:46:45:614 -- DatabaseSettingsActivity:apptask=
30/08/2020 19:46:45:646 -- DatabaseSettingsActivity.OnStart
30/08/2020 19:46:45:647 -- DatabaseSettingsActivity.OnResume
30/08/2020 19:46:45:647 --  DatabaseIsUnlocked=True
30/08/2020 19:46:45:647 -- Timeout cancel
30/08/2020 19:46:46:190 -- GroupActivity.OnStop

**Comment by antelle** [comment]
What happens if you open the file from Google Drive after changing it in KeeWeb, do you see the changes there?

**Comment by frederetienne** [comment]
Yes : if I do the modification in Keeweb from my desktop, I can see the changes from https://app.keeweb.info/
And I also can see changes in Keepass2Android
So keeweb works fine, I think.
But when I do modificaiton in Keepass2Android, I can not see the changes in https://app.keeweb.info/, and no changes also in my desktop.

**Comment by antelle** [comment]
If you do the change, then download the file from Google Drive and open it in KeeWeb from there - do you see the vhange?

**Comment by frederetienne** [comment]
I found out. I renamed my database, and add manually all modifications I made from my phone since last OK synchronisation.

It seems to be working now. I don't really know what happened.

Thanks a lot Antelle for your support.
