### ISSUE TITLE
 Error opening App with MS Edge

### ISSUE THREAD

**Issue by maurerle** [keeweb/keeweb#1591]
**Describe the bug**
I get an error in the console when opening https://app.keeweb.info/ from non-chromium-Edge
`SCRIPT5009: 'TextEncoder' is not defined`

The page is just left plain empty.

**To Reproduce**
1. Go to https://app.keeweb.info

**Environment**
Microsoft Edge 44.18362.449.0
Microsoft EdgeHTML 18.18363
Windows 10 1909

**Other Information**
Coming from https://github.com/jhass/nextcloud-keeweb/issues/158 this has to do with missing support for the TextEncoder in old Edge https://caniuse.com/#feat=textencoder

This should at least show some "not supported" message to non-techy end users

**Comment by antelle** [comment]
Can this version of Edge be updated, or it's the last one for this OS?

**Comment by antelle** [comment]
(closed by mistake; if it doesn't update, we should put it back indeed)

**Comment by antelle** [comment]
Fixed, deployed to [beta.keeweb.info](https://beta.keeweb.info), will be available in production soon.
