### ISSUE TITLE
Onedrive Configuration Selfhosted

### ISSUE THREAD

**Issue by BHAALOL** [keeweb/keeweb#1592]
[EN|Google Translate]

Hello,
I followed the guide to add one drive (https://github.com/keeweb/keeweb/wiki/Dropbox-and-GDrive#onedrive)
But I don't understand where I should add the line "onedriveClientId" I can't find the file "config.json" can you give me the structure of the file.

thank you in advance

[FR|Original]

Bonjour,
J'ai suivi le guide pour ajouter one drive (https://github.com/keeweb/keeweb/wiki/Dropbox-and-GDrive#onedrive)
Mais je ne comprend pas où je doit ajouter la ligne "onedriveClientId" je ne trouve pas le fichier "config.json" pouvez vous me donner la structure du fichier.

merci d'avance

**Comment by antelle** [comment]
Hi! config.json is described on this page: https://github.com/keeweb/keeweb/wiki/Configuration#json-app-config

**Comment by minecraftchest1** [comment]
I cannot figure out what to add. Please make it more clear.

**Comment by antelle** [comment]
Are you self-hosting KeeWeb or just using app.keeweb.info? If it's app.keeweb.info or the desktop app, this guide doesn't apply to you and it should just work.

**Comment by minecraftchest1** [comment]
I am using the self-hosted on my raspberry pi, and I got it half-way working. It asks for the onedrive login, but then gives me an error when redirecting afterwards.

**Comment by antelle** [comment]
Well, then you need to go through the setup. What you're probably missing, is the redirect uri, I'd suggest looking into this part of OneDrive configuration.
