### ISSUE TITLE
Invalid SSL certificate

### ISSUE THREAD

**Issue by ottahe** [keeweb/keeweb#1596]
I wonder if I'm the only one that gets this error during the last days. The message is:

Error 526
Ray ID: 5d03f32fffd06a71 •
2020-09-09 21:19:52 UTC
Invalid SSL certificate

You
Browser Working

London
Cloudflare Working

app.keeweb.info
Host Error

What happened?
The origin web server does not have a valid SSL certificate.

**Comment by antelle** [comment]
Hi! That’s strange, which browser it is?

**Comment by ottahe** [comment]
This is Chrome Version 83.0.4103.61.

**Comment by antelle** [comment]
To be honest, I don't know what to troubleshoot it. Does it happen from all locations? How often do you see this page? What happens in Incognito or another browser?

**Comment by ottahe** [comment]
I have this only on one notebook since last week. It happened thrice on Wednesday, yesterday only one time, today none so far. This is a company notebook, I'm not even local admin, so I can't simply install a new chrome browser or something else. I haven't seen that on another notebook with firefox or other android devices with chrome. I'll check with firefox and chrome on both notebooks.

**Comment by ottahe** [comment]
Some minutes after I sent the previous message it happened again. Can you see the Ray ID or something else in your logs at this certain time?

Ray ID: 5d11c4c98f3cfa44 2020-09-11 13:34:52 UTC
https://app.keeweb.info/oauth-result/gdrive.html?state=2e6f82a728d1dca61b0519de2227f40acb333708d216c98e428d768f83cdc2dfa77462aa4f0474b96c1950fc08a82a626d390cb07963fa01b09b8eab0295e304&code=4%2F4AFm67uRmOxlfcNOODMN9kTogmBWtZU3MY0OjPgVyL5Yo-9Q7j_YmlCHL9aJkzoEy_QWvR0F4Re0sonnmgUXJus&scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive

**Comment by antelle** [comment]
So it happens only from one laptop, right? Is this laptop connected through a proxy, so that it intercepts https connections?

**Comment by ottahe** [comment]
It's connected via a vpn-connection and there must be a proxy, because certain sites are blocked. But I haven't got this error before last week and synchronization works ok every 15 minutes except this few occurences during a day.

**Comment by antelle** [comment]
Very weird, I’ll try asking CloudFlare

**Comment by antelle** [comment]
Since logging on CloudFlare is available only for Enterprise accounts, I've enabled logging in GCP. Could you please try the request tomorrow or later, and if the error happens again, try loading something like https://app.keeweb.info/?skip_cache to make sure the request is not served from cache. If it fails, please paste all request and response http headers here, maybe there will be a hint inside. For example, you can record one network request and attach a HAR file with it here: [how to do it](https://support.zendesk.com/hc/en-us/articles/204410413-Generating-a-HAR-file-for-troubleshooting).

**Comment by ottahe** [comment]
Ok, I started the recording of requests.

**Comment by antelle** [comment]
You just need one of them, where it fails. I'd like to warn you that if you're loading your kdbx file from a cloud provider (e.g. from Dropbox), and you leave the recording during loading, the dump will include your file content, so if it's the case, it's better not to send it in this case and just extract HTTP headers.

**Comment by ottahe** [comment]
It happened fast this time. I deleted a big portion from the orginal line 162, the result from the reload.


[keeweb.short.zip](https://github.com/keeweb/keeweb/files/5211781/keeweb.short.zip)

**Comment by ottahe** [comment]
It also happened on the Linux-notebook with Firefox in the meantime:

Error 526
Ray ID: 5d14723babaebbac • 2020-09-11 21:22:48 UTC
Invalid SSL certificate
You Browser Working
London Cloudflare Working
app.keeweb.info Host Error
What happened?

The origin web server does not have a valid SSL certificate.
What can I do?
If you're a visitor of this website:

Please try again in a few minutes.
If you're the owner of this website:

The SSL certificate presented by the server did not pass validation. This could indicate an expired SSL certificate or a certificate that does not include the requested domain name. Please contact your hosting provider to ensure that an up-to-date and valid SSL certificate issued by a Certificate Authority is configured for this domain name on the origin server. Additional troubleshooting information here.

Cloudflare Ray ID: 5d14723babaebbac Your IP: 2003:ca:e747:c300:21a:80ff:fe57:ad1e Performance & security by Cloudflare

**Comment by antelle** [comment]
Thanks for the detailed info!

What I know now:
- the request looks perfectly OK
- I don't see it in GCS HTTP logs, most likely it's dropped on the handshake phase
- next request sent by your browser is visible in logs (with HTTP referrer set to the failed request url), and it returns 200 to you
- CloudFlare analytics shows that 526 HTTP errors happened for ≈1% of users last day

I've submitted a support ticket to CloudFlare, let's see what they reply.

**Comment by antelle** [comment]
Meanwhile, to mitigate the issue I've changed the HTTP connection mode on CF from Full (Strict) to Full, so the issue shouldn't happen for you now. Please let me know you still see it!

**Comment by antelle** [comment]
I see that 526 errors are going down, so I believe the issue is now mitigated, and the actual fix is being discussed with CloudFlare. Thank you for bringing my attention to this topic! I didn't realize that we've been returning these errors and there's no alert about it unfortunately.
