### ISSUE TITLE
Dropbox sync

### ISSUE THREAD

**Issue by daltinkurt** [keeweb/keeweb#1597]
I installed app to sifrem.daltinkurt.com.

dropbox settings are below:
![ScreenShot_20200911220802](https://user-images.githubusercontent.com/3593684/92963539-4b515e80-f47b-11ea-98d5-85388cbdf89f.png)
![ScreenShot_20200911215956](https://user-images.githubusercontent.com/3593684/92962807-345e3c80-f47a-11ea-902d-d722599593a1.png)

I filled the app&client secret passwords and folder name to config.file:
```
...
"dropbox": true, 
"dropboxFolder": "sifrem_daltinkurt_com", 
"dropboxAppKey": "yc9xxx",
"dropboxSecret": "td9xxx",
...

```

when i click to dropbox (file open screen) icon it says:

> Error (400)
> It seems the app you were using submitted a bad request. If you would like to report this error to the app's developer, include the information below.
> 
> More details for developers
> No scope requested can be granted for this app.
> 

what am i doing wrong?

(gdrive settings are working)

**Comment by antelle** [comment]
Hi! Thanks for the report, looks like this was a recent change in Dropbox because it offers to migrate KeeWeb to be able to use scopes, I guess if I do it, this will break too. So scopes have to be supported in KeeWeb, I'll look into it soon.

**Comment by antelle** [comment]
The fix is live, now your setup should work

**Comment by synonez** [comment]
I encountered this problem in version 1.18.7
