### ISSUE TITLE
KDBX 4 Compatibility issue: Non-standard format of encryption rounds

### ISSUE THREAD

**Issue by mitchellknight** [keeweb/keeweb#1598]
**Describe the bug**
It appears that KeeWeb saves the encryption rounds in a non-standard format (using 4 bytes instead of 8). Some KDBX compatible apps just assume that missing bytes are zeros (and everything works fine) but apps that don't make this assumption will have issues.

**To Reproduce**
1. Create a database with KDBX 4 / AES / 300000 key encryption rounds.
2. Save database.
3. Attempt to open database in KDBX 4 compatible software (KeePassium for iOS in my case).
4. Database fails to open.

**Expected behavior**
Database opens and is ready for use.

**Environment**
macOS Catalina (KeePass) / iOS - Latest (KeePassium)

**Kdbx File**
Issue happened after I changed my KDBX 3 database to KDBX 4. Issue may not impact KDBX 3 files.

**Logs**
N/A.

**Additional Details**
The developer behind KeePassium is going to work around this specific issue on his end but it would be a good idea to fix the issue in KeeWeb in case other implementations have the same problem.

**Comment by antelle** [comment]
Hi! Thanks for the detailed report! Just found how it's saved in KeePass and it's indeed Uint64 instead of Uint32 in KeeWeb. A fix is coming soon...

**Comment by antelle** [comment]
Fixed, deployed to [beta.keeweb.info](https://beta.keeweb.info), will be available in production soon.
