### ISSUE TITLE
KeeWeb fails to open: org.freedom.secrets: Timeout was reached

### ISSUE THREAD

**Issue by baschi29** [keeweb/keeweb#1600]
**Describe the bug**

After changing from x11 to wayland with kde plasma, KeeWeb isn't able to start anymore an throws the following error:

Error loading an app: Error: Error calling StartServiceByName for org.freedesktop.secrets: Timeout was reached

Reinstalling and restarting didn't fix the problem. 

**To Reproduce**
1. Download and install the .deb file from the KeeWeb website
2. Try to start KeeWeb
3. See error

**Expected behavior**
KeeWeb should start normally. I suspect this is an issue with the keyring. 

**Screenshots**

**Environment**
Kubuntu 20.04
KDE Plasma 5.18.5
KDE Framework 5.68.0
KeeWeb 1.15.6

**Kdbx File**

**Logs**

**Comment by antelle** [comment]
What happens if you install `gnome-keyring`?

**Comment by baschi29** [comment]
I have gnome-keyring already installed. Version 3.36.0.

**Comment by antelle** [comment]
Interesting, this means node-keytar somehow can't work with this setup. If you put an empty file called `disable-keytar` into the config folder, it should work, but it's not the best workaround indeed.

**Comment by baschi29** [comment]
That indeed works for the time being. Thanks!

**Comment by baschi29** [comment]
Just a quick heads up, after upgrading to Kubuntu 21.04 and KeeWeb 1.18.7 the issue no longer persists.
Might have been fixed by a newer version of node-keytar or the KeeWeb update itself :)

Unfortunately i cannot check if the issue still exists in the older Ubuntu version, but I think it can be closed for the time being.

**Comment by KaKi87** [comment]
Hello,

I'm suddenly experiencing this issue on Pop OS 22.04, and `touch ~/.config/KeeWeb/disable-keytar` didn't fix it.

Thanks
