### ISSUE TITLE
Any way to export data from Keeweb 

### ISSUE THREAD

**Issue by piclemx** [keeweb/keeweb#1602]
Hey, I want to try another solution for my password manager. I was hoping that a feature exist to export my db into a format that will be importable. Does someone know a way to do it?

**Comment by Harald-Koschinski** [comment]
Every keepass2 program is able to read the file in a native way. 
Do you want to leave the keepass2 world?

**Comment by antelle** [comment]
As already said above, KeeWeb is using the same file format as other KeePass apps, so it should work there as well. If you're going to export it to another password manager, there are several ways:
* export to XML or HTML from KeeWeb
* open the KDBX file in any other KeePass-compatible app, they have more export options
* load your KDBX file in the app where you would like to migrate, this format is often supported
