### ISSUE TITLE
Support userChrome.css OR userContent.css with Eelectron

### ISSUE THREAD

**Issue by homhom1416** [keeweb/keeweb#1603]
Override the CSS with userContent.css OR userChrome.css like firefox Or joplin ...

Just for more customization ...

**Comment by antelle** [comment]
Hi! We support custom themes, they’re explained here: https://github.com/keeweb/keeweb/wiki/Plugins, one of possibilities is defining a theme where you can write any css.
Just css, without signatures, would be a bit risky for a password manager.

**Comment by homhom1416** [comment]
I tried to do it before 6 months and failed to automatic load plugin every program launch .. i might retry again and see ...

**Comment by antelle** [comment]
If you submit it to plugins.keeweb.info, it will be possible, in the desktop version persistent plugins are not solved yet

**Comment by homhom1416** [comment]
Ok but it's easier than long way ... what you think if supported it and it's disabled by default like Firefox 59 .... and there is an option in advance options to enable it ..

**Comment by antelle** [comment]
Maybe we can have a sort of simple themes that can be saved to user settings. Either way, we need this to be solved first: #1254

**Comment by homhom1416** [comment]
I hope good future for keeweb ...
