### ISSUE TITLE
Auto Backup When Save with Electron ..

### ISSUE THREAD

**Issue by homhom1416** [keeweb/keeweb#1605]
How to backup locally database when save ..? i didn't find any option or document talking about that .. i think it's important thing ..

**Comment by antelle** [comment]
It's here, in settings:

<img width="478" alt="Screen Shot 2020-09-22 at 17 22 49" src="https://user-images.githubusercontent.com/633557/93902803-481a6600-fcf8-11ea-8c77-c2b75232c9e8.png">

**Comment by homhom1416** [comment]
Good to see it! ... what are available variables other than {date} ? ..

**Comment by antelle** [comment]
There are no other variables supported. What would you like to see there? Maybe we can add it if it's useful.

**Comment by homhom1416** [comment]
Nothing special .. But i am thinking to make a cycle of 10 files ... Maybe it's a different issue .

**Comment by antelle** [comment]
Now that’s not possible, it’s https://github.com/keeweb/keeweb/issues/873
