### ISSUE TITLE
Network error on loading kdbx from gdrive (chrome only)

### ISSUE THREAD

**Issue by ottahe** [keeweb/keeweb#1610]
Since around 10 days ago I noticed that synchronization was failing again. After exiting the app and reconnecting, I couldn't connect to GDrive anymore, see the attached har-file. KeeWeb was not alone, Google Drive itself showed errors on connection too, but it was working tho. I can edit files or download them. What makes me wonder is that these errors do not appear in Firefox, everything is working fine there. So it doesn't look like KeeWeb issue at all. What could be the reason for this?

Apart from this, I have some questions about the keeweb/app code. What would be a good place to ask them?

![2020-09-26 23_26_11-Window](https://user-images.githubusercontent.com/35665727/94373592-a97e7280-0106-11eb-87b6-a9760d50781d.png)
![2020-09-26 23_28_16-Window](https://user-images.githubusercontent.com/35665727/94373600-c024c980-0106-11eb-9612-242d5e4e3868.png)
![2020-09-26 23_28_27-Window](https://user-images.githubusercontent.com/35665727/94373602-c0bd6000-0106-11eb-98c5-7a9211b2eb23.png)

edit(@antelle) removed network capture

**Comment by antelle** [comment]
Hi! What happens if you open KeeWeb in incognito in the same browser, does it work?

**Comment by antelle** [comment]
Better not to paste your network log, it contains your Google access token.

**Comment by antelle** [comment]
But wait, since you're saying "Google Drive itself showed errors on connection", I can't help here, you need to understand why.
