### ISSUE TITLE
Nextcloud/keeweb and plugin firefox

### ISSUE THREAD

**Issue by francoisparreauxey** [keeweb/keeweb#1611]
Hello,
I don't succeed in configuring Keeweb on my computer.
I use windows10, install keeweb heavy client. install works but connection to db no. When connecting to webdav/nextcloud, it returns "No Last-Modified header".
I install Keeweb on nextcloud. I succeed in running it thanks to double click on my .kdbx file. it opens !
But when trying to install plugging (firefox plugging) it refuses to open catalog : "error loading plugging"
is there any wwork around to obtain pluggin.
I try to open url using :'https://plugins.keeweb.info/plugins/keewebhttp'... but nothing happen.
Do you have any idea ?
thks

**Comment by antelle** [comment]
Hi! I think this should be solved on Nextcloud configuration, so that it returns Last-Modified header. Not sure how to configure it, there should be guides on internet.
KeeWebHttp plugin won't work on web, so it won't be possible to install it.

**Comment by francoisparreauxey** [comment]
What I did, is connect heavy client to my database in windows folder thanks to nextcloud windows client...
it works ... but not sure that .kdbx sync will work if I connect through nextcloud.
What do you think ?

**Comment by antelle** [comment]
I'm not sure how Nextcloud sync works, so I'm afraid I will give wrong answers here.
It's not different from syncing text files: if Nextcloud uploads what you do in this local folder, it should work.

**Comment by francoisparreauxey** [comment]
I gonna see
thks
