### ISSUE TITLE
Loading of KDBX file fails with Kdbx error Random not implemented

### ISSUE THREAD

**Issue by labiloute** [keeweb/keeweb#1612]
Hi Keeweb team.
First please let me thank you for this great project.

I've downloaded the files from latest keeweb version and uploaded them on my LAMP webserver.

But opening my KDBX file fails with a loading icon stuck. In the console, I can read the following :

Object { name: "KdbxError", code: "NotImplemented", message: "Error NotImplemented: Random not implemented", stack: "" }
keeweb:1:298251
    random http://webserver/keeweb/:1
    getBytes http://webserver/keeweb/:1
    o http://webserver/keeweb/:1

No more to debug, sorry if it's a known bug.

KeeWeb v1.15.7 (7140a2d, 2020-09-12)
Environment: web
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:78.0) Gecko/20100101 Firefox/78.0

**Comment by antelle** [comment]
Hi! It’s because of HTTP, if you host it on HTTPS, it should work. It’s strange that it displays such message though, this should be checked on app start.

**Comment by antelle** [comment]
Fixed the check, next version will show a better error.

**Comment by labiloute** [comment]
Hi @antelle .
I would have prefered to make the choice of playing insecure or not by myself.
In some extreme case I would be happy to find an insecure version of KeeWeb.
Cheers
