### ISSUE TITLE
KeeWeb freezes Desktop for a few seconds on Ubuntu

### ISSUE THREAD

**Issue by monsieurhannes** [keeweb/keeweb#1613]
**Describe the bug**
When I use autotype on Ubuntu 20.04.1 both KeeWeb but basically the whole desktop freezes. I can move the mouse, but can't click anything. 
I had to change the autotype-shortcut to be able to use KeeWeb in Firefox but it's a brand new installation of KeeWeb and I had the same problem before I reinstalled it - blaming my configuration, now I'm not so sure anymore.

**To Reproduce**
1. (Change the autotype shortcut from ALT+SHIFT+T to CTRL+SHIFT+T)
2. Run the autotype on a homepage in e.g. Firefox
3. The desktop freezes, music and other processes are still running, but nothing is "clickable".
4. After a few seconds the username and password get filled and everything is back to normal.

**Expected behavior**
It shouldn't freeze and fill out the password immediately

**Environment**
`Linux 5.4.0-48-generic #52-Ubuntu SMP x86_64 x86_64 x86_64 GNU/Linux`

**Kdbx File**
Problems exist even with a newly created DB

**Logs**
As you can see it takes quite a while to open this "extremely long dict". That's the time for a almost empty KDBX-file with one entry! The dict gets longer with the size of the KDBX.
```
[DEBUG] 2020-10-02T17:45:16.819Z [auto-type] Auto type event null
[DEBUG] 2020-10-02T17:45:16.821Z [auto-type] Getting window info
[INFO ] 2020-10-02T17:45:16.829Z [launcher] spawn xdotool: 0, 8ms
Sign in to GitHub · GitHub - Chromium
<<<removed>>>
[DEBUG] 2020-10-02T17:45:16.829Z [auto-type] Window info <<<removed>>> Sign in to GitHub · GitHub - Chromium null
[DEBUG] 2020-10-02T17:45:19.146Z [auto-type] Entry selected {"<<<extremely long dict>>>}
[DEBUG] 2020-10-02T17:45:19.147Z [auto-type] Hide window
[DEBUG] 2020-10-02T17:45:19.170Z [storage-file] Stop watch dir <<<removed>>>
[DEBUG] 2020-10-02T17:45:19.258Z [auto-type] Getting window info
[INFO ] 2020-10-02T17:45:19.268Z [launcher] spawn xdotool: 0, 9ms
Sign in to GitHub · GitHub - Chromium
<<<removed>>>
[DEBUG] 2020-10-02T17:45:19.268Z [auto-type] Window info <<<removed>>> Sign in to GitHub · GitHub - Chromium null
[INFO ] 2020-10-02T17:45:19.268Z [auto-type] Active window matches
[DEBUG] 2020-10-02T17:45:19.268Z [auto-type] Start {USERNAME}{TAB}{PASSWORD}{ENTER}
[DEBUG] 2020-10-02T17:45:19.269Z [auto-type] Parsed [op:USERNAME,op:TAB,op:PASSWORD,op:ENTER]
[DEBUG] 2020-10-02T17:45:19.269Z [auto-type] Resolved [******,key:tab,[*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*],key:enter]
[INFO ] 2020-10-02T17:45:19.526Z [launcher] spawn xdotool: 0, 257ms
[INFO ] 2020-10-02T17:45:19.557Z [launcher] spawn xdotool: 0, 31ms
[INFO ] 2020-10-02T17:45:19.681Z [launcher] spawn xdotool: 0, 123ms
[INFO ] 2020-10-02T17:45:19.800Z [launcher] spawn xdotool: 0, 119ms
[INFO ] 2020-10-02T17:45:19.906Z [launcher] spawn xdotool: 0, 106ms
[INFO ] 2020-10-02T17:45:20.008Z [launcher] spawn xdotool: 0, 102ms
[INFO ] 2020-10-02T17:45:20.117Z [launcher] spawn xdotool: 0, 109ms
[INFO ] 2020-10-02T17:45:20.229Z [launcher] spawn xdotool: 0, 111ms
[INFO ] 2020-10-02T17:45:20.342Z [launcher] spawn xdotool: 0, 113ms
[INFO ] 2020-10-02T17:45:20.424Z [launcher] spawn xdotool: 0, 82ms
[INFO ] 2020-10-02T17:45:20.553Z [launcher] spawn xdotool: 0, 129ms
[INFO ] 2020-10-02T17:45:20.680Z [launcher] spawn xdotool: 0, 127ms
[INFO ] 2020-10-02T17:45:20.807Z [launcher] spawn xdotool: 0, 127ms
[INFO ] 2020-10-02T17:45:20.937Z [launcher] spawn xdotool: 0, 130ms
[INFO ] 2020-10-02T17:45:21.068Z [launcher] spawn xdotool: 0, 130ms
[INFO ] 2020-10-02T17:45:21.180Z [launcher] spawn xdotool: 0, 112ms
[INFO ] 2020-10-02T17:45:21.295Z [launcher] spawn xdotool: 0, 115ms
[INFO ] 2020-10-02T17:45:21.408Z [launcher] spawn xdotool: 0, 113ms
[INFO ] 2020-10-02T17:45:21.443Z [launcher] spawn xdotool: 0, 35ms
[DEBUG] 2020-10-02T17:45:21.443Z [auto-type] Complete 2174ms
```

**I love the app, thanks for your work!**

**Comment by antelle** [comment]
Hi! Does it freeze for ≈2.1 second, as it is in logs, i.e. during auto-type?

**Comment by monsieurhannes** [comment]
Hej!
I just measured with my phone on the side. 45-50 seconds with my regular file, 30 seconds with the new KDBX, with one entry.
One thing I forgot to mention in the workflow:
2.1 - I do the CTRL-SHIFT-T-combo and then I select the right entry. I can check how it works with a proper entry with the right name.

**Comment by antelle** [comment]
Interesting. Well the log says `2366ms` which is ≈2.4s, I wonder what happens during these 30s?

**Comment by antelle** [comment]
Let's check on v1.17, it may fix this

**Comment by monsieurhannes** [comment]
Hej @antelle,
sorry for the late reply. It still lags a bit when using auto-type, but it got faster! However, with the new auto-type I have issue https://github.com/keeweb/keeweb/issues/1738.
So I'm back to the legacy mode for the time being, but I saw that you're working on it in this very moment! Thanks for your work! It's a great app and I was able to convert a lot of friends and family who haven't used a password manager before. :1st_place_medal: 

Once the newest version is out I can tell you how it feels!

**Comment by antelle** [comment]
Cool, glad to hear! The issue you mentioned already resolved, I'm already preparing a release with it, it should appear in a couple of hours.

**Comment by antelle** [comment]
[v1.17.2](https://github.com/keeweb/keeweb/releases/tag/v1.17.2) is released, now it should work as expected. Let's see if everything is ok with it for you!

**Comment by monsieurhannes** [comment]
So great! 
It works again, just as smooth as on Windows! I wonder why I was the only one reporting this issue...
Thank you so much!
