### ISSUE TITLE
ubuntu 20.04 snap installation is not starting

### ISSUE THREAD

**Issue by bastos77** [keeweb/keeweb#1614]
**Describe the bug**
When I start keeweb from terminal it is not starting. Instead
`/snap/keeweb/x1/app/keeweb: error while loading shared libraries: libnss3.so: cannot open shared object file: No such file or directory`
appears
**To Reproduce**
1. open terminal
2. type `keeweb`

**Expected behavior**
keeweb should start

**Environment**
Ubuntu 20.04.1 LTS
Gnome 3.36.3
Windowsmanager x11
keeweb snap installation

**Comment by antelle** [comment]
Hi! That's #1473
