### ISSUE TITLE
Update Electron to version 10

### ISSUE THREAD

**Issue by AlexWayfer** [keeweb/keeweb#1617]
**Is your feature request related to a problem? Please describe.**

After upgrading Electron (in Arch Linux) from 9 to 10 there was the "Native module host crashed" error.

https://aur.archlinux.org/packages/keeweb/#comment-770482

**Describe the solution you'd like**

Upgrade Electron dependency to version 10.

**Describe alternatives you've considered**

Arch Linux package now locked at Electron 9.

**Additional context**

I know, it's not necessary, but I guess it'll be better, we should go toe to toe with dependencies.

**Comment by antelle** [comment]
Hi! Native modules must be recompiled for major versions, upgrading without doing it will cause thus error.
It's indeed locked to Electron v9, new version of KeeWeb will have new Electron as well.

**Comment by AlexWayfer** [comment]
> It's indeed locked to Electron v9, new versions of KeeWeb will have new Electron as well.

I thought it can be an issue for a new version of KeeWeb…

**Comment by antelle** [comment]
Upgrading Electron (as well as most of other dependencies) to a new major version always comes with incompatible things, that's why it's not possible to do it without manual work.

**Comment by AlexWayfer** [comment]
> Upgrading Electron (as well as most of other dependencies) to a new major version always comes with incompatible things, that's why it's not possible to do it without manual work.

I understand, but I thought this issue can be something like "oh, we should upgrade this dependency and do necessary manual work!".
