### ISSUE TITLE
Recommended way to share among a team?

### ISSUE THREAD

**Issue by anandaroop** [keeweb/keeweb#1618]
Thank you for developing KeeWeb! 

I work with a small team of volunteers who would like to maintain a team-shared password vault. But we are having trouble making KeeWeb work as a shared resource.

Our first thought was to share the file via Google Drive, but that leads to this permission grant dialog which seemed overly broad, as it seeks read/write permission on the user's _entire_ Drive.

<img height="400" src="https://user-images.githubusercontent.com/140521/96531903-b2bbb480-1258-11eb-92d7-eed5f38197e7.png" />

Our second thought was to try DropBox. This offers a more restricted scope (to files in the `Apps > KeeWeb` directory) which was reassuring. But sharing files to teammates via DropBox places them outside of that directory, thus making them inaccessible to KeeWeb.

Is there a recommended way to share a kdbx file among a team, that doesn't require an overly broad permission grant?

**Comment by thefiredragon** [comment]
We‘re using keeweb in our Team over a self hosted web server.
Our kdbx databases use 2fa auth over an key file and a password.
For the storage connection we‘re using WebDAV. This working fine.

Best Regards

Von meinem iPhone gesendet

**Comment by anandaroop** [comment]
I see, thanks! I was wondering if there was a way to do this without setting up a WebDAV server.

Or, alternatively, if a more restrictive grant could be used here, e.g. `https://www.googleapis.com/auth/drive.file` instead of `https://www.googleapis.com/auth/drive` ([reference](https://developers.google.com/identity/protocols/oauth2/scopes#drive))

https://github.com/keeweb/keeweb/blob/7140a2d89417ffb4722502b3d758b0f774a4ac92/app/scripts/storage/impl/storage-gdrive.js#L249

**Comment by antelle** [comment]
Hi! I think in your case best would be using WebDAV, as it's already mentioned above. Unfortunately the scope you mentioned (drive.file) won't cover what we need because you don't select files in KeeWeb, so we need to be able to read all files.
