### ISSUE TITLE
Colour rendering is wrong on Linux

### ISSUE THREAD

**Issue by NeroVanbiervliet** [keeweb/keeweb#1621]
**Describe the bug**

Colours render wrong on Linux.

**To Reproduce**
Open the application on Linux. Blue will be purple

**Screenshots**
Left = screenshot from the README
Right = my screenshot
![purple-is-blue](https://user-images.githubusercontent.com/7568919/97451539-1ff3d780-1934-11eb-9231-84c3e8a897d5.png)

**Solution**
This is a know bug in Electron.
Solve by adding the following in [main.js](https://github.com/keeweb/keeweb/blob/master/desktop/main.js)
```javascript
app.commandLine.appendSwitch('force-color-profile', 'srgb');
```

**Comment by NeroVanbiervliet** [comment]
I'll make a PR in one of the coming days

**Comment by antelle** [comment]
What a find, thanks 💯! I'll add it for sure.
Which OS is that, to verify the fix?

**Comment by NeroVanbiervliet** [comment]
Cool, thanks! On Linux (Ubuntu 20.04)
