### ISSUE TITLE
SCP support

### ISSUE THREAD

**Issue by Enlightments** [keeweb/keeweb#1624]
Hi guys

First, I want to thank you for your awesome product (it really solved my conspiracy theory problem).

I would like to request a feature in which the keeweb can remotely read from an SSH server using SCP or something similar.
So that we can simply host our password files on a private VPS without needing to set up a WebDav.

Thank you all and keep going

**Comment by antelle** [comment]
Hi! For now that's not planned and most likely won't be. You can create a plugin with this feature though.

**Comment by antelle** [comment]
Duplicate of #103
