### ISSUE TITLE
Help forcing config.json

### ISSUE THREAD

**Issue by acascianelli** [keeweb/keeweb#1626]
Trying to get KeeWeb to use a config.json file and for the life of me I can't figure out what I'm missing.  I had this working before, but when I upgraded KeeWeb to the current version, I forgot to save my previous index.html.

I'm currently running KeeWeb in a subfolder on my web server called 'KeeWeb' (www.asdf.com/KeeWeb), so the config.json file is under that folder.

I modify the kw-config metatag to look like this:

**meta name="kw-config" content="config.json"**

Getting the generic "Error loading app" error when attempt to go to the page.  No errors in the webserver logs.

Pretty simple config.json:

```
{
        "settings": {
                "locale":               "en",
                "theme":                "te",
                "cacheConfigSettings":  false,
                "canOpenDemo":          false,
                "canCreate":            false,
                "canOpenSettings":      false,
                "dropbox":              false,
                "gdrive":               false,
                "onedrive":             false,
                "webdav":               false
        }
}
```

**Comment by antelle** [comment]
Hi! What do you see in browser devtools logs?

**Comment by acascianelli** [comment]
Oh wow...I completely forgot about the browser developer tools...

[app] Error loading app config Malformed JSON

So it's complaining about my JSON config file?

**Comment by antelle** [comment]
Yes, most likely the json in config is broken. What is the contents of it?

**Comment by acascianelli** [comment]
```
{
        "settings": {
                "locale":               "en",
                "theme":                "te",
                "cacheConfigSettings":  false,
                "canOpenDemo":          false,
                "canCreate":            false,
                "canOpenSettings":      false,
                "dropbox":              false,
                "gdrive":               false,
                "onedrive":             false,
                "webdav":               false
        }
}
```

**Comment by antelle** [comment]
This seems to be valid, what do you see in Network panel in browser, does it successfully load this config?

**Comment by acascianelli** [comment]
I see it doing the GET for config.json, but doesn't look it's getting a 200 back from it.

**Comment by antelle** [comment]
Then you should fix this

**Comment by acascianelli** [comment]
I can hit the file if I browse to it.

**Comment by antelle** [comment]
What do you see in Network?

**Comment by acascianelli** [comment]
I found the problem...I had escape characters in the JSON file that were not being displayed when I was viewing the file...

**Comment by linuxmangr** [comment]
Hello, I setup this  project  [keeweb-local-server](https://github.com/vavrecan/keeweb-local-server)
And now I have  self hosted server my keeweb.
