### ISSUE TITLE
One Drive CORS issue

### ISSUE THREAD

**Issue by bendem** [keeweb/keeweb#1629]
I've tried to use keeweb to access my database file in onedrive entreprise (sharepoint) but the popup closes and nothing happens. I had to open the console to get a clue what's going on and apparently it's a CORS issue :

![image](https://user-images.githubusercontent.com/2681677/99964322-67368200-2d93-11eb-8109-6c2be5b38a06.png)

The network error code is ns_error_interception_failed (service worker interceptor failed).

Logs from the advanced settings:

```
[DEBUG] 2020-11-23T12:51:07.973Z [storage-onedrive] OAuth: popup opened
[DEBUG] 2020-11-23T12:51:10.172Z [storage-onedrive] OAuth code received
[INFO ] 2020-11-23T12:51:10.172Z [storage-onedrive] HTTP request POST https://login.microsoftonline.com/common/oauth2/v2.0/token
[ERROR] 2020-11-23T12:51:10.522Z [storage-onedrive] Error exchanging OAuth code network error
```

KeeWeb v1.15.7 (7140a2d, 2020-09-12)
Environment: web
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:84.0) Gecko/20100101 Firefox/84.0

Let me know if I can provide any other information.

**Comment by antelle** [comment]
Hi! Does it happen on regular, not enterprise accounts?

**Comment by bendem** [comment]
I don't have such an account so I wouldn't know, sorry.

**Comment by bendem** [comment]
I've created an account to test and it looks like it's working ok with that test account.

**Comment by antelle** [comment]
Okay, that's a bit more complicated, I need help here...

**Comment by bequiet88** [comment]
Hi there,

I experienced the same CORS error message with a Microsoft 365 enterprise tenant.

I found this [piece of documentation from Microsoft](https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-oauth2-auth-code-flow#redirect-uri-setup-required-for-single-page-apps).

Essentially, it's saying that you need to switch from type "web" to "spa" (single page application). This is different from what is documented in [KeeWeb's wiki](https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-oauth2-auth-code-flow#redirect-uri-setup-required-for-single-page-apps).

After I've done so in my app registration in Azure portal, I now receive a 401 error in KeeWeb even though with the same credentials I got this CORS error which actually means the the OAuth token was already issued (i.e. correct credentials) but just could not be sent back correctly.

![grafik](https://user-images.githubusercontent.com/2745963/102210046-f9810000-3ed1-11eb-9d5f-04dc7a086801.png)


Is it possible that the API call must be different for platform type "spa"?

**Comment by antelle** [comment]
Microsoft if always changing their OAuth client configuration for some reason, so I haven't pasted any instructions or screenshots to the KeeWeb wiki. Now there's SPA there and to be honest I have no idea what it changes, but if I enable it for my local client, it just works, so I assume there are no API changes required for that. Most likely it's something else that we need to change to support such accounts.

**Comment by antelle** [comment]
Just changed the production app to be SPA as well, for personal accounts everything seems to be working well.

**Comment by antelle** [comment]
I think I figured it out, we don't need to send the secret for SPA, otherwise it can generate 401. Uploaded a build to [beta](https://beta.keeweb.info?5), can you please give it a try?

**Comment by bequiet88** [comment]
yep, works now:
![grafik](https://user-images.githubusercontent.com/2745963/102393438-a34ab480-3fd8-11eb-9db5-adf507eae185.png)

but what surprised me a little bit, it just works and I dont have to set any of these
```
onedriveClientId: null
onedriveClientSecret: null
```
Also if I set them with my client ID & secret from Azure portal app registration, it behaves the same way as it does without them.

Thanks so much!

**Comment by antelle** [comment]
Ok, cool, then it will be released soon

**Comment by antelle** [comment]
Hm, I've found another issue with that, if we set up the app as SPA, it's not possible to exchange the token, so you need to re-authenticate every time, this is not cool.

**Comment by antelle** [comment]
From the [docs](https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-oauth2-auth-code-flow#redirect-uri-setup-required-for-single-page-apps):
> For refresh tokens sent to a redirect URI registered as spa, the refresh token will expire after 24 hours. Additional refresh tokens acquired using the initial refresh token will carry over that expiration time, so apps must be prepared to re-run the authorization code flow using an interactive authentication to get a new refresh token every 24 hours. Users do not have to enter their credentials, and will usually not even see any UX, just a reload of your application - but the browser must visit the login page in a top level frame in order to see the login session.

**Comment by antelle** [comment]
So, I've made the change, in v1.16.4 it can work in two modes:
1. if you configure app as WEB: then specify `onedriveClientId ` and `onedriveClientSecret`, it will work like it was before; that's how the default app is configured and it will remain like this;
2. if you configure your app as SPA: then specify only `onedriveClientId`, it will work for your case, however you will have to authorize once a day
