### ISSUE TITLE
Use a shared organization Gdrive folder to store password file

### ISSUE THREAD

**Issue by JEricaM** [keeweb/keeweb#1630]
Hi,
my organization would like to try Keeweb to store shared password.
We have gsuite so we would like to put the file inside a shared google drive folder. 
I've followed the WIKI and configured Gdrive successfully.

The "problem" is that it only let me see the folder and files inside my private Gdrive (organization account) and not my organization shared drive.

Is it possible to select a file inside a shared folder? if is not can I resolve the problem giving the permission (to all organization member) to read and edit the file inside my private folder?
I would like to set keeweb to open a specific file when loaded and don't have to manually select gDrive and which file open.

I've searched between the issues but I didn't found anything about this topic.

Thank so you much for Keeweb!

**Comment by antelle** [comment]
Hi! It's #618
