### ISSUE TITLE
How to correctly generate certificates for keeweb?

### ISSUE THREAD

**Issue by r2r200** [keeweb/keeweb#1634]
Hello!
Could you give an instruction how to generate correct dh.pem, cert.pem, key.pem for keeweb-docker-container, please?

I tried different parameters but have no success. I always get the error in general settings:
`[updater] Failed to register a service worker SecurityError: Failed to register a ServiceWorker for scope ('https://msk-mgmt01.youdo.corp/') with script ('https://msk-mgmt01.youdo.corp/service-worker.js'): An SSL certificate error occurred when fetching the script.`

And in docker container logs:
`[info] 8#8: *4 SSL_do_handshake() failed (SSL: error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown:SSL alert number 46) while SSL handshaking`
Thank you!

**Comment by antelle** [comment]
Hi! You mean how to generate these files or how to tell the container to use them?

**Comment by r2r200** [comment]
How to correctly generate

**Comment by antelle** [comment]
It's just a regular SSL certificate, you can google "how to generate a self-signed SSL certificate", there are plenty of tutorials on Internet: https://www.digitalocean.com/community/tutorials/openssl-essentials-working-with-ssl-certificates-private-keys-and-csrs

**Comment by r2r200** [comment]
Thank you! I'll try to do it again using this tutorial and write a result here.

**Comment by r2r200** [comment]
I made:
`openssl dhparam -out dh.pem 4096`
`openssl req -newkey rsa:2048 -nodes -keyout key.pem -x509 -days 365 -out cert.pem`

Though I have the same errors, I can see my certs were applied.

Thank you!

**Comment by antelle** [comment]
The certificate should be either valid, or trusted in the system, I assume, to make ServiceWorkers work.

**Comment by r2r200** [comment]
I made it in Firefox. Thank you for your help!
But I have one more question because I don't know how ServiceWorkers works. What does that error mean - the connection isn't secure for ServiceWorkers but it works? Or it doesn't work at all?

**Comment by antelle** [comment]
ServiceWorker is used for caching. KeeWeb will work, but it won't work offline if ServiceWorkers are broken.
