### ISSUE TITLE
Native Apple Silicon support

### ISSUE THREAD

**Issue by KovalevArtem** [keeweb/keeweb#1640]
Add full support for new processors Apple Silicon

**Comment by antelle** [comment]
Hi! There are several pieces here:
- [x] Apple Silicon support in Electron: done, they provide `darwin-arm64` artifact now
- [ ] native modules compilation for Apple Silicon, that's the hardest one here
- [ ] support in KeeWeb build system

I'm not sure if it's possible to cross-compile a native Electron module, i.e. if we can use a regular macOS runner have to wait until there's an Apple Silicon runner on GitLab actions.

**Comment by antelle** [comment]
I see that Electron folks used a secret keyword (`runs-on: apple-silicon`) to build on Apple Silicon: https://github.com/electron/electron/actions/runs/151715138/workflow. That build has failed though.

**Comment by antelle** [comment]
I managed to build native modules for Apple Silicon. Not sure if they work, I don't have a way to test it, but they should.

**Comment by antelle** [comment]
Next step is also done, here's a native helper built for both architectures: https://share.antelle.net/KeeWebHelper
Could you please check if it works? Download it and run:
```
echo "text  Hello\nkey 10\ntext  world\nexit\n" | ./KeeWebHelper
```
If you see a question about Terminal, allow it in Security & Privacy (and remove it from there after testing).
Expected output:
```
Hello§world
```

**Comment by antelle** [comment]
Yay, the first build is here! Now I need a volunteer with an M1 Mac to test it.
That's what you need to do:
1. download a dmg called [KeeWeb-1.16.0.mac.arm64.dmg](https://github.com/keeweb/keeweb-ci-sandbox/releases/download/v1.16.0/KeeWeb-1.16.0.mac.arm64.dmg)
2. delete KeeWeb.app, if you already have it installed
3. put it to `/Applications`, or `~/Applications`, whichever you use to save apps to
4. launch KeeWeb
5. open Activity Monitor, search "KeeWeb", verify that all processes are running not in emulation mode
6. open DevTools with <kbd>⌥</kbd><kbd>⌘</kbd><kbd>I</kbd> and switch to Console tab
7. check the logs, here's what you should expect (is there anything extra? report it here):
```
index.html:1 2020-11-30T20:07:56.662Z [start-profiler] Electron app started in 703ms: loading main requires=5ms, ...
index.html:1 2020-11-30T20:07:56.752Z [start-profiler] App started in 433ms: fetching=183ms, ...
index.html:1 2020-11-30T20:07:56.758Z [updater] Next update check will happen in 76869s
index.html:1 2020-11-30T20:07:56.762Z [usb-listener] Starting USB listener
index.html:1 2020-11-30T20:07:56.762Z [native-module-connector] Starting native module host
```
8. click the "+" (New) button
9. add an entry
10. save the file
11. close KeeWeb and open it again
12. open the file you just created and make sure it can be opened
13. open Demo
14. select any entry
15. run auto-type with <kbd>⌘</kbd><kbd>T</kbd> and check if it's working well
16. verify that `.kdbx` files in Finder have the proper icon and are opened with KeeWeb
17. do you have a YubiKey? Do [this](https://www.youtube.com/watch?v=5m0FkWaIgL4) and [this](https://www.youtube.com/watch?v=-JhhxRavvqg)
18. copy the logs after all of this here

**Comment by maybe** [comment]
> Yay, the first build is here! Now I need a volunteer with an M1 Mac to test it.
> That's what you need to do:
> 
> 1. download a dmg called [KeeWeb-1.16.0.mac.arm64.dmg](https://github.com/keeweb/keeweb-ci-sandbox/releases/download/v1.16.0/KeeWeb-1.16.0.mac.arm64.dmg)
> 2. delete an existing KeeWeb.app if you already have it installed
> 3. put it to `/Applications`, or `~/Applications`, whichever you use to save apps to
> 4. launch KeeWeb
> 5. open Activity Monitor, search "KeeWeb", verify that all processes are running not in emulation mode
> 6. open DevTools with ⌥⌘I and switch to Console tab
> 7. check the logs, here's what you should expect (is there anything extra? report it here):
> 
> ```
> index.html:1 2020-11-30T20:07:56.662Z [start-profiler] Electron app started in 703ms: loading main requires=5ms, ...
> index.html:1 2020-11-30T20:07:56.752Z [start-profiler] App started in 433ms: fetching=183ms, ...
> index.html:1 2020-11-30T20:07:56.758Z [updater] Next update check will happen in 76869s
> index.html:1 2020-11-30T20:07:56.762Z [usb-listener] Starting USB listener
> index.html:1 2020-11-30T20:07:56.762Z [native-module-connector] Starting native module host
> ```
> 
> 1. click the "+" (New) button
> 2. add an entry
> 3. save the file
> 4. close KeeWeb and open it again
> 5. open the file you just created and make sure it can be opened
> 6. open Demo
> 7. select any entry
> 8. run auto-type with ⌘T and check if it's working well
> 9. verify that `.kdbx` files in Finder have the proper icon and are opened with KeeWeb
> 10. if you have a YubiKey, do [this](https://www.youtube.com/watch?v=5m0FkWaIgL4) and [this](https://www.youtube.com/watch?v=-JhhxRavvqg)
> 11. copy the logs after all of this here

I cannot launch the app

Error loading app: Error: dlopen(/Applications/KeeWeb.app/Contents/Resources/node_modules/@keeweb/keeweb-native-modules/keytar-darwin-arm64.node, 1): no suitable image found.  Did find:
/Applications/KeeWeb.app/Contents/Resources/node_modules/@keeweb/keeweb-native-modules/keytar-darwin-arm64.node: mach-o, but wrong architecture
/Applications/KeeWeb.app/Contents/Resources/node_modules/@keeweb/keeweb-native-modules/keytar-darwin-arm64.node: mach-o, but wrong architecture

**Comment by antelle** [comment]
@maybe thanks, the add-on seems to be not build properly, looking into it.
Could you please test if KeeWebHelper [works](https://github.com/keeweb/keeweb/issues/1640#issuecomment-735939315) for you?

**Comment by antelle** [comment]
Not sure why it behaves like this on a runner, it compiles for arm on my macbook, but not there.
```
In file included from /Applications/Xcode_12.2.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/12.0.0/include/stdint.h:52:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/stdint.h:52:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/sys/_types.h:32:
/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/sys/cdefs.h:807:2: error: Unsupported architecture
#error Unsupported architecture
```
Very weird: `.../usr/lib/clang/12.0.0/include/stdint.h` includes `.../SDKs/MacOSX10.15.sdk/usr/include/stdint.h:52`, something is wrong with the SDK path.

**Comment by maybe** [comment]
> @maybe thanks, the add-on seems to be not build properly, looking into it.
> Could you please test if KeeWebHelper [works](https://github.com/keeweb/keeweb/issues/1640#issuecomment-735939315) for you?

It works.

**Comment by antelle** [comment]
Thanks! So, now we need to fix the native module. I'd rather wait for official support on GitHub actions or until other people come across this and solve it, so that I can just google and copy&paste. This should happen soon, [here](https://github.com/actions/virtual-environments/issues/1599) they say it should already happen, but rollout takes time. I'm too lazy to dig into this myself.

**Comment by antelle** [comment]
I [managed to build](https://github.com/keeweb/keeweb-native-modules/blob/master/.github/workflows/main.yaml#L100-L101) native modules on GitHub actions, now I see that it's built for arm64:
```
objdump -l node_modules/@keeweb/keeweb-native-modules/argon2-darwin-arm64.node
node_modules/@keeweb/keeweb-native-modules/argon2-darwin-arm64.node:
    file format Mach-O arm64
```
Here's a new build for you: [KeeWeb-1.16.0.mac.arm64.dmg](https://github.com/keeweb/keeweb-ci-sandbox/releases/download/v1.16.0/KeeWeb-1.16.0.mac.arm64.dmg)
Could you please give it a try?

**Comment by antelle** [comment]
Another question, about distribution. Could you please check what `navigator` returns in Chrome, Safari, and Firefox on Apple Silicon? I'm especially interested in `navigator.platform` and `navigator.userAgent`.

**Comment by maybe** [comment]
> I [managed to build](https://github.com/keeweb/keeweb-native-modules/blob/master/.github/workflows/main.yaml#L100-L101) native modules on GitHub actions, now I see that it's built for arm64:
> 
> ```
> objdump -l node_modules/@keeweb/keeweb-native-modules/argon2-darwin-arm64.node
> node_modules/@keeweb/keeweb-native-modules/argon2-darwin-arm64.node:
>     file format Mach-O arm64
> ```
> 
> Here's a new build for you: [KeeWeb-1.16.0.mac.arm64.dmg](https://github.com/keeweb/keeweb-ci-sandbox/releases/download/v1.16.0/KeeWeb-1.16.0.mac.arm64.dmg)
> Could you please give it a try?

It's still not working, shows the same error.

Error loading app: Error: dlopen(/Applications/KeeWeb.app/Contents/Resources/node_modules/@keeweb/keeweb-native-modules/keytar-darwin-arm64.node, 1): no suitable image found.  Did find:
/Applications/KeeWeb.app/Contents/Resources/node_modules/@keeweb/keeweb-native-modules/keytar-darwin-arm64.node: mach-o, but wrong architecture
/Applications/KeeWeb.app/Contents/Resources/node_modules/@keeweb/keeweb-native-modules/keytar-darwin-arm64.node: mach-o, but wrong architecture

**Comment by maybe** [comment]
> Another question, about distribution. Could you please check what `navigator` returns in Chrome, Safari, and Firefox on Apple Silicon? I'm especially interested in `navigator.platform` and `navigator.userAgent`. It's needed to select the right dmg on the website when you click "Download for macOS".

I installed the latest universal version for mac silicon.

Safari
<img width="1256" alt="WeChatWorkScreenshot_47a06365-9479-4b67-abe7-a7fc3695d4b2" src="https://user-images.githubusercontent.com/175235/101116299-cad86f00-361f-11eb-88a7-5ee0db05edd1.png">

Chrome
<img width="982" alt="WeChatWorkScreenshot_3e62cffb-a2a1-4db6-b1e5-522dfba35015" src="https://user-images.githubusercontent.com/175235/101117120-4f77bd00-3621-11eb-8ab6-681d5d9288eb.png">

Firefox
<img width="870" alt="WeChatWorkScreenshot_512917ae-1e72-45c1-855e-c6bc95a71cc2" src="https://user-images.githubusercontent.com/175235/101117146-5999bb80-3621-11eb-8225-c52f2830ae35.png">

**Comment by antelle** [comment]
Whoa, that's strange! What happens if you do the following?
```
/Applications/KeeWeb.app/Contents/Resources/node_modules/@keeweb/keeweb-native-modules/keytar-darwin-arm64.node 2>&1 | grep Format
objdump -l /Applications/KeeWeb.app/Contents/Resources/node_modules/@keeweb/keeweb-native-modules/argon2-darwin-arm64.node 2>/dev/null | grep 'format.*'  --only-match
```
For me it prints:
```
format Mach-O 64-bit x86-64
Format=Mach-O thin (x86_64)
```
I would expect it to be arm64 for you.

Thank you for the browser screenshots! It's a pity it's reported as `MacIntel` though.

**Comment by antelle** [comment]
Scratch it, I found the issue, now all modules are built for arm64 apart from this `keytar` thing! I didn't notice that all of them (I was testing `argon2`) were for `arm64`, but not `keytar`! Fixing it...

**Comment by antelle** [comment]
Created an issue about incorrect architecture in upstream: https://github.com/atom/node-keytar/issues/339
While it's being solved, I added a [workaround](https://github.com/keeweb/keeweb-native-modules/commit/e444584f2a844015f0ee851cc4c578a4f14bb833), does the [new build](https://github.com/keeweb/keeweb-ci-sandbox/releases/download/v1.16.0/KeeWeb-1.16.0.mac.arm64.dmg) work for you?

**Comment by maybe** [comment]
> Created an issue about incorrect architecture in upstream: [atom/node-keytar#339](https://github.com/atom/node-keytar/issues/339)
> While it's being solved, I added a [workaround](https://github.com/keeweb/keeweb-native-modules/commit/e444584f2a844015f0ee851cc4c578a4f14bb833), does the [new build](https://github.com/keeweb/keeweb-ci-sandbox/releases/download/v1.16.0/KeeWeb-1.16.0.mac.arm64.dmg) work for you?

It works! And it's much faster than the x86 version. I'll run for a time to check the stability.

**Comment by antelle** [comment]
Yeah, cool, very glad to hear it's faster! 🎉 
If you don't mind, can you please run the [scenario](https://github.com/keeweb/keeweb/issues/1640#issuecomment-736045256) above? If everything works, I think we're ready to release it today.

**Comment by maybe** [comment]
> Yeah, cool, very glad to hear it's faster! 🎉
> If you don't mind, can you please run the [scenario](https://github.com/keeweb/keeweb/issues/1640#issuecomment-736045256) above? If everything works, I think we're ready to release it today.

I don't have a YubiKey, so I can just test step 1-16.

```
index.html:1 2020-12-04T10:39:52.706Z [start-profiler] Electron app started in 508ms: loading main requires=3ms, getting data dir=0ms, checking for new version=0ms, loading app requires=1ms, single instance lock=1ms, portable check=0ms, userdata dir=0ms, defining args=10ms, setting env=0ms, app on ready=64ms, loading settings key=17ms, reading app settings=3ms, setting system appearance=0ms, creating main window=15ms, setting menu=1ms, configuring main window=2ms, restoring main window position=0ms, setting global shortcuts=0ms, subscribing to power events=0ms, setting request handlers=0ms, main window ready=245ms, main window shown=5ms
index.html:1 2020-12-04T10:39:52.767Z [start-profiler] App started in 325ms: fetching=169ms, pre-init=212ms, loading modules=28ms, document ready=8ms, creating app model=1ms, loading configs=16ms, initializing modules=1ms, loading remote config=0ms, checking features=0ms, initializing storage=0ms, first view rendering=58ms, app ready event=0ms
index.html:1 2020-12-04T10:39:52.784Z [updater] Next update check will happen in 78474s
index.html:1 2020-12-04T10:39:52.786Z [usb-listener] Starting USB listener
index.html:1 2020-12-04T10:39:52.786Z [native-module-connector] Starting native module host
index.html:1 2020-12-04T10:39:55.958Z [open:New1] File open request
index.html:1 2020-12-04T10:39:55.958Z [open:New1] Open file from storage file
index.html:1 2020-12-04T10:39:55.958Z [open:New1] Stat file
index.html:1 2020-12-04T10:39:55.958Z [storage-file] Stat /Users/panda/Desktop/New1.kdbx
index.html:1 2020-12-04T10:39:55.959Z [storage-file] Stat done /Users/panda/Desktop/New1.kdbx 1ms
index.html:1 2020-12-04T10:39:55.959Z [open:New1] Open file from storage (1607077539403, local 1607077539403)
index.html:1 2020-12-04T10:39:55.959Z [open:New1] Load from storage
index.html:1 2020-12-04T10:39:55.960Z [storage-file] Load /Users/panda/Desktop/New1.kdbx
index.html:1 2020-12-04T10:39:55.962Z [storage-file] Loaded /Users/panda/Desktop/New1.kdbx 1607077539403 2ms
index.html:1 2020-12-04T10:39:55.962Z [open:New1] Open file from content loaded from storage
index.html:1 2020-12-04T10:39:55.965Z [argon2] Using native argon2
index.html:1 2020-12-04T10:39:55.970Z [argon2] Argon2 hash calculated 5ms
index.html:1 2020-12-04T10:39:55.970Z [argon2] Hash computed 6ms
index.html:1 2020-12-04T10:39:55.980Z [file] Opened file New1: 17ms, P=1&I=2&M=1048576&V=19, 2 kB
index.html:1 2020-12-04T10:39:55.980Z [app] Add last open file 1d1b1509-7e59-68b9-c8a9-3968269bc53d New1 file /Users/panda/Desktop/New1.kdbx 1607077539403
index.html:1 2020-12-04T10:39:56.006Z [storage-file] Watch dir /Users/panda/Desktop
index.html:1 2020-12-04T10:40:04.397Z [sync:New1] Sync started file /Users/panda/Desktop/New1.kdbx Object
index.html:1 2020-12-04T10:40:04.400Z [sync:New1] Stat file
index.html:1 2020-12-04T10:40:04.400Z [storage-file] Stat /Users/panda/Desktop/New1.kdbx
index.html:1 2020-12-04T10:40:04.404Z [storage-file] Stat done /Users/panda/Desktop/New1.kdbx 4ms
index.html:1 2020-12-04T10:40:04.404Z [sync:New1] Stat found same version, not modified
index.html:1 2020-12-04T10:40:04.404Z [sync:New1] Sync finished no error
index.html:1 2020-12-04T10:40:10.444Z [sync:New1] Sync started file /Users/panda/Desktop/New1.kdbx Object
index.html:1 2020-12-04T10:40:10.446Z [sync:New1] Stat file
index.html:1 2020-12-04T10:40:10.446Z [storage-file] Stat /Users/panda/Desktop/New1.kdbx
index.html:1 2020-12-04T10:40:10.451Z [storage-file] Stat done /Users/panda/Desktop/New1.kdbx 4ms
index.html:1 2020-12-04T10:40:10.451Z [sync:New1] Stat found same version, modified, saving
index.html:1 2020-12-04T10:40:10.451Z [sync:New1] Getting file data for saving
index.html:1 2020-12-04T10:40:10.459Z [argon2] Argon2 hash calculated 3ms
index.html:1 2020-12-04T10:40:10.459Z [argon2] Hash computed 3ms
index.html:1 2020-12-04T10:40:10.474Z [sync:New1] Saving to file storage
index.html:1 2020-12-04T10:40:10.474Z [sync:New1] Save data to storage
index.html:1 2020-12-04T10:40:10.474Z [storage-file] Save /Users/panda/Desktop/New1.kdbx 1607077539403
index.html:1 2020-12-04T10:40:10.476Z [storage-file] Saved /Users/panda/Desktop/New1.kdbx 2ms
index.html:1 2020-12-04T10:40:10.476Z [sync:New1] Update rev in file info
index.html:1 2020-12-04T10:40:10.477Z [sync:New1] Save to storage complete, update sync date
index.html:1 2020-12-04T10:40:10.477Z [sync:New1] Sync finished no error
index.html:1 2020-12-04T10:40:10.487Z [storage-file] File changed /Users/panda/Desktop change New1.kdbx
index.html:1 2020-12-04T10:40:13.489Z [sync:New1] Sync started file /Users/panda/Desktop/New1.kdbx Object
index.html:1 2020-12-04T10:40:13.490Z [sync:New1] Stat file
index.html:1 2020-12-04T10:40:13.490Z [storage-file] Stat /Users/panda/Desktop/New1.kdbx
index.html:1 2020-12-04T10:40:13.498Z [storage-file] Stat done /Users/panda/Desktop/New1.kdbx 8ms
index.html:1 2020-12-04T10:40:13.498Z [sync:New1] Stat found same version, not modified
index.html:1 2020-12-04T10:40:13.498Z [sync:New1] Sync finished no error
index.html:1 2020-12-04T10:40:20.118Z [sync:New1] Sync started file /Users/panda/Desktop/New1.kdbx Object
index.html:1 2020-12-04T10:40:20.120Z [sync:New1] Stat file
index.html:1 2020-12-04T10:40:20.120Z [storage-file] Stat /Users/panda/Desktop/New1.kdbx
index.html:1 2020-12-04T10:40:20.125Z [storage-file] Stat done /Users/panda/Desktop/New1.kdbx 5ms
index.html:1 2020-12-04T10:40:20.125Z [sync:New1] Stat found same version, not modified
index.html:1 2020-12-04T10:40:20.125Z [sync:New1] Sync finished no error
index.html:1 2020-12-04T10:40:22.401Z [storage-file] Stop watch dir /Users/panda/Desktop
index.html:1 2020-12-04T10:40:27.744Z [open:New1] File open request
index.html:1 2020-12-04T10:40:27.744Z [open:New1] Open file from supplied content
index.html:1 2020-12-04T10:40:27.744Z [storage-file] Stat /Users/panda/Desktop/New1.kdbx
index.html:1 2020-12-04T10:40:27.745Z [storage-file] Stat done /Users/panda/Desktop/New1.kdbx 1ms
index.html:1 2020-12-04T10:40:27.749Z [argon2] Argon2 hash calculated 3ms
index.html:1 2020-12-04T10:40:27.749Z [argon2] Hash computed 3ms
index.html:1 2020-12-04T10:40:27.757Z [file] Opened file New1: 12ms, P=1&I=2&M=1048576&V=19, 2 kB
index.html:1 2020-12-04T10:40:27.757Z [app] Add last open file 1d1b1509-7e59-68b9-c8a9-3968269bc53d New1 file /Users/panda/Desktop/New1.kdbx 1607078410476
index.html:1 2020-12-04T10:40:27.774Z [storage-file] Watch dir /Users/panda/Desktop
index.html:1 2020-12-04T10:40:28.523Z [sync:New1] Sync started file /Users/panda/Desktop/New1.kdbx Object
index.html:1 2020-12-04T10:40:28.526Z [sync:New1] Stat file
index.html:1 2020-12-04T10:40:28.526Z [storage-file] Stat /Users/panda/Desktop/New1.kdbx
index.html:1 2020-12-04T10:40:28.530Z [storage-file] Stat done /Users/panda/Desktop/New1.kdbx 5ms
index.html:1 2020-12-04T10:40:28.531Z [sync:New1] Stat found same version, not modified
index.html:1 2020-12-04T10:40:28.531Z [sync:New1] Sync finished no error
index.html:1 2020-12-04T10:40:59.915Z [sync:New1] Sync started file /Users/panda/Desktop/New1.kdbx Object
index.html:1 2020-12-04T10:40:59.917Z [sync:New1] Stat file
index.html:1 2020-12-04T10:40:59.917Z [storage-file] Stat /Users/panda/Desktop/New1.kdbx
index.html:1 2020-12-04T10:40:59.921Z [storage-file] Stat done /Users/panda/Desktop/New1.kdbx 4ms
index.html:1 2020-12-04T10:40:59.921Z [sync:New1] Stat found same version, modified, saving
index.html:1 2020-12-04T10:40:59.921Z [sync:New1] Getting file data for saving
index.html:1 2020-12-04T10:40:59.927Z [argon2] Argon2 hash calculated 4ms
index.html:1 2020-12-04T10:40:59.927Z [argon2] Hash computed 4ms
index.html:1 2020-12-04T10:40:59.937Z [sync:New1] Saving to file storage
index.html:1 2020-12-04T10:40:59.937Z [sync:New1] Save data to storage
index.html:1 2020-12-04T10:40:59.937Z [storage-file] Save /Users/panda/Desktop/New1.kdbx 1607078410476
index.html:1 2020-12-04T10:40:59.938Z [storage-file] Saved /Users/panda/Desktop/New1.kdbx 1ms
index.html:1 2020-12-04T10:40:59.938Z [sync:New1] Update rev in file info
index.html:1 2020-12-04T10:40:59.939Z [sync:New1] Save to storage complete, update sync date
index.html:1 2020-12-04T10:40:59.940Z [sync:New1] Sync finished no error
index.html:1 2020-12-04T10:41:00.222Z [storage-file] File changed /Users/panda/Desktop change New1.kdbx
index.html:1 2020-12-04T10:41:03.228Z [sync:New1] Sync started file /Users/panda/Desktop/New1.kdbx Object
index.html:1 2020-12-04T10:41:03.231Z [sync:New1] Stat file
index.html:1 2020-12-04T10:41:03.231Z [storage-file] Stat /Users/panda/Desktop/New1.kdbx
index.html:1 2020-12-04T10:41:03.237Z [storage-file] Stat done /Users/panda/Desktop/New1.kdbx 5ms
index.html:1 2020-12-04T10:41:03.237Z [sync:New1] Stat found same version, not modified
index.html:1 2020-12-04T10:41:03.237Z [sync:New1] Sync finished no error
index.html:1 2020-12-04T10:42:25.000Z [storage-file] Stop watch dir /Users/panda/Desktop
index.html:1 2020-12-04T10:42:47.284Z [auto-type] Auto type event Proxy
index.html:1 2020-12-04T10:42:47.284Z [auto-type] Hide window
index.html:1 2020-12-04T10:42:47.388Z [auto-type] Start {USERNAME}{TAB}{PASSWORD}{ENTER}
index.html:1 2020-12-04T10:42:47.389Z [auto-type] Parsed [op:USERNAME,op:TAB,op:PASSWORD,op:ENTER]
index.html:1 2020-12-04T10:42:47.390Z [auto-type] Resolved [****************,key:tab,[*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*],key:enter]
index.html:1 2020-12-04T10:42:47.392Z [auto-type] Using auto-type helper /Applications/KeeWeb.app/Contents/Resources/helper/darwin/KeeWebHelper
index.html:1 2020-12-04T10:42:47.614Z [launcher] spawn /Applications/KeeWeb.app/Contents/Resources/helper/darwin/KeeWebHelper: 0, 222ms
index.html:1 2020-12-04T10:42:47.614Z [auto-type] Complete 226ms
```

**Comment by antelle** [comment]
Perfect, everything seems to be working, so it’s going live soon! 🚀

**Comment by antelle** [comment]
It's rolled out: https://github.com/keeweb/keeweb/releases/latest
Thank you very much for testing it! 🎁 

Now the question is, how to offer this build on the website? I have no idea how others do it because there seems to be no way to detect this mac in JavaScript. So what will happen, it will download the x64 dmg and you will be able to get the Apple Silicon version by clicking "all platforms". Not the greatest visibility I guess, and not everyone will be able to understand that we even offer a native build for Apple Silicon, so ideas are welcome.

**Comment by antelle** [comment]
Asked it on SO, let's see: https://stackoverflow.com/questions/65146751/detecting-apple-silicon-mac-in-javascript  
In the worst case, I can a question about it for macOS, but it's not good.

**Comment by maybe** [comment]
some apps offer the separate verison on the site.

![image](https://user-images.githubusercontent.com/175235/101198945-2e55b180-369f-11eb-8321-7fda74d26b7c.png)

![image](https://user-images.githubusercontent.com/175235/101199490-eaaf7780-369f-11eb-8d1a-5dd5361e0604.png)

**Comment by antelle** [comment]
> Mac with Apple chip

hehe, I can feel the pain of explaining to users.  
But I see, probably we'll have to make a switch, I'll add it if I don't find anything better.

**Comment by maybe** [comment]
or maybe you can build a universal app which can be run both on x86 an arm64
https://developer.apple.com/documentation/xcode/building_a_universal_macos_binary

```
$ lipo -archs /Applications/KeeWeb.app/Contents/MacOS/KeeWeb
arm64
$ lipo -archs /Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome
x86_64 arm64
```

**Comment by antelle** [comment]
That's not possible with Electron, see the motivation here: https://www.electronjs.org/blog/apple-silicon
> In the future, we will release a package that allows you to "merge" your arm64 and x64 apps into a single universal binary, but it's worth noting that this binary would be huge and probably isn't ideal for shipping to users.

**Comment by antelle** [comment]
Something like this:
![Download animation](https://user-images.githubusercontent.com/633557/101203003-5840b100-366a-11eb-94a5-1696db94a4b7.gif)

**Comment by antelle** [comment]
Added it in https://github.com/keeweb/keeweb-site/commit/9d5acc8eeba7e4d7097f6adf21f3f15e12ef6ab6, now the button should appear on [keeweb.info](https://keeweb.info/?next)

**Comment by maybe** [comment]
cool!
