### ISSUE TITLE
Webdav ERR_CERT_AUTHORITY_INVALID on MacOS Big Sur

### ISSUE THREAD

**Issue by dscowan** [keeweb/keeweb#1641]
This started happening after big sur update.  I do not see this on my linux or windows machines using the same url.  The certificate is a lets encrypt cert and it is still valid.  I even tried importing the cert and always trusting it, but I still get the same error.  I have verified chrome and safari view the cert as valid via the browsers. 

**Version**
1.15.7

**Logs**
2020-11-30T01:43:32.483Z [storage-webdav] Stat https://webdavserver:8081/keepass/keepass.kdbx
index.html:1 2020-11-30T01:43:32.533Z [storage-webdav] Stat error https://webdavserver:8081/keepass/keepass.kdbx 50ms
index.html:1 2020-11-30T01:43:32.533Z [sync:keepass] Stat error, not dirty network error
index.html:1 2020-11-30T01:43:32.533Z [sync:keepass] Sync finished network error
index.html:1 HEAD https://webdavserver:8081/keepass/keepass.kdbx net::ERR_CERT_AUTHORITY_INVALID

**Comment by antelle** [comment]
does it also happen on 1.16?

**Comment by dscowan** [comment]
1.16 fixes it
