### ISSUE TITLE
[UI] Bring back darker aside & bottom components

### ISSUE THREAD

**Issue by KaKi87** [keeweb/keeweb#1644]
**Is your feature request related to a problem? Please describe.**
I liked how the aside and bottom areas were as dark as the rest of the UI.

**Describe the solution you'd like**
Make those darker like before

**Describe alternatives you've considered**
Create a new variant of the dark theme in which the aside and bottom areas would be darker like before

**Additional context**

Before :

![efze1r4g36e87f36qze54f3a6qze8f7](https://user-images.githubusercontent.com/21284089/100740384-e998f480-33d8-11eb-8500-17d6f8ae63ad.png)

After :

![screenshot-app keeweb info-2020 12 01-13_25_55](https://user-images.githubusercontent.com/21284089/100740400-f0c00280-33d8-11eb-80e9-a8f56171f1a7.png)

Thanks

**Comment by antelle** [comment]
Hi! This won't be brought back in the default theme, but we can create a new dark theme that will look this way.

**Comment by antelle** [comment]
I made a "Darker" theme, apart from changed footer and aside colors, it also has darker colors overall, what do you think?

https://plugins.keeweb.info/plugins/theme-darker

![image](https://user-images.githubusercontent.com/633557/100784551-a6a64380-340f-11eb-9778-4dc8ccb5a9dc.png)
![image](https://user-images.githubusercontent.com/633557/100784570-ac038e00-340f-11eb-945b-979f2f676332.png)

GitHub actions are a bit slow today, it will appear in the gallery once the [build](https://github.com/keeweb/keeweb-plugins/actions/runs/394516347) is finished.

**Comment by KaKi87** [comment]
Nice, thanks !

**Comment by antelle** [comment]
The theme is published, you should be able to install it from the gallery now.
