### ISSUE TITLE
[UI] Colors incompatibility since accent colors used as background of currently selected item

### ISSUE THREAD

**Issue by KaKi87** [keeweb/keeweb#1645]
**Describe the bug**
Since the theme's accent color is featured as background color of the currently selected item, it can make the item's color itself indistinguishable from it.

**To Reproduce**
1. Open a KDBX file
2. Select an item which color is similar to the theme's accent color

**Expected behavior**
The theme's accent color and the item's color can be distinguished.

**Screenshots**

Before :

![efserf2zq7fzqef25zef](https://user-images.githubusercontent.com/21284089/100740867-af7c2280-33d9-11eb-9178-40c14afe5326.png)

After :

![2020-12-01 13_31_57-KeeWeb – Brave](https://user-images.githubusercontent.com/21284089/100740851-a5f2ba80-33d9-11eb-9c0f-15ceef85bb64.png)

**Environment**
KeeWeb v1.16.0 (undefined, 2020-11-29)
Environment: web
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.67 Safari/537.36

**Kdbx File**
Ireelevant

**Logs**
Irrelevant

**Comment by antelle** [comment]
Good find 👍

**Comment by antelle** [comment]
They look better now:

<img width="297" alt="Screen Shot 2020-12-04 at 18 06 17" src="https://user-images.githubusercontent.com/633557/101192544-8074e380-365b-11eb-9742-ddb4bad19b89.png">
<img width="297" alt="Screen Shot 2020-12-04 at 18 06 22" src="https://user-images.githubusercontent.com/633557/101192546-81a61080-365b-11eb-8b8f-cd96c5fe61a5.png">
<img width="297" alt="Screen Shot 2020-12-04 at 18 06 27" src="https://user-images.githubusercontent.com/633557/101192547-81a61080-365b-11eb-91e7-c16c39d691c6.png">
<img width="297" alt="Screen Shot 2020-12-04 at 18 06 40" src="https://user-images.githubusercontent.com/633557/101192548-823ea700-365b-11eb-8d67-5846c0987662.png">
<img width="297" alt="Screen Shot 2020-12-04 at 18 06 45" src="https://user-images.githubusercontent.com/633557/101192549-823ea700-365b-11eb-89a2-a4eeb6993237.png">

**Comment by KaKi87** [comment]
Yes, perhaps blue on green could be lighter but it's not vital. 😉

**Comment by antelle** [comment]
I tried the lighter version in the beginning, but it looks either dirty:
<img width="296" alt="Screen Shot 2020-12-04 at 18 19 56" src="https://user-images.githubusercontent.com/633557/101193800-63d9ab00-365d-11eb-9553-04a6bd94d61a.png">
<img width="296" alt="Screen Shot 2020-12-04 at 18 20 04" src="https://user-images.githubusercontent.com/633557/101193803-650ad800-365d-11eb-9242-4ec88aa77597.png">
<img width="296" alt="Screen Shot 2020-12-04 at 18 20 09" src="https://user-images.githubusercontent.com/633557/101193807-65a36e80-365d-11eb-82dd-b518a78dc252.png">

or too white:
<img width="296" alt="Screen Shot 2020-12-04 at 18 20 00" src="https://user-images.githubusercontent.com/633557/101193820-69cf8c00-365d-11eb-8a3f-8e0fa8924e6a.png">

so I thought maybe a darker blue on green would look better.
