### ISSUE TITLE
Desktop Fails to Connect to Google

### ISSUE THREAD

**Issue by gbatson** [keeweb/keeweb#1646]
400. That’s an error.

The server cannot process the request because it is malformed. It should not be retried. That’s all we know.

I'm trying to install desktop version 1.16 on ubuntu 18 running KDE Plasma with latest Firefox. Gdrive login gives failure. The online version works OK. Perhaps there is something special to do with Firefox?
This is the address bar for google out of firefox:
https://accounts.google.com/signin/oauth/legacy/consent?authuser=0&part=AJi8hAOmoirRjmAtp2KosjTsfiRY6KpD9LILzRM8rnvYXyEpYMkNj9s_YViHVa1zrTGIAphA3YT_kYICA4xbhEVaiGLtgmAO_BYvH7fTXv7xgr0ZjdxuE4wB8vPFlbVNaYpGQMbU2KyQzngftTBrJTkK5Oxf_bAn_748s_4JswkoWOLBemBQiZoShxq9-PuXLA8utlL_2jBWwlFCWI7NC61TzyLBfglvBDeL4bNMGqm9WwgCNXjRiRHYAwYKff6Icq8C0maCh7l-zr_cLghPchwyNPxVVm94nmvCST3BjuwPfpDAIFyJYoj18e3BlJXdxD3-8dgYqMxwdRJ1kBrp_vlQ7RfmBGtc56o_yrWUM2XyBcYAGtC-ccoKZHwtY4rs8K1aAn1W6VxVzRWT2iqLnL2tyhTbGYm-Bu3k8clUaQe1-zp_lrS4_V_CYCABUNWkERD4LS-s9Ero&as=S1762164049%3A1606879445211309&pli=1#

**Comment by antelle** [comment]
See #1499
