### ISSUE TITLE
Show Groups and sub groups instead all items on the Root "folder"

### ISSUE THREAD

**Issue by Alexaandre** [keeweb/keeweb#1647]
Hi, i just started to use this awesome app today, but i was like a little bit worried, as i can't "hide" entries on the Root Folder. 

It would be great if you have an option to show only groups and sub-groups, and/or all entries . So if you click the fisrt item on the dropdown menu, it shows only folders and the contents remains hidden until i click the desired folder.

_Also do you think it can be implemented using a plugin ?_ 

I beg Your pardon sir, i just saw there were an option for that, but you still can't show only groups instead of subgroups

**Comment by Alexaandre** [comment]
i've saw that the folders are natively displayed . i close this non issue :) Sorry

**Comment by antelle** [comment]
Hi! There's a checkbox in Settings / General called "Show entries from all subgroups", I believe that's what you're looking for.
