### ISSUE TITLE
Security options for Argon2 in v1.16.1

### ISSUE THREAD

**Issue by Matthaiks** [keeweb/keeweb#1649]
What happened to them? Is this a bug?

1.6.0
![1 6 0](https://user-images.githubusercontent.com/3577122/101731237-a109c700-3abb-11eb-9db4-5f273159633d.png)

1.6.1
![1 6 1](https://user-images.githubusercontent.com/3577122/101731286-b8e14b00-3abb-11eb-8895-9e495495c516.png)

**Comment by antelle** [comment]
Thanks! It's coming back today.

**Comment by antelle** [comment]
The fix is rolled out
