### ISSUE TITLE
The keyfile is not rememberd anymore in the internal app storage since version v1.16.2

### ISSUE THREAD

**Issue by micktg** [keeweb/keeweb#1650]
**Describe the bug**
The keyfile is not rememberd anymore then stored in internal app storage since version v1.16.2

**To Reproduce**
1. Open app
2. Select keyfile
3. Enter password
4. Keeweb opens successfully
5. Close app
6. Reopen app (keyfile is stored)
7. Enter password
8. Error message appears: kdbxError: InvalidArg: keyFile

**Expected behavior**
The app shouldn't print an error message and open the key container instead (just like before in version v1.16.1)

**Screenshots**
![Screenshot 2020-12-10 201234](https://user-images.githubusercontent.com/278107/101818484-3640a600-3b24-11eb-8901-aa105287adf3.jpg)

**Environment**
Windows 10

**Comment by antelle** [comment]
Thanks! Will be fixed soon. Meanwhile you can select "remember path to keyfiles" as a workaround.

**Comment by micktg** [comment]
> Thanks! Will be fixed soon. Meanwhile you can select "remember path to keyfiles" as a workaround.

My pleasure! I just download the previous version and wait for the fix.

**Comment by antelle** [comment]
Fixed it, it's building...

**Comment by micktg** [comment]
> Fixed it, it's [building](https://github.com/keeweb/keeweb/actions/runs/413816986)...

One has to love agile software development! Thanks for the effort!

**Comment by antelle** [comment]
Done, it's [rolled out](https://github.com/keeweb/keeweb/releases/latest)! Please let me know if it works well for you.

**Comment by micktg** [comment]
> Done, it's [rolled out](https://github.com/keeweb/keeweb/releases/latest)! Please let me know if it works well for you.

1.16.3 Works like a charm!
Thanks!
