### ISSUE TITLE
Keeweb automation of some settings

### ISSUE THREAD

**Issue by Dailan** [keeweb/keeweb#1651]
Hi guys,

I am planning to roll out keeweb for couple of users, and i dont want that they have to change some settings by themself, like "minimize the app instead of close" or like Auto lock to "Don't auto-lock". How can i achieve that? I dont see any config files or whatsoever, i have installed the desktop version of the Keeweb. Do someone experience with such things here?

**Comment by antelle** [comment]
Hi! This is not supported, it was also requested here: #1609
