### ISSUE TITLE
Entries missing in KeeWeb

### ISSUE THREAD

**Issue by derBobby** [keeweb/keeweb#1652]
Hello,

there are several entries in my kdbx database file which are not shown in the KeeWeb UI.
I know these entries exist because they are available in apps on other devices.

What information can I provide to look deeper into this issue?

KeeWeb v1.15.7 (73509ef8, 2020-09-27)
Environment: web
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36

**Comment by antelle** [comment]
Hi! Does this happen if you copy your kdbx file and open it? If not, it's something with sync.  
Is there anything interesting about these entries? Are they in a folder, deleted, etc...?

**Comment by derBobby** [comment]
In short: It was a sync issue.

I wanted to recreate the problem with a fresh database and accidentally re-synced the already existing one in the process.
With one eye on the http logs of the web server I could see that the old database has been synced. This fixed it for me.

Sorry for bothering! :-)
