### ISSUE TITLE
Yubikey Support in Web App

### ISSUE THREAD

**Issue by tilllt** [keeweb/keeweb#1653]
I know this has been discussed before and then dismissed for security reasons:

Since I am using keepass with Yubikey 2FA I am unable to use keeweb. The discussion here on github mentioned a security issue in WebUSB which has (afaik) been fixed mid-2018. So is this something that could be implemented in the near future given the fact that the desktop app already has that feature?

I guess it would be pretty easy to disable the Yubikey feature for browser versions that were affected by this bug.

**Comment by antelle** [comment]
Hi! It was fixed in a different way: before YubiKeys were available in WebUSB, now they're completely excluded. So, since there's no standard exposing challenge-response functionality of the YubiKey, it won't be possible to use it in the nearest future.

**Comment by antelle** [comment]
For reference, here's the bug you mentioned:
https://www.yubico.com/blog/webusb-and-responsible-disclosure/
https://www.yubico.com/support/security-advisories/ysa-2018-02/
https://pwnaccelerator.github.io/2018/webusb-yubico-disclosure.html

**Comment by tilllt** [comment]
Could you point me to the source of your claim that the fix was disabling the Chrome -> Yubikey interaction completely? WebUSB seems to be still a thing in recent chrome versions, so they didn't drop the overall idea of WebUSB...

**Comment by antelle** [comment]
Sure, here's a ticket in Chromium: https://crbug.com/818807, which is also [referenced from the source code](https://github.com/chromium/chromium/blob/6efa1184771ace08f3e2162b0255c93526d1750d/chrome/browser/usb/usb_blocklist.cc#L73). It's not only yubikeys, all authenticators are excluded from WebUSB.
You can read its history if you follow the links I posted above, especially the shitshow around bounties described on the last one is very interesting.

**Comment by tilllt** [comment]
I find this confusing since the I would assume that the vulnerable part of the bug also affects things like fido2, but it doesn't. https://support.yubico.com/hc/en-us/articles/360016615020-Operating-system-and-web-browser-support-for-FIDO2

**Comment by antelle** [comment]
It doesn't affect FIDO2. FIDO2 is a protocol of communication between browsers (Chrome) and authenticators (YubiKey) used for WebAuthn. For javascript it's exposed via WebAuthn. When you visit a website, Chrome tells YubiKey "please sign me some data for this website".
Now, the plot twist. Chrome exposes USB devices via WebAuthn (FIDO2). If I display a question about accessing a USB device on my website, I can do what Chrome did before, but I will do it for another website. This is not cool. On this level it can't be filtered, so it's better to disable all possibilities to communicate with authenticators as raw devices via WebUSB and WebBluetooth.

**Comment by tilllt** [comment]
Thanks for taking the time for explaining. So is there a theoretical physical second factor device I can carry with me that could be used securely with a web based password manager? For me the idea of a web accessible password safe _without_ a second factor doesn't feel very good ...

**Comment by antelle** [comment]
Not to my knowledge. I mean, it's nuanced. For KeePass family it's not possible.
In theory what we can do, is make our own device which will work the same way as YubiKey, but without the FIDO2 part. This device would let you use the Challenge-Response applet, but won't let you log in to websites via FIDO2. Which also defeats the idea of having a YubiKey as the only one thing you need and of course there's not enough budget for that.
Why others can do it and we cannot? The answer is simple, they store data on their servers and can give it to you is you authenticate using WebAuthn. So that you log in with a YubiKey, and only then you can access the data. In KeePass, all the data you have if always with you in a kdbx file, so here it's different.

**Comment by antelle** [comment]
Another idea is to make a webservice where you can log in using WebAuthn and store the kdbx file on it. For example, a similar thing can be achieved now if a kdbx file is stored on Google Drive behind their 2FA. This way you need to present a second factor to access your file, however if an attacker managed to get access to a device where this file was opened, they don't need the second factor.
So this a different thing and it protects you from different threads, you should weigh up pros and cons and make a decision based on your threat model.

**Comment by tilllt** [comment]
For me the most important consideration was to have a usable but secure password safe on my phone, so yubikey neo with nfc in combination with Keepass2android was kind of an obvious choice.  On my own computers it's no problem since I use keepassXC. But when I am on the road, it's sometimes a bit annoying to look up 16 special character password and type it into another computer... 

I even bought a qr code reader to remedy that problem so I could scan the passwords of the phone... But that's also not super practical :) ... Well I guess somebody has to invent the perfect solution to this problem...

**Comment by antelle** [comment]
I see. KeeWeb is not a solution for this unfortunately.
