### ISSUE TITLE
How do I autofill/capture web longs with KeeWeb and my browser?

### ISSUE THREAD

**Issue by snakyjake1** [keeweb/keeweb#1654]
I want to autofill and capture web logins.  
How do I connect KeeWeb to my browser?

KeeWeb v1.16.3 (211b058, 2020-12-10)

Thank you.

**Comment by antelle** [comment]
Hi! You can either auto-type credentials from KeeWeb, or use extensions compatible with KeePassHttp. We don't support KeePassXC-Browser and other extensions yet.
