### ISSUE TITLE
Make favicon feature more intuitive

### ISSUE THREAD

**Issue by snakyjake1** [keeweb/keeweb#1655]
**Describe the solution you'd like**

Rather right-click the icon and have a menu option to download AND use the favicon.

Before I figured it out, I didn't notice the "cloud" icon among all my custom favicons that were imported from KeePassXC.  I thought it was just another website favicon.

Same with the "..." mixed in with all the custom favicons.

Not intuitive for the user.

**Describe alternatives you've considered**
I like how KeePassXC has the feature.

KeeWeb v1.16.3 (211b058, 2020-12-10)

Thank you.

**Comment by antelle** [comment]
Hi! Favicon is not one of important things you need to with an entry, so it should remain in the icons section. What we can improve, is split the "..." part there.

**Comment by antelle** [comment]
Well, actually the dots icon is not very much hidden and I think it's quite prominent:
![image](https://user-images.githubusercontent.com/633557/102399469-f7599700-3fe0-11eb-8708-a0425d00a8ff.png)

**Comment by snakyjake1** [comment]
> Well, actually the dots icon is not very much hidden and I think it's quite prominent:

Not for me...It wasn't that obvious buried among all the other custom icons.  
![image](https://user-images.githubusercontent.com/8312560/102418284-545f4800-3ff5-11eb-9893-d47e16ae1921.png)

If anything, the "cloud" and "..." icons should be separated.

**Comment by snakyjake1** [comment]
The "cloud" and "..." icons are not favicons, but function icons.  Function icons and favicons should be separated.

**Comment by antelle** [comment]
Hm right if there are a lot of icons, they’re a but lost in it, I’ll think what can be done

**Comment by snakyjake1** [comment]
Some additional usability enhancements...
It appear I need to click the "cloud" icon twice; even though the tooltip says it will download and use.

![image](https://user-images.githubusercontent.com/8312560/102422646-20892000-3fff-11eb-9587-fd0e44d5f408.png)

For example, I clicked the cloud icon to download and use the favicon, but the entry icon did not change:
![image](https://user-images.githubusercontent.com/8312560/102422802-74940480-3fff-11eb-817e-c7d43ede6ce9.png)

I had to click the downloaded icon again (after the download) to get it to the entry to change.

**Comment by antelle** [comment]
Good observation, that's a bug

**Comment by antelle** [comment]
Now it will be like this and it will also select the download icon automatically:

<img width="674" alt="Screen Shot 2020-12-19 at 16 31 05" src="https://user-images.githubusercontent.com/633557/102692987-9c5db500-4217-11eb-8114-fbf89df1d60a.png">
