### ISSUE TITLE
Add "clear" button to search bar

### ISSUE THREAD

**Issue by snakyjake1** [keeweb/keeweb#1657]
**Describe the solution you'd like**
I would like a "clear" button added to the search bar.

Currently:
![image](https://user-images.githubusercontent.com/8312560/102422237-35b17f00-3ffe-11eb-84bd-a5e20169b385.png)

Request:
![image](https://user-images.githubusercontent.com/8312560/102422478-c8eab480-3ffe-11eb-9cac-2afd895893f4.png)

**Comment by antelle** [comment]
Makes sense, the icon should be 
![FE62C57A-457C-46B4-BF15-E4958DE4EDAF](https://user-images.githubusercontent.com/633557/102453164-fdc92c80-403b-11eb-9c4f-10febabe8e9f.jpeg)

**Comment by antelle** [comment]
Deployed to [beta.keeweb.info](https://beta.keeweb.info), will be available in the next release.
![out](https://user-images.githubusercontent.com/633557/102545605-c481d280-40b6-11eb-8b0a-ecbc8ea4d641.gif)
