### ISSUE TITLE
sync error with yubikey 5

### ISSUE THREAD

**Issue by alexanderj1988** [keeweb/keeweb#1658]
If i select my [yubikey 5](https://www.amazon.de/Yubico-Authentication-Security-Supported-Accounts/dp/B08DHL1YDL/ref=sr_1_4?__mk_de_DE=%C3%85M%C3%85%C5%BD%C3%95%C3%91&dchild=1&keywords=yubikey&qid=1608294691&sr=8-4) to protect the vault, a sync error happens (on windows and mac, linux untested)

![notworking](https://user-images.githubusercontent.com/4067526/102615036-87a8f080-4135-11eb-85c0-25d0ddcd3f10.PNG)

if i remove the yubikey again, it works as expected again (important, if you close keeweb with the yubikey 5 still attached with the sync error , you can no longer reopen the vault!!!!!)

![working](https://user-images.githubusercontent.com/4067526/102615139-b2934480-4135-11eb-91e3-60b15b39801b.PNG)

**Comment by antelle** [comment]
Hi! Let’s see the logs...
It’s ok that adding yubikey corrupts the db, that’s why there’s a big warning about making a backup which is not possible to not notice.
