### ISSUE TITLE
Can a web solution truly be secure? 

### ISSUE THREAD

**Issue by carpben** [keeweb/keeweb#1659]
Modern browsers are commonly used with extensions/plugins. This means there is a good chance a page will have additional external JavaScript that is aware of all page content. So my questions are: 
1) Can a web solution truly be secure? Isn't the security that could be provided by a web client  inferior to the security that can be provided by a native client? 
2) If a web security can be secure, what actions or technology are used to achieve this end?

**Comment by antelle** [comment]
Hi! 👋
First of all, let's begin with a bit of theory.

There's no secure, non-secure, or truly secure technologies. So, I cannot give an answer this question directly.
However there are threats that have different likelihood to happen based on your threat model. It's something that you should analyze to answer the question "should I use the web version?" or "should I use a particular tool" in general. Threat models and therefore risks are different per person and cannot be the same for everyone, there's no one-size-fits-all solution.

For example, let's break down one of things you mentioned:
> Modern browsers are commonly used with extensions/plugins. This means there is a good chance a page will have additional external JavaScript that is aware of all page content.

What are we trying to protect?
Passwords and usernames available on the page (that's more or less obvious).

Can external JavaScript added to the page access passwords?
Yes, it is possible.

How complicated is it?
The script must be specially crafted for KeeWeb to access data stored in it. It's not available directly on the page as-is.

What permissions a browser plugin needs to have to install this kind of script?
Yes, if this plugin has a permission "access content on all pages" and this permission is effectively on for this plugin on keeweb.info.

Is user interaction required?
You need to open the database while the plugin is active.

So, now we have this picture in mind: a plugin made with purpose to access data in KeeWeb that has permissions to access data on all pages, can read the data we're interested in. Do you have this kind of plugins (suspicious "website enhancers", "video downloaders" and similar crap with 2 users)? There's a probability that this risk will happen. However you should also keep in mind that those plugins can harvest data on other pages, they can easier steal your data just by harvesting it using common methods regardless of your password manager.

If you ask me, my recommendation to this would be never, ever install software you don't trust, including browser plugins.
