### ISSUE TITLE
Pin/Favorite Entry

### ISSUE THREAD

**Issue by snakyjake1** [keeweb/keeweb#1660]
**Describe the solution you'd like**
Pin/favorite an entry to always be viewed in list.
I want to get to my pinned/favorite entries quickly/easily.

There are entries I always want to see, and I always want to see them at the top of the list.  I prefer not to scroll/search for the entry.  

Another idea/option would be to always view colored entries at the top of the list, so they are always easy to see/find.

Thank you.
KeeWeb v1.16.4 (2120425, 2020-12-17)

**Comment by antelle** [comment]
Hi! You can achieve this effect using either rearranging entries through groups, or using colors / tags, they're also available as keyboard shortcuts.
I'm not sure if adding pinning in addition to that will make it anyhow easier to understand and navigate, so the idea of displaying colored entries on top sounds better to me, maybe there should be an option in settings for that. This needs some thinking...

**Comment by snakyjake1** [comment]
One problem I have with colors is that it is a favicon color.  There are favicons that don't work nicely with the color feature.  When I use a color, I lose the favicon, and the favicon becomes a solid color block.

**Comment by antelle** [comment]
You can also set "Colorful custom icons in the list", then custom icons won't be colored in the list but you will be able to filter by them.

**Comment by snakyjake1** [comment]
Pinning could be one of the sort options; perhaps a sort rank.

We have sorting by Title, Website, User, Creation Date, Update Date, Attachments, Auto.  So pinning is really another sort rank option.  

First sort by pinned entries, then by Title, Website, User, Creation Date, Update Date, Attachments.

Similar experience with the web browser where the user can pin a tab, and it gets sorted to the left of all the tabs.

But the user experience is really about:
1)  Always see my pinned/favorite entries so they are quick and easy to see/use/select.
2)  The entry will always be seen, regardless of tag, folder, color, sort.

**Comment by antelle** [comment]
Closing it, since it will overcomplicate the application. Some final thoughts:
- the concept is not supported in the format, so other forks works understand it;
- we already have these things for organizing entries, all of them have different characteristics:
  - folders
  - tags
  - colors
  - files
- adding more cognitive load to the sorters which are already hard to understand will overload it
