### ISSUE TITLE
Unable to drag an item into another group

### ISSUE THREAD

**Issue by nerddan** [keeweb/keeweb#1663]
**Describe the bug**
Unable to drag an item into another group.

**Environment**
Linux + Wayland + Sway
I tried the native Linux app and the Chrome app. Neither works.

**Comment by antelle** [comment]
Hi! Works for me, more info please. How did you do it, what's the group hierarchy, logs, screenshots, etc...

**Comment by nerddan** [comment]
Thank you for replying! I tried rebooting, and the dragging issue in KeeWeb and Todoist are both resolved. Sorry for taking your time.

**Comment by nerddan** [comment]
When I use it for a while, it does not work again. Restarting sway (window manager) then it works. Since the issue exists for both Todoist and KeeWeb, in both native app and chrome web app, I don't think it is a bug with KeeWeb.

**Comment by antelle** [comment]
Would be nice if you report it to Electron. Actually it looks like a bug in Chromium, since it’s in the webapp as well. So it’s somewhere deep in frameworks...
