### ISSUE TITLE
Which Webdav service should I use?

### ISSUE THREAD

**Issue by JEricaM** [keeweb/keeweb#1664]
Hi
I'm trying to use keeweb with webdav.
I've tried https://dropdav.com/ using in keeweb url https://dav.dropdav.com/myfile.kdbx but my keeweb gives me cors error. Then I've tried to use it with a https://api.allorigins.win/get?url=https%3A%2F%2Fdav.dropdav.com%2F and now I have **"no last-modified header"**

Which webdav server works good with keeweb? 
Someone can help?
<img width="380" alt="Schermata 2020-12-22 alle 09 49 53" src="https://user-images.githubusercontent.com/9347586/102868932-246fd480-443b-11eb-844d-26b509d0f264.png">

**Comment by antelle** [comment]
Hi!

I can't give any advice about public webdav services, if you have your own one, here's are some configs: https://github.com/keeweb/keeweb/wiki/WebDAV%20Config

About No Last-Modified error, you can enable a workaround for it in settings if you wish, but better to set up a server that supports this header.

**Comment by JEricaM** [comment]
Which is the workaround that can be used? @antelle

**Comment by antelle** [comment]
This thing 
![F21ED23E-1317-4F21-84C6-F00E19159FE4](https://user-images.githubusercontent.com/633557/102972583-927bd080-44fb-11eb-8af8-cf917c104dac.jpeg)

**Comment by edkedk99** [comment]
For those who have problems with "Last-Modified" header error. This webdav server image solved the problem for me without modifying any configuration: https://github.com/dgraziotin/docker-nginx-webdav-nononsense
