### ISSUE TITLE
Select keepass file from server host

### ISSUE THREAD

**Issue by xathon** [keeweb/keeweb#1667]
**Is your feature request related to a problem? Please describe.**
I'm hosting Keeweb on the same server I use to backup my KeePass file. Uploading the file every time I want to use it feels redundant.

**Describe the solution you'd like**
I'd like Keeweb to find Keepass files that are in a predetermined or configured location on the server. That way the file is directly selected and it only needs the decryption password to access the vault.

**Comment by antelle** [comment]
Hi! You need two things here:
1. set up or enable [webdav](https://github.com/keeweb/keeweb/wiki/WebDAV%20Config) on this server
2. create a [config](https://github.com/keeweb/keeweb/wiki/Configuration#json-app-config), so that your files appears automatically

**Comment by xathon** [comment]
Thanks for the insights. I'd hoped there was a way to do that without spinning up a local webdav, but alas.

**Comment by antelle** [comment]
Just HTTP with GET/PUT will be also enough, to make it work without WebDAV, change this setting:
![image](https://user-images.githubusercontent.com/633557/103300674-b9586c00-49ff-11eb-9e3d-a49b94e1fb42.png)

**Comment by xathon** [comment]
So, I set up a local WebDAV server and verified that it's working (though only with a self-signed certificate) and enabled CORS. Though I still get "network error" when trying to enter the keepass file. Is there something I'm doing wrong or is there some way to see what exactly the problem was?
This is the console output:
![image](https://user-images.githubusercontent.com/36819668/103376147-23464380-4adc-11eb-8ecd-8799a00f79d4.png)

**Comment by antelle** [comment]
Let's check your Network tab in DevTools

**Comment by xathon** [comment]
![image](https://user-images.githubusercontent.com/36819668/103376373-c434fe80-4adc-11eb-8772-255d48194bd6.png)
![image](https://user-images.githubusercontent.com/36819668/103376433-e3cc2700-4adc-11eb-947f-b27a0a530285.png)

Anything else from there that might help?

**Comment by xathon** [comment]
The ports are different because keeweb and webdav are running in a docker container

**Comment by antelle** [comment]
Strange, usually it shows an error, like for example options request failed. What was the request method (it's possible to select it in the list of fields)?

**Comment by antelle** [comment]
Another question, if you select the other one, with fetch, what does it show inside?

**Comment by antelle** [comment]
I just tried it on app.keeweb.info, it gives the same error if you do fetch on another port. So, it's not possible, you need to host keeweb on the same webdav server as well.

**Comment by antelle** [comment]
Hm, maybe I'm wrong, it just doesn't report CORS errors in this case.

**Comment by antelle** [comment]
Ok, I was able to make a minimal working example with two ports setup as you describe:
```js
const { createProxyServer } = require('http-proxy');
const { createServer } = require('https');
const { readFileSync } = require('fs');

const ssl = { key: readFileSync('key.pem', 'utf8'), cert: readFileSync('cert.pem', 'utf8') };

createProxyServer({
    ssl,
    target: { protocol: 'https:', host: 'app.keeweb.info', port: 443 },
    changeOrigin: true
}).listen(8000);

createServer(ssl, (req, resp) => {
    const data = readFileSync('db.kdbx');
    resp.writeHead(200, 'OK', {
        'Content-Type': 'application/octet-stream',
        'Content-Length': data.byteLength,
        'Content-Disposition': 'attachment; filename="db.kdbx"',
        'Access-Control-Allow-Origin': 'https://127.0.0.1:8000',
        'Access-Control-Allow-Headers': '*'
    });
    resp.end(data);
}).listen(8001);

console.log('KeeWeb: https://127.0.0.1:8000');
console.log('KDBX: https://127.0.0.1:8001/db.kdbx');
```

Then go to https://127.0.0.1:8000 and add https://127.0.0.1:8001/db.kdbx as WebDAV, it works. Now you need to find what's different in your setup.

**Comment by xathon** [comment]
> What was the request method (it's possible to select it in the list of fields)?
For the site itself, it was GET. There was no request method shown for the .kdbx file.

> if you select the other one, with fetch, what does it show inside?
![image](https://user-images.githubusercontent.com/36819668/103379042-93f15e00-4ae4-11eb-9b26-e8aaa6d90ae9.png)
If this is what you mean, I don't see any meaningful difference.

> So, it's not possible, you need to host keeweb on the same webdav server as well.
I mean, it's probably easiest to do that, so I don't have to set up another webserver.

> Ok, I was able to make a minimal working example with two ports setup as you describe:
Thanks! I'll try that in a bit and report back.

**Comment by antelle** [comment]
HTTP method can be selected this way. That's what it shows for me:

![image](https://user-images.githubusercontent.com/633557/103379533-3c53f200-4ae6-11eb-8e8e-8ff45bc16cd0.png)

**Comment by antelle** [comment]
I think it was `HEAD`, because it shows this in the error log you pasted above. Have you switched the setting to "Overwrite the kdbx file with PUT"?

**Comment by xathon** [comment]
Ah, I see. Yeah, it was HEAD, both before and after I switched to the "Overwrite the kdbx file with PUT" setting. 

The node server didn't work for me, when I checked `netstat -tulpn` it looked like it was only exposing its ports on IPV6:
```Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 0.0.0.0:80              0.0.0.0:*               LISTEN      1/nginx: master pro
tcp        0      0 0.0.0.0:443             0.0.0.0:*               LISTEN      1/nginx: master pro
tcp        0      0 127.0.0.11:33857        0.0.0.0:*               LISTEN      -
tcp6       0      0 :::80                   :::*                    LISTEN      1/nginx: master pro
tcp6       0      0 :::8001                 :::*                    LISTEN      3109/node
tcp6       0      0 :::8002                 :::*                    LISTEN      3109/node
udp        0      0 127.0.0.11:46003        0.0.0.0:*
```

> So, it's not possible, you need to host keeweb on the same webdav server as well.

As for this, it looks like nginx has some problems with hosting webdav, for some reason. So I'll keep trying to use Apache for the Webdav (worst case, I'll just move keeweb from nginx to Apache).

**Comment by antelle** [comment]
Just tested it on nginx, works for me as well, here's my config:

1. for one host mode, when KeeWeb is hosted on the same host as data stored in `files` directory:
```
server {
    listen 443;
    server_name kw-test.antelle.net;
    error_page 404 /404.html;
    error_page 500 502 503 504 /50x.html;
    ssl on;
    ssl_certificate /etc/ssl/certs/antelle.net.crt;
    ssl_certificate_key /etc/ssl/certs/antelle.net.key;
    ssl_protocols TLSv1.2 TLSv1.3;
    root /var/static/kw-test;
    location /files {
        dav_methods PUT;
    }
}
```
KeeWeb: https://kw-test.antelle.net
File: https://kw-test.antelle.net/files/Demo.kdbx

2. two hosts mode, one for KeeWeb and the other one for files:

`kw-test.conf`:
```
server {
    listen 443;
    server_name kw-test.antelle.net;
    error_page 404 /404.html;
    error_page 500 502 503 504 /50x.html;
    ssl on;
    ssl_certificate /etc/ssl/certs/antelle.net.crt;
    ssl_certificate_key /etc/ssl/certs/antelle.net.key;
    ssl_protocols TLSv1.2 TLSv1.3;
    root /var/static/kw-test;
}
```

`kw-test-files.conf`:
```
server {
    listen 443;
    server_name kw-test-files.antelle.net;
    error_page 404 /404.html;
    error_page 500 502 503 504 /50x.html;
    ssl on;
    ssl_certificate /etc/ssl/certs/antelle.net.crt;
    ssl_certificate_key /etc/ssl/certs/antelle.net.key;
    ssl_protocols TLSv1.2 TLSv1.3;
    root /var/static/kw-test/files;
    dav_methods PUT;
    location / {
        add_header 'Access-Control-Allow-Origin' 'https://kw-test.antelle.net' always;
        add_header 'Access-Control-Allow-Credentials' 'true' always;
        add_header 'Access-Control-Allow-Methods' 'GET, HEAD, POST, PUT, OPTIONS, MOVE, DELETE, COPY, LOCK, UNLOCK' always;
        add_header 'Access-Control-Allow-Headers' 'Authorization,DNT,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,X-Accept-Charset,X-Accept,origin,accept,if-match,destination,overwrite' always;
        add_header 'Access-Control-Expose-Headers' 'ETag' always;
        add_header 'Access-Control-Max-Age' 1728000 always;
        if ($request_method = 'OPTIONS') {
            add_header 'Content-Type' 'text/plain charset=UTF-8';
            add_header 'Content-Length' 0;
            add_header 'Access-Control-Allow-Origin' 'https://kw-test.antelle.net';
            add_header 'Access-Control-Allow-Credentials' 'true';
            add_header 'Access-Control-Allow-Methods' 'GET, HEAD, POST, PUT, OPTIONS, MOVE, DELETE, COPY, LOCK, UNLOCK';
            add_header 'Access-Control-Allow-Headers' 'Authorization,DNT,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,X-Accept-Charset,X-Accept,origin,accept,if-match,destination,overwrite';
            add_header 'Access-Control-Expose-Headers' 'ETag';
            add_header 'Access-Control-Max-Age' 1728000;
            return 204;
        }
    }
}
```

KeeWeb: https://kw-test.antelle.net
File: https://kw-test-data.antelle.net/Demo.kdbx

I dunno, works well for me both ways.

// for those who came here to try my webdav, those hosts are already disabled

**Comment by xathon** [comment]
The one host mode worked. Thanks a lot for your help!
