### ISSUE TITLE
Error FileCorrupt: bad xml

### ISSUE THREAD

**Issue by muchao512** [keeweb/keeweb#1668]
Hi, keeweb:
    I am new to KeeWeb. I just create a passwrod file. But, I am not able to open it after I edit it a few times. And it says:
    KdbxError: Error FileCorrupt: bad xml: This page contains the following errors: error on line 1 at column 3833: PCDATA invalid Char value 8

    I put some Chinese charactors, english letters and "-" in my password file. 
    I hope the information that I provide could help.
    PS: I run it on MacOS.

Charles Mu

**Comment by antelle** [comment]
Hi! Interesting, can you please share what you put there?

**Comment by muchao512** [comment]
> Hi! Interesting, can you please share what you put there?

I put "教育网" for a title of one of my entry. Sorry I cannot provide the file because of sensitive info inside. I am wondering is that an accident or I ran it with some wrong doings.

**Comment by antelle** [comment]
This word works for me, I think the reason was something else, like an invisible space, Chinese characters should be fine but maybe there are special ones. That's [what](https://unicode-table.com/en/0008/) you have in your file, the error says `invalid Char value 8`. We had this bug in the past, however, I assume the fix doesn't work in some cases. Do you need this file, or you have a backup? I can make a version that would open this file.

**Comment by antelle** [comment]
We actually have a tool for converting kdbx to xml: https://keeweb.info/tools/kdbx-to-xml.html
It's the same as KeeWeb, it doesn't upload your file anywhere and works in your browser.

Could you please try your file there? After you get the xml, open it in any editor and check what's located at `1:3833` and a couple of characters around it?

**Comment by antelle** [comment]
I've fixed it, v1.16.6 should work with your file, it will be live in an hour.

**Comment by antelle** [comment]
It's released

**Comment by muchao512** [comment]
> It's released

It works well now! Thank you very much.

That website put earlier cannot convert all my kdbx files(including unaccessed and accessed ones) to xml. There was an alert says: "KdbxError: Error NotImplemented: Argon2 not implemented." But anyway, I can enjoy it now.  👍
