### ISSUE TITLE
Keeweb lost file

### ISSUE THREAD

**Issue by rishikarri** [keeweb/keeweb#1669]
**Describe the bug**
Today when I tried to use the keeweb desktop app, all of my files were gone. I did not delete them at any point. Have you seen this before? 

**Expected behavior**
Files are available like the "New" one created for this screenshot

**Screenshots**
<img width="888" alt="Screen Shot 2020-12-29 at 7 00 28 PM" src="https://user-images.githubusercontent.com/23086217/103323390-41427400-4a08-11eb-86fe-ea551f34bd00.png">

**Comment by antelle** [comment]
Hi! Most likely the settings were erased, what happened since last time it was launched successfully, have you maybe restored a system backup, installed a big update, or similar?
Are there your files available in `~/Applications/KeeWeb/OfflineFiles`?

**Comment by rishikarri** [comment]
No there is nothing at that location :( - it's possible I did something along those lines.... I didn't realize that would delete those files. Thank you for your response though! Will keep backups from now on.

**Comment by antelle** [comment]
Ok then it’s unfortunately not much we can do here...
