### ISSUE TITLE
Formatting of notes is not preserved

### ISSUE THREAD

**Issue by alexanderharm** [keeweb/keeweb#1671]
**Describe the bug**
I often add a lot of unstructured information to the notes field of entries.  It really annoys me that KeeWeb seems to destroy the formatting as soon as I leave the field.

```
Lorem ipsum

dolor sit amet
```

becomes

```
Lorem ipsumdolor sit amet
```

Which feels strange because it should even support Markdown...

**To Reproduce**
1. Go to notes field of entry
2. Add more than one line (use Shift-Return at least on macOS)
3. Leave field

**Expected behavior**
Preserve formatting of notes.

**Screenshots**
<img width="308" alt="Screenshot 2020-12-31 at 14 25 51" src="https://user-images.githubusercontent.com/16108584/103412217-50decb80-4b74-11eb-9fce-793a7a975b85.png">
<img width="458" alt="Screenshot 2020-12-31 at 14 25 59" src="https://user-images.githubusercontent.com/16108584/103412219-52a88f00-4b74-11eb-81e9-d7a6f05fb107.png">

**Environment**
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) KeeWeb/1.16.6 Chrome/87.0.4280.67 Electron/11.0.3 Safari/537.36

**Kdbx File**
New and existing files.

**Logs**
Nothing related in the logs.

**Comment by antelle** [comment]
Hi! Thanks, this happened in the last release after c06db5a2b708407c178c14c937c1d48ffdf0c0d2, will be fixed soon.

**Comment by antelle** [comment]
Fixed, it's [building](https://github.com/keeweb/keeweb/actions/runs/454808392)...

**Comment by antelle** [comment]
The fix is [released](https://github.com/keeweb/keeweb/releases/latest), but I have some bad news: v1.16.6 destroys newlines everywhere in the file, so if you have a backup, you might want to restore from it and redo changes you made with v1.16.6.

**Comment by alexanderharm** [comment]
No prob for me, this issue was there for quite some time so we are used to it.

**Comment by alexanderharm** [comment]
Thanks for the quick fix!!!

**Comment by antelle** [comment]
You're welcome, happy new year! 🍾
