### ISSUE TITLE
OneDrive does not load in web app, but works fine from desktop

### ISSUE THREAD

**Issue by lafmbits** [keeweb/keeweb#1672]
**Issue**
This is what I am experiencing:
1. Go to https://app.keeweb.info/
2. click More > OneDrive
3. the "Trying to Sign you in..." window from Microsoft appears
4. It returns to the web app and does not show the list of files. Nothing changes at all, in fact.
5. Clicking the OneDrive button again simply causes the same window to appear and disappear.

**Expected**
However, this functionality works perfectly fine from the Windows Desktop app. It authenticates me with Microsoft, the directory listing from OneDrive comes up, and the kdbx file can be opened without issue.

**Environment**
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36 Edg/87.0.664.66

I am using Microsoft Edge, Chromium, to test. 

This OneDrive account is part of a commercial Microsoft 365 account.

**Logs**
[INFO ] 2021-01-01T21:26:40.295Z [start-profiler] App started in 366ms: fetching=5ms, pre-init=138ms, loading modules=112ms, document ready=15ms, creating app model=5ms, loading configs=1ms, initializing modules=2ms, loading remote config=1ms, checking features=3ms, initializing storage=0ms, first view rendering=90ms, app ready event=0ms
[INFO ] 2021-01-01T21:26:40.339Z [updater] Service worker registered
[DEBUG] 2021-01-01T21:26:41.902Z [storage-onedrive] OAuth: popup opened
[DEBUG] 2021-01-01T21:26:43.042Z [storage-onedrive] OAuth code received
[INFO ] 2021-01-01T21:26:43.042Z [storage-onedrive] HTTP request POST https://login.microsoftonline.com/common/oauth2/v2.0/token
[ERROR] 2021-01-01T21:26:43.265Z [storage-onedrive] Error exchanging OAuth code network error

**Comment by antelle** [comment]
Hi! Does it work with a personal account? I think we have some issues with corporate OneDrive.

**Comment by lafmbits** [comment]
> Hi! Does it work with a personal account? I think we have some issues with corporate OneDrive.

Yes, I just tested with my personal OneDrive account, and it works fine.

**Comment by antelle** [comment]
I see, then it's the same as #1633
