### ISSUE TITLE
Make provided password generator presets editable

### ISSUE THREAD

**Issue by snakyjake1** [keeweb/keeweb#1673]
**Is your feature request related to a problem? Please describe.**
I cannot edit the provided preset password generator (example: "* default preset"). 

**Describe the solution you'd like**
I would like to edit the provided password generator.

**Describe alternatives you've considered**
Create new password generator.  But doesn't make sense to create two different "default presets".

![image](https://user-images.githubusercontent.com/8312560/103470092-8a2a5d80-4d65-11eb-9e87-41dfc628681e.png)

**Comment by antelle** [comment]
Hi! If you add your own template, you can mark it as default, then it will be selected in the generator when you open it.
