### ISSUE TITLE
WebDAV file path displayed on hover

### ISSUE THREAD

**Issue by junglebells** [keeweb/keeweb#1676]
Using self hosted KeeWeb v1.16.7 (42b5b00, 2020-12-31)
Using WebDAV
Config file has the list of files and their respective path

On the main screen, list of files and their names are displayed, which is great. However, if you hover over these names, the path of the actual webdav storage (as entered in config.json) is displayed.

Is there a way to suppress the file path on hover?

**Comment by antelle** [comment]
Hi! It doesn't make a lot of sense to hide it, since it will be possible to see the url using devtools, settings, just load the config etc...
