### ISSUE TITLE
Key file name shown in next session (web version)

### ISSUE THREAD

**Issue by givebackfi** [keeweb/keeweb#1687]
**Describe the bug**
When you leave a session in chrome or mozilla, on return the name of the last keyfile is shown under the password field. A kdbx secured only by key file, particularly one with a unique name, could easily be found if a machine with key attached were accessed.  It would be preferable that an inside attacker not know the name of our key file...

**To Reproduce**
1. Go to app.keeweb.info
2. open a kdbx file secured by key
3. open key file
4. enter file
5. close file / tab / browser
6. return to app.keeweb.info (note what filenames you can see)

**Expected behavior**
Clear the key file name before/after the session!

**Environment**
web (tested on macos and chromeos)

**Comment by antelle** [comment]
Well, if you're concerned about this, you can rename the filename to something like "data", add it to KeeWeb, and then rename the file, then it won't be possible to find it by name. Or disable the "remember keyfiles" option at all. I'm not sure how we can display that a keyfile is in use without displaying its name.

**Comment by givebackfi** [comment]
It's not in use if you haven't opened the file yet.

I don't see why it wouldn't just make sense to clear the keyfile name and make the user find it...it makes you do that anyway. Try to log in the second time around using the key file that is already there, it fails (as it should).  that's not right behavior.  please consider reopening this issue. it would be quite an easy fix...

**Comment by givebackfi** [comment]
Behavior differs from desktop.  At a minimum it's worth considering what the expected behavior actually should be.

**Comment by antelle** [comment]
On desktop you can remember only path to keyfiles, without the keyfile itself (you can change it in settings).  
So, when you rename the keyfile, KeeWeb can't read it and there's an error. If you switch it to "remember keyfiles", it will be the same.
