### ISSUE TITLE
Oauth redirect URL not found in Keeweb docker

### ISSUE THREAD

**Issue by mattjcj** [keeweb/keeweb#1688]
**Describe the bug**
I configured my server to proxy Keeweb, so that it is located at https://host/keeweb and not at the root of the server.
When trying to connect using Oauth to Dropbox (and probably others as well but I didn't try), at the end of the login, I'm redirected to https://host/oauth-result/dropbox.html (as mentioned in the docs) instead of https://host/keeweb/oauth-result/dropbox.html 

**To Reproduce**
1. Configure any reverse proxy you want to redirect requests to http://host/keeweb to your Keeweb docker instance
2. Click on the Dropbox icon
3. Finish the Oauth process
4. 404 error

**Expected behavior**
Keeweb finishes the Oauth process (redirected on https://host/keeweb/oauth-result/dropbox.html)
(Maybe the fix is to just concatenate the path to window.location.origin ? But I'm not sure if it'll break something else https://github.com/keeweb/keeweb/blob/0e2475e6679a234049b061739dcf66ad5900d273/app/scripts/storage/storage-base.js#L205)

**Environment**
KeeWeb v1.16.7 (42b5b00, 2020-12-31)
Environment: web
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_3) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.0.3 Safari/605.1.15

**Kdbx File**
New database

Thanks !

**Comment by antelle** [comment]
Thanks for the detailed description! Will be fixed in the next version.

**Comment by antelle** [comment]
I just tested it, and it works correctly in `keeweb` folder. What is the url in your browser when you open it: `https://host/keeweb` or `https://host/keeweb/`? If it's the first variant, without slash, I don't think we'll be able to do anything with it. What you can do, is make a redirect so that typing `keeweb` redirects to `keeweb/`.
