### ISSUE TITLE
Onedrive unable to connect

### ISSUE THREAD

**Issue by msalhab767** [keeweb/keeweb#1689]
**Describe the bug**
Whenever I try to login to Onedrive through keeweb portal I receive the following message.

We're unable to complete your request
invalid_request: The provided value for the input parameter 'redirect_uri' is not valid. The expected value is a URI which matches a redirect URI registered for this client application.

**To Reproduce**
1. Run keeweb latest docker version
2. Onedrive
3. Login using your personal email

**Expected behavior**
If i compare the online version of keeweb to my locally installed one, using the online version i am able to login to Onedrive. The local version is 1.16.7 based on docker latest image.

**Environment**
Android chrome

**Kdbx File**
Trying to load it from onedrive

**Comment by antelle** [comment]
Hi! You need to create your own app in OneDrive to be able to work from a self-hosted installation: https://github.com/keeweb/keeweb/wiki/Dropbox%20and%20GDrive#onedrive
