### ISSUE TITLE
Add Apple Silicon to the Homebrew formula

### ISSUE THREAD

**Issue by xavierraffin** [keeweb/keeweb#1691]
**Is your feature request related to a problem? Please describe.**
Keeweb on Mac M1 is running on Rosetta 2: intel emulation mode.
Electron 11 [support Mac m1](https://www.electronjs.org/blog/electron-11-0) which should make the native build possible.

**Describe the solution you'd like**
A build for Arm based CPUs, especially M1 mac.

**Describe alternatives you've considered**
Running on intel emulation, which has a performance impact.

**Comment by antelle** [comment]
Hi! 👋 
Check it out: https://github.com/keeweb/keeweb/releases/download/v1.16.7/KeeWeb-1.16.7.mac.arm64.dmg 😉 
When downloading a build from keeweb.info, you should click this small guy:
<img width="271" alt="Screen Shot 2021-01-23 at 08 08 30" src="https://user-images.githubusercontent.com/633557/105571661-343c4a80-5d52-11eb-8079-6c8411fddb8b.png">

**Comment by xavierraffin** [comment]
@antelle thanks I installed it with brew and got the x86.
So do I create another issue for brew native packaging support on M1?

**Comment by antelle** [comment]
I see, thanks! We should update the brew formula indeed. You can leave it here, I'll edit the ticket.

**Comment by antelle** [comment]
Done, it should work now
