### ISSUE TITLE
documentation webdav usage in app.keeweb.info?

### ISSUE THREAD

**Issue by ace-at-git** [keeweb/keeweb#1692]
Hello keeweb-team,

I am new to keeweb and password safes, so maybe I miss something essential...

My intended use case is that I store the *.kdbx file on my self hosted nextcloud server via webdav protocol, with dynamic DNS and letscypt cert. That part is working already for long time ;-)

In order to minimize installation effort on various PCs and potentially Android devices I would like to use directly https://app.keeweb.info. If I am correct the browser would cache the *.kdbx file and I could access it also without internet connection?!
So I opened my Firefox and accessed the url and the app appears, good so far. Selecting webDAV shows me a dialog to put the url in webDAV style to the *.kdbx file and the login credentials of my nextcloud, but... instead of opening the file I see rotating dotts in the OK button for ages!

Using Firefox developers console I see various error messages:
* cross-origin blocked
* service worker type error
* uncaught type error

With my limited knowledge, I tried to change several nginx/nextcloud settings I found when using internet search on those errors - but I failed with that.

Strangely, it works like expected when I installed the *deb package on a Debian/Gnome PC, so the webDAV/nextcloud access to the *.kdbx file works!

I start to think that I miss something more obvious for my use case. I would appreciate if someone could point me to the right direction or appropriate documentation!

Kind regards

Bernd

**Comment by antelle** [comment]
Hi! You probably need to setup CORS on your WebDAV server. I'm not sure how to do it with nextcloud, we have some docs [here](https://github.com/keeweb/keeweb/wiki/WebDAV%20Config), but probably it's not what you're looking for.
