### ISSUE TITLE
Self-hosting Failed, WebCrypto is not supported

### ISSUE THREAD

**Issue by YohaneWW** [keeweb/keeweb#1694]
**Describe the bug**

I used Nginx as a http server to run KeeWeb. Everything is ok on Safari but It shows "WebCrypto is not supported" on Firefox, I sure my browser is supported WebCrypto and the [DemoWeb](https://app.keeweb.info/) also works fine.

It shows "WebAssembly, Resource not reload." in Firefox development tools, it may help.

Nginx conf:

```
server {
listen 80 default_server;

location /keeweb/ {
    alias /www/keeweb/;
    }
}
```

**Environment**

Firefox 78.6.1 ESR

Safari 14.0.2

**Comment by antelle** [comment]
Hi! You should host it on https, not http

**Comment by YohaneWW** [comment]
> Hi! You should host it on https, not http

Thanks for replying!

I just want to host it on my LAN, if any way to only use http?

**Comment by antelle** [comment]
No, there’s no wat to use http.

**Comment by antelle** [comment]
You can create a self-hosted certificate though

**Comment by YohaneWW** [comment]
> You can create a self-signed certificate though

Ok, many thanks!
