### ISSUE TITLE
AutoType on Mac is not working since last bigger update (1.16)

### ISSUE THREAD

**Issue by kochn** [keeweb/keeweb#1696]
**Describe the bug**
After the update at the beginning of the year, the AutoType is not working. After I type [Ctrl]+[Option]+T KeeWeb opens for entering my kdbx-Password. After that I have to choose the entry (although before the recognization of the right entry happened automatcally). The focus switch back to the application but nothing happens although the focus is on the user field.

**To Reproduce**
1. Focus the username field of your target application
2. Type the shortcut for AutoType [Ctrl]+[Option]+T
3. Choose your target entry
4. Focus has been switched
5. Nothin Happened
 
**Expected behavior**
Usually KeeWeb already choose the right Entry based on the entry name or website. But I have to choose it manually. 
After I selected the right entry in the auto-type prompt, KeeWeb should start to type: username[Tab]Password[Return] the target application after switching the focus.

**Environment**
KeeWeb v1.16.7 (42b5b00, 2020-12-31)
Environment: electron v11.0.3
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 11_1_0) AppleWebKit/537.36 (KHTML, like Gecko) KeeWeb/1.16.7 Chrome/87.0.4280.67 Electron/11.0.3 Safari/537.36

**Kdbx File**
See attached file. Password is: testpassword
There is one Entry with: GitHub. You can try it with this file for auto-type on https://github.com

[AutotypeDemo.kdbx.zip](https://github.com/keeweb/keeweb/files/5902137/AutotypeDemo.kdbx.zip)

**Logs**
```
index.html:1 2021-02-01T05:53:14.462Z [auto-type] Auto type event null
index.html:1 2021-02-01T05:53:14.464Z [auto-type] Getting window info
index.html:1 2021-02-01T05:53:15.230Z [launcher] spawn osascript: 0, 765ms
2671244 firefox
index.html:1 2021-02-01T05:53:15.821Z [launcher] spawn osascript: 1, 591ms

156:161: execution error: „System Events“ hat einen Fehler erhalten: osascript hat keine Berechtigung für den Hilfszugriff. (-1719)
   r.error @ index.html:1
   (anonymous) @ index.html:1
   emit @ events.js:315
   maybeClose @ internal/child_process.js:1021
   ChildProcess._handle.onexit @ internal/child_process.js:286
index.html:1 2021-02-01T05:53:15.822Z [auto-type] Error getting window info Exit code 1
   r.error @ index.html:1
   (anonymous) @ index.html:1
   (anonymous) @ index.html:1
   (anonymous) @ index.html:1
   emit @ events.js:315
   maybeClose @ internal/child_process.js:1021
   ChildProcess._handle.onexit @ internal/child_process.js:286
index.html:1 [Violation] 'keypress' handler took 157ms
[Violation] Forced reflow while executing JavaScript took 40ms
index.html:1 2021-02-01T05:53:33.925Z [auto-type] Entry selected {entry: Proxy, sequence: undefined}
index.html:1 2021-02-01T05:53:33.927Z [auto-type] Hide window
index.html:1 2021-02-01T05:53:34.036Z [auto-type] Getting window info
index.html:1 [Violation] 'setTimeout' handler took 488ms
index.html:1 2021-02-01T05:53:34.825Z [launcher] spawn osascript: 0, 788ms
2671244 firefox
index.html:1 2021-02-01T05:53:35.425Z [launcher] spawn osascript: 1, 600ms
156:161: execution error: „System Events“ hat einen Fehler erhalten: osascript hat keine Berechtigung für den Hilfszugriff. (-1719)
   r.error @ index.html:1
   (anonymous) @ index.html:1
   emit @ events.js:315
   maybeClose @ internal/child_process.js:1021
   ChildProcess._handle.onexit @ internal/child_process.js:286

index.html:1 2021-02-01T05:53:35.426Z [auto-type] Error getting window info Exit code 1
   r.error @ index.html:1
   (anonymous) @ index.html:1
   (anonymous) @ index.html:1
   (anonymous) @ index.html:1
   emit @ events.js:315
   maybeClose @ internal/child_process.js:1021
   ChildProcess._handle.onexit @ internal/child_process.js:286
index.html:1 2021-02-01T05:53:35.426Z [auto-type] Active window matches
index.html:1 2021-02-01T05:53:35.426Z [auto-type] Start {USERNAME}{TAB}{PASSWORD}{ENTER}
index.html:1 2021-02-01T05:53:35.427Z [auto-type] Parsed [op:USERNAME,op:TAB,op:PASSWORD,op:ENTER]
index.html:1 2021-02-01T05:53:35.428Z [auto-type] Resolved [**********************,key:tab,[*,*,*,*,*,*,*,*,*,*,*],key:enter]
index.html:1 2021-02-01T05:53:35.878Z [storage-file] Stop watch dir /Users/norbertkoch/Desktop
index.html:1 2021-02-01T05:53:36.057Z [launcher] spawn /Applications/KeeWeb.app/Contents/Resources/helper/darwin/KeeWebHelper: 0, 628ms
index.html:1 2021-02-01T05:53:36.057Z [auto-type] Complete 631ms
```

**Comment by antelle** [comment]
Hi!
> osascript hat keine Berechtigung für den Hilfszugriff

I think it should be fixed by adding KeeWeb to accessibility, see #953

**Comment by kochn** [comment]
Hi @antelle !

Thanks!

Just for note:
The confusing thing was, that the Accessibility was already checked and it was not possible to uncheck the option.
I had to remove the KeeWeb entry from the List within the Accessibility Section and add it from Application Folder.
After I restarted KeeWeb it worked as expected.

**Comment by antelle** [comment]
Yeah that’s how it usually works. I’ll try to add an explanation message to the app about it.
