### ISSUE TITLE
Database on removable media remains cached in-app

### ISSUE THREAD

**Issue by jstn** [keeweb/keeweb#170]
I'm using KeeWeb 1.0.4 (a6e7afe) locally on El Capitan, no key file or online sync. My database (with a passphrase) is on a removable encrypted drive, but it remains cached in the desktop app even when the drive is removed. This is very surprising behavior for a security app! There doesn't seem to be a way to disable this caching or easily locate where it exists on my (unencrypted) boot drive. At the very least there should be a warning to the user. Where else is KeeWeb caching my data that I'm not aware?

**Comment by antelle** [comment]
It was not caching files before, and caching was a frequent feature request, as most users keep db files on hard drive or cloud. For now, the only way to remove the cache is clicking delete (x) icon in last files list.
We should add caching as an option in settings.

**Comment by antelle** [comment]
In v1.2, files opened from local filesystem will not be saved to cache anymore. 
Cloud files will be cached though. There will be no option, as working with files not stored to cache results in extra complexity with locking, auto-locking, saving webdav passwords and other operations.
