### ISSUE TITLE
Password Server

### ISSUE THREAD

**Issue by GamerClassN7** [keeweb/keeweb#1700]
**Is your feature request related to a problem? Please describe.**
Hi, 
We use to use KEEWEB in our company unforchunatelly no more, now we are using: https://pleasantsolutions.com/passwordserver do you plan to support those password servers like KEEPASS do  ?
or  are you considering to make some server side solution. do each roup can have separet permission etc ? there is really nothing good at marked :)

Thank you for your answer in advance :)

**Comment by thefiredragon** [comment]
This would be a nice feature for multiple users where we could set permissions, We're using keeweb with our customers with own databases to solve this.

Also each one who can access an kdbx database can also Download this file. 
When keeweb would support users and permissions they would be Break lots of Things I think

**Comment by antelle** [comment]
Hi! We don't have any server-side product now. I'm not sure how this "password server" works, probably they return a kdbx file in some form and you need to connect to it. How does keepass open a file from this thing?

**Comment by GamerClassN7** [comment]
@antelle hi, i dont know how exactly it works but i guess it let you download KDBx with passwords for you or something they have some sort of api
https://pleasantsolutions.com/info/pleasant-password-server/m-programmatic-access/restful-api

**Comment by thefiredragon** [comment]
In theroy this would would Store all passwords in a big storage, based on user permissions it would collect for the user permission acessable entries and generate based on this a kdbx file. 
its a other system, for companys this handling would be better.
With ldap authentication and more features. Keeweb is focuced like other tools -> macpass etc.

**Comment by antelle** [comment]
So, it's not WebDAV, and if I read it correctly, they have API for entries, groups, etc... and they patched KeePass to support their server. In this case, it won't be possible to develop a plugin for KeeWeb and the only way of integration would be implementing support in KeeWeb. Which for obvious reasons won't happen here, unless they want to contribute it themselves.
