### ISSUE TITLE
New to Keeweb, cannot open kdbx which was used on Keepass 2 everyday

### ISSUE THREAD

**Issue by bnsonear** [keeweb/keeweb#1701]
Hi,
Today I firstly tried KeeWeb expecting perfect compatibility (I'm not using any plugin at Keepass),
but KeeWeb even cannot open the kdbx file I used everyday.
"Cannot open" means that the Keeweb's password input box's outline becomes redish and vibrated once when I pressed enter after typing password I know. Then nothing happens. I could not browse my kdbx file using KeeWeb.

I suspected my typo so I opened the kdbx with Keepass, and the file opened without any problems.
I'm not using any key file, just using a master password with the kdbx.

Is there any backward compatibility issues like doc & docx in kdbx format?
Or I have to apply some modifications on my kdbx to open it at KeeWeb?
I'm using that kdbx file on Android also, I wish that I can use the file without any modification in KeeWeb.

Any comment will be appreciated.

I'm using Windows 10 20H2 64 bit and the kdbx is located at OneDrive folder (saved in C drive via internal OneDrive app).
Windows is very fresh, just finished installation.

KeeWeb v1.16.7 (42b5b00, 2020-12-31)
Environment: electron v11.0.3
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) KeeWeb/1.16.7 Chrome/87.0.4280.67 Electron/11.0.3 Safari/537.36

**Comment by antelle** [comment]
Hi! If it doesn't open, it means the password is wrong. To make sure it's this, open the devtools and check the logs there. If you're using a desktop app, devtools are in Settings / General / Advanced.

**Comment by bnsonear** [comment]
@antelle  
> 
> Hi! If it doesn't open, it means the password is wrong. To make sure it's this, open the devtools and check the logs there. If you're using a desktop app, devtools are in Settings / General / Advanced.

Thank you for your response.
Of course I tested copy & paste method to prevent typo.
With the same master password, KeePass 2.47 could open the kdbx but KeeWeb could not.

I checked the log as you instructed, and result was what you said. I attached it below;
> 2021-02-03T06:56:02.272Z [open:20660207-7200rpm] File open request
> 2021-02-03T06:56:02.273Z [open:20660207-7200rpm] Open file from supplied content
> 2021-02-03T06:56:02.273Z [storage-file] Stat C:\Users\GitHub\OneDrive\20660207-7200rpm.kdbx
> 2021-02-03T06:56:02.274Z [storage-file] Stat done C:\Users\GitHub\OneDrive\20660207-7200rpm.kdbx 1ms
> 2021-02-03T06:56:02.279Z [file] Error opening file InvalidKey Error InvalidKey: invalid key t {name: "KdbxError", code: "InvalidKey", message: "Error InvalidKey: invalid key"}

Additionally, I am using Colemak layout which are configured by official setup program from Colemak site.
Keyboard layout would not a root cause because the issue occurs with copy & paste method.

I want to try KeeWeb because I am tired of outdated UI of KeePass.
Please let me know I have to do anything to help you inspect this issue.
Thank you for hearing me, cheers!

**Comment by antelle** [comment]
Well, it means the password or key was wrong.  
What happens if you make a new file with the same setup and a very simple password like "1" and open it in keeweb, does it work?

**Comment by bnsonear** [comment]
>  does it work?

@antelle , thank you for your response.
I made a new database with the same master password instead of "1" using Keepass 2.47, and KeeWeb finally opened that file flawlessly.

Then, what should I do? Is there really compatibility issues between kdbx versions? Or KeeWeeb doesn't support old kdbx version?
Should I update my kdbx to the lastest version?

**Comment by antelle** [comment]
Interesting, if the version is old, KeeWeb would tell about it. But you can try changing version to kdbx4 in KeePass file settings. What do you have there now?

**Comment by bnsonear** [comment]
Thank you for your help.
In KeePass, File - Export - Export File/Data menu existed and various format was listed.
Among them, KDB related formats are below:

KeePass KDB (1.x)
KeePass KDBX (2.x)
KeePass KDBX (2.34, Old Format)

I choose KeePass KDB (2.x), and the exported  file could be opened by KeeWeb also.
According to your mention, flie format checking and log system should be slightly improved.
Now I can use KeeWeb, I really appreciate!
P.S. Where is duplicated button for item? I use it frequently in KeePass, but I couldn't find it.

**Comment by antelle** [comment]
Interesting, I'll check what v2.34 is, we should of course show a warning like we do for v1.

**Comment by antelle** [comment]
It works for me if I export to v2.34 or v2 and gives an error for v1.  
Well, since it's solved, I'll close this issue.
