### ISSUE TITLE
url kdbx chaining/linking

### ISSUE THREAD

**Issue by mharj** [keeweb/keeweb#1704]
keepass itself can handle multiple kdbx:s which can be chain opened with password (if kdbx url override is enabled).
i.e. url like "kdbx://some_file_path%{ENV_DIRSEP}Database.kdbx"
This makes project based setups which can be i.e. opened like "personal vault" => "company main vault" => "project x/y/z vault"
Also other url open handlers at least in electron would be great.

**Comment by antelle** [comment]
Hi! It's #321
