### ISSUE TITLE
How does OneDrive sync work?

### ISSUE THREAD

**Issue by Boris-Sachet** [keeweb/keeweb#1706]
Hello, and sorry to create an issue for that but I can't find any information onlyne on how the OneDrive syncronisation is supposed to work.

I opened an existing local vault, enabled OneDrive sync, but there's no options, nothing to log into OneDrive, nor to choose the syncronisation path.
And yet KeeWeb tells me he synced my vault a few minutes ago, but synced with what? There's nothing configured (and obviously nothing was uploaded to my onedrive)

If anyone could enlight me there, it's really confusing.

**Comment by antelle** [comment]
Hi! You need to save your file to OneDrive in KeeWeb or open it from OneDrive. Then the file should appear in OneDrive.

**Comment by Boris-Sachet** [comment]
Thanks!
Is there any way to choose wich OneDrive account it connects to? It tries to connect to my work office 365 account wich is connected on some tools on this computer but is neither the main microsoft account of my user profile or the currently connected microsoft account in the browser where the login page opens. I dont get why it tries to use this account...

Here's what it looks like (sorry for the french), no switch account option.
![image](https://user-images.githubusercontent.com/74542867/107073604-db57c200-67e7-11eb-89b8-c5c0686a6c40.png)

**Comment by antelle** [comment]
I guess, you can sign out of all other accounts, and then select the one you need in KeeWeb. After this you can sign in again.
