### ISSUE TITLE
[Feature request] Syncronisation to more then one different source

### ISSUE THREAD

**Issue by Rurik19** [keeweb/keeweb#171]
I think it would be useful to open (and save) file from one source (say, WebDav) and sync it to one or to  other (say, OneDrive or Dropbox )  -- some type of backup.

**Comment by antelle** [comment]
This will be done in Backup but I think only FS and WebDAV backup will be supported.

**Comment by y0ast** [comment]
Please also consider supporting OneDrive/GDrive/Dropbox for backup. It doesn't need to instantly sync, but just replace the kdbx file at that place every week or so.

**Comment by antelle** [comment]
Deployed to [beta.keeweb.info](https://beta.keeweb.info), will be available in the next release.
v1.3 will support backups only to Dropbox and local files.
![keeweb 2016-08-21 19-47-33](https://cloud.githubusercontent.com/assets/633557/17838522/282a734e-67d8-11e6-9549-a7a735337b3f.png)

**Comment by nopivnick** [comment]
was this feature deprecated?

I can't for the life of me find it in Settings.

**Comment by antelle** [comment]
@nopivnick backups are here, they're not deprecated

**Comment by nopivnick** [comment]
I sincerely apologize for being so dense but could you tell me where exactly?

I can't find it in Settings:

![screen shot 2018-08-22 at 5 17 23 pm](https://user-images.githubusercontent.com/688639/44491583-b5e29800-a62f-11e8-9086-9c1c7b61a405.png)

![screen shot 2018-08-22 at 5 18 19 pm](https://user-images.githubusercontent.com/688639/44491590-b8dd8880-a62f-11e8-9d49-8d5bd604f681.png)

**Comment by antelle** [comment]
Click the last item on the left, it's called "keepass-something..."

**Comment by nopivnick** [comment]
crap.

thank you.
