### ISSUE TITLE
Can't use Dropbox in webapp on iPhone (Safari, Chrome and Firefox affected)

### ISSUE THREAD

**Issue by lukenowak** [keeweb/keeweb#1711]
**Describe the bug**

I am using app.keeweb.info successfully on my laptop and Android phone. I use dropbox for sharing the password file.

While trying to add Dropbox file on the iPhone with any browser, after logging correctly to dropbox the additional window stays open on url https://app.keeweb.info/oauth-result/dropbox.html?state=XXX&code=XXX and does not come to the app itself.

Retried few times, no effect (while being already logged in, I was able to access my dropbox conent)

**To Reproduce**
1. Use iphone, Firefox, Chrome or Safari
2. Go to 'app.keeweb.info'
3. Click on 'three dots', then 'dropbox', login sucesfuly to dropbox
4. See that new opened tab stays in https://app.keeweb.info/oauth-result/dropbox.html?state=XXX&code=XXX

**Expected behavior**
I'd expect the tab to close and have access to my file in app.keeweb.info

**Screenshots**
none

**Environment**
Impacts all browsers on iOS 14.4

**Kdbx File**
Can't arrive to kdbx file.

**Logs**
I need help with this for the device.

**Comment by antelle** [comment]
This broke in iOS 14, I see a white screen as well... will take a look, thanks!

**Comment by antelle** [comment]
Ok, I figured out how to fix it, somehow the pop-up forgets who it is after authentication and ends up in a weird state when it can't close itself, but it's possible to check its url. I assume, it's a but in Safari, but the workaround seems to be very easy.

**Comment by antelle** [comment]
Uploaded the fix to beta, works for me, could you please check if it works?

https://beta.keeweb.info/

**Comment by lukenowak** [comment]
> Uploaded the fix to beta, works for me, could you please check if it works for you too (but probably it will)?

Unfortunately I still have the same behaviour on https://beta.keeweb.info/ on all mentioned browsers.

**Comment by antelle** [comment]
First I thought it happens only in the "pinned website", so I fixed it there, but not in browsers. Now it should work.

**Comment by lukenowak** [comment]
> Now it should work.

Yes, it does, thank you :)

**Comment by antelle** [comment]
Good, I'll make a release with it soon then
