### ISSUE TITLE
Add an "Edit" button

### ISSUE THREAD

**Issue by tcz305** [keeweb/keeweb#1714]
**Is your feature request related to a problem? Please describe.**
Sometimes clicking on the url field changes the field to edit rather than open the url. Also clicking other fields sometimes makes them unintentionaly editable.

**Describe the solution you'd like**
make all fields non-editable unless clicking an "Edit" button somewhere like next to the "change icon" key/button

**Additional context**
With this proposal all fields would become editable only after clicking the "Edit" icon ....editing could then either be completed by again clicking the "Edit" button or clicking the enter key or clicking anywhere outside a field.
This would also prevent accidental changes.

**Comment by antelle** [comment]
No, now the idea is, there are no Edit/Ok buttons
