### ISSUE TITLE
Cannot use KeeWeb with DropBox from Epiphany

### ISSUE THREAD

**Issue by Barugon** [keeweb/keeweb#1715]
I'm trying to connect to DropBox using the Gnome web browser (Epiphany). After logging in to DropBox, I just get a white page and I'm not able to select the kdbx file. This used to work. I don't know when or what changed to make it not work anymore.

KeeWeb v1.16.7 (42b5b00, 2020-12-31)
Environment: web
User-Agent: Mozilla/5.0 (X11; Fedora; Linux x86_64) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0 Safari/605.1.15

**Comment by antelle** [comment]
Hi! What is the url if this white page? 

Do you see anything interesting in logs?

**Comment by Barugon** [comment]
Here's the URL:
> https://app.keeweb.info/oauth-result/dropbox.html?state=e36a5dea2c54d25dddfa287260031fe62e2f3cf6a7112516f8507964f489f21bfce3439623dfb29bf9b30c92822d3208c4c4fbeccba1f6a350e754368c2388fa&code=L3mJmQBS1SEAAAAAAAAAJkFyzht11G-hhIBxw4yTDc0

Here's what the log says:
> [INFO ] 2021-02-17T07:06:54.478Z [start-profiler] App started in 360ms: fetching=40ms, pre-init=97ms, loading modules=42ms, document ready=111ms, creating app model=4ms, loading configs=1ms, initializing modules=1ms, loading remote config=1ms, checking features=1ms, initializing storage=0ms, first view rendering=102ms, app ready event=0ms
[INFO ] 2021-02-17T07:06:54.518Z [updater] Service worker registered
[DEBUG] 2021-02-17T07:07:02.741Z [storage-dropbox] List
[DEBUG] 2021-02-17T07:07:02.789Z [storage-dropbox] OAuth: popup opened

**Comment by Barugon** [comment]
The DropBox icon in the othr tab is just spinning.

**Comment by antelle** [comment]
Interesting, does it work with other browsers?

**Comment by Barugon** [comment]
Firefox works fine. I made this issue because of the Librem 5 phone, which uses Epiphany as it's default browser. It is possible to use Firefox but it's UI has a number of issues on phones.

**Comment by Barugon** [comment]
The DropBox login is opened in a separate tab. Here's what the inspector has:

![Screenshot from 2021-02-17 11-22-02](https://user-images.githubusercontent.com/16503728/108256739-b5e58500-7112-11eb-8ff8-a20f8fb44378.png)

**Comment by antelle** [comment]
I see, that's why, it looks similar to #1711 and I think this will fix it as well. Could you please test if beta.keeweb.info works?

**Comment by antelle** [comment]
Well it won't work indeed, since the fix is applied only to mobile, but I can add it for this browser as well.

**Comment by antelle** [comment]
It works now!

**Comment by Barugon** [comment]
Thanks
