### ISSUE TITLE
WebDAV network error on Firefox (CORS)

### ISSUE THREAD

**Issue by drobyshevich** [keeweb/keeweb#1716]
**Describe the bug**
WebDAV not connected on https://app.keeweb.info/ (FF 86.0 (64-bit))

**To Reproduce**
1. Go to https://app.keeweb.info/
2. Click on WebDAV (paste data)
4. See error Error: nework error

But app KeeWeb nice work.

```Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://ewebdav.pcloud.com/my.kdbx. (Reason: CORS request did not succeed).```

```Failed to load ‘https://ewebdav.pcloud.com/my.kdbx’. A ServiceWorker passed a promise to FetchEvent.respondWith() that rejected with ‘TypeError: NetworkError when attempting to fetch resource.’.```

**Screenshots**

On https://app.keeweb.info/

![image](https://user-images.githubusercontent.com/72418201/108216317-0375e800-713b-11eb-9084-48acc55d9692.png)

![image](https://user-images.githubusercontent.com/72418201/108216501-3ae49480-713b-11eb-9e01-a9fca91cbcb5.png)

**Comment by antelle** [comment]
This means, this webdav server cannot be used with keeweb.
