### ISSUE TITLE
OneDrive is fail

### ISSUE THREAD

**Issue by AllenZou** [keeweb/keeweb#1719]
# please describe your issue here

KeeWeb v1.16.7 (42b5b00, 2020-12-31)
Environment: web
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 11_0_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.182 Safari/537.36

**Comment by antelle** [comment]
1713
