### ISSUE TITLE
Favicons are not found most of the time

### ISSUE THREAD

**Issue by nickbe** [keeweb/keeweb#1720]
Most of the time when I click on the favicon download button the icon is not found and downloaded. 3 out of 4 seem to have a slightly different format than "usual" here, but this shouldn't stop keeweb from downloading anyway.

**Comment by antelle** [comment]
Hi! Since you already found something interesting, can you please share what is special about the format?

**Comment by nickbe** [comment]
One of many examples that does not work: Open Open-Xchange

This is the icon:
![image](https://user-images.githubusercontent.com/10890765/108817619-77d7dd80-75b8-11eb-8150-4667d61f6a34.png)

And this is the header:
```
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no">
    <meta name="msapplication-tap-highlight" content="no">
    <meta name="google" value="notranslate">
    <meta name="robots" content="noindex, nofollow">
    <meta id="win8Icon" name="msapplication-TileImage" content="">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-title" content="">
    <meta name="apple-mobile-web-app-status-bar-style" content="black">
    <link id="favicon" rel="shortcut icon" href="v=7.10.4-16.20210115.220831/apps/themes/default/favicon.ico"
        type="image/x-icon">
    <link id="icon57" rel="apple-touch-icon" href="">
    <link id="icon72" rel="apple-touch-icon" sizes="72x72" href="">
    <link id="icon76" rel="apple-touch-icon" sizes="76x76" href="">
    <link id="icon114" rel="apple-touch-icon" sizes="114x114" href="">
    <link id="icon120" rel="apple-touch-icon" sizes="120x120" href="">
    <link id="icon152" rel="apple-touch-icon" sizes="152x152" href="">
    <link id="icon167" rel="apple-touch-icon" sizes="167x167" href="">
    <link id="icon180" rel="apple-touch-icon" sizes="180x180" href="">
    <link id="icon144" rel="icon" type="image/png" href="" sizes="144x144" />
    <link id="icon192" rel="icon" type="image/png" href="" sizes="192x192" />
    <link rel="stylesheet" href="v=7.10.4-16.20210115.220831/apps/themes/login/login.css">
```

**Comment by antelle** [comment]
Well, here https://www.open-xchange.com/ there's an icon:
```
<link rel="shortcut icon" sizes="16x16 24x24 32x32 48x48 64x64" href="https://www.open-xchange.com/favicon.ico">
```

but it returns 404.  The website favicon is broken.

Do you have other examples? To avoid ambiguity, please give just a website url "Open Xchange" is not very clear.

**Comment by nickbe** [comment]
The site shows a perfect favicon in Firefox, Chrome, Opera and on my iPhone... So I would suggest find out how to load this icon first. Since I can even rip the icon with httrack this should be easy to adapt to

**Comment by antelle** [comment]
We’re not going to fix each and every favicon. If you have other examples, please post the website urls, the more, the better, I’ll try to fix what’s possible.
