### ISSUE TITLE
Is there a way to delete the downloaded icon?

### ISSUE THREAD

**Issue by obnews** [keeweb/keeweb#1722]
I downloaded two same icons from a same website, so there are 2 identical icons in my downloaded icon list.

How can I delete one of them?

**Comment by antelle** [comment]
Hi! They will be deleted automatically when you save the file and open it again.

**Comment by obnews** [comment]
![2021-02-23_174836](https://user-images.githubusercontent.com/3361155/108906496-b80e7e80-75ff-11eb-802b-08814f19f2d6.png)
No, I restarted Keeweb, the icons are still there. Check the 2 icons in the first row rightmost and the 2 in the last row rightmost.

**Comment by antelle** [comment]
Hm, that's strange. I assume, there's an entry in history using one of those icons? If you delete it, they should be removed.

**Comment by obnews** [comment]
> Hm, that's strange. I assume, there's an entry in history using one of those icons? If you delete it, they should be removed.

You are right. It is gone now after I deleted some entry history.
