### ISSUE TITLE
Auto Type in Remote desktop sessions doesn't apply Shift Key

### ISSUE THREAD

**Issue by islamadel** [keeweb/keeweb#1724]
When I use auto type locally Passwords are applied correctly
But When using inside Apple Remote Desktop on macOS, they are transferred without the Shift Key being applied.
So all uppercase characters arrive at the remote machine as lowercase!

I assume this is because the SHIFT Key is hit very fast, which doesn't get fetched by the remote machine.
My Suggestion is to have the option to increase the duration of holding the Shift key before releasing.

This should solve it.

**Comment by antelle** [comment]
What happens if you have a username and password in ALL CAPS?

Next version may solve this by the way, could you please try it here: https://beta.keeweb.info/KeeWeb.app.zip

**Comment by islamadel** [comment]
if username and password all in Capital Letters, get applied all in lowercase too.

**Comment by islamadel** [comment]
The Beta reloved The issue. Thanks 👍

**Comment by antelle** [comment]
Awesome thank you for checking! This beta should be rather stable, you can continue using it if you find it good. I'm especially interested in auto-type quality because it was rewritten from scratch.
