### ISSUE TITLE
Search in: not working for password

### ISSUE THREAD

**Issue by onegin1** [keeweb/keeweb#1726]
Hello, 

I tried to use the advanced setup for the search function because I needed to search a string in my passwords. I rolled down the menu for advanced searching, I marked "password" and try to find passwords with a certain string, but the result was the empty list. 

I tried the same function in my Android application for KDBX and all worked fine, so I think, that problem has to be in the KeeWeb application. 

I'm using KDBX file saved in Google drive and my KeeWeb version is 1.16.7 (2020-12-31). 

Thank you very much for your advice. 
Best regards
Your very satisfied user.

**Comment by antelle** [comment]
Thank you! It's broken indeed, will be fixed soon

**Comment by antelle** [comment]
It's fixed

**Comment by onegin1** [comment]
Thank you very much, I tested the new version and all is working correctly. I very appreciate it.
