### ISSUE TITLE
Warn if closing keeweb before syncing

### ISSUE THREAD

**Issue by gweissman86** [keeweb/keeweb#1728]
After changing or adding password entries to a password file (in my case synced with gdrive), it's easy to forget to sync the file before closing. In the case of closing keeweb with unsynced changes, would be good if there was a popup alert to warn the user and remind them to sync first.

**Comment by antelle** [comment]
Hi! It syncs the file before closing, there shouldn't be a situation where changes are lost.  
What happens when you open it again, the data you entered is lost?

**Comment by gweissman86** [comment]
I thought that's what happened, but it turns out I confused myself and you are right. Sorry!
