### ISSUE TITLE
webdav destination double urlencode

### ISSUE THREAD

**Issue by forsaken628** [keeweb/keeweb#1729]
**Describe the bug**

:authority: seafile.leahcim7.cyou:8443
:method: MOVE
:path: /seafdav/%E7%A7%81%E4%BA%BA%E8%B5%84%E6%96%99%E5%BA%93/.pass.kdbx.1614958516727
:scheme: https
accept: */*
accept-encoding: gzip, deflate, br
accept-language: zh-CN,zh;q=0.9,en;q=0.8
destination: https://seafile.leahcim7.cyou:8443/seafdav/%25E7%25A7%2581%25E4%25BA%25BA%25E8%25B5%2584%25E6%2596%2599%25E5%25BA%2593/pass.kdbx
origin: https://app.keeweb.info
overwrite: T
referer: https://app.keeweb.info/
sec-fetch-dest: empty
sec-fetch-mode: cors
sec-fetch-site: cross-site
user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.190 Safari/537.36

**Environment**
online demo

**Logs**[DEBUG] 2021-03-05T16:00:22.807Z [storage-webdav] Save:stat https://seafile.leahcim7.cyou:8443/seafdav/%E7%A7%81%E4%BA%BA%E8%B5%84%E6%96%99%E5%BA%93/pass.kdbx

[DEBUG] 2021-03-05T16:00:22.853Z [storage-webdav] Save:stated https://seafile.leahcim7.cyou:8443/seafdav/%E7%A7%81%E4%BA%BA%E8%B5%84%E6%96%99%E5%BA%93/pass.kdbx Fri, 05 Mar 2021 14:59:28 GMT 44ms

[DEBUG] 2021-03-05T16:00:22.853Z [storage-webdav] Save:put https://seafile.leahcim7.cyou:8443/seafdav/%E7%A7%81%E4%BA%BA%E8%B5%84%E6%96%99%E5%BA%93/.pass.kdbx.1614960022807

[DEBUG] 2021-03-05T16:00:23.099Z [storage-webdav] Save:puted https://seafile.leahcim7.cyou:8443/seafdav/%E7%A7%81%E4%BA%BA%E8%B5%84%E6%96%99%E5%BA%93/.pass.kdbx.1614960022807 null 247ms

[DEBUG] 2021-03-05T16:00:23.099Z [storage-webdav] Save:stat https://seafile.leahcim7.cyou:8443/seafdav/%E7%A7%81%E4%BA%BA%E8%B5%84%E6%96%99%E5%BA%93/pass.kdbx

[DEBUG] 2021-03-05T16:00:23.146Z [storage-webdav] Save:stated https://seafile.leahcim7.cyou:8443/seafdav/%E7%A7%81%E4%BA%BA%E8%B5%84%E6%96%99%E5%BA%93/pass.kdbx Fri, 05 Mar 2021 14:59:28 GMT 47ms

[DEBUG] 2021-03-05T16:00:23.147Z [storage-webdav] Save:move https://seafile.leahcim7.cyou:8443/seafdav/%E7%A7%81%E4%BA%BA%E8%B5%84%E6%96%99%E5%BA%93/.pass.kdbx.1614960022807

[DEBUG] 2021-03-05T16:00:23.203Z [storage-webdav] Save:move error https://seafile.leahcim7.cyou:8443/seafdav/%E7%A7%81%E4%BA%BA%E8%B5%84%E6%96%99%E5%BA%93/.pass.kdbx.1614960022807 56ms

[INFO ] 2021-03-05T16:00:23.203Z [sync:Main] Error saving data to storage

[INFO ] 2021-03-05T16:00:23.204Z [sync:Main] Sync finished network error

**Comment by antelle** [comment]
Hi! Did you put encoded url into the URL field in KeeWeb? If you do it without encoding, it should help.

**Comment by antelle** [comment]
anyway, next version will detect double encoding
