### ISSUE TITLE
Permissions required for Google Drive are too broad

### ISSUE THREAD

**Issue by vsetka** [keeweb/keeweb#1730]
**Is your feature request related to a problem? Please describe.**
Now, I haven't gone through the source code, but my gut tells me the permissions the app asks of you are way too broad. Have a look at whatsapp backup permission set for comparison:
![permissions](https://i.ibb.co/hgnXPNr/Screen-Shot-2021-03-05-at-22-02-30.png)

**Describe the solution you'd like**
I would like the permissions to be constrained down to a single folder or file that is managed by the app, instead of requiring access to the entire drive.

**Describe alternatives you've considered**
I guess I could create an email account just for keeweb :)

**Additional context**
It makes me uncomfortable using this feature, even though it's an open source project.

**Comment by antelle** [comment]
Hi! KeeWeb can create files in Google Drive, so it requires permissions for that.  
If you would like to tighten that, there's a possibility to create your own Google Drive app and instruct KeeWeb to use it instead, but this requires a bit of configuration: https://github.com/keeweb/keeweb/wiki/Dropbox%20and%20GDrive#google-drive

**Comment by vsetka** [comment]
Thanks for the link, I'll check it out.

**Comment by antelle** [comment]
Actually, I just realized that it might not work. KeeWeb is not using Google Drive's picker, so GDrive won't give permission to anything if you set it up the way WhatsApp is set up. But you can try, if it works, please let me know, I'll create another version of Google Drive app, like we have a choice in Dropbox: "All Dropbox" or "KeeWeb folder".
