### ISSUE TITLE
Auto-type error after updating to latest version on MacOS

### ISSUE THREAD

**Issue by ValentinH** [keeweb/keeweb#1731]
**Describe the bug**
When I try to auto-type, it correctly fills the email and the password inputs but don't submit. Then Keeweb is stuck for a few seconds and then I get this error:
![image](https://user-images.githubusercontent.com/2678610/110246690-e75ead00-7f68-11eb-8a97-1d356f92afc1.png)

I followed the missing permissions procedure:
![image](https://user-images.githubusercontent.com/2678610/110246704-f9405000-7f68-11eb-9244-537c3da1e451.png)

**To Reproduce**
1. Go to 'paypal.com'
2. Try to auto-type
3. See error

**Expected behavior**
Auto-type should work as before

**Environment**
```
KeeWeb v1.17.0 (c03ed76, 2021-03-07)
Environment: electron v12.0.0
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 11_2_2) AppleWebKit/537.36 (KHTML, like Gecko) KeeWeb/1.17.0 Chrome/89.0.4389.69 Electron/12.0.0 Safari/537.36
```

**Comment by antelle** [comment]
Hi! Does it work in other applications, for example, a text editor, if you trigger auto-type from KeeWeb?

**Comment by antelle** [comment]
Another option to check is "Settings / General / Advanced / Use legacy auto-type" - let's see what it does with this checked.

**Comment by antelle** [comment]
One more thing to try: is KeeWeb added to "Input Monitoring" on the same tab? If no, does adding it there fix the issue?

**Comment by ValentinH** [comment]
Yes it worked in a text editor. 
After seeing this, I restarted my browser and now it works fine 🙈 

I guess this can be closed then, sorry for the inconvenience.

**Comment by antelle** [comment]
Cool, just to understand, you didn't switch to the legacy auto-type and haven't re-added KeeWeb to Input Monitoring, right? Just restarting the browser fixed it?

**Comment by ValentinH** [comment]
Yes indeed.

**Comment by antelle** [comment]
Perfect, thank you! I'll add more information to the wiki page that is opened from KeeWeb. This detection is a new thing in KeeWeb added, so it should stabilize in future. This version is expected to have some issues with auto-type, if you notice anything else or it repeats, please let me know!

**Comment by clustor** [comment]
I am seeing an auto-type issue on MacOS in the last two days. I am currently running 1.18.6. I have removed and added Keeweb in Security & Privacy/Accessibility Security & Privacy/Input Monitoring. I have restarted the browser and text editor and nothing seems to work.  I don't see an option to try "Leagcy Auto Type" mode in General/Advanced setting. 

```
[ERROR] 2021-05-23T01:21:19.610Z [native-module-connector] Received an error kbdText {"name":"Error","message":"Key press failed","stack":"Error: Key press failed\n    at kbdText (/Applications/KeeWeb.app/Contents/Resources/app.asar/native-module-host.js:119:30)\n    at /Applications/KeeWeb.app/Contents/Resources/app.asar/native-module-host.js:257:24","keyPressFailed":true}
[ERROR] 2021-05-23T01:21:19.610Z [auto-type] Run error {"name":"Error","message":"Key press failed","stack":"Error: Key press failed\n    at kbdText (/Applications/KeeWeb.app/Contents/Resources/app.asar/native-module-host.js:119:30)\n    at /Applications/KeeWeb.app/Contents/Resources/app.asar/native-module-host.js:257:24","keyPressFailed":true}

```

**Comment by antelle** [comment]
@clustor better to post it as a separate issue in this case. This is for sure not related to something that happened one major release ago. 
Anyway, is it broken since the last version or it stopped working? What was the last working version for you?

**Comment by clustor** [comment]
@antelle I suspected it could be related so sorry about that.. Created a new issue.
