### ISSUE TITLE
Auto-type character conflict

### ISSUE THREAD

**Issue by Akhilesh-T** [keeweb/keeweb#1735]
I was trying to login into a website using auto-type to enter the password, but the website said it was incorrect.
However, when I copy-pasted it, the website accepted it.

To understand what went wrong, I used the compare plugin in Notepad++ where I auto-typed the password in one text file and copy-pasted the password in another. On comparing, I found differences in both texts.

<img width="960" alt="notepad++_9MLF0ARNHx" src="https://user-images.githubusercontent.com/80357467/110527448-fb5b0800-813c-11eb-8811-13b3d2a30b77.png">

**Comment by antelle** [comment]
Hi! Do you see the same characters every time you auto-type this password or it happens randomly?

**Comment by antelle** [comment]
Another question, which keyboard layout did you have selected when you triggered auto-type?

**Comment by Akhilesh-T** [comment]
> 
> 
> Hi! Do you see the same characters every time you auto-type this password or it happens randomly?

Yes, I see the exact same password when I auto-type

**Comment by Akhilesh-T** [comment]
> 
> 
> Another question, which keyboard layout did you have selected when you triggered auto-type?

I didn't understand your question. I am using Windows 10 PC.

Also, I tried the same again with another random password. This time too, the auto-type and the copy pasted password contained different characters. Check the screenshot. I noticed the following things so far-

q in autotype = æ in copy paste

Y in autotype = Ñ in copy paste

When a letter is CAPITAL or small in autotype, it is also CAPITAL or small in copypaste

<img width="960" alt="notepad++_jx6BpJp50Q" src="https://user-images.githubusercontent.com/80357467/110599871-56c2df80-81a9-11eb-8118-273218af22f6.png">

**Comment by jivarson** [comment]
> Another question, which keyboard layout did you have selected when you triggered auto-type?

Sorry if it's unrelated, but i have auto-type issues aswell
Using Swedish keyboard-layout (windows 20H2) KeeWeb 1.17.0 autotypes the @-sign as the digit '2'.
Not sure if the autotype tries to use the modifiers AltGr or Ctrl+Alt (those works on my standard keyboard with swedish layout anyway.

Other special characters like " !"#%"  as well as our extended letters "åäö" works though.
If i switch to English layout, the @-sign is typed correctly. 

So just that one character but it's sort of involved in most USERNAME sequences :-)

**Comment by antelle** [comment]
@jivarson I can repeat this, thank you, I'll look into it and fix it soon, no input needed now.  
To mitigate it, you can select "use legacy auto-type" in Settings / Advanced.

**Comment by Akhilesh-T** [comment]
Is there any way that I can fix it from my side, or will it be fixed in the next version?

**Comment by antelle** [comment]
I've just fixed and merged it, it's [building](https://github.com/keeweb/keeweb/runs/2079596147)... If everything goes well, it will be live in ≈20min.

**Comment by Akhilesh-T** [comment]
You are awesome

**Comment by antelle** [comment]
It's published: https://github.com/keeweb/keeweb/releases/tag/v1.17.1, let's see if this build fixes your issue.  
If you have "use legacy auto-type" enabled in settings, don't forget to disable it before testing the new version.

**Comment by Akhilesh-T** [comment]
Yes, I was just trying the latest build.
It is fixed now 😍

I have an unrelated question. If I download the portable version, is it okay to cut-paste all the new files in the previous version folder and replace the files, or should I completely remove the older version?

**Comment by antelle** [comment]
Awesome, thank you! ❤️  auto-type is rewritten from scratch in v1.17, so there are issues like this, hopefully it will become mature soon.
On Windows it should be ok to copy-paste all program files, yes (assuming that everything works after it).

**Comment by Akhilesh-T** [comment]
And I'm sure you'll fix all issues, if any,

Thanks a lot for the prompt reply and action ❤

**Comment by jivarson** [comment]
1.17.1 works here aswell. And I agree with @Akhilesh-T; @antelle rocks.
