### ISSUE TITLE
Exclude Recycle bin from search

### ISSUE THREAD

**Issue by tcz305** [keeweb/keeweb#1736]
**Is your feature request related to a problem? Please describe.**
don't want entries in recycle bin to appear in search results

**Describe the solution you'd like**
option to exclude recycle bin from searches

Thanks

**Comment by antelle** [comment]
Hi! Trash folder is excluded from search by default. I assume, you changed this settings in another app, such as KeePass or KeePassXC. To fix this, you can open your file using one of apps and disable searching in Recycle Bin properties.

**Comment by popoway** [comment]
Hello! I also encountered this issue when I open a file initially created in another app. Is it possible to have an option in KeeWeb to toggle this setting? This would also allow new files created in KeeWeb to be able to include recycle bin in global search. Thanks!

**Comment by antelle** [comment]
Well, the intention is not to include the Recycle Bin in the global search...
