### ISSUE TITLE
Upgrade does not upgrade portable edition, but installs the "installer" edition.

### ISSUE THREAD

**Issue by snakyjake1** [keeweb/keeweb#1740]
**Describe the bug**
Looks like the previous version to v1.17.1 attempts to upgrade the _portable_ edition to an _installer_ edition to C:\Program Files (x86)\KeeWeb.  

This is not successful.

In addition, I cannot uninstall this upgrade that was installed to C:\Program Files (x86)\KeeWeb.  It is stuck on "InstallDir key is absent".

**To Reproduce**
Using the portable KeeWeb app, upgrade from the a version earlier than v1.17.1.

**Expected behavior**
The upgrade should install the portable edition into the same folder where the portable edition is installed.

**Screenshots**
When I try to uninstall using the supplied C:\Program Files (x86)\KeeWeb\uninst.exe file I get this.
![image](https://user-images.githubusercontent.com/8312560/110824566-09497f80-8248-11eb-8aaf-4157971d3a1b.png)

**Environment**
Microsoft Windows

**Comment by antelle** [comment]
I just tried making a portable version using `keeweb-portable.json`, it seems to be updated correctly. What was your setup, did you also use this json file to make a portable installation?

**Comment by antelle** [comment]
Let's check the following if you don't mind:
1. download [v1.7.1 installer](https://github.com/keeweb/keeweb/releases/download/v1.17.1/KeeWeb-1.17.1.win.x64.exe) (x64 exe)
2. launch it like this
```sh
KeeWeb-1.17.1.win.x64.exe /U1 /D=your-update-path
```

And let's see where it will install and what it prints.

**Comment by snakyjake1** [comment]
I think I originally just unzipped the files and ran the app.

**Comment by antelle** [comment]
Well, it won't create a portable installation and it will still use files in system locations. You can check it if you launch KeeWeb from another path: you will see the same settings, files, etc... But the updater should work in this setup, I just checked, it updates correctly. Could you pleas launch the command I pasted above?

**Comment by antelle** [comment]
If anyone has a similar issue, please let me know here. I tried hard, but I can't reproduce this, unfortunately.

**Comment by snakyjake1** [comment]
### Update

I originally unzipped the files and started from portable drive.  I then learned from this thread the zip file is not actually a portable configuration.  The updates do not install to the portable location.  A Windows User Roaming folder is created.

For portable mode with updates, I followed the additional instructions, and had success.

### Changes

Install using this command:
`KeeWeb-1.17.1.win.x64.exe /U1 /D=your-update-path`

Be careful, if you mistype the update path it will default to c:\program files (x86).

I also followed these [instructions for portable mode](https://github.com/keeweb/keeweb/wiki/Configuration#portable).

I also deleted the folder C:\Users\{user}\AppData\Roaming\KeeWeb.

### Start

I started the app.
I updated via the App, and it updates to the expected portable folder.

### Remaining Issues

1. The app still recreates the C:\Users\{user}\AppData\Roaming\KeeWeb folder.  There's an empty "Directories" folder and a lockfile.

2. The App's Update asked me to "Restart KeeWeb to update".  I click the blue button.  KeeWeb minimizes instead of exiting, updating, restarting.  Maybe it doesn't work as expected because I have enabled "Minimize the app instead of close".  I had to manually exit KeeWeb, and then the upgrade proceeded.

**Comment by antelle** [comment]
> Be careful, if you mistype the update path it will default to c:\program files (x86).

I cannot reproduce this, it creates a new folder for me. Can you please share how exactly you mistyped it?

> The app still recreates the C:\Users{user}\AppData\Roaming\KeeWeb folder

I don't think we'll be able to fix this now, it's Chromium who creates this thing. I disabled everything in the portable version, so that it doesn't write anything apart from this Dictionaries folder, but this folder doesn't seem to be removable. Here's an issue in Electron: https://github.com/electron/electron/issues/22995

> KeeWeb minimizes instead of exiting

Good find, thanks, will be fixed soon.

Apart from this, the updater updates the portable version, so, the original issue doesn't reproduce for you now, correct?

**Comment by antelle** [comment]
I also tried the following:
1. download KeeWeb v1.17.1, zip version
2. extract it to a folder
3. launch it
4. start the update

It correctly updates KeeWeb in that folder. Isn't it the same for you?

**Comment by snakyjake1** [comment]
> Apart from this, the updater updates the portable version, so, the original issue doesn't reproduce for you now, correct?

Yes, I was able to do the update successfully.

Thanks for everything you've done.

**Comment by snakyjake1** [comment]
> Apart from this, the updater updates the portable version, so, the original issue doesn't reproduce for you now, correct?

Yes, I was able to do the update successfully.

Thanks for everything you've done.

**Comment by antelle** [comment]
Great, then in the next minor release only the issue with tray will be included. If you notice that it doesn't upgrade, please let me know and we'll try to look into it together.

**Comment by antelle** [comment]
Well, let's check this. Download the installer and run it like this:
```
KeeWeb-xxx.win.x64.exe /U1 /D=your-update-path
```

**Comment by snakyjake1** [comment]
> KeeWeb-xxx.win.x64.exe /U1 /D=your-update-path

Yes, the above command works.  This is what I use when the app does not perform the upgrade to the portable location.

**Comment by antelle** [comment]
Interesting, so the portable version doesn't upgrade properly? I noticed something about x86, so I assume it's an x64 system. Is the portable version also x64?

**Comment by snakyjake1** [comment]
> So the portable version doesn't upgrade properly? 

It does not programmatically upgrade as a portable app.  The upgrade installs to the c:\program files (x86) folder, not to the portable location in which the current app is installed to.  The upgrade then appears as a fresh install; no configuration.

> Is the portable version also x64?
Yes.  This is a Windows x64 system.   The previous install is a x64.  I cannot remember which version the app automatically downloaded and tried to install (not sure if the log window showed that info).  

Maybe the app didn't correctly identify the OS architecture, then downloaded the x32 architecture instead of x64?
The app doesn't show which architecture is running/installed.

**Comment by antelle** [comment]
Actually, the updater won't start on a wrong architecture, so I assume both the app and updater are x64.
I was thinking, maybe portable app path contains special characters?

Does it repeat if you download KeeWeb, for example, v1.18.1, set up a portable version with it and upgrade?

**Comment by antelle** [comment]
I can't reproduce it, sorry, I need your help here. Let's try it step by step with exactly the same sequence:

1. Create an empty directory, to be sure, without any special characters in the path. For example:
    `C:\Util\kw-portable\`
    This directory will be used for our installation. Inside it will contain two subdirectories:
    * `C:\Util\kw-portable\KeeWeb`: for KeeWeb binaries
    * `C:\Util\kw-portable\data`: for portable application data
2. Create a subdirectory `C:\Util\kw-portable\KeeWeb`.
3. Make a JSON file and save it as `C:\Util\kw-portable\KeeWeb\keeweb-portable.json`, put the following contents there:
    ```json
    {
        "userDataDir": "C:\\Util\\kw-portable\\data"
    }
    ```
    Note the `data` part appended to the directory name and double slashes.
    Expected result:
    <img width="1037" alt="directory" src="https://user-images.githubusercontent.com/633557/117858122-d34b6a80-b28d-11eb-9671-432d3463fa47.png">
4. Download KeeWeb v1.18.2 that we will upgrade to v1.18.3:  [KeeWeb-1.18.2.win.x64.zip](https://github.com/keeweb/keeweb/releases/download/v1.18.2/KeeWeb-1.18.2.win.x64.zip)
5. Extract it into `C:\Util\kw-portable\KeeWeb\`. Expected result:
    <img width="601" alt="extracted" src="https://user-images.githubusercontent.com/633557/117858753-7bf9ca00-b28e-11eb-9c6d-1e94ce5722f5.png">
6. Make sure KeeWeb is not running. It's possible that you have another instance, it's minimized, not visible, and so on. To check, open the Command Prompt and run the following:
    ```
    tasklist /fi "imagename eq "KeeWeb.exe"
    ```
    Expected result:
    <img width="960" alt="cmd" src="https://user-images.githubusercontent.com/633557/117859367-2eca2800-b28f-11eb-9488-8f52aab5a47d.png">
7. Run `C:\Util\kw-portable\KeeWeb\KeeWeb.exe` by double-clicking it.
8. Make sure it shows `v1.18.2` in Settings / About
9. Go to Settings / General and update KeeWeb from there
10. Check what it prints:
    ![update](https://user-images.githubusercontent.com/633557/117859876-d9dae180-b28f-11eb-8289-6782500435ef.png)
11. When it launches KeeWeb, check its version in Settings / About
12. Close it and re-launch from the same directory. Check the version in Settings / About

**Comment by snakyjake1** [comment]
I appreciate and thank you for the time you put into this.  If I am the only one with the problem, I can work around it.

So far the above is working without issue.  However, even my currently installed version _sometimes_ properly upgrades to the expected location.

Here's a new example from my current installation (1.18.3 -> 1.18.4) that I can reproduce (and I captured extra info at Windows UAC prompt).

Notice the app does have the correct upgrade path, and looks like it will install to the correct location:
![IMG_1429_e](https://user-images.githubusercontent.com/8312560/118052696-0a765600-b338-11eb-8f2b-ef3288c7709f.JPG)

However, it doesn't:
![2021-05-12 15_16_54-Clipboard_e](https://user-images.githubusercontent.com/8312560/118052962-840e4400-b338-11eb-8745-c2097344ccc9.png)

**Comment by antelle** [comment]
Do you have `K:\Software\KeeWeb\keeweb-portable.json`? What is its content?

**Comment by snakyjake1** [comment]
> Do you have `K:\Software\KeeWeb\keeweb-portable.json`? What is its content?

Yes, I have a `K:\Software\KeeWeb\keeweb-portable.json` file.

Contents:

```
{
    "userDataDir": "K:\\Data\\KeePass"
}
```

**Comment by antelle** [comment]
The file looks good, it's very strange that it installs the update to a wrong location. Looks like your setup is correct, but as you also noticed, it doesn't update always.

Perhaps it has something to do with the way we launch the installer or there's some interesting bug in the installer.

**Comment by snakyjake1** [comment]
I think this issue might be caused by a linked drive/folder using vSubst, as seen in the screenshot above using drive K:.  

It appears the Keeweb installer doesn't recognize the linked drive/path shown in the screenshot, and reverts to the default program files path.  In addition, for some reason it will use "C:\Program Files (x86)" for a x64 install.

Upgrading from the command line:
If I manually use the link path, I have the problem.  
If I use the real path, no problem.

**Comment by antelle** [comment]
Interesting, thanks! This explains the issue.
