### ISSUE TITLE
[Bug] UI glitch since v1.17.1

### ISSUE THREAD

**Issue by KaKi87** [keeweb/keeweb#1742]
**Describe the bug**
Honestly, I have no idea how to describe this.

**To Reproduce**
1. Go to app.keeweb.info
2. Unlock your file
3. See glitch

**Expected behavior**
No glitch

**Screenshots**
![](https://cdn.discordapp.com/attachments/493524617714204672/819697505481785354/Screenshot_20210311-213534938.jpg)

**Environment**
Visible on screenshot

**Kdbx File**
Happens on demo database

**Logs**
Weirdly, no copy menu appears when selecting text inside the KeeWeb app, including logs and environment, although it appears on other tabs in same browser (Ungoogled Chromium)

Thanks

**Comment by antelle** [comment]
Hi! Does it behave like this in other browsers? I see it's ok Safari and Chrome.

**Comment by antelle** [comment]
I just tried latest Ungoogled Chromium with this setup, and it seems to be working as expected:

![image](https://user-images.githubusercontent.com/633557/111032355-0a2b0e80-840c-11eb-823d-c5d998032315.png)

I won't be able to do anything else about this issue, your help is needed to fix it. For example, you can try inspecting console, maybe there are some errors there?

**Comment by KaKi87** [comment]
Well, I first cleaned the app's data, which didn't worked, so I upgraded it, and I actually don't have any issues anymore. Thanks
