### ISSUE TITLE
Crash after Sleep mode

### ISSUE THREAD

**Issue by LiloBzH** [keeweb/keeweb#1744]
Hi

**Describe the bug**
After every each Sleep mode, Keeweb is dead (crash, no message)

Keeweb 1.17.1 x64
Windows 10 x64 Pro 19042.867

**Comment by antelle** [comment]
I knew that it would happen 😢 
In v1.17 native modules were moved to the main process, so crash in one of them crashes KeeWeb unfortunately. To mitigate the issue, you can launch KeeWeb with `--native-module-host-process` argument.

Not sure what to do with it yet, another process takes +50MB of memory so I'd prefer fixing the issue, but it may be hard.

**Comment by LiloBzH** [comment]
ok :'(

Test in progress to confirm (with argument)

**Comment by antelle** [comment]
Another thing to test also reported in #1743: do you experience a crash if you disable USB in Settings / Devices (first checkbox) and restart KeeWeb? If yes, then it's a bug in the USB module and fixing it will fix your issue as well.

**Comment by LiloBzH** [comment]
disable USB setting don't change. same crash.

But it's seem to be ok with argument in shortcut

**Comment by antelle** [comment]
Yeah, with this argument it will crash a subprocess, but not the main app.  
Ok, thanks for checking, I'll try to find a way to test it (Windows VirtualBox doesn't want to sleep). Meanwhile I can create a setting for this, but it probably crashes for other people as well and it's not good.

**Comment by antelle** [comment]
Another question: does it crash if you just start KeeWeb (with previously disabled USB) and put Windows to sleep?

**Comment by LiloBzH** [comment]
yep !!!!

I don't tested before but after disable USB option, i restart Keeweb (I did not restart on previous tests), Sleep, and Keeweb seems to be ok now

Keeweb is different after restart with option USB disable ?

**Comment by antelle** [comment]
This was without `--native-module-host-process`, right? Cool, so it's `node-usb` that causes these crashes and fixing it should fix your issue too. The fix is coming soon then.

**Comment by LiloBzH** [comment]
yes, this was without the argument so it's probably only a problem with USB

**Comment by antelle** [comment]
Yeah, it watches the device list and I assume, there's a bug somewhere in the library. Most likely it refreshes the list after sleep, so it crashes then too. I'll replace it with [node-usb-detection](https://github.com/MadLittleMods/node-usb-detection), which seems to contain less code and we'll see.

**Comment by LiloBzH** [comment]
You dont reproduce the crash ? so it's not all PCs ?

**Comment by antelle** [comment]
I have Windows only in VirtualBox, and it doesn't support sleeping there, so I can't test it. But it crashes when I insert or remove a YubiKey, so I can verify the other issue about it, but not this one.

**Comment by LiloBzH** [comment]
ahah ok ! i understand :-D

**Comment by antelle** [comment]
I made a new build with the library I mentioned above, could you please verify if it fixes your issue? I see that it doesn't crash if I insert/remove a yubikey, but I can't test the sleep behavior.
https://beta.keeweb.info/KeeWeb-win32-x64.zip

**Comment by LiloBzH** [comment]
It s seems to be ok !

**Comment by antelle** [comment]
Thank you for trying it! 🙏  a new release with it is coming soon

**Comment by antelle** [comment]
[v1.17.2](https://github.com/keeweb/keeweb/releases/tag/v1.17.2) is released, now it shouldn't crash. Please give it a try and let me know if the issue disappeared!

**Comment by LiloBzH** [comment]
@antelle Patch ok for me ! Well done ;)
