### ISSUE TITLE
Blank screen iOS 13

### ISSUE THREAD

**Issue by Krinkle** [keeweb/keeweb#1747]
**Describe the bug**

As of a few days ago, https://app.keeweb.info/ produces a blank screen. Initially via the fullscreen homescreen app, but affects regular Safari and Firefox iOS as well.

**Environment**

> `Mozilla/5.0 (iPhone; CPU iPhone OS 13_5_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.1.1 Mobile/15E148 Safari/604.1`

**Comment by antelle** [comment]
Hi! Interesting, does it work in private mode?
It works on this Safari version for me. Do you have any extensions installed, for example, content blockers?

**Comment by Krinkle** [comment]
No plugins or blockers. Fails in private browsing mode as well.

**Comment by antelle** [comment]
If you have access to developer tools where it doesn't load, could you please check if there's anything suspicious there?

**Comment by Krinkle** [comment]
I'll try to reproduce it in browserstack.

**Comment by antelle** [comment]
Thank you! I tried different options: on my iPhone with all possible browsers and on lambdatest (similar as browserstack), however it seems to load well everywhere.

**Comment by antelle** [comment]
Ok, I've found what it is and now I can reproduce this too, the fix is coming soon...

**Comment by Krinkle** [comment]
Awesome. Although I am able to reproduce it, there was nothing of use in BrowserStack's devtools console.

<img width="840" alt="cap" src="https://user-images.githubusercontent.com/156867/111080024-6cf7d500-84f4-11eb-9e24-870d2a906a8f.png">

**Comment by antelle** [comment]
yeah, if you refresh it, it will display the error

**Comment by antelle** [comment]
Does [beta](https://beta.keeweb.info?refresh) work for you?

**Comment by antelle** [comment]
In browserstack it will probably throw an error about WebAssembly because they have iOS 13.0, however it should be supported on a real device if you have 13.7 installed on it. But maybe there's something else...

**Comment by Krinkle** [comment]
OK, I did refresh earlier but it didn't show errors. Now it does, it displays:

1. `Unrecognized Content-Security-Policy directive 'worker-src'.`
2. `VM24:1 2021-03-14T18:52:31.011Z [app] Error starting app TypeError: e.addEventListener is not a function. (In 'e.addEventListener("change",(e=>{const t=e.matches;this.dark=t,i.Events.emit("dark-mode-changed",{dark:t})}))', 'e.addEventListener' is undefined)`

Beta loads fine to the familiar start screen, both on my actual device and in browserstack. 👍

**Comment by antelle** [comment]
Perfect, then I'll deploy the fix to production soon

**Comment by antelle** [comment]
It's [building](https://github.com/keeweb/keeweb/actions/runs/652024319), if everything goes well, it should be there in ≈30min.

**Comment by antelle** [comment]
It's live  🎉
