### ISSUE TITLE
KeeWeb freezes on native Arch Linux installation.

### ISSUE THREAD

**Issue by Flova** [keeweb/keeweb#1748]
**Describe the bug**
After launching keeweb I am not able to use any of the UI elements. The cursor blinks, but the window takes no user input. After a few seconds a gnome "do you want to kill this frozen window" window is shown. No other applications on my machine show this behavior. It occurs since about a week ago and makes keeweb unusable for me.

**To Reproduce**
* Install `aur/keeweb-desktop-bin` on Arch Linux.
* Run KeeWeb

**Expected behavior**
It should accept user input.

**Screenshots**
![image](https://user-images.githubusercontent.com/15075613/111083547-6e35fb80-850e-11eb-8318-a3fad165003d.png)

**Environment**
* Up to date Arch Linux
* KeeWeb: 1.17.1-1

**Kdbx File**
This happens before the database loading. 

**Logs**
Idk how to access the logs on the native version.

**Comment by antelle** [comment]
Hi! Which version of KeeWeb is it, v1.17?
Did v1.16 work?

**Comment by antelle** [comment]
Another question, if you download a zip from releases, does it work?

**Comment by Flova** [comment]
I just build the v1.17 myself and tried the AppImage from the releases. Both had the same issue.
Now I try v 1.16.

**Comment by antelle** [comment]
Interesting, maybe it's coming from a new usb module? What happens if you launch it with `--native-module-host-process` command-line argument?
The UI on the screenshot also looks odd, something seems to be seriously broken.

**Comment by Flova** [comment]
I tried the v1.16.8 AppImage and it works fine.

**Comment by Flova** [comment]
> Interesting, maybe it's coming from a new usb module? What happens if you launch it with `--native-module-host-process` command-line argument?
I give it a try. I have multiple USB devices connected, but none of them has any purposes regarding keeweb, only soundcards, webcam, ...

**Comment by antelle** [comment]
It monitors USB devices to detect YubiKeys, so I was thinking maybe it's because of this module?

**Comment by Flova** [comment]
I do not use a YubiKey, but you are totally right! Using `--native-module-host-process` fixes the issue on v1.17!

**Comment by Flova** [comment]
Btw. I get the following printout when using the said argument:
`libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
`

**Comment by antelle** [comment]
It doesn't matter much if you have a YubiKey, it starts a listener using [node-usb-detection](https://github.com/MadLittleMods/node-usb-detection) that runs in background and probably it hangs for some reason. If this argument fixes KeeWeb for you, you can keep using it, it won't be removed (however it will use +30MB of memory).
Meanwhile I'll try to understand why it hangs there.

**Comment by Flova** [comment]
Very good job on your side! Your activity is insane!

**Comment by Flova** [comment]
The extra ram is totally fine for me.

**Comment by Flova** [comment]
Starting KeeWeb once with `--native-module-host-process` to deactivate the USB devices setting, fixes the bug even if you start without the said flag later on.

**Comment by antelle** [comment]
Strange, I just installed a fresh Arch on VirtualBox and KeeWeb seems to be working well, so this error that you also mentioned above is just a warning:  

<img width="862" alt="Screen Shot 2021-03-15 at 20 56 07" src="https://user-images.githubusercontent.com/633557/111213333-f250b780-85d0-11eb-9a13-2d5e3f4c4473.png">

It also properly shows and hides the YubiKey icon when I attach and detach it.

Let's see if anyone else comes here to report the same, and maybe we'll be able to reproduce it.

**Comment by antelle** [comment]
By the way, this may be fixed in v1.17.2 or v1.17.3, because now we're using another USB module. Could you please check if it works for you with the USB feature enabled?

**Comment by Flova** [comment]
If I remember it correctly, I tried both of them in the initial troubleshooting without success.

**Comment by Flova** [comment]
Further Inspection of my system logs resulted in me noticing multiply frozen services. All of these Services had frozen while scanning my USB devices (power management daemon, USB fan controller, ...). Disconnecting all my USB devices fixed the issues with these services including keeweb without the described fix. I, therefore, would close this issue because it is related to a faulty USB device and not to keeweb.

**Comment by antelle** [comment]
Cool, glad to here it's working!
