### ISSUE TITLE
Autotype sometimes slow

### ISSUE THREAD

**Issue by dploeger** [keeweb/keeweb#1749]
**Describe the bug**
In some occasions (currently unclear in *what* occasions, but it happens from time to time), the autotype won't start for about ten seconds.

**To Reproduce**
1. Start an app, that needs a password
2. Hit the Autotype key
3. Select an entry
4. Select an autotype-mode (just hit enter for example or use shift-enter to select a field)
5. => Autotype window is closed
6. Autotyping starts ten seconds later

**Expected behavior**
Autotype starts right away

**Environment**
KeeWeb v1.17.2 (ae7f5fb, 2021-03-13)
Environment: electron v12.0.0
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) KeeWeb/1.17.2 Chrome/89.0.4389.69 Electron/12.0.0 Safari/537.36

**Logs**
2021-03-15T07:39:46.197Z [auto-type] Auto type event null
index.html:1 2021-03-15T07:39:46.198Z [auto-type] Getting window info using native helper
index.html:1 2021-03-15T07:39:46.215Z [auto-type] Window info undefined <redacted>
index.html:1 2021-03-15T07:39:49.392Z [auto-type] Entry selected {entry: Proxy, sequence: "{PASSWORD}"}entry: Proxy[[Handler]]: Object[[Target]]: w[[IsRevoked]]: falsesequence: "{PASSWORD}"__proto__: Object
index.html:1 2021-03-15T07:39:49.394Z [auto-type] Hide window
index.html:1 2021-03-15T07:39:49.497Z [auto-type] Skipped active window check because window id is unknown
index.html:1 2021-03-15T07:39:49.498Z [auto-type] Start {PASSWORD}
index.html:1 2021-03-15T07:39:49.498Z [auto-type] Parsed [op:PASSWORD]
index.html:1 2021-03-15T07:39:49.499Z [auto-type] Resolved [[*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*]]
index.html:1 2021-03-15T07:39:49.499Z [auto-type-emitter] Using native auto-type emitter
index.html:1 2021-03-15T07:39:59.689Z [auto-type] Complete 10192ms

**Comment by antelle** [comment]
That's really strange, does it always type after 10 seconds or sometimes it's stuck at all?  
I made a minimalistic example, could you please try running it several times in Terminal and check if it has the same issue?
[example.zip](https://github.com/keeweb/keeweb/files/6143379/example.zip)

Expected output:
```
Active window pid: 51892, window_id: 17004, app_name: "Code", title: "auto-type-darwin.cpp — keyboard-auto-type", url: ""
pressed_modifiers 0
key_down ch=0 code=56
key_down ch=72 code=4
key_up ch=72 code=4
key_up ch=0 code=56
key_down ch=101 code=14
key_up ch=101 code=14
Hekey_down ch=108 code=37
key_up ch=108 code=37
key_down ch=108 code=37
lkey_up ch=108 code=37
lkey_down ch=111 code=31
key_up ch=111 code=31
key_down ch=0 code=56
okey_down ch=33 code=18
key_up ch=33 code=18
key_up ch=0 code=56
!%                                                                                                             
keyboard-auto-type ᚶ master % Hello!
```

**Comment by dploeger** [comment]
Well, it's not really *often*, but still visible: I did a test of 540 calls and 12 of them took longer than 0 seconds. Here they are:

```
0m10.210s
0m9.505s
0m1.157s
0m10.208s
0m8.867s
0m1.648s
0m2.015s
0m1.001s
0m1.430s
0m8.215s
0m10.217s
0m10.212s
```

This is my (very rough) test script:

```bash
rm test.log
for i in $(seq 1 1 2000); do   (time "./example") >>test.log 2>&1; done
```

And here's the log:

[test.log](https://github.com/keeweb/keeweb/files/6147435/test.log)

**Comment by antelle** [comment]
Interesting log, thank you! I see that in all cases it's the Shift key that is reported as not changing state.
I spent some time trying different things, and finally I reproduce it! 🎉  It happens when the mouse is moved during auto-type.

Hopefully I'll come with a fix soon, meanwhile the mitigation is simple but ugly: don't move the mouse during auto-type.

**Comment by dploeger** [comment]
Hmmm... Are you sure about this? I'm using a trackpad and am pretty sure I didn't touch it because I'm only using keys there... But I'll keep an eye on it.

**Comment by antelle** [comment]
I’m not 100% sure but it repeats for me. Perhaps there’s something else influencing it in the same way. I did a lot of tests with different keys today and figured out that ut really affects only modifier keys. I also found a way to check if a modifier key is pressed that works. Tomorrow I’ll build a new release and if it works for me, will post it here for you to test if you don’t mind.

**Comment by dploeger** [comment]
I can confirm, it's not the mouse (for me). I didn't touch the trackpad when running autotype, keyboard-only.

And I'll absolutely am open to test anything. 😄

**Comment by antelle** [comment]
And here's a build of KeeWeb with this version of the library: https://storage.googleapis.com/beta.keeweb.info/KeeWeb.app.zip

**Comment by dploeger** [comment]
The beta build doesn't work on my side. It doesn't react to autotype and once I closed it and try to reopen the app, my mac says, that I "don't have the permission to open this app".

However, the example works well. All calls are below 1 second. 👍

**Comment by antelle** [comment]
Cool, thank you! The new release is [building](https://github.com/keeweb/keeweb/actions/runs/665164930), it should be available soon.

**Comment by antelle** [comment]
It's [released](https://github.com/keeweb/keeweb/releases/tag/v1.17.4)

**Comment by dploeger** [comment]
Works! Thanks a lot.
