### ISSUE TITLE
keewebhttp subdomain support

### ISSUE THREAD

**Issue by btxtiger** [keeweb/keeweb#1750]
**Describe the bug**
It seems that keewebhttp does not respect subdomains with the ChromeKeePass extension. I have already talked to the extension developer, he said that the extension passes the full url to KeeWeb, but Keeweb does not return a specific result for the current subdomain, but for all sites under the main domain.
So it is also some kind of design question if this behavior is intended, and the results should be filtered by the extension itself. But imo keeweb should only expose the minimal dataset for security reasons, as the user can not predict what happens to the autofill credentials on a (possibly) corrupted website.

**To Reproduce**
1. Install ChromeKeePass Extension for Chrome/Edge
2. Create 1st password for a site with url `example.com`
3. Create 2nd password for a site with url `subdomain.example.com`
4. Create 3rd password for a site with url `other-subdomain.example.com`
4. Open the site, which is hosted under a subdomain. KeeWeb will now provide all passwords for the single subdomain.

**Expected behavior**
KeeWeb should only suggest the password with a 100% match for the subdomain. Possibly also the password with the url that has not a subdomain (1st), as it can be considered as kind of wildcard login.

**Environment**
Chrome/Edge

**Comment by antelle** [comment]
It should be probably a setting, because it can be a desired behavior too.

**Comment by antelle** [comment]
This issue not exactly fixed as asked, and won't be fixed in this form because KeePassHttp is deprecated, but v1.18 version will have an option for subdomains:

<img width="1157" alt="subdomains" src="https://user-images.githubusercontent.com/633557/116430099-cdde3100-a846-11eb-9641-96741ef5d0f9.png">
