### ISSUE TITLE
Auto-type depends on the current keyboard layout

### ISSUE THREAD

**Issue by mkbaranovskyi** [keeweb/keeweb#1751]
**Describe the bug**
I have 2 keyboard layouts (languages) installed in my system. They have different special symbols in the numeric buttons that are pressed with modifiers. E.g. when I have the English layout active in the system and press `Shrift + 2`, this produces the symbol `@`. But when I have the Russian layout active and press the same combination - it produces another symbol: `"`. 
The problem should be clear now: I may have saved `9AjD!@1` but when I try to retrieve it via auto-type, it may produce `9AjD!@1` or `9AjD!"1` depending on my current active layout. Considering that password inputs are usually hidden and the number of typed symbols is the same in both cases, this leads to frustration for users that can't track the problem quickly. 

**To Reproduce**
1. Install 2+ keyboard layouts in your system.
2. Generate a password with special symbols `!@#`
3. Try to auto-type it with different keyboard layouts active - it will produce different results (I use double click to auto-type).

**Expected behavior**
The same password to be typed regardless of my current active keyboard layout.

**Environment**
KeeWeb v1.16.8 (69f7b02, 2021-03-02)
Environment: electron v11.0.3
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) KeeWeb/1.16.0 Chrome/87.0.4280.67 Electron/11.0.3 Safari/537.36

**Comment by antelle** [comment]
Hi! This is probably fixed in v1.17, let’s give it a try

**Comment by mkbaranovskyi** [comment]
> Hi! This is probably fixed in v1.17, let’s give it a try

Yes, you're right. Sorry, I didn't notice my app didn't update to the next major version. 
Btw, how can we control the update in 1.17.? I can't see the option in settings where it was previously.

**Comment by antelle** [comment]
Updater updates the whole app starting from v1.17, this doesn't sound like something Linux apps usually do.
So, the new updater was implemented only for macOS and Windows, while on Linux it should be installed via the package manager.
