### ISSUE TITLE
Unable to import tags when importing CSV

### ISSUE THREAD

**Issue by manthanf1** [keeweb/keeweb#1752]
**Is your feature request related to a problem? Please describe.**
 There's no convenient way to import tags while importing CSV.  TOTP values can be imported if column header in CSV is 'otp'.

**Describe the solution you'd like**
As with otp, if a column header is "Tags", it should be considered as a tag property.

**Describe alternatives you've considered**
The current workaround involves importing CSV with tags considered just a text field. Then exporting the entries from app as XML. Then using XML parser to convert 
`<String>
    <Key>Tag</Key>
    <Value>tag_value</Value>
</String>`
to 
`<Tags>tag_value</Tags>`

What are your thoughts on this?

**Comment by antelle** [comment]
How tags are usually separated in apps that can export them to CSV?

**Comment by manthanf1** [comment]
BitWarden, Enpass consider tags as just another string. I'm not sure how they support multiple tags for single entry. 

Further, other KeePass applications (KeepassDX particularly) use 'TOTP' header for OTP, could KeeWeb use 'TOTP' as well instead of 'otp'? It prevents duplication of same entry in KDBX file.

**Comment by antelle** [comment]
How can I add tags in Enpass? I don't see it in the UI.  
Or if possible, could you please export a file with two tags: "A tag", "Space in tag"?

**Comment by manthanf1** [comment]
BW has folders instead of tags and allows CSV export. 
Enpass has tags, exports JSON and CSV, but *doesn't* export any column with tags.

[Sample Enpass export using tags but without tag data](https://pastebin.com/aqK3F35R)

I wasn't aware of Groups feature, will be using that instead of Tags for now.

Can KeeWeb use 'TOTP' key value for TOTP instead of 'otp'? Other KeePass apps (tested with AuthPass, KeePassXC) use 'TOTP'. Should I open a new issue?

**Comment by antelle** [comment]
Yes, I got the same output without tags. So far, we don't know any app capable to export tags? Then we won't import them either.  
About TOTP, there's no agreement about this for now and it should change in the next version of KDBX format. So, now KeeWeb understands both `otp` (created for example by KeePassXC) and `TOTP Seed` + `TOTP Settings` created by TrayTOTP plugin for KeePass. Which app is using `TOTP` field name?

**Comment by manthanf1** [comment]
> Which app is using TOTP field name?

KeePassXD (Android) uses `TOTP`. As a result, I have two OTP fields: `otp` for KeeWeb and `TOTP` for KeePassXD in the same KDBX file.

I'm trying to find other KeePass Android apps. As long as it's consistent across, its fine. 

Thanks for your time 👍

**Comment by antelle** [comment]
What happens in other apps, for example, KeePassXC, does it understand this format as TOTP? It's probably a new format that I haven't seen before.

**Comment by manthanf1** [comment]
KeePassXC (snap package) uses `TOTP` field name for OTP. [While importing CSV](https://imgur.com/a/kENVv94)
KeePassXD (Android) uses `TOTP`.
AuthPass uses `TOTP`.

**Comment by antelle** [comment]
Well, I hope KDBX4.1 with TOTP standard will come soon and it will solve this mess.

**Comment by manthanf1** [comment]
Hi there. Could you help me with importing CSV into KeeWeb? Instead of `Tags`, I'm using `Groups`. However, KeeWeb doesn't recognize the columns with header `Group`. How can I import those?

**Comment by antelle** [comment]
It's not possible to automatically create groups based on imported CSV.

**Comment by howdytom** [comment]
@antelle Sorry, I have to reopen this issue. 

Why does KeepWeb creates a separate Tags field when I import from a CSV file? I would like to import and assign Tags from my previous Password manager. When you import a lot entries you have to go through hundreds of entries and manually assign Tags one by one. This is crazy. Any workaround?

**Comment by antelle** [comment]
@howdytom are there any clients that export tags in CSV? If yes, I'm more than happy to add support to KeeWeb.

**Comment by howdytom** [comment]
@antelle 1Password does support Tag export. Some clients also sort logins into groups. So, group name could import as Tags into KeeWeb.

**Comment by antelle** [comment]
Group name is imported as folder. Do you have an example of a CSV with tags from 1password?

**Comment by howdytom** [comment]
@antelle Yes, I attached a 1Password [example of a CSV file](https://github.com/keeweb/keeweb/files/7230178/1Password.2021-09-25.07_53.PM.1.items.csv). It is a raw and non modified CSV file. Usually you have to customize CSV to your needs with Excel... 

**1Password export settings**

![1Password CSV export settings](https://user-images.githubusercontent.com/9871520/134781905-4146c1da-150a-4eb3-ad33-c9b3f1ba8251.png)

**Comment by antelle** [comment]
So, it is
```
"{(
    Tag2,
    Tag1
)}",
```
Interesting format, I've never seen that, thank you, then it should be supported in KeeWeb.

**Comment by howdytom** [comment]
Yes, 1Password's format is crazy. What's the recommended tag format in KeeWeb? I though this one

```
Title,User,Password,Website,Tags
Login 1,Test user 1,Password1,Website1,Tag1
```

**Comment by antelle** [comment]
KeeWeb understands different formats, you can select how fields are saved when you import the CSV.
