### ISSUE TITLE
Support Feitian ePass

### ISSUE THREAD

**Issue by lexesv** [keeweb/keeweb#1756]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Support Feitian ePass  https://www.ftsafe.com/Products/FIDO/NFC

**Describe alternatives you've considered**
-

**Additional context**
-

**Comment by antelle** [comment]
Hi! It should be done in #1681 if this key supports `hmac-secret` FIDO2 extension.
