### ISSUE TITLE
Local file preset in JSON

### ISSUE THREAD

**Issue by miharix** [keeweb/keeweb#1759]
Flowing https://github.com/keeweb/keeweb/wiki/Configuration
Section: "JSON app config"

I would like storage location to link to local file.
Example: X:\secrets\my_passwords.kdbx
(X:\  is mapped drive and only visible to user when on same network as local keeweb website)

Or better scan specific local folder and list all kdbx files in it.
Example: X:\secrets\

Is this possible?

**Comment by antelle** [comment]
Hi! No, this is not possible for security reasons: you don't want web pages to be able to read files from disk.

**Comment by miharix** [comment]
Hi.

Thanks for answer.

ps: same wiki page
> "storage": "webdav", // dropbox, webdav, etc...
etc... ? what are other options? "dropbox" , ???

**Comment by antelle** [comment]
Thanks, changed the wiki page a bit. I meant "other cloud storage providers", namely, `onedrive` and `gdrive`.
