### ISSUE TITLE
Option to logout from Dropbox

### ISSUE THREAD

**Issue by antelle** [keeweb/keeweb#176]
There should be a possibility to switch/unlink/logout Dropbox account, as well as other cloud storage providers.

**Comment by antelle** [comment]
Deployed to [beta.keeweb.info](https://beta.keeweb.info), will be available in the next release

**Comment by gustawdaniel** [comment]
Can you explain how to logout from dropbox? Are you interested in pull request that allow to be logged in many dropbox accounts?

I want this feature, so if you want contribution like this I can try possibility of usage many Dropbox accounts in the same time. 

It is typical situation when I want to share some passwords with my client and it could be done by one dropbox account with one kdbx file.

**Comment by antelle** [comment]
You can disable and enable Dropbox to "logout". It should be more usable though.
> Are you interested in pull request that allow to be logged in many dropbox accounts?

Most likely no. We won't support it, it's overcomplicated. But it depends, maybe there's an easy way to do it.
