### ISSUE TITLE
ERROR_405_Keeweb 

### ISSUE THREAD

**Issue by anglsls** [keeweb/keeweb#1760]
Good afternoon everyone!!!!

I am using the keeweb app on a self-hosted on a server.
However, I have   the error shown in the screentshots when
I try to save the changes with the "sync" option. 

My virtualhost configuration is 
![image](https://user-images.githubusercontent.com/81113999/112052138-641c8a00-8b18-11eb-9f3b-a17d1375e13f.png)

and my config.json file is 

![image](https://user-images.githubusercontent.com/81113999/112053887-87483900-8b1a-11eb-8b03-41d858c3b6f4.png)

**Error**
![image](https://user-images.githubusercontent.com/81113999/112049241-f884ed80-8b14-11eb-9e26-36d984705038.png)

The solutions that I have tried is to give all the permissions in the folder where is the keepass and also to the keepass,  I disable selinux and active the "put" feature in webdav. 
Is another configuration missing? Could a self-signed ceritificate be the reason?

**Comment by antelle** [comment]
Hi! No, it can't be because of a self-hosted certificate. I assume, your server returns 405 on OPTIONS request (you can check what it was in the Network tab), so that's what you need to fix.
