### ISSUE TITLE
Markdown newline escape

### ISSUE THREAD

**Issue by gynet** [keeweb/keeweb#1762]
It looks like had some regressions with recent versions regarding the note markdown
For example, the following markdown code rendering is different from other markdown editors,  keeweb removes the newlines, I remember it was not the case before. 
```
# Test
Test
Test
```
Keeweb editing with above markdown code
![image](https://user-images.githubusercontent.com/2174522/112255664-e479e280-8c1f-11eb-8df7-f3d81230687d.png)

Keeweb rendering with above markdown code after editing
![image](https://user-images.githubusercontent.com/2174522/112255805-328ee600-8c20-11eb-8f4d-9dd57ab680b0.png)

Typora rendering results
![image](https://user-images.githubusercontent.com/2174522/112255726-03787480-8c20-11eb-9ec8-6d249fd4ae17.png)

**Comment by antelle** [comment]
Thanks, fixed it. If there's something else in this release, I'll include this fix in v1.17.x too.
