### ISSUE TITLE
Google Drive API drive vs drive.files

### ISSUE THREAD

**Issue by gynet** [keeweb/keeweb#1763]
Is it possible for KeeWeb to use acquire token scope as  'https://www.googleapis.com/auth/drive.file', instead of 'https://www.googleapis.com/auth/drive'? 

Just saw this [stackoverflow post](https://stackoverflow.com/questions/22403014/google-drive-api-scope-and-file-access-drive-vs-drive-files )

**Comment by antelle** [comment]
The first answer in the post you shared explains why we need this scope: for file listing and selection, because we’re not using Google Drive’s file selector (and we will not).
