### ISSUE TITLE
Open file from HTTP-URL (without WebDAV)

### ISSUE THREAD

**Issue by Zari** [keeweb/keeweb#1764]
**Is your feature request related to a problem? Please describe.**
By v1.17.4, KeeWeb cannot open a kdbx provided via an URL/webserver without WebDav.
Trying to paste a URL, will lead to an error message from the file open dialog (interface not available).

**Describe the solution you'd like**
I would like KeeWeb to be able to download and open one kdbx files from an URL. Either the URL can be provided from the GUI (less useful) or from the config files list (more useful). 
Obviously the kdbx will be read-only (or at least, saving won't be possible as there is no way uploading the modified file).

This allows Keeweb to be used with existing web services and apps (like document management systems), that do not feature WebDav and are not nativly supported in KeeWeb. 

**Describe alternatives you've considered**
Using a manual two step procedure would be an alternative (Download kdbx, open it in Keyweb). But this is rather cumbersome on a mobile device.
Using WebDav would raise a lot of complexity and constraints on the backend. Using just a copy downloaded from the URL would not.

**Comment by antelle** [comment]
Hi! KeeWeb already supports HTTP GET/PUT without WebDAV extensions. To use it, switch "WebDAV Save method" in settings.
