### ISSUE TITLE
Yubikey not recognized on Ubuntu 18.04

### ISSUE THREAD

**Issue by jannikdresselhaus** [keeweb/keeweb#1765]
**Describe the bug**
When I plug in a Yubikey 5 NFC, the YubiKey icon pops up. But when I click this icon it says "No YubiKeys found". When creating a new database, the key does not appear in the list of YubiKeys. **The YubiKey is found using ykman list in the terminal**. It is correctly configured for challenge-response in slot 2. It works on KeePassXC.

**Screenshots** 
![Screenshot from 2021-03-26 10 16 55@2x](https://user-images.githubusercontent.com/46087675/112610082-95e56780-8e1c-11eb-884c-e8931930dd8c.png)
![Screenshot from 2021-03-26 10 17 35@2x](https://user-images.githubusercontent.com/46087675/112610096-9aaa1b80-8e1c-11eb-8596-08e7c85b0708.png)
![Screenshot from 2021-03-26 10 19 23@2x](https://user-images.githubusercontent.com/46087675/112610256-c4fbd900-8e1c-11eb-8f38-e35db7643f15.png)

**Environment**
YubiKey 5 NFC, Ubuntu 18.04
KeeWeb v1.17.4 (f8a85af, 2021-03-18)
Environment: electron v12.0.0
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) KeeWeb/1.17.4 Chrome/89.0.4389.69 Electron/12.0.0 Safari/537.36

**Kdbx File**
The YubiKey is neither found when trying to create a new database nor when trying to access an existing one.

**Comment by antelle** [comment]
Just out of curiosity, what was it, did it fix itself?

**Comment by jannikdresselhaus** [comment]
Yes, like magic. After a few restarts, reinstalls and some iterations of inserting and removing the YubiKey, it now seems to work just fine. No idea what fixed it exactly. Thanks for the amazing work, keep it up! Love the UX.

**Comment by sheeepdev** [comment]
After a bit of digging I found this: https://github.com/Yubico/yubikey-personalization/issues/122 Appereantly my YubiKey is not supported.

**Comment by sheeepdev** [comment]
Tho it is a bit wierd and I dont really understand why wouldn't it be supported..

**Comment by antelle** [comment]
If it's a "security key", it doesn't support Yubico OTP anyway: https://www.yubico.com/nl/product/security-key-nfc-by-yubico/ (search "Function"), so if we were able to recognize it, it wouldn't be possible to use it.
