### ISSUE TITLE
Opening database with TouchID while in Autotype-Mode closes Autotype

### ISSUE THREAD

**Issue by dploeger** [keeweb/keeweb#1768]
**Describe the bug**
When the user opens Autotype and opens a new database directly in the Autotype view, usually the database is opened and we're back in the Autotype browser. However, using TouchID brings us to the editor and closes Autotype.

**To Reproduce**
1. Open Keeweb on macOS. Don't open a database yet.
2. Trigger Autotype
3. Use the hotkey to open a database
4. Unlock the database using TouchID
5. The database editor is shown

**Expected behavior**
After opening the database, autotype should be visible again.

**Environment**
KeeWeb v1.17.4 (f8a85af, 2021-03-18)
Environment: electron v12.0.0
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) KeeWeb/1.17.4 Chrome/89.0.4389.69 Electron/12.0.0 Safari/537.36

**Comment by antelle** [comment]
Thanks, I assume it's because the window loses focus and auto-type is cancelled.

**Comment by dploeger** [comment]
Ah, that could very much be because of the TouchID modal. I guess, it's a bit hard to fix that, right?

**Comment by antelle** [comment]
Not quite hard, we know that touch id authentication was called, so it's easy to understand what it was. The hardest part is to find the proper place to insert this workaround.

**Comment by antelle** [comment]
Fixed this, additionally, there will be also a message on the open screen:

<img width="1122" alt="unlock to auto-type" src="https://user-images.githubusercontent.com/633557/116060333-11d40900-a682-11eb-8462-9f2406fb57a2.png">

**Comment by dploeger** [comment]
Thanks
