### ISSUE TITLE
Add CORS headers on the plugin catalog

### ISSUE THREAD

**Issue by aslafy-z** [keeweb/keeweb#1771]
**Is your feature request related to a problem? Please describe.**
I'd like to download the plugin catalog from my private instance but it fails with CORS errors.

**Describe the solution you'd like**
Add Access-Control-Allow-Origin and Access-Control-Allow-Method headers to the plugin registry (json file) and all the files.

**Describe alternatives you've considered**
Download the file locally, but it fails when downloading plugins details.

**Additional context**
Full error

```
Access to XMLHttpRequest at 'https://plugins.keeweb.info/plugins.json' from origin 'https://tools.onecaas.vpodg1np.carrefour.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
2021-03-30T08:25:54.666Z [plugin-gallery] Network error loading plugins
GET https://plugins.keeweb.info/plugins.json net::ERR_FAILED
```

**Comment by antelle** [comment]
Done:

```
curl -SsL -H 'Origin: https://example.com' -I "https://plugins.keeweb.info/plugins.json" | grep access-control
access-control-allow-origin: *
access-control-expose-headers: Content-Length, Content-Type, Date, Server, Transfer-Encoding, X-GUploader-UploadID, X-Google-Trace
```

**Comment by aslafy-z** [comment]
Thank you, it works as expected!
