### ISSUE TITLE
Copy password in pwa

### ISSUE THREAD

**Issue by prashantkhurana** [keeweb/keeweb#1772]
**Describe the bug**
When keeweb is installed as pwa from chrome, copy password (command+C) invokes copy command of the web app which does nothing. (Copy username still works)
**To Reproduce**
1. Go to https://app.keeweb.info/
2. Install and open  app and load kdbx
3. Go to any entry and try to copy password by command+C 
4. nothing is copied

**Expected behavior**
Password is copied

**Comment by prashantkhurana** [comment]
to make sure, I just tried with chrome stable instead of chrome canary(v91) and it works there. Tried it on 2 laptops and can consistently reproduce with canary. We can close this and hopefully its a bug in chrome.

**Comment by antelle** [comment]
Yes, it's the same in Canary for me.

**Comment by prashantkhurana** [comment]
thanks for the quick response! much appreciated!
