### ISSUE TITLE
Unlocking database using Touch ID results in an error if new fingerprints are added in System Preferences

### ISSUE THREAD

**Issue by jlorenzetti** [keeweb/keeweb#1775]
**Describe the bug**
Trying to unlock database using MacBook Pro's Touch ID results in an error.

**To Reproduce**
1. Start KeeWeb for macOS
2. Click on fingerprint icon to open latest database using Touch ID
3. Place finger on Touch ID sensor as requested

**Expected behavior**
Database should be opened without error.

**Screenshots**
<img width="1112" alt="Schermata 2021-04-02 alle 00 09 38" src="https://user-images.githubusercontent.com/58301906/113359373-ecd0cc80-9347-11eb-9973-c6bffe4579a6.png">

**Environment**
KeeWeb v1.17.5 (4ee87e1, 2021-03-27)
Environment: electron v12.0.0
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 11_2_3) AppleWebKit/537.36 (KHTML, like Gecko) KeeWeb/1.17.5 Chrome/89.0.4389.69 Electron/12.0.0 Safari/537.36

**Kdbx File**
It happens on existing database. Everything works fine using password instead of Touch ID.

**Logs**
index.html:1 2021-04-01T22:02:51.336Z [open-view] Encrypting password using hardware decryption
index.html:1 2021-04-01T22:02:56.596Z [open-view] Error opening file Error: Error invoking remote method 'hardwareDecrypt': Error: SecKeyCreateDecryptedData: OSStatus -1
    at EventEmitter.i.invoke (electron/js2c/renderer_init.js:73)
    at async Object.hardwareDecrypt (index.html:1)
r.error @ index.html:1

**Comment by antelle** [comment]
Hi! To isolate the issue, could you please try encrypting and decrypting a random piece of data using this app: https://github.com/antelle/node-secure-enclave/releases/tag/0.4.1

**Comment by jlorenzetti** [comment]
> Hi! To isolate the issue, could you please try encrypting and decrypting a random piece of data using this app: https://github.com/antelle/node-secure-enclave/releases/tag/0.4.1

Just tested, the decryption with Touch ID worked fine

**Comment by antelle** [comment]
Interesting, this means the encrypted data has been corrupted somehow. What happens if you:
1. disable Touch ID
2. enable Touch ID
3. open a file with password
4. close the file
5. open it with Touch ID

?

**Comment by jlorenzetti** [comment]
> Interesting, this means the encrypted data has been corrupted somehow. What happens if you:
> 
> 1. disable Touch ID
> 2. enable Touch ID
> 3. open a file with password
> 4. close the file
> 5. open it with Touch ID
> 
> ?

Just tried: it still displays the same error

**Comment by antelle** [comment]
I can make a build with some logging, if you don't mind testing it.

**Comment by jlorenzetti** [comment]
Yes I can test it, thanks 👍

**Comment by antelle** [comment]
Uploaded it here: https://storage.googleapis.com/beta.keeweb.info/KeeWeb.app.zip
Please run it from Terminal like this:
```
KeeWeb.app/Contents/MacOS/KeeWeb
```

Then when it starts, open DevTools. Disable and enable Touch Id in settings. Then open a test (❕) database with password, close it, and open with Touch ID.

Find everything containing `encrypt` or `decrypt`, both in Terminal and DevTools. They're different values, however they must match each other. Let's see what it prints for you!

❗ please do it only on the test db! These values contain non-encrypted password to this db.

**Comment by jlorenzetti** [comment]
Terminal:
```
encrypt input dGVzdCBwYXNzd29yZA==
encrypt result BLFpyiitYDZ3PJnq+aiHz70l86D+OMIw9f3WNSyc0UJ0Z9ARSvbHg0td6ywCLMPZLMVb0p70gK9PezMk8no+2raizrw8t553lrKU4HLh0IyonbzrstQMWmKNr37FMw==
decrypt input BLFpyiitYDZ3PJnq+aiHz70l86D+OMIw9f3WNSyc0UJ0Z9ARSvbHg0td6ywCLMPZLMVb0p70gK9PezMk8no+2raizrw8t553lrKU4HLh0IyonbzrstQMWmKNr37FMw==
Error occurred in handler for 'hardwareDecrypt': [Error: SecKeyCreateDecryptedData: OSStatus -1] { code: -1 }
```

DevTools:
```
encrypt input dGVzdCBwYXNzd29yZA==
index.html:1 encrypt result BLFpyiitYDZ3PJnq+aiHz70l86D+OMIw9f3WNSyc0UJ0Z9ARSvbHg0td6ywCLMPZLMVb0p70gK9PezMk8no+2raizrw8t553lrKU4HLh0IyonbzrstQMWmKNr37FMw==
index.html:1 2021-04-02T12:14:25.187Z [open-view] Encrypting password using hardware decryption
index.html:1 decrypt input BLFpyiitYDZ3PJnq+aiHz70l86D+OMIw9f3WNSyc0UJ0Z9ARSvbHg0td6ywCLMPZLMVb0p70gK9PezMk8no+2raizrw8t553lrKU4HLh0IyonbzrstQMWmKNr37FMw==
index.html:1 2021-04-02T12:14:27.353Z [open-view] Error opening file Error: Error invoking remote method 'hardwareDecrypt': Error: SecKeyCreateDecryptedData: OSStatus -1
    at EventEmitter.i.invoke (electron/js2c/renderer_init.js:73)
    at async Object.hardwareDecrypt (index.html:1)
```

**Comment by antelle** [comment]
Now I'm don't understand this. I see that it's passed correctly, so it's the same value as we got, however it can't decrypt it 🤔

**Comment by jlorenzetti** [comment]
I don't know if it can be of any help: the first time (or maybe the first few times) I tried unlocking with Touch ID after installing KeeWeb it worked fine.

**Comment by jlorenzetti** [comment]
These lines appear in my system log every time I try to unlock a database with Touch ID:
```
errore	15:54:46.658934+0200	WindowServer	Error generating assertion string
errore	15:54:46.659143+0200	WindowServer	hid_event_callback: Invalid event type: 29
errore	15:54:47.151278+0200	biometrickitd	AssertMacros: _fingerDetectEndTime (value = 0x0),  file: /AppleInternal/BuildRoot/Library/Caches/com.apple.xbs/Sources/Mesa_NonUI/Mesa-692.80.18/AppleBiometricServices/MesaCoreAnalytics/MesaCoreAnalyticsEvent.m, line: 1068
errore	15:54:47.153723+0200	biometrickitd	AssertMacros: _fingerDetectEndTime (value = 0x0),  file: /AppleInternal/BuildRoot/Library/Caches/com.apple.xbs/Sources/Mesa_NonUI/Mesa-692.80.18/AppleBiometricServices/MesaCoreAnalytics/MesaCoreAnalyticsEvent.m, line: 1068
errore	15:54:47.155493+0200	biometrickitd	AssertMacros: _fingerDetectEndTime (value = 0x0),  file: /AppleInternal/BuildRoot/Library/Caches/com.apple.xbs/Sources/Mesa_NonUI/Mesa-692.80.18/AppleBiometricServices/MesaCoreAnalytics/MesaCoreAnalyticsEvent.m, line: 1068
errore	15:54:47.192370+0200	ctkd	Error acquiring assertion: <Error Domain=RBSAssertionErrorDomain Code=2 "Specified target process does not exist" UserInfo={NSLocalizedFailureReason=Specified target process does not exist}>
errore	15:54:47.219659+0200	containermanagerd	failed to read /Library/Preferences/Logging/com.apple.diagnosticd.filter.plist: [1: Operation not permitted]
errore	15:54:47.219818+0200	containermanagerd	failed to read /Library/Preferences/Logging/com.apple.diagnosticd.filter.plist: [1: Operation not permitted]
errore	15:54:47.244995+0200	setoken	Bootstrapping; external subsystem UIKit_PKSubsystem refused setup
errore	15:54:47.999089+0200	WindowServer	hid_event_callback: Invalid event type: 29
errore	15:54:47.998930+0200	biometrickitd	MesaCoreAnalyticsEvent valueForUndefinedKey: quickTapsCount
```

**Comment by antelle** [comment]
Interesting, however I don't understand what this means. Sounds like something with code signing (but I'm not sure), what happens if you do
```
codesign --display --entitlements :- /Applications/KeeWeb.app
```

**Comment by jlorenzetti** [comment]
> ```
> codesign --display --entitlements :- /Applications/KeeWeb.app
> ```
```
Executable=/Applications/KeeWeb.app/Contents/MacOS/KeeWeb
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>com.apple.security.cs.allow-jit</key>
    <true/>
    <key>com.apple.security.cs.allow-unsigned-executable-memory</key>
    <true/>
    <key>com.apple.security.cs.allow-dyld-environment-variables</key>
    <true/>
    <key>keychain-access-groups</key>
    <array>
      <string>3LE7JZ657W.net.antelle.keeweb</string>
    </array>
    <key>com.apple.application-identifier</key>
    <string>3LE7JZ657W.net.antelle.keeweb</string>
    <key>com.apple.developer.team-identifier</key>
    <string>3LE7JZ657W</string>
  </dict>
</plist>
```

**Comment by antelle** [comment]
That's the correct output. I'll try to inspect the code once again and read the docs to understand what can go wrong. Apple's docs about Secure Enclave don't reveal the reason though...

**Comment by jlorenzetti** [comment]
Bingo! The error only occurs if I have more than one fingerprint stored in my Touch ID system preferences. If I delete all the fingerprints except one, KeeWeb works as expected.

**Comment by antelle** [comment]
Wauw, what a find! Have you added an additional finger after launching KeeWeb? I just tried it in the same app, it works if enroll an additional finger before creating a key and gives the same error if I add it after it, I assume that's because we request that the same biometry is used to unlock the key (but I expected it to be a bit different).

**Comment by antelle** [comment]
I assume, we need can do two things here:

1. add an explanation to the error message
2. add a button that will re-create the encryption key

**Comment by jlorenzetti** [comment]
> Wauw, what a find! Have you added an additional finger after launching KeeWeb? I just tried it in the test app I shared above, it works if enroll an additional finger before creating a key and gives the same error if I first create a key and then add a finger, I assume that's because we request that the same biometry is used to unlock the key (but I expected it to be a bit different).

Exactly! I used KeeWeb one or a few times (and it worked without any error) and later I added an additional finger.

**Comment by antelle** [comment]
I made a build that deletes the key from Keychain when you disable Touch ID. Could you please give it a try? How it should work: https://storage.googleapis.com/beta.keeweb.info/KeeWeb.app.zip
1. launch KeeWeb 
2. make sure Touch ID is working
3. add a finger
4. check that Touch ID is not working
5. go to settings, disable and enable Touch ID
6. open and close a file using password
7. check if Touch ID is working now

**Comment by jlorenzetti** [comment]
Confirmed, everything went like you said 👍

**Comment by antelle** [comment]
Ok, thank you for help with testing! Added an error message (it seems to be not possible to understand what happened, so the it will say "maybe") and the explanation how to fix the issue.

**Comment by jlorenzetti** [comment]
Thank you!
