### ISSUE TITLE
Saving the webdav credentials.

### ISSUE THREAD

**Issue by Daeny85** [keeweb/keeweb#1778]
# please describe your issue here

I have set up keeweb on my webserver which is only accessible in my internal network.
So that I do not have to enter the URL and the credentials to the webdav server on which the kdbx file is located on each PC, I am looking for a way to be able to enter these once so that I do not have to enter them again on each PC.

KeeWeb v1.17.5 (4ee87e1, 2021-03-27)
Environment: web
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.1 Safari/605.1.15

**Comment by antelle** [comment]
Hi! You can achieve this using a config file: https://github.com/keeweb/keeweb/wiki/Configuration#json-app-config
