### ISSUE TITLE
The password generated in the "Password" field shouldn't be copied to clipboard

### ISSUE THREAD

**Issue by Akhilesh-T** [keeweb/keeweb#1779]
**Is your feature request related to a problem? Please describe.**
When I generate a password by clicking the bolt icon ⚡ in the **Password** field, the same is also saved to the **clipboard**. 

---

**Describe the solution you'd like**
- The password shouldn't be saved in the **clipboard** if it's generated from the **Password** field because it is saved in this field anyway.

![KeeWeb_zRRfyht8zM](https://user-images.githubusercontent.com/80357467/113501808-9f21b300-9545-11eb-9f1a-44b87134846a.jpg)

---
- But it's okay if the password is saved if generated from 2 other areas (because that's their purpose)

1. <img width="526" alt="KeeWeb_20nH9f2U2C" src="https://user-images.githubusercontent.com/80357467/113501928-92518f00-9546-11eb-8640-d01f0262e0d3.png">

AND

2. <img width="439" alt="KeeWeb_Qk3fx8xQED" src="https://user-images.githubusercontent.com/80357467/113501938-9ed5e780-9546-11eb-98f7-89f778812d3b.png">

Thanks a lot. I love this software ❤

**Comment by antelle** [comment]
It was not supposed to copy it, right, will be fixed in the next release

**Comment by Akhilesh-T** [comment]
Thanks a lot 😍
