### ISSUE TITLE
Self hosted keeweb modify problem

### ISSUE THREAD

**Issue by svetoslavsimeonov1987** [keeweb/keeweb#1781]
Is there a way that i can modify index.html on a self-hosted keeweb server. Currently when i want to remove a input field or change a text it is not working. 
I want to remove username and password fields in WebDav so that the users are not confused that they have to enter credentials.
Thank you.

**Comment by antelle** [comment]
Hi! It would be hard to find and modify the piece of javascript directly in the html, but you can make a patch and rebuild KeeWeb.

**Comment by svetoslavsimeonov1987** [comment]
Is there a guide how i can build it?

**Comment by antelle** [comment]
It's described in the readme: https://github.com/keeweb/keeweb#building
But you can just clone the repo and run
```
npm i
npm start
```

**Comment by svetoslavsimeonov1987** [comment]
If i understand correctly i have to :

git clone https://github.com/keeweb/keeweb.git
npm installl
npm start

and i will receive a dist directory with the build version of keeweb index.html and all other files?

**Comment by antelle** [comment]
If it works without issues, yes.

**Comment by svetoslavsimeonov1987** [comment]
im getting the following:


Running "webpack:app" (webpack) task
Fatal error: iconFontScssSource.matchAll(...) is not a function or its return value is not iterable


Execution Time (2021-04-06 22:25:34 UTC+3)
loading tasks    2.5s  ██████████████████████████ 14%
eslint:app      13.5s  ██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████ 73%
eslint:desktop  432ms  █████ 2%
eslint:build    627ms  ███████ 3%
webpack:app      1.1s  ████████████ 6%
Total 18.5s

npm ERR! code ELIFECYCLE
npm ERR! errno 3
npm ERR! keeweb@1.17.5 start: `grunt`
npm ERR! Exit status 3
npm ERR!
npm ERR! Failed at the keeweb@1.17.5 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:

**Comment by antelle** [comment]
Upgrading node.js should fix this
