### ISSUE TITLE
Disabling "USB support" crashes the app

### ISSUE THREAD

**Issue by Battleman** [keeweb/keeweb#1783]
**Describe the bug**
When disabling the "USB devices " support in the desktop app, the application unexpectedly crashes (segfault)

**To Reproduce**
1. Open Keeweb
2. (opt) open/create a DB
3. Open settings -> Devices
4. If Support is enabled, disable. If disabled, enable then disable.

**Expected behavior**
The disabling (or toggling) should open and close the menu below, and leave the app running

**Screenshots**

![Devtools error trace](https://user-images.githubusercontent.com/6746316/114015265-c93ae400-9869-11eb-8e74-ce4faa7a9c17.png)

**Environment**
KeeWeb v1.17.5 (4ee87e1, 2021-03-27)
Environment: electron v12.0.0
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) KeeWeb/1.17.5 Chrome/89.0.4389.69 Electron/12.0.0 Safari/537.36

**Kdbx File**
Happens on my normal KDBX file, as well as a "new" file, and even without file.

**Logs**
When opening the "Devices" menu, the following error is triggered in the logs (see screenshots for devtools trace):
```
[ERROR] 2021-04-08T10:48:14.608Z [launcher] spawn error: ykman, 40ms Error: spawn ykman ENOENT
[ERROR] 2021-04-08T10:48:14.610Z [launcher] spawn ykman: -2, 43ms
```
Opening another menu, then the Devices menu back yields the error each time the Devices menu is opened, but doesn't crash. Only disabling the USB support does crash.

When opening the app with the `--devtools` command line option, at crash time there is a segfault:
```
/usr/bin/keeweb: line 2:  9239 Segmentation fault      (core dumped) /usr/share/keeweb-desktop/keeweb "$@"
```

**Edits**
Issue opened on v1.17.3; just upgraded to v1.17.5, issue persisted; updated environment info

**Comment by antelle** [comment]
It's interesting that it should happen when you stop it, and not the other way around. I assume, an easy fix would be continue running the usb listener when it's stopped, but don't do anything. I'll check why it fails first.

Which operating system is that?

**Comment by Battleman** [comment]
I'm running Pop!_OS 20.10
`Linux  5.8.0-7642-generic #47~1614007149~20.10~82fb226-Ubuntu SMP Tue Feb 23 02:59:01 UTC  x86_64 x86_64 x86_64 GNU/Linux`
Also failed to mention, but although it crashes, it does work. At next startup, support is correctly disabled. So it's a minor bug I guess, just wanted to point it out.

**Comment by antelle** [comment]
Thank you! I assume, the disconnection function causes this crash.  
Now we're using [node-usb-detection](https://github.com/MadLittleMods/node-usb-detection) module to watch devices, which is much more stable compared to `node-usb`, but it seems to fail sometimes as well.

**Comment by antelle** [comment]
I can repeat it and I've fixed it in KeeWeb, however the library still crashes on exit when I call `stopMonitoring`. I figured out why it happens and submitted a PR there: https://github.com/MadLittleMods/node-usb-detection/pull/138

Since it's not critical and it happens only when you disable the checkbox, I won't fork the library for a while, however I'll do it if needed. But it seems to be well-maintained, so I hope my PR will be merged soon.

**Comment by Battleman** [comment]
Fair enough. Indeed, it's not critical, it doesn't seem so important to fork and build from that. Thanks for looking into it!

**Comment by antelle** [comment]
Well it's already forked and fixed, I just need to switch the build to it. But maybe by the time we come to it it will be already merged.

**Comment by antelle** [comment]
The author doesn't seem to be very enthusiastic about merging PR's 😏 , so I rebuilt the module from my fork, this fixes the issue.
