### ISSUE TITLE
[storage-gdrive] OAuth: popup opened

### ISSUE THREAD

**Issue by ottahe** [keeweb/keeweb#1786]
Hello,

since 2 days, the popup appears and I have to click on my standard account in order to continue.
It appears once after opening the kdbx and then every hour, and it happens on both Windows
and Linux.

In the log it says

<pre>
[INFO ] 2021-04-08T19:45:16.243Z [sync:ott] Sync started gdrive 1v...
[INFO ] 2021-04-08T19:45:16.268Z [sync:ott] Stat file
[DEBUG] 2021-04-08T19:45:16.400Z [storage-gdrive] OAuth: popup opened
[DEBUG] 2021-04-08T19:46:42.254Z [storage-gdrive] OAuth code received
[INFO ] 2021-04-08T19:46:42.255Z [storage-gdrive] HTTP request POST https://oauth2.googleapis.com/token
[INFO ] 2021-04-08T19:46:42.488Z [storage-gdrive] HTTP response 200
[DEBUG] 2021-04-08T19:46:42.488Z [storage-gdrive] OAuth code exchanged {"access_token":"ya...","expires_in":3598,"scope":"https://www.googleapis.com/auth/drive","token_type":"Bearer"}
[DEBUG] 2021-04-08T19:46:42.488Z [storage-gdrive] OAuth token received
[DEBUG] 2021-04-08T19:46:42.489Z [storage-gdrive] Stat 1v...
[INFO ] 2021-04-08T19:46:42.489Z [storage-gdrive] HTTP request GET https://www.googleapis.com/drive/v3/files/1v...?fields=headRevisionId
[INFO ] 2021-04-08T19:46:42.997Z [storage-gdrive] HTTP response 200
</pre>

KeeWeb v1.17.5 (4ee87e1, 2021-03-27)
Environment: web
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:84.0) Gecko/20100101 Firefox/84.0

KeeWeb v1.17.5 (4ee87e1, 2021-03-27)
Environment: web
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:78.0) Gecko/20100101 Firefox/78.0

How can I get this back to normal?

**Comment by antelle** [comment]
Hi! That's strange, what do you see in logs before it opens the popup?

**Comment by ottahe** [comment]
Just 2 successful syncs at 19:15 and 19:30, no errors or similar.

<pre>
[INFO ] 2021-04-08T19:15:15.696Z [sync:ott] Sync finished no error
[INFO ] 2021-04-08T19:30:15.289Z [sync:ott] Sync started gdrive 1v...
[INFO ] 2021-04-08T19:30:15.292Z [sync:ott] Stat file
[DEBUG] 2021-04-08T19:30:15.292Z [storage-gdrive] Stat 1v...
[INFO ] 2021-04-08T19:30:15.293Z [storage-gdrive] HTTP request GET https://www.googleapis.com/drive/v3/files/1v...?fields=headRevisionId
[INFO ] 2021-04-08T19:30:15.639Z [storage-gdrive] HTTP response 200
[DEBUG] 2021-04-08T19:30:15.639Z [storage-gdrive] Stated 1v... 0B9... 347ms
[INFO ] 2021-04-08T19:30:15.639Z [sync:ott] Stat found same version, not modified
[INFO ] 2021-04-08T19:30:15.640Z [sync:ott] Sync finished no error
[INFO ] 2021-04-08T19:45:16.243Z [sync:ott] Sync started gdrive 1v..
[INFO ] 2021-04-08T19:45:16.268Z [sync:ott] Stat file
[DEBUG] 2021-04-08T19:45:16.400Z [storage-gdrive] OAuth: popup opened
[DEBUG] 2021-04-08T19:46:42.254Z [storage-gdrive] OAuth code received
</pre>

**Comment by antelle** [comment]
Ouch. I see that Google API doesn't return the refresh token anymore 😢 
This of course means that KeeWeb will show the pop-up. Not sure what to do with it yet.

**Comment by antelle** [comment]
Hm, this is because of a bug introduces recently. I see that I do get a refresh token on production.
Are you maybe using `beta.keeweb.info` by any chance?

**Comment by ottahe** [comment]
No, the plain KeeWeb v1.17.5 (4ee87e1, 2021-03-27).

**Comment by ottahe** [comment]
It's there but not on localhost.
![2021-04-08 23_38_30-Window](https://user-images.githubusercontent.com/35665727/114099915-d8e71680-98c3-11eb-9276-6cecbb21f494.png)

**Comment by antelle** [comment]
I see that there's no `refreshToken`, only `accessToken` 🤔

**Comment by antelle** [comment]
Ok, I figured out why this happens, the bug was committed a bit earlier. No input is needed anymore, and my commit above will fix it. A patch is coming soon...

**Comment by ottahe** [comment]
ok, thanks.

**Comment by ottahe** [comment]
I still have to click on my account. Do I deed to refresh or delete something?

**Comment by antelle** [comment]
It's not released yet, I'll roll it out tonight or tomorrow.

**Comment by antelle** [comment]
It's rolled out 🎉

**Comment by ottahe** [comment]
I'm at v1.17.6 and It's still asking on Mozilla. Can I do something like remove cache?

**Comment by antelle** [comment]
I'll check why this happens, it doesn't give a refresh token for me as well.

**Comment by antelle** [comment]
It's strange, I see that it works on localhost and in the app, but it doesn't return refresh_token on web.

**Comment by antelle** [comment]
I don't think we'll be able to solve this. It's very likely that Google disabled refresh tokens for JavaScript apps, so the only way to get a permanent authentication is via installing an app.

**Comment by ottahe** [comment]
It works ok on Chrome tho.

---
Mit freundlichen Grüßen / Kind regards

Joachim Ott

GPG Fingerprint 8923 DE80 DB8C 9126 552A 967F 41EE DED6 DFF5 5986

Am 10.04.2021 17:13 schrieb Dimitri Witkowski:

**Comment by antelle** [comment]
Yeah, now the code is fixed and it works, however in some browsers Google doesn't return the refresh_token. For example for me it doesn't work in Chrome in incognito.

**Comment by ottahe** [comment]
I moved to Dropbox on all devices. Everything is fine so far.

**Comment by antelle** [comment]
Yeah, Dropbox seems to provide the most convenient authentication and file API for web compared to other social providers.
