### ISSUE TITLE
GDrive sync issues when not using .kdbx file extension

### ISSUE THREAD

**Issue by kasoban** [keeweb/keeweb#179]
Running the tagged 1.1.0 desktop client for x64 linux

The GDrive integration seems to only work when actually using the .kdbx file extension for a KeePass container. For various reasons that is not the case with most of my container files.
This leads to the following symptoms:
- Opened my local file based KeePass container (for sake of completeness: using a .dat extension)
- In container settings, clicked "Save to" and GDrive
- Entered GDrive credentials as it was the first time using it
  Now it begins to be interesting. I already had that file manually synced in GDrive, and when I look in the dev tools I see that it actually got mapped to that file in a GDrive subdirectory. But, it never wrote anything to that location, reporting a sync error based on a 404 error.
  At that point the icon for the container has changed to the GDrive icon, in the bottom bar and in the recent file startup screen. Choosing "Save to" again at that point, and saving to local file in the sync error state will result in a 1 byte large file, containing the hex value 00.

Another symptom of the .kdbx filter: When not having any .kdbx file in your GDrive, selecting the GDrive option from the startup screen results in the message "No files which could be opened (files are searched inside undefined folder". This is because GDrive returns an empty array for the .kdbx file lookup, which seems to be weirdly handled as the storage.list() result.

I can confirm though that syncing .kdbx files works fine with this version, and once a .kdbx file is in GDrive it will show up in the startup screen selection.

**Comment by kasoban** [comment]
On a second note, the sync issue itself might not be related to the file extension after all. I tried renaming my local container to .kdbx but it has the same issue when I open that and try to save it to GDrive. 

From dev console:

> 2016-04-06T14:07:03.535Z [storage-gdrive] List
> Failed to load resource: the server responded with a status of 401 ()
> 2016-04-06T14:07:03.663Z [storage-gdrive] OAuth popup opened
> 2016-04-06T14:07:03.906Z [storage-gdrive] OAuth success
> 2016-04-06T14:07:03.906Z [storage-gdrive] Repeat request, try #1 https://www.googleapis.com/drive/v3/files?fields=files&q=fileExtension%3D%2…0and%20mimeType%3D%22application%2Foctet-stream%22%20and%20trashed%3Dfalse
> 2016-04-06T14:07:04.387Z [storage-gdrive] Listed 852ms
> 2016-04-06T14:07:04.393Z [sync:mycontainername] Sync started gdrive /path/to/my/local/container.kdbx Object
> 2016-04-06T14:07:04.395Z [sync:mycontainername] Stat file
> 2016-04-06T14:07:04.396Z [storage-gdrive] Stat /path/to/my/local/container.kdbx
> Failed to load resource: the server responded with a status of 404 ()
> 2016-04-06T14:07:04.422Z [storage-gdrive] Stat error 26ms http status 404
> 2016-04-06T14:07:04.422Z [sync:mycontainername] Stat error, not dirty http status 404
> 2016-04-06T14:07:04.422Z [sync:mycontainername] Sync finished http status 404

Might the issue be the resource mapping for the container? Because a newly created container which I add to GDrive from the "Save to" menu will be referenced by a long hash-like identifier in the 
"[sync:containername] Sync started gdrive %identifier_here%" log line instead of the local path of the error case.

**Comment by antelle** [comment]
Looks like save to gdrive doesn't work always, I'll check it today

**Comment by antelle** [comment]
Custom extensions maybe will supported later... For now, only save errors will be fixed

**Comment by antelle** [comment]
File save issue was fixed, the hotfix will be available today. Saving with other file extensions triaged to Future.

**Comment by kasoban** [comment]
Confirming that upload of existing file containers works fine now. Thanks!

**Comment by antelle** [comment]
I think it's okay to leave it as is for now
