### ISSUE TITLE
Error checking for updates

### ISSUE THREAD

**Issue by melo0187** [keeweb/keeweb#1790]
**Describe the bug**
The application fails to check for updates both when checking automatically or when manually triggering the update check.

**To Reproduce**
1. Go to 'Settings / General'
2. Click on 'Check for Updates'
3. See error `Error checking for updates. Last successful check was at Mar 11, 2021, 1:23:15 PM: the latest version was 1.17.1`

**Expected behavior**
Expected check to succeed, discover the new version and offer to install it.

**Screenshots**
![image](https://user-images.githubusercontent.com/2528018/115692947-bcd18380-a35f-11eb-97f7-dfff8219ea5a.png)

**Environment**
```
KeeWeb v1.16.8 (69f7b02, 2021-03-02)
Environment: electron v11.0.3
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) KeeWeb/1.16.1 Chrome/87.0.4280.67 Electron/11.0.3 Safari/537.36
```

**Kdbx File**
Have not tested with Demo or New database yet, because I currently do not expect this issue to be connected to the actual kdbx file. However I will happily do the test if requested.

**Logs**
```
[INFO ] 2021-04-22T09:45:13.194Z [updater] Checking for update...
[INFO ] 2021-04-22T09:45:13.195Z [transport] GET https://app.keeweb.info/manifest.appcache
[INFO ] 2021-04-22T09:45:13.203Z [transport] Request to https://app.keeweb.info/manifest.appcache without proxy
[INFO ] 2021-04-22T09:45:13.348Z [transport] Response from https://app.keeweb.info/manifest.appcache: 404
[ERROR] 2021-04-22T09:45:13.349Z [updater] Update check error HTTP status 404
[INFO ] 2021-04-22T09:45:13.355Z [updater] Next update check will happen in 86400s
﻿

**Comment by antelle** [comment]
Hi! v1.16 is already quite old, if you update it, v1.17 will check for updates.

**Comment by melo0187** [comment]
@antelle Thanks for the fast feedback. I just upgraded by apt installing the 1.17.6 deb.
However the entire Update section in General Settings is gone. Is that to be expected?
How do I trigger an update check now to verify it will work?

**Comment by melo0187** [comment]
Oh, what a pity. I guess there are no plans to publish the deb to a ppa or the snap to snapcraft so that the system's package manager would update keeweb whenever you publish a new release, are there?
So I'm back to subscribing to release notifications and update manually?
I was actually quite happy with the integrated updater... :-/

**Comment by antelle** [comment]
Well, eventually snap and deb should be published, but I'm not sure when I come to it because there are rules too. Any help would be very welcome!
The integrated updater unfortunately doesn't scale anymore, now we're extensively using native modules, so updating just javascript is not what we want.

**Comment by melo0187** [comment]
I never published anything through those channels (and never packaged software as a deb or snap for that matter), but that does not mean I couldn't learn to.
I value keeweb and the work you put into it very much. So if I can contribute in some capacity I would be happy to do so.

I will look into what it takes to publish to a PPA and snapcraft and see what I can learn. Let me know if there is anything specific to look into or consider.

**Comment by antelle** [comment]
We already have a snap package, however:
1. it doesn't install the shortcut for an unknown reason because of #1473
2. when I tried to upload it to the store, it gave some violations, I don't remember what exactly and most likely these things are already fixed in Electron, I need to check again

With deb it should be easier I assume. I wonder if there are ready to use tools that would publish deb files, probably yes, but I don't know how to do it. The package is already built, so we just need to publish it. I assume, we need to create a pipeline and publish it from there, but I need to understand how. Ideally it should be a GitHub action, but we can run any possible tool  on CI.
