### ISSUE TITLE
Keeweb Unable to Find kdbx Database on Dropbox

### ISSUE THREAD

**Issue by fgimian** [keeweb/keeweb#1791]
**Describe the bug**
I have linked my Dropbox account with https://app.keeweb.info/ and my password file resides under `Documents/Password Database.kdbx` yet KeeWeb can't seem to find it.  I also attempted to move the database to the root of my Dropbox with similar results.

I initially was using 2-step authentication in Dropbox which I temporarily disabled in case that was the issue, but the issue persisted.

**To Reproduce**
1. Go to https://app.keeweb.info/
2. Click on More
3. Select Dropbox
4. Approve access to Dropbox
5. Error appears

**Expected behavior**
The password database file should be located.

**Screenshots**
![image](https://user-images.githubusercontent.com/1811813/115797976-886dce00-a418-11eb-9c72-fba382e92d03.png)

**Environment**
KeeWeb v1.17.6 (8efee7d, 2021-04-09)
Environment: web
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:88.0) Gecko/20100101 Firefox/88.0

**Kdbx File**
It happens on all KDBX files I've tried including a brand new database.

**Logs**

```
2021-04-22T23:46:59.862Z [storage-dropbox] List app.keeweb.info:1:411464
2021-04-22T23:46:59.863Z [storage-dropbox] HTTP request POST https://api.dropboxapi.com/2/files/list_folder app.keeweb.info:1:411585
2021-04-22T23:47:00.336Z [storage-dropbox] HTTP response 200 app.keeweb.info:1:411585
2021-04-22T23:47:00.336Z [storage-dropbox] Listed 474ms
```

**Comment by antelle** [comment]
Hi! Is Dropbox linked to the app folder of full dropbox? If it’s in app folder mode, this can be the reason

**Comment by fgimian** [comment]
> Hi! Is Dropbox linked to the app folder of full dropbox? If it’s in app folder mode, this can be the reason

Sorry I did miss your reply and honestly wasn't sure what you meant with your question.  Either way, I'm not really using Keeweb anymore anyway so happy to leave this closed.

Huge thanks for your help
Fotis
