### ISSUE TITLE
Automatic update does not work on macOS

### ISSUE THREAD

**Issue by willvousden** [keeweb/keeweb#1792]
**Describe the bug**
When I allow Keeweb to download an update and attempt to apply it, it just fails with an AppleScript error. Instead, I have to manually delete it (providing my password) and download the DMG afresh.

I suspect this is because the Keeweb app is locked and writable only by an admin account (therefore requiring password).

**To Reproduce**
1. Click "Download update and restart"
2. Application closes
3. Modal dialog appears with error message

**Expected behavior**
Application updates and restarts.

**Screenshots**

Here is the sequence of events. The AppleScript editor window is what I see if I click "Edit" on the modal.

<img width="1112" alt="Screenshot 2021-04-25 at 14 30 57" src="https://user-images.githubusercontent.com/152388/115993504-50f75100-a5d3-11eb-8e26-1afc08ba142c.png">
<img width="372" alt="Screenshot 2021-04-25 at 14 25 29" src="https://user-images.githubusercontent.com/152388/115993503-50f75100-a5d3-11eb-9e76-98fe1638d0c2.png">
<img width="812" alt="Screenshot 2021-04-25 at 14 32 11" src="https://user-images.githubusercontent.com/152388/115993501-4e94f700-a5d3-11eb-938e-1bd535f091c7.png">

**Environment**
macOS 11.2.3

**Logs**
The error is in the installer, not the application. I don't know how to get such logs (if there are any at all).

**Comment by antelle** [comment]
Hi! That's probably #1767, updating from v1.17.6 should work, but for now there's no way to test it because it's the latest release. Let's see if this releases fixes the issue.
