### ISSUE TITLE
Changes port HTTPS  

### ISSUE THREAD

**Issue by anglsls** [keeweb/keeweb#1793]
Hi!!!

I change the HTTPS port (443) to port 2222.
When I tried to use webdav, the following happened:
The path "https: //ip/webdav/archivo.kdbx" showed the error "Error: network error"
then I change the path to "https: // ip: 2222 / webdav / file.kdbx", but the error now is "No found the file"

What is the correct path?

Thanks for your attention

**Comment by antelle** [comment]
Hi! The port will work exactly the same way as in browser, so the way you did it is correct.  
Did you put it literally like this, with spaces? This won't work.

To debug why it doesn't work, open Network panel in your browser devtool and it will probably show what's wrong.

**Comment by anglsls** [comment]
Hi!!! 

I follow the same problem ¿Can it be for cors?

![image](https://user-images.githubusercontent.com/81113999/117175759-cc57c000-ad94-11eb-961e-6dcbf4488a4c.png)

**Comment by antelle** [comment]
It is not cors, it is HTTP. KeeWeb does not and will not work without HTTPS.

**Comment by antelle** [comment]
But actually, it may be CORS as well, you can check in Network.
