### ISSUE TITLE
[Question] Should the api key on self hosted keeweb not be hidden?

### ISSUE THREAD

**Issue by MrAdityaAlok** [keeweb/keeweb#1797]
I  hosted the keeWeb on gh-pages but the config.json file is publically visible containing my api key's.
How should I hide it?

**Comment by antelle** [comment]
Hi! To hide the config, you need to put it behind of authentication, then you will authenticate to load KeeWeb and config as well.

**Comment by MrAdityaAlok** [comment]
>Hi! To hide the config, you need to put it behind some sort of authentication, then you will authenticate to load KeeWeb and config as well.

Can you provide some examples..........How should I do it on gh-pages?

**Comment by antelle** [comment]
Not on GitHub, you need to host it somewhere else for this.
