### ISSUE TITLE
Microsoft OneDrive support: instructions are obsolete in Wiki

### ISSUE THREAD

**Issue by bouil** [keeweb/keeweb#1800]
In the wiki https://github.com/keeweb/keeweb/wiki/Dropbox%20and%20GDrive, the instructions about adding OneDrive support are obsolete.

The link provided ( https://apps.dev.microsoft.com/#/appList )  displays the following information :

"Starting February 2021, you can no longer create new Live SDK applications here. The Azure portal now supports applications for personal Microsoft accounts. We recommend registering new applications there."

I've tried without success to setup the API from the new config page. 

Do you know how we can make this work?

Thanks.

**Comment by antelle** [comment]
Every year, same story: OneDrive instructions are outdated 🤦 
I’ll update them today of course, thanks.

**Comment by bouil** [comment]
Thank you very much, and good luck with that.
I've tried around and couldn't find any combination of parameters in Azure portal that worked.

**Comment by antelle** [comment]
Done: https://github.com/keeweb/keeweb/wiki/Dropbox-and-GDrive#onedrive

**Comment by bouil** [comment]
Thanks. One question though: in the Azure portal, I cannot add the permission Directory.Read.All, the checkbox is disabled. Do you know how to enable it? Does it matter for the configuration?

![image](https://user-images.githubusercontent.com/557434/117541430-1b5f5880-b014-11eb-8c6b-446c066a8e3d.png)

**Comment by antelle** [comment]
You don't need this permission for KeeWeb

**Comment by bouil** [comment]
OK, it works now. 
I had to set the audience to "All Microsoft account users" , because using only "Personal accounts" leads to the following error in the web console :

`OAuth error invalid_request The request is not valid for the application's 'userAudience' configuration. In order to use /common/ endpoint, the application must not be configured with 'Consumer' as the user audience. The userAudience should be configured`

![image](https://user-images.githubusercontent.com/557434/117543278-654c3c80-b01c-11eb-8316-eea8bbd0f092.png)


Thank you!

**Comment by antelle** [comment]
This setting depends on your config yes
