### ISSUE TITLE
Unable to unlock my databse with 1.8.1

### ISSUE THREAD

**Issue by gynet** [keeweb/keeweb#1802]
**Describe the bug**
I am using Windows 10, and upgrade to 1.8.1,  not able to unlock my database now

see this error in dev console

![image](https://user-images.githubusercontent.com/2174522/117552032-f233cd80-affd-11eb-8499-926a0ac5747e.png)

**Comment by gynet** [comment]
I am using portable binaries, i also retried download and replace KeeWeb, but seem it remains

also saw this error in dev console before the error above

![image](https://user-images.githubusercontent.com/2174522/117552185-bf3e0980-affe-11eb-9ad6-46aad78f5f0e.png)
also see this error

**Comment by antelle** [comment]
I can reproduce the keyfile error, will fix it soon.  
About the second one, are you using KeeWebHttp plugin by any chance?

**Comment by antelle** [comment]
Ok, this is expected, KeeWebHttp will break in v1.18, I'll remove this plugin from the store.

**Comment by antelle** [comment]
Fixed, it's [building](https://github.com/keeweb/keeweb/actions/runs/823817783)... When it's released, please re-add your keyfile, then it should work.

**Comment by antelle** [comment]
I'm afraid, I can't release it today: Apple's notarization service returns an error 😢

**Comment by gynet** [comment]
@antelle that's fine, I can use the old version for now, thanks for working on the fix

**Comment by antelle** [comment]
https://developer.apple.com/system-status/
>  App Store Connect App Processing - Outage

I'll build it tomorrow morning then.

**Comment by antelle** [comment]
reopening for visibility

**Comment by antelle** [comment]
It's released 🎉 
And in the next version I'll focus on preventing issues like this from happening.

**Comment by gynet** [comment]
@antelle Thanks for the quick fix. I just verified it's working now, and the browser extension also works with my Firefox. I will test furter later.
