### ISSUE TITLE
KeeWeb Connect extension & Firefox Testing Results

### ISSUE THREAD

**Issue by gynet** [keeweb/keeweb#1804]
Thanks for the great work for the KeeWeb Connect, and the basic function like filling user name and password are working fine on Firefox, and i love using it. 

Here are some edge cases or issues I found during my testing with Firefox  

- [ ] the one time password seems not working. 
>  example : otpauth://totp/GitHub:user1?secret=xxxx&issuer=GitHub
- [ ] some web site ignore the characters filled by KeeWeb Connect
> example: https://leetcode.com/accounts/login, the website ignore the user name filed by the extension. i guess it is because usually many websites detect the user typying or focus events, and they usually ignore any character filled before any user event getting triggerred. It might be better the keeweb connect extension can simulate or behaviors more like "real" user typing behaviors instead of changing the text content directly

web mode only issues: 
- [ ] After clicking on "connect to keeweb", it redirect me to https://app.keeweb.info, which is expected, however, after 1 second, it redirects me back to the extension option page before I getting a chance to type my password
- [ ] The "other option" can fill the target web site's field, but it does not redirect me back to the target web site, it stays at https://app.keeweb.info

**Comment by antelle** [comment]
Hi 👋 
Thanks for testing the early version, as usual!

> the one time password seems not working

✅  I can repeat this, thanks! I'm using OTP's from a yubikey, so haven't noticed that OTP stored in the db are not working. A fix is coming soon...

> some web site ignore the characters filled by KeeWeb Connect

✅  Also can repeat. I assume, we need to generate `change` and `input` events, should be easy to fix.

> After clicking on "connect to keeweb", it redirect me to https://app.keeweb.info, which is expected, however, after 1 second, it redirects me back to the extension option page before I getting a chance to type my password

🚫  Does it show "Connected"? In this case it's fine, you're not supposed to open the db at this stage. It just verifies the possibility of sending messages to a KeeWeb tab. You can also skip the connection step and just trigger auto-fill from a website, in this case KeeWeb tab remains open and you can unlock the db.

> The "other option" can fill the target web site's field, but it does not redirect me back to the target web site, it stays at https://app.keeweb.info

✅  Same, thanks! Fixing it...

**Comment by gynet** [comment]
For the third one, it shows "connected" after I manually switch back to https://app.keeweb.info to unlock the db. 
The use case is: 
1. The database is locked, and the user go to the extension option page, 
2. Chose web-only & click "connect to keeweb"
3. the extension redirect to https://app.keeweb.info, expected
4. user see the database is locked, so try to type he/her password, but before the user can do that, the browser auto switch back to the  extension option page, so the user has to re-select the https://app.keeweb.info tab to unlock the databasee

Another UI style thing: the selecting entry panel, the entry seems too big for me on the browser 
![image](https://user-images.githubusercontent.com/2174522/117564826-d282c080-b062-11eb-9181-4f71ec64f8f8.png)

**Comment by antelle** [comment]
Fixed the table size in Firefox, thanks again!

`1.` you can skip this step, then it will connect automatically and leave the tab open
`4.` ideally we shouldn't switch to the tab at all, but it causes issues because the tab is not focused and the connection times out because of stricter limitations, so it behaves a bit strange yes, I'll think what to do with it, maybe we should show a message like "connecting to the extension, please wait"

**Comment by antelle** [comment]
[Released](https://github.com/keeweb/keeweb-connect/releases/latest) the extension with fixes, for Firefox it will be available in the store soon.

OTP fix in KeeWeb is committed, but a release is coming later today, maybe there will be something else to fix.

**Comment by antelle** [comment]
The fix is rolled out
