### ISSUE TITLE
filters for auto-type inctroduces 'clicks'

### ISSUE THREAD

**Issue by jivarson** [keeweb/keeweb#1805]
The new filters in 1.18 for the autotype selection screen forces me to untick 'Title' very often.
It works as dev. intended but causes more interaction.
Prior to 1.18, I used AutoType for everything and just typed three characters or something for stuff like adhoc SSH-sessions and other apps where Title doesnt reflect the entry to show the right entry.

now I have to untick Title with mouse.

Anyway to;
A. Persistently remember the state of the Title-filter (ticked/unticked)
B. Allow app-setting to show/hide those advanced filters in whole?
![image](https://user-images.githubusercontent.com/25992469/117570361-10ff9600-b0ca-11eb-84cb-2c9d1f412eb0.png)

**Comment by antelle** [comment]
Hi! Makes sense, it should work this way:
1. if something is found by title – the filter remains
2. nothing found – the filter is unchecked, all entries are displayed

**Comment by jivarson** [comment]
Didn't think of that option, but yes, thats probably the smartest fix.
If ones is actively searching for an entry based on its title there's search-functionality in the main app anyway

**Comment by antelle** [comment]
Just released a new version with this fix: https://github.com/keeweb/keeweb/releases/latest

**Comment by jivarson** [comment]
> Just released a new version with this fix: https://github.com/keeweb/keeweb/releases/latest

Thank you!
Works perfect.
