### ISSUE TITLE
Update issue => minimise app instead of close #1757

### ISSUE THREAD

**Issue by LiloBzH** [keeweb/keeweb#1807]
Hi
Juste for information (and sorry for that !)
Update today v1.18.2 to v1.18.3

Same problem

app is reducing instead of closing to upgrade

_Originally posted by @LiloBzH in https://github.com/keeweb/keeweb/issues/1757#issuecomment-835806800_

**Comment by antelle** [comment]
Not good, it worked for me when I tested the updater, but maybe there's something else. You updated from the app, not by downloading a new installer, right?

**Comment by LiloBzH** [comment]
updated from the app

**Comment by LiloBzH** [comment]
for next update, do you want i test with the download file ? (or it's not a good test ?)

**Comment by antelle** [comment]
It should be fine from within the app, this is more problematic compared to downloading an installer because the app needs to launch the updater and then close itself. But it should work of course.

**Comment by antelle** [comment]
It's possible that it's fixed with #1811

**Comment by LiloBzH** [comment]
it's ok now

thanks ;)

**Comment by antelle** [comment]
Great, thanks!
