### ISSUE TITLE
LDAP Integration

### ISSUE THREAD

**Issue by luigiBaldanza** [keeweb/keeweb#1809]
I see that the LDAP integration is necessary to manage many users and permissions of access in big business.

Is any plan to build this feature?

**Comment by antelle** [comment]
Hi! What kind of integration?

**Comment by luigiBaldanza** [comment]
Yes, for individual entries, build a access layer based on integration with Active Directory.

**Comment by antelle** [comment]
This won't be possible unfortunately because everything is stored in one file, so you can't implement access control per entry without changing format.
