### ISSUE TITLE
Unable to connect

### ISSUE THREAD

**Issue by youhost-joseph** [keeweb/keeweb#1810]
Hello, thank you very much for this software.
Unfortunately I am unable to connect:
```
Connection state: Error
Cannot connect to KeeWeb, please check if KeeWeb is open and browser integration is enabled in settings.
```
- osx 10.12
- KeeWeb v1.18.3 (337ef44, 2021-05-09)
- firefox 88.0.1 (64-bit)
- firefox KeeWeb Connect enabled in settings/browser

**Comment by youhost-joseph** [comment]
Thank you very much! Do you confirm I can close the issue?

**Comment by RaimonTr** [comment]
Hello 

First of all, excuse me if it is not the right place to comment this.

I had also many problems to make work the new version with 10.14.6 Mojave with patcher by dosdude1.

- The only browser that worked at first was Brave.
- For Chrome, I needed to create the file net.antelle.keeweb.keeweb_connect.json in /Library/Google/Chrome/NativeMessagingHosts/
- For Edge, the Edge extension (nmggpehkjmeaeocmaijenpejbepckinm) didn't work for me, then I installed the Chrome extension (pikpfmjfkekaeinceagbebpfkmkdlcjk) and it just worked.

Thanks for the software.

**Comment by antelle** [comment]
@RaimonTr 

It's good that you figured out how to make it work!

For Chrome, when you enable the support in KeeWeb, didn't it create the file you mentioned?

For Edge, I see that that the extension is still "In review", the one published is quite old.

**Comment by RaimonTr** [comment]
Hi antelle

"For Chrome, when you enable the support in KeeWeb, didn't it create the file you mentioned?"
It created the file in ~/Library/Application Support/Google/Chrome/NativeMessagingHosts/ BUT I use Chrome Beta (normal version of Chrome isn't installed anymore) so maybe  the file should have been created in ~/Library/Application Support/Google/Chrome Beta/NativeMessagingHosts.

Sorry for the delay in answer you.

Thanks again for your software.

**Comment by antelle** [comment]
In this case you need to install manually yes.
