### ISSUE TITLE
Cannot load custom icons

### ISSUE THREAD

**Issue by micktg** [keeweb/keeweb#1813]
Version 1.18.3
Windows x64

KeeWeb is unable to load an icon via web address (I guess a bug on its own) as well as saving a custom icon.
If I load a custom icon, it is correctly shown in the app, but as soon as I save the entry, I only see the standard icon.

![Screenshot 2021-05-11 173948](https://user-images.githubusercontent.com/278107/117844385-ece5b580-b27f-11eb-8a58-91de59a23796.jpg)
Icon loaded and click on icon to set icon to entry

![Screenshot 2021-05-11 174054](https://user-images.githubusercontent.com/278107/117844582-14d51900-b280-11eb-8ac9-dd6af6b13fcd.jpg)
KeeWeb shows standard logo.

I have tested several icons as well as several image types (jpg, png, svg). Its always the same behavior.
I could not see anything helpful in the logs, so unfortunately I can't provide any more useful information

**Comment by antelle** [comment]
Thank you! No further information needed, it will be fixed soon!

**Comment by antelle** [comment]
Now this should work

**Comment by micktg** [comment]
Thanks for fixing this!
But there is a behavior with SVG that does not seem to be correct.

When I select the following SVG: (sorry, GitHub does not support SVG upload)
https://finanzsache.com/wp-content/uploads/2019/06/DKB-Logo.svg

It is shown like this in preview (which is correct)
![1](https://user-images.githubusercontent.com/278107/118040971-87bebc80-b372-11eb-9cfd-43c876dbc153.jpg)

But as soon as I select it is stretched like this
![2](https://user-images.githubusercontent.com/278107/118041016-973e0580-b372-11eb-98fa-91227cb0e17a.jpg)

I am not sure if this behavior is new.

**Comment by antelle** [comment]
SVG were never supported very well. Also I'm not sure if they're supported across other forks. Eventually we should fix it of course.
