### ISSUE TITLE
Small Improvement for Auto-Type selection screen

### ISSUE THREAD

**Issue by jivarson** [keeweb/keeweb#1815]
Fix #1805 improved the Auto-Type filter behaviour in that it lists all entries should the initial result-set be empty.
I however from time to time need to enter items from different entries in the same situation, so I still have to untick the Title-filter with the mouse, prior to the advanced filtersets in 1.18 i would just type to land right.

Would it be possible to 
-  Add a hotkey to the Auto-Type selection screen like **Ctrl+A** to clear all filters, the same behaviour as when the resultset from Title is empty?
or
- Add an option to disable the advanced\finegrained filters in Settings?

**Comment by antelle** [comment]
Also related: #1814

**Comment by jivarson** [comment]
I'd conqur that an option would be the nice, sort of like mentioned in #1814 .
In my case I'd just prefer the former 'fuzzy' filter, so a "Hide filter options" in Settings (if you'd want to show the new filter-options by default) would do it. Here It's mostly about getting rid of the need for mouseclicks in the flow.

**Comment by jivarson** [comment]
Relates \ continues in #1814
