### ISSUE TITLE
V1.18 draws a blanc page on Edge Android

### ISSUE THREAD

**Issue by Stephan-P** [keeweb/keeweb#1816]
Keeweb app (app.keeweb.info) fails to load properly in the Android Edge browser.

- No error message
- Just a blanc page

This started a few days ago with v1.18.0 and continues through 1.18.4.
No problems with my other Android browsers Vivaldi and DuckDuckGo

Android 10
Edge 46.03.4.5155
Vivaldi Snapshot 3.9.2991.3
DDG browser 5.85.3

**Comment by antelle** [comment]
Hi! 👋 

Edge doesn't seem to work on an emulator at all, so I'll need your help. Could you please connect devtools to this browser and check what it prints? Probably there's an error.

**Comment by Stephan-P** [comment]
Hi Antelle, 
I'm all to happy to oblige, but I couldn't find information on 'connecting devtools'. 
How do I do this?

**Comment by antelle** [comment]
I have no idea how to do it on Android. If you google "Android devtools edge", there are some guides.

**Comment by Stephan-P** [comment]
I have no idea either, yet.
But I've done some more
- clear Edge app cache and local storage (no succes) 
- sent in an issue report with Microsoft Edge

I'll try and see if I can find something of a log file to send to you

**Comment by antelle** [comment]
I don't think that deleting cache will help.  
Issue report in Microsoft Edge won't help either because it's something that we're using that's not supported in Edge.

**Comment by Stephan-P** [comment]
Uncaught SyntaxError: Unexpected token '?'
But I can't find which of the 4000+ question marks that would be.
![image](https://user-images.githubusercontent.com/10008599/118099033-fb91b100-b3d4-11eb-81b1-fe10aaea4996.png)

**Comment by antelle** [comment]
I think I know what it is, but let's validate. What if you paste this to Console?
```
window?.x
```

**Comment by Stephan-P** [comment]
That results into this:

VM22:1 Uncaught SyntaxError: Unexpected token '.'

**Comment by antelle** [comment]
Hehe. What to do with it though...
Does it report which version of Blink / V8 it's running? Something like chrome://version/
Because probably there are other features of modern JS that are not supported there, and I'm not sure how I can test this without access to this browser.

**Comment by Stephan-P** [comment]
![image](https://user-images.githubusercontent.com/10008599/118099890-20d2ef00-b3d6-11eb-93a3-f349f2681247.png)

**Comment by Stephan-P** [comment]
Do you need any other debug information for now?

**Comment by antelle** [comment]
V8 7.7 🤮 
No, it's clear, thank you.

**Comment by Stephan-P** [comment]
Thank you, for I've learned a new thing today.

**Comment by antelle** [comment]
fixed, updated the [beta](https://beta.keeweb.info)

**Comment by Stephan-P** [comment]
Fix confirmed
![Screenshot_20210513-110718_Edge](https://user-images.githubusercontent.com/10008599/118104551-92fa0280-b3db-11eb-9cba-7f3a5e4cd0ae.jpg)

**Comment by antelle** [comment]
Thank you for your help! I'll make a release with it soon.
