### ISSUE TITLE
Cannot connect to KeeWeb

### ISSUE THREAD

**Issue by mpatca** [keeweb/keeweb#1818]
Hello, although KeeWeb is open and browser integration is enabled, no connection is established. Maybe the screenshot helps with troubleshooting.
![Image 1](https://user-images.githubusercontent.com/82024822/118136811-d026ba80-b404-11eb-96c7-b46f6b679497.png)

**Comment by antelle** [comment]
Hi! Which OS is that?

**Comment by mpatca** [comment]
Sorry, I should have specified that directly: Windows 10 Education 20H2.

**Comment by antelle** [comment]
What happens if you run this in Command Prompt:
```
wmic process where ProcessId=1 get ProcessId,ParentProcessId,ExecutablePath /format:value
```

**Comment by mpatca** [comment]
![Image 5](https://user-images.githubusercontent.com/82024822/118191143-6d551380-b444-11eb-85d4-0a7e95004518.png)

**Comment by antelle** [comment]
That's interesting. Now if you repeat the same in KeeWeb and run this command for a PID that you see in KeeWeb devtools - does it print the same information?

**Comment by mpatca** [comment]
If I understood the instruction, here is the result. Maybe the first error message also has a meaning?
![Image 1](https://user-images.githubusercontent.com/82024822/118317797-c9796f80-b4f8-11eb-93f2-7284c7b7337c.png)

**Comment by antelle** [comment]
That's a bit different. I wanted you to run this in the command line, not in the devtools. But with the PID that you see in devtools.

**Comment by mpatca** [comment]
No problem. I tried several times to connect the browser plug-in and put the respective PID displayed in the Dev Tools into the CMD, but only took a screenshot of it once, because the result was always the same.
![Image 2](https://user-images.githubusercontent.com/82024822/118320164-20cd0f00-b4fc-11eb-94e3-c7748da9ba12.png)
![Image 3](https://user-images.githubusercontent.com/82024822/118320181-2591c300-b4fc-11eb-879a-a79393031582.png)

**Comment by antelle** [comment]
That's interesting! Does a process with this PID exist in task manager?

**Comment by mpatca** [comment]
No. The PID seen in the Devtools are not present in the Windows Task Manager.

**Comment by antelle** [comment]
Which browser is it?

**Comment by mpatca** [comment]
Google Chrome 90.0.4430.212 64-Bit

**Comment by antelle** [comment]
Interesting, so it launches a process that disappears. We should probably show something like "an extension from unidentified app is trying to connect".
I wonder why this happens, it seems to be kind of edge case that happens in a specific setup. Anyway, the next version will have it fixed.

**Comment by mpatca** [comment]
Thank You!

**Comment by antelle** [comment]
Fixed it, now if you upgrade KeeWeb, it should show "Unidentified browser"
