### ISSUE TITLE
OneDrive Sync error netWork error

### ISSUE THREAD

**Issue by shieher-Xie** [keeweb/keeweb#1821]
![image](https://user-images.githubusercontent.com/57655145/118434231-4847f580-b70f-11eb-91c1-664b566406c5.png)

KeeWeb v1.17.6 (8efee7d, 2021-04-09)
Environment: electron v12.0.0
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) KeeWeb/1.17.6 Chrome/89.0.4389.69 Electron/12.0.0 Safari/537.36

**Comment by antelle** [comment]
A log from devtools, please.

**Comment by antelle** [comment]
please reopen with more info. not actionable now.

**Comment by shieher-Xie** [comment]
I think I have found the cause of the problem. The cause of the problem is that a single record is too large and cannot be submitted. The reason is that I added pictures and other files to the record, which caused the record to be too large to be submitted. It has been tested, please take a look Can you fix it or tell me what to do to solve this problem.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "keeweb/keeweb"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月18日(星期二) 凌晨0:46
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [keeweb/keeweb] OneDrive Sync error netWork error (#1821)





 
Closed #1821.

**Comment by shieher-Xie** [comment]
I think I have found the cause of the problem. The cause of the problem is that a single record is too large and cannot be submitted. The reason is that I added pictures and other files to the record, which caused the record to be too large to be submitted. It has been tested, please take a look Can you fix it or tell me what to do to solve this problem.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "keeweb/keeweb"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月18日(星期二) 凌晨0:46
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [keeweb/keeweb] OneDrive Sync error netWork error (#1821)





 
please reopen with more info. not actionable now.

**Comment by shieher-Xie** [comment]
I think I have found the cause of the problem. The cause of the problem is that a single record is too large and cannot be submitted. The reason is that I added pictures and other files to the record, which caused the record to be too large to be submitted. It has been tested, please take a look Can you fix it or tell me what to do to solve this problem.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "keeweb/keeweb"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月17日(星期一) 中午1:31
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [keeweb/keeweb] OneDrive Sync error netWork error (#1821)





 
A log from devtools, please.

**Comment by shieher-Xie** [comment]
log
[INFO ] 2021-05-18T13:11:14.318Z [storage-onedrive] HTTP request PUT https://graph.microsoft.com/v1.0/me/drive/root:/shieberPW.kdbx:/content[ERROR] 2021-05-18T13:11:14.919Z [storage-onedrive] HTTP error PUT https://graph.microsoft.com/v1.0/me/drive/root:/shieberPW.kdbx:/content Error: net::ERR_CONNECTION_RESET[ERROR] 2021-05-18T13:11:14.919Z [storage-onedrive] Save error /drive/root:/shieberPW.kdbx network error 601ms[INFO ] 2021-05-18T13:11:14.919Z [sync:shieberPW] Error saving data to storage[INFO ] 2021-05-18T13:11:14.920Z [sync:shieberPW] Sync finished network error









------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "keeweb/keeweb"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月18日(星期二) 凌晨0:46
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [keeweb/keeweb] OneDrive Sync error netWork error (#1821)





 
please reopen with more info. not actionable now.

**Comment by antelle** [comment]
That's #875. For now there's no way to fix it.
