### ISSUE TITLE
Browser Autofill wiki update for clarity

### ISSUE THREAD

**Issue by ryman1** [keeweb/keeweb#1823]
I've made a minor update to the documentation for the native app manifests to make it more clear where the reader should look if they don't know where to store the json file. 
My version: https://github.com/ryman1/keeweb-wiki/blob/main/Browser-AutoFill.md

Your file to merge into: https://github.com/keeweb/keeweb/wiki/Browser%20AutoFill

If there's something I can do better to make this easier to merge, let me know. This is my first time trying to help with a github wiki.

**Comment by antelle** [comment]
Hi! Thanks! Updated it
