### ISSUE TITLE
Tray icon more than one. Ubuntu 20.04 LTS

### ISSUE THREAD

**Issue by DimZ2** [keeweb/keeweb#1826]
When I launch KeeWeb from the tray icon or click the icon in the application menu and I close the window, the tray icon is duplicated
![image](https://user-images.githubusercontent.com/74352363/119186785-2ccb4a80-ba81-11eb-8315-0e824ab15def.png)

**Comment by antelle** [comment]
Not possible to fix unfortunately: #1181
