### ISSUE TITLE
Connection impossible between the client and the extension

### ISSUE THREAD

**Issue by Drarig29** [keeweb/keeweb#1827]
**Describe the bug**
Even with the KeeWeb Connect checkbox enabled for Chrome, the connection between KeeWeb and the browser extension doesn't work.

**Expected behavior**
The connection should work just fine.

**Environment**
```
KeeWeb v1.18.6 (070573e, 2021-05-19)
Environment: electron v12.0.7
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) KeeWeb/1.18.6 Chrome/89.0.4389.128 Electron/12.0.7 Safari/537.36
```

I just switched to Manjaro and I tested two AUR packages (`keeweb` and `keeweb-desktop-bin`). Same problem with both of them.

**Logs**

This is from the Background page of the extension.
![image](https://user-images.githubusercontent.com/9317502/119225604-e9b2bb00-bb04-11eb-9d13-c56dc667475e.png)

And there is no error in the client devtools.

**Comment by antelle** [comment]
Hi! Do you see anything in KeeWeb logs? Looks like it disconnects after connection

**Comment by Drarig29** [comment]
The only relevant information is this line:

```
2021-05-22T12:09:29.855Z [browser-extension-connector] Started
```

That's the only line containing `browser-extension-connector`.

Maybe I can check if a certain process is running... but I don't know what to look for.

**Comment by antelle** [comment]
Let's try launching `keeweb-native-messaging-host` manually. It should be located in the same directory as `keeweb`. Launch it like this:
```
keeweb-native-messaging-host keeweb-connect@keeweb.info
```

It won't product any output, but KeeWeb should show something about a new connection in its logs.

**Comment by Drarig29** [comment]
Nice! Still no connection in the extension though.

![image](https://user-images.githubusercontent.com/9317502/119226440-66479880-bb09-11eb-9d27-a4564f6e0822.png)

**Comment by antelle** [comment]
Interesting. Maybe something is not good with native messaging manifest setup? https://github.com/keeweb/keeweb/wiki/Browser%20AutoFill#other-browsers

**Comment by Drarig29** [comment]
I'm using Brave and I chose Chrome because they are both based on Chromium, but it worked fine on Windows so I don't think it's the issue.

**Comment by antelle** [comment]
I mean, go through the setup described on that page. For Brave, you need to create a manifest manually.

**Comment by antelle** [comment]
Now I think I understand what happens. The manifest is not created, so the browser can't connect to it. If you complete steps described on that page, it should work.

**Comment by Drarig29** [comment]
> Now I think I understand what happens. The manifest is not created, so the browser can't connect to it. If you complete steps described on that page, it should work. Enabling "Chrome" in KeeWeb creates a manifest for you, but only for Chrome.

Oh okay! Now I see what this little checkbox does :)

**Comment by antelle** [comment]
Yes, that's exactly manifest creation / deletion. If you check "other browsers", there will be an `i` button that will open the page I shared above.

**Comment by Drarig29** [comment]
It's weird though, I didn't have to make a Brave manifest on Windows.

**Comment by Drarig29** [comment]
It does work now, thanks :)

**Comment by antelle** [comment]
It's because https://github.com/brave/muon/commit/eda99ede604a3e6d6fb9f843aa81c23617ce0922 
🤣  they seem to just read Chrome's settings from the registry

**Comment by Drarig29** [comment]
Oh okay 😄
