### ISSUE TITLE
KdbxError: Error FileCorrupt: no kdf uuid

### ISSUE THREAD

**Issue by guifsdev** [keeweb/keeweb#1828]
**Describe the bug**
I started having this issue today. I normally store my kdbx file in Google Drive, but starting today it will not open the database anymore and the following error occurs:
![Capturar](https://user-images.githubusercontent.com/22643002/119271330-804fac80-bbd7-11eb-8f0b-9615a9b0b6bf.JPG)

I'm on a dual boot machine (Win7 and Ubuntu) and I checked that it only occurs in Windows while in Ubuntu it opens the database as expected.

Before testing in Ubuntu I tried to get an older version of the file from GDrive version history (from a month ago) and used that instead of my updated database thinking that it had something to do with GDrive. However the same error pops up. For every version of the database I use btw.

In windows I also tried opening the database file in KeePass client which gives me the error:
![Capturar2](https://user-images.githubusercontent.com/22643002/119271651-cbb68a80-bbd8-11eb-904b-a87a314d3ea7.JPG)

The last two lines reads:
```
"Value cannot be null.
Parameter name: value"
```

I also tried the Import/Recover functionality from an empty database but it does not recover anything. All I get is an empty database.  

**To Reproduce**

**Expected behavior**
Database file should open as always.

**Environment**
KeeWeb v1.18.6 (070573e, 2021-05-19)
Environment: web
User-Agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36

**Does it happen on Demo or New database? **
No.

**Kdbx File**
If you have a test db without your personal data, please attach it.

**Logs**
2021-05-23T18:13:08.493Z [settings-manager] Theme changed dark
(index):1 2021-05-23T18:13:08.561Z [start-profiler] App started in 670ms: fetching=10ms, pre-init=434ms, loading modules=115ms, document ready=45ms, creating app model=4ms, loading configs=1ms, initializing modules=1ms, loading remote config=3ms, checking features=1ms, initializing storage=0ms, starting usb=0ms, first view rendering=65ms, app ready event=0ms
(index):1 2021-05-23T18:13:09.073Z [browser-extension-connector] Started
(index):1 2021-05-23T18:13:09.073Z [updater] Service worker registered
(index):1 2021-05-23T18:13:11.416Z [storage-gdrive] List
(index):1 2021-05-23T18:13:11.416Z [storage-gdrive] HTTP request GET https://www.googleapis.com/drive/v3/files?fields=files(id%2Cname%2CmimeType%2CheadRevisionId)&q=trashed%3Dfalse%20and%20%22root%22%20in%20parents&pageSize=1000&includeItemsFromAllDrives=true&supportsAllDrives=true
(index):1 2021-05-23T18:13:11.941Z [storage-gdrive] HTTP response 200
(index):1 2021-05-23T18:13:11.941Z [storage-gdrive] Listed 526ms
(index):1 2021-05-23T18:13:21.273Z [open:cofre] File open request
(index):1 2021-05-23T18:13:21.273Z [open:cofre] Open file from storage gdrive
(index):1 2021-05-23T18:13:21.274Z [open:cofre] Load from storage
(index):1 2021-05-23T18:13:21.274Z [storage-gdrive] Stat 1zcEsuvCE67NR3aqCPOi4VXi_T3aYtY9K
(index):1 2021-05-23T18:13:21.274Z [storage-gdrive] HTTP request GET https://www.googleapis.com/drive/v3/files/1zcEsuvCE67NR3aqCPOi4VXi_T3aYtY9K?fields=headRevisionId&includeItemsFromAllDrives=true&supportsAllDrives=true
(index):1 2021-05-23T18:13:21.470Z [storage-gdrive] HTTP response 200
(index):1 2021-05-23T18:13:21.470Z [storage-gdrive] Stated 1zcEsuvCE67NR3aqCPOi4VXi_T3aYtY9K 0B9ze8F1EXDkLSDJIcTRlVnE0UUdxWkg4RjViam5uTGxPSGVvPQ 196ms
(index):1 2021-05-23T18:13:21.471Z [storage-gdrive] Load 1zcEsuvCE67NR3aqCPOi4VXi_T3aYtY9K
(index):1 2021-05-23T18:13:21.471Z [storage-gdrive] HTTP request GET https://www.googleapis.com/drive/v3/files/1zcEsuvCE67NR3aqCPOi4VXi_T3aYtY9K/revisions/0B9ze8F1EXDkLSDJIcTRlVnE0UUdxWkg4RjViam5uTGxPSGVvPQ?alt=media
(index):1 2021-05-23T18:13:22.322Z [storage-gdrive] HTTP response 200
(index):1 2021-05-23T18:13:22.323Z [storage-gdrive] Loaded 1zcEsuvCE67NR3aqCPOi4VXi_T3aYtY9K 0B9ze8F1EXDkLSDJIcTRlVnE0UUdxWkg4RjViam5uTGxPSGVvPQ 852ms
(index):1 2021-05-23T18:13:22.323Z [open:cofre] Open file from content loaded from storage
(index):1 2021-05-23T18:13:22.328Z [file] Error opening file FileCorrupt Error FileCorrupt: no kdf uuid KdbxError: Error FileCorrupt: no kdf uuid
    at Object.t.encrypt (https://app.keeweb.info/:1:1441033)
    at https://app.keeweb.info/:1:1475930
r.error @ (index):1
(anonymous) @ (index):1
Promise.catch (async)
open @ (index):1
u @ (index):1
openFileWithData @ (index):1
(anonymous) @ (index):1
success @ (index):1
(anonymous) @ (index):1
(anonymous) @ (index):1
load (async)
_httpRequestWeb @ (index):1
_httpRequest @ (index):1
_xhr @ (index):1
(anonymous) @ (index):1
success @ (index):1
(anonymous) @ (index):1
(anonymous) @ (index):1
load (async)
_httpRequestWeb @ (index):1
_httpRequest @ (index):1
_xhr @ (index):1
(anonymous) @ (index):1
_oauthAuthorize @ (index):1
stat @ (index):1
load @ (index):1
a @ (index):1
openFileFromStorage @ (index):1
openFile @ (index):1
(anonymous) @ (index):1
requestAnimationFrame (async)
(anonymous) @ (index):1
requestAnimationFrame (async)
afterPaint @ (index):1
openDb @ (index):1
inputKeydown @ (index):1
eventListener @ (index):1
e @ (index):1
(index):1 2021-05-23T18:13:22.329Z [open-view] Error opening file KdbxError: Error FileCorrupt: no kdf uuid
    at Object.t.encrypt (https://app.keeweb.info/:1:1441033)
    at https://app.keeweb.info/:1:1475930

**Comment by antelle** [comment]
Hi! I see that KeeWeb tells that the file is now corrupted, the same as in KeePass. So it's ok here I assume. 
The question, however, is how did you get into this state? What was the last thing that happened to this file before it became corrupted?

**Comment by guifsdev** [comment]
Hi @antelle and thanks for the quick response.
I usually open the file in KeeWeb to check some credentials, do some changes and Ctrl + S and only.
I did not do any major change in the file recently.

All I can say is that I did run CCleaner yesterday which freed a good amount of space (around 12GB) and solved some faulty registry entries. This is my only guess as to why  it started happening, because before that I could open the file without any problems.

**Comment by antelle** [comment]
Maybe. I don't know how it works, it's possible that it has corrupted the file.  
So, regarding the current state, you should restore from a backup because the file is now broken. It's unlikely that you will be able to open or recover this file. If you're interested about its contents, and you're familiar with node.js tooling, you can try checking the contents of the binary header inside using for example this tool: https://github.com/keeweb/kdbxweb#tools

Since it seems that it's not KeeWeb that broke the file, we can't do anything about it in this issue.

**Comment by guifsdev** [comment]
> Maybe. I don't know how CCleaner works, it's possible that it has corrupted the file.

But the file is not stored locally. 
It is my Google Drive and I don't use any Google Drive client. Only web interface.

> If you're interested about its contents...

Sure, I'll check that out!

**Comment by antelle** [comment]
If you manage to get anything interesting from the `dump-header` tool, let's see what it is. Maybe the file was corrupted during the last save operation somehow.

**Comment by guifsdev** [comment]
@antelle,

I managed to run dump-header tool and got an output:
 
```
versionMajor: 4
versionMinor: 0
dataCipherUuid: McHy5r9xQ1C+WAUhavxa/w==
compression: 1
masterSeed: +6MS5IFjp4S6c94mzbhcULpgMMp2uVQHwMcGs6iW5xE=
kdfParameters: { R: 6000, S: 'c+3K8yehS7FJx1VOSeUDdT5HaGqgA27bls+q66vC/vc=' }
encryptionIV: RW2J5g4WkOu87RauOBN2PQ==
endPos: 177
```

Sorry for the dump question, but can I do with it?

**Comment by antelle** [comment]
Interesting, it doesn't look garbage, that's what I wanted to check. Just one field seems to be missing here, so probably it was either KeeWeb, or some other application aware of the KDBX format that broke the file.  

What you can do, is replace [these lines](https://github.com/keeweb/kdbxweb/blob/master/lib/crypto/key-encryptor-kdf.ts#L11-L15) with:
```js
const kdfUuid = KdfId.Aes;
```

And then run `kdbx-to-xml` tool. Let's see if this helps.

**Comment by antelle** [comment]
❗  Please note: the XML contains your passwords and everything else, don't paste it here. However, if it succeeds, I'd like to know the value of `Generator` from here:
```xml
<KeePassFile>
    <Meta>
        <Generator>THIS</Generator>
```

**Comment by guifsdev** [comment]
@antelle, finally got my things.
Thank you!

And here it is:
`<KeePassFile><Meta><Generator>KeePassDroid</Generator>`

**Comment by antelle** [comment]
Cool! I think you know how to proceed from here. Import the XML in any app (you can do it in KeeWeb too using the open button or just drag-drop it to the open screen), save it back to KDBX, upload it back to GDrive.

Now, I can explain what's going on. Normally a header looks like this:
```
versionMajor: 4
versionMinor: 0
dataCipherUuid: McHy5r9xQ1C+WAUhavxa/w==
compression: 1
masterSeed: fD0QlFhmKcZJU6nYB+C4DnzmnW9lEnS9q1yyKL3rgKo=
encryptionIV: PMRbhn1KFRpocfYdLrIwoQ==
kdfParameters: {
  '$UUID': 'ydnzmmKKRGC/dA0IwYpP6g==',  <---------- this is missing
  S: 'at6YdNq6pFr4rVMKYXm70LfjJ1x0Vj/Tv659gOE2/BA=',
  R: 300000
}
endPos: 207
```

It contains so-called [extensible KDF](https://keepass.info/help/kb/kdbx_4.html#extkdf) section that describes how to hash the database password. It can be Argon2, AES, or something else added by plugins. Which KDF is used, is determined by `$UUID` property. In this case this property was missing, however looking at the parameters (`R` and `S`), I thought maybe it was AES because Argon2 has more parameters.

**Comment by antelle** [comment]
Reported to KeePassDroid authors: https://github.com/bpellin/keepassdroid/issues/457

**Comment by antelle** [comment]
I just realized that passwords will be broken if you import XML like that. I've updated `kdbx-to-xml` tool in `kdbxweb` for you, pull it and do the following:
```
npm run script:kdbx-to-xml file.kdbx pass -- --importable
```

**Comment by guifsdev** [comment]
Amazing man!
I was here banging my head on the table because I couldn't import the xml file in any way!
Worked like a charm. Thanks once again for all you attention.

I'll be glad to help keepassdroid devs with addl. info.

Peace.
