### ISSUE TITLE
Reminders [Feature request]

### ISSUE THREAD

**Issue by Akhilesh-T** [keeweb/keeweb#1829]
Several websites require that you login once in a few months to ensure your account remains active (Ex: _Proton Mail_ every 3 months, _Tutanota_ every 6 months)

The ability to set up **recurring reminders** would be useful in such cases.

Thank you ❤

**Comment by antelle** [comment]
Hi! I assume, password manager that you need to open yourself first, would not be the best fit for this. It's probably better to set up a reminder in a specialized reminder app that can send push notifications and so on. And of course we won't go into the area of proactively notifying the user.
