### ISSUE TITLE
Allow app to hide in system tray and open at startup (minimised)

### ISSUE THREAD

**Issue by Amplifi-Beats** [keeweb/keeweb#1830]
**Is your feature request related to a problem? Please describe.**
I'm frustrated by Keeweb not hiding to system tray, I don't want it chilling on my taskbar all day. Every time I open it, I need to enter my master password (which is unfortunately too secure for my convenience). It isn't deal breaking

**Describe the solution you'd like**
An option in the settings you can enable "hide to system tray", by clicking close or minimise it hides in the system tray (I'm describing Windows, haven't tried on my Linux box yet). So the taskbar is clear of Keeweb, but it can (similar to discord) be clicked and opened again. Without prompting for the password (seeing as it's technically minimised).

**Describe alternatives you've considered**
there are 3rd party solutions, but they don't really work.
I considered going to a different Keepass client, but they look kinda trash, Keeweb is (for the most part) superior.

ps. This is an amazing Keepass client, this obviously won't keep me from using it, but it's very annoying. Thanks so much and have a good day

**Comment by antelle** [comment]
Hi! But we have an option for that (minimize instead of close), it didn't match your expectations?
