### ISSUE TITLE
MacOS Autotype does not function as expected 

### ISSUE THREAD

**Issue by clustor** [keeweb/keeweb#1831]
**Describe the bug**
Autotype suddenty stopped working in the past four days. I do not remember precisely if this is tied to the update. Interestingly installing v1.17.0 also doesn't work anymore and I am pretty positive it was working with that version. It seems like something is changed on my system. 

I have tried removing/adding KeeWeb from Privacy settings as described in https://github.com/keeweb/keeweb/wiki/Auto%20Type#macos but it doesn't help. I do not see a way to switch to legacy auto type mode with Settings / General / Advanced. 

**To Reproduce**
1. Select any entry 
2. Type Cmd+T with text editor as the active app
3. Notice that username and password is not typed completely

**Version Details**
KeeWeb v1.18.6 (070573e, 2021-05-19)
Environment: electron v12.0.7
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 11_3_1) AppleWebKit/537.36 (KHTML, like Gecko) KeeWeb/1.18.6 Chrome/89.0.4389.128 Electron/12.0.7 Safari/537.36

**Logs**
```
[DEBUG] 2021-05-26T01:02:53.304Z [auto-type] Hide window
[DEBUG] 2021-05-26T01:02:53.410Z [auto-type] Start {USERNAME}{TAB}{PASSWORD}{ENTER}
[DEBUG] 2021-05-26T01:02:53.410Z [auto-type] Parsed [op:USERNAME,op:TAB,op:PASSWORD,op:ENTER]
[DEBUG] 2021-05-26T01:02:53.411Z [auto-type] Resolved [**********,key:tab,[*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*],key:enter]
[ERROR] 2021-05-26T01:03:03.634Z [native-module-connector] Received an error kbdText {"name":"Error","message":"Key press failed","stack":"Error: Key press failed\n    at kbdText (/Applications/KeeWeb.app/Contents/Resources/app.asar/native-module-host.js:119:30)\n    at /Applications/KeeWeb.app/Contents/Resources/app.asar/native-module-host.js:257:24","keyPressFailed":true}
[ERROR] 2021-05-26T01:03:03.634Z [auto-type] Run error {"name":"Error","message":"Key press failed","stack":"Error: Key press failed\n    at kbdText (/Applications/KeeWeb.app/Contents/Resources/app.asar/native-module-host.js:119:30)\n    at /Applications/KeeWeb.app/Contents/Resources/app.asar/native-module-host.js:257:24","keyPressFailed":true}

```

**Comment by clustor** [comment]
Yes. Absolutely. It's possible something changed on my Mac. I remember switching between brew install keeweb to Keeweb package from release area recently as brew is not picking up changes fast enough. I don't know if something got messed up in the process.

**Comment by antelle** [comment]
I made a simple app that prints "Hello!" with some debugging output, let's see if it works for you:
[kbd-example.zip](https://github.com/keeweb/keeweb/files/6551733/kbd-example.zip)

**Comment by clustor** [comment]
Yesterday I upgraded my Mac to 11.4 and everything is working fine now. Not sure what changed. Hope that gives you some ideas on what might have happened.  I was consistently having issues with where only one character would show up with Cmd+T but things are back to normal. I will try the example if it breaks again.

**Comment by antelle** [comment]
Good that it's working!
