### ISSUE TITLE
Remove entry from favorites

### ISSUE THREAD

**Issue by Xinas** [keeweb/keeweb#1835]
Hi, I've been using KeeWeb for a while now and have recorded countless passwords in it.
I'm really happy there is a way of have a way of marking an entry as a favorite with a color, because it saves me a lot of time. As time went on though, I started to use some passwords less and less and wanted to remove them from the favorite, but couldn't find a way to do it.
So, I was wondering if there was a way to actually remove an entry from the color favorites all together.

Thanks in advance

**Comment by antelle** [comment]
Hi! If you click on the colored bookmark icon one more time, it will be removed from favorites.
