### ISSUE TITLE
[Question] Possibility of dumping kbdx file from browser data

### ISSUE THREAD

**Issue by dashezup** [keeweb/keeweb#1839]
I have a keeweb instance and the keepass database inside my webdav server. but currently it's down and I don't have access to it for now.

I have two browsers (both firefox) which I was using the instance and loaded the keepass, is it possible to get the kbdx file from browser data? (I have the key and I know the password)

Is the keepass database saved in browser cache/data? or it's lost once the browser was closed?

(I may could get the keepass database from the webdav server someday but not possible for now. and I'm a bit curious about if it' possible this way)

**Comment by antelle** [comment]
Hi! It depends on your settings. By default files are cached in browser storage, if you can open your file in KeeWeb, you can go to file settings (for example, by clicking file name in the footer) and there will be an option to save it as a file.

**Comment by dashezup** [comment]
> Hi! It depends on your settings. By default files are cached in browser storage, if you can open your file in KeeWeb, you can go to file settings (for example, by clicking file name in the footer) and there will be an option to save it as a file.

but the KeeWeb instance is down. so I can't open the keeweb instance at all.

currently I tried to dump "webappsstore.sqlite" but didn't find any info related to keeweb yet.

**Comment by antelle** [comment]
I see. In this case, I would do the following:
1. download KeeWeb HTML from releases
2. add the hostname of your webdav server to hosts as 127.0.0.1
3. start a local webserver in the keeweb folder, e.g. using `http-server` npm package, on the same port
4. open the address in your browser

You can also try exporting data from IndexedDB, but I assume it would be more complicated.

**Comment by dashezup** [comment]
I'm trying it with python http.server now but I got stucked

1. HTTP does not work because of CSP (I tried to search `connect-src` and add `http:` but it still has the same CSP warning
2. I'm trying HTTPS with self-signed cert (it's not possible for me to get the letsencrypt cert I was using for now). but unfortunately I added the domain to HSTS preload and seems it's not possible to bypass HSTS

`http://localhost` works but does not work for the domain.

**Comment by antelle** [comment]
Hm, if you had HSTS on your webdav, it will be indeed more complicated. Then you can look into exporting IndexedDB from your browser, probably there's some solution, but I'm not familiar with it. IndexedDB is stored in the profile directory, but I don't know if there's a ready-to-use tool to extract data from it, probably yes.

**Comment by dashezup** [comment]
@antelle thank you so much for your help, I just managed to get the kdbx file. the last trick is bypass HSTS by changing system time to one year later and/or remove the site from `SiteSecurityServiceState.txt`. Learnt to make sure to have second/third backup and access to the backup from this.

**Comment by antelle** [comment]
Cool! I was a bit afraid suggesting clearing HSTS cache because it's possible that IndexedDB is cleaned as well depending on how you do it, but good that you managed to extract it!  
Better to always have a local backup of course.
