### ISSUE TITLE
Cannot access to KEEWEB via network

### ISSUE THREAD

**Issue by funyfizik** [keeweb/keeweb#1846]
Im installed keeweb using manual https://computingforgeeks.com/install-keeweb-password-manager-ubuntu/
Its installed and work if i access via local host 127.0.0.1, but if I try connect from another local computer I see blank page with console errors
![1](https://user-images.githubusercontent.com/86095002/122512645-d4e91a80-d011-11eb-87e3-a1e6475318c9.png)
![2](https://user-images.githubusercontent.com/86095002/122512651-d6b2de00-d011-11eb-88a3-b1f1e90e1fb1.png)

**Comment by antelle** [comment]
Hi! To fix it, host it on httpS.
