### ISSUE TITLE
Autofill on ChromeOS

### ISSUE THREAD

**Issue by bob2q** [keeweb/keeweb#1849]
Hello, I saw the Tweet that auto-fill now works on Chrome OS: https://twitter.com/kee_web/status/1391463959371427840

However, there are no instructions that I can find to help me set this up. I go to https://app.keeweb.info/ and unlock my Keepass file and yet I cannot find a way to autofill. I tried downloading the .deb Linux file but received an error.

Can someone please upload 5 or 6 steps for ChromeOS autofill? I spent half an hour but without knowing which area I should be attempting to tweak settings on, I'm really lost on how to gain access to the functionality advertised in the tweet.

Thank you.

**Comment by bob2q** [comment]
Specifically, here is my problem and why this Youtube video (https://www.youtube.com/watch?v=29tCxUylQnM&t=1s) doesn't help at all. At the very start of the video, the user already has accessed some extension that I cannot find anywhere. When I go to https://app.keeweb.info/ for the first time, my options look totally different than what the video shows:
![Screenshot 2021-06-23 9 22 26 AM](https://user-images.githubusercontent.com/85448327/123104158-b6fe2a00-d404-11eb-8975-fc9cdb8b2dc7.png)

When I click the KeeWeb Connect for Chrome link, it seems tries to re-open https://app.keeweb.info/ in a new tab and provides an error message that the app can only be open in one browser.

**Comment by antelle** [comment]
Hi! It should work using KeeWeb Connect extension, right. What happens if you close KeeWeb and then click connect in the extension options?

**Comment by bob2q** [comment]
Thanks for the reply. What do you mean by close KeeWeb? Should I have a desktop app? I wasn't sure which one works for ChromeOS. 

If it's not a desktop app, I don't know how to access the extension, I guess. I have checked the Chrome Web Store and run Internet searches trying to back into the extension but cannot locate it anywhere. Right now, the only way I know to access KeeWeb is at https://app.keeweb.info/. My next step is to navigate to Settings. Then, I click Browser from the options on the left. That yields the screenshot I sent earlier. After I click "KeeWeb Connect for Chrome", this is what it leads to: 

![Screenshot 2021-06-23 4 25 36 PM](https://user-images.githubusercontent.com/85448327/123163467-bdf65e00-d43f-11eb-89ed-1577d65c038f.png)

The conundrum for me is that I have no other instances of KeeWeb running other than the single Chrome tab access.  Should I be installing something beforehand? I am not sure how to gain access to the extension. If it's entirely web-based, I can't think of another workflow that would route allow me to route around this error message.

**Comment by antelle** [comment]
The extension link seems to be broken, it should take you to https://chrome.google.com/webstore/detail/keeweb-connect/pikpfmjfkekaeinceagbebpfkmkdlcjk

**Comment by bob2q** [comment]
Thank you, that's one thing that was missing for me. For Chrome OS users, is Web-only recommended or is there a native app set-up that works?

**Comment by antelle** [comment]
Yes, web is the only way on Chrome OS. Native app obviously can't be installed there, that item should be ideally deleted.

**Comment by bob2q** [comment]
Got it. With Chrome OS, there is a Linux VM environment where apps like KeePassXC can be installed as well and Android VM where apps like KeepassDX can be installed. I just never got auto-fill working, possibly because I'm a non-technical user. Both Linux and Android apps are Google-developed first party elements of ChromeOS. That's why I was asking.

**Comment by antelle** [comment]
Or really, you can install native apps there? I thought it was a web-only OS.
Anyway, the web mode should work.

**Comment by bob2q** [comment]
I got the web version working, thanks. Thought I would point out that the Chrome Web Store is doing a poor job surfacing the extension: https://chrome.google.com/webstore/search/keeweb. Not sure if there's anything that can be done about that.

Yes, access to both Android & Linux apps are official Chromium OS projects:
Android: https://www.chromium.org/chromium-os/chrome-os-systems-supporting-android-apps
Linux: https://sites.google.com/a/chromium.org/dev/chromium-os/chrome-os-systems-supporting-linux

**Comment by antelle** [comment]
It's intentional, for now the extension is in so-called "hidden" mode, when you can't find it.
