### ISSUE TITLE
Letter from autotype shortcut missing in login

### ISSUE THREAD

**Issue by existpierre** [keeweb/keeweb#1852]
Hi,

When i have autotype shortcut for example alt + shift + p, letter P missing in login input (existpierre -> existierre)
When i have autotype shortcut for example alt + shift + x, letter X missing in login input (existpierre -> eistpierre)

Letter also missing in password input

Firefox 89.0.2 (64-bit)
Keeweb Version 1.18.6 (070573e)
OS: MacOS Big Sur 11.4 (20F71)

**Comment by antelle** [comment]
Hi! Does it repeats always on this login?
What happens if you insert this letter to other words?

**Comment by existpierre** [comment]
Im sorry, i tryed disable addons because in private mode all works and problem was in addon (jazz-midi). After uninstall this addon all works.


thanks
