### ISSUE TITLE
Feature request: option to keep windows tray icon at all times

### ISSUE THREAD

**Issue by AtmanActive** [keeweb/keeweb#1853]
Right now KeeWeb shows it's tray icon only when it is minimized, which forces windows to forget the icon ordering and treat it like a brand new tray icon on each and every minimize event.
As a contrast, majority of other similar software, like Element, Rambox, Slack, Telegram, etc. keep their tray icon on at all times allowing me to set their ordering and thus manually decide which tray icons I want hidden and which ones shown always.

So, the only way how I can use KeeWeb right now is to keep it open on my taskbar (never minimized) at all times. In other words, for my usage pattern, which is being logged-in 24/7 and using it once every few minutes to insert some password somewhere, the minimize/tray function is useless. Why is it useless? Because every time I click close/minimize, KeeWeb creates a brand new tray icon which windows then promptly moves to hidden icons area. So, instead of then having KeeWeb available on a single click in tray area, I need to spend two clicks to first open the hidden-tray-icon-area and then to call KeeWeb back to foreground.

As I said, no other app that I use on a daily basis behaves in this way. All other apps keep their tray icon shown whether they are minimized/closed or shown. And this makes working with them comfortable.
KeeWeb is the only one that feels uncomfortable, in this sense.

Thank you.

KeeWeb v1.18.5 (d590318, 2021-05-14)
Environment: electron v12.0.7
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) KeeWeb/1.18.5 Chrome/89.0.4389.128 Electron/12.0.7 Safari/537.36

**Comment by antelle** [comment]
Hi! Thank you for the verbose description of the issue! This is also reported in #664
