### ISSUE TITLE
keeweb - Webdav

### ISSUE THREAD

**Issue by FRED7800** [keeweb/keeweb#1854]
Hello

I have installed keeweb on centos machine and also set up Webdav in order to store the kdbx files on it.
When I access to url, I can select my bdbx file to open it. I would like to be able to open other kdbx files
I have added the file and the path in the config.json file but each time I want to open another kdbx file, I have the error,  "There was an error opening file, File not found." The file is under the same directory than the first one which works fine.
Thanks for your help.

in the config.json
 "files": [
        {
                "storage": "webdav",
                "name": "XXXX",
                "path": "/webdav/XXXX.kdbx"
        },
{
                "storage": "webdav",
                "name": "YYYY",
                "path": "/webdav/YYYYY.kdbx"
} ]

**Comment by FRED7800** [comment]
I saw that it has been already asked to have multi sites but the link does not work anymore.

Implemented this, now you can add multiple files. New config: https://github.com/keeweb/keeweb/blob/develop/util/config-example.json#L38

**Comment by antelle** [comment]
Hi! If you open devtools, you should be able to see the path of the loaded file, it can suggest what's going wrong.

**Comment by FRED7800** [comment]
Hello Antelle

Thanks for your quick reply. 

In fact I enabled the devtools mod  and according the error, the YYYY.kdbx is not found
?config=/config.json:1 GET https://IP/webdav/YYYY.kdbx 404 (Not Found)
_request @ ?config=/config.json:1
load @ ?config=/config.json:1
a @ ?config=/config.json:1
openFileFromStorage @ ?config=/config.json:1
openFile @ ?config=/config.json:1
(anonymous) @ ?config=/config.json:1
requestAnimationFrame (async)
(anonymous) @ ?config=/config.json:1
requestAnimationFrame (async)
afterPaint @ ?config=/config.json:1
openDb @ ?config=/config.json:1
inputKeydown @ ?config=/config.json:1
eventListener @ ?config=/config.json:1
e @ ?config=/config.json:1
?config=/config.json:1 2021-06-29T16:25:43.037Z [storage-webdav] Load error /webdav/YYYY.kdbx 404 254ms
?config=/config.json:1 2021-06-29T16:25:43.037Z [open:TEST] Storage load error {notFound: true}
?config=/config.json:1 2021-06-29T16:25:43.038Z [open-view] Error opening file {notFound: true}notFound: true__proto__: Object
r.error @ ?config=/config.json:1
openDbComplete @ ?config=/config.json:1
(anonymous) @ ?config=/config.json:1
(anonymous) @ ?config=/config.json:1
(anonymous) @ ?config=/config.json:1
(anonymous) @ ?config=/config.json:1
load (async)
_request @ ?config=/config.json:1
load @ ?config=/config.json:1
a @ ?config=/config.json:1
openFileFromStorage @ ?config=/config.json:1
openFile @ ?config=/config.json:1
(anonymous) @ ?config=/config.json:1
requestAnimationFrame (async)
(anonymous) @ ?config=/config.json:1
requestAnimationFrame (async)
afterPaint @ ?config=/config.json:1
openDb @ ?config=/config.json:1
inputKeydown @ ?config=/config.json:1
eventListener @ ?config=/config.json:1
e @ ?config=/config.json:1


I did a test with another kdbx file which works. There is no issue. Also the both kdbx file are on the same directory.
I do not understand why there is an issue.

**Comment by antelle** [comment]
If it returns 404, you should debug this request on your webserver. I can't help further with this, sorry.

**Comment by FRED7800** [comment]
ok thanks, but you can confirm that we can have several kdbx files which can be opened on the home page with Webdav ?

**Comment by antelle** [comment]
Yes, multiple files should be supported of course. If they're visible on the start screen, they will work absolutely the same.
