### ISSUE TITLE
Default config.json

### ISSUE THREAD

**Issue by saulobejo** [keeweb/keeweb#1857]
Hello,

This is an improvement suggestion.

With the following change the app will always try to load `config.json` so that users can deploy configuration without re-compiling the app or passing a query string. this is advantageous in case of proxies and default routes.

The app does not crash If `config.json` does not exists.

I'm not submitting a pull request because this is quite small and I already have another pull request on the pipe.

Regards

```diff
diff --git a/app/scripts/app.js b/app/scripts/app.js
index de19718f..a4f4121d 100644
--- a/app/scripts/app.js
+++ b/app/scripts/app.js
@@ -130,6 +130,20 @@ ready(() => {
                                 throw e;
                             }
                         });
+                } else {
+                    const defaultParam = 'config.json';
+                    return appModel
+                        .loadConfig(defaultParam)
+                        .then(() => {
+                            SettingsManager.setBySettings();
+                        })
+                        .catch((e) => {
+                            if (!appModel.settings.cacheConfigSettings) {
+                                console.warn('No default config found');
+                                // showSettingsLoadError();
+                                // throw e;
+                            }
+                        });
                 }
             })
```

**Comment by antelle** [comment]
Hi! You can make the app behave like this, if you change `kw-config` meta-tag: https://github.com/keeweb/keeweb/blob/master/app/index.html#L22

It doesn't require recompiling the app or changing CSP.

**Comment by saulobejo** [comment]
indeed.

but this requires changing the HTML which means I can't just pull the git to keep it up to date without having to change it back every single time.

**Comment by antelle** [comment]
Well, it shouldn't submit a strange request all the time if it's not desired. I assume, if adding a url parameter is not an option, you can for example set up a script that will change the file after pull.

**Comment by antelle** [comment]
Another option is to make webserver change the content of the page.

**Comment by antelle** [comment]
...or add a redirect: `/ => /?config.json`

**Comment by saulobejo** [comment]
@antelle that makes sense as far as `strange request that only returns 404 goes` and i guess changing the proxy/webserver is not that onerous option.

thanks for the quick reply.
