### ISSUE TITLE
Please update keeweb for nextcloud (too old)

### ISSUE THREAD

**Issue by Kalimeiro** [keeweb/keeweb#1859]
Today we have Keeweb 1.16.7 on nextcloud but the lastest release of Keeweb is 1.18.6

Could you please export the release to Nextcloud ?

**Comment by antelle** [comment]
Hi! The nextcloud version of KeeWeb is a 3rd-party integration, it's not part of KeeWeb. I assume, you need this project: https://github.com/jhass/nextcloud-keeweb
