### ISSUE TITLE
strengthen the security of visibility 

### ISSUE THREAD

**Issue by HDInfautre** [keeweb/keeweb#1864]
Hello
I have been using your software for some time and I like it. Thank you!
I have not seen the following information or requirements in a faq or elsewhere.
Sorry to contact you, but I would like to know if it is possible or on the roadmap to be able to fully use and recommend to newbies this software in the defense of rights and freedoms

**1/ AppImage**
I tried to use the activation method KeeWeb-1.17.5.AppImage.home recommended in :
https://docs.appimage.org/user-guide/portable-mode.html, I always find traces in the home .../.config/keeweb
I don't want to leave any trace outside this directory which is on an external disk.
How can I do it?

**2/ Path of the files**
In the same logic of not leaving traces that an external person to ask us, is it possible not to display the history of file paths?

**3/ keeweb browser**
in the same way as other software, is it possible to connect to the member area of a website, without copying and pasting the username and password?

Regards

KeeWeb v1.17.5 (4ee87e1, 2021-03-27)
Environment: electron v12.0.0
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) KeeWeb/1.17.5 Chrome/89.0.4389.69 Electron/12.0.0 Safari/537.36

**Comment by antelle** [comment]
Hi! 

1. not sure if it's possible to remove this, most likely it's not easy
2. what do you mean by "history of file paths"? if you delete a file from KeeWeb, it's shouldn't leave traces anywhere.
3. yes, using either auto-type, or KeeWeb-Connect extension

**Comment by HDInfautre** [comment]
Hi,
Thank you for your reply.
1/ Ok I turn it into a suggestion because my other appImage use well this standard which allows to transform keeWeb into a portable application. Is it possible ?

2/ I'm talking about the history of the previous open file. I don't want to see it appear under the password box, not to say that I don't know it !

3/ indeed I had an old version. I just downloaded this extension for Firefox. It didn't work.
a) use app.keeweb.info
display of the connection message in green but no transfer of the login or the password
b) appImage keeWeb open
The firefox addon - Connection status: Error
Unable to connect to KeeWeb. Make sure KeeWeb is open and that the browser integration is enabled in the settings.
I wonder if I'm using appImage Firefox 90.0 (en) in portable mode!?

The web mode app.keeweb.info seems interesting to me but do you even recover encrypted my password data or is it just a local remote application that doesn't see any password?
regards

**Comment by antelle** [comment]
1. Can you please check what you see in that directory? KeeWeb itself doesn't write them, but they're created by the framework we're using, so it can be very complicated, depending on what is there.
2. I see, I thought you mean file saved in logs, etc... It's not good UX to disable file path there and it doesn't make a lot of sense, because you can easily see the file path in DevTools even without entering its password. So it doesn't add much in terms of security.
3. You should probably debug the Firefox add-on installation, you can find some information here: https://github.com/keeweb/keeweb/wiki/Browser%20AutoFill

> The web mode app.keeweb.info seems interesting to me but do you even recover encrypted my password data or is it just a local remote application that doesn't see any password?

It's an offline application, it doesn't upload your file anywhere, for extra security you can host it on your static webserver, it will work as well. But it has less possibilities compared to the desktop app, such as, you won't be able to save changes to local files.

**Comment by HDInfautre** [comment]
Hi,
1. I believe that all applications create files/directories (see picture). This leaves a trace on the computer.
The portable method generates files and directories on the external drive. I use it now for several applications like Firefox and it works well. Is it clearer? Do you see the point?

2. ah ok if it doesn't help an expert. Many applications allow you to hide these paths at least as an option. If others see the point of this option!

3. I had read this page well. I don't know how to debug the installation of an add-on! I wonder if it comes from the fact that firefox is an appImage (I seem to have had a similar problem). Anyway I'm leaving on Saturday, I hope others can check this problem otherwise I'll come back to you.
Regards

**Comment by antelle** [comment]
1: I mean, we don't write it _intentionally_ in KeeWeb. However, the framework that KeeWeb is built upon (Electron) does write those files. It indeed makes sense to avoid this, but if it's something that can't be easily disabled, we won't be able to do it. So, I asked which files you see there, but I can also check myself later.
3: You can start with inspecting the addon's background page to see what it is.

**Comment by HDInfautre** [comment]
oups 
I forgot 1.
![Capture d’écran de 2021-07-29 20-41-56](https://user-images.githubusercontent.com/6817936/127550699-a67f9fc2-9128-45fd-818b-90c43dac35a9.png)

**Comment by antelle** [comment]
I see, thank you, it's unlikely this can be fixed in AppImage, but you can create a portable installation using this method: https://github.com/keeweb/keeweb/wiki/Configuration#portable

**Comment by HDInfautre** [comment]
Hi,
Thanks for the follow up!
I tried many different path (absolute, relative with ...), it does not work anymore.
Here is the tree structure:
KeeWeb-portable
|-KeeWeb-donnees\ (data dir)
|-keeweb.json
|-KeeWeb-1.18.7.linux.AppImage

I wonder if it's not still related to the appimage because I'm not sure if it's the same thing as the doc!

**Comment by antelle** [comment]
It will work only with a zip distributable, not with AppImage I think

**Comment by HDInfautre** [comment]
Hi,
Ok maybe one day my suggestions will be taken into account?
I don't know if you can look (nothing urgent but annoying!) the connection between appImage keeWeb and Firefox + keeweb-browser !?
I will be on vacation.
Have a good weekend

**Comment by antelle** [comment]
So, from this it would be of course good to implement a portable AppImage, but I'm not sure if this will work for everyone because it will mean that we will also erase all settings after restarting KeeWeb. Let's see if anyone else comes with this suggestion.

About KeeWeb-Browser, you can try debugging the installation using the link I pasted above, I can't really help here.
