### ISSUE TITLE
Ability to reveal the master password while typing.

### ISSUE THREAD

**Issue by leorochael** [keeweb/keeweb#1866]
**Is your feature request related to a problem? Please describe.**
I  have a very long master password, and it's common for me to make a mistake in the middle of the password on certain keyboards.

I'd like to be able to make the master password visible to make sure I typed it correctly before hitting Enter to try to open the password database

**Describe the solution you'd like**
I'd like there to be an eye icon to the right of the master password field that toggles the password visibility.

A keyboard shortcut to go with it would be nice as well! Or at least a context menu, like in the Ubuntu login screen, which can be activated with a right click or the menu button in the keyboard.

Ideally, clicking on this icon should cause focus not to move (or to return quickly) to the password field if the focus was there, and the text cursor position should remain the same.

**Describe alternatives you've considered**
If there is a security worry, then the eye button could only show the password while it's being pressed and the password hidden again as soon as it's released, rather than being a toggle.

But in that case maintaining the focus and the cursor position in the password field becomes even more important.

**Additional context**

This codepen has an example of what I'm looking for, except for the focus and cursor position handling

https://codepen.io/Sohail05/pen/yOpeBm

![image](https://user-images.githubusercontent.com/239125/127552023-b919c102-dd27-4302-91cd-4a7264378af6.png)

![image](https://user-images.githubusercontent.com/239125/127552075-051621b7-dd9e-41dc-b22e-f71f532b1d0a.png)

This AskUbuntu answer has a screenshot of the Ubuntu password context menu:

https://askubuntu.com/a/1165923

Which is this:

![image](https://user-images.githubusercontent.com/239125/127553414-e7bf3450-60e8-4439-8684-541157a01836.png)

In any case, thank you for KeeWeb, it's an amazing piece of software!

**Comment by antelle** [comment]
Hi! Thanks for a verbose description, it's a better version of #749

**Comment by leorochael** [comment]
@antelle, sorry I searched the issues, but missed that one.

**Comment by antelle** [comment]
It's hard to find with that description, I agree
