### ISSUE TITLE
Unable to see KeeWeb version, using smartphone

### ISSUE THREAD

**Issue by TheFax** [keeweb/keeweb#1867]
When the Online Web App is open on a smartphone, there is no way to see the version of the application itself.

**Describe the solution you'd like**
The version should be visible in a corner of the home screen, or at least, from the settings panel BEFORE opening any file.

**Comment by antelle** [comment]
Hi! You can see the web version using the help button in the footer.
> The version should be visible in a corner of the home screen, or at least, from the settings panel BEFORE opening any file.

I don't see any reason why. This doesn't give any security: if you see a fake webapp, the version can be easily added there as well. As well as convenience: version information doesn't say anything, unless you're troubleshooting.

**Comment by TheFax** [comment]
Hello @antelle, and thankyou for your answer.


The help button appears on the screen only after I put the **correct password** opening a **pre-existent encrypted file**.


My request to put the version on the homepage (or into the settings menù) is **not for a security reason against fraudulent websites**, but a good practice in order to let your users choose and log-in into an updated version of KeeWeb.

Let me do two examples.
Example 1)
Should I use "www.website1.com" or "www.website2.com" if both of them have a KeeWeb installed and available to the public?
If the version is present in the homepage, there is no problem at all to choose the most updated.

Example 2)
If KeeWeb has got a bug that damage the file, or other unwanted malfunctions (also not yet currently discovered), (eg. [Issue 1832](https://github.com/keeweb/keeweb/issues/1832)) **how can I know if I'm logging in a password in a bugged software**?
Probably, if I'm a careful user, I would stay away from a bugged version of a software. 

Last, but not least, I think this improvement is not so difficult to be implemented.

This is just my opinion and I respectfully externalize it.
Sorry for my basic level of english: I apologize in advance if I used rude terms.
Thank you for your attention.

**Comment by antelle** [comment]
In general, it's a good idea to use a KeeWeb instance only if you trust the owner of the installation, in this case it should be either updated to the latest one, or fixed to some version that should work.   

The last version of KeeWeb, If you need to know it, can be found by clicking the Demo button and then the help screen, which is not something obvious, but you can use this trick if you need to.
