### ISSUE TITLE
Working on localhost but not on distant server

### ISSUE THREAD

**Issue by nicko27** [keeweb/keeweb#1869]
Hi, 
First excuse me for my lame English.
I used keeweb in my company without https installed on a debian server and without difficulties for more than a year and since the Firefox v78.9 (I think), I have a WebCrypto error. I tried in localhost (again without https on apache/ubuntu 20.04), on the same pc I used for the distant connection :  It work.
It's a big company and I can't install https without a lot of complicated demands and I don't understand why it work on localhost and not on distant. 
Can you help me or at least explain to me why it doesn't work ?
Thanks 
Nico from France

**Comment by antelle** [comment]
Hi! `localhost` is a bit special, it's supposed to be used for debugging, so there's an exception and WebCrypto works on localhost without HTTPS.

**Comment by nicko27** [comment]
Thanks for your fast answer. I thought it was something like this, and you confirm it worked before on http because of the version of firefox ?

**Comment by antelle** [comment]
Maybe it worked before, then browsers limited WebCrypto to HTTPS only, which is understandable.

**Comment by nicko27** [comment]
Understandable but in nationalwide company some change are difficult to apply and I don't know how I will do. Https will be complicate to obtain in our intranet.

**Comment by antelle** [comment]
You can make a self-hosted certificate, it should work if it's HTTPS.

**Comment by nicko27** [comment]
Yes, I know but for that I need some very high level permissions.
