### ISSUE TITLE
KeePassHttp no longer part of KeeWeb?

### ISSUE THREAD

**Issue by Andreas-Schoenefeldt** [keeweb/keeweb#1872]
**Describe the bug**
I used to work with KeePassHttp-Connector browser plugin, to connect to KeeWeb. This relies on KeePassHttp, which used to be enabled by default in KeeWeb.

I had to reinstall my system new recently, and now KeePassHttp seems to be removed from KeeWeb?

Is there a way to enable it again?

Many thx!

**To Reproduce**
1. INstall KeePassHttp-Connector Plugin in Chrome
2. Try to connect to KeeWeb Passwords

**Expected behavior**
It should be possible to use other plugins then KeeWebConnect (not working) or KeePassXC Browser (bad UX)

**Environment**
KeeWeb Version 1.18.7 (dfc6201)
passwords file via dropbox sync

**Logs**
```
[INFO ] 2021-08-06T11:05:20.404Z [start-profiler] Electron app started in 1837ms: loading app requires=4ms, single instance lock=1ms, portable check=0ms, userdata dir=0ms, defining args=11ms, setting env=0ms, app on ready=70ms, loading settings key=21ms, reading app settings=5ms, creating main window=30ms, configuring main window=2ms, restoring main window position=0ms, setting ipc handlers=11ms, setting global shortcuts=1ms, subscribing to power events=0ms, setting request handlers=0ms, main window ready=297ms, main window shown=3ms
[DEBUG] 2021-08-06T11:05:20.407Z [settings-manager] Theme changed dark
[INFO ] 2021-08-06T11:05:20.408Z [usb-listener] Starting USB listener
[DEBUG] 2021-08-06T11:05:20.408Z [native-module-connector] Starting native module host
[INFO ] 2021-08-06T11:05:20.488Z [start-profiler] App started in 418ms: fetching=194ms, pre-init=249ms, loading modules=52ms, document ready=10ms, creating app model=2ms, loading configs=21ms, initializing modules=1ms, loading remote config=1ms, checking features=1ms, initializing storage=0ms, starting usb=0ms, first view rendering=79ms, app ready event=0ms
[INFO ] 2021-08-06T11:05:20.992Z [updater] Next update check will happen in 86159s
[INFO ] 2021-08-06T11:05:21.002Z [browser-extension-connector] Started
[INFO ] 2021-08-06T11:05:24.192Z [open:passwords] File open request
[INFO ] 2021-08-06T11:05:24.192Z [open:passwords] Open file from cache, will sync after load dropbox
[DEBUG] 2021-08-06T11:05:24.192Z [storage-cache] Load 5e972174-1f53-39f9-f684-63b67c68b51f
[DEBUG] 2021-08-06T11:05:24.198Z [storage-cache] Loaded 5e972174-1f53-39f9-f684-63b67c68b51f 3ms
[INFO ] 2021-08-06T11:05:24.198Z [open:passwords] Loaded file from cache null
[INFO ] 2021-08-06T11:05:24.595Z [file] Opened file passwords: 396ms, 6000 rounds, 613 kB
[DEBUG] 2021-08-06T11:05:24.595Z [app] Add last open file 5e972174-1f53-39f9-f684-63b67c68b51f passwords dropbox /passwords.kdbx 5c8d3dcc7ec5158576c1c
[INFO ] 2021-08-06T11:05:24.641Z [open:passwords] Sync just opened file
[INFO ] 2021-08-06T11:05:24.649Z [sync:passwords] Sync started dropbox /passwords.kdbx {}
[INFO ] 2021-08-06T11:05:24.650Z [sync:passwords] Stat file
[DEBUG] 2021-08-06T11:05:24.650Z [storage-dropbox] Stat /passwords.kdbx
[INFO ] 2021-08-06T11:05:24.651Z [storage-dropbox] HTTP request POST https://api.dropboxapi.com/2/files/get_metadata
[INFO ] 2021-08-06T11:05:25.105Z [storage-dropbox] HTTP response POST https://api.dropboxapi.com/2/files/get_metadata 200 {"cache-control":"no-cache","x-content-type-options":"nosniff","x-frame-options":"SAMEORIGIN","x-server-response-time":"78","content-type":"application/json","accept-encoding":"identity,gzip","date":"Fri, 06 Aug 2021 11:05:24 GMT","server":"envoy","content-encoding":"gzip","vary":"Accept-Encoding","x-dropbox-response-origin":"far_remote","x-dropbox-request-id":"e32f0d40f43f41f598d09426f5733e95"}
[INFO ] 2021-08-06T11:05:25.106Z [storage-dropbox] HTTP response 200
[DEBUG] 2021-08-06T11:05:25.106Z [storage-dropbox] Stated /passwords.kdbx 5c8d3dcc7ec5158576c1c 456ms
[INFO ] 2021-08-06T11:05:25.107Z [sync:passwords] Stat found same version, not modified
[INFO ] 2021-08-06T11:05:25.107Z [sync:passwords] Sync finished no error
```

**Comment by antelle** [comment]
Hi! KeePassHttp will no longer work with KeeWeb. I think the problem is that 
> KeeWebConnect (not working)

so the solution would be to make it work.

**Comment by Andreas-Schoenefeldt** [comment]
Hi @antelle, thank you for the swift response! I tried it now with the help of this https://github.com/keeweb/keeweb/wiki/Browser-AutoFill#other-browsers documentation, and because I'm a developer myself, I did succeed :D  

I'm on macOS BigSur 11.5.1 
using Iron Browser (Chromium based): Version 91.0.4472.77 (Official Build) (x86_64)

In KeeWeb I have enabled KeeWeb Connect for "Chrome" and "Other browsers"

I created the file `net.antelle.keeweb.keeweb_connect.json` with this content:

```
{
    "allowed_origins": [
        "chrome-extension://pikpfmjfkekaeinceagbebpfkmkdlcjk/"
    ],
    "description": "KeeWeb native messaging host",
    "name": "net.antelle.keeweb.keeweb_connect",
    "type": "stdio",
    "path": "/Applications/KeeWeb.app/Contents/MacOS/util/keeweb-native-messaging-host"
}
```

The file is in this location: `/Users/andreas/Library/Application Support/Chromium/NativeMessagingHosts/net.antelle.keeweb.keeweb_connect.json`

And it worked! 

Any chance, that this could be automated? I guess if "other browsers" is enabled, a small script could scan the computer for available browsers and create this file on the fly? It would be a great addition :D

Many thx for this great tool btw - I'm using it for years already and it realy eases the pain of using keepass while still beeing in control of this billions of passwords. Hats off!

**Comment by antelle** [comment]
Good that it worked! 
The process is automated for supported browsers, for others we can make something like “select where your browser is located”, but that’s more complicated.

**Comment by Andreas-Schoenefeldt** [comment]
@antelle, do you know if there is some way of creating a similar UX with the native messaging as before with KeePassHttp?

right now if I have multiple usernames for a website, the KeWeb Window jumps in front and I have to select the fitting one. Also right clicking the input and selecting the KeeWeb Connect is pretty cumbersome. 

Ideal would be:
* I click into the login field and a dropdown with my available passwords appears. 
* I select the fitting one and the form get's filled
* I click on login myself

The auto login can be handy, but maybe this can be simply controlled by preference of the plugin? Maybe something like "auto login, if just one entry is available"

Many thx!
Andreas

**Comment by antelle** [comment]
It's possible, but time-consuming and error-prone, such UI and auto-fill is provided by KeePassXC-Browser, the connection with KeeWeb should be similar to KeeWeb-Connect.

**Comment by Andreas-Schoenefeldt** [comment]
The UX of KeePassXC-Browser is also not ideal at the moment, but then probably better to try improving that one. Is this also maintained by you or a seperate project? If it's seperate, do you know how to get in touch with them?

Many thx!

**Comment by antelle** [comment]
It's a completely separate project belonging to KeePassXC maintainers, so issues with KeeWeb should be never reported to KeePassXC-Browser, because if we deliver much trouble to them, we'll have to remove the possibility of connecting to KeePassXC-Browser at all.

What kind of issues did you notice? It can probably something like we don't return proper format from KeeWeb.

**Comment by Andreas-Schoenefeldt** [comment]
Man, this KeePassXC is real ugly... ok, let me try if I can connect it instead KeePassXC-Browsers UX is actually what I was looking for.

**Comment by antelle** [comment]
Eventually we'll support these features in KeeWeb-Connect too I think, here are the tickets: https://github.com/keeweb/keeweb-connect/issues

**Comment by Andreas-Schoenefeldt** [comment]
Ok, connected to KeeWeb KeePassXC-Browser does not provide the nice autoselect functionality, but at least I don't have to right click all the time ;)

I'll see a few days how it goes, and probably then join you in https://github.com/keeweb/keeweb-connect/issues

**Comment by Andreas-Schoenefeldt** [comment]
Many thx for the lightning fast help!

**Comment by antelle** [comment]
Yeah auto-select may not work because KeeWeb returns only one issue, this is possible to fix. There should be checkbox in the app settings for this.

**Comment by Andreas-Schoenefeldt** [comment]
That would be awesome!
