### ISSUE TITLE
RPM repository

### ISSUE THREAD

**Issue by jeffclay** [keeweb/keeweb#1873]
Just an FYI, I have started a COPR repository for this package. I am building for Centos Stream 8 & 9, EPEL 6, 7 & 8, Fedora 33, 34, ELN and Rawhide as well as Oracle Linux 7 & 8.  The EPEL 8 build should also work for Rocky Linux. Feel free to include this in the project documentation.

https://copr.fedorainfracloud.org/coprs/jclay/KeeWeb/

**Comment by antelle** [comment]
Hi! Thank you for making it!
