### ISSUE TITLE
The newest Keeweb (Desktop) version (1.18.7) is not compatible with the newest Debian stable (11)

### ISSUE THREAD

**Issue by atlochowski** [keeweb/keeweb#1879]
**Describe the bug**
The newest Keeweb version is not compatible with the newest Debian stable (11)

**To Reproduce**
1. Download Keeweb desktop
2. dpkg -i Keeweb-*.deb
3. There is no package libappindicator1 in repos

**Expected behavior**
installes packages

**Environment**
Debian 11

**Comment by antelle** [comment]
Hi! For now you can install it from a zip archive. I guess this will be fixed itself once the package is available. Duplicates #1876

**Comment by atlochowski** [comment]
Sorry for duplicate
