### ISSUE TITLE
Space characters are not shown in revealed password

### ISSUE THREAD

**Issue by noahfrederick** [keeweb/keeweb#1880]
**Describe the bug**
Space characters are not shown in revealed password.

I believe this bug has been present as long as the **Reveal** feature has existed.

**To Reproduce**
1. Enter `two words` into password field.
2. Click on disclosure arrow and then **Reveal**.
3. See `twowords` displayed.

**Expected behavior**
See `two words` (including entered space character) displayed.

**Screenshots**
Can provide if needed.

**Environment**
```
KeeWeb v1.18.7 (dfc6201, 2021-07-18)
Environment: electron v12.0.7
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 11_3_1) AppleWebKit/537.36 (KHTML, like Gecko) KeeWeb/1.18.7 Chrome/89.0.4389.128 Electron/12.0.7 Safari/537.36
```

**Kdbx File**
Does it happen on Demo or New database?
*Yes, happens in Demo database.*

**Logs**
Can provide if needed.

**Comment by Aetherinox** [comment]
This is addressed in v1.19
- https://github.com/keeweb/keeweb/pull/2168
