### ISSUE TITLE
Removing Color from Entries

### ISSUE THREAD

**Issue by pengster** [keeweb/keeweb#1884]
How do i remove a color from an entry?

**Comment by antelle** [comment]
if you click the same color, it will be removed

**Comment by gautierlabarre** [comment]
Hello, 
Sorry to dig on an old issue, but I had to remove a color and the UX is not really intuitive (I had to come here too).

Would it be possible, to just add the white icon to revert to default color instead of picking the same one ?

**Comment by antelle** [comment]
It would be possible indeed, or create a soft of transparent icon.
