### ISSUE TITLE
It is helpfuld that a field name is editable even after the field generation

### ISSUE THREAD

**Issue by bnsonear** [keeweb/keeweb#1886]
**Is your feature request related to a problem? Please describe.**
At the present version, name of field is only editable when the field is just generated.

**Describe the solution you'd like**
Right click on the existing field name can open a small box on the same position which is filled with the previous field name.

**Describe alternatives you've considered**
A right-click on the existing field name can give a context menu with "Edit this field name".

**Additional context**
Thank you for your hard work!

**Comment by antelle** [comment]
Hi! The name is editable, if you first click the value and then its name, it will be possible to change it. The UX is however not great, it should be fixed in next versions, there's another issue about it.
