### ISSUE TITLE
Generate and save pass to manager

### ISSUE THREAD

**Issue by babahcv** [keeweb/keeweb#1889]
Create possibility to generate password directly 
on password field and then save credential to KeeWeb database

**Comment by hoprikoma** [comment]
Do you talk about this ? 
![image](https://user-images.githubusercontent.com/43370494/131265959-f1fc875b-3f3a-4744-bb91-f719766b27ba.png)

**Comment by babahcv** [comment]
> Do you talk about this ?
> ![image](https://user-images.githubusercontent.com/43370494/131265959-f1fc875b-3f3a-4744-bb91-f719766b27ba.png)

No, I mean create a password on the web page in the password field, and then save the login and password to the database, so i want to generate pass directly on registration form.

**Comment by antelle** [comment]
Hi! This should be in the extension (keeweb-connect), but it already has https://github.com/keeweb/keeweb-connect/issues/11
