### ISSUE TITLE
Blank page when deploying to  on apache 

### ISSUE THREAD

**Issue by firetee13** [keeweb/keeweb#1892]
**Describe the bug**
Deploying keeweb to apache results in blank page

**To Reproduce**
1. unzip latest release to /var/www/html/ 

**Expected behavior**
Keeweb  applications appears

**Screenshots**

![132006805-288d8cb6-27c9-4feb-a1d0-0a934d9b37d5](https://user-images.githubusercontent.com/6322864/132008357-a23c813a-64e4-4e10-a163-cb2784d398fe.png)

**Environment**
version 1.18.7, tested on latest chrome and firefox in incognito and as guest

**Logs**
[Fri Sep 03 10:48:01.192660 2021] [access_compat:error] [pid 12:tid 139767018678016] [client 10.22.1.5:62957] AH01797: client denied by server configuration: /var/www/html/

[Fri Sep 03 14:39:16.120804 2021] [access_compat:error] [pid 11:tid 139767010285312] [client 10.22.1.5:51746] AH01797: client denied by server configuration: /var/www/html/

[Fri Sep 03 14:39:21.188453 2021] [access_compat:error] [pid 12:tid 139767141381888] [client 10.22.1.5:55766] AH01797: client denied by server configuration: /var/www/html/

[Fri Sep 03 14:39:21.647626 2021] [access_compat:error] [pid 12:tid 139767107811072] [client 10.22.1.5:55766] AH01797: client denied by server configuration: /usr/share/apache2/icons/favicon-32x32.png, referer: http://keepass-prod-2.company.com::8000/

[Fri Sep 03 14:39:21.676667 2021] [access_compat:error] [pid 12:tid 139767132989184] [client 10.22.1.5:55766] AH01797: client denied by server configuration: /usr/share/apache2/icons/favicon-16x16.png, referer: http://keepass-prod-2.company.com:8000/

**Comment by antelle** [comment]
Hi! You should inspect the webpage in browser devtools, probably there's an error there

**Comment by firetee13** [comment]
![image](https://user-images.githubusercontent.com/6322864/132304113-a9d99fb8-c8ed-4e21-9320-db57a23ee222.png)
this is the error

**Comment by firetee13** [comment]
It works if I access it from localhost so it must have something to do with the hostname.

**Comment by firetee13** [comment]
thanks! it worked with https
