### ISSUE TITLE
How to import custom fields?

### ISSUE THREAD

**Issue by howdytom** [keeweb/keeweb#1899]
Hi there,

I stumbled upon this wonderful password manager. What is the best way to important custom fields into KeeWeb? I would like migrate various hardware and software serial numbers, server IDs, warranty, passwords... Manually adding a lot of data is a pain. I have tried to add custom fields prior the CSV import. However custom fields are set per password entry and not globally in KeeWeb.

**Comment by antelle** [comment]
Hi! Custom fields are set per password entry in KeeWeb, there's no way to have a global custom field. So, you can't import it either.

**Comment by antelle** [comment]
You can add a template it you would like to have a customized entry.

**Comment by howdytom** [comment]
Thank you. This is exactly I was looking for.
