### ISSUE TITLE
[Feature Request] Ability to select multiple entries using ⌘ CMD key command

### ISSUE THREAD

**Issue by howdytom** [keeweb/keeweb#1900]
**Is your feature request related to a problem? Please describe.**
Sometimes I need to select and delete a bunch of entries in KeeWeb for macOS. 

**Describe the solution you'd like**
Please add the ability to select multiple entries by holding down the ⌘ CMD and shift key.

**Describe alternatives you've considered**
Holding down shift key and select first and last entry.

**Comment by antelle** [comment]
I think there was a request for this, but I can't find it now.

**Comment by jeff-h** [comment]
https://github.com/keeweb/keeweb/issues/729 perhaps?

You've done a great job making KeeWeb feel at home on Desktop eg the ability to drag items into different folders / databases. Being able to select and drag or delete multiple items would really take this up a notch :)
