### ISSUE TITLE
CSV import always ignores last entry

### ISSUE THREAD

**Issue by howdytom** [keeweb/keeweb#1904]
**Describe the bug**
When I try to import 10 entries from a comma separated CSV file, KeeWeb always skips and ignores the last entry. This issue is serious if you don't want to miss any entries and check imported entries carefully!

**To Reproduce**
1. I have attached a test CSV file with 10 Login entries
2. Import [CSV_test-import-10entries.csv](https://github.com/keeweb/keeweb/files/7228706/CSV_test-import-10entries.csv) into KeeWeb 
3. KeeWeb imports Login 1-9
4. Login 10 will be ignored

**Expected behavior**
All entries inluding the last line should be imported.

**Workaround**
Create a additional helper entry which will be skipped.

**Kdbx File**
This issue occurs on a new and and existing Kdbx database.

**Comment by antelle** [comment]
Hi! That's strange, thank you for spotting this!

**Comment by HarlemSquirrel** [comment]
Fixed by #1944
