### ISSUE TITLE
[Feature Request] Delete a single field

### ISSUE THREAD

**Issue by howdytom** [keeweb/keeweb#1909]
**Is your feature request related to a problem? Please describe.**
How can I delete a single field instead of removing a entry and recreating all fields? Adding a new field, hide or leave unused fields empty does not seem to be right. It will increase field structure/database.

**Describe the solution you'd like**
Please add an option to delete single fields using right click / ctrl key.

**Comment by antelle** [comment]
If you set the field value to a blank string, it will be deleted. This should be improved in the next version.

**Comment by howdytom** [comment]
👍  perfect! Such a nice and minimal solution. I love KeeWeb.
