### ISSUE TITLE
password length is limited (password generator)

### ISSUE THREAD

**Issue by dotpot** [keeweb/keeweb#191]
**- what were your actions?**
creating new entry.
**- what was wrong?**
password length is limited to **64**. 
**- app version**
v1.1.2
**- your user-agent (from Settings/Help section)**
KeeWeb v1.1.2 (fb00cf5, 2016-04-10)
Environment: electron v0.35.6
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_4) AppleWebKit/537.36 (KHTML, like Gecko) KeeWeb/1.0.3 Chrome/45.0.2454.85 Electron/0.35.6 Safari/537.36

**Comment by antelle** [comment]
Hello!
There's no such limitation. How do you manage to get it? In the password input field? Or it's a custom field?

**Comment by dotpot** [comment]
I mean `password generator`.
<img width="278" alt="screen shot 2016-04-12 at 09 13 13" src="https://cloud.githubusercontent.com/assets/524216/14451322/e48ac6f8-008e-11e6-9c7f-72216d8d572d.png">

**Comment by antelle** [comment]
Such limit (and step) is a reasonable balance between flexibility, speed (we want to optimize for the mainstream scenario: 3..16..32 characters) design (we don't want to make it a length textbox). If we add a next step as 128, tomorrow someone will ask about generating exactly 100.

**Comment by dotpot** [comment]
you could have a simple preference (settings) for this, or just a text box (appearing once you click on that number), so anyone could change it as needed. Now it's just too limited.

e.g. KeePassX password generator:
<img width="482" alt="screen shot 2016-04-13 at 11 26 10" src="https://cloud.githubusercontent.com/assets/524216/14487347/b5bddf2c-016a-11e6-8f30-ae8f7c037705.png">

**Comment by antelle** [comment]
> appearing once you click on that number

Good idea, thanks, this may have sense.

**Comment by ericbn** [comment]
+1
Do you accept pull requests for this?

**Comment by antelle** [comment]
Now you can do it with a custom preset with any desired length, up to 1000:
![presets](https://cloud.githubusercontent.com/assets/633557/17650358/7da8c66a-6254-11e6-9693-8e3f2450648c.png)
