### ISSUE TITLE
[Feature Request] Increase field description width?

### ISSUE THREAD

**Issue by howdytom** [keeweb/keeweb#1913]
**Is your feature request related to a problem? Please describe.**
Adding fields are fantastic and fast in KeeWeb. If you use long field names KeeWeb adds a line break.

**Describe the solution you'd like**
What column width does KeeWeb use? Is possible to increase the default field UI and use 2% longer field titles?
As a workaround, you could keep field name short, of course.

![Increase field description width](https://user-images.githubusercontent.com/9871520/134978056-4519ac10-3062-492d-8635-1319bdf383f3.png)

**Comment by antelle** [comment]
This works as expected, "hardware token date" would not fit the field length even if it's increased.
