### ISSUE TITLE
Is the web/online/browser app safe?

### ISSUE THREAD

**Issue by Snake883** [keeweb/keeweb#1918]
Is the web/online/browser app safe?

What security concerns are there using the online/web/browser app?

How is the security different between the online/web/browser app and the desktop client application?

**Comment by antelle** [comment]
Hi! It's hard to say unless you have your threat model in mind.
In general, the web version:
- doesn't support device interactions, like YubiKeys
- requires being careful with browser plugins, if you like to install unverified plugins, maybe web version is not the best choice
