### ISSUE TITLE
OneDrive integration not working

### ISSUE THREAD

**Issue by piyushparate1** [keeweb/keeweb#1919]
**Describe the bug**
When i tried to login into one drive, it throwing me the below error in the console:

2021-10-10T04:25:07.009Z [storage-onedrive] OAuth error invalid_request The request is not valid for the application's 'userAudience' configuration. In order to use /common/ endpoint, the application must not be configured with 'Consumer' as the user audience. The userAudience should be configured with 'All' to use /common/ endpoint.

**To Reproduce**
1. Self host the branch in Azure Static Web App - https://github.com/keeweb/keeweb/tree/gh-pages
2. Open the Web App
3. Enter password of kbdx file
4. Login into your Microsoft personal account
5. It will throw an error in Web App as well as in console

**Expected behavior**
It should work without an error and we should be able to browse the kbdx file content

**Screenshots**
![KeyWeb](https://user-images.githubusercontent.com/6030327/136682249-a1877793-2099-4d0a-9454-3fdfe25eddb8.png)

**Environment**
KeeWeb v1.18.7 (dfc6201, 2021-07-18)
Environment: web
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.71 Safari/537.36

**Kdbx File**
Does it happen on Demo or New database?  
I think it has nothing to do with the database file. But i am using my existing db file stored in one drive

**Logs**
![image](https://user-images.githubusercontent.com/6030327/136682304-2ed9ed5f-7d2d-40e3-9823-29988d282cd9.png)

**Comment by antelle** [comment]
Hi! This needs to be adjusted in your OneDrive application setup.  
KeeWeb also supports `onedriveTenantId` setting so that you use your tenant instead of `common`.
