### ISSUE TITLE
No documentation on configuring custom browsers for Linux

### ISSUE THREAD

**Issue by juneflowers** [keeweb/keeweb#1920]
I'm currently using Ungoogled-Chromium on Ubuntu and trying to follow the custom browser docs but they are missing info specifically for Linux users. Most importantly the location of "keeweb-native-messaging-host" on Linux. I've searched /home/.local/share and /home/.config but didn't find anything and I'm unsure of where else to look.
I'd like to be able to use this extension.
![image](https://user-images.githubusercontent.com/63337938/136827438-bfaf5732-8466-4862-aa9e-5d0cb6c59c49.png)

**Comment by antelle** [comment]
`/usr/bin/keeweb` is a shortcut, it should be located `/usr/share/keeweb-desktop/` if I'm not mistaken.

**Comment by antelle** [comment]
Added it to wiki.
What does it say in the background page of the extension? You can inspect it from the browser extension settings.

**Comment by ducky710** [comment]
Sorry if I'm being dumb but this it outputs nothing here.
![image](https://user-images.githubusercontent.com/63337938/136995692-21eff384-ac99-4c9f-aee3-e58c4a21d6cb.png)

**Comment by antelle** [comment]
I can't help further, you should search how to install a manifest for your browser.

**Comment by dcm** [comment]
I have the same issue on macOS. Ungoogled Chromium on macOS is unsigned so that can cause issues. But .deb files are usually unsigned so not sure if that's it.

**Comment by LukasPietzschmann** [comment]
I just wanted to quickly check if some of you did figure out a solution to this?
I'm encountering the same problem and I could not come up with a workaround.
