### ISSUE TITLE
History of my keeweb file

### ISSUE THREAD

**Issue by maramekoukou** [keeweb/keeweb#1928]
Hello, firstly i'm not familiar at all with keeweb, 

a friend of mine is using keeweb, i dont know what he did, he cant explain (newbie) but when he's opening his keeweb file, we can see his entry but there is no additional informations or password for his entry, and no history (last modification date is the same than file creation)

he  was using keeweb weekly without problems before that day.

I dont know where his file was saved, seems it wasn't local (maybe keeweb cloud?), but is there any way to get a back up of his file?

Thanks everyone.

**Comment by antelle** [comment]
Hi! I don’t think I’ll be able to help.
I’d suggest trying to understand what happened. We don’t have our own cloud, it could be Dropbox, Google drive, OneDrive.
