### ISSUE TITLE
Linux system tray

### ISSUE THREAD

**Issue by HanneMaes** [keeweb/keeweb#1929]
Is it possible to have KeeWeb rum from the system tray on Linux and be able to activate the autofill shortcut from there?
I'm running Zorin OS (Ubuntu based).

**Comment by antelle** [comment]
Hi! It's is not possible to do anything from system tray now, apart from opening the full application.

**Comment by HanneMaes** [comment]
Thanks for the fast reply!
Is that feature planned for the future?

**Comment by antelle** [comment]
I don't think so

**Comment by HanneMaes** [comment]
Ok, and why not if I may ask?
