### ISSUE TITLE
Save to Google Drive fails,  OAuth error popup closed

### ISSUE THREAD

**Issue by squalou** [keeweb/keeweb#1934]
**Describe the bug**

Save to Google Drive fails silently. Error show in browser console.

I use a locally running version of keeweb from master head.

**To Reproduce**

1. Go to Save To
2. Click on Google Drive
3. Popup opens, google drive asks to trust keeweb  etc... (asks for auth first time, as expected)
4. Click Yes, popup closes
5. nothing is saved
6. error in browser console :  [storage-gdrive] OAuth error popup closed

**Expected behavior**

.kbdx file should be saved to google drive

**Screenshots**

![image](https://user-images.githubusercontent.com/4623644/142723261-b3a5a4a0-3490-4712-ac77-dc5def6b9a65.png)

**Environment**

Tried with
- linux OS, Firefox and Chromium
- windows 10 : Chrome

I'm opening index.html file produced by npm, as it's a convenient portable way to use keeweb. 

**Kdbx File**

Tried with a blank new file, on a laptop where keeweb was never used before, to make sure there was no cache issues.

**Logs**

```
2021-11-20T10:35:23.536Z [storage-gdrive] OAuth error popup closed index.html:1:450893
    error file:///home/someuser/someplace//KeeWeb/index.html:1
    m file:///home/someuser/someplace//KeeWeb/index.html:1
    emit file:///home/someuser/someplace//KeeWeb/index.html:1
    triggerClosed file:///home/someuser/someplace//KeeWeb/index.html:1
    checkClosed file:///home/someuser/someplace//KeeWeb/index.html:1
    deferCheckClosed file:///home/someuser/someplace//KeeWeb/index.html:1
    checkClosed file:///home/someuser/someplace//KeeWeb/index.html:1
    deferCheckClosed file:///home/someuser/someplace//KeeWeb/index.html:1
    checkClosed file:///home/someuser/someplace//KeeWeb/index.html:1
    deferCheckClosed file:///home/someuser/someplace//KeeWeb/index.html:1
    checkClosed file:///home/someuser/someplace//KeeWeb/index.html:1
    deferCheckClosed file:///home/someuser/someplace//KeeWeb/index.html:1
    checkClosed file:///home/someuser/someplace//KeeWeb/index.html:1
    deferCheckClosed file:///home/someuser/someplace//KeeWeb/index.html:1
    checkClosed file:///home/someuser/someplace//KeeWeb/index.html:1
    deferCheckClosed file:///home/someuser/someplace//KeeWeb/index.html:1
    checkClosed file:///home/someuser/someplace//KeeWeb/index.html:1
    deferCheckClosed file:///home/someuser/someplace//KeeWeb/index.html:1
    checkClosed file:///home/someuser/someplace//KeeWeb/index.html:1
    deferCheckClosed file:///home/someuser/someplace//KeeWeb/index.html:1
    checkClosed file:///home/someuser/someplace//KeeWeb/index.html:1
    deferCheckClosed file:///home/someuser/someplace//KeeWeb/index.html:1
    checkClosed file:///home/someuser/someplace//KeeWeb/index.html:1
    deferCheckClosed file:///home/someuser/someplace//KeeWeb/index.html:1
    checkClosed file:///home/someuser/someplace//KeeWeb/index.html:1
    deferCheckClosed file:///home/someuser/someplace//KeeWeb/index.html:1
    checkClosed file:///home/someuser/someplace//KeeWeb/index.html:1
    deferCheckClosed file:///home/someuser/someplace//KeeWeb/index.html:1
    checkClosed file:///home/someuser/someplace//KeeWeb/index.html:1
    deferCheckClosed file:///home/someuser/someplace//KeeWeb/index.html:1
    checkClosed file:///home/someuser/someplace//KeeWeb/index.html:1
    deferCheckClosed file:///home/someuser/someplace//KeeWeb/index.html:1
    checkClosed file:///home/someuser/someplace//KeeWeb/index.html:1
    deferCheckClosed file:///home/someuser/someplace//KeeWeb/index.html:1
    checkClosed file:///home/someuser/someplace//KeeWeb/index.html:1
    deferCheckClosed file:///home/someuser/someplace//KeeWeb/index.html:1
    checkClosed file:///home/someuser/someplace//KeeWeb/index.html:1
    deferCheckClosed file:///home/someuser/someplace//KeeWeb/index.html:1
    checkClosed file:///home/someuser/someplace//KeeWeb/index.html:1
    deferCheckClosed file:///home/someuser/someplace//KeeWeb/index.html:1
    open file:///home/someuser/someplace//KeeWeb/index.html:1
    _openPopup file:///home/someuser/someplace//KeeWeb/index.html:1
    _oauthAuthorize file:///home/someuser/someplace//KeeWeb/index.html:1
    list file:///home/someuser/someplace//KeeWeb/index.html:1
    saveToStorage file:///home/someuser/someplace//KeeWeb/index.html:1
    eventListener file:///home/someuser/someplace//KeeWeb/index.html:1
    e file:///home/someuser/someplace//KeeWeb/index.html:1
```

**Comment by antelle** [comment]
Hi! Does the same work on:
- app.keeweb.info
- localhost
?

**Comment by squalou** [comment]
Damn, you did well to ask : it works when using local web server, I mean  `npm run dev` then localhost:8085

That would possibly be a limitation due to trying to use everything-from-html file ? 
(and fixing this is probably not even feasible)


Let me explain my use case maybe you'll have a brilliant idea.
- I usually take index.html file (found in /dist after compilation) and carry it with me, on a usb stick or on my phone
- this way i have a 'cheap' app I can use on any PC
- I even open index.html from my phone, works like a charm

never tried to save to cloud ever since today.

Now, for PC use that's not an issue. (I can save files easily enough to places synced to whataver)

But for a phone, what would you suggest ?

**Comment by antelle** [comment]
I see, I don't think it will be possible to fix this at all for `file://`.
For phone, if you would like to use KeeWeb, it's probably better to host it somewhere.

**Comment by squalou** [comment]
you're right, no only I don't see how it could be 'fixed', and honestly my case is so off-the-charts that I would'nt really ask for it :-)

And I only just discovered app.keeweb.info that does the job, at least unless I really want to host it myslef (I can I do have web servers easily available)

Thank you !
