### ISSUE TITLE
Documentation Request webdav 

### ISSUE THREAD

**Issue by thefiredragon** [keeweb/keeweb#1935]
A long time ago I requestet if its possible on self hosted keeweb to prevent access to webdav.

I noticed if keeweb is running behind a proxy webdav can't be reached, People on the Internet can See webdav ip or fqdn with password but can't reach this.

I only proxy the webadress of keeweb and not the webadress of webdav over ipv4.

Perhpahs someone Here also like to know my experiance

**Comment by antelle** [comment]
Hi! What do you mean as "prevent access to webdav"? You can for example hide the webdav button, is that what you're looking for?

**Comment by thefiredragon** [comment]
No this I dont mean, hiding Button I know, I have a config file created to use a kdbx stored on webdav.

A long time ago I asked something to prevent that everyone can See over development Tools the secrets for webdav so everyone can with little Knowlege access the webdav server.

I use a container for keeweb and a container as proxy 'cause I have only one static ipv4.

For webdav internal I have
webdav.danshome.de

and keeweb.danshome.de

If I proxy only keeweb.danshome.de, keeweb is working, can access webdav internal.

External webdav is not reachable. 
You know what I mean?

If someone ask like in the past that the login secrets can everyone read over the kwconfig json.

**Comment by antelle** [comment]
I see, yeah. So, what is your question? I didn't quite get what you mean. You can indeed combine internal/external proxying/dns with different ways.

**Comment by thefiredragon** [comment]
Perhaps u like to describe it for someone on keeweb wiki this I mean 🥰

**Comment by antelle** [comment]
Ok, added a short note to https://github.com/keeweb/keeweb/wiki/WebDAV-Config
