### ISSUE TITLE
Help needed : self hosting on S3 (js errors happen)

### ISSUE THREAD

**Issue by squalou** [keeweb/keeweb#1936]
This is not a feature request, nor a bug :-)

AWS S3 can act as a static web server. I've used it a lot.
Si, I did as usual (everything is well documented for this anyway)

Thing is : in the end it does'nt work, to my great surprise.

Any help would be appreciated, be it to help me debug things.

I've built from source, started a local http server (python for instance) => works great.
Transferred files to a properly configure s3 bucket=> error. below

Did the same with https://codeload.github.com/keeweb/keeweb/zip/gh-pages 

same result

![image](https://user-images.githubusercontent.com/4623644/142735627-1a9282d3-b6ea-4215-b801-6ef0f4ed4afa.png)

**Comment by squalou** [comment]
Post Scriptum : I'm not asking for help about S3,
just some clues on keeweb itself to try to understand / try to find what causes this error.

**Comment by squalou** [comment]
``

**Comment by antelle** [comment]
was it https or http? keeweb won’t work on http

**Comment by squalou** [comment]
That's obviously the reason !
thank you, closing
