### ISSUE TITLE
Autotype [feature request]

### ISSUE THREAD

**Issue by fuzzybear3965** [keeweb/keeweb#194]
KeePass comes with the ability to autotype passwords (<kbd>Ctrl-v</kbd>). I have seen a request to implement autotyping of passwords using a Chrome plugin but not a request to implement this as an OS-level feature. Could/Will this be implemented?

**Comment by antelle** [comment]
This will be implemented in v1.2 (please see [TODO](https://github.com/antelle/keeweb/wiki/TODO)). Actually, this is the feature I'm working on now. Actually, the basic support for mac is already here (however VERY buggy for now).

**Comment by fuzzybear3965** [comment]
Hm, I could have sworn that I checked both v1.1 and v1.2 milestones already and didn't see that. Well, I see it now! Thanks for the head-up.

<kbd>⌘</kbd><kbd>Ctrl</kbd><kbd>t</kbd> is what you plan on supporting for Macs. What keyboard shortcut do you plan on using for Windows and Linux? If I have a vote, I'm requesting <kbd>Ctrl</kbd><kbd>v</kbd>. It's standard and, as such, is easy to remember.

**Comment by antelle** [comment]
Inside the app: cmd-T on mac, ctrl-T on windows and linux
Global: ctrl-alt-T on mac, shift-alt-T on windows and linux
No, ctrl-v is paste and it mustn't be used for anything else.

**Comment by fuzzybear3965** [comment]
Alright, alright. <kbd>Ctrt</kbd><kbd>t</kbd> - auto**T**ype - sounds good. Haha, I agree that KeePass' established convention doesn't make a ton of sense given <kbd>Ctrl</kbd><kbd>v</kbd> is paste in, literally, every other GUI context.

**Comment by antelle** [comment]
I expect to finish the first implementation in a week or two, I'll write here once the first beta is available. Here are the supported commands and substitutions: https://github.com/antelle/keeweb/wiki/Auto-Type

**Comment by Loilo** [comment]
It's actually pretty amazing that's event possible with Electron. Is there an npm module doing something like that or do you actually write and compile some native module yourself for that purpose?

**Comment by antelle** [comment]
@Loilo  we'll use:
- osascript on mac
- powershell on windows
- xdotool on linux

You can preview the implementation [here](https://github.com/antelle/keeweb/tree/develop/app/scripts/comp/auto-type/emitter) (for linux it's not finished yet).
Currently I'm ok with it but I haven't tested it in details. If there are any serious fatal issues with Windows implementation (e.g. script execution blocked by default), it could be replaced by a native module.

**Comment by Loilo** [comment]
That sounds like the ingredients for an awesome future npm module. :)

**Comment by fuzzybear3965** [comment]
@antelle, keep up the good work. I'm excited for v1.2.

**Comment by pwFoo** [comment]
Improved auto type selection by a contained string that isn't the title field. Would be great to set a meaningful title and another field used for autotype.

**Comment by antelle** [comment]
@pwFoo sorry, I didn't understand you. What do you mean?

**Comment by pwFoo** [comment]
Hi @antelle,
Keepass(x) works with title field to select the entry used for autotype. So the entry title field have to match the website title. Many websites use titles like "login" instead of the site / domain name.
I would prefer meaningful entry titles in keepass / keeweb instead of keepass entry title like "login" to get autotype working.

**Comment by antelle** [comment]
You mean the case when you click auto-type hotkey in a browser, right? Then keepass tries to find the matching entry by title (and shows entry selection dialog if several are found). Your suggestion is to use another field, to find matching entry. Right?

**Comment by Loilo** [comment]
The problem is that the actual need would be to access the current website's domain instead of the browser window's title. But I don't know if there's actually a sane way to achieve this.

The more reasonable approach would probably be to make a browser extension which listens to the autotype shortcut and passes the current domain to keeweb.

**Comment by antelle** [comment]
I'm going to use the following algorithm (here's the pseudocode):
```javascript
title, url = getActiveWindowTitleAndUrl()
if not title and not url
  showAllRecords(); exit
if url
  entries = getByDomain(url)
  if (entries.length = 1) exit
  entries = filterByTitle(entries)
  if (entries.length = 1) exit
  showSelectFrom(entries); exit
if title
  entries = getMatchByTitle()
  if (entries.length = 1) exit
showSelectFrom(entries)
```
For Mac OS X, we get can get window title and url for Chrome and Safari, it's already implemented [here](https://github.com/antelle/keeweb/blob/develop/app/scripts/auto-type/helper/auto-type-helper-darwin.js), for Windows we'll get titles and urls with a powershell script, the way to get it is described [here](https://autohotkey.com/boards/viewtopic.php?t=3702). For linux - needs investigation.

**Comment by antelle** [comment]
Just implemented getting browser url for windows with UI automation, works for all mainstream browsers. As I expected, powershell scripts are too slow (about 5..6 sec on my machine), so a small helper app will be used instead.

**Comment by ulich** [comment]
https://github.com/perfectapi/CKP is a project that implemented a keepass chrome plugin with auto-fill functionality, no additional plugins required.

maybe it is worth having a look (at least for chrome). wouldn't some solution like this be a better approach for users that install keeweb as a browser extension?

**Comment by antelle** [comment]
For now, there are no plans for extensions. Later we'll think about integration with existing extensions or creating them.
