### ISSUE TITLE
Can I use the KeeWeb with the menu bar in Mac ?

### ISSUE THREAD

**Issue by faboxe** [keeweb/keeweb#1942]
sometimes I can't use the KeeWeb-connect in the web (some mail and shopping web) and application. so I just wonder if I can use the KeeWeb with the menu bar by search which just like the way the 1password do. but I can not find the KeeWeb in the menu bar, if there is a way to solve this problem? 
if not, please tell me. thanks a lot.
<img width="1018" alt="Snipaste_2021-12-03_21-33-30" src="https://user-images.githubusercontent.com/93846761/144610983-4ee8cac2-a6a8-44cb-9663-a608b84c3a6a.png">

**Comment by antelle** [comment]
Hi! KeeWeb doesn't support this kind of integration for now.
