### ISSUE TITLE
KeepassRPC support

### ISSUE THREAD

**Issue by ukch** [keeweb/keeweb#1947]
I noticed KeepassRPC was briefly mentioned in #874 but was not really discussed. So I'm bringing it up here.

I use the 'Kee' browser addon which is excellent and integrates with the core Keepass software by use of the KeepassRPC plugin. I have recently switched to using a Mac and would like to keep using this addon because it is better than any other Keepass addon that I have tried. However, the core Keepass software is not readily available on the Mac (without using ugly workarounds). This led me to your project - I am very happy with your desktop app so far and noticed it has a plugin infrastructure. As far as I understand, KeepassRPC is now the official way to build browser extensions for Keepass (replacing the old KeepassHTML), and I wonder if you would consider adding a plugin so I can use my favourite browser extension with your desktop app?

**Comment by antelle** [comment]
Hi! This protocol won't be supported. Now you can choose between KeeWeb-Connect and KeePassXC-Browser extensions that should be supported in all modern browsers.
