### ISSUE TITLE
ykman isn't recognized from the system

### ISSUE THREAD

**Issue by htd-tstepien** [keeweb/keeweb#1952]
**Describe the bug**  
So I want to add hardware key to my db but KeeWeb in the "Devices" says that ykman isn't installed - even tho I have installed YubiKey Manager 1.2.4. Should I add PATH somewhere to the YubiKey Manager? Also I get console error about loading ykman (screenshot below)

**To Reproduce**  

1.  Insert YubiKey to your PC + install YubiKey Manager
2.  Go to Devices
3.  There is no option for YubiKey

**Expected behavior**  
YubiKey option is visible in the KeeWeb

**Screenshots**  
YubiKey manager

![](https://user-images.githubusercontent.com/57900160/146172857-adb75767-7b12-4e69-a853-4dd4177165fd.png)

Information about no ykman

![](https://user-images.githubusercontent.com/57900160/146172982-17e307ff-a1ca-49dd-991d-cdcc4372e011.png)

**Environment**

*   Windows 10, 20H2

**Kdbx File**  
Does it happen on Demo or New database?  
If you have a test db without your personal data, please attach it.

**Logs**  

![](https://user-images.githubusercontent.com/57900160/146173146-2a2ae6c7-6a66-4b42-885a-2b7cc83c8f81.png)

**Comment by antelle** [comment]
Hi! You also need to install `ykman` command line tool, I remember it was a separate thing on Windows.

**Comment by htd-tstepien** [comment]
@antelle weird - I have installed CLI and still nothing  
\`\`\`  
C:\\Users\\Tymek>pip list  
Package         Version  
\--------------- -------  
cffi            1.15.0  
click           8.0.3  
colorama        0.4.4  
cryptography    3.4.8  
fido2           0.9.3  
pip             21.3.1  
pycparser       2.21  
pyOpenSSL       21.0.0  
pyscard         2.0.2  
pywin32         302  
setuptools      59.6.0  
six             1.16.0  
yubikey-manager 4.0.7  
\`\`\`

**Comment by antelle** [comment]
Is `ykman` available in the command prompt?

**Comment by htd-tstepien** [comment]
Hmm no, it's as package in python so when I run `python -m ykman` I get `No module named ykman.__main__; 'ykman' is a package and cannot be directly executed`. When trying to run `ykman` itself I get `'ykman' is not recognized as an internal or external command,`  
`operable program or batch file.` - even tho I have installed it properly

**Comment by antelle** [comment]
So, you should install the `ykman` tool, I don't remember how to do it on Windows.

**Comment by htd-tstepien** [comment]
Hmmm weird, because I used [this](https://docs.yubico.com/software/yubikey/tools/ykman/Install_ykman.html) (I know this isn't topic for this) manual (with `pip`) and... nothing. If they hid somewhere config I'd be very upset because it's almost impossible for now to do anything with CLI. I can add normally in GUI stuff but not in CLI... weird, I'll try to fight with this more then...

**Comment by htd-tstepien** [comment]
@antelle - ok resolved, they are lack in docs about that PATH isn't setup during installation

![](https://user-images.githubusercontent.com/57900160/146530793-1113d2a8-00c4-4178-b034-c8b06ffb070b.png)
