### ISSUE TITLE
Building on Apple Silicon

### ISSUE THREAD

**Issue by robin-moser** [keeweb/keeweb#1953]
Hi,

first of all, thanks for your work on this fantastic project! 
I tried to build the desktop app on MacOS myself, but the built app crashes at startup with following code signing error:

```
EXC_BAD_ACCESS (SIGKILL (Code Signature Invalid))
```

<details>
  <summary>Full error Report</summary>
-------------------------------------
Translated Report (Full Report Below)
-------------------------------------

Process:               KeeWeb [6536]
Path:                  /Users/USER/*/KeeWeb.app/Contents/MacOS/KeeWeb
Identifier:            net.antelle.keeweb
Version:               1.18.7 (dfc62012)
Code Type:             ARM-64 (Native)
Parent Process:        bash [91529]
User ID:               501

Date/Time:             2021-12-16 13:54:13.9904 +0100
OS Version:            macOS 12.0.1 (21A559)
Report Version:        12
Anonymous UUID:        3F7C1375-706B-EE5B-A51F-79BC3BEDDE73

Sleep/Wake UUID:       F1FF5F41-DE15-48CA-92CE-C89F9CEF3AF4

Time Awake Since Boot: 500000 seconds
Time Since Wake:       14805 seconds

System Integrity Protection: enabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_ACCESS (SIGKILL (Code Signature Invalid))
Exception Codes:       UNKNOWN_0x32 at 0x0000000112a87d9e
Exception Codes:       0x0000000000000032, 0x0000000112a87d9e
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    Namespace CODESIGNING, Code 2 

VM Region Info: 0x112a87d9e is in 0x10c804000-0x113838000;  bytes after start: 103300510  bytes before end: 14352993
      REGION TYPE                    START - END         [ VSIZE] PRT/MAX SHRMOD  REGION DETAIL
      __LINKEDIT                  1057c4000-1057e8000    [  144K] r--/rwx SM=COW  ...bffmpeg.dylib
      GAP OF 0x701c000 BYTES
--->  __TEXT                      10c804000-113838000    [112.2M] r-x/rwx SM=COW  ...ron Framework
      __DATA_CONST                113838000-113cec000    [ 4816K] r--/rwx SM=COW  ...ron Framework

Thread 0 Crashed::  Dispatch queue: com.apple.main-thread
0   libsystem_c.dylib				       0x1ba09684c __findenv_locked + 16
1   libsystem_c.dylib				       0x1ba096810 getenv + 64
2   Electron Framework				       0x10c983f70 ElectronInitializeICUandStartNode + 1473940
3   libobjc.A.dylib					       0x1ba05f5c0 load_images + 1088
4   dyld							       0x104edf9a8 dyld4::RuntimeState::notifyObjCInit(dyld4::Loader const*) + 164
5   dyld							       0x104ee5cf4 dyld4::Loader::runInitializersBottomUp(dyld4::RuntimeState&, dyld3::Array<dyld4::Loader const*>&) const + 196
6   dyld							       0x104ee5cdc dyld4::Loader::runInitializersBottomUp(dyld4::RuntimeState&, dyld3::Array<dyld4::Loader const*>&) const + 172
7   dyld							       0x104ee5dcc dyld4::Loader::runInitializersBottomUpPlusUpwardLinks(dyld4::RuntimeState&) const + 124
8   dyld							       0x104efadb4 dyld4::APIs::runAllInitializersForMain() + 312
9   dyld							       0x104ed5e00 dyld4::prepare(dyld4::APIs&, dyld3::MachOAnalyzer const*) + 3100
10  dyld							       0x104ed50d4 start + 488

Thread 0 crashed with ARM Thread State (64-bit):
    x0: 0x0000000112a87d9e   x1: 0x000000016b2fa1bc   x2: 0x000000016b2fee80   x3: 0xfffffffffffffff2
    x4: 0x000000000000004c   x5: 0x0000000000000044   x6: 0x0000000000000000   x7: 0x00000000000008d0
    x8: 0x0000000000000000   x9: 0x0000000104f40660  x10: 0x0000000210202e9c  x11: 0x0000000112a77149
   x12: 0x000000008261e7fb  x13: 0x000000000261e000  x14: 0x0000000002600000  x15: 0x0000000212ead4c8
   x16: 0x00000001ba1e54c0  x17: 0x00000002145b1dc8  x18: 0x0000000000000000  x19: 0x0000000112a87d9e
   x20: 0x00000002102080b0  x21: 0x00000001ba08cf4a  x22: 0x000000010c983f50  x23: 0x0000000210202000
   x24: 0x0000600003a6c200  x25: 0x00000002043f9fa3  x26: 0x0000000113d13a60  x27: 0x0000000210202000
   x28: 0x0000000210202000   fp: 0x000000016b2fa1d0   lr: 0x00000001ba096810
    sp: 0x000000016b2fa1b0   pc: 0x00000001ba09684c cpsr: 0x60000000
   far: 0x0000000112a87d9e  esr: 0x92000007 (Data Abort) byte read Translation fault

Binary Images:
       0x1ba095000 -        0x1ba115fff libsystem_c.dylib (*) <002a39ae-6431-3b2e-85e7-c45fc2f95ad0> /usr/lib/system/libsystem_c.dylib
       0x10c804000 -        0x113837fff com.github.Electron.framework (*) <cdf482cd-6a7f-3a1e-8ddc-98212962ae5a> /Users/USER/*/KeeWeb.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework
       0x1ba056000 -        0x1ba091fff libobjc.A.dylib (*) <2eabed7f-1e81-3a1b-bb4b-985b8dd3b77f> /usr/lib/libobjc.A.dylib
       0x104ed0000 -        0x104f2ffff dyld (*) <86a8ba48-8bb4-3b30-9cda-051f73c74f44> /usr/lib/dyld

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0

VM Region Summary:
ReadOnly portion of Libraries: Total=1.1G resident=0K(0%) swapped_out_or_unallocated=1.1G(100%)
Writable regions: Total=543.7M written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=543.7M(100%)

VIRTUAL   REGION 
REGION TYPE                        SIZE    COUNT (non-coalesced) 
===========                     =======  ======= 
Activity Tracing                   256K        1 
Kernel Alloc Once                   32K        1 
MALLOC                           146.2M       13 
MALLOC guard page                   96K        5 
MALLOC_NANO (reserved)           384.0M        1         reserved VM address space (unallocated)
STACK GUARD                       56.0M        1 
Stack                             8176K        1 
VM_ALLOCATE                        1.0G        1 
__AUTH                            2548K      307 
__AUTH_CONST                      19.4M      492 
__DATA                            19.6M      485 
__DATA_CONST                      22.5M      502 
__DATA_DIRTY                      1761K      211 
__FONT_DATA                          4K        1 
__LINKEDIT                       573.9M        8 
__OBJC_CONST                      3541K      272 
__OBJC_RO                         81.8M        1 
__OBJC_RW                         3088K        1 
__TEXT                           579.7M      519 
__UNICODE                          588K        1 
dyld private memory               1024K        1 
shared memory                       32K        2 
===========                     =======  ======= 
TOTAL                              2.9G     2827 
TOTAL, minus reserved VM space     2.5G     2827 

-----------
Full Report
-----------

{"app_name":"KeeWeb","timestamp":"2021-12-16 13:54:14.00 +0100","app_version":"1.18.7","slice_uuid":"25927884-fdc1-341f-9c15-ade8d0092b78","build_version":"dfc62012","platform":1,"bundleID":"net.antelle.keeweb","share_with_app_devs":0,"is_first_party":0,"bug_type":"309","os_version":"macOS 12.0.1 (21A559)","incident_id":"15A7454F-8B63-4306-8C2B-56351B2713BA","name":"KeeWeb"}
{
  "uptime" : 500000,
  "procLaunch" : "2021-12-16 13:54:13.0828 +0100",
  "procRole" : "Unspecified",
  "version" : 2,
  "userID" : 501,
  "deployVersion" : 210,
  "modelCode" : "MacBookPro18,3",
  "procStartAbsTime" : 12133808074189,
  "coalitionID" : 624,
  "osVersion" : {
    "train" : "macOS 12.0.1",
    "build" : "21A559",
    "releaseType" : "User"
  },
  "captureTime" : "2021-12-16 13:54:13.9904 +0100",
  "incident" : "15A7454F-8B63-4306-8C2B-56351B2713BA",
  "bug_type" : "309",
  "pid" : 6536,
  "procExitAbsTime" : 12133829845444,
  "translated" : false,
  "cpuType" : "ARM-64",
  "procName" : "KeeWeb",
  "procPath" : "\/Users\/USER\/*\/KeeWeb.app\/Contents\/MacOS\/KeeWeb",
  "bundleInfo" : {"CFBundleShortVersionString":"1.18.7","CFBundleVersion":"dfc62012","CFBundleIdentifier":"net.antelle.keeweb"},
  "storeInfo" : {"deviceIdentifierForVendor":"1AD0BF17-9F07-5A30-9C9E-998076DA2ED4","thirdParty":true},
  "parentProc" : "bash",
  "parentPid" : 91529,
  "coalitionName" : "com.googlecode.iterm2",
  "crashReporterKey" : "3F7C1375-706B-EE5B-A51F-79BC3BEDDE73",
  "responsiblePid" : 570,
  "wakeTime" : 14805,
  "sleepWakeUUID" : "F1FF5F41-DE15-48CA-92CE-C89F9CEF3AF4",
  "sip" : "enabled",
  "vmRegionInfo" : "0x112a87d9e is in 0x10c804000-0x113838000;  bytes after start: 103300510  bytes before end: 14352993\n      REGION TYPE                    START - END         [ VSIZE] PRT\/MAX SHRMOD  REGION DETAIL\n      __LINKEDIT                  1057c4000-1057e8000    [  144K] r--\/rwx SM=COW  ...bffmpeg.dylib\n      GAP OF 0x701c000 BYTES\n--->  __TEXT                      10c804000-113838000    [112.2M] r-x\/rwx SM=COW  ...ron Framework\n      __DATA_CONST                113838000-113cec000    [ 4816K] r--\/rwx SM=COW  ...ron Framework",
  "isCorpse" : 1,
  "exception" : {"codes":"0x0000000000000032, 0x0000000112a87d9e","rawCodes":[50,4607999390],"type":"EXC_BAD_ACCESS","signal":"SIGKILL (Code Signature Invalid)","subtype":"UNKNOWN_0x32 at 0x0000000112a87d9e"},
  "termination" : {"namespace":"CODESIGNING","flags":0,"code":2},
  "vmregioninfo" : "0x112a87d9e is in 0x10c804000-0x113838000;  bytes after start: 103300510  bytes before end: 14352993\n      REGION TYPE                    START - END         [ VSIZE] PRT\/MAX SHRMOD  REGION DETAIL\n      __LINKEDIT                  1057c4000-1057e8000    [  144K] r--\/rwx SM=COW  ...bffmpeg.dylib\n      GAP OF 0x701c000 BYTES\n--->  __TEXT                      10c804000-113838000    [112.2M] r-x\/rwx SM=COW  ...ron Framework\n      __DATA_CONST                113838000-113cec000    [ 4816K] r--\/rwx SM=COW  ...ron Framework",
  "extMods" : {"caller":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"system":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"targeted":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"warnings":0},
  "faultingThread" : 0,
  "threads" : [{"triggered":true,"id":70069374,"threadState":{"x":[{"value":4607999390},{"value":6093251004},{"value":6093270656},{"value":18446744073709551602},{"value":76},{"value":68},{"value":0},{"value":2256},{"value":0},{"value":4378068576,"symbolLocation":224,"symbol":"_main_thread"},{"value":8860479132,"symbolLocation":0,"symbol":"runtimeLock"},{"value":4607930697},{"value":2187454459},{"value":39968768},{"value":39845888},{"value":8907314376,"symbolLocation":0,"symbol":"__CFConstantStringClassReference"},{"value":7417517248,"symbolLocation":0,"symbol":"os_unfair_lock_lock_with_options"},{"value":8931450312},{"value":0},{"value":4607999390},{"value":8860500144,"symbolLocation":0,"symbol":"__environ_lock_obj"},{"value":7416106826},{"value":4506271568,"symbolLocation":1473908,"symbol":"ElectronInitializeICUandStartNode"},{"value":8860475392,"symbolLocation":5920,"symbol":"read_memory"},{"value":105553177526784},{"value":8661213091,"objc-selector":"load"},{"value":4627446368},{"value":8860475392,"symbolLocation":5920,"symbol":"read_memory"},{"value":8860475392,"symbolLocation":5920,"symbol":"read_memory"}],"flavor":"ARM_THREAD_STATE64","lr":{"value":7416145936},"cpsr":{"value":1610612736},"fp":{"value":6093251024},"sp":{"value":6093250992},"esr":{"value":2449473543,"description":"(Data Abort) byte read Translation fault"},"pc":{"value":7416145996,"matchesCrashFrame":1},"far":{"value":4607999390}},"queue":"com.apple.main-thread","frames":[{"imageOffset":6220,"symbol":"__findenv_locked","symbolLocation":16,"imageIndex":0},{"imageOffset":6160,"symbol":"getenv","symbolLocation":64,"imageIndex":0},{"imageOffset":1572720,"symbol":"ElectronInitializeICUandStartNode","symbolLocation":1473940,"imageIndex":1},{"imageOffset":38336,"symbol":"load_images","symbolLocation":1088,"imageIndex":2},{"imageOffset":63912,"symbol":"dyld4::RuntimeState::notifyObjCInit(dyld4::Loader const*)","symbolLocation":164,"imageIndex":3},{"imageOffset":89332,"symbol":"dyld4::Loader::runInitializersBottomUp(dyld4::RuntimeState&, dyld3::Array<dyld4::Loader const*>&) const","symbolLocation":196,"imageIndex":3},{"imageOffset":89308,"symbol":"dyld4::Loader::runInitializersBottomUp(dyld4::RuntimeState&, dyld3::Array<dyld4::Loader const*>&) const","symbolLocation":172,"imageIndex":3},{"imageOffset":89548,"symbol":"dyld4::Loader::runInitializersBottomUpPlusUpwardLinks(dyld4::RuntimeState&) const","symbolLocation":124,"imageIndex":3},{"imageOffset":175540,"symbol":"dyld4::APIs::runAllInitializersForMain()","symbolLocation":312,"imageIndex":3},{"imageOffset":24064,"symbol":"dyld4::prepare(dyld4::APIs&, dyld3::MachOAnalyzer const*)","symbolLocation":3100,"imageIndex":3},{"imageOffset":20692,"symbol":"start","symbolLocation":488,"imageIndex":3}]}],
  "usedImages" : [
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 7416139776,
    "size" : 528384,
    "uuid" : "002a39ae-6431-3b2e-85e7-c45fc2f95ad0",
    "path" : "\/usr\/lib\/system\/libsystem_c.dylib",
    "name" : "libsystem_c.dylib"
  },
  {
    "source" : "P",
    "arch" : "arm64",
    "base" : 4504698880,
    "CFBundleIdentifier" : "com.github.Electron.framework",
    "size" : 117653504,
    "uuid" : "cdf482cd-6a7f-3a1e-8ddc-98212962ae5a",
    "path" : "\/Users\/USER\/*\/KeeWeb.app\/Contents\/Frameworks\/Electron Framework.framework\/Versions\/A\/Electron Framework",
    "name" : "Electron Framework",
    "CFBundleVersion" : "12.0.7"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 7415881728,
    "size" : 245760,
    "uuid" : "2eabed7f-1e81-3a1b-bb4b-985b8dd3b77f",
    "path" : "\/usr\/lib\/libobjc.A.dylib",
    "name" : "libobjc.A.dylib"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 4377608192,
    "size" : 393216,
    "uuid" : "86a8ba48-8bb4-3b30-9cda-051f73c74f44",
    "path" : "\/usr\/lib\/dyld",
    "name" : "dyld"
  }
],
  "sharedCache" : {
  "base" : 7414235136,
  "size" : 3072180224,
  "uuid" : "a6162d66-93e3-3251-93cc-b11f7c8c830e"
},
  "vmSummary" : "ReadOnly portion of Libraries: Total=1.1G resident=0K(0%) swapped_out_or_unallocated=1.1G(100%)\nWritable regions: Total=543.7M written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=543.7M(100%)\n\n                                VIRTUAL   REGION \nREGION TYPE                        SIZE    COUNT (non-coalesced) \n===========                     =======  ======= \nActivity Tracing                   256K        1 \nKernel Alloc Once                   32K        1 \nMALLOC                           146.2M       13 \nMALLOC guard page                   96K        5 \nMALLOC_NANO (reserved)           384.0M        1         reserved VM address space (unallocated)\nSTACK GUARD                       56.0M        1 \nStack                             8176K        1 \nVM_ALLOCATE                        1.0G        1 \n__AUTH                            2548K      307 \n__AUTH_CONST                      19.4M      492 \n__DATA                            19.6M      485 \n__DATA_CONST                      22.5M      502 \n__DATA_DIRTY                      1761K      211 \n__FONT_DATA                          4K        1 \n__LINKEDIT                       573.9M        8 \n__OBJC_CONST                      3541K      272 \n__OBJC_RO                         81.8M        1 \n__OBJC_RW                         3088K        1 \n__TEXT                           579.7M      519 \n__UNICODE                          588K        1 \ndyld private memory               1024K        1 \nshared memory                       32K        2 \n===========                     =======  ======= \nTOTAL                              2.9G     2827 \nTOTAL, minus reserved VM space     2.5G     2827 \n",
  "legacyInfo" : {
  "threadTriggered" : {
    "queue" : "com.apple.main-thread"
  }
},
  "trialInfo" : {
  "rollouts" : [
    {
      "rolloutId" : "607844aa04477260f58a8077",
      "factorPackIds" : {
        "SIRI_MORPHUN_ASSETS" : "6103050cbfe6dc472e1c982a"
      },
      "deploymentId" : 240000066
    },
    {
      "rolloutId" : "60da5e84ab0ca017dace9abf",
      "factorPackIds" : {

      },
      "deploymentId" : 240000008
    },
    {
      "rolloutId" : "602ad4dac86151000cf27e46",
      "factorPackIds" : {
        "SIRI_DICTATION_ASSETS" : "61ae8d06da72d16a4beb762e"
      },
      "deploymentId" : 240000290
    },
    {
      "rolloutId" : "5ffde50ce2aacd000d47a95f",
      "factorPackIds" : {

      },
      "deploymentId" : 240000086
    },
    {
      "rolloutId" : "601d9415f79519000ccd4b69",
      "factorPackIds" : {
        "SIRI_TEXT_TO_SPEECH" : "61b913a253a0785760dd8bbb"
      },
      "deploymentId" : 240000341
    },
    {
      "rolloutId" : "5fc94383418129005b4e9ae0",
      "factorPackIds" : {

      },
      "deploymentId" : 240000185
    }
  ],
  "experiments" : [

  ]
}
}
</details>

---

I built it with:

```bash

nvm use 16 # using node V16.13.1

npm ci

grunt desktop-darwin --skip-sign
```

The built X64 app works (emulated with Rosetta2), its only the Arm64 version that fails.

```bash
./tmp/desktop/KeeWeb-darwin-arm64/KeeWeb.app/Contents/MacOS/KeeWeb
# Killed: 9
## [Error Report pops up]
```

Do you have an idea, what could cause the issue?

**Comment by antelle** [comment]
Hi! You should
1. replace the entitlements with yours
2. sign the app

**Comment by robin-moser** [comment]
Can I run the app locally without signing it, but without the app crashing? I know from some other downloaded applications, that you can shift+open an unsigned app to allow its execution, but this doesn't work here.

**Comment by antelle** [comment]
Yes you can, but you need to delete entitlements, and Touch ID also won't work. Otherwise macOS sees that there's an unsatisfied assertion and doesn't let the app to start. There's no instruction how to do it, you need to dig a bit because I also forgot what exactly you need to change.

**Comment by robin-moser** [comment]
Alright no problem, thanks for your help!
