### ISSUE TITLE
Non-gallery plugins always produce a public key mismatch

### ISSUE THREAD

**Issue by GrantMoyer** [keeweb/keeweb#1954]
**Describe the bug**
Since plugins' public keys are only checked against a fixed list, they always produce a public key mismatch. See:

- [app/scripts/plugins/plugin.js:108][1]
- [keeweb/app/scripts/util/data/signature-verifier.js:64][2]

This prevents plugins from installing (on page reload) or updating.

[1]: https://github.com/keeweb/keeweb/blob/dfc6201285ec1dfecd2e8f80363d82811e75bc6d/app/scripts/plugins/plugin.js#L108
[2]: https://github.com/keeweb/keeweb/blob/dfc6201285ec1dfecd2e8f80363d82811e75bc6d/app/scripts/util/data/signature-verifier.js#L64

**To Reproduce**
1. Go to Settings > Plugins
2. Install plugin from https://grantmoyer.github.io/keeweb-plugin-passphrase-generator/
3. Open javascript console
4. Reload page
5. Observe error: `[plugin:passphrase-generator] Manifest validation error Public key mismatch`

**Expected behavior**
KeeWeb should persist each plugin's public key, and check against that.

**Environment**
KeeWeb v1.18.7 (dfc6201, 2021-07-18)
Environment: web
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:95.0) Gecko/20100101 Firefox/95.0

**Kdbx File**
No database needs to be opened

**Logs**
<details>

```
2021-12-19T00:17:55.651Z [plugin:passphrase-generator] Manifest validation error Public key mismatch logger.js:59:16
    error logger.js:59
    install plugin.js:54
    (Async: promise callback)
    install plugin.js:51
    loadPlugin plugin-manager.js:198
    promises plugin-manager.js:36
    init plugin-manager.js:36
    (Async: promise callback)
    init plugin-manager.js:35
    (Async: promise callback)
    init plugin-manager.js:24
    initModules app.js:100
    (Async: promise callback)
    js app.js:45
    jQuery 13
    Webpack 15
```

</details>

**Comment by antelle** [comment]
Hi! Yes, custom plugins can be for now permanently added only in self-hosted installations using a config file.
