### ISSUE TITLE
Autotyper Help

### ISSUE THREAD

**Issue by artemis8888** [keeweb/keeweb#1958]
I created an auto typer that works, but I can't leave the window that its on. I don't know how to make a auto typer that works when you leave the window its working on. 

Below is my auto typer.

tell application "System Events"
		set texttosay to "Sample Text"
		display dialog "Text to type:" default answer "pls"
		set texttosay to the text returned of the result
		repeat
			activate application "Discord"
			repeat 1000 times
				delay 2
				keystroke texttosay
				key code 49
				key code 11
				key code 14
				key code 5
				delay 2
				keystroke return
				delay 2
				keystroke texttosay
				key code 49
				key code 4
				key code 32
				key code 45
				key code 17
				delay 2
				keystroke return
				delay 2
				keystroke texttosay
				key code 49
				key code 3
				key code 34
				key code 1
				key code 4
				delay 2
				keystroke return
				delay 2
				keystroke texttosay
				key code 49
				key code 2
				key code 34
				key code 5
				delay 8
				keystroke return
				
			end repeat
			
			display dialog the "Do you want to quit?" buttons {"Continue", "Quit"} default button 1
			if the button returned of the result is "Quit" then
				exit repeat
			end if
		end repeat
	end tell

**Comment by antelle** [comment]
Hi! I don't think it has anything to do with keeweb. Please go to stackoverflow with this.
