### ISSUE TITLE
Dropbox outh url needs to be updated

### ISSUE THREAD

**Issue by creativecoder** [keeweb/keeweb#1959]
**Describe the bug**

When connecting an existing Dropbox app, there's an error

<img width="634" alt="Screen Shot 2021-11-24 at 8 20 48 PM" src="https://user-images.githubusercontent.com/1699996/147512699-16315fd7-0cab-4b78-adf0-edefa5b53be1.png">

```
"scope": must be at most 0 characters, got 79
```

The oauth url looks like this:

```
https://www.dropbox.com/oauth2/authorize?client_id=xxx&scope=files.content.read files.content.write files.metadata.read files.metadata.write&state=xxx&redirect_uri=http://localhost:48149/oauth-result/dropbox.html&response_type=code&code_challenge=xxx&code_challenge_method=S256&token_access_type=offline
```

If the `scope` parameter is removed, it works as expected. I think the scope is now defined when the app is registered, rather than in the url (current documentation: https://developers.dropbox.com/oauth-guide#dropbox-api-permissions)

**To Reproduce**

1. Click on Dropbox as a password file source
2. Enter the client key and secret
3. Click Dropbox again to start the oauth connection and see the error

**Expected behavior**

Connection is created without error.

**Environment**

KeeWeb v1.18.7 (dfc6201, 2021-07-18)
Environment: electron v12.0.7
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 12_1_0) AppleWebKit/537.36 (KHTML, like Gecko) KeeWeb/1.18.7 Chrome/89.0.4389.128 Electron/12.0.7 Safari/537.36

**Kdbx File**

Does it happen on Demo or New database?  

Happens with an existing database.

**Comment by antelle** [comment]
Hi! It's something with the app configuration, because scope parameter is not removed: https://www.dropbox.com/developers/documentation/http/documentation#oauth2-authorize
> scope String? This parameter allows your user to authorize a subset of the scopes selected in the App Console. Multiple scopes are separated by a space. If this parameter is omitted, the authorization page will request all scopes selected on the Permissions tab. Read about scopes in the OAuth Guide.

**Comment by creativecoder** [comment]
You're right... there was a prompt from Dropbox to migrate to using scopes, I guess my app was using their older permissions model. After doing that and checking the appropriate scopes, it all seems to be working again.

<img width="729" alt="image" src="https://user-images.githubusercontent.com/1699996/147601648-e4b7f42d-cdb9-47df-9274-a6ba523a495e.png">


Thanks for your help!
