### ISSUE TITLE
Remember the last sorting order of entries within a group (or globally)

### ISSUE THREAD

**Issue by majorpb** [keeweb/keeweb#1961]
**Is your feature request related to a problem? Please describe.**
Each time Keeweb is opened, it forgets the previously set sorting order of the entries within a group/folder. 

**Describe the solution you'd like**
Keeweb could remember for each group/folder (or at least globally as an option) the last selected sorting order from one start of the application to another. It is useful not to end up with the default (i.e. alphabetical) sorting order every time, if for example "Creation date: From new to old" would be preferred by the user.

**Comment by antelle** [comment]
Duplicates #1082
