### ISSUE TITLE
How to prevent "Delete local file" with password?

### ISSUE THREAD

**Issue by IngoBelka** [keeweb/keeweb#1968]
Hello,

I'm testing keeweb for a couple of days and it seems to me to be really, what I was searching for.

One problem I see at the moment. How do I prevent a database against deleting accidentially or by willing? I would prefer a password to protect the database. I mean not the password of the database itself. If the problem is answered yet, please point me to solution.

Regards
Ingo

**Comment by antelle** [comment]
Hi! You cannot prevent a file from being deleted... If someone wants to delete a file, they're free to do so. One thing that you can do, it upload your kdbx file to an online storage, for example, Dropbox, and utilize its capabilities to restore deleted files.
