### ISSUE TITLE
Usability suggestion: reveal / large type

### ISSUE THREAD

**Issue by alexandru** [keeweb/keeweb#197]
Hello,

On the desktop one can press Cmd+C for copying a password. 
But this is only useful for filling passwords while using the same computer. And sometimes you want to copy passwords manually from the computer's screen to a phone or another computer. But then clicking on the password field to show it has two problems:
1. the text is too small to see from a distance (i.e our eyes are trained to easily recognize words, but not random characters) and
2. it's error prone, as one can easily make modifications

1Password (the manager I've been using) has two actions meant for password fields: "Reveal" which just displays passwords and "Large type" which displays passwords in a very big font, such that you can see it from a distance. And in "Large type" mode it displays letters, numbers and special characters in different colors, such that you can differentiate between o, 0 and O.

In regards to clicking on a password field, it's especially error prone on mobile phones. The interface is almost usable on my iPhone, which is more than I could have hoped for, but revealing a password field is error prone and the text is too small.

Btw, thanks for this project, looking great.

**Comment by Maxiride** [comment]
I'd like to reinforce that indeed clicking on a field automatically make it editable which is a huge risk of loosing a password. A locked\unlocked edit status would be awesome for this.

**Comment by kasoban** [comment]
@Maxiride unless you change it 10 times in a row by accident you will always be covered by the entry history (unless you like to live dangerously and turned that off)

**Comment by alexandru** [comment]
@kasoban on the desktop you're right, because we can be precise with a mouse/keyboard and accidents don't happen that often. But when they do, you might not notice it immediately and that can cause confusion the next time you try logging in.

But this is especially wrong on phones and tables, because that damn screen keyboard pops up once you focus an input field and you can easily touch it by accident and then you start becoming afraid at looking at passwords :-P Some sort of lock that prevents editing and makes those inputs disabled would be fine I guess.

**Comment by Maxiride** [comment]
@kasoban lol you are right. I've discovered the app just a couple of days ago and didn't noticed the history feature! My fault =)

**Comment by antelle** [comment]
@alexandru editing sucks on mobiles for now. e.g. exit from edit mode by click doesn't work for mobiles. Later, mobile editing ux will be improved with better controls, more suitable to touch devices. Edit/Save buttons are not necessary for this.

**Comment by antelle** [comment]
As a first step of this, now we show some buttons on mobile devices, so editing is now more convenient:
![editing](https://cloud.githubusercontent.com/assets/633557/25067040/130aa982-2238-11e7-810c-4cd7301c7db3.gif)

**Comment by antelle** [comment]
Next version will show this actions panel with different actions:
<img width="322" alt="Screen Shot 2019-10-26 at 20 51 56" src="https://user-images.githubusercontent.com/633557/67624572-7ff00380-f832-11e9-8b25-71e4b7ce7bc5.png">
