### ISSUE TITLE
Set foreground color instead of background color

### ISSUE THREAD

**Issue by gautierlabarre** [keeweb/keeweb#1970]
Hi,

When you set a color for a password, it changes the background color. 
It makes KeepassDX on android and KeepassXC look awful as the lines are colored.

It would be better if the color we set on KeeWeb were the foreground color.

**Comment by antelle** [comment]
Well I assume, that's how the color is represented. It's not much we can do about it...

**Comment by gautierlabarre** [comment]
When we set a foreground color (e.g : blue) and no background color from keepassDX to a password, Keeweb shows the icon with the right color (blue). 
It seems KeeWeb looks for a background color and then if none are found : the foreground color.

When we change the color with KeeWeb it sets the background color. 

So in order to have the color for foreground i have to set it from either KeepassDX and keepassXC and it displays the proper color on KeeWeb as well, however i can't set color from KeeWeb as it does change background color and not foreground.
