### ISSUE TITLE
Asking for minimal required permissions when storing data on Google Drive and other providers

### ISSUE THREAD

**Issue by ClementNerma** [keeweb/keeweb#1973]
Hi there!

I've recently switched to KeeWeb after trying to find a good open-source, multiplatform password manager which would not require a server (allowing to just store the encrypted passwords in my Drive account), and I thank you for this amazing program which is really nice to use.

One thing I noticed when I set it up is that, when you link your Drive account to KeeWeb, it asks for the permission to manage (create, read, rename, move, edit, delete) **ALL** of my files.

Where some other password managers like Enpass only asks for a simple permission constiting in managing files **created by** the authorized application.

Concretely, this permission would change nothing to KeeWeb: it could still create and manage files on its own, without limitations. It would only prevent the token from allowing access to _other_ files.

This could seem like an unimportant thing but on the contrary, it's important when giving access to such important accounts to limit at best the authorizations that are given to the final application.

So I think it would be interesting to switch to this other permission when creating a new database. Maybe this could be included in the upcoming 2.0 version?

What do you think?

**Comment by antelle** [comment]
Hi! This is unfortunately not possible, because KeeWeb can also create files. You can indeed try creating your own Google Drive application where you can configure permissions as you prefer, but not sure if it will work.

**Comment by ClementNerma** [comment]
> Hi! This is unfortunately not possible, because KeeWeb can also create files. You can indeed try creating your own Google Drive application where you can configure permissions as you prefer, but not sure if it will work.

Please read again what I said. You can absolutely create new files with the new permission - otherwise, what would it be useful for?

In fact, as far as I know, you could do _exactly_ the same things as KeeWeb currently does (creating, editing, renaming, moving, deleting its **own** files) without needing to access **all** of the user's files.

**Comment by antelle** [comment]
It's not only file creation, KeeWeb also selects files by displaying the list of folders from Google Drive. This wouldn't work then...

**Comment by nyukers** [comment]
Hi, I can't check it now, but KeeWeb require **full access** to ALL files in my DropBox or OneDrive too?
