### ISSUE TITLE
Crash on launch: GPU process isn't usable

### ISSUE THREAD

**Issue by neversun** [keeweb/keeweb#1975]
**Describe the bug**
App crashes on launch without showing any graphical interface

**To Reproduce**
```bash
➜  ~ keeweb                                         
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
[39809:0127/140651.852037:FATAL:gpu_data_manager_impl_private.cc(415)] GPU process isn't usable. Goodbye.
[1]    39809 trace trap (core dumped)  keeweb
```

**Expected behavior**
App starts

**Environment**
KeeWeb v1.18.7 (dfc6201, 2021-07-18)
Environment: electron v12.0.7
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) KeeWeb/1.18.7 Chrome/89.0.4389.128 Electron/12.0.7 Safari/537.36

Linux fedora 5.15.15-200.fc35.x86_64

**Notes**

This seems to be fixed starting with electron v13.5.0 (https://github.com/electron/electron/pull/31091)

Workaround by adding `--no-sandbox` to launch options: `keeweb --no-sandbox`
On Fedora 35, you can edit the desktop launch entry at `/usr/share/applications/keeweb.desktop`

**Comment by antelle** [comment]
Well, adding `--no-sandbox` by default is probably not best, but we can update Electron, maybe it will fix that.

**Comment by keyxmakerx** [comment]
This seems to happen on POP OS 22.04 as well now.

**Comment by rutonyru** [comment]
Hi,
I'm playing with a lot of virtual machines and i migrate some to ubuntu 22.04. Adding --no-sandbox saved me ! 
Tips -- As I launch keeweb from favorite bar (ubuntu), i added the parameters to the `/usr/share/applications/keeweb.desktop` file.
Have a good day ;)
Antoine

**Comment by AlexWayfer** [comment]
Now it fails on stable Arch Linux: https://bugs.archlinux.org/task/75902

Due to `glibc` minor update.

Please, update the Electron. And make a new release.

**Comment by HarlemSquirrel** [comment]
For what it's worth, I switched to the appimage with my ArchLinux install and it's working again for me

**Comment by ckruger097** [comment]
AppImage still yields the same error on Manjaro. Would really like to see https://github.com/keeweb/keeweb/pull/2052 merged in. @antelle is there an issue bumping the electron version?

**Comment by lustasag** [comment]
Debian package yields the same error on Debian testing (bookworm).

**Comment by dzek69** [comment]
anyone has a solution? it's getting close to a full year now and i have it on both appimage and deb package

**Comment by ckruger097** [comment]
@dzek69 

I would build a package myself and put it up on the AUR but I can't seem to get the dev environment to build on Linux. Very frustrating for this great app!

**Comment by dzek69** [comment]
I found the workaround that doesn't involve disabling sandbox, which is probably something i REALLY do not want in an app that has access to all my passwords.

`--in-process-gpu` flag

**Comment by SergiusTheBest** [comment]
> I found the workaround that doesn't involve disabling sandbox, which is probably something i REALLY do not want in an app that has access to all my passwords.

@dzek69  The sandbox doesn't have much sense for the app that doesn't load webpages from the internet.

**Comment by dzek69** [comment]
it doesn't load webpages, but it communicates with the internet (google drive sync, etc). Better safe than sorry in such sensitive case

**Comment by SergiusTheBest** [comment]
@dzek69 Yes, but AFAIK the sandbox runs only the UI part (frontend) of electron apps while the main part (backend) runs unrestricted. I don't know the KeeWeb architecture though. Anyways the sandbox is built to protect OS resources from the app and not to protect the app from malicious code: https://chromium.googlesource.com/chromium/src/+/refs/heads/main/docs/design/sandbox_faq.md

> Better safe than sorry

Agree.

**Comment by H-Ribeiro** [comment]
Running on 2 separate machines with same distro (POP OS 22.04 and kernel).
Laptop running discrete NVIDIA GPU prompts the same error.
Integrated Intel GPU runs well, either on Xorg or Wayland.
Can verify that issue is present only when running the app with NVIDIA discrete GPU.

**Comment by Gabb1995** [comment]
same here, having the samue issue oin POP OS 22.04

**Comment by Jurrie** [comment]
FYI: In https://github.com/keeweb/keeweb/issues/2072#issuecomment-1545331928 I posted another solution which worked for me, and seems to work for other people as well.

**Comment by Nebucatnetzer** [comment]
The `--in-process-gpu` works for me on NixOS in Virtualbox. The `/dev/video0` workaround doesn't, that file doesn't exist in my setup.

**Comment by KelvinNovais** [comment]
I have the same problem on Fedora 37: it's crashing when opening.
If I run KeeWeb on the terminal, it returns

`libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)`

**Comment by blinard-BIOINFO** [comment]
Crash still occurs after upgrade to Ubuntu 22.04.3 LTS. For the same reason, Electron is not up to date.

**Comment by Snake883** [comment]
Same issue with KeeWeb-1.18.7.linux.AppImage on Fedora Linux 40.20240705.0 (Budgie Atomic).

Workaround:
./KeeWeb-1.18.7.linux.AppImage --in-process-gpu

**Comment by Red-M** [comment]
I'm also having this issue on NixOS with 1.18.7

**Comment by Aetherinox** [comment]
@Red-M: Did you try the work-around posted above by Snake?

I'll do a VM install of NixOS later and test both the old version and the newer one with the dependency updates and see if there's anything additional that needs done.

**Comment by Red-M** [comment]
Yes I did, it does work but the currently most recent release from this repository isn't working and requires this workaround to function at all.

https://github.com/NixOS/nixpkgs/blob/nixos-24.05/pkgs/applications/misc/keeweb/default.nix#L25-L42
