### ISSUE TITLE
Icon size after transferring from Keepass 2

### ISSUE THREAD

**Issue by Miltora** [keeweb/keeweb#1978]
**Describe the bug**
I used before the normal Keepass and now I switched to Keeweb and I noticed all the icons from before were in the original size and now if I change a icon for a new entry it's smaller

**To Reproduce**
If I change the icon on an entry

**Expected behavior**
If I choose an icon which is eg. 128x128x it should be that big but somehow it's small. I made a screenshot of both situation. If I use the already existing icons, it works perfectly. The icon which is used, is for both the same, so the icon shouldn't be the problem. Is there anywhere a restriction to pixels?

**Screenshots**

![howitis](https://user-images.githubusercontent.com/79868191/152445508-43b3e52a-26b8-4ac8-abb4-4f8aa6844932.png)
![howitshouldbe](https://user-images.githubusercontent.com/79868191/152445510-79cbdb89-f403-4b66-a344-4f80cdea8ed5.png)

**Environment**
KeeWeb v1.18.7 (dfc6201, 2021-07-18)
Environment: electron v12.0.7
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) KeeWeb/1.18.7 Chrome/89.0.4389.128 Electron/12.0.7 Safari/537.36

**Kdbx File**
I have made a new db from Keepass with the icon and used the same KDBX file in Keeweb and made an entry with adding the icon again

**Logs**
2022-02-03T23:17:26.530Z [start-profiler] Electron app started in 464ms: loading app requires=2ms, single instance lock=2ms, portable check=0ms, userdata dir=0ms, defining args=0ms, setting env=0ms, app on ready=26ms, loading settings key=1ms, reading app settings=10ms, creating main window=17ms, configuring main window=9ms, restoring main window position=1ms, setting ipc handlers=9ms, setting global shortcuts=0ms, subscribing to power events=0ms, setting request handlers=0ms, main window ready=303ms, main window shown=1ms
index.html:1 2022-02-03T23:17:26.533Z [settings-manager] Theme changed sl
index.html:1 2022-02-03T23:17:26.589Z [start-profiler] App started in 389ms: fetching=201ms, pre-init=261ms, loading modules=51ms, document ready=10ms, creating app model=2ms, loading configs=8ms, initializing modules=1ms, loading remote config=1ms, checking features=0ms, initializing storage=0ms, starting usb=0ms, first view rendering=55ms, app ready event=0ms
index.html:1 2022-02-03T23:17:27.091Z [updater] Next update check will happen in 81256s
index.html:1 2022-02-03T23:17:31.704Z [open:Test] File open request
index.html:1 2022-02-03T23:17:31.704Z [open:Test] Open file from storage file
index.html:1 2022-02-03T23:17:31.704Z [open:Test] Stat file
index.html:1 2022-02-03T23:17:31.704Z [storage-file] Stat C:\Temp\Test.kdbx
index.html:1 2022-02-03T23:17:31.706Z [storage-file] Stat done C:\Temp\Test.kdbx 2ms
index.html:1 2022-02-03T23:17:31.706Z [open:Test] Open file from storage (1643930233014, local 1643930233014)
index.html:1 2022-02-03T23:17:31.707Z [open:Test] Load from storage
index.html:1 2022-02-03T23:17:31.707Z [storage-file] Load C:\Temp\Test.kdbx
index.html:1 2022-02-03T23:17:31.709Z [storage-file] Loaded C:\Temp\Test.kdbx 1643930233014 1ms
index.html:1 2022-02-03T23:17:31.709Z [open:Test] Open file from content loaded from storage
index.html:1 2022-02-03T23:17:31.730Z [file] Opened file Test: 20ms, 60000 rounds, 8 kB
index.html:1 2022-02-03T23:17:31.730Z [app] Add last open file 07ed7681-1d5a-0eae-5d4c-284fa451758c Test file C:\Temp\Test.kdbx 1643930233014
index.html:1 2022-02-03T23:17:31.765Z [storage-file] Watch dir C:\Temp

**Comment by Miltora** [comment]
I have made a KDBX file for this text. Where can I attach it?

**Comment by Miltora** [comment]
Hi, thanks for the reply! All the icons I use are custom images. I even used 512x512 images and they are as big as the 32x32 images in the db, so that can't really be, or am I missing something?

**Comment by antelle** [comment]
Let me clarify your question: you mean that they're of bad quality, or you expected to see icons that would be larger in size on the screen?

**Comment by Miltora** [comment]
I expect them to be bigger, the quality is good, but I see where you are going. The pixels doesn't matter the size of the icons, right?

**Comment by antelle** [comment]
Right. It's a design decision, they will not be bigger.

**Comment by Miltora** [comment]
Ahh my mistake! Sorry and thanks for helping / clarifying. Wish you a good evening!
