### ISSUE TITLE
Where does keeweb store the password db file (*.kdbx) in docker container?

### ISSUE THREAD

**Issue by MinistrBob** [keeweb/keeweb#1979]
Where does keeweb store the password db file (*.kdbx) in docker container?

I was not satisfied with the standard image antelle/keeweb because there is a redirect to protocol HTTPS. And I expose all my containers through one reverse proxy and I just need a container with port 8080 and HTTP.

So I downloaded the latest distribution files from the gh-pages branch and built my simple container.
```
FROM nginx:1.21.1
COPY. /usr/share/nginx/html
```

I start the container and upload my *.kdbx file there.
Then I go inside the container and try to find this file by searching, but I can’t find it
`find / -name *.kdbx`

It turns out that the next time you start the container, you will need to upload your file again, and all changes will be lost. I would like the file to lie locally on my server and be mounted into the container, for this I would like to know in which folder inside the container the application puts the *.kdbx files? 
Then it will be possible to use docker mount ( ... -v local_path:container_path)

**Comment by antelle** [comment]
Hi! KeeWeb doesn't store files in the container. They're stored in the browser...

**Comment by m0vida** [comment]
where exactly ? there should be a phsycil path. How about when you want to export it ?
