### ISSUE TITLE
Attachments not "attached" when dragging and dropping - Linux 64bit app

### ISSUE THREAD

**Issue by Maxiride** [keeweb/keeweb#198]
KeeWeb v1.1.2 (fb00cf5, 2016-04-10)
Environment: electron v0.37.4
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) KeeWeb/1.1.2 Chrome/49.0.2623.75 Electron/0.37.4 Safari/537.36

I dragged and dropped a png file on an entry using the KeeWeb linux app. Nothing happened, even the dev console showed nothing. I'm on Kubuntu 15.10 using Dolphin as file explorer.

**Comment by antelle** [comment]
For now, I can only confirm that it's working on ubuntu. I'll download kubuntu and try it.

**Comment by antelle** [comment]
I digged into it. Unfortunately, html5 drag-drop is broken in electron under kubuntu. So, there's no way to fix.
I've opened an issue in Electron: https://github.com/electron/electron/issues/5162

**Comment by antelle** [comment]
Drag-drop doesn't work in Chrome on KUbuntu as well, e.g. on this demo: http://html5demos.com/file-api
So, the fix might not arrive soon... First, Chrome guys will fix it; second, chrome runtime will be integrated in Electron; third, we'll switch to this new Electron version.

**Comment by antelle** [comment]
http://askubuntu.com/questions/718161/cant-drag-files-from-dolphin-to-chrome
https://bugs.chromium.org/p/chromium/issues/detail?id=348312

**Comment by Maxiride** [comment]
Thanks for the insights!
@antelle is there an alternative way to upload files in the keepass database? Like a "click to upload".

**Comment by antelle** [comment]
A button will be added in #190

**Comment by antelle** [comment]
As it's blocking for linux, triaged to the next release

**Comment by antelle** [comment]
Deployed to [beta.keeweb.info](https://beta.keeweb.info), will be available in the next release

**Comment by Maxiride** [comment]
Thank you very much for the quick answers and the damn fast implementation of the solution!

**Comment by antelle** [comment]
At the moment we don't accept donations, while we're starting up...

**Comment by Maxiride** [comment]
Tried the beta version to upload a file. Works fine but I can only add one attachment per entry, is that as intended?

**Comment by antelle** [comment]
This is ux issue because the label is hidden once anything is attached. Should be fixed...

**Comment by antelle** [comment]
now *add attachment* button is always visible

**Comment by antelle** [comment]
Let's think it's fixed because a workaround was added. Drag-drop will work automatically, once it's fixed in upstream.

**Comment by Maxiride** [comment]
The main goal was to be able to add attachments, no matter how ;) it's absolutely fixed.
