### ISSUE TITLE
Site is down?

### ISSUE THREAD

**Issue by peedrr** [keeweb/keeweb#1980]
I've been a very happy user of Keeweb for quite some time now. But as of this evening I cannot seem to log in. Usually there is some new window which opens up and I think it does the auth with Google (as my db file is in Google Drive) but today it is not working. And now I have checked the keeweb.info website and it seems to be down.

Is everything OK?

**Comment by peedrr** [comment]
nvm, it's back again. Keep up the good work.

**Comment by antelle** [comment]
Hm, works for me

**Comment by antelle** [comment]
Too late... I see
