### ISSUE TITLE
ERROR - Content Security Policy blocks inline execution of scripts and stylesheets

### ISSUE THREAD

**Issue by blakstrox** [keeweb/keeweb#1981]
**Describe the bug**.
Blank screen and browser console shows the following,

Refused to apply a stylesheet because its hash, its nonce, or 'unsafe-inline' does not appear in the style-src directive of the Content Security Policy.

**To Reproduce**
1. Host keeweb in a domain
2. Change the below line from,

`<meta name="kw-config" content="(no-config)">`

To 

`<meta name="kw-config" content="config.json"> `

3. Add a config.json file with auto load DB on a WebDAV configuration.
4. Load domain from browser and see the error in console.

**Expected behavior**
Keeweb loads with the configuration from config.json

**Screenshots**
[ERROR SCREENSHOT](https://i.ibb.co/XFK2Jsw/error-kweb.png)

**Environment**

**Kdbx File**

**Logs**
xxxxxxx.com/:1 Refused to apply inline style because it violates the following Content Security Policy directive: "style-src 'sha512-63edYbLgq599MAsyyqgCBk18k1RCKpZ3FjZ9G3l0pQlvxVchNVaPhiAE+GwP9NKPZVIinJuNXJx2xY1tZkzvZg==' blob:". Either the 'unsafe-inline' keyword, a hash ('sha256-+CYrDWrdxCl8xhCDbr4O/j5/JSq0edSL70Yi2Hwv5So='), or a nonce ('nonce-...') is required to enable inline execution.

xxxxxxx.com/:1 Refused to execute inline script because it violates the following Content Security Policy directive: "script-src 'sha512-jYN26k9MdXnhqu7Ssy7r+y/87ND1Br7yx4NzRHwx8dSII1LvinqIRKaXoIb0ObI9HQFILRWBg5gPRszhILAC9g==' 'unsafe-eval'". Either the 'unsafe-inline' keyword, a hash ('sha256-G3UjZrh+NvT/MzZyR0oTwZZ9zKCeEqF5bGN4U9kazsc='), or a nonce ('nonce-...') is required to enable inline execution.

**Comment by antelle** [comment]
Hi! does it work without changing the html file? I assume, the file was corrupted a bit, and the script hash was change.

**Comment by blakstrox** [comment]
> Hi! does it work without changing the html file? I assume, the file was corrupted a bit, and the script hash was changed.

Yes it works without any changes to thr html file. And for your information, I have only changed the config part of thr script to load the json config file automatically while loading the website. This is because I wanted to load the predefined DB from a webdav storage. 

I am currently using the version 1.15.7 with the same setup and I am only experiencing the issue while I am trying to load the same json file with the latest version using the following meta tag on html file

`<meta name="kw-config" content="(no-config)">`

**Comment by antelle** [comment]
I assume, your editor corrupted the HTML because there are some special symbols in it. I'd advise trying another editor to change only that part of the file... this should solve your issue.
To make sure, you can edit the file twice: first change something in the config line and then put it back to what it was. Compare the result. I assume, in your case, files would not be the same.
