### ISSUE TITLE
Error exchanging refresh token

### ISSUE THREAD

**Issue by PritishParihar** [keeweb/keeweb#1982]
**Describe the bug**
I'm using Keeweb on MXLinux-21 Wildflower Debian version 11.2. I'm using kdbx + key file + password combination. While using this from Gdrive while syncing it showing me an error, error seems to be since I switched to this Linux a few days back. 

Sync Error: Error exchanging refresh tokens.

Screenshot:
![image](https://user-images.githubusercontent.com/22941460/153745395-b0f92196-6b20-4674-aade-1c593945e709.png)

**Comment by antelle** [comment]
Hi! What happens if you click "log out" in settings / storage / google drive, does it reproduce?
Another question, if you open devtools, what do you see in logs? There should be a more verbose error

**Comment by PritishParihar** [comment]
Thank you for the suggestion, log-out option worked for me.
