### ISSUE TITLE
Quick Settings

### ISSUE THREAD

**Issue by anato511693** [keeweb/keeweb#1986]
Add the ability to change the order of fields **Drug & Drop**.
---
Add the ability to add custom fields to the group for quick convenience.

For example, I need a group of Bank cards and in them a field

**Card number
CSV code
Date
Bank's name**

When i'm creating the record, there were only field data

**Comment by anato511693** [comment]
> Привет! Это [# 398](https://github.com/keeweb/keeweb/issues/398)

I disagree slightly changed the request

**Comment by antelle** [comment]
Custom fields for groups are not supported by the file format...
