### ISSUE TITLE
Save new credentials in keepass db when you login to a website

### ISSUE THREAD

**Issue by piyu-sh** [keeweb/keeweb#1988]
**Is your feature request related to a problem? Please describe.**
Currently there is no option to save credentials through web browser plugin.

**Describe the solution you'd like**
 When you submit the form with creds, show user a way to either save the creds or ignore the notif

**Describe alternatives you've considered**
Earlier keepashttpconnector provided this functionality, keepasXC browser plugin also provides this functionality

**Additional context**
Nopes

**Comment by antelle** [comment]
Hi! This is https://github.com/keeweb/keeweb-connect/issues/11
