### ISSUE TITLE
Connection state: Error  Cannot connect to KeeWeb, please check if KeeWeb is open and browser integration is enabled in settings.

### ISSUE THREAD

**Issue by hrqmonteiro** [keeweb/keeweb#1992]
**Describe the bug**
Doesn't connect to Firefox although i have the extension and the Browser integration activated.
I am on Ubuntu, until some five hours ago it was working fine, then, when i tried this time when i opened Firefox, is stopped suddenly to work.

**To Reproduce**
Just open and try to connect

**Expected behavior**
To connect?

**Screenshots**
![Screenshot from 2022-03-01 20-33-22](https://user-images.githubusercontent.com/17055027/156266681-aa8577da-99dc-4894-9bd9-63a83ea93c77.png)

**Environment**
KeeWeb v1.18.7 (dfc6201, 2021-07-18)
Environment: electron v12.0.7
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) KeeWeb/1.18.7 Chrome/89.0.4389.128 Electron/12.0.7 Safari/537.36

**Kdbx File**
Yes, happens anywhere

**Logs**
```
2022-03-01T23:34:37.887Z [browser-extension-connector] Stopped
index.html:1 2022-03-01T23:34:37.887Z [browser-extension-connector] Disable Firefox KWC
index.html:1 2022-03-01T23:34:38.856Z [browser-extension-connector] Started
index.html:1 2022-03-01T23:34:38.856Z [browser-extension-connector] Enable Firefox KWC
```

**Comment by antelle** [comment]
Hi! How is the firefox installed? I heard that it doesn't work on for example AppImage.

**Comment by hrqmonteiro** [comment]
> Hi! How is the firefox installed? I heard that it doesn't work on for example AppImage.

I installed through apt

**Comment by btxtiger** [comment]
@hrqmonteiro Try to disable and re-enable the browser checkbox under "Keeweb Connect" in the KeeWeb settings
This helped me on Windows and Mac to fix the connection issue

**Comment by hrqmonteiro** [comment]
> @hrqmonteiro Try to disable and re-enable the browser checkbox under "Keeweb Connect" in the KeeWeb settings This helped me on Windows and Mac to fix the connection issue. (Possibly have the browser with KeeWeb Connect already launched while doing this).

I am able to use it now but i am on a Fedora machine. On Ubuntu it really wasn't connecting.

**Comment by evlo** [comment]
I just installed keeweb from github on windows10 and same problem with firefox plugin from store, but looking into help about it says
KeeWeb v1.18.7 (dfc6201, 2021-07-18)

So seems to me there is probably years newer version I should be using and not the github release, right?
