### ISSUE TITLE
No Connection with nextcloud keeweb site

### ISSUE THREAD

**Issue by TysonRoberts21** [keeweb/keeweb#1993]
I can't connect my Chrome Extension to my nextcloud Keeweb site

KeeWeb v1.18.7 (dfc62012, 2021-11-30)
Environment: web
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.51 Safari/537.36

**Comment by antelle** [comment]
I assume, this should be fixed in nextcloud-keeweb, that's a separate product...

**Comment by antelle** [comment]
not sure if it would be possible to fix there though
