### ISSUE TITLE
Clear a color flag

### ISSUE THREAD

**Issue by JannieT** [keeweb/keeweb#1995]
**Is your feature request related to a problem? Please describe.**
I enjoy the ability to mark some entries with colors, but it looks like there is no way to remove the color when marked by accident.

**Describe the solution you'd like**
The most natural solution I can think of would be if the color flag popup had a non-color entry to choose from.

![Screenshot 2022-03-12 at 11 08 38](https://user-images.githubusercontent.com/5163423/158011772-f1c399aa-4758-4d74-8113-d1cd7678e5bc.png)

**Describe alternatives you've considered**
An alternative would be to be able to right-click on the entry and there would be a "Remove color" option in the context menu.

**Comment by jivarson** [comment]
Uhm, you just click the same color-tag again to unmark it?

**Comment by JannieT** [comment]
Yikes! I should have tried that. Very neat. Thanks.
