### ISSUE TITLE
KeeWeb on Ubuntu 22.04

### ISSUE THREAD

**Issue by jivarson** [keeweb/keeweb#2014]
Are you people getting KeeWeb 1.18.7 to run on Ubuntu 22.04?

Im evaluating ubuntu in Vmware Workstation and getting 

```
@j0e-virtual-machine:~$ keeweb 
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
```
I have libva-wayland2 and libva-x11-2 installed.
Is KeeWeb not compatible with Wayland?

**Comment by jivarson** [comment]
appending --disable-gpu when running KeeWeb makes it run.

**Comment by Xientist** [comment]
What did you do to resolve the problem?
I have the same issue but it still does not work and the `--disable-gpu` doesn't work for me.

**Comment by Xientist** [comment]
Ok, I just found the related issue (#1975), leaving it here in case someone else finds itself here.

**Comment by jivarson** [comment]
> Ok, I just found the related issue (#1975), leaving it here in case someone else finds itself here.

For me it only happened in a virtual machine. Appending --disable-gpu "feels" more secure then to disable sandbox..

I didn't have this issue on a physical Ubuntu 22.04 installation today, guess I had proper hardware acceleration on my Lenovo laptop
