### ISSUE TITLE
Whitespace is not shown when revealing password

### ISSUE THREAD

**Issue by h00pl4** [keeweb/keeweb#2027]
If you create a password which contains whitespace...
![image](https://user-images.githubusercontent.com/4376781/176327480-48ef8814-8def-4043-ac44-668872657672.png)

When you reveal it...
![image](https://user-images.githubusercontent.com/4376781/176327519-8a369f6e-bef8-4167-b2cc-1c6c209b6894.png)

The whitespace is removed...
![image](https://user-images.githubusercontent.com/4376781/176327555-97060ff1-c2d0-46ed-94c5-a98d3bba872f.png)

Editing the password shows the whitespace still...
![image](https://user-images.githubusercontent.com/4376781/176327600-d23b3d64-7ab1-4186-a768-f74202d6b020.png)

And copying the password...
![image](https://user-images.githubusercontent.com/4376781/176327647-f8675fb3-c486-40ae-9342-33116321ee46.png)

Includes the whitespace as well...
`whitespace between words`

KeeWeb v1.18.7 (dfc6201, 2021-07-18)
Environment: electron v12.0.7
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) KeeWeb/1.18.7 Chrome/89.0.4389.128 Electron/12.0.7 Safari/537.36

**Comment by Aetherinox** [comment]
Thanks for submitting this. This fix was implemented in the upcoming v1.19
- https://github.com/keeweb/keeweb/pull/2168
