### ISSUE TITLE
OTP code is not generated correctly in KeeWeb for some services

### ISSUE THREAD

**Issue by Nu11u5** [keeweb/keeweb#2033]
**Describe the bug**

The OTP code in KeeWeb is not generating the correct code for some existing entries.  These codes are generated correctly when the same KDBX is opened in another app, such as KeePassium on IOS.

In my case, KeeWab is generating incorrect OTP codes for a Square Enix account, but the OTP code for GitHub is generating correctly.

**To Reproduce**

Add an OTP URL to a KDBX entry and compare the generated code in KeeWeb to another app like KeePassium.  Any OTP authenticator app should also work.  Notice that the codes do not match.

Example OTP URL provided for Square Enix accounts, anonymized and confirmed "valid".

`otpauth://totp/Square%20Enix%20ID:Username?secret=BASE32ENCODEDKEYWITH32CHARACTERS&issuer=Square%20Enix%20ID&algorithm=SHA1&digits=6&period=30`

The generated OTP codes for both the actual user account and the example do not match between KeeWeb and other apps.

**Expected behavior**

The generated OTP code is correct.

**Environment**

KeeWeb v1.18.7 (dfc6201, 2021-07-18)
Environment: web
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36

**Comment by Nu11u5** [comment]
I suspect the problem is caused by the `period=30` parameter.

**Comment by bdeeming** [comment]
It is also possible that the system clock of the device that you are running KeeWeb on is not quite synchronized with global time (and perhaps the other entries have a slightly longer period on them?). Not 100% sure, but maybe something worth checking.

**Comment by Nu11u5** [comment]
@bdeeming you may be right.  When I checked again today the OTP codes were correct and matching ones generated in other apps.  I'm not sure how my system clock could have skewed enough to throw off OTP.  It also could have been a temporary browser issue.  Closing
