### ISSUE TITLE
Nested groups hard to see in GUI

### ISSUE THREAD

**Issue by gsportelli** [keeweb/keeweb#204]
When a folder (i.e., a group) is using the default icon, one can understand if it contains any subfolders depending on its icon: if the icon is a closed folder you have to double click on it to show the subfolders; if it is an open folder, either it has no subfolders or the subfolders are shown already.

However, if the folder is using a custom icon, there are no visual hints that indicate if you have to expect any subfolders in it. Hence, if you want to browse your database, you have to double-click all folders to search for hidden subfolders. I think that this could be improved by adding something like in tree lists, where a triangle pointing to the right indicates that there are subfolders to be shown, a triangle pointing downside indicates that all subfolders are shown already and no triangle means that there are no subfolders.

**Comment by antelle** [comment]
This is already fixed on [beta.keeweb.info](https://beta.keeweb.info), will be available in the next release

**Comment by antelle** [comment]
related: #33
