### ISSUE TITLE
Key encryption rounds?

### ISSUE THREAD

**Issue by dgaroorkee** [keeweb/keeweb#2044]
# please describe your issue here

KeeWeb v1.18.7 (dfc6201, 2021-07-18)
Environment: electron v12.0.7
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) KeeWeb/1.18.7 Chrome/89.0.4389.128 Electron/12.0.7 Safari/537.36

**Comment by CapitainFlam** [comment]
Could you please describe your issue ? 
Because support is quite impossible right now :-/

Sorry.

**Comment by Aetherinox** [comment]
We cannot reply to tickets which don't have a description of what issue you're having or your question.
If you still need help, please fill out another report.
