### ISSUE TITLE
WebDav MOVE error

### ISSUE THREAD

**Issue by youlJunior** [keeweb/keeweb#205]
Hello,

I have a problem with webdav.
Keeweb is intalled on Lighttpd, on a RedHat VM.

When i open a DataBase on webdav with using only file path (without host:port), it opens, i can modify it, but I have an error when I try to save it.

Here is the request : 

MOVE /db/env/ru3/.DatabaseOi.kdbx.1461159947096 HTTP/1.1
Host: keepass.integration.dlp.erdf.fr
User-Agent: Mozilla/5.0 (Windows NT 6.1; rv:45.0) Gecko/20100101 Firefox/45.0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Language: fr,fr-FR;q=0.8,en-US;q=0.5,en;q=0.3
Accept-Encoding: gzip, deflate
Authorization: Basic XXXXXXX
Destination: db/env/ru3/DatabaseOi.kdbx
Overwrite: T
Referer: http://keepass.XXXXXX/
Connection: keep-alive

The response is an HTTP400.

I see that in the "Destination" field, the path is relative (no host:port), and it seems that the WebDav needs a full URL in this field.

Moreover, when i open the DataBase with full WebDav URL (http://host:port/path), there is no problem for saving.

**Comment by antelle** [comment]
Deployed to [beta.keeweb.info](https://beta.keeweb.info), will be available in the next release
