### ISSUE TITLE
字段建议

### ISSUE THREAD

**Issue by AisinGioroKiIoi** [keeweb/keeweb#2053]
希望可以自定义字段名称，比如绑定的手机号码、绑定的邮箱、注册时间等，而不是一堆【新字段】。
![image](https://user-images.githubusercontent.com/52952040/191898463-1a7623a1-4ba0-4175-accb-eded319151c4.png)

**Comment by TsLenMo** [comment]
有没有可能，这个字段名称本来就是可以自定义的呢？
![image](https://user-images.githubusercontent.com/23328499/194493239-9a38d60b-0d13-45ec-978b-e9854f4c784a.png)

**Comment by AisinGioroKiIoi** [comment]
@TsLenMo 您好，起先我也觉得应该可以自定义名称。我尝试过，双击，提示【已复制】。右键，六个选项：复制用户名、复制密码、新建字段、创建副本、复制所以栏、自动输入。请指导一下，如何自定义名称？

**Comment by TsLenMo** [comment]
> @TsLenMo 您好，起先我也觉得应该可以自定义名称。我尝试过，双击，提示【已复制】。右键，六个选项：复制用户名、复制密码、新建字段、创建副本、复制所以栏、自动输入。请指导一下，如何自定义名称？

左键点一下字段就好了

**Comment by AisinGioroKiIoi** [comment]
您好，左键点击，也是提示【已复制】

**Comment by AisinGioroKiIoi** [comment]
您好，我找到了。是右侧处于编辑状态下，左键左侧内容，可以编辑了。
