### ISSUE TITLE
Where does the tray icon comes from (in Linux)

### ISSUE THREAD

**Issue by hrqmonteiro** [keeweb/keeweb#2079]
**Describe the bug**
I am trying to change the keeweb icon to a monochrome one, since it is the only one who does not follow the GTK theme, and i literally cannot find it. I searched for keeweb icons in the whole disk, and found some in `/usr/share/icons/Hicolor` and some other places and changed it, but it still remains this blue icon that i don't know where it comes from...

**To Reproduce**
N/A

**Expected behavior**
N/A

**Screenshots**
![Screenshot from 2023-01-09 00-45-03](https://user-images.githubusercontent.com/17055027/211237855-270c2dfe-879b-4f34-b9c7-677ad2283978.png)

**Environment**
KeeWeb v1.18.7 (dfc6201, 2021-07-18)
Environment: electron v12.0.7
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) KeeWeb/1.18.7 Chrome/89.0.4389.128 Electron/12.0.7 Safari/537.36

**Kdbx File**
Any

**Logs**
N/A

**Comment by AlBundy33** [comment]
maybe from here?
https://github.com/keeweb/keeweb/tree/master/graphics
