### ISSUE TITLE
Use different colored icons

### ISSUE THREAD

**Issue by collector-ynh** [keeweb/keeweb#2087]
KeeWeb only offers white icons, which is a problem for users who are used to finding their way around the tree by the color of the icons. I would like to know if there is an easy way to change the color of the icons in Keeweb!

**Comment by Rh4via** [comment]
You can add a colorflag, so a color filter will be applied on all your icon : the default white ones, but also if you add some personalized icons.

**Comment by Aetherinox** [comment]
KeeWeb already offers the ability to select different colors for each entry. We may enhance this further later, but at present the requested functionality is there.
