### ISSUE TITLE
Please tell me how the password for this place is set in the first place

### ISSUE THREAD

**Issue by opencmit2** [keeweb/keeweb#2096]
# please describe your issue here

Please tell me how the password for this place is set in the first place
![image](https://user-images.githubusercontent.com/112474703/228596213-6de3f688-3531-42be-8f48-11eff9a06e4a.png)

Is it unsafe to display the password like this here? If I need this password, can I copy it without displaying it?
![image](https://user-images.githubusercontent.com/112474703/228596619-5377afe5-4a5a-4221-9412-cd297a60f50f.png)

KeeWeb v1.18.7 (dfc6201, 2021-07-18)
Environment: electron v12.0.7
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) KeeWeb/1.18.7 Chrome/89.0.4389.128 Electron/12.0.7 Safari/537.36

**Comment by IBS-IT** [comment]
1. You set the master password when creating the .kdbx file
2. Just hit ctrl-c to copy the password without displaying it.

**Comment by AlBundy33** [comment]
1. to change the master password open yoir database and click on the database name in the lower left corner - this will open a page where you can change the password.
2. in the web-version you can also click on the label to copy the value without displaying them.
