### ISSUE TITLE
Status of the project

### ISSUE THREAD

**Issue by GamerClassN7** [keeweb/keeweb#2102]
Hi @antelle,
Would be possible to ask you for staus of maintainer, there are several issues woth app minly after many updates for  OS.
Would be possible to share information if project have any feature or is Depricated and unmainatained ?

Thank you in advance :)

**Comment by Xavier-Mobius** [comment]
I think this is no longer maintained, unfortunately. 
https://github.com/keeweb/keeweb/issues/2022

**Comment by antelle** [comment]
My life has changed to good, and now I can't afford spending significant time on the project, enough to keep it up and running. I can contribute small updates, but it would not be enough, so I'm looking for someone who would like to maintain it instead, as it was mentioned before, see #2022.

**Comment by GamerClassN7** [comment]
> to good, and now I can't afford spending significant time on the project, enough to keep it up and running. I can contribute small updates, but it would not be enough, so I'm looking for someone who would like to maintain it inst

Hi, I looked in to the https://github.com/keeweb/keeweb/issues/2022, but since it is locket i wasnt shure if someone was selected ot not :) thank you for your answer :)
