### ISSUE TITLE
Certificate expired

### ISSUE THREAD

**Issue by w34sel** [keeweb/keeweb#2104]
[ERROR] 2023-05-23T16:17:51.568Z [transport] Cannot GET https://app.keeweb.info/update.json Error: certificate has expired
[ERROR] 2023-05-23T16:17:51.568Z [updater] Update check error Error: certificate has expired

**Comment by AlBundy33** [comment]
the site uses lets enceypt and has currently a valid certificate.

**Comment by w34sel** [comment]
this error appears in the desktop app

**Comment by Aetherinox** [comment]
Can you confirm if this is still an issue at present? From what I'm seeing, the certificate is valid, and I'm not getting these errors on v1.19 Desktop or Web.

**Comment by w34sel** [comment]
I changed already to another password manager. thx tho

**Comment by Aetherinox** [comment]
Just an update to anyone who stumbles on this ticket.

The certificate error is related to the signature used to sign the binary files. It expired in March of 2022. Once v1.19 releases, a brand new cert will be used and the certificate error will go away.
