### ISSUE TITLE
Passphrase keeping/generating option

### ISSUE THREAD

**Issue by 403-html** [keeweb/keeweb#2127]
**Is your feature request related to a problem? Please describe.**  
No (at least not which I could find of)

**Describe the solution you'd like**  
Introduce a new feature in KeePass password manager that enables users to securely store and generate noun passphrases alongside option for traditional passwords (in popup where we choose when generating new password).

So after I setup that I want 4 word passphrase I'd get like:  
`resolution vehicle freedom uncle`

If 10 then like:  
`volume story girlfriend speech year medicine editor bedroom buyer reading`

**Describe alternatives you've considered**  
Manual passphrase creation, or going to some random dictionary page and picking X random words.

**Additional context**

**Comment by Aetherinox** [comment]
Associated to
- https://github.com/keeweb/keeweb/issues/2152

Will be released in next major release.

**Comment by Aetherinox** [comment]
Changes added to PR. Will be pushed once the major items are wrapped up
- https://github.com/keeweb/keeweb/pull/2168
