### ISSUE TITLE
Github TOTP does not work.

### ISSUE THREAD

**Issue by BoKKeR** [keeweb/keeweb#2145]
**Describe the bug**
TOTP does not work from github. Now I am not sure if I saved this from the browser or used keepassium. The code never transforms into a OTP in the OTP field.

**To Reproduce**
1. Add OTP `otpauth://totp?secret=FX12345678912345&period=30&digits=6&algorithm=SHA1`
2. Cant copy OTP code
3. Add OTP code `otpauth://totp/default?secret=FX12345678912345&period=30&digits=6&algorithm=SHA1`
4. Can copy OTP

OTP code works.

```
not working
otpauth://totp?secret=FX12345678912345&period=30&digits=6&algorithm=SHA1

working
otpauth://totp/default?secret=FX12345678912345&period=30&digits=6&algorithm=SHA1
```

In the example above both are not working unfortunately, I had to replace my OTP secret. To test you have to supply your own secret

**Environment**
KeeWeb v1.18.7 (dfc6201, 2021-07-18)
Environment: electron v12.0.7
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 14_2_1) AppleWebKit/537.36 (KHTML, like Gecko) KeeWeb/1.18.7 Chrome/89.0.4389.128 Electron/12.0.7 Safari/537.36

**Comment by Aetherinox** [comment]
Hi,

Not sure I completely get your issue. You mention two different URLs, one working, and one not working, but then you mention further down that neither work.

The syntax for a otpauth URL is:

```
otpauth://totp/LABEL?secret=SECRET&issuer=ISSUER&algorithm=SHA512&digits=6&period=NUM
```

If I plug my Github OTP secret into your first example, it does indeed generate an OTP code

```
otpauth://totp/default?secret=FX12345678912345&period=30&digits=6&algorithm=SHA1
```

Have yet too see any otpauth URLs formatted starting with `otpauth://totp?secret`

**Comment by BoKKeR** [comment]
Thanks for supplying the page. Yes I am not sure if the format I got was from github itself or keepassium. I just wanted to post it since i came across it.

```
non working
otpauth://totp?secret=MNOTMSR4OU7U6&period=30&digits=6&algorithm=SHA1

working
otpauth://totp/default?secret=MNOTMSR4OU7U6&period=30&digits=6&algorithm=SHA1
```

**Comment by Aetherinox** [comment]
Ah ok. I'll load up Keepassium today and try it out, then I'll get back to you. That's the first time I've seen an otpauth url like that

**Comment by Aetherinox** [comment]
@BoKKeR Managed to work it out to where KeeWeb now supports both options of formatted string

![F6SCWPW](https://github.com/keeweb/keeweb/assets/118329232/d02500cf-c20d-458a-9f2b-16e91eac238f)

**Comment by BoKKeR** [comment]
That was very fast! Thanks for your work!

**Comment by Aetherinox** [comment]
No problem. Just trying to prioritize right now and get a feel for what is what so that I can start making a game-plan. Need to figure out how releases are going to go.
