### ISSUE TITLE
Roadmap: Dependency - font-awesome v5 -> v6

### ISSUE THREAD

**Issue by Aetherinox** [keeweb/keeweb#2155]
### Summary
At present, KeeWeb utilizes `5.15.3` of FontAwesome (based on FA v5). Package should be updated to the latest version [6.5.2](https://www.npmjs.com/package/@fortawesome/fontawesome-free/v/6.5.2) which adds a substantial amount of new icons, as well as some which have better appearances. 

This task is branched off of the Password Generation Overhaul
- https://github.com/keeweb/keeweb/issues/2152

**Comment by antelle** [comment]
Sorry I moved by mistake

**Comment by Aetherinox** [comment]
> Sorry I moved by mistake

To be honest, I didn't even see your name. I went back to the projects and saw it over in `Progress` again and thought "Man... I've been up too long today. I swear I moved this".

**Comment by antelle** [comment]
Yeah dependencies are indeed a pain after two years of inactivity. Another painful thing is CI that also becomes outdated very fast with Electron
