### ISSUE TITLE
Accessibility: contrast & font size

### ISSUE THREAD

**Issue by mlcdf** [keeweb/keeweb#217]
Hello,

I'm having a really hard time using the app due to the small font size and the lack of contrast between the secondary text color and the background color (with both the white and flat blue theme).

![screenshot from 2016-05-04 23 19 34](https://cloud.githubusercontent.com/assets/9364931/15030157/05ac6d68-1251-11e6-9275-1c95a58b50b9.png)

At first, I thought this might be a Linux only issue, but I tried the web app, and I've the same problem. To be able to use it correctly, I need to zoom at 150%. And, I've a perfectly good eyesight and I'm not color blind.

**Comment by ManuCart** [comment]
Hello, same for me.
I always use keeweb with zoom at 175% but it was not a big deal for me because chrome remenber the zoom for visited pages.

**Comment by antelle** [comment]
High contrast theme has been added, the preview is on https://beta.keeweb.info/
Default colors will remain the same of course.

**Comment by mlcdf** [comment]
Thanks!

(Still think you should increase the font size of some elements (when font-size < 12px) though. Because even with the high contrast mode, it's barely readable).

**Comment by antelle** [comment]
Deployed to [beta.keeweb.info](https://beta.keeweb.info), will be available in the next release

**Comment by mlcdf** [comment]
Awesome! Thanks!

**Comment by emyarod** [comment]
any possibility of a high contrast dark theme?

**Comment by antelle** [comment]
Sure, it’s possible and should be quite easy, you can try creating it.
