### ISSUE TITLE
🐛 Bug: manual download & update is OK, but auto update is dead, and still think I am stuck with the old version. 

### ISSUE THREAD

**Issue by CapitainFlam** [keeweb/keeweb#2172]
### Priority

Low

### Version: KeeWeb

KeeWeb v1.18.7 (dfc6201, 2021-07-18)

### Environment

Desktop

### Operating System

Windows

### Range of issue

The issue only occurs on my own setup, demo site works correctly

### Database Type

None

### Environment Copy/Paste

```shell
KeeWeb v1.18.7 (dfc6201, 2021-07-18)
Environment: electron v12.0.7
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) KeeWeb/1.18.7 Chrome/89.0.4389.128 Electron/12.0.7 Safari/537.36
```

### Description

No big deal, but I had a issue with Keeweb desktop app. So I tried to autodate. Nope, doesn't work. No problem, I downloaded and installed manually the last version. So far, so good. But the autoupdater A/ still doesn't work, and B/ still consider that I have the old Keeweb version. 

After reading the logs, it seems that the certificate has expired ?! ...see : 
**[ERROR] 2024-05-07T20:59:16.069Z [updater] Update check error Error: certificate has expired**

### Steps To Reproduce

- install old 1.17.6 windows version. 
- try to autoupdate ( ...it should not work, and say : )
![image](https://github.com/keeweb/keeweb/assets/31761317/68353745-4f66-4ee7-955e-4e9bb2ec83bc)
- download and install latest version manualy
- auto upload should not work anyway, even if you updated, and still say that you're in 1.17.6, even if you're in 1.18.7
it say this : 
![image](https://github.com/keeweb/keeweb/assets/31761317/5dcc30ca-1932-410f-bc69-0d1e821b2674)
even with this version : 
![image](https://github.com/keeweb/keeweb/assets/31761317/54dd967d-987b-40dd-905b-ca1fe4fa0321)

### Expected Behavior

- autoupdate shall work
- actual version shall work **and show** correctly
- 
- 

### Logs

```shell
[INFO ] 2024-05-07T20:58:41.532Z [start-profiler] Electron app started in 641ms: loading app requires=2ms, single instance lock=2ms, portable check=0ms, userdata dir=0ms, defining args=0ms, setting env=0ms, app on ready=75ms, loading settings key=2ms, reading app settings=11ms, creating main window=31ms, configuring main window=18ms, restoring main window position=1ms, setting ipc handlers=9ms, setting global shortcuts=0ms, subscribing to power events=0ms, setting request handlers=0ms, main window ready=330ms, main window shown=32ms
[DEBUG] 2024-05-07T20:58:41.535Z [settings-manager] Theme changed dark
[INFO ] 2024-05-07T20:58:41.538Z [usb-listener] Starting USB listener
[DEBUG] 2024-05-07T20:58:41.538Z [native-module-connector] Starting native module host
[INFO ] 2024-05-07T20:58:41.624Z [start-profiler] App started in 515ms: fetching=225ms, pre-init=296ms, loading modules=51ms, document ready=10ms, creating app model=2ms, loading configs=65ms, initializing modules=2ms, loading remote config=3ms, checking features=0ms, initializing storage=0ms, starting usb=0ms, first view rendering=86ms, app ready event=0ms
[INFO ] 2024-05-07T20:58:42.128Z [updater] Next update check will happen in 53617s
[INFO ] 2024-05-07T20:58:46.424Z [open:mymegadrive] File open request
[INFO ] 2024-05-07T20:58:46.424Z [open:mymegadrive] Open file from cache, will sync after load dropbox
[DEBUG] 2024-05-07T20:58:46.424Z [storage-cache] Load *REDACTED*
[DEBUG] 2024-05-07T20:58:46.433Z [storage-cache] Loaded *REDACTED* 6ms
[INFO ] 2024-05-07T20:58:46.433Z [open:mymegadrive] Loaded file from cache null
[INFO ] 2024-05-07T20:58:46.843Z [file] Opened file mymegadrive: 409ms, 500 rounds, 615 kB
[DEBUG] 2024-05-07T20:58:46.843Z [app] Add last open file *REDACTED*
 *REDACTED* dropbox /*REDACTED*.kdbx *REDACTED*
[INFO ] 2024-05-07T20:58:46.910Z [open:mymegadrive] Sync just opened file
[INFO ] 2024-05-07T20:58:46.944Z [sync:mymegadrive] Sync started dropbox /*REDACTED*.kdbx {}
[INFO ] 2024-05-07T20:58:46.945Z [sync:mymegadrive] Stat file
[DEBUG] 2024-05-07T20:58:46.945Z [storage-dropbox] Stat /*REDACTED*.kdbx
[INFO ] 2024-05-07T20:58:46.946Z [storage-dropbox] HTTP request POST https://api.dropboxapi.com/2/files/get_metadata
[INFO ] 2024-05-07T20:58:47.378Z [storage-dropbox] HTTP response POST https://api.dropboxapi.com/2/files/get_metadata 200 {"content-type":"application/json","cache-control":"no-cache","x-content-type-options":"nosniff","x-frame-options":"SAMEORIGIN","x-server-response-time":"81","date":"Tue, 07 May 2024 20:58:48 GMT","server":"envoy","content-encoding":"gzip","vary":"Accept-Encoding","x-dropbox-response-origin":"far_remote","x-dropbox-request-id":"*REDACTED*"}
[INFO ] 2024-05-07T20:58:47.378Z [storage-dropbox] HTTP response 200
[DEBUG] 2024-05-07T20:58:47.378Z [storage-dropbox] Stated /*REDACTED*.kdbx *REDACTED* 433ms
[INFO ] 2024-05-07T20:58:47.379Z [sync:mymegadrive] Stat found same version, not modified
[INFO ] 2024-05-07T20:58:47.379Z [sync:mymegadrive] Sync finished no error

[INFO ] 2024-05-07T20:59:15.859Z [updater] Checking for update...
[INFO ] 2024-05-07T20:59:15.859Z [transport] GET https://app.keeweb.info/update.json
[INFO ] 2024-05-07T20:59:15.868Z [transport] Request to https://app.keeweb.info/update.json without proxy
[ERROR] 2024-05-07T20:59:16.069Z [transport] Cannot GET https://app.keeweb.info/update.json Error: certificate has expired
[ERROR] 2024-05-07T20:59:16.069Z [updater] Update check error Error: certificate has expired
[INFO ] 2024-05-07T20:59:16.074Z [updater] Next update check will happen in 86400s
[ERROR] 2024-05-07T20:59:33.575Z [launcher] spawn error: ykman, 10ms Error: spawn ykman ENOENT
```

### Attachments: Screenshots

![image](https://github.com/keeweb/keeweb/assets/31761317/68353745-4f66-4ee7-955e-4e9bb2ec83bc)
![image](https://github.com/keeweb/keeweb/assets/31761317/54dd967d-987b-40dd-905b-ca1fe4fa0321)

**Comment by Aetherinox** [comment]
Thanks for submitting this. 
So, a big confusing, I have confirmed it does occur on v1.18.7. I get the same errors. However, on v1.19.0 (the current development version), works fine.

I'm new to the development team, so I'm having to look into these things a bit more slowly, but from what I see, the certificate for the site is fine, so I'm going to assume it must be checking the certificate for the app itself, which expired on ‎`Saturday, ‎March ‎26, ‎2022 4:00:00 PM`

Between the update and transport module is a signature checker, and I'm willing to bet that is where the error is coming from when it hits on `this.verifySignature(...)`.

There's not much that can be done with the existing version of KeeWeb (v1.18.7). However, there is a newer version currently in development. Once it releases, it will contain a new signature; which should correct the issue.

Version 1.19.0 is currently in development, and I don't get the error on that one, however, there are no signatures for it as it hasn't been signed and released yet.

**Comment by Aetherinox** [comment]
Closing this out for now, as mentioned in my previous comment, this should be OK in the next release.
