### ISSUE TITLE
Password reset

### ISSUE THREAD

**Issue by Brummelke** [keeweb/keeweb#2192]
# please describe your issue here
I need a password reset, because I forgot mine.

KeeWeb v1.18.7 (dfc6201, 2021-07-18)
Environment: electron v12.0.7
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) KeeWeb/1.18.7 Chrome/89.0.4389.128 Electron/12.0.7 Safari/537.36

**Comment by Jurrie** [comment]
Hi @Brummelke,

Thanks for taking the time to create a ticket with all the necessary info. But I'm afraid we can't help you here. Keeweb is a project that can reed Keepass databases. Those databases are basically files where you can store your passwords in. Keeweb is not a project that keeps records of user credentials somewhere.

An analogy would be if you would store your passwords in a Microsoft Excel spreadsheet (_do not do that in real life!_) Ever row in your Excel sheet is for an account you have somewhere. One row is for your Facebook account, one is for your Google account, and so on. You open your Excel worksheet to view and edit paswords. But if you loose your password for Facebook, you do not request a password reset with Excel. Rather, you should turn to Facebook.

That said, there is a "master password" on a Keepass database. If you are referring to that, I'm afraid it it not possible to reset it. It would be a grave security issue if that would be possible.

Hope this helps!
