### ISSUE TITLE
Preconfigured webdav link (in selfhosted mode)

### ISSUE THREAD

**Issue by x-drum** [keeweb/keeweb#220]
Hi,

i would like to selfhost a keeweb instance with a webdav backend in order to share it with multiple users,
it would be great to pre-configure a webdav resource in some way.
There is a way to achieve this currently?

Thanks for keeweb and keep up with the good work

**Comment by antelle** [comment]
Hello! Currently there's no way to achieve this. There are future plans to support pre-configures settings json though.

**Comment by redge76** [comment]
Something like:
https://www.server.com/keeweb/index.html?open=file.kdbx

**Comment by antelle** [comment]
I think, the desired result is to load not only the link but other settings as well - so it might be implemented as index.html?settings or index.html?settings=my-settings.json with settings stored on server.
But I'll think about specifying path in url as an additional option.

**Comment by redge76** [comment]
cool thanks
https://github.com/keeweb/keeweb/commit/f7da41db3ebee1aeebb4be452d91e1ec3e9c9eac
so the config file is in parameter with &config=filename.json

How do you make a config file ? best is to look at the chrome -> F12 -> local storage ?

**Comment by antelle** [comment]
You can add fields from [default](https://github.com/keeweb/keeweb/blob/master/app/scripts/models/app-settings-model.js#L7) section, like this:
```json
{
    "skipHttpsWarning": true,
    "dropbox": false
}
```

**Comment by redge76** [comment]
OK. So I used the F12 -> "local storage" trick in chrome to create a valid configuration.
But the database/files to open are not contained in the configuration. it is in anoter key (fileinfo key)
so this is not enougth to "pre-load" a list of webdav database.
or am I missing something ?

**Comment by antelle** [comment]
There's no option to set a file in preset at the moment.
I think, we can add this feature in future releases.

**Comment by antelle** [comment]
Added an option. In v1.3:
1. add meta-tag kw-config 
2. put [config.json](https://github.com/keeweb/keeweb/blob/develop/util/config-example.json) to your server
3. add webdav file with url and, optionally, credentials

**Comment by redge76** [comment]
Hi
Is there a way to get the already built/compiled version ?

**Comment by antelle** [comment]
@redge76 `wget https://beta.keeweb.info/index.html` (at your own risk)

**Comment by redge76** [comment]
I can't get this to work. I'm trying to use the ?settings=config.json trick because if I understand the meta-tag kw-config has to be added before compilation in index.html.
So I tried to change the config-example.json by just adding my wedav file. And I try to access my index.html with the ?settings=config.json parameter and nothing happens.

**Comment by antelle** [comment]
it's ?config=, not settings

**Comment by redge76** [comment]
ohh... yes better. I don't know where I found this name
Now works...

**Comment by redge76** [comment]
how do you add multiple files ?

**Comment by antelle** [comment]
For now, there's no way. Why do you want to add multiple files? A request to add one file was for corporate environments, where you want to pre-populate webdav info.

**Comment by antelle** [comment]
Implemented this, now you can add multiple files. New config: https://github.com/keeweb/keeweb/blob/develop/util/config-example.json#L38

**Comment by redge76** [comment]
Great! 
I, personally, use 2 DB. One for work related passwords and one for personal passwords. It's more convenient for me to have a clear separation between the 2. 
At work we use multiple DBs. One for each client we have. They all have different master passwords because not all DBs are shared with the same people.

**Comment by redge76** [comment]
Tried the 2DB config and it work great !

**Comment by antelle** [comment]
Would you be interested in enterprise version, so that you will not have to make a separate db per user and use access control lists instead?

**Comment by redge76** [comment]
That would be quite complicated as the DB are also sent to the customer. We also already have some full web solution. (manageengine)
thanks for the proposal anyway...

**Comment by pkoevesdi** [comment]
> Added an option. In v1.3:
> 
>     1. add meta-tag kw-config
> 
>     2. put [config.json](https://github.com/keeweb/keeweb/blob/develop/util/config-example.json) to your server
> 
>     3. add webdav file with url and, optionally, credentials

How can I protect the json with the credentials inside from the public, but make them readable by keeweb?
