### ISSUE TITLE
Word wrap in notes field

### ISSUE THREAD

**Issue by philogit** [keeweb/keeweb#221]
The notes field appears to wrap lines at the last character vs wrapping at the last complete word.

Example:

Current line wrapping:
```
this is the most venerab
le of the leviathans
```

Expected word wrapping:
```
this is the most 
venerable of the 
leviathans
```

=======

KeeWeb v1.1.4 (08087c3, 2016-04-21)
Environment: electron v0.37.4
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_4) AppleWebKit/537.36 (KHTML, like Gecko) KeeWeb/1.1.4 Chrome/49.0.2623.75 Electron/0.37.4 Safari/537.36

**Comment by antelle** [comment]
Deployed to https://beta.keeweb.info/

**Comment by philogit** [comment]
I just tested the beta version and it appears to now be fixed.
