### ISSUE TITLE
Display group names with entries

### ISSUE THREAD

**Issue by philogit** [keeweb/keeweb#224]
KeeWeb currently displays entries without providing information about which groups they belong to. This leads to confusion when attempting to disambiguate entries that exist in different groups but have similar names or similar content.

## Desired behavior:
* Each entry in list view should display the group that it belongs to.
<img width="447" alt="kw list view" src="https://cloud.githubusercontent.com/assets/12819820/15234247/8fc3a2be-1864-11e6-8f8b-715c7b5e03f5.png">

* Entry details should display the name of its group in the attributes area.
<img width="538" alt="kw detail view" src="https://cloud.githubusercontent.com/assets/12819820/15234560/c13dd1e0-1867-11e6-9c4b-9a948037d09e.png">

## Use examples:

Imagine that you have three amazon.com accounts: one each for yourself, your spouse and your company. Each entry is named 'Amazon' and sits under separate groups for yourself, your spouse and your company. Search results for 'amazon' would return ambiguous results. 

Currently, the only way to disambiguate is to (1) click each entry and check for key differences (e.g., email address), (2) narrow the search by first clicking on the group that you believe that you are searching within, (3) include the name of the group in the title of each entry (e.g., 'Mary's Amazon')--partially defeating the purpose of groups. 

Similar issues: #152, #219 

===
KeeWeb v1.1.4 (08087c3, 2016-04-21)
Environment: electron v0.37.4
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_4) AppleWebKit/537.36 (KHTML, like Gecko) KeeWeb/1.1.4 Chrome/49.0.2623.75 Electron/0.37.4 Safari/537.36

**Comment by antelle** [comment]
> Each entry in list view should display the group that it belongs to.

That would be a bit strange. We don't want to show a lot of info inside the entry card in list view. An option to show the group will be available in the upcoming release as a configured field in table view.

> Entry details should display the name of its group in the attributes area

This will be added, mentioned in #149

**Comment by philogit** [comment]
> That would be a bit strange. We don't want to show a lot of info inside of the entry card in the list view. 

I may be unusual in how I setup my file, but from my perspective, displaying the group name would be more useful than displaying summary information as in the current design. Perhaps providing an option to swap group names for summary info extract could be a solution. Another idea might be to prepend or append the group name to the summary extract without being visually distracting.

> An option to show the group will be available in the upcoming release as a configured field in table view. 

Making the group available as a column is a fine solution.

>What we may do here, is grouping entries in the list view by group. But I'm not sure about this, as sorting will behave strange. May be added in future releases as an app option.

KeePass groups entries in the list view by group, so it's expected behavior from users transitioning from that application (like myself). You could add a sort option override checkbox for grouping by group, with the remaining field sort options (title, website, user, etc.) left to sub-sort within groups when activated.

Thank you for your thoughtful comments. I'm very appreciative of the intuitive design of this project.

**Comment by aisbergde** [comment]
>An option to show the group will be available in the upcoming release as a configured field in table view.

I can't find how to setup to show the whole path of groups. My normal usage of KeePass (in other programs, using keepass databases) is to use the search function to find something related and then to switch to the group, where I can find the other related entries (siblings).

I have no idea how I can do this in keeweb: I can find entries using the search, but this ends in a dead end: The name of the group is shown, but this is not helpful to find this group in the tree.

It would be fine to see the whole path of the entry. And the final wish would be to jump from the current entry to the group in the tree, where it is located together with siblings. Currently it is only possible to jump back to the search result list.

I suggest any kind of synchronization between the current item and the tree.

**Comment by antelle** [comment]
Right, it's currently not possible to display full group name, but it would be good, I agree.
