### ISSUE TITLE
Cannot open file with path including spaces

### ISSUE THREAD

**Issue by ehannes** [keeweb/keeweb#230]
It appears as if it's not possible cannot open files when path name includes spaces.

With `test.kdbx`, everything works fine. Naming it `test 1.kdbx`, gives the following error:

```
keeweb Error: ENOENT: no such file or directory, open '1.kdbx
```

### Update
I use KeeWeb v1.1.4 on Ubuntu 16.04.
When I open the file via the **Open** button in the program, it works.

**The problem is when I try to open the file by double clicking on it.**

**Comment by antelle** [comment]
Hello! 
Please add more details: which app are you using? How do you open the file? 
Simple case works for me.

**Comment by ehannes** [comment]
I use KeeWeb v1.1.4 on Ubuntu 16.04.
I have tried to open the file by clicking on it and via the **Open** button in the program.

**Comment by ehannes** [comment]
@antelle See update above.
