### ISSUE TITLE
Closing Dropbox setup window hangs desktop UI

### ISSUE THREAD

**Issue by philogit** [keeweb/keeweb#232]
## Steps to repeat:
1. Open the desktop app.
2. From the locked screen, click the 'More ...' icon.
3. Click the 'Dropbox' icon.
  * 'Dropbox - API Request Authorization - Sign in' window opens.
  * Dropbox icon begins spinning animation.
4. Close the Dropbox window (x) without signing into Dropbox.
  * The user is returned to the expanded 'More ...' state.
  * The Dropbox icon continues to spin.
  * The UI no longer responds to commands except for Quit.

### NOTES:
* I have tested this behavior on the Mac desktop version only, not the Windows or Linux desktop versions.
* This issue does not appear in the web app.

====

KeeWeb v1.1.4 (08087c3, 2016-04-21)
Environment: electron v0.37.4
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_4) AppleWebKit/537.36 (KHTML, like Gecko) KeeWeb/1.1.4 Chrome/49.0.2623.75 Electron/0.37.4 Safari/537.36

**Comment by antelle** [comment]
Deployed to [beta.keeweb.info](https://beta.keeweb.info), will be available in the next release
