### ISSUE TITLE
Can not move items when using web app in Safari

### ISSUE THREAD

**Issue by matteoipri** [keeweb/keeweb#236]
Hi,
I cannot move items around when I use the web app in Safari.
Steps to reproduce:

0. go to [https://app.keeweb.info](https://app.keeweb.info) or [https://beta.keeweb.info](https://beta.keeweb.info) or on a self hosted instance
0. open the demo database (or an existing one) 
0. choose an entry from the password list, for example the fourth, "Facebook"
0. select it, drag and drop it on a new group, for example "Home"

"Home" doesn't turn blue and the item is not moved to the new group.

    KeeWeb v1.1.4 (08087c3, 2016-04-21)
    Environment: web
    User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/601.6.17 (KHTML, like Gecko) Version/9.1.1 Safari/601.6.17

Thanks for your attention
Matteo

**Comment by antelle** [comment]
Oh I see now. Thanks for adding steps, now it's clear what's not working. I thought you mentioned drag-drop attachments or files. Entries drag-drop is not working, will be fixed soon.

**Comment by matteoipri** [comment]
Thanks!
However, it does work in other browsers on the same computer and in the desktop app.

**Comment by antelle** [comment]
Deployed to [beta.keeweb.info](https://beta.keeweb.info), will be available in the next release

**Comment by matteoipri** [comment]
Thanks, I can confirm that it works!
