### ISSUE TITLE
OSX Desktop Update Agent Failure Message

### ISSUE THREAD

**Issue by anthonyw12123** [keeweb/keeweb#239]
The update agent reports failure when the version is up to date.

- what were your actions?
Clicking the 'Check for Updates' button

- what was wrong?
The message shown was, 'Error checking of updates. Last Successful check was 30 Apr 2016 03:49:24: the latest version was 1.1.4'

- app version
1.1.4

- your user-agent (from Settings/Help section)
KeeWeb v1.1.4 (08087c3, 2016-04-21)
Environment: electron v0.35.6
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_5) AppleWebKit/537.36 (KHTML, like Gecko) KeeWeb/1.0.4 Chrome/45.0.2454.85 Electron/0.35.6 Safari/537.36

- does it happen on Demo or New database?
Seems to be ubiquitous 

- if you are using a test db without your personal data, please attach it
Personal Db.

- please, open dev tools in your browser and attach output log from Console tab 
```
index.html:14 2016-06-05T03:43:19.684Z [updater] Next update check will happen in 86353s
index.html:14 2016-06-05T03:43:19.685Z [updater] Checking for update...
index.html:14 2016-06-05T03:43:19.686Z [transport] GET https://antelle.github.io/keeweb/manifest.appcache
index.html:14 2016-06-05T03:43:19.717Z [transport] Request to https://antelle.github.io/keeweb/manifest.appcache without proxy
index.html:14 2016-06-05T03:43:20.015Z [transport] Response from https://antelle.github.io/keeweb/manifest.appcache: 404
index.html:14 2016-06-05T03:43:20.016Z [updater] Update check error HTTP status 404c.error @ index.html:14
index.html:14 2016-06-05T03:43:20.029Z [updater] Next update check will happen in 86400s
```

**Comment by antelle** [comment]
v1.2 will be loading update info from app domain, instead of github repo.

**Comment by antelle** [comment]
Redirect website has been added, to fix update and notify the users of existing app of the future v1 update.
