### ISSUE TITLE
OneDrive Sync Issues

### ISSUE THREAD

**Issue by anthonyw12123** [keeweb/keeweb#240]
- what were your actions?
Save new, empty database to OneDrive. I use 2FA, if that matters. 

Note that this is not loading an existing database from OneDrive.

- what was wrong?
KeeWeb immdiately crashed upon auth.

It's probably an extension of this ticket, but using 1.1.4 on Win10 caused auth to pass, but no file to appear in OneDrive (unless they're somehow stored without being visible in the web interface), and for all subsequent saved copies created to be consistently corrupted databases with a 0 byte size. I'll attach the 0 byte files when I get on that computer, but the original database was my personal one. 

- app version
1.1.4

- your user-agent (from Settings/Help section)
KeeWeb v1.1.4 (08087c3, 2016-04-21)
Environment: electron v0.35.6
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_5) AppleWebKit/537.36 (KHTML, like Gecko) KeeWeb/1.0.4 Chrome/45.0.2454.85 Electron/0.35.6 Safari/537.36

- does it happen on Demo or New database?
Yes

- if you are using a test db without your personal data, please attach it
I would, but I don't know where the local cache for OneDrive sync is stored.

- please, open dev tools in your browser and attach output log from Console tab 
    (if you are using desktop app, devtools can be opened from Settings/General/Advanced)
The app crashed, so no console.

**Comment by antelle** [comment]
Most probably win-specific. On mac, files can be opened from onedrive.

**Comment by malimM** [comment]
I am experiencing the same error on Linux, it doesn't sync to OneDrive, though the entry I created to test it, gets saved locally.

**Comment by antelle** [comment]
Does it crash on Linux? If no, please attach logs

**Comment by antelle** [comment]
Does it crash for you in v1.2?

**Comment by antelle** [comment]
Looks like fixed / no action. Please reopen if it still occurs in v1.3+.
