### ISSUE TITLE
InvalidStateError in internet explorer when using WEBDAV

### ISSUE THREAD

**Issue by redge76** [keeweb/keeweb#242]
Hi,

I'm trying to use internet explorer to access a db on a webdav enabled webserver.
It works fine with chrome 50 and firefox 47.
But if I use Internet explorer 11.306 in a Windows 10 system, the page hangs when I click OK on the webdav parameter page (where you enter the URL + user + pass).
The OK button starts to "spin" and nothing happens.
The console (F12) display the following message:

2016-06-09T15:44:26.585Z [storage-webdav] Stat https://www.xxxxxx.net/p/keeweb/test123.kdbx
SCRIPT5022: InvalidStateError
keeweb (18,20290)

first google hit returns ... http://stackoverflow.com/questions/23071968/jquery-throws-script5022-hierarchyrequesterror-when-attempted-to-append-a-jquer

Regards,

**Comment by antelle** [comment]
Deployed to [beta.keeweb.info](https://beta.keeweb.info), will be available in the next release
