### ISSUE TITLE
How to create desktop app for windows

### ISSUE THREAD

**Issue by space-curiosity** [keeweb/keeweb#245]
I can't run `electron /tmp` it's showing an  error 

Error: Cannot find module "path/tmp"
Please let us know how to build the desktop application with this.

Thanks a lot

**Comment by antelle** [comment]
Hello!
Have you run `grunt` before it, was it successful?

**Comment by space-curiosity** [comment]
Yes I did and there was too many warning for deprecated modules but I was able to access it through browser.

**Comment by antelle** [comment]
Please try to build from `develop` branch: shrinkwrap was added only in that branch, modules in master can be installed in wrong versions.

**Comment by space-curiosity** [comment]
When I run `grunt` at the beginning it shows this error:
`grunt-cli: The grunt command line interface (v1.1.0)

Fatal error: Unable to find local grunt.

If you're seeing this message, grunt hasn't been installed locally to
your project. For more information about installing and configuring grunt,
please see the Getting Started guide:

http://gruntjs.com/getting-started`

I tried to run `npm install` first and than run `grunt`

**Comment by antelle** [comment]
Which npm and node.js versions do you have?

**Comment by space-curiosity** [comment]
Version: 3.7.3

**Comment by space-curiosity** [comment]
Node: 
v5.9.1

**Comment by antelle** [comment]
Mine is node.js 6 but v5 should be ok.
Do you have node_modules/grunt folder after you run `npm install`?

**Comment by space-curiosity** [comment]
Yes, I do have it

**Comment by antelle** [comment]
And with it, running `grunt` fails with this error?
`Unable to find local grunt`
Very strange. Do you run grunt from the project root?

**Comment by space-curiosity** [comment]
Yes, actually as I mentioned when I run grunt first I get that error and I have to run `npm install` first and when I did I was able to run `grunt`
what I need to do now is being able to run `electron /something` to run the app trough electron not browser and than build the desktop app.

**Comment by antelle** [comment]
Please try this: `cd electron && electron . --htmlpath=../tmp`

**Comment by space-curiosity** [comment]
one question:

When I clone the codes from repository, Should I run `npm install`?

**Comment by antelle** [comment]
Yes. And after switching branches as well. As grunt is an npm package itself, we cannot install npm deps from grunt. It's common for node projects, to run `npm i` first.

**Comment by antelle** [comment]
I assume, it's working for you now?
Build commands are described [here in the readme](https://github.com/keeweb/keeweb#building). Please let me know if something is not so clear and can be explained in more detailed way.

**Comment by space-curiosity** [comment]
I have cloned the develop repository and run `nmp i` and than `grunt`
There was too many errors while I run `npm i` but the grunt was Ok
Let me check the app with `electron . --htmlpath=../tmp`

**Comment by space-curiosity** [comment]
do you have any Idea why anti Virus shows this inside the project `TrojanDropper.VBS.f`

**Comment by antelle** [comment]
No, I don't know.
May be a trouble with something inside NPM module. Most probably it's not a trojan. My anti-viruses (I'm using mac osx) don't complain though.

**Comment by space-curiosity** [comment]
Let me find out what is the problem, I'll let you know about it. It's scary.

**Comment by space-curiosity** [comment]
http://www.infoworld.com/article/3048526/security/nodejs-alert-google-engineer-finds-flaw-in-npm-scripts.html

**Comment by antelle** [comment]
npm has changed unpublish policy after that left-pad issues: http://blog.npmjs.org/post/141905368000/changes-to-npms-unpublish-policy

**Comment by space-curiosity** [comment]
I found couple Trojan hours and Trojan dropper inside node modules.

`node_modules\core-js\client\core.min.js` -> `TrojanDropper.VBS.f`
`node_modules\electron-winstaller-fixed\vendor\winterop.dll` -> `Trojan.Win32.Dropper.bgbb`
`node_modules\electron-winstaller-fixed\vendor\Setup.exe` -> `TrojanDropper.VBS.f  and   `Trojan[:HEUR]/Win32.AGeneric`

Would you please remove them from the  repository?

**Comment by antelle** [comment]
Please write to these module owners. They are not in my repo.
I'm almost sure, it's anti-virus software false report, not real trojans.
