### ISSUE TITLE
keeweb deployment to wildfly (or jboss)?

### ISSUE THREAD

**Issue by achivl** [keeweb/keeweb#248]
Hi everyone! 

Have some of you ever tried to deploy keeweb to an application server like wildfly or jboss ?
I just want to know if it's feasible and how you did it...

Thanks!

**Comment by antelle** [comment]
Hello! Just make this server return static assets (index.html and app manifest), and that's it. Hope you already know how to do it with the server of your choice.

**Comment by achivl** [comment]
hey antelle! Thank you for answering me so fast. Okay i see, so i don't have to generate a war file of keeweb?

**Comment by antelle** [comment]
You can generate it, if you want (sometimes it simplifies the deployment, as I remember from jboss). But it's optional of course: there are only static assets you have to serve, you can return them in any way.
Sure, if you want to store kdbx files on your server as well, you will have to install and configure a webdav module (most probably as a separate server app).

**Comment by achivl** [comment]
Hey! thank you antelle! it worked ;) 
But i have a question, what is the tmp directory?

**Comment by antelle** [comment]
there's no `tmp` directory here: https://github.com/keeweb/keeweb/tree/gh-pages
it's used only for development, if you're building the app from sources
