### ISSUE TITLE
Change pre-defined shortcuts?

### ISSUE THREAD

**Issue by pwFoo** [keeweb/keeweb#250]
Hi,

I tested keeweb and really like it! Maybe I move my clients to keeweb in the near future (after auto-type is implemented ;) ).

I have a problem with the default auto-type shortcut because ctrl + t is browsers "new tab" shortcut. Shortcuts shoult be customizable, but I can't find a way to edit it.

**Comment by antelle** [comment]
Auto-type will be available only in desktop app.

**Comment by pwFoo** [comment]
Ok, auto type with keepass(x) also only works with desktop app, but downloaded latest KeeWeb.win32.exe and can't change shortcuts.

So shortcuts are customizable (change "ctrl + t" to "ctrl + y" as shortcut example) or hardcoded into keeweb?

**Comment by antelle** [comment]
No they are not customizable but there should be no shortcuts conflicting with other apps (like if ctrl/cmd+T would be assigned in browser app for some action). So, there will be no need to change them.
