### ISSUE TITLE
Issue with self-hosted page and Dropbox

### ISSUE THREAD

**Issue by gonik** [keeweb/keeweb#254]
Hello there. Thank you for this excellent piece of software.

I downloaded the standalone html file and followed the instructions you mention

I created a Dropbox app.
I noted the App Key in the New App and
i run this command:
`sed -i.bak s/qp7ctun6qt5n9d6/[APP-KEY]/g index.html`

And I uploaded the index to my server. Now when I access the page and I chose to open from Dropbox I get this window:
![kw](https://cloud.githubusercontent.com/assets/603308/16540324/6e877bde-4069-11e6-8a3f-5b32a9e0eb2e.png)

If i enter the app key in the designated field then the dropbox permission window is popping up to allow  access to the specific app, and after that... nothing! When i press the "Dropbox" icon again, the same window as above is shown!

What am I doing wrong?

**Comment by antelle** [comment]
Using `sed` to replace Dropbox key is no longer supported. Please fill in your Dropbox key. The next version will support json settings.

**Comment by gonik** [comment]
Hello antelle, thank you very much for your prompt reply!
What do you mean "fill in your dropbox key"? Fill it in where?

**Comment by antelle** [comment]
In the screen you pasted
