### ISSUE TITLE
libgconf-2.so.4 not found

### ISSUE THREAD

**Issue by Maxiride** [keeweb/keeweb#255]
I installed KeeWeb via the Arch linux AUR repository, the installation went fine however when launching it from the terminal it crashes due to a missing libraries. Oddly enough I can't find it in the Arch repositories nor the AUR.

Is this an issue I should report to the package maintainer instead of you?

`/opt/keeweb-desktop/KeeWeb: error while loading shared libraries: libgconf-2.so.4: cannot open shared object file: No such file or directory
`
Thanks in advance!

**Comment by Maxiride** [comment]
Well.. that's really odd. Querying the online Arch database via browser didn't found the library. Querying it via terminal using pacman found it inside the gconf package.

Solved installing gconf =)

Still a mystery why the web based database didn't found it :\

**Comment by antelle** [comment]
Hello,

Please try to download electron demo app and run it. Does it work for you?
https://github.com/electron/electron-api-demos

Most probably, this happens because electron version in keeweb v1.1 is
rather outdated, v1.2 will switch to a newer version.

**Comment by Maxiride** [comment]
Please check my second comment. Fixed it myself however I'll keep that in mind when the package will be updated to 1.2 if any issue will rise.

**Comment by retorquere** [comment]
For the `.deb`, a dependency on `libgconf-2-4` will do it.
