### ISSUE TITLE
Help with traduction

### ISSUE THREAD

**Issue by TheSirC** [keeweb/keeweb#256]
Hello ! Thanks for your fabulous work !
I would like to help you translate your app in order for it to reach a broader audience (help ?). I am a french native speaker.
How could I help you do that ?

**Comment by antelle** [comment]
Hello!
Thanks 🎁  
For now, strings are changing rather fast. Technically everything is almost ready but it's not practical, to translate at the moment.
I'll contact you once we're ready for translation. Translations will be handled by a crowdsourcing service (e.g. transifex, or something like it).

**Comment by Loilo** [comment]
As a native speaker I'd be happy to provide German translations. Just to mention that I'd like to be notified as well. :)

**Comment by antelle** [comment]
Translations will be handled here: http://keeweb.oneskyapp.com/
Just uploaded strings and screenshots to it, so translations may be confusing / not full. Please let me know if something is strange.

**Comment by Loilo** [comment]
This looks pretty nice. Do you know some quick intro to that software? I translated some words and am now stuck at a phrase that uses a glossary word because I'm not sure if/how to reference them in the translation.
I've come so far that I've read about glossary terms but I can't find a link to a kind of "glossary overview" in the OneSky app.

**Comment by antelle** [comment]
I'm new to it, just registered there 😆 
Maybe there's a short intro somewhere on their website?
Glossary is like a dictionary for app, e.g. we have terms 'Password', 'Entry', 'Key file' and so on.
Which phrase are you talking about, how does it look like in UI? Their UI is weird a bit...

**Comment by Loilo** [comment]
The first one that came up to me was "return to app" where *app* was kind of hyperlinked as a glossary entry. I'm not sure if the software acknowledges those itself or if you put some of the terms there manually.

btw I'm also not completely sure what form to use. There are formal and informal honorifics (as opposed to the english language). Both are pretty common in software, formal seems a little more common in really big software like Adobe and Microsoft stuff. But in general there's not really a great way to decide on one. I'd just stick with the informal language in the very few places it matters at all. One could change this to two translations, "German (formal)" and "German (informal)" afterwards, but whatever, this is really getting out of hand for a "btw" :D

**Comment by antelle** [comment]
I've added 'app' as a term to glossary. Hm, does it force you to add a sort of link / relation? How does it look like when you are translating it?
I think, we could use formal here...

**Comment by Loilo** [comment]
It does not force me to do, it rather gives a hint that the english phrase conains the glossary term and it needs to be translated (and I can do that in place right there).

The most helpful thing would just be to know if *you* actually kind of referenced glossary items in your phrases. If you did not we can conclude that the software just does that on its own and translators don't need to worry about anything.

P.S.: Yep, decided to stick with formal as well. Sounds much better to me on second hearing.

**Comment by antelle** [comment]
Oh, I got it. It suggests you terms from Glossary, because they should be translated in the same way, e.g. if you call it Trash and translate it as Papierkorb in one phrase, when translating next phrases, you will see a hint that it should be translated as Papierkorb, not Müll (not sure, if this is a real synonym for software trash in German, I haven't seen this anywhere).

**Comment by Loilo** [comment]
It's not, miraculously only "Papierkorb" made it to the translations, but you made your point very clear. Thanks. :)

**Comment by antelle** [comment]
Thanks for your help! Don't hesitate to comment about phrases with missing context, I'll upload screenshots for all of them, or just add a comment what it is.

**Comment by kasoban** [comment]
I commented in one item, but it became redundant because it affects all cases of it:
All entry field names are referenced twice as separate translation strings, once for the entry view and once for the filtering settings menue. Due to this there could easily be a translation mismatch between those two instances, especially if there are multiple valid variants to translate the field name to another language.
Is it possible to directly link those items as dependent on each other?

**Comment by antelle** [comment]
There may be some strange fields. I'll remove duplicates tonight. Obviously we should have one 'website' or 'username' field, there's no need to keep both.

**Comment by Loilo** [comment]
All German phrases are either translated and/or commented. Handing over to @antelle for comment moderation, I just created you another hell of a bunch of work. :)
Also handing over to everyone else for reviewing. 👍

**Comment by lholznagel** [comment]
When I have some time later I will take a look at the german words :)

**Comment by antelle** [comment]
@Loilo thank you so much! Replied to all messages. Now I'll remove duplicates and refine some phrases, then reupload again.

**Comment by antelle** [comment]
Uploaded new file without duplicates

**Comment by Loilo** [comment]
You're welcome. I'm happy to have a small part in this amazing project. :+1: 
It's almost sad that I'll just continue using most software in English. x)

**Comment by antelle** [comment]
If you have any troubles with OneSkyApp, please let me know. We may switch to something else in next versions.
I don't understand it completely, e.g. when I click this red 14, I get an error. But probably it's because upload is not finished/finalized yet, we'll see tomorrow. For now, let's stick with this service, but if you have used alternatives, you can suggest them...

**Comment by Loilo** [comment]
OneSkyApp really does have some drawbacks from what I can tell after intensive one day usage. Saving terms often takes *really* long. You can't switch pages during that - or maybe you can but you don't dare to do so. Great user experience doesn't seem to be their middle name in general. That's not too bad though.

Biggest weak link in my opinion are comments. There's no way to delete or edit your comments (so I left hella lot of typos in there which makes me crazy just a bit), you can't style them at all, line breaks are possible but do get totally misinterpreted (literal `<br/>`, anyone?). There seems to be no way to @mention people in the project as far as I can tell and the notification system is not great on-site, the most helpful things are actually the notification emails I receive whenever a new comment is posted.

It's probably not to bad for a free service and it maybe wouldn't be too bad in general if the comments section wasn't that weak.
I don't know any free alternatives though. The only thing I've worked with regarding translation management is [Transifex](https://www.transifex.com). I liked it but I didn't work very much with it so I can't evaluate it that deeply. You can try it for free <del>but regular plans are probably just too expensive for an open source project anyway.</del>
They seem to offer a free plan for Open Source projects though, it may be worth a try.

**Comment by antelle** [comment]
Wow, you have already completed it? Really fast, thank you so much! Added de-DE locale, fixed some tricky parts in app and deployed to [beta](https://beta.keeweb.info/).
Looks good  🇩🇪 👍  
If you notice that something is not translated, please let me know. Translation updates (if any) may be uploaded to oneskyapp, exports works like a charm, the format is exactly as we expect.

**Comment by antelle** [comment]
It looks like, 4 phrases are missing (but I still can't understand what does these numbers mean):
![app-tr](https://cloud.githubusercontent.com/assets/633557/17945055/dce1a2ac-6a4a-11e6-8c87-207437ea88ef.png)

Wow, we have -33 not approved phrases 😆 
![-33](https://cloud.githubusercontent.com/assets/633557/17945122/35a10dc4-6a4b-11e6-9e64-7f1c15abca07.png)

**Comment by Loilo** [comment]
To be honest, I'm really not sure if the stats are working correctly in any fashion. There have been more approved than translated items for a while now and whenever I use the "Not Translated" filter I'll only get things I already suggested something.

As far as the app does not actively *hide* content from me that needs to be translated we should be fine as of now. x)

**Comment by antelle** [comment]
Would you like me to add a note in Help section about translation contributors, something like 'German translation contributed by ...(authors)...'?

**Comment by Loilo** [comment]
You're free to do so if you want but I actually don't care at all. Also that may get out of hand pretty quickly as some people have and probably others will review the translated terms and then to be fair everybody had to be put into it and the list would get pretty long. :D
So I guess it's fine to just leave it as it is. :)

**Comment by antelle** [comment]
Fair enough.
Next steps we should take for better localisation experience:
- set app language by browser locale, so the app will be displayed in preferred locale automagically, if we have the translation
- make locales external: it's ok to have 2, 3, ... 5 locales but 10..20, it's already not on (added an item to Engineering wiki page)

**Comment by Loilo** [comment]
We maybe should also considere to translate shortcuts.
In particular the "Ctrl" key is named "Strg" ("Steuerung" ≙ "Control") on German keyboards.

I'd say "Ctrl" is at most little-known in Germany. I also consulted my wife — she's not a programmer but kind of well-versed with computers — and while she knows what the Ctrl key is she's sure that the average German user does not.
Maybe the average German user of a password manager does though. x)

Anyhow that's nice-to-have but a pretty niche concern since as far as I can tell from googling different keyboard layouts, Germans seem to be the only people that actually adjusted the modifier keys to their own language.

**Comment by antelle** [comment]
I was pretty sure, they are the same on all keyboards. Ok, I'll add modifiers to locale as well.

**Comment by antelle** [comment]
Which shortcuts are different? We have several strings:
- ⌘ (Command)
- ⌥ (Alt)
- ⌃ (Control)
- Shift
- Sleep
- PrintScreen

**Comment by Loilo** [comment]
Command and Alt stay the same.

Keys that differ are:
[Ctrl] → [Strg] aka Control → Steuerung
[Shift] → [Umschalt] (also different as a composed word: "shift key" → "Umschalttaste")
[Sleep] → [Pause]
[PrintScreen] → [Drucken]

**Comment by antelle** [comment]
I'll add them, thank you.
Hm, is Pause really the same as Sleep?
I'm used to a special Pause/Break key, which is different (but now it's disappearing from keyboards) https://michaelhyatt.com/wp-content/uploads/2010/03/iStock_000004497362Small-carousel.png

**Comment by Loilo** [comment]
That's right, this does not seem to be the same. But what the heck is a "Sleep" key then? I've never seen that on any of my keyboards.

Is this some kind of "send PC to standby" thing on the keyboard?

**Comment by antelle** [comment]
'Sleep+Home' is a special string which we display only for iPhone users, explaining them how to make a screenshot of QR code. Sleep is also known as 'Power button'.
![sleep-wake-and-home](https://cloud.githubusercontent.com/assets/633557/17946697/1c722bd8-6a52-11e6-90a4-8a404a56805b.png)

**Comment by Loilo** [comment]
Oh, alright. Our wording is more like "lock the phone" and "unlock the phone" but I don't think we really use any word for that.

I've just taken a look into the German iPhone manual though. On a nice picture that key is labeled as "Standby-Taste" – "standby key".

**Comment by Loilo** [comment]
So "Sleep+Home" could be referred to as "Standby+Home", or way more clearly as "Standby+Home Taste" as an expression of a kind of "keyboard shortcut".

**Comment by Loilo** [comment]
I also took a look into the current beta.
Some translated terms are not in there yet. I suppose you know but I'll still list the one's I've seen here:

* The Beta warning ribbon at the top
* Tooltips for adding, sorting and searching above the items column
* Search options
* The "no tags" modal

After seeing usage in context I also adjusted some translated terms. Others are probably to follow but that's why it's beta. :)

**Comment by antelle** [comment]
Fixed switching tags, ribbon and other.

**Comment by Loilo** [comment]
Great. I'm SO excited for 1.3. :))

**Comment by antelle** [comment]
The only thing left for v1.3 is audit, everything else is [done](https://github.com/keeweb/keeweb/wiki/TODO). Also I'm not sure about #326, maybe we'll also have new KeePass format in this version, this depends on KeePass release dates and feature complexity.

**Comment by Loilo** [comment]
Yep, #326 sounds kind of complex though.

**Comment by Loilo** [comment]
By the way we may in the language dropdown refer to German just as "Deutsch" instead of "Deutsch (Deutschland)". That seems overly verbose to me since there will most likely not be other German versions. Other German standard languages (e.g. in Austria) do differ only very marginally from it so that's probably a hint we can just drop.

**Comment by antelle** [comment]
Yes, let's remove country name, at least while we have only one German version.

**Comment by Loilo** [comment]
Played around in beta some more, translations in the actual "dropdowns" after clicking "Add new" and "Sort" are still missing. :)

**Comment by antelle** [comment]
fixed.
Also added a string: entry => Eintrag

**Comment by sikmir** [comment]
@antelle Could you please clarify how to make new translation available in Plugins?
As far as I see from https://github.com/keeweb/keeweb-plugins/blob/0086ea9fe4b3f808a7a67c51faae3fa3349e1c5f/scripts/download-translations.js#L14:
```javascript
const PHRASE_COUNT_THRESHOLD_PERCENT = 75;
```
That means new translation shoulld reach 75% threshold to be listed in Plugins.
I've translated KeeWeb into Finnish up to 75,2%, however the last plugins update (https://github.com/keeweb/keeweb-plugins/commit/0086ea9fe4b3f808a7a67c51faae3fa3349e1c5f) didn't get it.

**Comment by antelle** [comment]
@sikmir hi! Which language are we talking about? Maybe it's not imported for some reason, I can debug it.

**Comment by sikmir** [comment]
> Which language are we talking about? Maybe it's not imported for some reason, I can debug it.

Finnish

**Comment by antelle** [comment]
```
[fi] 406 / 551 (74%) -> SKIP
```
If you add a couple more phrases, it will appear :)

**Comment by sikmir** [comment]
I see) OneSky just misleaded me:
![scr1](https://user-images.githubusercontent.com/688044/66239125-c0f86a80-e701-11e9-8b44-2f0dc8fe0c0d.jpg)

**Comment by antelle** [comment]
I'm not sure why it calculates it like this.

**Comment by sikmir** [comment]
> If you add a couple more phrases, it will appear :)

Well, added. Now OneSky says 76,6%.

**Comment by antelle** [comment]
Done: https://github.com/keeweb/keeweb-plugins/commit/1e9d1037f77c5f5fdb0ef3b30040abf8de67bf04

<img width="436" alt="Screen Shot 2019-10-04 at 23 16 50" src="https://user-images.githubusercontent.com/633557/66240485-11b99480-e6fd-11e9-9129-2c69166077b7.png">

Thanks for the translation! ❤️
