### ISSUE TITLE
Can't launch 1.2.0 on OSX

### ISSUE THREAD

**Issue by JannieT** [keeweb/keeweb#262]
I just downloaded the version 1.2.0 build for OSX from this link https://github.com/keeweb/keeweb/releases/download/v1.2.0/KeeWeb.mac.dmg and used the installer to move the KeeWeb.app file to my Applications folder. When I double click on the app to launch it, I get a launcher popup that says:

> The application “KeeWeb.app” can’t be opened. 

If I try to launch it by selecting `Open` from the right-click context menu, I get the same popup message.

**Comment by isbad** [comment]
Same thing here, OSX 10.11.5
But run thru: 
> CTRL+Click from application folder → Open → Open from an unidentified developer 

works for me

**Comment by JannieT** [comment]
@isbad - not the same thing. I'm also on OSX 10.11.5 but as I said, the app won't run when I do

CTRL+Click from application folder → Open 

It does not offer the normal "Open from an unidentified developer", but gives the same

> The application “KeeWeb.app” can’t be opened.

instead.

**Comment by Sly777** [comment]
Yeah i'm getting same error. I cannot use keeweb now. 

OSX El Capitan 10.11.5

**Comment by antelle** [comment]
Is there any other message?
On my machine it doesn't show such error. Please open Console app and check if there are errors about KeeWeb.

**Comment by JannieT** [comment]
Thanks for looking into it antelle. When I try to open the app in terminal:

`
open KeeWeb.app
`

I get this response:

> LSOpenURLsWithRole() failed with error -10810 for the file /Applications/KeeWeb.app.

**Comment by antelle** [comment]
@JannieT what is the result of `ls -l /Applications/KeeWeb.app/Contents/MacOS/`?
Does it run with this command `Applications/KeeWeb.app/Contents/MacOS/KeeWeb`?

**Comment by JannieT** [comment]
`ls -l /Applications/KeeWeb.app/Contents/MacOS/` gives:

```
total 24
-rwxr-xr-x@ 1 jannie  admin  8608 11 Jul 21:38 KeeWeb*
```

And running it with Applications/KeeWeb.app/Contents/MacOS/KeeWeb works fine!

**Comment by antelle** [comment]
Resembles this issue in Atom: https://github.com/atom/atom/issues/3093
I think it's because the app executable was renamed in this release: previously is was Electron, now it's KeeWeb.
Please try the following:
1. reboot and try to run the app
2. if it doesn't help: `cd /Applications/KeeWeb.app/Contents/MacOS/ && ln -s KeeWeb Electron`

That's weird, looks like caching issue, I don't know how to fix this bug.

**Comment by JannieT** [comment]
Rebooting did the trick! I didn't need to create the symlink. Thanks a lot.

**Comment by antelle** [comment]
It looks like Finder is caching Info.plist (where the executable name is written) and doesn't update it when the new app is copied. If anyone experienced with macOS development knows how to deal with it, please let me know. But this will happen only for this update: we 'll not update executable name in future releases.

**Comment by pepijnve** [comment]
Did some googling on this issue. Based on the error I was seeing in the console
```
24/08/16 13:39:15,953 open[32758]: spawn_via_launchd() failed, errno=111 label=[0x0-0x281281].com.electron.keeweb path=/Applications/KeeWeb.app/Contents/MacOS/Electron flags=1 : LaunchApplicationClient.cp #963 LaunchApplicationWithSpawnViaLaunchD() q=com.apple.main-thread
```
it looks like the launch service database contains a stale reference to the old executable name.

[`The launch services documentation`](https://developer.apple.com/library/mac/documentation/Carbon/Conceptual/LaunchServicesConcepts/LSCConcepts/LSCConcepts.html#//apple_ref/doc/uid/TP30000999-CH202-BABEJFCD) describes when applications get registered in the launch services databse.
The second bullet states that the Finder should be doing this when you drag an application on to your local disk, but apparently that's not happening in this case.
The first bullet states that a background job rescans applications on boot which is probably why rebooting makes the issue go away.

You probably can't do anything about this except reporting the issue to apple and telling people to reboot...

**Comment by zintrepid** [comment]
I stumbled upon this thread when I ran into this problem today. I was able to fix it by running the following:

`/System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/LaunchServices.framework/Versions/A/Support/lsregister -u /Applications/KeeWeb.app`
