### ISSUE TITLE
Possible to NOT show item details at default

### ISSUE THREAD

**Issue by kevinn** [keeweb/keeweb#263]
Upon unlocking the database, "All items" and the first entry is active/selected thus automatically shown on the details pane (third panel). Which may allow someone other than yourself to glance at the information quickly.

Is it possible to have a toggle/checkbox for this behavior?

**Comment by antelle** [comment]
As a workaround, you can make the browser window small, and it will switch to mobile ui without details. We are not going to add such feature, it would look strange.

**Comment by philogit** [comment]
Another workaround is to create a entry where the title begins with punctuation, e.g. `- empty entry` or `- - - -`. It will sort to the top and be the first entry to appear first when opening, assuming that no other entry begins with punctuation.
