### ISSUE TITLE
Mac OS X: The application "KeeWeb" can't be opened

### ISSUE THREAD

**Issue by Raptor399** [keeweb/keeweb#264]
- what were your actions?

On Mac OS X, I installed KeeWeb 1.2.2 by downloading "KeeWeb.mac.dmg", opening the disk image and dragging and dropping the icon onto the Applications shortcut. Next, I tried to open the Applications folder and opened KeeWeb.

- what was wrong?

The application did not open. Instead I got a popup notice "The application "KeeWeb" can't be opened.

- app version

Version 1.2.2

- please, open dev tools in your browser and attach output log from Console tab 
    (if you are using desktop app, devtools can be opened from Settings/General/Advanced)

The utilities console says the following:

```
15/07/16 09:50:08,728 com.apple.xpc.launchd[1]: (com.apple.xpc.launchd.oneshot.0x10000011.Electron[2174])
Could not find and/or execute program specified by service: 2:
No such file or directory: /Applications/KeeWeb.app/Contents/MacOS/Electron
```

I opened a Terminal and it shows this directory indeed does not exist:
```
~ > ls -la /Applications/KeeWeb.app/Contents/MacOS
total 24
drwxr-xr-x@ 3 patrick  admin   102 Jul 14 21:01 .
drwxr-xr-x@ 7 patrick  admin   238 Jul 14 21:01 ..
-rwxr-xr-x@ 1 patrick  admin  8608 Jul 14 21:01 KeeWeb
```

The application does work when I open it directly from KeeWeb.mac.dmg. It looks like something is missed when installing it?

**Comment by antelle** [comment]
Please read starting from this comment: https://github.com/keeweb/keeweb/issues/262#issuecomment-232121122

**Comment by Raptor399** [comment]
Confirmed, that fixed it!

Thanks @antelle !
