### ISSUE TITLE
Dropbox loading is broken

### ISSUE THREAD

**Issue by Egor3f** [keeweb/keeweb#270]
- what were your actions?

Open app.keeweb.info in clean browser(or on new device).
Pressed "More", Then Dropbox.
Typed in my dropbox login and password.
- what was wrong?

After that i see blank(white) window, url is like that: https://app.keeweb.info/#access_token=***&token_type=bearer&state=***&uid=***&account_id=***
If I repeat the same actions(open app.keeweb.info and press dropbox) I see this blank window again.
There essential data is replaced with asterisks for privacy
- app version

1.2.2
- your user-agent (from Settings/Help section)

Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36 (Latest Google Chrome)
Also tried on iPhone and iPad with the latest iOS.
- does it happen on Demo or New database?

No, only with dropbox
- please, open dev tools in your browser and attach output log from Console tab 
    (if you are using desktop app, devtools can be opened from Settings/General/Advanced)

/#access_token=   &uid=   &account_id=    Document was loaded from Application Cache with manifest https://app.keeweb.info/manifest.appcache
/#access_token=   &uid=   &account_id=    Application Cache Checking event
/#access_token=   &uid=   &account_id=    Application Cache NoUpdate event

I have replaced my token and uid with whitespaces for privacy.

Please, fix that bug, because now app is completely unusable.

**Comment by antelle** [comment]
Fixed and deployed to [app.keeweb.info](https://app.keeweb.info), please let me know if it works for you now.

**Comment by mmirg** [comment]
I seem to witness this same phenomenon on an iOS device when app.keepass.info is "installed" as a webapp.  When I access the webapp from Safari as an ordinary tab, I am able to authenticate properly with Dropbox and access my files.  However, once the website is added to the home screen and launched from there (in what appears to be an independent browser instance), I encounter a blank white screen after attempting to authenticate with Dropbox.  This happens irrespective of whether I am trying to access the specific Keeweb folder, the entire KeePass directory or even when specified to access Dropbox via an app developer key.  I apologize if I am necrobumping this issue.

**Comment by antelle** [comment]
@mmirg this is another issue, extracted #298
