### ISSUE TITLE
App will always lock after minimizing on OS X

### ISSUE THREAD

**Issue by rogamoore** [keeweb/keeweb#271]
Thanks for the great app!

I´m using the OS X Desktop app. Despite setting ```Auto-lock if the app is inactive``` to ```Don't autolock``` every time I minimize the app or call it via Spotlight/Alfred it will lock as soon as the window appears.

    KeeWeb v1.2.2 (24cde9a, 2016-07-14)
    Environment: electron v1.2.1
    User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_5) AppleWebKit/537.36 (KHTML, like Gecko) KeeWeb/1.2.2 Chrome/51.0.2704.63 Electron/1.2.1 Safari/537.36
    Database: Existing DB

I also tried the beta version.

Any idea what is causing this? It's basically the same as in this issue: https://github.com/keeweb/keeweb/issues/181

**Comment by antelle** [comment]
On mac os x, we don't have the setting 'minimize on lock'. We should add it for mac as well.

**Comment by antelle** [comment]
Fixed and released an update.
Please update your app and test if it works for you.
![keeweb 2016-07-17 15-48-47](https://cloud.githubusercontent.com/assets/633557/16900732/ff07cefc-4c35-11e6-86fc-a101f839b1f4.png)

**Comment by rogamoore** [comment]
Works! Thank you :)
