### ISSUE TITLE
Auto-update was disabled?

### ISSUE THREAD

**Issue by Sigmanor** [keeweb/keeweb#273]
![keeweb_2016-07-17_19-17-16](https://cloud.githubusercontent.com/assets/7986067/16901737/79da18ce-4c54-11e6-9ef3-518ce5fbcdd9.png)

- Windows 10
- KeeWeb v1.1.4

**Comment by antelle** [comment]
It's not possible to update from v1.1 to v1.2 automatically.
We update only html/js, not electron binaries, and electron api has changed since that.
