### ISSUE TITLE
Clear search box on focus from keyboard shortcut

### ISSUE THREAD

**Issue by smacleod** [keeweb/keeweb#275]
I would like the search box to be emptied when focused using a keyboard shortcut (e.g. Cmd+f). 

Generally when using the search shortcut I would like to perform a new search. As it is now, my previous search remains and I must remove it before searching. This means in order to start my new search I must type "Cmd+f, Cmd+a, delete". While not *that* much work, it catches me up a number of times as I forget to clear the box and just start typing.

Note: I am more than happy to write the patch for this feature, assuming it is desired.

**Comment by smacleod** [comment]
An alternative would be to focus the box, but also select the current contents rather than emptying, this would allow users to just start typing, or un-select the current contents if they'd like to keep it.

**Comment by antelle** [comment]
> I must type "Cmd+f, Cmd+a, delete"

Don't press Cmd+F at all, just start typing.
Yes, we have to select a search box on Cmd+F, like in Finder.

**Comment by antelle** [comment]
Deployed to [beta.keeweb.info](https://beta.keeweb.info), will be available in the next release. Thanks for the tip. 🎁

**Comment by philogit** [comment]
+1 That's a very helpful improvement. Thanks!
