### ISSUE TITLE
Include version number in filenames in releases

### ISSUE THREAD

**Issue by koterpillar** [keeweb/keeweb#282]
Currently, the released files are named like `KeeWeb.linux.x64.zip`, which confuses at least `pacaur`: https://github.com/rmarquis/pacaur/issues/532, making it mis-cache the old version.

Including the version numbers, like `KeeWeb-1.2.4.linux.x64.zip`, would be nicer to all the users.

**Comment by antelle** [comment]
Isn't it possible to rename after download? I don't want to change app url

**Comment by antelle** [comment]
But let's add a version to the installers, because latest/.../*.zip doesn't work anyway, so there's a version in url.

**Comment by antelle** [comment]
Next version will have such files:
```
$ ls -l dist/desktop/
total 651928
-rw-r--r--  1 Antelle  staff  42311539 Jul 22 22:00 KeeWeb-1.2.4.linux.ia32.zip
-rw-r--r--  1 Antelle  staff  41886650 Jul 22 22:04 KeeWeb-1.2.4.linux.x64.deb
-rw-r--r--  1 Antelle  staff  41879036 Jul 22 22:00 KeeWeb-1.2.4.linux.x64.zip
-rw-r--r--@ 1 Antelle  staff  41683358 Jul 22 22:01 KeeWeb-1.2.4.mac.dmg
-rw-r--r--  1 Antelle  staff  31699800 Jul 22 22:04 KeeWeb-1.2.4.win.ia32.exe
-rw-r--r--  1 Antelle  staff  42903601 Jul 22 22:00 KeeWeb-1.2.4.win.ia32.zip
-rw-r--r--  1 Antelle  staff  38106936 Jul 22 22:04 KeeWeb-1.2.4.win.x64.exe
-rw-r--r--  1 Antelle  staff  52901279 Jul 22 22:00 KeeWeb-1.2.4.win.x64.zip
-rw-r--r--  1 Antelle  staff    393578 Jul 22 21:59 UpdateDesktop.zip
```

**Comment by koterpillar** [comment]
That will be perfect, thank you!
