### ISSUE TITLE
Open the popup (after entering the password) in background

### ISSUE THREAD

**Issue by Loilo** [keeweb/keeweb#283]
Once in a while when I entered my password and KeeWeb opens there will open an empty popup after about half a second. I'm pretty sure it's the third-party webpage belonging to the cloud provider I use.

The problem with that is kind of marginal but still I perceive it as really annoying: Until the popup closes (which lasts about a little shorter than one second) the KeeWeb window loses focus in favor of the popup which means I can't just type-and-search for the password I need.

So my suggestion for an enhanced usability would be to open this popup behind the original KeeWeb window and only drag it to the foreground if it requires any kind of interaction (which should be detectable somehow).

**Comment by antelle** [comment]
What do you mean as 'cloud provider'? Dropbox?
Are you using desktop or web app?

**Comment by Loilo** [comment]
I'm using the OS X desktop app. "Cloud provider" refers to, in my case, OneDrive.

**Comment by antelle** [comment]
Yes, onedrive shows a popup to authorize the app. We can make a request without ui first and only then show a popup. Or, at least, show it in background first.

**Comment by Loilo** [comment]
Kind of that would be nice from a UX viewpoint I guess. :)

**Comment by antelle** [comment]
Deployed to [beta.keeweb.info](https://beta.keeweb.info), will be available in the next release
