### ISSUE TITLE
Can't connect to Mac OS X Server webdav service

### ISSUE THREAD

**Issue by ulrith** [keeweb/keeweb#288]
Hi Keeweb developer!

I'm trying to connect to Mac OS X Server file sharing (webdav feature) through webdav dialog.

I'm getting the error

```
[DEBUG] 2016-07-29T11:03:00.871Z [storage-webdav] Stat https://192.168.104.102/Dev/solar.kdbx
[DEBUG] 2016-07-29T11:03:00.910Z [storage-webdav] Stat error https://192.168.104.102/Dev/solar.kdbx 38ms
```

I've tried both versions: app for Linux and web-version.

I can successfully connect to the server by native Finder dialog on another Mac.

**Comment by antelle** [comment]
You have to configure CORS on your server: https://github.com/keeweb/keeweb/wiki/WebDAV-Config

**Comment by ulrith** [comment]
As I wrote I'm talking about **Mac OS X Server** which is separate app on Mac OS X which provide webdav file sharing service, I don't use apache nor nginx.
Also I've already posted my app's error log above.

**Comment by antelle** [comment]
I don't know how to configure your server, apache and nginx configs are just an example, to get an idea.
This app log doesn't include error details, mode probably you copied it from Settings / Advanced / Show logs, but what I need is log from devtools with detailed error description. But I'm sure, there will be OPTIONS request error.
