### ISSUE TITLE
App randomly fails to lock

### ISSUE THREAD

**Issue by philogit** [keeweb/keeweb#290]
My 'Auto-lock if the app is inactive' value is set to 'In 15 minutes'. However, the app will occasionally fail to lock when inactive for more than 15 minutes, even when returning to my system after significant inactivity (e.g., a few hours or overnight).

I hesitate to open this ticket simply because there is little information to report outside of these symptoms. The log file shows only normal activity.

* EDIT: typo
---
KeeWeb v1.2.4 (c30e305, 2016-07-20)
Environment: electron v1.2.6
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) KeeWeb/1.2.4 Chrome/51.0.2704.106 Electron/1.2.6 Safari/537.36

**Comment by antelle** [comment]
I'll test it and add some logs of events which prevents app from locking, then we'll be able to figure it out.

**Comment by antelle** [comment]
What's your computer sleep setting? Inactivity locking works in the following way: the app receives keystrokes and clicks, if nothing happens, it's increasing the counter every minute. If the computer is not active, the counter is not increased. Most probably this is what has happened. I've replaced it and now it should not happen, you can try on beta (beta version can be switched on in app settings).

**Comment by philogit** [comment]
I just tried out the beta version (by switching it on in the app settings) and found that the app still won't lock when expected.

Latest actions:

> Assuming a 15-minute auto-lock.
> Sleep settings: `systemsetup -getcomputersleep` => Computer Sleep: after 1 minutes

* Do something in KeePass.
* Manually put the MacBook to sleep (hold power button for a second).
* Set a timer for 30 minutes.
* Log in to MacBook.
* KeePass remains unlocked.

**Comment by antelle** [comment]
Does it lock in 1 minute after returning from sleep?

**Comment by antelle** [comment]
btw electron has added [power monitor](http://electron.atom.io/docs/api/power-monitor/) module, so now we can handle sleep/resume, very good, I'll add it to the app.

**Comment by antelle** [comment]
Added power events handling, works for me. But it requires an update in electron code, not only html which can be downloaded with beta button. Latest beta: [mac](http://antelle.net/files/KeeWeb-1.3.0-beta.mac.dmg), [win](http://antelle.net/files/KeeWeb-1.3.0-beta.win.x64.zip)
