### ISSUE TITLE
Option to remove the open, new, .. buttons

### ISSUE THREAD

**Issue by redge76** [keeweb/keeweb#292]
Hi,
Now that we have a way to provide an already configured keeweb page, It would be nice to have a way to disable/hide the open, new, demo, settings buttons. The same way as the option there is already to disable webdav, google, onedrive, dropbox buttons.
Disabling the settings can also be interesting to have a userproof  setup. Where they can create a local file and loose everything when they change PC.
The disable settings option would be only available by editing a configuration file.

**Comment by antelle** [comment]
Deployed to [beta.keeweb.info](https://beta.keeweb.info), will be available in the next release
```json
{
    "canOpen": false,
    "canOpenDemo": false,
    "canOpenSettings": false,
    "canCreate": false,
    "canImportXml": false
}
```
