### ISSUE TITLE
Easy easy way to create a configuration file

### ISSUE THREAD

**Issue by redge76** [keeweb/keeweb#293]
Hi,
Can you provide an easy way to create a configuration file?
For ex. You could provide a link on the "general settings" page that display a config file matching the current settings and selected kdbx files.
You could also add on this page a small text to explain how to use the file (the kw-config and ?config= options)

**Comment by antelle** [comment]
A wiki page with description of config keys should be created. Special configurator app is out of scope...

**Comment by redge76** [comment]
I was not referring to a separate app. I think that a way to easily export the current configuration to a file would be great. A full configuration file is just a concatenation of the appSettings and fileInfo keys of the the local app storage. Just display the 2 keys somewhere in keeweb and all there is to do is copy/paste this to a config.json file.

**Comment by antelle** [comment]
appSettings and fileInfo may contain more info than app config must contain. I'd prefer not to export them, and instead, make config by hand, specifying what's really supported. Anyway, you can get currently running settings with kw.settings.get().

**Comment by antelle** [comment]
Description updated: https://github.com/keeweb/keeweb/wiki/Configuration#json-app-config
