### ISSUE TITLE
Auto-type with multiple monitors on mac is incorrect

### ISSUE THREAD

**Issue by stuarta0** [keeweb/keeweb#294]
This might be by design, but auto-typing into Chrome uses the active Chrome window on the same monitor as KeeWeb (Desktop).  In KeePass on Windows, the monitor that KeePass occupies is irrelevant to the window it's typing into.

The same behaviour occurs when clicking on a link in KeeWeb.

**Comment by antelle** [comment]
It's operating system who manage active apps. KeeWeb hides itself and then performs auto-type to the window which got focus. It's something we cannot change.
