### ISSUE TITLE
App v1.2.4 fails to launch on OSX 10.11.5

### ISSUE THREAD

**Issue by mitchellnemitz** [keeweb/keeweb#295]
### To Reproduce

On `OSX 10.11.5` download [`Desktop apps v1.2.4`](https://github.com/keeweb/keeweb/releases/download/v1.2.4/KeeWeb.mac.dmg), mount the dmg, copy `KeeWeb.app` to `/Applications/KeeWeb.app` and attempt to open through Finder in any way (double click, right click -> open, cmd-o, etc)

**Expected behavior**: The app opens

**Actual behavior**: The app fails to open with the rather cryptic message `The application “KeeWeb.app” can’t be opened.`

### Debugging Attempt

```
$ cd /Applications
$ open KeeWeb.app/
LSOpenURLsWithRole() failed with error -10810 for the file /Applications/KeeWeb.app.
$ sudo open KeeWeb.app # This works
$ ./KeeWeb.app/Contents/MacOS/KeeWeb # This works
```

### More Info

The app ***does*** open when launched from within the mounted dmg, which is incredibly confusing. I've observed the same behavior with available previous versions of the app. I have "Allow apps from anywhere" selected in security and privacy and I have tried with System Integrity Protection on and off. I have not (yet) attempted to build the app myself.

**Comment by antelle** [comment]
#262
TL/DR: reboot

**Comment by mitchellnemitz** [comment]
Ah, plist caching, thanks @antelle. I only searched open issues. My apologies.

**Comment by antelle** [comment]
It's okay... Very annoying issue for this release, unfortunately :(  the executable file was renamed and finder caches this.
