### ISSUE TITLE
Dropbox popup doesn't work in installed webapp

### ISSUE THREAD

**Issue by antelle** [keeweb/keeweb#298]
From https://github.com/keeweb/keeweb/issues/270#issuecomment-237664121

I seem to witness this same phenomenon on an iOS device when app.keeweb.info is "installed" as a webapp. When I access the webapp from Safari as an ordinary tab, I am able to authenticate properly with Dropbox and access my files. However, once the website is added to the home screen and launched from there (in what appears to be an independent browser instance), I encounter a blank white screen after attempting to authenticate with Dropbox. This happens irrespective of whether I am trying to access the specific Keeweb folder, the entire KeePass directory or even when specified to access Dropbox via an app developer key. I apologize if I am necrobumping this issue.

**Comment by alexandru** [comment]
FYI, it also happens to me.

**Comment by antelle** [comment]
yes, it's not implemented, because there are no popups in installed apps: Dropbox integration should be implemented in a different way,

**Comment by eli-oat** [comment]
Is there a workaround for this issue? As reported above, I'm unable to login to dropbox on iOS when the web app is saved to my home screen. 

I have 2 factor authentication turned on, which may also be impacting things.

**Comment by antelle** [comment]
The only workaround is
