### ISSUE TITLE
Generate password shortcut while password field is focused

### ISSUE THREAD

**Issue by jhass** [keeweb/keeweb#301]
Using Linux.

I usually have the following workflow:

1. Alt+N
1. Enter Title
1. Tab
1. Enter user
1. Tab

Now in order to generate a password I have to switch to the mouse. It would be much easier if Ctrl+G popped up the generator and the generated password then could be accepted with Enter or maybe even just inserts a generated password with the default settings.

**Comment by antelle** [comment]
Deployed to [beta.keeweb.info](https://beta.keeweb.info), will be available in the next release.
⌘G &rarr; show inline generator
Enter &rarr; close field and set value from generator

**Comment by jhass** [comment]
Almost perfect, could you also put the focus back into the password field after enter, so one can tab to the next field?

**Comment by antelle** [comment]
So, your proposal is to insert generated password into field and focus it, right? I'm thinking about it as well because there's another point in it: if we just replace the field silently (as implemented now), the user might not understand that it has been replaced.

**Comment by jhass** [comment]
Yes, the only issue with that is that it displays the generated password, while you never may want to see it. Personally I wouldn't mind an explicit toggle, like  the eye icon you often see to toggle such on password entries.

**Comment by antelle** [comment]
Done, deployed to beta.
Generating hidden password is another story (rather large), eventually it will be implemented but not now, when we always show passwords in the ui.

**Comment by jhass** [comment]
Thanks!

**Comment by benzkji** [comment]
is it possible that this prevents writing an @ and "g" char on mac, even in the username field? at least this is what I'm experiencing on latest beta and mac? (Yosemite)

**Comment by antelle** [comment]
Yes, it was preventing G key, thanks. Fixed and deployed to beta.
