### ISSUE TITLE
app hangs when entries are dragged to group

### ISSUE THREAD

**Issue by erewh0n** [keeweb/keeweb#302]
Attempting a drag/drop of an entry from one group to another causes the app to freeze. The main window stops responding entirely and I have to `kill -9` to recover.

Relevant info:
```
KeeWeb v1.2.4 (c30e305, 2016-07-20)
Environment: electron v1.2.6
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) KeeWeb/1.2.4 Chrome/51.0.2704.106 Electron/1.2.6 Safari/537.36
```

**Comment by antelle** [comment]
Hello,
Please add more info to this issue:
- does it happen on Demo db?
- from which group and to which (what matters here, is path in tree structure, and not concrete names) do you move entries?

**Comment by antelle** [comment]
please feel free to reopen with more info
