### ISSUE TITLE
Can't open a hidden database

### ISSUE THREAD

**Issue by KevinSeroux** [keeweb/keeweb#303]
Hello,

KeeWeb can't open hidden databases (e.g. a file named ".db"). Once the database location set, the buttons to select the key or to access to the db do nothing. Same problem on the desktop and web version.

Thanks

**Comment by antelle** [comment]
What do you mean as 'hidden'? Is it hidden in windows filesystem? Or it's located in cloud, e.g. Dropbox, and named .db?

**Comment by KevinSeroux** [comment]
I mean the way that Linux considers a file as beeing hidden. It just means a file on a HDD whose name start with a dot.

**Comment by antelle** [comment]
Same as #38 but for linux

**Comment by antelle** [comment]
I cannot repeat it, it works ok for me on linux, here's a video: https://monosnap.com/file/fHIEFDmwMbzvlVy6D3J18A0EX5dcOM
Please feel free to reopen with more info.

**Comment by KevinSeroux** [comment]
Ok, it is a particular case. It seems that the files need (even those starting with a dot) an extension. You can see this here: https://vid.me/xRLv

**Comment by antelle** [comment]
Now I see, your file doesn't have a name...

**Comment by antelle** [comment]
Deployed to [beta.keeweb.info](https://beta.keeweb.info), will be available in the next release

**Comment by KevinSeroux** [comment]
Thanks!
