### ISSUE TITLE
UX Improvement: Select search field when returning to the app 

### ISSUE THREAD

**Issue by Loilo** [keeweb/keeweb#304]
It repeatedly happened that I search for something in KeeWeb, copy it, leave the app and come back some minutes later for another password.

I start typing but then I realize that my search query is appended to the one from some minutes ago.

I think it would be nice to not only have the search field be focused but also selected when returning to the KeeWeb app.
If I need the same password again, I'll just do ⌘/Ctrl + C anyway. But as soon as I start typing, it's very likely that I'm actually searching for another entry and the old search query is irrelevant and thus can be discarded.

**Comment by antelle** [comment]
looks like already done in #275, search is now replaced when you start typing, but I'm not sure, I'll test your case tonight

**Comment by Loilo** [comment]
Oh, should've done a better job searching for that kind of issue.
I've only a 1.2.4 here to test but I'm sure it works well in the 1.3 beta.

**Comment by antelle** [comment]
this might be different...

**Comment by Loilo** [comment]
Mh, that's possible. It naturally only happens when I leave the app with the search field being focused since it'll be still focused when I come back.

**Comment by antelle** [comment]
Oh, it still focused? Previously you mentioned copy with cmd+c.
Yes, that's a separate issue, we just have to select field contents if it's focused when you return to the app, I'll add this.

**Comment by Loilo** [comment]
Well, copying with ⌘+C doesn't take the focus off the search field. :)
