### ISSUE TITLE
Auto Type - Not working in League of Legends client

### ISSUE THREAD

**Issue by Loilo** [keeweb/keeweb#305]
EDIT: This does not seem to be exclusive to global Auto Type shortcut, I adjusted the title accordingly.

As I'm about to open an issue about Auto Type on websites I also tried it in a desktop application to verify if the issue does not appear there.
Unfortunately the only desktop app installed on my current computer using a password is the game "League of Legends".

So to note that: The global Auto Type shortcut does not work there. It's clear that something's reacting to the shortcut since the games' splash screen animation stuttered very notably after pressing the keys but
* no Auto Type window popped up
* this is probably fine since I have only one valid entry for the game and it might have been auto-chosen but then it does not enter a password into the password field

It may be notable that the original KeePass software also has this issue sometimes with the League of Legends client, it might be related to that software being made using Adobe AIR which might bring some special challenges regarding input field focus etc.

**Comment by Loilo** [comment]
As I assumed above, this is probably about the Adobe AIR client architecture. Using Flash causes all kinds of weird stuff, on of it being the password input not regaining focus when leaving and returning to the app.
I guess we can close this as wontfix/cantfix.

**Comment by lholznagel** [comment]
As far as I got from other issues, keeweb is using the url for auto typing. I can be wrong

Offtopic: Lol launcher does not use Adobe Air anymore: [Blog](https://engineering.riotgames.com/news/architecture-league-client-update)

**Comment by Loilo** [comment]
It still does use AIR at the moment. The client update is not out yet and so it still sucks. But Adobe AIR apps should be the exception by today, so it's fine.

b2t: I thought KeeWeb used URL/domain if it detects a browser and window title otherwise. But I'm not sure either.

**Comment by antelle** [comment]
Please paste window name, as we get in in keeweb. Like this:
```
016-08-11T16:44:11.508Z [auto-type] Get window title
app.js?__inline=true:1 2016-08-11T16:44:11.635Z [launcher] spawn osascript: 0, 126ms
idea
app.js?__inline=true:1 2016-08-11T16:44:11.761Z [launcher] spawn osascript: 0, 125ms
keeweb - [~/..../keeweb]
app.js?__inline=true:1 2016-08-11T16:44:11.762Z [auto-type] Window title keeweb - [~/.../keeweb]
```

**Comment by antelle** [comment]
So... has it been fixed in the latest beta?

**Comment by Loilo** [comment]
There are multiple answers.
* It has been fixed if the entry is the only matching one. :+1:
* If there are more than one, the game client does not restore text field focus on coming back to the foreground. That's an issue with the client though and I don't think it can or should be solved by KeeWeb at all.
* It hasn't been solved for me since my password in the concerned entry is an ugly KeePass Reference to another password (à la {REF:P@I:VERYMANYCRYPTICCHARACTERS}) which is pasted as-is by KeeWeb and thus fails the login.

**Comment by antelle** [comment]
Ok, so:
- we can consider that auto-type issue has been fixed
- you're right
- this is not the first report about field references, I'll see what we can do now with references, most probably we'll resolve them and show/use as regular fields, replacing with text once you edit them

**Comment by antelle** [comment]
Thread about references, I'll post updated there, if any: #296

**Comment by antelle** [comment]
Added basic support for field references, you can find details about it [in this issue comment](https://github.com/keeweb/keeweb/issues/296#issuecomment-239690535).
Regarding auto-type: now field references are auto-typed as expected, if it doesn't work for you, please open a separate issue.

**Comment by Loilo** [comment]
Works nicely - thanks! :)
