### ISSUE TITLE
1.3 Beta: Global shortcut Auto Type - "Cannot read property  'getEffectiveAutoTypeSeq' of undefined"

### ISSUE THREAD

**Issue by Loilo** [keeweb/keeweb#308]
Disclaimer: I switched to beta-mode via 1.2.4 settings, not an explicitly compiled 1.3 version. All of this happens on OS X.

On some websites Auto Type fails silently, in my case it was Twitter.
The console states following error message:

> Uncaught TypeError: Cannot read property 'getEffectiveAutoTypeSeq' of undefined

This only happens using the global shortcut. Trying this from KeeWeb with ⌘+T will trigger #306.

**Comment by antelle** [comment]
auto-type will not work if you just switch to beta from v1.2.4 because it requires updating native part of code. but the bug may be valid for v1.3, I'll look into it

**Comment by antelle** [comment]
🎁  fixed, thanks
