### ISSUE TITLE
[Feature request] Support custom UI themes

### ISSUE THREAD

**Issue by kavolorn** [keeweb/keeweb#31]
I think if you increase padding for list items, feeling will become superior.

<img width="1552" alt="screenshot 2015-11-15 11 24 10" src="https://cloud.githubusercontent.com/assets/2448274/11168135/6901be42-8b8b-11e5-9f1f-ee4e82ea27a9.png">

Maybe this could an option in configuration. And maybe only for second column.

**Comment by antelle** [comment]
Maybe will make this as an option (as an options to increase overall fonts size). Personally I like current view looking better.

**Comment by kavolorn** [comment]
For some future release it would be nice to play. I can live with current interface though)

**Comment by antelle** [comment]
I know. As this is HTML app, it's very easy to customize, so it's better to add theming support, so everyone could create a theme and publish it.

**Comment by antelle** [comment]
Renamed this to Themes support, hope you don't mind

**Comment by kavolorn** [comment]
No problem! As you feel it better.

**Comment by frode** [comment]
I agree with @kavolorn here, his UX suggestion looks and feels more comfortable. At the current time I struggle to be comfortable with the current styling compared to MacPass that is much more comfortable mainly because of more space around the overall UI objects.

Font size could also be bumped up a size or two (as a option)

**Comment by antelle** [comment]
Hm, the spacing around elements looks like the same on KeeWeb, 1Password and MacPass:
![pass](https://cloud.githubusercontent.com/assets/633557/13060894/a69961ee-d445-11e5-9a3e-30d494ed5ec6.png)

On the design above the spacing is way higher, making it to look unnatural. To improve it, we can increase the font size as well. This may be developed as an optional theme (but for now it will be built into the app).

**Comment by frode** [comment]
Are you sure? 

![spacing](https://cloud.githubusercontent.com/assets/102189/13078132/7d32734a-d4bd-11e5-9b3a-c7c8ec1dd430.png)

**Comment by antelle** [comment]
You can increase menu with by dragging it, it will be saved.
I'll try to increase left padding a bit for menu and list.

**Comment by frode** [comment]
:+1:

**Comment by antelle** [comment]
You can drag the lower border of tags as well, so only two of them will be visible and they will not bother you. There's a TODO called 'draggable items in left panel', it's about dragging tags, treeview, ... - but it's not planned for the nearest future.

**Comment by antelle** [comment]
Spacing was increased a bit, the preview is on https://beta.keeweb.info

**Comment by Aquila111** [comment]
#528 Won't that help?

**Comment by antelle** [comment]
Next version will support plugins, including CSS themes.
I'm not sure about theme building infrastructure though. Thinking how to make them more usable for development. But anyway, themes will be here.
![kw-plugins](https://cloud.githubusercontent.com/assets/633557/23102131/ab97ca56-f6a3-11e6-9530-4161de534d9f.gif)

**Comment by EnricoMonese** [comment]
I switched to KeeWeb because it has more features. Before I was using https://buttercup.pw, which I found easier and more immediate to use. Would the new plugins allow to get a similar look and layout?

**Comment by antelle** [comment]
@EnricoMonese in terms of UI, it's possible. Probably some things could be very hard or not compatible at all, but at least, you can make keeweb to look like it.

**Comment by EnricoMonese** [comment]
I would actually be fine with just having different colors for each column, which wont probably be too hard. What could get more weird would be getting some [vibrancy](https://developer.apple.com/reference/appkit/nsvisualeffectview?language=objc) in there

**Comment by EnricoMonese** [comment]
Some quick playing around produced this, theming individual parts should not be difficult if the theming/plugins allow for global css, as every area has its specific class name.
![schermata 2017-03-26 alle 19 10 35](https://cloud.githubusercontent.com/assets/19847464/24333436/4cc75d9a-1258-11e7-80d0-b8b7f78d00b0.jpg)

**Comment by Loilo** [comment]
Wow. This is pretty exciting.

Is there already some kind of documentation or primitive example Plugin? 🤓

**Comment by antelle** [comment]
@Loilo, sure, I made a simple page with examples: https://github.com/keeweb/keeweb/wiki/Plugins

**Comment by Loilo** [comment]
That's great, thanks!

**Comment by Loilo** [comment]
While I'm already on it - are there also recent beta builds availble for download (apart from beta.keeweb.info)?

**Comment by antelle** [comment]
We don't have beta desktop, unfortunately.

**Comment by Loilo** [comment]
Okay, then I guess the web version will do the trick. :)

**Comment by antelle** [comment]
Yes, plugin support is implemented only for web, not desktop at the moment.

**Comment by antelle** [comment]
Pushed desktop plugin support, so now you can test them on desktop in beta mode as well.

**Comment by Loilo** [comment]
Isn't Beta mode in the desktop app just a beta.keeweb.info webview anyway?

So I was already able to test it yesterday but in fact I had to set up a HTTPS domain on my server for that. 🤓

Is that different now?

**Comment by antelle** [comment]
Yes, beta mode is just loading beta.keeweb.info, there are no other differences.

**Comment by Loilo** [comment]
So I'll still have to use a HTTPS domain for testing, right? (Since beta.keeweb.info is loaded over it and Chromium security policies won't allow anything else.)

**Comment by antelle** [comment]
Hm, beta button is working fine for me. What happens for you?

**Comment by Loilo** [comment]
It works as long as I provide a HTTPS URL for the plugin - else KeeWeb tells me it could not load manifest.json. According to DevTools that's caused by the browser engine blocking the request since beta.keeweb.info is loading over HTTPS while my localhost URLs is not.

I can use a fake HTTPS localhost URL on beta.keeweb.info (because my browser already knows that I consider the domain secure and thus let's request go through), but Electron's very own Chromium does not know that and thus blocks the https://localhost request. The only way to test there is to use an actual HTTPS URL.

**Comment by antelle** [comment]
I see what you mean, so beta itself is working, but plugins cannot be installed. Yes, it won't work without https. Maybe there are some electron options, but I'm not sure.

**Comment by Loilo** [comment]
There seem to be [Chromium flags](https://github.com/electron/electron/issues/971#issuecomment-68674610) for that.

**Comment by jorgelbg** [comment]
@EnricoMonese do you mind sharing that amazing theme/plugin? 👍

**Comment by thefiredragon** [comment]
@EnricoMonese did you have a copy of your theme elswhere?

**Comment by Fruchuxs** [comment]
To support themes like this from @EnricoMonese, the keeweb desktop version must allow transparent window. @antelle is there an option to enable [this](https://www.electronjs.org/docs/api/frameless-window#transparent-window) through a keeweb plugin, or is this transparent feature too picky?

**Comment by antelle** [comment]
@Fruchuxs what happens if `transparent` property is changed when the window is already created, does it work? In this case yes, it would be very easy.

**Comment by Fruchuxs** [comment]
@antelle digged into it and figured out, that this transparency (respectively "vibrance" effect) is very instable. It must be a frameless window, which make problems with resizing. I like the style, but I think it's to fragil to maintain. ;/
