### ISSUE TITLE
1.3 Beta, Auto Type: There was an error performing auto-type: Helper not found

### ISSUE THREAD

**Issue by benzkji** [keeweb/keeweb#310]
- what were your actions?
Trying autotype with the current beta on MAC.

- what was wrong?
Error message: There was an error performing auto-type: Helper not found

- app version
current beta (single screen setup)

- your user-agent (from Settings/Help section)
KeeWeb v1.3.0 (871987d, 2016-08-14)
Environment: electron v1.2.1
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) KeeWeb/1.2.1 Chrome/51.0.2704.63 Electron/1.2.1 Safari/537.36

- does it happen on Demo or New database?
own, new database

- LOG
[DEBUG] 2016-08-15T06:56:49.686Z [auto-type] Auto type event 
[DEBUG] 2016-08-15T06:56:49.688Z [auto-type] Get window title
[INFO ] 2016-08-15T06:56:49.814Z [launcher] spawn osascript: 0, 125ms
Safari
[INFO ] 2016-08-15T06:56:49.920Z [launcher] spawn osascript: 0, 106ms
https://github.com/login
Sign in to GitHub · GitHub
[DEBUG] 2016-08-15T06:56:49.920Z [auto-type] Window title Sign in to GitHub · GitHub https://github.com/login
[DEBUG] 2016-08-15T06:56:49.923Z [auto-type] Start {USERNAME}{TAB}{PASSWORD}{ENTER}
[DEBUG] 2016-08-15T06:56:49.924Z [auto-type] Parsed [op:USERNAME,op:TAB,op:PASSWORD,op:ENTER]
[DEBUG] 2016-08-15T06:56:49.926Z [auto-type] Resolved [*******,key:tab,[*,*,*,*,*],key:enter]
[ERROR] 2016-08-15T06:56:49.932Z [auto-type] Helper not found. Searched paths: /Applications/__own/KeeWeb.app/Contents/Resources/app/helper/darwin/KeeWebHelper, /Users/benzkji/Library/Application Support/KeeWeb/helper/darwin/KeeWebHelper, /helper/darwin/KeeWebHelper
[ERROR] 2016-08-15T06:56:49.932Z [auto-type] Resolve error Helper not found

**Comment by antelle** [comment]
How did you run this beta? Native helper was added, that's why button 'Try beta' won't work for auto-type.

**Comment by antelle** [comment]
By user-agent, I can see that it was 'Try beta' button. 
Latest beta with helper can be downloaded [here](http://antelle.net/files/KeeWeb-1.2.4-beta.mac.dmg).
btw if you download it and copy helper app to your installed app, the button 'Try beta' will work.

**Comment by benzkji** [comment]
works! thx
