### ISSUE TITLE
[Feature Request] Clone/Duplicate Entry

### ISSUE THREAD

**Issue by PercussiveRepair** [keeweb/keeweb#313]
Most other keepass clients have a Clone or Duplicate Entry function that copies an existing key entry and opens it for editing. A similar function in keeweb would be very useful.

**Comment by antelle** [comment]
Deployed to [beta.keeweb.info](https://beta.keeweb.info), will be available in the next release

**Comment by philogit** [comment]
To anyone searching for this new feature, inside an entry:

* Click `more...`
* Click `Make a copy`
* Go to the destination folder where you want to place the copy.
* Paste using `ctrl-v`/`cmd-v` or `edit > paste`.

**Comment by antelle** [comment]
@philogit, it works a bit different: click `more...` (or right-click) &rarr; `Make a copy` &rarr; entry will be placed in the same folder, it's not possible to paste it in another folder.

**Comment by philogit** [comment]
@antelle : Ah, I see. I've updated my comment. Thanks for the clarification.
