### ISSUE TITLE
Configure WebDAV Server

### ISSUE THREAD

**Issue by luoman8** [keeweb/keeweb#314]
Hello!

Before kicking me out, I have to tell you that i read many times the wiki page about configuring WebDAV but I don't get it and it's still not working :'(

My config is a Synology Server with DSM 6.0.2 and Apache.
I created a file "httpd-cors.conf" in /usr/local/etc/httpd/site-enabled with this:

```
Header always set Access-Control-Allow-Origin "*"
Header always set Access-Control-Allow-Headers "origin, content-type, accept, authorization, if-match, destination, overwrite"
Header always set Access-Control-Expose-Headers "ETag"
Header always set Access-Control-Allow-Methods "GET, HEAD, POST, PUT, OPTIONS, MOVE, DELETE, COPY, LOCK, UNLOCK"
Header always set Access-Control-Allow-Credentials "true"

RewriteEngine on
RewriteCond %{REQUEST_METHOD} OPTIONS
RewriteRule ^(.*)$ blank.html [R=200,L,E=HTTP_ORIGIN:%{HTTP:ORIGIN}]
```

But i still have "network error". Does my config is right ?

I also saw that my OPTIONS request return "**401 Authorization Required**"
Does anyone know if it's possible to enable it without authorization as asked on wiki page on Synology devices ?

Thanks

**Comment by antelle** [comment]
If you create httpd conf, it won't work, you have to find the one Apache is using.
You can google 'Synology Apache httpd location' and try different results, something will work for you (e.g. http://www.synology-wiki.de/index.php/Apache_Webserver).

**Comment by luoman8** [comment]
Synology overwrite custom config done in httpd.conf, but I have one config line "Include site-enabled/*.conf" in httpd.conf so it should include and load my file

Is there any VirtualHost / Location dedicated for WebDAV or is completly different ?

**Comment by antelle** [comment]
It's better to ask on Synology forums...

**Comment by waylonwang** [comment]
I have the same problem on DSM5.2, I think it might be to fix the problem that install an Apache or Nginx server in the docker to provide a new WebDAV services for keeweb

**Comment by antelle** [comment]
Yes, you can take [existing docker container](https://hub.docker.com/r/antelle/keeweb/) and customize it, e.g. make it inherit from nginx webdav, or apache webdav image.

**Comment by alebupal** [comment]
Hello, I have the same problem
I have keeweb in a docker in synology 6.1.4 and I have this error ("network error"):
https://image.prntscr.com/image/2uTzaH4LQOC7IPvy9HhbBw.png
Is there any solution?

**Comment by antelle** [comment]
@alebupal OPTIONS must work without authorization. I don't know how to configure synology thing though, probably makes sense to ask on some synology community.

**Comment by alebupal** [comment]
@antelle 
Finally it works, I found the solution here -> https://github.com/keeweb/keeweb/issues/703#issuecomment-326404286
Thanks to @skad

**Comment by antelle** [comment]
Added a link to Wiki.

**Comment by keiranlovett** [comment]
I looked at solution #703 for a solution but still have 401 issues. Is this no longer working?

**Comment by alebupal** [comment]
Hi, I have it working now and it works perfectly.
There are several bears to consider:
1-. The webdav url that you have to put in must be https with the corresponding https port
2-. Enter in the webdav url that you are going to put, for example (https: // IP: PORT / prueba.kdbx) this will come out:

https://image.prntscr.com/image/EORkNN9eSXeqqeRxI2SiOQ.png (I use chrome)

Click on the link below to access.

This will ask for webdav username and password but you can close it.

the only thing that interested us was to remove the security message that chrome gives us.

This way you will take the file, try again to put the file in keeweb and it should work.

I suppose that if you do this with a ssl certificate you will not have this problem. As I access via vpn I do not use ssl

**Comment by keiranlovett** [comment]
I've set the httpd files on my NAS and I can see in the headers are update to match when I try to load a .kdbx file. If I input the url for the .kdbx in the browser I get the dialog box to input my credentials and it successfully downloads, if I try via KeeWeb and input the credentials I then get the 401 response header with WWW-Authenticate: Basic realm="SYNO_WebDAV Storage"

**Comment by keiranlovett** [comment]
@alebupal are you using a Synology NAS for the webDAV server? If so what is the version? Mine is at: DSM 6.1.6-15266. My 

Looking at your server settings in the above image some lines are different (outside of the redbox), that may also be causing this issue. Hrmmm

**Comment by keiranlovett** [comment]
@alebupal ended up being an issue with my config file on the NAS. I've resolved and its all working - your screenshot helped!

**Comment by alebupal** [comment]
@keiranlovett Ok, fantastic!
I have looked and in the capture there can be confusion because the route of the notebook is changed.
The correct image is:
https://prnt.sc/j3qdhq
