### ISSUE TITLE
[Question] Auto save and sync with WebDAV?

### ISSUE THREAD

**Issue by fenghse** [keeweb/keeweb#316]
In the setting, the "automatically save and sync" is checked. But seems that the changes are not automatically saved. After it is saved, will it push the updates to another device unlocked the same file? Is that possible to open a file located in html server directly?

**Comment by antelle** [comment]
> will it push the updates to another device?

It will not push, but when you save or open the file from another device, or auto-save will happen, it will get the changes. Doesn't it happen for you? Please gather logs then,

**Comment by fenghse** [comment]
Thanks! If I reopen from another device, the changes will show; if I did not close the file first and then reopen it, the change will not show, is that as expected? Seems that the auto-save not working for me. How to gather the logs?

**Comment by antelle** [comment]
Yes, if it's not saved (blue dot next to the file name means there are unsaved changes), changes will be not be shown on another device of course. App logs are in browser dev console or Settings / General / Advanced / Show logs.

**Comment by antelle** [comment]
Looks like invalid... Please reopen if it repeats for you.
