### ISSUE TITLE
Working with multiple concurrently opened databases doesn't work

### ISSUE THREAD

**Issue by childnode** [keeweb/keeweb#317]
When opening two databases, the "files/database tab" at the bottom shows both databases as unlocked but only data from the first database is shown, you are not able to switch between both!

clicking the "inactive" database only opens the settings / save as panel

Version: 1.2.4 Desktop (Mac)

**Comment by antelle** [comment]
All data is shown from all databases. There's no switch between them.

**Comment by childnode** [comment]
uhhh ... ok, I see ... I have to scroll down since I have a lot of groups ... a lot ... god damn it ... who had the idea of this UI/UX?! sorry to be that rugh, but I'm not that stupid end user and I spend more than 10x the time a normal user does looking on this why I can't see the second database..

As long the two opened databases are shown as like "tabs" or "sheets" (if you think about end-users-beloved-Excel) it's quite common to switch the (more or less complete) screen content when selecting one of them.
if you ask me: Using this to allow quick access to the "settings and save" dialog is not that what you expect as a new user.

What about that wrong with this common interface behaviour? What are your reasons to implement it as an concatenated tree list?

At least: I expect to get the focus on the top tree node of the database I "selected" without the need to manually scroll down, hoping not to oversee the anchor node.
It would also help to allow collapsing ...oh yeah ... I see it's on double clicking ... should I repeat my "that's not intuitive" sentence? ;)

**Comment by philogit** [comment]
@childnode: The purpose of this forum is to promote and enhance the development of a creative and valuable program. Therefore, engaging in sarcastic chiding of antelle's design approach is unproductive and downright rude.

A more productive approach is to thank antelle for his ongoing work, his novel approach and his willingness to provide responsive support -- and to collaboratively engage with him to refine a product that many people happily use every day.

**Comment by antelle** [comment]
> I expect to get the focus on the top tree node of the database I "selected" without the need to manually scroll down

You don't need this.
You do, if you want to select entries only from **exactly this** db and only it, excluding other databases. Think of groups as a filter which you put on records. So, you open two databases and get all entries from all of them as one searcheable list.
