### ISSUE TITLE
(T)OTP is saved in custom field, HOTP not supported?!

### ISSUE THREAD

**Issue by childnode** [keeweb/keeweb#318]
The custom support for OTP field is great but:
The (t)OTP key is saved as a custom field "otp". Keeweb has some magic to treat this field as a TOTP field and shows / handles this always in Key-URI format `otpauth://totp/default?secret=<value of otp custom field>` (refer to https://github.com/google/google-authenticator/wiki/Key-Uri-Format) which is shown if you "edit" the field.
Any other keepass client only shows the custom field with the key in, but not the Key-URI notation.

Perhaps it might be useful to save the complete Key-URI and to allow any field containing this notation beeing treated as OTP field!

P.S: I'm also not sure (yes, untested by myself) if HOTP support as described on http://keepass.info/help/base/placeholders.html#hmacotp ?!
 
Version: 1.2.4 Desktop (Mac)

P.P.S. some thoughts when reading how keepass' password placeholder `{HMACOTP}` with `HmacOtp-Secret` custom field combination is implemented, it reads reasonable to only save the key in "otp" but perhaps then, a) a placeholder should be set in password like `{TOTP}` b) use custom field `TOtp-Secret`. BUT: the Key-URI has advantages, like allowing to save the username / visible name in it, in the example above: `default`. For an optional auto-generated otp-keyURI field it would be nice to save the entered username instead of "default"

**Comment by antelle** [comment]
Hm, we are saving complete totp uri. Doesn't it work for you?
> allow any field containing this notation beeing treated as OTP field

No, just use built-in otp field, we don't need additional complexity.
HOTP is supported but not in format KeePass does it. There are no plans to support other formats. But it's not tested much, so there may be issues. For which service do you need hotp support?

**Comment by childnode** [comment]
mhh .. ok, retested this with a new file and otp was saved indeed as Key-URI ;/ but only if key is correct but not for e.g. not for `sdasdfasdfasd` but for `234234234234`
in both cases, keeweb shows a OTP Token ... if the key is invalid, it should not generate a token, shouldn't it?!

@HMAC just to be feature complete ;) no, I do not have a real use case but perhaps others still have? I also don't think it's that hard to implement if TOTP is already in

**Comment by antelle** [comment]
You're right but `sdasdfasdfasd` is a valid base32 string.
If you don't have a real use case, it's better not to ask for the feature: we don't implement features which are needed only for completeness or ideal code. As a said previously, it's implemented but may contain bugs because unlike totp, I don't use it everyday, so it's almost untested.

**Comment by childnode** [comment]
Ack, so feature and change declined but found a bug?

**Comment by antelle** [comment]
Which bug do are you mentioning?

**Comment by kasoban** [comment]
base32 conformity should enforce uppercase letters, not lowercase. Maybe that's what he meant with `sdasdfasdfasd` not being a valid key.

**Comment by antelle** [comment]
@kasoban thanks for mentioning that! will be fixed

**Comment by kasoban** [comment]
Well I don't think it needs to be, I think. Many libraries make the choice to accept both upper & lowercase when interpreting a String assumed to be in base32 format.

Also the case here, as you can see in `Otp.fromBase32`: https://github.com/keeweb/keeweb/blob/88bfa7ec44251d175740b176ac43e666e745964a/app/scripts/util/otp.js#L105

**Comment by antelle** [comment]
Yes, that's why I added lowercase as well. But as all generators generate uppercase, so we should not get lowercase characters here, and I think it's safe to treat them as it's defined in RFC. i.e. upper only.

**Comment by antelle** [comment]
So, I made an investigation: checked this in Google Authenticator and 3 other iPhone and web apps. None of them actually disallows lowercase characters, generated codes are the same. So, let's allow them as well.

**Comment by childnode** [comment]
hi again @antelle and sorry coming back that late

thanks for the investigation but I'm not sure if I understand it what was discussed [since 10am](https://github.com/keeweb/keeweb/issues/318#issuecomment-240338485). To sum up:

@kasoban mentioned and you agreed that base32 enforces uppercases.
"The bug" was (sorry again for [that incomplete info](https://github.com/keeweb/keeweb/issues/318#issuecomment-240337723)) indicated that keeweb allows and consumes lowercase base32 string as secret.

But, what [I meant](https://github.com/keeweb/keeweb/issues/318#issuecomment-240337723):
saving `sdasdfasdfasd` as secret will let keeweb save `sdasdfasdfasd` but not Key-Secret URI format in the "otp" field. other codes are saved in the URI format ... that's strange to me. That's perhaps a (THE) bug?!

P.S: Perhaps, it would be great to auto-correct lowercased inputs to uppercase if this is the right case sense as defined per base32!?

**Comment by antelle** [comment]
Well, if we generate otp uri ourselves and have a possibility to make it valid, it's better to make it valid. Added uppercase transform, deployed to beta.

**Comment by alugarius** [comment]
I use OTP for Google, it works fine...
