### ISSUE TITLE
Save hotkey and change detection not working when input is focused

### ISSUE THREAD

**Issue by kasoban** [keeweb/keeweb#324]
Relates to / possible reoccurence of #144

Steps to reproduce:

1. Open existing entry in your database
2. Click into input, e.g. Title or Password, and start typing
3. Without blurring the input, press Ctrl+S
4. Expected a file sync to happen. Instead, nothing happens.

I suspect this is again due to the fact that KeeWeb doesn't recognize the input value to be 'changed' until the input is actually blurred. What actually happened to me, which is even more dangerous, is that I clicked into an entry, changed the password to a new one, and while still having the input focused closed the electron app. This triggered the expected file sync with GDrive, but my updated password was NOT synced.

Interestingly, if you create a "proper" change first before you reproduce this scenario (so that the blue "changed" indicator appears on the file) and then press Ctrl+S while the input is focused, you will notice that the entire hotkey is blocked and no sync will be triggered.

I'd suggest forcing an input blur and/or value copy when hitting Ctrl+S, or at the very least when clicking the Electron close button.

App info:
> KeeWeb v1.2.4 (c30e305, 2016-07-20)
> Environment: electron v1.2.6
> User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) KeeWeb/1.2.1 Chrome/51.0.2704.106 Electron/1.2.6 Safari/537.36

**Comment by antelle** [comment]
Deployed to [beta.keeweb.info](https://beta.keeweb.info), will be available in the next release

**Comment by benzkji** [comment]
@antelle are you not closing solved issues? methinks we are closer to 1.3 than 2 of 27 issues solved ;-)

**Comment by antelle** [comment]
Workflow states which I use:
- opened, no milestone assigned, 'need-info' label: wait for info, close in case of inactivity
- opened, no milestone assigned, complete info: to triage 
- opened, milestone assigned, not assigned: triaged, not fixed ([possible milestones](https://github.com/keeweb/keeweb/wiki/FAQ#features))
- opened, triaged to vNext, assigned: fixed, available on beta
- closed: available on production
Most of issues have commit linked to them and will be closed automatically by GitHub, once the commit is merged to master branch.

**Comment by benzkji** [comment]
ok thanks. is this somewhere visible? just tried to find out which ones are still open bugs for 1.3...now I know how 👍

**Comment by antelle** [comment]
Yes, you can use [this](https://github.com/keeweb/keeweb/issues?q=is%3Aopen+is%3Aissue+milestone%3Av1.3+no%3Aassignee) filter

**Comment by antelle** [comment]
Another reason to keep them open, is to avoid duplicates: it's unlikely, that someone will search in closed issues for actual bugs.

**Comment by benzkji** [comment]
so when I start getting all those "closed" notifications from github, I know you'll be releasing 1.3 :-)!

💯
