### ISSUE TITLE
Remember key files

### ISSUE THREAD

**Issue by denisgarci** [keeweb/keeweb#325]
First of all thanks for this great app, it solves a lot of issue I have with KeePass and it works on Linux! I'm currently using version 1.2.4 with my *.kdbx file is stored on Dropbox. Each time I open KeeWeb I have to select the key file again. It would be great if KeeWeb could remember the location of the key file.

**Comment by antelle** [comment]
There's a setting 'Remember keyfiles', doesn't it work for you?

**Comment by denisgarci** [comment]
Sorry I didn't see that option. It's working thank you!

**Comment by thomasfrobieter** [comment]
Isn't remembering the keyfile the expected behavior? So why not set 'remember keyfile location' as default?

**Comment by antelle** [comment]
@thomasfrobieter actually yes, now when we have an option to remember keyfile location and not keyfiles themselves, it makes sense.
