### ISSUE TITLE
Auto Type with locked db(s) / latest beta / mac

### ISSUE THREAD

**Issue by benzkji** [keeweb/keeweb#327]
- what were your actions?
trying auto type with locked db(s).

- what was wrong?
db unlocks after password entry, but found entry is copy pasted in keeweb itself.

- app version
1.3 beta, downloaded from your website

- your user-agent (from Settings/Help section)
KeeWeb v1.3.0 (15c5494, 2016-08-18)
Environment: electron v1.2.6
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_1) AppleWebKit/537.36 (KHTML, like Gecko) KeeWeb/1.3.0 Chrome/51.0.2704.106 Electron/1.2.6 Safari/537.36
- does it happen on Demo or New database?
both?

- if you are using a test db without your personal data, please attach it
nope

- please, open dev tools in your browser and attach output log from Console tab 
EBUG] 2016-08-24T09:05:03.999Z [auto-type] Auto type event 
[DEBUG] 2016-08-24T09:05:04.002Z [auto-type] Get window title
[INFO ] 2016-08-24T09:05:04.178Z [launcher] spawn osascript: 0, 176ms
Safari
[INFO ] 2016-08-24T09:05:04.238Z [launcher] spawn osascript: 0, 60ms
https://accounts.google.com/AddSession?continue=https%3A%2F%2Faccounts.google.com%2Fb%2F0%2FAddMailService#identifier
Anmelden – Google Konten
[DEBUG] 2016-08-24T09:05:04.238Z [auto-type] Window title Anmelden – Google Konten https://accounts.google.com/AddSession?continue=https%3A%2F%2Faccounts.google.com%2Fb%2F0%2FAddMailService#identifier
[DEBUG] 2016-08-24T09:05:04.238Z [auto-type] auto-type event delayed
[INFO ] 2016-08-24T09:05:10.028Z [open:benzkji-prive] File open request
[INFO ] 2016-08-24T09:05:10.028Z [open:benzkji-prive] Open file from storage dropbox
[INFO ] 2016-08-24T09:05:10.028Z [open:benzkji-prive] Stat file
[DEBUG] 2016-08-24T09:05:10.028Z [storage-dropbox] Stat /benzkji-prive.kdbx
[DEBUG] 2016-08-24T09:05:10.028Z [dropbox] Call stat
[DEBUG] 2016-08-24T09:05:10.756Z [dropbox] Result stat 728ms ,[object Object],
[DEBUG] 2016-08-24T09:05:10.756Z [storage-dropbox] Stated /benzkji-prive.kdbx 364b3776c1 728ms
[INFO ] 2016-08-24T09:05:10.756Z [open:benzkji-prive] Open file from cache because it is latest 
[DEBUG] 2016-08-24T09:05:10.756Z [storage-cache] Load 7c570a0d-ec8f-9ab3-03b4-1a55555a1657
[DEBUG] 2016-08-24T09:05:10.759Z [storage-cache] Loaded 7c570a0d-ec8f-9ab3-03b4-1a55555a1657 2ms
[INFO ] 2016-08-24T09:05:10.759Z [open:benzkji-prive] Loaded file from cache 
[INFO ] 2016-08-24T09:05:10.868Z [file] Opened file benzkji-prive: 108ms, 600000 rounds, 3 kB
[DEBUG] 2016-08-24T09:05:10.868Z [app] Add last open file 7c570a0d-ec8f-9ab3-03b4-1a55555a1657 benzkji-prive dropbox /benzkji-prive.kdbx 364b3776c1
[DEBUG] 2016-08-24T09:05:10.872Z [auto-type] processing pending auto-type event
[DEBUG] 2016-08-24T09:05:10.873Z [auto-type] Start {USERNAME}{ENTER}{DELAY 1000}{PASSWORD}{ENTER}
[DEBUG] 2016-08-24T09:05:10.874Z [auto-type] Parsed [op:USERNAME,op:ENTER,op:DELAY,op:PASSWORD,op:ENTER]
[DEBUG] 2016-08-24T09:05:10.874Z [auto-type] Resolved [************,key:enter,cmd:wait,[*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*],key:enter]
[INFO ] 2016-08-24T09:05:11.998Z [launcher] spawn /Applications/__own/KeeWeb.app/Contents/Resources/app/helper/darwin/KeeWebHelper: 0, 1123ms
[DEBUG] 2016-08-24T09:05:11.998Z [auto-type] Complete 1124ms

**Comment by antelle** [comment]
🎁  thanks, fixed, uploaded new beta

**Comment by benzkji** [comment]
perfect!
