### ISSUE TITLE
Can't launch 1.2.4 on Mac OS X

### ISSUE THREAD

**Issue by pepijnve** [keeweb/keeweb#328]
After upgrading to the 1.2.4 build I could no longer launch KeeWeb. Double clicking the icon showed an error stating the application could not be opened.

Running `open KeeWeb.app` gave the error `LSOpenURLsWithRole() failed with error -10810 for the file /Applications/KeeWeb.app.` and in the console I saw

```
24/08/16 13:39:15,953 open[32758]: spawn_via_launchd() failed, errno=111 label=[0x0-0x281281].com.electron.keeweb path=/Applications/KeeWeb.app/Contents/MacOS/Electron flags=1 : LaunchApplicationClient.cp #963 LaunchApplicationWithSpawnViaLaunchD() q=com.apple.main-thread
```

Based on that I renamed `Contents/MacOS/KeeWeb` to `Electron` and change the executable name in the Info.plist to Electron. After that change the application launched and the expected gatekeeper confirmation dialog appeared.

This was on OS X 10.11.6

**Comment by antelle** [comment]
#262
TL/DR: reboot
