### ISSUE TITLE
[UI] Remote file selection

### ISSUE THREAD

**Issue by Loilo** [keeweb/keeweb#329]
I stumbled upon this not only on first usage but multiple times, so I actually think this is something that might affect not just me.
When selecting a kdbx database from a remote source (OneDrive in my case) it'll have the available file(s) listed at the bottom right, next to the cancel button.

![open-from-remote](https://cloud.githubusercontent.com/assets/1922624/17946047/dce0656c-6a46-11e6-8acd-996e3a444bf1.jpg)

The issue is that everytime I've had this modal I thought that there is an empty list of files to pick from.
I read the instruction on the left but then I'm not even looking at the bottom right since my unconscious mind tells me that this bright blue thing clearly has to be the "Ok" button.

I think this clearly breaks with user expectations (as long as they have only one database file which seems pretty common to me).

Another possible layout may be to list databases aligned left below the instruction phrase.

It would be nice to hear opinions supporting this or if my mind's just a really strange place. :)

**Comment by antelle** [comment]
I totally agree, this dialog must not look like regular ok-cancel alert.
There must be a special folder selection dialog, with a possibility to display folders and files, go inside folders and back (and maybe a checkbox to display all file extensions, not only kdbx), so it's a subject to refactoring. There are two parts of this story:
1. support folder listing technically (now we just have a plain list of files)
2. redesign the dialog
This will be definitely done in future releases.

**Comment by antelle** [comment]
Finally, this dialog will have proper design soon:
![file-selection](https://user-images.githubusercontent.com/633557/33242913-3a7ac70e-d2dc-11e7-8d93-97c3e50af6ed.png)
