### ISSUE TITLE
Save categories tree collapsed/expanded state

### ISSUE THREAD

**Issue by KhodeN** [keeweb/keeweb#33]
subj. 
* Save/restore collapsed categories on save
* collapsed by default (optionally)

**Comment by antelle** [comment]
Good improvement :+1: , and I've already had some thoughts about it.
Kdbx format supports storing collapsed/expanded state but there's ux trouble. As there is no expand indication icon (+/-, or >, on the left of list), it will be unclear that a group is collapsed and has some groups inside. So, we can open a file with collapsed groups only if the user have already opened it and collapsed them by himself.
So, I'm still thinking, how to make this available.
Collapsed by default: wontfix this. If we have a possibility to store collapsed/expanded state, just collapse them and save.

**Comment by antelle** [comment]
Deployed to [beta.keeweb.info](https://beta.keeweb.info), will be available in the next release
![keeweb 2016-04-17 19-14-27](https://cloud.githubusercontent.com/assets/633557/14588388/114e0ff6-04d1-11e6-9d13-9aa07a4a09ef.png)
