### ISSUE TITLE
[UX] Shortcut to lock the app

### ISSUE THREAD

**Issue by Loilo** [keeweb/keeweb#330]
I've played around with beta.keeweb.info and stumbled upon the fact that ⌘L locks the database.
I think that's fine in the desktop app but in the browser this overrides the default behaviour of focusing the URL bar.
In my opinion browser behaviour should only be overridden where it really makes contextual sense (e.g. ⌘S for the save function of a web app).
At least it should be considered to only listen for ⌘L if a database is actually open so a user can get to the URL bar by using ⌘L twice (1. close the DB, 2. focus the URL bar).

**Comment by antelle** [comment]
We override also some other common shortcuts, like <kbd>⌘</kbd>+<kbd>,</kbd>.
But I agree, if no locking is performed, allowing to focus address bar has sense.

**Comment by antelle** [comment]
Deployed to [beta.keeweb.info](https://beta.keeweb.info), will be available in the next release
