### ISSUE TITLE
Keyboard navigation in dropdown list?

### ISSUE THREAD

**Issue by Rurik19** [keeweb/keeweb#333]
When I enter a user name there are list of suggested old names. It is wery good, but for use on of those, I must leave keyboard and use mouse. It would be great to navigate in the suggestion list with arrows (as in standard dropdown list)

**Comment by antelle** [comment]
Deployed to [beta.keeweb.info](https://beta.keeweb.info), will be available in the next release.

**Comment by Rurik19** [comment]
Great!  Thank you!
