### ISSUE TITLE
Building on Linux // Building only Web

### ISSUE THREAD

**Issue by CumpsD** [keeweb/keeweb#335]
I was trying to build Keeweb on an Ubuntu machine, which failed during `npm install` because of macos-alias failing to build.

Is there a way to build only the web-part of KeeWeb and not the Electron bits?

**Comment by antelle** [comment]
Hello!
Is build passing after it fails to install?
Which deps are failing? There's only one platform-specific dep (appdmg), and it's marked as optional.

**Comment by Rurik19** [comment]
**CumpsD **
No need to build only web-part, there is "gh-pages" branch of keeweb, who works absolutely the same way and consists only one index.html file.

**Comment by antelle** [comment]
I guess, @CumpsD wants to build from source and hack on it. But yes, if you want to get HTML, you can just download gh-pages and host it, or `docker install antelle/keeweb`

**Comment by antelle** [comment]
Just tried clean install on ubuntu vm. You can just ignore this message, go ahead and build with grunt, it should pass.

**Comment by antelle** [comment]
looks like everything is working. closing...

**Comment by CumpsD** [comment]
The problem is, it failed with an error code apparently, which caused the teamcity build I had setup to build it too also fail.

Ended up cloning gh-pages and manually editing in the minified version. Just wanted to use my own Google Drive API key.

**Comment by antelle** [comment]
There's no need to rebuild if you just want to use your api key.
You can set this key in json app config ([how?](https://github.com/keeweb/keeweb/wiki/Configuration#json-app-config)).

**Comment by CumpsD** [comment]
Thanks

**Comment by Hydro8** [comment]
Do you still have this gh-pages ? I don't achieve to use grunt on windows and I just want to self host webapp but I can't find gh-pages on the old github.

**Comment by antelle** [comment]
Sure: https://github.com/keeweb/keeweb/tree/gh-pages
