### ISSUE TITLE
Drag entries across files

### ISSUE THREAD

**Issue by antelle** [keeweb/keeweb#336]
There should be a possibility to drag entry into another file. Old entry in the source file should be moved to trash or deleted.

**Comment by timbru31** [comment]
I'd like to vote that when e.g. a modifier key is pressed while performing this action, it should make a copy instead. This is more like native Finder or Windows Explorer behavior.

**Comment by Coises** [comment]
I suggest that dragging to a different database is analogous to dragging to another drive in Windows Explorer. The default should be to copy (which should also work with `Ctrl` modifier); use `Shift` modifier to move. Between groups within a database, move should be the default (with redundant `Shift` modifier allowed) and `Ctrl` modifier should make a copy.

Complementing this, I'd suggest the **File** and **Group** fields in an entry should be drop-downs; **File** allowing copy to any other open database and **Group** allowing move to any other group within the current database or to the root of the database. It’s best if drag and drop isn’t the _only_ way to accomplish something—it can be an accessibility hurdle even when clicking remains practical.

**Comment by AlexHowser** [comment]
I would totally love to see that feature! :)

**Comment by isopterix** [comment]
Yes, pleeeeeese!!!
