### ISSUE TITLE
Dropbox sync succeeds but hangs

### ISSUE THREAD

**Issue by bbzg** [keeweb/keeweb#337]
* KeeWeb standalone app
* Sign in to a synced dropbox file
* Change / Add / Remove an entry
* Press save - green icon starts spinning, "sync is in progress", save button is greyed out

Save button is never enabled again, only close button is available. Database is properly saved, but need to press close and accept the warning dialog to save again.

LOG:
2016-09-02T06:59:00.174Z [storage-dropbox] Save /XXX.kdbx 24d2e93e50d
index.html:13 2016-09-02T06:59:00.174Z [dropbox] Call writeFile
index.html:13 2016-09-02T06:59:02.499Z [dropbox] Result writeFile 2325ms [null, t]
index.html:13 2016-09-02T06:59:02.501Z [storage-dropbox] Saved /Apps/YYY/XXX.kdbx 2327ms
index.html:13 2016-09-02T06:59:02.501Z [sync:XXX] Update rev in file info
index.html:13 2016-09-02T06:59:02.503Z [sync:XXX] Save to storage complete, update sync date
index.html:18 Uncaught TypeError: Cannot read property 'scheduleBackupFile' of undefined(anonymous function) @ index.html:18(anonymous function) @ index.html:18(anonymous function) @ index.html:14(anonymous function) @ index.html:10h.Util.Xhr.t.onReadyStateChange @ index.html:11(anonymous function) @ index.html:11

**Comment by bbzg** [comment]
KeeWeb version 1.3.0

**Comment by y0ast** [comment]
Same for Google Drive at the moment

**Comment by antelle** [comment]
same for all storage providers... will be fixed today

**Comment by antelle** [comment]
Fixed, please update
