### ISSUE TITLE
[Question] Where are encrypt/decrypt functions?

### ISSUE THREAD

**Issue by dulac** [keeweb/keeweb#339]
Please forgive the stupid question. I'm trying to understand the codebase to contribute.

I've been searching the source code but cannot find where the encrypt/decrypt of the database is occurring. Can you please point me to the specific source files for these functions? Thanks!

**Comment by antelle** [comment]
Hello! All db operations are performed in a separate library, kdbxweb: https://github.com/keeweb/kdbxweb
Specifically, db ebcryption is here: https://github.com/keeweb/kdbxweb/blob/master/lib/format/kdbx.js
I would like to warn you: I'm working on [Kdbx4](http://keepass.info/help/kb/kdbx_4.html) format right now, the entire library will be heavily refactored, including API. I'm removing asmCrypto, making async api with webCrypto only, and preparing to integrate Argon2 and ChaCha.
Tests: https://github.com/keeweb/kdbxweb/tree/master/test
