### ISSUE TITLE
Ctrl+Backspace does not work on input fields

### ISSUE THREAD

**Issue by LiraNuna** [keeweb/keeweb#341]
Ctrl+Space is used on Linux to delete a word. It is currently not possible to use this combo.

To reproduce:
- On a Linux desktop, open the app
- Open the demo db
- Input a word into the search box
- Hit Ctrl+Backspace

Expected result:
Word is erased

Current result:
Nothing happens

The example provided only uses the search bar but any text input field has this issue.

**Comment by antelle** [comment]
Deployed to [beta.keeweb.info](https://beta.keeweb.info), will be available in the next release
