### ISSUE TITLE
UX: Selecting the search field on KeeWeb focus can be problematic

### ISSUE THREAD

**Issue by Loilo** [keeweb/keeweb#343]
A while ago, I opened #304 for UX reasons.
Now with 1.3 installed I realize that solving this brought an even larger UX issue:
Returning to the app now correctly selects the content of the search field. That also means though that pressing the ⌘C shortcut copies the contents of the search field and not the password of the selected item.

I'd suggest to just ignore any attempts to copy search field content with the ⌘C shortcut and instead always copy the underlying item's password.

**Comment by antelle** [comment]
No, if the field is in focus and something is selected, we cannot copy anything except this field. Maybe we should remove focus from field when you return to the app. I'll think about it...

**Comment by antelle** [comment]
To sum up:
- we'll reset input focus on window blur (unfocus)
- ⌘C will work after returning to app
- we'll not copy anything else, when there's selection somewhere

**Comment by nopivnick** [comment]
> Maybe we should remove focus from search field when you return to the app. I'll think about it...

for what it's worth, I always appreciated this particular behavior in KeePass.

perhaps at some point you might consider bringing it back as a setting.
