### ISSUE TITLE
The application "KeeWeb.app" can't be opened

### ISSUE THREAD

**Issue by spyesx** [keeweb/keeweb#346]
Hello,

I just downloaded the last update 1.3.1 on Mac and I can't open it anymore. A message says `The application "KeeWeb.app" can't be opened.`.

[screenshot](https://www.dropbox.com/s/46mtsutrnoyipkq/Screenshot%202016-09-06%2007.22.37.png?dl=0)

I'm on OSX 10.11.6 if it helps.

**Comment by antelle** [comment]
#262
TL/DR: reboot

**Comment by spyesx** [comment]
Answer to myself and to other people who might face the problem.

The solution is here [262](https://github.com/keeweb/keeweb/issues/262#issuecomment-232121122). We all need to reboot.

**Comment by spyesx** [comment]
@antelle We posted at the same time :) Thx for your reactivity!
It might be useful to mention that on the download button of KeeWeb's website.
Great work though !

**Comment by antelle** [comment]
It's only valid if you upgrade from v1.1, so now it should happen almost never.
