### ISSUE TITLE
[Feature request] Customize Keyboard Shortcuts

### ISSUE THREAD

**Issue by p4gs** [keeweb/keeweb#348]
It'd be great if users could customize their keyboard shortcuts, especially global shortcuts (for when the app is in the background). I've run into a few issues now where e.g. the global auto-type shortcut overlaps with another global shortcut I have for a different app.

In the case of global auto-type, it interferes with the auto-typing operation.

**Comment by antelle** [comment]
Global shortcuts have to be customized, yes. In-app shortcuts will remain hard-coded.

**Comment by ConcurrentHashMap** [comment]
@antelle Please make this configurable. The shortcut for auto-type (Ctrl+Alt+T) is really hard to handle with one hand without getting a crick in the fingers ;-). I would like to make it same with the KeePass one's (Ctrl+Alt+A), that is easy to use, but it would be best to make this configurable to make the app intuitive and easy to use.

**Comment by lesu1** [comment]
Hey, any progress on this? :-) Almost 3 years passed.

**Comment by antelle** [comment]
It seems to be quite clear from github that nothing has been done, right? Feel free to contribute of course.

**Comment by antelle** [comment]
The bot was misconfigured, sorry for a wrong notification.

**Comment by antelle** [comment]
v1.11 will allow customizing global shortcuts:

<img width="1065" alt="image" src="https://user-images.githubusercontent.com/633557/64909543-f6ff8b80-d70d-11e9-8891-4afcef60f691.png">

It won't be possible to change internal KeeWeb shortcuts, this doesn't make sense.

**Comment by Dmitra** [comment]
that's great, cause I'm using "Alt+Shift+t" for new tab in browser, and having my passwords in browser history isn't good :)

thank you very much @antelle , I'm looking forward next release.

**Comment by noahbaxter** [comment]
Hi, how do I remove a global shortcut? Seems that ctrl-alt-t interferes with atom shortcuts. I can see that `copy OTP` and `open KeeWeb` are both unset, but how do I unset any of the others? Typing -, or del does not work.

**Comment by antelle** [comment]
@noahbaxter you cannot. However you can set it to something meaningless that you will never type.
