### ISSUE TITLE
The application "KeeWeb.app" can't be opened

### ISSUE THREAD

**Issue by retorquere** [keeweb/keeweb#350]
After installing the desktop version of 1.3.1 on OSX 10.11.6, I get the message `The application "KeeWeb.app" can't be opened` when I try to start KeeWeb. This is before I can open a database -- the application screen doesn't come up at all, so I also cannot open the devtools.

**Comment by antelle** [comment]
Are you updating from v1.1?
#262 (reboot)

**Comment by retorquere** [comment]
That was it, and apologies for not searching. I browsed through the open issues, but not the closed ones. The new release is really nice BTW -- KyPass Companion can pretty much close shop (as if they hadn't already)

**Comment by redbug26** [comment]
Not yet..
But thanks for the support :-)
