### ISSUE TITLE
Passphrase Generation

### ISSUE THREAD

**Issue by zQueal** [keeweb/keeweb#354]
A passphrase generator should be bundled with KeeWeb. Preferably one [such as this](https://oneshallpass.com/pp.html).

This allows users to generate easily rememberable and high entropy password/phrase credentials at the push of a button.

**Comment by antelle** [comment]
We already have pronounceable passwords generator. Here's a request to add more advanced generator with dictionaries: #210 
I think, it's pretty much the same, so let's close this as a duplicate
