### ISSUE TITLE
Portuguese Translation

### ISSUE THREAD

**Issue by caramelomartins** [keeweb/keeweb#355]
Hello,

First, thank you for such an awesome project.

I'm Portuguese and I'd like to contribute to this project in the only way I can as of this moment so I'd like to try and help with a Portuguese translations for Portugal.

I'm sorry by opening an issue just to ask for that but I couldn't find how to do it in https://keeweb.oneskyapp.com/.

If you'd like me to go ahead please help with adding Portuguese (Portugal) to the list of languages. :)

**Comment by antelle** [comment]
done

**Comment by caramelomartins** [comment]
The translation is now finished for community review. I think I was able to be fairly consistent with the translation but I'll try to use it as much as I can in Portuguese to understand what can be improved.

**Comment by antelle** [comment]
Thank you so much! 🎁 
Added, uploaded to beta.
