### ISSUE TITLE
Auto Type starts switching tabs in Chromium

### ISSUE THREAD

**Issue by ginkel** [keeweb/keeweb#357]
Thanks for taking the time to contribute!

Please, read https://github.com/keeweb/keeweb/wiki/FAQ before submitting a new issue and fill in the following (if applicable):

- what were your actions?

Selected an entry, switched to web browser (Chromium Version 53.0.2785.92 on Arch Linux) window, highlighted the username input, hit Alt+Shift+T for auto-typing. The auto-type sequence is configured as "{USERNAME}{TAB}{PASSWORD}{ENTER}".

- what was wrong?

Chromium reproducibly starts switching tabs instead of accepting the Auto Type input, which may end up on different tabs (being a security issue).

- app version

KeeWeb v1.3.1 (234333d, 2016-09-02)

- your user-agent (from Settings/Help section)

Environment: electron v1.3.3
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) KeeWeb/1.3.1 Chrome/52.0.2743.82 Electron/1.3.3 Safari/537.36

- does it happen on Demo or New database?

Also happens with real DB.

- if you are using a test db without your personal data, please attach it

n/a

- please, open dev tools in your browser and attach output log from Console tab 
    (if you are using desktop app, devtools can be opened from Settings/General/Advanced)

index.html:13 2016-09-09T16:30:45.866Z [auto-type] Auto type event null
index.html:13 2016-09-09T16:30:45.868Z [auto-type] Get window title
index.html:13 2016-09-09T16:30:45.882Z [launcher] spawn xdotool: 0, 14ms
Startseite Privat- und Geschäftskunden - Commerzbank - Chromium
index.html:13 2016-09-09T16:30:45.883Z [auto-type] Window title Startseite Privat- und Geschäftskunden - Commerzbank - Chromium undefined
index.html:13 2016-09-09T16:30:45.887Z [auto-type] Hide window
index.html:13 2016-09-09T16:30:45.890Z [auto-type] Start {USERNAME}{TAB}{PASSWORD}{ENTER}
index.html:13 2016-09-09T16:30:45.891Z [auto-type] Parsed [op:USERNAME,op:TAB,op:PASSWORD,op:ENTER]
index.html:13 2016-09-09T16:30:45.893Z [auto-type] Resolved [************,key:tab,[*,*,*,*,*,*,*,*],key:enter]
index.html:13 2016-09-09T16:30:46.139Z [launcher] spawn xdotool: 0, 245ms
index.html:13 2016-09-09T16:30:46.176Z [launcher] spawn xdotool: 0, 36ms
index.html:13 2016-09-09T16:30:46.199Z [launcher] spawn xdotool: 0, 23ms
index.html:13 2016-09-09T16:30:46.221Z [launcher] spawn xdotool: 0, 21ms
index.html:13 2016-09-09T16:30:46.319Z [launcher] spawn xdotool: 0, 97ms
index.html:13 2016-09-09T16:30:46.341Z [launcher] spawn xdotool: 0, 22ms
index.html:13 2016-09-09T16:30:46.362Z [launcher] spawn xdotool: 0, 20ms
index.html:13 2016-09-09T16:30:46.382Z [launcher] spawn xdotool: 0, 19ms
index.html:13 2016-09-09T16:30:46.403Z [launcher] spawn xdotool: 0, 21ms
index.html:13 2016-09-09T16:30:46.423Z [launcher] spawn xdotool: 0, 20ms
index.html:13 2016-09-09T16:30:46.424Z [auto-type] Complete 533ms

**Comment by antelle** [comment]
most probably, linux specific, or distro-specific, I'll check it on ubuntu vm

**Comment by ginkel** [comment]
It's as if the Ctrl key was pressed during the whole sequence (but physically isn't).

**Comment by antelle** [comment]
yes, but we call xdotool with clearmodifiers flag, somehow it's not working, I'll try to figure it out

**Comment by antelle** [comment]
I've added the fix (`keyup ctrl alt shift`). Could you please verify it by clicking `Try beta` button in settings?

**Comment by ValentinH** [comment]
I'll test it tomorrow on my work computer...

**Comment by ginkel** [comment]
"Try beta" just minimizes the window. The behavior afterwards regarding auto type is unchanged.

**Comment by antelle** [comment]
You mean the 'try beta' button itself? Or auto-type after you downloaded beta?

**Comment by ginkel** [comment]
I mean clicking the "Try beta" button in 1.3.1. I'm using the Arch Linux AUR package for KeeWeb, not sure if it has a functional beta version.

**Comment by antelle** [comment]
Most probably Beta button is not working in AUR distribution. Here's the full app archive with this patch: http://antelle.net/files/KeeWeb-1.3.1.linux.x64.zip
On both my Ubuntu boxes, 14 and 15 versions, it works.

**Comment by ginkel** [comment]
Excellent, Auto Type in the (beta-enabled) download you referenced works like a charm!

**Comment by nnjeremy** [comment]
I have try the beta version (thanks for your work !!!) but I still have the same issue : #362 
if I don't release the keys and wait something like 2 seconds then nothing is write in the input text (login+pwd)
if I release the keys "slowly" then I just have the end of the login (+ full password)
if I release "quickly" the keys then it's work correctly (but it's difficult)

**Comment by antelle** [comment]
@nnjeremy I managed to repeat it: it happens, when you hit 3 keys and hold T. Usefully people release the key itself (`T` in out case) very fast and keep modifiers down. I've just added keyup for T but it doesn't work I don't know why, needs further investigation...

**Comment by nnjeremy** [comment]
I have made a new test with the beta version and it works perfectly !!!

**Comment by ValentinH** [comment]
It works perfectly for me as well! Even when keeping T pressed. Well done! :+1:

**Comment by antelle** [comment]
deployed to production, please update
