### ISSUE TITLE
Doc update request: security of auto-update

### ISSUE THREAD

**Issue by fritzophrenic** [keeweb/keeweb#359]
I could not find this information in the wiki or homepage, so please document it somewhere (or point me to it if it's already there).

What security features are used in the auto-update? Specifically, does the auto-update download over an encrypted connection? Is the download signed and the signature verified before installing the update?

**Comment by antelle** [comment]
Yes, we should document this. Updates are:
- downloaded over HTTPS
- checked for signature before unarchiving ([source code](https://github.com/keeweb/keeweb/blob/master/app/scripts/comp/updater.js#L233))

**Comment by antelle** [comment]
added to faq, as it's rather frequent question
