### ISSUE TITLE
Installing .deb package fails on Ubuntu 16.04

### ISSUE THREAD

**Issue by florianletsch** [keeweb/keeweb#360]
I have downloaded the .deb package from https://keeweb.info/

I run the installation from the command line, via: `sudo dpkg -i KeeWeb-1.3.1.linux.x64.deb`

However, the installation fails, this is the log I am presented with:

```
(Reading database ... 428293 files and directories currently installed.)
Preparing to unpack KeeWeb-1.3.1.linux.x64.deb ...
Unpacking keeweb-desktop (1.3.1-1) over (1.3.1-1) ...
dpkg: dependency problems prevent configuration of keeweb-desktop:
 keeweb-desktop depends on libappindicator1; however:
  Package libappindicator1 is not installed.

dpkg: error processing package keeweb-desktop (--install):
 dependency problems - leaving unconfigured
Processing triggers for bamfdaemon (0.5.3~bzr0+16.04.20160701-0ubuntu1) ...
Rebuilding /usr/share/applications/bamf-2.index...
Processing triggers for gnome-menus (3.13.3-6ubuntu3.1) ...
Processing triggers for desktop-file-utils (0.22-1ubuntu5) ...
Processing triggers for mime-support (3.59ubuntu1) ...
Processing triggers for shared-mime-info (1.5-2ubuntu0.1) ...
Processing triggers for hicolor-icon-theme (0.15-0ubuntu1) ...
Errors were encountered while processing:
 keeweb-desktop
```

I am running this on a recent 64-bit version of Ubuntu 16.04.

Any ideas?

**Comment by florianletsch** [comment]
Weird. Apparently the installation went through anyway. At least it's installed on my system now. Sorry for the confusion.

**Comment by antelle** [comment]
Hm, shouldn't deb install dependencies automatically?

**Comment by sainaen** [comment]
> Apparently the installation went through anyway

@florianletsch You may still want to install `libappindicator1` manually to get a tray icon working.

@antelle 
No, `dpkg` is manager of Debian packages in the system, it doesn't know about remote repositories. But after installation with `dpkg -i` one can use `apt-get -f install` to download missing dependencies. Also, there is a `gdebi`.
