### ISSUE TITLE
Autotype shortcut error (ubuntu with xdotool)

### ISSUE THREAD

**Issue by nnjeremy** [keeweb/keeweb#362]
Hello,
I have try the autotype of keeweb and it's not working correctly on Ubuntu 16.04.

### - what were your actions?
I try to use autotype on chrome/firefox in a simple login form (2 input text and 1 button).

### - what was wrong?
the problem is the delay between the shortcut (shift+alt+T) and the fields completion.

_example with :_
login = username
password = 123456
autotype = {USERNAME}{TAB}{PASSWORD}{ENTER}

_case 1 :_
if I use the shortcut shift+alt+T and press the 3 keys during **1s** (delay is just an example)
then  input text username is **empty**, action {TAB} run correctly, input text password is **empty**, action {ENTER} run correctly.

_case 2 :_
if I use the shortcut shift+alt+T and press the 3 keys during **0.1s** (delay is just an example)
then  input text username is **partially completed** "rname", action {TAB} run correctly, input text password is **correctly completed**, action {ENTER} run correctly.

_case 3 :_
if I use the shortcut shift+alt+T and press the 3 keys during **0.01s** (delay is just an example)
then  input text username is **correctly completed** "username", action {TAB} run correctly, input text password is **correctly completed**, action {ENTER} run correctly.

I think that autotype start running the "script" when I press down shift+alt+T and if keys are still pushed (depressed ?)  then autotype can't complete input text correctly...
Maybe this problem can be solved by executing autotype when keys are released.

also note that :
- I have the same issue on firefox & chrome
- shift+alt+B work correctly
- shift+alt+C work correctly
- shift+alt+T work correctly when "no match found" and manually select the correct entry

PS : Sorry for my bad English

### - app version
KeeWeb v1.3.1 (234333d, 2016-09-02)
Environment: electron v1.3.3
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) KeeWeb/1.3.1 Chrome/52.0.2743.82 Electron/1.3.3 Safari/537.36

### - please, open dev tools in your browser and attach output log from Console tab 
[DEBUG] 2016-09-12T11:45:51.777Z [auto-type] Auto type event 
[DEBUG] 2016-09-12T11:45:51.782Z [auto-type] Get window title
[INFO ] 2016-09-12T11:45:51.820Z [launcher] spawn xdotool: 0, 37ms
Site - Google Chrome
[DEBUG] 2016-09-12T11:45:51.820Z [auto-type] Window title Site - Google Chrome 
[DEBUG] 2016-09-12T11:45:51.822Z [auto-type] Hide window
[DEBUG] 2016-09-12T11:45:51.825Z [auto-type] Start {USERNAME}{TAB}{PASSWORD}{ENTER}
[DEBUG] 2016-09-12T11:45:51.826Z [auto-type] Parsed [op:USERNAME,op:TAB,op:PASSWORD,op:ENTER]
[DEBUG] 2016-09-12T11:45:51.828Z [auto-type] Resolved [*******,key:tab,[*,*,*,*,*,*,*,*,*],key:enter]
[INFO ] 2016-09-12T11:45:51.937Z [launcher] spawn xdotool: 0, 107ms
[INFO ] 2016-09-12T11:45:51.980Z [launcher] spawn xdotool: 0, 43ms
[INFO ] 2016-09-12T11:45:52.007Z [launcher] spawn xdotool: 0, 27ms
[INFO ] 2016-09-12T11:45:52.042Z [launcher] spawn xdotool: 0, 34ms
[INFO ] 2016-09-12T11:45:52.065Z [launcher] spawn xdotool: 0, 23ms
[INFO ] 2016-09-12T11:45:52.098Z [launcher] spawn xdotool: 0, 32ms
[INFO ] 2016-09-12T11:45:52.124Z [launcher] spawn xdotool: 0, 26ms
[INFO ] 2016-09-12T11:45:52.148Z [launcher] spawn xdotool: 0, 23ms
[INFO ] 2016-09-12T11:45:52.170Z [launcher] spawn xdotool: 0, 22ms
[INFO ] 2016-09-12T11:45:52.193Z [launcher] spawn xdotool: 0, 23ms
[INFO ] 2016-09-12T11:45:52.216Z [launcher] spawn xdotool: 0, 22ms
[DEBUG] 2016-09-12T11:45:52.216Z [auto-type] Complete 391ms

**Comment by nnjeremy** [comment]
maybe link with #357

**Comment by antelle** [comment]
yes, it's the same..

**Comment by antelle** [comment]
Uploaded the fix to beta. If you verify it before releasing with Try Beta button, that would be great.
🎁
