### ISSUE TITLE
Problem with OneSky

### ISSUE THREAD

**Issue by Matthaiks** [keeweb/keeweb#364]
These strings cannot be translated ("Translation cannot be empty" error):
>  #22487959 #22487962 #22487971 #22487974 #22488304 #22488400 #22488407 #22488463 #22488581 #22488608 #22488617 #22488629 #22488691

**Comment by antelle** [comment]
Written to OneSky support... We cannot do anything with it, thanks for mentioning though, hope they will fix it.

**Comment by antelle** [comment]
You can just email me them, if the error persists in a day or two.

**Comment by Matthaiks** [comment]
OK. Thanks.

**Comment by antelle** [comment]
Should be ok now

**Comment by Matthaiks** [comment]
"New phrases have been added into the project KeeWeb/KeeWeb App", but:

![57848964945](https://user-images.githubusercontent.com/3577122/106817710-8b59ed80-6677-11eb-84e6-e45b6b40cf5a.png)

**Comment by antelle** [comment]
Hi! I think they should appear soon, probably there's a glitch in OneSky. I can try uploading them once again tomorrow, maybe it will help.
