### ISSUE TITLE
WebDav on Desktop app not working

### ISSUE THREAD

**Issue by apollo13** [keeweb/keeweb#365]
Using the latest linux version for keeweb, I get:
![selection_495](https://cloud.githubusercontent.com/assets/81547/18451019/aa9be7e0-7935-11e6-91ba-f03eb8e2ad69.png)
when I try to connect to my password file via WebDav. The page uses a custom CA, which I added to my browser, can I do something similar for the electron build? Or why does the app consider the resource as insecure.

**Comment by antelle** [comment]
Most probably, your browser doesn't allow CORS requests to this resource. Can you open a simple HTML page from this domain without a security warning?

**Comment by antelle** [comment]
Oh, you mean electron app, I missed it, so it's working in browser but doesn't work in Electron app, right?

**Comment by antelle** [comment]
Just found this: `electron --ignore-certificate-errors 'https://self-signed.badssl.com/'`.
Works for me, most probably will also work in KeeWeb, so you can launch it with this key.
But I recommend getting a valid cert, e.g. on letsencrypt, this would be more reliable.

**Comment by apollo13** [comment]
Indeed, that is it. letsencrypt is sadly not an option, since that homepage is inside a corporate lan and has no public domain names I could request the cert for… I wonder if I can tell electron about my CA.

**Comment by antelle** [comment]
It accepts almost all keys which chrome does. So, you can google for it. I'm not sure whether this possible. If it's possible in Electron, KeeWeb automatically support it also. If not, we'll not be able to add it as well.
Maybe there's a way to add it system-wide? E.g. on Windows, you can add trusted CA. Not sure if it's possible under Linux.

**Comment by apollo13** [comment]
Keeweb could hook into http://electron.atom.io/docs/api/app/#event-certificate-error  and then ask the user if he wants to trust the cert.

**Comment by antelle** [comment]
Hm, looks good, thanks. Let's implement it. But it's something low-priority... not sure about time frame.

**Comment by antelle** [comment]
Maybe just add an app setting, instead of a dialog? This would be both configurable and easy to implement.

**Comment by apollo13** [comment]
Ha, your chrome tip saved me:
```
certutil -d sql:$HOME/.pki/nssdb -A -t TC -n "my_domain.lan" -i ~/ca.crt
```
added the cert to the proper database!

**Comment by antelle** [comment]
So, after this, KeeWeb accepts custom cert, right? Then we can add this to wiki docs and leave as is, right? Is the issue solved for you?

**Comment by apollo13** [comment]
Jupp, that is enough for me. I just had no idea how and what electron uses of chrome. Added your custom certs to this db is certainly the better/saner way than trying to handle cert errors.

**Comment by antelle** [comment]
Yes, I think it's the most appropriate way of adding a custom cert, I'm adding it

**Comment by antelle** [comment]
Done, added the tip: https://github.com/keeweb/keeweb/wiki/WebDAV-Config#custom-certificates
