### ISSUE TITLE
Multi-user support

### ISSUE THREAD

**Issue by MikeKulls2** [keeweb/keeweb#367]
Users can overwrite each others changes.

Steps to reproduce
1) Open the same file in 2 web pages
2) Add a different entry in each
3) Save both
4) Login again. Notice that the entry added by the first user is missing.

KeeWeb v1.3.2 (fb3b741, 2016-09-13)
User-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:48.0) Gecko/20100101 Firefox/48.0
New database

**Comment by antelle** [comment]
Hello,
We support multiple users users, the changes should be merged.
But the case is not clear for me:
- to which storage did you save the database? e.g. Dropbox, Google drive, ...
- were there sync errors? let's see the logs.

Please note that if you means '2 web pages' as two tabs in one browser session, you can close this now, this is unreal case, not two users.

**Comment by MikeKulls2** [comment]
I had a file local to my windows machine and clicked the add button. I believe this copies the file to the linux server (redhat 7) that is running the web app. I created an entry is one tab and then created an entry in a second tab. I clicked the button on the bottom right to log me out on both tabs. I am under the impression this is what causes it to save. When I logged back in only the second entry that I added was there. I am not at the office so can't check now but will try to get logs tomorrow.

**Comment by MikeKulls2** [comment]
I should add I don't believe it is 2 new files. The steps I used were:
1) Create file on windows machine using KeePass windows version
2) Open KeeWeb
3) Click add button and add my file to KeeWeb, played around with it a bit, logged out and in a few times
4) Open a new tab
5) Click on my file which is shown in the web browser
6) Enter password
7) Add new entry in both tabs
8) Log out of KeeWeb and back in again
9) Can only see second entry

**Comment by antelle** [comment]
> I believe this copies the file to the linux server (redhat 7) that is running the web app.

No. It stores this file only in app cache, we don't work with server, unless you open the file from WebDAV.
> both tabs

The app doesn't work properly in two tabs, nothing is guaranteed. Maybe we'll add an error and don't allow to start the app in two tab in future at all.

**Comment by antelle** [comment]
Added a check for several tabs, deployed to beta. Now second tab will display an error, so it will be clear that we don't support it.

**Comment by KaKi87** [comment]
Why not making support for multiple accounts ?
Thanks.

**Comment by antelle** [comment]
@KaKi87 it does support multiple accounts, as I mentioned in the comment above, the changes will be merged if both users save the same file.

**Comment by BoKKeR** [comment]
In fear of bumping this thread, from what I understand from this link https://keepass.info/help/base/multiuser.html keepass does not support multiple users with multiple permissions. Which is what people expect when talking about multi-user. The multi-user solution in keepass is only meant for multiple sources editing the same file and auto merging conflicts. 

I think a real multi user (permissions, multiple keys, lastpass like) solution is not possible with keepass right now and is out scope for keeweb

**Comment by antelle** [comment]
@BoKKeR auto merging conflicts is exactly what this issue is about.  
Multi-user DB possibilities are discussed in #464 and most likely it will remain out of scope, you're right.
