### ISSUE TITLE
Exporting Dropbox file to disk doesn't work

### ISSUE THREAD

**Issue by hameerabbasi** [keeweb/keeweb#368]
Hello. Opening a file from Dropbox and exporting to disk doesn't work on OS X and Linux.

### What were your actions?
1. Open any file from Dropbox. (May have issues with other providers too)
2. Export to disk.

### What was wrong?
A 1-byte file was exported instead of the full file.

### App version
[This one](https://github.com/keeweb/keeweb/releases/tag/v1.3.2) for Linux, some old one for OS X, can't remember.

### Your user-agent (from Settings/Help section)
Does it matter if I'm using the Desktop App? I guess not.

**Comment by antelle** [comment]
Thanks, fixed it, will be released with other bugfixes in v1.3.3
