### ISSUE TITLE
Project does not have a Donate button

### ISSUE THREAD

**Issue by MichalKarnicki** [keeweb/keeweb#370]
KeeWeb is too good not to have a Donate button.

To me, KeeWeb is a natural successor of KeePassX, which I have been using for so many years now. I'm filing this bug so I get notified when I can buy antelle a couple beers.

I love it and would like to show my appreciation 👍, I believe there will be others who will want the same. I guess PayPal would be convenient for many, but any way is fine really.

**Comment by antelle** [comment]
next version will have it, thanks

**Comment by MichalKarnicki** [comment]
Thank you. Donated 👍

**Comment by antelle** [comment]
Thank you!
