### ISSUE TITLE
Generate password window not hidden on timeout

### ISSUE THREAD

**Issue by koterpillar** [keeweb/keeweb#372]
While the main KeeWeb window times out to a password prompt after some time, the password generation one doesn't and stays on top of it.

Steps to reproduce:
- Create a new entry
- Click on the "generate password" icon
- Wait until the window times out

Expected result:
- The unlock database screen is visible

Actual result:
- The "generate password" window is visible on top of the "unlock database" screen

KeeWeb version: 1.3.2
OS: Arch Linux
Window manager: XMonad

**Comment by antelle** [comment]
Deployed to [beta.keeweb.info](https://beta.keeweb.info), will be available in the next release
