### ISSUE TITLE
config.json

### ISSUE THREAD

**Issue by zpcgnlur** [keeweb/keeweb#376]
Hi,

The config.json is bugged. It auto-loads from kw-config. What the problem is, it's that even if i set webdav, gdrive, dropbox or one drive to false, they still appear in the more menu. The other settings are loaded like theme to sd or canOpenDemo to false but this.

Also please describe better this section:

  "files": [{
    "storage": "webdav",
    "name": "",
    "path": "db",
    "options": { "user": "", "password": "" }
  }]

i put the path in path but it doesn't auto-poplulate webdav with the value, so examples sake, if i have the db file in the same dir as index.html called db it doesn't load but if i manually type db in the url field it loads the db.

The ultimate goal would be to just load the url with everything predefined and i just add the master password or the master master and key file, is this possible as well as the issues above?

If not would it be possible to use the config to remove all options shown (not even more) and just have, in this case, WebDav with the fields either empty or prefilled?

KeeWeb v1.3.2 (fb3b741, 2016-09-13)
Environment: web
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:48.0) Gecko/20100101 Firefox/48.0

**Comment by antelle** [comment]
Hello,
> they still appear in the more menu

Thanks, it was a bug, fixed it and deployed to beta.
I didn't understood about webdav, sorry. Let's try to repeat it by steps:
1. add a config.json to your server
2. load the app with this config, e.g. by adding ?config=config.json to url
3. the file is shown in the ui, you just have to enter the password
