### ISSUE TITLE
Network error using webdav since version 1.32

### ISSUE THREAD

**Issue by planet77** [keeweb/keeweb#378]
Hello,
I'm using KeeWeb version 1.24 with Webdav and it works without problems. After updating to version 1.32 i get the Message "Error: network error" when trying to open my key file. The same with version 1.33. Switching back to version 1.24 and it works like a charm. Could the fix #344: prevent caching WebDAV requests from 1.32 be the problem?
Thanks for the great Web App.

**Comment by antelle** [comment]
Most probably, cors error, please check what's in network panel, because we are adding a new header now

**Comment by planet77** [comment]
Sorry, but do you mean the network panel like the one from Firebug? In this Panel it looks like HEAD key.kdbx get no response compared to 1.24 were HEAD get 200 OK status. Only Options get 200 OK response.

**Comment by antelle** [comment]
Yes, I mean network panel, is there anything in it? Also, maybe there are any console errors?

**Comment by planet77** [comment]
The following console error is shown - but it's in german - hope it helps anyway:
Quellübergreifende (Cross-Origin) Anfrage blockiert: Die Gleiche-Quelle-Regel verbietet das Lesen der externen Ressource auf https://domain.....com/...../......./key.kdbx. (Grund: fehlendes Token 'cache-control' in CORS-Kopfzeile 'Access-Control-Allow-Headers' aus dem CORS-Preflight-Kanal).
2016-09-21T14:19:07.961Z [storage-webdav] Stat error https://domain....com/...../.../key.kdbx 145ms

**Comment by antelle** [comment]
Yes, that's what I said before: we added a new cors header, so to use it, you must add it to your server allowed headers, here's an example (note Cache-Control here):
`add_header 'Access-Control-Allow-Headers' 'Authorization,DNT,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,X-Accept-Charset,X-Accept,origin,accept,if-match,destination, overwrite';`
