### ISSUE TITLE
[Bug] Search doesn't recognize entries

### ISSUE THREAD

**Issue by FilipJaksic** [keeweb/keeweb#380]
Hello,
it's me again, the guy with the all-fields-protected database.

I am testing the new 1.3.3 release and noticed that the search feature doesn't work -- it doesn't recognize any entry for my db. But it does work in the demo.

Maybe something to do with the fact that in my db all fields are protected?

User agent:
KeeWeb v1.3.3 (52701af, 2016-09-20)
Environment: electron v1.3.3
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_3) AppleWebKit/537.36 (KHTML, like Gecko) KeeWeb/1.3.3 Chrome/52.0.2743.82 Electron/1.3.3 Safari/537.36

**Comment by antelle** [comment]
Hm, it's working for me. Have you checked 'Protected values' option in advanced search?

**Comment by FilipJaksic** [comment]
Oh, didn't see that, sorry. It works!
