### ISSUE TITLE
Incorrect Translation - Portuguese

### ISSUE THREAD

**Issue by caramelomartins** [keeweb/keeweb#381]
Hello,

I have found a couple of incorrect translations of Portuguese in the most recent release. Should I fix them directly in OneSky?

Thanks!

**Comment by antelle** [comment]
Yes, sure. Translation contributions are accepted only from OneSky: after you update necessary strings, I'll download json and next release will have updated strings.

**Comment by caramelomartins** [comment]
Thanks @antelle! :+1:
