### ISSUE TITLE
KeepassX: "Impossible to open the database. Invalid bool value"

### ISSUE THREAD

**Issue by filippogasbarro** [keeweb/keeweb#385]
I tried to create a new database file kdbx in keeweb with the older version 0.3.2 and now you cannot longer open this file with the ultimate version of keepassx (fortunately it was a test database). The error message is: "Impossible to open the database. Invalid bool value".
I send to you the kdbx file for see where and what is the problem (the password of the DB is: "a")

Thank you

[DB password.kdbx.zip](https://github.com/keeweb/keeweb/files/491784/DB.password.kdbx.zip)

**Comment by antelle** [comment]
Hello, what keeweb version was it?

**Comment by filippogasbarro** [comment]
The previous version: 0.3.2

Filippo Gasbarro

2016-09-25 19:54 GMT+02:00 antelle <notifications@github.com>:

**Comment by antelle** [comment]
You mean 1.3.2?

**Comment by filippogasbarro** [comment]
Yes sorry, 1.3.2

**Comment by antelle** [comment]
It, looks like, KeePassX doesn't understand null in AutoType/Enabled. Maybe we should just omit this tag in case when auto-type is not enabled.

**Comment by Knah-Tsaeb** [comment]
AutoType is enabled in my all entries. How I can fix it manually ?
Thanks

**Comment by antelle** [comment]
Deployed to [beta.keeweb.info](https://beta.keeweb.info), will be available in the next release
