### ISSUE TITLE
Closes, instead of minimize to the tray

### ISSUE THREAD

**Issue by repsac-by** [keeweb/keeweb#389]
- what were your actions?
  - [x] Minimize app instead of closing
  - [ ] Make changes in database, without save.
  - [ ] Click close.
- what was wrong?
  - Closes, instead of minimize to the tray
- app version
  - KeeWeb v1.3.3 (undefined, 2016-09-26)
    Environment: electron v1.4.1
    User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) KeeWeb/1.3.3 Chrome/53.0.2785.113 Electron/1.4.1 Safari/537.36

**Comment by antelle** [comment]
Which distro are you running? It's working for me on ubuntu

**Comment by repsac-by** [comment]
Arch Linux

**Comment by antelle** [comment]
Is Tray module working for you in electron api demos app? 
http://electron.atom.io/#get-started

**Comment by repsac-by** [comment]
Прошу меня простить, тяжело с английским.
С лотком всё хорошо, он работает и сворачивается. 

Проблема возникает только, если пытаться закрыть и предварительно не сохранить базу, когда были внесены изменения. 

Если же перед сворачиванием нажать CTRL+S, то продолжает сворачиваться.
