### ISSUE TITLE
Selft hosting on wamp and webdav

### ISSUE THREAD

**Issue by Hydro8** [keeweb/keeweb#394]
Hi,

I download  gh-page branch and put the file on my wamp server (3.0.4).
I have a webdav service to expose my kdbx file so when I try to open this file from my KeeWeb, I got cross domain error.

So I add lines from the wifi to httpd.conf but it doesn't change a thing. I also try to put in on .htaccess but still nothing. I active header use on wamp modules.

Is someone self hosting Keeweb with wamp ?

The crossdomain error come from KeeWeb server or Webdav server ?

Thank

**Comment by antelle** [comment]
What is wamp, I know only Windows-Apache-Mysql-Php?
> The crossdomain error come from KeeWeb server or Webdav server?

I didn't understand your question, sorry. KeeWeb tries to download a file from webdav server, if there's a crossdomain error, it will fail. This means, you have to tune your webdav server.

**Comment by Hydro8** [comment]
I manage to have it work by moving my webdav from synology web station to wamp :)

Thank
