### ISSUE TITLE
URL recognition does not work on Linux

### ISSUE THREAD

**Issue by ghost** [keeweb/keeweb#396]
- what were your actions: Click in Keeweb on link and then try to autotype
- what was wrong: URL is not recognized
- app version: KeeWeb v1.3.3 (52701af, 2016-09-20)
- your user-agent: Mozilla/5.0 (X11; Linux x86_64)

> 2016-10-01T10:15:25.525Z [auto-type] Auto type event null
> 2016-10-01T10:15:25.527Z [auto-type] Get window title
> 2016-10-01T10:15:25.543Z [launcher] spawn xdotool: 0, 15ms
> Login | ProtonMail - Mozilla Firefox
> 2016-10-01T10:15:25.543Z [auto-type] Window title Login | ProtonMail - Mozilla Firefox undefined
> 2016-10-01T10:15:25.552Z [auto-type] Hide window
> 2016-10-01T10:15:25.554Z [auto-type] Start {USERNAME}{TAB}{PASSWORD}{ENTER}
> 2016-10-01T10:15:25.555Z [auto-type] Parsed [op:USERNAME,op:TAB,op:PASSWORD,op:ENTER]
> 2016-10-01T10:15:25.555Z [auto-type] Resolved [***************************_,key:tab,[_,_,_,_,_,_,_,_,_,_,_,*],key:enter]
> 2016-10-01T10:15:26.003Z [launcher] spawn xdotool: 0, 447ms
> 2016-10-01T10:15:26.089Z [launcher] spawn xdotool: 0, 86ms
> 2016-10-01T10:15:26.164Z [launcher] spawn xdotool: 0, 74ms
> 2016-10-01T10:15:26.237Z [launcher] spawn xdotool: 0, 72ms
> 2016-10-01T10:15:26.310Z [launcher] spawn xdotool: 0, 72ms
> 2016-10-01T10:15:26.383Z [launcher] spawn xdotool: 0, 72ms
> 2016-10-01T10:15:26.456Z [launcher] spawn xdotool: 0, 72ms
> 2016-10-01T10:15:26.529Z [launcher] spawn xdotool: 0, 73ms
> 2016-10-01T10:15:26.603Z [launcher] spawn xdotool: 0, 73ms
> 2016-10-01T10:15:26.678Z [launcher] spawn xdotool: 0, 74ms
> 2016-10-01T10:15:26.751Z [launcher] spawn xdotool: 0, 72ms
> 2016-10-01T10:15:26.824Z [launcher] spawn xdotool: 0, 72ms
> 2016-10-01T10:15:26.898Z [launcher] spawn xdotool: 0, 74ms
> 2016-10-01T10:15:26.933Z [launcher] spawn xdotool: 0, 34ms
> 2016-10-01T10:15:26.934Z [auto-type] Complete 1380ms
> 2016-10-01T10:15:45.483Z [auto-type] Auto type event null
> 2016-10-01T10:15:45.485Z [auto-type] Get window title
> 2016-10-01T10:15:45.496Z [launcher] spawn xdotool: 0, 11ms
> Take Todoist with you. - Mozilla Firefox
> 2016-10-01T10:15:45.496Z [auto-type] Window title Take Todoist with you. - Mozilla Firefox undefined
> 2016-10-01T10:15:45.501Z [auto-type] Hide window
> 2016-10-01T10:15:45.502Z [auto-type] Start {USERNAME}{TAB}{PASSWORD}{ENTER}
> 2016-10-01T10:15:45.503Z [auto-type] Parsed [op:USERNAME,op:TAB,op:PASSWORD,op:ENTER]
> 2016-10-01T10:15:45.503Z [auto-type] Resolved [***************************_,key:tab,[_,_,_,_,_,_,_,*],key:enter]
> 2016-10-01T10:15:45.953Z [launcher] spawn xdotool: 0, 449ms
> 2016-10-01T10:15:46.040Z [launcher] spawn xdotool: 0, 87ms
> 2016-10-01T10:15:46.114Z [launcher] spawn xdotool: 0, 73ms
> 2016-10-01T10:15:46.187Z [launcher] spawn xdotool: 0, 73ms
> 2016-10-01T10:15:46.261Z [launcher] spawn xdotool: 0, 73ms
> 2016-10-01T10:15:46.335Z [launcher] spawn xdotool: 0, 73ms
> 2016-10-01T10:15:46.408Z [launcher] spawn xdotool: 0, 72ms
> 2016-10-01T10:15:46.481Z [launcher] spawn xdotool: 0, 73ms
> 2016-10-01T10:15:46.555Z [launcher] spawn xdotool: 0, 74ms
> 2016-10-01T10:15:46.578Z [launcher] spawn xdotool: 0, 22ms
> 2016-10-01T10:15:46.579Z [auto-type] Complete 1076ms

**Comment by antelle** [comment]
Known issue. If you know a way to get URL, please feel free to contribute.

**Comment by KevinSeroux** [comment]
To help the auto-type you can use a web browser addon to add the URL in the title. For Firefox, there are [Add URL to Window Title](https://addons.mozilla.org/en-US/firefox/addon/add-url-to-window-title/) or [KeePass Helper](https://addons.mozilla.org/en-US/firefox/addon/keepass-helper/).

**Comment by antelle** [comment]
Now this should work in Firefox and Chromium.
