### ISSUE TITLE
KeeWeb not displaying correctly

### ISSUE THREAD

**Issue by snakyjake1** [keeweb/keeweb#402]
KeeWeb not displaying correctly:

![keeweb](https://cloud.githubusercontent.com/assets/8312560/19216962/a4d34aa0-8d86-11e6-8ff3-7bfb990a3d8b.jpg)

Ubuntu 16.04.1 hosted in VirtualBox
keeweb v 1.3.3

**Comment by antelle** [comment]
Please add logs.

**Comment by antelle** [comment]
Oh, you mean desktop app.
Just tries this version, it's working for me. Which KeeWeb install package did you use? deb-x64?
![vm](https://cloud.githubusercontent.com/assets/633557/19218422/3c3b4ad4-8e02-11e6-9e68-ab01e74d4849.png)

**Comment by snakyjake1** [comment]
I finally got it to work.  I think it is now working because it had something to do with increasing either the display video memory from 16mb to 32mb or disabling 3D acceleration in VirtualBox.
