### ISSUE TITLE
[Suggestion] Add new entry to selected group

### ISSUE THREAD

**Issue by mikerockett** [keeweb/keeweb#403]
It can be quite frustrating when I add a new entry whilst a group is selected and the entry is saved to the root of the keychain. I then have to go back to the root and drag the entry to the applicable group.

Apart from this, I'm _loving_ KeeWeb - it's so much better than KeePass. 👍 

```
KeeWeb v1.3.3 (52701af, 2016-09-20)
Environment: electron v1.3.3
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) KeeWeb/1.3.3 Chrome/52.0.2743.82 Electron/1.3.3 Safari/537.36
```

**Comment by antelle** [comment]
Hmm, for me, the entry is saved to the selected group. How do you add it?
Here's a video:
https://monosnap.com/file/6cSy58tau9n7Dw6vDo0kl9uT1bmyZh

**Comment by mikerockett** [comment]
I restarted the app, and it appears to be working now. As a result, I'm not able to help with any debugging of sorts.

Additionally, at some point I could not paste into the password field. I was migrating data from one keychain to another and it just wouldn't let me do it for one entry. So I deleted the new entry, re-created it, and paste worked. Again, unable to debug.

If these kinds of things happen again, what information do you think I'd be able to gather from the inspector?

**Comment by antelle** [comment]
Okay, that's good.
Basically, what I need to fix the issue, is a way to reproduce in on my machine. So, I need detailed steps to reproduce, if they are not obvious (e.g. 1. open the db, 2. click with mouse on group, 3. click it again. ...). You can also make a video, like I posted above. If this happens on Demo or New databases, it would be easier to debug. If it happens only on your database, I may ask you for more info, if I have any guess about the reason.

**Comment by mikerockett** [comment]
Okay thanks - I'll be sure to provide more information if it happens again. 👍
