### ISSUE TITLE
The right click menù don't appear in Ubuntu

### ISSUE THREAD

**Issue by filippogasbarro** [keeweb/keeweb#409]
If you go in all text field and/or above every written on Ubuntu 16.04 Keeweb app, the right contextual menu is blocked, and so not appear at the right click (for do for example: copy, cut, paste etc.)
- app version: 1.3.3
- user-agent:
  KeeWeb v1.3.3 (52701af, 2016-09-20)
  Environment: electron v1.3.3
  User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) KeeWeb/1.3.3 Chrome/52.0.2743.82 Electron/1.3.3 Safari/537.36

**Comment by antelle** [comment]
Valid for other desktop OS but ok on web.
