### ISSUE TITLE
Feature request: Automatically use group icon for new entries

### ISSUE THREAD

**Issue by FlxVctr** [keeweb/keeweb#411]
Like in KeepassX :)

Awesome UI. Thanks!

**Comment by antelle** [comment]
Group icon should not be used for entries. But there are cases where it could be useful, e.g. folder with credit cards has credit cards inside.
So, automatically this shouldn't happen: it's better to add a setting for this.

**Comment by FlxVctr** [comment]
Yep, that's what I meant. Sorry for being unclear. KeepassX has this setting.
