### ISSUE TITLE
Clipboard is not cleared if ctrl+c is used to copy the password

### ISSUE THREAD

**Issue by daker** [keeweb/keeweb#412]
- what were your actions?
ctrl+c a password
- what was wrong?
clipboard is not cleared after 15sec as set on the app
- app version
KeeWeb v1.3.3 (52701af, 2016-09-20)
- your user-agent (from Settings/Help section)
User-Agent: Mozilla/5.0 (X11; Linux i686) AppleWebKit/537.36 (KHTML, like Gecko) KeeWeb/1.3.3 Chrome/52.0.2743.82 Electron/1.3.3 Safari/537.36
- does it happen on Demo or New database?
New database

**Comment by antelle** [comment]
Hello,
What's your OS? Just tested, it's cleared for me on os x.

**Comment by daker** [comment]
Ubuntu 14.04

**Comment by antelle** [comment]
It works for me on Ubuntu 16.
Don't know how to reproduce/fix.

**Comment by daker** [comment]
Maybe if you can add some debugging in the console that will help debugging ?

**Comment by antelle** [comment]
btw, which message is displayed when you copy the password (I mean the tooltip): 'copied' or 'copied for X seconds'?

**Comment by daker** [comment]
Nothing is displayed since i am selecting the password with ctrl+a then ctrl+c, but if i use "Copy password" i get the right behavior "Copied for X seconds" is displayed

**Comment by antelle** [comment]
Oh, if you copy this way, it won't be cleared, this is by design. And if you copy password, does it get erased in X seconds?

**Comment by daker** [comment]
Yes i get the right behavior "Copied for X seconds" and the clipboard is cleared after X seconds, closing the issue since then.
