### ISSUE TITLE
Preselected group is ignored, if more than one database are open

### ISSUE THREAD

**Issue by curious-jim** [keeweb/keeweb#413]
I use multiple Databases at the same time, and found this issue

for example, I have structure like:

```
db1 root
- Project 1
- Project 2
db2 root
- Archive
etc..
```

if I open only one db, when I can preselect the Group and create new entry, it will be added to selected group,

but when I have more than one db, preselected group is ignored, and entry will be added to the root group

**Comment by antelle** [comment]
Deployed to [beta.keeweb.info](https://beta.keeweb.info), will be available in the next release
