### ISSUE TITLE
Can't open file from Drive

### ISSUE THREAD

**Issue by gillchristian** [keeweb/keeweb#414]
Hello, I'm using the 1.3.3 desktop dersion on Ubuntu 16.04 and I can't access a file from Drive that was generated with the online app. It says the password is wrong, but it does work on the web version.

KeeWeb v1.3.3 (52701af, 2016-09-20)
Environment: web
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.92 Safari/537.36

**UPDATE**: I tried to open it from other web client (my phone), and it does not work either.

**Comment by antelle** [comment]
You mean Google Drive?
Please attach logs.

**Comment by gillchristian** [comment]
Yes I mean Google Drive.

Sorry for the question, but how can I get the logs, are they in a file or on the console?

**Comment by antelle** [comment]
Yes, they are in browser dev console.

**Comment by antelle** [comment]
Try to delete the file from keeweb and link again. Does it help?

**Comment by antelle** [comment]
Please feel free to reopen with more info.
