### ISSUE TITLE
Updates through WebDAV storage are not shown on different connections

### ISSUE THREAD

**Issue by tanji** [keeweb/keeweb#415]
If I use WebDAV as a storage method, create some entries in keeweb and sync up the file, they don't show up instantly when logging in to keeweb on another computer. Closing the tab and reconnecting doesn't change anything (self-hosted keeweb, Firefox and Chrome on Linux). Updates are only shown after, i suspect, some kind of cache expires.

**Comment by antelle** [comment]
Most probably caching issue. Please attach logs from both clients.

**Comment by tanji** [comment]
Where do I find the logs?

**Comment by antelle** [comment]
in browser dev console, or by clicking a button in app settings, if you're using a desktop app

**Comment by antelle** [comment]
> Stat error

Are there any errors in Network panel?

**Comment by tanji** [comment]
OK, so the issue was the following:
KeeWeb now sends a cache-control header to the webdav server, and this wasn't the case previously, so I had to add Cache-Control to Access-Control-Allow-Headers. This fixed the problem. Thanks for your help!

**Comment by tanji** [comment]
If that helps anyone here are the options I've used in Apache:

```                Header always set Access-Control-Allow-Origin "*"
                Header always set Access-Control-Allow-Headers "x-requested-with, Cache-Control, Content-Type, origin, destination, overwrite, authorization, accept, client-security-token"
                Header always set Access-Control-Allow-Methods "POST, GET, OPTIONS, DELETE, PUT, MOVE"
```
