### ISSUE TITLE
Global auto-type ignores sort rank of entries

### ISSUE THREAD

**Issue by macdanger** [keeweb/keeweb#417]
first of all forgive me if I do this wrong, this is my very first post/contribution on github :-)
- what were your actions?
  configure several keepass entries for the same domain. Use some entries pointing to a sub-path of the website you want to auto-type into. Example:
  https://github.com user:hans
  https://github.com/login user:peter

got to https://github.com with your web browser and call the global auto-type shortcut

You will be presented with the two entries to chose from.
- what was wrong?
  The sort order of these entries is most likely wrong. There will be a ranking of all found entries in auto-type-filter.js but it is not taken into account.

I already found the reason: It seems that the found entries were sorted and filtered and then given as an argument to new EntryCollection(). It seems that the EntryCollection in turn will re-sort the collection again. This has the additional negative effect that the collection is sorted twice and in this case destroyed the sort order by rank.

I fixed it by adding the option {sort:false} in auto-type-filter.js:  
entries = new EntryCollection(entries
            .map(e => [e, this.getEntryRank(e)])
            .filter(e => e[1])
            .sort((x, y) => x[1] === y[1] ? x[0].title.localeCompare(y[0].title) : y[1] - x[1])
            .map(p => p[0]), {sort:false}); 
- app version
  KeeWeb v1.3.3 (undefined, 2016-10-19)
  Environment: electron v1.3.3
- your user-agent (from Settings/Help section)
  User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_4) AppleWebKit/537.36 (KHTML, like Gecko) KeeWeb/1.3.3 Chrome/52.0.2743.82 Electron/1.3.3 Safari/537.36
- does it happen on Demo or New database?
  private database

**Comment by antelle** [comment]
this is fixed now
