### ISSUE TITLE
[Feature request] Global add new entry shortcut with window info

### ISSUE THREAD

**Issue by macdanger** [keeweb/keeweb#418]
I read some comments about supporting KeePassHTTP. That would be great but if that is not planned anymore there might be a short term solution and a more "general" approach:

What about adding a global shortcut (like for global auto-type) to add a new entry to the keepass db. You would be e.g. in the browser which has some input fields I already may have filled with user and password, press the global add new entry shortcut and I will be displayd with the add a new entry screen.
Ideally the fields title, username, password, and URL are pre-populated with the information from the browser.

This would mostly make sense for saving browser passwords but may also be interesting for saving passwords for other applications. At least the window title will always be available. I don't know about e.g. browser input fields.

**Comment by antelle** [comment]
This should be done by browser plugins, not by keeweb itself.
It's not possible, to get browser fields from the app. Window title is also not always available.
