### ISSUE TITLE
[EXPIRED] Support of alternative encryption algorithms (e.g. Twofish)?

### ISSUE THREAD

**Issue by sergeevabc** [keeweb/keeweb#420]
Dear Keeweb, could you be so kind to explain how to open databases encrypted with Twofish? Keepass allows it [via plugin](http://keepass.info/plugins.html#twofishcipher) and KeepassDroid has [internal support](https://keepassdroid.uservoice.com/forums/12442-general/suggestions/302097-twofish-encrypted-support). At present it seems the only workaround is to export entries from Keepass (XML) and import to Keeweb.

**Comment by antelle** [comment]
should be implemented as a plugin
