### ISSUE TITLE
Lose the sync with webdav

### ISSUE THREAD

**Issue by FheA** [keeweb/keeweb#421]
Hi,

Today i work with keeweb instead of the old version of keepass.

We uses webdav for the sync.
And for the first time, we looses sync. My mate create a new entry on keeweb and when i connect on this keeweb i dont see his entry. But we can see what sync is done.

I dont understand because we have three files for keeweb for any environment and just one file dont sync.

Please give us an issue :).

Regards.

KeeWeb v1.2.1 (24e17c6, 2016-07-12)
Environment: web
User-Agent: Mozilla/5.0 (Windows NT 6.2; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36

**Comment by antelle** [comment]
Please paste logs from the device which doesn't get synced. Maybe it's caching issue.
Also, please test it on new KeeWeb version, v1.3.

**Comment by FheA** [comment]
[DEBUG] 2016-10-26T12:40:51.970Z [storage-webdav] Stat myserver.xxx.xxx
[DEBUG] 2016-10-26T12:40:51.989Z [storage-webdav] Stated myserver.xxx.xxx Mon, 05 Sep 2016 12:15:18 GMT 20ms
[INFO ] 2016-10-26T12:40:51.989Z [sync:PEDev] Stat found same version, not modified
[INFO ] 2016-10-26T12:40:51.989Z [sync:PEDev] Sync finished no error
[INFO ] 2016-10-26T12:40:52.992Z [sync:PEDev] Sync started webdav myserver.xxx.xxx[object Object]
[INFO ] 2016-10-26T12:40:52.993Z [sync:PEDev] Stat file
[DEBUG] 2016-10-26T12:40:52.993Z [storage-webdav] Stat myserver.xxx.xxx
[DEBUG] 2016-10-26T12:40:53.014Z [storage-webdav] Stated myserver.xxx.xxx Mon, 05 Sep 2016 12:15:18 GMT 20ms
[INFO ] 2016-10-26T12:40:53.014Z [sync:PEDev] Stat found same version, not modified
[INFO ] 2016-10-26T12:40:53.014Z [sync:PEDev] Sync finished no error
[INFO ] 2016-10-26T13:27:39.262Z [open:PEDev] File open request
[INFO ] 2016-10-26T13:27:39.262Z [open:PEDev] Open file from cache, will sync after load webdav
[DEBUG] 2016-10-26T13:27:39.262Z [storage-cache] Load b92d0539-8693-d950-2191-fd31d3919a57
[DEBUG] 2016-10-26T13:27:39.264Z [storage-cache] Loaded b92d0539-8693-d950-2191-fd31d3919a57 2ms
[INFO ] 2016-10-26T13:27:39.264Z [open:PEDev] Loaded file from cache 
[INFO ] 2016-10-26T13:27:39.372Z [file] Opened file PEDev: 107ms, 6000 rounds, 10 kB
[DEBUG] 2016-10-26T13:27:39.372Z [app] Add last open file b92d0539-8693-d950-2191-fd31d3919a57 PEDev webdav myserver.xxx.xxx Mon, 05 Sep 2016 12:15:18 GMT
[INFO ] 2016-10-26T13:27:39.444Z [open:PEDev] Sync just opened file
[INFO ] 2016-10-26T13:27:39.453Z [sync:PEDev] Sync started webdav myserver.xxx.xxx [object Object]
[INFO ] 2016-10-26T13:27:39.455Z [sync:PEDev] Stat file
[DEBUG] 2016-10-26T13:27:39.455Z [storage-webdav] Stat myserver.xxx.xxx
[DEBUG] 2016-10-26T13:27:39.464Z [storage-webdav] Stated myserver.xxx.xxx Mon, 05 Sep 2016 12:15:18 GMT 8ms
[INFO ] 2016-10-26T13:27:39.464Z [sync:PEDev] Stat found same version, not modified
[INFO ] 2016-10-26T13:27:39.464Z [sync:PEDev] Sync finished no error


I dont have an error.

**Comment by antelle** [comment]
Your server gives the same last-modified date for changed file. Please fix it and add corresponding cache expiration headers.

**Comment by antelle** [comment]
looks like server issue. closing until server software is adjusted
