### ISSUE TITLE
Feature Request: Auto-Lock on OS lock

### ISSUE THREAD

**Issue by drtomasso** [keeweb/keeweb#422]
Hi

Could you add an option for immediately locking KeeWeb if Windows (or other OS) is being locked?

**Comment by antelle** [comment]
Is it possible to handle this notification in Electron? Not sure. If yes, it would be fairly simple.

**Comment by antelle** [comment]
It looks like, there's no such API in electron.

**Comment by mkarnicki** [comment]
Damn. I do hope they add that API, I would *love* to have a feature (or plugin) that would lock KeeWeb when macOS is put to sleep. I donated once, would happily donate again. KeeWeb is the-best password manager out there, no doubt. (Side note: you kick ass, @antelle !).

**Comment by antelle** [comment]
Found this in Electron, so we can support it now: https://electron.atom.io/docs/api/browser-window/#event-session-end-windows

**Comment by mammuth** [comment]
But according to the reference this event is only available on Windows, isn't it.

**Comment by antelle** [comment]
Yes, it's windows-only. For mac, electron doesn't handle it for now, so there's no way to check subscribe to the event (it's called `screenIsLocked`). We can still lock keeweb on computer sleep though.

**Comment by antelle** [comment]
Submitted a feature request to Electron: https://github.com/electron/electron/issues/9653

**Comment by antelle** [comment]
I've added a preference to lock on sleep (and moved auto-lock to a separate section):
![lock](https://cloud.githubusercontent.com/assets/633557/26738982/6cd2971e-47d0-11e7-9feb-04ec81733ed9.png)
However in mac it will work only on sleep, not on screensaver or manual locking, until it's implemented in Electron.

**Comment by mkarnicki** [comment]
Lock KeeWeb when macOS put to sleep?! You, Sir, are my hero. I will buy you another two beers soon. Rock on!!! 💯👏

**Comment by antelle** [comment]
Wow, actually, there is a way to detect os lock or screensaver on mac, please see linked electron issue if you're interested. Added to keeweb, will be there in v1.6.

**Comment by mkarnicki** [comment]
Can't wait to see this released :D 💯  ❤️

**Comment by antelle** [comment]
It should happen, hopefully, this month

**Comment by Andreas-Schoenefeldt** [comment]
Hey, just found this amazing feature request - would love to see that too :)

The new version is still on the way?

Best wishes and thx again for this amazing tool!
Andreas

**Comment by antelle** [comment]
Yep, there were some difficulties... But this feature is ready and waiting for it.

**Comment by mkarnicki** [comment]
YESSS v1.6.0 🔥. I just bought you two beers, @antelle . I'll gladly do it again in a couple months. You should definitely add a Donate button on keeweb.info website. I was looking for it there, but I only found it in the KeeWeb app -> Settings -> About section. No need to be shy, this is a great piece of software and you definitely deserve donations, if you're giving it away for free.

Thank you for Auto-Lock on OS lock!

**Comment by antelle** [comment]
Thanks!
Sorry that it took so long.
