### ISSUE TITLE
Cache the Config file in the Localstorage too.

### ISSUE THREAD

**Issue by apollo13** [keeweb/keeweb#428]
Currently KeeWeb fails to load with:
```
Error loading app
There was an error loading app settings. Please double check app url or contact your administrator. 
```
if I am not in the company VPN since it cannot load the config. Since the config is nothing which will change on a regular basis, it would be nice to cache it in the localstorage or so till one has network access again.

**Comment by antelle** [comment]
But on the first load, if the config key is present, we should fail.
Also, it would be useful, to have a special property in config, e.g. `cacheable: true`, to denote that it could be cached.

**Comment by apollo13** [comment]
Yeah, it absolutely makes sense to fail on the first request. The property is a nice idea too!

**Comment by apollo13** [comment]
Note for anyone else running into this: This effectively stops the offline usable of the App since it will not load without the config.

**Comment by antelle** [comment]
Deployed to [beta.keeweb.info](https://beta.keeweb.info), will be available in the next release.
{ "cacheConfigSettings": true }
