### ISSUE TITLE
[Feature request] Disable remove option

### ISSUE THREAD

**Issue by rtfmjoey** [keeweb/keeweb#429]
Is it possible to add an option which disables the ability to remove databases via the login page?

I load my database via WebDAV and have disabled most options via settings:
    "canOpen": false, // show Open button
    "canOpenDemo": false, // show Demo button
    "canOpenSettings": false, // show Settings button
    "canCreate": false, // show Create button
    "canImportXml": false, // show Import XML button

However, the webdav database can still be deleted: https://s22.postimg.org/wzrzn23ip/keeweb_delete.png (listed as Joey)

It would be nice to have an option to disable this :)

**Comment by antelle** [comment]
Deployed to [beta.keeweb.info](https://beta.keeweb.info), will be available in the next release.
Settings key: "canRemoveLatest", `true` by default.
