### ISSUE TITLE
Not possible to change group of an entry

### ISSUE THREAD

**Issue by freijon** [keeweb/keeweb#432]
Once an entry has been generated it's impossible to change the group (folder?). It should be possible to move (re-group) entries by dragging them into an other group.

KeeWeb v1.3.3 (52701af, 2016-09-26)
Environment: web
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.89 Safari/537.36 Vivaldi/1.5.658.3

**Comment by antelle** [comment]
Hello,
Are you sure they are not moved?
Please try to open the desired group and check if this entry is there.
By default, parent group includes all entries from the inside, you can change it in settings.

**Comment by freijon** [comment]
I just tested it with Google Chrome. It works there.
My standard browser is Vivaldi and unfortunately there it does not work.

**Comment by antelle** [comment]
With the same steps, right?
Is it the same on Demo db? Maybe there's something in console log?

**Comment by antelle** [comment]
It doesn't work, you're right, checked it. No further information is needed, thanks for your report, will be fixed.

**Comment by freijon** [comment]
Yes, I do it exactly the same way: Dragging and dropping the entry to the
group. I also tried changing the "Group" property on the right, but it
seems to be of informative nature and is read-only. I don't have access to
my console right now but I'll check it later.

**Comment by antelle** [comment]
I don't need any log now, for me it's the same, so I'll be able to fix it.

**Comment by freijon** [comment]
Great. Keep me posted if you need any further information or further
testing.

On Tue, Nov 8, 2016 at 8:43 AM antelle <notifications@github.com> wrote:

I don't need any log now, for me it's the same, so I'll be able to fix it.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/keeweb/keeweb/issues/432#issuecomment-259067563>, or mute
the thread

**Comment by jacobmischka** [comment]
It's also not working for me in the desktop app anymore, on Linux.

Thanks!

**Comment by antelle** [comment]
Deployed to [beta.keeweb.info](https://beta.keeweb.info), will be available in the next release.
Vivaldi is weird, added a dirty hack.
