### ISSUE TITLE
keyboard layout issue (y/z) with autotype on linux

### ISSUE THREAD

**Issue by benzkji** [keeweb/keeweb#441]
- what were your actions?
auto type on linux. works technically ok, as can be seen from the logs...

- what was wrong?
somehow, it pasted y instead of z. keyboard layout issue? I have a fresh installed Xubuntu, with a ch-de mac keyboard layout...

- app version
1.3.3 64bit .deb download from your webpage

- your user-agent (from Settings/Help section)
KeeWeb v1.3.3 (52701af, 2016-09-20)
Environment: electron v1.3.3
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) KeeWeb/1.3.3 Chrome/52.0.2743.82 Electron/1.3.3 Safari/537.36

- does it happen on Demo or New database?
probably, didn't try?

- if you are using a test db without your personal data, please attach it
no

- please, open dev tools in your browser and attach output log from Console tab 
[DEBUG] 2016-11-15T09:54:15.653Z [auto-type] Auto type event 
[DEBUG] 2016-11-15T09:54:15.656Z [auto-type] Get window title
[INFO ] 2016-11-15T09:54:15.661Z [launcher] spawn xdotool: 0, 5ms
Sign in to GitHub · GitHub - Mozilla Firefox
[DEBUG] 2016-11-15T09:54:15.661Z [auto-type] Window title Sign in to GitHub · GitHub - Mozilla Firefox 
[DEBUG] 2016-11-15T09:54:23.021Z [auto-type] Entry selected [object Object]
[DEBUG] 2016-11-15T09:54:23.022Z [auto-type] Hide window
[DEBUG] 2016-11-15T09:54:23.127Z [auto-type] Start {USERNAME}{TAB}{PASSWORD}{ENTER}
[DEBUG] 2016-11-15T09:54:23.127Z [auto-type] Parsed [op:USERNAME,op:TAB,op:PASSWORD,op:ENTER]
[DEBUG] 2016-11-15T09:54:23.127Z [auto-type] Resolved [*******,key:tab,[*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*],key:enter]
[INFO ] 2016-11-15T09:54:23.275Z [launcher] spawn xdotool: 0, 147ms
[INFO ] 2016-11-15T09:54:23.353Z [launcher] spawn xdotool: 0, 78ms
[INFO ] 2016-11-15T09:54:23.422Z [launcher] spawn xdotool: 0, 69ms
[INFO ] 2016-11-15T09:54:23.487Z [launcher] spawn xdotool: 0, 65ms
[INFO ] 2016-11-15T09:54:23.553Z [launcher] spawn xdotool: 0, 65ms
[INFO ] 2016-11-15T09:54:23.618Z [launcher] spawn xdotool: 0, 65ms
[INFO ] 2016-11-15T09:54:23.685Z [launcher] spawn xdotool: 0, 66ms
[INFO ] 2016-11-15T09:54:23.750Z [launcher] spawn xdotool: 0, 65ms
[INFO ] 2016-11-15T09:54:23.816Z [launcher] spawn xdotool: 0, 66ms
[INFO ] 2016-11-15T09:54:23.882Z [launcher] spawn xdotool: 0, 65ms
[INFO ] 2016-11-15T09:54:23.947Z [launcher] spawn xdotool: 0, 66ms
[INFO ] 2016-11-15T09:54:24.013Z [launcher] spawn xdotool: 0, 65ms
[INFO ] 2016-11-15T09:54:24.080Z [launcher] spawn xdotool: 0, 66ms
[INFO ] 2016-11-15T09:54:24.145Z [launcher] spawn xdotool: 0, 66ms
[INFO ] 2016-11-15T09:54:24.211Z [launcher] spawn xdotool: 0, 65ms
[INFO ] 2016-11-15T09:54:24.276Z [launcher] spawn xdotool: 0, 65ms
[INFO ] 2016-11-15T09:54:24.343Z [launcher] spawn xdotool: 0, 67ms
[INFO ] 2016-11-15T09:54:24.359Z [launcher] spawn xdotool: 0, 17ms
[DEBUG] 2016-11-15T09:54:24.360Z [auto-type] Complete 1233ms

**Comment by antelle** [comment]
what happens, if you type `xdotool key U7a`?

**Comment by benzkji** [comment]
it says "y"

**Comment by antelle** [comment]
It's xdotool bug, then. It must send Z.

**Comment by benzkji** [comment]
ok. seems there are some issues with xdotool. will post here if I find something.

**Comment by benzkji** [comment]
use `setxkbmap -query | grep layout`
to get current layout, then (ironically) `setxkbmap your_layout` seems to solve it. need to make this somehow persistent, but that's another story.

**Comment by benzkji** [comment]
setting the layout explicitly (instead of "use system default") helped in my case (using xubuntu, and the included keyboard settings gui tool).

**Comment by antelle** [comment]
This should be fixed in v1.17
