### ISSUE TITLE
Website not showing in list table view mode

### ISSUE THREAD

**Issue by whookid** [keeweb/keeweb#444]
- Enable "Entries list table view" in settings
- Add a new entry and fill in the "Website" field
- Notice how the table containing the entry does not contain the value entered in the "Website" field

App info:
KeeWeb v1.3.3 (52701af, 2016-09-20)
Environment: electron v1.3.3
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_2) AppleWebKit/537.36 (KHTML, like Gecko) KeeWeb/1.3.3 Chrome/52.0.2743.82 Electron/1.3.3 Safari/537.36

**Comment by antelle** [comment]
Deployed to [beta.keeweb.info](https://beta.keeweb.info), will be available in the next release
