### ISSUE TITLE
Problem with key files on Windows 10

### ISSUE THREAD

**Issue by alexandru** [keeweb/keeweb#447]
Here's a screenshot: 

![screenshot 2016-11-20 16 47 39](https://cloud.githubusercontent.com/assets/11753/20463680/64523d06-af41-11e6-84fb-897bcd31e2e7.png)

In order for it to be able to open my passwords file I had to delete `C:\Users\alexa\AppData\Roaming\KeeWeb`. So in order to have this happening, the only thing I did was to try and add a "key file" to my database. In which case I first got this weird message:

![screenshot 2016-11-20 16 54 18](https://cloud.githubusercontent.com/assets/11753/20463718/23914234-af42-11e6-93b9-a72c9a3b33d9.png)

You can't escape this screen and if you cancel then you end up in this invalid state (notice the "sync error" message):

![screenshot 2016-11-20 16 56 27](https://cloud.githubusercontent.com/assets/11753/20463727/6121b106-af42-11e6-8185-0eda5552dad2.png)

And after this I can't open my database anymore until I manually delete `C:\Users\alexa\AppData\Roaming\KeeWeb`, as I've said in the beginning.

EDIT: for completeness here's the key file that I tried using, in case that makes any difference:
https://www.dropbox.com/s/gqg3dq2a50geojf/ParolaMea.key

**Comment by antelle** [comment]
So, you changed the key on remote machine, and it ended up with this error. Right?

**Comment by alexandru** [comment]
My original message said that, but no, there's no need for a remote machine to be involved at all - while writing the description I tested again the steps required - so all you need to do is to try and add that key file to a database.

**Comment by antelle** [comment]
Doesn't repeat on mac. Maybe the file gets changed somehow, because I see that it's located in Dropbox folder. Needs investigation

**Comment by alexandru** [comment]
@antelle yes, I forgot to mention, I couldn't reproduce it on OS X or Linux either. This is a Windows specific problem.

**Comment by antelle** [comment]
fixed
