### ISSUE TITLE
Desktop app start in background on startup?

### ISSUE THREAD

**Issue by Tephnos** [keeweb/keeweb#448]
Didn't see this as an option, so possible enhancement? Of course, the database would be locked, but instead of having to open the app manually you can hotkey or quickly fire it up from the icons bar.

**Comment by gustavohw** [comment]
Any updates? Auto-starting the app via shell folder on Windows but can't do minimized, maybe pass an --argument on the shortcut?

**Comment by antelle** [comment]
It should be an option in settings. Not that hard to implement.

**Comment by BWPanda** [comment]
I'd love to see an option for KeeWeb to start minimized on Linux.

**Comment by aroumeliotis** [comment]
Yes, I totally agree! Having apps throwing a window on boot is pretty annoying!

**Comment by ikogan** [comment]
For now, I'm creating a start command that looks like this:

```bash
bash -c 'KeeWeb & xdotool windowminimize $(xdotool search --sync --onlyvisible --class "keeweb")'
```

**Comment by mkarnicki** [comment]
Nice @ikogan ! If someone has time to come up with similar workaround for OS X, that'd be sweet :)

**Comment by XavierTolza** [comment]
Anything new on this request? I would love to have keeweb started in the system tray when I open my session

**Comment by antelle** [comment]
There's also a similar request here: https://github.com/keeweb/keeweb/issues/1179#issuecomment-542269102
