### ISSUE TITLE
Error after opening a database with a changed password

### ISSUE THREAD

**Issue by omidfi** [keeweb/keeweb#449]
Using the web version, I changed the master key. I also use a key file. Both loaded from Dropbox. 

- what was wrong?
Now on any other device, I need to login with my old master key. After a few seconds, I'm redirected to a page that says: Master Key Changed, insert new master key

From there, entering the new master key doesn't work. And this is the error in console:

```
:formatted:46431 Uncaught TypeError: Cannot read property 'el' of null
    at n.accept (https://app.keeweb.info/:21:14385)
    at HTMLDivElement.dispatch (https://app.keeweb.info/:3:20061)
    at HTMLDivElement.q.handle (https://app.keeweb.info/:3:18088)accept @ :formatted:46431dispatch @ :formatted:17612q.handle @ :formatted:17538
```

Here's a screenshot that might help

![keeweb](https://cloud.githubusercontent.com/assets/7697632/20520148/5e0439cc-b0ae-11e6-931a-db6d88df220a.png)

**Comment by omidfi** [comment]
Removing the database file, in the first login screen, and adding again solves the problem.

**Comment by antelle** [comment]
fixed

**Comment by omidfi** [comment]
Awesome. Thanks :)
