### ISSUE TITLE
Faster responsiveness of auto-type

### ISSUE THREAD

**Issue by Tephnos** [keeweb/keeweb#451]
This is just me comparing 1Password and KeeWeb, is it at all possible to make the app faster at starting up from inactive when trying to hit shift+alt+t to auto-type?

1Password is mostly instant, but KeeWeb can take a couple of seconds to get going. Not sure if this can be sped up based on how you programmed it, but if possible it would be nice.

**Comment by antelle** [comment]
Not constructive, duplicate of #347
