### ISSUE TITLE
Move entry from one database into another?

### ISSUE THREAD

**Issue by orschiro** [keeweb/keeweb#452]
Hi all, 

Is it possible to move an entry from one database to another like this?

![image](https://cloud.githubusercontent.com/assets/170947/20664367/29136416-b55b-11e6-80a0-b3acb490203a.png)

**Comment by antelle** [comment]
no, it's not possible for now

**Comment by orschiro** [comment]
Thank you.

Do you think it is a useful feature?

**Comment by antelle** [comment]
Sure, it would be a very useful feature

**Comment by timbru31** [comment]
Isn't this a dupe of #336?

**Comment by antelle** [comment]
@timbru31, exactly. Thanks!
