### ISSUE TITLE
Import from LastPass?

### ISSUE THREAD

**Issue by orschiro** [keeweb/keeweb#453]
Dear all, 

Using LastPass Pocket I can export all my data as `lastpass_backup_lps.xml.csv`.

I tried to use "Import XML" in KeeWeb to import this file but it is failing.

![image](https://cloud.githubusercontent.com/assets/170947/20671521/e4618f64-b57d-11e6-9f33-7ce88a079780.png)

**Comment by antelle** [comment]
We don't support import from other formats at the moment. You can use KeePass to convert between them.

**Comment by orschiro** [comment]
Great, this worked for me. Thank you. :-)

**Comment by tibdex** [comment]
Hi,

I know this is an old issue but new people might still stumble into it. I made a small serverless tool a while ago to convert the LastPass CSV export to a KeePass XML file compatible with KeeWeb. It's open source and available here: https://github.com/tibdex/lastpass-to-keepass.

I hope you will find it useful.

**Comment by antelle** [comment]
Deployed to [beta.keeweb.info](https://beta.keeweb.info), will be available in the next release.

<img width="1028" alt="Screen Shot 2019-09-25 at 23 25 46" src="https://user-images.githubusercontent.com/633557/65641008-f60f0980-dfeb-11e9-8cbb-d784fc24d067.png">
