### ISSUE TITLE
AutoType URL detection and Chrome

### ISSUE THREAD

**Issue by drtomasso** [keeweb/keeweb#454]
Hi

URL detection for Google Chrome (`54.0.2840.99 m 64-bit`) has recently stopped working. Auto-Type is only detecting window title. Is there a way to get it working again?

KeeWeb version:
```
KeeWeb v1.3.3 (52701af, 2016-09-20)
Environment: electron v1.3.3
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) KeeWeb/1.3.3 Chrome/52.0.2743.82 Electron/1.3.3 Safari/537.36
```

**Comment by drtomasso** [comment]
Just some additional information. I tried reinstalling both KeeWeb and Chrome (deleting local appdata as well), but with no luck. I have another computer were Chrome is synced with this one, and there it still works. Both computers have the same settings and plugins in Chrome. The only difference I know about, is that this computer has Bitlocker activated, but that shouldn't cause the problem, I think.

Log:
```
2017-01-13T07:45:27.351Z [auto-type] Auto type event null   index.html:13
2017-01-13T07:45:27.353Z [auto-type] Get window title   index.html:13
2017-01-13T07:45:27.823Z [launcher] spawn C:\Program Files\KeeWeb\resources\app\helper\win32\KeeWebHelper.exe: 0, 469ms
Twitter - Google Chrome   index.html:13
2017-01-13T07:45:27.823Z [auto-type] Window title Twitter - Google Chrome undefined
```

**Comment by antelle** [comment]
For me, it works, may have been fixed. At least on http://keepass.info/help/kb/testform.html and Chrome 56, please feel free to reopen if it's still failing
