### ISSUE TITLE
Sync to Google Drive spinning forever

### ISSUE THREAD

**Issue by tanob** [keeweb/keeweb#456]
### Actions:
1. the sync process starts automatically (not started by user)
2. the sync process is stuck forever, this only happens sometimes, I'm not sure what causes it

### Investigation:

By looking the logs I've noticed that successful syncs to Google Drive usually have a "OAuth popup opened" and are followed by a "OAuth success". When the sync gets stuck the latter doesn't happen. For example:
```
2016-11-30T18:40:28.856Z [storage-gdrive] OAuth popup opened
2016-11-30T20:10:28.093Z [updater] Checking for update...
```

So looking at the code I see that one thing that can fail is opening the popup so I opened devtools and tried calling `window.open` with some parameters, which caused a window to open, when I closed it then the sync process got unstuck:

```
var url = 'https://accounts.google.com/o/oauth2/v2/auth';
var title = 'OAuth';
var settings = "width=600,height=400,left=1166,top=116,dialog=yes,dependent=yes,scrollbars=yes,location=yes";
var foo =  window.open(url, title, settings);
2016-12-02T02:29:57.853Z [storage-gdrive] OAuth error popup closed
2016-12-02T02:29:57.853Z [storage-gdrive] Stat error 47264085ms unauthorized
2016-12-02T02:29:57.854Z [sync:Passwords v2] Stat error, dirty, save to cache unauthorized
```

Then I was able to click in "Save" and the sync happened successfully.

### Expected behavior: 
Sync start automatically and finish within some time limit (e.g. 30 secs)

### App information:
```
KeeWeb v1.3.3 (52701af, 2016-09-20)
Environment: electron v1.3.3
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_1) AppleWebKit/537.36 (KHTML, like Gecko) KeeWeb/1.3.1 Chrome/52.0.2743.82 Electron/1.3.3 Safari/537.36
```

Let me know if you need more information. Thanks!

**Comment by avently** [comment]
@antelle please, review this issue. I have such problems too often. I can't stop sync and resync changes then. I will lose new data even if i close the tab. So time-out is what we need here. And maybe local backup before remote sync. My sync stopped after a line "Stat ...kdbx_file_location..."

**Comment by tanob** [comment]
Just to report I'm still having this issue with the following app version:
```
KeeWeb v1.6.3 (cded8a4, 2017-12-11)
Environment: electron v1.7.9
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) KeeWeb/1.6.3 Chrome/58.0.3029.110 Electron/1.7.9 Safari/537.36
```

**Comment by gynet** [comment]
Had the same issue.

**Comment by tanob** [comment]
I've been running a local version based on `develop` branch listening to more events and with more logs added to the [PopupNotifier](https://github.com/keeweb/keeweb/compare/develop...tanob:wip-issue-456?expand=1#diff-3517be16578eabf694fad15dab54afbc) which provides the function to open windows (aka `window.open`).

I can see at least two scenarios where this bug is happening:
1. __Mac wakes up from sleep with lid closed__, this might be happening due to some `pmset` assertion added by specific applications (e.g. to sync mail/addressbook, verify VPN status, etc.)

   For this case Electron calls the `crashed` event with `killed` parameter as true. You can see in my branch that I'm handling that event now on the same way as for `closed`.

2. __Network issue opening URL in webContents__

    <img width="779" alt="screen shot 2018-01-30 at 12 17 36" src="https://user-images.githubusercontent.com/5013/35655975-c9c878b0-06db-11e8-9b01-fd1a8e74f1b2.png">

    Notice that in this scenario there was a 2h difference from when storage got the window handler (5th line above) back to when Electron actually called the `did-fail-load` event with error code -105 (`ERR_NAME_NOT_RESOLVED`) trying to open the Google OAuth URL.
    In this case the window was also not opened and the sync spinner indicator was active. Seems to be like a bug in Electron.

    Should we also handle `did-fail-load` the same way as `closed`? Since there's probably no reload action available for user when in Electron mode, other than close the popup if it opens?

**Comment by tanob** [comment]
@antelle what do you think about the analysis above?

**Comment by antelle** [comment]
@tanob yes, of course it makes sense to handle `did-fail-load` event.

**Comment by tanob** [comment]
@antelle any plans to release a new app version with this fix?

**Comment by antelle** [comment]
@tanob a bit later, with the Google Cookies fix.
