### ISSUE TITLE
How to with Auto Type?

### ISSUE THREAD

**Issue by bueltge** [keeweb/keeweb#457]
Thanks for working, developing this app - really great and helpful.

But what I miss is a documentation about the functionalities of the app. Especially a how to to work with Auto Type. The wiki have hints about the keywords and shortcuts, but I can find a post, more content, how is it possible to use this. What is necessary in the auto type settings that a user can use this?

Maybe a export, a active user of KeeWeb can write a small how to, add to the wiki?

**Comment by antelle** [comment]
You can use auto-type just as is, without any customization. Just select entry and hit Ctrl/Cmd+T.
If you would like to customize settings, go to more... -> auto-type.

**Comment by bueltge** [comment]
Thanks @antelle 
I played with this shortcut and also the customize possibilities. But is necessary as field, as key inside the setting that it works?

**Comment by antelle** [comment]
Sorry, I didn't understand your message... Auto-type settings are optional

**Comment by bueltge** [comment]
Yes, I understand this. But what is the power of the possibilities, the customization?

**Comment by antelle** [comment]
Be default, it types username / tab / password / tab / enter.
You might want to type another sequence (e.g. remove Enter), which can be changes in this setting.

**Comment by bueltge** [comment]
OK, nice start to play and maybe, I think I understand the possibility now. 

#closed for now. A deep test is now on my side.
Thanks! :heart:
