### ISSUE TITLE
Pronouncable passwords not random enough?

### ISSUE THREAD

**Issue by FlxVctr** [keeweb/keeweb#458]
When using the password generator for pronounceable passwords with 10 chars it occurred to me that, except for uppercase/lowercase, words repeat themselves astonishingly often. Are the generated pws truly random, or are they generated from a fixed seed? Was testing the desktop application.

**Comment by antelle** [comment]
That's strange, does it repeat for longer passwords?

**Comment by FlxVctr** [comment]
Got this with about 30 refreshs:
![2016-12-03 at 4 36 pm](https://cloud.githubusercontent.com/assets/8951994/20857408/de7c308e-b976-11e6-90a7-c1432a6758ac.png)

**Comment by antelle** [comment]
This should be investigated. The generator we use is Phonetic.JS, here's it: https://github.com/keeweb/keeweb/blob/master/app/scripts/util/phonetic.js

**Comment by antelle** [comment]
I can guess, it's related to this: 
https://github.com/keeweb/keeweb/blob/master/app/scripts/util/phonetic.js#L169
Math.random() is used there, which should be replaced with crypto.getRandomValues.

**Comment by FlxVctr** [comment]
Yes, after a quick sift through the code I also suspected Math.random() to be the culprit.

It is also used across kdbxweb at a number of places. But I'm not knowledgeable enough, neither in JS, this codebase, nor in Cryptography in general, to judge whether that is an issue or whether truly random numbers would just result in a not justifiable slow down.

It's just a bit concerning considering that it is said to be not providing secure random numbers (https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Math/random).

Thanks for the quick response.

**Comment by antelle** [comment]
No, kdbxweb is not using Math.random for random numbers generation, we're using crypto.getRandomValues: https://github.com/keeweb/kdbxweb/blob/master/lib/crypto/random.js#L19
We'll fix this by providing random seed to phoneticjs from kdbxweb.

**Comment by antelle** [comment]
Added the fix and deployed to [beta.keeweb.info](https://beta.keeweb.info), please test if it works for you

**Comment by FlxVctr** [comment]
At the moment the beta version does not even open the password generator when I click on the bolt.

**Comment by antelle** [comment]
thanks, fixed it

**Comment by FlxVctr** [comment]
Seems to be fixed now judging by manual testing. Could be a good idea to have this implemented as part of a test suite (test for statistically significant recurrence of random pws for all the different pw generators) for the future as it's pretty critical for security imho.
