### ISSUE TITLE
Auto-Type issue on Safari Mac

### ISSUE THREAD

**Issue by umlx5h** [keeweb/keeweb#459]
Hi.
I used Auto-type in Safari Mac, but it does not work.
TAB does not work and ID and password are entered only in the top field.
It works properly with Chrome and Firefox.

> KeeWeb version:
> KeeWeb v1.3.3 (52701af, 2016-09-20)
> Environment: electron v1.3.3
> User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_1) AppleWebKit/537.36 (KHTML, like Gecko) KeeWeb/1.3.3 Chrome/52.0.2743.82 Electron/1.3.3 Safari/537.36

**Comment by antelle** [comment]
It works for me here: http://keepass.info/help/kb/testform.html
Is it a website-specific issue?

**Comment by umlx5h** [comment]
Sorry, I solved it.
I edited auto-type settings and inserted DELAY behind TAB.
Then it worked normally.
Thank you.
