### ISSUE TITLE
Problems with config.json

### ISSUE THREAD

**Issue by olli84** [keeweb/keeweb#460]
Thanks for taking the time to contribute!

Please, read https://github.com/keeweb/keeweb/wiki/FAQ before submitting a new issue and fill in the following (if applicable):

- what were your actions?
Keeweb selfhosting, v. 1.3.3 with the sample config.json from wiki, integrated with kw-config

- what was wrong?
Error loading app
There was an error loading app settings. Please double check app url or contact your administrator.

- app version
1.3.3
- your user-agent (from Settings/Help section)
every browser same. Firefox, Chrome, Internet Explorer

- does it happen on Demo or New database?
everywhere only error loading app

- if you are using a test db without your personal data, please attach it
-
- please, open dev tools in your browser and attach output log from Console tab 
    (if you are using desktop app, devtools can be opened from Settings/General/Advanced)

Internet Explorer:
DOM7011: Der Code auf dieser Seite hat die Zwischenspeicherung für das Vor- und Zurücknavigieren deaktiviert. Weitere Informationen dazu finden Sie unter: http://go.microsoft.com/fwlink/?LinkID=291337
Datei: xxx
HTML1300: Navigation wurde ausgeführt.
Datei: xxx
"AppCache" wird erstellt mit Manifest: "https://kweb.07141.net/manifest.appcache".
HTML1424: Ungültiges Zeichen
Datei: xxx, Zeile: 29, Spalte: 20526
HTML1424: Ungültiges Zeichen
Datei: xxx, Zeile: 29, Spalte: 20927
2016-12-07T05:00:18.258Z [app] Loading config from config.json
2016-12-07T05:00:18.559Z [app] Invalid app config, no settings section {
  "settings": {
    "theme": "fb", // UI theme, possible values: fb (flat blue), wh (white), hc (high contrast) and other
    "locale": "en", // language
    "expandGroups": true, // show entries from all subgroups
    "listViewWidth": null, // list view width
    "menuViewWidth": null, // left menu width
    "tagsViewHeight": null, // tags menu section height
    "autoUpdate": "install", // auto-update options: "install", "check", ""
    "autoSave": true, // auto-save open files
    "rememberKeyFiles": false, // remember keyfiles selected on Open page
    "idleMinutes": 15, // app lock timeout after inactivity
    "tableView": false, // view entries as table, instead of list
    "colorfulIcons": false, // use colorful custom icons, instead of grayscale
    "lockOnCopy": false, // lock app on password copy
    "skipOpenLocalWarn": false, // don't show warning for local files
    "hideEmptyFields": false, // hide empty entry fields
    "s

That's all i got. Where is my error? "xxx" is my homepage.

**Comment by olli84** [comment]
Hey there,

tried serveral thinks, nothing works.

tried a really small config.json

`{
  "settings": {
    "locale": "de-DE"
}
}`

and tried with v. 1.3.3 - 1.3.0
everytime the same error:
`2016-12-08T08:19:22.671Z [app] Invalid app config, no settings section {
  "settings": {
    "locale": "de-DE"
}
}`

**Comment by antelle** [comment]
please open devtools in your browser, select config request and see what's there

**Comment by olli84** [comment]
Hey antelle,
thanks for your message. I only have Internet Explorer 11 here, so this is everything i can get:
`URL	Protokoll	Methode	Ergebnis	Typ	Empfangen	Benötigte Zeit	Initiator	Warten‎‎	Start‎‎	Anforderung‎‎	Antwort‎‎	Cachelesezugriff‎‎	Zeitspanne‎‎
https://kweb.07141.net/	HTTPS	GET	304	text/html	188 B	16 ms	Aktualisieren	0	0	0	16	0	717
/manifest.appcache	HTTPS	GET	200	text/cache-manifest	369 B	156 ms		546	125	16	15	0	31
/settings.json	HTTPS	GET	200	application/json	306 B	140 ms	XMLHttpRequest	593	94	46	0	0	0`

`DOM7011: Der Code auf dieser Seite hat die Zwischenspeicherung für das Vor- und Zurücknavigieren deaktiviert. Weitere Informationen dazu finden Sie unter: http://go.microsoft.com/fwlink/?LinkID=291337
Datei: xxx.net
HTML1300: Navigation wurde ausgeführt.
Datei: xxx.net
"AppCache" wird erstellt mit Manifest: "https://xxx.net/manifest.appcache".
2016-12-08T10:39:48.957Z [app] Loading config from settings.json
2016-12-08T10:39:49.116Z [app] Invalid app config, no settings section {
  "settings": {
    "locale": "de-DE"
}
}
`
Do you need something else?

Thanks alot!

**Comment by antelle** [comment]
is it ok on beta.keeweb.info?

**Comment by olli84** [comment]
Whoooooohooooo! YES! The Beta is okay, perfect! Thanks alot!

**Comment by antelle** [comment]
Yes, I forgot about this ie-specific bug, it has been recently fixed on beta

**Comment by olli84** [comment]
Thanks, so i will close that! :)
