### ISSUE TITLE
[Feature request] Multiline fields support and/or internal text editor

### ISSUE THREAD

**Issue by arantir** [keeweb/keeweb#461]
Sometimes you have a pice of private data which you want to save into kdbx but don't want to store it on the disk as a file (just to attach it later) because then you would have to purge the file from the disk in a secure way which can be rather complicated. And the data can contain new line characters and various Unicode chars as well.

KeeWeb has only single-line text field and removes new lines even if you copy-past them.

KeePass has a textarea-like input for extra fields and also has an internal text editor, even allowing you to create an empty file and edit it (without exposing it to the disk), and download as an attachment (if ever needed).

Although KeePass implementation is quite advanced it would be really great to be able, at least, to copy-paste some text exactly as is into KeeWeb.

**Comment by antelle** [comment]
It's a bug... #107

**Comment by arantir** [comment]
I looked to similar issu but missed that one :(

If so can we leave this a a feature request for a text editor? There're quite a lot JS editors in the wild, so this should be a big deal.

**Comment by antelle** [comment]
First, we should implement a multi-line fields.
Text editor may be implemented as a plugin later, they are rather heavy and should not be built-in.

**Comment by arantir** [comment]
Fair. Thank you.
