### ISSUE TITLE
Setup dev environment

### ISSUE THREAD

**Issue by amitguptagwl** [keeweb/keeweb#462]
I was trying to add a feature. where double click on text area can popup a bigger text box (may be markdown/HTML editor) to edit the notes. But I couldn't setup the dev environment.

If possible, can we have a wiki page about how to setup dev environment?

**Comment by antelle** [comment]
`npm i`
`grunt dev`

**Comment by amitguptagwl** [comment]
Thanks. But it was giving an error "dev task not found" :(

**Comment by antelle** [comment]
Are you on develop branch?

**Comment by amitguptagwl** [comment]
Yes.

**Comment by antelle** [comment]
Please launch 'grunt --help' and copy the output section 'Available tasks'.

**Comment by amitguptagwl** [comment]
Umm.. thanks, I'll try that. I had removed the project from my local as it was not working.
