### ISSUE TITLE
ACLs, multi-user DBs possibility

### ISSUE THREAD

**Issue by jaddie** [keeweb/keeweb#464]
Hi, 

I was just taking a look through the app, it looks very interesting and I would quite like to use it, although I was wondering how possible the item you have in your ideas wiki page would be & maybe how hard you think it is?

"ACLs, multi-user DBs" -- This would be incredibly useful, as we are currently trying to not end up having to pay for something which costs a small fortune especially for us as a startup such as 1Password!

We'll obviously contribute and work on this where possible with you as well as this would make a very unique side to the program.

Kind Regards
James
RealDNA

**Comment by antelle** [comment]
It would be rather hard, most probably, if we create it, it will be an enterprise version with server: https://keeweb.info/enterprise.html

**Comment by jaddie** [comment]
Ah I see, thats a shame, well either way even if it is hard, it would be great if you maybe released a todo list for it, or similar. That way possible public contributors (such as myself) could start working on it as and when time permitting and get to having something made as this would really tilt the scales for us tbh, especially with it being open source & such and not costing a bloody fortune like everything else.

**Comment by antelle** [comment]
At this stage, I don't have clear understanding of what has to be done, because the idea is not ready yet: there are several problems to solve.

**Comment by jaddie** [comment]
Ooh, does this mean you might have an idea in sight for how this might work? If you do then please drop a message on here as and when as I'll try and help out with it any way I can, even if its just providing some kind of resources :)

**Comment by antelle** [comment]
Yes, I have an idea, briefly it's described in [this](https://keeweb.info/img/diag.svg) picture.

**Comment by Pit-Storm** [comment]
It there ongoing progress on this feature? Would be a charm to have that. The links posted here are not working anymore.

**Comment by antelle** [comment]
No, and most likely we won't be able to make it.  
The format is not designed to support multiple users, add it would be quite complicated to add it there.

**Comment by antelle** [comment]
I assume, this can be closed, we won't be able to provide this in KDBX format.
