### ISSUE TITLE
Application closing down instead of minimising to taskbar

### ISSUE THREAD

**Issue by Tephnos** [keeweb/keeweb#465]
I have the option of minimising the app to the taskbar instead of closing it down when I 'close' it, so that autotype still works on command. However, sometimes after opening the app back up and then closing it again, it actually does close down, not always respecting the option to minimise to taskbar.

App version is latest desktop for Windows. Unable to provide a log since well, the app shuts off.

**Comment by antelle** [comment]
I think it's the same as #389, so fixed in v1.4
