### ISSUE TITLE
Mac App - Language change for master password filling

### ISSUE THREAD

**Issue by romdim** [keeweb/keeweb#466]
Hello there! Thanks a lot for your app!

I'm using the mac app.
When I open a kdbx file, it asks for the master password and I cannot change from English to another language even though I can do this for every other app in the OS.
So I have to fill it in elsewhere and then copy-paste it there to open my passwords.

Thank you very much in advance!

**Comment by antelle** [comment]
You cannot change language for all passwords input on macOS.

**Comment by romdim** [comment]
Heck, you're right! I'm a new Mac user and I'm finding new reasons to hate it.. :)
Thanks for the quick reply!
