### ISSUE TITLE
date of last sync wrong in german version

### ISSUE THREAD

**Issue by gruenheit** [keeweb/keeweb#469]
Allthough in the logfile the latest sync is dated today, in the settings it states "Letzte Synchronisierung: 4 Dez 2016 11:21:34" the file in hosted via WebDAV.
[Sync_not_currently.txt](https://github.com/keeweb/keeweb/files/659672/Sync_not_currently.txt)

KeeWeb v1.3.3 (52701af, 2016-09-20)
Environment: electron v1.3.3
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_2) AppleWebKit/537.36 (KHTML, like Gecko) KeeWeb/1.3.3 Chrome/52.0.2743.82 Electron/1.3.3 Safari/537.36

**Comment by antelle** [comment]
Sorry, I completely missed your issue.
Please feel free to reopen with logs, if it's still actual.
