### ISSUE TITLE
Request to include vault

### ISSUE THREAD

**Issue by blaggacao** [keeweb/keeweb#47]
Kudos for this! My favorite tool getting even more favored!

I'd like to point you to the vaultproject.io by Hashicorp, which takes secrets management to the next level in distributed environenmets, sure they have no UI included, and both KeePass and your Webport would probably make a very nice complement. 

A vault backend to your Keepass app would just be hilarious.

**Comment by antelle** [comment]
:+1:  this is definitely a good idea and would be a unique feature, to allow changing not only storage (dropbox, onedrive, ...) but also db providers, also someone requested work with [pass](http://www.passwordstore.org/). However it's possible, to make storage abstract. I've put it down to [Random Ideas page](https://github.com/antelle/keeweb/wiki/Random-Ideas), for now it needs much to be thinked over.
What's your opinion, how to support it? Just disable certain features not supported by driver, like colors? Or store them if format somehow (e.g. `pass` allow this, not sure about `vault`)?

**Comment by blaggacao** [comment]
vault is actually just middle ware, it's not the storage backed. vault implements some common back ends so far. Have a look here: https://github.com/hashicorp/vault/tree/master/physical

it does handle the sealing/unsealing of an api endpoint (connected to whatever backend you want)
just like keepass sealse/unseals it's own database format.

The difference is that this api is made for user and programmatic (distributed) consumption.

vault just implements a rest api where you can query values: 
```
$ vault write secret/hello value=world
Success! Data written to: secret/hello

$ vault read secret/hello
Key            	Value
lease_id       	secret/hello/f264a3d7-39e2-248a-eeb8-c45531d52d9c
lease_duration 	2592000
lease_renewable	false
value          	world
```

For a complete look and feel: https://www.vaultproject.io/#/demo/0

So this means any value can theoretically be mapped, but this would probably not be sensible and not what vault excels at. The best integration of those two worlds would be a plugin which allows building a subtree of the vault stored secrets (and they basically only do have those 5 fields from above). Through interaction with the api endpoint, the user could even create and invalidate secrets. 

The coolest feature is the keypass ssh-agent plugin (currently only for keepass standard), which would let you ssh around the world with the same certs that your infrastructure uses internally...

Alternatively, by simply connecting to vault as the main back end, we would have a quite reduced schema. But which is just right for the use case..

**Comment by antelle** [comment]
Yes this should be a plugin for desktop app which will be enabled somewhere in settings. On activation, it will allow connecting to Vault backend. Valut databases/storages creation should be not available in valut support mvp, only opening and usage.
I'll dig into it. Good that it's crossplatform and there'are clients for all OS. But support will happen after v1, not now.

**Comment by blaggacao** [comment]
that's really great to hear.

**Comment by antelle** [comment]
After several years, I'd say, we won't be able to support this. KDBX format is deeply integrated into the app and we're using quite a lot of features of it. Switching it to something else would require a massive rewrite, or even redesign.
