### ISSUE TITLE
Icons not showing correctly

### ISSUE THREAD

**Issue by Saboti** [keeweb/keeweb#471]
Hello,
I have downloaded the latest Keeweb Repo with:
git clone -b gh-pages https://github.com/keeweb/keeweb.git and host it with Apache2.

I now have the problem that the icons are Not displayed correctly.
[http://i.imgur.com/5mI9FQn.jpg](url)
Any idears? :-)

Regards Saboti

Thanks for taking the time to contribute!

Please, read https://github.com/keeweb/keeweb/wiki/FAQ before submitting a new issue and fill in the following (if applicable):

- what were your actions?
- what was wrong?
- app version
- your user-agent (from Settings/Help section)
- does it happen on Demo or New database?
- if you are using a test db without your personal data, please attach it
- please, open dev tools in your browser and attach output log from Console tab 
    (if you are using desktop app, devtools can be opened from Settings/General/Advanced)

**Comment by antelle** [comment]
Your Apache configuration seems to be invalid: it converts encoding and / or gives wrong content-type in the response. Things you can try:

- download HTML from your Apache and compare it with the original one (byte-by-byte)
- look on the response headers, especially encoding

**Comment by Saboti** [comment]
Hi @antelle, thank you gor the hint.
The chatset was wrong. I changed it to utf-8.
Now the Icons are showing correctly.

Regards Saboti
