### ISSUE TITLE
[Feature Request] Integration of other ciphers for keepass

### ISSUE THREAD

**Issue by mightyBroccoli** [keeweb/keeweb#472]
Is it possible to include the TwoFishCipher or the Serpant cipher eg. from the official plugins list for keepass? 
[Serpent Cipher](https://github.com/drizzt/KeePass-SerpentCipher) @drizzt

[TwoFishCipher](http://gogogadgetscott.info/keepass/twofishcipher/)

**Comment by antelle** [comment]
plugins are not supported for now...
