### ISSUE TITLE
Add a red flag when backup fails

### ISSUE THREAD

**Issue by benrubson** [keeweb/keeweb#475]
Hello,

When the database is saving, there is a progress icon near its name.

![screen shot 2016-12-21 at 08 24 52](https://cloud.githubusercontent.com/assets/6764151/21380902/8b2447ba-c758-11e6-9432-f08f74bbba7e.png)

Could it be possible for this icon to become a red circle if the backup fails ?

The problem is that for example, if we choose to make a backup "Every time the file is saved", and if the backup fails, it will silently fail.
Would then be nice to have a (non-blocking) red flag so that the user can then investigate.

(a simple case of a backup failing is setting a NAS volume as the target, without mounting it)

Thank you !

Ben

**Comment by benrubson** [comment]
Some news regarding this @antelle ?
Thank you very much 👍

**Comment by antelle** [comment]
Not yet indeed, once anything happens, you will see related commits/comments in this issue. Feel free to submit a patch though.

**Comment by benrubson** [comment]
_Closing this, feel free to re-open if really needed..._
