### ISSUE TITLE
Keeweb - online

### ISSUE THREAD

**Issue by hba-3380** [keeweb/keeweb#477]
KeeWeb v1.3.3 (52701af, 2016-09-20)
Environment: web
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.75 Safari/537.36

Hello - 
I have Keeweb - on your server and data and key on dropbox
I have 5 data files with the passwords - on dropbox
and i have 5 key files with the passwords for the data files.
It works perfect - untill this morning 
- only one data file i can open
on all other files i get error message:
- KdbxError:Error InvalidArg:data
Hope you can help me
I like your  work.
Thanks
Hermann

**Comment by antelle** [comment]
What happens if you remove the file and add it again?

**Comment by hba-3380** [comment]
Hello 
Then it work - thanks
pls close #477
what happens - i work now more than 4 weeks with it and never happens like this.
Thanks again
Hermann

24. Dezember 2016 12:19 Uhr, "antelle"  schrieb:
	What happens if you remove the file and add it again?

**Comment by jacobmischka** [comment]
This happened to me too, kept getting `InvalidArg: data` errors. Removing and readding the file did work. Thanks!
