### ISSUE TITLE
link from nextcloud opens Save As instead of Keeweb

### ISSUE THREAD

**Issue by rocky4546** [keeweb/keeweb#478]
Thanks for taking the time to contribute!

Please, read https://github.com/keeweb/keeweb/wiki/FAQ before submitting a new issue and fill in the following (if applicable):

- what were your actions?
This was on an initial install of nextcloud.  I have tries three times and I get different results from the same file.  Most times, it displays a save as box, but sometimes in specific locations, the *.kdbx file will open in KeeWeb.  I do have external storage enabled and have tried it there.  One time it worked, but in general, the saveas popup appears instead of going to KeeWeb.
- what was wrong?
I have look over the logs with debug turned on.   the data/nextcloud.log file does not enter any log when it is successful, but when it fails I will get
{"reqId":"lYP+ucdIm4AKoARicgpm","remoteAddr":"192.168.1.80","app":"PHP","message":"rewinddir(): 16 is not a valid Directory resource at \/home\/nextcloud\/apps\/files_external\/3rdparty\/icewind\/streams\/src\/Wrapper.php#31","level":0,"time":"2016-12-25T03:21:57+00:00","method":"GET","url":"\/nextcloud\/remote.php\/webdav\/KeePass\/abcdefgh.kdbx","user":"tmpuser","version":"11.0.0.10"}

- app version
I downloaded it today from this git which I believe is at 1.3.1

- your user-agent (from Settings/Help section)
User-Agent: Mozilla/5.0 (Windows NT 10.0; WOW64; rv:50.0) Gecko/20100101 Firefox/50.0

- does it happen on Demo or New database?
This is only for a new database.  Not sure where a nextcloud demo i can use

- if you are using a test db without your personal data, please attach it
- please, open dev tools in your browser and attach output log from Console tab 
    (if you are using desktop app, devtools can be opened from Settings/General/Advanced)
Console tab / all sub tabs are empty when clicking on the link

I guess my insanity is that it will work for a short and then stop working.  The exact same file in another folder will never work.  Thank you for your time.

**Comment by antelle** [comment]
How did you install keeweb to nextcloud? This should be posted to nextcloud-keeweb, I guess.

**Comment by rocky4546** [comment]
thanks for the reply.  I was confused with install since most install instructions indicated that the keeweb app was part of the apps folder in the nextcloud install and all you needed to do was enable it.  I did not find it in the folder, so I went to here, grabbed the release zip file and unpacked it into the general apps folder.  It then appeared in the app list and I enabled it.

A number of other items.  I am running Ubuntu 16.04. I also determined that nextcloud is somehow not updating the indexes correctly, so any new *.kdbx files are not launching KeeWeb.  If I run the following command, it fixes the indexes so KeeWeb works for all *.kdbx files in the data area.
sudo -u www-data php <nextcloudhome>/occ -vvv files:scan --all
Then lets say I download one of the files in the data area, use KeePass to update it and upload the new file with the same name.  That file now will do the SaveAs and not launch KeeWeb until the command is run to fix the indexes.  The log does not have any errors on the upload, so it looks like the upload is fine.  So the workaround to fix the index bug which stops KeeWeb from launching is to cronjob the command above often to fix these issues.

On one other strange topic, I do have the external storage turned on.  In that area, I have four files in two different folders.  One of the four files launches KeeWeb while the other three do not.  The above command does nothing to fix external storage files even though they are listed on its output.  If all did not work, I would be fine, but to have one work and the others do the SaveAs is confusing as well as the occ command listing that it fixed them when that command had no effect.

**Comment by antelle** [comment]
keeweb itself is not integrated with nextcloud, this is a wrong project to post this issue. most probably you're looking for https://github.com/jhass/nextcloud-keeweb

**Comment by rocky4546** [comment]
Trying to stick to the single issue, but wanted to state what the goal is.  I am trying to have multiple accounts be able to modify and update the *kdbx file.  One way is to have the file on the External Storage.  This is simple, but in general does not seem to be able to use the KeeWeb (except for one case which may break at any time).  The other way is to use the "share" ability.  When I share the file and then go to the other user account (user2) and use KeeWeb, when the update is saved, the share link breaks.  User2 has the updated file and shows not shared and the main user still says the file is shared, but does not have the update. So it looks like sharing with edit enabled does not work.
