### ISSUE TITLE
Change Browser, fill the app key again?

### ISSUE THREAD

**Issue by Argado** [keeweb/keeweb#481]
I try to open my database that stored in dropbox, but if i want open from another browser in one computer or in another computer, it's always need to fill the dropbox app key again.

I think, i can just open the url of my keeweb self hosted, and fill the password.

What's the problem?

I try to use config.json, but there is appear:
Error Loading App.
There was an error loading app settings. Please double check app url or contact your administrator.

I not change anything [https://github.com/keeweb/keeweb/blob/develop/util/config-example.json](url) except line 31 and 32 and uploaded it to my server.

**Comment by antelle** [comment]
What's there in the console?
