### ISSUE TITLE
AutoType global shortcut not working

### ISSUE THREAD

**Issue by saksmt** [keeweb/keeweb#482]
- what were your actions?
Open entry, switch focus to other app, hit `Shift` + `Alt` + `T`

- what was wrong?
Nothing happens

- app version
KeeWeb v1.3.3 (52701af, 2016-09-20)
Environment: electron v1.3.3
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) KeeWeb/1.3.3 Chrome/52.0.2743.82 Electron/1.3.3 Safari/537.36

- logs
Empty

- description
I have wm-wide shortcut for switchning layout (`Shift` + `Alt`), so seems like KeeWeb receives only `T` in random language. Also in-app shortcut (`Ctrl` + `T`) works just fine

**Comment by antelle** [comment]
a possible solution is #348

**Comment by mindsolve** [comment]
The problem is, this is a _**new**_ bug!
I am using KeeWeb for about 5 months, and I love the autotype shortcut, but like a week ago the same as above happened (nothing to be correct) but after restarting KeeWeb (and/or the computer) the issue temporarily disappeared.
Today the shortcut doesn't work again.
**App version:**
```
KeeWeb v1.3.3 (52701af, 2016-09-20)
Environment: electron v1.3.3
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) KeeWeb/1.3.3 Chrome/52.0.2743.82 Electron/1.3.3 Safari/537.36 
```
**System:**
`Ubuntu 16.10 x64, latest updates installed.`

**Comment by antelle** [comment]
@mindsolve this is weird, because the app seems to handle shortcuts correctly, the issue is linux-specific, somehow the shortcuts are not handled...

**Comment by akroii** [comment]
Same here, i am using keeweb on a mac.
when i press shift + alt + t nothing happends

**Comment by xilef6000** [comment]
@antelle Today I was finally able to recreate the error, and it looks like it's some kind of problem in KeeWeb, _not_ the system. 
This is the log: (I tried the shortcut 3 times)

```
2017-01-28T16:15:26.534Z [auto-type] Auto type event null
2017-01-28T16:15:26.535Z [auto-type] Already running, skipping event
2017-01-28T16:15:37.250Z [auto-type] Auto type event null
2017-01-28T16:15:37.250Z [auto-type] Already running, skipping event
2017-01-28T16:16:03.634Z [auto-type] Auto type event null
2017-01-28T16:16:03.635Z [auto-type] Already running, skipping event
```

Do you have any idea what the problem might be?
Can I help you in any way finding the problem?

**Comment by antelle** [comment]
@xilef6000 it looks like previous auto-type has not completed normally, does this happen on the first time you open keeweb? are there any logs before it?

**Comment by mindsolve** [comment]
@antelle Now (finally) I could reproduce this behavior!
```
[INFO ] 2017-02-16T19:41:37.961Z [open:Keeys] File open request
[INFO ] 2017-02-16T19:41:37.964Z [open:Keeys] Open file from storage file
[INFO ] 2017-02-16T19:41:37.965Z [open:Keeys] Stat file
[DEBUG] 2017-02-16T19:41:37.966Z [storage-file] Stat /home/felix/Dokumente/KeePass/Keeys.kdbx
[DEBUG] 2017-02-16T19:41:37.966Z [storage-file] Stat done /home/felix/Dokumente/KeePass/Keeys.kdbx 0ms
[INFO ] 2017-02-16T19:41:37.967Z [open:Keeys] Open file from storage (1487184881973, local 1487184881973)
[INFO ] 2017-02-16T19:41:37.967Z [open:Keeys] Load from storage
[DEBUG] 2017-02-16T19:41:37.967Z [storage-file] Load /home/felix/Dokumente/KeePass/Keeys.kdbx
[DEBUG] 2017-02-16T19:41:38.009Z [storage-file] Loaded /home/felix/Dokumente/KeePass/Keeys.kdbx 1487184881973 42ms
[INFO ] 2017-02-16T19:41:38.010Z [open:Keeys] Open file from content loaded from storage
[INFO ] 2017-02-16T19:41:40.130Z [file] Opened file Keeys: 2063ms, 3910912 rounds, 230 kB
[DEBUG] 2017-02-16T19:41:40.132Z [app] Add last open file 2b90649b-a7d8-329a-67a9-24d2be177eea Keeys file /home/felix/Dokumente/KeePass/Keeys.kdbx 1487184881973
[DEBUG] 2017-02-16T19:41:40.433Z [storage-file] Watch dir /home/felix/Dokumente/KeePass
[DEBUG] 2017-02-16T19:41:44.351Z [auto-type] Auto type event 
[DEBUG] 2017-02-16T19:41:44.354Z [auto-type] Get window title
[INFO ] 2017-02-16T19:41:44.407Z [launcher] spawn xdotool: 0, 52ms
SpardaNet-Banking - Google Chrome
[DEBUG] 2017-02-16T19:41:44.408Z [auto-type] Window title SpardaNet-Banking - Google Chrome 
[DEBUG] 2017-02-16T19:41:44.420Z [auto-type] Hide window
[DEBUG] 2017-02-16T19:41:44.423Z [auto-type] Start {USERNAME}{TAB}{PASSWORD}{ENTER}
[DEBUG] 2017-02-16T19:41:44.426Z [auto-type] Parsed [op:USERNAME,op:TAB,op:PASSWORD,op:ENTER]
[DEBUG] 2017-02-16T19:41:44.427Z [auto-type] Resolved [**********,key:tab,,key:enter]
[INFO ] 2017-02-16T19:41:44.622Z [launcher] spawn xdotool: 0, 193ms
[INFO ] 2017-02-16T20:11:31.336Z [sync:Keeys] Sync started file /home/felix/Dokumente/KeePass/Keeys.kdbx [object Object]
[INFO ] 2017-02-16T20:11:31.340Z [sync:Keeys] Stat file
[DEBUG] 2017-02-16T20:11:31.340Z [storage-file] Stat /home/felix/Dokumente/KeePass/Keeys.kdbx
[DEBUG] 2017-02-16T20:11:31.341Z [storage-file] Stat done /home/felix/Dokumente/KeePass/Keeys.kdbx 1ms
[INFO ] 2017-02-16T20:11:31.341Z [sync:Keeys] Stat found same version, not modified
[INFO ] 2017-02-16T20:11:31.342Z [sync:Keeys] Sync finished no error
[INFO ] 2017-02-16T20:41:31.335Z [sync:Keeys] Sync started file /home/felix/Dokumente/KeePass/Keeys.kdbx [object Object]
[INFO ] 2017-02-16T20:41:31.338Z [sync:Keeys] Stat file
[DEBUG] 2017-02-16T20:41:31.338Z [storage-file] Stat /home/felix/Dokumente/KeePass/Keeys.kdbx
[DEBUG] 2017-02-16T20:41:31.339Z [storage-file] Stat done /home/felix/Dokumente/KeePass/Keeys.kdbx 0ms
[INFO ] 2017-02-16T20:41:31.339Z [sync:Keeys] Stat found same version, not modified
[INFO ] 2017-02-16T20:41:31.339Z [sync:Keeys] Sync finished no error
[INFO ] 2017-02-16T21:11:31.335Z [sync:Keeys] Sync started file /home/felix/Dokumente/KeePass/Keeys.kdbx [object Object]
[INFO ] 2017-02-16T21:11:31.338Z [sync:Keeys] Stat file
[DEBUG] 2017-02-16T21:11:31.339Z [storage-file] Stat /home/felix/Dokumente/KeePass/Keeys.kdbx
[DEBUG] 2017-02-16T21:11:31.339Z [storage-file] Stat done /home/felix/Dokumente/KeePass/Keeys.kdbx 0ms
[INFO ] 2017-02-16T21:11:31.339Z [sync:Keeys] Stat found same version, not modified
[INFO ] 2017-02-16T21:11:31.339Z [sync:Keeys] Sync finished no error
[DEBUG] 2017-02-16T21:36:17.681Z [auto-type] Auto type event 
[DEBUG] 2017-02-16T21:36:17.682Z [auto-type] Already running, skipping event
[DEBUG] 2017-02-16T21:36:21.833Z [auto-type] Auto type event 
[DEBUG] 2017-02-16T21:36:21.833Z [auto-type] Already running, skipping event
[DEBUG] 2017-02-16T21:36:41.392Z [auto-type] Auto type event 
[DEBUG] 2017-02-16T21:36:41.392Z [auto-type] Already running, skipping event
```

**Comment by antelle** [comment]
Gotcha: you have empty password. Fixed, uploaded to [beta.keeweb.info](https://beta.keeweb.info).

**Comment by mindsolve** [comment]
Yayyy! I am so happy you could finally find this nasty bug!As a workaround:Custom Auto-Type (for entries with empty fields) to only type the field that is filled.For example: {password} not {username}{tab}{password} (where username is empty) 
This should work, right?
-------- Ursprüngliche Nachricht --------Von: antelle <notifications@github.com> Datum: 16.02.17  23:15  (GMT+01:00) An: keeweb/keeweb <keeweb@noreply.github.com> Cc: "Felix E." <info@feli.ga>, Mention <mention@noreply.github.com> Betreff: Re: [keeweb/keeweb] AutoType global shortcut not working (#482) 
Gotcha: you have empty password. Fixed, uploaded to beta.keeweb.info.

**Comment by antelle** [comment]
Exactly, this should work. But it's very unobvious...

**Comment by saksmt** [comment]
@antelle, I hope that you won't stop on fixing this one and also fix original one (related to handling of keyboard-events in linux env) :)

**Comment by antelle** [comment]
Wasn't the original issue the same?

**Comment by antelle** [comment]
I see now, it's a bit different. It's not possible to fix it, the only way is #348.

**Comment by saksmt** [comment]
@antelle, well at least it would work somehow :) So waiting for it to be implemented.

**Comment by dploeger** [comment]
For anybody else who came across this, I'll put that here:

For me, Keeweb not reacting to global shortcuts was simply that the system lacked the "xdotool". So just go ahead and run

`apt install xdotool`(on Debian-ish)

and it worked. 😄
