### ISSUE TITLE
[FeatureRequest] Ability to change shortcuts

### ISSUE THREAD

**Issue by saksmt** [keeweb/keeweb#483]
It's really awkward when exist collision between user-defined system shortcut and KeeWeb shortcuts. It leads to following (#482)

**Comment by antelle** [comment]
duplicate of #348

**Comment by saksmt** [comment]
@antelle, That issue already closed and also mention auto-type, so I've opened this one

**Comment by antelle** [comment]
> That issue already closed

no, it's open
basically it is for auto-type...

**Comment by saksmt** [comment]
@antelle Sorry, missed that it was open
