### ISSUE TITLE
Where i locate and load config.json file?

### ISSUE THREAD

**Issue by hepf68** [keeweb/keeweb#485]
Hi everyone,

I want load a config.json using the ?config=config.json Ex: http://MYSERVERIP/?config=config.json.

I used and changed the sample config-sample.json file and put on the site root.

When i try to load the file appears that message:

Error loading app
There was an error loading app settings. Please double check app url or contact your administrator.

What i'm doing wrong?

PS: I'm using the latest versing of keeweb

Best regards :)

Hugo F.

**Comment by sainaen** [comment]
@hepf68 
Can you check the console in your browser for details? It [should](https://github.com/keeweb/keeweb/blob/master/app/scripts/models/app-model.js#L60) print an actual status text there.

Also, on the Network tab you can check out an actual request for the config file that KeeWeb is doing to verify that URL is correct.

**Comment by hepf68** [comment]
@sainaen It was a file permissions :) Now, i can load config.json without problems :). Thank you 🗡 
It is possible load a local or network Database file with config.json?
I want use a DB file located on another or in NAS accessible by my internal network. If it's not possible i want load a local DB file where i have keeweb deployed in IIS

Best Regards,

Hugo F

**Comment by sainaen** [comment]
@hepf68 
Great!

Sorry, I don't know much about config file, I use KeeWeb only locally. There's an example though for loading WebDAV (which is probably supported by your NAS) file in the wiki: [JSON app config](https://github.com/keeweb/keeweb/wiki/Configuration#json-app-config) (look for the `files` section of config.)

**Comment by antelle** [comment]
@sainaen  👍  yes, it's available with WebDAV setting. You can specify there either absolute, or relative path
