### ISSUE TITLE
Single shortcut for ⌘A ⌘F (all item search)

### ISSUE THREAD

**Issue by aragos** [keeweb/keeweb#488]
Search limits itself to the currently selected category when triggered through the search keyboard shortcut (⌘F). In my case I always want to search all items but this requires two shortcuts in succession: ⌘A ⌘F. It would be great if there was a single shortcut that achieved both, for example ⌘ + Shift + F.

KeeWeb v1.3.3 (52701af, 2016-09-20)
Environment: electron v1.3.3
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_2) AppleWebKit/537.36 (KHTML, like Gecko) KeeWeb/1.3.3 Chrome/52.0.2743.82 Electron/1.3.3 Safari/537.36

**Comment by antelle** [comment]
Just hit ⌘A and start typing.
