### ISSUE TITLE
[Feature request] Always show certain custom fields

### ISSUE THREAD

**Issue by quassy** [keeweb/keeweb#494]
I regularly add the same custom field to my entries (the e-mail address used for registration). It'd be handy if one could sticky a certain custon field so it gets displayed on all entries without having to manually add it every time.

```
KeeWeb v1.3.3 (52701af, 2016-09-20)
Environment: electron v1.3.3
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) KeeWeb/1.3.3 Chrome/52.0.2743.82 Electron/1.3.3 Safari/537.36
```

**Comment by antelle** [comment]
This will be possible later with entry templates, so kinda duplicate of #112

**Comment by antelle** [comment]
Looks like exact the same as #112, closing as duplicate
