### ISSUE TITLE
[Feature Request] kdbx4 file format support

### ISSUE THREAD

**Issue by karrots** [keeweb/keeweb#495]
Add support for KDBX4.

http://keepass.info/help/kb/kdbx_4.html

**Comment by antelle** [comment]
That's a good point.
Good news is that I'm working on it, please see #326 and https://github.com/keeweb/kdbxweb/projects/1 for details.
Most parts are already done, I hope to return to it in the nearest couple of weeks and make it happen.

**Comment by karrots** [comment]
Ah sorry about that I did a issue search first. Must be case sensitive.
