### ISSUE TITLE
Add support for Argon2 and ChaCha20 to conform with KDBX v4

### ISSUE THREAD

**Issue by xenithorb** [keeweb/keeweb#496]
- what were your actions?

Opening a KDBX v4 database that utilized Argon2 and ChaCha20

- what was wrong?
```txt
KdbxError: Error InvalidVersion
```
- app version

```txt
KeeWeb v1.3.3 (52701af, 2016-12-17)
Environment: web
User-Agent: Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:50.0) Gecko/20100101 Firefox/50.0
```

- if you are using a test db without your personal data, please attach it

Just make a new one with version 2.35 of the official keepass client

----

Hopefully this can be used to track efforts on getting the new database format supported

**Comment by antelle** [comment]
please make a quick search for kdbx4 in issues
