### ISSUE TITLE
Import CSV files

### ISSUE THREAD

**Issue by pedrosimao** [keeweb/keeweb#498]
It would be great to be able to import CSV files.

**Comment by carlowahlstedt** [comment]
It seems this issue and [Import LastPass](https://github.com/keeweb/keeweb/issues/453), which is CSV, would be the same thing?

**Comment by antelle** [comment]
Yes, sure it's the same

**Comment by ashishpatel1992** [comment]
Any update on import csv feature?

**Comment by antelle** [comment]
Deployed to [beta.keeweb.info](https://beta.keeweb.info), will be available in the next release.

<img width="1028" alt="Screen Shot 2019-09-25 at 23 25 46" src="https://user-images.githubusercontent.com/633557/65641008-f60f0980-dfeb-11e9-8cbb-d784fc24d067.png">

**Comment by fuzepod** [comment]
Where is the option at beta.keeweb.info?

**Comment by antelle** [comment]
XML and other import types are now hidden. To use it, select a CSV file using Open button or drag it to the open screen.

**Comment by fuzepod** [comment]
My Google Drive file doesn't show up, only "New File" and there is only a cancel button in the bottom right, no import button

**Comment by antelle** [comment]
Import from Google Drive is not possible, only from a local file.

**Comment by fuzepod** [comment]
![image](https://user-images.githubusercontent.com/41087722/65803425-895f5080-e14c-11e9-979e-0244721d8af7.png)
Ok so I downloaded the keepass file off google drive and it still wont let me select it for csv import

**Comment by antelle** [comment]
Oh you mean this thing? Now I see, I thought you wanted to select a CSV file from Google Drive an open it using Google Drive button. What you actually asking, is how to import entries from CSV into a kdbx file stored in Google Drive, right? To be able to do it, you need to open your kdbx file in KeeWeb first, then click Open/New and select/drag a CSV there. Then you should be able to select your kdbx file and group inside it as a target. Looks like Import button is hidden because of layout issues, if you make your window a bit bigger you should be able to see it. I'll look into it.

**Comment by fuzepod** [comment]
Ok that worked. The button issue also seems to be a layout problem, I had to expand the window across two 1080p monitors to click it. Thanks for the help.

**Comment by fuzepod** [comment]
Update: Not sure if this is due to a large CSV file, but I could only import once I downloaded the file locally and reuploaded it to google drive. When I import it directly to google drive it was stuck syncing for 3 hours. Downloading and reuploading took 1 minute

**Comment by antelle** [comment]
This looks like just some sync issues. Does it reproduce? If so, please provide steps, I'll look into it.
If a file is really that large to take hours to sync, you're doing it wrong, but I guess, it's not the case and most likely it contains no more than 100 records.

**Comment by antelle** [comment]
@fuzepod width is fixed, now the table will be scrollable.

**Comment by andremann** [comment]
This worked like a charm, however the password field imported from the CSV field behaves as a string type. The passwords in fact are revealed by default, nor it is possible to hide them. 
Also, the generate icon, although displayed on the password field on the right, triggers nothing when clicked.

**Comment by antelle** [comment]
Thanks! Moved it here: https://github.com/keeweb/keeweb/issues/1391
