### ISSUE TITLE
Default setting for key encryption rounds pretty low.

### ISSUE THREAD

**Issue by FlxVctr** [keeweb/keeweb#502]
At the moment the standard setting is at the keepass default of 6000 which is too low for a modern CPU imho. E.g. keepassx's benchmark suggests a value of over 13 * 10**6 rounds for a not so new MacBook Air.

**Comment by antelle** [comment]
It makes sense, to set this time to ≈100ms. But 'rounds' is getting obsolete, with new KDBX4 format and Argon2 KDF, there are more parameters to adjust, rather than one 'rounds'. So I think, we can leave rounds as it it.

**Comment by gnu-user** [comment]
@antelle Just reviewed a paper highlighting some recent attacks on Argon2i, the abstract states that for the attack to fail there must be more than 10 rounds. Given that Argon2i has only been around for a number of years it may be worthwhile to consider increasing the number of rounds to a tolerable default amount that provides future-proof security against other attacks.

The following is the cryptanalysis paper: https://eprint.iacr.org/2016/759.pdf

**Comment by antelle** [comment]
Hm, 10 rounds? That's pretty low, we have much more. Is this number correct?

**Comment by gnu-user** [comment]
That's based on the paper, the default is 6,000. I've seen it mentioned in other issues, it may be best to add support for a simple benchmark that runs a test and then determines the appropriate number of rounds so that the computation time is ~100ms.

**Comment by antelle** [comment]
yep, that's what this issue about :)
