### ISSUE TITLE
New translation items

### ISSUE THREAD

**Issue by Loilo** [keeweb/keeweb#503]
OneSky emailed me about new phrases to translate.
Sadly using beta mode from advanced settings doesn't work at the moment and I can't figure out the possible context for every item.

Could you provide a beta version to look throught if there is one? Or should we just comment those phrases with "context please" and wait for screenshots?

**Comment by antelle** [comment]
I'm uploading them now...

**Comment by antelle** [comment]
done

**Comment by Loilo** [comment]
Oh. And I also had to change my KeeWeb language to English, that made it work. 😅

**Comment by antelle** [comment]
It didn't start in german?

**Comment by antelle** [comment]
Found the error, thanks for the report, I'll fix it now.

**Comment by Loilo** [comment]
Activating the beta only showed a blank page. Then I tried [beta.keeweb.info](https://beta.keeweb.info) and got an error in the console:

```
Cannot find module './de-DE.json
```

It somehow worked in a private browser window though. Thought it was about the language but actually the private window was in German too. Whatever.
But that got me the idea to change KeeWeb language to English and that got the Beta working for me. (Even if *that* was in Germain again. 🙃)

**Comment by antelle** [comment]
Fixed, deployed to beta. Thanks!

**Comment by antelle** [comment]
Now we set the language automatically by browser language, that was the reason. So, if your browser is set to `de`, it will be German.

**Comment by Loilo** [comment]
Aaaand now after restarting KeeWeb, the normal version doesn't work anymore – blank page, like in the beta before. 🙈

Well, risks of using beta, I'll just reinstall the app.

**Comment by antelle** [comment]
Oh, you loaded beta inside the app. Yes, language names have been changed, so it will refuse to start in this case :expressionless:

**Comment by Loilo** [comment]
It does, even after reinstall. Well probably I should just clear the Application Support folder.

**Comment by antelle** [comment]
Yes, it's stored in settings json inside Application Support/KeeWeb.

**Comment by Loilo** [comment]
Yep, changed it to "en", all good now. 👍

**Comment by antelle** [comment]
The new release should happen this or next week, so hopefully, this issue with beta will not affect many users.
