### ISSUE TITLE
[Feature request] Autocomplete should be accessible by keyboard

### ISSUE THREAD

**Issue by Loilo** [keeweb/keeweb#504]
We have a really useful user name autocompletion feature since 1.1, but what annoys me from time to time is that I always get the correct username suggested but cannot select it via keyboard (or it's not documented how to do it). It's especially frustrating because I can get to work any other step for creating a new password exclusively per keyboard.

In case there isn't implemented keyboard access yet, I'd suggest to either use up / down keys for selecting them or directly picking them with `Ctrl + 1`, `Ctrl + 2`, ...

**Comment by antelle** [comment]
Deployed to [beta.keeweb.info](https://beta.keeweb.info), will be available in the next release.
