### ISSUE TITLE
App seems to have been updated, but still shows old version.

### ISSUE THREAD

**Issue by vahotm** [keeweb/keeweb#507]
I updated from 1.3.3 to 1.4.0, restarted the app - and it still shows 1.3.3 in "About" window. In  settings however it says, that I have the most recent version.

KeeWeb v1.4.0 (c651343, 2017-02-04)
Environment: electron v1.3.3
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_2) AppleWebKit/537.36 (KHTML, like Gecko) KeeWeb/1.3.3 Chrome/52.0.2743.82 Electron/1.3.3 Safari/537.36

**Comment by antelle** [comment]
About window cannot be updated, it's stored in app plist which is not writable. So, not an issue. To get a new version there, download a new build from releases.
