### ISSUE TITLE
Dragging entries between files (databases) does not work

### ISSUE THREAD

**Issue by johannesjh** [keeweb/keeweb#508]
I expected a function to move entries between databases. I tried dragging entries and found that dragging is possible between groups, but not between databases. I am not sure if this is a bug or a feature request?

- what were your actions?
  I opened two files (kdbx databases)
  I then tried to drag-and-drop an entry from one database to another

- what was wrong?
  I expected to be able to move entries between databases.
  But the entries stay in the same database (nothing changes).

- app version
  1.4.0

- your user-agent (from Settings/Help section)
  Desktop app on Mac OS Sierra

- does it happen on Demo or New database?
  yes, both when dragging from demo to new database, as well as when dragging between two new databases.

- if you are using a test db without your personal data, please attach it
[Test databases.zip](https://github.com/keeweb/keeweb/files/752986/Test.databases.zip)

**Comment by antelle** [comment]
Feature request, dup: #336
