### ISSUE TITLE
"no last-modified header" when I try to use webdav

### ISSUE THREAD

**Issue by barghest** [keeweb/keeweb#511]
Hey,
I'm using the Windows as well as the Linux Desktop client (1.4.0) and I try to load my existent keepass file that is stored on a webdav share but I receive the following message:

Error: no last-modified header (console output: no headers)

With kepass2android and keepass2 the file is usable without any problems.

User-Agent: Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) KeeWeb/1.4.0 Chrome/53.0.2785.143 Electron/1.4.15 Safari/537.36

Thanks in advance!

**Comment by antelle** [comment]
Just add this header.

**Comment by barghest** [comment]
Sorry for the dumb question, but how do I "add this header"?
It's a managed webdav from my mail provider. Do you have any additional information that I can send to him?

**Comment by antelle** [comment]
If it's a public server, and you don't have access to it, then it will not be possible to use this server with keeweb.

**Comment by barghest** [comment]
Oh, too bad :(

Is there any chance that this will be changed? Or, just for my understanding, why is this a problem (since it works in Keepass2 and Keepass2Android)?

**Comment by antelle** [comment]
We're not going to fix it at the moment.
Other apps don't have a feature of continuous synchronization, that's why it's more crucial for keeweb to have this header.

**Comment by matecode** [comment]
Same problem. I use a safe mail provider in germany, https://mailbox.org ... I expect this is exatly the target group for keepass ergo keeweb.

**Comment by youyou015** [comment]
I also encounter this issue, @antelle what do you mean "Just add this header"? Add what files to where? I'm using a private webdav server, thanks.

**Comment by antelle** [comment]
@youyou015 you can add it on the server. If you're using a public server, and it doesn't support this header, it's not possible to use keeweb with this server.

**Comment by akki42** [comment]
I'm also encountering this issue / error message; however, my (shared hosting) server does seem to send a last-modified header. A `curl -v` output for the kdbx-file shows:

```
> GET /nextcloud/remote.php/webdav/Test.kdbx HTTP/1.1
> Authorization: Basic ###key###
> User-Agent: curl/7.37.0
> Host: host.domain
> Accept: */*
> 
* SSLv2, Unknown (23):
{ [data not shown]
< HTTP/1.1 200 OK
< Date: Tue, 25 Jul 2017 18:31:38 GMT
* Server quarxConnect.de HTTPd is not blacklisted
< Server: quarxConnect.de HTTPd
< Expires: Thu, 19 Nov 1981 08:52:00 GMT
< Cache-Control: no-store, no-cache, must-revalidate
< Pragma: no-cache
< X-Frame-Options: SAMEORIGIN
< Content-Security-Policy: default-src 'none';
< Content-Disposition: attachment; filename*=UTF-8''Test.kdbx; filename="Test.kdbx"
< OC-ETag: "c92d34a3dd6b6c404abb01dbccf3b7d9"
< Set-Cookie: oc_sessionPassphrase=###passphrase###; path=/nextcloud; secure; HttpOnly
< Set-Cookie: nc_sameSiteCookielax=true; path=/nextcloud; httponly;secure; expires=Fri, 31-Dec-2100 23:59:59 GMT; SameSite=lax
< Set-Cookie: nc_sameSiteCookiestrict=true; path=/nextcloud; httponly;secure; expires=Fri, 31-Dec-2100 23:59:59 GMT; SameSite=strict
< Set-Cookie: ###cookie###; path=/nextcloud; secure; HttpOnly
< Set-Cookie: cookie_test=test; expires=Tue, 25-Jul-2017 19:31:38 GMT; Max-Age=3600
< Last-Modified: Tue, 25 Jul 2017 18:21:39 GMT
< ETag: "c92d34a3dd6b6c404abb01dbccf3b7d9"
< Content-Length: 6398
< Vary: Accept-Encoding
< X-Content-Type-Options: nosniff
< X-XSS-Protection: 1; mode=block
< X-Robots-Tag: none
< X-Download-Options: noopen
< X-Permitted-Cross-Domain-Policies: none
< Content-Type: application/octet-stream
```

Any idea what's missing?

**Comment by antelle** [comment]
I guess, it doesn't allow to access this header to other website (CORS policy).
You can try to inspect the request sent by keeweb and see what's there.

**Comment by lodart** [comment]
I have a private server with Nextcloud, but I don't know how to add the "last-modified header" ? Is there a tuto or something ?

**Comment by antelle** [comment]
@lodart it's more about nextcloud config

**Comment by SISolutions** [comment]
i have the same problem!
trying to use Keeweb 1.6.1 webdav to save my db but i have this error. 
Also i see that no one cares about it from the Nextcloud side of course. Generally most of their apps are dysfunctional and with a lot of problems unfortunately

**Comment by lodart** [comment]
Okay, I'm just dumb. In the URL field, I just put the URL of my Webdav server, expecting a popup window that could allow me to select my kdbx file. I just realised I had to put the full URL with the `path/to/the/file`. Like that : `https://nextcloudServer.com/remote.php/webdav/Documents/passwords.kdbx`
Hope it will help

**Comment by salmanchan** [comment]
same problem on KeeWeb for mac Version 1.6.3,  can you fix it? thank you

**Comment by antelle** [comment]
This cannot be fixed, it's about server config. Without last-modified info we won't be able to decide if the file on server is older of newer than us.

**Comment by guzheyuan** [comment]
Same problem :(

**Comment by antelle** [comment]
Basically, there's no point to discuss or report this issue, it won't be fixed. 
For future readers: if you're here because it repeats for you, please fix your server. If it's not your server, it can't be used with KeeWeb.
