### ISSUE TITLE
Menu broken in Mac desktop client

### ISSUE THREAD

**Issue by jouml** [keeweb/keeweb#512]
Hey,
the menu in the menu bar of the Mac desktop client is broken in 1.4.0.
Menu entries are hidden (keyboard shortcuts are visible), cmd-Q is inactive and doesn't quit.

- your user-agent (from Settings/Help section)
KeeWeb v1.4.0 (c651343, 2017-02-04)
Environment: electron v1.2.1
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) KeeWeb/1.2.0 Chrome/51.0.2704.63 Electron/1.2.1 Safari/537.36

nothing of interest in the logs

Thanks!

**Comment by antelle** [comment]
Hi, could you please test it in fresh version on keeweb? It works ok for me.

**Comment by jouml** [comment]
After fresh install everything is fine. Thanks!
