### ISSUE TITLE
Argon2 memory limitation

### ISSUE THREAD

**Issue by Matthaiks** [keeweb/keeweb#513]
Database cannot be opened if Argon2's memory is set too high (e.g. 160 MB).

Error message:
`abort("Cannot enlarge memory arrays. Either (1) compile with  -s TOTAL_MEMORY=X  with X higher than the current value 134217728, (2) compile with  -s ALLOW_MEMORY_GROWTH=1  which adjusts the size at runtime but prevents some optimizations, (3) set Module.TOTAL_MEMORY to a higher value before the program runs, or if you want malloc to return NULL (0) instead of this abort, compile with  -s ABORTING_MALLOC=0 ")`

KeeWeb v1.4.0 (c651343, 2017-02-04)
Environment: web
User-Agent: Mozilla/5.0 (Windows NT 6.3; Win64; x64; rv:51.0) Gecko/20100101 Firefox/51.0

**Comment by antelle** [comment]
Future: a bit tricky to fix. Please note that you can achieve the same level of computational difficulty by tweaking other argon2 parameters.

**Comment by YellowOnion** [comment]
@antelle the entire point of high memory usage is to protect against GPU cracking, an 8GB card with 512MB scratch pad size with 5 rounds is only 16 threads, if I drop it down to 2MB and 1000 rounds, I'm still just as fast on a CPU, but now I can run 4,096 threads on the GPU getting closer to saturating the SIMD units and getting an order of magnitude speed up.

**Comment by antelle** [comment]
@YellowOnion argon2 is designed in such way that you cannot run it in more threads than you specify. I.e. cycles depend on each other and you will no be able to split it to 4096 threads to run it on GPU in parallel.
For now, there's a memory limitation, I don't see any possible way to change it. Also, threads are not implemented (but they're planned in wasm).

**Comment by YellowOnion** [comment]
@antelle You're misunderstanding how GPU brute forcing works, A GPU does a map over an array of password guesses, and spits out an array of keys/solutions. Nothing is stopping you from running two completely separate instances at the same time if you have an extra thread or two and enough memory for the instance, and when GPUs have 8GB of memory, and 64 wide SIMD units, and 64 units onboard, and then you can rent a bunch of EC2 instances on top of that, you can see why GPUs are a threat to low entropy passwords, that use little amount of memory.

**Comment by antelle** [comment]
@YellowOnion I thought you mean that you can run one round of Argon2 in parallel, but you're talking about another thing. Of course, you can run it on GPU this way. But it will be 8gb / memory, which gives you about 50 threads. If the round setting is quite high, it's still not that bad.
Btw, I see that wasm can use 1-2 gb nowadays, which is already better compared to what we have now, I'll check if it's possible to use it. However it won't be possible support more than that until it's implemented in wasm.

**Comment by antelle** [comment]
Pushed support of Argon2 up to ≈2GB, you can test it on [beta.keeweb.info](https://beta.keeweb.info), will be available in the next release.

**Comment by YellowOnion** [comment]
How are you doing wasm?

I see that libsodium.js exists and targets wasm.

**Comment by antelle** [comment]
This way: https://github.com/keeweb/keeweb/blob/master/app/scripts/util/kdbxweb-init.js#L22
It still contains asm.js fallback, it will be removed soon, as now all modern browsers support wasm.
And here's argon2 wasm module: https://antelle.github.io/argon2-browser/

**Comment by antelle** [comment]
So, now it's released and can use up to 2GB memory. Let's keep it open, to wait for x64 memory in WASM, which is not available now.
