### ISSUE TITLE
WebDAV : write to temp then move causes error on webdav server

### ISSUE THREAD

**Issue by Gruck** [keeweb/keeweb#514]
Hi,

I am currently trying to set up KeeWeb 1.4 desktop app using WebDAV exposed by our Atlassian Confluence instance.

Confluence is used in our team to share knowledge, so why not kdbx ? I attached the kdbx to a confluence page. It is then accessible through WebDAV.

Then, if i try to edit an entry in keeWeb and save, it seems the client first writes to a temp file, ".<filename>.<randominteger>", then attemps to MOVE that file to the destination.

Confluence is not quite happy with this but fails silently, no error what so ever, but subsequent HEAD on file by keeweb lead to 404 Not Found... In Confluence User Interface, i can see the file upload time changed, but it looks like it is more of a delete/upload than a newer version of the file.

Is it not easier to PUT the update kdbx instead of writing a temp file and moving it ? Is this optimization a standard when it comes to WebDav ?

Thanks in advance :)

**Comment by antelle** [comment]
Yes, this is a standard way to write files, e.g. macOS writes files in this way to webdav.
We might consider creating a setting deep in advanced settings, that will control this. If it's really stopping you, you can contribute that code and it will be included in the next version on keeweb. But please keep in mind that it might cause file overwriting and inconsistent states, depending on server software used.

**Comment by Gruck** [comment]
Hi,

Thanks for your fast answer.
As of today, i am not sure i could implement such a feature. But i'll keep on reading.
In the case of my webdav server, i want overwriting, for WebDav server watches such changes at stores the new version accessible through web interface.
 Cheers :)

**Comment by NP-Hardass** [comment]
Worth noting, KeePass has an option in the "Advanced" tab, "File Input/Output Connections" section called "Use file transactions for writing databases."  When I use KeePass over WebDAV (Apache), I also have to disable that, both in KeePass and KeePass2Android.

**Comment by antelle** [comment]
Yes, we should create an option like that.

**Comment by antelle** [comment]
Deployed to [beta.keeweb.info](https://beta.keeweb.info), will be available in the next release.
Now there's a switch in Settings &rarr; General &rarr; Storage &rarr; WebDAV.

**Comment by NP-Hardass** [comment]
Works beautifully @antelle.  Thanks!

**Comment by HalliHalloSchatz** [comment]
wonderful. I am happy and waiting for this feature

**Comment by Gruck** [comment]
Hi ! I didn't think you would implement it that fast !
We used a workarround. Instead of putting or kdbx file in Atlassian confluence over webdav, we decided to go for Sharepoint + One Drive client for sync.
Seems to work just fine that way.
I'll give it a try nevertheless if i manage to find the time to try it out.
Cheers to you @antelle ! :)
