### ISSUE TITLE
[Feature Request] Browser Plugin to autofill forms

### ISSUE THREAD

**Issue by j-p-k** [keeweb/keeweb#519]
While some user value the fact that KeeWeb (and other KeePass implementations are independent from web browser and the), the auto-type feature does not provide the same convenience that password manager implemented as a browser plugin provide. Is there an effort made to use KeeWeb from inside the browsers?

Given that KeeWeb does already have a web UI, and cloud sync, it would be perfect fit for a browser-centric password manager.

**Comment by antelle** [comment]
This is one of the first issues and one of the hardest, please refer to #4
