### ISSUE TITLE
Issue with keeweb on on server and google drive

### ISSUE THREAD

**Issue by lvpre** [keeweb/keeweb#520]
Having issues getting keeweb working on my own server with google drive.  I either receive an Error 400 or Error 401 when I click on Google drive.  I added the id to the config.json for the google drive.  Anyone want to provide a step by step guide to getting it to work or do I need a secure server for it?  Thanks.

**Comment by antelle** [comment]
you have to replace google drive client id in your config, to get it work

**Comment by lvpre** [comment]
I receive this:

400. That’s an error.

Error: redirect_uri_mismatch

The redirect URI in the request, http://tonybabecka.com/keeweb/, does not match the ones authorized for the OAuth client. Visit https://console.developers.google.com/apis/credentials/oauthclient/847548101761-koqkji474gp3i2gn3k5omipbfju7pbt1.apps.googleusercontent.com?project=847548101761 to update the authorized redirect URIs.

I added the google client ID for web application to my json file, but still get this error.  I've tried to run the app as ....index.html?config=test.json and add the kw-config to redirect.  Same error.  Wonder what step I'm missing.

**Comment by antelle** [comment]
Then add redirect uri to your google app in your dev console.

**Comment by lvpre** [comment]
If you have time, I've tried to set it up on a dummy server, but still getting the same errors.

https://keewebtesttest.000webhostapp.com/  is the URL

files.000webhost.com is the hosting site.  User:  keewebtesttest  pass:  keeweb2017

Gmail account for testing:  keewebtesttest@gmail.com  pass: keeweb2017

Not sure what I'm missing, but if you fix it or help fix it, I would greatly appreciate.  Plus, I would create a step-by-step guide for you. Thanks for any help!

**Comment by antelle** [comment]
1. go here: https://console.developers.google.com/
2. create an app
3. set google drive client id in keeweb. you can do it either in config (but you are not using config), or just execute `kw.settings.set('gdriveClientId', '763137903241-gvpiuu8ae2cffupr619gdsq9b9f8cb5f.apps.googleusercontent.com')` in browser console (this way it will be saved only for your browser session).
4. add javascript origin and redirect uri
5. refresh the app page and try now

Some mistakes:
1, 2 - you already did these two steps, cool!
3. you have a config (well, kinda), but: 1. you have "test.json" in app kw-config, but must be "test.json", 2. test.json gives 404
4. you have not added js origin and made a mistake in redirect uri (it had no dot and slash, redirect URI must be exactly the same)

now it's working

**Comment by antelle** [comment]
I added this: https://github.com/keeweb/keeweb/wiki/Dropbox-and-GDrive
Hope it helps

**Comment by lvpre** [comment]
Thanks.  Finally, got it working.  I had to change something inside the index.html file.  This: 847548101761-koqkji474gp3i2gn3k5omipbfju7pbt1.apps.googleusercontent.com is in the original index.html file, I took that out and put in my google auth and it worked like a charm.  Let me know it this was a fluke or something else.  Thanks again for your help.

**Comment by antelle** [comment]
I would not advice that, because you will have to change this id every new release. Adding a config file is a better approach, but if you're ok with editing, it will work as well.
Yes, you will have to use https in order to access google drive or some other features. KeeWeb even warns you if you are trying to use it without https.

**Comment by lvpre** [comment]
Thanks again for your help and for making the app!  I have more free time next week, so I'll see if I can get it going correctly then.  The dropbox featured worked without a hitch.  Should the index.html have a google auth id in it or does it matter because it is bypassed for the config file?  I literally played with it for hours and the index.html workaround was the only way I could get it to work.  

Is the sample config.json here a good example?  Should I be able to copy it and just plug in data?  For example, take the sample and change "gdriveClientId": null, to "gdriveClientId": thegoogleusercontent.com,  ?

And for the index.html, do I change name="kw-config" content="(no-config)"> to name="kw-config" content="config.json"> ?



Thanks again for your help...and not perfect, but I did manage to get it up and running...and do you happen to have a donation link?

**Comment by kasoban** [comment]
@lvpre not in the app, but on the project readme:
https://github.com/keeweb/keeweb#donations

**Comment by antelle** [comment]
> Should the index.html have a google auth id in it or does it matter because it is bypassed for the config file?

The problem with index.html is that 1. it can change, 2. editing binary files is a bit tricky.
> Is the sample config.json here a good example?

Yes, just copy the parts you need.
> And for the index.html, do I change name="kw-config" content="(no-config)"> to name="kw-config" content="config.json"?

Exactly.

**Comment by Memphie** [comment]
@antelle when I klick on Google Drive, the Google Drive Icon turns around and nothing happens. When I edit my google acount in the Index.html , i have an blank Website when I open the Keeweb. So I whant test the way with the config.json. I thing my config.json is wrong. So you can help me with a config.json. Can you post one? I need google drive. Webdav is greate but not important.
I would open a new case, but this case is the same problem so I wrote here.

**Comment by antelle** [comment]
I guess, you should add a config instead of editing index.html

**Comment by Memphie** [comment]
Yes, I edit the Index.html:
ich use this for config.json:
`
<meta name="kw-config" content="(config.json)">
`
And when i change your Google Account to my i se only a blank site.

`
847548101761-koqkji474gp3i2gn3k5omipbfju7pbt1.apps.googleusercontent.com
`
This is my config.json:
`
{
  "settings": {

    gdrive: true, // enable Google Drive integration
    gdriveClientId: 123456789-25f9rpgauoemktpd3foid087ergsd5hh.apps.googleusercontent.com, // custom Google Drive client id
    gdriveClientSecret: myclientsecet // custom Google Drive client secret
    
  },
  "files": [{ // pre-defined files that will appear on Open page
    "storage": "webdav", // dropbox, webdav, etc...
    "name": "My file", // file name, as it will be displayed in UI
    "path": "webdav-url", // full path to file, including file name, e.g. WebDAV url
    "options": { "user": "", "password": "" } // only for WebDAV, server auth details
  }],
  "showOnlyFilesFromConfig": false, // allow to open only files from config, remove previously opened files
  "plugins": [{ // if you want to auto-install some plugins
    "url": "" // plugin url (you can also add "manifest" to enforce publicKey validation)
  }]
}
`

**Comment by antelle** [comment]
Probably the file gets corrupted when editing. What happens if you add a config and load it?

**Comment by Memphie** [comment]
i edit the index.html with notepat from windows. Today i installed noteplad++.  When i Edit the html i see only a blank side. I don`t know what is wrong. How change you the html file? What do i need ? Or can you change the values for me? Have yor a mailadress for me? What do you need?

**Comment by antelle** [comment]
As I said, please try adding a config instead of changing the file.

**Comment by Memphie** [comment]
How can i adding a Config?

**Comment by antelle** [comment]
https://github.com/keeweb/keeweb/wiki/Configuration#json-app-config

**Comment by Memphie** [comment]
OK, i Test it totay an write here.
But i must change this in the index.html? And this format with "?" bevor config.json ?
name="kw-config" content="https://mydomain.net/?config.json">

**Comment by Memphie** [comment]
so i testet it. I have create a config.json file and put it in the same path wehe the index.html is stored. 
when i open the url in Firefox https://mydomain.ddns.net/kw/?config.json i have this error:

Fehler 400: redirect_uri_mismatch .....   visit: https://console.developers.google.com/apis/credentials/oauthclient/847548101761-koqkji474gp3i2gn3k5omipbfju7pbt1.apps.googleusercontent.com?....

When I oben the URL in Firefox http://mydomain.ddns.net/kw/?config.json this happens:
when i Click on GoogleDrive the symbol only turns arount and nothing else happens.

Short Info, I have a Synology NAS where i installed a webserver (Apache), and i create a ddns Acout for access the webside. For this Test i have create a new folder on the webserver. So The cache from the Firefox should not the problem. Is my config.json the problem?

**Comment by Memphie** [comment]
This ist my config.json:
`
{
  "settings": {

    gdrive: true, 
    gdriveClientId: myID-25f9rpgauoemktpd3foid087ergsd5hh.apps.googleusercontent.com, 
    gdriveClientSecret: mysecret, 
    
  }
 }


`

**Comment by Memphie** [comment]
I testet to start Keeweb with a config file. It dossend work. I don't know if ihe Index.html startet withe the config.json. How can i see it?

**Comment by antelle** [comment]
What does it say in the browser console? Does it start without config?
