### ISSUE TITLE
Major issue with menus 1.4.0

### ISSUE THREAD

**Issue by eMerzh** [keeweb/keeweb#521]
Hi,first, much thanks for your work!

I've just updated keeweb to the latest 1.4.0 
and it seems that i have no menu anymore .
does't seems to have errors in the console
and i can't quit anymore using cmd-q (seems releated to the menu ;) )

<img width="881" alt="capture d ecran 2017-02-12 a 13 25 47" src="https://cloud.githubusercontent.com/assets/177003/22862050/4ac67622-f127-11e6-8b58-6e0666dee0df.png">

**Comment by antelle** [comment]
Just re-download the app, electron has changed their API #512
