### ISSUE TITLE
Blank permissions page

### ISSUE THREAD

**Issue by collectorgeneral** [keeweb/keeweb#523]
First off, great piece of software! Sleek, and useful at the same time. 
- what were your actions?
Enter google account details to sync to google drive
- what was wrong?
After entering user name and password, a blank permissions page comes up, rendering it useless. (see attached screenshot). The only way to get it to work is to close the window, and open it again. And then the permissions page loads correctly. However, this causes issues with sync, causes the 'Sync Error [object ...] thing to pop up. 
The only way to circumvent all this is to accept the permission so Google allows keeWeb to access the drive, purge the config files for KeeWeb, now try syncing to drive again. 
- app details:
Running on Linux Mint 18.1 Cinnamon,
KeeWeb v1.4.0 (c651343, 2017-02-04)
Environment: electron v1.4.15
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) KeeWeb/1.4.0 Chrome/53.0.2785.143 Electron/1.4.15 Safari/537.36
- does it happen on Demo or New database?
Existing database, NOT demo.
- if you are using a test db without your personal data, please attach it
- please, open dev tools in your browser and attach output log from Console tab 
    (if you are using desktop app, devtools can be opened from Settings/General/Advanced)
NA

![screenshot from 2017-02-14 10-01-30](https://cloud.githubusercontent.com/assets/15972594/22932352/fcc9e396-f29d-11e6-908a-1699d79bd574.png)

**Comment by antelle** [comment]
Seems to be fixed now.
