### ISSUE TITLE
Question: Performance penalty for using KeeWeb?

### ISSUE THREAD

**Issue by collectorgeneral** [keeweb/keeweb#524]
First off, fantastic work on the software! It has been my main passowrd manager for months now due to the ability to sync with cloud!

I noticed that KeeWeb is noticeably slower than, say KeepassX or others in terms of decrypting the database for a given set of rounds. My original database was encrypted using KeepassX and using the benchmark yielded around 10000000 rounds. It takes the other ports <=1 sec for decrypting the database, however on KeeWeb it takes an average of 5-6 seconds to decrypt the same file. I am not sure if it is a bug or simply a limitation of the way KeeWeb works. It would be nice to know!

**Comment by lholznagel** [comment]
Well, a web application (what KeeWeb is) will always be slower than a native application.

**Comment by lholznagel** [comment]
Well, a web application (what KeeWeb is) is slower than a native application.

**Comment by antelle** [comment]
That's expected. We should put expected benchmarks somewhere in readme. The advice is to set this value to 1/10 sec, so you should not notice the difference. One zero will add almost nothing to the complexity.

**Comment by collectorgeneral** [comment]
@antelle 
I suspected as much, but did not want to assume anything. Thanks for letting me know!
