### ISSUE TITLE
[Q] Is it possible to somehow use this from an app?

### ISSUE THREAD

**Issue by skrupler** [keeweb/keeweb#526]
Hi,
I've been looking into the possibility to use keeweb instead of the somewhat clunky keepass desktop/android apps (which are great in their own regard ofc). The reason being that the databases dont sync themselves. However with keeweb it seems it might be possible to have one database within nextcloud and access it via web both from a phone and a desktop/laptop - and maybe have somekind of wrapper app for it? Im not sure how keeweb works behind the scene but would it be possible?

Thanks in advance

**Comment by antelle** [comment]
Hi,
In order to sync, you can save your db to Dropbox / Nextcloud / whatever... and open it on another device. It will be synced automatically. You can also look into this project: https://github.com/jhass/nextcloud-keeweb

**Comment by skrupler** [comment]
@antelle thank you. I will check out the nextcloud-keeweb app. 
Offtopic: Btw I took the liberty to finish translating the keeweb into swedish - how can we finilize that one?

**Comment by antelle** [comment]
Perfect, I just left some comments to your questions. Phrase upload process is automatic: they are exported from OneSky API and added to the app ([here's](https://github.com/keeweb/keeweb/blob/develop/util/download-translations.js) the script), if there's no problem with them and the number of phrases exceeds 75%. Then they will appear in the next version.

**Comment by antelle** [comment]
Uploaded new build with translations to beta
