### ISSUE TITLE
Saving to file causes sync error with google drive

### ISSUE THREAD

**Issue by collectorgeneral** [keeweb/keeweb#527]
Thanks for taking the time to contribute!

Please, read https://github.com/keeweb/keeweb/wiki/FAQ before submitting a new issue and fill in the following (if applicable):

- what were your actions?
Import XML. Save to file. Now save to Google Drive. 
- what was wrong?
The above will cause the Sync to fail every time. This will also leave an 'empty' entry on the start screen which will leave to 'file not found' error. 
Instead do the opposite: First Sync, then save to file. Everything is fine.
- app version
KeeWeb v1.4.0 (c651343, 2017-02-04)
Environment: electron v1.4.15
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) KeeWeb/1.4.0 Chrome/53.0.2785.143 Electron/1.4.15 Safari/537.36
- does it happen on Demo or New database?
Existing DB

- please, open dev tools in your browser and attach output log from Console tab 
    (if you are using desktop app, devtools can be opened from Settings/General/Advanced)
SEE ATTACHED LOG

I encountered this weird behaviour where google drive kept failing to sync and load. I have finally figured out what is causing the annoying error I keep getting. 
To reproduce this (Already stated above): Import an XML file containing PWs. First save to file. Now save to Google Drive. Sync will fail (Sync Error; [Object object] or something like that). 
This will lead to another problem: This results in an invalid entry on the start page which will point to a non existent file in the cache, causing KeeWeb to throw an error (See attached log). 
Do the reverse: Save to Drive first, then save to file. All smooth sailing.

My understanding of the issue: reading the log suggests this is an intended (probably unexpected) behaviour:
`2017-02-15T01:41:17.492Z [sync:NewDB] Saving to storage, skip cache because not dirty`

It appears to me that the file is not cached if it has been saved to file prior to saving to cloud. This then causes issues with Sync (I speculate that this is probably because keeweb is looking to sync the file from the cache to the cloud? And since it does not exist {owing to the fact that it was skipped earlier} it fails to sync)? 
EDIT: I think the sync error I mentioned in #523  is due to this and has nothing to do with the blank permissions page. I always save to local file first prior to trying to save to the cloud, so it leads to this error. The blank permissions page however is still a problem.
[201702142146 - GDRIVE ERROR.txt](https://github.com/keeweb/keeweb/files/775806/201702142146.-.GDRIVE.ERROR.txt)
[201702142135.txt](https://github.com/keeweb/keeweb/files/775889/201702142135.txt)

**Comment by antelle** [comment]
Thanks for the detailed steps!
