### ISSUE TITLE
Icon is not quite round

### ISSUE THREAD

**Issue by xunilarium** [keeweb/keeweb#531]
Hi
I'm using the last version of your app and tested in Windows 7, 10 and also Ubuntu and Arch but the result was the same. the app icon in main app and tray system is not not quite round.

![02](https://cloud.githubusercontent.com/assets/10381709/23045135/b559ef52-f4b8-11e6-9100-0d6e998c7407.png)
![01](https://cloud.githubusercontent.com/assets/10381709/23045136/b5629dd2-f4b8-11e6-820b-e91d5b3d67de.png)

**Comment by antelle** [comment]
Good point, I noticed this being on Windows, but I don't quite understand how to build the appropriate icon, because now it includes hi-res images as well. Any help with icon is appreciated.

**Comment by xunilarium** [comment]
I am a network administrator and not a programmer or designer to help you and because of that I'm sorry. I saw this issue in many apps and I hope some one help you with that but maybe use a square icon instead of the circle one helps.

**Comment by antelle** [comment]
For anyone who would like to dig into it: we have quite a lot of icons inside the ico file, on windows installed through bootcamp (on retina screen) they look pretty good.
![icon](https://cloud.githubusercontent.com/assets/633557/23078231/15c35718-f548-11e6-8964-24abb9883609.png)
