### ISSUE TITLE
Frequently require discrete graphics on MacOS

### ISSUE THREAD

**Issue by GhostFlying** [keeweb/keeweb#536]
- what were your actions?

just use it as usual.

- what was wrong?

the keeweb desktop require discrete graphics frequently and cause extra battery use

- app version

1.3.3 (52701af)

- platform

macOS 10.12.3 on macbook pro 2016 later 15 inch

it seems caused by the framework but if there any way to resolve?

**Comment by antelle** [comment]
https://github.com/electron/electron/issues/4380
Does '--disable-gpu' flag solve the issue for you?

**Comment by GhostFlying** [comment]
As it may need some time to reproduce, I need some time to test with it and will reply asap.

**Comment by GhostFlying** [comment]
It seems strange that I do not reproduce this issue the last two days and I am not sure if the version 1.4.0 or the latest system update fix it.  

Maybe this issue can be closed and reopened if I or someone can reproduce it.

**Comment by honiewelle** [comment]
Currently experiencing this with v1.7.8 running on MacOS X Mojave 10.14.3. Running KeeWeb desktop by default uses GPU.
