### ISSUE TITLE
Bad behavior when copied password on Chrome iOS

### ISSUE THREAD

**Issue by piclemx** [keeweb/keeweb#537]
- what were your actions?
Copied password from the web version
- what was wrong?
When I minimize my browser ( Google Chrome iPhone) and the setting to auto lock on copied password, KeeWeb doesn't lock.
- app version v1.4.0 (c651343, 2017-02-04)
- your user-agent (from Settings/Help section)
User-Agent: Mozilla/5.0 (iPhone; CPU iPhone OS 10_2_1 like Mac OS X) AppleWebKit/6021.50 (KHTML, like Gecko) CriOs/56.0.2924.79 Mobile/14D27 Safari/602.1
- does it happen on Demo or New database?
My database

**Comment by antelle** [comment]
To me, it's locked. What happens, when you open your browser, does it get locked then?

**Comment by piclemx** [comment]
No.

**Comment by antelle** [comment]
I got it, it's chrome-specific, because they still don't implement clipboard api, and you see a menu with Copy button. Works perfectly in safari.

**Comment by piclemx** [comment]
Do you know how to fix this? I can work on it if you tell me how.

**Comment by antelle** [comment]
Yes, it should be rather simple.
[Here](https://github.com/keeweb/keeweb/blob/master/app/scripts/views/details/details-view.js#L418) we're adding a hidden input for old browsers, you should add a callback to `createHiddenInput` method and call it on copy [here](https://github.com/keeweb/keeweb/blob/master/app/scripts/comp/copy-paste.js#L50), then subscribe to it and and call `this.fieldCopied({ source: editView });`.

**Comment by antelle** [comment]
Chrome has implemented clipboard API. Support of browsers without this API is now completely removed from KeeWeb.
