### ISSUE TITLE
Menus do not work on macOS

### ISSUE THREAD

**Issue by warkdarrior** [keeweb/keeweb#539]
- what were your actions?
I just upgraded to v1.4.0 (2017-02-04), on macOS Sierra 10.12.3.

- what was wrong?
The menus in the main menu bar are non-functional and missing text.

- app version
v1.4.0 (2017-02-04)

- your user-agent (from Settings/Help section)
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit/537.36 (KHTML, like Gecko) KeeWeb/1.2.1 Chrome/51.0.2704.63 Electron/1.2.1 Safari/537.36

- does it happen on Demo or New database?
Don't know

![image](https://cloud.githubusercontent.com/assets/15383098/23278621/034fd5ce-f9c7-11e6-97a2-efc7a92a78a5.png)
![image](https://cloud.githubusercontent.com/assets/15383098/23278648/17b07474-f9c7-11e6-8dc3-7009c06d5c68.png)
![image](https://cloud.githubusercontent.com/assets/15383098/23278657/1fd5bfb0-f9c7-11e6-8c8e-2e7ade63307e.png)

**Comment by antelle** [comment]
just re-download the whole app
