### ISSUE TITLE
Issue saving database WebDav

### ISSUE THREAD

**Issue by milkshakespoon** [keeweb/keeweb#540]
- what were your actions?
Opening a WebDav .kdbx file successfully. Issue occurs when attempting to save the database back to the server.

- what was wrong?
Upon hitting the save button I am getting the errors I have provided below.

- app version
V1.4.0

- your user-agent (from Settings/Help section)
KeeWeb v1.4.0 (c651343, 2017-02-04)
Environment: web
User-Agent: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36

- does it happen on Demo or New database?
This is happenig on new databases saved in a directory on the server.

- please, open dev tools in your browser and attach output log from Console tab 
    (if you are using desktop app, devtools can be opened from Settings/General/Advanced)
Browser log
```
2017-02-24T17:26:22.764Z [app] Add last open file 1a3eac6d-d711-accb-825d-4fdf0d2184ca Keepass Tester webdav database/KeepassDB_Test.kdbx Sat, 18 Feb 2017 11:41:55 GMT
(index):16 2017-02-24T17:26:22.848Z [storage-cache] Saved 1a3eac6d-d711-accb-825d-4fdf0d2184ca 1ms
(index):16 2017-02-24T17:26:32.201Z [sync:Keepass Tester] Sync started webdav database/KeepassDB_Test.kdbx Object {startedByUser: true}
(index):16 2017-02-24T17:26:32.213Z [sync:Keepass Tester] Stat file
(index):16 2017-02-24T17:26:32.213Z [storage-webdav] Stat database/KeepassDB_Test.kdbx
(index):16 2017-02-24T17:26:32.265Z [storage-webdav] Stated database/KeepassDB_Test.kdbx Sat, 18 Feb 2017 11:41:55 GMT 51ms
(index):16 2017-02-24T17:26:32.273Z [sync:Keepass Tester] Stat found same version, modified, saving
(index):16 2017-02-24T17:26:32.277Z [sync:Keepass Tester] Getting file data for saving
(index):16 2017-02-24T17:26:32.397Z [sync:Keepass Tester] Saving to cache
(index):16 2017-02-24T17:26:32.401Z [storage-cache] Save 1a3eac6d-d711-accb-825d-4fdf0d2184ca
(index):16 2017-02-24T17:26:32.401Z [storage-cache] Saved 1a3eac6d-d711-accb-825d-4fdf0d2184ca 0ms
(index):16 2017-02-24T17:26:32.405Z [sync:Keepass Tester] Saved to cache, saving to storage
(index):16 2017-02-24T17:26:32.405Z [sync:Keepass Tester] Save data to storage
(index):16 2017-02-24T17:26:32.409Z [storage-webdav] Save:stat database/KeepassDB_Test.kdbx
(index):16 2017-02-24T17:26:32.445Z [storage-webdav] Save:stated database/KeepassDB_Test.kdbx Sat, 18 Feb 2017 11:41:55 GMT 38ms
(index):16 2017-02-24T17:26:32.449Z [storage-webdav] Save:put database/.KeepassDB_Test.kdbx.1487957192409
(index):22 PUT https://192.168.0.67/database/.KeepassDB_Test.kdbx.1487957192409 404 (Not Found)
_request @ (index):22
(anonymous) @ (index):22
(anonymous) @ (index):22
(index):16 2017-02-24T17:26:32.481Z [storage-webdav] Save:put error database/.KeepassDB_Test.kdbx.1487957192409 404 31ms
(index):16 2017-02-24T17:26:32.481Z [sync:Keepass Tester] Error saving data to storage
(index):16 2017-02-24T17:26:32.481Z [sync:Keepass Tester] Sync finished Object {notFound: true}

```

Application log
```
[INFO ] 2017-02-24T17:26:32.277Z [sync:Keepass Tester] Getting file data for saving
[INFO ] 2017-02-24T17:26:32.397Z [sync:Keepass Tester] Saving to cache
[DEBUG] 2017-02-24T17:26:32.401Z [storage-cache] Save 1a3eac6d-d711-accb-825d-4fdf0d2184ca
[DEBUG] 2017-02-24T17:26:32.401Z [storage-cache] Saved 1a3eac6d-d711-accb-825d-4fdf0d2184ca 0ms
[INFO ] 2017-02-24T17:26:32.405Z [sync:Keepass Tester] Saved to cache, saving to storage
[INFO ] 2017-02-24T17:26:32.405Z [sync:Keepass Tester] Save data to storage
[DEBUG] 2017-02-24T17:26:32.409Z [storage-webdav] Save:stat database/KeepassDB_Test.kdbx
[DEBUG] 2017-02-24T17:26:32.445Z [storage-webdav] Save:stated database/KeepassDB_Test.kdbx Sat, 18 Feb 2017 11:41:55 GMT 38ms
[DEBUG] 2017-02-24T17:26:32.449Z [storage-webdav] Save:put database/.KeepassDB_Test.kdbx.1487957192409
[DEBUG] 2017-02-24T17:26:32.481Z [storage-webdav] Save:put error database/.KeepassDB_Test.kdbx.1487957192409 404 31ms
[INFO ] 2017-02-24T17:26:32.481Z [sync:Keepass Tester] Error saving data to storage
[INFO ] 2017-02-24T17:26:32.481Z [sync:Keepass Tester] Sync finished [object Object]
```

Nginx config copied from the WebDav help page.

```
Config.json
{
  "settings": {
    "theme": "fb",
    "locale": "en",
    "expandGroups": true,
    "listViewWidth": null,
    "menuViewWidth": null,
    "tagsViewHeight": null,
    "autoUpdate": "install",
    "autoSave": true,
    "rememberKeyFiles": false,
    "idleMinutes": 15,
    "tableView": false,
    "colorfulIcons": false,
    "lockOnCopy": false,
    "skipOpenLocalWarn": false,
    "hideEmptyFields": false,
    "skipHttpsWarning": false,
    "demoOpened": false,
    "fontSize": 1,
    "tableViewColumns": null,
    "generatorPresets": null,

    "canOpen": true,
    "canOpenDemo": true,
    "canOpenSettings": true,
    "canCreate": false,
    "canImportXml": false,
    "canRemoveLatest": true,

    "dropbox": false,
    "dropboxFolder": null,
    "dropboxAppKey": null,

    "webdav": true,

    "gdrive": false,
    "gdriveClientId": null,

    "onedrive": false,
    "onedriveClientId": null,

    "cacheConfigSettings": false
  },
  "files": [{
    "storage": "webdav",
    "name": "Keepass Tester",
    "path": "database/KeepassDB_Test.kdbx",
    "options": { "user": "user", "password": "testpassword" }
      
  }],
  "showOnlyFilesFromConfig": false
}
```

**Comment by antelle** [comment]
Your webdav server is returning 404 on put, please fix it.

**Comment by milkshakespoon** [comment]
Would you happen to have any ideas as to why? I notice during the put the name has a random string attached to the end? I'm not experienced with WebDAV really. I just copied the contents of the Nginx config from the help files on my server.

**Comment by antelle** [comment]
No, I have no idea, you should check your server logs.
> random string attached to the end

It's by design, first we create temp file, and then replace the original one. This is a common practice, e.g. macOS webdav does this as well.

**Comment by milkshakespoon** [comment]
Sure, so here is my Nginx config if you wouldn't mind checking over it please? Your help is much appreciated!

# You may add here your
# server {
#	...
# }
# statements for each of your virtual hosts to this file

##
# You should look at the following URL's in order to grasp a solid understanding
# of Nginx configuration files in order to fully unleash the power of Nginx.
# http://wiki.nginx.org/Pitfalls
# http://wiki.nginx.org/QuickStart
# http://wiki.nginx.org/Configuration
#
# Generally, you will want to move this file somewhere, and start with a clean
# file but keep this around for reference. Or just disable in sites-enabled.
#
# Please see /usr/share/doc/nginx-doc/examples/ for more detailed examples.
##

server {
	listen 80 default_server;
	listen [::]:80 default_server ipv6only=on;

	listen 443 ssl;

	root /usr/share/nginx/html/keeweb/;
	index index.html index.htm;
	
	# Make site accessible from http://localhost/
	server_name keeweb;
	ssl_certificate /etc/nginx/ssl/keeweb.crt;
	ssl_certificate_key /etc/nginx/ssl/keeweb.key;

	location / {
		# First attempt to serve request as file, then
		# as directory, then fall back to displaying a 404.
		try_files $uri $uri/ =404;
		# Uncomment to enable naxsi on this location
		# include /etc/nginx/naxsi.rules
		add_header 'Access-Control-Allow-Origin' '*';
		add_header 'Access-Control-Allow-Credentials' 'true';
		add_header 'Access-Control-Allow-Methods' 'GET, HEAD, POST, PUT, OPTIONS, MOVE, DELETE, COPY, LOCK, UNLOCK';
		add_header 'Access-Control-Allow-Headers' 'Authorization,DNT,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,X-Accept-Charset,X-Accept,origin,accept,if-match,destination, overwrite';
		add_header 'Access-Control-Expose-Headers' 'ETag';
		add_header 'Access-Control-Max-Age' 1728000;
		if ($request_method = 'OPTIONS') {
    			add_header 'Content-Type' 'text/plain charset=UTF-8';
    			add_header 'Content-Length' 0;
    			return 204;
		}
}

	# Only for nginx-naxsi used with nginx-naxsi-ui : process denied requests
	#location /RequestDenied {
	#	proxy_pass http://127.0.0.1:8080;    
	#}

	#error_page 404 /404.html;

	# redirect server error pages to the static page /50x.html
	#
	#error_page 500 502 503 504 /50x.html;
	#location = /50x.html {
	#	root /usr/share/nginx/html;
	#}

	# pass the PHP scripts to FastCGI server listening on 127.0.0.1:9000
	#
	#location ~ \.php$ {
	#	fastcgi_split_path_info ^(.+\.php)(/.+)$;
	#	# NOTE: You should have "cgi.fix_pathinfo = 0;" in php.ini
	#
	#	# With php5-cgi alone:
	#	fastcgi_pass 127.0.0.1:9000;
	#	# With php5-fpm:
	#	fastcgi_pass unix:/var/run/php5-fpm.sock;
	#	fastcgi_index index.php;
	#	include fastcgi_params;
	#}

	# deny access to .htaccess files, if Apache's document root
	# concurs with nginx's one
	#
	#location ~ /\.ht {
	#	deny all;
	#}
}


# another virtual host using mix of IP-, name-, and port-based configuration
#
#server {
#	listen 8000;
#	listen somename:8080;
#	server_name somename alias another.alias;
#	root html;
#	index index.html index.htm;
#
#	location / {
#		try_files $uri $uri/ =404;
#	}
#}


# HTTPS server
#
#server {
#	listen 443;
#	server_name localhost;
#
#	root html;
#	index index.html index.htm;
#
#	ssl on;
#	ssl_certificate cert.pem;
#	ssl_certificate_key cert.key;
#
#	ssl_session_timeout 5m;
#
#	ssl_protocols SSLv3 TLSv1 TLSv1.1 TLSv1.2;
#	ssl_ciphers "HIGH:!aNULL:!MD5 or HIGH:!aNULL:!MD5:!3DES";
#	ssl_prefer_server_ciphers on;
#
#	location / {
#		try_files $uri $uri/ =404;
#	}
#}

**Comment by antelle** [comment]
And where do you enable webdav?

**Comment by milkshakespoon** [comment]
That is a very good question. Something I'm clearly missing in that case. Do you have any recommended documentation for that config?

**Comment by antelle** [comment]
This could be a good start: http://nginx.org/en/docs/http/ngx_http_dav_module.html

**Comment by milkshakespoon** [comment]
Thank you for your help. Potentially this is something that could be added to the WebDAV information section? A user like myself has no experience with WebDAV. 

Once I get this up and running I plan to donate some money to this project. 

Thanks again!

**Comment by antelle** [comment]
We assume that if you enable webdav, you already know how to setup a webdav server ;)
KeeWeb requires some additional configuration though, you can find it in webdav section of our wiki.
