### ISSUE TITLE
App crash in browser and app (Mac OSX)

### ISSUE THREAD

**Issue by jkimbo** [keeweb/keeweb#543]
**what were your actions?**
Trying to open an `.kdbx` database in either the web app or the electron app. The database size is `24.2 MB`

**what was wrong?**
The app just displays an empty white screen. The web app crashes with an `Aww snap...` page. Running Chrome with logging turned on I get the following stack trace:

```
[33172:43011:0227/142938.221361:ERROR:connection_factory_impl.cc(367)] Failed to connect to MCS endpoint with error -102

<--- Last few GCs --->

[33268:0x7fcc33819400]    28388 ms: Mark-sweep 1413.7 (1463.7) -> 1413.7 (1432.7) MB, 879.2 / 0.8 ms  (+ 0.0 ms in 0 steps since start of marking, biggest step 0.0 ms, walltime since start of marking 879 ms) last resort
[33268:0x7fcc33819400]    29282 ms: Mark-sweep 1413.7 (1432.7) -> 1413.7 (1432.7) MB, 893.9 / 0.8 ms  last resort


<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0x34507043c501 <String[23]: https://app.keeweb.info>
    2: i(aka i) [https://app.keeweb.info/:~16] [pc=0x1a39b25a1679](this=0x12c828402311 <undefined>,e=0x3d205e6b9649 <JS Array[32067782]>)
    3: o [https://app.keeweb.info/:16] [pc=0x1a39b25d62a3](this=0x1d06b0ce0531 <a c with map 0x6110b98ce91>,e=0x3d205e6b9649 <JS Array[32067782]>)
    4: /* anonymous */ [https://app.keeweb.info/:16] [pc=0x1a39b259e4e3](this=0x1d06b0...
```

**app version**
The electron app version is: `v1.4.0` and I'm running Chrome `56.0.2924.87`

**your user-agent**
`Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36`

**does it happen on Demo or New database?**
No

---

My suspicion is that the database is too big to be opened with Chrome (opening it with [MacPass](https://github.com/mstarke/MacPass) is fine for example). Does that sound like a possibility? Also any suggestions on how to reduce the size of it?

**Comment by antelle** [comment]
Wow, so huge! 24MB is gzipped size, so it's way larger. You definitely have a problem with your db, it's enormous, typically all databases are <100kb. E.g. I have about 500 passwords with history, custom icons and some attachment, and the db size is 70kb.
You should investigate your db. Probably you have a large attachment inside.
Hm, that's interesting idea, to create a devtool, which would show the distribution of space in your database. Now I encourage you to export your db to XML and see what's inside.

**Comment by jkimbo** [comment]
Ok thanks for the tip! I managed to open the database in chrome on another machine and after digging through it I found some entries that had past records with attachments in them. After deleting them I got the size down to 9MB (still have a few attachments in there).

Thanks for the help!
