### ISSUE TITLE
Cannot read property 'then' of undefined. DB does not open

### ISSUE THREAD

**Issue by danlegion** [keeweb/keeweb#544]
Please, read https://github.com/keeweb/keeweb/wiki/FAQ before submitting a new issue and fill in the following (if applicable):

- what were your actions?
**trying to unlock/open the DB**

- what was wrong?
**The DB doesnt open and the following error shows up:
"TypeError: Cannot read property 'then' of undefined**

- app version
**Version 1.4.0 (c651343) It happened with previous versions too**

- agent
**Environment: electron v1.4.15
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_2) AppleWebKit/537.36 (KHTML, like Gecko) KeeWeb/1.4.0 Chrome/53.0.2785.143 Electron/1.4.15 Safari/537.36**

- does it happen on Demo or New database?
 **No, only on my own DB**

- please, open dev tools in your browser and attach output log from Console tab 
    (if you are using desktop app, devtools can be opened from Settings/General/Advanced)
**index.html:16 2017-02-27T21:25:56.447Z [open-view] Error opening file TypeError: Cannot read property 'then' of undefined(…)s.error @ index.html:16openDbComplete @ index.html:25(anonymous function) @ index.html:20(anonymous function) @ index.html:18**

**Comment by antelle** [comment]
Hello!
Could you please open browser devtools and paste a full stack trace here? You can get it by expanding error message. In electron app, you can open them with Cmd+F12 or Ctrl+F12.

**Comment by danlegion** [comment]
`index.html:16 2017-02-27T21:30:14.548Z [file] Error opening file undefined Cannot read property 'then' of undefined TypeError: Cannot read property 'then' of undefined
    at a.getBinaryHash (file:///Applications/KeeWeb.app/Contents/Resources/app/index.html:13:13269)
    at file:///Applications/KeeWeb.app/Contents/Resources/app/index.html:13:13005
    at Array.forEach (native)
    at a.hash (file:///Applications/KeeWeb.app/Contents/Resources/app/index.html:13:12965)
    at y._loadFromXml (file:///Applications/KeeWeb.app/Contents/Resources/app/index.html:14:10290)
    at file:///Applications/KeeWeb.app/Contents/Resources/app/index.html:13:15090s.error @ index.html:16(anonymous function) @ index.html:18
index.html:16 2017-02-27T21:30:14.559Z [open-view] Error opening file TypeError: Cannot read property 'then' of undefined
    at a.getBinaryHash (file:///Applications/KeeWeb.app/Contents/Resources/app/index.html:13:13269)
    at file:///Applications/KeeWeb.app/Contents/Resources/app/index.html:13:13005
    at Array.forEach (native)
    at a.hash (file:///Applications/KeeWeb.app/Contents/Resources/app/index.html:13:12965)
    at y._loadFromXml (file:///Applications/KeeWeb.app/Contents/Resources/app/index.html:14:10290)
    at file:///Applications/KeeWeb.app/Contents/Resources/app/index.html:13:15090s.error @ index.html:16openDbComplete @ index.html:25(anonymous function) @ index.html:20(anonymous function) @ index.html:18`

**Comment by antelle** [comment]
Hello, thanks, the stack trace is helpful, there's an issue with reading binary.
How did you create this file, in which app?

**Comment by danlegion** [comment]
Hey @antelle  thanks for your quick reply. The DB was created with the windows version of keepass a few years ago. It is still read by keepass and keepassX, but it is giving keeweb a hard time

**Comment by antelle** [comment]
Could you please open your file with this version and check the output? 
[keeweb-dev.zip](https://github.com/keeweb/keeweb/files/805155/keeweb-dev.zip)

**Comment by danlegion** [comment]
![screen shot 2017-02-27 at 3 33 50 pm](https://cloud.githubusercontent.com/assets/2336246/23383128/2b550a06-fd02-11e6-8b67-dd1391c9018e.png)

**Comment by antelle** [comment]
Interesting. It looks like, you have an empty binary in the db. Is it possible to open it with this version?
[keeweb-dev.zip](https://github.com/keeweb/keeweb/files/805208/keeweb-dev.zip)

**Comment by danlegion** [comment]
whoa! success! that worked!
Thanks for the help. I love using the desktop app. Would you be able to include this fix in the next release?

**Comment by antelle** [comment]
Cool, updating beta. Of course it will be included to the next hotfix! I'll just wait a bit, to collect fixes.

**Comment by danlegion** [comment]
sweet thanks again. Can't wait for the next release

**Comment by antelle** [comment]
Deployed to [beta.keeweb.info](https://beta.keeweb.info), will be available in the next release.
Many thanks for help with debugging!

**Comment by pckujawa** [comment]
I must have the same issue. It seemed to open ok with version 1.3.3 (or maybe it was an even older version), but I recently downloaded that old version and ran it and the About page said it was still v1.4.0 - is the actually keeweb binary not inside of the dmg?

I tried to use the file linked, keeweb-dev.zip, but it just extracted an index.html which wouldn't open, for some reason. I'm happy to just use what's in master, but I couldn't get it to build on my Mac.

Actually, I was able to go to Settings and "use beta version" and now I can open my file again. Would you mind creating a new release with this fix, since it's been almost a month?

**Comment by antelle** [comment]
Oops, completely forgot about this issue. As there are no major issues with this release, I'll make a hotfix tomorrow, thanks for the reminder!

**Comment by danlegion** [comment]
awesome thanks. I've been waiting for this fix

**Comment by antelle** [comment]
it's live now

**Comment by pckujawa** [comment]
Thank you!
