### ISSUE TITLE
keeweb opens periodically a new tab

### ISSUE THREAD

**Issue by gsportelli** [keeweb/keeweb#549]
> what were your actions?

I use google drive storage for the kdb file and keep the keeweb tab open while working.

> what was wrong?

keeweb opens a new tab periodically. I don't know exactly why, maybe for synchronising. Normally, the new tab closes itself instantly. This is annoying because if I'm working on something else, the tab takes the focus temporarily. On my mac the focus switch can also change the current desktop, which is more annoying.
Things got worse when I added a new google account to gmail, because now when keeweb opens the tab, it asks me every time to choose a google account. Again, I think that this is because it wants to access the kdb file, so I choose the account on which I have it.

> app version and user-agent (from Settings/Help section)

KeeWeb v1.4.0 (c651343, 2017-02-04)
Environment: web
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36

> does it happen on Demo or New database?

N/A

> if you are using a test db without your personal data, please attach it please, open dev tools in your browser and attach output log from Console tab

N/A

**Comment by antelle** [comment]
Hello,
Unfortunately, unlike Dropbox, Google doesn't allow to use long-lived token flow in serverless apps, so we must authorize you again and again. You can read about it on this page, Clientside section: https://developers.google.com/identity/protocols/OAuth2#clientside.
If you know how to resolve it, please let me know.

**Comment by gsportelli** [comment]
I'm not experienced in the field, and maybe I'm wrong, but from the docs it seems to me that [refresh tokens](https://developers.google.com/identity/protocols/OAuth2WebServer#offline) can be requested for this purpose.

**Comment by antelle** [comment]
@gsportelli have you ever seen a working example? I tried this, but it gives 40* error, when trying to access from javascript.

**Comment by gsportelli** [comment]
No, I don't, and I'm quite new to js programming. A nice resource is this [blog article](https://alexbilbie.com/guide-to-oauth-2-grants/).

One thing that I don't understand is that all of this is about OAuth2, which is not just Google. Shouldn't be it the same as for Dropbox?

**Comment by antelle** [comment]
Thanks, but I do know how to use OAuth2 and what's the difference between two flows. We can't use it, because Google doesn't want it to happen. So, the example I'm asking for is exactly using Google from JavaScript, not basic OAuth2 example.
No, it doesn't have to be the same, it's OAuth provider's decision, to allow permanent codes in browser or not. Well, classically, browser apps were considered short-living, insecure and so on, and a simple auth token was enough, that's why Google is still returning an error when trying to request a permanent code from browser. They suggest that we save permanent access codes only on server, not on the client. Dropbox doesn't have such a dumb limitation.

**Comment by avently** [comment]
@antelle you can use iframe for that. https://stackoverflow.com/a/26007491

**Comment by antelle** [comment]
Hm, will it work with Google? I guess, they prohibit opening in iframe, but I'll check.

**Comment by jalmeroth** [comment]
@antelle have you checked to submit a form like shown in the `oauth2SignIn` function of [this example](https://developers.google.com/identity/protocols/OAuth2UserAgent#example)?

It might be helpful to set the `prompt` parameter to `none` for refreshing the token? Although this should happen automagically on the server side, this is what Microsoft suggests for refreshing tokens: https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-v2-protocols-implicit#refreshing-tokens

**Comment by antelle** [comment]
Yeah I was going to check it, since we moved to new API in v1.6, so we have more possibilities now.

**Comment by jalmeroth** [comment]
Well Google knows the prompt parameter too: https://developers.google.com/identity/protocols/OAuth2UserAgent#redirecting

**Comment by antelle** [comment]
This was actually fixed with other OAuth improvements in v1.14.
