### ISSUE TITLE
[Feature request] Browser plugin for secure logins (clipboard major security risk)

### ISSUE THREAD

**Issue by snakyjake1** [keeweb/keeweb#550]
Need a secure browser plugin that can enter/save/transfer passwords between the browser and keeweb.

Copy/pasting into the clipboard is not secure, especially if there are applications that monitor the clipboard, save the clipboard, or keep clipboard history.

**Comment by antelle** [comment]
This duplicates #4
> if there are applications that monitor the clipboard

...then you should NEVER run a password manager on that machine, because they can monitor browser requests as well.
But having the extension would be very convenient, so we should develop it somehow.
