### ISSUE TITLE
Crash when opening large size kdbx

### ISSUE THREAD

**Issue by feiming** [keeweb/keeweb#551]
I'm trying to open 34MB local kdbx file, stores files as attachment. After entering password, it took a few seconds before showing white page. 

![screen shot 2017-03-05 at 5 05 16 pm](https://cloud.githubusercontent.com/assets/1654592/23585962/2be6fb64-01c6-11e7-8eac-398c034ebe6a.png)

KeeWeb v1.4.0 (c651343, 2017-02-04)
Environment: electron v1.4.15
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit/537.36 (KHTML, like Gecko) KeeWeb/1.4.0 Chrome/53.0.2785.143 Electron/1.4.15 Safari/537.36

**Comment by antelle** [comment]
This is an edge case, you should remove some old attachments from your db. Normally, the db should be much more less than 1MB.
