### ISSUE TITLE
Google Drive icon symmetry is a little bit off

### ISSUE THREAD

**Issue by Loilo** [keeweb/keeweb#552]
This is a minor visual thing: The bottom left gap of the Google Drive icon is slightly wider than the other two.

![wider](https://cloud.githubusercontent.com/assets/1922624/23604038/bd1cfa02-0257-11e7-9081-04f0191ca7bf.png)

In case you crafted the icon yourself and thus it's easy to fix – great.

If not you might also just replace it with this:

![drive](https://cloud.githubusercontent.com/assets/1922624/23603816/e7860514-0256-11e7-9812-5eeaad3e718d.png)

```svg
<svg xmlns="http://www.w3.org/2000/svg" width="128" height="128" viewBox="0 0 128 128"><path d="M86.657536,76.246208 L47.768064,9 L89.111168,9 L128,76.246208 L86.657536,76.246208 Z M25.010048,119.08 L102.690048,119.08 L123.36256,83.24 L45.68064,83.24 L25.010048,119.08 L25.010048,119.08 Z M38.793088,9.003712 L0,76.30496 L20.671872,112.110016 L59.464704,44.808128 L38.793088,9.003712 Z"></path></svg>
```

I created it [a while ago](https://github.com/Loilo/fontelico.font/blob/235d15e12704acc26c6dd914659f17e39d906181/src/svg/google-drive.svg) for the Fontello project but due to inactivity on their side it has never been merged. I put it under [CC0 1.0](https://creativecommons.org/publicdomain/zero/1.0/) as far as that's possible regarding trademark laws in different countries.

Side-by-side comparison:

![side-by-side](https://cloud.githubusercontent.com/assets/1922624/23604141/1baa1118-0258-11e7-9849-4d33ad4fb8c9.png)

In case you'd want to use it, I'd be happy to attach a PR.

**Comment by antelle** [comment]
Thanks! It's better now. 🎁
