### ISSUE TITLE
[Feature request] Possibility to link fields?

### ISSUE THREAD

**Issue by joists** [keeweb/keeweb#553]
Hi

In KeePass it is possible to link field content between diffrent entries, so for intance if I have the same account for diffrent systems I can link the password and/or username between the entries.

**Comment by Loilo** [comment]
You're basically asking for a thing kalled "References" in KeePass. That's already been discussed in #296 and currently has [partial support](https://github.com/keeweb/keeweb/issues/296#issuecomment-239690535).

**Comment by antelle** [comment]
@Loilo exactly, thanks.
