### ISSUE TITLE
[Privacy Issue] Shortcut pastes password into any app in foreground

### ISSUE THREAD

**Issue by ylogx** [keeweb/keeweb#554]
- what were your actions?

1. Chrome full screen on mac. Press Ctrl+Alt+T to fill password.
1. Keeweb shows popup to select website comes.
1. Select website
1. Popup disappears
1. Slack is open behind the popup. This app gets selected and focus goes into that app.
1. Keeweb fills password into the chatbox. Voila, embarrassingly enough everyone has your username and password now.
1. Go change your password on the website

- what was expected?

Only paste the username/password if the selected app is the one where the action was initiated

- app version

Version **1.3.3 (52701af)**

- your user-agent (from Settings/Help section)

Mac App

- does it happen on Demo or New database?
Yup.
- please, open dev tools in your browser and attach output log from Console tab 
    (if you are using desktop app, devtools can be opened from Settings/General/Advanced)
N/A

**Comment by antelle** [comment]
The proposed fix is to get window title again and run auto-type only after a comparison.
