### ISSUE TITLE
Error with the key file after entering a wrong password

### ISSUE THREAD

**Issue by SwissTico** [keeweb/keeweb#555]
Hello everybody!

We discovered a probable bug, and we are sorry if it is already posted here (in this case you can delete our message).  Our test is only based on G Drive, we didn't test it with a local file or other cloud service, and only on Debian Testing. It was also tested with the parameter "Rember key files > Remember only path to key file".

**Steps**
1. We opened more than one KeePass file
2. We laid it auto-lock
3. We wanted to open the second KeePass file in the list, but forgot to select it, so entered the wrong password to the pre-selected base (last file opened)
4. We selected the right KeePass file in the list and entered the correct password

**Result**
The password is rejected and KeeWeb don't open the file.

**How to fix the problem**
We must deselect the key file, and select it again to open the KeePass file (however we don't need to re-enter the password).

Hope it helps :-)

Thanks for your excellent software.

**Comment by antelle** [comment]
Sorry, I didn't understand you. Could you please write, which files do you have, with passwords or not, and more detailed use case, for example:
I have setting 'keyfiles' set to 'Remember only paths'.
keyfile 1: password, no keyfile
keyfile 2: paddword + keyfile
1. select keyfile 1
2. enter password
3. select keyfile
...etc
I really can't understand the full sequence now.

**Comment by SwissTico** [comment]
Hello Antelle,

Sorry to not be enough clear.

That is our config for the key files
![keeweb-config](https://cloud.githubusercontent.com/assets/19218132/23678078/3b9f825a-0348-11e7-9db1-00f96525d0fd.png)

Those are the steps we are doing
![keeweb-steps](https://cloud.githubusercontent.com/assets/19218132/23678079/3ba370d6-0348-11e7-8db8-9dec332abad5.png)
At the present moment we don't have any KeePass database opened 
1. We want to open the XXX-Network database in G Drive
2. But we forgot to select first the XXX-Network database, so instead, it opens the XXX-Personal database in G Drive (The last one opened / the first one in the list)
3. We entered the password of the XXX-Network database (1) (still thinking opening the other database) and of course it is the wrong one so it can't be opened. Up to here everything normal.

However, now we select (click on) the XXX-Network database (1), enter (again) the correct password (3) for this database, and it is rejected as well.
So we have to empty the key file path (4), select the key file again (no need to re-enter the password (3) ) and it works.

Feel free to ask more details if needed :-)

Thanks!

**Comment by antelle** [comment]
Gotcha.
Thanks for precise steps, I managed to repeat it.
Will be fixed in the next version.

**Comment by antelle** [comment]
Fixed, deployed to [beta.keeweb.info](https://beta.keeweb.info), will be available in the next release.
Thanks again for your time!
