### ISSUE TITLE
Notes are used as sub text?

### ISSUE THREAD

**Issue by DracoMilesX** [keeweb/keeweb#556]
Hello, recently installed keeweb on my nas and just started filling it but I noticed that when I add an entry with "Notes" the grey subtext in the entry list view changes from the "User" text to the "Notes" text.

![keeweb](https://cloud.githubusercontent.com/assets/13802602/23725058/64b95168-044f-11e7-978d-def5e4cebdaa.png)

KeeWeb v1.4.0 (c651343, 2017-02-04)
Environment: web
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:55.0) Gecko/20100101 Firefox/55.0

As well a side question the entry list view is only used for half the screen is this intended?
And how can I change the sub text color from grey to something else if possible?

**Comment by antelle** [comment]
> grey subtext in the entry list view

It shows the fields in this order: notes &rarr; url &rarr; user. If you sort by some field, it will be changed to that field. It's not possible to change it, but you can switch to table view, to be able to see other fields or select the fields you would like to display.
> half the screen 

You can resize it, to make it smaller, drag it's size to do that. Somehow it's very big for you (maybe a bug?), normally it takes less space.
> how can I change the sub text color from grey to something else

You can change it only by changing theme. In the next version, it will be also possible to create a custom theme.

**Comment by DracoMilesX** [comment]
Oke thank you for the information. 

By the looks of it it might be related to browser/caching issue on my pc for the entry list view.
