### ISSUE TITLE
KeeWeb only uses one core for key transformation

### ISSUE THREAD

**Issue by mustaqimM** [keeweb/keeweb#557]
Using KeePass with mono, the database opens in ~4 seconds with the following settings:
Encryption algorithm: AES
Key derivation function - Argon2
Iterations - 1024
Memory - 2
Parallelism - 4

In KeeWeb, it took more than a minute to open, and saving took almost 6 minutes because only a single core was being used.

Is this because of electron, does it only support using a single core?

KeeWeb version: 1.4.0-1
KeePass database version: 2.35

**Comment by antelle** [comment]
We'll support multiple cores once WebAssembly support them, this will happen after MVP, so probably next year: http://webassembly.org/docs/future-features/
Now you're using very slow asm.js version, which sucks a lot. On web, we already support WebAssembly, but Electron doesn't support it at the moment.
In electron, though, we can create a native add-on for hashing, but now it's not the first priority.
