### ISSUE TITLE
[BUG?]half of the entries list is not showing after "Entries List Table View" closed.

### ISSUE THREAD

**Issue by jerrulusfls** [keeweb/keeweb#558]
Version: 1.40_win_x64

Bug description: half of the entries list is not showing after "Entries List Table View" closed.

Step by Step:
1. open "Entries list table view" in Settings
2. come back to the main view
3. go back to setting and turn "Entries list table view" off
4. come back to the main view

Screenshot:
![sp170311_214719](https://cloud.githubusercontent.com/assets/17522475/23823801/4e599f6a-06a5-11e7-99dd-b2aaa59c5f21.png)

**Comment by antelle** [comment]
I can't repeat it.
What is your Windows version?
Does it persist, e.g. when you select an entry or make something else?

**Comment by jerrulusfls** [comment]
1. Windows 8.1 x64
2. Yes. Whatever I do it's still here.
3. Web app version is all right. Seems like only happen in windows app.
4. Yes.
![image](https://cloud.githubusercontent.com/assets/17522475/23829193/beda84cc-0725-11e7-8266-ae7e59803ea3.png)

**Comment by jerrulusfls** [comment]
Update: This stoped to happen after a Windows restart.
Seems like something that happens randomly.
This issue may close now.

**Comment by antelle** [comment]
Some weird layout bug, it's not possible to fix it on our side.
