### ISSUE TITLE
Show both, matching entries and all entries in auto-type

### ISSUE THREAD

**Issue by mammuth** [keeweb/keeweb#559]
The current behavior is, that the search box in the auto-type dialog is filtering the set of displayed sites. Those sites are only the one that seems to match the application we want to fill in our credentials. 

In this case, where the auto-matching fails, I always start typing to search for the wished site and expect to search on all my sites. Instead, a click on "show all entries" is needed.

I have around 400 items in my database, but it does not occur often, that there are false-friends matched (for a dumb example: it does not happen often, that I'm on facebook.com and it does suggest my X facebook accounts PLUS some random accounts that are not associated with facebook). As a result, the list of proposed passwords is rather small and doesn't even need a filter in my eyes.

Maybe we should do an evaluation what behavior is more expected? 

(PS: Is there a keyboard shortcut for "show all entries"?)

**Comment by antelle** [comment]
We can show matching entries first and after them all entries, e.g. separated somehow, so it will not require the button at all, I think it would be the best we can do.

**Comment by mammuth** [comment]
I really like your suggestion! Would probably the best way.

**Comment by antelle** [comment]
Now we'll show all entries, with matching on top. Probably it makes no sense to separate them, because it should be pretty obvious.

**Comment by mammuth** [comment]
Cool, tested it and like the way it is now!

**Comment by antelle** [comment]
Will be live in several weeks, in the next release.
