### ISSUE TITLE
'x' does not remove database from cache

### ISSUE THREAD

**Issue by ryan101** [keeweb/keeweb#561]
Hi,

First, I'm a big fan of this project- it really improves the usefulness of keepass and it's beautiful too!

I've been experimenting with the web version, and I'm either not understanding something or there is a bug with clearing of the cache. My use case is that if I find myself at a public terminal or friend's computer, I would like to be able to point keeweb to a database on my google drive, look up whatever information I need, then sign out of google drive, and clear the keeweb cache so my password database is not left on the computer.

In my tests with firefox and chromium on windows and linux, I've found that I can reliably connect to my google account and load my database. I then sign out of my google account, close the database, and click the 'x' on the recent files list. I also close the browser, re-open it, and make sure that I am definitely logged out of my google drive. However, I can still go to the keeweb web interface, select connect to google drive, and my database will appear without any entering of passwords. I can load the database, but have not found a way to delete it without clearing all private data from browser. 

Besides not being able to delete my password database, I am unable to select a different google account to log into. That is, I click the connect to google drive button and am shown the password database stored on that drive, but I am unable to log into a different google account. 

I could work around the issues described above by using private browsing windows in my use case, but I am still curious if the behavior I'm observing is as designed, or if the 'x' on the recent database list should prevent that database from being loaded again if I'm not signed into my google account.

Thanks for your great work!

**Comment by antelle** [comment]
'x' doesn't unlink google drive. To do so, you should go to Settings and uncheck Google Drive checkbox, then check it again.
