### ISSUE TITLE
More than one keyfile support

### ISSUE THREAD

**Issue by dburucu** [keeweb/keeweb#562]
It's not possible to select more than one keyfile. Keepass supports it.

**Comment by antelle** [comment]
but why??

**Comment by antelle** [comment]
if you find a way to add it without any additional control visible to all users, please feel free to suggest.

**Comment by antelle** [comment]
This adds nothing to security and is very complex to implement in both ux and technical terms. Closing.
Btw, I haven't found a way to do it in KeePass, maybe it's too deep in settings.
