### ISSUE TITLE
Steam Authenticator OTP

### ISSUE THREAD

**Issue by alexfaria** [keeweb/keeweb#564]
It would be cool if KeeWeb could support Steam's authenticator OTP like it does for the normal OTP.
[This](https://github.com/victor-rds/KeeTrayTOTP) is a keepass 2 plugin that does what I mean
Perhaps this could be achieved using something like [node-steam-otp](https://github.com/DoctorMcKay/node-steam-totp)

**Comment by antelle** [comment]
This must be implemented as a plugin, it's not commonly used. Next version will provide an ability to create plugins.

**Comment by alexfaria** [comment]
Thank you, I did look into how to make a plugin but gave up

**Comment by antelle** [comment]
https://github.com/keeweb/keeweb/wiki/Plugins

**Comment by alexfaria** [comment]
I wasnt sure where to access the bit where it displays the otp. Thanks though, keep up the good work.

**Comment by alexfaria** [comment]
I'm trying to make it but I don't understand what you mean by, "Now add your plugin to KeeWeb with this url: http://127.0.0.1:8081", in the documentation you provide. Could you help me with running a plugin?

**Comment by antelle** [comment]
This is the url where you host your plugin, an example is given in the previous line (Host your plugin somewhere, for example ...).

**Comment by alexfaria** [comment]
I get that, what I mean is how do i get the plugin into keeweb

**Comment by antelle** [comment]
Ah I see, you should go to setting->plugins and enter your url there.

**Comment by alexfaria** [comment]
Oh I just realised that's only available on the beta version you have at https://beta.keeweb.info/

**Comment by antelle** [comment]
Sure, plugins are now in beta.

**Comment by C0rn3j** [comment]
Just wanted to point out that KeePassXC now has Steam OTP support (since 2.3.0).

Maybe this could be added as a native feature? They seemed to think it's common enough ^^

**Comment by alexfaria** [comment]
Steam apparently uses the standard TOTP but uses strings, so it might not be that hard to implement
here's a similar issue on andOTP https://github.com/andOTP/andOTP/issues/38

**Comment by eulercamposbarros** [comment]
I'm working on this. I'll make the PR ASAP!

**Comment by antelle** [comment]
Deployed to [beta.keeweb.info](https://beta.keeweb.info), will be available in the next release.

**Comment by monroe-dylan-m** [comment]
It should be noted that the OPT needs to be in URI form like so:
`otpauth://totp/Steam:[steam_username]?secret=[shared_secret_base32]=&issuer=Steam`
You either need the `Steam:[steam_username]` identifier before the parameters, or `issuer=Steam` in order for the new formatting to be used.
