### ISSUE TITLE
[feature request] Global Hotkey

### ISSUE THREAD

**Issue by Arty2** [keeweb/keeweb#565]
One of the most handy features of KeePass, is the [global hotkey](http://keepass.info/help/base/integration.html) that restores the Window to front when minimized, in taskbar or background. By default it is set at `Ctrl + Alt + K`. WOuld it be possible to add this to KeeWeb as well?

**Comment by antelle** [comment]
<img width="987" alt="Screen Shot 2019-10-06 at 12 38 29" src="https://user-images.githubusercontent.com/633557/66267803-36655780-e836-11e9-9c03-c860887c9f77.png">
