### ISSUE TITLE
Add option to 'Minimize when copying to clipboard'

### ISSUE THREAD

**Issue by BWPanda** [keeweb/keeweb#568]
KeePassX has an option to 'Minimize when copying to clipboard', and I'd like to request the same for KeeWeb (apologies if it's already been discussed somewhere, but I searched and couldn't find anything).

This option would allow KeeWeb (the desktop app, not the web app obviously) to be minimized when you copy something to the clipboard. The use case for this would be that you're copying a password onto a website; you open the website, open KeeWeb, copy the password, KeeWeb automatically minimizes, then you can paste straight onto the website.

The closest existing functionality I could find in KeeWeb is 'Auto-lock on password copy', however this locks the app instead of minimizing it (not ideal if you're copying a few things at once (username, password, PIN, etc.).

**Comment by antelle** [comment]
This should be implemented as two options:
On password reset:
[ ] lock
[ ] minimize the app

**Comment by antelle** [comment]
Now auto-type for any field is supported, so I believe this is no longer required.
