### ISSUE TITLE
Minor grammar issue on keeweb.info

### ISSUE THREAD

**Issue by Loilo** [keeweb/keeweb#569]
Just stumbled upon a little thing on [keeweb.info](https://keeweb.info/):

> Desktop apps look *beautifully* on each platform

Correct would be the use of an adjective insted of an adverb though:

> Desktop apps look *beautiful* on each platform

**Comment by antelle** [comment]
Thanks, fixed.
Probably there are a lot of typos, I didn't spend much time on that page.
I was going to check it, but forgot about it. Thank you for the reminder!
