### ISSUE TITLE
Better macOS titlebar

### ISSUE THREAD

**Issue by EnricoMonese** [keeweb/keeweb#570]
I did some changes to make the the titlebar style fit more with the new macOS unified titlebar trend/style.
Code changes are minimal and very unobtrusive,but  if you can achieve the same result with less code changes are welcome
For testing compatibility on windows/linux here is the [branch](https://github.com/EnricoMonese/keeweb/tree/ui)

Edit:
There is already this [pr](https://github.com/keeweb/keeweb/pull/530) which is another option. As suggested there I think we should add an option in the settings. You could the choose to have the default titlebar, the one inside the window or this one which is inset.

These would be the three options
![1](https://cloud.githubusercontent.com/assets/19847464/24325074/432d6372-1192-11e7-9b94-be9b7fa66cf2.jpg)
![2](https://cloud.githubusercontent.com/assets/19847464/24325075/44b5425a-1192-11e7-93e1-93b77378fa7c.png)
![3](https://cloud.githubusercontent.com/assets/19847464/24325076/466ffda6-1192-11e7-9daa-fbd30bf72625.jpg)

**Comment by antelle** [comment]
Hello. Isn't it the same? 
https://github.com/keeweb/keeweb/pull/530

**Comment by EnricoMonese** [comment]
Edited

**Comment by antelle** [comment]
Well, I don't understand the difference with this PR anyway, but you can open a new one, once you add a setting.
