### ISSUE TITLE
RPM releases

### ISSUE THREAD

**Issue by den-is** [keeweb/keeweb#572]
Any ETA for RPM packages?

I'm sure many people will be happy to have ability to install this beautiful app, if not from some RPM repo, but at least manually from RPM package (like Atom).
In my case, I'm using Fedora.

**Comment by antelle** [comment]
We have deb packages at the moment.

**Comment by mikelolasagasti** [comment]
1.4.0 seems to be available from copr:

https://copr.fedorainfracloud.org/coprs/philphil/KeeWeb/

**Comment by mikelolasagasti** [comment]
https://github.com/philphilphil/Fedora-Packaging/blob/master/KeeWeb/KeeWeb.spec

**Comment by den-is** [comment]
Wow, so exiting.
But why they don't provide rpm package on release page, among other 20 urls.

**Comment by andreicristianpetcu** [comment]
I cannot install it in Fedora 25 :(
```bash
$sudo dnf copr enable philphil/KeeWeb
$sudo dnf update -y
$sudo dnf install KeeWeb
Last metadata expiration check: 0:02:32 ago on Mon Jun  5 22:39:47 2017.
Error: nothing provides libffmpeg.so()(64bit) needed by KeeWeb-1.4.0-3.fc25.x86_64
(try to add '--allowerasing' to command line to replace conflicting packages)
$sudo dnf install KeeWeb --allowerasing
Last metadata expiration check: 0:03:08 ago on Mon Jun  5 22:39:47 2017.
Error: nothing provides libffmpeg.so()(64bit) needed by KeeWeb-1.4.0-3.fc25.x86_64
```

What am I doing wrong?

**Comment by mikelolasagasti** [comment]
@andreicristianpetcu KeeWeb bundles libffmpeg.so but that RPM is trying to find it in the system. 

You can install ffmpeg from rpmfusion or you can use the RPM I built in copr https://copr.fedorainfracloud.org/coprs/mikelo2/keeweb/  based on Philip's rpm with a change to use the bundled library.

**Comment by andreicristianpetcu** [comment]
Thank you! Will try!

**Comment by BoKKeR** [comment]
This would be welcomed as the other source seems dead.

**Comment by BoKKeR** [comment]
To anyone searching for a working build. https://copr-be.cloud.fedoraproject.org/results/mikelo2/keeweb/fedora-25-x86_64/00564467-KeeWeb/ I used the one from this link and it works perfectly on Fedora 29

**Comment by mikelolasagasti** [comment]
> To anyone whom is searching for a working build.
> https://copr-be.cloud.fedoraproject.org/results/mikelo2/keeweb/fedora-25-x86_64/00564467-KeeWeb/ I
> have used the one from and it works perfectly on Fedora 29

I've updated the repo to 1.8.0 and tested in F29.

**Comment by TeknoMobil** [comment]
> > To anyone whom is searching for a working build.
> > https://copr-be.cloud.fedoraproject.org/results/mikelo2/keeweb/fedora-25-x86_64/00564467-KeeWeb/ I
> > have used the one from and it works perfectly on Fedora 29
> 
> I've updated the repo to 1.8.0 and tested in F29.

Hello
Keeweb did the installation from the top of the current repo, but the app does not work and does not have the icon. I tried from the command line and it doesn't work there.

System: Fedora 30 Workstation

**Comment by mikelolasagasti** [comment]
@TeknoMobil I've updated the package and now works fine. Desktop file was not updated with correct path. Tested on Fedora-30.

**Comment by TeknoMobil** [comment]
Thank you very much, it works smoothly :+1:
