### ISSUE TITLE
Website icon download doesn't always work

### ISSUE THREAD

**Issue by EnricoMonese** [keeweb/keeweb#576]
As the title says, downloading icons many times doesn't work.
The current method seems to be using some "_cloud_" based code. Maybe stuff like [this](http://stackoverflow.com/questions/10282939/how-to-get-favicons-url-from-a-generic-webpage-in-javascript) could be useful to make it more reliable.
 This is on the latest version

**Comment by antelle** [comment]
you mean, put something like this into thar cloud service downloading favicons?
Now we handle basic cases, we don't try to parse a page

**Comment by EnricoMonese** [comment]
Yeah or something like that. There is no real need to have every case covered but making a bit more reliable would be something.
There is also this `http://www.google.com/s2/favicons?domain=www.example.com` which is quite handy but it gives a 16x16px image and is undocumented API. A quick search gave this http://grabicon.com but it's a paid one, maybe there is some other open source project that does it.

**Comment by antelle** [comment]
Google service (and other public services) cannot be used, it doesn't provide CORS.
We're not going to use paid services or untrusted free services.
Well, there's no purpose to get favicon for absolutely every website, favicon.ico works for most cases. We could also read a webpage and it's favicon there, but I'm not sure if it's legal to do so.

**Comment by antelle** [comment]
This can be closed now, when we have a service for downloading favicons and it seems to handle most of cases, which is its goal.
