### ISSUE TITLE
keeweb config.json not working with kw-config in index.html

### ISSUE THREAD

**Issue by bitking** [keeweb/keeweb#577]
Hiya i just installed the latest version on a self hosted webserver and when setting the kw-config the url with the config.json i get 

"Error loading app
There was an error loading app settings. Please double check app url or contact your administrator. "

I read the wiki page about the json @ https://github.com/keeweb/keeweb/wiki/Configuration but its still not clear how to configure it, i try'd all below configuration settings in index.html.

<meta name="kw-config" content="https://mydomain/?config=config.json">
<meta name="kw-config" content="https://mydomain/config.json">
<meta name="kw-config" content="config.json">

All are not working, what am i doing wrong.

**Comment by bitking** [comment]
It works just not for the following browsers:

Firefox 51.0.1 Built on Ubuntu , running on LinuxMint 18.1 (64-bit)
Version 56.0.2924.76 Built on Ubuntu , running on LinuxMint 18.1 (64-bit)

It do works in:
Internet Explorer 11
Chrome 38 for Windows
havent tested the rest.

**Comment by antelle** [comment]
Please paste the info from browser console and network tab.

**Comment by antelle** [comment]
Please feel free to reopen with more info.

**Comment by JimmyS83** [comment]
Palemoon, example config like:
`{
  "settings": {
    "theme": "fb",
    "locale": "en",
  }
}
`

gives MALFORMED JSON:  https://s14.postimg.org/iejb08x75/Snap1.png

Unfortunatelly cant test against IE11, the page doesnt load, just dark background and title (even without custom config)

https://s8.postimg.org/vis14ym9x/Snap2.png
https://s8.postimg.org/xbzj70wud/Snap3.png

**Comment by antelle** [comment]
Trailig commas (after "en") are not allowed in JSON.

**Comment by JimmyS83** [comment]
Shame on me, you are right! Config are no londer problem  . Do you think, you can help me with finding IE11 problem, or should I open another issue to not mess with this?

**Comment by antelle** [comment]
We don't support IE11 anymore, that's ok.

**Comment by JimmyS83** [comment]
Ow :( Thanks for repluy.  Ok.. I cant test it within Chrome, but Chrome and Mozilla like browser would be maybe sufficient. Could I hope for some support in future, or there is some major issue with IE?

**Comment by antelle** [comment]
No, IE is abandoned by Microsoft and is not updated anymore. We used to support it, and previous release was working in IE, but now we require more: argon2 hashing (for kdbx4 format), plugin support, css theming, [page size improvement](https://keeweb.info/stats/) in the latest release - we cannot implement all of this for outdated browsers, it will: 1. be very slow, probably unacceptable; 2. make the page size larger in twice.

**Comment by JimmyS83** [comment]
Allright. Fair enough. Thanks!
