### ISSUE TITLE
Keeweb doesnt let me use "Save" or "Save File To" on IE11

### ISSUE THREAD

**Issue by bitking** [keeweb/keeweb#578]
- what were your actions?
Go to URL app.keeweb.info or your own selfhosted -> press new -> go to left bottom and press the new keyfile -> press Save to and select file -> you get popup asking to make a password, press yes or no doesnt matter and fill in a password and press save -> the wheel on the key file left bottom keeps on turning and nothing happens.

- what was wrong?
Keyfile doesnt get saved

- app version
KeeWeb v1.4.1 (df218ae, 2017-03-26)

- your user-agent (from Settings/Help section)
User-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; .NET4.0C; .NET4.0E; rv:11.0) like Gecko

- does it happen on Demo or New database?
New database

**Comment by antelle** [comment]
I'll see what happens, but we're going to deprecate IE11 soon.

**Comment by antelle** [comment]
As we're deprecating IE11 in the next version, it's safe to close this issue.
