### ISSUE TITLE
Auto-type hangs after invoking from entry with empty fields

### ISSUE THREAD

**Issue by philogit** [keeweb/keeweb#581]
### Steps to reproduce this issue:
* Locate an entry that 
  1. has no values in User and Password and an empty (default) Auto-type field OR
  1. where the Auto-type field contains value(s) that points to an empty field.
* Invoke auto-type from that entry.
* KeeWeb opens target window and stops.
* Locate an entry that auto-types normally.
* Invoke auto-type from that entry.
* Auto-type does nothing.
* Restart KeeWeb to restore Auto-type.

**Expected:** Auto type should continue to work for future requests, even after encountering an error condition.

#### ...with normal field values, before failure:
```
[auto-type] Resolved [******,key:tab,[*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*],key:enter]
[auto-type] Using auto-type helper /Users/***/Library/Application Support/KeeWeb/helper/darwin/KeeWebHelper
[launcher] spawn /Users/***/Library/Application Support/KeeWeb/helper/darwin/KeeWebHelper: 0, 933ms
[auto-type] Complete 941ms
```
 
#### ...with abnormal field values, during failure:
```
[auto-type] Resolved [,key:tab,,key:enter]
(no further actions)
```

#### ...after auto-type has failed:
```
[auto-type] Already running, skipping event
(no further actions)
```
---
KeeWeb v1.4.0 (c651343, 2017-02-04)
Environment: electron v1.4.15
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) KeeWeb/1.4.0 Chrome/53.0.2785.143 Electron/1.4.15 Safari/537.36

**Comment by antelle** [comment]
Deployed to [beta.keeweb.info](https://beta.keeweb.info), will be available in the next release.
