### ISSUE TITLE
Auto-type hangs on field names containing spaces

### ISSUE THREAD

**Issue by philogit** [keeweb/keeweb#582]
### Steps to reproduce this issue:
* Within an entry, create a new field with a name containing a space, e.g., 'Card Number'.
* Within the same entry, specify keystrokes that refer to the custom field, e.g., {S:Card Number}.
* Invoke auto-type from within that entry.
* KeeWeb opens target window and stops.
* (Auto-type is now inoperable):
* Locate an entry that auto-types normally.
* Invoke auto-type from that entry.
* Auto-type does nothing.
* Restart KeeWeb to restore Auto-type.

**Expected:** Auto type should successfully resolve to fields whose names include a space character. If possible, auto-type should gracefully recover from errors.

### Console output:
```
index.html:16 2017-04-02T21:28:17.226Z [auto-type] Auto type event 
n {cid: "c396", attributes: Object, _changing: false, _previousAttributes: Object, changed: Object…}
index.html:16 2017-04-02T21:28:17.229Z [auto-type] Hide window
index.html:16 2017-04-02T21:28:17.337Z [auto-type] Start {S:Card Number}
index.html:16 2017-04-02T21:28:17.338Z [auto-type] Parsed [op:S]
index.html:16 2017-04-02T21:28:17.339Z [auto-type] Resolved []
```
#### ...after auto-type has failed:
```
2017-04-03T05:24:58.137Z [auto-type] Already running, skipping event
```
---
KeeWeb v1.4.0 (c651343, 2017-02-04)
Environment: electron v1.4.15
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) KeeWeb/1.4.0 Chrome/53.0.2785.143 Electron/1.4.15 Safari/537.36

**Comment by antelle** [comment]
looks like the same as #581, probably will be fixed together
