### ISSUE TITLE
[Feature Request] TOTP for DB encryption

### ISSUE THREAD

**Issue by 3Lies** [keeweb/keeweb#584]
Thanks for this awesome software !

How about add support for TOTP on the database itself?

This may add a huge security layer and permit to shorten our main password :)

Thanks for your job ! 👍 ;)

**Comment by antelle** [comment]
But we support totp, you can even scan the qr code on mobile to enter it. What do you mean?

**Comment by antelle** [comment]
Oh you've edited it. No, database cannt support TOTP, because it's not active: it's not something which can be given access to, but a thing protected with a static key.
