### ISSUE TITLE
Auto-type keyboard layout problems and strange behavior

### ISSUE THREAD

**Issue by mammuth** [keeweb/keeweb#585]
I just installed KeeWeb Desktop on my Arch machine and encountered some errors and strange bahvior.

The system:
- Linux Arch, Gnome 3.22
- xdotool 3.20160805.1-1
- KeeWeb 1.4.1
- The following locale settings (language English, keyboard layout: German)

```
$ localectl status
System Locale: LANG=en_US.UTF-8
VC Keymap: de
X11 Layout: de
X11 Model: deadacute
```

Let's use the following demo entry:

Username: test.demo@gmail.com
Password: i@$*1s^w:Y
Auto-Type: {USERNAME}{TAB}{PASSWORD}{ENTER}

**Steps I did:**
Auto-type this entry into a text-editor. It results in (note the ')' after the linebreak/enter-key hit):
_test.account"gmail.com	i"$(1s&w:Z
)_

I then changed KeeWeb langauge from German to English which results in the following auto-type:
_test.account@gmail.com	i"$(1s&wÖZ
)_

Changed KeeWeb language to German again:
_test.account@gmail.com	i"$(1s&wÖY
)_

Changed nothing, just did the auto-typing again:
_test.account@gmail.com	i"$(1s&wÖZ
)_

Changed nothing, just did the auto-typing again:
_test.account@gmail.com	i"$(1s&wÖY
)_

Final step: Be like _dafuq_ :open_mouth: 

I have no idea what's going on here, did anyone encounter a similar problem? The Chrome console didn't log anything locale / character map related. 
Can I provide any further information / testing?

**Comment by antelle** [comment]
Could you please try `xdotool key U7a` in terminal? It must print Z.

**Comment by antelle** [comment]
looks like #441

**Comment by mammuth** [comment]
The linked issue looks similar, indeed!

`xdotool key U7a` actually does print `Z`.

However:
```
$ setxkbmap -query | grep layout
layout:     de,us
```

After setting the xdotool layout to de only, it's working. :+1: 

I'm closing this since it's probably a dupe of 441 (which I wasn't able to find via the awesome GitHub search. Mea culpa).
