### ISSUE TITLE
[Feature] Autotype: No username+tab, only password

### ISSUE THREAD

**Issue by bbzg** [keeweb/keeweb#588]
(I use OSX, but this probably applies to at least Linux as well)

# Only password

* In some uses cases only password is needed - e.g. Terminal

## Motivation

When using ssh you normally input the username and domain first, e.g. `ssh user@domain.com`, then you need the password. At this point it would be useful to bring up autotype dialog, find the correct entry by searching (this is already possible), then somehow select a row and only input the password

## Possible ways of solving

* A checkbox in the autotype dialog to disable username + tab, just input password
* A special key kombination to input only the password (shift+enter, ctrl+enter, or similar)

Might be useful for other things than terminal

P.S: I LOVE keeweb!

**Comment by antelle** [comment]
It's already here.
To change the auto-type sequence, please go to Entry auto-type settings / Group settings / File settings (whichever you like more) and change the sequence to `{PASSWORD}{ENTER}` or `{PASSWORD}`.

**Comment by bbzg** [comment]
Wow this really is the perfect app. Thank you so much!

**Comment by bbzg** [comment]
@antelle I have identified a use-case for my request (selecting the type of sequence dynamically) - sometimes e.g. google will ask for ONLY your password (my work domain expires every 30 days), in that case I can't use autotype because normally I sign in using username and password...

Please tell me this is also already available ;)

**Comment by antelle** [comment]
I don't think anybody will be able to understand, why there are two sequences and how to use different auto-types, this is way too complex. Probably it makes sense just copy a password and paste it. There's a setting 'minimize on copy', so the app could also be minimized after it automatically.
