### ISSUE TITLE
[Wrong Translation]"Copied for 15 seconds." in Chinese

### ISSUE THREAD

**Issue by jerrulusfls** [keeweb/keeweb#589]
Problem: Wrong Translation for "Copied for 15 seconds."

Description: After you click on the "Passwords", the password will be copied and a message will be shown. But the translation of this message is wrong in Chinese.

Original Text: Copied for 15 seconds.
Current Translation: 复制完成用了15秒。(In English: It takes 15 seconds to finish copy.)
Correction: 复制项将在15秒后失效。(In English: The item copied will be erased from clipboard in 15 seconds.)
Sorry for I can't find a better translation, but this is the best and the shortest translation I can find.

**Comment by antelle** [comment]
Translations are managed with OneSky, please update this tag: 
http://keeweb.oneskyapp.com/collaboration/translate/project/project/173183/language/3#/?keyword=detFieldCopiedTime
