### ISSUE TITLE
oneDrive doesn't show added files immediately

### ISSUE THREAD

**Issue by paul-alkhimov** [keeweb/keeweb#592]
It is a minor thing, but still it cost me some time and nerves.
The sequence is following 1) I added the file on oneDrive and 2) logged with KeeWeb to oneDrive. The problem was, the KeeWeb did not find the file even after many retries. So searched the web for solutions. As I did not give up and tried many times, some time later the problem disappeared.

So I suggest to add something like **sync can take some time** so that user is not misleaded.

**Comment by antelle** [comment]
Ideally, we should list it immediately, but I'm not sure it if's possible with onedrive, I'll try to find something about it.

**Comment by antelle** [comment]
I believe this is now fixed.
