### ISSUE TITLE
Add an option for caching files from Filesystem

### ISSUE THREAD

**Issue by poscar** [keeweb/keeweb#593]
## Steps
Currently, if I:
1. Open a KeePass file with KeeWeb
2. Add/remove entries and save the file.
3. Close the file.
4. File goes away from the filesystem (e.g. network mapped drive disconnected, unmounted filesystem, etc...)
5. Attempt to re-open the file by clicking on it from KeeWeb's recent file list.

## Result
`File Not Found` error.

## Expected Result
Cached file is opened using data from local storage.  Could be in read-only mode, but preferably allow for synchronization once the filesystem is accesssible.

Is there any current way to enable this automatic caching of local files in KeeWeb?  If not, is this feature planned?

Otherwise, I might take a stab at this over a weekend. and submit a PR.

Thanks!

**Comment by antelle** [comment]
This is considered as something which should never happen, because if you open a file from cache and think it's from a filesystem, there will be a huge confusion. We used to do it previously, and it was removed. In this case, it's better to restore the file manually.

**Comment by poscar** [comment]
Isn't this the same use-case as opening a Dropbox file with no network connection?

**Comment by antelle** [comment]
No, when you open a file from Dropbox, it's opened from cloud, something which you don't have access to, if you go offline. Filesystem is considered to be a reliable storage, where we don't have to create additional cache.

**Comment by antelle** [comment]
Another issue was that when you open a file from a file storage and physically eject it, you don't want this file to be available anywhere in cache. When we cached them, it caused a lot of misunderstanding and wtf-questions.

**Comment by poscar** [comment]
In most operating systems you can have a a network drive mounted which is not "reliable".

I definitely see the confusion with ejecting a thumbdrive or another physical storage and seeing your data still there.  Perhaps this could be `disabled` by default, but configurable from the "file" settings...

For my use-case, the password for my NAS is within my KeePass file, but I plan on keeping my KeePass file in my NAS.  If I restart the NAS and need to type the NAS password again, there's no way for me to get that password using KeeWeb. 

I could keep a local copy of my password on various machines, but that kind of defeats the purpose if there's a perfectly usable local storage mechanism available..

**Comment by antelle** [comment]
That makes sense. Making it configurable is a good idea, let's open it. However it will require some effort.

**Comment by antelle** [comment]
This is now fixed, forgot to close the issue.

**Comment by LorenzoFioroni** [comment]
Good morning,

I'm experiencing the very same issue under Kubuntu 20.10, with KeeWeb 1.16.1.
I have my NAS mounted as cifs Network File System, where the KeePass file is stored.

When I am not at home I can't access the NAS but It would be important to have access to my passwords anyway. When I try to open a previously opened file on KeePass, though, if the nfs folder is not mounted it fails with the error `File not found`.

Under the settings I cannot find any entry to enable some caching functionality, apart from "Backup this file". Is that the option to enable or am I missing something?

Thank you,

Lorenzo
