### ISSUE TITLE
Sync error

### ISSUE THREAD

**Issue by ChrisBdk** [keeweb/keeweb#595]
When I try to sync to Google Drive, I get an error.
Last sync: (correct time and date)
Sync error: [object Object]

KeeWeb v1.4.1 (df218ae, 2017-03-26)
Environment: electron v1.3.3
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_4) AppleWebKit/537.36 (KHTML, like Gecko) KeeWeb/1.3.3 Chrome/52.0.2743.82 Electron/1.3.3 Safari/537.36

**Comment by antelle** [comment]
Please add more details, i.e. go to dev console, expand this [object Object] and paste it here.

**Comment by antelle** [comment]
please reopen with more info.
