### ISSUE TITLE
WebDAV access fails when behind proxy

### ISSUE THREAD

**Issue by kochs-online** [keeweb/keeweb#596]
I'm trying to use a self-hosted version of KeeWeb to have access to my passwords while at work. While at home I set up a working WebDAV and made sure KeeWeb can access the files stored there.
However KeeWeb reports an error whenever I'm trying to open the WebDAV files from my working place where we are required to use a proxy (with authentication).

**- what were your actions?**
opening a .kdbx file via WebDAV protocol

**- what was wrong?**
getting a HTTP 401 error ["Authorization Required"] although user/password is correct

**- app version**
KeeWeb v1.3.1 (234333d, 2016-09-02)

**- your user-agent**
Mozilla/5.0 (Windows NT 6.1; WOW64; rv:45.0) Gecko/20100101 Firefox/45.0

**- does it happen on Demo or New database?**
no (no WebDAV access)

**- if you are using a test db without your personal data, please attach it**
n/a

**- please, open dev tools in your browser and attach output log from Console tab**
```
2017-04-11T11:30:04.662Z [storage-webdav] Stat "https://webdav.example.com/file.kdbx" keeweb:13:6475
HEAD XHR https://webdav.exmaple.com/file.kdbx [HTTP/1.1 401 Authorization Required 133ms]
2017-04-11T11:30:07.723Z [storage-webdav] Stat error "https://webdav.example.com/file.kdbx" 401 3061ms keeweb:13:6475
```
A file of the HTTP request/response is attached:
[http request-response.txt](https://github.com/keeweb/keeweb/files/913131/http.request-response.txt)

Maybe this issue is related to the way KeeWeb is trying (or not) to do the proxy authentication?

Possible causes that I have tried to rule out:
**- wrong credentials**
I double-checked the user/password combinations and used them to access the WebDAV resources directly (see next point).
**- proxy blocking access to these WebDAV URIs/files**
Accessing the WebDAV files directly by entering the URI in my browser's address bar works perfectly fine, so it's not the proxy blocking requests to the WebDAV URI.
**- misconfigured WebDAV server**
The same setup works from home.

Analyzing the server's logs I cannot find an entry for a failed authorization request. So it seems like the request doesn't even reach the WebDAV server. (Log entries are created, if I use wrong credentials deliberately while accessing the files from home.)

**Comment by antelle** [comment]
The only possibility is to fix the proxy.

**Comment by kochs-online** [comment]
Why do you think the proxy is causing this issue? Accessing the WebDAV files from behind the proxy is working as long as I don't use KeeWeb (same browser, same session, same credentials, ...).

Requesting https://www.example.com/file.kdbx from the browser's address bar: ok
Requesting https://www.example.com/file.kdbx from KeeWeb's open dialog: not ok

I'd be ok with the proxy being responsible, but right now I can't see that. Anything I can check to support one or the other theory?

**Comment by antelle** [comment]
Of course, we cannot support everything which is supported by browser.

**Comment by Vagrantin** [comment]
Hello  
 I'm experiencing this issue has well and I think it would be a good feature to have it working behind proxy. since it's a Webapp, supporting proxy is natural for me.

Matth
