### ISSUE TITLE
libgconf-2.so.4: cannot open error in Ubuntu 17.04

### ISSUE THREAD

**Issue by countableSet** [keeweb/keeweb#600]
what were your actions?
Install keeweb using `dpgk -i` on a fresh install of Ubuntu 17.04 amd64 desktop, then try to open the app.

what was wrong?
App failed to launch, flashing in the dock/launcher and never starts.

app version
KeeWeb-1.4.1.linux.x64.deb

your user-agent (from Settings/Help section)
KeeWeb v1.4.1 (df218ae, 2017-03-26)
Environment: electron v1.4.15
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML,
like Gecko) KeeWeb/1.4.1 Chrome/53.0.2785.143 Electron/1.4.15
Safari/537.36

does it happen on Demo or New database?
N/A happens before getting to database menu.

if you are using a test db without your personal data, please attach it
N/A

please, open dev tools in your browser and attach output log from Console tab (if you are using desktop app, devtools can be opened from Settings/General/Advanced)
N/A, but was able to get logs from
```
$ tail -f /var/log/syslog
Apr 16 17:55:24 ubuntu compiz[2025]: /opt/keeweb-desktop/KeeWeb:
error while loading shared libraries: libgconf-2.so.4: cannot open
shared object file: No such file or directory
```

Found this issue https://github.com/electron/electron/issues/1518 thus might need to add dependency for gconf2.
Looking at the atom deb package dependencies, seems they do add gconf2

**Comment by antelle** [comment]
Thanks for the detailed report!
It looks like it was preinstalled on earlier Ubuntu versions 😕

**Comment by antelle** [comment]
Dependency added, tested new deb on fresh Ubuntu 17.04, after running `sudo apt-get install -f` KeeWeb can be started.
