### ISSUE TITLE
Passwords lost

### ISSUE THREAD

**Issue by fotosmotos** [keeweb/keeweb#601]
file .kdbx was located on the google drive, adding of password to the file automaticly brings it to all computers.

Yesterday file at google drive was replaced to the old one and all new passwords stored for a half of year were lost. I don't understand the reason of such replacing and mechanizm of solving the problem.
I also cannot find any .kdbx file at the PC locally (thought may be keeweb store it temporaly at the drive).

KeeWeb v1.4.1 (df218ae, 2017-03-26)
Environment: web
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.76 Safari/537.36

**Comment by antelle** [comment]
We'll not be able to anything without logs.
Google Drive stores file history, maybe you can find your file there.

**Comment by fotosmotos** [comment]
How to get file logs?

**Comment by antelle** [comment]
They're available in Settings &rarr; General, but only for active session, i.e. while the app is still running. We don't store logs, because they can contain sensitive information.
