### ISSUE TITLE
AutoTypeFilter does not remove wwws subdomain

### ISSUE THREAD

**Issue by lawrencium** [keeweb/keeweb#602]
When auto-typing in a browser on a URL with a wwws subdomain (eg, https://wwws.website.com), the wwws is not filtered out during the prepareFilter() step in auto-type-filter.js. This results in a this.urlParts of ["https://wwws.website.com", "https://", "wwws.website.com"] which means that the website url for a matching entry must be "wwws.website.com" and not "website.com" for the entry to earn a high rank. I think that "wwws" should have the same treatment as "www" and not be required in the entry url. 

We could fix this by changing the domain check (line 51 of [auto-type-filter.js](https://github.com/keeweb/keeweb/blob/develop/app/scripts/auto-type/auto-type-filter.js#L51)) from

> entryUrlParts[2] === this.urlParts[2]

to 

> entryUrlParts[2].includes(this.urlParts[2]) || this.urlParts[2].includes(entryUrlParts[2])

This greatly relaxes the equality check, but I think it's ok -- if the expression returns true, I'd be fairly confident that the two urls reside on the same domain. And, another advantage of this is the urlPartsRegex can be simplified to not have to match against "www."

The idea of simplifying regexes leads me to my final point... what are your thoughts on parsing the url without the use of regexes? I think regexes can be difficult to comprehend and reason about. Rather than using a regex, we could do something like [this](https://gist.github.com/jlong/2428561). I think it would improve code-readability.

**Comment by antelle** [comment]
Automatically using a password from xxx.domain.com on yyy.domain.com is not something we want, but www, wwws and secure are special. Added them, it should cover the majority of cases.

**Comment by lawrencium** [comment]
Oh shoot... I did not think about `you-got-screwed-domain.com`. I think this is why you chose for an equality check. Thanks!
