### ISSUE TITLE
Installing plugins requires https

### ISSUE THREAD

**Issue by EnricoMonese** [keeweb/keeweb#606]
The wiki [here](https://github.com/keeweb/keeweb/wiki/Plugins#testing-your-plugin) doesn't say that you need https but it looks like it is needed.
The wiki should be updated and maybe `Error loading plugin manifest`in Keeweb is a bit too generic.

**Comment by antelle** [comment]
Sure, added it to plugins page, thanks.

**Comment by EnricoMonese** [comment]
Also just noticed that it complains about **Access-Control-Allow-Origin** headers too. This is fixed by using the `--cors` argument. And apparently that also gets rid of the http**s** errors, weird as it should still be normal http.
`http-server -c-1 --cors -p8081`

**Comment by antelle** [comment]
added it as well
