### ISSUE TITLE
Custome changes

### ISSUE THREAD

**Issue by absalan** [keeweb/keeweb#607]
Hi @antelle ,
I'm trying to add new option for entries but didn't work for me. please take a look at the image below.
So I'm trying to add an option on new entry and when I click on that a new entry with custom fields as you see on the image below show up. please help me let me  #know how I can do that,
Thanks
![keeweb1](https://cloud.githubusercontent.com/assets/893480/25239671/7b6bf40c-25a5-11e7-9d7f-c63075110b61.JPG)

**Comment by antelle** [comment]
Sorry, I didn't understand what you're trying to do. Are you trying to implement templates?

**Comment by absalan** [comment]
@antelle Thanks for quick response. I don't know if you call it template or new feature but it's kind of new feature. As you see on the picture I need to create new option on create new "custom" entry menu, It will show custom key with two fields "title and Note".
Thanks all I need to do.
Le t me know if you need more info.
Thank you

**Comment by antelle** [comment]
I still don't underdtand how you're going to save it to the db, but you can tweak entry editor (details-view) and for this.

**Comment by absalan** [comment]
@antelle I don't want to change the entry key view. I need to add it as new option for adding notes and perhaps it should be saved to database.

**Comment by antelle** [comment]
Then you can add your own view for this.
But still, I don't understand, how you're going to save it to the db, because we must be compatible with keepass.

**Comment by absalan** [comment]
Sounds good but where I should add my codes or what file I should change. Also I think it's compatible with keepass. All other field will be null or 0 for data. I just need the title and the note part of the key. How I can save it to database?

**Comment by antelle** [comment]
Please find some existing ui element, see how it works and implement yours like this. Like it's usually done 😋

**Comment by absalan** [comment]
Is there a way to do this with creating plugin?

**Comment by antelle** [comment]
Yes. But please don't ask, how exactly.

**Comment by absalan** [comment]
Ok thanks anyway.
