### ISSUE TITLE
Sass for plugins css

### ISSUE THREAD

**Issue by EnricoMonese** [keeweb/keeweb#608]
Would it be possible to use .scss files in the plugins?

**Comment by antelle** [comment]
Feel free to use any builder to make output css. Of course, we'll not include buildet in keeweb.
Same for ES6.

**Comment by EnricoMonese** [comment]
Yeah makes sense. But wanted to try anyway. Guess I'll try cleaning up the classes a bit to make theming a bit easier.

**Comment by antelle** [comment]
Theming is almost impossible now, yes, we need some theme builder in future versions.

**Comment by EnricoMonese** [comment]
The fact that each section has a class like `app__list` makes things a bit easier. But changing for example the hover color of all buttons is a mess. :/

**Comment by antelle** [comment]
yes, that's why we need theme builder.

**Comment by antelle** [comment]
or structural changes (not this version, requires quite a lot of thinking)

**Comment by EnricoMonese** [comment]
Trying some things https://github.com/EnricoMonese/keeweb/tree/theming
For now I just moved the appearance settings in a new section. Will try some color picker sort of things now

**Comment by EnricoMonese** [comment]
What about this one http://www.dematte.at/colorPicker/ ? It's a bit advanced but should be without jquery and has a simplified UI option.
And how would a choosen color be applied to the css. Should a css file be generated?

**Comment by EnricoMonese** [comment]
Moving to #611
