### ISSUE TITLE
Auto-type with obfuscation very slow

### ISSUE THREAD

**Issue by rodrigo-pedro** [keeweb/keeweb#616]
I'm using the latest version of Keeweb. When i use the global auto-type key (shift+alt+t) it takes like 7 seconds to insert the credentials completly, as opposed to keepass 2 which takes max 2 seconds. Keep in mind i'm using passwords with obfuscation auto-type. Is there any fix?

**Comment by antelle** [comment]
Maybe we can try to change some timeouts. Could you please paste the logs?

**Comment by Rody00** [comment]
[DEBUG] 2017-04-30T17:33:08.675Z [auto-type] Auto type event 
[DEBUG] 2017-04-30T17:33:08.681Z [auto-type] Get window title
[DEBUG] 2017-04-30T17:33:08.681Z [auto-type] Using auto-type helper C:\Program Files\KeeWeb\resources\app\helper\win32\KeeWebHelper.exe
[INFO ] 2017-04-30T17:33:09.781Z [launcher] spawn C:\Program Files\KeeWeb\resources\app\helper\win32\KeeWebHelper.exe: 0, 1089ms
Bohemia Accounts - Google Chrome
https://account.bistudio.com/auth?redirect_url=https:%2F%2Fwww.bistudio.com%2Fprofile%2Flogin&session=true&client_id=$635d4b976b90b04b7255c32bc0d43f9&client_secret=null&redirect_back=https:%2F%2Fwww.bistudio.com%2F
[DEBUG] 2017-04-30T17:33:09.782Z [auto-type] Window title Bohemia Accounts - Google Chrome https://account.bistudio.com/auth?redirect_url=https:%2F%2Fwww.bistudio.com%2Fprofile%2Flogin&session=true&client_id=$635d4b976b90b04b7255c32bc0d43f9&client_secret=null&redirect_back=https:%2F%2Fwww.bistudio.com%2F
[DEBUG] 2017-04-30T17:33:09.784Z [auto-type] Hide window
[DEBUG] 2017-04-30T17:33:09.786Z [auto-type] Start {USERNAME}{TAB}{PASSWORD}{ENTER}
[DEBUG] 2017-04-30T17:33:09.787Z [auto-type] Parsed [op:USERNAME,op:TAB,op:PASSWORD,op:ENTER]
[DEBUG] 2017-04-30T17:33:09.788Z [auto-type] Resolved [******************************,key:tab,[*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*],key:enter]
[DEBUG] 2017-04-30T17:33:09.795Z [auto-type] Obfuscated
[INFO ] 2017-04-30T17:33:16.439Z [launcher] spawn C:\Program Files\KeeWeb\resources\app\helper\win32\KeeWebHelper.exe: 0, 6639ms
[DEBUG] 2017-04-30T17:33:16.441Z [auto-type] Complete 6655ms

**Comment by antelle** [comment]
Yes, and all of them spent inside helper, which means typing.

**Comment by antelle** [comment]
Let's check this in v1.17, auto-type should be faster now.
