### ISSUE TITLE
Config.json loading error

### ISSUE THREAD

**Issue by sh0eps** [keeweb/keeweb#617]
Hi !

With the last rev of self hosting app, i'm getting in trouble when trying to load my config.json.

I checked in the network tab, the file is read and in console tab the error message is : [app] Error loading app config – "OK" 

Any clue ? I tried with Safari / Chrome but the problem still.

I'm trying to get the same behavior than in a previous version which is : store Dropbox app key somewhere :)

Thank you !

**Comment by antelle** [comment]
Hi! It looks like your config is empty. Could you please inspect what you get in Network tab, is it in the response?

**Comment by sh0eps** [comment]
Hi ! Thank you for answering. Unfortunately, my config.json retrieved isn't empty :).

Here is the content : 
`{
  "settings": {
    "theme": "fb", // UI theme, possible values: fb (flat blue), wh (white), hc (high contrast) and other
    "locale": "en", // language
    "expandGroups": true, // show entries from all subgroups
    "listViewWidth": null, // list view width
    "menuViewWidth": null, // left menu width
    "tagsViewHeight": null, // tags menu section height
    "autoUpdate": "install", // auto-update options: "install", "check", ""
    "autoSave": true, // auto-save open files
    "rememberKeyFiles": false, // remember keyfiles selected on Open page
    "idleMinutes": 15, // app lock timeout after inactivity
    "tableView": false, // view entries as table, instead of list
    "colorfulIcons": false, // use colorful custom icons, instead of grayscale
    "lockOnCopy": false, // lock app on password copy
    "skipOpenLocalWarn": false, // don't show warning for local files
    "hideEmptyFields": false, // hide empty entry fields
    "skipHttpsWarning": false, // don't show insecure http connection warning
    "demoOpened": false, // think that demo has already been opened, hide Demo button inside More
    "fontSize": 0, // global font size, possible options: 0, 1, 2
    "tableViewColumns": null, // columns inside table view (complex option, use with care)
    "generatorPresets": null, // user-defined generator presets (complex option, use with care)
    "cacheConfigSettings": false, // allow to start the app if the config is not available

    "canOpen": true, // show Open button
    "canOpenDemo": true, // show Demo button
    "canOpenSettings": true, // show Settings button
    "canCreate": true, // show Create button
    "canImportXml": true, // show Import XML button

    "dropbox": true, // enable Dropbox
    "dropboxFolder": null, // default folder path
    "dropboxAppKey": null, // custom app key

    "webdav": true, // enable WebDAV
    "webdavSaveMethod": "move", // how to save files with WebDAV ("move" or "put")

    "gdrive": true, // enable Google Drive
    "gdriveClientId": null, // custom client id

    "onedrive": true, // enable OneDrive
    "onedriveClientId": null // custom client id
  },
  "files": [{ // pre-defined files that will appear on Open page
    "storage": "webdav", // dropbox, webdav, etc...
    "name": "My file", // file name, as it will be displayed in UI
    "path": "webdav-url", // full path to file, including file name, e.g. WebDAV url
    "options": { "user": "", "password": "" } // only for WebDAV, server auth details
  }],
  "showOnlyFilesFromConfig": false // allow to open only files from config, remove previously opened files
}

`

I copy paste the example given

**Comment by antelle** [comment]
You should not copy-paste it, it's invalid JSON.
Please create a config from scratch (i.e. `{}`) and add keys you need.

**Comment by antelle** [comment]
I changed error handling, so now it will say `Malformed JSON` instead of this weird `OK`;

**Comment by sh0eps** [comment]
Yay, nice ! Thank you for your support :)
