### ISSUE TITLE
[Feature request] Support for Google TeamDrive (aka Shared Drive)

### ISSUE THREAD

**Issue by bkix** [keeweb/keeweb#618]
Hi,

Google has released a new Feature in Google Drive called "TeamDrive" [1] some weeks ago. 
This is a totally useful and long needed feature and it would be nice to support it in keeweb.

As of now I can't see any *.kdbx Files that are located in a TeamDrive, when i want to open through the Drive option.

To this date there is no "sync-client" (will be beta in some weeks called "Google Drive FileStream"),
so it may be not possible to implement it just yet, because the API needs to support it, too(?)

Regards
Ben

[1] https://support.google.com/a/answer/7212025?hl=en

**Comment by antelle** [comment]
We'll have to support root folder chooser UI for this.

**Comment by titix12** [comment]
a quick fix is to add a few options to the queries :  supportsTeamDrives=true
(and an extra includeTeamDriveItems=true for the List method)

https://developers.google.com/drive/v3/reference/files/list

I was a big fan of the file extension filter (fileExtension="kdbx"), with this option no need to worry about the root folder !

**Comment by Jhiino** [comment]
Up! This could be very useful.

**Comment by Nu11u5** [comment]
This would be useful for our group.  Currently the only way to find a shared .kdbx file is to use normal sharing and manually navigate through the "GDrive > Shared with me" file list with the filter disabled (an active user or group would have thousands of files - terrible UX!).  At the very least an option to provide a URL to the file would help.

**Comment by JEricaM** [comment]
Something changed about this topic?
@Nu11u5 how di you solved? Have you added the file url in your config? 
```
 "files": [{ 
      "storage": "gdrive",
      "name": "name",
      "path": "url"
    }],
```

**Comment by razielvamp666** [comment]
@antelle 
Thank you for redirect to this issue, but...
is there any progress since 2017? Any plans to add this feature?

At least can you point the file where I may edit api requests according @titix12 solution?

**Comment by antelle** [comment]
It's a pity that it's not possible to test it without TeamDrive, that's why it's not fixed yet.  
I assume, I can subscribe to Google Business Suite for a month and figure it out, if they don't require any official business confirmation.

**Comment by bkix** [comment]
Oh.. I'll be happy to help you out with that @antelle 
Just give me an gmail.com address and i'll invite that account to a sharedDrive. 

You just can't create SharedDrives without a Business license, but you can contribute to one with a standard (invited) gmail-Account.

**Comment by bkix** [comment]
Never mind. Just found your address and invited you to a SharedDrive.

**Comment by antelle** [comment]
Hey, thank you! Could you please invite this account instead? `keeweb.tester@gmail.com`
Google advanced account protection doesn't give a possibility to connect apps (including your own), and I have it enabled all my non-testing Google accounts.

**Comment by bkix** [comment]
Sure. Just changed to that account.

**Comment by antelle** [comment]
Ok, thank you very much! I've uploaded some files to that drive and I'll try to check what needs to be done in KeeWeb this weekend.

**Comment by antelle** [comment]
What do yo u think?

https://user-images.githubusercontent.com/633557/114086463-ef38a680-98b2-11eb-80de-7a4681b0a458.mov

You can try it on [beta](https://beta.keeweb.info/?refresh).

**Comment by aslafy-z** [comment]
@antelle Could you release a docker image for this branch so I can test on my side?

**Comment by bkix** [comment]
@antelle nice.. and you were fast :)
A quick test gave me all i expected. 
Maybe one tip: Google renamed "Team Drive" to "Shared Drive" some time ago. Maybe you want to change that too. 
https://support.google.com/a/answer/7212025?hl=en

**Comment by antelle** [comment]
Cool, glad that it works and thanks for the testing account @bkix! 🙏  
Ok, thanks, forgot that it "Shared Drive" now, renamed the button of course.

I don't release Docker images without releasing KeeWeb so that they match each other, but I can make a release with this feature because it shouldn't break anything. I'll release it soon then.

**Comment by antelle** [comment]
It's rolled out! Now finally you should be able to use shared drives 🎉
