### ISSUE TITLE
Request for .deb for 32 bit linux

### ISSUE THREAD

**Issue by adatum** [keeweb/keeweb#619]
Could a .deb of the desktop app be provided for 32 bit linux systems?

**Comment by antelle** [comment]
Is there a lot of users with 32-bit linux now?

**Comment by adatum** [comment]
A lot of users? I don't know, but some of my old hardware isn't even capable of 64-bit.

I wanted to try Keeweb but as I'm not familiar with node/js, I didn't understand how to build with `grunt` etc.

**Comment by antelle** [comment]
But we provide 32-bit zip packages for this: https://github.com/keeweb/keeweb/releases/latest

**Comment by adatum** [comment]
How is that zip to be used?

**Comment by antelle** [comment]
Unpack and launch: it contains the same as in deb.

**Comment by adatum** [comment]
Oh, sorry, I had not seen the executable `KeeWeb` file in that archive before. 

Aside, I would suggest having a table quickly listing the features and possibly compare with KeePass2, KeePassXC, and maybe even others like SpiderOak's Encryptr. It would augment the already visually appealing feature breakdown on keeweb.info 

Thanks for making and actively maintaining this interesting project!

**Comment by antelle** [comment]
Let's keep this issue open for some time, to understand the demand in 32-bit debs.
I'll think about feature table, but we already have something like [this page](https://github.com/keeweb/keeweb/wiki/Unsupported-Features), highlighting the features we're not considering. Not sure if we should list something that we (will) support, but we can put it to [wiki](https://github.com/keeweb/keeweb/wiki), because it's kinda tech stuff.

**Comment by avh-on1** [comment]
+1 for a 32-bit version

**Comment by antelle** [comment]
Next version will have 32-bit deb. However we might want to remove it later, if there will be few downloads.

**Comment by antelle** [comment]
Do, 32-bit deb has been downloaded 16 times during the first 8 hours. Well, there's definitely some demand for it, let's leave it there.

**Comment by adatum** [comment]
Old hardware everywhere thanks you. 

Aside, I'm very glad that KeeWeb is also web-hosted, as that is very convenient for quick use without installation.
