### ISSUE TITLE
[Bug] Middle-click clipboard not cleared

### ISSUE THREAD

**Issue by adatum** [keeweb/keeweb#620]
The middle-click clipboard (Ubuntu 16.04 32-bit, MATE desktop environment) is not cleared as per the "Clear clipboard after copy" setting. The Ctrl-V clipboard is cleared as expected.

Reproduced with the Demo Database and desktop version of KeeWeb. The web version does not seem to have the clipboard clearing feature (feature request?). 

Version/user-agent info: 
```
KeeWeb v1.4.1 (df218ae, 2017-03-26)
Environment: electron v1.4.15
User-Agent: Mozilla/5.0 (X11; Linux i686) AppleWebKit/537.36 (KHTML, like Gecko) KeeWeb/1.4.1 Chrome/53.0.2785.143 Electron/1.4.15 Safari/537.36
```

For comparison, I tried the same test with KeePass and KeePassXC, which clear both clipboards.

**Comment by antelle** [comment]
I don't understand what you are talking about.

**Comment by adatum** [comment]
In linux, highlighting text with the mouse can be used to copy, and middle-clicking the middle mouse button to paste. This is one clipboard, in addition to the usual Ctrl-C/Ctrl-V clipboard. I frequently use the highlight/middle-click functionality as it's faster.

When copying fields from KeeWeb (and other password managers) by clicking their field title, the username/password/etc gets copied to both clipboards.

https://askubuntu.com/questions/167570/how-does-middle-click-paste-work/167577#167577

**Comment by antelle** [comment]
I guess, it's not supported in Electron.

**Comment by adatum** [comment]
Copying works fine and goes to both clipboards. The problem is that only the Ctrl-V clipboard is being cleared by KeeWeb after the set delay. 

The middle-click clipboard retains passwords indefinitely until overwritten.

**Comment by antelle** [comment]
We just call the only available `clipboard.clear` method, if it doesn't clear both of them, it means that it's not supported... There's no other API we can call.

**Comment by antelle** [comment]
I think that you should not mention keeweb when posting issues to electron, probably they will not download all apps trying to debug the issue. I would create a simple demo for electron issue request instead.

**Comment by adatum** [comment]
I'm not familiar enough with electron to make such a demo, but if you have the time to do so, I'm willing to test it and update the issue posting.

**Comment by antelle** [comment]
I see that the issue is accepted by electron maintainers, cool.

**Comment by hesalx** [comment]
@antelle It look like there is access to both clipboards on Linux now.
Please see https://www.electronjs.org/docs/api/clipboard

You can even check that it's indeed working from dev tools on KeeWeb app.
```js
const { clipboard } = require('electron')
clipboard.clear() // Ctrl+V pastes nothing now
clipboard.clear('selection') // middle mouse button in Terminal pastes nothing now
```

**Comment by antelle** [comment]
Cool, thanks, I'll add it in the next version
