### ISSUE TITLE
[Improvement] Provide checksums for binaries

### ISSUE THREAD

**Issue by bkix** [keeweb/keeweb#623]
Hi,

in addition to https://github.com/keeweb/keeweb/issues/196, could you please provide checksums for the binaries?
Maybe on two separate pages like the downloadpage and here on github.

As said in the other issue this is a security app that needs trust. So checksums help building this trust.

Regards 
Ben

**Comment by antelle** [comment]
only for linux builds: everything else has sugnatures.

**Comment by antelle** [comment]
Next version will contain sha256 digests and signatures on GitHub Releases page.
