### ISSUE TITLE
Menus with empty text in MacOS 10.11.6

### ISSUE THREAD

**Issue by ericbn** [keeweb/keeweb#630]
Also, the Quit (Command-Q) option is disabled.

I'm using the latest 1.5.0 version.

<img width="337" alt="screen shot 2017-05-20 at 10 31 23 pm" src="https://cloud.githubusercontent.com/assets/4120606/26280998/792ba0fa-3dad-11e7-9c9c-0921febda3fb.png">

**Comment by antelle** [comment]
Please re-download it, then it will work. It's due to old launcher and new code.

**Comment by antelle** [comment]
#521
