### ISSUE TITLE
Special characters in the database name causes error

### ISSUE THREAD

**Issue by ertseyhan** [keeweb/keeweb#631]
- What were your actions?
    - I was trying to access the database on Dropbox.
- What was wrong?
    - Error occurred after selecting the database.
- App version:
    - KeeWeb 1.5.0 (4c4a308) on Win10 1607
    - Web App on Waterfox and MS Edge (**It worked fine** on MS Edge)
- User-Agent:
    - **Desktop:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) KeeWeb/1.5.0 Chrome/53.0.2785.143 Electron/1.4.15 Safari/537.36
    - **Waterfox:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:53.0) Gecko/20100101 Firefox/53.0.1 Waterfox/53.0.1
- Log(s)
    - Web App running on Waterfox 53.0.1 64-bit

        > [open:Ertuğrul Seyhan] File open request  app.keeweb.info:14:897
            [open:Ertuğrul Seyhan] Open file from storage dropbox  app.keeweb.info:14:897
            [open:Ertuğrul Seyhan] Load from storage  app.keeweb.info:14:897
            [storage-dropbox] Load /Ertuğrul Seyhan.kdbx  app.keeweb.info:14:736
            **TypeError**: Cannot convert string to ByteString because the character at index 14 has value 287 which is greater than 255.
    - Desktop App

        > [open:Ertuğrul Seyhan] File open request
            [open:Ertuğrul Seyhan] Open file from storage dropbox
            [open:Ertuğrul Seyhan] Load from storage
            [storage-dropbox] Load /Ertuğrul Seyhan.kdbx
            index.html:14 **Uncaught SyntaxError**: Failed to execute 'setRequestHeader' on 'XMLHttpRequest': '{"path":"/Ertuğrul Seyhan.kdbx"}' is not a valid HTTP header field value.

**Temporary workaround**: Deleting diacritical marks from the database name solves the problem. In my case, the problem was caused by the letter 'ğ'.

**Comment by antelle** [comment]
The same for Chrome. Dropbox API upgrade has caused it, investigating.

**Comment by antelle** [comment]
Deployed to [beta.keeweb.info](https://beta.keeweb.info), will be available in the upcoming hotfix.
Thanks for the fast bug report! 🎁

**Comment by antelle** [comment]
Release published.
