### ISSUE TITLE
Template causing UUID problems when the modified db is loaded by Keepass2Android

### ISSUE THREAD

**Issue by gynet** [keeweb/keeweb#633]
- what were your actions?
Add some empty templates to my db . 
Tried adding a "secure note" with all field empty. Click save. 
Open the db from Keepass2Android, it will complain about duplicate UUIDs for secure note
 
- what was wrong?
 Keepass2Android, it will complain about duplicate UUIDs for secure note
 
- app version
1.5.0 
- your user-agent (from Settings/Help section)
KeeWeb v1.5.0 (4c4a308, 2017-05-20)
Environment: electron v1.4.15
User-Agent: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) KeeWeb/1.4.1 Chrome/53.0.2785.143 Electron/1.4.15 Safari/537.36

**Comment by antelle** [comment]
Not only KeePass2Android, actually. Thanks, well noted, will hotfix it.

**Comment by antelle** [comment]
Deployed to [beta.keeweb.info](https://beta.keeweb.info), will be available in the next release.

**Comment by antelle** [comment]
Fixed, please update.
Unfortunately, you will have to restore your db to the state before you added that entry from template.
