### ISSUE TITLE
Database not saving after entries from KeePass Touch (iOS) 

### ISSUE THREAD

**Issue by r-philip** [keeweb/keeweb#634]
I use **KeePass Touch (iOS)** for dropbox syncing. Just started to use Keeweb today.

I noticed that any new entry generated by KeePass touch, when opened later in KeeWeb has the following values in the **'Generated'** and **'Updated'** fields.

Generated:   NaN undefined NaN NaN:NaN:NaN
Updated:    NaN undefined NaN NaN:NaN:NaN

I am guessing it is KeePass Touch not filling these entries. The issue is that the **database will not save** after another entry is added using KeeWeb. 

Error:    **Sync error: RangeError: Invalid time value**

KeeWeb v1.5.1 (daba40e, 2017-05-23)
Environment: electron v1.4.15
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_5) AppleWebKit/537.36 (KHTML, like Gecko) KeeWeb/1.5.0 Chrome/53.0.2785.143 Electron/1.4.15 Safari/537.36

**Comment by antelle** [comment]
Please attach an example of such database.

**Comment by r-philip** [comment]
[Problem Database.kdbx.zip](https://github.com/keeweb/keeweb/files/1027254/Problem.Database.kdbx.zip)

Password: 1234

If the database it modified Keeweb will not save

**Comment by antelle** [comment]
Here we go:
```xml
<Times>
    <LastModificationTime>2017-05-24T9:03:57 pmZ</LastModificationTime>
    <CreationTime>2017-05-24T9:03:31 pmZ</CreationTime>
    <LastAccessTime>2017-05-24T9:03:31 pmZ</LastAccessTime>
    <ExpiryTime>2017-05-24T9:03:31 pmZ</ExpiryTime>
    <Expires>False</Expires>
    <UsageCount>0</UsageCount>
    <LocationChanged>2017-05-24T9:03:31 pmZ</LocationChanged>
</Times>
```
It's not correct date, please report to KeePass Touch maintainers.
I'll think, shall we handle it or not, and how to behave in such cases.

**Comment by antelle** [comment]
Oh, no, it's totally, horribly wrong, because the time is also incorrect (instead of 21, I guess, it's inserting 9...pm), we can't read such things. Sync will generate something weird, even if we parse it.
So, it's better to fail fast.

**Comment by r-philip** [comment]
oh dear. I guess I will have to find KeePass Touch developers. Thanks for your time and the quick replies

**Comment by antelle** [comment]
I tried to report the issue to them, but it looks like, it's not an open-source project :(

**Comment by r-philip** [comment]
I guess I will have to leave a review in the App Store. Meanwhile any plans on making an iOS app of Keeweb?

**Comment by antelle** [comment]
I've just tested bunch of different clients, and they display different time, depending on framework apps are using. We can do the same, actually, but anyway, sync will not behave properly, probably, because it relies on dates, so I don't like this approach.
Mobile app will require some love, it's discussed here: #534

**Comment by r-philip** [comment]
Oh well. I have just emailed KeePass Touch developers. Their domain seems to have been repossessed . Does not look promising. Thanks for your help
