### ISSUE TITLE
Gfx issue with Edge browser

### ISSUE THREAD

**Issue by Hexaae** [keeweb/keeweb#636]
As you can see from the pics below the color scheme is broken with latest Microsoft Edge 40.15063.0.0 on Windows 10 x64 CU 15063.296:

<a href='https://postimg.org/image/boz3vsr0h/' target='_blank'><img src='https://s8.postimg.org/boz3vsr0h/Senza_nome.jpg' border='0' alt='postimage'/></a> <a href='https://postimg.org/image/wu42it8ej/' target='_blank'><img src='https://s17.postimg.org/wu42it8ej/Senza_nome_02.jpg' border='0' alt='postimage'/></a>

**Comment by antelle** [comment]
Hm, interesting. Do you have any idea, why?
I still have v14, but my Windows is a bit outdated, will try to get the latest edge and figure out.

**Comment by Hexaae** [comment]
Tried also on another PC with Edge 38.14393.1066.0 and Windows 10 x64 14393.1198... color scheme is ok there, but LMB are ignored (RMB and wheel do work, as well as laptop touchpad)

**Comment by antelle** [comment]
Very weird. Is there anything in console, is CPU loaded 100%?

**Comment by Hexaae** [comment]
No, and everything works fine with Chrome or FFox for example...

**Comment by antelle** [comment]
Yes, I know, pther browsers are fine. I mean, is your cpu 100% loaded when you open keeweb in Edge?

**Comment by Hexaae** [comment]
[Edge 38.14393.1066.0 and Windows 10 x64 14393.1198]
No, cpu is 3%.
I've found a weird way to "unlock" LMB clicks: have to click on the _Demo > Agent Forum_ Website link. After this action LMB starts working as expected.

[Edge 40.15063.0.0 on Windows 10 x64 CU 15063.296]
No issues with RMB and clicks, but color scheme is broken...

**Comment by antelle** [comment]
Got it, looks like something touch-related. Still no clue about color theme... We've seitched to css color variables this release, maybe there's an issue with ie15 with them. I'll try to bisect.

**Comment by antelle** [comment]
So, that's because of CSS variables. F*ck you, Microsoft, again.
I'll think what can we do about it.

**Comment by antelle** [comment]
Could you please test if beta.keeweb.info works ok for you with both issues?
(it's not possible to switch theme, this is expected)

**Comment by antelle** [comment]
Found why exactly this happens, will report to MS. So, if we use variables inside `*::selection`, they're applied without selection. This is awesome, check it out in msedge: http://jsbin.com/dovapedimo/edit?html,css,output
In the meanwhile, I'll create a workaround.

**Comment by antelle** [comment]
Here we go: https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/12132854/
Workaround pushed, please test on beta. Themes are working as well, but selection color is a bit weird.

**Comment by Hexaae** [comment]
[Edge 40.15063.0.0 on Windows 10 x64 CU 15063.296]
beta.keeweb.info is perfect now :) Colors are correct.

[Edge 38.14393.1066.0 and Windows 10 x64 14393.1198]
beta.keeweb.info
Still have to use the workaround written here https://github.com/keeweb/keeweb/issues/636#issuecomment-303979558 clicking on a Website link to "unlock" LMB and touchpad clicks

**Comment by antelle** [comment]
https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/5782378/
Added another workaround for the smartest browser in the world. Deployed to beta.

**Comment by Hexaae** [comment]
LOL, we opened Pandora's box... ;)
The funny thing is that every new Edge version might break something as far as we can see... It's not always an improvement. I thought Edge was finally a more than decent browser from MS, but this recent discoveries are scaring me... sob...

Great work: beta.keeweb.info
is now working fine on all (?) Edge versions / Win 10.

**Comment by antelle** [comment]
Yes it can break, not only in Edge, software requires support 😉  but I'm not going to disappear, so if you report bugs... keeweb will continue to work.
