### ISSUE TITLE
[Feature request] Template Display

### ISSUE THREAD

**Issue by gynet** [keeweb/keeweb#637]
I am not familiar with the feature of "template" but I was testing on it. 

Following is an example of an entry created with membership template: 

![untitled](https://cloud.githubusercontent.com/assets/2174522/26460606/0dd8b650-412f-11e7-9392-04327f9e938c.png)

I saw a bunch of fields have the prefix "_etm_xxx_"

I wonder is it possible for keeweb only display or make an option to display only related fields and dereference those "_etm_" prefix to make it more user-friendly 

Or, I was not using it correctly, please let me know. 

- app version 

1.5.2

**Comment by antelle** [comment]
Hi!
We don't have any built-in templates, so it's up to you, which fields to include. Please go to the Templates groups of your db and remove fields that you don't need.
