### ISSUE TITLE
Dragging the password length knob drags the whole window

### ISSUE THREAD

**Issue by ericbn** [keeweb/keeweb#638]
- what were your actions? On General Settings, set the Windows style to "Custom title, draggable window", and restart the app if necessary. Open the password generator, either by clicking on the "thunder" icon on a entry password field or by clicking on the "thunder" icon on the bottom-right corner. Try to drag the password length knob.
- what was wrong? The whole window is dragged. Expected just the knob to move horizontally.
- app version: v1.5.1 (daba40e, 2017-05-23)
- user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) KeeWeb/1.5.0 Chrome/53.0.2785.143 Electron/1.4.15 Safari/537.36
- does it happen on Demo or New database? both
- please, open dev tools in your browser and attach output log from Console tab: nothings gets logged after the actions, and also issue is not reproducible while dev tools is open.

Note: I wish we still could have an editable size field in the password generator as it was proposed in #191...

**Comment by antelle** [comment]
Fixed, will be available in the next hotfix.
