### ISSUE TITLE
Autotype don't work on Amazon (Germany)

### ISSUE THREAD

**Issue by Phreeak** [keeweb/keeweb#639]
- what were your actions?
 i try to fill username and password for amazon (germany) with autotype.

- what was wrong?
 The entry is not recognise. If i choose the entry manually, i get password wrong
 When i c&p the username and password, it works 

- app version
 v1.5.2

- your user-agent (from Settings/Help section)
 User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) 
   KeeWeb/1.5.0 Chrome/53.0.2785.143 Electron/1.4.15 Safari/537.36

- does it happen on Demo or New database?
 new Database

- if you are using a test db without your personal data, please attach it
 -

- please, open dev tools in your browser and attach output log from Console tab 
    (if you are using desktop app, devtools can be opened from Settings/General/Advanced)
 Amazon Anmelden - Google Chrome
https://www.amazon.de/ap/signin?_encoding=UTF8&openid.assoc_handle=deflex&openid.claimed_id=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0%2Fidentifier_select&openid.identity=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0%2Fidentifier_select&openid.mode=checkid_setup&openid.ns=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0&openid.ns.pape=http%3A%2F%2Fspecs.openid.net%2Fextensions%2Fpape%2F1.0&openid.pape.max_auth_age=0&openid.return_to=https%3A%2F%2Fwww.amazon.de%2F%3Ftag%3Dhyddeabkm-21%26hvadid%3D5366295824%26hvqmt%3De%26hvbmt%3Dbe%26hvdev%3Dc%26ref%3Dnav_custrec_signin
[DEBUG] 2017-05-25T18:17:21.486Z [auto-type] Window title Amazon Anmelden - Google Chrome https://www.amazon.de/ap/signin?_encoding=UTF8&openid.assoc_handle=deflex&openid.claimed_id=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0%2Fidentifier_select&openid.identity=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0%2Fidentifier_select&openid.mode=checkid_setup&openid.ns=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0&openid.ns.pape=http%3A%2F%2Fspecs.openid.net%2Fextensions%2Fpape%2F1.0&openid.pape.max_auth_age=0&openid.return_to=https%3A%2F%2Fwww.amazon.de%2F%3Ftag%3Dhyddeabkm-21%26hvadid%3D5366295824%26hvqmt%3De%26hvbmt%3Dbe%26hvdev%3Dc%26ref%3Dnav_custrec_signin
[DEBUG] 2017-05-25T18:17:26.046Z [auto-type] Entry selected null
[DEBUG] 2017-05-25T18:17:26.048Z [auto-type] Hide window
[DEBUG] 2017-05-25T18:17:36.075Z [auto-type] Auto type event null
[DEBUG] 2017-05-25T18:17:36.076Z [auto-type] Get window title
[INFO ] 2017-05-25T18:17:36.706Z [launcher] spawn C:\Users\*USERNAME*\AppData\Roaming\KeeWeb\helper\win32\KeeWebHelper.exe: 0, 630ms
Amazon Anmelden - Google Chrome
https://www.amazon.de/ap/signin?_encoding=UTF8&openid.assoc_handle=deflex&openid.claimed_id=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0%2Fidentifier_select&openid.identity=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0%2Fidentifier_select&openid.mode=checkid_setup&openid.ns=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0&openid.ns.pape=http%3A%2F%2Fspecs.openid.net%2Fextensions%2Fpape%2F1.0&openid.pape.max_auth_age=0&openid.return_to=https%3A%2F%2Fwww.amazon.de%2Fgp%2Fyourstore%2Fhome%3Fie%3DUTF8%26action%3Dsign-out%26path%3D%252Fgp%252Fyourstore%252Fhome%26ref_%3Dnav_youraccount_signout%26signIn%3D1%26useRedirectOnSuccess%3D1
[DEBUG] 2017-05-25T18:17:36.706Z [auto-type] Window title Amazon Anmelden - Google Chrome https://www.amazon.de/ap/signin?_encoding=UTF8&openid.assoc_handle=deflex&openid.claimed_id=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0%2Fidentifier_select&openid.identity=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0%2Fidentifier_select&openid.mode=checkid_setup&openid.ns=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0&openid.ns.pape=http%3A%2F%2Fspecs.openid.net%2Fextensions%2Fpape%2F1.0&openid.pape.max_auth_age=0&openid.return_to=https%3A%2F%2Fwww.amazon.de%2Fgp%2Fyourstore%2Fhome%3Fie%3DUTF8%26action%3Dsign-out%26path%3D%252Fgp%252Fyourstore%252Fhome%26ref_%3Dnav_youraccount_signout%26signIn%3D1%26useRedirectOnSuccess%3D1
[DEBUG] 2017-05-25T18:17:45.424Z [auto-type] Entry selected null
[DEBUG] 2017-05-25T18:17:45.426Z [auto-type] Hide window

**Comment by antelle** [comment]
So, what happens for you, I mean, what do you see in browser?
Could you please open keeweb and hit command-T, to trigger auto-type for specific entry on amazon and see what happens?

**Comment by Phreeak** [comment]
Ok, forget it....
It was my fault :(
I had two entries for Amazon. To confusing for keeweb

All ok. Sorry for wasting your time

**Comment by antelle** [comment]
Cool. If you have any ideas, how to improve entry disambiguation ui, please let me know.
