### ISSUE TITLE
macOS titlebar overlapping autotyping window

### ISSUE THREAD

**Issue by mammuth** [keeweb/keeweb#641]
When setting the window style to _Custom title, draggable window_ on macOS, there is no padding at the top of the autotype window as seen in the following screenshot.

Related PR: #571
Version: 1.5.2

<img width="998" alt="screen shot 2017-05-26 at 12 24 01" src="https://cloud.githubusercontent.com/assets/3121306/26491061/3db0f9de-420e-11e7-8d24-0c1fc7703de3.png">

**Comment by EnricoMonese** [comment]
Probably my fault. Not really an Auto-type user tho. How does one get to that window?

**Comment by mammuth** [comment]
You get there via the global shortcut ctrl+options+T 😊

**Comment by EnricoMonese** [comment]
@antelle right now we put the `app--titlebar-style-hidden` class on the app `div`, maybe it should be moved to the `body` to make the class available for other things too?
![schermata 2017-05-26 alle 14 54 25](https://cloud.githubusercontent.com/assets/19847464/26495285/59bd8e16-4223-11e7-82c1-a0a3abf520ac.png)

**Comment by antelle** [comment]
@EnricoMonese yes it should be in `body` in this case. Pushed, will be released in the upcoming hotfix.

**Comment by EnricoMonese** [comment]
Hm, I don't seem to be able to drag the window in any way with the hidden-inset titlebar now

**Comment by antelle** [comment]
@EnricoMonese thanks, fixed.
