### ISSUE TITLE
KeeWeb main password started to not working for no reason

### ISSUE THREAD

**Issue by Marchalle** [keeweb/keeweb#643]
- what were your actions? Only leaving the password page http://prntscr.com/fcobhf

- what was wrong? My password is not working anymore

- app version 1.5.2

- your user-agent (from Settings/Help section) 
KeeWeb v1.5.2 (84d8eda, 2017-05-25)
Environment: electron v1.3.3
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) KeeWeb/1.3.3 Chrome/52.0.2743.82 Electron/1.3.3 Safari/537.36

- does it happen on Demo or New database? Only on my passworded file.

- if you are using a test db without your personal data, please attach it //

- please, open dev tools in your browser and attach output log from Console tab 
    (if you are using desktop app, devtools can be opened from Settings/General/Advanced)

[INFO ] 2017-05-27T11:52:37.214Z [updater] Next update check will happen in 217s
[INFO ] 2017-05-27T11:52:37.216Z [app] Started in 501ms ¯\_(ツ)_/¯
[INFO ] 2017-05-27T11:52:42.834Z [open:BDD] File open request
[INFO ] 2017-05-27T11:52:42.835Z [open:BDD] Open file from supplied content
[ERROR] 2017-05-27T11:52:42.845Z [file] Error opening file InvalidKey Error InvalidKey: invalid key KdbxError: Error InvalidKey: invalid key
[ERROR] 2017-05-27T11:52:42.845Z [open-view] Error opening file KdbxError: Error InvalidKey: invalid key

**Comment by antelle** [comment]
There's no error here. Probably you're using wrong password or keyfile.

**Comment by Marchalle** [comment]
Im not using a wrong password.
The passwor started to not working, A friend got the same problem some weeks ago.

**Comment by Marchalle** [comment]
Im enterring my password everyday, I can't forget it like that. It's important that you investigate that issue because I have actually lost all my personnal data because of something. 
Keep in mind that I'm not the only one in my friend (using keeweb) that got this problem.

**Comment by antelle** [comment]
I cannot investigate it, unless you give clear and repeatable steps to reproduce. Please reopen the issue then.
