### ISSUE TITLE
Switching "Entries list table view" will cause GUI distort

### ISSUE THREAD

**Issue by gynet** [keeweb/keeweb#645]
- what were your actions?
1. Check the option "Entries list table view" 
2. Uncheck the option "Entries list table view" 
- what was wrong?
After I unchecking the option, the entry list in the middle the of the GUI just shown half of the list, and another half of the list gotten hidden.  
- app version
1.5.2

- User Agent
KeeWeb v1.5.2 (84d8eda, 2017-05-25)
Environment: electron v1.4.15
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) KeeWeb/1.4.0 Chrome/53.0.2785.143 Electron/1.4.15 Safari/537.36

 Other GUI configuration.
Theme: terminal
Window Style: **Custom title, draggable window**
Show entries from all subgroups: **unchecked**
Colorful custom icons in list: **checked**

**Comment by antelle** [comment]
Hm, I cannot repeat it... Is the UI just cut off, or there are buttons below? Could you please make a screenshot of it?

**Comment by gynet** [comment]
Sure. Here is the screenshot, please see the area around the entry test4, and test5 and other entries are covered by a panel. 
![untitled](https://cloud.githubusercontent.com/assets/2174522/26562459/406c5906-447b-11e7-9f7e-76b072fc52b5.jpg)

**Comment by antelle** [comment]
Does it recover back to normal, e.g. when you restart the app?

**Comment by gynet** [comment]
Yes, restart the app will recover back

**Comment by antelle** [comment]
And if you click something in the left menu?

**Comment by gynet** [comment]
Clicking on the left menu does not help, and the scroll bar in the middle only be able to reach half of the panel

**Comment by antelle** [comment]
Ah, gotcha. You have resized it with the horizontal line being in table view. I've managed to repeat it, will fix, thanks.

**Comment by gynet** [comment]
Thanks!

**Comment by antelle** [comment]
Deployed to [beta.keeweb.info](https://beta.keeweb.info), will be available in the next release.
