### ISSUE TITLE
Master password should be inserted twice to check correctness

### ISSUE THREAD

**Issue by andreapx** [keeweb/keeweb#646]
- what was wrong? I think that for changing the "Master password" in the settings, it should be inserted twice to avoid errors writing it. Yesterday for example I must accidentally have added a char to that field just before saving the file and...the file is now not anymore accessible.
- app version: **1.5.2**
- your user-agent (from Settings/Help section): Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:53.0) Gecko/20100101 Firefox/53.0

Thanks!

**Comment by antelle** [comment]
you can create a plugin for it

**Comment by andreapx** [comment]
I would like to be able to do it!!!

**Comment by gynet** [comment]
I think double checking the input during changing the master password should be important especially for someone like me has a fat finger :)

**Comment by antelle** [comment]
Well, master password is a bit special compared to other passwords, let's add this to the core product.

**Comment by andreapx** [comment]
Can I have hire a freelance to solve this and then upload it here?

**Comment by antelle** [comment]
It's up to you, if you want it right now, of course you can, but please note that there may be some changes requested. As I see it now: when you change your password, we show an additional text field below it, where you can repeat your password.

**Comment by andreapx** [comment]
What do you mean by "there may be some changes requested"?

**Comment by antelle** [comment]
Whan you submit a pull request on github, project maintainersay want to request changes to be made, i.e. if there's something not implemented properly (not alighed with maintainers' point of view) in the pr: design, architecture, etc...

**Comment by andreapx** [comment]
Is there anybody willing to do this "now" upon payment?

**Comment by austil** [comment]
I looked at this last friday, the changes required seems fairly simple.
I may have the time to submit a pull request before the end of the year.

And last but not least, I'm willing to do this for free. This feature is important to me (never changed my master password because of this). Feel free to make a donation to the maintainer of this pretty useful app instead 😉

**Comment by andreapx** [comment]
That's great!!!
Let me know when you upload it!

**Comment by andreapx** [comment]
@austil 
When you'll do it, will it go directly in app.keeweb.info?

**Comment by antelle** [comment]
@andreapx after a successful merge it will be included in the next release and then yes, to app.keeweb.info and apps, after some time, together with other features. So, not directly but eventually it will be there.

**Comment by austil** [comment]
As you probably noticed, I haven't found time to do it. I'm not in control of my time at the moment and will not be before June ...
If you still want to pay somebody to do that (via a website like BountySource I assume), here is a time estimation of mine to help you fix a price : 

* for a dev knowing the framework (backbone.js) : ~4H (changes after review included)
* for someone how know JS but not this particular framework (like me) : from 7 to 11H

Hope it helps.

**Comment by andreapx** [comment]
Is this feature in the roadmap?

**Comment by andreapx** [comment]
Hi, is there a way to sponsor this feature?

**Comment by andreapx** [comment]
I've create a bounty here: https://www.bountysource.com/issues/45707648-master-password-should-be-inserted-twice-to-check-correctness
I've put there 20$, if ther's anybody else that want to contribute...

**Comment by sahalsaad** [comment]
I tried to implement this but stuck at how to compare the password.

**Comment by sahalsaad** [comment]
I tried to implement this but get stuck at comparing the password hash . Is it possible or can I just compare the text ?

**Comment by antelle** [comment]
@sahalsaad you can just compare the password indeed, there's no need to compute hash, since it's already stored unprotected in the ui.

**Comment by sahalsaad** [comment]
Can we close this ticket so that I can claim the bounty? Thanks.

**Comment by andreapx** [comment]
Hi @sahalsaad 
I can't see this function on either the production or the beta, how can I see it?
Thanks!

**Comment by sahalsaad** [comment]
Hi @andreapx
It is available in beta. I guess you need to start typing in the master password.
![alt text](https://i.imgur.com/DTuOpUc.png "SS")

**Comment by andreapx** [comment]
Uh, lovely!
Sorry, I didn't notice.
Thanks!

**Comment by sahalsaad** [comment]
No problem and Thanks!
