### ISSUE TITLE
[Feature request] Plugin Settings Support - E.g Keewebhttp

### ISSUE THREAD

**Issue by gynet** [keeweb/keeweb#647]
It would be nice for keeweb to support plugin settings 

The KeePass keepasshttp implementation has some configurations, it would be nice for keeweb to have those too 
![options-advanced](https://cloud.githubusercontent.com/assets/2174522/26652986/8c2fcdc8-4606-11e7-97ab-a74cabb7ecb2.png)

**Implementation Suggestion**
Similar to Visual Studio Code, I would suggest having a json confg file for each plugin so that plugin would be able to fetch according to values. 
Based on that, it would be a bonus to have a more user-friendly config page for each plugin

**Comment by antelle** [comment]
Plugins do have [settings](https://github.com/keeweb/keeweb/wiki/Plugins#settings), but I keepasshttp settings are pointless.
