### ISSUE TITLE
Keewebthttp URL Detection : "https://*.domain/*" not working

### ISSUE THREAD

**Issue by gynet** [keeweb/keeweb#648]
- what were your actions?
Using Keewebthttp with chrome
- what was wrong?
Keewebthttp does not detect the entry with the website field value as https://*.domain.com/. 
So the web site URL filed have to be fully matching. 
- app version 
1.5.2
- your user-agent (from Settings/Help section)
KeeWeb v1.5.2 (84d8eda, 2017-05-25)
Environment: electron v1.4.15
User-Agent: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) KeeWeb/1.4.1 Chrome/53.0.2785.143 Electron/1.4.15 Safari/537.36
- does it happen on Demo or New database? 
No

**Comment by antelle** [comment]
Do you mean literally *.domain.com or something.domain.com?

**Comment by lukx** [comment]
@gynet I know of macpass and keepassxc, that it should instead of "*.example.org", it should simply  be "example.org", and then you'll get a selection option to let you choose among the matching web sites, if you navigate to any of the subdomains (e.g. mysite.example.org)

**Comment by gynet** [comment]
@antelle  
I mean something.domain.com, basically, all subdomains seems not getting detected. 

Repo steps: 
1. Define an entry with website value either as https://google.com or https://*.google.com/*
2. Go to https://accounts.google.com/

Actual result: 
Keewebhtto does not show any entry available

Expected result:
Expect keewebhttp detects any subdomain matches the entries with defined website values as https://domain.com or https://*.domain.com/*
So, Keewebhtto should show the entry define in step 1.

**Comment by antelle** [comment]
Keeweb doesn't include subdomains for auto-type. Probably it should be changed, yes, because the most common example is `accounts.google.com`.

**Comment by gynet** [comment]
Yes, I agree, that may need to think about the consequences. Maybe we can take a look at the how keepasshttp or CPK handle these situations.

**Comment by lukx** [comment]
@antelle I might be able to help investigate.

* [MacPass](https://github.com/MacPass/MacPassHTTP) will fill in the top-most, best-matching domain
* KeePassXC (and I think also Keepass 2) will find all best-matching URLs, and prompt a window which ones ChromIPass (or Passifox) will get access to.
   * If you have an entry for accounts.google.com AND google.com, and navigate to accounts.google.com, only the accounts.google.com entry will be presented
   * If you have two entries for google.com and navigate to accounts.google.com, both entries will be presented

The user's decision is stored in a JSON-Like format in a custom property field for that entry (allow/deny syntax).:
`KeePassHttpSettings: {"Allow":["accounts.google.com"],"Deny":[],"Realm":""}`

**Comment by lukx** [comment]
Thank you so much, works great in 1.6.1! @antelle
