### ISSUE TITLE
Large type

### ISSUE THREAD

**Issue by lwis** [keeweb/keeweb#650]
How feasible would it be to add [Large Type](https://tooagile-wpengine.netdna-ssl.com/wp-content/uploads/2015/10/1Password54MacLargeType-1500x935.png) to KeeWeb?

My frontend skills aren't great, else I'd love to get my hands dirty.

**Comment by antelle** [comment]
https://github.com/keeweb/keeweb/issues/197

**Comment by lwis** [comment]
:+1: sorry!
