### ISSUE TITLE
Windows Style with "Custom title" is still draggable 

### ISSUE THREAD

**Issue by gynet** [keeweb/keeweb#651]
- what were your actions?
Change the setting Windows Style to be "Custom title" without "draggable" 
- what was wrong?
Window is still draggable 
- app version 
1.5.3
- your user-agent (from Settings/Help section)
KeeWeb v1.5.3 (517f662, 2017-05-29)
Environment: electron v1.4.15
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) KeeWeb/1.4.0 Chrome/53.0.2785.143 Electron/1.4.15 Safari/537.36

**Comment by antelle** [comment]
Yeah, and 'Custom title, draggable window' is not draggable. Already fixed, will be in the next release or hotfix.
