### ISSUE TITLE
Keeweb automaticly close tab

### ISSUE THREAD

**Issue by Guisch** [keeweb/keeweb#653]
Hi,

I have a problem on my server.
I have keeweb (gh-pages branch) on my server with webdav.
I put a link on my server home page to access to my keeweb page but when i click on it, it open the tab and automaticly close after few seconds. However, when I do right click "open link in new tab" on the link, it successfully open the link.
I tried on chrome and firefox and it do the same for both browsers.
The server use a Let's Encrypt certificate and the domain is in .tk, maybe this is the causes.

It's no big deal, just want to warn.
Also thanks for keeweb, it's awesome.

**Comment by antelle** [comment]
Hi,
What does the link look like, is it a normal link? Maybe you're trying to open keeweb in popup with window.open?

**Comment by Guisch** [comment]
Nop, it's a basic html+php link

``` php
<?php $kwURL = "https://XXXXXXXX.tk/kw";?>

<li><a href="<?php echo "$kwURL"; ?>" class="grayscale" target="_blank"><i class="fa fa-key"></i> <span>Keeweb</span></a></li>
```

**Comment by antelle** [comment]
Interesting. I can repeat it here: http://jsbin.com/cejopujiso/edit?html,output
Very weird, will be fixed.

**Comment by antelle** [comment]
Fixed. JSbin: http://jsbin.com/kewepijaza/edit?html,output
You can actually save beta to your server, if you want it now: we don't have any other changes at the moment.
