### ISSUE TITLE
Font Problum

### ISSUE THREAD

**Issue by royink** [keeweb/keeweb#654]
Keeweb will use the SimSun font when it meets CJK characters.
This font is ugly and Not easy to read, Microsoft Yahei is better.

KeeWeb v1.5.4 (b730cbd, 2017-06-03)
Environment: electron v1.4.15
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) KeeWeb/1.5.4 Chrome/53.0.2785.143 Electron/1.4.15 Safari/537.36

**Comment by antelle** [comment]
Hi, could you please an example? Do you know a way to fix?

**Comment by antelle** [comment]
I've added these fonts:
```
"Microsoft YaHei", "微软雅黑", "STXihei", "华文细黑"
```
But I'm not sure: on Mac and Windows in BrowserStack nothing changes in Chinese language.
Could you please test if it's better on [beta](https://beta.keeweb.info)?

**Comment by royink** [comment]
@antelle 
In [beta](https://beta.keeweb.info/) , I saw Microsoft YaHei on Edge and Chrome.

But 'PingFang' looks better on Mac.  STXihei (华文细黑 ),is not a nice font for UI display.

**Comment by antelle** [comment]
I got these fonts from [this](http://www.kendraschaefer.com/2012/06/chinese-standard-web-fonts-the-ultimate-guide-to-css-font-family-declarations-for-web-design-in-simplified-chinese/) guide.
I'm a bit lost. Should I use this instead?
```
"Microsoft YaHei", "微软雅黑", "PingFang", "STXihei", "华文细黑"
```
It looks like, PingFang is not installed on my mac, or the name is incorrect?

**Comment by royink** [comment]
```
"Microsoft YaHei", "微软雅黑", "PingFang SC", "Hiragino Sans GB"
```

[1]"PingFang SC" is the Simplified Chinese Version of "PingFang", correct name of
"PingFang" is "PingFang SC", "PingFang HK" or "PingFang TW".
[2]"Hiragino Sans GB" looks better than "STXihei"，and was installed on macOS after 10.6.

**Comment by antelle** [comment]
Added, deployed to beta
