### ISSUE TITLE
Bad xml root

### ISSUE THREAD

**Issue by doogalbear** [keeweb/keeweb#655]
Hi. Awesome app. Thanks. Now I want to import instead of making single entry, but when I do I get bad XML root. What does this mean? Can you show me a proper XML layout? 
I've tried converting csv to XML with libre office and http://www.convertcsv.com/csv-to-xml.htm both options give same error.  
This happens with both Linux desktop and online version.

**Comment by antelle** [comment]
`Import XML` can import only kdbx files saved as xml, not entries. It's not possible to import several entries at once. We'll support import from xml and csv in future, for now you can use KeePass for that.
