### ISSUE TITLE
 Global Auto Type Running against Desktop Applications Only Matches on Entry Titles 

### ISSUE THREAD

**Issue by gynet** [keeweb/keeweb#657]
It looks like the global autotype for desktop applications only detects matching entry titles only. 

For example, I want to autotype with SSH login, if I just put the terminal title value, e.g "cmd.exe" to the website field of a keeweb entry, but I put a random value as the entry title, e.g ssh server IP addess, it won't be detected by global typing, and you have to make the entry title match the terminal title value, which does not meet most people's use cases. 

I wonder if the auto type ignores the website field and only try to match with title field? 
It would be nice to make it able to select other fields rather than the title field, like notes, tages, website

**Comment by antelle** [comment]
This will be solved with custom window configuration: #433, so it's a special field where you can additionally specify window title match.
Website is checked only if there's url, so it's used only for browsers, when we can get the url.

**Comment by gynet** [comment]
thanks, added some comments at there.
