### ISSUE TITLE
rearrange fields

### ISSUE THREAD

**Issue by doogalbear** [keeweb/keeweb#658]
I was able to import per your instructions. Thank you. Now, I would like to know, is it possible to rearrange some of these fields. 
For example, before import I have the file laid out like it should and then after import it's in alphabetical order after Expires. Example given below.

Expected Format|What actually processed
---|---
Title|Title
User|User
Password|Password
Website|Website
Notes|Notes
Tags|Tags
Expires|Expires
Security Question 1|Email
Security Answer 1|Image
Security Question 2|Security Answer 1
Security Answer 2|Security Answer 2
Security Question 3|Security Answer 3
Security Answer 3|Security Answer 4
Security Question 4|Security Answer 5
Security Answer 4|Security Question 1
Security Question 5|Security Question 2
Security Answer 5|Security Question 3
Image|Security Question 4
Title/Phrase|Security Question 5
Email|Title/Phrase

KeeWeb v1.5.3 (517f662, 2017-05-29)
Environment: electron v1.4.15
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) KeeWeb/1.5.3 Chrome/53.0.2785.143 Electron/1.4.15 Safari/537.36

Updated: Questions wrong order

**Comment by jourdanritchey** [comment]
I also would like the ability to rearrange fields. A visual grab, drag, drop would do it.

Absolutely loving KeeWeb! 😍

**Comment by antelle** [comment]
It's #398
