### ISSUE TITLE
Appcrash on Windows 10 (with keewebhttp)

### ISSUE THREAD

**Issue by LiloBzH** [keeweb/keeweb#659]
Hi,

- what were your actions? Reduce in tray, open immédiatly, reduce, open => crash
- what was wrong? Crash
- app version 1.5.4
- your user-agent (from Settings/Help section)
KeeWeb v1.5.4 (b730cbd, 2017-06-03)
Environment: electron v1.4.15
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) KeeWeb/1.5.4 Chrome/53.0.2785.143 Electron/1.4.15 Safari/537.36

- does it happen on Demo or New database? Database with webdav

If i disable "keewebhttp" , no crash ! Si it's a problem with this module.

Thanks 

> chromeIPass Version:2.8.1
> KeePassHttp Version:1.8.4.2

http://www.whoishostingthis.com/tools/user-agent/
> Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.86 Safari/537.36

> Nom de l’application défaillante KeeWeb.exe, version : 1.5.4.0, horodatage : 0x5880f159
> Nom du module défaillant : node.dll, version : 6.5.0.0, horodatage : 0x5880f113
> Code d’exception : 0xc000041d
> Décalage d’erreur : 0x000000000036b37c
> ID du processus défaillant : 0x3334
> Heure de début de l’application défaillante : 0x01d2e3929d895f29
> Chemin d’accès de l’application défaillante : E:\Logiciels\KeeWeb\KeeWeb.exe
> Chemin d’accès du module défaillant: E:\Logiciels\KeeWeb\node.dll
> ID de rapport : 41f01019-65fd-4c18-b7e0-2ec9f6488d5b
> Nom complet du package défaillant : 
> ID de l’application relative au package défaillant :

**Comment by antelle** [comment]
It's not because of keewebhttp, duplicate of #621, fixed, will be in the next version

**Comment by LiloBzH** [comment]
Duplicate ! Sorry.

Thank you for the patch :)
