### ISSUE TITLE
Enhancement search - add folder in search

### ISSUE THREAD

**Issue by InfinityWebMe** [keeweb/keeweb#661]
Hello,

when we search, the app search on key and custom fields but don't use the folder name. 

It's interesting if we can search on folder too :)

**Comment by antelle** [comment]
Such folder selection would be tricky to implement. It should be a button which will show a popup with available files/folders.

**Comment by antelle** [comment]
Wait... You can select folder on the left and then search inside it.
Sorry, misread the request first time.
