### ISSUE TITLE
Enpass CSV import

### ISSUE THREAD

**Issue by kzshantonu** [keeweb/keeweb#662]
Hi,

Trying to permanently move away from Enpass. The Enpass TXT importer in keepass is unreliable.
Would really appreciate a Enpass CSV importer. The format is really simple.

Title, field name 1, field content 1, field name 2, field content 2.......

example:

`
"Title","Field","Value","Field","Value",.........,"Note"
"website.com","Username","guyfawkes","Email","guy@fawkes.com","Password","3\9q,Fbr:4YR>Vh:Mg","Phone","123456789","URL","https://guy.fawkes.com","Security question","super secret question","Security answer","super secret answer","notes and stuff here"
"just a secure note example","super secret secure note content here"
"Passport example","Number","AB1234567","Full name","Guy Fawkes","Sex","gender","Type","ordinary","Nationality","country name",""
"Credit card example","Cardholder","Guy Fawkes","Type","Visa Card","Number","1234567890098765","CVC","123","PIN","1234","Expiry date","01/22",""
`

**Comment by antelle** [comment]
This is #498, in future we'll allow to import any CSV format.
