### ISSUE TITLE
Check for Updates doesn't work

### ISSUE THREAD

**Issue by 4brunu** [keeweb/keeweb#666]
### What were your actions?
- Open Settings
- Click button Check for Updates

### What was wrong?
I'm using version 1.5.3 (517f662), and it's not the last version.
The last version is v1.5.4 (b730cbd, 2017-06-03).
But after I had clicked the button check for updates, it show's the message "you are using the last version".

### App version, Environment and User-Agent
KeeWeb 1.5.3 (517f662)
Environment: electron v1.4.15
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_5) AppleWebKit/537.36 (KHTML, like Gecko) KeeWeb/1.5.3 Chrome/53.0.2785.143 Electron/1.4.15 Safari/537.36

### does it happen on Demo or New database?
The bug it's not related to the database

### please, open dev tools in your browser and attach output log from Console tab
[INFO ] 2017-06-15T17:42:45.530Z [updater] Next update check will happen in 86100s
[INFO ] 2017-06-15T17:42:45.531Z [app] Started in 821ms ¯\_(ツ)_/¯
[INFO ] 2017-06-15T17:44:54.756Z [updater] Checking for update...
[INFO ] 2017-06-15T17:44:54.757Z [transport] GET https://app.keeweb.info/manifest.appcache
[INFO ] 2017-06-15T17:44:54.792Z [transport] Request to https://app.keeweb.info/manifest.appcache without proxy
[INFO ] 2017-06-15T17:44:55.401Z [transport] Response from https://app.keeweb.info/manifest.appcache: 200
[INFO ] 2017-06-15T17:44:55.405Z [updater] Update check: # 2017-06-03:v1.5.4
[INFO ] 2017-06-15T17:44:55.415Z [updater] Next update check will happen in 86400s

### Screenshot
<img width="531" alt="screen shot 2017-06-15 at 18 36 44" src="https://user-images.githubusercontent.com/784666/27194560-ebccc628-51fa-11e7-951b-0eb8dacc8c26.png">

**Comment by antelle** [comment]
How do you check app version? If it's mac app, version will not be updated in KeeWeb/About.

**Comment by 4brunu** [comment]
It's a mac app, and I was checking on the About menu.
So the app is updated successfully, but the about menu will show the old version, right?

**Comment by antelle** [comment]
Yes. It's not possible to update About menu, unfortunately. This version is stored in plist file and overwriting it will make resource digital signature invalid. Updating the whole app with 100+MB on every update doesn't seem to be a good solution as well.

**Comment by 4brunu** [comment]
Ok, seems good, thanks!
