### ISSUE TITLE
Additions needed to the Dropbox and GDrive auth Wiki page for Google API usage

### ISSUE THREAD

**Issue by magnetikonline** [keeweb/keeweb#667]
Hey,

   just a quick one - trying to setup a self hosted instance of KeeWeb using databases within Google Drive.

Following the steps from here: https://github.com/keeweb/keeweb/wiki/Dropbox-and-GDrive#google-drive

Seems there are now two more requirements needed (introduced recently it seems, so Wiki just needs more steps):
- Personal/testing access either needs verification of your domain, or if it's just for a single "one domain one account" you can join the [Risky Access Permissions By Unreviewed Apps](https://groups.google.com/forum/#!forum/risky-access-by-unreviewed-apps) Google group, which magically unlocks access.
  - This is also documented here: https://developers.google.com/gmail/api/auth/scopes.
- Need to enable the `Drive API` for your project via the following URL: https://console.developers.google.com/apis/library.

Probably in need of some extra steps as text and possible screenshots.

Cheers

   Pete

**Comment by antelle** [comment]
Interesting: I'm not in that group. Does it apply to normal Google accounts, or it's something for business/team accounts?

**Comment by magnetikonline** [comment]
@antelle No you wouldn't be, since you would have approved your domain (`keeweb.info` / `app.keeweb.info`) meaning your setup can be used by _anyone_ (which is great!).

For the solo user like me, whom just wants to self-host - you can try to get your domain approved, or simply add yourself (and thus your Google account) to that group.

Does that make sense? I was reading this change only came in middle of May this year.

**Comment by antelle** [comment]
Yes this absolutely makes sense, thanks a lot, I'll update the docs soon.

**Comment by magnetikonline** [comment]
Thanks @antelle - keep up the great work, really enjoying this as a nicer way to handle "roaming" Keepass databases 👍

**Comment by pejobo** [comment]
Can't find the information about 'risky access' you are mentioning on the linked page.
Woudn't it be a better approach to not provide the keeweb domain as parameter to oauth when a custom gdriveClientId is provided?

**Comment by antelle** [comment]
@pejobo added it to wiki (somehow it was not saved last time)
It's not possible to fix it in keeweb, redirect uri is a security limitation for your project (i.e. google api).

**Comment by pejobo** [comment]
In app/scripts/storage/storage-base.js redirect uri 'calculated' to "window.location.href", if this is a "file://" uri (as in my case), the uri "https://app.keeweb.info" is used.

**Comment by antelle** [comment]
Ah I see. Keeweb doesn't support file uris, also, I think, it won't be possible to put file uri to Dropbox / GDrive / etc...

**Comment by pejobo** [comment]
I just want to use "file://.." for 'hosting', the storage file should be hosted on GDrive. So I can use my local chromium instead of an additional electron environment..

**Comment by antelle** [comment]
You need a redirect uri for Google Drive to be able to authenticate and read/write data.

**Comment by timshannon** [comment]
I've been trying to set this up for a while now.  Google won't validate my Oauth request, because the video I made doesn't show "How to request an OAuth token (OAuth Consent Screen/Permissions Page)", which I can't because they haven't validated my OAuth request.

I'm not sure how you're supposed show access to something they haven't approved yet?

So the alternative is to join the "Allow Risky Access Permissions By Unreviewed Apps" google group, but I'm not see anywhere on the page to join the group?
