### ISSUE TITLE
[Feature Request] Editable file properties

### ISSUE THREAD

**Issue by NP-Hardass** [keeweb/keeweb#668]
I'm running keeweb 1.5.4 where I'm serving up a json configuration file:

```
{
  "files": [
    {
      "storage": "webdav",
      "name": "Some Name",
      "path": "https://url/to/my/file.kdbx",
      "options": { 
        "user": "USER",
        "password": ""
      }
    }
  ]
}
```

I don't want to serve up my password in plaintext for all to see.  It'd be nice to be able to edit the list of files so that one could change the path, name, user, password, etc. in the web UI.

#669 is a related, but separate feature request.

**Comment by antelle** [comment]
We don't have a config editor at the moment. Maybe later we'll have one, but it will be a separate page, like plugin creator.

**Comment by NP-Hardass** [comment]
Sounds good.  I'll look forward to it ^_^  Let me know if I can assist in testing when you get to the point of development.

**Comment by antelle** [comment]
Closing this, there are no plans to implement config editor. The password in the file is xor-ed, so it's safe to show it.
