### ISSUE TITLE
'master-password'-input does not accept some characters

### ISSUE THREAD

**Issue by nirbos** [keeweb/keeweb#670]
Hello there,

## What were your actions?
Trying to log into a database.

## What was wrong?
It seems to me that the 'master-password'-input does not accept some characters. It won't type them.

Characters not supported I found out so far: 
- ^
- ~
- ´
- `

Within the settings however (of a demo-environment) I can change the password to those characters (although I can not export the demo-db to a kdbx-file).

## App version & User agent
KeeWeb v1.5.4 (b730cbd, 2017-06-03)
Environment: electron v1.4.15
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_5) AppleWebKit/537.36 (KHTML, like Gecko) KeeWeb/1.5.4 Chrome/53.0.2785.143 Electron/1.4.15 Safari/537.36

## Does it happen on Demo or New database?
It happens on a database previously used with KeePass. 

## Console Log
Of course then the console throws a:
[file] Error opening file InvalidKey Error InvalidKey: invalid key KdbxError {name: "KdbxError", code: "InvalidKey", message: "Error InvalidKey: invalid key"}code: "InvalidKey"message: "Error InvalidKey: invalid key"name: "KdbxError"__proto__: Objecto.error @ index.html:14(anonymous function) @ index.html:17

**Comment by antelle** [comment]
Hi, I can't repeat it, what happens for you, they are just skipped? Do they appear as dots in the password field?

**Comment by nirbos** [comment]
Yes, the characters are entirely skipped, no dots appearing.

**Comment by antelle** [comment]
Interesting... I'll try to repeat it. Any suggestions are welcome.

**Comment by antelle** [comment]
Does it repeat only on one computer/user? Maybe you have some special keyboard-related software installed?

**Comment by nirbos** [comment]
No, I have not installed any keyboard related software.

- If I put a value="´" or value="``" to the input it wouldn't show either.
- If I put in another <input type="password" ...> right before that, I can type a ´.

There are no errors in the console.

**Comment by antelle** [comment]
Can you copy-paste it there? Is it the same on https://app.keeweb.info?

**Comment by nirbos** [comment]
I have tried a demo-db on https://app.keeweb.info via Safari, changed the password to `, exported and reopened it. It does work that way.

**Comment by antelle** [comment]
So, it works in browser but not in desktop app right?

**Comment by nirbos** [comment]
Pasting the password does work. That way I found out :)

**Comment by nirbos** [comment]
Yes.

**Comment by antelle** [comment]
Interesting. Which keyboard layout do you have?

**Comment by nirbos** [comment]
I have the German keyboard layout. The ISO I don't know :)

**Comment by antelle** [comment]
So, how do you type this symbol? Maybe you're trying accent, not the actual symbol? It will not work then.

**Comment by nirbos** [comment]
Hm, you're right. It seems that all of this characters mentioned at the entry-post are also used for accents. 
However, one of the combinations a database depends on is ~]. Wich should cancel out the accent starting with ~ ?

**Comment by antelle** [comment]
Just tried on a simple password field: accents (´ and `) cannot be entered in password field in Chrome, and thus, in KeeWeb (because KeeWeb is chromium):
http://jsbin.com/yilufafuhi/edit?html,output
On US keyboard layout acute accent (´) is <kbd>alt</kbd>+<kbd>e</kbd>, but grave accent (`) is typed as a char, not accent.

**Comment by nirbos** [comment]
Ok. 
Thank you very much for your effort.

**Comment by kasoban** [comment]
This confuses me a bit, this is working as expected here on Windows 10 with default German keyboard.

KeeWeb v1.5.4 (b730cbd, 2017-06-03)
Environment: electron v1.4.15
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) KeeWeb/1.4.1 Chrome/53.0.2785.143 Electron/1.4.15 Safari/537.36

**Comment by nirbos** [comment]
I have retested this on Windows 10 but it don't seems to work for me using my password.

KeeWeb v1.5.4 (d02a467, 2017-06-07)
Environment: electron v1.4.15
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) KeeWeb/1.5.4 Chrome/53.0.2785.143 Electron/1.4.15 Safari/537.36

**Comment by kasoban** [comment]
Just to clarify: If you press the button for "^" twice in the password input field on keeweb desktop on Windows 10, no dots show up?

**Comment by antelle** [comment]
@kasoban probably yes: Windows doesn't have smart accents input.
Actually, you can try it in Chrome and see if your char gets typed.

**Comment by nirbos** [comment]
@kasoban My mistake. It does work on Windows. It does not work on MacOS however.

**Comment by Nalapl3** [comment]
Polish diactritic characters such as ń, ć, ł, ó are not working.
