### ISSUE TITLE
I can't open file when I didn't select generated key file.

### ISSUE THREAD

**Issue by tristachentw** [keeweb/keeweb#671]
Hi,
I can't open file, and I think of my operation flow.

I found below step can reproduce this case:
1. Create a new db.
2. Go to the db setting page.
3. In "Key file" field, select "Generated new key file", and click "Cancel", don't save.
4. Close the db.
5. Reopen the db and try type password, but it will fail...
And I found after step3, "Key file" field will set "Use generated key file", but I actually don't save any key file...

This is my app info:
KeeWeb v1.5.4 (b730cbd, 2017-06-03)
Environment: electron v1.4.15
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_5) AppleWebKit/537.36 (KHTML, like Gecko) KeeWeb/1.5.4 Chrome/53.0.2785.143 Electron/1.4.15 Safari/537.36

Does anybody can help me...?
My password all in the db...

**Comment by antelle** [comment]
So, you changed your keyfile to generated one, but haven't saved it, and you haven't switched it back to no keyfile aftet it.
Now your db is locked with this generated keyfile, the only way is to restore from a backup.

**Comment by tristachentw** [comment]
Hi @antelle
Many thanks for your reply, this is bad news for me...
