### ISSUE TITLE
Membership entries hava a wrong creationdate

### ISSUE THREAD

**Issue by gruenheit** [keeweb/keeweb#673]
today I created a membership entry and had trouble to insert the expiry date, the year was wrong, so I changed to year +1 later and saved the file. Since the creation date is set to Feb 17th 2017 and it's not changeable the sorting by date does not work. 
It's reproducible.

KeeWeb v1.5.4 (b730cbd, 2017-06-03)
Environment: electron v1.4.15
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_5) AppleWebKit/537.36 (KHTML, like Gecko) KeeWeb/1.4.0 Chrome/53.0.2785.143 Electron/1.4.15 Safari/537.36

**Comment by antelle** [comment]
There's no option to sort by expiration date.
