### ISSUE TITLE
Default Group

### ISSUE THREAD

**Issue by atomicdecay** [keeweb/keeweb#675]
Not sure how possible this would be, but it would be cool if we were able to set a default group that KeeWeb jumped to once the database was opened (as opposed to defaulting on 'All Items').  I use a number of groups in my database but one specific group is where I keep the majority of my web accounts, which is what I access in KeeWeb about 90% of the time.

**Comment by antelle** [comment]
It will not be in core product, as we don't include overcomplicating options to settings UI and will kinda break the idea of searching experience. But you can create a plugin for it.
