### ISSUE TITLE
KeeWeb Desktop app and Alfresco

### ISSUE THREAD

**Issue by Yaronn44** [keeweb/keeweb#677]
Hello,
I have been asked for my work to see if it's possible to modify the KeeWeb Desktop application to connect it with Alfresco. So each time the file.kdbx is modify and save with one of the app in the enterprise it will modify it on the Alfresco's server.  
Actually I'm quit lost on how it could be done (with a CMIS connector maybe ?) and I don't really see where I should modify or add code to do it.
Also if I understand well the development of the desktop app can only be done on mac ?

If someone can enlighten me it would be great ! Sorry if I posted this at the wrong place, I didn't find somewhere else to do it.

**Comment by antelle** [comment]
Hi,
You will need a plugin for it, we have a special Storage plugins tupe with an interface to implement.
You can start here: https://github.com/keeweb/keeweb/wiki/Plugins

**Comment by antelle** [comment]
closing, as it's more or less question.
