### ISSUE TITLE
Prefill WebDAV settings from query parameters

### ISSUE THREAD

**Issue by djanosik** [keeweb/keeweb#681]
I am working on a web application allowing to share KeePass files in team. All files are hosted on secure WebDAV server, I would like to open KeeWeb application with WebDAV settings prefilled from query string. Do you accept any query string parameters?
```
https://app.keeweb.info/?storage=webdav&url=...&user=...
```

**Comment by antelle** [comment]
No, we don't support parameters in the url, but if you host a config with your files somewhere, you can add `config=` parameter for keeweb, will it work for you?
https://github.com/keeweb/keeweb/wiki/Configuration#json-app-config

**Comment by djanosik** [comment]
That would be even better solution. The only issue is that KeeWeb will not prompt for WebDAV password when not specified in the files section of configuration.

**Comment by antelle** [comment]
Okay, closing then.
About asking for webdav password, it's #669, will be implemented.

**Comment by djanosik** [comment]
Is it now impossible to load custom configuration into https://app.keeweb.info/?

**Comment by antelle** [comment]
It's not possible anymore

**Comment by djanosik** [comment]
Ok, never mind. I have integrated KeeWeb into https://kdbx.online/.
