### ISSUE TITLE
How do I find my keyfile in the 'internal app storage'? label:need help

### ISSUE THREAD

**Issue by koyanoa** [keeweb/keeweb#684]
#Thanks for taking the time to contribute!

Please, read https://github.com/keeweb/keeweb/wiki/FAQ before submitting a new issue and fill in the following (if applicable):

- what were your actions?
- what was wrong?
- app version
- your user-agent (from Settings/Help section)
- does it happen on Demo or New database?
- if you are using a test db without your personal data, please attach it
- please, open dev tools in your browser and attach output log from Console tab 
    (if you are using desktop app, devtools can be opened from Settings/General/Advanced)

**Comment by antelle** [comment]
internal storage is %appdata%/OffilneFiles

**Comment by koyanoa** [comment]
Thank you! I should have specified that I'm on mac. I looked into ~/Library/Application Support and ~/Library/Preferences but couldn't find my .key file, any other places it could be in?

**Comment by antelle** [comment]
About keyfiles, it depends. Have you selected What's the value of _Remember keyfiles_ option in settings? It may be not stored at all.

**Comment by koyanoa** [comment]
Yes, I've selected it to be 'stored in the internal app storage'

**Comment by antelle** [comment]
With keyfiles, it's not that simple. They are stored in app settings, e.g. on mac it's `~/Library/Application Support/KeeWeb/file-info.json`, search for `keyFileHash` inside it.
