### ISSUE TITLE
[Feature Request] Add confirmation box for deleting entries

### ISSUE THREAD

**Issue by Allen-B1** [keeweb/keeweb#685]
I accidentally deleted an entry. Could you add a dialog box asking for confirmation to delete?

**Comment by antelle** [comment]
You can restore it from trash, it's still there, that's why we need it.

**Comment by JulianNymark** [comment]
How does on actually restore from trash? I only found the "permanently delete" button, and i feel like I tried a bunch of normal UX actions (like right clicking the entry in the list, dragging it from the list to the tags view/above the trash icon), i see the item has the "Group: Recycle Bin" property, and It's un-editable? tried double clicking & right clicking etc. I feel I must be missing something obvious.
