### ISSUE TITLE
[Feature request] Reload database

### ISSUE THREAD

**Issue by screendriver** [keeweb/keeweb#687]
Hi,

is it possible to reload a currently opened database from the file system? I have multiple devices that synchronise my keepass.kdbx file seamless over the network. Other KeePass clients informs me that the local file changed and asks me if I want to reload the changes. Also I didn't find an action to reload it manually (at the moment I close keeweb and reopen it)

**Comment by antelle** [comment]
The database is reloading automatically when the file is changed, doesn't it happen for you?
Which OS are you using?

**Comment by screendriver** [comment]
Oh. My fault. It's working. Awesome! 😎 👍
