### ISSUE TITLE
Custom Windows form titlebar color

### ISSUE THREAD

**Issue by jasperweiss** [keeweb/keeweb#689]
For the sake of aesthetics, it'd be nice if the titlebar matches the theme rather than being harsh white in Windows 10.

**Comment by antelle** [comment]
Interesting, didn't know about that. Do you know if it's supported in Electron?

**Comment by Bodup** [comment]
Seems like it isn't unfortunately (see [here](https://github.com/electron/electron/issues/4856). You'd have to make a custom form. But if it's only a bar with maximize, minimize, close buttons it shouldn't be too difficult.

**Comment by antelle** [comment]
we'll support it only if electron supports it.

**Comment by luop90** [comment]
I mean, electron does _technically_ support it, as you can hide the default title bar, and then create your own custom one. Would you be open to a PR with this feature?

**Comment by antelle** [comment]
If you can implement it with a few lines of code, without external dependencies - you're welcome.
There are some technical limitations and we don't have dependency distribution mechanism at the moment.

**Comment by 16patsle** [comment]
You could probably base the UI off of [this](https://github.com/gabrielbull/react-desktop). The files you would be looking for in that case would be [here](https://github.com/gabrielbull/react-desktop/tree/master/src/window/windows). MIT licensed so no problem to borrow some code.

**Comment by 16patsle** [comment]
I made a [quick fiddle](https://jsfiddle.net/16patsle/f4kewbsv/2/) to demonstrate

**Comment by luop90** [comment]
The only issue I've ran into trying to create this is making the top bar draggable. Is there a simple API in Electron to do this that I simply haven't seen? Or does it need a hack?

**Comment by 16patsle** [comment]
Yes, and it is documented in the Electron docs too. https://electron.atom.io/docs/api/frameless-window/#draggable-region

**Comment by antelle** [comment]
We're actually using this webkit-drag in Mac custom titlebar. However, for Mac, it's a built-in feature of Electron/OS.

**Comment by 16patsle** [comment]
I would guess the reason you can hide only the title bar and make the "traffic lights" remain on Mac, but not on Windows has something to do with platform limitations. Would be nice if there could be a built-in Electron feature to make window controls on Windows too even if they are not the native ones, so not every app would need to go through the same procedure of creating native-looking controls.

**Comment by antelle** [comment]
Yes, that's what I meant in the beginning: if Electron supports it, the feature can appear in KeeWeb very quickly. For now, it requires some infrastructural changes, to allow 3rdparty module distribution.

**Comment by Bodup** [comment]
This should do it https://github.com/sidneys/electron-titlebar-windows
I'd work on it myself, if I knew where to start

**Comment by Bodup** [comment]
> This should do it https://github.com/sidneys/electron-titlebar-windows
> I'd work on it myself, if I knew where to start

According to the [guidelines](https://github.com/keeweb/keeweb/blob/master/.github/PULL_REQUEST_TEMPLATE.md), we're not allowed to add dependencies. So [electron-titlebar-windows](https://github.com/keeweb/keeweb/blob/master/.github/PULL_REQUEST_TEMPLATE.md) is not an option? 

It would only be a matter of adding

`const customTitlebar = require('custom-electron-titlebar');`

`new customTitlebar.Titlebar({`
	`backgroundColor: customTitlebar.Color.fromHex('#444')`
`});`

Where `#444` would be the color of the current theme.

**Comment by antelle** [comment]
For this particular dependency, let's add it, because it's not bloated and looks like the feature is not going to appear in Electron for Windows.  
However it's not the matter of adding the code that shows it, there are other changes requires:
- dependency selection: the production section of dependencies of `electron-titlebar-windows` includes unnecessary items, which means, we cannot just distribute everything that's installed
- building: probably something will go wrong, we need to check if it works well

**Comment by WeslyG** [comment]
@antelle Hi, I can try to do this if the add dependency permission is still valid. I really want a nice toolbar on windows)
Is everything still valid?

**Comment by antelle** [comment]
@WeslyG yes of course. But I also see that they still haven't cleaned up dependencies (and the module seems to be abandoned, it was last updated 4 years ago), so you'll probably have to do some cleanup manually or copy-paste it.

**Comment by antelle** [comment]
I've pushed an initial version of custom titlebar for Windows, it looks like this:

<img width="1020" alt="Screen Shot 2021-03-03 at 22 09 24" src="https://user-images.githubusercontent.com/633557/109873179-b3843e80-7c6d-11eb-995a-28b21dfdfe80.png">

But it needs some more style adjustments to be production-ready.

**Comment by antelle** [comment]
Fixed all styles, everything seems to be working and ready to release.

**Comment by antelle** [comment]
Here's the latest version with this feature: https://github.com/keeweb/keeweb-ci-sandbox/releases/latest  
Please give it a try and report issues here if you find anything.

A new release with it is coming soon.

**Comment by antelle** [comment]
It's released 🎉
