### ISSUE TITLE
"more" on start page is dispensable

### ISSUE THREAD

**Issue by quassy** [keeweb/keeweb#690]
When opening KeeWeb a "more" button is displayed which then only includes two elements, which would fit easily, and thus is rather useless and bad for discoverability. Unless there will be more menu items added they should be all displayed at all times and not hidden.

**Comment by Komic** [comment]
agreed, having only the gdrive button under "_more_" is bugging me right now~

**Comment by antelle** [comment]
Well, these options can be disabled with a config. For now we don't remove the more button, however it can be removed in case when we have only a couple of options.
