### ISSUE TITLE
Icon on Windows (small taskbar) seems wrong

### ISSUE THREAD

**Issue by pedrofilho20** [keeweb/keeweb#691]
I'm on a 64bit Windows10, and seems that the Icon on my taskbar is broke

![image](https://user-images.githubusercontent.com/13142568/28506238-4265f108-7000-11e7-9165-098da78d98bb.png)

I think that the old Github Desktop had this issue too, but they correct this.

Its just a small issue..

Thanks a lot for this amazing app

**Comment by antelle** [comment]
Duplicates #531
