### ISSUE TITLE
[Feature Request] config.json: option to use kdb password as webdav password 

### ISSUE THREAD

**Issue by Gol4nTreviz3** [keeweb/keeweb#692]
Hello.
Someone has asked to prompt for the webdav password on the main authentication page.
Same problem here, the security is too low if the webdav password is saved in the conf file.
But in my case, I was thinking to a more "simple" feature :  to use the kdb password as the webdav password via an option in the config file. The password entered in the main page is used to open the webdav folder and the keepass DB at the same time.

**Comment by antelle** [comment]
WebDav passwords are not secure, since they're sent in plaintext. We should not encourage to use such things. If you would like to implement it as a plugin, you can do it.

**Comment by Gol4nTreviz3** [comment]
The webdav folder is hosted in a separate server with SSL. Password is not send in clear text (technically it is but wrapped in SSL encryption).
I am hosting keeweb on a SSL web server with Webdav preconfigured. The password can be read from the conf file. Therefore, any user can download the .kdbx file and upload it to a bruteforce server or replace the file/delete without knowing the kdbx password. Meaning the kdbx file is freely downloadable by everyone. With a Webdav password implementation linked with the kdbx password, only the users knowing the kdbx password can access the Webdav folder.

**Comment by Gol4nTreviz3** [comment]
The option would be "use kdb password for webdav connection". If true then ignore the configured webdav password and use the entered kdb password instead.

**Comment by antelle** [comment]
Well, it's SSL, and if we enforce SSL for such cases, then of course there's no risk sending the password to this server. I can imagine some scenarios where it can be useful, however if an attacker gets access to the server, he will automatically get access to the kdbx stored on this server, this is something violating our concept of keeping your file secure on untrusted storage and transport, and I guess, it's not for mainstream usage, when you have separate passwords for webdav and kdbx. I would do it as a plugin for those who really need it.

**Comment by Gol4nTreviz3** [comment]
The scenario is as follow : Keeweb is published in an intranet environment with preconfigured settings for office users. Users can open the kdbx only if they know the password. The problem is that educated users who don't know the password can launch the debug module of the web browser, get the webdav password, and download the file. If the webdav password is dynamically parsed with this implementation, then we can make sure the file is only accessible for users who know the kdbx password.

**Comment by sainaen** [comment]
@Gol4nTreviz3 
Just curious: how getting kdbx file would help the attacker? They still don't know the password. And if they can somehow “learn” it, they'd be able to download it even in with this change implemented.

**Comment by Gol4nTreviz3** [comment]
If you can freely download the file from the network without any password this is a major risk. You can then upload the file to a bruteforce server and crack it. But more pratically the webdav login has write access (to allow password saving), so the file could be deleted by the attacker or, worst case, replaced by an infected file.

**Comment by sainaen** [comment]
@Gol4nTreviz3 
Thanks! Ok, I see the issue with writable webdav. Do you think #669 would be a reasonable way to achieve the same thing? It'd have a slight overhead asking for a second password, but still you'd be able to set webdav pass to be the same as a password for the kdbx.

**Comment by Gol4nTreviz3** [comment]
The change will at least guarantee that the file is downloadable only by users who knows the kdbx password. Then you may argue that an attacker who break into the webdav server will have access to both webdav password and kdbx password. It's true. But if the attacker can break our webdav server in an intranet only and strongly firewalled environment, the problem is not just about webdav. Also, IIS security will block any IP after 5 failed attempts to login to the webdav server.

**Comment by Gol4nTreviz3** [comment]
@sainaen Yes issue #669 is describing the same security concern

**Comment by antelle** [comment]
For now, you can put keeweb to the same server where you host kdbx files and use something else as webdav password (or, kdbx password, if you prefer).
