### ISSUE TITLE
CORS related Question

### ISSUE THREAD

**Issue by emb3dded** [keeweb/keeweb#700]
Hello

I see some strange behavior on my webServer
If I want to add a WebDAV File which is entered in Form of:
https://FQDN:8443/webdav/file.kdbx
I see the following Headers (FF Developer Tools Headers -> Response Headers):
Access-Control-Allow-Origin:"*"
Access-Control-Allow-Methods:"GET, HEAD, POST, PUT, OPTIONS, MOVE, DELETE, COPY, LOCK, UNLOCK"
Access-Control-Allow-Headers:"origin, content-type, cache-control, accept, authorization, if-match, destination, overwrite"
Access-Control-Allow-Credentials:"true"

BUT, in the Network Tab i can see an  401:
Request Method: Options
Status Code: 401 Unauthorized

It seems like the CORS headers get added but the rewrite does not work. My Apache Config:
```
<Directory /var/www/html/webdav>

Header always set Access-Control-Allow-Origin *
Header always set Access-Control-Allow-Headers "origin, content-type, cache-control, accept, authorization, if-match, destination, overwrite"
Header always set Access-Control-Expose-Headers "ETag"
Header always set Access-Control-Allow-Methods "GET, HEAD, POST, PUT, OPTIONS, MOVE, DELETE, COPY, LOCK, UNLOCK"
Header always set Access-Control-Allow-Credentials "true"

RewriteEngine On
RewriteCond %{REQUEST_METHOD} OPTIONS
RewriteRule ^(.*)$ $1 [R=200,L]

        DAV On
        AuthType Basic
        AuthName "Authentication Required"
        AuthUserFile /etc/httpd/.htpasswd
        Require valid-user
</Directory>
```

Did i miss something or could it be that on the Rewrite does not work on Apache/2.4.6 (CentOS).
I really have no idea how to debug a rewrite. Is there a way to trace such things?

**Comment by antelle** [comment]
It's better to ask somewhere on your server community, in your case, Apache.
