### ISSUE TITLE
Store passphrase in system keychain

### ISSUE THREAD

**Issue by Bodup** [keeweb/keeweb#701]
Would it be possible to store the passphrase in the system keychain?
since the security of the database requires the integrity of the host operating system anyway, it doesn't really matter whether the passphrase is stored on the system or not.
It does allow the user to use more complex passphrases without the inconvenience, which allows for more security if the file is synced with a cloud service.

**Comment by antelle** [comment]
It depends. Keychain can be attacked separately from password manager. So this will not be the default option and we'll not encourage using it.
But the feature makes sense for those who need it, so it should be added.
