### ISSUE TITLE
[Feature request] Synology Cloudstation support

### ISSUE THREAD

**Issue by Thargarius** [keeweb/keeweb#703]
Hello !
For use Keeweb on webdav, CORS must be enable.
On Synology devices this is a problem because its disable.
I have achieved with a lot of config to enable this but next week, with the first DSM update CORS was disabled again...
Is it possible to support Synology Cloudstation ?
It would solve the problem easily...
Thank you for your wonderful work guys !

**Comment by antelle** [comment]
Unfortunately, as you're saying CORS cannot be enabled, it's not possible.
As a workaround, you can put keeweb html right on your synology server and open it from there in your browser, it will work.

**Comment by skad** [comment]
Hi, just for information and maybe need to go in the wiki
for enable the CORS on webdav server in Synology:
```
ssh ip-synology
cd /var/packages/WebDAVServer/target/etc/httpd/
sudo vim conf/httpd.conf-webdav
   add LoadModule rewrite_module modules/mod_rewrite.so
sudo vim conf/extra/httpd-ssl.conf-webdav
   add https://github.com/keeweb/keeweb/wiki/WebDAV-Config infos for apache

cd /var/packages/WebDAVServer/target/tools
sudo ./start_stop.sh start restart
```
Keeweb must ask for the password of the kdbx file

Sadly, the next update of the webdav server will break this :/

**Comment by alexanderharm** [comment]
I wrapped @skad's solution into a little bash-script which you can run periodically via Synology's task manager. It creates/restores the necessary settings. You can find the repo here:
<https://github.com/alexanderharm/syno-webdav-keeweb>

**Comment by iromeister** [comment]
Does this still work in 2020? I tried but still am getting stat errors.

**Comment by sshaginyan** [comment]
Does this work in 2020?

**Comment by ben-ba** [comment]
> Does this still work in 2020? I tried but still am getting stat errors.



> Does this work in 2020?

It still works, but only with the webversion of keeweb (self hosted, or https://app.keeweb.info)

1. Follow the instructions by skad
2. Access your keeweb instance over https; https://<IP>:<Port>
3. Insert your webdav url; https://<IP>:<Port>/home/keepass/keys.kdbx    (default port ist 5006)
4. Hit ok, got an error "Error: network error"? all things are fine for now, next step
5. Open a new tab insert your webdav url ones more, ignore the ssl certificate warnings (you know what you do), insert your credentials, break the download and close this tab, exception for this browser on this machine is saved
6. Got back to keeweb, hit ok once more, error message should be now "error: http status 401"
7. Insert user and pass
8. finished

Not all Browsers work, so far i tested:

Windows 10 + Firefox -> works
Windows 10 + Chrome -> works
Windows 10 + Internet Explorer -> didn't work
Windows 10 + Edge -> didn't work
macOS Catalina + Safari ->works
macOS Catalina + Firefox -> works

**Comment by DachsbauTV** [comment]
It's really weird. WebDAV does work for me with the official https://app.keeweb.info but as soon as I start a self hosted instance, I get the following errors:
![Screenshot 2021-02-22 at 11 03 56](https://user-images.githubusercontent.com/70434961/108693536-3d116f00-74fe-11eb-82e7-55c96e96d500.jpg)

Any idea what could cause this?

**Comment by antelle** [comment]
@DachsbauTV Network panel in your devtools can reveal the issue

**Comment by DachsbauTV** [comment]
![Screenshot 2021-02-22 at 11 03 56](https://user-images.githubusercontent.com/70434961/108757341-02cdbf00-754a-11eb-9a28-97acaeb5fbcb.jpg)
This still leaves me confused...
When i connect to the webdav file through my browser i can download it normally

**Comment by antelle** [comment]
If you download it from the same host or manually, it will work indeed. The problems is when another website is trying to download it from your behalf, that's what CORS is for.

**Comment by DachsbauTV** [comment]
I've setup the CORS script though and tried @ben-ba  s workaround.

And it seems to work for the first time it connects (in a browser or on a device) and afterwards it won't

**Comment by alexanderharm** [comment]
> Does this work in 2020?

Does work for me in 2021. However, it needs a valid certificate now which was not the case back then. I will open a seperate issue to ask for an option to allow self-signed certificates.

**Comment by antelle** [comment]
If you trust the self-signed certificate in the system keychain, you will be able to use it.

**Comment by alexanderharm** [comment]
Thanks for the hint.

**Comment by Meloman-zz** [comment]
Anyone did the same for passing CORS accross Application Portal of Synology for a VM (API as a js loaded from other website) ?

**Comment by jortfal** [comment]
Hi,

In DSM 7 `synoservice` has been replaced by `systemctl`. And tool `start_stop.sh` (/var/packages/WebDAVServer/target/tools) a is no longer available.

Therefore it is necessary to modify the line "synoservice --restart pkgctl-WebDAVServer" by 

`sudo systemctl restart pkgctl-WebDAVServer`

Another option is to manually restart WebDAV => https://www.howtogeek.com/322201/how-to-stop-andrestart-applications-on-your-synology-nas/

I have opened an issue in the repository https://github.com/alexanderharm/syno-webdav-keeweb in respect this https://github.com/alexanderharm/syno-webdav-keeweb/issues/3 

Regards
