### ISSUE TITLE
[Feature request] Hide empty fields from display

### ISSUE THREAD

**Issue by 16patsle** [keeweb/keeweb#704]
When using the app I noticed that certain types of entries only really need a few of the default fields. It is for example a bit superfluous to have a website field if you are putting in a credit card, or the password to your local machine.

My proposition is to optionally be able to hide empty fields, either through a setting, or through a button with an icon, like an eye, for example to the right of the "Delete" button. This would overall lead to less visual clutter in the UI. 

An extension of this feature would be to be able to hide fields by default on templates, and have those fields be hidden on entries made from that template (like having a credit card template that hides the website field).

**Comment by 16patsle** [comment]
I just discovered that there is indeed a "Hide empty" feature, I just didn't look for it in the More dropdown. Though I think it should be more obvious.

But my idea about the template thing still applies, I believe (correct me if I'm wrong).

**Comment by antelle** [comment]
We cannot distinguish between entries created from templates and now, and if we would, we still shouldn't: just one setting for all entries is enough.
