### ISSUE TITLE
Autotype with obfuscation sometimes fails

### ISSUE THREAD

**Issue by JochenDiekenbrock** [keeweb/keeweb#708]
- what were your actions?

crl-shift-t (autotype) with obfuscation (mix real keystrokes with random) on Website https://kunde.comdirect.de/lp/wt/login?execution=e2s1

- what was wrong?

Entry  fails, some wrong characters are displayed.
If obfuscation is switched off, login works fine. Timing problem? Perhaps an option to limit the key rate would help?

- app version

KeeWeb v1.5.4 (b730cbd, 2017-06-03)
Environment: electron v1.4.15

- your user-agent (from Settings/Help section)
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) KeeWeb/1.5.4 Chrome/53.0.2785.143 Electron/1.4.15 Safari/537.36

- does it happen on Demo or New database?
- if you are using a test db without your personal data, please attach it
- please, open dev tools in your browser and attach output log from Console tab 
    (if you are using desktop app, devtools can be opened from Settings/General/Advanced)

...more similar lines left out, apparently successful key strokes....
2017-08-05T09:42:24.915Z [launcher] spawn xdotool: 0, 158ms index.html:14 
2017-08-05T09:42:26.070Z [launcher] spawn xdotool: 1, 1149ms xdotool: Unknown command: E
Run 'xdotool help' if you want a command listo.error @ index.html:14
2017-08-05T09:42:26.070Z [auto-type] Run error Exit code 1

**Comment by antelle** [comment]
Could you please open devtools, execute this:
```javascript
localStorage.autoTypeDebug = 1;
```
and see what's there before `Unknown command: E`?
Probably linux-specific.

**Comment by JochenDiekenbrock** [comment]
No more information, I think:

2017-08-05T10:34:15.334Z [launcher] spawn xdotool: 0, 96ms index.html:14 
2017-08-05T10:34:16.423Z [launcher] spawn xdotool: 1, 1086ms
xdotool: Unknown command: 
Run 'xdotool help' if you want a command list

2017-08-05T10:34:16.425Z [auto-type] Run error Exit code 1 index.html:14 

o.error	@	index.html:14
(anonymous function)	@	index.html:14
l.emitNext	@	index.html:20
complete	@	index.html:17
(anonymous function)	@	index.html:20
emitTwo	@	events.js:106
emit	@	events.js:191
maybeClose	@	internal/child_process.js:877
(anonymous function)	@	internal/child_process.js:334
emitOne	@	events.js:96
emit	@	events.js:188
_handle.close	@	net.js:493

**Comment by JochenDiekenbrock** [comment]
The character after unknown command is not displayed at all in the console. When I pasted it here it was displayed as a triangle pointing to the right. Tab keystroke perhaps?

**Comment by JochenDiekenbrock** [comment]
Here's a new log. On the first try after entering the above comment, the login succeeded, a second try failed.
[log.txt](https://github.com/keeweb/keeweb/files/1202307/log.txt)

**Comment by antelle** [comment]
This should be fixed in v1.17

**Comment by antelle** [comment]
Closing this, since it's a rather old issue. If it still repeats, please let me know.
