### ISSUE TITLE
keewebhttp plugin does not work with KeePassHelper in Safari

### ISSUE THREAD

**Issue by ericbn** [keeweb/keeweb#709]
- what were your actions? Unlock database in KeeWeb, install [KeePassHelper plugin](https://safari-extensions.apple.com/details/?id=com.add0n.keepass-RED8XKG2R4) v0.1.1. in Safari v10.1.2, open a website with a login page, and click on the KeePassHelper button on the Safari toolbar.
- what was wrong? KeePassHelper dialog shows "Cannot connect to KeePassHTTP. Either KeePass is not running or communication is broken". Expected KeePassHelper to connect to keewebhttp.
- app version: KeeWeb v1.5.4 (b730cbd, 2017-06-03) with keewebhttp v0.1.0
- your user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) KeeWeb/1.5.0 Chrome/53.0.2785.143 Electron/1.4.15 Safari/537.36
- does it happen on Demo or New database? Yes
- please, open dev tools in your desktop app and attach output log from Console tab: No new output logged during process above.

**Comment by antelle** [comment]
Fixed, please update keewebhttp.

**Comment by ericbn** [comment]
Thank you one more time for your amazing work!

**Comment by emmanuelbbc** [comment]
Issue present with KeeWeb v1.5.6 (10229e7, 2017-08-31) and KeewebHttp 0.1.2 on MacOsX.

Tested with Safari KeePassHelper plugin or Firefox with Passifox.
