### ISSUE TITLE
[Plugin Idea/Request] Automatic Password Changer

### ISSUE THREAD

**Issue by stefnats** [keeweb/keeweb#710]
Hi,

i love Keeweb, because it's intuitive, built on modern technologies and because it's open source.
I also love Dashlane, because it has some nice features, for example an automatic password changer. But i also hate it, because i'm not in control of my data.

So my suggestion: Let's implement an automatic password changer for Keeweb as a plugin. Following features come to mind:

- Single click to change password on site
- Reminder for passwords that were not changed in a long time (threshold configurable)
- Maybe an interface to create scripts for changing passwords on sites

This is it in Dashlane: https://www.dashlane.com/features/password-changer

**Comment by antelle** [comment]
This makes sense.
Reminder will be implemented in audit (which will be in next release).
After it, we can make a button to change all outdated passwords or some of them.

**Comment by stefnats** [comment]
Would you implement the automatic change as a core component or as a plugin?
I haven't dived into implementing plugins for Keeweb yet, but would it be possible to load external components (say, PhantomJS) and do prompts with inputs (For Captcha, 2FA, etc.)?

**Comment by antelle** [comment]
No, automatic changing of passwords on the websites is not possible. We can implement something like UI, which will say, this password is old, let's change it, and guide you through the process of changing it in the password manager, but websites are way too different to change the password automatically. I think it's not possible to implement as a plugin as well, it will not be maintainable. For now, there's no plans to support native components in plugins, but maybe this will change, if there's a reason to have native modules.

**Comment by LosEagle** [comment]
Can't this be achieved by user-defined macros? The Electron app can already autofill forms. Giving it set of instructions on where to navigate and what form to fill in order to change password shouldn't be any different. Of course the web design changes all the time but then it would be up to user to update those instructions.

**Comment by stefnats** [comment]
Absolutely, it'd be hard to maintain, but i was thinking of a similar approach like @LosEagle 
Users could share / create their own scripts, maybe even based on PhantomJS.

**Comment by antelle** [comment]
Using a lot of userscripts would open a huge possibility of attacks, it's not something you would like to use in your password manager, and I don't see any effective mechanism of prevention such attacks. When it's maintained by a company (like dashlane, etc...), that's fine, since you already trust the password manager.

**Comment by stefnats** [comment]
That's a valid Point, @antelle 
So two options for this would be:

1. implement this as a feature "native" in keeweb
2. implement this with user scripts

2 is not safe at all and 1 is not maintainable. I see that.

**Comment by antelle** [comment]
Let's close this issue, it's not actionable. Audit is another thing, it will be there, but password changer doesn't seem to be realistic.

**Comment by xieve** [comment]
This can be easily achieved through advanced auto-type presets in your root folder in the standard KeePass, but sadly KeeWeb has no {NEWPASSWORD} substition thing. I'm opening a feature request. ^^

**Comment by antelle** [comment]
@xieve there are a lot of questions about it:
- how to validate that the password has been changed?
- when to save it?
- which rule use to generate it?
And so on. It should depend on the website and be regularly validated, otherwise it's quite dangerous.

**Comment by xieve** [comment]
@antelle keeweb would only do that supervised. Like it prompts the user: Hey this password should be changed, takes the user to the site where he clicks on the right field and then, if there's no need to change the auto-type string because of design, he just initiates auto-type as usual.

**Comment by antelle** [comment]
This is slightly different from what was discussed in this issue.
Although it can be implemented, it doesn't have such value as the idea described above. But yes, probably it's the only way.
