### ISSUE TITLE
KeeWeb fails to launch on Windows after first restart

### ISSUE THREAD

**Issue by hameerabbasi** [keeweb/keeweb#711]
# What were your actions?

1. Installing KeeWeb
2. Running it, signing in to Dropbox, opening my KeePass store, and then closing it and restarting the PC.

# What was wrong?
It wouldn't launch after that. The window didn't even show up. If I uninstall/reinstall and launch, that temporarily fixes it. I even deleted everything KeeWeb related from AppData and it still happens.

# App version
1.5.4

# Please, open dev tools in your browser and attach output log from Console tab 
Can't, because the window doesn't show up.

Willing to provide any additional information if required.

**Comment by antelle** [comment]
Hi!
How do you start it? Does it start, if you don't sign in to Dropbox? What's your Windows version?

**Comment by hameerabbasi** [comment]
I start it from the start menu or double-clicking the .exe. I'm not sure, I'll check and get back to you. Windows 10.

**Comment by antelle** [comment]
Maybe you have _Minimize to tray_ option turned on and it's started, but minimized? Please check if there's an icon in your tray.
