### ISSUE TITLE
Cannot set changed password, after sync

### ISSUE THREAD

**Issue by max-wittig** [keeweb/keeweb#712]
After changing my keepass password on my main machine, I expected to login to my other machine as normal and expected the database to get synced (via dropbox) after I logged in to change the password. That worked, but after that an error occured

![image](https://user-images.githubusercontent.com/6639323/29253140-223b8db2-8076-11e7-8658-957b23fdf779.png)

Unfortunately it's not possible to click the `OK` Button to confirm the new password. Instead this message appears in the developer console
<pre>
2017-08-13T20:21:38.345Z [sync:keepass] Load from storage Object {rev: "e4449b84e6"} no error
index.html:16 2017-08-13T20:21:38.372Z [file] Error opening file to merge InvalidKey Error InvalidKey: invalid key KdbxError {name: "KdbxError", code: "InvalidKey", message: "Error InvalidKey: invalid key"}s.error @ index.html:16(anonymous function) @ index.html:18
index.html:16 2017-08-13T20:21:38.373Z [sync:keepass] Merge complete KdbxError {name: "KdbxError", code: "InvalidKey", message: "Error InvalidKey: invalid key"}
index.html:16 2017-08-13T20:21:38.415Z [sync:keepass] Remote key changed, request to enter new key
index.html:16 2017-08-13T20:21:38.424Z [sync:keepass] Sync finished KdbxError {name: "KdbxError", code: "InvalidKey", message: "Error InvalidKey: invalid key"}code: "InvalidKey"message: "Error InvalidKey: invalid key"name: "KdbxError"__proto__: Object
index.html:24 Uncaught TypeError: Cannot read property 'el' of nullaccept @ index.html:24inputKeydown @ index.html:24dispatch @ index.html:3q.handle @ index.html:3
index.html:24 Uncaught TypeError: Cannot read property 'el' of nullaccept @ index.html:24dispatch @ index.html:3q.handle @ index.html:3
</pre>

* KeeWeb v1.4.0
* User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) KeeWeb/1.4.0 Chrome/53.0.2785.143 Electron/1.4.15 Safari/537.36

**Comment by max-wittig** [comment]
nvm seems to be fixed in 1.5.4

**Comment by antelle** [comment]
yes, it was #628
