### ISSUE TITLE
Information needed about Dropbox/Google Drive/OneDrive pre-defined files

### ISSUE THREAD

**Issue by Komic** [keeweb/keeweb#716]
https://github.com/keeweb/keeweb/wiki/Configuration
https://github.com/keeweb/keeweb/wiki/Dropbox-and-GDrive

Just finished setting up KeeWeb, thanks for all your work, great piece of software! As a finishing touch, I'm trying to add my gdrive-hosted database as a pre-defined file, but I'm having issues figuring out what to use as `path`. Any idea?

**Comment by antelle** [comment]
It's not possible to pre-configure databases stored in Google Drive.

**Comment by Komic** [comment]
Alright, then I guess it could make a great addition. Cheers~

**Comment by matteustace** [comment]
I tried this and was surprised to find that, despite the above, it does appear to work, using the ID of the Google Drive object as the path.

**Comment by Komic** [comment]
I can actually confirm this, I found two gdrive-related IDs in the log, using the smaller one as `path` works perfectly. Closing this!
