### ISSUE TITLE
A few suggestions for improvement

### ISSUE THREAD

**Issue by i-panov** [keeweb/keeweb#718]
I really liked this program. An excellent analogue to the obsolete KeePass2. But it is still very "raw". Here are a few suggestions for improvement:

1. Now all groups are displayed in groups, including elements from subgroups. I propose to do the same as in KeePass2: only the elements of the group should be displayed, without subgroup elements. This is much more logical and convenient.
2. Now you can add new fields to the elements, but you can not delete them or change their name. It is necessary to correct it.
3. In the original KeePass2 there are a lot of options for import and export. Is it possible to somehow transfer them here, at least in part?
4. It would be nice to make it possible to change hotkeys.

By the way, do you plan to make a version for smartphones? You could also do it on the JS (for example NativeScript or ReactNative).

**Comment by antelle** [comment]
1. you can switch it in settings
2. it's possible to change field name, click its name to edit (probably we should find a better ux solution for that, it's causing quite a lot of questions)
3. we should do export/import in future, however I don't know when this happens; probably will be implemented as a plugin, see `import/export` label for open issues about it
4. it's #348

Actually, there's nothing new in this issue, closing.

**Comment by i-panov** [comment]
> it's possible to change field name, click its name to edit (probably we should find a better ux solution for that, it's causing quite a lot of questions)

You checked it yourself? When I click on the name of the field, its contents are copied to the clipboard. No editing takes place. Editing is available only for the contents of the field, but not its name. And I also asked about the removal of fields. You did not answer.

**Comment by antelle** [comment]
> You checked it yourself? 
> You did not answer.

Please learn how to use the appropriate language first, okay? You came to ask a question, and not to blame. People are not going to spend their time for free to read _this_.

You can set the field value to empty string, to delete it. Field name editor can be opened when you're in field editing mode (i.e. start to edit it and click field name then). Only custom fields can be edited or deleted. As noted before, field editing UX should be improved, including these issues.

**Comment by i-panov** [comment]
> Please learn how to use the appropriate language first, okay? You came to ask a question, and not to blame. People are not going to spend their time for free to read this.

I did not try to offend you. And I did not blame anything, just asked if you tried it yourself.

> You can set the field value to empty string, to delete it. Field name editor can be opened when you're in field editing mode (i.e. start to edit it and click field name then). Only custom fields can be edited or deleted. As noted before, field editing UX should be improved, including these issues.

At last. And yes, this is really an extremely unevident behavior.

Thanks for the help. Do not be offended! :)
