### ISSUE TITLE
IIS Server configuration RUS

### ISSUE THREAD

**Issue by alkopit** [keeweb/keeweb#719]
Помогите с настройкой IIS
Сделал в IIS сайт, положил в его корень файлы из keeweb-gh-pages, установил SSL сертификаты, сделал файл config.json и поменял index.html
Не открывается сайт при запросе вида https://your-keeweb-deployment-url/?config=your-config.json
И неверно считывается index.html
Что я упустил? в чем проблема?

**Comment by alkopit** [comment]
Вот что выводит консоль хрома

Document was loaded from Application Cache with manifest https://kw.itavg.ru/manifest.appcache
kw.itavg.ru/:1 Application Cache Checking event
(index):1 Application Cache NoUpdate event
(index):14 2017-08-29T13:53:28.624Z [app] Error loading app config Malformed JSON
o.error @ (index):14
(anonymous) @ (index):18
XMLHttpRequest.send (async)
(anonymous) @ (index):18
loadConfig @ (index):18
(anonymous) @ (index):27
Promise resolved (async)
R @ (index):27
Promise resolved (async)
(anonymous) @ (index):27
j @ (index):10
k @ (index):10
setTimeout (async)
(anonymous) @ (index):10
i @ (index):10
fireWith @ (index):10
fire @ (index):10
i @ (index):10
fireWith @ (index):10
ready @ (index):11
R @ (index):11
(index):18 XHR finished loading: GET "https://kw.itavg.ru/config.json".
(anonymous) @ (index):18
loadConfig @ (index):18
(anonymous) @ (index):27
Promise resolved (async)
R @ (index):27
Promise resolved (async)
(anonymous) @ (index):27
j @ (index):10
k @ (index):10
setTimeout (async)
(anonymous) @ (index):10
i @ (index):10
fireWith @ (index):10
fire @ (index):10
i @ (index):10
fireWith @ (index):10
ready @ (index):11
R @ (index):11
(index):14 2017-08-29T13:53:28.632Z [app] Error starting app Error loading app config
o.error @ (index):14
(anonymous) @ (index):27
Promise rejected (async)
(anonymous) @ (index):27
j @ (index):10
k @ (index):10
setTimeout (async)
(anonymous) @ (index):10
i @ (index):10
fireWith @ (index):10
fire @ (index):10
i @ (index):10
fireWith @ (index):10
ready @ (index):11
R @ (index):11

**Comment by antelle** [comment]
Две проблемы.
1.
```
wget -S -O - https://kw.itavg.ru/config.json
  HTTP/1.1 200 OK
  Cache-Control: private
  Content-Type: text/html <-------- should be application/json
  Server: Microsoft-IIS/10.0
  X-Powered-By: ASP.NET
  Content-Length: 70
```
2. 
```
{
  "settings": {
    "theme": "fb",
    "locale": "ru"   
  }, <------- invalid json, comma is not allowed here
}
```

**Comment by alkopit** [comment]
Спасибо.
У меня настроен обработчик JSON, но никак не пойму почему вместо application/json IIS отдает Content-Type: text/html ...

**Comment by antelle** [comment]
`¯\_(ツ)_/¯`
если исправить `},` может быть будет работать и так.

**Comment by alkopit** [comment]
Я исправил запятую после скобки.
Config.json сейчас выглядит так
{
  "settings": {
    "theme": "fb",
    "locale": "en",
	"gdriveClientId": xxx.apps.googleusercontent.com
  }
}

**Comment by antelle** [comment]
https://jsonlint.com

"gdriveClientId": "..."

**Comment by alkopit** [comment]
... не работает.
сейчас поднял апач на ubuntu 16.04.3 + LAMP
положил в папку /var/www/html файлы из архива keeweb-gh-pages
сделал config.json поправил файл index.html (content=(no-config) поменял на "config.json")
вот содержание конфига:
```
{
  "settings": {
    "theme": "fb", // UI theme, possible values: fb (flat blue), wh (white), hc (high contrast) and other
    "locale": "en", // language
    "canOpen": true, // show Open button
    "canOpenDemo": false, // show Demo button
    "canOpenSettings": true, // show Settings button
    "canCreate": true, // show Create button
    "canImportXml": true, // show Import XML button
    "dropbox": false, // enable Dropbox
    "gdrive": true, // enable Google Drive
    "gdriveClientId": "475261058701-2cfg0n1qhmpkge9tlc760l18melr28a8.apps.googleusercontent.com", // custom client id
    "onedrive": false // enable OneDrive
  }
}
```
не раотает конфиг.  Gdrive ID не меняется, настройки не меняются.

вот вывод команды wget -S -O - https://kw.itavg.ru/config.json
appliance@bf-zabbix:~$ wget -S -O - https://kw.itavg.ru/config.json
--2017-08-30 06:49:30--  https://kw.itavg.ru/config.json
Resolving kw.itavg.ru (kw.itavg.ru)... 5.35.67.8
Connecting to kw.itavg.ru (kw.itavg.ru)|5.35.67.8|:443... connected.
HTTP request sent, awaiting response...
  HTTP/1.1 200 OK
  Date: Wed, 30 Aug 2017 06:49:12 GMT
  Server: Apache/2.4.18 (Ubuntu)
  Last-Modified: Wed, 30 Aug 2017 06:39:49 GMT
  ETag: "281-557f2cb61934a"
  Accept-Ranges: bytes
  Content-Length: 641
  Keep-Alive: timeout=5, max=100
  Content-Type: application/json
  Proxy-Connection: Keep-Alive
Length: 641 [application/json]
Saving to: ‘STDOUT’

 0% [                                                                                                     ] 0           --.-K/s              {
  "settings": {
    "theme": "fb", // UI theme, possible values: fb (flat blue), wh (white), hc (high contrast) and other
    "locale": "en", // language
    "canOpen": true, // show Open button
    "canOpenDemo": false, // show Demo button
    "canOpenSettings": true, // show Settings button
    "canCreate": true, // show Create button
    "canImportXml": true, // show Import XML button
    "dropbox": false, // enable Dropbox
    "gdrive": true, // enable Google Drive
    "gdriveClientId": "475261058701-2cfg0n1qhmpkge9tlc760l18melr28a8.apps.googleusercontent.com", // custom client id
    "onedrive": false // enable OneDrive
  }
}
100%[====================================================================================================>] 641         --.-K/s   in 0s

2017-08-30 06:49:30 (32.7 MB/s) - written to stdout [641/641]


в чем проблема тоооооо???
в WIKI написано что все как то просто и из коробки работает.... а на деле все как обычно.

**Comment by sainaen** [comment]
> в чем проблема тоооооо???

В JSON нельзя комменты `// бла-бла`

[Без них](https://sainaen.com/config.json) всё [ок](https://app.keeweb.info/?config=https://sainaen.com/config.json). (Убрал `gdriveClientId`, на всякий случай.)

@antelle 
Это, кстати, ок, что можно грузить конфиг с другого домена? Выглядит не очень безопасно, учитывая возможность включить какие-нибудь «интересные» плагины.

**Comment by alkopit** [comment]
Оуеее)) Заработало)
Спасибо. Надо бы ман чтоль какой то с примерами конкретными сделать типо how-to.
Довольно сложно разобраться самостоятельно в таких нюансах обычным смертным, особенно учитывая, что в Wiki в разделе Configuration указан JSON с комментариями.

**Comment by alkopit** [comment]
Еще вопрос по конфигу с локалью.
Если указываю "ru" то локаль не меняется. Я так понимаю это из-за отсутствия плагина. А как можно это исправить? Что бы пользаку новому не надо было ходить за плаином, а сразу открывалась страница на Русском языке?

**Comment by sainaen** [comment]
> Что бы пользаку новому не надо было ходить за плаином, а сразу открывалась страница на Русском языке?

Похоже, достаточно [включить плагин](https://sainaen.com/config.json) в конфиге: [результат](https://app.keeweb.info/?config=https://sainaen.com/config.json)

**Comment by antelle** [comment]
@sainaen 
это совсем не ок
++, fixed, rolled out

**Comment by sainaen** [comment]
@antelle 
Извини, надо было приватно написать. Подумал когда уже запостил. :)

**Comment by alkopit** [comment]
Все работает, большое спасибо за помощь.
antelle, спасибо за отличное ПО.
У меня вопрос по поводу плагинов, а как их можно скачать, что бы разместить у себя на сервере?

**Comment by antelle** [comment]
@alkopit https://github.com/keeweb/keeweb-plugins/archive/master.zip
