### ISSUE TITLE
Offline translations

### ISSUE THREAD

**Issue by xesarni** [keeweb/keeweb#720]
How to use them? I'm trying with the JSON app config but with no success (Error loading app). Something like this doesn't work:
```
 {
 	"settings": {
 		"locale": "es-ES"
 	},
 	"plugins": [{
 		"url": "es-ES.json"
 	}]

 }
```
I just don't know how to configure it exactly.

**Comment by antelle** [comment]
Hi! It should be the full url:
"url": "https://plugins.keeweb.info/translations/es-ES"

**Comment by xesarni** [comment]
H! But it's not offline. Is it possible to read the translation file from the local disk?

**Comment by antelle** [comment]
A web page cannot read files from disk, so it's not possible.
However, you can host some plugins on your server and point the url to it.

**Comment by xesarni** [comment]
Do I need to modify manifest.json & index.html from the es-ES folder?

**Comment by antelle** [comment]
no, just host it as is

**Comment by xesarni** [comment]
OK, now it's working. Thanks for your help!
