### ISSUE TITLE
Cannot find Google Drive database file

### ISSUE THREAD

**Issue by kongy** [keeweb/keeweb#723]
- what were your actions?
  Open a database file stored on Google Drive
- what was wrong?
  "Nothing found, no files which could be opened." error 
- app version: 1.5.5
- your user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 
- does it happen on Demo or New database? N/A
- if you are using a test db without your personal data, please attach it N/A
- please, open dev tools in your browser and attach output log from Console tab 
    (if you are using desktop app, devtools can be opened from Settings/General/Advanced)

app.keeweb.info/:1 Document was loaded from Application Cache with manifest https://app.keeweb.info/manifest.appcache
app.keeweb.info/:1 Application Cache Checking event
(index):14 2017-08-31T14:57:31.656Z [app] Started in 341ms ¯\_(ツ)_/¯
(index):1 Application Cache NoUpdate event

Response from Google Drive:
{
 "files": []
}

**Comment by kasoban** [comment]
Does your file name end in .kdbx? Can you check in the Drive webinterface, when you click on the file, does it say in the info box on the right "Type: Binary File"?

**Comment by kongy** [comment]
Yes. Besides, I'm still able to open the file from my other computer which has the database file in the recently opened database history.

**Comment by antelle** [comment]
Will be kinda solved in the next version, with Open dialog capable to open folders.

**Comment by antelle** [comment]
Next version will allow to select any file and go inside folders:
![gdrive](https://user-images.githubusercontent.com/633557/33243586-63946bba-d2e9-11e7-977e-219254d86c24.png)
