### ISSUE TITLE
Webapp JSON config broken in 1.5.6?

### ISSUE THREAD

**Issue by xesarni** [keeweb/keeweb#724]
Upgraded KeeWeb from 1.5.5 to 1.5.6 and now I'm getting Error loading app error. Restarting a server, using browsers with clean profiles and the stock config file didn't help. No errors after downgrading to 1.5.5.

**Comment by antelle** [comment]
How are you trying to load your config?
Since 1.5.6, it's possible to load it only from the same server.

**Comment by antelle** [comment]
Probably you're getting this error, right?
```
Error starting app DOMException: Failed to execute 'removeChild' on 'Node'
```
Should be fixed.

**Comment by antelle** [comment]
Deployed to [beta.keeweb.info](https://beta.keeweb.info), will be available in the next release.

**Comment by Matthaiks** [comment]
Yeah, that's the error. I'll stick with 1.5.5. Thanks!

**Comment by xesarni** [comment]
Thanks!

**Comment by antelle** [comment]
let's keep it open, since it's still broken in this version

**Comment by Ciiss0u** [comment]
Hi i also have related problem starting from 1.5.6 :
![image](https://user-images.githubusercontent.com/16646471/30086555-e25d8e4c-929b-11e7-922c-0cbb3dc8f5f0.png)

Thanks for your great work anyway.

**Comment by antelle** [comment]
Yes, 1.5.6 has problems with config, it cannot be used. You can use v1.5.5 for selfhosting for now.

**Comment by SkYNewZ** [comment]
Hello, i had this problem too and i understand i have to deploy beta or release 1.5. But anyone can help me about the "deployment" procedure ? I know how to deploy the safe-hosting but not the "normal" release.

Thank!

**Comment by antelle** [comment]
@SkYNewZ "deployment" in this case means just to copy the html file. So, select the desired version from gh-pages and check it out: https://github.com/keeweb/keeweb/commits/gh-pages

**Comment by SkYNewZ** [comment]
@antelle Yeah **thank you,** my app work fine! (Except "locale", It looks like is not considered)
