### ISSUE TITLE
Webapp, windows app problem

### ISSUE THREAD

**Issue by XaBerr** [keeweb/keeweb#725]
A file created with the webapp does not recognize the password if it is opened with the windows app.

Webapp info:
KeeWeb v1.5.6 (10229e7, 2017-08-31)
Environment: web
User-Agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36

Windows app info:
KeeWeb v1.5.6 (10229e7, 2017-08-31)
Environment: electron v1.6.11
User-Agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) KeeWeb/1.5.6 Chrome/56.0.2924.87 Electron/1.6.11 Safari/537.36

**Comment by XaBerr** [comment]
Windows app info:
KeeWeb v1.5.6 (10229e7, 2017-08-31)
Environment: electron v1.6.11
User-Agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) KeeWeb/1.5.6 Chrome/56.0.2924.87 Electron/1.6.11 Safari/537.36

**Comment by antelle** [comment]
Hi! Could you please elaborate more?
How do you create a file? Is it possible to open it in webapp again, if you unlink/delete it? Is it protected with a password, or password + keyfile?

**Comment by XaBerr** [comment]
The file is called **New.kdbx**.
I created it about a year ago via the "dropbox" setting of the webapp.
I just tried to unlink it. Now the webapp does not open it anymore.
If I try to open it with the "dropbox" and "open" (adding mannualy the path) in webapp setting, the password does not work anymore.
I think only password, how I can check?

**Comment by antelle** [comment]
Probably the file somehow got stored in the internal app storage.
Is it possible to repeat this from the beginning to get into this? I still don't understand full steps.

**Comment by XaBerr** [comment]
Steps:
1) File is stored in my dropbox.
![screenshot 2017-09-04 19 56 50](https://user-images.githubusercontent.com/16030020/30035513-40bdb7ec-91ab-11e7-9328-0a59772f6c48.png)

2) I can access it from the webapp but when I enter my password does not work.
![keewebdropbox](https://user-images.githubusercontent.com/16030020/30035568-d496f08c-91ab-11e7-9a2c-9b130f9d7832.JPG)

3) I noticed that I could not access it when I tried yesterday to get in with the windows application.

4) The webapp probably worked because it was connected. Now that I unplugged and tried to reconnect it, it does not work anymore.

5) I'm pretty sure the file was the one for two reasons: I just have that file; a couple of months ago I connected it back to the web because it had canceled the link.

**Comment by XaBerr** [comment]
I think I made a big mistake. The file I just posted has the date of last editing on July 18th. Instead, the file I used should have today as the last change. Probably on July 18th I must have duplicated it by mistake or saved it in the webapp. Now I imagine I can not retrieve it since I disconnected it.

**Comment by antelle** [comment]
Probably that's what happened, yes... No, there's no way to restore. I guess, it makes sense to download files when you delete it or make something like trash. However, this is another discussion.
