### ISSUE TITLE
No Backup to Dropbox

### ISSUE THREAD

**Issue by r100gs** [keeweb/keeweb#727]
THX for the great app!
A the moment I have Problem:
Backup to Dropbox is not working anymore. It was fine in the past.

I get the error message:

Fehler beim Schreiben der Sicherungsdatei
Cannot stat backup folder

The webapp log shows:
[ERROR] 2017-09-08T08:44:16.642Z [storage-dropbox] API error files/get_metadata 400 Error: Network error
[ERROR] 2017-09-08T08:44:16.643Z [backup:Stefan] Stat folder error Error: Network error

Best regards,
Stefan

KeeWeb v1.5.6 (10229e7, 2017-08-31)
Environment: web
User-Agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36

**Comment by antelle** [comment]
Hi!
I can't reproduce it. Is KeeWeb linked to Dropbox? I mean, is it possible for you to open normal files from Dropbox, not only save backups?

**Comment by acrox999** [comment]
I'm having the same error when trying to backup to Dropbox. Loading files from Dropbox worked fine.

What I'm trying to do is load from OneDrive and backup to Dropbox.

**Comment by antelle** [comment]
@acrox999 thanks, probably Dropbox backups work only with files stored in Dropbox, I'll check it.

**Comment by anonjnr** [comment]
Hey Guys, I had the same problem. @r100gs @acrox999 @antelle 

KeeWeb wants to put the backup in a folder. So the path to where the backup will be can't be just `backupfile.{date].bak` but has to be `Backup/backupfile.{date}.bak`.
You can name the folder and file as you please. `{date}` automatically puts the date and time of when the backup has been created in the filename.

Cheers!

**Comment by antelle** [comment]
probably solved now.
