### ISSUE TITLE
The background colors are inaccurate/weird/... on MacOS Sierra

### ISSUE THREAD

**Issue by SonRiab** [keeweb/keeweb#728]
- what were your actions? no actions required
- what was wrong? The background colors are inaccurate/weird/... on MacOS Sierra
- app version? 1.3.1
- your user-agent (from Settings/Help section)? Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) KeeWeb/1.3.1 Chrome/52.0.2743.82 Electron/1.3.3 Safari/537.36
- does it happen on Demo or New database? both
- if you are using a test db without your personal data, please attach it
- please, open dev tools in your browser and attach output log from Console tab 
    (if you are using desktop app, devtools can be opened from Settings/General/Advanced)

This should be fixed in newer Electron versions (see https://github.com/electron/electron/issues/7304) so updating Electron should do the trick.

**Comment by antelle** [comment]
Hi!
Could you please check in v1.5.6? 1.3.3 is quite old.

**Comment by SonRiab** [comment]
Okay, the updater didn't find the new versions, so yeah, quite old. Seems to be fixed, so I close the issues. Thanks anyway!
