### ISSUE TITLE
Syncing from Dropbox PW DB down to the Desktop App?

### ISSUE THREAD

**Issue by brucept2** [keeweb/keeweb#730]
I am having issues with the desktop app syncing down from my Dropbox PW DB. I connect the desktop app successfully and "Allow" it, but it is always saying "Nothing can be found" but the DB is in the default location in the App folder and has not moved. What gives and how do I fix this?

_B

**Comment by antelle** [comment]
You need to save your file to Dropbox to sync it: open file settings and click save to Dropbox.

**Comment by brucept2** [comment]
I did in fact save the file to dropbox to sync. I built a few test entries on the web app, clicked Save to for Dropbox. Then I installed the desktop app, clicked More "..." and then Dropbox. Logged in, then get this message :  https://imgur.com/a/9Eo87 "Nothing found" - "No files which could be opened." When I clicked save on the web version to get the password db to Dropbox, I did not change the filepath and let it use the default. When I did that, it looks like it saved here on my Dropbox account by default: "/Apps/<name of my new db file>/vault" Is there a specific way to save or point it to another location if that location is not indeed correct so I can try to get the desktop version to read the file?

Thanks,

_B

**Comment by brucept2** [comment]
Ok so I saw the app uses Apps/KeeWeb, so I moved the password db there and kept the desktop app default. The Webapp requires a appkey, so I put mine in and put the same filepath when asked in the next field "Apps/Keeweb" is there something I am missing here?

**Comment by brucept2** [comment]
Just double confirmed:

I deleted all data on Dropbox (was test data anyways). Created a new PW DB on the web version, linked up Dropbox, saved PW DB to Dropbox in the default location (by clicking "Save" inside settings, opened up Desktop app, and I still get the message: https://imgur.com/a/9Eo87 "Nothing found" - "No files which could be opened." Why might this be happening and what do I need to do to get it to work?

**Comment by antelle** [comment]
From what I can understand, you're using a custom folder.
Where is the kdbx file in your Dropbox? I mean, is it in `Apps/KeeWeb` or another folder? If it's in another folder, you need to configure the folder before selecting the file.

**Comment by brucept2** [comment]
Okay. I got all of this setup now correctly, but now when I try to connect the desktop app (using all default App folders) I get this error: https://imgur.com/a/AP3Nu

I followed the App setup guide here: https://github.com/keeweb/keeweb/wiki/Dropbox-and-GDrive so I am not quite sure why I am getting an error relating to app.keeweb.info

Why might this be the case?

**Comment by brucept2** [comment]
I have tried re-creating the App via dropbox.com/developers, clearing the users, deleteing the desktop app, clearing the cache, etc. and I am not sure why I am still getting the error: https://imgur.com/a/AP3Nu just FYI...

**Comment by antelle** [comment]
If you're using a dropbox app, you need to configure KeeWeb to use it:
![dropbox](https://user-images.githubusercontent.com/633557/30425613-013d127e-994a-11e7-96ee-0541c85e5467.png)

**Comment by brucept2** [comment]
I am using the Dropbox App, and I have configured the desktop app above just as you have in the screenshot above. I have left the app folder blank because I let the App create the default. I have selected "Own Dropbox app" on both the web version and desktop version with the same app key.

"From what I can understand, you're using a custom folder.
Where is the kdbx file in your Dropbox? I mean, is it in Apps/KeeWeb or another folder? If it's in another folder, you need to configure the folder before selecting the file."

I am not using a custom folder, but am letting Dropbox create the folder by default (I leave the "App folder:" field blank on both the Web version and Desktop version with my app key in the app key field") Do you think by leaving the field "App folder:" blank it is causing issues, though it is putting it in a default location? I can try to set a specified path and let you know my findings, but I assumed leaving it blank would just use default.

Let me know your thoughts and thanks again for all of your help. I know this is open source but if you have some sort of donation page that I can contribute to, I will gladly fund it to get this working.

_B

**Comment by brucept2** [comment]
So just to confirm:

I just tested by changing the "App folder:" to a new folder called "Database" instead of keeping it blank to save to the root, and I am still getting this error when trying to access this on the Desktop app: https://imgur.com/a/AP3Nu

Do you think My Oauth2 Redirect URLs or Chooser/Saver domains are not setup correctly? I have nothing set for Chooser/Saver domains because when I put my root domain, I still get the error. I tried removing and still got the error so I know that it seems to be unaffected by it. For my Oauth2 Redirect URLs, I also just put the subdomain.domain.com in that field just as I did for Chooser/Saver domains and it also seems unaffected with our without these URLs set.

Just wanted to confirm what I have tried.

Let me know what you might think it is.

_B

**Comment by antelle** [comment]
Are settings in your desktop keeweb the same as in web app? If so, what happens if you create a new file on web and save it to Dropbox, is it visible in desktop?

**Comment by brucept2** [comment]
They are a literal clone in terms of settings. I usually create the file on Web, save to Dropbox, then try to access it on the Desktop, in which it has never worked that way. At first I got it to say "no file found" but then it kept giving me the 400 error I sent you above.

**Comment by antelle** [comment]
As a quick workaround, you can install Dropbox and just open the file from filesystem in desktop.

**Comment by brucept2** [comment]
This isnt a bad workaround. Are these errors something or issues something that can be addressed in the next build of desktop app? I noticed some others having 400 errors too :)

**Comment by antelle** [comment]
I don't understand why you get these 400 errors, but I'll try to reproduce it. Maybe custom dropbox apps don't work in desktop?..

**Comment by brucept2** [comment]
Sounds like that is the case. Others seem to be having similar issues but I think that is the overall issue. I am going to use the dropbox sync thing for now as a temp and follow the threads to see if we can get it fixed. If there is anything I can help contribute let me know.

**Comment by antelle** [comment]
Actually, I haven't seen this issue reported earlier. Previous issues were caused by misconfigured Dropbox app and/or bad docs, without a description how to configure redirects, apps, etc...

**Comment by brucept2** [comment]
Oh ok, my bad :) I am not sure what it is then. Yeah I just tried to link them again by creating it on web app first, saving it to dropbox, using the EXACT same settings as web for desktop app and I get this error still:

https://imgur.com/a/AP3Nu

Would the Chooser/Saver or OAuth2 Redirect URLs being wrong or not correct cause the issue? I just have the subdomain.domain.com they are located at currently.

_B

**Comment by brucept2** [comment]
Also in terms of autosyncing, how does that work? If I enter something on either the Web or Desktop (Desktop for now just opening the PW DB from the Dropbox app synced to the computer) does it automatically sync the data after a certain point? SO for example I add a PW to the DB on Desktop, then I want to use web version if I login there and open the Dropbox PWDB that is linked, will I see the change or addition immediately or how does that work exactly?

Thanks!

_B

**Comment by antelle** [comment]
Yes, wrong redirect URLs will cause this error. But I'm not sure why it's asking for `https//app.keeweb.info`, it's something I'd like to check. Maybe if you add `https://app.keeweb.info` as OAuth2 redirect url it will work, but why?..

**Comment by brucept2** [comment]
omg it worked by doing that! Not sure why I have to do that but it worked!

I added https://app.keeweb.info/ as an OAuth2 redirect URL and it is works now.

Now I am just curious how syncing works per my question above. :)

Like if I add a pass on either end (Desktop or Web) how does it sync? Is it automatic if it is checked in settings or does it do it in intervals?

Thanks so much!

**Comment by antelle** [comment]
I see, I'll add this to the docs. I've figured it out, it was changed in new version of Dropbox API (introduced this year): earlier keeweb used url like `https://dropbox.com/oauth/redirect`, but how all Dropbox app oauth redirect urls are required to be real urls, so it's not possible to use Dropbox url anymore.
Auto-sync can be triggered when the db is auto-locked, or you close the app, etc... It checks the latest version in Dropbox, merges the changes (if any) and uploads the changed version back.

**Comment by brucept2** [comment]
Perfect! Yes I dont mind having to add that URL, it was such an easy fix :)

Ok this is amazing thanks for explaining that I appreciate your efforts so much!

_B

**Comment by antelle** [comment]
I've just added a note to the Dropbox doc: completely forgot that this url is now required.

**Comment by brucept2** [comment]
That is ok! I am glad we got it working. Amazing thank you so much!
