### ISSUE TITLE
[Feature request] Pass key file on command line

### ISSUE THREAD

**Issue by GabLeRoux** [keeweb/keeweb#731]
Hi there,  
I really enjoy this application. Best keepass compatible multiplatform client I've used so far 👍 

I found the following documentation for command line switches: 🎉 
https://github.com/keeweb/keeweb/wiki/Configuration#command-line-switches

We can open a `.kdbx` file by passing it as first argument (says "last argument" in the wiki but according [to the code](https://github.com/keeweb/keeweb/blob/52701af6d6aacd5d0171ef1509f9d264c3e6a499/electron/app.js#L10), I think it grabs the first match of `.kdbx` for any argument. 

That'd be nice if we could also pass the key file along, something like this:
_edited based on Antelle's suggestion_ 🍻 
```bash
keeweb path/to/safe.kdbx --keyfile=path/to/secret.key
```

I only took a quick look at the code, but if this sounds like something that could get merged, I'll consider sending a PR :)

**Comment by antelle** [comment]
Hi,
This makes sense! I would make it as `--keyfile=...`.

**Comment by antelle** [comment]
Implemented it, so it will be `--keyfile=...`

**Comment by GabLeRoux** [comment]
Awesome, thanks for this :+1:
