### ISSUE TITLE
WebDAV network error

### ISSUE THREAD

**Issue by dougen** [keeweb/keeweb#732]
When I use the [jianguoyun](https://www.jianguoyun.com) webdav url, keeweb show network error.
KeeWeb v1.5.6 (10229e7, 2017-08-31)
Environment: web
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36

**Comment by antelle** [comment]
Hello! Which network error do you get?

**Comment by totorigolo** [comment]
Same here. The logs aren't very talkative:

```
[INFO ] 2017-09-16T10:11:48.535Z [app] Started in 1571ms ¯\_(ツ)_/¯
[DEBUG] 2017-09-16T10:12:22.690Z [storage-webdav] Stat https://my.vps.fr/webdav
[DEBUG] 2017-09-16T10:12:22.888Z [storage-webdav] Stat error https://my.vps.fr/webdav 199ms
```

But maybe in my case it's because my certificate isn't signed by an authority. Here is `cadaver` output:

```
$ cadaver https://my.vps.fr/webdav                   
WARNING: Untrusted server certificate presented for `my.vps.fr':
Issued to: totorigolo's fun, OVH, Some-State, FR
Issued by: totorigolo's fun, OVH, Some-State, FR
Certificate is valid from Thu, 13 Jul 2017 23:17:20 GMT to Sat, 21 Aug 2021 23:17:20 GMT
Do you wish to accept the certificate? (y/n)
```

---
Tried both in release and beta version:
```
KeeWeb v1.5.4 (34f91ac, 2017-08-31)
Environment: electron v1.6.11
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) KeeWeb/1.5.6 Chrome/56.0.2924.87 Electron/1.6.11 Safari/537.36
```
_PS: Of course, I don't own `vps.fr`._

**Comment by antelle** [comment]
@totorigolo you can see the actual error in Network panel. Browser doesn't expose the error details, that's why we can't print it in logs.

**Comment by antelle** [comment]
Feel free to reopen with more info; probably that's cors or certificate error.

**Comment by leysont** [comment]
Hi @antelle, 
I don't know if this is the right place to seek help but I have been trying to use Keeweb to access Nextcloud and I always get "Error: network error". I'm using the WebDAV address provided by Nextcloud plus the path to the kdbx. 
In Firefox' Console, it indeed mentions CORS: "Reason: CORS request did not succeed". I don't know much about networks and servers so I would be thankful for any help.
![Screenshot_20200714_221010](https://user-images.githubusercontent.com/25365383/87472714-abb15480-c620-11ea-90e6-d91a866c2be7.png)

**Comment by antelle** [comment]
@leysont if you're using nextcloud-keeweb, probably better to ask there. But looks like the server is configured to disallow cors.

**Comment by leysont** [comment]
@antelle I don't use nextcloud-keeweb because I have no possibility to self host and as far as I know you need self-hosted Nextcloud to install apps. Because of nextcloud-keeweb, I can't find anything about this on the web.
Does it mean that Keeweb cannot access Nextcloud instances or does it mean that my Nextcloud provider doesn't allow whatever cors is? I had tried it with at least two other providers and it didn't work either.

**Comment by antelle** [comment]
Your nextcloud provider doesn't allow cors (cross-origin request sharing). This is normal, most of providers disable it as a security measure.
