### ISSUE TITLE
No icon for Safari's Favorites screen

### ISSUE THREAD

**Issue by agurz** [keeweb/keeweb#733]
- what was wrong?
Icon doesn't show up on Safari Favorites screen

<img width="876" alt="screen shot 2017-09-14 at 8 46 23 pm" src="https://user-images.githubusercontent.com/13837769/30460647-7d2a8ba2-998e-11e7-87d2-af4577625b9e.png">

- app version
- your user-agent (from Settings/Help section)
> KeeWeb v1.5.6 (10229e7, 2017-08-31)
> Environment: web
> User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/603.3.8 (KHTML, like Gecko) Version/10.1.2 Safari/603.3.8

> Safari Version 10.1.2 (12603.3.8)

**Comment by agurz** [comment]
As far as I tested this problem disappear when using the image url instead of the base64 representation as the href value of the apple-touch-icon link.

I don't know yet if it's a Safari bug or they explicitly refuse to save the icon when it's encoded in base64. Should we change it anyways if it solves the issue? (I can make a PR)

**Comment by antelle** [comment]
Indeed it will work. I'll try to understand why it doesn't work with base64 first, it should be fine in theory.

**Comment by antelle** [comment]
Deployed to [beta.keeweb.info](https://beta.keeweb.info), will be available in the next release.
<img width="135" alt="fav" src="https://user-images.githubusercontent.com/633557/32692462-b9ea912e-c718-11e7-8812-e1ebf089b0cc.png">
