### ISSUE TITLE
TOTP(TrayOTP format) does not work with secrets containing spaces

### ISSUE THREAD

**Issue by ajayvk-tw** [keeweb/keeweb#734]
When the secret field('TOTP seed') has spaces, the OTP is not generated.
Upon manually removing the spaces, I see OTP getting generated. Based on a quick inspection of code, I think Space removal is not done for TrayOTP format.

KeeWeb v1.5.6 (10229e7, 2017-08-31)
Environment: electron v1.6.11
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) KeeWeb/1.5.6 Chrome/56.0.2924.87 Electron/1.6.11 Safari/537.36

**Comment by antelle** [comment]
Hi! Could you please give an example? Maybe it trayotp doesn't generate spaces always? It looks like mine is writing fields without spaces.

**Comment by ajayvigneshk** [comment]
Sure! TrayOTP doesn't generate spaces, but websites when going the non-barcode way, manually saving the shared secret they show the secret with spaces.
For eg, one such account has 'otp' field as **_otpauth://totp/default?secret=foo1 bar1 foo2 bar2 baz1 baz2 foo3 baz3&period=30&digits=6_**. This does not work on keeweb, as in does'nt show the TOTP.
But if I edit the same to _**otpauth://totp/default?secret=foo1bar1foo2bar2baz1baz2foo3baz3&period=30&digits=6**_ it starts generating the TOTP.

**Comment by antelle** [comment]
Well, this is not allowed by the standard, but as long as it's used by some websites, we can add it. Do you have an example of such website to test?

**Comment by ajayvigneshk** [comment]
<img width="481" alt="screen shot 2017-09-18 at 2 23 22 pm" src="https://user-images.githubusercontent.com/31986090/30534743-287fc13e-9c7d-11e7-993f-a6430c3b3dbe.png">

Google itself shows Secret with spaces.

**Comment by stefnats** [comment]
I think you need to URL-encode the secret in the totp:// url

**Comment by antelle** [comment]
After two years, one line that removes spaces from string is finally there 🤦🏻‍♀️
