### ISSUE TITLE
Make Pronounceable passwords easier to remember (feature request)

### ISSUE THREAD

**Issue by koosvanderkolk** [keeweb/keeweb#737]
The current algorithm comes up with passwords like this:

peDuCoucheYirekobayath
piSedunimemiBormaghU
HouTobojuflaCahabe

Although these words are somewhat pronounceable, they are difficult to remember (at least, for me :-)). 

SafeInCloud Password Manager generates passwords like this:

Perfect13\information\Outer\Cry
Soldier2934]gentleman]Beside]]]
syllables980.Gentleman.outside.

Which are both more pronounceable and also better to remember. +1 it follows https://xkcd.com/936

**Comment by antelle** [comment]
duplicates #210
