### ISSUE TITLE
Running Keeweb on IIS WebDAV - Local Cache Problem

### ISSUE THREAD

**Issue by hutchers** [keeweb/keeweb#738]
Hello,

I haven't come across many instances where people are hosting Keeweb on IIS with WebDAV hence why I'm posting here.

I'm unable to save changes made back to the kdbx file - it will only let me save to the cached instance.

![image](https://user-images.githubusercontent.com/32144303/30664779-bcfcc0b2-9e46-11e7-857e-695e51aa5f17.png)

Thanks

**Comment by antelle** [comment]
Hi,
Yes, sure, that's how it should work. In order to save back, you need to configure webdav and save to it. By default web version will save to cache (and that's why it shows this warning).
