### ISSUE TITLE
[Feature request] Add articicestudio's Nord theme to keeweb

### ISSUE THREAD

**Issue by agurz** [keeweb/keeweb#740]
Hi! Just wondering if it's possible to add a theme using this open source color palette. https://github.com/arcticicestudio/nord

**Comment by antelle** [comment]
Hi!
Sure, it's possible! I've just tried to create a plugin with it, it needs some color tweaks, to me it lacks some contrast now:
https://user-images.githubusercontent.com/633557/30758297-1cd6fc50-9fd2-11e7-8fde-d8c911c3e4c3.png
Here's the plugin file: [nord-theme.zip](https://github.com/keeweb/keeweb/files/1325429/nord-theme.zip), you can try to play with it and tweak it. Or, I'll do it later.

**Comment by agurz** [comment]
Good! I'll try to take a look of it this weekend.

**Comment by agurz** [comment]
Hi! I just tweaked it a little bit. It looks like this right now:

<img width="1270" alt="screen shot 2017-09-27 at 11 36 35 pm" src="https://user-images.githubusercontent.com/13837769/30946907-fbe6ff04-a3dc-11e7-8f69-0961ca4cc9b0.png">

What do you think? IMO it looks nice but we should remove the text-shadow effect for inputs (Don't know yet if that's possible using the plugin css)

Here the files: [nord-theme.zip](https://github.com/keeweb/keeweb/files/1339302/nord-theme.zip)

**Comment by antelle** [comment]
Yes, sure, it's possible, but which text-shadow do you mean? There's no text-shadow anywhere in keeweb.

**Comment by antelle** [comment]
Ah, I see, yes, it's better without box-shadow, removed it.
Added the theme, you can install it from Plugins section.

**Comment by agurz** [comment]
Shall we add KeeWeb to https://github.com/arcticicestudio/nord#port-projects?

**Comment by antelle** [comment]
It looks like all projects in that list are from arcticicestudio, not sure if our theme is suitable for it.
