### ISSUE TITLE
Get all webapp features without internet connection

### ISSUE THREAD

**Issue by wget** [keeweb/keeweb#742]
Hi antelle,

Maybe asking here is [better than Twitter](https://twitter.com/wget42/status/912008012415537153).

I'm currently in the process of packaging keeweb for Arch Linux, only the webapp version, without any electron dependencies, but I want to have all the features without net access.

Here, when I try to execute the demo, webpack cannot inject Demo.kdbx while the file is present. How come?

![screenshot_20170924_193441](https://user-images.githubusercontent.com/2997662/30786797-a1ed9dcc-a17b-11e7-9b71-36b41455f86a.png)
![screenshot_20170924_193546](https://user-images.githubusercontent.com/2997662/30786798-a658a15e-a17b-11e7-9cde-1f577de8278a.png)

Also, I'm trying to understand that injection principle. When I set back net access, Demo.kdbx is found as if it was downloaded from net (and it seems is).

This is what I'm trying to get the files in `./dist` generated: `index.html` and `manifest.appcache`:

	npm install
	node_modules/.bin/grunt --skip-sign 

Actually the build steps you describe in your README.md are not very clear (actually for those coming to that tech):

"Desktop apps are built with grunt desktop", then below "$ grunt dev $ npm run-script electron", what are the differences? I think this should be rephrased.

Also on Arch Linux the configuration files of webapps are located in `/etc/webapps/keeweb/`. I wan tto tell keeweb to search for the configuration in that folder. But since the webapp is a simple html, this doesn't seem easy.

Thanks for your help.

**Comment by antelle** [comment]
Hi,
It looks like, something weird is going on with your webpack config.
Is it the same when you use pre-built version of the html, e.g. from gh-pages branch?
- `grunt desktop` builds the desktop app and exits
- `grunt dev` and `npm run-script electron` are used to develop the desktop app, i.e. run webpack-devserver and load the app from it
> on Arch Linux the configuration files of webapps are located in /etc/webapps/keeweb/

Probably you will need to create an own [Launcher](https://github.com/keeweb/keeweb/blob/master/app/scripts/comp/launcher-electron.js) for your OS, but it could be quite complicated.

**Comment by wget** [comment]
Hi antelle,

Yes, I cloned the branch you specified and run the file from my nginx server in my VM not connected to the internet and the issue is still present.

So there isn't a simple command to build only the html webapp without any electron deps? From the two commands (bullets) you mentionned, both are creating the webapp (html file) I assume? There is no preference to have (choose one or the other command) in the context of the webapp, I assume?

Maybe there is a misunderstanding here. Wrt. the conf file you linked to me, the latter is really tied to electron. But since I just want the webapp, I don't need (want) any electron dependencies. Could you help me to understand? Why does electron seem needed in this context while only the html is wantd and since the html file doesn't have any configuration file (AFAIK).

**Comment by antelle** [comment]
To build the webapp, you can use the default target, i.e. just run `grunt` (or `grunt build-web-app`). You will still need electron dependencies fetched during `npm install`, but they will not be used if you're building only webapp. Here's this task in gruntfile: https://github.com/keeweb/keeweb/blob/master/Gruntfile.js#L646

**Comment by wget** [comment]
Thanks, I'll check that out.

**Comment by wget** [comment]
@antelle On another side, when I run the electron app and I press the Demo button (**without an internet connection**), the Demo.kdbx is loaded but I don't know from where. I cleaned the KeeWeb related temp files in the user profile. A find / -name Demo.kdbx doesn't report anything and in the keeweb.asar file, I don't see any trace of it. Could it be encoded in the app as base64? I don't know if this is possible though.

**Comment by wget** [comment]
Otherwise, I think I'll disable that Demo option. In that case, please give me a hint where I could remove that feature.

**Comment by antelle** [comment]
It's embedded into the HTML file here: https://github.com/keeweb/keeweb/blob/master/app/scripts/models/file-model.js#L7
The same file is used in both web and desktop apps. There are other dependencies embedded in the same way, e.g. WebAssembly hashing module. So, if demo.kdbx is not embedded for you somehow, probably everything else will be broken.

**Comment by wget** [comment]
@antelle  Hum. That's weird then. How can we explain the file is not loaded without internet connection as you said it is present in the html file as base64?

But though. When checking in the final html file and unminify it: https://raw.githubusercontent.com/keeweb/keeweb/gh-pages/index.html
we can see there is no base64 encoded Demo.kdbx file :-/

So when that file is not embedded, you have crafted a fallback method to download it from the internet?

**Comment by antelle** [comment]
I don't know, it means that you're building it wrong. It's loaded fine if you use the html from `gh-pages`, right?
> When checking in the final html file and unminify it

Webpack strips module names, it's not possible to find it in the html file. But if you're curious, you can find the first bytes of it: `A9mimmf7S7UBAAMAAhAAMcHy5r9xQ1C`, it's inside.
You can get these bytes if you run `openssl base64 -in keeweb/app/resources/Demo.kdbx`.
Probably webpack will try to download a missing modules from network, I don't know actually which fallback strategy it's using in this case. Successful build must contain everything inside, probably external modules will not work at all, even if they can be downloaded (because of transpilation,  preprocessing, exports and other stuff).

**Comment by wget** [comment]
No, like I said previously, even the html file from the gh-pages can't load the Demo feature without an internet connection.

Even if I'm building the app like you recommended, the feature is not working without connection.

Indeed, the first bytes (`A9mimmf7S7UBAAMAAhAAMcHy5r9xQ1C`) are present in my file in an `export` function as I can see (at the same exact location as in the html file of your branch gh-pages). So my build process seems indeed good.

**Comment by antelle** [comment]
Sorry, I misunderstood it then. How do you host it and what’s the error in logs? Does it happen on app.keeweb.info as well?

**Comment by wget** [comment]
I host it in a VM disconnected from the internet, just to have a bare linux installation, but it happens on my local system as well (both Arch Linux), so the VM isn't at fault here.
It doesn't happen on app.keeweb.info. Test steps: launch the webapp from the link you mentioned, disconnect from the internet, click on the Demo feature, the file is loaded successfully.

**Comment by antelle** [comment]
I don't quite understand it.
What happens for you if you host the HTML file from gh-pages inside your VM, which error do you get when you click Demo?

**Comment by antelle** [comment]
Just to understand, let's try this:
```
wget https://raw.githubusercontent.com/keeweb/keeweb/gh-pages/index.html
npm i -g http-server
http-server
```
Then open it in browser and try to load demo. Does it work this way?

**Comment by wget** [comment]
When I click demo from the file hosted on my VM without internet connection, I got the error message mentioned above in the JS console in red. Here is a copy again if you want.
![screenshot_20170924_193546](https://user-images.githubusercontent.com/2997662/31101471-1c5df31a-a7ce-11e7-8ddc-74f743c63156.png)

If I run the file from your node http-server, this is working nicely. I assume the issue comes when distributing the file with nginx then (not tested with Apache).

**Comment by antelle** [comment]
Well, you mentioned missing demo.kdbx earlier, so I thought it was another error. The error in this screenshot is not about demo.kdbx, it’s about some other modules.
If it’s working well with http-server, you can try to save the html from browser and compare to the file downloaded from gh-pages, probably it’s not encoded properly by nginx for some reason.

**Comment by wget** [comment]
@antelle This error seems indeed to be due to that Demo function.

I think the error I get is related to the demo function. I made a screencast of the exception triggered and visible in the js log: https://youtu.be/KO3bRBG5h4o

Also, I realized there are substantial differences between an html file run directly in the browser and a version delivered via nginx. Please find them attached to this answer for you to have a look:
[keeweb-webapp.tar.gz](https://github.com/keeweb/keeweb/files/1351892/keeweb-webapp.tar.gz)

**Comment by antelle** [comment]
This is not because of Demo function, it will fail for some other files. So, the file is corrupted. Please tune your nginx to return the file without modifications, it must be the same to work. The easiest way to make sure the file is served correctly is calculating a hash. E.g. on your files:
```
$ md5 index*
MD5 (index.html) = 2ca29b799378600726226b7800e8c242
MD5 (index_nginx.html) = eea167a88ed29e7d02d553344811842c
```
So, none of them is correct. It must be:
```
$ wget -qO- https://raw.githubusercontent.com/keeweb/keeweb/gh-pages/index.html | md5
9ec34aeec587b923706d4b9b44173266
```

**Comment by wget** [comment]
Ok. Actually the file `index.html` is the one I have built from the latest release and is not the one provided from your branch `gh-pages`. So, this might explain why its digest is different indeed. And the one with `_nginx` is indeed the one corrupted by nginx. Now I have to find why and write a doc for Arch Linux users (a doc that might apply to others as well). Keep you posted.
