### ISSUE TITLE
[Feature Request] Export item to .txt

### ISSUE THREAD

**Issue by phoenixweiss** [keeweb/keeweb#743]
It would be very useful to implement the ability to export an element to the txt format.

**Comment by bmehling** [comment]
👍 Aside from the orig keepass (on mono on mac osx), I can't find a version that will allow me to print groups of passwords. The use case is simply printing accounts/passwords and placing them in a safe for family.

**Comment by antelle** [comment]
Now it's already possible to export the whole file as HTML. v1.11 will also allow copying entries to clipboard in HTML and TXT format:

<img width="1072" alt="image" src="https://user-images.githubusercontent.com/633557/64909882-abe77780-d711-11e9-98a4-673453a8320b.png">

What will be copied:

<img width="489" alt="image" src="https://user-images.githubusercontent.com/633557/64909906-d5080800-d711-11e9-9512-f0ac46d63ebc.png">

**Comment by bmehling** [comment]
@antelle Latest updates are really awesome, thanks for your work!

I am trying to see how to export to HTML. Where can I access this features (running latest). Thx!

**Comment by antelle** [comment]
@bmehling it's in file settings, inside "Save to...":
<img width="676" alt="Screen Shot 2019-09-29 at 19 49 04" src="https://user-images.githubusercontent.com/633557/65836725-345d3f00-e2f2-11e9-93d4-e2b6552d4c9f.png">

**Comment by bmehling** [comment]
@antelle Got it! Thank you!
