### ISSUE TITLE
autoSave on close only on desktop app ?

### ISSUE THREAD

**Issue by gtndrd** [keeweb/keeweb#745]
Hi,

- what were your actions?
The whole team (Linux, Mac and Windows) is using KeeWeb with a database shared on a SMB directory (Windows 2008r2).

- what was wrong?
It seems that autosave only triggers when quitting the app (closing the file). Any change (made by a member of the team on his local app) is only seen by the others when closing the database.
As far as I remember, this was triggered each time a modification was made in former release of the desktop app. I mean I thought the file was always opened in read only mode and then accessed in write mode when a change occurred, then back in read only mode. And that was great, no need to install a web site…
Is it still the case ?
I've checked the settings and autosave is set to "true"

- app version
Version 1.5.4 (b730cbd)
Only because it's different from "about KeeWeb"

- your user-agent (from Settings/Help section)
KeeWeb v1.5.6 (10229e7, 2017-08-31)
Environment: electron v1.4.15
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) KeeWeb/1.5.4 Chrome/53.0.2785.143 Electron/1.4.15 Safari/537.36

- does it happen on Demo or New database?
Brand new database (made from scratch with KeeWeb for tests, 2 entries)

- if you are using a test db without your personal data, please attach it

- please, open dev tools in your browser and attach output log from Console tab 
    (if you are using desktop app, devtools can be opened from Settings/General/Advanced)
I can give it to you if you think it's not useless…

Best regards,

Gaetan

**Comment by antelle** [comment]
Hi,
No, auto-save was never triggered on modifications both in desktop and web. Probably it makes sense to add auto-save by timer, e.g. when you modified the database, save it after 5 minutes or so.

**Comment by gtndrd** [comment]
Hi,
Is it a parameter I can tweak somewhere ?

**Comment by antelle** [comment]
no
