### ISSUE TITLE
[RaspberryPI/ARM][lighttpd]

### ISSUE THREAD

**Issue by petschwim** [keeweb/keeweb#746]
Hello,

i want to run Keeweb on an raspberry Pi 3.
Is there any tutorial how to setup Keeweb on an raspberry pi?

**Comment by antelle** [comment]
You will need to host the contents of gh-pages branch: https://github.com/keeweb/keeweb/tree/gh-pages
I don't know how to set up a webserver there, but there are no special requirements to it, any of webservers will work.
