### ISSUE TITLE
[Feature request] what about 2fa authenticator functionality?

### ISSUE THREAD

**Issue by AlexAlabyev** [keeweb/keeweb#747]
There is not many desktop "2-factor authentication code generating" apps (especially cross-platform) 
Wouldn't that be great if keeweb would allow to generate 2fa codes? (like the Google authenticator app on android, but for desktops)

**Comment by avbor** [comment]
It's already can do it :)

![image](https://user-images.githubusercontent.com/32452033/31123405-6e957548-a848-11e7-8638-69d757b1d9e5.png)
![image](https://user-images.githubusercontent.com/32452033/31123424-85b078b8-a848-11e7-9612-4f52d670c6ba.png)

**Comment by AlexAlabyev** [comment]
@avbor oh wow! Thanks for letting me know, I didn't see it, I suppose the issue is close then :)

**Comment by GreatBigWhiteWorld** [comment]
I am looking for 2FA to guard Keeweb database but find this. I however think this feature that provides 2fa stored with password is a very bad idea...No?
My second question is then "do we have a 2FA feature that aims to guard keeweb database, like keepassxc currently has?" Thank you.

**Comment by antelle** [comment]
@GreatBigWhiteWorld it depends on where you store a file with it, storing it with the password is not the smartest idea indeed but again, it depends on type of attack you're trying to prevent.
We don't have the feature to protect kdbx with 2fa at the moment, and it's not completely clear how to implement it, but it's another issue, #517.

**Comment by GreatBigWhiteWorld** [comment]
That clears up my questions. Thanks a lot!
