### ISSUE TITLE
[Feature request] Auto-type button

### ISSUE THREAD

**Issue by mrpouletcurry** [keeweb/keeweb#748]
Why not add a auto-type button on the top menu ? On the rigth, next to sort button.

![keeweb_2017-10-04_10-58-10](https://user-images.githubusercontent.com/31985048/31167693-34a0a8fc-a8f3-11e7-9057-2e7505214622.png)

**Comment by zendre4** [comment]
+1

**Comment by antelle** [comment]
Buttons in that list belong to entries list, not the concrete entry. Auto-type button should not be there.
