### ISSUE TITLE
beta.keeweb.info down

### ISSUE THREAD

**Issue by ffflorian** [keeweb/keeweb#751]
The beta website https://beta.keeweb.info/ is down with a `503`.
![screenshot from 2017-10-09 12-04-53](https://user-images.githubusercontent.com/5497598/31333426-5a643e00-acea-11e7-84fc-d64f041dd8d4.png)

**Comment by antelle** [comment]
it’s openshift, they have closed free plans, will migrate to somewhere else this week

**Comment by antelle** [comment]
fixed
