### ISSUE TITLE
[Feature Request] AWS S3 Bucket Sync Support

### ISSUE THREAD

**Issue by MAHDTech** [keeweb/keeweb#752]
Hi,

I've been enjoying using KeeWeb as a replacement for KeePass and would like to know if there is any thought about adding AWS S3 Bucket Sync support into the app.

Basically a replacement for the KeeCloud plugin for KeePass.

Has anyone considered this as a plugin to KeeWeb maybe if not directly integrated?

Thanks.

**Comment by antelle** [comment]
Hi,
You can implement a plugin for it, here's a guide: https://github.com/keeweb/keeweb/wiki/Plugins
Example storage plugin: https://github.com/keeweb/keeweb/tree/develop/plugins/examples/fail-storage
It will not be implemented in KeeWeb itself, since it's more or less developer feature.
