### ISSUE TITLE
"Generate" functionality for custom fields

### ISSUE THREAD

**Issue by koterpillar** [keeweb/keeweb#753]
Some websites insist on recovery questions like "mother's maiden name". I would like to enter fake password-like information there and store it using KeeWeb instead - this limits the exposure of my personal information and I can change the answers at any moment.

It would be nice if custom fields in KeeWeb had a "Generate" button like the "Password" field.

**Comment by antelle** [comment]
you can just open generator, copy it and put into any field

**Comment by koterpillar** [comment]
Oh, I missed the generator in the bottom right corner. Maybe it would be more convenient if the button is there wherever the field is "locked" (contents hidden)?
