### ISSUE TITLE
Start KeeWeb as a background service without user-interface for plugins

### ISSUE THREAD

**Issue by kutsan** [keeweb/keeweb#755]
Correct me if am wrong, but you need to keep KeeWeb open in order to autofill forms with its KeeWebHTTP plugin and for just this kind of job no need for GUI. It's just waste of resources across running system. It would be so much better if we can start KeeWeb as a daemon mode (maybe with `--daemon` flag?). Unlocked version of password database can be kept open in background in command of the plugin.

**Comment by antelle** [comment]
Start in tray (#480) should be implemented for this. As for resources usage, electron apps consume normally about 100MB, and if we don't show the UI, it will be about the same. If it seems to much, I would advice to use another clients.

**Comment by kutsan** [comment]
I don't think it's the same problem actually. Starting in tray isn't the same as a daemon. I don't use desktop app so often, and don't want to seeing it in my tray. I'm talking about [individual background process](http://www.launchd.info).

**Comment by antelle** [comment]
But it's hidden: it doesn't appear in apps switcher, windows list, etc... Tray icons also can be hidden deep (depending on your OS, but now it's possible almost everywhere), so they should not be a problem.
