### ISSUE TITLE
Keefox not saving my Passwords to Keeweb

### ISSUE THREAD

**Issue by stevie86** [keeweb/keeweb#756]
Hi!
My Keefox is not saving my Firefox Passwords to Keeweb
I don't know what to do.
Thanks!

KeeWeb v1.5.6 (10229e7, 2017-08-31)
Environment: electron v1.6.11
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) KeeWeb/1.5.6 Chrome/56.0.2924.87 Electron/1.6.11 Safari/537.36

**Comment by antelle** [comment]
KeeFox is using KeePassRPC, which is not supported by keeweb.
