### ISSUE TITLE
Auto-Type fails on Debian

### ISSUE THREAD

**Issue by mishugashu** [keeweb/keeweb#757]
It inserts the username just fine, then goes to the password, puts in 1 letter, and then stops & errors out. I've never had this issue on ArchLinux or Ubuntu, so I assume I'm missing some sort of library on Debian (wheezy), but I'm unsure how to find out what it is. It happens on Chrome, Chromium, and Firefox, so I imagine it has something to do with xdotool.

Log of event:
```
[DEBUG] 2017-10-16T15:56:30.169Z [auto-type] Start {USERNAME}{TAB}{PASSWORD}{ENTER}
[DEBUG] 2017-10-16T15:56:30.169Z [auto-type] Parsed [op:USERNAME,op:TAB,op:PASSWORD,op:ENTER]
[DEBUG] 2017-10-16T15:56:30.169Z [auto-type] Resolved [**********************,key:tab,[*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*],key:enter]
[INFO ] 2017-10-16T15:56:30.563Z [launcher] spawn xdotool: 0, 394ms
[ERROR] 2017-10-16T15:56:30.649Z [launcher] spawn xdotool: 1, 85ms

X Error of failed request:  BadValue (integer parameter out of range for operation)
  Major opcode of failed request:  132 (XTEST)
  Minor opcode of failed request:  2 (X_XTestFakeInput)
  Value in failed request:  0x3
  Serial number of failed request:  86
  Current serial number in output stream:  88
[ERROR] 2017-10-16T15:56:30.649Z [auto-type] Run error Exit code 1
```

```
$ apt-cache policy xdotool
xdotool:
  Installed: 1:3.20160805.1-3
  Candidate: 1:3.20160805.1-3
  Version table:
 *** 1:3.20160805.1-3 500
        500 http://ftp.us.debian.org/debian buster/main amd64 Packages
        500 http://deb.debian.org/debian stretch/main amd64 Packages
        100 /var/lib/dpkg/status
```

```
KeeWeb v1.5.6 (10229e7, 2017-08-31)
Environment: electron v1.6.11
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) KeeWeb/1.5.6 Chrome/56.0.2924.87 Electron/1.6.11 Safari/537.36
```

Please let me know if you need any other information on my system.

**Comment by antelle** [comment]
Hi!
Do you have any special characters in your password?

**Comment by mishugashu** [comment]
Some of them do, some of them are just `[a-zA-Z1-9]`. This behaviour happens on every single auto-type on this system.

**Comment by mishugashu** [comment]
I can no longer reproduce this problem. Everything works properly. It somehow seemed to have fixed itself. Maybe during a software update.

**Comment by stas-bool** [comment]
Same issue.
OS Debian GNU/Linux 9.3 (stretch). Try to reinstall libraries and app.
- app version
KeeWeb v1.6.3 (cded8a4, 2017-12-11)
Environment: electron v1.7.9
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) KeeWeb/1.6.1 Chrome/58.0.3029.110 Electron/1.7.9 Safari/537.36

- does it happen on Demo or New database?
Database from KeepAss. Long time worked fine, but few months ago appear this problem.

- log

`[DEBUG] 2018-01-23T04:33:39.692Z [auto-type] Auto type event {"id":"5f5fd1ed-c367-a0e3-b835-c136a29de473:vAxVRDO2n0ONbFK6SdjHJA==","uuid":"vAxVRDO2n0ONbFK6SdjHJA=="}
[DEBUG] 2018-01-23T04:33:39.692Z [auto-type] Hide window
[DEBUG] 2018-01-23T04:33:39.806Z [auto-type] Start {USERNAME}{TAB}{PASSWORD}{ENTER}
[DEBUG] 2018-01-23T04:33:39.808Z [auto-type] Parsed [op:USERNAME,op:TAB,op:PASSWORD,op:ENTER]
[DEBUG] 2018-01-23T04:33:39.809Z [auto-type] Resolved [*****************,key:tab,[*,*,*,*,*,*,*,*,*,*,*,*],key:enter]
[INFO ] 2018-01-23T04:33:40.169Z [launcher] spawn xdotool: 0, 358ms
[ERROR] 2018-01-23T04:33:40.267Z [launcher] spawn xdotool: 1, 97ms

X Error of failed request:  BadValue (integer parameter out of range for operation)
  Major opcode of failed request:  132 (XTEST)
  Minor opcode of failed request:  2 (X_XTestFakeInput)
  Value in failed request:  0x3
  Serial number of failed request:  92
  Current serial number in output stream:  94
[ERROR] 2018-01-23T04:33:40.268Z [auto-type] Run error Exit code 1`
