### ISSUE TITLE
The Dropbox v1 API is retired

### ISSUE THREAD

**Issue by malicz** [keeweb/keeweb#758]
Thank you for this wonderful application. I use the online tool, download the gh-pages.zip and put it on my server.

Recently I could not save changes to my Dropbox and got the error: {"error","v1_retired"}

https://blogs.dropbox.com/developers/2017/09/api-v1-shutdown-details/

Can you take a look at this?

Thank you
Malic

**Comment by antelle** [comment]
Hi! How did you manage to get this error? KeeWeb is using v2 api quite a long ago.

**Comment by malicz** [comment]
Appaerently I have 1.3.3
Can I download the newest version somewhere. https://app.keeweb.info/ works for me

**Comment by antelle** [comment]
Oh, that's an old thing! Sure, recent version can be always downloaded here: https://github.com/keeweb/keeweb/archive/gh-pages.zip
