### ISSUE TITLE
Cannot drag and drop in Linux

### ISSUE THREAD

**Issue by gab-fan** [keeweb/keeweb#759]
Puppy Linux tharpup 64 bit
Using the native app install from a .deb file.
When dragging/dropping I get the following:
![capture11419](https://user-images.githubusercontent.com/32948465/31804347-dca52a0a-b582-11e7-8e1d-8d56a7003a37.png)
To get around this I use keepass and then save it back to a file for keeweb.

**Comment by gab-fan** [comment]
Puppy Linux tharpup 64 bit
Using the native app install from a .deb file.
When dragging/dropping I get the following:
![capture11419](https://user-images.githubusercontent.com/32948465/31804347-dca52a0a-b582-11e7-8e1d-8d56a7003a37.png)
To get around this I use keepass and then save it back to a file for keeweb.

**Comment by antelle** [comment]
Probably it's the same as #198
So, the only way is to use the attachment button.
