### ISSUE TITLE
[UI] Improve multiple attachments display

### ISSUE THREAD

**Issue by dlouzan** [keeweb/keeweb#764]
Hello, first of all thank you for such a great tool.

I have an issue with the display of attachments in entries: when there's a sufficient amount of them, as they are shown in a horizontal widget, it's impossible to distinguish elements, please check the screenshot.

A solution would be to allow an alternative display mode in which files where shown vertically in a list or table, but I could not find such a configuration option. Even better, provide options to sort entries by name, date, etc.

<img width="1239" alt="screen shot 2017-10-27 at 15 12 25" src="https://user-images.githubusercontent.com/223870/32105702-a4fd0c6a-bb29-11e7-8235-ad2333a025c4.png">

Regards

**Comment by antelle** [comment]
Attachments are not designed for this, actually, typically it's 1-2 items attached to a password.
Should be redesigned if there are many attachments, but this is kinda edge case.

**Comment by dlouzan** [comment]
Hello @antelle, thank you for the answer. It comes to me as a surprise your indication that entries are only supposed to have one or two items attached, I never saw that stated in the keepass 2.x documentation (in fact, iirc multiple attachments per entry was a feature added between 1.x and 2.x). The Mono client in Linux in shows entries on a list widget and I've had no issues with multiple attachments on a single entry. It makes the db bigger, but it's not actually any problem.

It's not that we are storing dozens of files with each entry, but sometimes we want to store e.g. several versions of a configuration that should be secret, and keepass is a very convenient place to keep them.

Keep up the work, this is an amazing keepass client :-)

**Comment by antelle** [comment]
v1.11 will display it like this:

<img width="614" alt="Screen Shot 2019-09-11 at 22 25 14" src="https://user-images.githubusercontent.com/633557/64732347-1bc3eb00-d4e3-11e9-929d-d436f017df7f.png">

Still not suitable for insane numbers, but somewhat better.
