### ISSUE TITLE
Autotype not typing @ sign in username

### ISSUE THREAD

**Issue by DasEarl** [keeweb/keeweb#765]
Hello,

When AutoTyping, the @ sign will be send as q but only in the User field. See:
![image](https://user-images.githubusercontent.com/5646150/32143349-66c48c90-bca8-11e7-8aa2-689f01197087.png)

To still use this feature I made a new entry called E-Mail and set a custom keystroke.

I'm using the latest version 1.5.6 and i3wm on Ubuntu 17 if that helps.

**Comment by antelle** [comment]
Seems to be linux-specific.

**Comment by DasEarl** [comment]
Apparently only the first send @ sign will be send as q no matter which entry it is. So sending an @ sign first and deleting it will always work:
@{BACKSPACE}{USERNAME}{TAB}{PASSWORD}{ENTER}
