### ISSUE TITLE
Exception to display Password when hide empty fields is selected

### ISSUE THREAD

**Issue by kumabon** [keeweb/keeweb#768]
I have a follow up question on issue #58 

May I ask why the exception to always display Password?

Personally, I have records (e.g. Membership #) with no password so it would be nice to have the field hidden as well.

I must also add that your implementation of record display is already miles ahead of your peer, especially with the custom fields all displayed together with standard ones without needing to switch tabs.

**Comment by antelle** [comment]
Well, since we have `Add Username`, `Add Notes`, etc..., in the dropdown list, we can also have `Add Password` for those who have entries without a password and allow empty passwords. However, it should be visible when you create an entry, unlike other fields.

**Comment by kumabon** [comment]
Noticed that during entry creation, both username and password fields are always visible. No objection to that. My recommendation was specific to entry viewing anyway. Thanks.

**Comment by antelle** [comment]
Deployed to [beta.keeweb.info](https://beta.keeweb.info), will be available in the next release.
