### ISSUE TITLE
List entry 2nd line value priority

### ISSUE THREAD

**Issue by kumabon** [keeweb/keeweb#770]
In the list part of the UI in the middle, each entry has a 2nd line displayed.

Based on my experiment, the logic of what to display appears to be:
1. Notes, unless null
2. URL, unless null
3. Username, unless null
4. Null

I would make a case of changing the logic to:
1. Username, unless null
2. Notes, unless null
3. URL, unless null
4. Null

Reasons:
- In case of multiple entries for the same website, the best differentiating field would be Username
- In any case, Notes shouldn't have higher display priority than Username
- URL can be displayed if no Username and no Notes, as a supplemental info. Users typically put the name of the Website in the Title field already so this is not the most valuable piece of info

Examples:

Existing:
Google
https://www.google.com
Google
https://www.google.com
Google
This is a note

Proposed:
Google
someone@gmail.com
Google
someoneelse@gmail.com
Google
john@gmail.com

**Comment by antelle** [comment]
Makes sense

**Comment by antelle** [comment]
Deployed to [beta.keeweb.info](https://beta.keeweb.info), will be available in the next release.

**Comment by kumabon** [comment]
Wow thats fast!
