### ISSUE TITLE
Root group name always display as file name

### ISSUE THREAD

**Issue by kumabon** [keeweb/keeweb#771]
At the root group location, the UI would always display the file name instead of the actual root group name.

Moreover, in the settings of the root group, its name cannot be changed. Which I suppose makes sense since it is not really the root group settings.

The file name is already displayed in the lower left corner. So probably no need to duplicate the same info at the root group location.

**Comment by antelle** [comment]
There's no need to rename root group.

**Comment by kumabon** [comment]
In KeePass however, root group can have its own name that is different from file name. Its not a big deal though but just wanted to point this out.
