### ISSUE TITLE
New entries created using template took "Created date" value of template

### ISSUE THREAD

**Issue by kumabon** [keeweb/keeweb#774]
When new entries are created using templates, the "Created date" field would be populated with value of the template entry.

Would it be better to use the current date time instead?

Similarly, entries created as a duplicate of an existing one would have the same issue.

**Comment by antelle** [comment]
This is a bug indeed

**Comment by antelle** [comment]
Deployed to [beta.keeweb.info](https://beta.keeweb.info), will be available in the next release.
