### ISSUE TITLE
json config issue

### ISSUE THREAD

**Issue by krumpaul** [keeweb/keeweb#776]
Please, read https://github.com/keeweb/keeweb/wiki/FAQ before submitting a new issue and fill in the following (if applicable):

- **what were your actions?**
  create json file for testing: {"settings": {"theme": "hc"}}
  point browser to https://URL/?config=config.json
- **what was wrong?**
  unable to use the json file.
- **app version**
KeeWeb v1.5.6 (10229e7, 2017-08-31)
Environment: web

- **your user-agent (from Settings/Help section)**
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36

- **please, open dev tools in your browser and attach output log from Console tab**

 017-11-09T17:06:17.212Z [app] Error starting app DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at n.ensureCanLoadConfig (https://URL/?config=config.json:18:28921)
    at https://URL/?config=config.json:18:27771
    at new Promise (<anonymous>)
    at n.loadConfig (https://URL/?config=config.json:18:27743)
    at https://URL/?config=config.json:27:13141
    at <anonymous>
o.error @ ?config=config.json:14
(anonymous) @ ?config=config.json:27
Promise rejected (async)
(anonymous) @ ?config=config.json:27
j @ ?config=config.json:10
k @ ?config=config.json:10
setTimeout (async)
(anonymous) @ ?config=config.json:10
i @ ?config=config.json:10
fireWith @ ?config=config.json:10
fire @ ?config=config.json:10
i @ ?config=config.json:10
fireWith @ ?config=config.json:10
ready @ ?config=config.json:11
R @ ?config=config.json:11

**Comment by antelle** [comment]
Yep, it's broken in the latest release, please downgrade to v1.5.5 for self-hosted version. There were no changes since 1.5.5.
