### ISSUE TITLE
Favicon download service is down

### ISSUE THREAD

**Issue by timendum** [keeweb/keeweb#777]
The service used for favicon downloading (favicon-antelle.rhcloud.com) is down.

Is there any replacement?

**Comment by antelle** [comment]
No replacement at the moment. I'm thinking where to host it.
Probably it will be Heroku, however there's idling...

**Comment by justinribeiro** [comment]
Could use Google's favicon service: `https://www.google.com/s2/favicons?domain_url=`

**Comment by antelle** [comment]
Unfortunately, no: all [these alternatives](https://github.com/keeweb/favicon-proxy#alternatives) don't provide CORS headers, which makes them impossible to use in webapps. I just discovered that there's no idling if you add a credit card on Heroku. I'll move the app tonight. However, we'll have to update the domain name, which will happen only in the next version.

**Comment by antelle** [comment]
Fixed it, deployed to [beta.keeweb.info](https://beta.keeweb.info), will be available in the next release.

**Comment by EricGrange** [comment]
I tried using the service url from beta version (https://favicon.keeweb.info/) but it seems CORS is not enabled on it?

**Comment by antelle** [comment]
It works ok for me, what happens for you?
![cors](https://user-images.githubusercontent.com/633557/33028209-9433769a-ce15-11e7-9d2e-98a114f2e59b.png)

**Comment by EricGrange** [comment]
Sorry it was a fluke apparently, it's working now.

**Comment by antelle** [comment]
It also supports more websites, e.g. those with png favicon.

**Comment by stefnats** [comment]
Why rely on a webservice that downloads favicons instead of retrieving them in-app? is there anything that can't be done with that?
Downside of a hosted service is that it could be down and the function wouldn't work.

**Comment by antelle** [comment]
@stefnats you cannot download favicons from a webapp.
Desktop apps download icons themselves, they don't use this service.
