### ISSUE TITLE
Enable keepasshttp settings for String Fields (KPH)

### ISSUE THREAD

**Issue by facutopa** [keeweb/keeweb#779]
Hi!

I have a request about the Keepasshttp plugin.
If you see in the page of _passifox_  : [Point 3.7](https://github.com/pfn/passifox/blob/master/documentation/chromeIPass.md#37-fill-in-additional-values-via-string-fields)
In this point it send to the guide of settings: [Point 11](https://github.com/pfn/keepasshttp#settings-in-keepasshttp-options)

You will be able to see that is possible to add more than two fields for autofill.
This is possible when you enable some feature in the settings of the plugin.
Is possible to add this to **keeweb**?

If you answered to this issue, sorry, I didn't find something related.

Data:
KeeWeb v1.5.6 (10229e7, 2017-08-31)
Environment: electron v1.6.11
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_1) AppleWebKit/537.36 (KHTML, like Gecko) KeeWeb/1.5.6 Chrome/56.0.2924.87 Electron/1.6.11 Safari/537.36

Thanks and best regards!

**Comment by antelle** [comment]
Well, KeeWebHttp returns all fields by default, there's no need in the setting. The question is, why plugins don't understand it? Probably the format is incorrect, I'll look into it.
