### ISSUE TITLE
Template stays in dropdown when Templates folder is deleted

### ISSUE THREAD

**Issue by jochec** [keeweb/keeweb#780]
If you create empty template and then deletes the "Templates" folder, empty template will stay in dropdown menu and there is no way how to delete it.

**How to reproduce:**
- Click  "+" icon for adding new record and select "Template"
- Don't fill anything into template ("Templates" folder appears on the left side)
- Delete the "Templates" folder
- Click +" icon for adding new record again - there is empty dropdown option with no way to delete it

![empty_dropdown](https://user-images.githubusercontent.com/7040084/32978020-ba03c10a-cc39-11e7-81d2-f465aaf34fba.png)

It is possible to restore Templates folder from trash and then delete the template inside it, but I suggest to remove all templates from dropdown menu when their containing folder is deleted.

App information:
KeeWeb v1.5.6 (10229e7, 2017-08-31)
Environment: electron v1.6.11
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_1) AppleWebKit/537.36 (KHTML, like Gecko) KeeWeb/1.5.6 Chrome/56.0.2924.87 Electron/1.6.11 Safari/537.36

**Comment by antelle** [comment]
Thanks for the detailed report!

**Comment by antelle** [comment]
Deployed to [beta.keeweb.info](https://beta.keeweb.info), will be available in the next release.
