### ISSUE TITLE
WebExtension mentioned for Firefox

### ISSUE THREAD

**Issue by Trollwut** [keeweb/keeweb#781]
It is recommended to use `PassIFox` with Firefox for KeeWeb. Now as this isn't a WebExtension, it's not useable for now. Maybe recommend another addon?

**Comment by antelle** [comment]
Hi!
Found two extensions:
https://addons.mozilla.org/en-US/firefox/addon/keepasshttp-connector/
https://addons.mozilla.org/en-US/firefox/addon/keepasshelper/
Not sure if they're compatible though, I haven't checked them. Please let me know if they're working.

**Comment by tmthrgd** [comment]
@antelle I can confirm that KeePassHttp-Connector works fine with Firefox 57 (and I'm using it now).

**Comment by antelle** [comment]
Cool!

**Comment by vjooris** [comment]
sorry for my stupid questions , but I installed this add-on, and I do have this error :  

KeePassHttp-Connector has encountered an error:
Unable to connect to KeePassHttp 

I've just opened my Keepass file with keepass web for desktop on MAC

**Comment by antelle** [comment]
@vjooris you should install keewebhttp plugin in Settings > Plugins.

**Comment by vjooris** [comment]
It's magical ! THANK YOU

**Comment by dbogdanov** [comment]
On its github page it is said that KeePassHttp-Connector is depricated and is no longer maintained. What should be used instead?

**Comment by antelle** [comment]
@dbogdanov Hm, it doesn't look deprecated for me. Where did you find the warning?

**Comment by dbogdanov** [comment]
@antelle See here: https://github.com/smorks/keepasshttp-connector#deprecation-notice

**Comment by dbogdanov** [comment]
@antelle It seems KeePassHelper can connect to KeeWeb as there was a a popup in KeeWeb to confirm an external application. However, I get "No match!" in the addon. In KeePassHelper window, is the upper field with URL supposed to be a text string filter for all entries to a KeePass database? Manually inputting any other text string their I can't get any matches as well.

**Comment by antelle** [comment]
I'm not sure if that add-on works now, probably it doesn't send the website name or something like this. In Safari and Firefox it's working.
Maybe there's any other add-on?

**Comment by dbogdanov** [comment]
I am using the Firefox addon. Is it possible to manually search through entries in the database in the addon?

**Comment by antelle** [comment]
I don't know, it depends on the add-on. It's possible to enumerate entries through the API, but I'm not sure what it looks like in plugins.
