### ISSUE TITLE
Security on config.json

### ISSUE THREAD

**Issue by jb911** [keeweb/keeweb#782]
Hello,

I configured a username and password in config.json file.
When I access to the URL of my selfhosted Keeweb, I can download the config file and the password is cleartext.

How to add security in this file ?

Thanks,

**Comment by antelle** [comment]
Hi,
You should put your config and keeweb behind auth on your server / network. If it's not possible and config must be public, there's no way to protect credentials inside it. There's a feature request about asking for password from config, but it's not implemented yet: #669

**Comment by Peronia** [comment]
I've experimented a lot.
I put the .kdbx and config.json into a .htaccess protected folder. Now the basic auth spam me always when I load the app.
In some cases the basic auth plop up when I entered the right password. I'ts a loop.

What went wrong?
The webdav header were set from my hoster.
