### ISSUE TITLE
Losing focus on selected Group after Keeweb lock

### ISSUE THREAD

**Issue by auprobst** [keeweb/keeweb#783]
Hi all and thank you working on this wonderfull project.

I'm using Keeweb for MacOS since v1.5.4 and recently updated to v1.5.6.

I have organised my Keeweb entries in groups and I often need to get several logins from entries of a same group in a short time (e.g. 1 or 2 hours).
My problem is that everytime the Keeweb app locks down, when I unlock it, the selected group is always "All items". I would prefer to get the last Group selected after unlock of Keeweb.

Would that be possible ?

**Comment by antelle** [comment]
Hi! This duplicates #175 (it's about search, but search also includes group and so on)
