### ISSUE TITLE
Add AppImage

### ISSUE THREAD

**Issue by waotzi** [keeweb/keeweb#784]
Right now you only provide .deb files which is only useful for people that use debian-like systems. I would be thankful if you also provided an AppImage (https://appimage.org/), it allows the app to run on any linux distribution. thank you for your hard work!

**Comment by Thatoo** [comment]
That would be really needed in order to keep KeeWeb always in a thumbdrive and have portable app.

**Comment by AlexandreMarkus** [comment]
@antelle any news about this feature?
Thank you for your work!

**Comment by Thatoo** [comment]
Thank you!
