### ISSUE TITLE
No syncronisation with webdav possible

### ISSUE THREAD

**Issue by Phreeak** [keeweb/keeweb#786]
Hi, i have a problem with webdav and saving the database on it.

- what were your actions?
I try to tave the db on my Nextcloud/WebDAV Storage
- what was wrong?
Syncronisation is not possible
Error
 *
[DEBUG] 2017-12-03T20:17:59.186Z [storage-webdav] Stat https://mydomain/nextcloud/remote.php/webdav/
[DEBUG] 2017-12-03T20:17:59.196Z [storage-webdav] Stat error https://mydomain/nextcloud/remote.php/webdav/ 503 10ms
[INFO ] 2017-12-03T20:17:59.196Z [sync:Tresor] Stat error, not dirty HTTP status 503
[INFO ] 2017-12-03T20:17:59.196Z [sync:Tresor] Sync finished HTTP status 503
[INFO ] 2017-12-03T20:17:59.391Z [sync:Tresor] Sync started webdav https://mydomain/nextcloud/remote.php/webdav/ {"startedByUser":true}
[INFO ] 2017-12-03T20:17:59.391Z [sync:Tresor] Stat file
*
- app version
1.6.1
- your user-agent (from Settings/Help section)
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) KeeWeb/1.6.1
- does it happen on Demo or New database?
on both
- if you are using a test db without your personal data, please attach it
- please, open dev tools in your browser and attach output log from Console tab 
    (if you are using desktop app, devtools can be opened from Settings/General/Advanced)

**Comment by antelle** [comment]
Hi,
it looks like your webserver returns 503 and sync doesn't work because of it.

**Comment by antelle** [comment]
btw, url should include file name:
https://mydomain/nextcloud/remote.php/webdav/
