### ISSUE TITLE
Make resources/app/icon.png available outside of the asar archive

### ISSUE THREAD

**Issue by daenney** [keeweb/keeweb#788]
Since the release of 1.6.x the `icon.png` resource is only available inside the ASAR archive. However, in some situations we need access to `icon.png`, like during the execution of the [PKGBUILD for keeweb-desktop](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=keeweb-desktop#n29).

Though it's possible to extract this that would require Node.JS to be installed on the target system as well as the asar package, just for that purpose.

Would it be possible to instead also include a copy of the `icon.png` resource in the release tarbal/zip but not as part of the asar archive?>

**Comment by fthiery** [comment]
In the meantime i included the icon directly in the PKGBUILD.

**Comment by antelle** [comment]
Hi!
Added the icon, it will be in the archive next to `KeeWeb` executable. But please note, it's another icon.
The one you mention is a low-quality tray icon, it should not be used as app icon, so it's purely app resource.

**Comment by fthiery** [comment]
I changed the icon

**Comment by daenney** [comment]
Thank you very much!

**Comment by antelle** [comment]
Now zips contain the icon.

**Comment by fthiery** [comment]
The Arch user package is now using it, thanks.
