### ISSUE TITLE
Web version: Specifying a file path to open through url query parameters

### ISSUE THREAD

**Issue by pmiossec** [keeweb/keeweb#789]
I just discover this very good soft and plan to use it but I'd like a feature and didn't found documentation about it.

In the web version of the application (like the one that we could use with `gh-pages`), is it possible to specify a path toward a file throught a query param?

For exemple:

index.html?file=file://C:/path/toward/a/file.kdbx

That way, a file could be easily open through a link (that can be shared or added to a web page).

**Comment by antelle** [comment]
Hi!
Do you mean self-hosted version? You can add a file in config: https://github.com/keeweb/keeweb/wiki/Configuration#json-app-config
So, put a config somewhere, add your file there and add `?config=...` parameter.

**Comment by pmiossec** [comment]
Thanks for the info.
I forgot to thanked you, so... Thank you!

**Comment by bunchofsage** [comment]
**Workaround for those who cannot use the json config to specify a file:**
if you just want to have the filepath handy e.g. file://C:/path/toward/a/file.kdbx or https://path/to/webdav/file.kdbx
- bookmark your keeweb link _with_ ?https://path/to/webdav/file.kdbx as URL parameter
- once called the parameter will be still visible and you can copy and paste the path from the URL into keeweb where needed

...it's still not convenient but at least you have the path handy when you need it
