### ISSUE TITLE
Exclude Backup folder from "All items" search.

### ISSUE THREAD

**Issue by Nebucatnetzer** [keeweb/keeweb#790]
In the Keepass2 application the search ignores the "Backup" directory.
It would be nice if Keeweb would include an option for this.

In addition thanks a ton for this great application, works really well 👍

**Comment by antelle** [comment]
Hi!
You can exclude any folder from search:
<img width="772" alt="settings" src="https://user-images.githubusercontent.com/633557/33622252-9fa6ea3c-d9ed-11e7-8005-e1b30233b835.png">
