### ISSUE TITLE
[Feature Request] Bring version signature to front screen, check for updates

### ISSUE THREAD

**Issue by zdfowler** [keeweb/keeweb#794]
To help users verify that the copy of Keeweb is in fact the latest and greatest, official, and fully up-to-date version, I'd like to suggest copying the commit hash and version number to the front of the app's main screen.  This can be seen by users immediately to ensure they are on the latest version.  Additionally, a HTTP request could be performed to check if  "this" version matches the latest stable version, similarly to the desktop "check for updates" feature.

Thanks for considering!

![keeweb-verified-hash-feature](https://user-images.githubusercontent.com/3877397/33683541-e1aab686-da90-11e7-8594-a46fe7e5dd92.png)

Mockup attached.

**Comment by antelle** [comment]
Keeweb is not an app for geeks, it shouldn't display technical info like this.

**Comment by rEnr3n** [comment]
I thought you're already a geek if you use a password manager.
