### ISSUE TITLE
[Bug] Input validation incorrect on "Ask to change key after (days) field"

### ISSUE THREAD

**Issue by zdfowler** [keeweb/keeweb#795]
- In checking for valid input checking in a class project, we found that the ability to enter nonsensical values exists in one field due to invalid Regex pattern.

During initial tests this resulted in a corrupt database file, but these results were confirmed in a second round of testing.

- Input on DB file -> Settings -> Advanced Settings -> "Ask to change key after (days):" field
- Able to enter non numeric values.
- Able to save with non-numeric and/or very large values.

KeeWeb v1.6.1 (09b1c60, 2017-12-03)
Environment: web
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36

- Occurs on any new / test database, or old database.
Open attached with password 'test' (no quotes).

References to CWE-450 - Multiple Interpretations Of UI Input, CWE-357 Insufficient Warning Of UI Operations

![image](https://user-images.githubusercontent.com/3877397/33684098-b39ed05e-da92-11e7-872e-b0d901aa78b6.png)

[New1.zip](https://github.com/keeweb/keeweb/files/1536798/New1.zip)

**Comment by antelle** [comment]
Actually this applies not only to this input but everything else on this page.
Fixed, will be available in the next version.
