### ISSUE TITLE
Scheduled export database

### ISSUE THREAD

**Issue by hari-bo** [keeweb/keeweb#796]
I would like an feature which you can schedule to export the Keeweb database on an location. Because if you use this within an Docker and it crashes you won't have an backup from the database on an external location.

**Comment by antelle** [comment]
Hi!
What do you mean as scheduled? I don't quite understand it.

**Comment by hari-bo** [comment]
I'm looking for an feature to export the keepass database within the Keeweb docker to an file share. I only see dropbox solution, but I want my data locally and not within the cloud.

**Comment by antelle** [comment]
You need to build webdav container for it. So, build webdav image, put keeweb there and save to webdav next to it - that should be it.
