### ISSUE TITLE
[Feature request] Add option to clear clipboard after a certain duration after copying a field

### ISSUE THREAD

**Issue by nakhan98** [keeweb/keeweb#797]
Add an option to clear the clipboard after copying a field (particularly, password) from an entry. Keepass/x/xc all have this option and it is quite critical imho.. I'm using the keeweb webapp here.

Thanks

**Comment by antelle** [comment]
Hi! It's there for desktop apps: 
![clipboard](https://user-images.githubusercontent.com/633557/33729475-1333c36c-db7e-11e7-936d-1ad4e296777f.png)

Not possible in web version, unfortunately. You cannot clear the clipboard without any user action.

**Comment by SchotenAndi** [comment]
Hi Antelle!
I searched for exactly this feature (for security reasons) and I think you could solve the problem easily. The missing user action should be the log out button. No later than with logout the clipboard should be cleared.
Bye Andreas
