### ISSUE TITLE
Allow customization of font when viewing password

### ISSUE THREAD

**Issue by markasoftware** [keeweb/keeweb#803]
The default font when I reveal the password has exactly the same glyph for l (lowercase L) and 1 (number one). This makes it difficult for me to copy the password to a different device by hand. It would be nice to be able to set the font to one that has more distinct glyphs.

**Comment by antelle** [comment]
Font selection is not something we should do, but there will be an option to reveal the password, probably it will solve this issue as well.
Btw, which OS are you on? They have different glyphs in Mac and Windows.

**Comment by markasoftware** [comment]
Arch Linux.
