### ISSUE TITLE
Unclear UX Lock/Unlock in field. No ToolTip, would be nice if added.

### ISSUE THREAD

**Issue by xgpt** [keeweb/keeweb#805]
This is my first github issue, so please bear with me.

- what were your actions?
     * Downloaded KeeWeb and tried adding an entry template. 
     * Added a "New Field", and changed it to "Registered Email Address" (so I can remember which email I used to sign up for each service.)
     * In the information field to the right, there's a little lock icon that's kind of greyed out, it changes the text from a nice looking one, to a coding looking monospaced one. 
- what was wrong?
     * I can see now (after starting this issue report) that it is a masking/unmasking button.
     * THIS IS NOT CLEAR TO END USERS.
- app version
     * v.1.6.3 Windows

**_Suggestion: CHANGE THE LOCK/UNLOCK ICON TO A EYE WITH A LINE THROUGH IT. 

Pictures attached show first the UX of this program, as well as some examples from the web, the green one shows the default icon used with Windows, which I would suggest as a localization for this platform, or perhaps another one that's more universal such as the full eye. 

But DEFINITELY a tooltip if nothing else.

![screenshot 284](https://user-images.githubusercontent.com/1377974/33920089-14669c18-df8a-11e7-85d7-727c34d200c0.png)
![show_password_ie](https://user-images.githubusercontent.com/1377974/33920012-b3e99886-df89-11e7-92e1-f2c9ff3a517b.png)
![download](https://user-images.githubusercontent.com/1377974/33920013-b3f44466-df89-11e7-8c96-498d05a09ea2.png)
![1_p25-djn37rfl_2tjfwnhpq](https://user-images.githubusercontent.com/1377974/33920014-b4017e56-df89-11e7-812c-f0edfd7ecbd7.png)
![hideshowpasswordswp-180x180](https://user-images.githubusercontent.com/1377974/33920015-b4120b54-df89-11e7-830c-ea83ecc22cc0.jpg)

_**

**Comment by antelle** [comment]
Hi,
This makes sense. It _is_ a security feature, as it's implied (fields are encrypted in memory), but probably it doesn't make sense for users and it's better to change the icon or add a tooltip.

**Comment by xgpt** [comment]
I have been playing with the software some more @antelle and really have been enjoying what I've seen. Very polished, very clean implementation. 

I think just a tool tip would be most appropriate for this instead of an icon/UX paradigm shift. I didn't understand that it was a "secure field" until I re-checked the home page and then played with the search function settings. 

Just a few more words cluttering up your very clean implementation to make it clear. It's not even evident that "secure fields" are secure. It sounds like a well thought out feature that I'd be more likely to use if I knew "secure" meant that it:

-wouldn't show up in searches (Super confusing, putting "secure field" next to the option will maybe alleviate headaches when people can't find the things they are searching for without "secure field" checked in the search box) 
- was somehow more secure/encrypted? In memory? I don't understand what that means necessarily, is it more secure than the regular passwords/usernames/urls in the database? I'm just a user, not a coder. 

Sorry if I'm being nitpicky, I just like pointing out to coders my first impressions of software and things that make me go "huh?" so that it doesn't happen to other people. 

Best to design to the lowest common denominator (lol) and just add a tooltip maybe? 

Thanks!

**Comment by antelle** [comment]
Yeah, tooltip is probably better here. I'll think how to explain it better and will add it.

**Comment by dploeger** [comment]
I would consider a two-faced tooltip. For unlocked fields, the tooltip would read something like this:

```Lock this field, so its content isn't searchable and visible. Displaying the content requires explicitly clicking it.```

And for locked fields:

```Unlock this field, making its content searchable and visible immediately```

This would also add a ring of a security notice to this feature (because unlocking *can* be hazardous)

**Comment by antelle** [comment]
@dploeger makes sense

**Comment by dploeger** [comment]
Created a PR with these two strings. If you come up with a better message, just replace it. 😁
