### ISSUE TITLE
rangeerror: Failed to normalize: invalid or missing unicode character at index 0

### ISSUE THREAD

**Issue by remisharrock** [keeweb/keeweb#808]
- what were your actions?
open my keepass file using dropbox on Edge on Windows 10 using the keeweb.info website
- what was wrong?
had the error 
RangeError: Failed to normalize: invalid or missing unicode character at index 0.
- app version
1.6.3  from the keeweb.info website
- your user-agent (from Settings/Help section)
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36 Edge/16.16299
- does it happen on Demo or New database?
no
- if you are using a test db without your personal data, please attach it
- please, open dev tools in your browser and attach output log from Console tab 

`
 2017-12-14T18:08:39.915Z [open:kp] File open request
app.keeweb.info (1,789992)

 2017-12-14T18:08:39.920Z [open:kp] Open file from supplied content
app.keeweb.info (1,789992)

2017-12-14T18:08:40.392Z [file] Error opening file undefined Failed to normalize: invalid or missing unicode character at index 0. RangeError: Failed to normalize: invalid or missing unicode character at index 0.

app.keeweb.info (1,790313)

[object Error]: {description: "Failed to normalize: invalid or missing unicode character at index 0.", message: "Failed to normalize: invalid or missing unicode character at index 0.", number: -2146822686, stack: "RangeError: Failed to normalize: invalid or missing unicode character at index 0. at Anonymous function (https://app.keeweb.info/:1:828847) at Array.prototype.sort (native code) at sort (https://app.keeweb.info/:1:276834) at set (https://app.keeweb.info/:1:275434) at add (https://app.keeweb.info/:1:273994) at Anonymous function (https://app.keeweb.info/:1:824062) at Array.prototype.forEach (native code) at setGroup (https://app.keeweb.info/:1:823825) at d.fromGroup (https://app.keeweb.info/:1:828319) at Anonymous function (https://app.keeweb.info/:1:823925)"}

2017-12-14T18:08:40.398Z [open-view] Error opening file RangeError: Failed to normalize: invalid or missing unicode character at index 0.

app.keeweb.info (1,790313)

[object Error]: {description: "Failed to normalize: invalid or missing unicode character at index 0.", message: "Failed to normalize: invalid or missing unicode character at index 0.", number: -2146822686, stack: "RangeError: Failed to normalize: invalid or missing unicode character at index 0. at Anonymous function (https://app.keeweb.info/:1:828847) at Array.prototype.sort (native code) at sort (https://app.keeweb.info/:1:276834) at set (https://app.keeweb.info/:1:275434) at add (https://app.keeweb.info/:1:273994) at Anonymous function (https://app.keeweb.info/:1:824062) at Array.prototype.forEach (native code) at setGroup (https://app.keeweb.info/:1:823825) at d.fromGroup (https://app.keeweb.info/:1:828319) at Anonymous function (https://app.keeweb.info/:1:823925)"}
`

    (if you are using desktop app, devtools can be opened from Settings/General/Advanced)
![image](https://user-images.githubusercontent.com/8048877/34007459-1b690342-e102-11e7-8ad2-7496e01d6f04.png)

**Comment by antelle** [comment]
Hi! Could you please check if it works now? It doesn't happen for me.

**Comment by dploeger** [comment]
@antelle I think, this is fixed than, right?

**Comment by antelle** [comment]
yep
