### ISSUE TITLE
[Feature request] Custom copy to clipboard

### ISSUE THREAD

**Issue by shackra** [keeweb/keeweb#809]
As this software can hold OTP field, I was thinking on a custom field that can specify other fields, like auto-type, but that instead of writing something somewhere it copies the content of the specified field to the clipboard when its name is pressed.

The use case for this is that on my job I have to input my Active Directory password with a OTP to connect to a VPN, on Gnome 3.26.x the password prompt is not friendly with auto-type thus I have to paste the password on the prompt and see the OTP behind the password prompt to input it.

Hope this makes sense.

**Comment by antelle** [comment]
Such fields are not supported in KeePass and other ports, so we won't be able to do it.
Also, having a field that references another field that is computable seems to be very complicated stuff both to implement and understand.
