### ISSUE TITLE
SelfHosting on google drive

### ISSUE THREAD

**Issue by FR-TheS** [keeweb/keeweb#813]
Hi everyone,

I'm trying to configure keeweb on my gdrive but i'm fucking like a noob and blocked ...
I have upload on my gdrive the folder and configure the index.html to point on config.json file which is valid(verified on the json validator).
My id client is set but i'm not sure what to put in my web apps on google api about the two URL and how access to the website after ?
FYI, i have validate my domain on the project.

**Comment by antelle** [comment]
Hi,
You should add a config file and set Google Drive ID there: https://github.com/keeweb/keeweb/wiki/Configuration#json-app-config

**Comment by FR-TheS** [comment]
erf it's done and said in my text :x

**Comment by FR-TheS** [comment]
It's not closed, what I said it's my json cfg file is ok, I'm just don't know what url put in my google web apps panel.

**Comment by antelle** [comment]
Your KeeWeb url, i.e. where you hosted it.
You can find more info about Google Drive here: https://github.com/keeweb/keeweb/wiki/Dropbox-and-GDrive

**Comment by FR-TheS** [comment]
Oh okay, I think i was fucking missunderstood the utility of that xD.
I was thinking it was for hosting the application directly on google drive but it's not. krkrkr my bad !
