### ISSUE TITLE
[Feature Request] The search should first check Title, then the rest

### ISSUE THREAD

**Issue by paul-alkhimov** [keeweb/keeweb#814]
I think that the order of results should first consider title, then website, then user, then the rest. Maybe also groups should be considered before everything.

In case I search for say "mail.ru", almost all records are found (because this domain is mentioned almost everywhere in my case either in user name or in notes) making the search futile.

I know I can do it myself in advanced search, but that's exactly the point: the app should do it for user, not user himself.

I believe this feature is very important, because my usual usage of the programs is as follows: open keeweb, enter password, search. And then as the search is not helping much I must either click-read-click-read-click in advanced search, or I must basically imagine all my data, think what part of the searched record is different from other records and search for it. Also sometimes it involves looking through the list and picking the group which narrows the list down. In any case, it is way too much and what is more important: ***it can be automated***.

I also believe I am not alone with this use case. In fact, I cannot imagine how could one use the keeweb in any other way. So IMHO it is the main functionality, the main purpose of the program (apart from security) - to search in a smart way.

v1.6.3 (2017-12-11)

**Comment by Xavier-Plasma** [comment]
I also think that this feature would be very useful.
(by the way, thak you very much for this amazing work, antelle)

**Comment by antelle** [comment]
Yes makes sense, I also noticed this when searching for "gmail".
Probably we need a new sorter for this, i.e. smart sort which will order to the best match when there's something in the search field. The most difficult thing here is switching to it, I'll think how to to it better.

**Comment by dploeger** [comment]
Hm. Isn't this already integrated in the rank calculation of AutoTypeFilter? Matching titles are given an additional rank:

https://github.com/keeweb/keeweb/blob/72c912d57f1363b4df912213384390721ff9910e/app/scripts/auto-type/auto-type-filter.js#L39-L97

Maybe this rank is a little too low, because matching domains could supersede it, but the overall functionality seems to exist. Or am I missing something here?

**Comment by antelle** [comment]
@dploeger that's another thing: it checks if the app title (e.g. website title, displayed as the window title) matched entry title. In this case it works.
What is discussed here is the behavior or the search field, not the autocomplete. So, for example, if you open a demo db and search "smith", it will display all entries sorted A → Z. I'm not sure how to fix this without introducing a new sorter, something like "automatic", which will switch to best match algorithm when a user searches something. Then a user will be able to select this sorter and it will do its job.
<img width="250" alt="screen shot 2019-01-02 at 21 54 18" src="https://user-images.githubusercontent.com/633557/50612063-fa811880-0ed8-11e9-81e8-fa969c60605b.png">
