### ISSUE TITLE
Feature Request: Separate the database save and close functions to a seperate tab from the password settings 

### ISSUE THREAD

**Issue by BAS1350** [keeweb/keeweb#815]
![image](https://user-images.githubusercontent.com/34751369/34270490-f7fe0eec-e64d-11e7-8e06-371f51936121.png)

This request is related to this closed issue:
https://github.com/keeweb/keeweb/issues/656

Because master password field is on the same page as the save button, when saving changes and closing the file, the browser may autofill the master password section and save the new entry when a user updates and closes the DB.

This is particularly troublesome when you are using a key file only, as it could potentially add a password to the database that should not exist if a user is not careful.

Apologies if there is an easy workaround for this that I am unaware of.

**Comment by antelle** [comment]
Hi,
Which browser autofill these fields?
They shouldn't. Or, if they do, it makes sense to disable this.

**Comment by BAS1350** [comment]
I recreated the issue in Firefox 57.0.1 on Ubuntu, but I haven't done much testing on other browsers yet.

**Comment by antelle** [comment]
BTW, on your screenshot it doesn't seem to be auto-completed. Is it?

**Comment by antelle** [comment]
I just checked it, although Firefox (same version, but on mac) allows auto-complete options for the password field on the main page (the large one), it doesn't offer anything for file settings.
Are you sure it was autocomplete, and not the default value which is your password replaced with bullets?

**Comment by antelle** [comment]
Yeah I managed to repeat it. The crucial thing is empty password, it happens only in this case.

**Comment by BAS1350** [comment]
I'll try to recreate the issue to confirm, but I specifically made this database without a master password and a keyfile as part of the troubleshooting, and then when I closed it I could no longer access the database with just a key file.  The database did accept a password that was used for another database so I assumed it was autocomplete; perhaps my understanding of the issue is wrong.

**Comment by BAS1350** [comment]
Ok, thats what i was experiencing as well.

**Comment by antelle** [comment]
Yes. Already fixed it, deployed to [beta.keeweb.info](https://beta.keeweb.info).

**Comment by BAS1350** [comment]
Thank you for the prompt response!

**Comment by antelle** [comment]
Let's keep it open, since it's not live yet. I'll include it in the hotfix, if there's any, or it will appear in v1.7.
