### ISSUE TITLE
Style-creator missing semicolons at the end of each line

### ISSUE THREAD

**Issue by xieve** [keeweb/keeweb#818]
As mentioned in issue #817:

> Here's the content of plugin.css:
>```
>.th-material {
>  --background-color: #263238
>  --medium-color: #abb2bf
>  --text-color: #d7dae0
>  --action-color: #00bcd4
>  --error-color: #c34034
>}
>```

The css file created by the theme creator misses semicolons at the end of each line. I just thought that this is an entirely other bug.

**Comment by antelle** [comment]
Thanks! Fixed it.
