### ISSUE TITLE
Remember opened database files and start with (locked) files?

### ISSUE THREAD

**Issue by pwFoo** [keeweb/keeweb#822]
Hi @antelle,

I use keeweb (browser + desktop) and it works fine with multiple database files so far, but after I closed the application I have to re-open (open first, add additional files after unlocked first one) all files again.

Is it possible to re-add all last opend files again?

I used different files because keepass / keeweb don't support user permissions. So I used different database files for differend user(-groups).

**Comment by antelle** [comment]
Hi, that's basically it: #321.
