### ISSUE TITLE
Issue about WebDAV function

### ISSUE THREAD

**Issue by s5unty** [keeweb/keeweb#824]
Hi!

I have an issue about WebDAV function. After we typed URL/User/Password , we got an error shows "network error" .
We use development mode and found the error as follows:
![image](https://user-images.githubusercontent.com/50655/34403425-1f9599d0-ebe3-11e7-86cb-7c2532769766.png)

@Document was loaded from Application Cache with manifest @https://app.keeweb.info/manifest.appcache
@(index):1 Application Cache Checking event
@(index):1 2017-12-28T06:34:19.456Z [app] Started in 485ms ¯\_(ツ)_/¯
@(index):1 Application Cache NoUpdate event
@(index):1 2017-12-28T06:34:32.835Z [storage-webdav] Stat https://xxxxxxxx/linux.kdbx
@(index):1 Failed to load https://xxxxxxxx/linux.kdbx: Request header field Cache-Control is not allowed by Access-Control-Allow-Headers in preflight response.
@(index):1 2017-12-28T06:34:34.569Z [storage-webdav] Stat error https://xxxxxxxx/linux.kdbx 1734ms
@(index):1 2017-12-28T06:35:02.045Z [storage-webdav] Stat https://xxxxxxxx/linux.kdbx
(index):1 Failed to load https://xxxxxxxx/linux.kdbx: Request header field Cache-Control is not allowed by Access-Control-Allow-Headers in preflight response.
@(index):1 2017-12-28T06:35:02.157Z [storage-webdav] Stat error https://xxxxxxxx/linux.kdbx 112ms
@(index):1 2017-12-28T06:35:07.109Z [storage-webdav] Stat https://xxxxxxxx/linux.kdbx

The environment we used that are not Apache/Nginx/Caddy . 
So could ou give me some suggestions about this issue?

**Comment by antelle** [comment]
Hi,
> @(index):1 Failed to load https://xxxxxxxx/linux.kdbx: Request header field Cache-Control is not allowed by Access-Control-Allow-Headers in preflight response.

Please configure your server to enable CORS.
