### ISSUE TITLE
UI got Extra Margin at the bottom of the Tag Panel, Can not decrease the size

### ISSUE THREAD

**Issue by gynet** [keeweb/keeweb#825]
My database has no tags defined, however, It got extra space at the bottom of the tag panel, and it cannot be resized to remove the empty space.  

Be able to reproduce using demo db by removing all the existing tags. 

- app version
1.6.3

- User-agent (from Settings/Help section)

KeeWeb v1.6.3 (cded8a4, 2017-12-11)
Environment: electron v1.7.9
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_1) AppleWebKit/537.36 (KHTML, like Gecko) KeeWeb/1.6.1 Chrome/58.0.3029.110 Electron/1.7.9 Safari/537.36

<img width="700" alt="5127d6c6-6f67-4cad-a62d-72b78d262dd0" src="https://user-images.githubusercontent.com/2174522/34427328-2e1b31c8-ebf6-11e7-8e9f-e1da78f6ed30.png">

**Comment by antelle** [comment]
Probably you had resized Tags section earlier before you removed existing tags.
It's not possible to resize the section to one line by dragging it, but if you double-click the line, it will go back to one line (auto-)size: https://monosnap.com/file/f81ILYucSoHVvau8Ggq3wWSvlJjr0D

**Comment by gynet** [comment]
yes, got it resized back, thx
