### ISSUE TITLE
Feature Request: For Every Entry to have Multiply Auto-Type Settings be able to mapping to different URL/Title 

### ISSUE THREAD

**Issue by gynet** [keeweb/keeweb#826]
It would be nice for one entry be able to have multiple auto-type settings, and each of them is able to map to different URLs or titles.

**User Scenario**:  As a user, he/she may have different auto-type requirements for different scenarios.

 --  e.g A user may have one entry apply to multiple application/UI/URL, some of them may just require a password, and some of them may require type both username and password, or some of them could require other keystrokes before typing password too.

**Comment by antelle** [comment]
Hi,
It's "auto-type window configuration" feature, yeah, it should be implemented: #433
