### ISSUE TITLE
File hosting on the same server as keeweb

### ISSUE THREAD

**Issue by vavrecan** [keeweb/keeweb#828]
if anybody was wondering how to do this, I did it in my fork 
https://github.com/vavrecan/keeweb/commit/b364f5a86c0d3589db1d64d545328bd020e72038

which adds support for simple storage on same self hosted server (hiding all other options).
Reading and writing is done through simple php script that should go to /server/ directory. 

User is then asked for password to access server files (which can also be changed in php script) and then he can use keepass with server stored files easily. It should be easy to rewrite script to other programming languages as well.

<a href="https://ibb.co/jEwcSG"><img src="https://thumb.ibb.co/jEwcSG/Screenshot_from_2017_12_30_21_07_32.png" alt="Screenshot_from_2017_12_30_21_07_32" border="0"></a> <a href="https://ibb.co/hPHvEw"><img src="https://thumb.ibb.co/hPHvEw/Screenshot_from_2017_12_30_21_07_37.png" alt="Screenshot_from_2017_12_30_21_07_37" border="0"></a> <a href="https://ibb.co/jTWcSG"><img src="https://thumb.ibb.co/jTWcSG/Screenshot_from_2017_12_30_21_07_53.png" alt="Screenshot_from_2017_12_30_21_07_53" border="0"></a>

Files stored on the server
<a href="https://ibb.co/mA48Zw"><img src="https://thumb.ibb.co/mA48Zw/Screenshot_from_2017_12_30_21_11_00.png" alt="Screenshot_from_2017_12_30_21_11_00" border="0"></a>

Hope it helps.

**Comment by vavrecan** [comment]
@antelle I have question in that case - how to compile plugin with grunt to the keeweb so that users do not have to install it? 
Thank you

**Comment by antelle** [comment]
Probably they will add a json config anyway (at least most users do so), where they can enable this plugin as well.
