### ISSUE TITLE
Suggestion about stay the app only in the Menu Bar of OSX

### ISSUE THREAD

**Issue by facutopa** [keeweb/keeweb#830]
Hi,

I don't think here is the place for request or suggestion, but in the "Pull request" tab I see only one entry and the "Issues" tab a lots of requests.

Currently the app stay open (but locked) in the dock, like here: 
![Dock picture](https://user-images.githubusercontent.com/7283431/34462579-b7380f2c-ee25-11e7-889c-c50f6c0b2f96.png)

I thought will be cool if we have the option to hide from the dock and have only the icon on the Menu Bar, like other apps did:
![Menu bar picture](https://user-images.githubusercontent.com/7283431/34462577-ab612170-ee25-11e7-907d-b06b8b39eafd.png)

I don't find this feature in the app so I suggested. If it isn't possible no problem.
Thanks, regards and a happy new year

**Comment by antelle** [comment]
Hi,
This is the right place for suggestions!
Some tray improvements will be in the next version: https://github.com/keeweb/keeweb/issues/762
It will also be there probably.
Happy new year you too 🎅 🎄

**Comment by jaimehrubiks** [comment]
This sounds great

**Comment by RowanKaag** [comment]
It would be awesome if this could actually make it into milestone v1.14 / v1.15, looks like it has been dragged to new milestones for quite some time @antelle.
