### ISSUE TITLE
Save to Google Drive: File already exists

### ISSUE THREAD

**Issue by jalmeroth** [keeweb/keeweb#833]
- what were your actions?

1. In Google Drive create a file or folder with the name `Test`
2. In KeeWeb create a new file, go to settings and rename it to `Test`
3. Press Save to… and choose Google Drive as target
- what was wrong?
The app asks for confirmation to overwrite a file that does not exist (yet). The issue here seems to be that the app sees the folder `Test` in the file list and compares it against the new name of the file being `Test` as well. But the file will be stored as Test.kdbx later on. So the comparison is apples and oranges :)
Btw, please note that Google Drive supports multiple files in one directory with the same name, but this is not the issue here.
- app version
1.6.3 and develop
- your user-agent (from Settings/Help section)
KeeWeb v1.6.3 (undefined, 2018-01-03)
Environment: web
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.108 Safari/537.36
- does it happen on Demo or New database?
- if you are using a test db without your personal data, please attach it
- please, open dev tools in your browser and attach output log from Console tab 
    (if you are using desktop app, devtools can be opened from Settings/General/Advanced)

**Comment by antelle** [comment]
Yeah, old issue, it's there since when we didn't allow to use other file extensions...

**Comment by antelle** [comment]
Deployed to [beta.keeweb.info](https://beta.keeweb.info), will be available in the next release.

**Comment by jalmeroth** [comment]
Ok, I tested the beta version and it works as expected. Very good! Thank you very much for this project and your instant response/fix. Your effort is highly appreciated here.

**Comment by jalmeroth** [comment]
… well, I actually did an other test, which is related to this issue and which failed:

I created two kdbx files in my Google Drive, gave the same name to both files, stored in the same directory. Now, if you save another DB with this name into the directory and allow the app to overwrite, it will remove whatever Google Drive file that matches with the same name first. :/

I think this could lead to an unexpected deletion of any Google Drive file with this name?

**Comment by antelle** [comment]
Well, this is another issue. Having a directory with the same name is not the same as having two files with the same name. While the first is absolutely normal and common, the second is geeky, google-specific and confusing in terms of file selection and further support. So I would say, let's leave it as is.

**Comment by jalmeroth** [comment]
> So I would say, let's leave it as is.

I think an application that deletes user's files, should have 100% certainty to handle the correct file. 

Anyway I can respect that decision as it is an edge-case, but I would recommend to document that multiple files with the same name in one directory-scenarios are not supported; either in the FAQ, on the Google Drive Wiki page or both.

**Comment by joanrieu** [comment]
Let's just say that I lost 10 GB of data stored in a "Perso" folder when I saved a file called "Perso" in KeeWeb (expecting it to be named "Perso.kdbx", by the way). I won't try to describe my anger when that happened. NB : the folder had been 100% erased, not put in the trash (which could have been acceptable). Correct behavior would have been to just create the damn file as it was supposed to.

If that happens to someone else, you can contact Google Drive Support and they will be able to restore everything you've ever deleted from Google Drive BUT you will lose some parts of your folder hierarchy, and you'll get many unwanted files from 10 years ago... Make backups people.

> So I would say, let's leave it as is.

Please don't.

**Comment by antelle** [comment]
Well, according to the bug description and how it should behave, it asks if you want to overwrite if there's a folder with such name (which was reported here as a bug). It must not overwrite it indeed.

**Comment by joanrieu** [comment]
If you think it's a separate issue, I'll open a new one with more details whenever I get some time to reproduce the issue (it was a few months ago). Great piece of software nevertheless. ;)

**Comment by antelle** [comment]
I think there's no need to create a new issue, anyway this is already fixed for the next release.
