### ISSUE TITLE
[Feature Request] Don't open second instance of KeeWeb from windows menu

### ISSUE THREAD

**Issue by Akeboshiwind** [keeweb/keeweb#835]
My usual workflow for opening keeweb is to search for it in the windows search bar as I can do this using only the keyboard. It would be great if this wouldn't open another instance of keeweb as this prevents the keewebhttp plugin from working.

I understand that sometimes people will want to open two instances of keeweb, perhaps there could be an option for this in the right-click menu on the keeweb taskbar icon?

**Comment by tmthrgd** [comment]
This looks like a duplicate of #807.

**Comment by antelle** [comment]
@tmthrgd yeah exactly.

**Comment by Akeboshiwind** [comment]
Yup, those are the same symptoms I'm getting.
Glad to see this is getting looked into :)
