### ISSUE TITLE
Changing between multiple vault / password db setting 

### ISSUE THREAD

**Issue by loriopatrick** [keeweb/keeweb#838]
I have two vaults / password dbs. I click the first vault using the bottom left tab, then click the second vault in the same tab bar. When I click on the first vault it brings me to its settings. When I click the second, the nav on the left indicates I'm viewing the second vault however the settings interface does not change, it remains on the first vault. I can only view the second vault's settings if I click on its tab first from the main app.

App Version: Desktop v1.6.3

**Comment by dploeger** [comment]
This is a duplicate of #904 and already fixed. 😁

**Comment by antelle** [comment]
@dploeger exactly, thanks!
