### ISSUE TITLE
Application Error: The application was unable to start correctly

### ISSUE THREAD

**Issue by Matvei27** [keeweb/keeweb#839]
I get this on Windows 10 64bit.
error code is 0xc0000005

**Comment by antelle** [comment]
Logs / crash info please.

**Comment by Matvei27** [comment]
I tried creating those registry entries, but nothing appears under %localappdata%\crashdumps

**Comment by antelle** [comment]
@Matvei27 this article could be up-to-date:
https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/enabling-postmortem-debugging

**Comment by antelle** [comment]
more details in #840
