### ISSUE TITLE
Google Drive file/folder browser shows first page only

### ISSUE THREAD

**Issue by anneb** [keeweb/keeweb#844]
When browsing google drive files and folders, only the first set (page) of files and folders are displayed. There seems to be no option to load more files and folders and there seems to be no other way to open such files or folders from gdrive.

**Comment by antelle** [comment]
You can scroll it, it’s scrollable, but the scrollbar is not visible on that view. It was already mentioned somewhere, so I’ll close it.

**Comment by anneb** [comment]
Yes, the list is scrollable, but when you reach the bottom, the next set of files/folders is not fetched.

I think there is a pagetoken option in the google drive rest api for list that can be passed in to request the next set of files/folders.

Maybe filtering for just folders and .kdbx files would make it less likely that people need multi-page listings?

**Comment by antelle** [comment]
Ah you mean the page size, when there are more than 100 files? Yep, let's change it to max possible 1000, it will be enough for almost everyone.

**Comment by anneb** [comment]
Applied fix https://github.com/keeweb/keeweb/commit/cc14a5e7e5aeee5760061356540e529dc24ba0ee, works well. Good and simple solution.
