### ISSUE TITLE
Make cache and cloud service credential more configurable

### ISSUE THREAD

**Issue by gynet** [keeweb/keeweb#846]
Currently, the cache is saving at an unknown location within the app. 
It would be nice to:
- Make the caching mechanism more configurable: 
1. enable a way to save the cache to a different location / relative location to the binaries folder. 
 User scenario: e.g, a user may only want to save all the data on a USB stick without saving anything to the system disk. 
2. Turn cache on / off 
- Add a way to Save/Clean the cloud service credentials. 
1. currently I can not clean the google drive credential for the desktop app, it is able to retrieve all the files even after I deleting the cache db

**Comment by antelle** [comment]
Hi,
To “logout” from Google Drive, disable it and enable again in settings. It's indeed not the smartest way, there's another issue about it, so it will be changed in future to something like “forget me” action.
KeeWeb doesn't cache files opened from a file system (disks, usb sticks, etc...) exactly for the reasons you mentioned (prevent copying files from removable media). Other than that, I don't see any need in making something that cannot be understood and read by a normal user, configurable.

**Comment by gynet** [comment]
@antelle Thanks for the reply, is that possible to show and provide a user a way to change the cache location.  Some users might have security concern to cache the db on the system drive. Also, for some user, like me,  would like to use **Keeweb + Cloud Drive** fully on a flash drive, in this scenario, it looks like keeweb keeps the db on the system drive instead of the flash drive.

**Comment by gynet** [comment]
Some users might want to use keeweb on a guest machine, public machine or a working PC, they still want to have the feature of cloud sync but prefer to cache it on a flash drive.

**Comment by antelle** [comment]
Then we need an option to disable cache (#404), those who would like to open files from cloud storages and save them only to a usb stick when it's inserted, could disable cache and setup backups for it.

**Comment by gynet** [comment]
@antelle  That would work, thanks!
