### ISSUE TITLE
Cannot Create Groups

### ISSUE THREAD

**Issue by M94antony** [keeweb/keeweb#849]
Can't seem to create Groups - no confirmation or save buttons ; so it mostly returns without creating the group

![image](https://user-images.githubusercontent.com/9370806/35097910-248027a4-fc4a-11e7-9047-1dea58b1a51b.png)

**Comment by M94antony** [comment]
Apologies, it took me a while to find the group though creation had no save button and the toggle to breakdown could be useful.

**Comment by chenjie4255** [comment]
@M94antony so how to create a group, I can not find a way

**Comment by M94antony** [comment]
on the top there is a + sign(right next to the search bar). clicking it will give you a drop down to create a group

**Comment by chenjie4255** [comment]
@M94antony thanks for your reply, however, I clicked everywhere, but nothing happened, I still cannot create any group, it going to makes me crazy...
![1558432658962](https://user-images.githubusercontent.com/5313665/58086882-0eac8480-7bf2-11e9-90b4-5644146514da.jpg)

**Comment by Xavier-Plasma** [comment]
@chenjie4255 :
![image](https://user-images.githubusercontent.com/13536762/58086998-f91e6700-7bbf-11e9-8b1b-0fe40b29d9d3.png)

**Comment by M94antony** [comment]
Honestly, this is why it causes so much confusion. There should atleast be a save button rather than assuming the group is automatically created. Really bad ux design choice

**Comment by luckyrat** [comment]
Can you reproduce using the demo on https://app.keeweb.info/ ?

For me, using Chrome desktop, I click the New Group button and the group is immediately listed in the side-bar - "(no title)". The name updates as I type the name of the new group. It's 100% clear to me that the group has been created and there is therefore no need for an additional save button. However, the screenshot @chenjie4255 posted suggests that others might be seeing different behaviour in different environments?

**Comment by chenjie4255** [comment]
@luckyrat 
No, I can't reproduce it on this website if I just created a new database. the function Create Group work perfectly.

However, after saving my local database as a file and open it on this website, the function of Create Group is broken. it has the same behavior as the Mac App.

I think there may be some stains with my database file, I removed all entries of it and save it into another file (see the attachment), you could try it by yourself, the password is 'test'.


[bad copy.kdbx.zip](https://github.com/keeweb/keeweb/files/3230593/bad.copy.kdbx.zip)

**Comment by massimo1993** [comment]
On the desktop application, I am not able to create a group. When I type the name of the group the entry is not populated on the left side. There is no group being created. I am running the desktop application on Windows 10.
