### ISSUE TITLE
How set lang?

### ISSUE THREAD

**Issue by SHKEd** [keeweb/keeweb#850]
I do not have plugins and I can not load language.How????

Network error loading plugins =((((

KeeWeb v1.5.0 (4c4a308, 2017-05-22)
Environment: web
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.97 Safari/537.36 Vivaldi/1.94.1008.44

**Comment by antelle** [comment]
Could you please be more verbose, what’s this link about?
I tried on Mac and Windows, it doesn’t repeat.

**Comment by SHKEd** [comment]
Я просто перепутал вкладки) Спасибо!
