### ISSUE TITLE
HTTP Connector for Self-Hosting 

### ISSUE THREAD

**Issue by berliozz** [keeweb/keeweb#854]
Does anyway to use KeePassHttp-Connector for selfhosted version of Keeweb?
Or maybe exist other solution?
Now, I found Tusk https://addons.mozilla.org/ru/firefox/addon/keepass-tusk/ - but not sure about trust them.

**Comment by antelle** [comment]
Hi! Web version can't connect with KeePassHttp, so it won't be possible.
From what I understand, this add-on is loading kdbx files inside it, so it doesn't require neither keepass app, nor keeweb.
