### ISSUE TITLE
[Feature request] Ship Appdata file with Linux Packages

### ISSUE THREAD

**Issue by arshubham** [keeweb/keeweb#855]
- what was wrong?
Currently Appdata files are not shipped with Linux packages. It ensures integration with Linux app stores.
Docs : https://www.freedesktop.org/software/appstream/docs/chap-Quickstart.html#sect-Quickstart-DesktopApps

After installing a valid appstream file. Keeweb can be uninstalled with  a dedicated entry in the installed section of any modern app store. 
- app version
```
KeeWeb v1.6.3 (cded8a4, 2017-12-11)
Environment: electron v1.7.9
```
- your user-agent (from Settings/Help section)
```
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) KeeWeb/1.6.3 Chrome/58.0.3029.110 Electron/1.7.9 Safari/537.36
```

**Comment by antelle** [comment]
Hi,
What is AppData files and how to include them?
Also, is it the only limitation? From what I saw when I checked the app, there are a lot of other violations coming from plenty of libraries keeweb is using, so it won't be possible to submit the app to linux app stores.

**Comment by arshubham** [comment]
The link works for me. Anyway Here is the example:
```
<?xml version="1.0" encoding="UTF-8"?>
​<!-- Copyright 2013 First Lastname <your@email.com> -->
​<component type="desktop-application">
​  <id>org.gnome.gnome-power-statistics</id>
​  <metadata_license>FSFAP</metadata_license>
​  <project_license>GPL-2.0+</project_license>
​  <name>Power Statistics</name>
​  <summary>Observe power management</summary>
​
​  <description>
​    <p>
​      Power Statistics is a program used to view historical and current battery
​      information and will show programs running on your computer using power.
​    </p>
​    <p>Example list:</p>
​    <ul>
​      <li>First item</li>
​      <li>Second item</li>
​    </ul>
​    <p>
​      You probably only need to install this application if you are having problems
​      with your laptop battery, or are trying to work out what programs are using
​      significant amounts of power.
​    </p>
​  </description>
​
​  <launchable type="desktop-id">org.gnome.gnome-power-statistics.desktop</launchable>
​
​  <screenshots>
​    <screenshot type="default">
​      <caption>The options dialog</caption>
​      <image>http://www.hughsie.com/en_US/main.png</image>
​    </screenshot>
​    <screenshot>
​      <image>http://www.hughsie.com/en_US/preferences.png</image>
​    </screenshot>
​  </screenshots>
​
​  <url type="homepage">http://www.gnome.org/projects/en_US/gnome-power-manager</url>
​  <project_group>GNOME</project_group>
​
​  <provides>
​    <binary>gnome-power-statistics</binary>
​  </provides>
​
​  <releases>
​    <release version="3.12.2" date="2013-04-12">
​      <description>
​        <p>Fixes issues X, Y and Z</p>
​      </description>
​    </release>
​  </releases>
​</component>
```

An appdata file basically gives info about the application to appstores (like gnome-software or elementary's appcenter). It will show up in the installed apps section and clicking on it will show the screenshots and other info about the application. **It doesn't need to be installed through the appstore**.

According to a similar [open issue](https://github.com/Microsoft/vscode/issues/37813) in vscode appdata file needs to be installed in '/usr/share/metainfo/%{id}.appdata.xml' 

I don't know exactly how to do with this in electron as I only worked with native app and it is taken care by meson.

**Comment by antelle** [comment]
Well, adding an xml file is pretty easy to do (I thought it was about temporary files from AppData generated in runtime).
Do you know if it's the only violation of app stores conditions?
// The link is now working for me as well.

**Comment by arshubham** [comment]
> Do you know if it's the only violation of app stores conditions?
I have worked with elementary appcenter. And they only require a proper appdata file, dektop file and icons of different sizes (16, 24, 32, 48, 64, 128).  
When I installed my application in Ubuntu 18.04 it showed up correctly in gnome-software too, so I think requirements are the same.

**Comment by antelle** [comment]
Okay cool, thanks
