### ISSUE TITLE
Add a notification when the password is copied from history

### ISSUE THREAD

**Issue by deeperton** [keeweb/keeweb#857]
Please add ability to copy field content from history for item. Currently I'm unable even to see old password.

KeeWeb v1.6.3 (cded8a4, 2017-12-11)
Environment: electron v1.7.9
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_2) AppleWebKit/537.36 (KHTML, like Gecko) KeeWeb/1.6.3 Chrome/58.0.3029.110 Electron/1.7.9 Safari/537.36

**Comment by antelle** [comment]
Hi,
This is possible in entry history:
1. go to entry details
2. open history by clicking a link under entry dates
3. select a state with arrows
4. copy the password

**Comment by Sysix** [comment]
Hello it is not possible for me in my windows application.

I can select the state with the errors but the password I can't be copy/showed.  
Maybe the only possible way is for me to "Revert to state". 

I'm Using the current KeeWeb Version and Win10 Pro-Edition

**Comment by deeperton** [comment]
Same case was for me. Eventually it just starts working as expected. Without any tooltip, but it starts coping values. Probably there is some bug which hard to reproduce.

**Comment by antelle** [comment]
We should add a tooltip for that, yeah, it's quite hard to copy a password without it.

**Comment by deeperton** [comment]
The thing is -- it is not always work as expected. Not only tooltip...

**Comment by antelle** [comment]
This needs more details, I can't reproduce it. Does it repeat for you?

**Comment by deeperton** [comment]
Exactly after your first response, I've tried and it starts copying, without any visual feedback, but works.

I don't know how to reproduce it. Right now - it working.

**Comment by Sysix** [comment]
I finally found out, that I must click on the label to copy the value.  
It is a bit wierd because I usally try to click inside the value to copy it.

**Comment by deeperton** [comment]
I definitely clicked on labels... I clicked everywhere when first faced with my issue and after each click tried to paste into Sublime.

**Comment by antelle** [comment]
Yes, it's a human error because there's no feedback. Adding a message will solve this.

**Comment by antelle** [comment]
Let's reopen it to track.
