### ISSUE TITLE
Web App not using my updated database (webdav)

### ISSUE THREAD

**Issue by benbuc** [keeweb/keeweb#858]
Hi,
I just set up KeeWeb web app on my server and included a database file using webdav. The problem is, that I want to edit the same file with other software as well. When I update the file locally and overwrite the file on my server, keeweb somehow seems to still use the old file. Am I doing anything wrong or is there some kind of workaround?

Otherwise I already love the app. Thanks for sharing.
Best,
Benito

**Comment by benbuc** [comment]
@antelle Hi again and thanks for your answer. I checked the last modified date and it seemed that it was not the issue.
Nonetheless I found a setting on my way I had overseen before.
After changing General -> Synchronisation -> Webdav -> Saving method from temporary file to overwrite everything works like a charm.

Thanks for your answer.

**Comment by antelle** [comment]
Weird, they both should work, but cool that it solved your issue.
