### ISSUE TITLE
[Feature request] Right click entry to select copy username / password

### ISSUE THREAD

**Issue by frode** [keeweb/keeweb#86]
Would be very handy if you could right click a entry and select "copy username" for one option, and "copy password" for another. This is to avoid passwords being visible on screen and makes it a little quicker to get these details into the clipboard.

**Comment by antelle** [comment]
For now, you can copy the password with Cmd/Ctrl+C while you are on the entry list. To copy a username, or any other field in entry, click its title.
I'll think about right-click, for now it's not used anywhere in the interface but could be, as additional option for fast access to some actions.

**Comment by smari** [comment]
A button to do this would also be appreciated. Right now the only point-and-click way of copying the password that I can find involves exposing the password visually -- something I'd like to avoid.

**Comment by antelle** [comment]
Buttons will look ugly, imagine them next to the very field. So they won't be added.
You can copy the password without exposing:
- by ctrl-C (which is said on shortcuts page)
- with click title (on the first use, you get the hint about it)

**Comment by smari** [comment]
Agreed that beside every field would be bad, but I'd argue that the password field is a special case. Either way, good hint on the title -- although I missed that hint, and it wasn't intuitive.

**Comment by antelle** [comment]
Manual close button on the tooltip could help in this case

**Comment by antelle** [comment]
Deployed to [beta.keeweb.info](https://beta.keeweb.info), will be available in the next release

**Comment by smari** [comment]
Many thanks!
