### ISSUE TITLE
Argon broken on iOS?

### ISSUE THREAD

**Issue by biyori** [keeweb/keeweb#861]
- what were your actions? Open a argon keepass file on iphone through the web app
- what was wrong? It fails to open the database saying something about argon being undefined
- app version (web app web.keeweb.info)
- your user-agent (from Settings/Help section) Safari
- does it happen on Demo or New database? 
- if you are using a test db without your personal data, please attach it 
- please, open dev tools in your browser and attach output log from Console tab 

`[INFO ] 2018-02-03T01:00:11.728Z [app] Started in 160ms ¯\_(ツ)_/¯
[INFO ] 2018-02-03T01:00:27.752Z [open:lastpass2] File open request
[INFO ] 2018-02-03T01:00:27.752Z [open:lastpass2] Open file from supplied content
[DEBUG] 2018-02-03T01:00:27.813Z [argon2] WebAssembly runtime loaded 47ms
[ERROR] 2018-02-03T01:00:27.813Z [argon2] Worker error Error: Argon2 error -1
[ERROR] 2018-02-03T01:00:27.814Z [file] Error opening file undefined undefined Error: Argon2 error -1
[ERROR] 2018-02-03T01:00:27.814Z [open-view] Error opening file Error: Argon2 error -1
`

**Comment by antelle** [comment]
It is. Also crashes reported sometimes.

**Comment by antelle** [comment]
Seems to be working on latest iOS.
