### ISSUE TITLE
Download attachment on mobile

### ISSUE THREAD

**Issue by jivarson** [keeweb/keeweb#862]
Is there any way to download attachments from Keeweb from from the phone using the web app? 

Using Android 7+, when I long-press the attachment I get the generic context-menu to copy user or password etc.

**Comment by antelle** [comment]
There's no way at the moment...

**Comment by atmouse-** [comment]
+1

**Comment by antelle** [comment]
<img width="275" alt="Screen Shot 2019-10-06 at 12 57 15" src="https://user-images.githubusercontent.com/633557/66268011-d58b4e80-e838-11e9-9eb3-adfa117de452.png">
