### ISSUE TITLE
Always show password instead of 'dots'

### ISSUE THREAD

**Issue by seasonw** [keeweb/keeweb#864]
Hi, possible to show password instead of 'dots' in entry? I cannot find it in configuration, so I guess there is no way to config it. But I think it should not be a hard job to modify the source file, anyone can enlighten me which js file should I modify and what should I modify. Thanks!

**Comment by antelle** [comment]
Hi,
It's not possible currently, but can be added of course.

**Comment by seasonw** [comment]
Thank you for your response and added to enhancement. I found it is very useful especially on accessing keeweb from mobile browser, because we have to tap on password field in order to view the password, but the soft keyboard will pop up too, it is very annoying. And yet, I would say it is very useful to know the password without tap on the password field to view.

BTW, any easy temporary solution to modify the source code, for example to change password field to text?

Thanks!

**Comment by antelle** [comment]
Well, there are plugins, however it won't be easy to change the password field type, it's kinda special and there's some hard code, so I would say, there's no easy way to change it.

**Comment by seasonw** [comment]
Thanks for prompted reply, then I will check for plugins while waiting for the new enhancement. Thanks again, antelle 👍

**Comment by antelle** [comment]
Now it's possible to reveal the password. An option to always show it won't be added because it's very strange, but feel free to create a plugin for that.
On mobile, there will be another improvement in the next release that will simplify working with fields.

**Comment by seasonw** [comment]
Thanks for the feature, I will upgrade it ASAP to test it out.
