### ISSUE TITLE
Dropbox sync issue

### ISSUE THREAD

**Issue by Aneyrin** [keeweb/keeweb#865]
Hello,

Faced with issue trying to sync KeeWeb with my Dropbox account.

What Exactly I did:

0. Created new App, aded all strings from these instructions: https://github.com/keeweb/keeweb/wiki/Dropbox-and-GDrive
1. Added my App key to Keeweb settings
2. Entered valid login and pass in "Dropbox - API Request Authorization - Sing in" window
3. Have issue "There was a problem completing this reguest" in Dropbox Authorization window

Please look at attached screenshots for details. Any idea how to fix it?

<img width="857" alt="keewebdropboxappsettings" src="https://user-images.githubusercontent.com/3351788/35913156-da413a4a-0c0f-11e8-902e-37d20a309319.png">

![keewebissue](https://user-images.githubusercontent.com/3351788/35913186-ef7cf098-0c0f-11e8-8826-8fdd4aa12037.png)

**Comment by antelle** [comment]
Hi,
It looks like, you need to add your server to RedirectURIs.

**Comment by Aneyrin** [comment]
Thank for your suggestion. Any idea what I need to add there? I don't have local server.

**Comment by antelle** [comment]
How do you access your keeweb app?

**Comment by Aneyrin** [comment]
I`m using local *.kdbx file and KeeWeb for MacOS application. Where can I find my local server adress?

**Comment by antelle** [comment]
Hm. Then it should just work, is there anything interesting in devtools?

**Comment by Aneyrin** [comment]
I`m successfully synced to Dropbox with web version of KeeWeb, but still can't do the same with installed App (issue message on second screenshot). I guess anything good with devtols, other way it wasn't work with web app.  Probably I need modify this string "https://localhost:B085/tmp/" in redirect URLs? Any other idea?

**Comment by antelle** [comment]
No, the app doesn't use this url, it's using app.keeweb.info, so this url won't help.
You can open devtools in apps from Settings -> General -> Advanced.

**Comment by Aneyrin** [comment]
Anything interesting here?

![screenshot at feb 08 01-21-58](https://user-images.githubusercontent.com/3351788/35944718-79e71926-0c6e-11e8-9320-ab44d607681c.png)

**Comment by antelle** [comment]
Try Network or Console panel, they can have something :)

**Comment by Aneyrin** [comment]
![screenshot at feb 08 02-16-03](https://user-images.githubusercontent.com/3351788/35946756-1581f7b4-0c76-11e8-9204-147c6b8233a0.png)
![screenshot at feb 08 02-16-52](https://user-images.githubusercontent.com/3351788/35946769-22c07de2-0c76-11e8-9d8b-c8fefd48e9cc.png)

**Comment by antelle** [comment]
we need to open devtools in this popup :( but it’s not possible.
I can make a build for it, would you lile to test it?

**Comment by Aneyrin** [comment]
Sure, let's do it.

**Comment by antelle** [comment]
ok, I’ll upload it tomorrow

**Comment by antelle** [comment]
Uploaded it to beta, you can switch to beta build in Settings -> Advanced

**Comment by Aneyrin** [comment]
Hi,

I hope it`s will be helpful. Let me know if I can to try something else.

![dropboxissue](https://user-images.githubusercontent.com/3351788/35990795-4a9c677c-0d16-11e8-97b8-d84a6f68b56f.png)

**Comment by antelle** [comment]
Sorry, I don't see a failed request there. Also, your Dropbox window doesn't show any sign of error.
Please try to repeat the error, then find the failed request, select it and see what's there in the response.

**Comment by Aneyrin** [comment]
error message dissapear too fast. Did the same this time screen with error:
![dropboxissue2](https://user-images.githubusercontent.com/3351788/35991978-f8fad0e4-0d19-11e8-99b3-1bc368733de7.png)

**Comment by antelle** [comment]
Interesting. Let's try filtering by XHR, maybe there's anything interesting there? E.g. requests with non-200 status codes?

**Comment by Aneyrin** [comment]
![screenshot at feb 08 21-53-25](https://user-images.githubusercontent.com/3351788/35992156-86c8135a-0d1a-11e8-8cdc-2cb1008beaf3.png)

**Comment by antelle** [comment]
That's more interesting, gives a hope :)
Let's select first ajax_login and check the Response tab for it :)

**Comment by Aneyrin** [comment]
![screenshot at feb 08 22-03-20](https://user-images.githubusercontent.com/3351788/35992644-e7ac627e-0d1b-11e8-90c3-8a4c8a1de192.png)

![screenshot at feb 08 22-04-10](https://user-images.githubusercontent.com/3351788/35992680-0471197c-0d1c-11e8-9986-5c1bb3c89915.png)

**Comment by antelle** [comment]
Try to uncheck Dropbox in app settings and then check it back, it will reset cookies.

**Comment by Aneyrin** [comment]
I did the same many times. This is what I got:

![screenshot at feb 08 23-59-54](https://user-images.githubusercontent.com/3351788/35997966-400e02a0-0d2c-11e8-8e64-2ce8961c7426.png)

**Comment by antelle** [comment]
Deleting this app settings file could also help:
`~/Library/Application\ Support/KeeWeb/app-settings.json`
(but please make a backup of it somewhere before you delete it)

**Comment by Aneyrin** [comment]
Any idea what else I can try? (

![screenshot at feb 09 00-14-22](https://user-images.githubusercontent.com/3351788/35998599-3668722e-0d2e-11e8-838e-0cb0cd28a4fa.png)

**Comment by antelle** [comment]
Maybe also this: `Library/Application\ Support/KeeWeb/runtime-data.json`, or whole directory: `Library/Application\ Support/KeeWeb/`

**Comment by Tiposbingo** [comment]
When I delete whole directory: Library/Application\ Support/KeeWeb/ it works again :)  thank you

**Comment by antelle** [comment]
Could be fixed in v1.7
