### ISSUE TITLE
Inactivity auto-lock is delayed until UI is accessed 

### ISSUE THREAD

**Issue by philogit** [keeweb/keeweb#868]
### Step to reproduce this issue
* Set auto-lock timeout inactivity to a value > 0.
* Unlock a database and interact with UI.
* Leave the application for time > inactivity timeout.
* Return to application.
* Observe that the unlocked UI is fully visible for ~ less than a second.
* Application switches to login screen.

### Expected behavior
When returning to the application after inactivity timeout:
* Application should display only the login screen

### App version
KeeWeb v1.6.3 (cded8a4, 2017-12-11)
Environment: electron v1.7.9
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) KeeWeb/1.6.3 Chrome/58.0.3029.110 Electron/1.7.9 Safari/537.36

**Comment by antelle** [comment]
Hi, the app is actually locked, however we can't clean cached screen state, so you will see a visual flash with old state for some period of time until Electron is “waking up”. We won't be able to fix it unfortunately, this is how Chromium works, it will be the same in browser or other Electron apps.
If you know a way to fix it in Electron, please reopen.
