### ISSUE TITLE
Support backups to directory

### ISSUE THREAD

**Issue by fireworkerfp** [keeweb/keeweb#869]
- what were your actions?
I want to create al local backup of my Database
- what was wrong?
When i click on "save now" i got ERROR: EISDIR illegal operation on a direcoty, open a "Path to my backup folder
- app version
Desktopapp V 1.6.3
- your user-agent (from Settings/Help section)
Mozilla/5.0 (Windows NT 10.0; Win64; x64) 
- does it happen on Demo or New database?
old Database from Keepass2
- please, open dev tools in your browser and attach output log from Console tab 
    (if you are using desktop app, devtools can be opened from Settings/General/Advanced)
2018-01-21T17:19:21.803Z [backup:Florian] Backup file to file "Path to my backup folder"
index.html:1 2018-01-21T17:19:21.804Z [storage-file] Stat "Path from my Databse" 
index.html:1 2018-01-21T17:19:21.805Z [storage-file] Stat done "Path from my Databse"   1ms
index.html:1 2018-01-21T17:19:21.805Z [backup:Florian] Backup folder exists, saving
index.html:1 2018-01-21T17:19:21.806Z [storage-file] Save "Path to my backup folder" undefined
index.html:1 2018-01-21T17:19:21.807Z [storage-file] Error writing local file "Path to my backup folder" Error: EISDIR: illegal operation on a directory, open 'Path to my backup folder'
a.error @ index.html:1
l @ index.html:1
(anonymous) @ index.html:1
(anonymous) @ fs.js:1306
(anonymous) @ fs.js:114
index.html:1 2018-01-21T17:19:21.811Z [backup:Florian] Backup error Error: EISDIR: illegal operation on a directory, open 'Path to my backup folder'

**Comment by antelle** [comment]
Hi,
What was your backup path? It must include file name.

**Comment by fireworkerfp** [comment]
Hi,

this was my backup path: C:\Users\Flo\Documents\Privat\keep_Backup

**Comment by antelle** [comment]
It looks like a folder, doesn't it? :)

**Comment by fireworkerfp** [comment]
Sry but I don't get it. 
Did I something wrong? :-)

**Comment by kasoban** [comment]
@fireworkerfp you seem to have configured a directory as backup target, not a file.

instead of `C:\Users\Flo\Documents\Privat\keep_Backup`
try `C:\Users\Flo\Documents\Privat\keep_Backup\myBackupFile`

Or is "keep_Backup" indeed a file and not a directory?

**Comment by fireworkerfp** [comment]
No it is a directory. Sry I thought that I have to choose a backup directory and not a File.

I am sry for the trouble.

**Comment by antelle** [comment]
Yes, it must be a file. We should support directories as well, or add a message.

**Comment by dploeger** [comment]
Created PR #1058 for that. I simply optimized the error message, when a directory is encountered rather than a file. Also created translations for it with a possibly bad french translation courtesy of the google translater 😉 

I think, supporting directories shouldn't at least be a high priority as we would need to come up with a default file name pattern for that and the current feature simply does what it needs to do.
