### ISSUE TITLE
Feature Request: Place settings behind login and disable demo...

### ISSUE THREAD

**Issue by k1rb** [keeweb/keeweb#870]
Hello,

Using the self-hosted keeweb server, is there a way to protect the settings? I want to be able to deploy this for teams of people but I don't want them to be able to access backup settings and things like that.
Can these settings be placed behind a login page?

I would also like to disable the "Demo" at some point later down the road.

Thanks so much for all of your hard work, keeweb may solve a lot of problems for us in the future!

**Comment by antelle** [comment]
You can protect the whole server with authorization and add settings to json config: https://github.com/keeweb/keeweb/wiki/Configuration, indeed it won't make settings encrypted and won't prevent users from modifying them, but you can pre-configure some stuff.
Protecting app settings and moving them to kdbx would require redesign the whole app, including UX approach we use, so I would say, it's impossible.
Demo can be disabled with `canOpenDemo` config key.
