### ISSUE TITLE
[Feature request] Add ability to duplicate entries

### ISSUE THREAD

**Issue by phoenixweiss** [keeweb/keeweb#872]
Right now there is no way to duplicate any entry, but unfortunately quite often I suffer a lack of this feature. That would be great if someone add the feature to duplicate a whole entry.

Thanks in advance.

**Comment by Xavier-Plasma** [comment]
![image](https://user-images.githubusercontent.com/13536762/36426511-772962e4-164a-11e8-8db4-0e5f5c22500c.png)
This feature already exist. (it is in french in my screen-capture).

**Comment by phoenixweiss** [comment]
@Xavier-Plasma

Thank you very much! You saved me a ton of time.

As for UI, the current realization is kinda weird and totally inconvenient.
