### ISSUE TITLE
Issue with WebDav (Can you read message please ?)

### ISSUE THREAD

**Issue by LiloBzH** [keeweb/keeweb#878]
- what were your actions? Sync with Webdav and Owncloud
- what was wrong? **# Erreur 500 . Keeweb send a request with url : file://**
- app version 1.6.3 (windows)
- does it happen on Demo or New database? all
- please, open dev tools in your browser and attach output log from Console tab 
    (if you are using desktop app, devtools can be opened from Settings/General/Advanced)

```
[DEBUG] 2018-02-27T08:40:33.178Z [storage-webdav] Save:put error https://cloud.blop.com/remote.php/dav/files/blop/.blop.kdbx.4851678186768 500 337ms
[INFO ] 2018-02-27T08:40:33.178Z [sync:Lilo] Error saving data to storage
[INFO ] 2018-02-27T08:40:33.179Z [sync:Lilo] Sync finished HTTP status 500
```
Ticket Owncloud here : https://github.com/owncloud/core/issues/30330 but we think the problem is Keeweb.

Keeweb seems bo be send local URL first and after remote url

first : file://
2nd : https://cloud.blop.com/remote.php/dav/files/blop/.coucou.1519646962149
3rd : file://
4 : https://cloud.blop.com/remote.php/dav/files/blop/.coucou.1519646962149

**Comment by antelle** [comment]
Reposting the issue several times doesn't make sense, sorry
