### ISSUE TITLE
Dropbox sync and "Save" button

### ISSUE THREAD

**Issue by paul-alkhimov** [keeweb/keeweb#880]
The database is located in `Drobpox > Apps > KeeWeb` folder. Two-step verification on Dropbox is enabled. The database is used from Win7, Win10 and Android (via KeePass2Android). 

I already had a problem in the past (not more than two weeks ago, on the latest keeweb version) with local database on my PC being not refreshed. I had no time to create an issue at that moment, I solved the problem by deleting the complete Keeweb data folder altogether (on windows it is like %USERPROFILE%\AppData\Roaming\KeeWeb\).

On the https://keeweb.info/ I see the button "Sync with Dropbox", but my version has "Save", which is... a completely different thing IMHO.

I would like to clarify which button text is correct and in case if it depends on the type of the used storage (or whatever), what can be written on the button?

- app version: v1.6.3

**Comment by antelle** [comment]
Hi!
Could you please attach the logs when it happens? Then we can check what we get from Dropbox and why it's not refreshed.
"Sync with Dropbox" was replaced with "Save to..." about two releases ago, because now we can save to other storages too. Once you saved it there, "Save" button will stat sync when you need it.

**Comment by paul-alkhimov** [comment]
Yes, I will do in case it repeats.

But anyway I do not like the "Save" word, because it implies "Ignore the other side" or "Overwrite".
The best solution IMHO would be to show somewhere close to the button the very brief sync log of three of four lines maximum. It costs not much (console already has it more or less), but brings extremely important confidence in the most important user actions.

**Comment by antelle** [comment]
I agree, it's better to rename "Save" to "Sync" it the file is opened from a cloud storage.
Not sure about logs though, we have "Syncing..." status and last sync time, apart from this it's more or less technical details, the messages we have now in logs are not readable by "normal" people.
