### ISSUE TITLE
Is there any way to use keeweb in the terminal?

### ISSUE THREAD

**Issue by DrDonkey** [keeweb/keeweb#884]
Couldn't find anyone to contact, so posting query as issue.

**Comment by antelle** [comment]
Hi!
How would you like to use it in terminal?
There are a couple of command-line options, but I'm not sure what you mean: https://github.com/keeweb/keeweb/wiki/Configuration#command-line-switches

**Comment by antelle** [comment]
I see. This project is GUI for KeePass, so it's different.
I heard something about `kpcli` tool, but haven't tried it, not sure if it still works.
