### ISSUE TITLE
Adjust Global Auto-Type Delay

### ISSUE THREAD

**Issue by HarlemSquirrel** [keeweb/keeweb#885]
I'm using v1.6.3 on Arch Linux and the global auto-type begins before I can lift up my fingers from the keyboard shortcut which messes up the auto-type. 

It would be awesome to just have an option to adjust the delay before auto-type begins typing.

**Comment by antelle** [comment]
Hi! There's an option to set global auto-type sequence: 
![auto-type](https://user-images.githubusercontent.com/633557/37049787-54db8004-2172-11e8-90e8-4bf85acc5398.png)
You can change it to
```
{DELAY X}{USERNAME}{TAB}{PASSWORD}{ENTER}
```
(replace X with a number)
Will this work for you?

**Comment by HarlemSquirrel** [comment]
This is _exactly_ what I needed! Thank you!
Tip left :-)
