### ISSUE TITLE
.kdbx file in Google Drive fails to Sync

### ISSUE THREAD

**Issue by jhelmink** [keeweb/keeweb#887]
- what were your actions?
Save changes in KeeWeb.
Expect to see updated kdbx file in Google Drive.
Use KeePass to verify changes have not been made to local kdbx file.
Use KeeWeb SaveTo function to download temporary kdbx and verify changes with KeePass.
Use Google Drive Web interface to download kdbx and verify changes not updated (confirm not a local syncing issue).
Use KeePass to make changes to local kdbx file.
Verify changes synced to Google Drive.
Use KeeWeb to open synced file and verify no changes shown.
Verify no duplicate files exist in Google Drive.

- what was wrong?
Changes saved by KeeWeb are not updating master file in Google Drive.
Changes saved to master file are not updating in KeeWeb.

- app version
KeePass Portable v2.38

- your user-agent (from Settings/Help section)
KeeWeb v1.6.3 (cded8a4, 2017-12-11)
Environment: web
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.186 Safari/537.36

- please, open dev tools in your browser and attach output log from Console tab 
[ConsoleLog.txt](https://github.com/keeweb/keeweb/files/1795103/ConsoleLog.txt)

**Comment by antelle** [comment]
Hi,
I don't understand it. Could you please explain what is:
- local kdbx file
- temporary kdbx

How do you use Google Drive and connect KeeWeb to it?

**Comment by jhelmink** [comment]
Sure thing, sorry it wasn't clear.

So I have the Google Drive app installed on my PC (Now called Backup and Sync).

This syncs the kdbx (KeePass database) file from Google Drive in the cloud to my PC (and my laptop)
Before KeeWeb I just used KeePass portable app to access my kdbx file from my PC or my Laptop, so this was a good way to keep them in sync.

So the local copy of the file is the copy on my PC that has been synced with the Google Drive copy.

KeeWeb is pointing at the same kdbx file in Google Drive. The temporary kdbx file; I used the KeeWeb Save To functionality to save a temporary copy of the kdbx file straight out of KeeWeb to confirm that the changes were made there, and that it had the correct file name.

I assumed that KeeWeb would save any changes to the file, and that the file would then sync down to my PC/Laptop via Backup and Sync. But this does not appear to be the case.

I hope that clears things up, let me know otherwise.

**Comment by antelle** [comment]
How did you open the file in KeeWeb? Selected from Google Drive with a button or dragged from a local file / opened it / clicked Open and selected?

**Comment by jhelmink** [comment]
Selected from Google Drive through the KeeWeb interface connecting my Google Account.

**Comment by antelle** [comment]
Ok, then:
> Save changes in KeeWeb.
Expect to see updated kdbx file in Google Drive.
Use KeePass to verify changes have not been made to local kdbx file.

Changes must have been made to the local kdbx file, right, this is what you expected (and from this, of course, everything is going wrong, because the file seems to be out of sync with the local file)?

**Comment by jhelmink** [comment]
That's correct.

I expected I could make changes to the local file, have that sync back to Google Drive and see the changes in KeeWeb, and vice versa, make changes in KeeWeb, and see those changes in the local file.

Is that not the correct assumption?

**Comment by antelle** [comment]
That's the correct assumption indeed. Let's try to understand why it happens.
Could you please check these cases:
- if you create a file in keeweb, then save it to Google Drive - does it get synced to your computer?
- if you link a new file in keeweb using Google Drive button, then save it - what happens in Google Drive Web UI, is Last Modified date updated for this file?

**Comment by jhelmink** [comment]
Haven't had time to complete testing on this yet sorry, will try to do this weekend.

In the meantime I noticed something else interesting - on my phone I use Keepass2Android, this also syncs with the same Google Drive file. This is syncing correctly with any KeeWeb changes, and vice versa.

However through the web UI Google Drive still does not report any changes to the Last Modified date on the file, and hence it does not get updated on my PC/Laptop.

Will report back when I've tested the cases you've requested.

**Comment by jhelmink** [comment]
You can close this issue as user stupidity.

Searching in Google Drive Web UI returns another kdbx file with the same name in the Trash.
This file is still being updated by KeeWeb / Keepass2Android as shown by the last modified date.

A couple of weeks ago a had a syncing issue on my PC. I deleted the file (which would have moved it to Trash in the cloud) and copied a replacement with the same name. I assumed everything would point to the new file. But in hindsight KeeWeb would of course be linked on some kind of file ID rather than just the file name and folder location.

I will merge the kdbx files, relink in KeeWeb etc and all should be well.

Thanks for your time, apologies for wasting it.
