### ISSUE TITLE
Feature request - more flexible Dropbox config - many accounts for different files.

### ISSUE THREAD

**Issue by gustawdaniel** [keeweb/keeweb#888]
My version:

KeeWeb v1.6.3 (cded8a4, 2017-12-11)
Environment: electron v1.7.9
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) KeeWeb/1.6.3 Chrome/58.0.3029.110 Electron/1.7.9 Safari/537.36

Lets consider following situation:

I am developer creating web service for client. I want to share accounts and passwords to external services with him. I would be able to create second Dropbox account and file containing only accounts connected with his company. I do not want to synchronize this file with my personal Dropbox.

Now I can setup **only one** connection with Dropbox and any file is synchronized with this account. Is it possible to add possibility of connecting with **many accounts**?

**Comment by antelle** [comment]
It's of course possible in theory, but is very complicated and used only for very specific cases like the one you described. Cookie management doesn't work properly with one account, with multiple accounts it would be even more complicated. Also UI for file selection will need modifications, I don't know what exactly.
I'll keep it open and put it to future, but that's pretty much never. Feel free to create a plugin, however it will not be easy too.

**Comment by antelle** [comment]
#407
