### ISSUE TITLE
feature request: keyboard navigation/shortcuts for open dialog

### ISSUE THREAD

**Issue by benzkji** [keeweb/keeweb#889]
I currently work with two .kdbx files, one for private stuff, one for my business related secrets. When opening (ctrl-o) a database file, the last opened .kdbx is still there, and the passphrase can be entered without any more actions/clicks. But then, opening the second one involves mouse clicking it. The same could be probably be achieved by a (tab [focus latest items list] => arrow-down [scroll one item down]) key sequence. I can guess that tab is already implemented (every third tab pressed focuses the passphrase field, again), but it's not clear how and what it does?

clearly optimizing the nifty small things - but that's why I really dig keeweb!

**Comment by antelle** [comment]
Hi, there are some tab improvements for the next release on [beta.keeweb.info](https://beta.keeweb.info), is it what you mean?

**Comment by benzkji** [comment]
nice already. for achieving my goal, I had to type "shift-tab" for times, to select the bottom entry of last opened .kdbx files...tab behaviour after hitting "ctrl-o" is not yet very clear (first selects url in browser, then buttons, then open field, then enter, and only thenafter the last opened .kdbx files).

how about that simple proposal: arrow down and up in the open dialog selects previously opened files?

**Comment by antelle** [comment]
This makes sense yeah

**Comment by benzkji** [comment]
nice, thank you!
