### ISSUE TITLE
Do not install to opt on Linux

### ISSUE THREAD

**Issue by ghost** [keeweb/keeweb#890]
The deb package for linux installs keeweb to `/opt/keeweb-desktop`. This is undesirable on systems like Qubes OS.

**Comment by antelle** [comment]
Hi! What should be there instead?

**Comment by siddhanathan** [comment]
Perhaps `/usr/bin/keeweb-desktop`, similar to how keepassx and keepassxc do it.

**Comment by antelle** [comment]
Should the whole folder be there, or just a symlink to the executable?

**Comment by siddhanathan** [comment]
Just a symlink to the executable. The remaining files would be in `/usr/lib` likely. https://github.com/unindented/electron-installer-debian follows this convention.

**Comment by antelle** [comment]
Ok, this makes sense

**Comment by ramnes** [comment]
Take a look at [the FHS](https://wikipedia.org/wiki/Filesystem_Hierarchy_Standard).

**Comment by antelle** [comment]
Now it will install to `/usr/share`, as for example vscode does.
