### ISSUE TITLE
Google Drive expired session cookies are not deleted or overwritten

### ISSUE THREAD

**Issue by rchipka** [keeweb/keeweb#892]
Our team keeps passwords synced with a KeeWeb database stored in Google Drive.

When the Google Drive session authentication cookies expire, KeeWeb will no longer sync and shows a perpetual blue spinning "sync" icon.

If you try to sync manually, KeeWeb opens the Google login prompt, which will show the user that you were previously authenticated as.

If you try login (as the remembered user or any other user), it redirects to a Google authentication failure page.

Our current workaround is to delete `~/Library/Application\ Support/KeeWeb/runtime-data.json` whenever this happens.

This restores the Google login prompt to it's default state and is able to successfully login.

Another fix is to just delete the `cookies` array inside of `runtime-data.json`

I assume that the cause of this issue is that KeeWeb isn't deleting certain stored session cookies when they expire, and either isn't overwriting the stored values when you re-authenticate or doesn't get a valid session cookie back from Google at all because it may have sent the authentication request with an expired cookie.

Not sure what the correct fix would be, but there's probably a ton of simple fixes and other measures that can be taken instead.

For example, KeeWeb could just clear the `cookies` array after any unsuccessful Google authentication request.

```
KeeWeb v1.6.3 (cded8a4, 2017-12-11)
Environment: electron v1.7.9
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit/537.36 (KHTML, like Gecko) KeeWeb/1.6.3 Chrome/58.0.3029.110 Electron/1.7.9 Safari/537.36
```

**Comment by antelle** [comment]
Yes, this is a known issue, will be fixed in the next release: #810
