### ISSUE TITLE
Log level not checked correctly

### ISSUE THREAD

**Issue by leolivier** [keeweb/keeweb#893]
Hi @antelle 
I think the log levels are not check correctly in util/logger.js.
E.g. :
```
Logger.prototype.debug = function() {
    arguments[0] = this.getPrefix() + arguments[0];
    if (this.level > Level.Debug) {
        Logger.saveLast('debug', arguments);
        console.debug.apply(console, arguments); // eslint-disable-line no-console
    }
};
```  

I would have expected a test:
`    if (this.level >= Level.Debug) {
`
and the like for all levels.
This way, if I cretae a logger and sets its level to Debug, then I can the logs created with logger.debug ('xxx')

**Comment by antelle** [comment]
Thanks! 🎁 
Fixed it
