### ISSUE TITLE
RangeError: Offset is outside the bounds of the DataView

### ISSUE THREAD

**Issue by yaozzzhao** [keeweb/keeweb#894]
- what were your actions?
          I use MacOS as my primary workstation and have installed the latest keeweb client. Today I switched to my secondary workstation(WIN7 Pro x64) and updated the keeweb client to the latest version and tried to open the database, the error occurs. My database file is on google cloud.
- what was wrong?
- app version 
          latest
- your user-agent (from Settings/Help section)
- does it happen on Demo or New database?
          No
- if you are using a test db without your personal data, please attach it
- please, open dev tools in your browser and attach output log from Console tab 
    (if you are using desktop app, devtools can be opened from Settings/General/Advanced)

index.html:1 2018-03-29T01:45:51.342Z [open-view] Error opening file RangeError: Offset is outside the bounds of the DataView
    at DataView.getUint32 (<anonymous>)
    at BinaryStream.(anonymous function) [as getUint32] (file:///E:/Program%20Files/KeeWeb/resources/app.asar/index.html:1:325279)
    at m._readSignature (file:///E:/Program%20Files/KeeWeb/resources/app.asar/index.html:1:348874)
    at Function.m.read (file:///E:/Program%20Files/KeeWeb/resources/app.asar/index.html:1:356254)
    at file:///E:/Program%20Files/KeeWeb/resources/app.asar/index.html:1:369752
    at <anonymous>

**Comment by antelle** [comment]
Hi! Please attach logs. I guess, the file was empty, this is the only reason it can fail here.

**Comment by antelle** [comment]
I've added a better error message for this here: https://github.com/keeweb/kdbxweb/commit/fb5955a8d017a19ba2c1bf95c6b38aad63a5ec34, next versions will report such cases as `not enough data`.
