### ISSUE TITLE
Password generation panel unclickable on List table view

### ISSUE THREAD

**Issue by kkoubat** [keeweb/keeweb#895]
OS: Arch Linux 
DE: Xfce4
AUR package: https://aur.archlinux.org/packages/keeweb-desktop

In list table view mode, the password generation panel exceed desktop screen (to bottom), make it unable to create new password unless exit List Table View mode.
Standard view mode can but it displays username too small (or to be exact, it's unreadable), and switching between two mode view when creating new entry / password is too inconvenient
![screenshot_2018-03-29_23-03-00](https://user-images.githubusercontent.com/24636690/38099957-2399c2da-33a6-11e8-9acf-aa429530ec45.png)

**Comment by dploeger** [comment]
@kkoubat Could you please post a larger screen shot and your desktop resolution? I can only reproduce that, if I drag the horizontal bar between the list and entry views down, so that the panel hits the bottom.

**Comment by dploeger** [comment]
@antelle Maybe we can close this one with cannot-reproduce?

**Comment by antelle** [comment]
I can reproduce it, however it's a bit edge case:
<img width="913" alt="screen shot 2019-01-04 at 18 12 18" src="https://user-images.githubusercontent.com/633557/50700966-54eeb600-104c-11e9-9de8-1a69aa7cb529.png">

It should open to the top in this case. But can be a bit complicated to fix, we can move it.
