### ISSUE TITLE
WebAssembly timeout

### ISSUE THREAD

**Issue by tuxether** [keeweb/keeweb#896]
KeeWeb times out on this line when trying to decrypt:

https://github.com/keeweb/keeweb/blob/abd8f6d20a6b61903090c9432063e9498507562b/app/scripts/util/kdbxweb-init.js#L101

The logs I see are the following:

```
[INFO ] 2018-04-01T01:35:29.995Z [open:Passwords] Open file from content loaded from storage
[WARN ] 2018-04-01T01:35:31.017Z [argon2] WebAssembly error timeout
[ERROR] 2018-04-01T01:35:31.020Z [file] Error opening file undefined s.loadAsmJsFallbackRuntime is not a function TypeError: s.loadAsmJsFallbackRuntime is not a function
[ERROR] 2018-04-01T01:35:31.034Z [open-view] Error opening file TypeError: s.loadAsmJsFallbackRuntime is not a function
[DEBUG] 2018-04-01T01:35:31.547Z [argon2] WebAssembly runtime loaded 1531ms
```

**Comment by antelle** [comment]
Hi,
Your user-agent please.

**Comment by tuxether** [comment]
Chromium, Linux, aarch64, Arch Linux ARM. It works fine on my x86 machine, but the webassembly runtime loads about 3x faster on that machine.

**Comment by antelle** [comment]
I've increased the timeout, but this timing is super weird indeed.

**Comment by tuxether** [comment]
Thanks. Works for me on beta.keeweb.info
