### ISSUE TITLE
Can't access the demo, create a new DB and load plugins

### ISSUE THREAD

**Issue by Peronia** [keeweb/keeweb#902]
Hello,

- what were your actions?
Create a new database with keeweb, open webdav DB, plugins can't loaded

- what was wrong?
Nothing happens, demo doesn't work too, webdav can probably a CORS issue, thats yet not clear

- app version
1.6.3 - self hostet

- your user-agent (from Settings/Help section)
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36

- does it happen on Demo or New database?
Both

- if you are using a test db without your personal data, please attach it
[NeueDatenbank.zip](https://github.com/keeweb/keeweb/files/1901372/NeueDatenbank.zip)
PW: test
This is the webdav DB

- please, open dev tools in your browser and attach output log from Console tab 
    (if you are using desktop app, devtools can be opened from Settings/General/Advanced)

Open DBs log:
[Deprecation] Use of the Application Cache is deprecated on insecure origins. Support will be removed in the future. You should consider switching your application to a secure origin, such as HTTPS. See https://goo.gl/rStTGz for more details.
/keeweb/:1 Document was loaded from Application Cache with manifest http://finnex.indus.uberspace.de/keeweb/manifest.appcache
/keeweb/:1 Application Cache Checking event
/keeweb/:1 Application Cache NoUpdate event
(index):1 2018-04-12T04:41:29.049Z [app] Started in 22365ms ¯\_(ツ)_/¯
(index):1 [Deprecation] Use of the Application Cache is deprecated on insecure origins. Support will be removed in the future. You should consider switching your application to a secure origin, such as HTTPS. See https://goo.gl/rStTGz for more details.
checkAppCacheUpdateReady @ (index):1
init @ (index):1
F @ (index):1
Promise.then (async)
(anonymous) @ (index):1
j @ (index):1
k @ (index):1
setTimeout (async)
(anonymous) @ (index):1
i @ (index):1
fireWith @ (index):1
fire @ (index):1
i @ (index):1
fireWith @ (index):1
ready @ (index):1
R @ (index):1
(index):1 This page includes a password or credit card input in a non-secure context. A warning has been added to the URL bar. For more information, see https://goo.gl/zmWq3m.
pageModifier.js:113 check for duplicates: insertTimeout
(index):1 Uncaught KdbxError {name: "KdbxError", code: "NotImplemented", message: "Error NotImplemented: Random not implemented"}
random @ (index):1
getBytes @ (index):1
KdbxUuid.random @ (index):1
l.create @ (index):1
y.createDefaultGroup @ (index):1
y.create @ (index):1
create @ (index):1
createNewFile @ (index):1
createNew @ (index):1
dispatch @ (index):1
q.handle @ (index):1
(index):1 Uncaught (in promise) KdbxError {name: "KdbxError", code: "NotImplemented", message: "Error NotImplemented: Random not implemented"}
Promise.then (async)
l @ (index):1
create @ (index):1
createNewFile @ (index):1
createNew @ (index):1
dispatch @ (index):1
q.handle @ (index):1
pageModifier.js:113 check for duplicates: insertTimeout
pageModifier.js:113 check for duplicates: insertTimeout
pageModifier.js:113 check for duplicates: insertTimeout
pageModifier.js:113 check for duplicates: insertTimeout
pageModifier.js:113 check for duplicates: insertTimeout
pageModifier.js:113 check for duplicates: insertTimeout

Plugin log:
[Deprecation] Use of the Application Cache is deprecated on insecure origins. Support will be removed in the future. You should consider switching your application to a secure origin, such as HTTPS. See https://goo.gl/rStTGz for more details.
/keeweb/:1 Document was loaded from Application Cache with manifest http://finnex.indus.uberspace.de/keeweb/manifest.appcache
/keeweb/:1 Application Cache Checking event
/keeweb/:1 Application Cache NoUpdate event
(index):1 2018-04-12T05:10:00.960Z [app] Started in 2549ms ¯\_(ツ)_/¯
(index):1 [Deprecation] Use of the Application Cache is deprecated on insecure origins. Support will be removed in the future. You should consider switching your application to a secure origin, such as HTTPS. See https://goo.gl/rStTGz for more details.
checkAppCacheUpdateReady @ (index):1
init @ (index):1
F @ (index):1
Promise.then (async)
(anonymous) @ (index):1
j @ (index):1
k @ (index):1
setTimeout (async)
(anonymous) @ (index):1
i @ (index):1
fireWith @ (index):1
fire @ (index):1
i @ (index):1
fireWith @ (index):1
ready @ (index):1
R @ (index):1
(index):1 This page includes a password or credit card input in a non-secure context. A warning has been added to the URL bar. For more information, see https://goo.gl/zmWq3m.
pageModifier.js:113 check for duplicates: insertTimeout
pageModifier.js:113 check for duplicates: insertTimeout
pageModifier.js:113 check for duplicates: insertTimeout
(index):1 2018-04-12T05:10:10.906Z [plugin-gallery] Loading plugins...
(index):1 2018-04-12T05:10:11.228Z [signature-verifier] Signature key verification error TypeError: Cannot read property 'importKey' of undefined
    at (index):1
    at new Promise (<anonymous>)
    at Object.verify ((index):1)
    at Object.verifySignature ((index):1)
    at (index):1
a.error @ (index):1
(anonymous) @ (index):1
verify @ (index):1
verifySignature @ (index):1
(anonymous) @ (index):1
Promise.then (async)
loadPlugins @ (index):1
loadPluginGalleryClick @ (index):1
dispatch @ (index):1
q.handle @ (index):1
(index):1 2018-04-12T05:10:11.233Z [plugin-gallery] Error verifying plugins signature undefined
a.error @ (index):1
(anonymous) @ (index):1
Promise.catch (async)
verifySignature @ (index):1
(anonymous) @ (index):1
Promise.then (async)
loadPlugins @ (index):1
loadPluginGalleryClick @ (index):1
dispatch @ (index):1
q.handle @ (index):1
pageModifier.js:113 check for duplicates: insertTimeout

I know the insecure of HTTP. I switch to HTTPS when all works fine.

**Comment by antelle** [comment]
Hi! Yes this is because of HTTP, not HTTPS. Next version will explicitly refuse to work if launched via HTTP.
