### ISSUE TITLE
[Question]Can't load config "[app] Error starting app Loading config from this location is not allowed"

### ISSUE THREAD

**Issue by Peronia** [keeweb/keeweb#903]
Hi,
I start keeweb with this URL: https://keeweb.myhost.com/?config=https://otherfolder.myhost.com

The dev console says: [app] Error starting app Loading config from this location is not allowed

I've tried to fill in the path, e.g. ~/html/protected/config.json in the config URL parameter, that raise the same issue.

Where can I place the config? Google doesn't help me.

When I fill the kw-config tag in the index.html, keeweb ignore the config file completly.

**Comment by antelle** [comment]
Hi!
It must be located on the same domain as keeweb.
