### ISSUE TITLE
Local .kdbx?

### ISSUE THREAD

**Issue by DocMAX** [keeweb/keeweb#907]
Can you please add the option to load a local kdbx? (The kdbx file resides on the same server keeweb is running)

**Comment by antelle** [comment]
Hi! You can setup a webdav on your server and host your kdbx there, it will work as local kdbx. We don't have server software in keeweb (and there are no plans to implement it).

**Comment by DocMAX** [comment]
Yes i tried this way, but i get "Error: network error". Where can i get details to debug this? (On other systems, same WebDAV adress is working fine)

**Comment by antelle** [comment]
You can try inspecting Network panel in browser devtools
