### ISSUE TITLE
KDBX file from Google Drive

### ISSUE THREAD

**Issue by SebP7669** [keeweb/keeweb#909]
Hi all,
I can't open a kdbx file from Google Drive anymore.

The login popup tells me about a cookie issue... but I can't do anything to change my cookie settings inside Keeweb desktop.
It used to work fine a few weeks ago, then I switched to a Nextcloud hosting, and came back to Goole Drive.

Thanks for your help
Seb.

![keeweb_gdrive](https://user-images.githubusercontent.com/33777208/39167718-ed7f1f20-4790-11e8-89ac-7888bfe3c00e.jpg)
![keeweb_gdrive_en](https://user-images.githubusercontent.com/33777208/39167720-edc34f42-4790-11e8-956b-442de33a7c3b.jpg)

---
KeeWeb v1.6.3 (cded8a4, 2017-12-11)
Environment: electron v1.7.9
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) KeeWeb/1.6.3 Chrome/58.0.3029.110 Electron/1.7.9 Safari/537.36

**Comment by antelle** [comment]
Hi! This is the Cookie issue: #810

**Comment by SebP7669** [comment]
Excellent ! Thanks very much.

**Comment by borgogelli** [comment]
+1
