### ISSUE TITLE
Keeweb self-host webpage

### ISSUE THREAD

**Issue by minhuy58** [keeweb/keeweb#912]
Hello,

I downloaded the self-hosted web page app from your github, trying to setup open from GDrive and Onedrive. During the microsoft app registration, it ask for redirect uri. It does not matter what I type in the redirect URI, the Onedrive login still say incorrect redirect URI from the pop up window. 

Note: I edited the code from your index file, added App ID to the code, exactly like your instruction in one ticket before. Please help me. Can you screen capture the part of your Redirect URI setup in Microsoft App registration panel?

**Comment by antelle** [comment]
Hi! Redirect URI is the same where you access your KeeWeb in browser, i.e. your server URL. For app.keeweb.info it's this:
![redirect](https://user-images.githubusercontent.com/633557/39374557-795c413c-4a4b-11e8-86a8-33ce5dbd2e8e.png)

**Comment by minhuy58** [comment]
Thank you for your prompt reply. I did exactly like your screenshot, but could not login. Here is step by step what I did

1/ Edit the code from your index.html, replace "onedriveClientId" by my App ID: "95547926-xxxxxxxxxx-xxxxxx-2242f8a2eb3b" . you can search for my app ID from the keeweb index page on my site.

https://uyit.pro/keeweb/ 

2/ From my Microsoft app registration portal. I added screenshots, so you can see how I setup. 
https://uyit.pro/keeweb/Capture.PNG
https://uyit.pro/keeweb/Capture1.PNG
https://uyit.pro/keeweb/Capture2.PNG

It does not work. Everytime I try to open from Onedrive, after login, there is an error about not match redirect URI. Please help.

Thanks,

**Comment by antelle** [comment]
What happens if you host it without `/keeweb/`, e.g. on a subdomain?

**Comment by minhuy58** [comment]
Here is the error: https://login.live.com/err.srf?lc=1033#error=invalid_request&error_description=The+provided+value+for+the+input+parameter+'redirect_uri'+is+not+valid.+The+expected+value+is+'https://login.live.com/oauth20_desktop.srf'+or+a+URL+which+matches+the+redirect+URI+registered+for+this+client+application..

I never try host it with a subdomain

**Comment by antelle** [comment]
Is there a way to check what was sent as the redirect uri? Maybe we drop the path and send only the domain? What happens if you register your domain in MS, without `/keeweb/`?

**Comment by minhuy58** [comment]
I tried that, same issue. 
From your screenshot, I see you have 3 field to put in the domain, from my screenshot, you as you can see for web platform, there are only 2 fields to put my domain in. Is that something different?

**Comment by minhuy58** [comment]
I like your program so so much. That's why I downloaded to host it by myself. I really hope it will work

**Comment by antelle** [comment]
About my screenshot, I have three fields there for the app itself and beta. Not sure why keeweb.info is there, it shouldn't. Btw, how did you create an app on microsoft, could you please paste a screenshot of what it looks like in the apps list? Maybe it's another app type?

**Comment by minhuy58** [comment]
There are 3 options for app types (or Microsoft call it platform - capture 7), but there is only 1 Web app type has the option to input redirect URI
https://uyit.pro/keeweb/Capture4.PNG
https://uyit.pro/keeweb/Capture5.PNG
https://uyit.pro/keeweb/Capture6.PNG
https://uyit.pro/keeweb/Capture7.PNG
I screenshot all my settings from my app registrtation

**Comment by antelle** [comment]
My app is here, maybe this is the reason?
![app](https://user-images.githubusercontent.com/633557/39382801-127febd2-4a67-11e8-9b2c-b99d8f4e39cc.png)
Maybe you also need Live SDK support in Advanced Options here? https://uyit.pro/keeweb/Capture2.PNG

**Comment by minhuy58** [comment]
I enabled the Live SDK. Tested again, no help. Here is my  Application Manifest. Also with Google, I got same problem, about redirect URI not match. see my screenshot

https://uyit.pro/keeweb/Capture8.PNG

{
    "id": "29574fcf-c748-42e2-884d-67f40ca65df6",
    "addIns": [],
    "allowPublicClient": null,
    "appId": "95547926-8e76-4dcd-bfe5-2242f8a2eb3b",
    "oauth2AllowUrlPathMatching": false,
    "createdDateTime": "2018-04-27T03:51:59Z",
    "identifierUris": [],
    "informationalUrls": {
        "termsOfService": null,
        "privacy": null
    },
    "isDeviceOnlyAuthSupported": null,
    "keyCredentials": [],
    "knownClientApplications": [],
    "logoUrl": null,
    "logoutUrl": "https://uyit.pro/",
    "name": "Keeweb",
    "oauth2AllowIdTokenImplicitFlow": false,
    "oauth2AllowImplicitFlow": true,
    "oauth2Permissions": [],
    "oauth2RequirePostResponse": false,
    "parentalControlSettings": {
        "countriesBlockedForMinors": [],
        "legalAgeGroupRule": "Allow"
    },
    "passwordCredentials": [],
    "preAuthorizedApplications": [],
    "publisherDomain": null,
    "replyUrls": [
        "https://uyit.pro/"
    ],
    "requiredResourceAccess": [
        {
            "resourceAppId": "00000003-0000-0000-c000-000000000000",
            "resourceAccess": [
                {
                    "id": "10465720-29dd-4523-a11a-6a75c743c9d9",
                    "type": "Scope"
                },
                {
                    "id": "df85f4d6-205c-4ac5-a5ea-6bf408dba283",
                    "type": "Scope"
                },
                {
                    "id": "5447fe39-cb82-4c1a-b977-520e67e724eb",
                    "type": "Scope"
                },
                {
                    "id": "5c28f0bf-8a70-41f1-8ab2-9032436ddb65",
                    "type": "Scope"
                },
                {
                    "id": "863451e7-0667-486c-a5d6-d135439485f0",
                    "type": "Scope"
                },
                {
                    "id": "e1fe6dd8-ba31-4d61-89e7-88639da4683d",
                    "type": "Scope"
                },
                {
                    "id": "a154be20-db9c-4678-8ab7-66f6cc099a59",
                    "type": "Scope"
                },
                {
                    "id": "b340eb25-3456-403f-be2f-af7a0d370277",
                    "type": "Scope"
                },
                {
                    "id": "b4e74841-8e56-480b-be8b-910348b18b4c",
                    "type": "Scope"
                },
                {
                    "id": "204e0828-b5ca-4ad8-b9f3-f32a958e7cc4",
                    "type": "Scope"
                },
                {
                    "id": "01d4889c-1287-42c6-ac1f-5d1e02578ef6",
                    "type": "Role"
                },
                {
                    "id": "75359482-378d-4052-8f01-80520e7db3cd",
                    "type": "Role"
                },
                {
                    "id": "df021288-bdef-4463-88db-98f22de89214",
                    "type": "Role"
                },
                {
                    "id": "741f803b-c850-494e-b5df-cde7c675a1ca",
                    "type": "Role"
                }
            ]
        }
    ],
    "samlMetadataUrl": null,
    "signInUrl": null,
    "tags": [
        "appModelVersion:2",
        "accessTokenVersion:1",
        "availableToOtherTenants:true",
        "supportsConvergence:true"
    ],
    "tokenEncryptionKeyId": null
}

**Comment by minhuy58** [comment]
Your index.html file is super hard to read or follow.If you dont mind, can you send me the file you are using on keeweb.info? I just want to double check I replaced correct ""onedriveClientId" and "gDriveClientId". By some how I see people get so much difficult to self host the web version of keyweb app.

**Comment by minhuy58** [comment]
I said it hard to read because when I edit your file by either notepad or notepad++ or view source by browser, all the code show in 1 super long line. Just 1 line. I dont know why. The reason I ask for double check because, here is the code I found from your original file on github
`||this._oauthRevokeToken("https://accounts.google.com/o/oauth2/revoke?token={token}"),i.prototype.setEnabled.call(this,e)},_getOAuthConfig:function(){return{scope:"https://www.googleapis.com/auth/drive",url:"https://accounts.google.com/o/oauth2/v2/auth",clientId:this.appSettings.get("gdriveClientId")||"847548101761-koqkji474gp3i2gn3k5omipbfju7pbt1.apps.googleusercontent.com",width:600,height:400}}});e.exports=new a},function(e,t,n){"use strict";var i=n(17),s={Production:"000000004818ED3A",Local:"0000000044183D18"},a=i.extend({name:"onedrive",enabled:!0,uipos:40,iconSvg:'<svg `

In this code, very next to gDriveClientID, there is a string, look like someone's Google App ID, maybe yours. Do you think it is the reason cause Onedrive and Gdrive problem?

> ("gdriveClientId")||"847548101761-koqkji474gp3i2gn3k5omipbfju7pbt1.apps.googleusercontent.com"

**Comment by minhuy58** [comment]
So, if I replace "gdriveClientID" by my Google App, client ID here: https://uyit.pro/keeweb/Capture8.PNG 
, then next to that || there is another clientID. Confusing. 

Is there something you can double check you did not have any preset value for redirect URI or App ID/Client ID for both OneDrive and GDrive? Cause if the file coded the 100 % the same as the file you are hosting on keeweb.info like you said, it would included your APP/Client ID somewhere already. 

I cannot check the whole script. It is too long, and no spacers, no separate paragraphs, super difficult to read and follow the script. See my screenshot how the source code of index.html file display:

![image](https://user-images.githubusercontent.com/9346215/39387096-589a361a-4a3d-11e8-8205-51b399b59597.png)


![image](https://user-images.githubusercontent.com/9346215/39387125-832ed4b2-4a3d-11e8-9ad8-89c589508df7.png)

**Comment by antelle** [comment]
> all the code show in 1 super long line

Of course it is, it's compiled and not debuggable. You can clone the repos and build a dev version from source, if you would like to debug it. But I guess, in this case you don't need it.

> Do you think it is the reason cause Onedrive and Gdrive problem?

No it is not. If you set it in settings, it will use your client ID.

Oh I think I know the reason. You replaced something in index.html but you shouldn't do this. Instead, could you please create a json config and replace a value there? https://github.com/keeweb/keeweb/wiki/Configuration#json-app-config

**Comment by minhuy58** [comment]
I spent this morning to follow your new direction. However it still did not work. It does not matter I have json file for settings or not. All came the same result, redirect uri does not match the value...

I did move the page and related folders for keeweb web to main path: https://uyit.pro for testing. Surprisingly GDrive work now. I still need to follow Google requirement to get the notice of unverified app disappear, but at least, it works. I can ignore the unverified app notice for now. Microsoft is still, no work at all. Do you have any idea? You can go to my site, and experience by yourself.

**Comment by minhuy58** [comment]
Forgot to ask you this
![image](https://user-images.githubusercontent.com/9346215/39400053-800118c0-4aee-11e8-9067-1776a4269a57.png)
Do we need this setup for the web app? If yes then how did you set it up, I mean all 3 or just 1 of 3 options. After setup, do we need to add or replace a value from the html file script?
Thanks,

**Comment by antelle** [comment]
> It does not matter I have json file for settings or not.

Did you load keeweb app with the normal url or with `index.html?config=...`?
The config won't be read by default, you have to add it to the url.

> Do we need this setup for the web app?

No, we don't need it.

Let's try to create a config and see what happens. When you load the app, open dev console and run this:
```js
kw.settings.get('onedriveClientId')
```
It must return your client ID. If it doesn't, this means default client id will be used.

**Comment by minhuy58** [comment]
Antelle,

![image](https://user-images.githubusercontent.com/9346215/39411304-f80ab964-4bcc-11e8-8181-477f439ce0bc.png)

**Comment by antelle** [comment]
It shows the reason in logs, let’s check them

**Comment by minhuy58** [comment]
Where is the log saved?

**Comment by antelle** [comment]
In browser devtools, console section

**Comment by antelle** [comment]
probably there’s an error in Network tab

**Comment by minhuy58** [comment]
I made it works for me. For who are having same problem as me with redirect URI, please follow my instruction as below
Edit the index.html file
1/ Search for "onedriveClientID", replace it with Microsoft App ID, include all the dashes:
Search for "GDriveClientID", replace it with Google Client ID
2/ Next to the "gdriveClientID" ||, you will see the code like this 
function (e) {el I this. oauthRevokeToken ("https://accounts.google.com/o/oauth2/revoke?token={token}") , i -prototype . setEnab1ed. call (this, e) } , getOAuthConfig:function() {return{scope: "https : / ww"w'. googleapis . com/auth/drive",ur1 : "https : // accounts . google . com/o/oauth2/v2/auth" , clientld: this . appsettings . get ( "gdriveclientld") I I "8475481017 61—koqki i474gp3i2gn3k50mipbfju7pbt1 -apps .googleusercontent . com" , width: 600, height :400} exports=new a} , function (e, t, n) { "use strict" ; var (17) , "000000004 BIBED3A" , Local: "00000000441B3DIB"} , . extend ( {name: "onedrive" , enabled: ! O, uipos:40, iconsvg: '<svg xmlns: svg="http://'www'.w3. org/2000/svg" xmlns="http://w.r.l.w3. org/2000/svg" width="2S6" height="2S6" 0 256 "><g transform="trans1ate(222.B5714,—11. 428576)

The "84754 …. googleusercontent.com" is the App ID of this app author from his/her Google account, need to replace it by your own Google App ID 

The 4818ED3A and 44183D18 are Microsoft app ID of Author as well. We don’t have Local develop account here, so we don’t need it. We will need to delete from: ,Local...D18" (include the comma ","). Then replace the 0000....8ED3A with your Microsoft App ID. 

3/ For the redirect URI in both Google dev console and Microsoft App registration control, you need to type exactly the URI, include the file name: "index.html" or "KeeWeb.html", or anything you can come up with. For example: if your file name index.html, place in a subfolder name abc. Then the uri will be: https://yourmaindomain.com/abc/index.html. If you copy and paste from your browser address bar: https://yourmaindomain.com/abc/, both Google and Microsoft return error not match return URI

**Comment by minhuy58** [comment]
Antelle, it's clearly that from the keeweb web page index.html, you need to clear your own App ID on both Microsoft and Google dev console. Also, from the Google and Microsoft dev console, the URI need to include full file name with extension. I spent a lot of time to feature it out. If you dont mind, please make this issue as your reference resource, tag it for people easier host their own keeweb. 

And... you are welcome. 

Finally, Thank you for your great app. I am your fan.
