### ISSUE TITLE
IOFileCache does not allow storing an object

### ISSUE THREAD

**Issue by leolivier** [keeweb/keeweb#913]
Hi @antelle 
I'm trying to setup a persistent cache for the HIBP plugin and I'm facing an issue for the desktop app.
The IOBrowserCache works but is not persistent across sessions apparently.
So I tried IOCache instead which seems to be usable for both desktop and webb app. It uses IOFileCache for desktop app.
Unfortunately, IOFileCache does not allow storing an object :(
It says `First argument must be a string, Buffer, ArrayBuffer, Array, or array-like object.`
I tried to debug this and found that the implementation of Launcher.writeFile for electron uses 
 ```
       this.req('fs').writeFile(path, new window.Buffer(data), callback);
```
and `new window.Buffer(data)` returns the above error if data is an object... 
For instance, executing in the desktop app console:
```
var obj = { a: "a", b:1, c:[1, 2, 3]};
b = new window.Buffer(obj);

```
results in:
```
Uncaught TypeError: First argument must be a string, Buffer, ArrayBuffer, Array, or array-like object.
    at fromObject (buffer.js:274)
    at Function.Buffer.from (buffer.js:106)
    at new Buffer (buffer.js:85)
    at <anonymous>:1:5
fromObject @ buffer.js:274
Buffer.from @ buffer.js:106
Buffer @ buffer.js:85
(anonymous) @ VM278:1
index.html:1 
```
So maybe the IOFileCache might be changed to "stringify" the data object before storing it ?

**Comment by antelle** [comment]
Hi,
Yes, you're absolutely right, you should use `IoCache` (not the concrete storage directly), it will select a proper cache storage (either FileCache or BrowserCache).
Our storages don't serialize objects, you can do it yourself and pass ArrayBuffer there.
You can also use `require('kdbxweb').ByteUtils.stringToBytes(str)` to convert between strings and ArrayBuffers.
