### ISSUE TITLE
Instruction to use html file with config.json

### ISSUE THREAD

**Issue by minhuy58** [keeweb/keeweb#915]
Hi antelle,

Can you give us a detail instruction for how to use the config file together with web version html file?

I saw there is an instruction here, but it is confusing...
https://github.com/keeweb/keeweb/wiki/Configuration 

`add config url parameter: https://your-keeweb-deployment-url/?config=your-config.json`
--> where to add, how t o add this url parameter?

`set kw-config meta-tag value: replace (no-config) string in app index.html with your config url`
--> this option is still editing the html code, replace the no-config with config url, do you have an example? ok, if I place the config.json file in the same folder of the index.html file, what should I type to replace the (no-config)? is it like this: https://mydomain.com/keeweb.html?config=config.json?

**Comment by antelle** [comment]
Hi!
The URL parameter must be added to you keeweb url. For example, if you access keeweb from `https://example.com/keeweb`, then it will be `https://example.com/keeweb?config=your-config.json`.
Then KeeWeb will try to load config from `your-config.json`.

The second option (editing the html file) is for those who for some reasons can't add url parameters, so keeweb can be loaded with just `https://example.com/keeweb` in this case. You can replace `(no-config)` with the location of your config, e.g. `your-config.json`.
