### ISSUE TITLE
[Feature Request] Keyboard shortcuts for recent files on open dialog

### ISSUE THREAD

**Issue by filipkis** [keeweb/keeweb#919]
Similar to #889 I too often work with two files. However, as I have setting that it automatically locks the DB after few minutes my use case is that often switch to the app and need to unlock the other DB (not the one I used most recently). 

Therefore, it would be nice if on the opening screen, in the list of recently used files is numbered and then I could do CMD+1 (or CTRL+1) for first file, etc.

**Comment by antelle** [comment]
Hi! I believe, #889 and #321 will solve it. I don't think shortcuts for latest files will be useful it we have two these issues solved.

**Comment by filipkis** [comment]
Actually, on careful reading of #889 I realised yes, if the arrows up/down
change active file that would be great. Even better if the focus stayed the
whole time on the password input box.

For #321 I would say it only works on some cases.  I two people using
KeeWeb on the same computer. You wouldn't want to link the files in such
way. Additionally, that feature is much more complicated so who knows when
will be implemented.
