### ISSUE TITLE
Autofill in browser without a desktop app.

### ISSUE THREAD

**Issue by mat-m** [keeweb/keeweb#925]
Hello

I would like to have a workflow which can allow to use Autofill in browser without a desktop app.

I thought about the following workflow to use keeweb by browser extension using KeePassHTTP:
* Connect to app.keeweb.info 
* Load a kdbx file (ideally through webdav)
* Connect this database to the same browser with KeePassHelper

This was the "simplest" IMO because the browser extension already exists and allow for custom urls.

**Comment by antelle** [comment]
Hi! Yes it would be the ideal case. However this must be implemented in the browser extension itself, we can't do it from keeweb.

**Comment by mat-m** [comment]
Oh, I had one supposition that you needed to expose the same methods as KeepassHttp so the browser extensions would not see the difference.

**Comment by antelle** [comment]
You cannot communicate via TCP from a web page. Instead a plugin should access the page using some API, but this has to be implemented inside a plugin.

**Comment by antelle** [comment]
We do have KeePassHttp, but it's available only as a plugin for keeweb-desktop.

**Comment by mat-m** [comment]
They do have, that's my point.

Below is the setting of the browser extension [KeePassHelper](https://github.com/belaviyo/keepass-macpass-helper) based on [KeePassHttp](https://github.com/pfn/keepasshttp) already have a config for URL.:
![image](https://user-images.githubusercontent.com/1039753/39971058-545a7cf8-56f5-11e8-80f2-3e85e3ca6911.png)

The localhost:xxxxx is leading to the mini webserver managed by the KeePassHttp plugin installed in the desktop app. If we could have a app.keeweb.info/xxxx where xxx would be a something ot uniquely identify the opened database, it would be great (something like a  prefix to handle the special API and a token: e.g. app.keeweb.info/expose/ace1d5f12de54)

**Comment by antelle** [comment]
Yes, this is the config that allows you to change the TCP port.
We cannot implement a webserver inside a page, the request will go to the HTTP server (i.e. backend that hosts keeweb), and not to our page opened inside a browser tab.

**Comment by mat-m** [comment]
Ah ok, I understand now :)
