### ISSUE TITLE
OTP code not working and work 30/40 seconds after.

### ISSUE THREAD

**Issue by fapsovidri** [keeweb/keeweb#928]
- what were your actions?
Paste OTP for my entry

- what was wrong?
Code is wrong and work after 30/40 seconds

- app version
v1.6.3

- your user-agent (from Settings/Help section)
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) KeeWeb/1.6.3 Chrome/58.0.3029.110 Electron/1.7.9 Safari/537.36

- does it happen on Demo or New database?
///

- if you are using a test db without your personal data, please attach it
///

- please, open dev tools in your browser and attach output log from Console tab
(nothing to paste, since it's not an error).

Note that this ""bug"" is here since a few weeks and I'm using my DB since a year now.

**Comment by antelle** [comment]
Hi! Could you please elaborate more?
Which service did you try it on, does it work with other services (e.g. Google), what is _work after 30/40 seconds_?

**Comment by fapsovidri** [comment]
Protonmail and Discord for exemple don't work properly using KeeWeb, tried to reinstall OTP using a new code for each but problem persist. It's working for some other website directly but not a lot. I'm talking about the 6 numbers code that work after 30/40 seconds. When it's generated in KeeWeb, the code don't exist for the website and after 30/40 seconds website recognize it and let me connect. 

https://streamable.com/7clg3 video to explain the situation

**Comment by antelle** [comment]
Another question: does it happen every time you're trying to use OTP, or it's from time to time?

**Comment by fapsovidri** [comment]
Yes I'm doing the same as the video. Note that it started to do that since a few weeks and like I told you before in a previous message, I'm using my KeeWeb DB since more than a year and Discord (and OTP) were working since around 7 months before it started to not work properly. 

It's actually doing it on more website and I don't know why. Some website that worked before are now telling me that the code is incorrect at first and accept it 30/40 seconds later. Sometime it's working directly and I don't have any explanation.

For the clock, I have the following:

> Accuracy of synchronization was ±0.054 seconds.

**Comment by fapsovidri** [comment]
Ok, I just fixed it.. My clock was 1 minute ahead never notice that before, thanks you !

**Comment by antelle** [comment]
🙃
