### ISSUE TITLE
Building KeeWeb on Windows

### ISSUE THREAD

**Issue by hAbd0u** [keeweb/keeweb#929]
Hello,
I am compiling KeeWeb on windows, but when runs only a blue dark screen appears with the menu.

**- what were your actions?**
L:\gitrepo>git clone https://github.com/keeweb/keeweb.git
Cloning into 'keeweb'...
remote: Counting objects: 14360, done.
remote: Total 14360 (delta 0), reused 0 (delta 0), pack-reused 14360
Receiving objects: 100% (14360/14360), 8.49 MiB | 240.00 KiB/s, done.
Resolving deltas: 100% (10715/10715), done.

L:\gitrepo>cd keeweb\app
L:\gitrepo\keeweb\app>grunt dev
grunt-cli: The grunt command line interface (v1.2.0)

Fatal error: Unable to find local grunt.

If you're seeing this message, grunt hasn't been installed locally to
your project. For more information about installing and configuring grunt,
please see the Getting Started guide:

http://gruntjs.com/getting-started

L:\gitrepo\keeweb\app>npm run-script electron

> keeweb@1.6.3 electron L:\gitrepo\keeweb
> electron desktop --htmlpath=http://localhost:8085/tmp/

**- what was wrong?**
The app starts but only a dark blue screen.

**- app version**
Latest git repo.

![build keeweb](https://user-images.githubusercontent.com/6846543/40289692-b2e69ab2-5c6e-11e8-88f8-8f6c8b2d9b81.jpg)

**Comment by antelle** [comment]
It looks like, you forgot to run `npm install` before running `grunt`.

**Comment by hAbd0u** [comment]
After typing 'npm install' and then 'grunt dev' it shows some errors, I included the full output in attachment.
Is it necessary to compile it from source in order to build my plugin?
[Uploading grunt-dev.txt…]()

**Comment by antelle** [comment]
I can't download your file.

**Comment by hAbd0u** [comment]
@antelle Here is a link even I upload it here as an attachment.
https://drive.google.com/open?id=1uCfNAWFTvhMOuKhL8ynli9vUSige7NWW

**Comment by antelle** [comment]
>  even I upload it here as an attachment.

Try to download your attachment from here ;) 
Now I see, this is the filesaver thing, it's fixed in `develop` branch. If you check it out, it should work.

**Comment by hAbd0u** [comment]
@antelle  I switched to develop branch now but unfortunately still having errors.
https://drive.google.com/open?id=1u8pBXan_aKy_2MG3qUJovzMyfKdr-Z6R

**Comment by antelle** [comment]
It's something new, I just tried and it didn't happen for me. Let's try this:
```
git clone git@github.com:keeweb/keeweb.git -b develop && cd keeweb && npm i && npm run dev
```
– this works for me.

**Comment by antelle** [comment]
If it doesn't work, please capture logs and output of `npm -v && node -v`

**Comment by hAbd0u** [comment]
Another error now:
`L:\gitrepo>git clone git@github.com:keeweb/keeweb.git -b develop && cd keeweb && npm i && npm run dev`
Cloning into 'keeweb'...
The authenticity of host 'github.com (192.30.253.113)' can't be established.
RSA key fingerprint is SHA256:nThbg6kXUpJWGl7E1IGOCspRomTxdCARLviKw6E5SY8.
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added 'github.com,192.30.253.113' (RSA) to the list of known hosts.
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by antelle** [comment]
You can clone as http if ssh doesn't work.

**Comment by hAbd0u** [comment]
This the output I got:
https://drive.google.com/file/d/1mSll8l3jNoF7PD_da-VKKPlnOP0pUpc4/view?usp=sharing
https://drive.google.com/file/d/1D0iXYC1uOYKSjfPFGOVWAj-xq8sx2kpA/view?usp=sharing

```
L:\gitrepo\keeweb>npm -v && node -v
3.10.10
v6.10.3
```

**Comment by hAbd0u** [comment]
@antelle Can you tell me which node and npm version you are working on?

**Comment by antelle** [comment]
node v10.1.0, npm v5.6.0, macOS 10.13.4

**Comment by hAbd0u** [comment]
I downgraded the **npm** version, it seems the latest version have some issues
`npm i -g npm@5.6.0`
Also I have to install **keytar** package.
`npm install keytar`
Now running `grunt dev `gives me this warring:

> Running "sign-html:app" (sign-html) task
> Warning: Error signing app html. To build without sign, please launch grunt with --skip-sign. Use --force to continue.
> 
> Aborted due to warnings.

**Comment by antelle** [comment]
Right, signing is possible only if you generate a key, that's why it's started with `--skip-sign` if you run `npm run dev`. It should work, is the server running while you launch electron?

**Comment by hAbd0u** [comment]
@antelle No, the server is not running, should it be?

**Comment by antelle** [comment]
Yes, in devmode the app content is loaded from it.

**Comment by hAbd0u** [comment]
@antelle Now it works, but how about signing the plugins?

**Comment by antelle** [comment]
Plugins are separate thing. Here's a description how to create a plugin, this tool includes a built-in server to test it: https://github.com/keeweb/keeweb/wiki/Plugins
But I don't quite understand what you're trying to solve. For developing plugins you don't need dev-keeweb, and vice versa.

**Comment by yakiang** [comment]
> Right, signing is possible only if you generate a key, that's why it's started with `--skip-sign` if you run `npm run dev`.
> It should work now, is the server running while you launch electron?

I'm newbee to grunt and webpack, but do I run the server?
