### ISSUE TITLE
Not able to login keeweb with Google Drive anymore

### ISSUE THREAD

**Issue by gynet** [keeweb/keeweb#930]
I am using Windows 10 with latest keeweb. 

It shows error: 

"
We've detected a problem with your cookie settings.

Enable cookies
Make sure your cookies are enabled. To enable cookies, follow these browser-specific instructions.

Clear cache and cookies
If you have cookies enabled but are still having trouble, clear your browser's cache and cookies.

Adjust your privacy settings
If clearing your cache and cookies doesn't resolve the problem, try adjusting your browser's privacy settings. If your settings are on high, manually add www.google.com to your list of allowed sites. Learn more"

**Comment by antelle** [comment]
Duplicates #810

**Comment by borgogelli** [comment]
+1
