### ISSUE TITLE
Feature Request: default file open and enabled user

### ISSUE THREAD

**Issue by blademckain** [keeweb/keeweb#932]
Hi all,
thanks for your work

I request 2 feature:
First Simple Request: be able to indicate a local file to be opened automatically at startup.
For example in the web version, when you visit the web page automatically opens a file (which must be in the same folder as the program) (obviously he will ask them for the master password)

Second Feature: 
Enter the possibility to create users, which after logging in automatically will open the file associated with them (files must reside in the same folder as the program) (obviously he will ask them for the master password)
or as an alternative the possibility to specify variables inside the file config
example:
 "files": [{ 
    "storage": "webdav"
    "name": "%username%",
    "path": "%path%",
    "options": { "%username%": "", "%password%": "" } 
  }],
and the url will become https://your-keeweb-deployment-url/?config=your-config.json&username=myuser&path=mypath&password=mypass

**Comment by antelle** [comment]
Hi!
It looks like your suggesting is about server software for KeeWeb. At the moment we don't have it (and don't plan to do it), so feel free to implement this. You will need to:
for (1.): get a file you would like to open and build a config with it; inject the config to keeweb
for (2.): the same, with users
I would like to warn about putting passwords it URLs: URLs saved to history, shared with public services and can be easily stolen this way; it's better not to do that.
