### ISSUE TITLE
Align the icons on the start page in one line if most of the icons are disabled

### ISSUE THREAD

**Issue by tobiaskarch** [keeweb/keeweb#934]
I have a self-hosted KeeWeb instance where I have disabled most options/icons. So I only have the icons "Open", "New", "More", "Google Drive" and "Settings". "Open", "New" and "More" are on the first line and the other two are on the bottom and are not visible at first. To see them, I have to click on "More".

Up to a certain number of icons, the "More" icon is unnecessary and the remaining activated icons (in my case four) can be displayed in one line.

This is nothing serious, but a great enhancement.

![](https://user-images.githubusercontent.com/22427880/40492504-ea6a8a20-5f70-11e8-97ad-457e58796112.gif)

**Comment by antelle** [comment]
Hi! This would be nice indeed, duplicates #690
