### ISSUE TITLE
App doesent save pah to file on Flash Drive 

### ISSUE THREAD

**Issue by GamerClassN7** [keeweb/keeweb#939]
if i set up flash drive with app an DB every time i plug flashdrive to same PC i need to setup db path ol over again! is there any solution ? how to write pat in some format like ./ ?

**Comment by GamerClassN7** [comment]
yes if i insert flash drive to different computer i need to map database file again

**Comment by antelle** [comment]
Does its path remain the same, of the drive is mapped to a different location?
