### ISSUE TITLE
WebDav IIS 8.5 network error

### ISSUE THREAD

**Issue by carving85** [keeweb/keeweb#940]
I have configured the webdav server on iis.

When I go to the site, the kdbx file is downloaded.
File : http://xxx/test.kdbx
But on keeweb as I enter the address I get an error.
"Error: network error"

What may be the problem?

[DEBUG] 2018-06-06T10:05:35.358Z [storage-webdav] Stat http://keepass.sixin.ml/test.kdbx
[DEBUG] 2018-06-06T10:05:35.360Z [storage-webdav] Stat error http://keepass.sixin.ml/test.kdbx 2ms

**Comment by carving85** [comment]
Well when I use https it works.

But I have another problem that does not work on firefox

There is a "Error: network erro" error

**Comment by antelle** [comment]
Hi! You cannot host it on HTTP, right. Next version will explicitly refuse to work on HTTP.
So, what do you see in Firefox?

**Comment by antelle** [comment]
I believe, this is fixed now, as you said earlier. Please reopen if it repeats.
