### ISSUE TITLE
Feature request: shortcut to bring up KeeWeb from background

### ISSUE THREAD

**Issue by tbradsha** [keeweb/keeweb#944]
First off, KeeWeb is great! Thanks for your hard work to make a polished product that just works.

Often I have places where I need to look up a password or username without using it directly. It would be nice to have a shortcut to bring KeeWeb forward so I can search for an entry and get the information I need, as well as a shortcut to hide it when I'm done.

**Comment by antelle** [comment]
Hi! I think you can create it with tools built into your OS. E.g. create a shortcut to open an app, and then hide it with a shortcut that hides apps/windows.

**Comment by tbradsha** [comment]
On my Mac, I use Cmd-H and Cmd-Tab with no problem. With Windows, it takes taskbar space if I just minimize it, so I have it minimize to the tray, and Alt-F4 seems to work fine to close it. However, a shortcut to open the app results in a new instance each time it's opened rather than unminimizing the existing instance.

**Comment by tbradsha** [comment]
It looks like the extra instance is addressed in #807 :^) I still think it'd be nice to have a shortcut to bring up the app, but you can close this if you prefer, as there are more important things to focus on.

**Comment by antelle** [comment]
I see, then it can be helpful yeah. It's kinda related to this issue, yeah.

**Comment by antelle** [comment]
This will be fixed in the next release, duplicates #565
