### ISSUE TITLE
Navigation in version history impeded by long comment

### ISSUE THREAD

**Issue by Eniki** [keeweb/keeweb#945]
- Put a REALLY long (> 200 chars) text in the "Notes" section (or is it "Comment" in the english version?) of an entry.
- Create several versions of this entry, some with a time stamp very long ago (> 1 year)
- go to the version history and navigate back (left) to the oldest version
==> the arrow right and buttons "restore this version" "delete this version" have moved off the panel to the right. Hence no navigation back to a more recent version is possible (except stepping out and back in to this entry) 
The problem would be avaioded if the Comment was also displayed with lines wrapped like in the normal display.
Long text in the comment field IMO should not be considered a corner case.
-------------
KeeWeb v1.6.3 (cded8a4, 2017-12-11)
Environment: electron v1.7.9
User-Agent: Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) KeeWeb/1.6.3 Chrome/58.0.3029.110 Electron/1.7.9 Safari/537.36

**Comment by Coises** [comment]
It's not just the comment field. None of the field values wrap or (in the case of Website) show ellipses; instead, they push the details__history container width beyond the edge of the window, moving some navigation elements out of view.  Adding `max-width: 100%;` to the `details__history` style in `_details.scss` fixes that, but something else is still wrong: If you reduce the height of the window enough to make the history entry scroll, there is some ugly overlapping between the data fields and the control information at the top, which also leads to the navigation controls being inoperable.

I'll see if I can figure out what it needs.
