### ISSUE TITLE
Two factor authentication with google drive not working

### ISSUE THREAD

**Issue by mduft** [keeweb/keeweb#947]
Thanks for taking the time to contribute!

Please, read https://github.com/keeweb/keeweb/wiki/FAQ before submitting a new issue and fill in the following (if applicable):

- what were your actions?
I enabled two factor auth with my google account
- what was wrong?
From there on, when logging in in KeeWeb to my google account (after entering password and confirming on my phone), the popup window shows "We've detected a problem with your cookie settings." and authentication is not successfully applied.
- app version
1.6.3 (desktop)
- your user-agent (from Settings/Help section)
KeeWeb v1.6.3 (cded8a4, 2017-12-11)
Environment: electron v1.7.9
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) KeeWeb/1.6.3 Chrome/58.0.3029.110 Electron/1.7.9 Safari/537.36
- does it happen on Demo or New database?
existing DB from gdrive
- if you are using a test db without your personal data, please attach it
- please, open dev tools in your browser and attach output log from Console tab 
    (if you are using desktop app, devtools can be opened from Settings/General/Advanced)
logs from the application:
[INFO ] 2018-06-22T19:06:10.958Z [transport] GET https://app.keeweb.info/manifest.appcache
[INFO ] 2018-06-22T19:06:10.984Z [transport] Request to https://app.keeweb.info/manifest.appcache without proxy
[INFO ] 2018-06-22T19:06:11.905Z [transport] Response from https://app.keeweb.info/manifest.appcache: 200
[INFO ] 2018-06-22T19:06:11.912Z [updater] Update check: # 2017-12-11:v1.6.3
[INFO ] 2018-06-22T19:06:11.926Z [updater] Next update check will happen in 86400s
[INFO ] 2018-06-22T19:07:06.221Z [sync:Passwords] Sync started gdrive 0B05h8C3gLt38UDZVNTRJWkZEdTQ {}
[INFO ] 2018-06-22T19:07:06.224Z [sync:Passwords] Stat file
[DEBUG] 2018-06-22T19:07:06.225Z [storage-gdrive] OAuth: popup opened
[ERROR] 2018-06-22T19:07:39.547Z [storage-gdrive] OAuth error popup closed
[INFO ] 2018-06-22T19:07:39.547Z [sync:Passwords] Stat error, not dirty OAuth: popup closed
[INFO ] 2018-06-22T19:07:39.547Z [sync:Passwords] Sync finished OAuth: popup closed

**Comment by antelle** [comment]
Hi! It's #810, cookie problem with Google, will be fixed in the next release.

**Comment by mduft** [comment]
Thanks, thats it. Removing %APPDATA%\Roaming\KeeWeb solved it for my Windows box. I guess I will try the same on my Linux at work on Monday :)

**Comment by antelle** [comment]
It will work as a temp workaround yeah, then the issue will appear again after some time.

**Comment by mduft** [comment]
OK, well, at least there /is/ a workaround :) thanks for this amazing app :)

**Comment by dzek69** [comment]
@antelle any ETA on next release? #810 doesn't say anything about it. I keep returing back to it for workaround (using KeeWeb on several computers, losing a session happens each 2-4 weeks)

**Comment by borgogelli** [comment]
+1
