### ISSUE TITLE
2FA support

### ISSUE THREAD

**Issue by emmnx** [keeweb/keeweb#955]
Please include support for Time-based One-time Password Algorithm.

Currently I store the 2FA key in KeeWeb, but I need to import that key onto a tool like this one: https://gauth.apps.gbraad.nl/  to get the one-time password, and only then I can login to the service in question. It's an extra step that I don't see as necessary, since it can be easily implemented on KeeWeb.

Thanks in advance.

**Comment by Eraac** [comment]
@emmnx it's actually supported https://github.com/keeweb/keeweb/issues/747

<img width="192" alt="capture d ecran 2018-07-06 a 12 55 48" src="https://user-images.githubusercontent.com/5497623/42375501-05a5e7d6-811c-11e8-882d-ab8bf846381a.png">
