### ISSUE TITLE
Undo accidental change

### ISSUE THREAD

**Issue by Krinkle** [keeweb/keeweb#957]
What were your actions?

Creating an entry, generating a new password, selecting it to copy it for the first time.
Then switching to a browser and pasting it. A few minutes later coming back to the
KeeWeb app (unintentionally) and immediately typed two characters and press tab.

What went wrong?

The stored password was replaced with my unintentional input. It seemed that no amount of pressing cmd-Z or Undo had the desired effect of undoing the change.

It also seems there was no version history, despite "Automatic save and sync" being enabled. I didn't realise until now, but I understand now this only triggers when closing the application.

An easy way to reproduce the basic principle:

* Create or edit an entry and add a new field, e.g. "Note". Enter text "important text" and then select it and replace by typing "123", and press cmd-Z/Undo - this brings back "important text", despite not being save as a version.
* Now, select the Notes text again, replacing it by typing "456" and press tab, then immediately go back and try Undo – no effect, the value was permanently lost?

I can see how this might be an intentional decision for security (to not indefinitely store previously entered text in app memory), but perhaps we can find a compromise that is as secure as today, but a little bit more tolerant to human error?

App version and user-agent:
```
KeeWeb v1.6.3 (cded8a4, 2017-12-11)
Environment: electron v1.7.9
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_5) AppleWebKit/537.36 (KHTML, like Gecko) KeeWeb/1.6.3 Chrome/58.0.3029.110 Electron/1.7.9 Safari/537.36
```

**Comment by antelle** [comment]
Hi!
Basically all more or less important changes should be saved in entry history or backups.
The decision to avoid undo was made because of complexity of the undo operation, not because of security. With distributed sync it would cost quite a lot of efforts to implement.
So, let's be honest, it won't be implemented, but if someone feels he or she has a spare month to contribute, I can help reviewing the changes and describing where to start.
(Leaving the issue open to be able to refer to it)

**Comment by Krinkle** [comment]
> Basically all more or less important changes should be saved in entry history or backups.

Do you mean the application is intended to do this, but isn't. Or do you mean, that users should "Settings>kdbx>Save" after each important change?

**Comment by Krinkle** [comment]
@antelle Thanks for the quick response, appreciate it. I mainly wanted to better understand how it is meant to work, and what your recommendation is for users to avoid this.

I understand (some of) the complexity involved and agree it probably isn't worth prioritising to make work for this purpose.

> Basically all more or less important changes should be saved in entry history or backups.

Do you mean the application is intended to do this automatically (but isn't). Or do you mean, that users should "Settings>kdbx>Save" after each important change?

**Comment by antelle** [comment]
> users should "Settings>kdbx>Save" after each important change

Save can also happen automatically. The problem is, we can't create a history entry every time an entry is edited. Maybe we should additionally do it, e.g. after x minutes since last edit or something like this. This is actually the case that is ideally described by your issue, where we can't save to history, but having undo would be super handy.

**Comment by Krinkle** [comment]
@antelle I didn't know there were automatic saves aside from when closing the application.

From a quick glance at the code I found three cases of automatic saving:

1. When exiting the app (beforeUnload) / settings.get.autoSave / saveAndLock
2. When locking the app (lockWorkspace) / hasUnsavedFiles / settings.get.autoSave / saveAndLock
3. Every Timeouts.AutoSync interval (syncAllByTimer)

This third one sounds interesting. I didn't know that existed. If I see correctly, it is currently set to an interval of 30 minutes. Is that right?

The second one (on lock) is a feature I don't currently use, as I close the application instead. However, I did find in the settings that locking can be triggered automatically upon various actions (a configurable timer, when minimising the application, when copying a password).

I assume that these automatic locks also trigger the automatic save. Which means enabling Auto Lock for "on copy password" and/or on a 5 min timer, would have prevented the problem in my original scenario.

**Comment by Coises** [comment]
Would it make sense to trigger an auto-save when the app loses focus and there are unsaved changes?  That would have solved the problem from the original post... but would it create too many spurious history entries?

**Comment by antelle** [comment]
I'm not sure about that. Maybe yes, with some throttling.

**Comment by Krinkle** [comment]
I don't recall having updated the app recently, but it seems to be working much better in this regard as of this week.

1. Whenever I navigate away from the app, it appears to automatically lock (and presumably save). Previously, it didn't auto-lock for me. It's great now.
2. I'm now using the feature of pressing the label to auto-copy, which is **amazing**. This means I never make it visible on the screen (nice security wise), and (more important for me) it avoids any risk of accidentally losing a password when typing "c" instead of "cmd+c". I can't tell you how often I lost a password because of this. In no small part due to commonly used keys on Apple laptop keyboards inevitably ceasing to work reliably after 6-12 months of use. Which, together with Undo not working sometimes, made it a problem without clear recovery.

I'll close this for now. The only thing I'd maybe suggest is to make the (safe) "copy to clipboard" feature more discoverable in some way. I'm quite a fan of KeeWeb's minimal interface, so this is difficult to solve. But, on the other hand, a feature doesn't really count if users don't know about its existence, so there's that.
