### ISSUE TITLE
Implement Web App Manifest

### ISSUE THREAD

**Issue by carlbennett** [keeweb/keeweb#958]
A Web App Manifest with proper icons specified would allow mobile users to pin the KeeWeb app from their web browser to their home screen without seeing the ugly white borders on the home icon.

https://developers.google.com/web/fundamentals/web-app-manifest/

KeeWeb v1.6.3 (cded8a4, 2017-12-11)
Environment: web
User-Agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.183 Safari/537.36 Vivaldi/1.96.1147.52

**Comment by antelle** [comment]
Hi! Next version will have it, it's in development already.
