### ISSUE TITLE
Feature Request: Add a keyboard shortcut to Copy OTP in background

### ISSUE THREAD

**Issue by cdsimpkins** [keeweb/keeweb#963]
Just a minor inconvenience gripe.  

When using accounts that have an OTP field, I have to come back to the app to get the OTP, but I use the background copy/paste shortcuts for user/pass.  Can you add a similar shortcut for the OTP field?  

Thanks!

**Comment by tbradsha** [comment]
This would be great!

**Comment by tbradsha** [comment]
If this gets added, can you add a OTP shortcode to the account selection popup as well?

**Comment by antelle** [comment]
The bot was misconfigured, sorry for a wrong notification.

**Comment by tbradsha** [comment]
Great! Just waiting for v1.11 to come out to test it!

**Comment by antelle** [comment]
@tbradsha v1.11 is released

**Comment by antelle** [comment]
So now, when we have configurable shortcuts, it will be possible to enable it, however it will be disabled by default.
