### ISSUE TITLE
Webdav IIS (anonymous OK, Basic Auth NOK)

### ISSUE THREAD

**Issue by C-Bam** [keeweb/keeweb#964]
Hi,

I'm trying to set Keeweb with Webdav.

I followed the wiki and have this web.config

<?xml version="1.0" encoding="UTF-8"?>
<configuration>
<system.webServer>
  <httpProtocol>
    <customHeaders>
      <add name="Access-Control-Allow-Origin" value="*" />
      <add name="Access-Control-Allow-Methods" value="GET, HEAD, POST, PUT, OPTIONS, MOVE, DELETE, COPY, LOCK, UNLOCK" />
      <add name="Access-Control-Allow-Headers" value="origin, content-type, cache-control, accept, authorization, if-match, destination, overwrite" />
	  <add name="Access-Control-Expose-Headers" value="ETag" />
	  <add name="Access-Control-Allow-Credentials" value="true" />
    </customHeaders>
  </httpProtocol>
</system.webServer>
</configuration>

When I use Anonymous access, it works fine in read mode but I can't save the file (This is a IIS7+ limitation for security purpose)

However, when I set Basic Authentication, it works ok if I go to http://localhost/webdav (It asks for some credential and accept them) but I have "network error" on Keeweb. So I wonder what I've been doing wrong.

Thanks for your help.

**Comment by antelle** [comment]
Hi,
I guess, it's because of http, you need to host it on https.
