### ISSUE TITLE
Restore the previous clipboard value after a copy

### ISSUE THREAD

**Issue by matheod** [keeweb/keeweb#972]
We can currently delete the value in clipboard after a delay.
It would be good if we could also just revert to what it was before.

Might be carreful to handle the case where we double click the label.

**Comment by antelle** [comment]
Hi,
I'm not sure about this, do you know if any other apps revert the clipboard after they clear it?

**Comment by antelle** [comment]
So I've tested several apps, and haven't found anything with such behavior.
I assume, it would be quite unnatural, when the clipboard restores old content by itself.

**Comment by matheod** [comment]
I also tested multiple apps and to my surprise they also don't do it.
