### ISSUE TITLE
[Feature Request] Name the password field

### ISSUE THREAD

**Issue by mgohin** [keeweb/keeweb#975]
Hi,

I'm using a complex password to use Keepass, so when I'm on the login page of Keeweb I'd like my Lastpass extension to fill the password field, but it can do it because the password field seems to missing some requirements like the html `name` property.

Could you add it ? Or I'm I missing something?

**Comment by antelle** [comment]
I guess, it won’t work, but we can try adding a name

**Comment by antelle** [comment]
Deployed to [beta.keeweb.info](https://beta.keeweb.info), will be available in the next release.
