### ISSUE TITLE
Please create a way of retrieving password.

### ISSUE THREAD

**Issue by himanshuc3** [keeweb/keeweb#980]
I just don't remember my master password and all of my important passwords are stored in it. I forgot to keep a key file and I know that is damn careless. But I really need to see account Ids and passwords.

**Comment by Eraac** [comment]
Sorry, but it's not how this works ... master password aren't used for ensure who access, but it's use for decrypt .kdbx file ... without the master password no way to decrypt your file

And no way to retrieve master password, because is "physical" not store

**Comment by antelle** [comment]
@Eraac, thanks, that's exactly how it works.
If you could retrieve the password, someone else would do that as well.
