### ISSUE TITLE
Reseting the application - removing the manifest cache? 

### ISSUE THREAD

**Issue by aaronburt** [keeweb/keeweb#981]
I want to know how to fully clear the cache and reset the application to when i first installed it. I have attempted to open dev tools and clear the cache from the application menu to no avail. Any ideas?

**Comment by antelle** [comment]
Hi! It's here:
<img width="459" alt="image" src="https://user-images.githubusercontent.com/633557/44483892-94dc7000-a64c-11e8-8d9d-7571fbbf5b52.png">
<img width="329" alt="image" src="https://user-images.githubusercontent.com/633557/44483917-a32a8c00-a64c-11e8-839f-8f9a8a5291dc.png">

**Comment by antelle** [comment]
Additionally, if you would like to remove app settings, clear the localStorage as well.
