### ISSUE TITLE
[ Question ] clarification on sync via Dropbox

### ISSUE THREAD

**Issue by nopivnick** [keeweb/keeweb#982]
am I correct in understanding that KeeWeb's bi-directional, entry-level merge / sync as discussed variously in #70, #171, #384, #387, #726, and #887 happens 'behind the scenes' by making a temporary working copy of some kind when opening a `.kdbx` in the Dropbox directory on the file system?

that is to say, while KeeWeb incorporates KeePass.exe's [sync algorithm](https://keepass.info/help/v2/sync.html), it's not necessary to setup a local file outside of the Dropbox directory and a master file inside of the Dropbox directory as described [here](https://keepass.info/help/kb/trigger_examples.html#dbsync) (triggers notwithstanding)?

**Comment by antelle** [comment]
It doesn't make a temporary copy, instead it merges changes in memory and then writes a saved version back.
Right, this setup is not required, everything should work when the file is in Dropbox.
(if you're going to use sync actively, I would recommend to enable backups, just in case it goes wrong)
