### ISSUE TITLE
Better to remove obsolete drag-and-drop hack for Vivaldi?

### ISSUE THREAD

**Issue by Coises** [keeweb/keeweb#983]
I worked out a commit to enable dragging field labels (feature request #970).

In testing that, I found the immediate flashing of the “Drop files here” message while dragging out of the details panel annoying. I realized that in many places KeeWeb indicates that it is possible to drop something without first checking what is being dragged. I came up with a commit to show the “drop files here” message only when dragging a file, and another to make sure that throughout KeeWeb, we only indicate that something can be dropped when the type of thing being dragged can, in fact, be dropped there. At least on Windows, this would be considered less confusing and better-behaved.

In the preparing latter commit, I came across the code to work around a Vivaldi bug — Issue #432, resolved by <https://github.com/keeweb/keeweb/commit/60e59da94d392545ed635af63b88f997f39df712>.

I did some testing; the Vivaldi bug was fixed over a year ago. Using installers from https://vivaldi.com/download/archive/ I verified that on Windows 7, with the “Vivaldi hack” disabled, dragging and dropping folders and entries in KeeWeb fails in [1.6.689.40](https://downloads.vivaldi.com/stable/Vivaldi.1.6.689.40.x64.exe) (2016-12-19) and works in [1.7.735.46](https://downloads.vivaldi.com/stable/Vivaldi.1.7.735.46.x64.exe) (2017-02-08). [Cannot Drag and Drop Anything!](https://forum.vivaldi.net/topic/13411/cannot-drag-and-drop-anything/) documents the resolution of the problem around the same time in Linux.

Antelle, my question is, since the bug has been fixed in Vivaldi for over a year, and the work-around in KeeWeb is, as you described it in #432, “a dirty hack”...

When I put this all together to make a pull request, which would you prefer that I do?

1. Preserve the Vivaldi hack (writing the new code as if the hack were still needed)?

2. Revert the 60e59da commit first, then make clean commits for the changes?

3. Remove the hack as part of the commit that tightens up drag-and-drop behavior, without a separate revert?

These are all pretty small and simple changes; I just don’t know if you have a preference as to how things are done.

**Comment by antelle** [comment]
Thanks for the detailed description!
Reverted it, to keep it simple for both of us.
