### ISSUE TITLE
Moved group sometimes appears one position too low

### ISSUE THREAD

**Issue by Coises** [keeweb/keeweb#984]
Under some conditions, dragging a group to reorder the groups list results in the group appearing one position lower than the position to which it was dragged. This happens in the 1.6.3 release both on Windows desktop and in Firefox browser.

Steps to reproduce:

1. Open the Demo database.
2. Move the eMail group from inside Internet to Demo.
3. Move the Forums group from inside Sites to Demo.

The last three items under Demo are now Finance, eMail and Forums.

4. Move Finance between eMail and Forums.

Finance now appears after Forums instead of before it.

I haven’t yet pinned down exactly when this happens; every case I have seen occurs when there are nested groups present, and the moved group always appears one position lower than expected.

I'll try to find the cause; at this point, I’m just documenting that it exists in the 1.6.3 release so it’s not mistaken for something introduced in the Develop branch.

**Comment by antelle** [comment]
Thanks for the detailed steps, fixed (this happened when you move a group below itself).
