### ISSUE TITLE
Feature request: Configurable global hotkeys

### ISSUE THREAD

**Issue by Coises** [keeweb/keeweb#986]
I started thinking about this in connection with issues [#943 Shortcuts while app is in background copy wrong site info](https://github.com/keeweb/keeweb/issues/943) and [#963 Feature Request: Add a keyboard shortcut to Copy OTP in background](https://github.com/keeweb/keeweb/issues/963).

It seems a bit inconsiderate for a desktop application to define global hot keys without user choice. In effect, we’re expecting other applications to stay out of our way while providing no corresponding mechanism to get us out of their way. So, just on general principles, I think users should have control of what key combinations are to be registered as global hot keys.

While there probably is good reason to think a one-time password is a special case, #963 still makes me think that it’s hard to predict what any given user might find useful to access from a global hot key. If we let users configure hot keys, we don’t need to guess.

In #943 the problem is that we have hot keys that copy the desired fields, but they don’t perform an entry match first. In a comment to that issue, I gave an example in which changing this behavior would disrupt a plausible workflow that does work now.

So, what I’m suggesting is that we make the global hot keys configurable, shown as a table to which the user can add as many rows as desired. The columns in that table would be:

* Enabled -- a checkbox to enable or disable the row

* Keys -- any combination of keys that’s valid on the relevant platform for a system-wide hot key definition

* Entry selection:
     * `match`: select the unique matching entry if one exists; otherwise show the selection dialog
     * `select`: always show the selection dialog
     * `active`: always use the last active entry (the one that would be showing in the details view if KeeWeb were brought to the foreground)

* Action:
     * `type` the configured text
     * `copy` the configured text to the clipboard
     * `show` KeeWeb, displaying the matching, selected or active entry (in this case, Text can’t be specified)

* Text -- any specification that can be configured for auto-type; empty to use the entry’s auto-type definition
     
The default entries on Windows, matching what we have now, would be:

```
Enabled  Shift+Alt+B  active  copy  {USERNAME}
Enabled  Shift+Alt+C  active  copy  {PASSWORD}
Enabled  Shift+Alt+T  match   type
Enabled  Shift+Alt+U  active  copy  {URL}
```

A subtle point is that matching/selecting should be augmented by considering only entries for which at least one of the fields specified in the Text is not empty. For example:

```
Enabled  Shift+Alt+A  select  type  {S:Account Number}
```

should only show entries which have an Account Number field.

Then #943 could be resolved by selecting `match` instead of `active` (and maybe `type` instead of `copy`) in the first two rows of the default table; #963 could be resolved by adding:

```
Enabled  Shift+Alt+O  match   type  {TOTP}
```

and [#944 Feature request: shortcut to bring up KeeWeb from background](https://github.com/keeweb/keeweb/issues/944) could be resolved by adding:

```
Enabled  Shift+Alt+K  active  show
```

**Comment by antelle** [comment]
I don't think we should display this kind of complicated control to edit shortcuts. What could be done, is a list of hotkeys with a possibility to set it to a custom one or remove it:
 
<img width="234" alt="hotkeys" src="https://user-images.githubusercontent.com/633557/44626214-fcc6db00-a918-11e8-9671-1cd8ccad5123.png">

**Comment by antelle** [comment]
Let's close this one. We should keep hotkeys as simple default/nothing/my_custom_hotkey, without a possibility to redefine what happens when you click it.
