### ISSUE TITLE
file isn't saved to webdav?

### ISSUE THREAD

**Issue by pwFoo** [keeweb/keeweb#987]
Hi @antelle 
looks like file isn't written to webdav directory or an unmodified file is written?

webdav log says all OK.
```
"PUT /file.kdbx HTTP/1.1" 200 4798
```

But file is unchanged in directory
```
4.7K Jun  2 10:36 file.kdbx
```
Last changed should be today!

Looks like a keeweb bug...?

**Comment by pwFoo** [comment]
Any idea why it isn't saved with PUT 200 status code?

subject changed after some more debugging.

**Comment by antelle** [comment]
Please reopen with more info if it repeats.
What can be helpful:

- logs from keeweb with logs from the webserver
- sequence of your actions
- try to test a simple case: open a file, modify, check what happens
- logs for this

**Comment by pwFoo** [comment]
Domain and file name changed.
Why the old file is puted to the remote storage? Changed and saved just before save it to webdav from keeweb app.
```
2018-08-26T11:35:44.548Z [storage-webdav] Save:puted https://webdav/file.kdbx Sat, 02 Jun 2018 10:36:26 GMT 142ms
```

Should be saved to local storage first?
```
2018-08-26T11:35:44.370Z [sync:file] Saved to cache, saving to storage
```

Tested with mobile chrome for Android, desktop keeweb app and desktop chrome.

**Comment by antelle** [comment]
> Domain and file name changed.

Context please. I don't understand what you mean.
Let's check the full log when you open a file, change something and save it.

**Comment by pwFoo** [comment]
Hi @antelle,

I fixed it by playing with webdav parameters, but don't understand the error message.

Why it said file is unchanged... But after do same changes it works now. So http code 200 with local logged "file unchanged" and a changed date in June it's confusing...

But... Keeweb should work fine, it was a problem with webdav because I fixed it there...

Thanks
