### ISSUE TITLE
Getting a 401 when trying to open a keepass file from nextcloud though webdav

### ISSUE THREAD

**Issue by bearmoo-repo** [keeweb/keeweb#991]
Thanks for taking the time to contribute!

Please, read https://github.com/keeweb/keeweb/wiki/FAQ before submitting a new issue and fill in the following (if applicable):

- what were your actions?
goto https://example.com/test_keeweb
select webdav
enter the uri address for keepass db
enter username
enter password
click ok
- what was wrong?
I'm getting a 401 when trying to open a keepass file from Nextcloud though webdav
- app version
latest release
- your user-agent (from Settings/Help section)
"Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:61.0) Gecko/20100101 Firefox/61.0"
- does it happen on Demo or New database?
Happens in an existing database.

- please, open dev tools in your browser and attach output log from Console tab 
    (if you are using desktop app, devtools can be opened from Settings/General/Advanced)
Document was loaded from Application Cache with manifest https://example.com/keeweb/manifest.appcache
(index):1 Application Cache Checking event
(index):1 2018-08-29T03:58:07.476Z [app] Loading config from config.json
(index):1 2018-08-29T03:58:07.480Z [app] Loaded app config from config.json 3ms
(index):1 2018-08-29T03:58:07.535Z [app] Started in 254ms ¯\_(ツ)_/¯
(index):1 Application Cache NoUpdate event
(index):1 2018-08-29T03:58:25.922Z [storage-webdav] Stat https://example.com/remote.php/webdav/example_keepass.kdbx
(index):1 HEAD https://example.com/remote.php/webdav/example_keepass.kdbx 401 (Unauthorized)
_request @ (index):1
stat @ (index):1
applyConfig @ (index):1
_ @ (index):1
m @ (index):1
f @ (index):1
u.trigger @ (index):1
apply @ (index):1
keyup @ (index):1
dispatch @ (index):1
q.handle @ (index):1
(index):1 2018-08-29T03:58:26.196Z [storage-webdav] Stat error https://example.com/remote.php/webdav/example_keepass.kdbx 401 273ms

Here is the nextcloud error I'm getting as well:
Sabre\DAV\Exception\NotAuthenticated: CSRF check not passed.

  | Sabre\DAV\Exception\NotAuthenticated: CSRF check not passed./var/www/html/nextcloud/apps/dav/lib/Connector/Sabre/Auth.php - line 155:  OCA\DAV\Connector\Sabre\Auth->auth(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))/var/www/html/nextcloud/3rdparty/sabre/dav/lib/DAV/Auth/Plugin.php - line 201:  OCA\DAV\Connector\Sabre\Auth->check(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))/var/www/html/nextcloud/3rdparty/sabre/dav/lib/DAV/Auth/Plugin.php - line 150:  Sabre\DAV\Auth\Plugin->check(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))[internal function] Sabre\DAV\Auth\Plugin->beforeMethod(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))/var/www/html/nextcloud/3rdparty/sabre/event/lib/EventEmitterTrait.php - line 105:  call_user_func_array(Array, Array)/var/www/html/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 466:  Sabre\Event\EventEmitter->emit('beforeMethod', Array)/var/www/html/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 254:  Sabre\DAV\Server->invokeMethod(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))/var/www/html/nextcloud/apps/dav/appinfo/v1/webdav.php - line 80:  Sabre\DAV\Server->exec()/var/www/html/nextcloud/remote.php - line 164:  require_once('/var/www/html/n...'){main}
-- | --

**Comment by antelle** [comment]
Hi! This must be fixed on the WebDav server rejecting the request.

**Comment by subdavis** [comment]
> This must be fixed on the WebDav server rejecting the request.

@antelle That's not completely correct.

I was able to get this to work with [subdavis/Tusk](https://github.com/subdavis/Tusk) by hacking perry-mitchell/webdav-client a bit.  Thanks for that library, @perry-mitchell.

Fetch is a double-edged sword, evidently, and my old fork of that repo is the only thing I've found that works with nextcloud.

[Here are the changes I made](https://github.com/subdavis/webdav-client/commit/4077f156bac6fdf26cc9603574efde85dea499bf).  Keep in mind this is from an old version (1.6ish) of webdav-client.

See how I make the requests [here](https://github.com/subdavis/Tusk/blob/develop/services/webdavFileManager.js#L216)

Essentially, you need to send all requests authenticated with Basic auth and never send any cookies that nextcloud tries to set.

**Comment by antelle** [comment]
So, what do we need to change to make it work?

> never send any cookies that nextcloud tries to set

not possible on web

**Comment by antelle** [comment]
It's possible to disable it, but it will also disable basic auth, if I'm not mistaken: https://developer.mozilla.org/en-US/docs/Web/API/Request/credentials

**Comment by antelle** [comment]
But we can try to set `credentials: omit` and see if it works, @subdavis, do you have a possibility to check this if I build it to beta?

**Comment by subdavis** [comment]
`omit` will not disable basic auth if you set those headers using https://developer.mozilla.org/en-US/docs/Web/API/Request/headers

If you build it to beta, I can figure out how to build the client.  I've done it before, but it's been a while.  Won't be able to do it until later tonight.

**Comment by antelle** [comment]
I took another look, it looks like ignoring cookies won't help in our case, because the first request fails. Do you know on which request these cookies are set?

**Comment by subdavis** [comment]
You're sending an `OPTIONS` request, which is triggered by some other method, right?

You should be sending `PROPFIND`, which doesn't trigger propfind.

https://github.com/subdavis/webdav-client/blob/fix/fetch/source/interface/directoryContents.js#L21

**Comment by antelle** [comment]
I see, probably we need an options for that, because it will break plain http implementation, when there's no propfind

**Comment by subdavis** [comment]
Sorry, I don't know what possessed me to say that.

You need to avoid sending an OPTIONS request by using fetch without `Content-Type` set.  See how to avoid triggering preflight: https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS#Simple_requests

PROPFIND isn't relevant to the problem.  My mistake.

**Comment by antelle** [comment]
But you can't avoid it, it's by design.

**Comment by subdavis** [comment]
*Sigh*

I never remember that browser extensions are able to disregard CORS headers (or lack thereof).

:+1: There's nothing you can do from the keeweb side, just like you said.

**Comment by perry-mitchell** [comment]
This is a pain-point for many.. I've definitely had enough CORS issues on ownCloud/Nextcloud to last me a lifetime. We're considering forcefully bypassing CORS in the browser extension of [Buttercup](https://github.com/buttercup) (only for vault requests) so that we can do away with the issue. Unless you have complete control over the network aspect of your platform (browser extensions, nodejs, mobile etc.) you can't really get past the brokenness of these services.
