### ISSUE TITLE
Auto-type adds trailing 0 to username

### ISSUE THREAD

**Issue by HarlemSquirrel** [keeweb/keeweb#996]
Thanks for taking the time to contribute!

Please, read https://github.com/keeweb/keeweb/wiki/FAQ before submitting a new issue and fill in the following (if applicable):

- what were your actions?
Perform auto-type using [Ctrl]+[T] or [Shift]+[Alt]+[T]
- what was wrong?
Username includes trailing `0`
- app version
v1.6.3
- your user-agent (from Settings/Help section)
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) KeeWeb/1.6.3 Chrome/58.0.3029.110
- does it happen on Demo or New database?
Have not tested
- if you are using a test db without your personal data, please attach it
N/A
- please, open dev tools in your browser and attach output log from Console tab 
    (if you are using desktop app, devtools can be opened from Settings/General/Advanced)

```
2018-09-07T12:37:12.775Z [auto-type] Auto type event null
index.html:1 2018-09-07T12:37:12.778Z [auto-type] Get window title
index.html:1 2018-09-07T12:37:12.796Z [launcher] spawn xdotool: 0, 17ms
Error: Sign in - chase.com - Mozilla Firefox
index.html:1 2018-09-07T12:37:12.796Z [auto-type] Window title Error: Sign in - chase.com - Mozilla Firefox undefined
index.html:1 2018-09-07T12:37:12.811Z [auto-type] Hide window
index.html:1 2018-09-07T12:37:12.812Z [auto-type] Start {DELAY 500}{USERNAME}{TAB}{PASSWORD}{ENTER}
index.html:1 2018-09-07T12:37:12.813Z [auto-type] Parsed [op:DELAY,op:USERNAME,op:TAB,op:PASSWORD,op:ENTER]
index.html:1 2018-09-07T12:37:12.814Z [auto-type] Resolved [cmd:wait,*************,key:tab,[*,*,*,*,*,*,*,*,*,*],key:enter]
index.html:1 2018-09-07T12:37:13.549Z [launcher] spawn xdotool: 0, 734ms
index.html:1 2018-09-07T12:37:13.631Z [launcher] spawn xdotool: 0, 81ms
index.html:1 2018-09-07T12:37:13.701Z [launcher] spawn xdotool: 0, 69ms
index.html:1 2018-09-07T12:37:13.769Z [launcher] spawn xdotool: 0, 68ms
index.html:1 2018-09-07T12:37:13.838Z [launcher] spawn xdotool: 0, 69ms
index.html:1 2018-09-07T12:37:13.908Z [launcher] spawn xdotool: 0, 70ms
index.html:1 2018-09-07T12:37:13.979Z [launcher] spawn xdotool: 0, 70ms
index.html:1 2018-09-07T12:37:14.049Z [launcher] spawn xdotool: 0, 69ms
index.html:1 2018-09-07T12:37:14.118Z [launcher] spawn xdotool: 0, 69ms
index.html:1 2018-09-07T12:37:14.189Z [launcher] spawn xdotool: 0, 70ms
index.html:1 2018-09-07T12:37:14.259Z [launcher] spawn xdotool: 0, 70ms
index.html:1 2018-09-07T12:37:14.281Z [launcher] spawn xdotool: 0, 21ms
index.html:1 2018-09-07T12:37:14.281Z [auto-type] Complete 1469ms
```

**Comment by HarlemSquirrel** [comment]
Doing some more testing, this seems to be isolated to one folder of entries.

**Comment by HarlemSquirrel** [comment]
Doing a bit more testing, this seems to be happening based on the length of the username. I only seem to get an extra character when the username is 1,2,3,8,9,12, or 13 characters long. I increased the length of a username by one using sequential numbers and letters and performed auto-type:

```
1P	password
12E	password
123E	password
1234	password
12345	password
123456	password
1234567	password
12345678P	password
123456789P	password
1234567890	password
1234567890A	password
1234567890AB0	password
1234567890ABC0	password
1234567890ABCD	password
1234567890ABCDE	password
1234567890ABCDEF	password
1234567890ABCDEFG	password
1234567890ABCDEFGH	password
1234567890ABCDEFGHI	password
1234567890ABCDEFGHIJ	password
```

**Comment by antelle** [comment]
Hi! This seems to be #425

**Comment by dploeger** [comment]
@HarlemSquirrel Could you please take a look at #425 and see, if that issue matches yours? If so, we could close this as duplicate.

**Comment by HarlemSquirrel** [comment]
Yeah it appears to be the same.
