### ISSUE TITLE
Cannot Sync KeeWeb file With Google Drive

### ISSUE THREAD

**Issue by AhmedAlZabidi** [keeweb/keeweb#997]
![keeweb error](https://user-images.githubusercontent.com/19707982/45283344-451ff480-b4e6-11e8-9479-96eb15d0090a.PNG)

When I press Save it returns the attached popup message, I have applied all three steps but still I get the same error.

I uninstalled the older version and installed new version still not solved.

I want to sync my KeeWeb file with Google Drive.

KeeWeb v1.6.3 (cded8a4, 2017-12-11)
Environment: electron v1.7.9
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) KeeWeb/1.6.3 Chrome/58.0.3029.110 Electron/1.7.9 Safari/537.36

**Comment by Sustenance** [comment]
This may be limited to Windows. I got the same message on Windows 10, but on my MacBook, also running KeeWeb v1.6.3, I did not get this message.

**Comment by antelle** [comment]
this is #810
