### ISSUE TITLE
Application rendering incorrectly

### ISSUE THREAD

**Issue by Gabb1995** [keeweb/keeweb#998]
Application is rendering incorrectly as seen in the screenshot.
![screenshot from 2018-09-13 08 54 16](https://user-images.githubusercontent.com/20728259/45471858-b5bb5100-b732-11e8-9379-ddd4e463fad1.png)

Happens with all themes, I'm using Ubuntu 18.04. It is clearly seen in App twitter part.

KeeWeb v1.6.3 (cded8a4, 2017-12-11)
Environment: electron v1.7.9
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) KeeWeb/1.6.3 Chrome/58.0.3029.110 Electron/1.7.9 Safari/537.36

**Comment by antelle** [comment]
Duplicates #900
